package tr.bible;

public class trbible47 {

public trbible47() {

putmapbible47();

}

private void putmapbible47() {

trsuperobject.biblemap.put("b47_1_1", new trsuperobject(47,1,1,"Tanrının isteğiyle Mesih İsanın elçisi atanan ben Pavlus ve kardeşimiz Timoteostan Ahayanın her yanındaki bütün kutsallara ve Tanrının Korintteki kilisesine selam!"));
trsuperobject.biblemap.put("b47_1_2", new trsuperobject(47,1,2,"Babamız Tanrıdan ve Rab İsa Mesihten sizlere lütuf ve esenlik olsun."));
trsuperobject.biblemap.put("b47_1_3", new trsuperobject(47,1,3,"Her türlü tesellinin kaynağı olan Tanrıya, merhametli Babaya, Rabbimiz İsa Mesihin Tanrısı ve Babasına övgüler olsun!"));
trsuperobject.biblemap.put("b47_1_4", new trsuperobject(47,1,4,"Kendisinden aldığımız teselliyle her türlü sıkıntıda olanları teselli edebilmemiz için bizi bütün sıkıntılarımızda teselli ediyor."));
trsuperobject.biblemap.put("b47_1_5", new trsuperobject(47,1,5,"Çünkü Mesihin acılarını nasıl büyük ölçüde çekiyorsak, Mesih sayesinde büyük teselli de buluyoruz."));
trsuperobject.biblemap.put("b47_1_6", new trsuperobject(47,1,6,"Sıkıntı çekiyorsak, bu sizin teselliniz ve kurtuluşunuz içindir. Teselli buluyorsak bu, bizim çektiğimiz acıların aynısına dayanmanızda etkin olan bir teselli bulmanız içindir."));
trsuperobject.biblemap.put("b47_1_7", new trsuperobject(47,1,7,"Size ilişkin umudumuz sarsılmaz. Çünkü acılarımıza olduğu gibi, tesellimize de ortak olduğunuzu biliyoruz."));
trsuperobject.biblemap.put("b47_1_8", new trsuperobject(47,1,8,"Kardeşlerim, Asya İlinde çektiğimiz sıkıntılardan habersiz kalmanızı istemiyoruz. Dayanabileceğimizden çok ağır bir yük altındaydık. Öyle ki, yaşamaktan bile umudumuzu kesmiştik."));
trsuperobject.biblemap.put("b47_1_9", new trsuperobject(47,1,9,"Ölüme mahkûm olduğumuzu içimizde hissettik. Ama bu, kendimize değil, ölüleri dirilten Tanrıya güvenmemiz için oldu."));
trsuperobject.biblemap.put("b47_1_1-011", new trsuperobject(47,1,1-011,"Tanrı bizi böylesine büyük bir ölüm tehlikesinden kurtardı; daha da kurtaracaktır. Umudumuzu Ona bağladık. Siz de dualarınızla bize yardım ettikçe, bizi yine kurtaracaktır. Öyle ki, birçok kişinin dualarıyla bize sağlanan lütuftan ötürü birçoklarının ağzından bizim için şükranlar sunulsun."));
trsuperobject.biblemap.put("b47_1_12", new trsuperobject(47,1,12,"Dünyaya ve özellikle size, insan bilgeliğiyle değil, Tanrının lütfuyla, Tanrıdan gelen kutsallık ve içtenlikle davrandığımıza vicdanımız tanıktır. Ve biz bununla övünüyoruz."));
trsuperobject.biblemap.put("b47_1_13-14", new trsuperobject(47,1,13-14,"Okuyup anlayabileceğinizden başka bir şey yazmıyoruz. Bizi bir ölçüde anladığınız gibi, tümüyle anlayacağınızı umarım. Rabbimiz İsanın gününde bizim övüncümüz siz olacağınız gibi, sizin övüncünüz de biz olalım."));
trsuperobject.biblemap.put("b47_1_15-16", new trsuperobject(47,1,15-16,"Bu güvenle, sizleri iki kez sevindirmek için önce size uğramak, sonra Makedonyaya geçmek, Makedonyadan yine size geri gelerek tarafınızdan Yahudiyeye uğurlanmak niyetindeydim."));
trsuperobject.biblemap.put("b47_1_17", new trsuperobject(47,1,17,"Bunu isterken acaba kararsız mıydım? Ya da isteklerim benlikten mi doğuyor ki, önce ‹‹Evet, evet››, sonra ‹‹Hayır, hayır›› diyeyim?"));
trsuperobject.biblemap.put("b47_1_18", new trsuperobject(47,1,18,"Tanrının güvenilirliği hakkı için diyorum ki, size ilettiğimiz söz hem ‹‹evet›› hem ‹‹hayır›› değildir."));
trsuperobject.biblemap.put("b47_1_19", new trsuperobject(47,1,19,"Silvanus ve Timoteosla birlikte size tanıttığımız Tanrının Oğlu İsa Mesih hem ‹‹evet›› hem ‹‹hayır›› değildi. Onda yalnız ‹‹evet›› vardır."));
trsuperobject.biblemap.put("b47_1_20", new trsuperobject(47,1,20,"Çünkü Tanrının bütün vaatleri Mesihte ‹‹evet››tir. Bu nedenle Tanrının yüceliği için Mesih aracılığıyla Tanrıya ‹‹Amin›› deriz."));
trsuperobject.biblemap.put("b47_1_21", new trsuperobject(47,1,21,"Bizi sizinle birlikte Mesihte pekiştiren ve meshetmiş olan Tanrıdır."));
trsuperobject.biblemap.put("b47_1_22", new trsuperobject(47,1,22,"O bizi mühürledi, güvence olarak da yüreklerimize Kutsal Ruhu yerleştirdi."));
trsuperobject.biblemap.put("b47_1_23", new trsuperobject(47,1,23,"Tanrıyı tanık tutarım ki, Korinte dönmeyişimin nedeni sizi esirgemekti."));
trsuperobject.biblemap.put("b47_1_24", new trsuperobject(47,1,24,"İmanınıza egemen olmak istemiyoruz, sevinmeniz için sizinle birlikte çalışıyoruz. Çünkü imanda dimdik duruyorsunuz."));
trsuperobject.biblemap.put("b47_2_1", new trsuperobject(47,2,1,"Size tekrar keder dolu bir ziyaret yapmamaya karar verdim."));
trsuperobject.biblemap.put("b47_2_2", new trsuperobject(47,2,2,"Çünkü sizi kederlendirirsem, keder verdiğim sizlerden başka beni kim sevindirecek?"));
trsuperobject.biblemap.put("b47_2_3", new trsuperobject(47,2,3,"Bunu yazdım ki, geldiğimde beni sevindirmesi gerekenler beni kederlendirmesin. Sevincimin hepinizin sevinci olduğuna ilişkin hepinize güvenim var."));
trsuperobject.biblemap.put("b47_2_4", new trsuperobject(47,2,4,"Kederlenesiniz diye değil, size beslediğim derin sevgiyi anlayasınız diye büyük bir sıkıntı ve yürek acısıyla gözyaşları içinde size yazdım."));
trsuperobject.biblemap.put("b47_2_5", new trsuperobject(47,2,5,"Eğer biri bir başkasını kederlendirdiyse, beni değil -abartmadan söyleyeyim- bir dereceye kadar hepinizi kederlendirmiş olur."));
trsuperobject.biblemap.put("b47_2_6", new trsuperobject(47,2,6,"Böyle birine çoğunluğun verdiği bu ceza yeterlidir."));
trsuperobject.biblemap.put("b47_2_7", new trsuperobject(47,2,7,"Aşırı kedere boğulmasın diye o kişiyi daha fazla cezalandırmayıp bağışlamalı ve teselli etmelisiniz."));
trsuperobject.biblemap.put("b47_2_8", new trsuperobject(47,2,8,"Bunun için ona duyduğunuz sevgiyi yenilemenizi rica ederim."));
trsuperobject.biblemap.put("b47_2_9", new trsuperobject(47,2,9,"Sizi sınamak ve her durumda söz dinleyenler olup olmadığınızı anlamak için yazdım size."));
trsuperobject.biblemap.put("b47_2_10", new trsuperobject(47,2,10,"Kimi bağışlarsanız, ben de onu bağışlarım. Eğer bir şeyi bağışladımsa, bunu sizin için Mesihin önünde bağışladım."));
trsuperobject.biblemap.put("b47_2_11", new trsuperobject(47,2,11,"Öyle ki, Şeytanın oyununa gelmeyelim. Çünkü onun düzenlerini bilmez değiliz."));
trsuperobject.biblemap.put("b47_2_12-13", new trsuperobject(47,2,12-13,"Mesihin Müjdesini yaymak amacıyla Troasa geldiğimde Rabbin işi için bana bir kapı açıldığı halde, kardeşim Titusu orada bulamadığım için iç huzurum yoktu. Bu nedenle oradakilere veda ederek Makedonyaya gittim."));
trsuperobject.biblemap.put("b47_2_14", new trsuperobject(47,2,14,"Bizi her zaman Mesihin zafer alayında yürüten, Onu tanımanın güzel kokusunu aracılığımızla her yerde yayan Tanrıya şükürler olsun!"));
trsuperobject.biblemap.put("b47_2_15", new trsuperobject(47,2,15,"Çünkü biz hem kurtulanlar hem de mahvolanlar arasında Tanrı için Mesihin güzel kokusuyuz."));
trsuperobject.biblemap.put("b47_2_16", new trsuperobject(47,2,16,"Mahvolanlar için ölüme götüren ölüm kokusu, kurtulanlar içinse yaşama götüren yaşam kokusuyuz. Böylesi bir işe kim yeterlidir?"));
trsuperobject.biblemap.put("b47_2_17", new trsuperobject(47,2,17,"Birçokları gibi, Tanrı'nın sözünü ticaret aracı yapanlar değiliz. Tanrı tarafından gönderilen ve Mesih'e ait olan kişiler olarak Tanrı'nın önünde içtenlikle konuşuyoruz."));
trsuperobject.biblemap.put("b47_3_1", new trsuperobject(47,3,1,"Kendimizi yine tavsiye etmeye mi başlıyoruz? Yoksa bazıları gibi size ya da sizden tavsiye mektuplarına ihtiyacımız mı var?"));
trsuperobject.biblemap.put("b47_3_2", new trsuperobject(47,3,2,"Bütün insanlarca bilinen ve okunan, yüreklerimize yazılmış mektubumuz sizsiniz."));
trsuperobject.biblemap.put("b47_3_3", new trsuperobject(47,3,3,"Hizmetimizin sonucu olup mürekkeple değil, yaşayan Tanrının Ruhuyla, taş levhalara değil, insan yüreğinin levhalarına yazılmış Mesihin mektubu olduğunuz açıktır."));
trsuperobject.biblemap.put("b47_3_4", new trsuperobject(47,3,4,"Mesih sayesinde Tanrıya böyle bir güvenimiz vardır."));
trsuperobject.biblemap.put("b47_3_5", new trsuperobject(47,3,5,"Herhangi bir şeyi kendi başarımız olarak saymaya yeterliyiz demek istemiyorum; bizi yeterli kılan Tanrıdır."));
trsuperobject.biblemap.put("b47_3_6", new trsuperobject(47,3,6,"O bizi yazılı yasaya değil, Ruha dayalı yeni bir antlaşmanın hizmetkârları olmaya yeterli kıldı. Yazılı yasa öldürür, Ruh ise yaşatır."));
trsuperobject.biblemap.put("b47_3_7-8", new trsuperobject(47,3,7-8,"Ölümle sonuçlanan hizmet, yani taş üzerine harf harf kazılan yasa yücelik içinde geldiyse -öyle ki, İsrailoğulları geçici olan parlaklığından ötürü Musanın yüzüne bakamadılar- Ruha dayalı hizmetin yücelik içinde olacağı daha kesin değil mi?"));
trsuperobject.biblemap.put("b47_3_9", new trsuperobject(47,3,9,"İnsanı suçlu çıkaran hizmetin yüceliği varsa, aklanmayı sağlayan hizmetin yüceliği çok daha aşkındır."));
trsuperobject.biblemap.put("b47_3_10", new trsuperobject(47,3,10,"Çünkü eskiden yüceltilmiş olanın, şimdi yücelikte aşkın olana göre yüceliği yoktur."));
trsuperobject.biblemap.put("b47_3_11", new trsuperobject(47,3,11,"Geçici olan, yücelik içinde geldiyse, kalıcı olanın yüceliği çok daha büyüktür."));
trsuperobject.biblemap.put("b47_3_12", new trsuperobject(47,3,12,"Böyle bir umuda sahip olduğumuz için büyük cesaretle konuşabiliriz."));
trsuperobject.biblemap.put("b47_3_13", new trsuperobject(47,3,13,"Yüzündeki parlaklığın giderek söndüğünü İsrailoğulları görmesin diye yüzünü peçeyle örten Musa gibi değiliz."));
trsuperobject.biblemap.put("b47_3_14", new trsuperobject(47,3,14,"İsrailoğullarının zihinleri körelmişti. Bugün bile Eski Antlaşma okunurken zihinleri aynı peçeyle örtülü kalıyor. Çünkü bu peçe ancak Mesih aracılığıyla kalkar."));
trsuperobject.biblemap.put("b47_3_15", new trsuperobject(47,3,15,"Ne var ki, bugün bile Musanın yazıları okunduğunda yüreklerini bir peçe örtüyor."));
trsuperobject.biblemap.put("b47_3_16", new trsuperobject(47,3,16,"Oysa ne zaman biri Rabbe dönerse, o peçe kaldırılır."));
trsuperobject.biblemap.put("b47_3_17", new trsuperobject(47,3,17,"Rab Ruhtur, Rabbin Ruhu neredeyse orada özgürlük vardır."));
trsuperobject.biblemap.put("b47_3_18", new trsuperobject(47,3,18,"Ve biz hepimiz peçesiz yüzle Rab'bin yüceliğini görerek yücelik üstüne yücelikle O'na benzer olmak üzere değiştiriliyoruz. Bu da Ruh olan Rab sayesinde oluyor."));
trsuperobject.biblemap.put("b47_4_1", new trsuperobject(47,4,1,"Bu hizmeti Tanrının merhametiyle üstlendiğimiz için cesaretimizi yitirmeyiz."));
trsuperobject.biblemap.put("b47_4_2", new trsuperobject(47,4,2,"Utanç verici gizli yolları reddettik. Hileye başvurmayız, Tanrının sözünü de çarpıtmayız. Gerçeği ortaya koyarak kendimizi Tanrının önünde her insanın vicdanına tavsiye ederiz."));
trsuperobject.biblemap.put("b47_4_3", new trsuperobject(47,4,3,"Yaydığımız Müjde örtülüyse de, mahvolanlar için örtülüdür."));
trsuperobject.biblemap.put("b47_4_4", new trsuperobject(47,4,4,"Tanrının görünümü olan Mesihin yüceliğiyle ilgili Müjdenin ışığı imansızların üzerine doğmasın diye, bu çağın ilahı onların zihinlerini kör etmiştir."));
trsuperobject.biblemap.put("b47_4_5", new trsuperobject(47,4,5,"Biz kendimizi ilan etmiyoruz; ama Mesih İsayı Rab, kendimizi de İsa uğruna kullarınız ilan ediyoruz."));
trsuperobject.biblemap.put("b47_4_6", new trsuperobject(47,4,6,"Çünkü, ‹‹Işık karanlıktan parlayacak›› diyen Tanrı, İsa Mesihin yüzünde parlayan kendi yüceliğini tanımamızdan doğan ışığı bize vermek için yüreklerimizi aydınlattı."));
trsuperobject.biblemap.put("b47_4_7", new trsuperobject(47,4,7,"Üstün gücün bizden değil, Tanrıdan kaynaklandığı bilinsin diye bu hazineye toprak kaplar içinde sahibiz."));
trsuperobject.biblemap.put("b47_4_8", new trsuperobject(47,4,8,"Her yönden sıkıştırılmışız, ama ezilmiş değiliz. Şaşırmışız, ama çaresiz değiliz."));
trsuperobject.biblemap.put("b47_4_9", new trsuperobject(47,4,9,"Kovalanıyoruz, ama terk edilmiş değiliz. Yere yıkılmışız, ama yok olmuş değiliz."));
trsuperobject.biblemap.put("b47_4_10", new trsuperobject(47,4,10,"İsanın yaşamı bedenimizde açıkça görülsün diye İsanın ölümünü her an bedenimizde taşıyoruz."));
trsuperobject.biblemap.put("b47_4_11", new trsuperobject(47,4,11,"Çünkü İsanın yaşamı ölümlü bedenimizde açıkça görülsün diye, biz yaşayanlar İsa uğruna sürekli olarak ölüme teslim ediliyoruz."));
trsuperobject.biblemap.put("b47_4_12", new trsuperobject(47,4,12,"Böylece ölüm bizde, yaşamsa sizde etkin olmaktadır."));
trsuperobject.biblemap.put("b47_4_13", new trsuperobject(47,4,13,"‹‹İman ettim, bu nedenle konuştum›› diye yazılmıştır. Aynı iman ruhuna sahip olarak biz de iman ediyor ve bu nedenle konuşuyoruz."));
trsuperobject.biblemap.put("b47_4_14", new trsuperobject(47,4,14,"Çünkü Rab İsayı dirilten Tanrının, bizi de İsayla diriltip sizinle birlikte kendi önüne çıkaracağını biliyoruz."));
trsuperobject.biblemap.put("b47_4_15", new trsuperobject(47,4,15,"Bütün bunlar sizin yararınızadır. Böylelikle Tanrının lütfu çoğalıp daha çok insana ulaştıkça, Tanrının yüceliği için şükran da artsın."));
trsuperobject.biblemap.put("b47_4_16", new trsuperobject(47,4,16,"Bu nedenle cesaretimizi yitirmeyiz. Her ne kadar dış varlığımız harap oluyorsa da, iç varlığımız günden güne yenileniyor."));
trsuperobject.biblemap.put("b47_4_17", new trsuperobject(47,4,17,"Çünkü geçici, hafif sıkıntılarımız bize, ağırlıkta hiçbir şeyle karşılaştırılamayacak kadar büyük, sonsuz bir yücelik kazandırmaktadır."));
trsuperobject.biblemap.put("b47_4_18", new trsuperobject(47,4,18,"Gözlerimizi görünen şeylere değil, görünmeyenlere çeviriyoruz. Çünkü görünenler geçicidir, görünmeyenlerse sonsuza dek kalıcıdır."));
trsuperobject.biblemap.put("b47_5_1", new trsuperobject(47,5,1,"Biliyoruz ki, barındığımız bu dünyasal çadır yıkılırsa, göklerde Tanrının bize sağladığı bir konut -elle yapılmamış, sonsuza dek kalacak bir evimiz- vardır."));
trsuperobject.biblemap.put("b47_5_2", new trsuperobject(47,5,2,"Şimdiyse göksel evimizi giyinmeyi özleyerek inliyoruz."));
trsuperobject.biblemap.put("b47_5_3", new trsuperobject(47,5,3,"Onu giyinirsek çıplak kalmayız."));
trsuperobject.biblemap.put("b47_5_4", new trsuperobject(47,5,4,"Dünyasal çadırda yaşayan bizler ağır bir yük altında inliyoruz. Asıl istediğimiz soyunmak değil, giyinmektir. Öyle ki, ölümlü olan, yaşam tarafından yutulsun."));
trsuperobject.biblemap.put("b47_5_5", new trsuperobject(47,5,5,"Bizleri tam bu amaç için hazırlamış ve güvence olarak bize Ruhu vermiş olan Tanrıdır."));
trsuperobject.biblemap.put("b47_5_6", new trsuperobject(47,5,6,"Bu nedenle her zaman cesaretimiz vardır. Şunu biliyoruz ki, bu bedende yaşadıkça Rabden uzaktayız."));
trsuperobject.biblemap.put("b47_5_7", new trsuperobject(47,5,7,"Gözle görülene değil, imana dayanarak yaşarız."));
trsuperobject.biblemap.put("b47_5_8", new trsuperobject(47,5,8,"Cesaretimiz vardır diyorum ve bedenden uzakta, Rabbin yanında olmayı yeğleriz."));
trsuperobject.biblemap.put("b47_5_9", new trsuperobject(47,5,9,"Bunun için, ister bedende yaşayalım ister bedenden uzak olalım, amacımız Rabbi hoşnut etmektir."));
trsuperobject.biblemap.put("b47_5_10", new trsuperobject(47,5,10,"Çünkü bedende yaşarken gerek iyi gerek kötü, yaptıklarımızın karşılığını almak için hepimiz Mesihin yargı kürsüsü önüne çıkmak zorundayız."));
trsuperobject.biblemap.put("b47_5_11", new trsuperobject(47,5,11,"Rabden korkmanın ne demek olduğunu bildiğimizden insanları ikna etmeye çalışıyoruz. Ne olduğumuzu Tanrı biliyor; umarım siz de vicdanınızda biliyorsunuz."));
trsuperobject.biblemap.put("b47_5_12", new trsuperobject(47,5,12,"Kendimizi yine size tavsiye etmeye çalışmıyoruz. Ama yürekle değil, dış görünüşle övünenleri yanıtlayabilmeniz için bizimle övünmenize fırsat veriyoruz."));
trsuperobject.biblemap.put("b47_5_13", new trsuperobject(47,5,13,"Eğer kendimizde değilsek, bu Tanrı içindir. Aklımız başımızdaysa, bu sizin içindir."));
trsuperobject.biblemap.put("b47_5_14", new trsuperobject(47,5,14,"Bizi zorlayan, Mesihin sevgisidir. Yargımız şu: Biri herkes için öldü; öyleyse hepsi öldü."));
trsuperobject.biblemap.put("b47_5_15", new trsuperobject(47,5,15,"Evet, Mesih herkes için öldü. Öyle ki, yaşayanlar artık kendileri için değil, kendileri uğruna ölüp dirilen Mesih için yaşasınlar."));
trsuperobject.biblemap.put("b47_5_16", new trsuperobject(47,5,16,"Bu nedenle, biz artık kimseyi insan ölçülerine göre tanımayız. Mesihi bu ölçülere göre tanıdıksa da, artık öyle tanımıyoruz."));
trsuperobject.biblemap.put("b47_5_17", new trsuperobject(47,5,17,"Bir kimse Mesihteyse, yeni yaratıktır; eski şeyler geçmiş, her şey yeni olmuştur."));
trsuperobject.biblemap.put("b47_5_18", new trsuperobject(47,5,18,"Bunların hepsi Tanrıdandır. Tanrı, Mesih aracılığıyla bizi kendisiyle barıştırdı ve bize barıştırma görevini verdi."));
trsuperobject.biblemap.put("b47_5_19", new trsuperobject(47,5,19,"Şöyle ki Tanrı, insanların suçlarını saymayarak dünyayı Mesihte kendisiyle barıştırdı ve barıştırma sözünü bize emanet etti."));
trsuperobject.biblemap.put("b47_5_20", new trsuperobject(47,5,20,"Böylece, Tanrı aracılığımızla çağrıda bulunuyormuş gibi Mesihin adına elçilik ediyor, Onun adına yalvarıyoruz: Tanrıyla barışın."));
trsuperobject.biblemap.put("b47_5_21", new trsuperobject(47,5,21,"Tanrı, günahı bilmeyen Mesih'i bizim için günah sunusu yaptı. Öyle ki, Mesih sayesinde Tanrı'nın doğruluğu olalım."));
trsuperobject.biblemap.put("b47_6_1", new trsuperobject(47,6,1,"Tanrıyla birlikte çalışan bizler, Onun lütfunu boş yere kabul etmemenizi ayrıca rica ediyoruz."));
trsuperobject.biblemap.put("b47_6_2", new trsuperobject(47,6,2,"Çünkü Tanrı diyor ki,  ‹‹Uygun zamanda seni duydum,  Kurtuluş günü sana yardım ettim.››"));
trsuperobject.biblemap.put("b47_6_3", new trsuperobject(47,6,3,"Hizmetimizin kötülenmemesi için hiçbir konuda hiç kimsenin sürçmesine neden olmadık."));
trsuperobject.biblemap.put("b47_6_4-8", new trsuperobject(47,6,4-8,"Tersine Tanrının hizmetkârları olarak olağanüstü dayanmada, sıkıntı, güçlük ve elemlerde, dayak, hapis, karışıklık, emek, uykusuzluk ve açlıkta; pak yaşayışta, bilgi, sabır, iyilik, Kutsal Ruh ve içten sevgide; gerçeğin ilanında ve Tanrının gücünde; sağ ve sol ellerimizde doğruluğun silahlarıyla, yücelikte ve onursuzlukta, iyi ünde ve kötü ünde, kendimizi her durumda örnek gösteriyoruz. Aldatanlar sayılıyorsak da dürüst kişileriz."));
trsuperobject.biblemap.put("b47_6_9", new trsuperobject(47,6,9,"Tanınmıyor gibiyiz, ama iyi tanınıyoruz. Ölümün ağzındayız, ama işte yaşıyoruz. Dövülüyorsak bile öldürülmüş değiliz."));
trsuperobject.biblemap.put("b47_6_10", new trsuperobject(47,6,10,"Kederliyiz ama her zaman seviniyoruz. Yoksuluz ama birçoklarını zengin ediyoruz. Hiçbir şeyimiz yok ama her şeye sahibiz."));
trsuperobject.biblemap.put("b47_6_11", new trsuperobject(47,6,11,"Ey Korintliler, sizinle açıkça konuştuk, size yüreğimizi açtık."));
trsuperobject.biblemap.put("b47_6_12", new trsuperobject(47,6,12,"Sizden sevgimizi esirgemedik, ama siz bizden sevginizi esirgediniz."));
trsuperobject.biblemap.put("b47_6_13", new trsuperobject(47,6,13,"Bize aynı karşılığı verebilmek için -çocuklarıma söyler gibi söylüyorum- siz de yüreğinizi açın."));
trsuperobject.biblemap.put("b47_6_14", new trsuperobject(47,6,14,"İmansızlarla aynı boyunduruğa girmeyin. Çünkü doğrulukla fesadın ne ortaklığı, ışıkla karanlığın ne paydaşlığı olabilir?"));
trsuperobject.biblemap.put("b47_6_15", new trsuperobject(47,6,15,"Mesihle Beliyal uyum içinde olabilir mi? İman edenle iman etmeyenin ortak yanı olabilir mi?"));
trsuperobject.biblemap.put("b47_6_16", new trsuperobject(47,6,16,"Tanrının tapınağıyla putlar uyuşabilir mi? Çünkü biz yaşayan Tanrının tapınağıyız. Nitekim Tanrı şöyle diyor:  ‹‹Aralarında yaşayacak,  Aralarında yürüyeceğim.  Onların Tanrısı olacağım,  Onlar da benim halkım olacak.››"));
trsuperobject.biblemap.put("b47_6_17", new trsuperobject(47,6,17,"Bu nedenle, ‹‹İmansızların arasından çıkıp ayrılın›› diyor Rab.  ‹‹Murdara dokunmayın,  Ben de sizi kabul edeceğim.››"));
trsuperobject.biblemap.put("b47_6_18", new trsuperobject(47,6,18,"Her Şeye Gücü Yeten Rab diyor ki,  ‹‹Size Baba olacağım,  Siz de oğullarım, kızlarım olacaksınız.››"));
trsuperobject.biblemap.put("b47_7_1", new trsuperobject(47,7,1,"Sevgili kardeşler, bu vaatlere sahip olduğumuza göre, bedeni ve ruhu lekeleyen her şeyden kendimizi arındıralım; Tanrı korkusuyla kutsallıkta yetkinleşelim."));
trsuperobject.biblemap.put("b47_7_2", new trsuperobject(47,7,2,"Yüreklerinizde bize yer verin. Kimseye haksızlık etmedik, kimseyi yoldan saptırmadık, kimseyi sömürmedik."));
trsuperobject.biblemap.put("b47_7_3", new trsuperobject(47,7,3,"Bunu sizi yargılamak için söylemiyorum. Daha önce de söylediğim gibi, yüreğimizde öyle bir yeriniz var ki, sizinle ölürüz de yaşarız da."));
trsuperobject.biblemap.put("b47_7_4", new trsuperobject(47,7,4,"Size çok güveniyor, sizinle çok övünüyorum. Teselliyle doluyum. Bütün sıkıntılar arasında sevincim sonsuzdur."));
trsuperobject.biblemap.put("b47_7_5", new trsuperobject(47,7,5,"Makedonyaya geldiğimizde de hiç rahat yüzü görmedik. Her bakımdan sıkıntı çekiyorduk. Dışarıda kavgalar, yüreğimizde korkular vardı."));
trsuperobject.biblemap.put("b47_7_6-7", new trsuperobject(47,7,6-7,"Ama yüreği ezik olanları teselli eden Tanrı, Titusun yanımıza gelişiyle -yalnız gelişiyle değil, sizden aldığı teselliyle de- bizi teselli etti. Titus beni özlediğinizi, benim için üzülüp gayret ettiğinizi bize anlatınca sevincim bir kat daha arttı."));
trsuperobject.biblemap.put("b47_7_8-9", new trsuperobject(47,7,8-9,"Mektubumla size acı verdiysem bile pişman değilim. Aslında pişman olmuştum -kısa bir süre için de olsa, o mektubun size acı verdiğini görüyorum- ama şimdi seviniyorum; acı duymanıza değil, bu acınızın sizi tövbeye yöneltmesine seviniyorum. Tanrının isteğine uygun olarak acı çektiniz. Böylece hiçbir şekilde bizden zarar görmediniz."));
trsuperobject.biblemap.put("b47_7_10", new trsuperobject(47,7,10,"Tanrının isteğiyle çekilen acı, kişiyi kurtuluşla sonuçlanan ve pişmanlık doğurmayan tövbeye götürür. Dünyanın acılarıysa ölüm getirir."));
trsuperobject.biblemap.put("b47_7_11", new trsuperobject(47,7,11,"Bakın bu acılar, Tanrının isteğiyle çektiğiniz bu acılar sizde ne büyük ciddiyet, paklanmak için ne büyük istek yarattı! Sizde ne büyük öfke, korku, özlem, gayret ve suçluyu cezalandırma arzusu uyandırdı! Bu konuda her bakımdan masum olduğunuzu kanıtladınız."));
trsuperobject.biblemap.put("b47_7_12", new trsuperobject(47,7,12,"Size o mektubu yazdımsa da, haksızlık edeni ya da haksızlık göreni düşünerek yazmadım; bize ne denli adanmış olduğunuzu Tanrı önünde açıkça görmenizi istiyordum."));
trsuperobject.biblemap.put("b47_7_13", new trsuperobject(47,7,13,"Bütün bunlarla teselli buluyoruz. Tesellimize ek olarak Titusun sevinci bizi daha da çok sevindirdi. Çünkü hepiniz onun yüreğini ferahlattınız."));
trsuperobject.biblemap.put("b47_7_14", new trsuperobject(47,7,14,"Sizleri ona övdüm, beni utandırmadınız. Size söylediğimiz her şey nasıl doğru idiyse, sizi Titusa övmemiz de öylece doğru çıktı."));
trsuperobject.biblemap.put("b47_7_15", new trsuperobject(47,7,15,"Hepinizin nasıl söz dinlediğini, kendisini nasıl saygı ve korkuyla kabul ettiğinizi anımsadıkça size olan sevgisi daha da artıyor."));
trsuperobject.biblemap.put("b47_7_16", new trsuperobject(47,7,16,"Size her bakımdan güvenebildiğim için seviniyorum."));
trsuperobject.biblemap.put("b47_8_1-2", new trsuperobject(47,8,1-2,"Kardeşler, sizlere Tanrının Makedonyadaki kiliselerine sağladığı lütuftan söz etmek istiyoruz: Büyük sıkıntılarla denendiklerinde, coşkun sevinçleri ve aşırı yoksullukları tam bir cömertliğe dönüştü."));
trsuperobject.biblemap.put("b47_8_3", new trsuperobject(47,8,3,"Ellerinden geldiği kadarını, hatta daha fazlasını kendi istekleriyle verdiklerine tanıklık ederim."));
trsuperobject.biblemap.put("b47_8_4", new trsuperobject(47,8,4,"Kutsallara yapılan yardıma katkıda bulunma ayrıcalığının kendilerine verilmesi için bize yalvarıp yakardılar."));
trsuperobject.biblemap.put("b47_8_5", new trsuperobject(47,8,5,"Umduğumuzdan da öte, kendilerini önce Rabbe, sonra Tanrının isteğiyle bize adadılar."));
trsuperobject.biblemap.put("b47_8_6", new trsuperobject(47,8,6,"Bu nedenle, aranızda daha önce başladığı bu hayırlı işi tamamlaması için Titusu isteklendirdik."));
trsuperobject.biblemap.put("b47_8_7", new trsuperobject(47,8,7,"İmanda, söz söylemekte, bilgide, her tür gayrette, bize beslediğiniz sevgide, her şeyde üstün olduğunuz gibi, bu hayırlı işte de üstün olmaya bakın."));
trsuperobject.biblemap.put("b47_8_8", new trsuperobject(47,8,8,"Bunu buyruk olarak söylemiyorum, yalnızca sevginizin içtenliğini ötekilerin gayretiyle karşılaştırarak sınamak istiyorum."));
trsuperobject.biblemap.put("b47_8_9", new trsuperobject(47,8,9,"Rabbimiz İsa Mesihin lütfunu bilirsiniz. Onun yoksulluğuyla siz zengin olasınız diye, zengin olduğu halde sizin uğrunuza yoksul oldu."));
trsuperobject.biblemap.put("b47_8_10", new trsuperobject(47,8,10,"Bu konuda size yararlı olanı salık veriyorum. Geçen yıl bağış toplamaya ilk girişen, hatta buna ilk heveslenen siz oldunuz."));
trsuperobject.biblemap.put("b47_8_11", new trsuperobject(47,8,11,"Şimdi bu işi tamamlayın; bunu candan arzuladığınız gibi, elinizden geldiğince tamamlamaya bakın."));
trsuperobject.biblemap.put("b47_8_12", new trsuperobject(47,8,12,"Çünkü istek varsa, insanın elinde olmayana göre değil, elindekine göre yardımda bulunması uygundur."));
trsuperobject.biblemap.put("b47_8_13-15", new trsuperobject(47,8,13-15,"Amacımız sizi sıkıntıya sokup başkalarını rahatlatmak değildir. Ama eşitlik olsun diye, şimdi elinizdeki fazlalık onların eksiğini tamamladığı gibi, başka zaman onların elindeki fazlalık sizin eksiğinizi tamamlasın. Öyle ki, ‹‹Çok toplayanın fazlası, az toplayanın da eksiği yoktu›› diye yazılmış olduğu gibi, eşitlik olsun."));
trsuperobject.biblemap.put("b47_8_16", new trsuperobject(47,8,16,"Titusun yüreğinde sizin için aynı ilgiyi uyandıran Tanrıya şükürler olsun!"));
trsuperobject.biblemap.put("b47_8_17", new trsuperobject(47,8,17,"Çünkü Titus yalnız ricamızı kabul etmekle kalmadı, size derin ilgi duyduğu için kendi isteğiyle yanınıza geliyor."));
trsuperobject.biblemap.put("b47_8_18", new trsuperobject(47,8,18,"Müjdeyi yayma çabalarından ötürü bütün kiliselerce övülen bir kardeşi de onunla birlikte gönderiyoruz."));
trsuperobject.biblemap.put("b47_8_19", new trsuperobject(47,8,19,"Üstelik bu kardeş, Rabbi yüceltmek ve yardıma hazır olduğumuzu göstermek için yürüttüğümüz bu hayırlı hizmette yol arkadaşımız olmak üzere kiliseler tarafından seçildi."));
trsuperobject.biblemap.put("b47_8_20", new trsuperobject(47,8,20,"Bu büyük bağışla ilgili hizmetimizde kimsenin eleştirisine hedef olmamaya özen gösteriyoruz."));
trsuperobject.biblemap.put("b47_8_21", new trsuperobject(47,8,21,"Çünkü yalnız Rabbin gözünde değil, insanların gözünde de doğru olanı yapmaya dikkat ediyoruz."));
trsuperobject.biblemap.put("b47_8_22", new trsuperobject(47,8,22,"Birçok konuda defalarca deneyip gayretli bulduğumuz, şimdi size duyduğu büyük güvenle çok daha gayretli olan kardeşimizi de bu iki kişiyle birlikte gönderiyoruz."));
trsuperobject.biblemap.put("b47_8_23", new trsuperobject(47,8,23,"Titusa gelince, o benim paydaşım ve aranızdaki emektaşımdır. Öbür kardeşlerimizse kiliselerin elçileri, Mesihin kıvancıdırlar."));
trsuperobject.biblemap.put("b47_8_24", new trsuperobject(47,8,24,"Bunun için onlara sevginizi kanıtlayın, kiliselerin önünde sizinle övünmemizin nedenini gösterin."));
trsuperobject.biblemap.put("b47_9_1", new trsuperobject(47,9,1,"Kutsallara yapılacak bu yardımla ilgili olarak size yazmama gerek yok."));
trsuperobject.biblemap.put("b47_9_2", new trsuperobject(47,9,2,"Çünkü yardıma hazır olduğunuzu biliyorum. Ahayadaki sizlerin geçen yıldan beri hazırlıklı olduğunu söyleyerek Makedonyalılar karşısında sizinle övünmekteyim. Gayretiniz onların çoğunu harekete geçirdi."));
trsuperobject.biblemap.put("b47_9_3", new trsuperobject(47,9,3,"Bu konuda sizinle övünmemiz boşa çıkmasın; dediğim gibi, hazırlıklı olasınız diye kardeşleri yanınıza gönderiyorum."));
trsuperobject.biblemap.put("b47_9_4", new trsuperobject(47,9,4,"Öyle ki, bazı Makedonyalılar benimle birlikte gelir ve sizi hazırlıksız bulurlarsa, sizler bir yana, bizler duyduğumuz güvenden ötürü utanmayalım."));
trsuperobject.biblemap.put("b47_9_5", new trsuperobject(47,9,5,"Bu nedenle önce yanınıza gelmeleri ve cömertçe vermeyi vaat ettiğiniz armağanları hazırlamaları için kardeşlere ricada bulunmayı gerekli gördüm. Öyle ki, armağanınız cimrilik değil, cömertlik örneği olarak hazır olsun."));
trsuperobject.biblemap.put("b47_9_6", new trsuperobject(47,9,6,"Şunu unutmayın: Az eken az biçer, çok eken çok biçer."));
trsuperobject.biblemap.put("b47_9_7", new trsuperobject(47,9,7,"Herkes yüreğinde niyet ettiği gibi versin; isteksizce ya da zorlanmış gibi değil. Çünkü Tanrı sevinçle vereni sever."));
trsuperobject.biblemap.put("b47_9_8", new trsuperobject(47,9,8,"Her zaman, her yönden, her şeye yeterli ölçüde sahip olarak her iyi işe cömertçe katkıda bulunabilmeniz için, Tanrı her nimeti size bol bol sağlayacak güçtedir."));
trsuperobject.biblemap.put("b47_9_9", new trsuperobject(47,9,9,"Nitekim şöyle yazılmıştır:  ‹‹Armağanlar dağıttı, yoksullara verdi;  Doğruluğu sonsuza dek kalıcıdır.››"));
trsuperobject.biblemap.put("b47_9_10", new trsuperobject(47,9,10,"Ekinciye tohum ve yiyecek ekmek sağlayan Tanrı, sizin de ekeceğinizi sağlayıp çoğaltacak, doğruluğunuzun ürünlerini artıracaktır."));
trsuperobject.biblemap.put("b47_9_11", new trsuperobject(47,9,11,"Her durumda cömert olmanız için her bakımdan zenginleştiriliyorsunuz. Cömertliğiniz bizim aracılığımızla Tanrıya şükran nedeni oluyor."));
trsuperobject.biblemap.put("b47_9_12", new trsuperobject(47,9,12,"Yaptığınız bu hizmet yalnız kutsalların eksiklerini gidermekle kalmıyor, birçoklarının Tanrıya şükretmesiyle de zenginleşiyor."));
trsuperobject.biblemap.put("b47_9_13", new trsuperobject(47,9,13,"Onlar, içtenliğinizi kanıtlayan bu hizmetten ötürü, açıkça benimsediğiniz Mesih Müjdesine uyarak kendileriyle ve herkesle malınızı cömertçe paylaştığınız için Tanrıyı yüceltiyorlar."));
trsuperobject.biblemap.put("b47_9_14", new trsuperobject(47,9,14,"Tanrının size bağışladığı olağanüstü lütuftan dolayı sizler için dua ediyor, sizi özlüyorlar."));
trsuperobject.biblemap.put("b47_9_15", new trsuperobject(47,9,15,"Sözle anlatılamayan armağanı için Tanrı'ya şükürler olsun!"));
trsuperobject.biblemap.put("b47_10_1-2", new trsuperobject(47,10,1-2,"Sizinle birlikteyken ürkek, ama aranızda değilken yiğit kesilen ben Pavlus, Mesihteki alçakgönüllülük ve yumuşaklıkla size rica ediyor, yalvarıyorum: Yanınıza geldiğim zaman, bizi olağan insanlar gibi yaşayanlardan sayan bazılarına karşı güvenle takınmak niyetinde olduğum tavrı aynı cesaretle size karşı takınmaya zorlamayın beni."));
trsuperobject.biblemap.put("b47_10_3", new trsuperobject(47,10,3,"Olağan insanlar gibi yaşıyorsak da, insansal güce dayanarak savaşmıyoruz."));
trsuperobject.biblemap.put("b47_10_4", new trsuperobject(47,10,4,"Çünkü savaşımızın silahları insansal silahlar değil, kaleleri yıkan tanrısal güce sahip silahlardır."));
trsuperobject.biblemap.put("b47_10_5", new trsuperobject(47,10,5,"Safsataları, Tanrı bilgisine karşı diklenen her engeli yıkıyor, her düşünceyi tutsak edip Mesihe bağımlı kılıyoruz."));
trsuperobject.biblemap.put("b47_10_6", new trsuperobject(47,10,6,"Mesihe tümüyle bağımlı olduğunuz zaman, Ona bağımlı olmayan her eylemi cezalandırmaya hazır olacağız."));
trsuperobject.biblemap.put("b47_10_7", new trsuperobject(47,10,7,"Gözünüzün önündekine bakın. Bir kimse Mesihe ait olduğuna güveniyorsa, yine düşünsün: Kendisi kadar biz de Mesihe aitiz."));
trsuperobject.biblemap.put("b47_10_8", new trsuperobject(47,10,8,"Sizi yıkmak için değil, geliştirmek için Rabbin bize verdiği yetkiyle biraz fazla övünsem de utanmam."));
trsuperobject.biblemap.put("b47_10_9", new trsuperobject(47,10,9,"Mektuplarımla sizi korkutmaya çalışıyormuş gibi görünmek istemiyorum."));
trsuperobject.biblemap.put("b47_10_10", new trsuperobject(47,10,10,"Çünkü bazıları, ‹‹Mektupları ağır ve etkilidir, ama kişisel varlığı etkisiz, konuşma yeteneği de sıfır›› diyormuş."));
trsuperobject.biblemap.put("b47_10_11", new trsuperobject(47,10,11,"Böyle diyenler şunu bilsin ki, uzaktayken mektuplarımızda ne diyorsak, aranızdayken de öyle davranıyoruz."));
trsuperobject.biblemap.put("b47_10_12", new trsuperobject(47,10,12,"Kendilerini tavsiye eden bazılarıyla kendimizi bir tutmaya ya da karşılaştırmaya elbette cesaret edemeyiz! Onlar kendilerini kendileriyle ölçüp karşılaştırmakla akılsızlık ediyorlar."));
trsuperobject.biblemap.put("b47_10_13", new trsuperobject(47,10,13,"Ama biz haddimizi aşıp fazla övünmeyiz; övünmemiz, Tanrının bizim için belirlediği, sizlere kadar da uzanan alanın sınırları içinde kalır."));
trsuperobject.biblemap.put("b47_10_14", new trsuperobject(47,10,14,"Etkinlik alanımız size kadar uzanmasaydı, sizinle ilgilenmekle sınırlarımızın dışına çıkmış sayılabilirdik. Oysa Mesihin Müjdesini size kadar ilk ulaştıran biz olduk."));
trsuperobject.biblemap.put("b47_10_15", new trsuperobject(47,10,15,"Başkalarının emeğiyle övünüp haddimizi aşmayız. Umudumuz odur ki, sizin imanınız büyüdükçe sayenizde etkinlik alanımız alabildiğine genişleyecek."));
trsuperobject.biblemap.put("b47_10_16", new trsuperobject(47,10,16,"Böylelikle Müjdeyi sizlerden daha ötelere yayabileceğiz. Çünkü başkasının etkinlik alanında başarılmış işlerle övünmek istemiyoruz."));
trsuperobject.biblemap.put("b47_10_17", new trsuperobject(47,10,17,"‹‹Övünen, Rable övünsün.››"));
trsuperobject.biblemap.put("b47_10_18", new trsuperobject(47,10,18,"Kabule değer kişi kendi kendini tavsiye eden değil, Rab'bin tavsiye ettiği kişidir."));
trsuperobject.biblemap.put("b47_11_1", new trsuperobject(47,11,1,"Umarım yapacağım küçük bir akılsızlığı hoş görürsünüz. Ne olur, beni hoş görün!"));
trsuperobject.biblemap.put("b47_11_2", new trsuperobject(47,11,2,"Sizler için tanrısal bir kıskançlık duyuyorum. Çünkü sizleri el değmemiş kız gibi tek ere, Mesihe sunmak üzere nişanladım."));
trsuperobject.biblemap.put("b47_11_3", new trsuperobject(47,11,3,"Ne var ki, yılanın Havvayı kurnazlığıyla aldatması gibi, düşüncelerinizin Mesihe olan içten ve pak adanmışlıktan saptırılmasından korkuyorum."));
trsuperobject.biblemap.put("b47_11_4", new trsuperobject(47,11,4,"Çünkü size gelen ve bizim tanıttığımızdan değişik bir İsayı tanıtanları pekâlâ hoş görüyorsunuz. Ayrıca, aldığınız ruhtan farklı bir ruhu ve kabul ettiğinizden farklı bir müjdeyi kabul ederek bunları hoş görüyorsunuz."));
trsuperobject.biblemap.put("b47_11_5", new trsuperobject(47,11,5,"Sözüm ona üstün elçilerden hiç de aşağı olduğumu sanmıyorum!"));
trsuperobject.biblemap.put("b47_11_6", new trsuperobject(47,11,6,"Acemi bir konuşmacı olabilirim, ama bilgiden yana acemi değilim. Bunu size her durumda, her bakımdan açıkça gösterdik."));
trsuperobject.biblemap.put("b47_11_7", new trsuperobject(47,11,7,"Yücelmeniz için kendimi alçaltarak Tanrının Müjdesini size karşılıksız bildirmekle günah mı işledim?"));
trsuperobject.biblemap.put("b47_11_8", new trsuperobject(47,11,8,"Size hizmet etmek için yardım aldığım başka kiliseleri adeta soydum."));
trsuperobject.biblemap.put("b47_11_9", new trsuperobject(47,11,9,"Aranızdayken ihtiyacım olduğu halde hiçbirinize yük olmadım. Çünkü Makedonyadan gelen kardeşler eksiklerimi tamamladılar. Size yük olmamaya hep özen gösterdim, bundan böyle de özen göstereceğim."));
trsuperobject.biblemap.put("b47_11_10", new trsuperobject(47,11,10,"Mesihin gerçeğine sahip olarak kesinlikle diyebilirim ki, Ahaya İlinde hiç kimse beni böyle övünmekten alıkoyamaz."));
trsuperobject.biblemap.put("b47_11_11", new trsuperobject(47,11,11,"Neden mi? Sizi sevmediğimden mi? Tanrı biliyor ki, sizi seviyorum."));
trsuperobject.biblemap.put("b47_11_12", new trsuperobject(47,11,12,"Övündükleri konuda bize eşit sayılmak isteyen fırsatçılara fırsat vermemek için, yaptığımı yapmaya devam edeceğim."));
trsuperobject.biblemap.put("b47_11_13", new trsuperobject(47,11,13,"Bu tür adamlar sahte elçiler, düzenbaz işçiler, kendilerine Mesihin elçisi süsü verenlerdir."));
trsuperobject.biblemap.put("b47_11_14", new trsuperobject(47,11,14,"Buna şaşmamalı. Şeytan da kendisine ışık meleği süsü verir."));
trsuperobject.biblemap.put("b47_11_15", new trsuperobject(47,11,15,"Ona hizmet edenlerin de kendilerine doğruluğun hizmetkârları süsü vermesi şaşırtıcı değildir. Onların sonu yaptıklarına göre olacaktır."));
trsuperobject.biblemap.put("b47_11_16", new trsuperobject(47,11,16,"Yine söylüyorum, kimse beni akılsız sanmasın. Öyle sanıyorsanız, akılsız birini kabul eder gibi de olsa beni kabul edin ki, ben de biraz övüneyim!"));
trsuperobject.biblemap.put("b47_11_17", new trsuperobject(47,11,17,"Söylediklerimi Rabbin söyleyeceği gibi değil, akılsız biri gibi, bu övüngen tavırla söylüyorum."));
trsuperobject.biblemap.put("b47_11_18", new trsuperobject(47,11,18,"Mademki birçokları ne olduklarıyla övünüyorlar, ben de övüneceğim."));
trsuperobject.biblemap.put("b47_11_19", new trsuperobject(47,11,19,"Sizler akıllı olduğunuz için akılsızlara seve seve katlanıyorsunuz!"));
trsuperobject.biblemap.put("b47_11_20", new trsuperobject(47,11,20,"Aslında sizi köle edenlere, sömürenlere, sizden yararlananlara, büyüklük taslayanlara ya da sizi tokatlayanlara katlanıyorsunuz."));
trsuperobject.biblemap.put("b47_11_21", new trsuperobject(47,11,21,"Utanarak kabul ediyorum ki, biz bunu yapacak güçte değildik! Ama birinin övünmeye cesaret ettiği konuda -akılsız biri gibi konuşuyorum- ben de övünmeye cesaret ediyorum."));
trsuperobject.biblemap.put("b47_11_22", new trsuperobject(47,11,22,"Onlar İbrani mi? Ben de İbraniyim. İsrailli mi? Ben de İsrailliyim. İbrahimin soyundan mıdırlar? Ben de onun soyundanım."));
trsuperobject.biblemap.put("b47_11_23", new trsuperobject(47,11,23,"Mesihin hizmetkârları mıdırlar? Aklımı kaçırmış gibi konuşuyorum. Ben Onun daha üstün bir hizmetkârıyım. Ben daha çok emek verdim, hapse daha çok girdim, sayısız dayak yedim, çok kez ölümle burun buruna geldim."));
trsuperobject.biblemap.put("b47_11_24", new trsuperobject(47,11,24,"Beş kez Yahudilerden otuz dokuzar kırbaç yedim."));
trsuperobject.biblemap.put("b47_11_25", new trsuperobject(47,11,25,"Üç kez değnekle dövüldüm, bir kez taşlandım, üç kez deniz kazasına uğradım. Bir gün bir gece açık denizde kaldım."));
trsuperobject.biblemap.put("b47_11_26", new trsuperobject(47,11,26,"Sık sık yolculuk ettim. Irmaklarda, haydutlar arasında, gerek soydaşlarımın gerekse öteki ulusların arasında tehlikelere uğradım. Kentte, kırda, denizde, sahte kardeşler arasında tehlikelere düştüm."));
trsuperobject.biblemap.put("b47_11_27", new trsuperobject(47,11,27,"Emek verdim, sıkıntı çektim, çok kez uykusuz kaldım. Açlığı, susuzluğu tattım. Çok kez yiyecek sıkıntısı çektim, soğukta çıplak kaldım."));
trsuperobject.biblemap.put("b47_11_28", new trsuperobject(47,11,28,"Öbür sorunların yanısıra, bütün kiliseler için her gün çektiğim kaygının baskısı var üzerimde."));
trsuperobject.biblemap.put("b47_11_29", new trsuperobject(47,11,29,"Kim güçsüz olur da ben güçsüz olmam? Kim günaha düşürülür de ben onun için yanmam?"));
trsuperobject.biblemap.put("b47_11_30", new trsuperobject(47,11,30,"Övünmem gerekiyorsa, güçsüzlüğümü gösteren şeylerle övüneceğim."));
trsuperobject.biblemap.put("b47_11_31", new trsuperobject(47,11,31,"Rab İsanın sonsuza dek övülecek olan Tanrısı ve Babası biliyor ki, yalan söylemiyorum."));
trsuperobject.biblemap.put("b47_11_32", new trsuperobject(47,11,32,"Şamda Kral Aretasın valisi beni yakalatmak için kenti denetim altına almıştı."));
trsuperobject.biblemap.put("b47_11_33", new trsuperobject(47,11,33,"Ama beni küfe içinde surdaki bir pencereden sarkıttılar; böylece onun elinden sıyrılıp kaçtım."));
trsuperobject.biblemap.put("b47_12_1", new trsuperobject(47,12,1,"Yararlı olmasa da övünmek gereklidir. Şimdi görümlere ve Rabbin vahiylerine geleyim."));
trsuperobject.biblemap.put("b47_12_2", new trsuperobject(47,12,2,"On dört yıl önce alınıp üçüncü göğe götürülmüş bir Mesih izleyicisi tanıyorum. Bu, bedensel olarak mı, yoksa beden dışında mı oldu, bilmiyorum, Tanrı bilir."));
trsuperobject.biblemap.put("b47_12_3-4", new trsuperobject(47,12,3-4,"Evet, bu adamın cennete götürüldüğünü biliyorum; bu, bedensel olarak mı, yoksa bedenden ayrı mı oldu, bilmiyorum, Tanrı bilir. Orada, dille anlatılamaz, insanın söylemesi yasak olan sözler işitti."));
trsuperobject.biblemap.put("b47_12_5", new trsuperobject(47,12,5,"Böyle biriyle övüneceğim. Ama kendimle ilgili olarak, güçsüzlüklerimden başka bir şeyle övünmeyeceğim."));
trsuperobject.biblemap.put("b47_12_6", new trsuperobject(47,12,6,"Övünmek istesem bile akılsız olmayacağım. Çünkü gerçeği söylemiş olacağım. Ama kimse beni gördüğünden ya da işittiğinden daha üstün görmesin diye övünmekten kaçınıyorum."));
trsuperobject.biblemap.put("b47_12_7", new trsuperobject(47,12,7,"Aldığım vahiylerin üstünlüğüyle gururlanmayayım diye bana bedende bir diken, beni yumruklamak için Şeytanın bir meleği verildi, gururlanmayayım diye."));
trsuperobject.biblemap.put("b47_12_8", new trsuperobject(47,12,8,"Bundan kurtulmak için Rabbe üç kez yalvardım."));
trsuperobject.biblemap.put("b47_12_9", new trsuperobject(47,12,9,"Ama O bana, ‹‹Lütfum sana yeter. Çünkü gücüm, güçsüzlükte tamamlanır›› dedi. İşte, Mesihin gücü içimde bulunsun diye güçsüzlüklerimle sevinerek daha çok övüneceğim."));
trsuperobject.biblemap.put("b47_12_10", new trsuperobject(47,12,10,"Bu nedenle Mesih uğruna güçsüzlükleri, hakaretleri, zorlukları, zulümleri ve darlıkları sevinçle karşılıyorum. Çünkü ne zaman güçsüzsem, o zaman güçlüyüm."));
trsuperobject.biblemap.put("b47_12_11", new trsuperobject(47,12,11,"Akılsız biri gibi davrandım, ama beni buna siz zorladınız. Aslında beni siz tavsiye etmeliydiniz. Çünkü bir hiç isem de, sözüm ona üstün elçilerden hiç de aşağı değilim."));
trsuperobject.biblemap.put("b47_12_12", new trsuperobject(47,12,12,"Elçiliğimin kanıtları aranızda büyük bir sabırla, belirtiler, harikalar ve mucizelerle gösterildi."));
trsuperobject.biblemap.put("b47_12_13", new trsuperobject(47,12,13,"Size yük olmayışımdan başka öbür kiliselerden ne eksiğiniz var ki? Bu haksızlığımı bağışlayın!"));
trsuperobject.biblemap.put("b47_12_14", new trsuperobject(47,12,14,"İşte, üçüncü kez yanınıza gelmeye hazırım ve size yük olmayacağım. Çünkü sizde olanı değil, sizi istiyorum. Çocukların anne babaları için değil, anne babaların çocukları için para biriktirmesi gerekir."));
trsuperobject.biblemap.put("b47_12_15", new trsuperobject(47,12,15,"Ben de canlarınız uğruna malımı da kendimi de seve seve harcayacağım. Sizi daha çok seversem, daha az mı sevileceğim?"));
trsuperobject.biblemap.put("b47_12_16", new trsuperobject(47,12,16,"Öyle olsun, ben size yük olmadım. Ama kurnaz biri olduğumdan sizi hileyle elde etmişim!"));
trsuperobject.biblemap.put("b47_12_17", new trsuperobject(47,12,17,"Size gönderdiğim adamlardan biri aracılığıyla sizi sömürdüm mü?"));
trsuperobject.biblemap.put("b47_12_18", new trsuperobject(47,12,18,"Titusu size gelmeye isteklendirdim ve öbür kardeşi de onunla birlikte gönderdim. Titus sizi sömürmedi, değil mi? Aynı ruhla davranmadık mı, aynı yolu izlemedik mi?"));
trsuperobject.biblemap.put("b47_12_19", new trsuperobject(47,12,19,"Bunca zamandır önünüzde kendimizi savunduğumuzu mu düşünüyorsunuz? Tanrının önünde, Mesihe ait kişiler olarak konuşuyoruz. Sevgili kardeşler, yaptığımız her şey sizin gelişmeniz içindir."));
trsuperobject.biblemap.put("b47_12_20", new trsuperobject(47,12,20,"Çünkü geldiğimde sizi istediğim durumda bulamayacağımdan korkuyorum. Sizler de beni istediğiniz durumda bulamayabilirsiniz. Aranızda çekişme, kıskançlık, öfke, bencil tutkular, iftira, dedikodu, böbürlenme, kargaşa olmasından korkuyorum."));
trsuperobject.biblemap.put("b47_12_21", new trsuperobject(47,12,21,"Korkarım size tekrar geldiğimde Tanrım beni önünüzde utandıracak; daha önce günah işleyip de kapıldıkları pisliklerden, fuhuş ve sefahatten tövbe etmeyen birçokları için yas tutacağım."));
trsuperobject.biblemap.put("b47_13_1", new trsuperobject(47,13,1,"Bu, yanınıza üçüncü gelişim olacak. Her suçlama iki ya da üç tanığın tanıklığıyla doğrulanmalıdır."));
trsuperobject.biblemap.put("b47_13_2", new trsuperobject(47,13,2,"Daha önce, aranızda ikinci kez bulunduğumda, geçmişte günah işlemiş olanlarla onların dışında kalanların hepsine söylemiştim, şimdi sizden uzaktayken de yineliyorum: Tekrar yanınıza gelirsem, hiç kimseyi esirgemeyeceğim!"));
trsuperobject.biblemap.put("b47_13_3", new trsuperobject(47,13,3,"Mesihin benim aracılığımla konuştuğuna ilişkin kanıt istiyorsunuz. Mesih size karşı güçsüz değildir; Onun gücü sizde etkindir."));
trsuperobject.biblemap.put("b47_13_4", new trsuperobject(47,13,4,"Güçsüzlük içinde çarmıha gerildiği halde, şimdi Tanrının gücüyle yaşıyor. Biz de Onda güçsüz olduğumuz halde, Tanrının gücü sayesinde Onunla birlikte sizin yararınıza yaşayacağız."));
trsuperobject.biblemap.put("b47_13_5", new trsuperobject(47,13,5,"İman yolunda olup olmadığınızı anlamak için kendinizi sınayıp yoklayın. İsa Mesihin içinizde olduğunu bilmiyor musunuz? Yoksa sınavdan başarısız çıkarsınız."));
trsuperobject.biblemap.put("b47_13_6", new trsuperobject(47,13,6,"Umarım bizim başarısızlığa uğramadığımızı anlayacaksınız."));
trsuperobject.biblemap.put("b47_13_7", new trsuperobject(47,13,7,"Kötü bir şey yapmamanız için Tanrıya dua ediyoruz. Dileğimiz, bizim sınavı geçmiş görünmemiz değil, biz sınavda başarısız görünsek bile sizin iyi olanı yapmanızdır."));
trsuperobject.biblemap.put("b47_13_8", new trsuperobject(47,13,8,"Çünkü gerçeğe karşı değil, ancak gerçek uğruna bir şey yapabiliriz."));
trsuperobject.biblemap.put("b47_13_9", new trsuperobject(47,13,9,"Biz güçsüz, sizse güçlüyken seviniyoruz. Yetkin olmanız için de dua ediyoruz."));
trsuperobject.biblemap.put("b47_13_10", new trsuperobject(47,13,10,"Rabbin yıkmak değil, geliştirmek için bana verdiği yetkiyi yanınıza geldiğimde sert biçimde kullanmak zorunda kalmayayım diye, bunları aranızda değilken yazıyorum."));
trsuperobject.biblemap.put("b47_13_11", new trsuperobject(47,13,11,"Son olarak hoşça kalın, kardeşlerim. Yaşantınızı düzeltin, çağrıma kulak verin, düşüncelerinizde birlik olun, esenlik içinde yaşayın. Sevgi ve esenlik kaynağı olan Tanrı sizinle birlikte olacaktır."));
trsuperobject.biblemap.put("b47_13_12", new trsuperobject(47,13,12,"Birbirinizi kutsal öpüşle selamlayın."));
trsuperobject.biblemap.put("b47_13_13", new trsuperobject(47,13,13,"Bütün kutsallar size selam eder."));
trsuperobject.biblemap.put("b47_13_14", new trsuperobject(47,13,14,"Rab İsa Mesih'in lütfu, Tanrı'nın sevgisi ve Kutsal Ruh'un paydaşlığı hepinizle birlikte olsun."));

}

}