package tr.bible;

public class trbible28 {

public trbible28() {

putmapbible28();

}

private void putmapbible28() {

trsuperobject.biblemap.put("b28_1_1", new trsuperobject(28,1,1,"Uzziya, Yotam, Ahaz ve Hizkiyanın Yahudada ve Yehoaş oğlu Yarovamın İsrailde krallık ettiği dönemde RABbin Beeri oğlu Hoşeaya bildirdiği sözler."));
trsuperobject.biblemap.put("b28_1_3", new trsuperobject(28,1,3,"Böylece Hoşea gidip Divlayimin kızı Gomerle evlendi. Kadın hamile kalıp kendisine bir oğul doğurdu."));
trsuperobject.biblemap.put("b28_1_5", new trsuperobject(28,1,5,"Ve o gün Yizreel Vadisinde İsrailin yayını kıracağım.›› anlamına gelir."));
trsuperobject.biblemap.put("b28_1_6", new trsuperobject(28,1,6,"Gomer yine hamile kaldı ve bir kız doğurdu. RAB Hoşeaya, ‹‹Adını Lo-Ruhama koy›› dedi, ‹‹Çünkü artık İsrail soyuna acımayacağım, onları bağışlamayacağım."));
trsuperobject.biblemap.put("b28_1_7", new trsuperobject(28,1,7,"Ancak Yahuda soyuna merhamet edeceğim. Ben kurtaracağım onları, ama yay, kılıç, savaş, at ve atlılar aracılığıyla değil, kendi aracılığımla.››"));
trsuperobject.biblemap.put("b28_1_8", new trsuperobject(28,1,8,"Gomer Lo-Ruhamayı sütten kesince yine hamile kaldı ve bir oğul doğurdu."));
trsuperobject.biblemap.put("b28_1_10", new trsuperobject(28,1,10,"‹‹Yine de İsraillilerin sayısı denizin kumu gibi sayılamaz, ölçülemez olacak. Kendilerine, ‹Siz halkım değilsiniz› denilen yerde, ‹Yaşayan Tanrının çocuklarısınız› denecek."));
trsuperobject.biblemap.put("b28_1_11", new trsuperobject(28,1,11,"Yahuda ve İsrail halkları yeniden birleşecek. Başlarına tek önder atayacaklar. Ülkeden çıkacaklar. Çünkü Yizreel günü büyük bir gün olacak."));
trsuperobject.biblemap.put("b28_2_1", new trsuperobject(28,2,1,"‹‹Kardeşlerinizi ‹Halkım›, kızkardeşlerinizi ‹Merhamete ermişler› diye çağırın.››"));
trsuperobject.biblemap.put("b28_2_2", new trsuperobject(28,2,2,"‹‹Azarlayın annenizi, azarlayın,Çünkü o benim karım değil artık,Ben de onun kocası değilim.Yüzünden akan fahişeliği,Koynundan zinaları atsın."));
trsuperobject.biblemap.put("b28_2_3", new trsuperobject(28,2,3,"Yoksa onu çırılçıplak soyacak,Anneden doğma edeceğim,Çöle, çorak toprağa çevirecek,Susuzluktan öldüreceğim."));
trsuperobject.biblemap.put("b28_2_4", new trsuperobject(28,2,4,"Acımayacağım çocuklarına,Çünkü onlar zina çocuklarıdır."));
trsuperobject.biblemap.put("b28_2_5", new trsuperobject(28,2,5,"Anneleri zina etti,Onlara gebe kaldı, rezillik etti.‹Oynaşlarımın ardından gideceğim› dedi,‹Ekmeğimi, suyumu, yapağımı, ketenimi, zeytinyağımı, içkimi onlar veriyor.›"));
trsuperobject.biblemap.put("b28_2_6", new trsuperobject(28,2,6,"İşte bu yüzden onun yoluna dikenli çit çekeceğim,Yolunu bulamasın diyeÖnüne duvar öreceğim."));
trsuperobject.biblemap.put("b28_2_7", new trsuperobject(28,2,7,"Oynaşlarının ardına düşecek,Ama onlara erişemeyecek,Onları arayacak,Ama bulamayacak.O zaman, ‹İlk kocama döneyim› diyecek,‹Çünkü o zamanki halim şimdikinden iyiydi!›"));
trsuperobject.biblemap.put("b28_2_8", new trsuperobject(28,2,8,"Ama kendisine tahıl, yeni şarap, zeytinyağı verenin,Baal için harcadığı altınla gümüşü bol bol sağlayanınBen olduğumu bilmedi."));
trsuperobject.biblemap.put("b28_2_9", new trsuperobject(28,2,9,"Bu yüzden zamanında tahılımı,Mevsiminde yeni şarabımı geri alacağım;Çıplak bedenini örten yapağımı, ketenimi çekip alacağım."));
trsuperobject.biblemap.put("b28_2_10", new trsuperobject(28,2,10,"Evet, oynaşlarının önünde ayıbını ortaya çıkaracağım,Kimse elimden kurtaramayacak onu."));
trsuperobject.biblemap.put("b28_2_11", new trsuperobject(28,2,11,"Bütün sevincine, bayramlarına,Yeni Ay törenlerine, Şabat günlerine,Dinsel bayramlarının tümüne son vereceğim."));
trsuperobject.biblemap.put("b28_2_12", new trsuperobject(28,2,12,"Viran edeceğim asmalarını, incir ağaçlarını,Hani, ‹Bunlar oynaşlarımın bana verdiği ücrettir› dediği;Çalılığa çevireceğim onları,Yem olacaklar yabanıl hayvanlara."));
trsuperobject.biblemap.put("b28_2_13", new trsuperobject(28,2,13,"Cezalandıracağım onu,Baallara buhur yaktığı günler için;Halkalarla, takılarla süslenmiş,Oynaşlarının ardınca gitmiş,Beni unutmuştu››Diyor RAB."));
trsuperobject.biblemap.put("b28_2_14", new trsuperobject(28,2,14,"‹‹İşte bu yüzden onu ikna edip çöle götürecek,Onunla dostça konuşacağım."));
trsuperobject.biblemap.put("b28_2_15", new trsuperobject(28,2,15,"Kendisine orada bağlar vereceğim,Akorfç Vadisini ona umut kapısı yapacağım.Gençlik günlerinde olduğu gibi,Mısırdan çıktığı günlerde olduğu gibi,Ezgiler söyleyecek."));
trsuperobject.biblemap.put("b28_2_16", new trsuperobject(28,2,16,"Ve o gün gelecek›› diyor RAB,‹‹Bana, ‹Kocam› diyeceksin;Artık, ‹Efendim› demeyeceksin. var. Baal hem bir ilahın adı hem de ‹‹Koca››, ‹‹Efendi›› anlamlarına gelir."));
trsuperobject.biblemap.put("b28_2_17", new trsuperobject(28,2,17,"Ağzından Baalların adını sileceğim,Adları bir daha anılmayacak."));
trsuperobject.biblemap.put("b28_2_18", new trsuperobject(28,2,18,"Kırdaki hayvanlarla, gökteki kuşlarla,Toprakta yaşayan canlılarla,Halkım için o gün antlaşma yapacağım;Ülkeden yayı, kılıcı, savaşı kaldıracağım,Güvenlik içinde yatıracağım onları."));
trsuperobject.biblemap.put("b28_2_19", new trsuperobject(28,2,19,"Seni sonsuza dek kendime eş alacağım,Doğruluk, adalet, sevgi, merhamet temelindeSeninle evleneceğim."));
trsuperobject.biblemap.put("b28_2_20", new trsuperobject(28,2,20,"Sadakatle seninle evleneceğim,RABbi tanıyacaksın."));
trsuperobject.biblemap.put("b28_2_21", new trsuperobject(28,2,21,"‹‹Ve o gün yanıt vereceğim›› diyor RAB,‹‹Göklere yanıt vereceğim;Onlar da yere yanıt verecek;"));
trsuperobject.biblemap.put("b28_2_22", new trsuperobject(28,2,22,"Yerse, tahıla, yeni şaraba,Zeytinyağına yanıt verecek,Onlar da Yizreele yanıt verecekler."));
trsuperobject.biblemap.put("b28_2_23", new trsuperobject(28,2,23,"Onu ülkede kendim için ekeceğim,Merhamete ermemiş olana acıyacağım,Halkım olmayana, ‹Halkımsın› diyeceğim;Onlar da bana, ‹Tanrım› diyecekler.››"));
trsuperobject.biblemap.put("b28_3_2", new trsuperobject(28,3,2,"Böylece onu on beş şekel gümüş, bir homer bir letek arpa karşılığında satın aldım kendime."));
trsuperobject.biblemap.put("b28_3_3", new trsuperobject(28,3,3,"Ona, ‹‹Uzun süre benimle yaşayacaksın›› dedim, ‹‹Zina etmeyecek, başka bir erkekle dostluk kurmayacaksın. Ben de sana öyle davranacağım.››"));
trsuperobject.biblemap.put("b28_3_4", new trsuperobject(28,3,4,"Çünkü İsrailliler uzun süre kral, önder, kurban, dikili taş, efod, aile putu olmadan yaşayacak."));
trsuperobject.biblemap.put("b28_3_5", new trsuperobject(28,3,5,"Sonra dönüp Tanrıları RAB'bi, kralları Davut'u arayacaklar. Son günlerde korkarak RAB'be ve O'nun iyiliğine yönelecekler."));
trsuperobject.biblemap.put("b28_4_1", new trsuperobject(28,4,1,"Ey İsrailliler, dinleyin RABbin sözünü,Çünkü RABbin davası var bu ülkede yaşayanlarla;‹‹Yok olmuş sevgi, sadakat, Tanrı bilgisi."));
trsuperobject.biblemap.put("b28_4_2", new trsuperobject(28,4,2,"Lanet, yalan, adam öldürme, hırsızlık,Zina almış her şeyin yerini.Zorbalık ediyorlar,Kan üstüne kan döküyorlar."));
trsuperobject.biblemap.put("b28_4_3", new trsuperobject(28,4,3,"Bu yüzden ülke yas tutuyor,Tükeniyor orada yaşayan herkes,Kırdaki hayvanlar, gökteki kuşlarDenizdeki balıklar..."));
trsuperobject.biblemap.put("b28_4_4", new trsuperobject(28,4,4,"‹‹Ancak kimse kimseyle çekişmesin,Kimse kimseyi suçlamasın,Çünkü halkın kâhinle çekişenlere benziyor."));
trsuperobject.biblemap.put("b28_4_5", new trsuperobject(28,4,5,"Sen gündüz tökezleyeceksin,Peygamber de gece seninle birlikte,Yok edeceğim anneni."));
trsuperobject.biblemap.put("b28_4_6", new trsuperobject(28,4,6,"‹‹Yok oldu halkım bilgisizlikten,Sen bilgiyi reddettiğin için,Ben de seni reddedeceğim,Bana kâhinlik etmeyesin diye.Sen Tanrının yasasını unuttuğun için,Ben de senin çocuklarını unutacağım."));
trsuperobject.biblemap.put("b28_4_7", new trsuperobject(28,4,7,"Kâhinler çoğaldıkçaDaha çok günah işlediler bana karşı,Onların onurunu utanca çevireceğim. Süryanice ve bazı eski İbrani din bilginlerine göre ‹‹Onurumu utanca çevirecekler››."));
trsuperobject.biblemap.put("b28_4_8", new trsuperobject(28,4,8,"Halkımın günahlarıylafı besleniyorlar,Onların suç işlemesini istiyorlar. ‹‹Günah sunusu›› anlamına gelir (bkz. Lev.6:25-30)."));
trsuperobject.biblemap.put("b28_4_9", new trsuperobject(28,4,9,"Halkın başına gelenler kâhinlerin başına da gelecek,Tuttukları yol yüzünden cezalandıracağım onları,Yaptıklarının karşılığını vereceğim."));
trsuperobject.biblemap.put("b28_4_10", new trsuperobject(28,4,10,"Yiyecekler, ama doymayacaklar,Zina edecekler, ama çoğalmayacaklar.Çünkü RABbi dinlemekten vazgeçtiler."));
trsuperobject.biblemap.put("b28_4_11", new trsuperobject(28,4,11,"‹‹Zina, yeni ve eski şarap insanın aklını başından alır."));
trsuperobject.biblemap.put("b28_4_12", new trsuperobject(28,4,12,"Halkım tahta puta danışıyor,Değneğinden yanıt alıyor.Çünkü zina ruhu onları saptırdı,Kendi Tanrılarından ayrılarak zina ettiler."));
trsuperobject.biblemap.put("b28_4_13", new trsuperobject(28,4,13,"Dağ başlarında kurban kesiyor,Tepelerde meşe, aselbent, yabanıl fıstık ağaçları altında buhur yakıyorlar,Gölgeleri güzel olduğu için.Bu yüzden kızlarınız fahişelik ediyor,Gelinleriniz zina."));
trsuperobject.biblemap.put("b28_4_14", new trsuperobject(28,4,14,"Fahişelik ettiklerinde kızlarınızı,Zina ettiklerinde gelinlerinizi cezalandırmayacağım.Çünkü erkekleriniz fahişelerle oynaşıyor,Putların tapınağında fuhuş yapanlarla kurban kesiyorlar.Anlayışsız halk mahvolacak."));
trsuperobject.biblemap.put("b28_4_15", new trsuperobject(28,4,15,"‹‹Ey İsrail, sen zina etsen de,Yahuda suç işlemese bari.  ‹‹Gilgala gitmeyin,Beytavene çıkmayın.‹Yaşayan RABbin hakkı için› diye ant içmeyin. tapınma merkezleriydi."));
trsuperobject.biblemap.put("b28_4_16", new trsuperobject(28,4,16,"Çünkü İsrail inatçı bir inek gibi inat etti,Şimdi RAB nasıl güder onları otlakta kuzu gibi?"));
trsuperobject.biblemap.put("b28_4_17", new trsuperobject(28,4,17,"Efrayim putlarına sarıldı,Bırak onu!"));
trsuperobject.biblemap.put("b28_4_18", new trsuperobject(28,4,18,"İçkileri tükendi,Hâlâ zina ediyorlar;Önderleri rezilliğe gönül verdi."));
trsuperobject.biblemap.put("b28_4_19", new trsuperobject(28,4,19,"Rüzgar onları kanatlarına sardı,Kurbanları yüzünden utanacaklar."));
trsuperobject.biblemap.put("b28_5_1", new trsuperobject(28,5,1,"‹‹Ey kâhinler, işitin bunu!Ey İsrailliler, dikkatle dinleyin!Kulak verin, ey saraydakiler!Bu yargı size uygulanacak.Çünkü siz Mispada bir tuzak,Tavor Dağına serilmiş bir ağ oldunuz."));
trsuperobject.biblemap.put("b28_5_2", new trsuperobject(28,5,2,"Başkaldıranlar azıttıkça azıttı,Ama ben hepsini yola getireceğim."));
trsuperobject.biblemap.put("b28_5_3", new trsuperobject(28,5,3,"Efrayimi tanırım,İsrailde de benim için gizli bir şey yok.Çünkü daha yeni zina ettin, ey Efrayim,Kirlenmiş İsrail."));
trsuperobject.biblemap.put("b28_5_4", new trsuperobject(28,5,4,"Yaptıkları işler Tanrılarına dönmeye izin vermiyor,Çünkü zina ruhu var içlerinde,RABbi tanımıyorlar."));
trsuperobject.biblemap.put("b28_5_5", new trsuperobject(28,5,5,"İsrailin gururu kendine karşı tanıklık ediyor;Suç içinde tökezliyor İsraille Efrayim,Yahuda da birlikte."));
trsuperobject.biblemap.put("b28_5_6", new trsuperobject(28,5,6,"Davarlarıyla, sığırlarıyla RABbi aramaya gidecekler,Ama bulamayacaklar.Çünkü RAB onlardan uzaklaştı."));
trsuperobject.biblemap.put("b28_5_8", new trsuperobject(28,5,8,"‹‹Givada boru, Ramada borazan çalın,Beytavende savaş çağrısı yapın;Düşman peşinizde, ey Benyaminliler!"));
trsuperobject.biblemap.put("b28_5_9", new trsuperobject(28,5,9,"Azar günü Efrayim yıkıma uğrayacak,Kararımı bildiriyorum İsrail oymaklarına."));
trsuperobject.biblemap.put("b28_5_10", new trsuperobject(28,5,10,"Yahuda önderleri sınır taşlarının yerini değiştirenlere benziyor,Gazabımı su gibi dökeceğim üzerlerine."));
trsuperobject.biblemap.put("b28_5_11", new trsuperobject(28,5,11,"Baskı gördü Efrayim,Ezildi yargı önünde,Çünkü bile bile boş şeylerin ardına düştü."));
trsuperobject.biblemap.put("b28_5_12", new trsuperobject(28,5,12,"Ben Efrayimlilere karşı güve,Yahuda halkına karşı küf gibi olacağım."));
trsuperobject.biblemap.put("b28_5_13", new trsuperobject(28,5,13,"‹‹Efrayim hastalığını,Yahuda yarasını görünce,Efrayim Asura gitti,Büyük kraldan yardım istedi.Ama o size şifa veremez,Yaranızı iyileştiremez."));
trsuperobject.biblemap.put("b28_5_14", new trsuperobject(28,5,14,"Çünkü ben Efrayime bir aslan,Yahuda halkına genç bir aslan gibi saldıracağım.Ben parçalayacağım onları,Alıp götüreceğim, kurtaran çıkmayacak."));
trsuperobject.biblemap.put("b28_5_15", new trsuperobject(28,5,15,"Sonra gidip yerime döneceğim,Onlar suçlarını kabul edinceye,Yüzümü arayıncaya dek orada kalacağım.Sıkıntıya düşünce gayretle beni arayacaklar.››"));
trsuperobject.biblemap.put("b28_6_1", new trsuperobject(28,6,1,"‹‹Gelin, RABbe dönelim.Bizi O parçaladı,O iyileştirecek.Bizi O yaraladı,Yaramızı O saracak."));
trsuperobject.biblemap.put("b28_6_2", new trsuperobject(28,6,2,"İki gün sonra bizi diriltecek,Üçüncü gün ayağa kaldıracak,Huzurunda yaşayalım diye."));
trsuperobject.biblemap.put("b28_6_4", new trsuperobject(28,6,4,"Tanrı şöyle diyor:‹‹Ey Efrayim, ne yapayım sana?Ey Yahuda, sana ne yapayım?Sevginiz sabah sisine benziyor,Erkenden uçup giden çiy gibi."));
trsuperobject.biblemap.put("b28_6_5", new trsuperobject(28,6,5,"Bu yüzden sizi peygamberler aracılığıyla lime lime doğradım,Ağzımdan çıkan sözlerle öldürdüm;Yargılarım şimşek gibi ışıldıyor."));
trsuperobject.biblemap.put("b28_6_6", new trsuperobject(28,6,6,"Çünkü ben kurbandan değil, bağlılıktan hoşlanırım,Yakmalık sunulardan çok beni tanımanızı isterim."));
trsuperobject.biblemap.put("b28_6_7", new trsuperobject(28,6,7,"Oysa onlar Adam KentindeAntlaşmaya uymadılar,Orada bana ihanet ettiler. Kenti gibi›› anlamlarına da gelebilir."));
trsuperobject.biblemap.put("b28_6_8", new trsuperobject(28,6,8,"Gilat kötülük yapanların kentidir,Kan izleriyle doludur."));
trsuperobject.biblemap.put("b28_6_9", new trsuperobject(28,6,9,"Haydut çeteleri nasıl pusuya yatarsa,Kâhinler takımı da öyle;Şekem yolunda adam öldürüyor,Rezillik yapıyorlar."));
trsuperobject.biblemap.put("b28_6_10", new trsuperobject(28,6,10,"İsrail halkında korkunç bir şey gördüm.Efrayim zinaya kapılmış,Kirlenmiş İsrail."));
trsuperobject.biblemap.put("b28_6_11", new trsuperobject(28,6,11,"‹‹Ey Yahuda, senin için de bir hasat günü saptandı.  ‹‹Ne zaman halkımın durumunu düzeltmek,"));
trsuperobject.biblemap.put("b28_7_1", new trsuperobject(28,7,1,"İsraile şifa vermek istesem,Efrayimin suçları,Samiriyenin kötülükleri ortaya çıkıyor.Çünkü hile yapıyorlar,Evlere hırsız giriyor,Dışarda haydut çeteleri soygun yapıyor."));
trsuperobject.biblemap.put("b28_7_2", new trsuperobject(28,7,2,"Ne var ki, düşünmüyorlar,Kötülüklerini unutmadığımı.Günahları kuşatıyor onları,Gözümün önündeler."));
trsuperobject.biblemap.put("b28_7_3", new trsuperobject(28,7,3,"‹‹Kralı kötülükleriyle,Önderleri yalanlarıyla sevindiriyorlar."));
trsuperobject.biblemap.put("b28_7_4", new trsuperobject(28,7,4,"Hepsi zinaya düşkün,Yoğrulan hamur ekşiyinceye dekFırıncının ateşini karıştırmaya gerek duymadığı fırın gibi kızgınlar."));
trsuperobject.biblemap.put("b28_7_5", new trsuperobject(28,7,5,"Kralımızın şenlik gününde,Önderler şarabın ateşinden hastalandılar,Kral da alaycılarla elele verdi."));
trsuperobject.biblemap.put("b28_7_6", new trsuperobject(28,7,6,"Fırın gibidir yürekleri,Dolap çevirerek ona yaklaşırlar.İçin için yanar öfkeleriGece boyunca.Alevli ateş gibi parlarSabah olunca."));
trsuperobject.biblemap.put("b28_7_7", new trsuperobject(28,7,7,"Hepsi fırın gibi kızgındır,Yutar yöneticilerini.Bütün kralları düştü,Kimse yardıma çağırmıyor beni."));
trsuperobject.biblemap.put("b28_7_8", new trsuperobject(28,7,8,"‹‹Efrayim öteki halklarla karışıyor,Çevrilmemiş pideye döndü."));
trsuperobject.biblemap.put("b28_7_9", new trsuperobject(28,7,9,"Gücünü yabancılar yedi,Farkında değil;Saçlarına ak düştü,Farkında değil."));
trsuperobject.biblemap.put("b28_7_10", new trsuperobject(28,7,10,"İsrailin gururu kendine karşı tanıklık ediyor;Bütün bunlara karşınYine de dönmüyorlar ben, Tanrıları RABbe,Aramıyorlar beni."));
trsuperobject.biblemap.put("b28_7_11", new trsuperobject(28,7,11,"‹‹Efrayim bön, akılsız bir güvercin gibi,Ya Mısırı yardıma çağırıyor,Ya Asura gidiyor."));
trsuperobject.biblemap.put("b28_7_12", new trsuperobject(28,7,12,"Gittiklerinde ağımı üzerlerine atacak,Gökte uçan kuşlar gibi onları yere indireceğim.Topluluklarına bildirildiği gibi,Onları yola getireceğim."));
trsuperobject.biblemap.put("b28_7_13", new trsuperobject(28,7,13,"Vay onların haline,Çünkü benden uzaklaştılar!Felaket gelecek başlarına,Çünkü başkaldırdılar bana!Ben onları kurtarmak istiyorum,Onlarsa iftira ediyor bana."));
trsuperobject.biblemap.put("b28_7_14", new trsuperobject(28,7,14,"Yürekten yakarmıyorlar,Uluyorlar yataklarının üzerinde.Tahıl ve yeni şarap için kendilerini yaralıyor,Bana sırt çeviriyorlar."));
trsuperobject.biblemap.put("b28_7_15", new trsuperobject(28,7,15,"Ben onları eğittim, bileklerine güç verdim,Onlarsa bana düzen kuruyor."));
trsuperobject.biblemap.put("b28_7_16", new trsuperobject(28,7,16,"Dönüyorlar,Ama Yüce Olan'a değil;Kusurlu yay gibiler.Arsız dilleri yüzündenÖnderleri kılıçtan geçirilecek.Mısır'da gülünç duruma düşecekler bu yüzden.››"));
trsuperobject.biblemap.put("b28_8_1", new trsuperobject(28,8,1,"‹‹Boru çalmaya hazırlan!Düşman kartal gibi dolaşıyor evimin üzerinde;Çünkü İsrail antlaşmaya uymadı,Yasama karşı çıktılar."));
trsuperobject.biblemap.put("b28_8_2", new trsuperobject(28,8,2,"‹Ey Tanrımız,Biz İsrailliler seni tanıyoruz!›Diye bana yakarıyorlar."));
trsuperobject.biblemap.put("b28_8_3", new trsuperobject(28,8,3,"İyi olanı reddettiler,Düşman kovalayacak onları."));
trsuperobject.biblemap.put("b28_8_4", new trsuperobject(28,8,4,"Krallar atadılar bana sormadan,Önderler seçtiler benden habersiz.Altın ve gümüşleriyle yıkımlarına yol açan putlar yaptılar."));
trsuperobject.biblemap.put("b28_8_5", new trsuperobject(28,8,5,"Ey Samiriye, atın buzağı putunuzu,Öfkem alevleniyor size karşı!Hiç mi temiz olamayacaksınız?"));
trsuperobject.biblemap.put("b28_8_6", new trsuperobject(28,8,6,"Çünkü bu İsrailin işidir.O buzağıyı bir usta yaptı,Tanrı değildir o.Samiriyenin buzağı putu parçalanacak."));
trsuperobject.biblemap.put("b28_8_7", new trsuperobject(28,8,7,"Çünkü rüzgar eken kasırga biçer.Baş vermeyen buğday un vermez.Verse bile yabancılar yutacak onu."));
trsuperobject.biblemap.put("b28_8_8", new trsuperobject(28,8,8,"‹‹Yutuldu İsrail,Şimdi uluslar arasında kimsenin beğenmediği bir kap gibi."));
trsuperobject.biblemap.put("b28_8_9", new trsuperobject(28,8,9,"Tek başına dolaşan yaban eşeği gibi Asura gittiler,Efrayim ücretli oynaşlar tuttu."));
trsuperobject.biblemap.put("b28_8_10", new trsuperobject(28,8,10,"Uluslar arasında oynaşlar tutsalar da,Şimdi onları bir araya toplayacağım.Çünkü azalmaya başladılar güçlü kralın baskısı altında."));
trsuperobject.biblemap.put("b28_8_11", new trsuperobject(28,8,11,"‹‹Efrayim günah sunusu sunmak için çok sunak yaptı,Bunlar günah işlemelerine neden oldu."));
trsuperobject.biblemap.put("b28_8_12", new trsuperobject(28,8,12,"Yasamdaki pek çok şeyi onlar için yazdım,Ne var ki garipsediler bunları."));
trsuperobject.biblemap.put("b28_8_13", new trsuperobject(28,8,13,"Bana sundukları kurbanlara gelince,Kurban kesiyor, eti kendileri yiyorlar;Oysa RAB bunu yapanlardan hoşlanmaz.Şimdi anımsayacak suçlarını,Günahları için onları cezalandıracak;Geri dönecekler Mısıra."));
trsuperobject.biblemap.put("b28_8_14", new trsuperobject(28,8,14,"Çünkü İsrail Yaratıcısı'nı unuttu,Saraylar yaptı;Yahuda'ysa birçok kenti surlarla çevirdi,Ama ateş göndereceğim kentlerinin üstüne,Yiyip bitirsin kalelerini.››"));
trsuperobject.biblemap.put("b28_9_1", new trsuperobject(28,9,1,"Ey İsrail, öteki halklar gibi sevinme, coşma!Çünkü kendi Tanrına vefasızlık ederek zina ettin,Harman yerlerinin tümünde zina kazancına gönül verdin."));
trsuperobject.biblemap.put("b28_9_2", new trsuperobject(28,9,2,"Ama harman yeri, şarap teknesi halkı doyurmayacak,Yeni şarap umutları boşa çıkacak."));
trsuperobject.biblemap.put("b28_9_5", new trsuperobject(28,9,5,"Ne yapacaksınız dinsel bayramlarda,RABbin bayram gününde?"));
trsuperobject.biblemap.put("b28_9_6", new trsuperobject(28,9,6,"Yıkımdan kaçsalar bile,Mısır bir araya toplayacak onları,Mof gömecek.Değerli gümüş eşyalarını yabanıl otlar saracak,Diken bitecek çadırlarında."));
trsuperobject.biblemap.put("b28_9_7", new trsuperobject(28,9,7,"Onların ceza günleri geldi,Hesap günleri çattı.Bunu bilsin İsrail!Suçunuzun çokluğundan,Düşmanlığınızın büyüklüğü yüzünden,Peygamber aptal, ruhsal insan deli sayıldı."));
trsuperobject.biblemap.put("b28_9_8", new trsuperobject(28,9,8,"Peygamber Tanrımın yanısıra Efrayime gözcülük eder,Ama tuzak kurulmuş bütün yollarına,Düşmanlık var Tanrının Tapınağında."));
trsuperobject.biblemap.put("b28_9_9", new trsuperobject(28,9,9,"Alabildiğine yozlaştılar,Givada olduğu gibi.Tanrı suçlarını anımsayacak,Günahlarının cezasını verecek."));
trsuperobject.biblemap.put("b28_9_10", new trsuperobject(28,9,10,"‹‹İsrail çöldeBir salkım üzüm gibi geldi bana,Atalarıysa incir ağacının ilk ürünü gibi.Ama Baal-Peora geldiklerindeUtanç dolu puta adadılar kendilerini,Sevdikleri şey kadar iğrenç oldular."));
trsuperobject.biblemap.put("b28_9_11", new trsuperobject(28,9,11,"Efrayimin görkemi bir kuş gibi uçup gidecek,Ne doğum ne gebelik olacak, kimse gebe kalmayacak."));
trsuperobject.biblemap.put("b28_9_12", new trsuperobject(28,9,12,"Çocuklarını büyütseler bile,Çocuklarından edeceğim onları,Kimse kalmayıncaya dek;Evet, vay başlarına,Onları terk ettiğimde!"));
trsuperobject.biblemap.put("b28_9_13", new trsuperobject(28,9,13,"Efrayimi, Sur Kenti gibi,Güzel bir yere kurulmuş gördüm.Ama Efrayim çocuklarını celladın önüne götürecek.››"));
trsuperobject.biblemap.put("b28_9_14", new trsuperobject(28,9,14,"Ya RAB, ver onlara ne vereceksen!Düşük yapan rahimler, sütsüz memeler ver."));
trsuperobject.biblemap.put("b28_9_15", new trsuperobject(28,9,15,"‹‹Gilgaldaki kötülükleri yüzünden,Nefret ettim orada onlardan.İşledikleri günahlardan ötürü,Onları evimden kovacağım.Artık sevmeyeceğim onları,Bütün önderleri asidir."));
trsuperobject.biblemap.put("b28_9_16", new trsuperobject(28,9,16,"Vuruldu Efrayim,Kökleri kurudu,Meyve vermeyecekler artık.Çocuk doğursalar bile,Rahimlerinin değerli meyvelerini öldüreceğim.››"));
trsuperobject.biblemap.put("b28_9_17", new trsuperobject(28,9,17,"Reddedecek Tanrım onları,Çünkü O'nu dinlemediler,Uluslar arasında dolaşıp duracaklar."));
trsuperobject.biblemap.put("b28_10_1", new trsuperobject(28,10,1,"İsrail serpilen bir asmaya benzer,Meyvesini veriyor.Meyvesi arttıkça,Sunakları da arttı.Ülkesi zenginleştikçe,Onu güzel dikili taşlarla donattı."));
trsuperobject.biblemap.put("b28_10_2", new trsuperobject(28,10,2,"İçleri yalan doldu,Şimdi suçlarının cezasını taşımalılar.RAB sunaklarını yıkacak,Dikili taşlarını yok edecek."));
trsuperobject.biblemap.put("b28_10_3", new trsuperobject(28,10,3,"O zaman, ‹‹Kralsız kaldık›› diyecekler,‹‹Çünkü RABden korkmadık.Kralımız olsa bile,Ne yapabilirdi bize?››"));
trsuperobject.biblemap.put("b28_10_4", new trsuperobject(28,10,4,"Antlaşma yaparken,Boş sözler veriyor, yalan yere ant içiyorlar,Bu yüzden davalar, sürülmüş tarladaki zehirli ot gibi boy veriyor."));
trsuperobject.biblemap.put("b28_10_5", new trsuperobject(28,10,5,"Samiriyede yaşayanlarBeytavendeki inek putu yüzünden korkuya kapılacak.Halkı onun ardından yas tutacak,Onun görkemiyle coşan putperest kâhinlerOradan sürgün edildiği için dövünecek."));
trsuperobject.biblemap.put("b28_10_6", new trsuperobject(28,10,6,"Put armağan olarak büyük krala, Asura götürülecek.Efrayim rezil olacak,İsrail aldığı öğütten utanacak."));
trsuperobject.biblemap.put("b28_10_7", new trsuperobject(28,10,7,"Samiriye, Kralıyla birlikteSu üstündeki çubuk gibi akıp gidecek."));
trsuperobject.biblemap.put("b28_10_8", new trsuperobject(28,10,8,"İsrailin günahı olan Avendeki puta tapılan yerler yok olacak,Sunaklarını dikenler, devedikenleri saracak.O zaman dağlara, ‹‹Bizi örtün!››,Tepelere, ‹‹Üzerimize düşün!›› diyecekler."));
trsuperobject.biblemap.put("b28_10_9", new trsuperobject(28,10,9,"‹‹Ey İsrail, Givada geçirdiğin günlerden beriGünah işledin.Orada direndiniz bana.Kötülere karşı açılan savaşGivada size erişemez mi?"));
trsuperobject.biblemap.put("b28_10_10", new trsuperobject(28,10,10,"İstediğim zaman onları cezalandıracağım,Çifte günahlarına bağlandıkları zaman,Uluslar toplanacak onlara karşı."));
trsuperobject.biblemap.put("b28_10_11", new trsuperobject(28,10,11,"Efrayim eğitilmiş ineğe benzer,Buğday dövmeyi sever.Ama ben boyunduruk takacağım onun güzel boynuna.Koşum vuracağım Efrayimin sırtına,Yahuda çift sürecek,Yakup tırmık çekecek."));
trsuperobject.biblemap.put("b28_10_12", new trsuperobject(28,10,12,"Doğruluk ekin kendiniz için,Sevgi meyveleri biçin.Nadasa bıraktığınız toprağı işleyin;Çünkü RABbe yönelme zamanıdır,Gelip üzerinize doğruluk yağdırıncaya dek."));
trsuperobject.biblemap.put("b28_10_13", new trsuperobject(28,10,13,"Ama siz kötülük ektiniz,Fesat biçtiniz,Yalanın meyvesini yediniz.Çünkü kendi yolunuza,Yiğitlerinizin çokluğuna güvendiniz."));
trsuperobject.biblemap.put("b28_10_14", new trsuperobject(28,10,14,"Bu yüzden halkınızın arasında savaş uğultusu çıkacak,Yıkılacak bütün surlarınız,Şalmanın savaşta Beytarveli yıktığı gibi.Anneler çocuklarıyla birlikte yere çalınıp parçalandı."));
trsuperobject.biblemap.put("b28_10_15", new trsuperobject(28,10,15,"Ey Beytel, sana da aynısı yapılacak,Kötülüğünün büyüklüğü yüzünden.Tan ağarırken İsrail Kralı büsbütün yok olacak."));
trsuperobject.biblemap.put("b28_11_1", new trsuperobject(28,11,1,"‹‹Çocukluğunda sevdim İsraili,Oğlumu Mısırdan çağırdım."));
trsuperobject.biblemap.put("b28_11_2", new trsuperobject(28,11,2,"Peygamberler İsraili çağırdıkça,İsrail uzaklaştı onlardan.Kurban kestiler Baallara,Buhur yaktılar putlara."));
trsuperobject.biblemap.put("b28_11_3", new trsuperobject(28,11,3,"Efrayime yürümeyi ben öğrettim,Kollarıma aldım onları.Ama kendilerine şifa verenin ben olduğumu anlamadılar."));
trsuperobject.biblemap.put("b28_11_4", new trsuperobject(28,11,4,"Onları insancıl iplerle,Sevgi bağlarıyla kendime çektim;Boyunduruklarını kaldıran biri gibi oldum,Eğilip yiyeceklerini verdim."));
trsuperobject.biblemap.put("b28_11_5", new trsuperobject(28,11,5,"‹‹Mısıra dönmeyecekler,Asur kral olacak başlarına,Çünkü bana dönmek istemediler."));
trsuperobject.biblemap.put("b28_11_6", new trsuperobject(28,11,6,"Fırıl fırıl kılıç dönecek kentlerinde,Kapı sürgülerini yok edecek,Tüketecek onları düzenleri yüzünden."));
trsuperobject.biblemap.put("b28_11_7", new trsuperobject(28,11,7,"Halkım benden uzaklaşmaya kararlı.Beni, Yüce Olanı çağırsalar bile,Asla yüceltmeyeceğim onları."));
trsuperobject.biblemap.put("b28_11_8", new trsuperobject(28,11,8,"‹‹Nasıl vazgeçerim senden, ey Efrayim?Nasıl teslim ederim seni, ey İsrail?Admaya yaptığımı nasıl sana yaparım?Seni nasıl Sevoyime çeviririm?Yüreğim değişti içimde,Alevlendi acıma duygularım."));
trsuperobject.biblemap.put("b28_11_9", new trsuperobject(28,11,9,"Kızgın öfkemi başınıza yağdırmayacağım,Efrayimi yeniden yok etmeyeceğim.Çünkü ben insan değil, Tanrıyım,Kutsal Olanım aranızda,Artık öfkeyle üzerinize varmayacağım."));
trsuperobject.biblemap.put("b28_11_10", new trsuperobject(28,11,10,"Aslan gibi kükreyenRABbin ardınca yürüyecekler;O kükreyince titreyerek gelecek çocukları batıdan."));
trsuperobject.biblemap.put("b28_11_11", new trsuperobject(28,11,11,"Mısırdan kuşlar gibi,Asurdan güvercinler gibiTitreyerek gelecekler.Evlerine oturtacağım onları››Diyor RAB."));
trsuperobject.biblemap.put("b28_11_12", new trsuperobject(28,11,12,"Efrayim yalanla,İsrail halkı hileyle çevremi sardı.Yahuda'ysa hâlâ dizginsiz,Tanrı'ya, Kutsal ve Sadık Olan'a karşı."));
trsuperobject.biblemap.put("b28_12_1", new trsuperobject(28,12,1,"Efrayim rüzgarı güdüyor,Doğu rüzgarının ardına düşüyor bütün gün;Yalanı, zorbalığı artıyor.Asurla antlaşma yapıyor,Mısıra zeytinyağı gönderiyor."));
trsuperobject.biblemap.put("b28_12_3", new trsuperobject(28,12,3,"Yakup ana rahminde kardeşinin topuğunu tuttu,Büyüyünce Tanrıyla güreşti."));
trsuperobject.biblemap.put("b28_12_4-5", new trsuperobject(28,12,4-5,"Melekle güreşip yendi,Ağladı, kutsanmak istedi.Tanrıyı Beytelde buldu,RAB, Her Şeye Egemen Tanrı bizimle orada konuştu,O RAB diye anılır."));
trsuperobject.biblemap.put("b28_12_6", new trsuperobject(28,12,6,"Bu yüzden Tanrına dön sen,Sevgiye, adalete sarıl,Sürekli Tanrını bekle."));
trsuperobject.biblemap.put("b28_12_7", new trsuperobject(28,12,7,"Efrayim tüccardır,Hileli terazi kullanır,Aldatmayı sever."));
trsuperobject.biblemap.put("b28_12_8", new trsuperobject(28,12,8,"‹‹Çok zengin oldum›› diye böbürlenir,‹‹Varlığa kavuştum,Çok emek çektim,Günah denecek bir suç bulamayacaklar bende.››"));
trsuperobject.biblemap.put("b28_12_9", new trsuperobject(28,12,9,"‹‹Ama seni Mısırdan çıkaranTanrın RAB benim.Bayram günlerindeki gibi,Seni yine çadırlarda oturtacağım."));
trsuperobject.biblemap.put("b28_12_10", new trsuperobject(28,12,10,"Peygamberlere de söyledim,Çok görümler sağladım,Onlar aracılığıyla örnekler verdim.››"));
trsuperobject.biblemap.put("b28_12_11", new trsuperobject(28,12,11,"Kötülük mü var Gilatta?Gerçekten değersiz bir halk!Gilgalda sığır üstüne sığır kurban ediyorlar,Sunakları sürülmüş tarladaki taş yığınlarını andırıyor."));
trsuperobject.biblemap.put("b28_12_12", new trsuperobject(28,12,12,"Yakup Arama kaçtı,İsrail bir karı için kul oldu,Koyun güttü."));
trsuperobject.biblemap.put("b28_12_13", new trsuperobject(28,12,13,"RAB İsraili bir peygamber aracılığıyla Mısırdan çıkardı,Yine bir peygamber korudu onları."));
trsuperobject.biblemap.put("b28_12_14", new trsuperobject(28,12,14,"Ama Efrayim Tanrı'yı aşırı öfkelendirdi.Rab döktükleri kanın hesabını soracak,Aşağılamalarının karşılığını verecek."));
trsuperobject.biblemap.put("b28_13_1", new trsuperobject(28,13,1,"Efrayim konuştuğunda herkes titrerdi,Yücelmişti İsrailde.Ama Baala taparak suç işleyince öldü."));
trsuperobject.biblemap.put("b28_13_2", new trsuperobject(28,13,2,"Şimdi günah üstüne günah işliyorlar,Gümüşlerinden dökme putlar,Akıllıca tasarlanmış putlar yapıyorlar,Hepsi de usta işi.Bu insanlar hakkında,‹‹İnsan kurban edenlerBuzağıları öpüyor!›› diye konuşuluyor."));
trsuperobject.biblemap.put("b28_13_3", new trsuperobject(28,13,3,"Bu yüzden sabah sisine,Erken uçup giden çiye,Harman yerinden savrulan saman çöpüne,Bacadan tüten dumana dönecekler."));
trsuperobject.biblemap.put("b28_13_4", new trsuperobject(28,13,4,"‹‹Ama seni Mısırdan çıkaranTanrın RAB benim,Benden başka tanrı tanımayacaksın,Çünkü başka kurtarıcı yoktur."));
trsuperobject.biblemap.put("b28_13_5", new trsuperobject(28,13,5,"Ben sana çölde,Kurak topraklarda göz kulak oldum."));
trsuperobject.biblemap.put("b28_13_6", new trsuperobject(28,13,6,"Otlaklara sahip olunca doydular,Doyunca gurura kapıldılar;Bu yüzden unuttular beni."));
trsuperobject.biblemap.put("b28_13_7", new trsuperobject(28,13,7,"Ben de onlara karşı bir aslan gibi olacağım,Bir pars gibi yol kenarında pusuya yatacağım."));
trsuperobject.biblemap.put("b28_13_8", new trsuperobject(28,13,8,"Yavrularından edilmiş dişi ayı gibiKarşılarına çıkacak,Yüreklerinin zarını yırtacağım,Dişi aslan gibi onları oracıkta yiyip bitireceğim,Yabanıl bir hayvan parçalayacak onları."));
trsuperobject.biblemap.put("b28_13_9", new trsuperobject(28,13,9,"‹‹Ey İsrail, bana, yardımcına karşı çıkmanYıkıma uğratıyor seni."));
trsuperobject.biblemap.put("b28_13_10", new trsuperobject(28,13,10,"Nerede seni bütün kentlerindeKurtaracak kralın?Yöneticilerin nerede?Hani, onlar için:‹Bana bir kral ve önderler ver!› demiştin."));
trsuperobject.biblemap.put("b28_13_11", new trsuperobject(28,13,11,"Öfkelendiğimde bir kral verdim sana,Gazaba gelince alıp götürdüm onu."));
trsuperobject.biblemap.put("b28_13_12", new trsuperobject(28,13,12,"Efrayimin suçu birikmiş,Günahı kayda geçmiş."));
trsuperobject.biblemap.put("b28_13_13", new trsuperobject(28,13,13,"Doğum sancıları çeken kadının akılsız oğludur o,Çünkü zamanı geldiğinde,Açık rahimden çıkmıyor."));
trsuperobject.biblemap.put("b28_13_14", new trsuperobject(28,13,14,"‹‹Onları fidyeyle kurtaracağımÖlüler diyarının elinden,Ölümden fidyeyle kurtaracağım.Felaketin nerede, ey ölüm?Yıkıcılığın nerede, ey ölüler diyarı?Hiç pişmanlık duymayacağım."));
trsuperobject.biblemap.put("b28_13_15", new trsuperobject(28,13,15,"‹‹Kardeşleri arasında serpilip gelişse de,Doğu rüzgarı, çölden esen RABbin soluğu üzerine gelecek,Onun kaynağı kuruyacak,Pınarı kesilecek,Değerli eşyalarının hazinesi yağmalanacak."));
trsuperobject.biblemap.put("b28_13_16", new trsuperobject(28,13,16,"Samiriye halkı suçunun cezasını çekecek,Çünkü Tanrısı'na başkaldırdı.Kılıçla yıkılacaklar,Yere çalınıp parçalanacak yavruları,Gebe kadınlarının karnı yarılacak.››"));
trsuperobject.biblemap.put("b28_14_1", new trsuperobject(28,14,1,"Tanrın RABbe dön, ey İsrail,Çünkü suçlarından ötürü tökezledin."));
trsuperobject.biblemap.put("b28_14_2", new trsuperobject(28,14,2,"Dualarla gidin, RABbe dönün,Ona, ‹‹Bağışla bütün suçlarımızı›› deyin,‹‹Lütfet, kabul et bizi,Öyle ki, dudaklarımızın kurbanını sunalım."));
trsuperobject.biblemap.put("b28_14_3", new trsuperobject(28,14,3,"Asur kurtaramaz bizi,Savaş atlarına binmeyeceğiz.Artık ellerimizle yaptığımıza‹Tanrımız› demeyeceğiz,Çünkü öksüz sende merhamet bulur.››"));
trsuperobject.biblemap.put("b28_14_4", new trsuperobject(28,14,4,"‹‹Onların dönekliğini düzelteceğim,Gönülden seveceğim onları,Çünkü onlara karşı öfkem dindi."));
trsuperobject.biblemap.put("b28_14_5", new trsuperobject(28,14,5,"Çiy gibi olacağım İsraile;Zambak gibi çiçek açacak,Lübnan sediri gibi kök salacaklar."));
trsuperobject.biblemap.put("b28_14_6", new trsuperobject(28,14,6,"Dallanıp budaklanacaklar,Görkemleri zeytin ağacını,Kokuları Lübnan sedirini andıracak."));
trsuperobject.biblemap.put("b28_14_7", new trsuperobject(28,14,7,"Yine insanlar oturacak gölgesinde;Buğday gibi gelişecek,Asma gibi serpilecekler;Lübnan şarabı kadar ün kazanacaklar."));
trsuperobject.biblemap.put("b28_14_8", new trsuperobject(28,14,8,"Ey Efrayim, artık ne işim var putlarla?Yanıtlayacak, seninle ilgileneceğim.Yeşil çam gibiyim ben,Senin verimliliğin benden kaynaklanıyor.››"));
trsuperobject.biblemap.put("b28_14_9", new trsuperobject(28,14,9,"Bilge kişi kavrasın bunları,Anlayan anlasın.Çünkü RAB'bin yolları adildir;Bu yollarda yürür doğrular,Ama başkaldıranlar bu yollarda sendeler."));

}

}