package tr.bible;

public class trbible46 {

public trbible46() {

putmapbible46();

}

private void putmapbible46() {

trsuperobject.biblemap.put("b46_1_1-3", new trsuperobject(46,1,1-3,"Tanrının isteğiyle Mesih İsanın elçisi olmaya çağrılan ben Pavlus ve kardeşimiz Sostenisten Tanrının Korintteki kilisesine selam! Mesih İsada kutsal kılınmış, kutsal olmaya çağrılmış olan sizlere ve hepimizin Rabbi İsa Mesihin adını her yerde anan herkese Babamız Tanrıdan ve Rab İsa Mesihten lütuf ve esenlik olsun."));
trsuperobject.biblemap.put("b46_1_4", new trsuperobject(46,1,4,"Tanrının Mesih İsada size bağışladığı lütuftan ötürü sizin için her zaman Tanrıma şükrediyorum."));
trsuperobject.biblemap.put("b46_1_5-6", new trsuperobject(46,1,5-6,"Mesihle ilgili tanıklığımız sizde pekiştiği gibi Mesihte her bakımdan -her tür söz ve bilgi bakımından- zenginleştiniz."));
trsuperobject.biblemap.put("b46_1_7", new trsuperobject(46,1,7,"Şöyle ki, Rabbimiz İsa Mesihin görünmesini beklerken hiçbir ruhsal armağandan yoksun değilsiniz."));
trsuperobject.biblemap.put("b46_1_8", new trsuperobject(46,1,8,"Rabbimiz İsa Mesih kendi gününde kusursuz olmanız için sizi sonuna dek pekiştirecektir."));
trsuperobject.biblemap.put("b46_1_9", new trsuperobject(46,1,9,"Sizleri Oğlu Rabbimiz İsa Mesihle paydaşlığa çağıran Tanrı güvenilirdir."));
trsuperobject.biblemap.put("b46_1_10", new trsuperobject(46,1,10,"Kardeşler, Rabbimiz İsa Mesihin adıyla yalvarıyorum: Hepiniz uyum içinde olun, aranızda bölünmeler olmadan aynı düşünce ve görüşte birleşin."));
trsuperobject.biblemap.put("b46_1_11", new trsuperobject(46,1,11,"Kardeşlerim, Kloinin ev halkından aranızda çekişmeler olduğunu öğrendim."));
trsuperobject.biblemap.put("b46_1_12", new trsuperobject(46,1,12,"Şunu demek istiyorum: Her biriniz, ‹‹Ben Pavlus yanlısıyım››, ‹‹Ben Apollos yanlısıyım››, ‹‹Ben Kefas yanlısıyım›› ya da ‹‹Ben Mesih yanlısıyım›› diyormuş."));
trsuperobject.biblemap.put("b46_1_13", new trsuperobject(46,1,13,"Mesih bölündü mü? Sizin için çarmıha gerilen Pavlus muydu? Pavlusun adıyla mı vaftiz edildiniz?"));
trsuperobject.biblemap.put("b46_1_14-15", new trsuperobject(46,1,14-15,"Hiç kimse benim adımla vaftiz edildiğinizi söylemesin diye Krispusla Gayustan başka hiçbirinizi vaftiz etmediğim için Tanrıya şükrediyorum."));
trsuperobject.biblemap.put("b46_1_16", new trsuperobject(46,1,16,"Evet, bir de İstefanasın ev halkını vaftiz ettim; bunun dışında kimseyi vaftiz ettiğimi anımsamıyorum."));
trsuperobject.biblemap.put("b46_1_17", new trsuperobject(46,1,17,"Çünkü Mesih beni vaftiz etmeye değil, Mesihin çarmıhtaki ölümü boşa gitmesin diye, bilgece sözlere dayanmaksızın Müjdeyi yaymaya gönderdi."));
trsuperobject.biblemap.put("b46_1_18", new trsuperobject(46,1,18,"Çarmıhla ilgili bildiri mahva gidenler için saçmalık, biz kurtulmakta olanlar içinse Tanrı gücüdür."));
trsuperobject.biblemap.put("b46_1_19", new trsuperobject(46,1,19,"Nitekim şöyle yazılmıştır:  ‹‹Bilgelerin bilgeliğini yok edeceğim,  Akıllıların aklını boşa çıkaracağım.››"));
trsuperobject.biblemap.put("b46_1_20", new trsuperobject(46,1,20,"Hani nerede bilge kişi? Din bilgini nerede? Nerede bu çağın hünerli tartışmacısı? Tanrı dünya bilgeliğinin saçma olduğunu göstermedi mi?"));
trsuperobject.biblemap.put("b46_1_21", new trsuperobject(46,1,21,"Mademki dünya Tanrının bilgeliği uyarınca Tanrıyı kendi bilgeliğiyle tanımadı, Tanrı iman edenleri saçma sayılan bildiriyle kurtarmaya razı oldu."));
trsuperobject.biblemap.put("b46_1_22", new trsuperobject(46,1,22,"Yahudiler doğaüstü belirtiler ister, Greklerse bilgelik arar."));
trsuperobject.biblemap.put("b46_1_23", new trsuperobject(46,1,23,"Ama biz çarmıha gerilmiş Mesihi duyuruyoruz. Yahudiler bunu yüzkarası, öteki uluslar da saçmalık sayarlar."));
trsuperobject.biblemap.put("b46_1_24", new trsuperobject(46,1,24,"Oysa Mesih, çağrılmış olanlar için -ister Yahudi ister Grek olsun- Tanrının gücü ve Tanrının bilgeliğidir."));
trsuperobject.biblemap.put("b46_1_25", new trsuperobject(46,1,25,"Çünkü Tanrının ‹‹saçmalığı›› insan bilgeliğinden daha üstün, Tanrının ‹‹zayıflığı›› insan gücünden daha güçlüdür."));
trsuperobject.biblemap.put("b46_1_26", new trsuperobject(46,1,26,"Kardeşlerim, aldığınız çağrıyı düşünün. Birçoğunuz insan ölçülerine göre bilge, güçlü ya da soylu kişiler değildiniz."));
trsuperobject.biblemap.put("b46_1_27", new trsuperobject(46,1,27,"Ne var ki, Tanrı bilgeleri utandırmak için dünyanın saçma saydıklarını, güçlüleri utandırmak için de dünyanın zayıf saydıklarını seçti."));
trsuperobject.biblemap.put("b46_1_28", new trsuperobject(46,1,28,"Dünyanın önemli gördüklerini hiçe indirmek için dünyanın önemsiz, soysuz, değersiz gördüklerini seçti."));
trsuperobject.biblemap.put("b46_1_29", new trsuperobject(46,1,29,"Öyle ki, Tanrının önünde hiç kimse övünemesin."));
trsuperobject.biblemap.put("b46_1_30", new trsuperobject(46,1,30,"Ama siz Tanrı sayesinde Mesih İsadasınız. O bizim için tanrısal bilgelik, doğruluk, kutsallık ve kurtuluş oldu."));
trsuperobject.biblemap.put("b46_1_31", new trsuperobject(46,1,31,"Bunun için yazılmış olduğu gibi, ‹‹Övünen, Rab'le övünsün.››"));
trsuperobject.biblemap.put("b46_2_1", new trsuperobject(46,2,1,"Kardeşler, Tanrıyla ilgili bildiriyi duyurmak için size geldiğimde, söz ustalığıyla ya da üstün bilgelikle gelmedim."));
trsuperobject.biblemap.put("b46_2_2", new trsuperobject(46,2,2,"Aranızdayken, İsa Mesihten ve Onun çarmıha gerilişinden başka hiçbir şey bilmemeye kararlıydım."));
trsuperobject.biblemap.put("b46_2_3", new trsuperobject(46,2,3,"Size zayıflık ve korku içinde geldim, tir tir titriyordum!"));
trsuperobject.biblemap.put("b46_2_4", new trsuperobject(46,2,4,"Sözüm ve bildirim, insan bilgeliğinin ikna edici sözlerine değil, Ruhun kanıtlayıcı gücüne dayanıyordu."));
trsuperobject.biblemap.put("b46_2_5", new trsuperobject(46,2,5,"Öyle ki, imanınız insan bilgeliğine değil, Tanrı gücüne dayansın."));
trsuperobject.biblemap.put("b46_2_6", new trsuperobject(46,2,6,"Gerçi olgun kişiler arasında bilgece sözler söylüyoruz; ama bu bilgelik ne şimdiki çağın, ne de bu çağın gelip geçici önderlerinin bilgeliğidir."));
trsuperobject.biblemap.put("b46_2_7-8", new trsuperobject(46,2,7-8,"Tanrının saklı bilgeliğinden gizemli biçimde söz ediyoruz. Zamanın başlangıcından önce Tanrının bizim yüceliğimiz için belirlediği bu bilgeliği bu çağın önderlerinden hiçbiri anlamadı. Anlasalardı yüce Rabbi çarmıha germezlerdi."));
trsuperobject.biblemap.put("b46_2_9", new trsuperobject(46,2,9,"Yazılmış olduğu gibi,  ‹‹Tanrının kendisini sevenler için hazırladıklarını  Hiçbir göz görmedi,  Hiçbir kulak duymadı,  Hiçbir insan yüreği kavramadı.››"));
trsuperobject.biblemap.put("b46_2_10", new trsuperobject(46,2,10,"Oysa Tanrı Ruh aracılığıyla bunları bize açıkladı. Çünkü Ruh her şeyi, Tanrının derin düşüncelerini bile araştırır."));
trsuperobject.biblemap.put("b46_2_11", new trsuperobject(46,2,11,"İnsanın düşüncelerini, insanın içindeki ruhundan başka kim bilebilir? Bunun gibi, Tanrının düşüncelerini de Tanrının Ruhundan başkası bilemez."));
trsuperobject.biblemap.put("b46_2_12", new trsuperobject(46,2,12,"Tanrının bize lütfettiklerini bilelim diye, bu dünyanın ruhunu değil, Tanrıdan gelen Ruhu aldık."));
trsuperobject.biblemap.put("b46_2_13", new trsuperobject(46,2,13,"Ruhsal kişilere ruhsal gerçekleri açıklarken, Tanrının lütfettiklerini insan bilgeliğinin öğrettiği sözlerle değil, Ruhun öğrettiği sözlerle bildiririz."));
trsuperobject.biblemap.put("b46_2_14", new trsuperobject(46,2,14,"Doğal kişi, Tanrının Ruhuyla ilgili gerçekleri kabul etmez. Çünkü bunlar ona saçma gelir, ruhça değerlendirildikleri için bunları anlayamaz."));
trsuperobject.biblemap.put("b46_2_15", new trsuperobject(46,2,15,"Ruhsal kişi her konuda yargı yürütebilir, ama kimse onun hakkında yargı yürütemez."));
trsuperobject.biblemap.put("b46_2_16", new trsuperobject(46,2,16,"‹‹Rab'bin düşüncesini kim bildi ki,  O'na öğüt verebilsin?›› Oysa biz Mesih'in düşüncesine sahibiz."));
trsuperobject.biblemap.put("b46_3_1", new trsuperobject(46,3,1,"Kardeşler, ben sizinle ruhsal kişilerle konuşur gibi konuşamadım. Benliğe uyanlarla, Mesihte henüz bebeklik çağında olanlarla konuşur gibi konuştum."));
trsuperobject.biblemap.put("b46_3_2", new trsuperobject(46,3,2,"Size süt verdim, katı yiyecek değil. Çünkü katı yiyeceği henüz yiyemiyordunuz. Şimdi bile yiyemezsiniz."));
trsuperobject.biblemap.put("b46_3_3", new trsuperobject(46,3,3,"Çünkü hâlâ benliğe uyuyorsunuz. Aranızda kıskançlık ve çekişme olması, benliğe uyduğunuzu, öbür insanlar gibi yaşadığınızı göstermiyor mu?"));
trsuperobject.biblemap.put("b46_3_4", new trsuperobject(46,3,4,"Biriniz, ‹‹Ben Pavlus yanlısıyım››, ötekiniz, ‹‹Ben Apollos yanlısıyım›› diyorsa, öbür insanlardan ne farkınız kalır?"));
trsuperobject.biblemap.put("b46_3_5", new trsuperobject(46,3,5,"Apollos kim, Pavlus kim? İman etmenize aracı olmuş hizmetkârlardır. Rab her birimize bir görev vermiştir."));
trsuperobject.biblemap.put("b46_3_6", new trsuperobject(46,3,6,"Tohumu ben ektim, Apollos suladı. Ama Tanrı büyüttü."));
trsuperobject.biblemap.put("b46_3_7", new trsuperobject(46,3,7,"Önemli olan, eken ya da sulayan değil, ekileni büyüten Tanrıdır."));
trsuperobject.biblemap.put("b46_3_8", new trsuperobject(46,3,8,"Ekenle sulayanın değeri birdir. Her biri kendi emeğinin karşılığını alacaktır."));
trsuperobject.biblemap.put("b46_3_9", new trsuperobject(46,3,9,"Biz Tanrının emektaşlarıyız. Sizler de Tanrının tarlası, Tanrının binasısınız."));
trsuperobject.biblemap.put("b46_3_10", new trsuperobject(46,3,10,"Tanrının bana lütfettiği görev uyarınca bilge bir mimar gibi temel attım, başkaları da bu temel üzerine inşa ediyor. Herkes nasıl inşa ettiğine dikkat etsin."));
trsuperobject.biblemap.put("b46_3_11", new trsuperobject(46,3,11,"Çünkü hiç kimse atılan temelden, yani İsa Mesihten başka bir temel atamaz."));
trsuperobject.biblemap.put("b46_3_12", new trsuperobject(46,3,12,"Bu temel üzerine kimi altın, gümüş ya da değerli taşlarla, kimi de tahta, ot ya da kamışla inşa edecek."));
trsuperobject.biblemap.put("b46_3_13", new trsuperobject(46,3,13,"Herkesin yaptığı iş belli olacak, yargı günü ortaya çıkacak. Herkesin işi ateşle açığa vurulacak. Ateş her işin niteliğini sınayacak."));
trsuperobject.biblemap.put("b46_3_14", new trsuperobject(46,3,14,"Bir kimsenin inşa ettikleri ateşe dayanırsa, o kimse ödülünü alacak."));
trsuperobject.biblemap.put("b46_3_15", new trsuperobject(46,3,15,"Yaptıkları yanarsa, zarar edecek. Kendisi kurtulacak, ama ateşten geçmiş gibi olacaktır."));
trsuperobject.biblemap.put("b46_3_16", new trsuperobject(46,3,16,"Tanrının tapınağı olduğunuzu, Tanrının Ruhunun sizde yaşadığını bilmiyor musunuz?"));
trsuperobject.biblemap.put("b46_3_17", new trsuperobject(46,3,17,"Kim Tanrının tapınağını yıkarsa, Tanrı da onu yıkacak. Çünkü Tanrının tapınağı kutsaldır ve o tapınak sizsiniz."));
trsuperobject.biblemap.put("b46_3_18", new trsuperobject(46,3,18,"Kimse kendini aldatmasın. Aranızdan biri bu çağın ölçülerine göre kendini bilge sanıyorsa, bilge olmak için ‹‹akılsız›› olsun!"));
trsuperobject.biblemap.put("b46_3_19", new trsuperobject(46,3,19,"Çünkü bu dünyanın bilgeliği Tanrının gözünde akılsızlıktır. Yazılmış olduğu gibi, ‹‹O, bilgeleri kurnazlıklarında yakalar.››"));
trsuperobject.biblemap.put("b46_3_20", new trsuperobject(46,3,20,"Yine, ‹‹Rab bilgelerin düşüncelerinin boş olduğunu bilir›› diye yazılmıştır."));
trsuperobject.biblemap.put("b46_3_21", new trsuperobject(46,3,21,"Bu nedenle hiç kimse insanlarla övünmesin. Çünkü her şey sizindir."));
trsuperobject.biblemap.put("b46_3_22", new trsuperobject(46,3,22,"Pavlus, Apollos, Kefas, dünya, yaşam ve ölüm, şimdiki ve gelecek zaman, her şey sizindir."));
trsuperobject.biblemap.put("b46_3_23", new trsuperobject(46,3,23,"Siz Mesih'insiniz, Mesih de Tanrı'nındır."));
trsuperobject.biblemap.put("b46_4_1", new trsuperobject(46,4,1,"Böylece insanlar bizi Mesihin hizmetkârları ve Tanrının sırlarının kâhyaları saysın."));
trsuperobject.biblemap.put("b46_4_2", new trsuperobject(46,4,2,"Kâhyada aranan başlıca nitelik güvenilir olmasıdır."));
trsuperobject.biblemap.put("b46_4_3", new trsuperobject(46,4,3,"Sizin tarafınızdan ya da olağan bir mahkeme tarafından yargılanırsam hiç aldırmam. Kendi kendimi de yargılamıyorum."));
trsuperobject.biblemap.put("b46_4_4", new trsuperobject(46,4,4,"Kendimde bir kusur görmüyorum. Ama bu beni aklamaz. Beni yargılayan Rabdir."));
trsuperobject.biblemap.put("b46_4_5", new trsuperobject(46,4,5,"Bu nedenle, belirlenen zamandan önce hiçbir şeyi yargılamayın. Rabbin gelişini bekleyin. O, karanlığın gizlediklerini aydınlığa çıkaracak, yüreklerdeki amaçları açığa vuracaktır. O zaman herkes Tanrıdan payına düşen övgüyü alacaktır."));
trsuperobject.biblemap.put("b46_4_6", new trsuperobject(46,4,6,"Kardeşler, bizden örnek alarak, ‹‹Yazılmış olanın dışına çıkmayın›› sözünün anlamını öğrenmeniz için bu ilkeleri sizin yararınıza kendime ve Apollosa uyguladım. Öyle ki, hiç kimse biriyle övünüp bir başkasını hor görmesin."));
trsuperobject.biblemap.put("b46_4_7", new trsuperobject(46,4,7,"Seni başkasından üstün kılan kim? Tanrıdan almadığın neyin var ki? Madem aldın, niçin almamış gibi övünüyorsun?"));
trsuperobject.biblemap.put("b46_4_8", new trsuperobject(46,4,8,"Zaten tok ve zenginsiniz! Biz olmadan krallar olmuşsunuz! Keşke gerçekten krallar olsaydınız da, biz de sizinle birlikte krallık etseydik!"));
trsuperobject.biblemap.put("b46_4_9", new trsuperobject(46,4,9,"Kanımca Tanrı biz elçileri, en geriden gelen ölüm hükümlüleri gibi gözler önüne serdi. Hem melekler hem insanlar için, bütün evren için seyirlik oyun olduk."));
trsuperobject.biblemap.put("b46_4_10", new trsuperobject(46,4,10,"Biz Mesih uğruna akılsızız, ama siz Mesihte akıllısınız! Biz zayıfız, siz güçlüsünüz! Siz saygıdeğer kişilersiniz, bizse değersiziz!"));
trsuperobject.biblemap.put("b46_4_11", new trsuperobject(46,4,11,"Şu ana dek aç, susuz, çıplağız. Dövülüyoruz, barınacak yerimiz yok."));
trsuperobject.biblemap.put("b46_4_12", new trsuperobject(46,4,12,"Kendi ellerimizle çalışıp emek veriyoruz. Bize sövenlere iyilik diliyoruz, zulmedilince sabrediyoruz."));
trsuperobject.biblemap.put("b46_4_13", new trsuperobject(46,4,13,"İftiraya uğrayınca tatlılıkla karşılık veriyoruz. Şu ana dek adeta dünyanın süprüntüsü, her şeyin döküntüsü olduk."));
trsuperobject.biblemap.put("b46_4_14", new trsuperobject(46,4,14,"Bunları sizi utandırmak için değil, siz sevgili çocuklarımı uyarmak için yazıyorum."));
trsuperobject.biblemap.put("b46_4_15", new trsuperobject(46,4,15,"Çünkü Mesihin yolunda sayısız eğiticiniz olsa da çok sayıda babanız yoktur. Size Müjdeyi ulaştırmakla Mesih İsada manevi babanız oldum."));
trsuperobject.biblemap.put("b46_4_16", new trsuperobject(46,4,16,"Bu nedenle beni örnek almaya çağırıyorum sizi."));
trsuperobject.biblemap.put("b46_4_17", new trsuperobject(46,4,17,"Rabbe sadık olan sevgili çocuğum Timoteosu bu amaçla size gönderiyorum. Her yerde, her kilisede öğrettiğim ve Mesihte izlediğim yolları o size anımsatacaktır."));
trsuperobject.biblemap.put("b46_4_18", new trsuperobject(46,4,18,"Bazılarınız yanınıza gelmeyeceğimi sanarak küstahlaşıyor."));
trsuperobject.biblemap.put("b46_4_19", new trsuperobject(46,4,19,"Ama Rab dilerse yakında yanınıza geleceğim. O zaman bu küstahların söylediklerini değil, güçlerinin ne olduğunu öğreneceğim."));
trsuperobject.biblemap.put("b46_4_20", new trsuperobject(46,4,20,"Çünkü Tanrının Egemenliği lafta değil, güçtedir."));
trsuperobject.biblemap.put("b46_4_21", new trsuperobject(46,4,21,"Ne istiyorsunuz? Size sopayla mı geleyim, yoksa sevgi ve yumuşak bir ruhla mı?"));
trsuperobject.biblemap.put("b46_5_1", new trsuperobject(46,5,1,"Aranızda fuhuş olduğu söyleniyor, üstelik putperestler arasında bile rastlanmayan türden bir fuhuş! Biri babasının karısını almış."));
trsuperobject.biblemap.put("b46_5_2", new trsuperobject(46,5,2,"Siz hâlâ böbürleniyorsunuz! Oysa yas tutup bu işi yapanı aranızdan atmanız gerekmez miydi?"));
trsuperobject.biblemap.put("b46_5_3-5", new trsuperobject(46,5,3-5,"Bedence olmasa da ruhça aranızdayım. Bu suçu işleyeni, aranızdaymışım gibi Rabbimiz İsanın adıyla zaten yargılamış bulunuyorum. Ben ruhça aranızdayken Rabbimiz İsanın gücüyle toplandığınız zaman, bedeninin yok olması için bu adamı Şeytana teslim edin ki, Rab İsanın gününde ruhu kurtulabilsin."));
trsuperobject.biblemap.put("b46_5_6", new trsuperobject(46,5,6,"Övünmeniz yersizdir. Azıcık mayanın bütün hamuru kabarttığını bilmiyor musunuz?"));
trsuperobject.biblemap.put("b46_5_7", new trsuperobject(46,5,7,"Yeni bir hamur olabilmek için eski mayadan arınıp temizlenin. Zaten mayasızsınız. Çünkü Fısıh kuzumuz Mesih kurban edildi."));
trsuperobject.biblemap.put("b46_5_8", new trsuperobject(46,5,8,"Bunun için eski mayayla -kin ve kötülük mayasıyla- değil, içtenliğin ve dürüstlüğün mayasız ekmeğiyle bayram edelim."));
trsuperobject.biblemap.put("b46_5_9", new trsuperobject(46,5,9,"Mektubumda size fuhuş yapanlarla arkadaşlık etmemenizi yazdım."));
trsuperobject.biblemap.put("b46_5_10", new trsuperobject(46,5,10,"Kuşkusuz dünyadaki ahlaksızları, açgözlüleri, soyguncuları ya da putperestleri demek istemedim. Öyle olsaydı, dünyadan ayrılmak zorunda kalırdınız!"));
trsuperobject.biblemap.put("b46_5_11", new trsuperobject(46,5,11,"Ama şimdi size şunu yazıyorum: Kardeş diye bilinirken fuhuş yapan, açgözlü, putperest, sövücü, ayyaş ya da soyguncu olanla arkadaşlık etmeyin, böyle biriyle yemek bile yemeyin."));
trsuperobject.biblemap.put("b46_5_12", new trsuperobject(46,5,12,"İnanlılar topluluğunun dışındakileri yargılamaya benim ne hakkım var? Sizin de yargılamanız gereken kişiler topluluğun içindekiler değil mi?"));
trsuperobject.biblemap.put("b46_5_13", new trsuperobject(46,5,13,"Topluluğun dışında kalanları Tanrı yargılar. ‹‹Kötü adamı aranızdan kovun!››"));
trsuperobject.biblemap.put("b46_6_1", new trsuperobject(46,6,1,"Sizden birinin öbürüne karşı bir davası varsa kutsallar önünde değil de, imansızlar önünde yargılanmaya cesaret eder mi?"));
trsuperobject.biblemap.put("b46_6_2", new trsuperobject(46,6,2,"Kutsalların dünyayı yargılayacağını bilmiyor musunuz? Madem dünyayı yargılayacaksınız, böyle önemsiz davaları görmeye yeterli değil misiniz?"));
trsuperobject.biblemap.put("b46_6_3", new trsuperobject(46,6,3,"Bu yaşamla ilgili davalar bir yana, melekleri bile yargılayacağımızı bilmiyor musunuz?"));
trsuperobject.biblemap.put("b46_6_4", new trsuperobject(46,6,4,"Bu yaşamla ilgili davalarınız olduğunda, inanlılar topluluğunda en önemsiz sayılanları mı yargıç atıyorsunuz?"));
trsuperobject.biblemap.put("b46_6_5", new trsuperobject(46,6,5,"Sizi utandırmak için söylüyorum bunu. Kardeşler arasındaki davalarda yargıçlık edecek kadar bilge biri yok mu aranızda?"));
trsuperobject.biblemap.put("b46_6_6", new trsuperobject(46,6,6,"Kardeş kardeşe karşı dava açıyor, üstelik imansızlar önünde!"));
trsuperobject.biblemap.put("b46_6_7", new trsuperobject(46,6,7,"Aslında birbirinizden davacı olmanız bile sizin için düpedüz yenilgidir. Haksızlığa uğrasanız daha iyi olmaz mı? Dolandırılsanız daha iyi olmaz mı?"));
trsuperobject.biblemap.put("b46_6_8", new trsuperobject(46,6,8,"Bunun yerine, siz kendiniz haksızlık edip başkasını dolandırıyorsunuz. Üstelik bunu kardeşlerinize yapıyorsunuz."));
trsuperobject.biblemap.put("b46_6_9-10", new trsuperobject(46,6,9-10,"Günahkârların, Tanrı Egemenliğini miras almayacağını bilmiyor musunuz? Aldanmayın! Ne fuhuş yapanlar Tanrının Egemenliğini miras alacaktır, ne puta tapanlar, ne zina edenler, ne oğlanlar, ne oğlancılar, ne hırsızlar, ne açgözlüler, ne ayyaşlar, ne sövücüler, ne de soyguncular."));
trsuperobject.biblemap.put("b46_6_11", new trsuperobject(46,6,11,"Bazılarınız böyleydiniz; ama yıkandınız, kutsal kılındınız, Rab İsa Mesih adıyla ve Tanrımızın Ruhu aracılığıyla aklandınız."));
trsuperobject.biblemap.put("b46_6_12", new trsuperobject(46,6,12,"‹‹Bana her şey serbest›› diyorsunuz, ama her şey yararlı değildir. ‹‹Bana her şey serbest›› diyorsunuz, ama hiçbir şeyin tutsağı olmayacağım."));
trsuperobject.biblemap.put("b46_6_13", new trsuperobject(46,6,13,"‹‹Yemek mide için, mide de yemek içindir›› diyorsunuz, ama Tanrı hem mideyi hem de yemeği ortadan kaldıracaktır. Beden fuhuş için değil, Rab içindir. Rab de beden içindir."));
trsuperobject.biblemap.put("b46_6_14", new trsuperobject(46,6,14,"Rabbi dirilten Tanrı, kudretiyle bizi de diriltecek."));
trsuperobject.biblemap.put("b46_6_15", new trsuperobject(46,6,15,"Bedenlerinizin Mesihin üyeleri olduğunu bilmiyor musunuz? Mesihin üyelerini alıp bir fahişenin üyeleri mi yapayım? Asla!"));
trsuperobject.biblemap.put("b46_6_16", new trsuperobject(46,6,16,"Yoksa fahişeyle birleşenin, onunla tek beden olduğunu bilmiyor musunuz? Çünkü ‹‹İkisi tek beden olacak›› deniyor."));
trsuperobject.biblemap.put("b46_6_17", new trsuperobject(46,6,17,"Rable birleşen kişiyse Onunla tek ruh olur."));
trsuperobject.biblemap.put("b46_6_18", new trsuperobject(46,6,18,"Fuhuştan kaçının. İnsanın işlediği bütün öbür günahlar bedenin dışındadır; ama fuhuş yapan, kendi bedenine karşı günah işler."));
trsuperobject.biblemap.put("b46_6_19", new trsuperobject(46,6,19,"Bedeninizin, Tanrıdan aldığınız ve içinizdeki Kutsal Ruhun tapınağı olduğunu bilmiyor musunuz? Kendinize ait değilsiniz."));
trsuperobject.biblemap.put("b46_6_20", new trsuperobject(46,6,20,"Bir bedel karşılığı satın alındınız; onun için Tanrı'yı bedeninizde yüceltin."));
trsuperobject.biblemap.put("b46_7_1", new trsuperobject(46,7,1,"Şimdi bana yazdığınız konulara gelelim: ‹‹Erkeğin kadına dokunmaması iyidir›› diyorsunuz."));
trsuperobject.biblemap.put("b46_7_2", new trsuperobject(46,7,2,"Ama fuhuştan ötürü her erkek karısıyla, her kadın da kocasıyla yaşasın."));
trsuperobject.biblemap.put("b46_7_3", new trsuperobject(46,7,3,"Erkek karısına, kadın da kocasına hakkını versin."));
trsuperobject.biblemap.put("b46_7_4", new trsuperobject(46,7,4,"Kadının bedeni kendisine değil, kocasına aittir. Bunun gibi, erkeğin bedeni de kendisine değil, karısına aittir."));
trsuperobject.biblemap.put("b46_7_5", new trsuperobject(46,7,5,"Geçici bir süre için anlaşıp kendinizi duaya vermekten başka bir nedenle birbirinizi mahrum etmeyin. Sonra yine birleşin ki, kendinizi denetleyemediğiniz için Şeytan sizi ayartmasın."));
trsuperobject.biblemap.put("b46_7_6", new trsuperobject(46,7,6,"Bunu bir buyruk olarak değil, bir uzlaşma yolu olarak söylüyorum."));
trsuperobject.biblemap.put("b46_7_7", new trsuperobject(46,7,7,"Herkesin benim gibi olmasını dilerdim. Ama herkesin Tanrıdan aldığı ruhsal bir armağanı vardır; kiminin şöyle, kiminin böyle."));
trsuperobject.biblemap.put("b46_7_8", new trsuperobject(46,7,8,"Yine de evli olmayanlarla dul kadınlara şunu söyleyeyim: Benim gibi kalsalar kendileri için iyi olur."));
trsuperobject.biblemap.put("b46_7_9", new trsuperobject(46,7,9,"Ama kendilerini denetleyemiyorlarsa, evlensinler. Çünkü için için yanmaktansa evlenmek daha iyidir."));
trsuperobject.biblemap.put("b46_7_10", new trsuperobject(46,7,10,"Evlilereyse şunu buyuruyorum, daha doğrusu Rab buyuruyor: Kadın kocasından ayrılmasın."));
trsuperobject.biblemap.put("b46_7_11", new trsuperobject(46,7,11,"Ayrılırsa evlenmesin, ya da kocasıyla barışsın. Erkek de karısını boşamasın."));
trsuperobject.biblemap.put("b46_7_12", new trsuperobject(46,7,12,"Geri kalanlara Rab değil, ben söylüyorum: Eğer bir kardeşin karısı iman etmemişse ama kendisiyle yaşamaya razıysa, onu boşamasın."));
trsuperobject.biblemap.put("b46_7_13", new trsuperobject(46,7,13,"Bir kadının kocası iman etmemişse ama kendisiyle yaşamaya razıysa, kadın onu boşamasın."));
trsuperobject.biblemap.put("b46_7_14", new trsuperobject(46,7,14,"Çünkü iman etmemiş koca karısı aracılığıyla, iman etmemiş kadın da imanlı kocası aracılığıyla kutsanır. Yoksa çocuklarınız murdar olurdu. Ama şimdi kutsaldırlar."));
trsuperobject.biblemap.put("b46_7_15", new trsuperobject(46,7,15,"İman etmeyen ayrılırsa ayrılsın. Kardeş ya da kızkardeş böyle durumlarda özgürdür. Tanrı sizi barış içinde yaşamaya çağırdı."));
trsuperobject.biblemap.put("b46_7_16", new trsuperobject(46,7,16,"Ey kadın, kocanı kurtarıp kurtaramayacağını nereden biliyorsun? Ey erkek, karını kurtarıp kurtaramayacağını nereden biliyorsun?"));
trsuperobject.biblemap.put("b46_7_17", new trsuperobject(46,7,17,"Ancak herkes Rabbin kendisi için belirlediği duruma uygun biçimde, Tanrıdan aldığı çağrıya göre yaşasın. Bunu bütün kiliselere buyuruyorum."));
trsuperobject.biblemap.put("b46_7_18", new trsuperobject(46,7,18,"Biri sünnetliyken mi çağrıldı, sünnetsiz olmasın. Bir başkası sünnetsizken mi çağrıldı, sünnet olmasın."));
trsuperobject.biblemap.put("b46_7_19", new trsuperobject(46,7,19,"Sünnetli olup olmamak önemli değildir. Önemli olan, Tanrının buyruklarını yerine getirmektir."));
trsuperobject.biblemap.put("b46_7_20", new trsuperobject(46,7,20,"Herkes ne durumda çağrıldıysa, o durumda kalsın."));
trsuperobject.biblemap.put("b46_7_21", new trsuperobject(46,7,21,"Köleyken mi çağrıldın, üzülme. Ama özgür olabilirsen, fırsatı kaçırma!"));
trsuperobject.biblemap.put("b46_7_22", new trsuperobject(46,7,22,"Çünkü Rabbin çağrısını aldığı zaman köle olan kimse, şimdi Rabbin özgürüdür. Özgürken çağrılan kişi de Mesihin kölesidir."));
trsuperobject.biblemap.put("b46_7_23", new trsuperobject(46,7,23,"Bir bedel karşılığı satın alındınız, insanlara köle olmayın."));
trsuperobject.biblemap.put("b46_7_24", new trsuperobject(46,7,24,"Kardeşler, herkes ne durumda çağrıldıysa, Tanrı önünde o durumda kalsın."));
trsuperobject.biblemap.put("b46_7_25", new trsuperobject(46,7,25,"Kızlara gelince, Rabden onlarla ilgili bir buyruk almış değilim. Ama Rabbin merhameti sayesinde güvenilir biri olarak düşündüklerimi söylüyorum."));
trsuperobject.biblemap.put("b46_7_26", new trsuperobject(46,7,26,"Öyle sanıyorum ki, şimdiki sıkıntılar nedeniyle insanın olduğu gibi kalması iyidir."));
trsuperobject.biblemap.put("b46_7_27", new trsuperobject(46,7,27,"Karın varsa, boşanmayı isteme. Karın yoksa, kendine eş arama."));
trsuperobject.biblemap.put("b46_7_28", new trsuperobject(46,7,28,"Ama evlenirsen günah işlemiş olmazsın. Bir kız da evlenirse günah işlemiş olmaz. Ne var ki, evlenenler bu yaşamda sıkıntılarla karşılaşacak. Ben sizi bu sıkıntılardan esirgemek istiyorum."));
trsuperobject.biblemap.put("b46_7_29-31", new trsuperobject(46,7,29-31,"Kardeşler, şunu demek istiyorum: Zaman daralmıştır. Bundan böyle, karısı olanlar karıları yokmuş gibi, yas tutanlar yas tutmuyormuş gibi, sevinenler sevinmiyormuş gibi, mal alanlar malları yokmuş gibi, dünyadan yararlananlar alabildiğine yararlanmıyormuş gibi olsun. Çünkü dünyanın şimdiki hali geçicidir."));
trsuperobject.biblemap.put("b46_7_32", new trsuperobject(46,7,32,"Kaygısız olmanızı istiyorum. Evli olmayan erkek, Rabbi nasıl hoşnut edeceğini düşünerek Rabbin işleri için kaygılanır."));
trsuperobject.biblemap.put("b46_7_33", new trsuperobject(46,7,33,"Evli erkekse karısını nasıl hoşnut edeceğini düşünerek dünya işleri için kaygılanır."));
trsuperobject.biblemap.put("b46_7_34", new trsuperobject(46,7,34,"Böylece ilgisi bölünür. Evli olmayan kadın ya da kız hem bedence hem ruhça kutsal olmak amacıyla Rabbin işleri için kaygılanır. Evli kadınsa kocasını nasıl hoşnut edeceğini düşünerek dünya işleri için kaygılanır."));
trsuperobject.biblemap.put("b46_7_35", new trsuperobject(46,7,35,"Bunu sizin iyiliğiniz için söylüyorum, özgürlüğünüzü kısıtlamak için değil. İlginizi dağıtmadan, Rabbe adanmış olarak, Ona yaraşır biçimde yaşamanızı istiyorum."));
trsuperobject.biblemap.put("b46_7_36", new trsuperobject(46,7,36,"Bir kimse nişanlı olduğu kıza yakışıksız davrandığını düşünüyorsa, aşırı tutkuları varsa ve evlenmesi gerekiyorsa, istediğini yapsın, günah işlemiş olmaz; evlensinler."));
trsuperobject.biblemap.put("b46_7_37", new trsuperobject(46,7,37,"Ama zorunluluk altında bulunmayan, yüreği kararlı, istediğini yapabilecek durumdaki kişi, nişanlısıyla evlenmemeye yüreğinde karar vermişse, iyi eder."));
trsuperobject.biblemap.put("b46_7_38", new trsuperobject(46,7,38,"Kısacası nişanlısıyla evlenen iyi eder, evlenmeyense daha iyi eder."));
trsuperobject.biblemap.put("b46_7_39", new trsuperobject(46,7,39,"Kadın, kocası yaşadıkça kocasına bağlıdır. Kocası ölürse dilediği kimseyle evlenmekte özgürdür; yeter ki, o kişi Rabbe ait biri olsun."));
trsuperobject.biblemap.put("b46_7_40", new trsuperobject(46,7,40,"Ama dul kadın, olduğu gibi kalırsa daha mutlu olur. Ben böyle düşünüyorum ve sanırım bende de Tanrı'nın Ruhu vardır."));
trsuperobject.biblemap.put("b46_8_1", new trsuperobject(46,8,1,"Şimdi putlara sunulan kurbanların etine gelelim. ‹‹Hepimizin bilgisi var›› diyorsunuz, bunu biliyoruz. Bilgi insanı böbürlendirir, sevgiyse geliştirir."));
trsuperobject.biblemap.put("b46_8_2", new trsuperobject(46,8,2,"Bir şey bildiğini sanan, henüz bilmesi gerektiği gibi bilmiyordur."));
trsuperobject.biblemap.put("b46_8_3", new trsuperobject(46,8,3,"Ama Tanrıyı seveni Tanrı bilir."));
trsuperobject.biblemap.put("b46_8_4", new trsuperobject(46,8,4,"Putlara sunulan kurban etinin yenmesine gelince, biliyoruz ki, ‹‹Dünyada put bir hiçtir›› ve ‹‹Birden fazla Tanrı yoktur››."));
trsuperobject.biblemap.put("b46_8_5-6", new trsuperobject(46,8,5-6,"Yerde ya da gökte ilah diye adlandırılanlar varsa da -nitekim pekçok ‹‹ilah››, pekçok ‹‹rab›› vardır- bizim için tek bir Tanrı Baba vardır. O her şeyin kaynağıdır, bizler Onun için yaşıyoruz. Tek bir Rab var, O da İsa Mesihtir. Her şey Onun aracılığıyla yaratıldı, biz de Onun aracılığıyla yaşıyoruz."));
trsuperobject.biblemap.put("b46_8_7", new trsuperobject(46,8,7,"Ne var ki, herkes bu bilgiye sahip değildir. Hâlâ putperest alışkanlıklarının etkisinde kalan bazıları, yedikleri etin puta sunulduğunu düşünüyorlar. Vicdanları zayıf olduğu için lekeleniyor."));
trsuperobject.biblemap.put("b46_8_8", new trsuperobject(46,8,8,"Yiyecek bizi Tanrıya yaklaştırmaz. Yemezsek bir kaybımız olmaz, yersek de bir kazancımız olmaz."));
trsuperobject.biblemap.put("b46_8_9", new trsuperobject(46,8,9,"Yalnız dikkat edin, bu özgürlüğünüz vicdanı zayıf olanların sürçmesine neden olmasın."));
trsuperobject.biblemap.put("b46_8_10", new trsuperobject(46,8,10,"Eğer zayıf vicdanlı biri, bilgili olan seni bir put tapınağında sofraya oturmuş görürse, puta sunulan kurbanın etini yemek için cesaret almaz mı?"));
trsuperobject.biblemap.put("b46_8_11", new trsuperobject(46,8,11,"Sonuçta bu zayıf vicdanlı kişi, Mesihin uğruna öldüğü bu kardeş, senin bilgin yüzünden mahvolur!"));
trsuperobject.biblemap.put("b46_8_12", new trsuperobject(46,8,12,"Bu şekilde kardeşlere karşı günah işleyip onların zayıf vicdanlarını yaralayarak Mesihe karşı günah işlemiş olursunuz."));
trsuperobject.biblemap.put("b46_8_13", new trsuperobject(46,8,13,"Bu nedenle, yediğim şey kardeşimin sendeleyip düşmesine yol açacaksa, kardeşimin düşmemesi için bir daha et yemeyeceğim."));
trsuperobject.biblemap.put("b46_9_1", new trsuperobject(46,9,1,"Özgür değil miyim? Elçi değil miyim? Rabbimiz İsayı görmedim mi? Sizler Rab yolunda verdiğim emeğin ürünü değil misiniz?"));
trsuperobject.biblemap.put("b46_9_2", new trsuperobject(46,9,2,"Başkaları için elçi değilsem bile, sizler için elçiyim ya! Rab yolunda elçiliğimin kanıtı sizsiniz."));
trsuperobject.biblemap.put("b46_9_3", new trsuperobject(46,9,3,"Beni sorguya çekenlere karşı kendimi böyle savunurum."));
trsuperobject.biblemap.put("b46_9_4", new trsuperobject(46,9,4,"Yiyip içmeye hakkımız yok mu bizim?"));
trsuperobject.biblemap.put("b46_9_5", new trsuperobject(46,9,5,"Öbür elçiler gibi, Rabbin kardeşleri ve Kefas gibi, yanımızda imanlı bir eş gezdirmeye hakkımız yok mu?"));
trsuperobject.biblemap.put("b46_9_6", new trsuperobject(46,9,6,"Geçimi için çalışması gereken yalnız Barnabayla ben miyim?"));
trsuperobject.biblemap.put("b46_9_7", new trsuperobject(46,9,7,"Kim kendi parasıyla askerlik yapar? Kim bağ diker de ürününü yemez? Kim sürüyü güder de sütünden içmez?"));
trsuperobject.biblemap.put("b46_9_8", new trsuperobject(46,9,8,"İnsansal açıdan mı söylüyorum bunları? Kutsal Yasa da aynı şeyleri söylemiyor mu?"));
trsuperobject.biblemap.put("b46_9_9-10", new trsuperobject(46,9,9-10,"Musanın Yasasında, ‹‹Harman döven öküzün ağzını bağlamayacaksın›› diye yazılmıştır. Tanrının kaygısı öküzler mi, yoksa bunu özellikle bizim için mi söylüyor? Kuşkusuz, bizim için yazılmıştır bu. Çünkü çift sürenin umutla sürmesi, harman dövenin de harmana ortak olma umuduyla dövmesi gerekir."));
trsuperobject.biblemap.put("b46_9_11", new trsuperobject(46,9,11,"Aranıza ruhsal tohumlar ektiysek, sizden maddesel bir harman biçmemiz çok mu?"));
trsuperobject.biblemap.put("b46_9_12", new trsuperobject(46,9,12,"Başkalarının sizden yardım almaya hakları varsa, bizim daha çok hakkımız yok mu? Ama biz bu hakkımızı kullanmadık. Mesih Müjdesinin yayılmasına engel olmayalım diye her şeye katlanıyoruz."));
trsuperobject.biblemap.put("b46_9_13", new trsuperobject(46,9,13,"Tapınakta çalışanların tapınaktan beslendiklerini, sunakta görevli olanların da sunakta adanan adaklardan pay aldıklarını bilmiyor musunuz?"));
trsuperobject.biblemap.put("b46_9_14", new trsuperobject(46,9,14,"Bunun gibi, Rab Müjdeyi yayanların da geçimlerini Müjdeden sağlamasını buyurdu."));
trsuperobject.biblemap.put("b46_9_15", new trsuperobject(46,9,15,"Ama ben bu haklardan hiçbirini kullanmış değilim. Bunlar bana sağlansın diye de yazmıyorum. Bunu yapmaktansa ölmeyi yeğlerim. Kimse beni bu övünçten yoksun bırakmayacaktır!"));
trsuperobject.biblemap.put("b46_9_16", new trsuperobject(46,9,16,"Müjdeyi yayıyorum diye övünmeye hakkım yok. Çünkü bunu yapmakla yükümlüyüm. Müjdeyi yaymazsam vay halime!"));
trsuperobject.biblemap.put("b46_9_17", new trsuperobject(46,9,17,"Eğer Müjdeyi gönülden yayarsam, ödülüm olur; gönülsüzce yayarsam, yalnızca bana emanet edilen görevi yapmış olurum."));
trsuperobject.biblemap.put("b46_9_18", new trsuperobject(46,9,18,"Peki, ödülüm nedir? Müjdeyi karşılıksız yaymak ve böylece Müjdeyi yaymaktan doğan hakkımı kullanmamaktır."));
trsuperobject.biblemap.put("b46_9_19", new trsuperobject(46,9,19,"Ben özgürüm, kimsenin kölesi değilim. Ama daha çok kişi kazanayım diye herkesin kölesi oldum."));
trsuperobject.biblemap.put("b46_9_20", new trsuperobject(46,9,20,"Yahudileri kazanmak için Yahudilere Yahudi gibi davrandım. Kendim Kutsal Yasanın denetimi altında olmadığım halde, Yasa altında olanları kazanmak için onlara Yasa altındaymışım gibi davrandım."));
trsuperobject.biblemap.put("b46_9_21", new trsuperobject(46,9,21,"Tanrının Yasasına sahip olmayan biri değilim, Mesihin Yasası altındayım. Buna karşın, Yasaya sahip olmayanları kazanmak için Yasaya sahip değilmişim gibi davrandım."));
trsuperobject.biblemap.put("b46_9_22", new trsuperobject(46,9,22,"Güçsüzleri kazanmak için onlarla güçsüz oldum. Ne yapıp yapıp bazılarını kurtarmak için herkesle her şey oldum."));
trsuperobject.biblemap.put("b46_9_23", new trsuperobject(46,9,23,"Bunların hepsini Müjdede payım olsun diye, Müjde uğruna yapıyorum."));
trsuperobject.biblemap.put("b46_9_24", new trsuperobject(46,9,24,"Koşu alanında yarışanların hepsi koştuğu halde ödülü bir kişinin kazandığını bilmiyor musunuz? Öyle koşun ki ödülü kazanasınız."));
trsuperobject.biblemap.put("b46_9_25", new trsuperobject(46,9,25,"Yarışa katılan herkes kendini her yönden denetler. Böyleleri bunu çürüyüp gidecek bir defne tacı kazanmak için yaparlar. Bizse hiç çürümeyecek bir taç için yapıyoruz."));
trsuperobject.biblemap.put("b46_9_26", new trsuperobject(46,9,26,"Bunun içindir ki, amaçsızca koşan biri gibi koşmuyorum. Yumruğumu havayı döver gibi boşa atmıyorum."));
trsuperobject.biblemap.put("b46_9_27", new trsuperobject(46,9,27,"Müjde'yi başkalarına duyurduktan sonra kendim reddedilmemek için bedenime eziyet çektirip onu köle ediyorum."));
trsuperobject.biblemap.put("b46_10_1", new trsuperobject(46,10,1,"Kardeşler, atalarımızın hepsinin bulut altında korunduğunu ve hepsinin denizden geçtiğini bilmenizi istiyorum."));
trsuperobject.biblemap.put("b46_10_2", new trsuperobject(46,10,2,"Musaya bağlanmak üzere hepsi bulutta ve denizde vaftiz edildi."));
trsuperobject.biblemap.put("b46_10_3", new trsuperobject(46,10,3,"Hepsi aynı ruhsal yiyeceği yedi;"));
trsuperobject.biblemap.put("b46_10_4", new trsuperobject(46,10,4,"hepsi aynı ruhsal içeceği içti. Artlarından gelen ruhsal kayadan içtiler; o kaya Mesihti."));
trsuperobject.biblemap.put("b46_10_5", new trsuperobject(46,10,5,"Ne var ki, Tanrı onların çoğundan hoşnut değildi; nitekim cesetleri çöle serildi."));
trsuperobject.biblemap.put("b46_10_6", new trsuperobject(46,10,6,"Bu olaylar, onlar gibi kötü şeylere özlem duymamamız için bize ders olsun diye oldu."));
trsuperobject.biblemap.put("b46_10_7", new trsuperobject(46,10,7,"Onlardan bazıları gibi puta tapanlar olmayın. Nitekim şöyle yazılmıştır: ‹‹Halk yiyip içmeye oturdu, sonra kalkıp çılgınca eğlendi.››"));
trsuperobject.biblemap.put("b46_10_8", new trsuperobject(46,10,8,"Onlardan bazıları gibi fuhuş yapmayalım. Fuhuş yapanların yirmi üç bini bir günde yok oldu."));
trsuperobject.biblemap.put("b46_10_9", new trsuperobject(46,10,9,"Yine bazıları gibi Rabbi denemeyelim. Böyle yapanları yılanlar öldürdü."));
trsuperobject.biblemap.put("b46_10_10", new trsuperobject(46,10,10,"Kimileri gibi de söylenip durmayın. Söylenenleri ölüm meleği öldürdü."));
trsuperobject.biblemap.put("b46_10_11", new trsuperobject(46,10,11,"Bu olaylar başkalarına ders olsun diye onların başına geldi; çağların sonuna ulaşmış olan bizleri uyarmak için yazıya geçirildi."));
trsuperobject.biblemap.put("b46_10_12", new trsuperobject(46,10,12,"Onun için, ayakta sağlam durduğunu sanan dikkat etsin, düşmesin!"));
trsuperobject.biblemap.put("b46_10_13", new trsuperobject(46,10,13,"Herkesin karşılaştığı denemelerden başka denemelerle karşılaşmadınız. Tanrı güvenilirdir, gücünüzü aşan biçimde denenmenize izin vermez. Dayanabilmeniz için denemeyle birlikte çıkış yolunu da sağlayacaktır."));
trsuperobject.biblemap.put("b46_10_14", new trsuperobject(46,10,14,"Bu nedenle, sevgili kardeşlerim, putperestlikten kaçının."));
trsuperobject.biblemap.put("b46_10_15", new trsuperobject(46,10,15,"Aklı başında insanlarla konuşur gibi konuşuyorum. Söylediklerimi kendiniz tartın."));
trsuperobject.biblemap.put("b46_10_16", new trsuperobject(46,10,16,"Tanrıya şükrettiğimiz şükran kâsesiyle Mesihin kanına paydaş olmuyor muyuz? Bölüp yediğimiz ekmekle Mesihin bedenine paydaş olmuyor muyuz?"));
trsuperobject.biblemap.put("b46_10_17", new trsuperobject(46,10,17,"Ekmek bir olduğu gibi, biz de çok olduğumuz halde bir bedeniz. Çünkü hepimiz bir ekmeği paylaşıyoruz."));
trsuperobject.biblemap.put("b46_10_18", new trsuperobject(46,10,18,"İsrail halkına bakın; kurban etini yiyenler sunağa paydaş değil midir?"));
trsuperobject.biblemap.put("b46_10_19", new trsuperobject(46,10,19,"Öyleyse ne demek istiyorum? Puta sunulan kurban etinin bir özelliği mi var? Ya da putun bir önemi mi var?"));
trsuperobject.biblemap.put("b46_10_20", new trsuperobject(46,10,20,"Hayır, yok! Dediğim şu: Putperestler kurbanlarını Tanrıya değil, cinlere sunuyorlar. Cinlerle paydaş olmanızı istemem."));
trsuperobject.biblemap.put("b46_10_21", new trsuperobject(46,10,21,"Hem Rabbin, hem cinlerin kâsesinden içemezsiniz; hem Rabbin, hem cinlerin sofrasına ortak olamazsınız."));
trsuperobject.biblemap.put("b46_10_22", new trsuperobject(46,10,22,"Yoksa Rabbi kıskandırmaya mı çalışıyoruz? Biz Ondan daha mı güçlüyüz?"));
trsuperobject.biblemap.put("b46_10_23", new trsuperobject(46,10,23,"‹‹Her şey serbest›› diyorsunuz, ama her şey yararlı değildir. ‹‹Her şey serbest›› diyorsunuz, ama her şey yapıcı değildir."));
trsuperobject.biblemap.put("b46_10_24", new trsuperobject(46,10,24,"Herkes kendi yararını değil, başkalarının yararını gözetsin."));
trsuperobject.biblemap.put("b46_10_25", new trsuperobject(46,10,25,"Kasaplar çarşısında satılan her eti vicdan sorunu yapmadan, sorgusuz sualsiz yiyin."));
trsuperobject.biblemap.put("b46_10_26", new trsuperobject(46,10,26,"Çünkü ‹‹Yeryüzü ve içindeki her şey Rabbindir.››"));
trsuperobject.biblemap.put("b46_10_27", new trsuperobject(46,10,27,"İman etmemiş biri sizi yemeğe çağırır, siz de gitmek isterseniz, önünüze konulan her şeyi vicdan sorunu yapmadan, sorgusuz sualsiz yiyin."));
trsuperobject.biblemap.put("b46_10_28", new trsuperobject(46,10,28,"Ama biri size, ‹‹Bu kurban etidir›› derse, hem bunu söyleyen için, hem de vicdan huzuru için yemeyin."));
trsuperobject.biblemap.put("b46_10_29", new trsuperobject(46,10,29,"Senin değil, öbür adamın vicdan huzuru için demek istiyorum. Benim özgürlüğümü neden başkasının vicdanı yargılasın?"));
trsuperobject.biblemap.put("b46_10_30", new trsuperobject(46,10,30,"Şükrederek yemeğe katılırsam, şükrettiğim yiyecekten ötürü neden kınanayım?"));
trsuperobject.biblemap.put("b46_10_31", new trsuperobject(46,10,31,"Sonuç olarak, ne yer ne içerseniz, ne yaparsanız, her şeyi Tanrının yüceliği için yapın."));
trsuperobject.biblemap.put("b46_10_32", new trsuperobject(46,10,32,"Yahudilerin, Greklerin ya da Tanrı topluluğunun tökezleyip düşmesine neden olmayın."));
trsuperobject.biblemap.put("b46_10_33", new trsuperobject(46,10,33,"Ben de kendi yararımı değil, kurtulsunlar diye birçoklarının yararını gözeterek herkesi her yönden hoşnut etmeye çalışıyorum."));
trsuperobject.biblemap.put("b46_11_1", new trsuperobject(46,11,1,"Mesihi örnek aldığım gibi, siz de beni örnek alın."));
trsuperobject.biblemap.put("b46_11_2", new trsuperobject(46,11,2,"Her durumda beni anımsadığınız ve size ilettiğim öğretileri olduğu gibi koruduğunuz için sizi övüyorum."));
trsuperobject.biblemap.put("b46_11_3", new trsuperobject(46,11,3,"Ama şunu da bilmenizi isterim: Her erkeğin başı Mesih, kadının başı erkek, Mesihin başı da Tanrıdır."));
trsuperobject.biblemap.put("b46_11_4", new trsuperobject(46,11,4,"Başına bir şey takıp dua ya da peygamberlik eden her erkek, başını küçük düşürür."));
trsuperobject.biblemap.put("b46_11_5", new trsuperobject(46,11,5,"Ama başı açık dua ya da peygamberlik eden her kadın, başını küçük düşürür. Böylesinin, başı tıraş edilmiş bir kadından farkı yoktur."));
trsuperobject.biblemap.put("b46_11_6", new trsuperobject(46,11,6,"Kadın başını açarsa, saçını kestirsin. Ama kadının saçını kestirmesi ya da tıraş etmesi ayıpsa, başını örtsün."));
trsuperobject.biblemap.put("b46_11_7", new trsuperobject(46,11,7,"Erkek başını örtmemeli; o, Tanrının benzeri ve yüceliğidir. Kadın da erkeğin yüceliğidir."));
trsuperobject.biblemap.put("b46_11_8", new trsuperobject(46,11,8,"Çünkü erkek kadından değil, kadın erkekten yaratıldı."));
trsuperobject.biblemap.put("b46_11_9", new trsuperobject(46,11,9,"Erkek kadın için değil, kadın erkek için yaratıldı."));
trsuperobject.biblemap.put("b46_11_10", new trsuperobject(46,11,10,"Bu nedenle ve melekler uğruna kadının başı üzerinde yetkisi olmalıdır."));
trsuperobject.biblemap.put("b46_11_11", new trsuperobject(46,11,11,"Ne var ki, Rabde ne kadın erkekten ne de erkek kadından bağımsızdır."));
trsuperobject.biblemap.put("b46_11_12", new trsuperobject(46,11,12,"Çünkü kadın erkekten yaratıldığı gibi, erkek de kadından doğar. Ama her şey Tanrıdandır."));
trsuperobject.biblemap.put("b46_11_13", new trsuperobject(46,11,13,"Siz kendiniz karar verin: Kadının açık başla Tanrıya dua etmesi uygun mu?"));
trsuperobject.biblemap.put("b46_11_14-15", new trsuperobject(46,11,14-15,"Doğanın kendisi bile size erkeğin uzun saçlı olmasının kendisini küçük düşürdüğünü, kadının uzun saçlı olmasının ise kendisini yücelttiğini öğretmiyor mu? Çünkü saç kadına örtü olarak verilmiştir."));
trsuperobject.biblemap.put("b46_11_16", new trsuperobject(46,11,16,"Bu konuda çekişmek isteyen varsa, şunu bilsin ki, bizim ya da Tanrının kiliselerinin böyle bir alışkanlığı yoktur."));
trsuperobject.biblemap.put("b46_11_17", new trsuperobject(46,11,17,"Toplantılarınız yarardan çok zarar getirdiği için aşağıdaki uyarıları yaparken sizi övemem."));
trsuperobject.biblemap.put("b46_11_18", new trsuperobject(46,11,18,"Birincisi, toplulukça bir araya geldiğinizde aranızda ayrılıklar olduğunu duyuyorum. Buna biraz da inanıyorum."));
trsuperobject.biblemap.put("b46_11_19", new trsuperobject(46,11,19,"Çünkü Tanrının beğenisini kazananların belli olması için aranızda bölünmeler olması gerekiyor!"));
trsuperobject.biblemap.put("b46_11_20", new trsuperobject(46,11,20,"Toplandığınızda Rabbin Sofrasına katılmak için toplanmıyorsunuz."));
trsuperobject.biblemap.put("b46_11_21", new trsuperobject(46,11,21,"Her biriniz ötekini beklemeden kendi yemeğini yiyor. Kimi aç kalıyor, kimi sarhoş oluyor."));
trsuperobject.biblemap.put("b46_11_22", new trsuperobject(46,11,22,"Yiyip içmek için evleriniz yok mu? Tanrının topluluğunu hor mu görüyorsunuz, yiyeceği olmayanları utandırmak mı istiyorsunuz? Size ne diyeyim? Sizi öveyim mi? Bu konuda övemem!"));
trsuperobject.biblemap.put("b46_11_23-24", new trsuperobject(46,11,23-24,"Size ilettiğimi ben Rabden öğrendim. Ele verildiği gece Rab İsa eline ekmek aldı, şükredip ekmeği böldü ve şöyle dedi: ‹‹Bu sizin uğrunuza feda edilen bedenimdir. Beni anmak için böyle yapın.››"));
trsuperobject.biblemap.put("b46_11_25", new trsuperobject(46,11,25,"Aynı biçimde yemekten sonra kâseyi alıp şöyle dedi: ‹‹Bu kâse kanımla gerçekleşen yeni antlaşmadır. Her içtiğinizde beni anmak için böyle yapın.››"));
trsuperobject.biblemap.put("b46_11_26", new trsuperobject(46,11,26,"Bu ekmeği her yediğinizde ve bu kâseden her içtiğinizde, Rabbin gelişine dek Rabbin ölümünü ilan etmiş olursunuz."));
trsuperobject.biblemap.put("b46_11_27", new trsuperobject(46,11,27,"Bu nedenle kim uygun olmayan biçimde ekmeği yer ya da Rabbin kâsesinden içerse, Rabbin bedenine ve kanına karşı suç işlemiş olur."));
trsuperobject.biblemap.put("b46_11_28", new trsuperobject(46,11,28,"Kişi önce kendini sınasın, sonra ekmekten yiyip kâseden içsin."));
trsuperobject.biblemap.put("b46_11_29", new trsuperobject(46,11,29,"Çünkü bedeni farketmeden yiyip içen, böyle yiyip içmekle kendi kendini mahkûm eder."));
trsuperobject.biblemap.put("b46_11_30", new trsuperobject(46,11,30,"İşte bu yüzden birçoğunuz zayıf ve hastadır, bazılarınız da ölmüştür."));
trsuperobject.biblemap.put("b46_11_31", new trsuperobject(46,11,31,"Kendimizi doğrulukla yargılasaydık, yargılanmazdık."));
trsuperobject.biblemap.put("b46_11_32", new trsuperobject(46,11,32,"Dünyayla birlikte mahkûm olmayalım diye Rab bizi yargılayıp terbiye ediyor."));
trsuperobject.biblemap.put("b46_11_33", new trsuperobject(46,11,33,"Öyleyse kardeşlerim, yemek için bir araya geldiğinizde birbirinizi bekleyin."));
trsuperobject.biblemap.put("b46_11_34", new trsuperobject(46,11,34,"Aç olan karnını evde doyursun. Öyle ki, toplanmanız yargılanmanıza yol açmasın. Öbür sorunları ise geldiğimde çözerim."));
trsuperobject.biblemap.put("b46_12_1", new trsuperobject(46,12,1,"Ruhsal armağanlara gelince, kardeşlerim, bu konuda bilgisiz kalmanızı istemem."));
trsuperobject.biblemap.put("b46_12_2", new trsuperobject(46,12,2,"Biliyorsunuz, putperestken şöyle ya da böyle saptırılıp dilsiz putlara tapmaya yöneltilmiştiniz."));
trsuperobject.biblemap.put("b46_12_3", new trsuperobject(46,12,3,"Bunun için bilmenizi isterim ki: Tanrının Ruhu aracılığıyla konuşan hiç kimse, ‹‹İsaya lanet olsun!›› demez. Kutsal Ruhun aracılığı olmaksızın da kimse, ‹‹İsa Rabdir›› diyemez."));
trsuperobject.biblemap.put("b46_12_4", new trsuperobject(46,12,4,"Çeşitli ruhsal armağanlar vardır, ama Ruh birdir."));
trsuperobject.biblemap.put("b46_12_5", new trsuperobject(46,12,5,"Çeşitli görevler vardır, ama Rab birdir."));
trsuperobject.biblemap.put("b46_12_6", new trsuperobject(46,12,6,"Çeşitli etkinlikler vardır, ama herkeste hepsini etkin kılan aynı Tanrıdır."));
trsuperobject.biblemap.put("b46_12_7", new trsuperobject(46,12,7,"Herkesin ortak yararı için herkese Ruhu belli eden bir yetenek veriliyor."));
trsuperobject.biblemap.put("b46_12_8-10", new trsuperobject(46,12,8-10,"Ruh aracılığıyla birine bilgece konuşma yeteneği, ötekine aynı Ruhtan bilgi iletme yeteneği, birine aynı Ruh aracılığıyla iman, ötekine aynı Ruh aracılığıyla hastaları iyileştirme armağanları, birine mucize yapma olanakları, birine peygamberlikte bulunma, birine ruhları ayırt etme, birine çeşitli dillerle konuşma, bir başkasına da bu dilleri çevirme armağanı veriliyor."));
trsuperobject.biblemap.put("b46_12_11", new trsuperobject(46,12,11,"Bunların tümünü etkin kılan tek ve aynı Ruhtur. Ruh bunları herkese dilediği gibi, ayrı ayrı dağıtır."));
trsuperobject.biblemap.put("b46_12_12", new trsuperobject(46,12,12,"Beden bir olmakla birlikte birçok üyeden oluşur ve çok sayıdaki bu üyelerin hepsi tek bir beden oluşturur. Mesih de böyledir."));
trsuperobject.biblemap.put("b46_12_13", new trsuperobject(46,12,13,"İster Yahudi ister Grek, ister köle ister özgür olalım, hepimiz bir beden olmak üzere aynı Ruhta vaftiz edildik ve hepimizin aynı Ruhtan içmesi sağlandı."));
trsuperobject.biblemap.put("b46_12_14", new trsuperobject(46,12,14,"İşte beden tek üyeden değil, birçok üyeden oluşur."));
trsuperobject.biblemap.put("b46_12_15", new trsuperobject(46,12,15,"Ayak, ‹‹El olmadığım için bedene ait değilim›› derse, bu onu bedenden ayırmaz."));
trsuperobject.biblemap.put("b46_12_16", new trsuperobject(46,12,16,"Kulak, ‹‹Göz olmadığım için bedene ait değilim›› derse, bu onu bedenden ayırmaz."));
trsuperobject.biblemap.put("b46_12_17", new trsuperobject(46,12,17,"Bütün beden göz olsaydı, nasıl duyardık? Bütün beden kulak olsaydı, nasıl koklardık?"));
trsuperobject.biblemap.put("b46_12_18", new trsuperobject(46,12,18,"Gerçek şu ki, Tanrı bedenin her üyesini dilediği biçimde bedene yerleştirmiştir."));
trsuperobject.biblemap.put("b46_12_19", new trsuperobject(46,12,19,"Eğer hepsi bir tek üye olsaydı, beden olur muydu?"));
trsuperobject.biblemap.put("b46_12_20", new trsuperobject(46,12,20,"Gerçek şu ki, çok sayıda üye, ama tek beden vardır."));
trsuperobject.biblemap.put("b46_12_21", new trsuperobject(46,12,21,"Göz ele, ‹‹Sana ihtiyacım yok!›› ya da baş ayaklara, ‹‹Size ihtiyacım yok!›› diyemez."));
trsuperobject.biblemap.put("b46_12_22", new trsuperobject(46,12,22,"Tam tersine, bedenin daha zayıf görünen üyeleri vazgeçilmezdir."));
trsuperobject.biblemap.put("b46_12_23", new trsuperobject(46,12,23,"Bedenin daha az değerli saydığımız üyelerine daha çok değer veririz. Böylece gösterişsiz üyelerimiz daha gösterişli olur."));
trsuperobject.biblemap.put("b46_12_24", new trsuperobject(46,12,24,"Gösterişli üyelerimizin özene ihtiyacı yoktur. Ama Tanrı, değeri az olana daha çok değer vererek bedende birliği sağladı."));
trsuperobject.biblemap.put("b46_12_25", new trsuperobject(46,12,25,"Öyle ki, bedende ayrılık olmasın, üyeler birbirini eşit biçimde gözetsin."));
trsuperobject.biblemap.put("b46_12_26", new trsuperobject(46,12,26,"Bir üye acı çekerse, bütün üyeler birlikte acı çeker; bir üye yüceltilirse, bütün üyeler birlikte sevinir."));
trsuperobject.biblemap.put("b46_12_27", new trsuperobject(46,12,27,"Sizler Mesihin bedenisiniz, bu bedenin ayrı ayrı üyelerisiniz."));
trsuperobject.biblemap.put("b46_12_28", new trsuperobject(46,12,28,"Tanrı kilisede ilkin elçileri, ikinci olarak peygamberleri, üçüncü olarak öğretmenleri, sonra mucize yapanları, hastaları iyileştirme armağanlarına sahip olanları, başkalarına yardım edenleri, yönetme yeteneği olanları ve çeşitli dillerle konuşanları atadı."));
trsuperobject.biblemap.put("b46_12_29", new trsuperobject(46,12,29,"Hepsi elçi mi? Hepsi peygamber mi? Hepsi öğretmen mi? Hepsi mucize yapar mı?"));
trsuperobject.biblemap.put("b46_12_30", new trsuperobject(46,12,30,"Hepsinin hastaları iyileştirme armağanları var mı? Hepsi bilmediği dilleri konuşabilir mi? Hepsi bu dilleri çevirebilir mi?"));
trsuperobject.biblemap.put("b46_12_31", new trsuperobject(46,12,31,"Ama siz daha üstün armağanları gayretle isteyin. Şimdi size en iyi yolu göstereyim."));
trsuperobject.biblemap.put("b46_13_1", new trsuperobject(46,13,1,"İnsanların ve meleklerin diliyle konuşsam, ama sevgim olmasa, ses çıkaran bakırdan ya da çınlayan zilden farkım kalmaz."));
trsuperobject.biblemap.put("b46_13_2", new trsuperobject(46,13,2,"Peygamberlikte bulunabilsem, bütün sırları bilsem, her bilgiye sahip olsam, dağları yerinden oynatacak kadar büyük imanım olsa, ama sevgim olmasa, bir hiçim."));
trsuperobject.biblemap.put("b46_13_3", new trsuperobject(46,13,3,"Varımı yoğumu sadaka olarak dağıtsam, bedenimi yakılmak üzere teslim etsem, ama sevgim olmasa, bunun bana hiçbir yararı olmaz."));
trsuperobject.biblemap.put("b46_13_4", new trsuperobject(46,13,4,"Sevgi sabırlıdır, sevgi şefkatlidir. Sevgi kıskanmaz, övünmez, böbürlenmez."));
trsuperobject.biblemap.put("b46_13_5", new trsuperobject(46,13,5,"Sevgi kaba davranmaz, kendi çıkarını aramaz, kolay kolay öfkelenmez, kötülüğün hesabını tutmaz."));
trsuperobject.biblemap.put("b46_13_6", new trsuperobject(46,13,6,"Sevgi haksızlığa sevinmez, gerçek olanla sevinir."));
trsuperobject.biblemap.put("b46_13_7", new trsuperobject(46,13,7,"Sevgi her şeye katlanır, her şeye inanır, her şeyi umut eder, her şeye dayanır."));
trsuperobject.biblemap.put("b46_13_8", new trsuperobject(46,13,8,"Sevgi asla son bulmaz. Ama peygamberlikler ortadan kalkacak, diller sona erecek, bilgi ortadan kalkacaktır."));
trsuperobject.biblemap.put("b46_13_9", new trsuperobject(46,13,9,"Çünkü bilgimiz de peygamberliğimiz de sınırlıdır."));
trsuperobject.biblemap.put("b46_13_10", new trsuperobject(46,13,10,"Ne var ki, yetkin olan geldiğinde sınırlı olan ortadan kalkacaktır."));
trsuperobject.biblemap.put("b46_13_11", new trsuperobject(46,13,11,"Çocukken çocuk gibi konuşur, çocuk gibi anlar, çocuk gibi düşünürdüm. Yetişkin biri olunca çocukça davranışları bıraktım."));
trsuperobject.biblemap.put("b46_13_12", new trsuperobject(46,13,12,"Şimdi her şeyi aynadaki silik görüntü gibi görüyoruz, ama o zaman yüz yüze görüşeceğiz. Şimdi bilgim sınırlıdır, ama o zaman bilindiğim gibi tam bileceğim."));
trsuperobject.biblemap.put("b46_13_13", new trsuperobject(46,13,13,"İşte kalıcı olan üç şey vardır: İman, umut, sevgi. Bunların en üstünü de sevgidir."));
trsuperobject.biblemap.put("b46_14_1", new trsuperobject(46,14,1,"Sevginin ardınca koşun ve ruhsal armağanları, özellikle peygamberlik yeteneğini gayretle isteyin."));
trsuperobject.biblemap.put("b46_14_2", new trsuperobject(46,14,2,"Bilmediği dilde konuşan, insanlarla değil, Tanrıyla konuşur. Kimse onu anlamaz. O, ruhuyla sırlar söyler."));
trsuperobject.biblemap.put("b46_14_3", new trsuperobject(46,14,3,"Peygamberlikte bulunansa insanların ruhça gelişmesi, cesaret ve teselli bulması için insanlara seslenir."));
trsuperobject.biblemap.put("b46_14_4", new trsuperobject(46,14,4,"Bilmediği dilde konuşan kendi kendini geliştirir; ama peygamberlikte bulunan, inanlılar topluluğunu geliştirir."));
trsuperobject.biblemap.put("b46_14_5", new trsuperobject(46,14,5,"Hepinizin dillerle konuşmasını isterim, ama peygamberlikte bulunmanızı yeğlerim. Diller inanlılar topluluğunun gelişmesi için çevrilmedikçe peygamberlikte bulunan, dillerle konuşandan üstündür."));
trsuperobject.biblemap.put("b46_14_6", new trsuperobject(46,14,6,"Şimdi kardeşlerim, yanınıza gelip dillerle konuşsam, ama size bir vahiy, bir bilgi, bir peygamberlik sözü ya da bir öğreti getirmesem, size ne yararım olur?"));
trsuperobject.biblemap.put("b46_14_7", new trsuperobject(46,14,7,"Kaval ya da lir gibi ses veren cansız nesneler bile değişik sesler çıkarmasa, kaval mı, lir mi çalındığını kim anlar?"));
trsuperobject.biblemap.put("b46_14_8", new trsuperobject(46,14,8,"Borazan belirgin bir ses çıkarmasa, kim savaşa hazırlanır?"));
trsuperobject.biblemap.put("b46_14_9", new trsuperobject(46,14,9,"Bunun gibi, siz de anlaşılır bir dil konuşmazsanız, söyledikleriniz nasıl anlaşılır? Havaya konuşmuş olursunuz!"));
trsuperobject.biblemap.put("b46_14_10", new trsuperobject(46,14,10,"Kuşkusuz dünyada çeşit çeşit diller vardır, hiçbiri de anlamsız değildir."));
trsuperobject.biblemap.put("b46_14_11", new trsuperobject(46,14,11,"Ne var ki, konuşulan dili anlamazsam, ben konuşana yabancı olurum, konuşan da bana yabancı olur."));
trsuperobject.biblemap.put("b46_14_12", new trsuperobject(46,14,12,"Bu nedenle, siz de ruhsal armağanlara heveslendiğinize göre, inanlılar topluluğunu geliştiren ruhsal armağanlar bakımından zenginleşmeye bakın."));
trsuperobject.biblemap.put("b46_14_13", new trsuperobject(46,14,13,"Bunun için, bilmediği dili konuşan, kendi söylediklerini çevirebilmek için dua etsin."));
trsuperobject.biblemap.put("b46_14_14", new trsuperobject(46,14,14,"Bilmediğim dille dua edersem ruhum dua eder, ama zihnimin buna katkısı olmaz."));
trsuperobject.biblemap.put("b46_14_15", new trsuperobject(46,14,15,"Öyleyse ne yapmalıyım? Ruhumla da zihnimle de dua edeceğim. Ruhumla da zihnimle de ilahi söyleyeceğim."));
trsuperobject.biblemap.put("b46_14_16", new trsuperobject(46,14,16,"Tanrıyı yalnız ruhunla översen, yeni katılanlar senin ne söylediğini bilmediğinden, ettiğin şükran duasına nasıl ‹‹Amin!›› desin?"));
trsuperobject.biblemap.put("b46_14_17", new trsuperobject(46,14,17,"Uygun biçimde şükrediyor olabilirsin, ama bu başkasını geliştirmez."));
trsuperobject.biblemap.put("b46_14_18", new trsuperobject(46,14,18,"Dillerle hepinizden çok konuştuğum için Tanrıya şükrediyorum."));
trsuperobject.biblemap.put("b46_14_19", new trsuperobject(46,14,19,"Ama inanlılar topluluğunda dillerle on bin söz söylemektense, başkalarını eğitmek için zihnimden beş söz söylemeyi yeğlerim."));
trsuperobject.biblemap.put("b46_14_20", new trsuperobject(46,14,20,"Kardeşler, çocuk gibi düşünmeyin. Kötülük konusunda çocuklar gibi, ama düşünmekte yetişkinler gibi olun."));
trsuperobject.biblemap.put("b46_14_21", new trsuperobject(46,14,21,"Kutsal Yasada şöyle yazılmıştır:  ‹‹Rab, ‹Yabancı diller konuşanların aracılığıyla,  Yabancıların dudaklarıyla bu halka sesleneceğim;  Yine de beni dinlemeyecekler!› diyor.››"));
trsuperobject.biblemap.put("b46_14_22", new trsuperobject(46,14,22,"Görülüyor ki, bilinmeyen diller imanlılar için değil, imansızlar için bir belirtidir. Peygamberlikse imansızlar için değil, imanlılar için bir belirtidir."));
trsuperobject.biblemap.put("b46_14_23", new trsuperobject(46,14,23,"Şimdi bütün inanlılar topluluğu bir araya gelip hep birlikte bilmedikleri dillerle konuşurlarken yeni katılanlar ya da iman etmeyenler içeri girerse, ‹‹Siz çıldırmışsınız!›› demezler mi?"));
trsuperobject.biblemap.put("b46_14_24", new trsuperobject(46,14,24,"Ama herkes peygamberlikte bulunurken iman etmeyen ya da yeni katılan biri içeri girerse, söylenen her sözle günahlı olduğuna ikna edilecek, her sözle yargılanacak."));
trsuperobject.biblemap.put("b46_14_25", new trsuperobject(46,14,25,"Yüreğindeki gizli düşünceler açığa çıkacak ve, ‹‹Tanrı gerçekten aranızdadır!›› diyerek yüzüstü yere kapanıp Tanrıya tapınacaktır."));
trsuperobject.biblemap.put("b46_14_26", new trsuperobject(46,14,26,"Öyleyse ne diyelim, kardeşler? Toplandığınızda her birinizin bir ilahisi, öğretecek bir konusu, bir vahyi, bilmediği dilde söyleyecek bir sözü ya da bir çevirisi vardır. Her şey topluluğun gelişmesi için olsun."));
trsuperobject.biblemap.put("b46_14_27", new trsuperobject(46,14,27,"Eğer bilinmeyen dillerle konuşulacaksa, iki ya da en çok üç kişi sırayla konuşsun, biri de söylenenleri çevirsin."));
trsuperobject.biblemap.put("b46_14_28", new trsuperobject(46,14,28,"Çeviri yapacak biri yoksa, bilmediği dilde konuşan, toplulukta sessiz kalsın, içinden Tanrıyla konuşsun."));
trsuperobject.biblemap.put("b46_14_29", new trsuperobject(46,14,29,"İki ya da üç peygamber konuşsun, öbürleri söylenenleri iyice düşünüp tartsın."));
trsuperobject.biblemap.put("b46_14_30", new trsuperobject(46,14,30,"Toplantıda oturanlardan birine vahiy gelirse, konuşmakta olan sussun."));
trsuperobject.biblemap.put("b46_14_31", new trsuperobject(46,14,31,"Herkesin öğrenmesi ve cesaret bulması için hepiniz teker teker peygamberlikte bulunabilirsiniz."));
trsuperobject.biblemap.put("b46_14_32", new trsuperobject(46,14,32,"Peygamberlerin ruhları peygamberlerin denetimi altındadır."));
trsuperobject.biblemap.put("b46_14_33", new trsuperobject(46,14,33,"Çünkü Tanrı karışıklık değil, esenlik Tanrısıdır. Kutsalların bütün topluluklarında böyledir."));
trsuperobject.biblemap.put("b46_14_34", new trsuperobject(46,14,34,"Kadınlar toplantılarınızda sessiz kalsın. Konuşmalarına izin yoktur. Kutsal Yasanın da belirttiği gibi, uysal olsunlar."));
trsuperobject.biblemap.put("b46_14_35", new trsuperobject(46,14,35,"Öğrenmek istedikleri bir şey varsa, evde kocalarına sorsunlar. Çünkü kadının toplantı sırasında konuşması ayıptır."));
trsuperobject.biblemap.put("b46_14_36", new trsuperobject(46,14,36,"Tanrının sözü sizden mi kaynaklandı, ya da yalnız size mi ulaştı?"));
trsuperobject.biblemap.put("b46_14_37", new trsuperobject(46,14,37,"Kendini peygamber ya da ruhça olgun sayan varsa, bilsin ki, size yazdıklarım Rabbin buyruğudur."));
trsuperobject.biblemap.put("b46_14_38", new trsuperobject(46,14,38,"Bunları önemsemeyenin kendisi de önemsenmesin."));
trsuperobject.biblemap.put("b46_14_39", new trsuperobject(46,14,39,"Özet olarak, kardeşlerim, peygamberlikte bulunmayı gayretle isteyin, bilinmeyen dillerle konuşulmasına engel olmayın. Ancak her şey uygun ve düzenli biçimde yapılsın."));
trsuperobject.biblemap.put("b46_15_1", new trsuperobject(46,15,1,"Şimdi, kardeşler, size bildirdiğim, sizin de kabul edip bağlı kaldığınız Müjdeyi anımsatmak istiyorum."));
trsuperobject.biblemap.put("b46_15_2", new trsuperobject(46,15,2,"Size müjdelediğim söze sımsıkı sarılırsanız, onun aracılığıyla kurtulursunuz. Yoksa boşuna iman etmiş olursunuz."));
trsuperobject.biblemap.put("b46_15_3-4", new trsuperobject(46,15,3-4,"Aldığım bilgiyi size öncelikle ilettim: Kutsal Yazılar uyarınca Mesih günahlarımıza karşılık öldü, gömüldü ve Kutsal Yazılar uyarınca üçüncü gün ölümden dirildi."));
trsuperobject.biblemap.put("b46_15_5", new trsuperobject(46,15,5,"Kefasa, sonra Onikilere göründü."));
trsuperobject.biblemap.put("b46_15_6", new trsuperobject(46,15,6,"Daha sonra da beş yüzden çok kardeşe aynı anda göründü. Bunların çoğu hâlâ yaşıyor, bazılarıysa öldüler."));
trsuperobject.biblemap.put("b46_15_7-8", new trsuperobject(46,15,7-8,"Bundan sonra Yakupa, sonra bütün elçilere, son olarak zamansız doğmuş bir çocuğa benzeyen bana da göründü."));
trsuperobject.biblemap.put("b46_15_9", new trsuperobject(46,15,9,"Ben elçilerin en önemsiziyim. Tanrının kilisesine zulmettiğim için elçi olarak anılmaya bile layık değilim."));
trsuperobject.biblemap.put("b46_15_10", new trsuperobject(46,15,10,"Ama şimdi neysem, Tanrının lütfuyla öyleyim. Onun bana olan lütfu boşa gitmedi. Elçilerin hepsinden çok emek verdim. Aslında ben değil, Tanrının bende olan lütfu emek verdi."));
trsuperobject.biblemap.put("b46_15_11", new trsuperobject(46,15,11,"İşte, gerek benim yaydığım, gerek öbür elçilerin yaydığı ve sizin de iman ettiğiniz bildiri budur."));
trsuperobject.biblemap.put("b46_15_12", new trsuperobject(46,15,12,"Eğer Mesihin ölümden dirildiği duyuruluyorsa, nasıl oluyor da aranızda bazıları ölüler dirilmez diyor?"));
trsuperobject.biblemap.put("b46_15_13", new trsuperobject(46,15,13,"Ölüler dirilmezse, Mesih de dirilmemiştir."));
trsuperobject.biblemap.put("b46_15_14", new trsuperobject(46,15,14,"Mesih dirilmemişse, bildirimiz de imanınız da boştur."));
trsuperobject.biblemap.put("b46_15_15", new trsuperobject(46,15,15,"Bu durumda Tanrıyla ilgili tanıklığımız da yalan demektir. Çünkü Tanrının, Mesihi dirilttiğine tanıklık ettik. Ama ölüler gerçekten dirilmezse, Tanrı Mesihi de diriltmemiştir."));
trsuperobject.biblemap.put("b46_15_16", new trsuperobject(46,15,16,"Ölüler dirilmezse, Mesih de dirilmemiştir."));
trsuperobject.biblemap.put("b46_15_17", new trsuperobject(46,15,17,"Mesih dirilmemişse imanınız yararsızdır, siz de hâlâ günahlarınızın içindesiniz."));
trsuperobject.biblemap.put("b46_15_18", new trsuperobject(46,15,18,"Buna göre Mesihe ait olarak ölmüş olanlar da mahvolmuşlardır."));
trsuperobject.biblemap.put("b46_15_19", new trsuperobject(46,15,19,"Eğer yalnız bu yaşam için Mesihe umut bağlamışsak, herkesten çok acınacak durumdayız."));
trsuperobject.biblemap.put("b46_15_20", new trsuperobject(46,15,20,"Oysa Mesih, ölmüş olanların ilk örneği olarak ölümden dirilmiştir."));
trsuperobject.biblemap.put("b46_15_21", new trsuperobject(46,15,21,"Ölüm bir insan aracılığıyla geldiğine göre, ölümden diriliş de bir insan aracılığıyla gelir."));
trsuperobject.biblemap.put("b46_15_22", new trsuperobject(46,15,22,"Herkes nasıl Ademde ölüyorsa, herkes Mesihte yaşama kavuşacak."));
trsuperobject.biblemap.put("b46_15_23", new trsuperobject(46,15,23,"Her biri sırası gelince dirilecek: İlk örnek olarak Mesih, sonra Mesihin gelişinde Mesihe ait olanlar."));
trsuperobject.biblemap.put("b46_15_24", new trsuperobject(46,15,24,"Bundan sonra Mesih her yönetimi, her hükümranlığı, her gücü ortadan kaldırıp egemenliği Baba Tanrıya teslim ettiği zaman son gelmiş olacak."));
trsuperobject.biblemap.put("b46_15_25", new trsuperobject(46,15,25,"Çünkü Tanrı bütün düşmanlarını ayakları altına serinceye dek Onun egemenlik sürmesi gerekir."));
trsuperobject.biblemap.put("b46_15_26", new trsuperobject(46,15,26,"Ortadan kaldırılacak son düşman ölümdür."));
trsuperobject.biblemap.put("b46_15_27", new trsuperobject(46,15,27,"Çünkü, ‹‹Tanrı her şeyi Mesihin ayakları altına sererek Ona bağımlı kıldı.›› ‹‹Her şey Ona bağımlı kılındı›› sözünün, her şeyi Mesihe bağımlı kılan Tanrıyı içermediği açıktır."));
trsuperobject.biblemap.put("b46_15_28", new trsuperobject(46,15,28,"Her şey Oğula bağımlı kılınınca, Oğul da her şeyi kendisine bağımlı kılan Tanrıya bağımlı olacaktır. Öyle ki, Tanrı her şeyde her şey olsun."));
trsuperobject.biblemap.put("b46_15_29", new trsuperobject(46,15,29,"Diriliş yoksa, ölüler için vaftiz edilenler ne olacak? Ölüler gerçekten dirilmeyecekse, insanlar neden ölüler için vaftiz ediliyorlar?"));
trsuperobject.biblemap.put("b46_15_30", new trsuperobject(46,15,30,"Biz de neden her saat kendimizi tehlikeye atıyoruz?"));
trsuperobject.biblemap.put("b46_15_31", new trsuperobject(46,15,31,"Kardeşler, sizinle ilgili olarak Rabbimiz Mesih İsada sahip olduğum övüncün hakkı için her gün ölüyorum."));
trsuperobject.biblemap.put("b46_15_32", new trsuperobject(46,15,32,"Eğer insansal nedenlerle Efeste canavarlarla dövüştümse, bunun bana yararı ne? Eğer ölüler dirilmeyecekse, ‹‹Yiyelim içelim, nasıl olsa yarın öleceğiz.››"));
trsuperobject.biblemap.put("b46_15_33", new trsuperobject(46,15,33,"Aldanmayın, ‹‹Kötü arkadaşlıklar iyi huyu bozar.››"));
trsuperobject.biblemap.put("b46_15_34", new trsuperobject(46,15,34,"Uslanıp kendinize gelin, artık günah işlemeyin. Bazılarınız Tanrıyı hiç tanımıyor. Utanasınız diye söylüyorum bunları."));
trsuperobject.biblemap.put("b46_15_35", new trsuperobject(46,15,35,"Ama biri çıkıp, ‹‹Ölüler nasıl dirilecek? Nasıl bir bedenle gelecekler?›› diye sorabilir."));
trsuperobject.biblemap.put("b46_15_36", new trsuperobject(46,15,36,"Ne akılsızca bir soru! Ektiğin tohum ölmedikçe yaşama kavuşmaz ki!"));
trsuperobject.biblemap.put("b46_15_37", new trsuperobject(46,15,37,"Ekerken, oluşacak bitkinin kendisini değil, yalnızca tohumunu -buğday ya da başka bir bitkinin tohumunu- ekersin."));
trsuperobject.biblemap.put("b46_15_38", new trsuperobject(46,15,38,"Tanrı tohuma dilediği bedeni -her birine kendine özgü bedeni- verir."));
trsuperobject.biblemap.put("b46_15_39", new trsuperobject(46,15,39,"Her canlının eti aynı değildir. İnsan eti başka, hayvan eti başka, kuş eti, balık eti başka başkadır."));
trsuperobject.biblemap.put("b46_15_40", new trsuperobject(46,15,40,"Göksel bedenler vardır, dünyasal bedenler vardır. Göksel olanların görkemi başka, dünyasal olanlarınki başkadır."));
trsuperobject.biblemap.put("b46_15_41", new trsuperobject(46,15,41,"Güneşin görkemi başka, ayın görkemi başka, yıldızların görkemi başkadır. Görkem bakımından yıldız yıldızdan farklıdır."));
trsuperobject.biblemap.put("b46_15_42", new trsuperobject(46,15,42,"Ölülerin dirilişi de böyledir. Beden çürümeye mahkûm olarak gömülür, çürümez olarak diriltilir."));
trsuperobject.biblemap.put("b46_15_43", new trsuperobject(46,15,43,"Düşkün olarak gömülür, görkemli olarak diriltilir. Zayıf olarak gömülür, güçlü olarak diriltilir."));
trsuperobject.biblemap.put("b46_15_44", new trsuperobject(46,15,44,"Doğal beden olarak gömülür, ruhsal beden olarak diriltilir. Doğal beden olduğu gibi, ruhsal beden de vardır."));
trsuperobject.biblemap.put("b46_15_45", new trsuperobject(46,15,45,"Nitekim şöyle yazılmıştır: ‹‹İlk insan Adem yaşayan can oldu.›› Son Ademse yaşam veren ruh oldu."));
trsuperobject.biblemap.put("b46_15_46", new trsuperobject(46,15,46,"Önce ruhsal olan değil, doğal olan geldi. Ruhsal olan sonra geldi."));
trsuperobject.biblemap.put("b46_15_47", new trsuperobject(46,15,47,"İlk insan yerden, yani topraktandır. İkinci insan göktendir."));
trsuperobject.biblemap.put("b46_15_48", new trsuperobject(46,15,48,"Topraktan olan insan nasılsa, topraktan olanlar da öyledir. Göksel insan nasılsa, göksel olanlar da öyledir."));
trsuperobject.biblemap.put("b46_15_49", new trsuperobject(46,15,49,"Bizler topraktan olana nasıl benzediysek, göksel olana da benzeyeceğiz."));
trsuperobject.biblemap.put("b46_15_50", new trsuperobject(46,15,50,"Kardeşler, şunu demek istiyorum, et ve kan Tanrının Egemenliğini miras alamaz. Çürüyen de çürümezliği miras alamaz."));
trsuperobject.biblemap.put("b46_15_51-52", new trsuperobject(46,15,51-52,"İşte size bir sır açıklıyorum. Hepimiz ölmeyeceğiz; son borazan çalınınca hepimiz bir anda, göz açıp kapayana dek değiştirileceğiz. Evet, borazan çalınacak, ölüler çürümez olarak dirilecek, ve biz de değiştirileceğiz."));
trsuperobject.biblemap.put("b46_15_53", new trsuperobject(46,15,53,"Çünkü bu çürüyen beden çürümezliği, bu ölümlü beden ölümsüzlüğü giyinmelidir."));
trsuperobject.biblemap.put("b46_15_54", new trsuperobject(46,15,54,"Çürüyen ve ölümlü beden çürümezliği ve ölümsüzlüğü giyinince, ‹‹Ölüm yok edildi, zafer kazanıldı!›› diye yazılmış olan söz yerine gelecektir."));
trsuperobject.biblemap.put("b46_15_55", new trsuperobject(46,15,55,"‹‹Ey ölüm, zaferin nerede?  Ey ölüm, dikenin nerede?››"));
trsuperobject.biblemap.put("b46_15_56", new trsuperobject(46,15,56,"Ölümün dikeni günahtır. Günah ise gücünü Kutsal Yasadan alır."));
trsuperobject.biblemap.put("b46_15_57", new trsuperobject(46,15,57,"Rabbimiz İsa Mesih aracılığıyla bizi zafere ulaştıran Tanrıya şükürler olsun!"));
trsuperobject.biblemap.put("b46_15_58", new trsuperobject(46,15,58,"Bu nedenle, sevgili kardeşlerim, Rab yolunda verdiğiniz emeğin boşa gitmeyeceğini bilerek dayanın, sarsılmayın, Rab'bin işinde her zaman gayretli olun."));
trsuperobject.biblemap.put("b46_16_1", new trsuperobject(46,16,1,"Kutsallara yapılacak para yardımına gelince: Galatya kiliselerine ne buyurduysam, siz de öyle yapın."));
trsuperobject.biblemap.put("b46_16_2", new trsuperobject(46,16,2,"Haftanın ilk günü herkes kazancına göre bir miktar para ayırıp biriktirsin. Öyle ki, yanınıza geldiğimde para toplamaya gerek kalmasın."));
trsuperobject.biblemap.put("b46_16_3", new trsuperobject(46,16,3,"Oraya vardığımda, bağışlarınızı götürmek üzere uygun gördüğünüz kişileri tanıtıcı mektuplarla Yeruşalime göndereceğim."));
trsuperobject.biblemap.put("b46_16_4", new trsuperobject(46,16,4,"Benim de gitmeme değerse, onları yanıma alıp gideceğim."));
trsuperobject.biblemap.put("b46_16_5", new trsuperobject(46,16,5,"Makedonyadan geçtikten sonra yanınıza geleceğim. Çünkü Makedonyadan geçmek niyetindeyim."));
trsuperobject.biblemap.put("b46_16_6", new trsuperobject(46,16,6,"Belki bir süre yanınızda kalırım, hatta kışı da sizinle geçirebilirim. Öyle ki, sonra nereye gidecek olsam, bana yardım edebilesiniz."));
trsuperobject.biblemap.put("b46_16_7", new trsuperobject(46,16,7,"Sizi öyle kısaca görüp geçmek istemiyorum. Rabbin izniyle uzunca bir süre yanınızda kalmayı umut ediyorum."));
trsuperobject.biblemap.put("b46_16_8", new trsuperobject(46,16,8,"Ama Pentikost Gününe dek Efeste kalacağım."));
trsuperobject.biblemap.put("b46_16_9", new trsuperobject(46,16,9,"Çünkü büyük ve etkili işler yapmam için burada bana bir kapı açıldı. Ne var ki, bana karşı çıkanlar çoktur."));
trsuperobject.biblemap.put("b46_16_10", new trsuperobject(46,16,10,"Timoteos yanınıza gelirse, bir şeyden korkmamasına dikkat edin. Çünkü o da benim gibi Rabbin işini yapıyor."));
trsuperobject.biblemap.put("b46_16_11", new trsuperobject(46,16,11,"Kimse onu hor görmesin. Yanıma gelmesi için onu esenlikle uğurlayın. Kardeşlerle birlikte onun da gelmesini bekliyorum."));
trsuperobject.biblemap.put("b46_16_12", new trsuperobject(46,16,12,"Kardeşimiz Apollosa gelince, kardeşlerle birlikte size gelmesi için ona çok ricada bulundum, ama şimdilik gelmeye hiç de istekli değil. Fırsat bulunca gelecek."));
trsuperobject.biblemap.put("b46_16_13", new trsuperobject(46,16,13,"Uyanık kalın, imanda dimdik durun, mert ve güçlü olun."));
trsuperobject.biblemap.put("b46_16_14", new trsuperobject(46,16,14,"Her şeyi sevgiyle yapın."));
trsuperobject.biblemap.put("b46_16_15-16", new trsuperobject(46,16,15-16,"Ahayada ilk iman eden ve kendilerini kutsalların hizmetine adayan İstefanasın ev halkını bilirsiniz. Kardeşler, size yalvarırım, bu gibilere ve onlarla birlikte çalışıp emek verenlerin hepsine bağımlı olun."));
trsuperobject.biblemap.put("b46_16_17", new trsuperobject(46,16,17,"İstefanas, Fortunatus ve Ahaykosun gelişine sevindim. Yokluğunuzu bana unutturdular."));
trsuperobject.biblemap.put("b46_16_18", new trsuperobject(46,16,18,"Sizin ruhunuzu da benim ruhumu da ferahlattılar. Böylelerinin değerini bilin."));
trsuperobject.biblemap.put("b46_16_19", new trsuperobject(46,16,19,"Asya İlindeki kiliseler size selam eder. Akvila ve Priska, evlerinde buluşan toplulukla birlikte Rabde size çok selam ederler."));
trsuperobject.biblemap.put("b46_16_20", new trsuperobject(46,16,20,"Buradaki bütün kardeşlerin size selamı var. Birbirinizi kutsal öpüşle selamlayın."));
trsuperobject.biblemap.put("b46_16_21", new trsuperobject(46,16,21,"Ben Pavlus, bu selamı kendi elimle yazıyorum."));
trsuperobject.biblemap.put("b46_16_22", new trsuperobject(46,16,22,"Rabbi sevmeyene lanet olsun. Maranata!"));
trsuperobject.biblemap.put("b46_16_23", new trsuperobject(46,16,23,"Rab İsanın lütfu sizinle birlikte olsun."));
trsuperobject.biblemap.put("b46_16_24", new trsuperobject(46,16,24,"Hepinize Mesih İsa'da sevgiler! Amin. Revision"));

}

}