package tr.bible;

public class trbible15 {

public trbible15() {

putmapbible15();

}

private void putmapbible15() {

trsuperobject.biblemap.put("b15_1_1", new trsuperobject(15,1,1,"Pers Kralı Koreşin krallığının birinci yılında RAB, Yeremya aracılığıyla bildirdiği sözünü yerine getirmek amacıyla, Pers Kralı Koreşi harekete geçirdi. Koreş yönetimi altındaki bütün halklara şu yazılı bildiriyi duyurdu:"));
trsuperobject.biblemap.put("b15_1_2", new trsuperobject(15,1,2,"‹‹Pers Kralı Koreş şöyle diyor: ‹Göklerin Tanrısı RAB yeryüzünün bütün krallıklarını bana verdi. Beni Yahudadaki Yeruşalim Kentinde kendisi için bir tapınak yapmakla görevlendirdi."));
trsuperobject.biblemap.put("b15_1_3", new trsuperobject(15,1,3,"Aranızda Onun halkından kim varsa Tanrısı onunla olsun. Yahudadaki Yeruşalim Kentine gidip İsrailin Tanrısı RABbin, Yeruşalimdeki Tanrının Tapınağını yeniden yapsınlar."));
trsuperobject.biblemap.put("b15_1_4", new trsuperobject(15,1,4,"Krallığımda yaşayan yerliler, sürgün oldukları yerlerde sağ kalmış olanlara altın, gümüş, mal ve hayvanlar sağlamakla birlikte Yeruşalimdeki Tanrının Tapınağına gönülden sunular sunsun.››"));
trsuperobject.biblemap.put("b15_1_5", new trsuperobject(15,1,5,"Böylece Yahuda ve Benyamin oymaklarının boy başları, kâhinler, Levililer ve ruhları Tanrı tarafından harekete geçirilen herkes, RABbin Yeruşalimdeki Tapınağını yeniden yapmak için gidiş hazırlıklarına girişti."));
trsuperobject.biblemap.put("b15_1_6", new trsuperobject(15,1,6,"Komşuları gönülden verdikleri armağanların yanısıra, altın, gümüş kaplar, mal, hayvan ve değerli armağanlarla onları desteklediler."));
trsuperobject.biblemap.put("b15_1_7-8", new trsuperobject(15,1,7-8,"Pers Kralı Koreş de Nebukadnessarın Yeruşalimdeki RABbin Tapınağından alıp kendi ilahının tapınağına koymuş olduğu kapları çıkardı. Bunları hazine görevlisi Mitredata getirterek sayımını yaptırdı ve Yahuda önderi Şeşbassara verdi."));
trsuperobject.biblemap.put("b15_1_9", new trsuperobject(15,1,9,"Sayım sonucu şuydu:"));
trsuperobject.biblemap.put("b15_1_30", new trsuperobject(15,1,30,"altın tas"));
trsuperobject.biblemap.put("b15_1_11", new trsuperobject(15,1,11,"Altın ve gümüş eşyaların toplamı 5 400 parçaydı. Sürgünler Babil'den Yeruşalim'e dönerken Şeşbassar bunların hepsini birlikte getirdi."));
trsuperobject.biblemap.put("b15_2_1", new trsuperobject(15,2,1,"Babil Kralı Nebukadnessarın Babile sürgün ettiği insanlar yaşadıkları ilden Yeruşalim ve Yahudadaki kendi kentlerine döndü."));
trsuperobject.biblemap.put("b15_2_2", new trsuperobject(15,2,2,"Bunlar Zerubbabil, Yeşu, Nehemya, Seraya, Reelaya, Mordekay, Bilşan, Mispar, Bigvay, Rehum ve Baananın önderliğinde geldiler. Sürgünden dönen İsraillilerin sayıları şöyleydi:"));
trsuperobject.biblemap.put("b15_2_3", new trsuperobject(15,2,3,"Paroşoğulları: 2172"));
trsuperobject.biblemap.put("b15_2_4", new trsuperobject(15,2,4,"Şefatyaoğulları: 372"));
trsuperobject.biblemap.put("b15_2_5", new trsuperobject(15,2,5,"Arahoğulları: 775"));
trsuperobject.biblemap.put("b15_2_6", new trsuperobject(15,2,6,"Yeşu ve Yoav soyundan Pahat-Moavoğulları: 2812"));
trsuperobject.biblemap.put("b15_2_7", new trsuperobject(15,2,7,"Elamoğulları: 1254"));
trsuperobject.biblemap.put("b15_2_8", new trsuperobject(15,2,8,"Zattuoğulları: 945"));
trsuperobject.biblemap.put("b15_2_9", new trsuperobject(15,2,9,"Zakkayoğulları: 760"));
trsuperobject.biblemap.put("b15_2_10", new trsuperobject(15,2,10,"Banioğulları: 642"));
trsuperobject.biblemap.put("b15_2_11", new trsuperobject(15,2,11,"Bevayoğulları: 623"));
trsuperobject.biblemap.put("b15_2_12", new trsuperobject(15,2,12,"Azgatoğulları: 1222"));
trsuperobject.biblemap.put("b15_2_13", new trsuperobject(15,2,13,"Adonikamoğulları: 666"));
trsuperobject.biblemap.put("b15_2_14", new trsuperobject(15,2,14,"Bigvayoğulları: 2056"));
trsuperobject.biblemap.put("b15_2_15", new trsuperobject(15,2,15,"Adinoğulları: 454"));
trsuperobject.biblemap.put("b15_2_16", new trsuperobject(15,2,16,"Hizkiya soyundan Ateroğulları: 98"));
trsuperobject.biblemap.put("b15_2_17", new trsuperobject(15,2,17,"Besayoğulları: 323"));
trsuperobject.biblemap.put("b15_2_18", new trsuperobject(15,2,18,"Yoraoğulları: 112"));
trsuperobject.biblemap.put("b15_2_19", new trsuperobject(15,2,19,"Haşumoğulları: 223"));
trsuperobject.biblemap.put("b15_2_20", new trsuperobject(15,2,20,"Gibbaroğulları: 95"));
trsuperobject.biblemap.put("b15_2_21", new trsuperobject(15,2,21,"Beytlehemliler: 123"));
trsuperobject.biblemap.put("b15_2_22", new trsuperobject(15,2,22,"Netofalılar: 56"));
trsuperobject.biblemap.put("b15_2_23", new trsuperobject(15,2,23,"Anatotlular: 128"));
trsuperobject.biblemap.put("b15_2_24", new trsuperobject(15,2,24,"Azmavetliler: 42"));
trsuperobject.biblemap.put("b15_2_25", new trsuperobject(15,2,25,"Kiryat-Yearimliler, Kefiralılar ve Beerotlular: 743"));
trsuperobject.biblemap.put("b15_2_26", new trsuperobject(15,2,26,"Ramalılar ve Gevalılar: 621"));
trsuperobject.biblemap.put("b15_2_27", new trsuperobject(15,2,27,"Mikmaslılar: 122"));
trsuperobject.biblemap.put("b15_2_28", new trsuperobject(15,2,28,"Beytel ve Ay kentlerinden olanlar: 223"));
trsuperobject.biblemap.put("b15_2_29", new trsuperobject(15,2,29,"Nevolular: 52"));
trsuperobject.biblemap.put("b15_2_30", new trsuperobject(15,2,30,"Magbişliler: 156"));
trsuperobject.biblemap.put("b15_2_31", new trsuperobject(15,2,31,"Öbür Elam Kentinden olanlar: 1254"));
trsuperobject.biblemap.put("b15_2_32", new trsuperobject(15,2,32,"Harimliler: 320"));
trsuperobject.biblemap.put("b15_2_33", new trsuperobject(15,2,33,"Lod, Hadit ve Ono kentlerinden olanlar: 725"));
trsuperobject.biblemap.put("b15_2_34", new trsuperobject(15,2,34,"Erihalılar: 345"));
trsuperobject.biblemap.put("b15_2_35", new trsuperobject(15,2,35,"Senaalılar: 3630."));
trsuperobject.biblemap.put("b15_2_36", new trsuperobject(15,2,36,"Kâhinler:  Yeşu soyundan Yedayaoğulları: 973"));
trsuperobject.biblemap.put("b15_2_37", new trsuperobject(15,2,37,"İmmeroğulları: 1052"));
trsuperobject.biblemap.put("b15_2_38", new trsuperobject(15,2,38,"Paşhuroğulları: 1247"));
trsuperobject.biblemap.put("b15_2_39", new trsuperobject(15,2,39,"Harimoğulları: 1017."));
trsuperobject.biblemap.put("b15_2_40", new trsuperobject(15,2,40,"Levililer:  Hodavya soyundan Yeşu ve Kadmieloğulları: 74."));
trsuperobject.biblemap.put("b15_2_41", new trsuperobject(15,2,41,"Ezgiciler:  Asafoğulları: 128."));
trsuperobject.biblemap.put("b15_2_42", new trsuperobject(15,2,42,"Tapınak kapı nöbetçileri:  Şallumoğulları, Ateroğulları,  Talmonoğulları, Akkuvoğulları,  Hatitaoğulları, Şovayoğulları, toplam 139."));
trsuperobject.biblemap.put("b15_2_43", new trsuperobject(15,2,43,"Tapınak görevlileri:  Sihaoğulları, Hasufaoğulları, Tabbaotoğulları,"));
trsuperobject.biblemap.put("b15_2_44", new trsuperobject(15,2,44,"Kerosoğulları, Siahaoğulları, Padonoğulları,"));
trsuperobject.biblemap.put("b15_2_45", new trsuperobject(15,2,45,"Levanaoğulları, Hagavaoğulları, Akkuvoğulları,"));
trsuperobject.biblemap.put("b15_2_46", new trsuperobject(15,2,46,"Hagavoğulları, Şalmayoğulları, Hananoğulları,"));
trsuperobject.biblemap.put("b15_2_47", new trsuperobject(15,2,47,"Giddeloğulları, Gaharoğulları, Reayaoğulları,"));
trsuperobject.biblemap.put("b15_2_48", new trsuperobject(15,2,48,"Resinoğulları, Nekodaoğulları, Gazzamoğulları,"));
trsuperobject.biblemap.put("b15_2_49", new trsuperobject(15,2,49,"Uzzaoğulları, Paseahoğulları, Besayoğulları,"));
trsuperobject.biblemap.put("b15_2_50", new trsuperobject(15,2,50,"Asnaoğulları, Meunimoğulları, Nefusimoğulları,"));
trsuperobject.biblemap.put("b15_2_51", new trsuperobject(15,2,51,"Bakbukoğulları, Hakufaoğulları, Harhuroğulları,"));
trsuperobject.biblemap.put("b15_2_52", new trsuperobject(15,2,52,"Baslutoğulları, Mehidaoğulları, Harşaoğulları,"));
trsuperobject.biblemap.put("b15_2_53", new trsuperobject(15,2,53,"Barkosoğulları, Siseraoğulları, Temahoğulları,"));
trsuperobject.biblemap.put("b15_2_54", new trsuperobject(15,2,54,"Nesiahoğulları, Hatifaoğulları."));
trsuperobject.biblemap.put("b15_2_55", new trsuperobject(15,2,55,"Süleymanın kullarının soyu:  Sotayoğulları, Hassoferetoğulları, Perudaoğulları,"));
trsuperobject.biblemap.put("b15_2_56", new trsuperobject(15,2,56,"Yalaoğulları, Darkonoğulları, Giddeloğulları,"));
trsuperobject.biblemap.put("b15_2_57", new trsuperobject(15,2,57,"Şefatyaoğulları, Hattiloğulları,  Pokeret-Hassevayimoğulları, Amioğulları."));
trsuperobject.biblemap.put("b15_2_58", new trsuperobject(15,2,58,"Tapınak görevlileriyle Süleymanın kullarının soyundan olanlar: 392."));
trsuperobject.biblemap.put("b15_2_59", new trsuperobject(15,2,59,"Tel-Melah, Tel-Harşa, Keruv, Addan ve İmmerden dönen, ancak hangi aileden olduklarını ve soylarının İsrailden geldiğini kanıtlayamayanlar şunlardır:"));
trsuperobject.biblemap.put("b15_2_60", new trsuperobject(15,2,60,"Delayaoğulları, Toviyaoğulları, Nekodaoğulları: 652."));
trsuperobject.biblemap.put("b15_2_61", new trsuperobject(15,2,61,"Kâhinlerin soyundan: Hovayaoğulları, Hakkosoğulları ve Gilatlı Barzillayın kızlarından biriyle evlenip kayınbabasının adını alan Barzillayın oğulları."));
trsuperobject.biblemap.put("b15_2_62", new trsuperobject(15,2,62,"Bunlar soy kütüklerini aradılar. Ama yazılı bir kayıt bulamayınca, kâhinlik görevi ellerinden alındı."));
trsuperobject.biblemap.put("b15_2_63", new trsuperobject(15,2,63,"Vali, Urim ile Tummimi kullanan bir kâhin çıkıncaya dek en kutsal yiyeceklerden yememelerini buyurdu."));
trsuperobject.biblemap.put("b15_2_64", new trsuperobject(15,2,64,"Bütün halk toplam 42 360 kişiydi."));
trsuperobject.biblemap.put("b15_2_65-67", new trsuperobject(15,2,65-67,"Ayrıca 7 337 erkek ve kadın köle,  kadınlı erkekli 200 ezgici,  736 at,  245 katır,  435 deve,  6 720 eşek vardı."));
trsuperobject.biblemap.put("b15_2_68", new trsuperobject(15,2,68,"Bazı aile başları Yeruşalimdeki RAB Tanrının Tapınağına varınca, tapınağın bulunduğu yerde yeniden kurulması için gönülden armağanlar verdiler."));
trsuperobject.biblemap.put("b15_2_69", new trsuperobject(15,2,69,"Her biri gücü oranında hazineye bu iş için toplam 61 000 darik altın, 5 000 mina gümüş, 100 kâhin mintanı bağışladı."));
trsuperobject.biblemap.put("b15_2_70", new trsuperobject(15,2,70,"Kâhinler, Levililer, halktan bazı kişiler -ezgiciler, tapınak görevlileri ve kapı nöbetçileri- kendi kentlerine yerleştiler. Böylece bütün İsrailliler kentlerinde yaşamaya başladılar."));
trsuperobject.biblemap.put("b15_3_1", new trsuperobject(15,3,1,"İsrailliler kendi kentlerine yerleştikten sonra, yedinci ay Yeruşalimde tek vücut halinde toplandılar."));
trsuperobject.biblemap.put("b15_3_2", new trsuperobject(15,3,2,"Yosadak oğlu Yeşu ve kâhin olan kardeşleri, Şealtiel oğlu Zerubbabille kardeşleri İsrailin Tanrısının sunağını yeniden kurdular. Amaçları, Tanrı adamı Musanın yasası uyarınca, sunağın üzerinde yakmalık sunular sunmaktı."));
trsuperobject.biblemap.put("b15_3_3", new trsuperobject(15,3,3,"Çevrelerinde yaşayan halklardan korkmalarına karşın, sunağı eski temeli üzerine yeniden kurdular. Üzerinde RABbe sabah, akşam öngörülen yakmalık sunuları sundular."));
trsuperobject.biblemap.put("b15_3_4", new trsuperobject(15,3,4,"Sonra yazılanlara uygun biçimde Çardak Bayramını kutladılar. Kural uyarınca, her gün için belirlenen sayıya göre, yakmalık sunuları sundular."));
trsuperobject.biblemap.put("b15_3_5", new trsuperobject(15,3,5,"Bundan sonra da günlük yakmalık sunuyu, Yeni Ay sunularını, RABbin belirlediği bütün kutsal bayramların sunularını ve RABbe gönülden verilen sunuları sundular."));
trsuperobject.biblemap.put("b15_3_7", new trsuperobject(15,3,7,"İsrailliler taşçılarla marangozlara para ödediler. Ayrıca sedir tomruklarını Lübnandan denize indirerek Yafaya getirmeleri için Saydalılara ve Surlulara yiyecek, içecek, zeytinyağı sağladılar. Bütün bunlara Pers Kralı Koreş izin vermişti."));
trsuperobject.biblemap.put("b15_3_8", new trsuperobject(15,3,8,"Tanrının Yeruşalimdeki Tapınağına vardıktan sonra, ikinci yılın ikinci ayında Şealtiel oğlu Zerubbabil, Yosadak oğlu Yeşu ve bütün öteki kardeşleri, kâhinler, Levililer ve sürgünden Yeruşalime dönenlerin tümü işe başladılar. RABbin Tapınağının yapımını denetlemek için yirmi ve daha yukarı yaştaki Levilileri görevlendirdiler."));
trsuperobject.biblemap.put("b15_3_9", new trsuperobject(15,3,9,"Levililerden Yeşu, oğulları ve kardeşleri, Yahuda soyundan Kadmiel ile oğulları, Henadatın oğullarıyla torunları Tanrının Tapınağının yapımında çalışanları denetleme işini hep birlikte yüklendiler."));
trsuperobject.biblemap.put("b15_3_10", new trsuperobject(15,3,10,"Yapıcılar RABbin Tapınağının temelini atınca, İsrail Kralı Davutun kuralı uyarınca kâhinler RABbi övmek için tören giysilerini giymiş olarak ellerinde borazanlarla, Levili Asafoğulları da zillerle yerlerini aldılar."));
trsuperobject.biblemap.put("b15_3_11", new trsuperobject(15,3,11,"RABbe övgüler, şükranlar sunarak ezgi okudular:  ‹‹RAB iyidir;  İsraile sevgisi sonsuzdur.›› RABbin Tapınağının temeli atıldığı için herkes yüksek sesle RABbi övmeye başladı."));
trsuperobject.biblemap.put("b15_3_12", new trsuperobject(15,3,12,"Eski tapınağı görmüş birçok yaşlı kâhin, Levili ve boy başı tapınağın temelinin atıldığını görünce hıçkıra hıçkıra ağladılar. Birçokları da sevinç çığlıkları attı."));
trsuperobject.biblemap.put("b15_3_13", new trsuperobject(15,3,13,"Sevinç çığlıkları ağlama sesinden ayırt edilemiyordu. Çünkü halk avaz avaz bağırıyordu. Ses uzak yerlerden bile duyuluyordu."));
trsuperobject.biblemap.put("b15_4_1", new trsuperobject(15,4,1,"Yahudalılarla Benyaminlilerin düşmanları, sürgünden dönenlerin İsrailin Tanrısı RAB için bir tapınak yaptığını duyunca,"));
trsuperobject.biblemap.put("b15_4_2", new trsuperobject(15,4,2,"Zerubbabilin ve boy başlarının yanına vardılar. ‹‹Tapınağı sizinle birlikte kuralım›› dediler, ‹‹Çünkü biz de, sizin gibi Tanrınıza tapıyoruz; bizi buraya getiren Asur Kralı Esarhaddonun döneminden bu yana sizin Tanrınıza kurban sunuyoruz.››"));
trsuperobject.biblemap.put("b15_4_3", new trsuperobject(15,4,3,"Ne var ki Zerubbabil, Yeşu ve İsrailin öteki boy başları, ‹‹Tanrımıza bir tapınak kurmak size düşmez›› diye karşılık verdiler, ‹‹Pers Kralı Koreşin buyruğu uyarınca, İsrailin Tanrısı RAB için tapınağı yalnız biz kuracağız.››"));
trsuperobject.biblemap.put("b15_4_4", new trsuperobject(15,4,4,"Bunun üzerine çevre halkı Yahudalıları tapınağın yapımından caydırmak için korkutmaya, cesaretlerini kırmaya girişti."));
trsuperobject.biblemap.put("b15_4_5", new trsuperobject(15,4,5,"Tasarılarına engel olmak için Pers Kralı Koreşin döneminden Pers Kralı Dariusun krallığına dek rüşvetle danışmanlar tuttular."));
trsuperobject.biblemap.put("b15_4_6", new trsuperobject(15,4,6,"Ahaşveroşunfç krallığının başlangıcında, Yahudalıların düşmanları Yahuda ve Yeruşalimde yaşayanları suçlayan bir belge düzenlediler."));
trsuperobject.biblemap.put("b15_4_7", new trsuperobject(15,4,7,"Pers Kralı Artahşastanın krallığı döneminde, Bişlam, Mitredat, Taveel ve öbür çalışma arkadaşları Artahşastaya bir mektup yazdılar. Mektup Aramice yazılıp çevrildi. yazılmıştır."));
trsuperobject.biblemap.put("b15_4_8", new trsuperobject(15,4,8,"Vali Rehum ile Yazman Şimşay Kral Artahşastaya Yeruşalimi suçlayan bir mektup yazdılar. Mektup şöyleydi:"));
trsuperobject.biblemap.put("b15_4_9", new trsuperobject(15,4,9,"‹‹Vali Rehum, Yazman Şimşay ve öbür çalışma arkadaşları, yargıçlar, yöneticiler, görevliler, Persler, Erekliler, Babilliler, Elam topraklarından gelen Sus halkı,"));
trsuperobject.biblemap.put("b15_4_10", new trsuperobject(15,4,10,"büyük ve onurlu Asurbanipalın sürüp Samiriye Kentiyle Fıratın batı yakasındaki bölgeye yerleştirdiği öbür halklarından.››"));
trsuperobject.biblemap.put("b15_4_11", new trsuperobject(15,4,11,"İşte Kral Artahşastaya gönderilen mektubun örneği: ‹‹Kral Artahşastaya, ‹‹Fıratın batı yakasındaki bölgede yaşayan kullarından:"));
trsuperobject.biblemap.put("b15_4_12", new trsuperobject(15,4,12,"‹‹Yönetimindeki öbür bölgelerden çıkıp bize gelen Yahudiler Yeruşalime yerleşerek o asi ve kötü kenti yeniden kurmaya başladılar. Bunu bilgine sunuyoruz. Temelini pekiştiriyor, surlarını tamamlıyorlar."));
trsuperobject.biblemap.put("b15_4_13", new trsuperobject(15,4,13,"Ey kral, bilmelisin ki, bu kent yeniden kurulur, surları tamamlanırsa, Yahudiler yine vergi ödemeyecek; krallığının geliri de azalacak."));
trsuperobject.biblemap.put("b15_4_14", new trsuperobject(15,4,14,"Biz sarayının ekmeğini yedik. Sana zarar gelmesine izin veremeyiz. Bunun için, haberin olsun diye bu mektubu gönderiyoruz."));
trsuperobject.biblemap.put("b15_4_15", new trsuperobject(15,4,15,"Atalarının belgeleri araştırılsın. Kayıtlarda bu kentin asi, krallara, valilere zarar veren bir kent olduğunu göreceksin. Bu kent öteden beri başkaldıran bir kenttir. Yerle bir edilmesinin nedeni de budur."));
trsuperobject.biblemap.put("b15_4_16", new trsuperobject(15,4,16,"Bu yüzden, ey kral, sana bildiriyoruz: Bu kent yeniden kurulur, surları tamamlanırsa, Fıratın batı yakasındaki bölgede hiçbir payın kalmayacak.›› yedik.››"));
trsuperobject.biblemap.put("b15_4_17", new trsuperobject(15,4,17,"Kral şu yanıtı gönderdi: ‹‹Samiriyede ve Fıratın batı yakasındaki öbür yerlerde yaşayan Vali Rehuma, Yazman Şimşaya ve öbür çalışma arkadaşlarına selamlar."));
trsuperobject.biblemap.put("b15_4_18", new trsuperobject(15,4,18,"‹‹Bize gönderdiğiniz mektup çevrilip bana okundu."));
trsuperobject.biblemap.put("b15_4_19", new trsuperobject(15,4,19,"Buyruğum üzerine araştırma yapıldı. Bu kentin öteden beri krallara başkaldırdığı, isyan ettiği, ayaklandığı saptandı."));
trsuperobject.biblemap.put("b15_4_20", new trsuperobject(15,4,20,"Yeruşalimi güçlü krallar yönetti. Fıratın batı yakasındaki bütün bölgede egemenlik sürdüler. Oradaki halktan vergi topladılar."));
trsuperobject.biblemap.put("b15_4_21", new trsuperobject(15,4,21,"Şimdi işi durdurmaları için bu adamlara bir buyruk çıkarın. Öyle ki, ben buyruk vermedikçe kent yeniden kurulmasın."));
trsuperobject.biblemap.put("b15_4_22", new trsuperobject(15,4,22,"Bu konuya özen gösterin; krallığıma daha fazla zarar gelmesin.››"));
trsuperobject.biblemap.put("b15_4_23", new trsuperobject(15,4,23,"Kral Artahşastanın mektubunun örneği kendilerine okunur okunmaz, Rehum, Yazman Şimşay ve öbür çalışma arkadaşları hemen Yeruşalime Yahudilerin yanına gittiler ve zorla onları durdurdular."));
trsuperobject.biblemap.put("b15_4_24", new trsuperobject(15,4,24,"Böylece Tanrı'nın Yeruşalim'deki Tapınağı'nın yapımı, Pers Kralı Darius'un krallığının ikinci yılına dek askıda kaldı."));
trsuperobject.biblemap.put("b15_5_1", new trsuperobject(15,5,1,"O sırada Peygamber Hagay ile İddo oğlu Peygamber Zekeriya, Yahuda ve Yeruşalimdeki Yahudilere İsrail Tanrısının adıyla peygamberlikte bulundular."));
trsuperobject.biblemap.put("b15_5_2", new trsuperobject(15,5,2,"Bunun üzerine Şealtiel oğlu Zerubbabil ile Yosadak oğlu Yeşu Tanrının Yeruşalimdeki Tapınağını yeniden kurmaya giriştiler. Tanrının peygamberleri de onlarla birlikteydi ve onlara yardım ediyordu."));
trsuperobject.biblemap.put("b15_5_3", new trsuperobject(15,5,3,"Fıratın batı yakasındaki bölgenin valisi Tattenay, Şetar-Bozenay ve çalışma arkadaşları onlara gidip, ‹‹Bu tapınağı yeniden kurmak ve yapımını tamamlamak için size kim yetki verdi?›› diye sordular."));
trsuperobject.biblemap.put("b15_5_4", new trsuperobject(15,5,4,"Yapıyı kuranların adlarını da sordular."));
trsuperobject.biblemap.put("b15_5_5", new trsuperobject(15,5,5,"Ama Tanrıları Yahudi ileri gelenlerini koruyordu. Bu yüzden, Dariusa bir haber gönderilip ondan yazılı bir yanıt alınıncaya dek Yahudiler durdurulmadı."));
trsuperobject.biblemap.put("b15_5_6", new trsuperobject(15,5,6,"Fıratın batı yakasındaki bölgenin valisi Tattenay, Şetar-Bozenay, çalışma arkadaşları ve oradaki görevlilerin Kral Dariusa gönderdikleri mektubun örneği aşağıdadır."));
trsuperobject.biblemap.put("b15_5_7", new trsuperobject(15,5,7,"Gönderdikleri belge şöyleydi: ‹‹Kral Dariusa candan selamlar."));
trsuperobject.biblemap.put("b15_5_8", new trsuperobject(15,5,8,"Yahuda İline, yüce Tanrının Tapınağına gittiğimizi krala bildiririz. Tapınağı büyük taşlarla kuruyor, duvarlarına kirişler yerleştiriyorlar. Tapınağın yapımında canla başla çalışılıyor ve yapım işi başarıyla ilerliyor."));
trsuperobject.biblemap.put("b15_5_9", new trsuperobject(15,5,9,"‹‹Halkın ileri gelenlerine, ‹Bu tapınağı yeniden kurmak ve yapımını tamamlamak için size kim yetki verdi?› diye sorduk."));
trsuperobject.biblemap.put("b15_5_10", new trsuperobject(15,5,10,"Bilgine sunmak üzere önderlerinin kim olduklarını sana yazabilmek için adlarını da sorduk."));
trsuperobject.biblemap.put("b15_5_11", new trsuperobject(15,5,11,"‹‹İşte bize verdikleri yanıt: ‹‹Biz yerin ve göğün Tanrısının kullarıyız. Uzun yıllar önce İsrailin büyük bir kralının kurup yapımını tamamladığı tapınağı yeniden kuruyoruz."));
trsuperobject.biblemap.put("b15_5_12", new trsuperobject(15,5,12,"Ama atalarımız Göklerin Tanrısını öfkelendirdi. Bu yüzden Tanrı onları Babil Kralı Kildani Nebukadnessarın eline teslim etti. Nebukadnessar tapınağı yıktı, halkı da Babile sürdü."));
trsuperobject.biblemap.put("b15_5_13", new trsuperobject(15,5,13,"Ama Babil Kralı Koreş, krallığının birinci yılında Tanrının Tapınağının yeniden yapılması için buyruk verdi."));
trsuperobject.biblemap.put("b15_5_14", new trsuperobject(15,5,14,"Ayrıca Nebukadnessarın Tanrının Yeruşalimdeki Tapınağından çıkarıp Babildeki tapınağa götürdüğü altın ve gümüş kapları da oradan çıkararak vali atadığı Şeşbassar adlı kişiye verdi."));
trsuperobject.biblemap.put("b15_5_15", new trsuperobject(15,5,15,"Koreş ona, Bu kapları al, gidip Yeruşalimdeki tapınağa yerleştir dedi, Tanrının Tapınağını eski yerinde yeniden kur."));
trsuperobject.biblemap.put("b15_5_16", new trsuperobject(15,5,16,"Böylece Şeşbassar gelip Tanrının Yeruşalimdeki Tapınağının temelini attı. O günden bu yana yapım işleri sürmekte, ama daha bitmedi.›"));
trsuperobject.biblemap.put("b15_5_17", new trsuperobject(15,5,17,"‹‹Kral uygun görüyorsa, Babil Sarayı'ndaki arşivde bir araştırma yapılsın. Tanrı'nın Yeruşalim'deki Tapınağı'nın yeniden kurulması için Kral Koreş'in bir buyruk verip vermediği saptansın. Sonra kral bu konuya ilişkin kararını bize bildirsin.››"));
trsuperobject.biblemap.put("b15_6_1", new trsuperobject(15,6,1,"Kral Dariusun buyruğu uyarınca, Babilde kayıtların saklandığı odada araştırma yapıldı."));
trsuperobject.biblemap.put("b15_6_2", new trsuperobject(15,6,2,"Medya İlindeki Ahmeta Kalesinde bir tomar bulundu. Tomarın içinde şunlar yazılıydı:"));
trsuperobject.biblemap.put("b15_6_3-4", new trsuperobject(15,6,3-4,"‹‹Kral Koreş, krallığının birinci yılında, Tanrının Yeruşalimdeki Tapınağına ilişkin şöyle buyruk verdi: ‹Kurban kesmek üzere bu tapınağın yeniden kurulması için temel atılsın. Üç sıra büyük taş, bir sıra kiriş döşensin. Yüksekliği ve genişliği altmışar arşınfı olsun. Giderler saraydan karşılansın."));
trsuperobject.biblemap.put("b15_6_5", new trsuperobject(15,6,5,"Nebukadnessarın Yeruşalimdeki Tanrının Tapınağından çıkarıp Babile getirdiği altın ve gümüş kaplar da geri verilsin. Yeruşalimdeki tapınakta özel yerlerine götürülsün. Hepsi Tanrının Tapınağına konsun.››"));
trsuperobject.biblemap.put("b15_6_6", new trsuperobject(15,6,6,"‹‹Onun için siz, Fıratın batı yakasındaki bölge valisi Tattenay, Şetar-Bozenay, çalışma arkadaşları ve oranın görevlileri, tapınaktan uzak durun!"));
trsuperobject.biblemap.put("b15_6_7", new trsuperobject(15,6,7,"Tanrının Tapınağının yapım işlerine karışmayın. Bırakın, Yahudilerin valisiyle ileri gelenleri Tanrının Tapınağını eski yerinde yeniden kursunlar."));
trsuperobject.biblemap.put("b15_6_8", new trsuperobject(15,6,8,"Ayrıca Tanrının Tapınağının yeniden kurulması için Yahudi ileri gelenlerine neler yapmanız gerektiğini de size buyuruyorum: Bu adamların bütün giderleri kralın hazinesinden, Fıratın batı yakasındaki bölgeden toplanan vergilerden ödensin. Öyle ki, yapım işleri aksamasın."));
trsuperobject.biblemap.put("b15_6_9", new trsuperobject(15,6,9,"Yeruşalimdeki kâhinlerin bütün gereksinimlerini hiç aksatmadan her gün vereceksiniz: Göklerin Tanrısına sunulacak yakmalık sunular için genç boğalar, koçlar, kuzular ve buğday, tuz, şarap, zeytinyağı."));
trsuperobject.biblemap.put("b15_6_10", new trsuperobject(15,6,10,"Öyle ki, Göklerin Tanrısını hoşnut eden sunular sunsunlar, ben ve oğullarım sağ kalalım diye dua etsinler."));
trsuperobject.biblemap.put("b15_6_11", new trsuperobject(15,6,11,"Bundan başka buyuruyorum ki, bu kararı değiştirenin evinden bir kiriş çıkarılacak ve o kişi kirişin üzerine asılacak. Evi de bu suçtan ötürü çöplüğe çevrilecek."));
trsuperobject.biblemap.put("b15_6_12", new trsuperobject(15,6,12,"Yeruşalimi adına konut seçen Tanrı, bu kararı değiştirmeye, oradaki Tanrı Tapınağını yıkmaya kalkışan her kralı ve ulusu yok etsin. Ben Darius böyle buyurdum. Buyruğum özenle yerine getirilsin.››"));
trsuperobject.biblemap.put("b15_6_13", new trsuperobject(15,6,13,"Fıratın batı yakasındaki bölge valisi Tattenay, Şetar-Bozenay ve çalışma arkadaşları Kral Dariusun buyruğunu özenle yerine getirdiler."));
trsuperobject.biblemap.put("b15_6_14", new trsuperobject(15,6,14,"Peygamber Hagay ile İddo oğlu Zekeriyanın yaptıkları peygamberlik sayesinde Yahudi ileri gelenleri yapım işlerini başarıyla ilerlettiler. İsrail Tanrısının buyruğu ve Pers kralları Koreşin, Dariusun, Artahşastanın buyrukları uyarınca tapınağın yapımını bitirdiler."));
trsuperobject.biblemap.put("b15_6_15", new trsuperobject(15,6,15,"Tapınak Kral Dariusun krallığının altıncı yılı, Adar ayının üçüncü günü tamamlandı."));
trsuperobject.biblemap.put("b15_6_16", new trsuperobject(15,6,16,"İsrail halkı -kâhinler, Levililer ve sürgünden dönenlerin tümü- Tanrının Tapınağının adanmasını sevinçle kutladılar."));
trsuperobject.biblemap.put("b15_6_17", new trsuperobject(15,6,17,"Tanrının Tapınağının adanması için yüz boğa, iki yüz koç, dört yüz kuzu kurban ettiler. Oymakların sayısına göre, bütün İsrailliler için günah sunusu olarak on iki teke sundular."));
trsuperobject.biblemap.put("b15_6_18", new trsuperobject(15,6,18,"Musanın Kitabındaki kural uyarınca Tanrının Yeruşalimdeki hizmeti için kâhinlerle Levilileri bağlı oldukları bölüklere göre görevlere atadılar."));
trsuperobject.biblemap.put("b15_6_19", new trsuperobject(15,6,19,"Sürgünden dönenler birinci ayın on dördüncü günü Fısıh Bayramını kutladılar."));
trsuperobject.biblemap.put("b15_6_20", new trsuperobject(15,6,20,"Kâhinlerle Levililer hep birlikte kendilerini arındırdılar; dinsel açıdan hepsi arındı. Levililer sürgünden dönenlerin tümü, kardeşleri olan kâhinler ve kendileri için Fısıh kurbanını kestiler."));
trsuperobject.biblemap.put("b15_6_21", new trsuperobject(15,6,21,"Sürgünden dönen İsraillilerle İsrailin Tanrısı RABbe yönelmek amacıyla kendilerini çevredeki halkların kötü alışkanlıklarından ayırıp onlara katılanların hepsi kurban etinden yedi."));
trsuperobject.biblemap.put("b15_6_22", new trsuperobject(15,6,22,"Mayasız Ekmek Bayramı'nı yedi gün sevinçle kutladılar. Çünkü RAB onları sevindirdi ve Asur Kralı'nın onlara iyi davranmasını, İsrail'in Tanrısı Tanrı'nın Tapınağı'nın yapım işlerinde onlara yardım etmesini sağladı."));
trsuperobject.biblemap.put("b15_7_1-6", new trsuperobject(15,7,1-6,"Bu olaylardan sonra, Pers Kralı Artahşastanın krallığı döneminde, Başkâhin Harun oğlu Elazar oğlu Pinehas oğlu Avişua oğlu Bukki oğlu Uzzi oğlu Zerahya oğlu Merayot oğlu Azarya oğlu Amarya oğlu Ahituv oğlu Sadok oğlu Şallum oğlu Hilkiya oğlu Azarya oğlu Seraya oğlu Ezra adında biri Babilden geldi. Ezra İsrailin Tanrısı RABbin Musaya verdiği yasayı iyi bilen bir bilgindi. Tanrısı RABbin yardımıyla kral ona her istediğini verdi."));
trsuperobject.biblemap.put("b15_7_7", new trsuperobject(15,7,7,"Kral Artahşastanın krallığının yedinci yılında İsrail halkından, kâhinlerden, Levililerden, ezgicilerden, tapınak görevlilerinden ve kapı nöbetçilerinden bazıları Yeruşalime gitti."));
trsuperobject.biblemap.put("b15_7_8", new trsuperobject(15,7,8,"Ezra, Artahşastanın krallığının yedinci yılının beşinci ayında Yeruşalime vardı."));
trsuperobject.biblemap.put("b15_7_9", new trsuperobject(15,7,9,"Birinci ayın birinci günü Babilden ayrılmıştı. Tanrısının koruyucu eli sayesinde beşinci ayın birinci günü Yeruşalime vardı."));
trsuperobject.biblemap.put("b15_7_10", new trsuperobject(15,7,10,"Ezra kendini RABbin Yasasını inceleyip uygulamaya ve İsrailde kuralları, ilkeleri öğretmeye adamıştı."));
trsuperobject.biblemap.put("b15_7_11", new trsuperobject(15,7,11,"Kral Artahşastanın RABbin buyruklarını, İsrail için koyduğu kuralları iyi bilen Kâhin ve Bilgin Ezraya verdiği mektubun bir örneği şudur:"));
trsuperobject.biblemap.put("b15_7_12", new trsuperobject(15,7,12,"‹‹Kralların Kralı Artahşastadan Gökler Tanrısının Yasasının bilgini Kâhin Ezraya selamlar!"));
trsuperobject.biblemap.put("b15_7_13", new trsuperobject(15,7,13,"‹‹Krallığımda yaşayan İsrail halkından, kâhinlerden ve Levililerden Yeruşalime gitmek isteyen herkesin seninle gidebilmesi için buyruk veriyorum."));
trsuperobject.biblemap.put("b15_7_14", new trsuperobject(15,7,14,"Elindeki Tanrının Yasasının uygulanıp uygulanmadığı konusunda Yahuda ve Yeruşalimde araştırma yapman için, ben ve yedi danışmanım seni görevlendirdik."));
trsuperobject.biblemap.put("b15_7_15", new trsuperobject(15,7,15,"Benim ve danışmanlarımın Yeruşalimde konut kuran İsrailin Tanrısına gönülden verdiğimiz altını, gümüşü birlikte götürmelisin."));
trsuperobject.biblemap.put("b15_7_16", new trsuperobject(15,7,16,"Babil İlinden elde edeceğin altının, gümüşün tümünü, halkın ve kâhinlerin Tanrılarının Yeruşalimdeki Tapınağına gönülden verdikleri armağanları da alıp götürmelisin."));
trsuperobject.biblemap.put("b15_7_17", new trsuperobject(15,7,17,"‹‹Bu parayla hemen boğalar, koçlar, kuzular, tahıl sunuları ve dökmelik sunular satın alacak ve hepsini Tanrının Yeruşalimdeki Tapınağının sunağı üzerinde sunacaksın."));
trsuperobject.biblemap.put("b15_7_18", new trsuperobject(15,7,18,"Sen ve kardeşlerin artan altını, gümüşü Tanrınızın isteği uyarınca dilediğiniz gibi kullanın."));
trsuperobject.biblemap.put("b15_7_19", new trsuperobject(15,7,19,"Tanrının Tapınağının hizmetinde kullanılmak üzere sana verilen kapların hepsini Yeruşalimin Tanrısına sun."));
trsuperobject.biblemap.put("b15_7_20", new trsuperobject(15,7,20,"Tanrının Tapınağı için ödemen gereken başka bir şey varsa, giderleri kralın hazinesinden karşılarsın."));
trsuperobject.biblemap.put("b15_7_21", new trsuperobject(15,7,21,"‹‹Ben, Kral Artahşasta, Fıratın batı yakasındaki bölgenin bütün hazine görevlilerine buyruk veriyorum: Gökler Tanrısının Yasasının bilgini Kâhin Ezranın sizden her istediğini özenle yerine getirin."));
trsuperobject.biblemap.put("b15_7_22", new trsuperobject(15,7,22,"Kendisine gerektiğinde yüz talanta kadar gümüş, yüz kor buğday, yüz bat şarap, yüz bat zeytinyağı ve istediği kadar tuz sağlayın."));
trsuperobject.biblemap.put("b15_7_23", new trsuperobject(15,7,23,"Göklerin Tanrısı kendi tapınağı için ne buyurursa, özenle yerine getirin. Öyle ki, bana ve oğullarıma öfkelenmesin."));
trsuperobject.biblemap.put("b15_7_24", new trsuperobject(15,7,24,"Şunu da bilesiniz ki, kâhinlerden, Levililerden, ezgicilerden, tapınak görevlilerinden ve kapı nöbetçilerinden, Tanrının Tapınağının öbür hizmetkârlarından vergi almaya yetkiniz yoktur."));
trsuperobject.biblemap.put("b15_7_25", new trsuperobject(15,7,25,"‹‹Sana gelince, Ezra, sendeki Tanrı bilgeliği uyarınca yargıçlar ata. Bunlar Fıratın batı yakasındaki bölgede yaşayan bütün halka, Tanrının yasalarını bilenlerin hepsine adalet sağlasınlar. Yasayı bilmeyenlere de siz öğreteceksiniz."));
trsuperobject.biblemap.put("b15_7_26", new trsuperobject(15,7,26,"Tanrının Yasasına ve kralın buyruklarına uymayanlar ya ölümle, ya sürgünle, ya mallarına el konarak, ya da hapsedilerek cezalandırılsın.››"));
trsuperobject.biblemap.put("b15_7_27", new trsuperobject(15,7,27,"Atalarımızın Tanrısı RABbe övgüler olsun! Kralın yüreğine Yeruşalimdeki tapınağını onurlandırma isteğini koydu."));
trsuperobject.biblemap.put("b15_7_28", new trsuperobject(15,7,28,"Kralın, danışmanlarının, güçlü komutanlarının bana iyi davranmalarını sağladı. Tanrım RAB'bin eli üzerimde olduğundan yüreklendim. İsrail ileri gelenlerinin bazılarını toplayıp benimle Yeruşalim'e dönmelerini sağladım."));
trsuperobject.biblemap.put("b15_8_1", new trsuperobject(15,8,1,"Artahşastanın krallığı döneminde ben Ezrayla birlikte Babilden dönen boy başlarının ve onlarla birlikte kayıtlı olanların listesi:"));
trsuperobject.biblemap.put("b15_8_2", new trsuperobject(15,8,2,"Pinehasoğullarından Gerşom,  İtamaroğullarından Daniel,  Davutoğullarından Hattuş."));
trsuperobject.biblemap.put("b15_8_3", new trsuperobject(15,8,3,"Şekanyaoğullarından, Paroşoğullarından Zekeriya ve onunla birlikte bu boydan kaydedilen 150 erkek."));
trsuperobject.biblemap.put("b15_8_4", new trsuperobject(15,8,4,"Pahat-Moavoğullarından Zerahya oğlu Elyehoenay ve onunla birlikte 200 erkek."));
trsuperobject.biblemap.put("b15_8_5", new trsuperobject(15,8,5,"Yahaziel oğlu Şekanyanın oğullarından 300 erkek."));
trsuperobject.biblemap.put("b15_8_6", new trsuperobject(15,8,6,"Adinoğullarından Yonatan oğlu Ebet ve onunla birlikte 50 erkek."));
trsuperobject.biblemap.put("b15_8_7", new trsuperobject(15,8,7,"Elamoğullarından Atalya oğlu Yeşaya ve onunla birlikte 70 erkek."));
trsuperobject.biblemap.put("b15_8_8", new trsuperobject(15,8,8,"Şefatyaoğullarından Mikael oğlu Zevadya ve onunla birlikte 80 erkek."));
trsuperobject.biblemap.put("b15_8_9", new trsuperobject(15,8,9,"Yoavoğullarından Yehiel oğlu Ovadya ve onunla birlikte 218 erkek."));
trsuperobject.biblemap.put("b15_8_10", new trsuperobject(15,8,10,"Yosifya oğlu Şelomitin oğullarından 160 erkek."));
trsuperobject.biblemap.put("b15_8_11", new trsuperobject(15,8,11,"Bevayoğullarından Bevay oğlu Zekeriya ve onunla birlikte 28 erkek."));
trsuperobject.biblemap.put("b15_8_12", new trsuperobject(15,8,12,"Azgatoğullarından Hakkatan oğlu Yohanan ve onunla birlikte 110 erkek."));
trsuperobject.biblemap.put("b15_8_13", new trsuperobject(15,8,13,"Adonikamın küçük oğullarından adları Elifelet, Yeiel, Şemaya olanlar ve onlarla birlikte 60 erkek."));
trsuperobject.biblemap.put("b15_8_14", new trsuperobject(15,8,14,"Bigvayoğullarından Utay, Zakkur ve onlarla birlikte 70 erkek."));
trsuperobject.biblemap.put("b15_8_15", new trsuperobject(15,8,15,"Onları Ahava Kentine doğru uzanan kanalın yanına topladım. Orada üç gün konakladık. Halkın ve kâhinlerin arasında yoklama yaptığımda orada Levililerden kimse olmadığını gördüm."));
trsuperobject.biblemap.put("b15_8_16", new trsuperobject(15,8,16,"Bunun üzerine Eliezer, Ariel, Şemaya, Elnatan, Yariv, Elnatan, Natan, Zekeriya, Meşullam adındaki önderleri, Öğretmen Yoyarivi ve Elnatanı çağırttım."));
trsuperobject.biblemap.put("b15_8_17", new trsuperobject(15,8,17,"Sonra onları Kasifyada bulunan Önder İddoya gönderdim. İddoya ve tapınak görevlisi olan kardeşlerine neler söylemeleri gerektiğini bildirdim. Öyle ki, bize Tanrımızın Tapınağında görev yapacak adamlar göndersinler."));
trsuperobject.biblemap.put("b15_8_18", new trsuperobject(15,8,18,"Tanrımızın iyiliği sayesinde İsrail oğlu Levi oğlu Mahlioğullarından Şerevya adında bilge bir kişiyi bize gönderdiler. Kendisiyle birlikte oğulları ve kardeşleri toplam on sekiz kişi geldi."));
trsuperobject.biblemap.put("b15_8_19", new trsuperobject(15,8,19,"Haşavyayı, Merarioğullarından Yeşayayı ve kardeşleriyle oğullarını, toplam yirmi kişiyi de gönderdiler."));
trsuperobject.biblemap.put("b15_8_20", new trsuperobject(15,8,20,"Ayrıca Levililere yardım etmek üzere Davutla görevlilerinin atadığı tapınak görevlilerinden iki yüz yirmi kişi gönderdiler. Hepsinin adı listeye yazılmıştı."));
trsuperobject.biblemap.put("b15_8_21", new trsuperobject(15,8,21,"Tanrımızın önünde alçakgönüllü davranmak, Ondan kendimiz, çocuklarımız, mallarımız için güvenli bir yolculuk dilemek üzere orada, Ahava Kanalı yanında oruç ilan ettim."));
trsuperobject.biblemap.put("b15_8_22", new trsuperobject(15,8,22,"Yolculuğumuz sırasında herhangi bir düşmandan bizi korumaları için, kraldan asker ve atlı istemeye utanıyordum. Çünkü krala, ‹‹Tanrımız kendisine yönelenlerin hepsine iyilik eder, ama kızgın öfkesi kendisini bırakanların üzerindedir›› demiştik."));
trsuperobject.biblemap.put("b15_8_23", new trsuperobject(15,8,23,"Oruç tuttuk ve bu konuda Tanrımıza yakardık. O da yakarışımızı yanıtladı."));
trsuperobject.biblemap.put("b15_8_24", new trsuperobject(15,8,24,"Şerevya, Haşavya ve kardeşlerinden on kişiyle birlikte on iki önde gelen kâhin seçtim."));
trsuperobject.biblemap.put("b15_8_25", new trsuperobject(15,8,25,"Kralın, danışmanlarının, komutanlarının ve orada bulunan İsraillilerin Tanrımızın Tapınağına bağışladığı altını, gümüşü, kapları tartıp onlara verdim."));
trsuperobject.biblemap.put("b15_8_26", new trsuperobject(15,8,26,"Tartıp verdiklerim şunlardır:  650 talant gümüş,  100 talant gümüş kap,  100 talant altın,"));
trsuperobject.biblemap.put("b15_8_27", new trsuperobject(15,8,27,"bin dariklik yirmi altın tas ve altın kadar değerli, kaliteli, parlak tunçtan iki kap."));
trsuperobject.biblemap.put("b15_8_28", new trsuperobject(15,8,28,"Onlara, ‹‹Siz RAB için kutsalsınız, bu kaplar da öyle›› dedim, ‹‹Altın ve gümüş, atalarınızın Tanrısı RABbe gönülden sunulan sunudur."));
trsuperobject.biblemap.put("b15_8_29", new trsuperobject(15,8,29,"RABbin Yeruşalimdeki Tapınağının odalarında, önde gelen kâhinlerin, Levililerin, İsrailin boy başlarının önünde tartıncaya dek bunları iyi koruyun.››"));
trsuperobject.biblemap.put("b15_8_30", new trsuperobject(15,8,30,"Böylece kâhinlerle Levililer Yeruşalime, Tanrımızın Tapınağına götürülmek için tartılan altını, gümüşü, kapları aldılar."));
trsuperobject.biblemap.put("b15_8_31", new trsuperobject(15,8,31,"Birinci ayın on ikinci günü Yeruşalime gitmek üzere Ahava Kanalından ayrıldık. Tanrımızın eli üzerimizdeydi; yol boyunca düşmandan, pusuya yatanların saldırısından bizi korudu."));
trsuperobject.biblemap.put("b15_8_32", new trsuperobject(15,8,32,"Sonunda Yeruşalime vardık. Orada üç gün kaldık."));
trsuperobject.biblemap.put("b15_8_33", new trsuperobject(15,8,33,"Dördüncü gün, Tanrımızın Tapınağına gidip altını, gümüşü, kapları tarttık ve Uriya oğlu Kâhin Meremota verdik. Pinehas oğlu Elazar, Levili Yeşu oğlu Yozavat ve Binnuy oğlu Noadya da onunla birlikteydi."));
trsuperobject.biblemap.put("b15_8_34", new trsuperobject(15,8,34,"Her şey sayıldı, tartıldı; tartılanların tümü anında kayda geçirildi."));
trsuperobject.biblemap.put("b15_8_35", new trsuperobject(15,8,35,"Sürgünden dönenler İsrailin Tanrısına yakmalık sunular sundular: Bütün İsrail için on iki boğa, doksan altı koç, yetmiş yedi kuzu ve günah sunusu olarak on iki teke. Bütün bunlar RABbe yakmalık sunu olarak sunuldu."));
trsuperobject.biblemap.put("b15_8_36", new trsuperobject(15,8,36,"Ayrıca kralın buyruklarını içeren belgeyi kralın satraplarına ve Fırat'ın batı yakasındaki valilere verdiler. Bunlar İsrail halkına ve Tanrı'nın Tapınağı'na yardım etmişlerdi."));
trsuperobject.biblemap.put("b15_9_1", new trsuperobject(15,9,1,"Bütün bunlardan sonra, önderler yanıma gelerek şöyle dediler: ‹‹İsrail halkı, kâhinlerle Levililer dahil, çevredeki halkların -Kenanlıların, Hititlerin, Perizlilerin, Yevusluların, Ammonluların, Moavlıların, Mısırlıların, Amorluların- iğrenç alışkanlıklarından kendilerini ayrı tutmadı."));
trsuperobject.biblemap.put("b15_9_2", new trsuperobject(15,9,2,"Kendilerine ve oğullarına bu halklardan kız aldılar. Böylece kutsal soy çevredeki halklarla karıştı. Önderlerle görevliler bu hainlikte öncülük etti.››"));
trsuperobject.biblemap.put("b15_9_3", new trsuperobject(15,9,3,"Bunu duyunca giysimi ve cüppemi yırttım, saçımı sakalımı yoldum, dehşet içinde oturakaldım."));
trsuperobject.biblemap.put("b15_9_4", new trsuperobject(15,9,4,"Sürgünden dönenlerin bu hainliğinden ötürü İsrailin Tanrısının sözlerinden titreyenlerin hepsi çevremde toplandı. Bense akşam sunusu sunulana dek dehşet içinde kaldım."));
trsuperobject.biblemap.put("b15_9_5", new trsuperobject(15,9,5,"Akşam sunusu saati gelince üzüntümü bir yana bırakıp kalktım. Giysimle cüppem hâlâ yırtıktı. Diz çöküp ellerimi Tanrım RABbe açtım."));
trsuperobject.biblemap.put("b15_9_6", new trsuperobject(15,9,6,"Şöyle dua ettim: ‹‹Ey Tanrım, yüzümü sana çevirmeye utanıyorum, sıkılıyorum. Ey Tanrım, günahlarımız başımızdan aşkın. Suçlarımız göklere ulaştı."));
trsuperobject.biblemap.put("b15_9_7", new trsuperobject(15,9,7,"Atalarımızın günlerinden bugüne dek suçlarımız içinde boğulduk. Günahlarımız yüzünden biz de, krallarımızla kâhinlerimiz de yabancı kralların eline teslim edildik. Kılıçtan geçirildik, sürgüne gönderildik. Yağmalandık. Bugün de olduğu gibi aşağılandık."));
trsuperobject.biblemap.put("b15_9_8", new trsuperobject(15,9,8,"‹‹Şimdiyse Tanrımız RAB bir an için bize acıdı. Sürgünden kurtulan bir azınlık bıraktı bize. Kutsal yerinde bize sarsılmaz bir destek verdi. Gözlerimizi aydınlattı. Köleliğimizde bize yenilenme fırsatı sağladı."));
trsuperobject.biblemap.put("b15_9_9", new trsuperobject(15,9,9,"Köle olduğumuz halde Tanrımız bizi köle bırakmadı. Pers krallarının bize iyi davranmalarını sağladı: Tanrımızın Tapınağını yeniden kurmak, yıkık yerleri onarmak için bize yenilenme fırsatı verdi. Yeruşalimde ve Yahudada bize bir korunma duvarı verdi."));
trsuperobject.biblemap.put("b15_9_1-011", new trsuperobject(15,9,1-011,"‹‹Ey Tanrımız, bundan başka ne diyebiliriz? Kulların peygamberler aracılığıyla verdiğin buyruklara uymadık. Şöyle demiştin: ‹Mülk edinmek için gitmekte olduğunuz ülke, orada yaşayan halkların iğrençlikleriyle kirlenmiştir. İğrençlikleri yüzünden ülke baştan başa murdarlıklarla doldu."));
trsuperobject.biblemap.put("b15_9_12", new trsuperobject(15,9,12,"Bunun için kızlarınızı onların oğullarına vermeyin. Onların kızlarını da oğullarınıza almayın. Hiçbir zaman onların esenliği ve iyiliği için çalışmayın. Öyle ki, güç bulasınız, ülkenin iyi ürünlerini yiyesiniz ve ülkeyi sonsuza dek oğullarınıza miras bırakasınız.›"));
trsuperobject.biblemap.put("b15_9_13", new trsuperobject(15,9,13,"‹‹Başımıza gelenlere yaptığımız kötülükler ve büyük suçumuz neden oldu. Sen, ey Tanrımız, bizi hak ettiğimizden daha az cezalandırdın ve bize sürgünden kurtulan böyle bir azınlık bıraktın."));
trsuperobject.biblemap.put("b15_9_14", new trsuperobject(15,9,14,"‹‹Yine buyruklarına karşı gelecek miyiz? Bu iğrençlikleri yapan halklarla evlilik bağıyla karışacak mıyız? Bunu yaparsak, tek kişi sağ kalmadan yok edinceye dek bize öfkelenmeyecek misin?"));
trsuperobject.biblemap.put("b15_9_15", new trsuperobject(15,9,15,"Ey İsrail'in Tanrısı RAB, sen adilsin! Bugün sürgünden kurtulan bir azınlık olarak bırakıldık. Senin önünde durmaya hakkımız olmadığı halde, suçlarımızın içinde önünde duruyoruz.››"));
trsuperobject.biblemap.put("b15_10_1", new trsuperobject(15,10,1,"Ağlayarak kendini Tanrının Tapınağının önünde yere atan Ezra dua edip günahlarını açıkladı. Bu arada erkek, kadın, çocuk, İsraillilerden çok büyük bir topluluk Ezranın çevresine toplandı. Onlar da hıçkıra hıçkıra ağlıyordu."));
trsuperobject.biblemap.put("b15_10_2", new trsuperobject(15,10,2,"Elamoğullarından Yehiel oğlu Şekanya, Ezraya şöyle dedi: ‹‹Çevremizdeki halklardan yabancı karılar aldığımız için Tanrımıza ihanet ettik. Buna karşın İsrail için hâlâ umut var."));
trsuperobject.biblemap.put("b15_10_3", new trsuperobject(15,10,3,"Senin ve Tanrımızın buyrukları karşısında titreyenlerin öğütleri uyarınca, bütün yabancı kadınları ve çocuklarını uzaklaştırmak için Tanrımızla şimdi bir antlaşma yapalım. Bu antlaşma yasaya uygun olsun."));
trsuperobject.biblemap.put("b15_10_4", new trsuperobject(15,10,4,"Haydi kalk! Sorumluluk senin üzerinde. Biz seni destekleyeceğiz. Güçlü ol ve gerekeni yap!››"));
trsuperobject.biblemap.put("b15_10_5", new trsuperobject(15,10,5,"Bunun üzerine yerden kalkan Ezra önde gelen Levili kâhinlere ve öbür İsraillilere söyleneni yapmaları için ant içirdi. Hepsi ant içti."));
trsuperobject.biblemap.put("b15_10_6", new trsuperobject(15,10,6,"Sonra Ezra Tanrının Tapınağının önünden ayrılıp Elyaşiv oğlu Yehohananın odasına gitti. Orada gecelerken ne yemek yedi, ne su içti. Sürgünden dönenler Tanrıya bağlı kalmadığı için yas tutuyordu."));
trsuperobject.biblemap.put("b15_10_7", new trsuperobject(15,10,7,"Sürgünden dönenlerin hepsinin Yeruşalimde toplanması için Yahuda ve Yeruşalimde bir duyuru yapıldı:"));
trsuperobject.biblemap.put("b15_10_8", new trsuperobject(15,10,8,"Halkın önderlerinin ve ileri gelenlerinin kararı uyarınca, üç gün içinde gelmeyenin bütün malına el konulacak, kendisi de sürgünden dönenler topluluğundan atılacaktı."));
trsuperobject.biblemap.put("b15_10_9", new trsuperobject(15,10,9,"Bütün Yahudalı ve Benyaminli erkekler üç gün içinde Yeruşalimde toplandılar. Dokuzuncu ayın yirminci günü hepsi Tanrının Tapınağının önündeki alandaydı. Hem durumun öneminden, hem de yağmurdan ötürü herkes titriyordu."));
trsuperobject.biblemap.put("b15_10_10", new trsuperobject(15,10,10,"Kâhin Ezra kalkıp, ‹‹Siz Tanrıya ihanet ettiniz›› dedi, ‹‹Yabancı kadınlarla evlendiniz. İsrailin suçuna suç kattınız."));
trsuperobject.biblemap.put("b15_10_11", new trsuperobject(15,10,11,"Şimdi atalarınızın Tanrısı RABbe suçunuzu açıklayın. Onun istediğini yapın. Çevredeki halklardan ve yabancı karılardan ayrılın.››"));
trsuperobject.biblemap.put("b15_10_12", new trsuperobject(15,10,12,"Topluluk yüksek sesle şöyle karşılık verdi: ‹‹Bütün söylediklerini yapacağız."));
trsuperobject.biblemap.put("b15_10_13", new trsuperobject(15,10,13,"Yalnız kalabalık çok, üstelik hava da yağmurlu. Dışarda duracak gücümüz kalmadı. Hem bu bir iki günde çözülecek iş değil. Çünkü bu konuda çok günah işledik."));
trsuperobject.biblemap.put("b15_10_14", new trsuperobject(15,10,14,"Bütün topluluk adına önderlerimiz bu konuyla ilgilensin. Sonra kentlerimizde yabancı kadınla evli olan herkes saptanan bir zamanda kentin ileri gelenleri ve yargıçlarıyla birlikte gelsin. Yeter ki, Tanrımızın bu konudaki kızgın öfkesi üzerimizden kalksın.››"));
trsuperobject.biblemap.put("b15_10_15", new trsuperobject(15,10,15,"Ancak, Asahel oğlu Yonatan, Tikva oğlu Yahzeya ve onları destekleyen Meşullam ile Levili Şabbetay buna karşı çıktılar."));
trsuperobject.biblemap.put("b15_10_16", new trsuperobject(15,10,16,"Sürgünden dönenler bu öneriye göre davrandılar. Kâhin Ezra adlarını belirterek her boydan boy başlarını seçti. Onuncu ayın birinci günü oturup konuyu incelemeye başladılar."));
trsuperobject.biblemap.put("b15_10_17", new trsuperobject(15,10,17,"Birinci ayın birinci günü yabancı kadınlarla evlenen bütün erkeklerin durumunu incelemeyi bitirdiler."));
trsuperobject.biblemap.put("b15_10_18", new trsuperobject(15,10,18,"Kâhinlerin soyundan gelip yabancı kadınlarla evlenenler şunlardı: Yosadak oğlu Yeşunun oğullarından ve kardeşlerinin soyundan Maaseya, Eliezer, Yariv, Gedalya."));
trsuperobject.biblemap.put("b15_10_19", new trsuperobject(15,10,19,"Bunlar karılarını kovacaklarına söz verdiler. İşledikleri suç için suç sunusu olarak sürüden bir koç sundular."));
trsuperobject.biblemap.put("b15_10_20", new trsuperobject(15,10,20,"İmmeroğullarından: Hanani, Zevadya."));
trsuperobject.biblemap.put("b15_10_21", new trsuperobject(15,10,21,"Harimoğullarından: Maaseya, Eliya, Şemaya, Yehiel, Uzziya."));
trsuperobject.biblemap.put("b15_10_22", new trsuperobject(15,10,22,"Paşhuroğullarından: Elyoenay, Maaseya, İsmail, Netanel, Yozavat, Elasa."));
trsuperobject.biblemap.put("b15_10_23", new trsuperobject(15,10,23,"Levililerden: Yozavat, Şimi, Kelaya -Kelita- Petahya, Yahuda, Eliezer."));
trsuperobject.biblemap.put("b15_10_24", new trsuperobject(15,10,24,"Ezgicilerden: Elyaşiv. Tapınak kapı nöbetçilerinden: Şallum, Telem, Uri."));
trsuperobject.biblemap.put("b15_10_25", new trsuperobject(15,10,25,"Öbür İsraillilerden: Paroşoğullarından: Ramya, Yizziya, Malkiya, Miyamin, Elazar, Malkiya, Benaya."));
trsuperobject.biblemap.put("b15_10_26", new trsuperobject(15,10,26,"Elamoğullarından: Mattanya, Zekeriya, Yehiel, Avdi, Yeremot, Eliya."));
trsuperobject.biblemap.put("b15_10_27", new trsuperobject(15,10,27,"Zattuoğullarından: Elyoenay, Elyaşiv, Mattanya, Yeremot, Zavat, Aziza."));
trsuperobject.biblemap.put("b15_10_28", new trsuperobject(15,10,28,"Bevayoğullarından: Yehohanan, Hananya, Zabbay, Atlay."));
trsuperobject.biblemap.put("b15_10_29", new trsuperobject(15,10,29,"Banioğullarından: Meşullam, Malluk, Adaya, Yaşuv, Şeal, Yeremot."));
trsuperobject.biblemap.put("b15_10_30", new trsuperobject(15,10,30,"Pahat-Moavoğullarından: Adna, Kelal, Benaya, Maaseya, Mattanya, Besalel, Binnuy, Manaşşe."));
trsuperobject.biblemap.put("b15_10_31", new trsuperobject(15,10,31,"Harimoğullarından: Eliezer, Yişşiya, Malkiya, Şemaya, Şimon,"));
trsuperobject.biblemap.put("b15_10_32", new trsuperobject(15,10,32,"Benyamin, Malluk, Şemarya."));
trsuperobject.biblemap.put("b15_10_33", new trsuperobject(15,10,33,"Haşumoğullarından: Mattenay, Mattatta, Zavat, Elifelet, Yeremay, Manaşşe, Şimi."));
trsuperobject.biblemap.put("b15_10_34", new trsuperobject(15,10,34,"Banioğullarından: Maaday, Amram, Uel,"));
trsuperobject.biblemap.put("b15_10_35", new trsuperobject(15,10,35,"Benaya, Bedeya, Keluhu,"));
trsuperobject.biblemap.put("b15_10_36", new trsuperobject(15,10,36,"Vanya, Meremot, Elyaşiv,"));
trsuperobject.biblemap.put("b15_10_37", new trsuperobject(15,10,37,"Mattanya, Mattenay, Yaasay,"));
trsuperobject.biblemap.put("b15_10_38", new trsuperobject(15,10,38,"Bani, Binnuy, Şimi,"));
trsuperobject.biblemap.put("b15_10_39", new trsuperobject(15,10,39,"Şelemya, Natan, Adaya,"));
trsuperobject.biblemap.put("b15_10_40", new trsuperobject(15,10,40,"Maknadvay, Şaşay, Şaray,"));
trsuperobject.biblemap.put("b15_10_41", new trsuperobject(15,10,41,"Azarel, Şelemya, Şemarya,"));
trsuperobject.biblemap.put("b15_10_42", new trsuperobject(15,10,42,"Şallum, Amarya, Yusuf."));
trsuperobject.biblemap.put("b15_10_43", new trsuperobject(15,10,43,"Nevooğullarından: Yeiel, Mattitya, Zavat, Zevina, Yadday, Yoel, Benaya."));
trsuperobject.biblemap.put("b15_10_44", new trsuperobject(15,10,44,"Bunların hepsi yabancı kadınlarla evlenmişti. Bazılarının bu kadınlardan çocukları da vardı."));

}

}