package tr.bible;

public class trbible21 {

public trbible21() {

putmapbible21();

}

private void putmapbible21() {

trsuperobject.biblemap.put("b21_1_1", new trsuperobject(21,1,1,"Bunlar Yeruşalimde krallık yapan Davut oğlu Vaizin sözleridir:"));
trsuperobject.biblemap.put("b21_1_2", new trsuperobject(21,1,2,"‹‹Her şey boş, bomboş, bomboş!›› diyor Vaiz."));
trsuperobject.biblemap.put("b21_1_3", new trsuperobject(21,1,3,"Ne kazancı var insanınGüneşin altında harcadığı onca emekten?"));
trsuperobject.biblemap.put("b21_1_4", new trsuperobject(21,1,4,"Kuşaklar gelir, kuşaklar geçer,Ama dünya sonsuza dek kalır."));
trsuperobject.biblemap.put("b21_1_5", new trsuperobject(21,1,5,"Güneş doğar, güneş batar,Hep doğduğu yere koşar."));
trsuperobject.biblemap.put("b21_1_6", new trsuperobject(21,1,6,"Rüzgar güneye gider, kuzeye döner,Döne döne eserekHep aynı yolu izler."));
trsuperobject.biblemap.put("b21_1_7", new trsuperobject(21,1,7,"Bütün ırmaklar denize akar,Yine de deniz dolmaz.Irmaklar hep çıktıkları yere döner."));
trsuperobject.biblemap.put("b21_1_8", new trsuperobject(21,1,8,"Her şey yorucu,Sözcüklerle anlatılamayacak kadar.Göz görmekle doymuyor,Kulak işitmekle dolmuyor."));
trsuperobject.biblemap.put("b21_1_9", new trsuperobject(21,1,9,"Önce ne olduysa, yine olacak.Önce ne yapıldıysa, yine yapılacak.Güneşin altında yeni bir şey yok."));
trsuperobject.biblemap.put("b21_1_10", new trsuperobject(21,1,10,"Var mı kimsenin, ‹‹Bak bu yeni!›› diyebileceği bir şey?Her şey çoktan, bizden yıllar önce de vardı."));
trsuperobject.biblemap.put("b21_1_11", new trsuperobject(21,1,11,"Geçmiş kuşaklar anımsanmıyor,Gelecek kuşaklar da kendilerinden sonra gelenlerce anımsanmayacak."));
trsuperobject.biblemap.put("b21_1_12", new trsuperobject(21,1,12,"Ben Vaiz, Yeruşalimde İsrail kralıyken"));
trsuperobject.biblemap.put("b21_1_13", new trsuperobject(21,1,13,"kendimi göklerin altında yapılan her şeyi bilgece araştırıp incelemeye adadım. Tanrının uğraşsınlar diye insanlara verdiği çetin bir zahmettir bu."));
trsuperobject.biblemap.put("b21_1_14", new trsuperobject(21,1,14,"Güneşin altında yapılan bütün işleri gördüm; hepsi boştur, rüzgarı kovalamaya kalkışmaktır!"));
trsuperobject.biblemap.put("b21_1_15", new trsuperobject(21,1,15,"Eğri olan doğrultulamaz, eksik olan sayılamaz."));
trsuperobject.biblemap.put("b21_1_16", new trsuperobject(21,1,16,"Kendi kendime, ‹‹İşte, bilgeliğimi benden önce Yeruşalimde krallık yapan herkesten çok artırdım›› dedim, ‹‹Alabildiğine bilgi ve bilgelik edindim.››"));
trsuperobject.biblemap.put("b21_1_17", new trsuperobject(21,1,17,"Kendimi bilgi ve bilgeliği, deliliği ve akılsızlığı anlamaya adadım. Gördüm ki, bu da yalnızca rüzgarı kovalamaya kalkışmakmış."));
trsuperobject.biblemap.put("b21_1_18", new trsuperobject(21,1,18,"Çünkü çok bilgelik çok keder doğurur, bilgi arttıkça acı da artar."));
trsuperobject.biblemap.put("b21_2_1", new trsuperobject(21,2,1,"Kendi kendime, ‹‹Gel, zevki tat. İyi mi, değil mi, gör›› dedim. Ama gördüm ki, o da boş."));
trsuperobject.biblemap.put("b21_2_2", new trsuperobject(21,2,2,"Gülmeye, ‹‹Delilik››, zevke, ‹‹Ne işe yarar?›› dedim."));
trsuperobject.biblemap.put("b21_2_3", new trsuperobject(21,2,3,"İnsanların göklerin altında geçirdiği birkaç günlük ömürleri boyunca, yapacakları iyi bir şey olup olmadığını görünceye dek, bilgeliğimin önderliğinde, bedenimi şarapla nasıl canlandırayım, akılsızlığı nasıl ele alayım diye düşündüm durdum."));
trsuperobject.biblemap.put("b21_2_4", new trsuperobject(21,2,4,"Büyük işlere girdim. Kendime evler inşa ettim, bağlar diktim."));
trsuperobject.biblemap.put("b21_2_5", new trsuperobject(21,2,5,"Bahçeler, parklar yaptım, oralara türlü türlü meyve ağaçları diktim."));
trsuperobject.biblemap.put("b21_2_6", new trsuperobject(21,2,6,"Dal budak salan orman ağaçlarını sulamak için havuzlar yaptım."));
trsuperobject.biblemap.put("b21_2_7", new trsuperobject(21,2,7,"Kadın, erkek köleler satın aldım; evimde doğan kölelerim de vardı. Ayrıca benden önce Yeruşalimde yaşayan herkesten çok sığıra, davara sahip oldum."));
trsuperobject.biblemap.put("b21_2_8", new trsuperobject(21,2,8,"Altın, gümüş biriktirdim; kralların, illerin hazinelerini topladım. Kadın, erkek şarkıcılar ve erkeklerin özlemi olan bir harem edindim."));
trsuperobject.biblemap.put("b21_2_9", new trsuperobject(21,2,9,"Böylece büyük üne kavuştum, benden önce Yeruşalimde yaşayanların hepsini aştım. Bilgeliğimden de bir şey yitirmedim."));
trsuperobject.biblemap.put("b21_2_10", new trsuperobject(21,2,10,"Gözümün dilediği hiçbir şeyi kendimden esirgemedim.Gönlümü hiçbir zevkten alıkoymadım.Yaptığım her işten zevk aldı gönlüm.Bütün emeğimin ödülü bu oldu."));
trsuperobject.biblemap.put("b21_2_11", new trsuperobject(21,2,11,"Yaptığım bütün işlere,Çektiğim bütün emeklere bakınca,Gördüm ki, hepsi boş ve rüzgarı kovalamaya kalkışmakmış.Güneşin altında hiçbir kazanç yokmuş."));
trsuperobject.biblemap.put("b21_2_12", new trsuperobject(21,2,12,"Sonra bilgelik, delilik, akılsızlık nedir diye baktım;Çünkü kralın yerine geçecek kişiZaten yapılanın ötesinde ne yapabilir ki?"));
trsuperobject.biblemap.put("b21_2_13", new trsuperobject(21,2,13,"Işığın karanlıktan üstün olduğu gibiBilgeliğin de akılsızlıktan üstün olduğunu gördüm."));
trsuperobject.biblemap.put("b21_2_14", new trsuperobject(21,2,14,"Bilge nereye gittiğini görür,Ama akılsız karanlıkta yürür.İkisinin de aynı sonu paylaştığını gördüm."));
trsuperobject.biblemap.put("b21_2_15", new trsuperobject(21,2,15,"‹‹Akılsızın başına gelen, benim de başıma gelecek››Dedim kendi kendime, ‹‹Öyleyse kazancım ne bilgelikten?››‹‹Bu da boş›› dedim içimden."));
trsuperobject.biblemap.put("b21_2_16", new trsuperobject(21,2,16,"Çünkü akılsız gibi, bilge de uzun süre anılmaz,Gelecekte ikisi de unutulur.Nitekim bilge de akılsız gibi ölür!"));
trsuperobject.biblemap.put("b21_2_17", new trsuperobject(21,2,17,"Böylece hayattan nefret ettim.Çünkü güneşin altında yapılan iş çetindi bence.Her şey boş ve rüzgarı kovalamaya kalkışmakmış."));
trsuperobject.biblemap.put("b21_2_18", new trsuperobject(21,2,18,"Güneşin altında harcadığım bütün emekten nefret ettim. Çünkü her şeyi benden sonra gelecek olana bırakmak zorundayım."));
trsuperobject.biblemap.put("b21_2_19", new trsuperobject(21,2,19,"Kim bilir, bilge mi olacak, akılsız mı? Güneşin altında bilgeliğimi kullanarak harcadığım bütün emek üzerinde saltanat sürecek. Bu da boş."));
trsuperobject.biblemap.put("b21_2_20", new trsuperobject(21,2,20,"Bu yüzden güneşin altında harcadığım onca emeğe üzülmeye başladım."));
trsuperobject.biblemap.put("b21_2_21", new trsuperobject(21,2,21,"Çünkü biri bilgelik, bilgi ve beceriyle çalışır, sonunda her şeyini hiç emek vermemiş başka birine bırakmak zorunda kalır. Bu da boş ve büyük bir hüsrandır."));
trsuperobject.biblemap.put("b21_2_22", new trsuperobject(21,2,22,"Çünkü ne kazancı var adamın, güneşin altında harcadığı bunca emekten, bunca kafa yormaktan?"));
trsuperobject.biblemap.put("b21_2_23", new trsuperobject(21,2,23,"Günler boyunca çektiği zahmet acı ve dert doğurur. Gece bile içi rahat etmez. Bu da boş."));
trsuperobject.biblemap.put("b21_2_24", new trsuperobject(21,2,24,"İnsan için yemekten, içmekten ve yaptığı işten zevk almaktan daha iyi bir şey yoktur. Gördüm ki, bu da Tanrıdandır."));
trsuperobject.biblemap.put("b21_2_25", new trsuperobject(21,2,25,"Onsuz kim yiyebilir, kim zevk alabilir?"));
trsuperobject.biblemap.put("b21_2_26", new trsuperobject(21,2,26,"Çünkü Tanrı bilgiyi, bilgeliği, sevinci hoşnut kaldığı insana verir. Günahkâra ise, yığma, biriktirme zahmeti verir; biriktirdiklerini Tanrı'nın hoşnut kaldığı insanlara bıraksın diye. Bu da boş ve rüzgarı kovalamaya kalkışmakmış."));
trsuperobject.biblemap.put("b21_3_1", new trsuperobject(21,3,1,"Her şeyin mevsimi, göklerin altındaki her olayın zamanı vardır."));
trsuperobject.biblemap.put("b21_3_2", new trsuperobject(21,3,2,"Doğmanın zamanı var, ölmenin zamanı var.Dikmenin zamanı var, sökmenin zamanı var."));
trsuperobject.biblemap.put("b21_3_3", new trsuperobject(21,3,3,"Öldürmenin zamanı var, şifa vermenin zamanı var.Yıkmanın zamanı var, yapmanın zamanı var."));
trsuperobject.biblemap.put("b21_3_4", new trsuperobject(21,3,4,"Ağlamanın zamanı var, gülmenin zamanı var.Yas tutmanın zamanı var, oynamanın zamanı var."));
trsuperobject.biblemap.put("b21_3_5", new trsuperobject(21,3,5,"Taş atmanın zamanı var, taş toplamanın zamanı var.Kucaklaşmanın zamanı var, kucaklaşmamanın zamanı var."));
trsuperobject.biblemap.put("b21_3_6", new trsuperobject(21,3,6,"Aramanın zamanı var, vazgeçmenin zamanı var.Saklamanın zamanı var, atmanın zamanı var."));
trsuperobject.biblemap.put("b21_3_7", new trsuperobject(21,3,7,"Yırtmanın zamanı var, dikmenin zamanı var.Susmanın zamanı var, konuşmanın zamanı var."));
trsuperobject.biblemap.put("b21_3_8", new trsuperobject(21,3,8,"Sevmenin zamanı var, nefret etmenin zamanı var.Savaşın zamanı var, barışın zamanı var."));
trsuperobject.biblemap.put("b21_3_9", new trsuperobject(21,3,9,"Çalışanın harcadığı emekten ne kazancı var?"));
trsuperobject.biblemap.put("b21_3_10", new trsuperobject(21,3,10,"Tanrının uğraşsınlar diye insanlara verdiği zahmeti gördüm."));
trsuperobject.biblemap.put("b21_3_11", new trsuperobject(21,3,11,"O her şeyi zamanında güzel yaptı. İnsanların yüreğine sonsuzluk kavramını koydu. Yine de insan Tanrının yaptığı işi başından sonuna dek anlayamaz."));
trsuperobject.biblemap.put("b21_3_12", new trsuperobject(21,3,12,"İnsan için yaşamı boyunca mutlu olmaktan, iyi yaşamaktan daha iyi bir şey olmadığını biliyorum."));
trsuperobject.biblemap.put("b21_3_13", new trsuperobject(21,3,13,"Her insanın yiyip içmesi, yaptığı her işle doyuma ulaşması bir Tanrı armağanıdır."));
trsuperobject.biblemap.put("b21_3_14", new trsuperobject(21,3,14,"Tanrının yaptığı her şeyin sonsuza dek süreceğini biliyorum. Ona ne bir şey eklenebilir ne de ondan bir şey çıkarılabilir. Tanrı insanların kendisine saygı duymaları için bunu yapıyor."));
trsuperobject.biblemap.put("b21_3_15", new trsuperobject(21,3,15,"Şimdi ne oluyorsa, geçmişte de oldu,Ne olacaksa, daha önce de olmuştur.Tanrı geçmiş olayların hesabını soruyor."));
trsuperobject.biblemap.put("b21_3_16", new trsuperobject(21,3,16,"Güneşin altında bir şey daha gördüm:Adaletin ve doğruluğun yerini kötülük almış."));
trsuperobject.biblemap.put("b21_3_17", new trsuperobject(21,3,17,"İçimden ‹‹Tanrı doğruyu da, kötüyü de yargılayacaktır›› dedim,‹‹Çünkü her olayın, her eylemin zamanını belirledi.››"));
trsuperobject.biblemap.put("b21_3_18", new trsuperobject(21,3,18,"İnsanlara gelince, ‹‹Tanrı hayvan olduklarını görsünler diye insanları sınıyor›› diye düşündüm."));
trsuperobject.biblemap.put("b21_3_19", new trsuperobject(21,3,19,"Çünkü insanların başına gelen hayvanların da başına geliyor. Aynı sonu paylaşıyorlar. Biri nasıl ölüyorsa, öbürü de öyle ölüyor. Hepsi aynı soluğu taşıyor. İnsanın hayvandan üstünlüğü yoktur. Çünkü her şey boş."));
trsuperobject.biblemap.put("b21_3_20", new trsuperobject(21,3,20,"İkisi de aynı yere gidiyor; topraktan gelmiş, toprağa dönüyor."));
trsuperobject.biblemap.put("b21_3_21", new trsuperobject(21,3,21,"Kim biliyor insan ruhunun yukarıya çıktığını, hayvan ruhunun aşağıya, yeraltına indiğini?"));
trsuperobject.biblemap.put("b21_3_22", new trsuperobject(21,3,22,"Sonuçta insanın yaptığı işten zevk almasından daha iyi bir şey olmadığını gördüm. Çünkü onun payına düşen budur. Kendisinden sonra olacakları görmesi için kim onu geri getirebilir?"));
trsuperobject.biblemap.put("b21_4_1", new trsuperobject(21,4,1,"Güneşin altında yapılan baskılara bir daha baktım,Ezilenlerin gözyaşlarını gördüm;Avutanları yok,Güç ezenlerden yana,Avutanları yok."));
trsuperobject.biblemap.put("b21_4_2", new trsuperobject(21,4,2,"Çoktan ölmüş ölüleri,Hâlâ sağ olan yaşayanlardan daha mutlu gördüm."));
trsuperobject.biblemap.put("b21_4_3", new trsuperobject(21,4,3,"Ama henüz doğmamış,Güneşin altında yapılan kötülükleri görmemiş olanİkisinden de mutludur."));
trsuperobject.biblemap.put("b21_4_4", new trsuperobject(21,4,4,"Harcanan her emeğin, yapılan her ustaca işin ardında kıskançlık olduğunu gördüm. Bu da boş ve rüzgarı kovalamaya kalkışmakmış."));
trsuperobject.biblemap.put("b21_4_5", new trsuperobject(21,4,5,"Akılsız ellerini kavuşturup kendi kendini yer."));
trsuperobject.biblemap.put("b21_4_6", new trsuperobject(21,4,6,"Rahat kazanılan bir avuç dolusuZahmetle, rüzgarı kovalamaya kalkışarak kazanılanİki avuç dolusundan daha iyidir."));
trsuperobject.biblemap.put("b21_4_7", new trsuperobject(21,4,7,"Güneşin altında bir boş şey daha gördüm:"));
trsuperobject.biblemap.put("b21_4_8", new trsuperobject(21,4,8,"Yalnız bir adam vardı,Oğlu da kardeşi de yoktu.Çabaları dinmek nedir bilmezdi,Gözü zenginliğe doymazdı.‹‹Kimin için çalışıyorum,Neden kendimi zevkten yoksun bırakıyorum?›› diye sormazdı.Bu da boş ve çetin bir zahmettir."));
trsuperobject.biblemap.put("b21_4_9", new trsuperobject(21,4,9,"İki kişi bir kişiden iyidir,Çünkü emeklerine iyi karşılık alırlar."));
trsuperobject.biblemap.put("b21_4_10", new trsuperobject(21,4,10,"Biri düşerse, öteki kaldırır.Ama yalnız olup da düşenin vay haline!Onu kaldıran olmaz."));
trsuperobject.biblemap.put("b21_4_11", new trsuperobject(21,4,11,"Ayrıca iki kişi birlikte yatarsa, birbirini ısıtır.Ama tek başına yatan nasıl ısınabilir?"));
trsuperobject.biblemap.put("b21_4_12", new trsuperobject(21,4,12,"Yalnız biri yenik düşer,Ama iki kişi direnebilir.Üç kat iplik kolay kolay kopmaz."));
trsuperobject.biblemap.put("b21_4_13", new trsuperobject(21,4,13,"Yoksul ama bilge bir genç artık öğüt almayı bilmeyen kocamış akılsız kraldan iyidir."));
trsuperobject.biblemap.put("b21_4_14", new trsuperobject(21,4,14,"Çünkü genç, ülkesinde yoksulluk içinde doğsa bile cezaevinden krallığa yükselebilir."));
trsuperobject.biblemap.put("b21_4_15", new trsuperobject(21,4,15,"Güneşin altında yaşayan herkesin kralın yerine geçen genci izlediğini gördüm."));
trsuperobject.biblemap.put("b21_4_16", new trsuperobject(21,4,16,"Yeni kralın yönettiği halk sayısız olabilir. Yine de sonrakiler ondan hoşnut olmayabilir. Gerçekten bu da boş ve rüzgarı kovalamaya kalkışmaktır."));
trsuperobject.biblemap.put("b21_5_1", new trsuperobject(21,5,1,"Tanrının evine gittiğinde davranışına dikkat et. Yaptıkları kötülüğün farkında olmayan akılsızlar gibi kurban sunmak için değil, dinlemek için yaklaş."));
trsuperobject.biblemap.put("b21_5_2", new trsuperobject(21,5,2,"Ağzını çabuk açma,Tanrının önünde hemen konuya girme,Çünkü Tanrı gökte, sen yerdesin,Bu yüzden, az konuş."));
trsuperobject.biblemap.put("b21_5_3", new trsuperobject(21,5,3,"Çok tasa kötü düş,Çok söz akılsızlık doğurur."));
trsuperobject.biblemap.put("b21_5_4", new trsuperobject(21,5,4,"Tanrıya adak adayınca, yerine getirmekte gecikme. Çünkü O akılsızlardan hoşlanmaz. Adağını yerine getir!"));
trsuperobject.biblemap.put("b21_5_5", new trsuperobject(21,5,5,"Adamamak, adayıp da yerine getirmemekten iyidir."));
trsuperobject.biblemap.put("b21_5_6", new trsuperobject(21,5,6,"Ağzının seni günaha sürüklemesine izin verme. Ulağın önünde: ‹‹Adağım yanlıştı›› deme. Tanrı niçin senin sözlerine öfkelensin, yaptığın işi yok etsin?"));
trsuperobject.biblemap.put("b21_5_7", new trsuperobject(21,5,7,"Çünkü çok düş kurmak hayalciliğe ve laf kalabalığına yol açar; Tanrıya saygı göster. anlamına gelebilir."));
trsuperobject.biblemap.put("b21_5_8", new trsuperobject(21,5,8,"Bir yerde yoksullara baskı yapıldığını, adaletin ve doğruluğun çiğnendiğini görürsen şaşma; çünkü üstü gözeten daha üst biri var, onların da üstleri var."));
trsuperobject.biblemap.put("b21_5_9", new trsuperobject(21,5,9,"Tarlaların sürülmesini isteyen bir kral ülke için her bakımdan yararlıdır."));
trsuperobject.biblemap.put("b21_5_10", new trsuperobject(21,5,10,"Parayı seven paraya doymaz,Zenginliği seven kazancıyla yetinmez.Bu da boştur."));
trsuperobject.biblemap.put("b21_5_11", new trsuperobject(21,5,11,"Mal çoğaldıkça yiyeni de çoğalır.Sahibine ne yararı var, seyretmekten başka?"));
trsuperobject.biblemap.put("b21_5_12", new trsuperobject(21,5,12,"Az yesin, çok yesin işçi rahat uyur,Ama zenginin malı zengini uyutmaz."));
trsuperobject.biblemap.put("b21_5_13-14", new trsuperobject(21,5,13-14,"Güneşin altında acı bir kötülük gördüm:Sahibinin zararına biriktirilenVe bir talihsizlikle yok olup giden servet.Böyle bir servet sahibi baba olsa bile,Oğluna bir şey bırakamaz."));
trsuperobject.biblemap.put("b21_5_15", new trsuperobject(21,5,15,"Annesinin rahminden çıplak çıkar insan.Dünyaya nasıl geldiyse öyle gider,Emeğinden hiçbir şey götürmez elinde."));
trsuperobject.biblemap.put("b21_5_16", new trsuperobject(21,5,16,"Dünyaya nasıl geldiyse öyle gider insan.Bu da acı bir kötülüktür.Ne kazancı var yel için zahmet çekmekten?"));
trsuperobject.biblemap.put("b21_5_17", new trsuperobject(21,5,17,"Ömrü boyunca büyük üzüntü, hastalık, öfke içindeKaranlıkta yiyor."));
trsuperobject.biblemap.put("b21_5_18", new trsuperobject(21,5,18,"Gördüm ki, iyi ve güzel olan şu: Tanrının insana verdiği birkaç günlük ömür boyunca yemek, içmek, güneşin altında harcadığı emekten zevk almak. Çünkü insanın payına düşen budur."));
trsuperobject.biblemap.put("b21_5_19", new trsuperobject(21,5,19,"Üstelik Tanrı bir insana mal mülk veriyor, onu yemesi, ödülünü alması, yaptığı işten mutluluk duyması için ona güç veriyorsa, bu bir Tanrı armağanıdır."));
trsuperobject.biblemap.put("b21_5_20", new trsuperobject(21,5,20,"Bu yüzden insan, geçen ömrünü pek düşünmez. Çünkü Tanrı onun yüreğini mutlulukla meşgul eder."));
trsuperobject.biblemap.put("b21_6_1", new trsuperobject(21,6,1,"Güneşin altında insana ağır gelen bir kötülük gördüm:"));
trsuperobject.biblemap.put("b21_6_2", new trsuperobject(21,6,2,"Adam vardır, Tanrı kendisine mal, mülk, saygınlık verir, yerine gelmeyecek isteği yoktur. Ama Tanrı yemesine izin vermez; bir yabancı yer. Bu da boş ve acı bir derttir."));
trsuperobject.biblemap.put("b21_6_3", new trsuperobject(21,6,3,"Bir adam yüz çocuk babası olup uzun yıllar yaşamış, ama uzun ömrüne karşılık, zenginliğin tadını çıkaramamış, bir mezara bile gömülmemişse, düşük çocuk ondan iyidir derim."));
trsuperobject.biblemap.put("b21_6_4", new trsuperobject(21,6,4,"Çünkü düşük çocuk boş yere doğuyor, karanlık içinde geçip gidiyor, adı karanlığa gömülüyor."));
trsuperobject.biblemap.put("b21_6_5-6", new trsuperobject(21,6,5-6,"Ne güneş yüzü görüyor, ne de bir şey tanıyor. Öbür adam iki kez biner yıl yaşasa bile mutluluk duymaz, düşük çocuk ondan rahattır. Hepsi aynı yere gitmiyor mu?"));
trsuperobject.biblemap.put("b21_6_7", new trsuperobject(21,6,7,"İnsan hep boğazı için çalışır,Yine de doymaz."));
trsuperobject.biblemap.put("b21_6_8", new trsuperobject(21,6,8,"Bilgenin akılsızdan ne üstünlüğü var?Yoksul başkasına nasıl davranacağını bilmekle ne yarar sağlar?"));
trsuperobject.biblemap.put("b21_6_9", new trsuperobject(21,6,9,"Gözün gördüğü gönlün çektiğinden iyidir.Bu da boş ve rüzgarı kovalamaya kalkışmaktır."));
trsuperobject.biblemap.put("b21_6_10", new trsuperobject(21,6,10,"Ne varsa, adı çoktan konmuştur,İnsanın da ne olduğu biliniyor.Kimse kendinden güçlü olanla çekişemez."));
trsuperobject.biblemap.put("b21_6_11", new trsuperobject(21,6,11,"Söz çoğaldıkça anlam azalır,Bunun kime yararı olur?"));
trsuperobject.biblemap.put("b21_6_12", new trsuperobject(21,6,12,"Çünkü gölge gibi gelip geçen kısa ve boş ömründe insana neyin yararlı olduğunu kim bilebilir? Bir adama kendisinden sonra güneşin altında neler olacağını kim söyleyebilir?"));
trsuperobject.biblemap.put("b21_7_1", new trsuperobject(21,7,1,"İyi ad hoş kokulu yağdan,Ölüm günü doğum gününden iyidir."));
trsuperobject.biblemap.put("b21_7_2", new trsuperobject(21,7,2,"Yas evine gitmek, şölen evine gitmekten iyidir.Çünkü her insanın sonu ölümdür,Yaşayan herkes bunu aklında tutmalı."));
trsuperobject.biblemap.put("b21_7_3", new trsuperobject(21,7,3,"Üzüntü gülmekten iyidir,Çünkü yüz mahzun olunca yürek sevinir."));
trsuperobject.biblemap.put("b21_7_4", new trsuperobject(21,7,4,"Bilge kişinin aklı yas evindedir,Akılsızın aklıysa şenlik evinde."));
trsuperobject.biblemap.put("b21_7_5", new trsuperobject(21,7,5,"Bilgenin azarını işitmek,Akılsızın türküsünü işitmekten iyidir."));
trsuperobject.biblemap.put("b21_7_6", new trsuperobject(21,7,6,"Çünkü akılsızın gülmesi,Kazanın altındaki çalıların çatırtısı gibidir.Bu da boştur."));
trsuperobject.biblemap.put("b21_7_7", new trsuperobject(21,7,7,"Haksız kazanç bilgeyi delirtir,Rüşvet karakteri bozar."));
trsuperobject.biblemap.put("b21_7_8", new trsuperobject(21,7,8,"Bir olayın sonu başlangıcından iyidir.Sabırlı kibirliden iyidir."));
trsuperobject.biblemap.put("b21_7_9", new trsuperobject(21,7,9,"Çabuk öfkelenme,Çünkü öfke akılsızların bağrında barınır."));
trsuperobject.biblemap.put("b21_7_10", new trsuperobject(21,7,10,"‹‹Neden geçmiş günler bugünlerden iyiydi?›› diye sorma,Çünkü bu bilgece bir soru değil."));
trsuperobject.biblemap.put("b21_7_11", new trsuperobject(21,7,11,"Bilgelik miras kadar iyidir,Güneşi gören herkes için yararlıdır."));
trsuperobject.biblemap.put("b21_7_12", new trsuperobject(21,7,12,"Bilgelik siperdir, para da siper,Bilginin yararı ise şudur:Bilgelik ona sahip olan kişinin yaşamını korur."));
trsuperobject.biblemap.put("b21_7_13", new trsuperobject(21,7,13,"Tanrının yaptığını düşün:Onun eğrilttiğini kim doğrultabilir?"));
trsuperobject.biblemap.put("b21_7_14", new trsuperobject(21,7,14,"İyi günde mutlu ol,Ama kötü günde dikkatle düşün;Tanrı birini öbürü gibi yaptı ki,İnsan kendisinden sonra neler olacağını bilmesin."));
trsuperobject.biblemap.put("b21_7_15", new trsuperobject(21,7,15,"Boş ömrümde şunları gördüm:Doğru insan doğruluğuna karşın ölüyor,Kötü insanın ise, kötülüğüne karşın ömrü uzuyor."));
trsuperobject.biblemap.put("b21_7_16", new trsuperobject(21,7,16,"Ne çok doğru ol ne de çok bilge.Niçin kendini yok edesin?"));
trsuperobject.biblemap.put("b21_7_17", new trsuperobject(21,7,17,"Ne çok kötü ol ne de akılsız.Niçin vaktinden önce ölesin?"));
trsuperobject.biblemap.put("b21_7_18", new trsuperobject(21,7,18,"Birini tutman iyidir,Öbüründen de elini çekme.Çünkü Tanrıya saygı duyan ikisini de başarır."));
trsuperobject.biblemap.put("b21_7_19", new trsuperobject(21,7,19,"Bilgelik, bilge kişiyi kentteki on yöneticiden daha güçlü kılar."));
trsuperobject.biblemap.put("b21_7_20", new trsuperobject(21,7,20,"Çünkü yeryüzünde hep iyilik yapan,Hiç günah işlemeyen doğru insan yoktur."));
trsuperobject.biblemap.put("b21_7_21", new trsuperobject(21,7,21,"İnsanların söylediği her söze aldırma,Yoksa uşağının bile sana sövdüğünü duyabilirsin."));
trsuperobject.biblemap.put("b21_7_22", new trsuperobject(21,7,22,"Çünkü sen de birçok kezBaşkalarına sövdüğünü pekâlâ biliyorsun."));
trsuperobject.biblemap.put("b21_7_23", new trsuperobject(21,7,23,"Bütün bunları bilgelikle denedim:‹‹Bilge olacağım›› dedim.Ama bu beni aşıyordu."));
trsuperobject.biblemap.put("b21_7_24", new trsuperobject(21,7,24,"Bilgelik denen şeyUzak ve çok derindir, onu kim bulabilir?"));
trsuperobject.biblemap.put("b21_7_25", new trsuperobject(21,7,25,"Böylece, bilgelik ve çözüm aramaya, incelemeye, kavramaya,Kötülüğün akılsızlık, akılsızlığın delilik olduğunu anlamaya kafa yordum."));
trsuperobject.biblemap.put("b21_7_26", new trsuperobject(21,7,26,"Kimi kadını ölümden acı buldum.O kadın ki, kendisi tuzak, yüreği kapan, elleri zincirdir.Tanrının hoşnut kaldığı insan ondan kaçar,Günah işleyense ona tutsak olur."));
trsuperobject.biblemap.put("b21_7_27", new trsuperobject(21,7,27,"Vaiz diyor ki, ‹‹Şunu gördüm:Bir çözüm bulmak içinBir şeyi öbürüne eklerken"));
trsuperobject.biblemap.put("b21_7_28", new trsuperobject(21,7,28,"Araştırıp hâlâ bulamazken-Binde bir adam buldum,Ama aralarında bir kadın bulamadım."));
trsuperobject.biblemap.put("b21_7_29", new trsuperobject(21,7,29,"Bulduğum tek şey:Tanrı insanları doğru yarattı,Oysa onlar hâlâ karmaşık çözümler arıyorlar.››"));
trsuperobject.biblemap.put("b21_8_1", new trsuperobject(21,8,1,"Bilge insan gibisi var mı?Kim olup bitenlerin anlamını bilebilir?Bilgelik insanın yüzünü aydınlatır,Sert görünüşünü değiştirir."));
trsuperobject.biblemap.put("b21_8_2", new trsuperobject(21,8,2,"Kralın buyruğuna uy, diyorum. Çünkü Tanrının önünde ant içtin."));
trsuperobject.biblemap.put("b21_8_3", new trsuperobject(21,8,3,"Kralın huzurundan ayrılmak için acele etme. Kötülüğe bulaşma. Çünkü o dilediği her şeyi yapar."));
trsuperobject.biblemap.put("b21_8_4", new trsuperobject(21,8,4,"Kralın sözünde güç vardır. Kim ona, ‹‹Ne yapıyorsun?›› diyebilir?"));
trsuperobject.biblemap.put("b21_8_5", new trsuperobject(21,8,5,"Onun buyruğuna uyan zarar görmez.Bilge kişi bunun zamanını ve yolunu bilir."));
trsuperobject.biblemap.put("b21_8_6", new trsuperobject(21,8,6,"Çünkü her işin bir zamanı ve yolu vardır.İnsanın derdi kendine yeter."));
trsuperobject.biblemap.put("b21_8_7", new trsuperobject(21,8,7,"Kimse geleceği bilmez,Kim kime geleceği bildirebilir?"));
trsuperobject.biblemap.put("b21_8_8", new trsuperobject(21,8,8,"Rüzgarı tutup ona egemen olmaya kimsenin gücü yetmediği gibi,Ölüm gününe egemen olmaya da kimsenin gücü yetmez.Savaştan kaçış olmadığı gibi, kötülük de sahibini kurtaramaz."));
trsuperobject.biblemap.put("b21_8_9", new trsuperobject(21,8,9,"Bütün bunları gördüm ve güneşin altında yapılan her iş üzerinde kafa yordum. Gün gelir, insanın insana egemenliği kendine zarar verir."));
trsuperobject.biblemap.put("b21_8_10", new trsuperobject(21,8,10,"Bir de kötülerin gömüldüğünü gördüm. Kutsal yere girip çıkar, kötülük yaptıkları kentte övülürlerdi. Bu da boş."));
trsuperobject.biblemap.put("b21_8_11", new trsuperobject(21,8,11,"Suçlu çabuk yargılanmazsa, insanlar kötülük etmek için cesaret bulur."));
trsuperobject.biblemap.put("b21_8_12", new trsuperobject(21,8,12,"Günahlı yüz kez kötülük edip uzun yaşasa bile, Tanrıdan korkanların, Onun önünde saygıyla duranların iyilik göreceğini biliyorum."));
trsuperobject.biblemap.put("b21_8_13", new trsuperobject(21,8,13,"Oysa kötü, Tanrıdan korkmadığı için iyilik görmeyecek, gölge gibi olan ömrü uzamayacaktır."));
trsuperobject.biblemap.put("b21_8_14", new trsuperobject(21,8,14,"Yeryüzünde boş bir şey daha var: Kötülerin hak ettiği doğruların, doğruların hak ettiğiyse kötülerin başına geliyor. Bu da boş, diyorum."));
trsuperobject.biblemap.put("b21_8_15", new trsuperobject(21,8,15,"Mutluluğu övgüye değer buldum. Çünkü güneşin altında insan için yiyip içmekten, mutlu olmaktan daha iyi bir şey yoktur. Çünkü Tanrının güneşin altında kendisine verdiği ömür boyunca çektiği zahmetten insana kalacak olan budur."));
trsuperobject.biblemap.put("b21_8_16", new trsuperobject(21,8,16,"Bilgeliği ve dünyada çekilen zahmeti anlamak için kafamı yorunca -öyleleri var ki, gece gündüz gözüne uyku girmez-"));
trsuperobject.biblemap.put("b21_8_17", new trsuperobject(21,8,17,"Tanrı'nın yaptığı her şeyi gördüm. İnsan güneşin altında olup bitenleri keşfedemez. Arayıp bulmak için ne kadar çaba harcarsa harcasın, yine de anlamını bulamaz. Bilge kişi anladığını söylese bile gerçekten kavrayamaz."));
trsuperobject.biblemap.put("b21_9_1", new trsuperobject(21,9,1,"Böylece bütün bunları düşünüp taşındım ve şu sonuca vardım: Doğrular, bilgeler ve yaptıkları her şey Tanrının elindedir. Onları sevginin mi, nefretin mi beklediğini kimse bilmez."));
trsuperobject.biblemap.put("b21_9_2", new trsuperobject(21,9,2,"Herkesin başına aynı şey geliyor. Doğrunun, iyinin, kötünün, temizin, kirlinin, kurban sunanla sunmayanın başına gelen şey aynı.  İyi insana ne oluyorsa, günahlıya da oluyor;Ant içene ne oluyorsa, ant içmekten korkana da aynısı oluyor."));
trsuperobject.biblemap.put("b21_9_3", new trsuperobject(21,9,3,"Güneşin altında yapılan işlerin tümünün kötü yanı şu ki, herkesin başına aynı şey geliyor. Üstelik insanların içi kötülük doludur, yaşadıkları sürece içlerinde delilik vardır. Ardından ölüp gidiyorlar."));
trsuperobject.biblemap.put("b21_9_4", new trsuperobject(21,9,4,"Yaşayanlar arasındaki herkes için umut vardır. Evet, sağ köpek ölü aslandan iyidir!"));
trsuperobject.biblemap.put("b21_9_5", new trsuperobject(21,9,5,"Çünkü yaşayanlar öleceğini biliyor,Ama ölüler hiçbir şey bilmiyor.Onlar için artık ödül yoktur,Anıları bile unutulmuştur."));
trsuperobject.biblemap.put("b21_9_6", new trsuperobject(21,9,6,"Sevgileri, nefretleri,Kıskançlıkları çoktan bitmiştir.Güneşin altında yapılanlardanBir daha payları olmayacaktır."));
trsuperobject.biblemap.put("b21_9_7", new trsuperobject(21,9,7,"Git, sevinçle ekmeğini ye, neşeyle şarabını iç. Çünkü yaptıkların baştan beri Tanrının hoşuna gitti."));
trsuperobject.biblemap.put("b21_9_8", new trsuperobject(21,9,8,"Giysilerin hep ak olsun. Başından zeytinyağı eksilmesin."));
trsuperobject.biblemap.put("b21_9_9", new trsuperobject(21,9,9,"Güneşin altında Tanrının sana verdiği boş ömrün bütün günlerini, bütün anlamsız günlerini sevdiğin karınla güzel güzel yaşayarak geçir. Çünkü hayattan ve güneşin altında harcadığın emekten payına düşecek olan budur."));
trsuperobject.biblemap.put("b21_9_10", new trsuperobject(21,9,10,"Çalışmak için eline ne geçerse, var gücünle çalış. Çünkü gitmekte olduğun ölüler diyarında iş, tasarı, bilgi ve bilgelik yoktur."));
trsuperobject.biblemap.put("b21_9_11", new trsuperobject(21,9,11,"Güneşin altında bir şey daha gördüm:Yarışı hızlı koşanlar,Savaşı yiğitler,Ekmeği bilgeler,Serveti akıllılar,Beğeniyi bilgililer kazanmaz.Ama zaman ve şans hepsinin önüne çıkar."));
trsuperobject.biblemap.put("b21_9_12", new trsuperobject(21,9,12,"Dahası insan kendi vaktini bilmez:Balığın acımasız ağa, kuşun kapana düştüğü gibi,İnsanlar da üzerlerine ansızın çöken kötü zamana yakalanırlar."));
trsuperobject.biblemap.put("b21_9_13", new trsuperobject(21,9,13,"Güneşin altında bilgelik olarak şunu da gördüm, beni çok etkiledi:"));
trsuperobject.biblemap.put("b21_9_14", new trsuperobject(21,9,14,"Çok az insanın yaşadığı küçük bir kent vardı. Güçlü bir kral saldırıp onu kuşattı. Karşısına büyük rampalar kurdu."));
trsuperobject.biblemap.put("b21_9_15", new trsuperobject(21,9,15,"Kentte yoksul ama bilge bir adam vardı. Bilgeliğiyle kenti kurtardı. Ne var ki, kimse bu yoksul adamı anmadı."));
trsuperobject.biblemap.put("b21_9_16", new trsuperobject(21,9,16,"Bunun üzerine, ‹‹Bilgelik güçten iyidir›› dedim, ‹‹Ne yazık ki, yoksul insanın bilgeliği küçümseniyor, söyledikleri dikkate alınmıyor.››"));
trsuperobject.biblemap.put("b21_9_17", new trsuperobject(21,9,17,"Bilgenin sessizce söylediği sözler,Akılsızlar arasındaki önderin bağırışından iyidir."));
trsuperobject.biblemap.put("b21_9_18", new trsuperobject(21,9,18,"Bilgelik silahtan iyidir,Ama bir deli çıkar, her şeyi berbat eder."));
trsuperobject.biblemap.put("b21_10_1", new trsuperobject(21,10,1,"Ölü sinekler attarın ıtırını kokutur.Biraz aptallık da bilgeliği ve saygınlığı bastırır."));
trsuperobject.biblemap.put("b21_10_2", new trsuperobject(21,10,2,"Bilgenin yüreği hep doğruya eğilimlidir,Akılsızın ise, hep yanlışa."));
trsuperobject.biblemap.put("b21_10_3", new trsuperobject(21,10,3,"Yolda yürürken bile akılsızın aklı kıttır,Akılsız olduğunu herkese gösterir."));
trsuperobject.biblemap.put("b21_10_4", new trsuperobject(21,10,4,"Yöneticinin öfkesi sana karşı alevlenirse,Yerinden ayrılma;Çünkü serinkanlılık büyük yanlışları bastırır."));
trsuperobject.biblemap.put("b21_10_5", new trsuperobject(21,10,5,"Güneşin altında gördüğüm bir haksızlık var,Yöneticiden kaynaklanan bir yanlışı andırıyor:"));
trsuperobject.biblemap.put("b21_10_6", new trsuperobject(21,10,6,"Zenginler düşük makamlarda otururken,Aptallar yüksek makamlara atanıyor."));
trsuperobject.biblemap.put("b21_10_7", new trsuperobject(21,10,7,"Köleleri at sırtında,Önderleri yerde köleler gibi yürürken gördüm."));
trsuperobject.biblemap.put("b21_10_8", new trsuperobject(21,10,8,"Çukur kazan içine kendi düşer,Duvarda gedik açanı yılan sokar."));
trsuperobject.biblemap.put("b21_10_9", new trsuperobject(21,10,9,"Taş çıkaran taştan incinir,Odun yaran tehlikeye girer."));
trsuperobject.biblemap.put("b21_10_10", new trsuperobject(21,10,10,"Balta körse, ağzı bilenmemişse,Daha çok güç gerektirir;Ama bilgelik başarı doğurur."));
trsuperobject.biblemap.put("b21_10_11", new trsuperobject(21,10,11,"Yılan büyü yapılmadan önce sokarsa,Büyücünün yararı olmaz."));
trsuperobject.biblemap.put("b21_10_12", new trsuperobject(21,10,12,"Bilgenin ağzından çıkan sözler benimsenir,Oysa akılsız kendi ağzıyla yıkımına yol açar."));
trsuperobject.biblemap.put("b21_10_13", new trsuperobject(21,10,13,"Sözünün başı aptallık,Sonu zırdeliliktir."));
trsuperobject.biblemap.put("b21_10_14", new trsuperobject(21,10,14,"Akılsız konuştukça konuşur.  Kimse ne olacağını bilmez.Kim ona kendisinden sonra ne olacağını bildirebilir?"));
trsuperobject.biblemap.put("b21_10_15", new trsuperobject(21,10,15,"Akılsızın emeği kendini öylesine yıpratır ki,Kente bile nasıl gideceğini bilemez."));
trsuperobject.biblemap.put("b21_10_16", new trsuperobject(21,10,16,"Kralın bir çocuksafç,Önderlerin sabah şölen veriyorsa, vay sana, ey ülke!"));
trsuperobject.biblemap.put("b21_10_17", new trsuperobject(21,10,17,"Kralın soyluysa,Önderlerin sarhoşluk için değilGüçlenmek için vaktinde yemek yiyorsa, ne mutlu sana, ey ülke!"));
trsuperobject.biblemap.put("b21_10_18", new trsuperobject(21,10,18,"Tembellikten dam çöker,Miskinlikten çatı akar."));
trsuperobject.biblemap.put("b21_10_19", new trsuperobject(21,10,19,"Şölen eğlenmek için yapılır,Şarap yaşama sevinç katar,Paraysa her ihtiyacı karşılar."));
trsuperobject.biblemap.put("b21_10_20", new trsuperobject(21,10,20,"İçinden bile krala sövme,Yatak odanda zengine lanet etme,Çünkü gökte uçan kuşlar haber taşır,Kanatlı varlıklar söylediğini aktarır."));
trsuperobject.biblemap.put("b21_11_1", new trsuperobject(21,11,1,"Ekmeğini suya at,Çünkü günler sonra onu bulursun. alıp paranı ticarete yatırarak geçimini sağla›› ya da ‹‹İhtiyacı olanlara ver›› anlamına gelir."));
trsuperobject.biblemap.put("b21_11_2", new trsuperobject(21,11,2,"Yedi, hatta sekiz kişiye pay ver,Çünkü ülkenin başına ne felaket geleceğini bilemezsin."));
trsuperobject.biblemap.put("b21_11_3", new trsuperobject(21,11,3,"Bulutlar su yüklüyse,Yeryüzüne döker yağmurlarını.Ağaç ister güneye ister kuzeye devrilsin,Devrildiği yerde kalır."));
trsuperobject.biblemap.put("b21_11_4", new trsuperobject(21,11,4,"Rüzgarı gözeten ekmez,Bulutlara bakan biçmez."));
trsuperobject.biblemap.put("b21_11_5", new trsuperobject(21,11,5,"Ana rahmindeki çocuğun nasıl ruh ve beden aldığını bilmediğin gibi,Her şeyi yaratan Tanrının yaptıklarını da bilemezsin."));
trsuperobject.biblemap.put("b21_11_6", new trsuperobject(21,11,6,"Tohumunu sabah ek,Akşam da elin boş durmasın.Çünkü bu mu iyi, şu mu,Yoksa ikisi de aynı sonucu mu verecek, bilemezsin."));
trsuperobject.biblemap.put("b21_11_7", new trsuperobject(21,11,7,"Işık tatlıdır,Güneşi görmek güzeldir."));
trsuperobject.biblemap.put("b21_11_8", new trsuperobject(21,11,8,"Evet, insan uzun yıllar yaşarsa,Sevinçle yaşasın.Ama karanlık günleri unutmasın,Çünkü onlar da az değil.Gelecek her şey boştur."));
trsuperobject.biblemap.put("b21_11_9", new trsuperobject(21,11,9,"Ey delikanlı, gençliğinle sevin,Bırak gençlik günlerinde yüreğin sevinç duysun.Gönlünün isteklerini, gözünün gördüklerini izle,Ama bil ki, bütün bunlar için Tanrı seni yargılayacaktır."));
trsuperobject.biblemap.put("b21_11_10", new trsuperobject(21,11,10,"Öyleyse at tasayı yüreğinden,Uzaklaştır derdi bedeninden.Çünkü gençlik de dinçlik de boştur."));
trsuperobject.biblemap.put("b21_12_1-2", new trsuperobject(21,12,1-2,"Bu yüzden zor günler gelmeden,‹‹Zevk almıyorum›› diyeceğin yıllar yaklaşmadan,Güneş, ışık, ay ve yıldızlar kararmadanVe yağmurdan sonra bulutlar geri dönmeden,Gençlik günlerinde seni yaratanı anımsa."));
trsuperobject.biblemap.put("b21_12_3", new trsuperobject(21,12,3,"O gün, evi bekleyenler titreyecek,Güçlüler eğilecek,Öğütücüler azaldığı için duracak,Pencereden bakanlar kararacak."));
trsuperobject.biblemap.put("b21_12_4", new trsuperobject(21,12,4,"Değirmen sesi yavaşlayınca,Sokağa açılan çift kapı kapanacak,İnsanlar kuş sesiyle uyanacak,Ama şarkıların sesini duyamayacaklar."));
trsuperobject.biblemap.put("b21_12_5", new trsuperobject(21,12,5,"Dahası yüksek yerden,Sokaktaki tehlikelerden korkacaklar;Badem ağacı çiçek açacak,Çekirge ağırlaşacak,Tutku zayıflayacak.Çünkü insan sonsuzluk evine gidecek,Yas tutanlar sokakta dolaşacak. kuş gibi yükselecek››."));
trsuperobject.biblemap.put("b21_12_6", new trsuperobject(21,12,6,"Gümüş tel kopmadan,Altın tas kırılmadan,Testi çeşmede parçalanmadan,Kuyu makarası kırılmadan,"));
trsuperobject.biblemap.put("b21_12_7", new trsuperobject(21,12,7,"Toprak geldiği yere dönmeden,Ruh onu veren Tanrıya dönmeden,Seni yaratanı anımsa."));
trsuperobject.biblemap.put("b21_12_8", new trsuperobject(21,12,8,"‹‹Her şey boş›› diyor Vaiz, ‹‹Bomboş!››"));
trsuperobject.biblemap.put("b21_12_9", new trsuperobject(21,12,9,"Vaiz yalnız bilge değildi, bildiklerini halka da öğretiyordu. Hesap etti, araştırdı ve birçok özdeyişi düzene soktu."));
trsuperobject.biblemap.put("b21_12_10", new trsuperobject(21,12,10,"Güzel sözler bulmaya çalıştı. Yazdıkları gerçek ve doğrudur."));
trsuperobject.biblemap.put("b21_12_11", new trsuperobject(21,12,11,"Bilgelerin sözleri üvendire gibidir, derledikleri özdeyişlerse, iyi çakılan çivi gibi; bir tek Çoban tarafından verilmişler."));
trsuperobject.biblemap.put("b21_12_12", new trsuperobject(21,12,12,"Bunların dışındakilerden sakın, evladım. Çok kitap yazmanın sonu yoktur, fazla araştırma da bedeni yıpratır."));
trsuperobject.biblemap.put("b21_12_13", new trsuperobject(21,12,13,"Her şey duyuldu, sonuç şu:Tanrıya saygı göster, buyruklarını yerine getir,Çünkü her insanın görevi budur."));
trsuperobject.biblemap.put("b21_12_14", new trsuperobject(21,12,14,"Tanrı her işi, her gizli şeyi yargılayacaktır,İster iyi ister kötü olsun."));

}

}