package tr.bible;

public class trbible25 {

public trbible25() {

putmapbible25();

}

private void putmapbible25() {

trsuperobject.biblemap.put("b25_1_1", new trsuperobject(25,1,1,"O kent ki, insan doluydu,Nasıl da tek başına kaldı şimdi!Büyüktü uluslar arasında,Dul kadına döndü!Soyluydu iller arasında,Angarya altına düştü!"));
trsuperobject.biblemap.put("b25_1_2", new trsuperobject(25,1,2,"Geceleyin acı acı ağlıyor,Yanaklarında gözyaşı;Avutan tek kişi bile yokBunca oynaşı arasında.Dostları ona hainlik etti,Düşman oldu."));
trsuperobject.biblemap.put("b25_1_3", new trsuperobject(25,1,3,"Yahuda acı çekip ağır kölelik ettikten sonraSürgün edildi,Ulusların arasında oturuyor,Ama rahat bulamıyor.O sıkıntıdayken ardına düşenler ona yetişti."));
trsuperobject.biblemap.put("b25_1_4", new trsuperobject(25,1,4,"Siyona giden yollar yas tutuyor,Çünkü bayramlara gelen yok.Bütün kapıları ıssız, kâhinleri inliyor,Erden kızları sıkıntıda, kendisi de acı çekiyor."));
trsuperobject.biblemap.put("b25_1_5", new trsuperobject(25,1,5,"Hasımları başa geçti, düşmanları rahat içinde.Çok isyan ettiği için RAB ona acı çektiriyor,Yavruları hasımlarının gözü önünde sürgüne gitti."));
trsuperobject.biblemap.put("b25_1_6", new trsuperobject(25,1,6,"Siyon kızının bütün güzelliği uçtu,Önderleri otlak bulamayan geyiklere döndü,Dermanları kesildiKendilerini kovalayanların önünde."));
trsuperobject.biblemap.put("b25_1_7", new trsuperobject(25,1,7,"Yeruşalim sıkıntı içinde başıboş dolaşırkenEski günlerdeki varlığını anımsıyor.Halkı hasmının eline düşüp deYardımına koşan çıkmayınca,Hasımları haline bakıpYıkılışına güldüler."));
trsuperobject.biblemap.put("b25_1_8", new trsuperobject(25,1,8,"Yeruşalim büyük günah işledi,Bu yüzden kirlendi.Ona saygı duyanların hepsiŞimdi onu hor görüyor,Çünkü onu çıplak gördüler.O da inleyip öbür yana dönüyor."));
trsuperobject.biblemap.put("b25_1_9", new trsuperobject(25,1,9,"Kirliliği eteklerindeydi,Sonunu düşünmedi;Bu yüzden düşüşü korkunç oldu,Avutanı yok.‹‹Ya RAB, düşkün halimi gör,Çünkü düşmanım kazandı!››"));
trsuperobject.biblemap.put("b25_1_10", new trsuperobject(25,1,10,"Değerli her şeyine düşman el uzattı.Tapınağına başka ulusların girdiğini gördü,Topluluğuna girmesini yasakladığın uluslar."));
trsuperobject.biblemap.put("b25_1_11", new trsuperobject(25,1,11,"Halkı inleyip ekmek arıyor,Yeniden güçlerine kavuşmak içinDeğerli neleri varsa ekmekle değiştiler;‹‹Bak da gör, ya RAB, ne kadar sefil oldum.››"));
trsuperobject.biblemap.put("b25_1_12", new trsuperobject(25,1,12,"‹‹Ey sizler, yoldan geçenler,Sizin için önemi yok mu bunun?Bakın da görün, başıma gelen dert gibisi var mı?Öyle bir dert ki, RAB öfkesinin alevlendiği günBaşıma yağdırdı onu. başınıza da gelmesin.››"));
trsuperobject.biblemap.put("b25_1_13", new trsuperobject(25,1,13,"Ateş saldı yukarıdan,Kemiklerimin içine işledi ateş;Ağ serdi ayaklarıma,Geri çevirdi beni;Mahvetti, baygın kaldım bütün gün."));
trsuperobject.biblemap.put("b25_1_14", new trsuperobject(25,1,14,"İsyanlarım boyunduruğa döndü,RABbin eliyle birbirine tutturulupBoynuma geçirildi, gücüm tükendi.Rab karşı duramadığımİnsanların eline verdi beni."));
trsuperobject.biblemap.put("b25_1_15", new trsuperobject(25,1,15,"Hiçe saydı beni savunan yiğitleri,Gençlerimi kırıp geçirmek için çağrı yaptı ordulara,Rab erden Yahuda kızınıÜzüm sıkma çukurunda çiğnedi adeta."));
trsuperobject.biblemap.put("b25_1_16", new trsuperobject(25,1,16,"‹‹Ağlıyorum bunlara,Gözlerimden yaşlar boşanıyor;Çünkü beni avutan,Canımı tazeleyen benden uzak.Çocuklarım şaşkına döndü,Çünkü düşmanım üstün çıktı.››"));
trsuperobject.biblemap.put("b25_1_17", new trsuperobject(25,1,17,"Siyon ellerini açmış,Ama onu avutan yok.RAB Yakup soyuna karşı buyruk verdi,Komşuları ona hasım olsun, dedi.Yeruşalim aralarında paçavraya döndü."));
trsuperobject.biblemap.put("b25_1_18", new trsuperobject(25,1,18,"‹‹RAB haklıdır, çünkü buyruğuna karşı geldim.Şimdi dinleyin, ey halklar, çektiğim acıyı görün;Erden kızlarım, gençlerim sürgüne gitti."));
trsuperobject.biblemap.put("b25_1_19", new trsuperobject(25,1,19,"Oynaşlarımı çağırdım,Ama aldattılar beni.Yeniden güçlerine kavuşmak için yiyecek ararkenKâhinlerimle önderlerim kentte can verdi."));
trsuperobject.biblemap.put("b25_1_20", new trsuperobject(25,1,20,"Gör, ya RAB, ne sıkıntılar çektiğimi,İçim kanıyor, yüreğim buruk,Çünkü çok asilik ettim;Dışarıda kılıç beni çocuklarımdan ayırmakta,İçerdeyse ölüm kol gezmekte."));
trsuperobject.biblemap.put("b25_1_21", new trsuperobject(25,1,21,"İnlediğimi duydular,Beni avutan olmadı.Bütün düşmanlarım başıma gelen felaketi duydu,Sen yaptın diye sevinçten coştular.İlan ettiğin günü getir,Onlar da benim gibi olsunlar."));
trsuperobject.biblemap.put("b25_1_22", new trsuperobject(25,1,22,"Yaptıkları her kötülüğü anımsa,İsyanlarımdan ötürü bana ne yaptınsa onlara da yap;Çünkü sürekli inliyor, baygınlık geçiriyorum.››"));
trsuperobject.biblemap.put("b25_2_1", new trsuperobject(25,2,1,"Rab öfkelenince Siyon kızını nasıl bulutla kapladı!İsrailin görkemini gökten yere fırlattı,Öfkelendiği gün ayağının taburesini anımsamadı."));
trsuperobject.biblemap.put("b25_2_2", new trsuperobject(25,2,2,"Yakup soyunun yaşadığı her yeri acımadan yuttu,Yahuda kızının surlu kentlerini gazabıyla yıktı,Yerle bir etti onları,Krallığını ve önderlerini alçalttı."));
trsuperobject.biblemap.put("b25_2_3", new trsuperobject(25,2,3,"Kızgın öfkesiyle İsrailin gücünü kökünden kesti,Düşmanın önünde sağ elini onların üstünden çekti,Çevresini yiyip bitiren alevli ateş gibi Yakup soyunu yaktı."));
trsuperobject.biblemap.put("b25_2_4", new trsuperobject(25,2,4,"Düşman gibi yayını gerdi,Hasım gibi sağ elini kaldırdı,Göz zevkini okşayan herkesi öldürdü,Gazabını Siyon kızının çadırı üstüne ateş gibi döktü."));
trsuperobject.biblemap.put("b25_2_5", new trsuperobject(25,2,5,"Rab adeta bir düşman olup İsraili yuttu,Bütün saraylarını yutup surlu kentlerini yıktı,Yahuda kızının feryadını, figanını arşa çıkardı."));
trsuperobject.biblemap.put("b25_2_6", new trsuperobject(25,2,6,"Bahçe çardağını söker gibi kendi çardağını söküp attı,Buluşma yerini yok etti,RAB Siyonda bayram ve Şabat günlerini unutturdu,Şiddetli öfkesi yüzünden kralı da kâhini de reddetti."));
trsuperobject.biblemap.put("b25_2_7", new trsuperobject(25,2,7,"Rab sunağını attı,Tapınağını terk etti;Siyon saraylarını çeviren surları düşman eline bıraktı.Bayram gününde olduğu gibi,Düşman RABbin Tapınağında sevinç çığlıkları attı."));
trsuperobject.biblemap.put("b25_2_9", new trsuperobject(25,2,9,"Siyonun kapıları yere battı,RAB kapı sürgülerini kırıp yok etti,Kralıyla önderleri başka ulusların arasında kaldı,Kutsal Yasa uygulanmaz oldu,Peygamberlerine RABden görüm gelmiyor artık."));
trsuperobject.biblemap.put("b25_2_10", new trsuperobject(25,2,10,"Siyon kızının ileri gelenleri suskun, yere oturmuş,Başlarına toprak saçıp çul kuşanmışlar,Yeruşalimin erden kızları yere eğmiş başlarını."));
trsuperobject.biblemap.put("b25_2_11", new trsuperobject(25,2,11,"Gözlerim tükenmekte ağlamaktan,İçim kanıyor;Halkımın yıkımındanYüreğim sızlıyor,Çünkü kent meydanlarında çocuklarla bebekler bayılmakta."));
trsuperobject.biblemap.put("b25_2_12", new trsuperobject(25,2,12,"Kent meydanlarında yaralılar gibi bayılıpCan çekişirken annelerinin bağrında,‹‹Ekmekle şarap nerede?›› diye soruyorlar annelerine."));
trsuperobject.biblemap.put("b25_2_13", new trsuperobject(25,2,13,"Senin için ne diyeyim?Ey Yeruşalim kızı, seni neye benzeteyim?Ey Siyonun erden kızı, sana neyi örnek göstereyim deSeni avutayım?Sendeki gedik deniz kadar büyük,Kim sana şifa verebilir?"));
trsuperobject.biblemap.put("b25_2_14", new trsuperobject(25,2,14,"Peygamberlerin senin için boş ve anlamsız görümler gördüler.Suçunu ortaya çıkarsalardı, eski gönencine kavuşabilirdin;Oysa seni ayartacak boş görümler gördüler."));
trsuperobject.biblemap.put("b25_2_15", new trsuperobject(25,2,15,"Yoldan geçen herkes el çırparak seninle alay ediyor,Yeruşalim kızına baş sallayıp ıslık çalarak,‹‹Bütün dünyanın sevinci, güzellik simgesi dedikleri kent bu mu?›› diyorlar."));
trsuperobject.biblemap.put("b25_2_16", new trsuperobject(25,2,16,"Düşmanlarının hepsi seninle alay etti,Islık çalıp diş gıcırdatarak,‹‹Onu yuttuk›› diyorlar,‹‹İşte beklediğimiz gün, sonunda gördük onu.››"));
trsuperobject.biblemap.put("b25_2_17", new trsuperobject(25,2,17,"RAB düşündüğünü yaptı,Geçmişte söylediği sözü yerine getirdi,Yıktı, acımadı,Düşmanı senin haline sevindirdi,Hasımlarını güçlü kıldı. boynuzunu yükseltti››."));
trsuperobject.biblemap.put("b25_2_18", new trsuperobject(25,2,18,"Halk Rabbe yürekten feryat ediyor.Ey Siyon kızının surları,Gece gündüz gözyaşın sel gibi aksın!Dinlenme, gözüne uyku girmesin!"));
trsuperobject.biblemap.put("b25_2_19", new trsuperobject(25,2,19,"Kalk, gece her nöbet başında haykır,Rabbin huzurunda yüreğini su gibi dök!Her sokak başında açlıktan bayılan çocuklarının başı için Ona ellerini aç."));
trsuperobject.biblemap.put("b25_2_20", new trsuperobject(25,2,20,"‹‹Bak, ya RAB, gör! Kime böyle yaptın?Kadınlar çocuklarını, sevgili yavrularını mı yesin?Kâhinle peygamber Rabbin Tapınağında mı öldürülsün?"));
trsuperobject.biblemap.put("b25_2_21", new trsuperobject(25,2,21,"Gençler, yaşlılar sokaklarda, yerlerde yatıyor,Kılıçtan geçirildi erden kızlarımla gençlerim,Öfkelendiğin gün öldürdün onları, acımadan boğazladın."));
trsuperobject.biblemap.put("b25_2_22", new trsuperobject(25,2,22,"Bir bayram günü davet eder gibiBeni dehşete düşürenleri davet ettin her yandan.RAB'bin öfkelendiği gün kaçıp kurtulan,Sağ kalan olmadı.Sevgiyle büyüttüğüm çocuklarımıDüşmanım yok etti.››"));
trsuperobject.biblemap.put("b25_3_2", new trsuperobject(25,3,2,"Beni güttü,Işıkta değil karanlıkta yürüttü."));
trsuperobject.biblemap.put("b25_3_3", new trsuperobject(25,3,3,"Evet, dönüp dönüp bütün gün bana elini kaldırıyor."));
trsuperobject.biblemap.put("b25_3_4", new trsuperobject(25,3,4,"Etimi, derimi yıprattı, kemiklerimi kırdı."));
trsuperobject.biblemap.put("b25_3_5", new trsuperobject(25,3,5,"Beni kuşattı,Acı ve zahmetle sardı çevremi."));
trsuperobject.biblemap.put("b25_3_6", new trsuperobject(25,3,6,"Çoktan ölmüş ölüler gibiBeni karanlıkta yaşattı."));
trsuperobject.biblemap.put("b25_3_7", new trsuperobject(25,3,7,"Çevreme duvar çekti, dışarı çıkamıyorum,Zincirimi ağırlaştırdı."));
trsuperobject.biblemap.put("b25_3_8", new trsuperobject(25,3,8,"Feryat edip yardım isteyince deDuama set çekiyor."));
trsuperobject.biblemap.put("b25_3_9", new trsuperobject(25,3,9,"Yontma taşlarla yollarımı kesti,Dolaştırdı yollarımı."));
trsuperobject.biblemap.put("b25_3_10", new trsuperobject(25,3,10,"Benim için O pusuya yatmış bir ayı,Gizlenmiş bir aslandır."));
trsuperobject.biblemap.put("b25_3_11", new trsuperobject(25,3,11,"Yollarımı saptırdı, paraladı,Mahvetti beni."));
trsuperobject.biblemap.put("b25_3_12", new trsuperobject(25,3,12,"Yayını gerdi, okunu savurmak içinBeni nişangah olarak dikti."));
trsuperobject.biblemap.put("b25_3_13", new trsuperobject(25,3,13,"Oklarını böbreklerime sapladı."));
trsuperobject.biblemap.put("b25_3_14", new trsuperobject(25,3,14,"Halkımın önünde gülünç düştüm,Gün boyu alay konusu oldum türkülerine."));
trsuperobject.biblemap.put("b25_3_15", new trsuperobject(25,3,15,"Beni acıya doyurdu,Bana doyasıya pelinsuyu içirdi."));
trsuperobject.biblemap.put("b25_3_16", new trsuperobject(25,3,16,"Dişlerimi çakıl taşlarıyla kırdı,Kül içinde diz çöktürdü bana."));
trsuperobject.biblemap.put("b25_3_17", new trsuperobject(25,3,17,"Esenlik yüzü görmedi canım,Mutluluğu unuttum."));
trsuperobject.biblemap.put("b25_3_18", new trsuperobject(25,3,18,"Bu yüzden diyorum ki,‹‹Dermanım tükendi,RABden umudum kesildi.››"));
trsuperobject.biblemap.put("b25_3_19", new trsuperobject(25,3,19,"Acımı, başıboşluğumu,Pelinotuyla ödü anımsa!"));
trsuperobject.biblemap.put("b25_3_20", new trsuperobject(25,3,20,"Hâlâ onları düşünmekteVe sıkılmaktayım."));
trsuperobject.biblemap.put("b25_3_21", new trsuperobject(25,3,21,"Ama şunu anımsadıkça umutlanıyorum:"));
trsuperobject.biblemap.put("b25_3_22", new trsuperobject(25,3,22,"RABbin sevgisi hiç tükenmez,Merhameti asla son bulmaz; sayesinde yok olmadık.››"));
trsuperobject.biblemap.put("b25_3_23", new trsuperobject(25,3,23,"Her sabah tazelenir onlar,Sadakatin büyüktür."));
trsuperobject.biblemap.put("b25_3_24", new trsuperobject(25,3,24,"‹‹Benim payıma düşen RABdir›› diyor canım,‹‹Bu yüzden Ona umut bağlıyorum.››"));
trsuperobject.biblemap.put("b25_3_25", new trsuperobject(25,3,25,"RAB kendisini bekleyenler,Onu arayan canlar için iyidir."));
trsuperobject.biblemap.put("b25_3_26", new trsuperobject(25,3,26,"RABbin kurtarışını sessizce beklemek iyidir."));
trsuperobject.biblemap.put("b25_3_27", new trsuperobject(25,3,27,"İnsan için boyunduruğu gençken taşımak iyidir."));
trsuperobject.biblemap.put("b25_3_28", new trsuperobject(25,3,28,"RAB insana boyunduruk takınca,İnsan tek başına oturup susmalı;"));
trsuperobject.biblemap.put("b25_3_29", new trsuperobject(25,3,29,"Umudunu kesmeden yere kapanmalı,"));
trsuperobject.biblemap.put("b25_3_30", new trsuperobject(25,3,30,"Kendisine vurana yanağını dönüpUtanca doymalı;"));
trsuperobject.biblemap.put("b25_3_31", new trsuperobject(25,3,31,"Çünkü Rab kimseyi sonsuza dek geri çevirmez."));
trsuperobject.biblemap.put("b25_3_32", new trsuperobject(25,3,32,"Dert verse de,Büyük sevgisinden ötürü yine merhamet eder;"));
trsuperobject.biblemap.put("b25_3_33", new trsuperobject(25,3,33,"Çünkü isteyerek acı çektirmez,İnsanları üzmez."));
trsuperobject.biblemap.put("b25_3_34", new trsuperobject(25,3,34,"Ülkedeki bütün tutsakları ayak altında ezmeyi,"));
trsuperobject.biblemap.put("b25_3_35", new trsuperobject(25,3,35,"Yüceler Yücesinin huzurunda insan hakkını saptırmayı,"));
trsuperobject.biblemap.put("b25_3_36", new trsuperobject(25,3,36,"Davasında insana haksızlık etmeyiRab doğru görmez."));
trsuperobject.biblemap.put("b25_3_37", new trsuperobject(25,3,37,"Rab buyurmadıkça kim bir şey söyler de yerine gelir?"));
trsuperobject.biblemap.put("b25_3_38", new trsuperobject(25,3,38,"İyilikler gibi felaketler de Yüceler Yücesinin ağzından çıkmıyor mu?"));
trsuperobject.biblemap.put("b25_3_39", new trsuperobject(25,3,39,"İnsan, yaşayan insanNiçin günahlarının cezasından yakınır?"));
trsuperobject.biblemap.put("b25_3_40", new trsuperobject(25,3,40,"Davranışlarımızı sınayıp gözden geçirelim,Yine RABbe dönelim."));
trsuperobject.biblemap.put("b25_3_41", new trsuperobject(25,3,41,"Ellerimizin yanısıra yüreklerimizi de göklerdeki Tanrıya açalım:"));
trsuperobject.biblemap.put("b25_3_42", new trsuperobject(25,3,42,"‹‹Biz karşı çıkıp başkaldırdık,Sen bağışlamadın."));
trsuperobject.biblemap.put("b25_3_43", new trsuperobject(25,3,43,"Öfkeyle örtünüp bizi kovaladın,Acımadan öldürdün."));
trsuperobject.biblemap.put("b25_3_44", new trsuperobject(25,3,44,"Dualar sana erişmesin diyeBulutları örtündün."));
trsuperobject.biblemap.put("b25_3_45", new trsuperobject(25,3,45,"Uluslar arasında bizi pisliğe, süprüntüye çevirdin."));
trsuperobject.biblemap.put("b25_3_46", new trsuperobject(25,3,46,"Düşmanlarımızın hepsi bizimle alay etti."));
trsuperobject.biblemap.put("b25_3_47", new trsuperobject(25,3,47,"Dehşet ve çukur, kırgın ve yıkım çıktı önümüze.››"));
trsuperobject.biblemap.put("b25_3_48", new trsuperobject(25,3,48,"Kırılan halkım yüzündenGözlerimden sel gibi yaşlar akıyor."));
trsuperobject.biblemap.put("b25_3_49", new trsuperobject(25,3,49,"Durup dinmeden yaş boşanıyor gözümden,"));
trsuperobject.biblemap.put("b25_3_50", new trsuperobject(25,3,50,"RAB göklerden bakıp görünceye dek."));
trsuperobject.biblemap.put("b25_3_51", new trsuperobject(25,3,51,"Kentimdeki kızların halini gördükçeYüreğim sızlıyor."));
trsuperobject.biblemap.put("b25_3_52", new trsuperobject(25,3,52,"Boş yere bana düşman olanlar bir kuş gibi avladılar beni."));
trsuperobject.biblemap.put("b25_3_53", new trsuperobject(25,3,53,"Beni sarnıca atıp öldürmek istediler,Üzerime taş attılar."));
trsuperobject.biblemap.put("b25_3_54", new trsuperobject(25,3,54,"Sular başımdan aştı, ‹‹Tükendim›› dedim."));
trsuperobject.biblemap.put("b25_3_55", new trsuperobject(25,3,55,"Sarnıcın dibinden seni adınla çağırdım, ya RAB;"));
trsuperobject.biblemap.put("b25_3_56", new trsuperobject(25,3,56,"Sesimi, ‹‹Ahıma, çağrıma kulağını kapama!›› dediğimi duydun."));
trsuperobject.biblemap.put("b25_3_57", new trsuperobject(25,3,57,"Seni çağırınca yaklaşıp, ‹‹Korkma!›› dedin."));
trsuperobject.biblemap.put("b25_3_58", new trsuperobject(25,3,58,"Davamı sen savundun, ya Rab,Canımı kurtardın."));
trsuperobject.biblemap.put("b25_3_59", new trsuperobject(25,3,59,"Bana yapılan haksızlığı gördün, ya RAB,Davamı sen gör."));
trsuperobject.biblemap.put("b25_3_60", new trsuperobject(25,3,60,"Benden nasıl öç aldıklarını,Bana nasıl dolap çevirdiklerini gördün."));
trsuperobject.biblemap.put("b25_3_61-62", new trsuperobject(25,3,61-62,"Aşağılamalarını, ya RAB,Çevirdikleri bütün dolapları,Bana saldıranların dediklerini,Gün boyu söylendiklerini duydun."));
trsuperobject.biblemap.put("b25_3_63", new trsuperobject(25,3,63,"Oturup kalkışlarına bak,Alay konusu oldum türkülerine."));
trsuperobject.biblemap.put("b25_3_64", new trsuperobject(25,3,64,"Yaptıklarının karşılığını ver, ya RAB."));
trsuperobject.biblemap.put("b25_3_65", new trsuperobject(25,3,65,"İnat etmelerini sağla,Lanetin üzerlerinden eksilmesin."));
trsuperobject.biblemap.put("b25_3_66", new trsuperobject(25,3,66,"Göklerinin altından öfkeyle kovala, yok et onları, ya RAB."));
trsuperobject.biblemap.put("b25_4_1", new trsuperobject(25,4,1,"Altın nasıl donuklaştı,Saf altın nasıl değişti!Kutsal taşlar sokak başlarına dağılmış."));
trsuperobject.biblemap.put("b25_4_2", new trsuperobject(25,4,2,"Değerleri saf altınla ölçülen Siyon çocuklarıNasıl çömlekçi işi, toprak testi yerine sayılır oldu!"));
trsuperobject.biblemap.put("b25_4_3", new trsuperobject(25,4,3,"Çakallar bile meme verip yavrularını emzirir,Ama halkım çöldeki devekuşları kadar acımasız oldu."));
trsuperobject.biblemap.put("b25_4_4", new trsuperobject(25,4,4,"Susuzluktan emzikteki bebeklerin dili damağına yapışıyor,Çocuklar ekmek istiyor, veren yok."));
trsuperobject.biblemap.put("b25_4_5", new trsuperobject(25,4,5,"Onlar ki, yemeğin en iyisini yerlerdi,Sokaklarda perişan oldular;Onlar ki, al giysiler içinde büyüdüler,Çöp yığınlarını kapışır oldular."));
trsuperobject.biblemap.put("b25_4_6", new trsuperobject(25,4,6,"Halkımın suçu el değmeden, bir anda yıkılanSodomun günahından daha büyüktür."));
trsuperobject.biblemap.put("b25_4_7", new trsuperobject(25,4,7,"Beyleri kardan temiz, sütten aktılar,Bedence mercandan kızıl, laciverttaşı kadar biçimliydiler."));
trsuperobject.biblemap.put("b25_4_8", new trsuperobject(25,4,8,"Şimdiyse görünüşleri kömürden kara,Sokaklarda tanınmaz oldular.Bir deri bir kemiğe döndüler, odun gibi kurudular."));
trsuperobject.biblemap.put("b25_4_9", new trsuperobject(25,4,9,"Kılıçla öldürülenler kıtlıktan ölenlerden mutludur,Çünkü kıtlıktan ölenler tarla ürününün yokluğundan yıpranarak erimekteler."));
trsuperobject.biblemap.put("b25_4_10", new trsuperobject(25,4,10,"Merhametli kadınlar çocuklarını elleriyle pişirdiler,Halkım kırılırken yiyecek oldu bu kendilerine."));
trsuperobject.biblemap.put("b25_4_11", new trsuperobject(25,4,11,"RAB öfkesini boşalttı, kızgın öfkesini döktü,Temellerini yiyip bitiren ateşi Siyonun içinde tutuşturdu."));
trsuperobject.biblemap.put("b25_4_12", new trsuperobject(25,4,12,"Dünyadaki kralların ve insanların hiçbiriYeruşalim kapılarından hasımların, düşmanların gireceğine inanmazdı."));
trsuperobject.biblemap.put("b25_4_13", new trsuperobject(25,4,13,"Peygamberlerinin günahı, kâhinlerinin suçu yüzündendi bu,Çünkü onlar kentin ortasında doğruların kanını döktüler."));
trsuperobject.biblemap.put("b25_4_14", new trsuperobject(25,4,14,"Sokaklarda körler gibi dolaşıyorlar,Kanla kirlendikleri için kimse giysilerine dokunamıyor."));
trsuperobject.biblemap.put("b25_4_15", new trsuperobject(25,4,15,"‹‹Çekilin! Kirliler!›› diye bağırdılar onlara,‹‹Çekilin! Çekilin! Dokunmayın!››Kaçıp başıboş dolaştıklarında,Öteki uluslar, ‹‹Artık burada kalmasınlar›› dediler."));
trsuperobject.biblemap.put("b25_4_16", new trsuperobject(25,4,16,"RAB kendisi dağıttı onları,Artık yüzlerine bakmayacak.Kâhinleri saymadılar, yaşlılara acımadılar."));
trsuperobject.biblemap.put("b25_4_17", new trsuperobject(25,4,17,"Boş yere yardım beklemekten gözlerimizin feri sönüyor,Gözetleme kulesinde bizi kurtaramayacak bir ulusu bekledikçe bekledik."));
trsuperobject.biblemap.put("b25_4_18", new trsuperobject(25,4,18,"İzlerimizi sürüyorlar,Sokaklarımızda gezemez olduk.Sonumuz yaklaştı, günlerimiz tükendi,Çünkü sonumuz geldi."));
trsuperobject.biblemap.put("b25_4_19", new trsuperobject(25,4,19,"Bizi kovalayanlar gökteki kartallardan çevikti,Dağların üstünde kovaladılar bizi,Çölde bize pusu kurdular."));
trsuperobject.biblemap.put("b25_4_20", new trsuperobject(25,4,20,"Yaşam soluğumuz,RABbin meshettiği kral onların çukurunda yakalandı;Hani onun için, ‹‹Ulusların arasında onun gölgesinde yaşayacağız›› dediğimiz."));
trsuperobject.biblemap.put("b25_4_21", new trsuperobject(25,4,21,"Ûs ülkesinde yaşayan Edom kızı, sevin, coş,Ancak kâse sana da gelecek, sarhoş olup soyunacaksın."));
trsuperobject.biblemap.put("b25_4_22", new trsuperobject(25,4,22,"Ey Siyon kızı, suçunun cezası sona erdi,RAB bir daha seni sürgüne göndermeyecek.Ama, ey Edom kızı, suçun yüzünden seni cezalandırıp günahlarını ortaya çıkaracak."));
trsuperobject.biblemap.put("b25_5_1", new trsuperobject(25,5,1,"Anımsa, ya RAB, başımıza geleni,Bak da utancımızı gör."));
trsuperobject.biblemap.put("b25_5_2", new trsuperobject(25,5,2,"Mülkümüz yabancılara geçti,Evlerimiz ellere."));
trsuperobject.biblemap.put("b25_5_3", new trsuperobject(25,5,3,"Öksüz kaldık, babasız,Annelerimiz dul kadınlara döndü."));
trsuperobject.biblemap.put("b25_5_4", new trsuperobject(25,5,4,"Suyumuzu parayla içtik,Odunumuzu parayla almak zorunda kaldık."));
trsuperobject.biblemap.put("b25_5_5", new trsuperobject(25,5,5,"Bizi kovalayanlar ensemizde,Yorgun düştük, rahatımız yok."));
trsuperobject.biblemap.put("b25_5_6", new trsuperobject(25,5,6,"Ekmek içinMısıra, Asura el açtık."));
trsuperobject.biblemap.put("b25_5_7", new trsuperobject(25,5,7,"Atalarımız günah işledi,Ama artık onlar yok;Suçlarının cezasını biz yüklendik."));
trsuperobject.biblemap.put("b25_5_8", new trsuperobject(25,5,8,"Köleler üstümüzde saltanat sürüyor,Bizi ellerinden kurtaracak kimse yok."));
trsuperobject.biblemap.put("b25_5_9", new trsuperobject(25,5,9,"Çöldeki kılıçlı haydutlar yüzündenEkmeğimizi canımız pahasına kazanıyoruz."));
trsuperobject.biblemap.put("b25_5_10", new trsuperobject(25,5,10,"Kıtlığın yakıcı sıcağındanDerimiz fırın gibi kızardı."));
trsuperobject.biblemap.put("b25_5_11", new trsuperobject(25,5,11,"Siyonda kadınların,Yahuda kentlerinde erden kızların ırzına geçtiler."));
trsuperobject.biblemap.put("b25_5_12", new trsuperobject(25,5,12,"Önderler ellerinden asıldı,Yaşlılar saygı görmedi."));
trsuperobject.biblemap.put("b25_5_13", new trsuperobject(25,5,13,"Değirmen taşını gençler çevirdi,Çocuklar odun yükü altında tökezledi."));
trsuperobject.biblemap.put("b25_5_14", new trsuperobject(25,5,14,"Yaşlılar kent kapısında oturmaz oldu,Gençler saz çalmaz oldu."));
trsuperobject.biblemap.put("b25_5_15", new trsuperobject(25,5,15,"Yüreğimizin sevinci durdu,Oyunumuz yasa döndü."));
trsuperobject.biblemap.put("b25_5_16", new trsuperobject(25,5,16,"Taç düştü başımızdan,Vay başımıza!Çünkü günah işledik."));
trsuperobject.biblemap.put("b25_5_17", new trsuperobject(25,5,17,"Bu yüzden yüreğimiz baygın,Bunlardan ötürü gözlerimiz karardı."));
trsuperobject.biblemap.put("b25_5_18", new trsuperobject(25,5,18,"Viran olan Siyon Dağının üstündeÇakallar geziyor!"));
trsuperobject.biblemap.put("b25_5_19", new trsuperobject(25,5,19,"Ama sen, sonsuza dek tahtında oturursun, ya RAB,Egemenliğin kuşaklar boyu sürer."));
trsuperobject.biblemap.put("b25_5_20", new trsuperobject(25,5,20,"Niçin bizi hep unutuyorsun,Neden bizi uzun süre terk ediyorsun?"));
trsuperobject.biblemap.put("b25_5_21", new trsuperobject(25,5,21,"Bizi kendine döndür, ya RAB, döneriz,Eski günlerimizi geri ver."));
trsuperobject.biblemap.put("b25_5_22", new trsuperobject(25,5,22,"Bizi büsbütün attıysan,Bize çok öfkelenmiş olmalısın."));

}

}