package tr.bible;

public class trbible49 {

public trbible49() {

putmapbible49();

}

private void putmapbible49() {

trsuperobject.biblemap.put("b49_1_1", new trsuperobject(49,1,1,"Tanrının isteğiyle Mesih İsanın elçisi atanan ben Pavlustan Efeste bulunan kutsallara, Mesih İsaya ait olan sadıklara selam!"));
trsuperobject.biblemap.put("b49_1_2", new trsuperobject(49,1,2,"Babamız Tanrıdan ve Rab İsa Mesihten sizlere lütuf ve esenlik olsun."));
trsuperobject.biblemap.put("b49_1_3", new trsuperobject(49,1,3,"Bizi Mesihte her ruhsal kutsamayla göksel yerlerde kutsamış olan Rabbimiz İsa Mesihin Babası Tanrıya övgüler olsun."));
trsuperobject.biblemap.put("b49_1_4", new trsuperobject(49,1,4,"O kendi önünde sevgide kutsal ve kusursuz olmamız için dünyanın kuruluşundan önce bizi Mesihte seçti."));
trsuperobject.biblemap.put("b49_1_5", new trsuperobject(49,1,5,"Kendi isteği ve iyi amacı uyarınca İsa Mesih aracılığıyla kendisine oğullar olalım diye bizi önceden belirledi."));
trsuperobject.biblemap.put("b49_1_6", new trsuperobject(49,1,6,"Öyle ki, sevgili Oğlunda bize bağışladığı yüce lütfu övülsün."));
trsuperobject.biblemap.put("b49_1_7-8", new trsuperobject(49,1,7-8,"Tam bir bilgelik ve anlayışla üzerimize yağdırdığı lütfunun zenginliği sayesinde Mesihin kanı aracılığıyla Mesihte kurtuluşa, suçlarımızın bağışlanmasına kavuştuk."));
trsuperobject.biblemap.put("b49_1_9", new trsuperobject(49,1,9,"Tanrı sır olan isteğini, Mesihte edindiği iyi amaç uyarınca bize açıkladı."));
trsuperobject.biblemap.put("b49_1_10", new trsuperobject(49,1,10,"Zaman dolunca gerçekleştireceği bu tasarıya göre, yerdeki ve gökteki her şeyi Mesihte birleştirecek."));
trsuperobject.biblemap.put("b49_1_11", new trsuperobject(49,1,11,"Her şeyi kendi isteği doğrultusunda düzenleyen Tanrının amacı uyarınca önceden belirlenip Mesihte seçildik."));
trsuperobject.biblemap.put("b49_1_12", new trsuperobject(49,1,12,"Öyle ki, Mesihe ilk umut bağlayan bizler, Onun yüceliğinin övülmesi için yaşayalım."));
trsuperobject.biblemap.put("b49_1_13", new trsuperobject(49,1,13,"Gerçeğin bildirisini, kurtuluşunuzun Müjdesini duyup Ona iman ettiğinizde, siz de vaat edilen Kutsal Ruhla Onda mühürlendiniz."));
trsuperobject.biblemap.put("b49_1_14", new trsuperobject(49,1,14,"Ruh, Tanrının yüceliğinin övülmesi için Tanrıya ait olanların kurtuluşuna dek mirasımızın güvencesidir."));
trsuperobject.biblemap.put("b49_1_15-16", new trsuperobject(49,1,15-16,"Bunun için, Rab İsaya iman ettiğinizi ve bütün kutsalları sevdiğinizi duyduğumdan beri ben de sizin için sürekli şükrediyor, sizi dualarımda hep anıyorum."));
trsuperobject.biblemap.put("b49_1_17", new trsuperobject(49,1,17,"Rabbimiz İsa Mesihin Tanrısı, yüce Baba, kendisini tanımanız için size bilgelik ve vahiy ruhunu versin diye dua ediyorum."));
trsuperobject.biblemap.put("b49_1_18-20", new trsuperobject(49,1,18-20,"Onun çağrısından doğan umudu, kutsallara verdiği mirasın yüce zenginliğini ve iman eden bizler için etkin olan kudretinin aşkın büyüklüğünü anlamanız için, yüreklerinizin gözleri aydınlansın diye dua ediyorum. Bu kudret, Tanrının, Mesihi ölümden diriltirken ve göksel yerlerde sağında oturturken Onda sergilediği üstün güçle aynı etkinliktedir."));
trsuperobject.biblemap.put("b49_1_21", new trsuperobject(49,1,21,"Tanrı Onu bütün yönetimlerin, hükümranlıkların, güç ve egemenliklerin, yalnız bu çağda değil, gelecek çağda da anılacak bütün adların çok üstüne çıkardı."));
trsuperobject.biblemap.put("b49_1_22", new trsuperobject(49,1,22,"Her şeyi ayakları altına sererek Ona bağımlı kıldı. Onu her şeyin üzerinde baş olmak üzere kiliseye verdi."));
trsuperobject.biblemap.put("b49_1_23", new trsuperobject(49,1,23,"Kilise O'nun bedenidir, her yönden her şeyi dolduranın doluluğudur."));
trsuperobject.biblemap.put("b49_2_1-2", new trsuperobject(49,2,1-2,"Sizler bir zamanlar içinde yaşadığınız suçlardan ve günahlardan ötürü ölüydünüz. Bu dünyanın gidişine ve havadaki hükümranlığın egemenine, yani söz dinlemeyen insanlarda şimdi etkin olan ruha uymaktaydınız."));
trsuperobject.biblemap.put("b49_2_3", new trsuperobject(49,2,3,"Bir zamanlar hepimiz böyle insanların arasında, benliğin ve aklın isteklerini yerine getirerek benliğimizin tutkularına göre yaşıyorduk. Doğal olarak ötekiler gibi biz de gazap çocuklarıydık."));
trsuperobject.biblemap.put("b49_2_4-5", new trsuperobject(49,2,4-5,"Ama merhameti bol olan Tanrı bizi çok sevdiği için, suçlarımızdan ötürü ölü olduğumuz halde, bizi Mesihle birlikte yaşama kavuşturdu. Onun lütfuyla kurtuldunuz."));
trsuperobject.biblemap.put("b49_2_6", new trsuperobject(49,2,6,"Tanrı bizi Mesih İsada, Mesihle birlikte diriltip göksel yerlerde oturttu."));
trsuperobject.biblemap.put("b49_2_7", new trsuperobject(49,2,7,"Bunu, Mesih İsada bize gösterdiği iyilikle, lütfunun sonsuz zenginliğini gelecek çağlarda sergilemek için yaptı."));
trsuperobject.biblemap.put("b49_2_8", new trsuperobject(49,2,8,"İman yoluyla, lütufla kurtuldunuz. Bu sizin başarınız değil, Tanrının armağanıdır."));
trsuperobject.biblemap.put("b49_2_9", new trsuperobject(49,2,9,"Kimsenin övünmemesi için iyi işlerin ödülü değildir."));
trsuperobject.biblemap.put("b49_2_10", new trsuperobject(49,2,10,"Çünkü biz Tanrının yapıtıyız, Onun önceden hazırladığı iyi işleri yapmak üzere Mesih İsada yaratıldık."));
trsuperobject.biblemap.put("b49_2_11", new trsuperobject(49,2,11,"Bunun için, öteki uluslardan doğan sizler bir zamanlar ne olduğunuzu anımsayın: Bedende elle yapılmış sünnete sahip olup ‹‹sünnetli›› diye anılanların ‹‹sünnetsiz›› dedikleri sizler,"));
trsuperobject.biblemap.put("b49_2_12", new trsuperobject(49,2,12,"o zaman Mesihsiz, İsrailde vatandaşlıktan yoksun, vaade dayanan antlaşmalara yabancı, dünyada umutsuz ve tanrısızdınız."));
trsuperobject.biblemap.put("b49_2_13", new trsuperobject(49,2,13,"Ama bir zamanlar uzak olan sizler, şimdi Mesih İsada Mesihin kanı sayesinde yakın kılındınız."));
trsuperobject.biblemap.put("b49_2_14-16", new trsuperobject(49,2,14-16,"Çünkü Mesihin kendisi barışımızdır. Kutsal Yasayı, buyrukları ve kurallarıyla birlikte etkisiz kılarak iki topluluğu birleştirdi, aradaki engel duvarını, yani düşmanlığı kendi bedeninde yıktı. Amacı bu iki topluluktan kendisinde yeni bir insan yaratarak esenliği sağlamak, düşmanlığı çarmıhta öldürmek ve çarmıh aracılığıyla bir bedende iki topluluğu Tanrıyla barıştırmaktı."));
trsuperobject.biblemap.put("b49_2_17", new trsuperobject(49,2,17,"O gelip hem uzakta olan sizlere hem de yakındakilere esenliği müjdeledi."));
trsuperobject.biblemap.put("b49_2_18", new trsuperobject(49,2,18,"Onun aracılığıyla hepimiz tek Ruhta Babanın huzuruna çıkabiliriz."));
trsuperobject.biblemap.put("b49_2_19", new trsuperobject(49,2,19,"Böylece artık yabancı ve garip değil, kutsallarla birlikte yurttaş ve Tanrının ev halkısınız."));
trsuperobject.biblemap.put("b49_2_20", new trsuperobject(49,2,20,"Elçilerle peygamberlerden oluşan temel üzerine inşa edildiniz. Köşe taşı Mesih İsanın kendisidir."));
trsuperobject.biblemap.put("b49_2_21", new trsuperobject(49,2,21,"Bütün yapı Rabbe ait kutsal bir tapınak olmak üzere Onda kenetlenip yükseliyor."));
trsuperobject.biblemap.put("b49_2_22", new trsuperobject(49,2,22,"Siz de Ruh aracılığıyla Tanrı'nın konutu olmak üzere hep birlikte Mesih'te inşa ediliyorsunuz."));
trsuperobject.biblemap.put("b49_3_1", new trsuperobject(49,3,1,"Bu nedenledir ki, ben Pavlus siz uluslar uğruna Mesih İsanın tutuklusu oldum."));
trsuperobject.biblemap.put("b49_3_2", new trsuperobject(49,3,2,"Tanrının bana bağışladığı lütfu size ulaştırmakla görevlendirildiğimi duymuşsunuzdur."));
trsuperobject.biblemap.put("b49_3_3", new trsuperobject(49,3,3,"Yukarıda kısaca değindiğim gibi Tanrı, sır olan tasarısını bana vahiy yoluyla bildirdi."));
trsuperobject.biblemap.put("b49_3_4", new trsuperobject(49,3,4,"Bu mektubu okuduğunuzda Mesih sırrını nasıl kavradığımı anlayabilirsiniz."));
trsuperobject.biblemap.put("b49_3_5", new trsuperobject(49,3,5,"Bu sır önceki kuşaklara açıkça bildirilmemişti. Şimdiyse Mesihin kutsal elçilerine ve peygamberlerine Ruh aracılığıyla açıklanmış bulunuyor."));
trsuperobject.biblemap.put("b49_3_6", new trsuperobject(49,3,6,"Şöyle ki, öteki uluslar da mirasa ortaktır, aynı bedenin üyeleridir ve Müjde aracılığıyla Mesih İsada vaade ortaktır."));
trsuperobject.biblemap.put("b49_3_7", new trsuperobject(49,3,7,"Tanrının etkin gücüyle bana verilen lütuf armağanı uyarınca bu Müjdeyi yaymakla görevlendirildim."));
trsuperobject.biblemap.put("b49_3_8-9", new trsuperobject(49,3,8-9,"Bütün kutsalların en değersiziydim. Yine de Mesihin akıl ermez zenginliğini uluslara müjdeleme ve her şeyi yaratan Tanrıda öncesizlikten beri gizli tutulan sırrın nasıl düzenlendiğini bütün insanlara açıklama ayrıcalığı bana verildi."));
trsuperobject.biblemap.put("b49_3_10", new trsuperobject(49,3,10,"Öyle ki, Tanrının çok yönlü bilgeliği, kilise aracılığıyla göksel yerlerdeki yönetimlere ve hükümranlıklara şimdiki dönemde bildirilsin."));
trsuperobject.biblemap.put("b49_3_11", new trsuperobject(49,3,11,"Bu, Tanrının başlangıçtan beri tasarladığı ve Rabbimiz Mesih İsada yerine getirdiği amaca uygundu."));
trsuperobject.biblemap.put("b49_3_12", new trsuperobject(49,3,12,"Mesihte ve Mesihe olan imanımızla Tanrıya cesaret ve güvenle yaklaşabiliriz."));
trsuperobject.biblemap.put("b49_3_13", new trsuperobject(49,3,13,"Bu nedenle, uğrunuza çektiğim sıkıntılar karşısında yılmamanızı rica ediyorum. Bunlar size yücelik kazandırır."));
trsuperobject.biblemap.put("b49_3_14-15", new trsuperobject(49,3,14-15,"Bunun için, yerde ve gökte her ailenin adını kendisinden aldığı Babanın önünde diz çökerim."));
trsuperobject.biblemap.put("b49_3_16-19", new trsuperobject(49,3,16-19,"Babanın kendi yüceliğinin zenginliği uyarınca Ruhuyla sizi iç varlığınızda kudretle güçlendirmesini ve Mesihin iman yoluyla yüreklerinizde yaşamasını dilerim. Öyle ki, Tanrının bütün doluluğuyla dolmanız için, sevgide köklenmiş ve temellenmiş olarak bütün kutsallarla birlikte Mesihin sevgisinin ne denli geniş ve uzun, yüksek ve derin olduğunu anlamaya, bilgiyi çok aşan bu sevgiyi kavramaya gücünüz yetsin."));
trsuperobject.biblemap.put("b49_3_20", new trsuperobject(49,3,20,"Tanrı, bizde etkin olan kudretiyle, dilediğimiz ya da düşündüğümüz her şeyden çok daha fazlasını yapabilecek güçtedir."));
trsuperobject.biblemap.put("b49_3_21", new trsuperobject(49,3,21,"Kilisede ve Mesih İsa'da bütün kuşaklar boyunca sonsuzlara dek O'na yücelik olsun! Amin."));
trsuperobject.biblemap.put("b49_4_1", new trsuperobject(49,4,1,"Bu nedenle, Rabbin uğruna tutuklu olan ben, aldığınız çağrıya yaraşır biçimde yaşamanızı rica ederim."));
trsuperobject.biblemap.put("b49_4_2", new trsuperobject(49,4,2,"Her bakımdan alçakgönüllü, yumuşak huylu, sabırlı olun. Birbirinize sevgiyle, hoşgörüyle davranın."));
trsuperobject.biblemap.put("b49_4_3", new trsuperobject(49,4,3,"Ruhun birliğini esenlik bağıyla korumaya gayret edin."));
trsuperobject.biblemap.put("b49_4_4-6", new trsuperobject(49,4,4-6,"Çağrınızdan doğan tek bir umuda çağrıldığınız gibi, beden bir, Ruh bir, Rab bir, iman bir, vaftiz bir, her şeyden üstün, her şeyle ve her şeyde olan herkesin Tanrısı ve Babası birdir."));
trsuperobject.biblemap.put("b49_4_7", new trsuperobject(49,4,7,"Ama lütuf her birimize Mesihin armağanı ölçüsünde bağışlandı."));
trsuperobject.biblemap.put("b49_4_8", new trsuperobject(49,4,8,"Bunun için Kutsal Yazı şöyle der:  ‹‹Yükseğe çıktı ve tutsakları peşine taktı,  İnsanlara armağanlar verdi.››"));
trsuperobject.biblemap.put("b49_4_9", new trsuperobject(49,4,9,"Şimdi bu ‹‹çıktı›› sözcüğü, Mesih önce aşağılara, yeryüzüne indi demek değil de nedir?"));
trsuperobject.biblemap.put("b49_4_10", new trsuperobject(49,4,10,"İnen de Odur, her şeyi doldurmak üzere bütün göklerin çok üstüne çıkan da Odur."));
trsuperobject.biblemap.put("b49_4_11", new trsuperobject(49,4,11,"Kendisi kimini elçi, kimini peygamber, kimini müjdeci, kimini önder ve öğretmen atadı."));
trsuperobject.biblemap.put("b49_4_12", new trsuperobject(49,4,12,"Öyle ki, kutsallar hizmet görevini yapmak ve Mesihin bedenini geliştirmek üzere donatılsın."));
trsuperobject.biblemap.put("b49_4_13", new trsuperobject(49,4,13,"Sonunda hepimiz imanda ve Tanrı Oğlunu tanımada birliğe, yetkinliğe, Mesih doluluğundaki olgunluk düzeyine erişeceğiz."));
trsuperobject.biblemap.put("b49_4_14", new trsuperobject(49,4,14,"Böylece artık insanların kurnazlığıyla, aldatıcı düzenler kurmaktaki becerileriyle, her öğretinin rüzgarıyla çalkalanıp öteye beriye sürüklenen çocuklar olmayacağız."));
trsuperobject.biblemap.put("b49_4_15", new trsuperobject(49,4,15,"Tersine, sevgiyle gerçeğe uyarak bedenin başı olan Mesihe doğru her yönden büyüyeceğiz."));
trsuperobject.biblemap.put("b49_4_16", new trsuperobject(49,4,16,"Onun önderliğinde bütün beden, her eklemin yardımıyla kenetlenip kaynaşmış olarak her üyesinin düzenli işleyişiyle büyüyüp sevgide gelişiyor."));
trsuperobject.biblemap.put("b49_4_17", new trsuperobject(49,4,17,"Bunun için şunu söylüyor ve Rab adına sizi uyarıyorum: Artık öteki uluslar gibi boş düşüncelerle yaşamayın."));
trsuperobject.biblemap.put("b49_4_18", new trsuperobject(49,4,18,"Onların zihinleri karardı. Bilgisizlikleri ve yüreklerinin duygusuzluğu yüzünden Tanrının yaşamına yabancılaştılar."));
trsuperobject.biblemap.put("b49_4_19", new trsuperobject(49,4,19,"Bütün duyarlılıklarını yitirip açgözlülükle her türlü pisliği yapmak üzere kendilerini sefahate verdiler."));
trsuperobject.biblemap.put("b49_4_20", new trsuperobject(49,4,20,"Ama siz Mesihi böyle öğrenmediniz."));
trsuperobject.biblemap.put("b49_4_21", new trsuperobject(49,4,21,"Kuşkusuz İsanın sesini duydunuz, Ondaki gerçeğe uygun olarak Onun yolunda eğitildiniz."));
trsuperobject.biblemap.put("b49_4_22-23", new trsuperobject(49,4,22-23,"Önceki yaşayışınıza ait olup aldatıcı tutkularla yozlaşan eski yaradılışı üzerinizden sıyırıp atmayı, düşüncede ve ruhta yenilenmeyi,"));
trsuperobject.biblemap.put("b49_4_24", new trsuperobject(49,4,24,"gerçek doğruluk ve kutsallıkta Tanrıya benzer yaratılan yeni yaradılışı giyinmeyi öğrendiniz."));
trsuperobject.biblemap.put("b49_4_25", new trsuperobject(49,4,25,"Bunun için yalanı üzerinizden sıyırıp atarak her biriniz komşusuna gerçeği söylesin. Çünkü hepimiz aynı bedenin üyeleriyiz."));
trsuperobject.biblemap.put("b49_4_26", new trsuperobject(49,4,26,"Öfkelenin, ama günah işlemeyin. Öfkenizin üzerine güneş batmasın."));
trsuperobject.biblemap.put("b49_4_27", new trsuperobject(49,4,27,"İblise de fırsat vermeyin."));
trsuperobject.biblemap.put("b49_4_28", new trsuperobject(49,4,28,"Hırsızlık eden artık hırsızlık etmesin. Tersine, kendi elleriyle iyi olanı yaparak emek versin; böylece ihtiyacı olanla paylaşacak bir şeyi olsun."));
trsuperobject.biblemap.put("b49_4_29", new trsuperobject(49,4,29,"Ağzınızdan hiç kötü söz çıkmasın. İşitenler yararlansın diye, ihtiyaca göre, başkalarının gelişmesine yarayacak olanı söyleyin."));
trsuperobject.biblemap.put("b49_4_30", new trsuperobject(49,4,30,"Tanrının Kutsal Ruhunu kederlendirmeyin. Kurtuluş günü için o Ruhla mühürlendiniz."));
trsuperobject.biblemap.put("b49_4_31", new trsuperobject(49,4,31,"Her kötü niyetle birlikte her türlü kin, öfke, kızgınlık, bağrışma ve iftira sizden uzak olsun."));
trsuperobject.biblemap.put("b49_4_32", new trsuperobject(49,4,32,"Birbirinize karşı iyi yürekli, şefkatli olun. Tanrı sizi Mesih'te bağışladığı gibi, siz de birbirinizi bağışlayın."));
trsuperobject.biblemap.put("b49_5_1", new trsuperobject(49,5,1,"Bunun için, sevgili çocukları olarak Tanrıyı örnek alın."));
trsuperobject.biblemap.put("b49_5_2", new trsuperobject(49,5,2,"Mesih bizi nasıl sevdiyse ve bizim için kendisini güzel kokulu bir sunu ve kurban olarak nasıl Tanrıya sunduysa, siz de öylece sevgi yolunda yürüyün."));
trsuperobject.biblemap.put("b49_5_3", new trsuperobject(49,5,3,"Aranızda fuhuş, pislik ya da açgözlülük anılmasın bile. Kutsallara yaraşmaz bu."));
trsuperobject.biblemap.put("b49_5_4", new trsuperobject(49,5,4,"Aranızda açık saçıklık, budalaca konuşmalar, bayağı şakalar da olmasın. Bunlar size yakışmaz. Bunun yerine şükredin."));
trsuperobject.biblemap.put("b49_5_5", new trsuperobject(49,5,5,"Şunu kesinlikle bilin ki, fuhuş yapanın, pisliğe düşkün olanın ya da putperest demek olan açgözlü kişinin, Mesihin ve Tanrının Egemenliğinde mirası yoktur."));
trsuperobject.biblemap.put("b49_5_6", new trsuperobject(49,5,6,"Hiç kimse sizi boş sözlerle aldatmasın. Bu şeylerden ötürü Tanrının gazabı söz dinlemeyenlerin üzerine gelir."));
trsuperobject.biblemap.put("b49_5_7", new trsuperobject(49,5,7,"Onun için böyleleriyle oturup kalkmayın."));
trsuperobject.biblemap.put("b49_5_8", new trsuperobject(49,5,8,"Bir zamanlar karanlıktınız, ama şimdi Rabde ışıksınız. Işık çocukları olarak yaşayın."));
trsuperobject.biblemap.put("b49_5_9", new trsuperobject(49,5,9,"Çünkü ışığın meyvesi her iyilikte, doğrulukta ve gerçekte görülür."));
trsuperobject.biblemap.put("b49_5_10", new trsuperobject(49,5,10,"Rabbi neyin hoşnut ettiğini ayırt edin."));
trsuperobject.biblemap.put("b49_5_11", new trsuperobject(49,5,11,"Karanlığın meyvesiz işlerine katılmayın. Tersine, onları açığa çıkarın."));
trsuperobject.biblemap.put("b49_5_12", new trsuperobject(49,5,12,"Karanlıktakilerin gizlice yaptıklarından söz etmek bile ayıptır."));
trsuperobject.biblemap.put("b49_5_13", new trsuperobject(49,5,13,"Işığın açığa vurduğu her şey görünür."));
trsuperobject.biblemap.put("b49_5_14", new trsuperobject(49,5,14,"Çünkü görünen her şey ışıktır. Bunun için şöyle deniyor:  ‹‹Uyan, ey uyuyan! Ölümden diril!  Mesih sana ışık saçacak.››"));
trsuperobject.biblemap.put("b49_5_15", new trsuperobject(49,5,15,"Öyleyse nasıl yaşadığınıza çok dikkat edin. Bilgelikten yoksun olanlar gibi değil, bilgeler gibi yaşayın."));
trsuperobject.biblemap.put("b49_5_16", new trsuperobject(49,5,16,"Fırsatı değerlendirin. Çünkü yaşadığımız günler kötüdür."));
trsuperobject.biblemap.put("b49_5_17", new trsuperobject(49,5,17,"Bunun için akılsız olmayın, Rabbin isteğinin ne olduğunu anlayın."));
trsuperobject.biblemap.put("b49_5_18", new trsuperobject(49,5,18,"Şarapla sarhoş olmayın, bu sizi sefahate götürür. Bunun yerine Ruhla dolun:"));
trsuperobject.biblemap.put("b49_5_19", new trsuperobject(49,5,19,"Birbirinize mezmurlar, ilahiler, ruhsal ezgiler söyleyin; yürekten Rabbe ezgiler, mezmurlar okuyun;"));
trsuperobject.biblemap.put("b49_5_20", new trsuperobject(49,5,20,"durmadan, her şey için Rabbimiz İsa Mesihin adıyla Baba Tanrıya şükredin;"));
trsuperobject.biblemap.put("b49_5_21", new trsuperobject(49,5,21,"Mesihe duyduğunuz saygıdan ötürü birbirinize bağımlı olun."));
trsuperobject.biblemap.put("b49_5_22", new trsuperobject(49,5,22,"Ey kadınlar, Rabbe bağımlı olduğunuz gibi, kocalarınıza bağımlı olun."));
trsuperobject.biblemap.put("b49_5_23", new trsuperobject(49,5,23,"Çünkü Mesih bedenin kurtarıcısı olarak kilisenin başı olduğu gibi, erkek de kadının başıdır."));
trsuperobject.biblemap.put("b49_5_24", new trsuperobject(49,5,24,"Kilise Mesihe bağımlı olduğu gibi, kadınlar da her durumda kocalarına bağımlı olsunlar."));
trsuperobject.biblemap.put("b49_5_25", new trsuperobject(49,5,25,"Ey kocalar, Mesih kiliseyi nasıl sevip onun uğruna kendini feda ettiyse, siz de karılarınızı öyle sevin."));
trsuperobject.biblemap.put("b49_5_26", new trsuperobject(49,5,26,"Mesih kiliseyi suyla yıkayıp tanrısal sözle temizleyerek kutsal kılmak için kendini feda etti."));
trsuperobject.biblemap.put("b49_5_27", new trsuperobject(49,5,27,"Öyle ki, kiliseyi üzerinde leke, buruşukluk ya da buna benzer bir şey olmadan, görkemli biçimde kendine sunabilsin. Amacı kilisenin kutsal ve kusursuz olmasıdır."));
trsuperobject.biblemap.put("b49_5_28", new trsuperobject(49,5,28,"Aynı biçimde kocalar da karılarını kendi bedenleri gibi sevmelidir. Karısını seven kendini sever."));
trsuperobject.biblemap.put("b49_5_29", new trsuperobject(49,5,29,"Hiç kimse hiçbir zaman kendi bedeninden nefret etmemiştir. Tersine, onu besler ve kayırır; tıpkı Mesihin kiliseyi besleyip kayırdığı gibi."));
trsuperobject.biblemap.put("b49_5_30", new trsuperobject(49,5,30,"Çünkü bizler Onun bedeninin üyeleriyiz."));
trsuperobject.biblemap.put("b49_5_31", new trsuperobject(49,5,31,"‹‹Bunun için adam annesini babasını bırakıp karısına bağlanacak, ikisi tek beden olacak.››"));
trsuperobject.biblemap.put("b49_5_32", new trsuperobject(49,5,32,"Bu sır büyüktür; ben bunu Mesih ve kiliseyle ilgili olarak söylüyorum."));
trsuperobject.biblemap.put("b49_5_33", new trsuperobject(49,5,33,"Size gelince, her biriniz karısını kendisi gibi sevsin. Kadın da kocasına saygı göstersin."));
trsuperobject.biblemap.put("b49_6_1", new trsuperobject(49,6,1,"Ey çocuklar, Rab yolunda anne babanızın sözünü dinleyin. Çünkü doğrusu budur."));
trsuperobject.biblemap.put("b49_6_2-3", new trsuperobject(49,6,2-3,"‹‹İyilik bulmak, yeryüzünde uzun ömürlü olmak için annene babana saygı göstereceksin.›› Vaat içeren ilk buyruk budur."));
trsuperobject.biblemap.put("b49_6_4", new trsuperobject(49,6,4,"Ey babalar, siz de çocuklarınızın öfkesini uyandırmayın. Onları Rabbin terbiye ve öğüdüyle büyütün."));
trsuperobject.biblemap.put("b49_6_5", new trsuperobject(49,6,5,"Ey köleler, dünyadaki efendilerinizin sözünü Mesihin sözünü dinler gibi saygı ve korkuyla, saf yürekle dinleyin."));
trsuperobject.biblemap.put("b49_6_6", new trsuperobject(49,6,6,"Bunu, yalnız insanları hoşnut etmek isteyenler gibi göze hoş görünmek için yapmayın. Mesihin kulları olarak Tanrının isteğini candan yerine getirin."));
trsuperobject.biblemap.put("b49_6_7", new trsuperobject(49,6,7,"İnsanlara değil, Rabbe hizmet eder gibi gönülden hizmet edin."));
trsuperobject.biblemap.put("b49_6_8", new trsuperobject(49,6,8,"Çünkü ister köle ister özgür olsun, herkesin yaptığı her iyiliğin karşılığını Rabden alacağını biliyorsunuz."));
trsuperobject.biblemap.put("b49_6_9", new trsuperobject(49,6,9,"Ey efendiler, siz de kölelerinize aynı biçimde davranın. Artık onları tehdit etmeyin. Onların da sizin de Efendinizin göklerde olduğunu ve insanlar arasında ayrım yapmadığını biliyorsunuz."));
trsuperobject.biblemap.put("b49_6_10", new trsuperobject(49,6,10,"Son olarak Rabde, Onun üstün gücüyle güçlenin."));
trsuperobject.biblemap.put("b49_6_11", new trsuperobject(49,6,11,"İblisin hilelerine karşı durabilmek için Tanrının sağladığı bütün silahları kuşanın."));
trsuperobject.biblemap.put("b49_6_12", new trsuperobject(49,6,12,"Çünkü savaşımız insanlara karşı değil, yönetimlere, hükümranlıklara, bu karanlık dünyanın güçlerine, kötülüğün göksel yerlerdeki ruhsal ordularına karşıdır."));
trsuperobject.biblemap.put("b49_6_13", new trsuperobject(49,6,13,"Bu nedenle, kötü günde dayanabilmek, gerekli her şeyi yaptıktan sonra yerinizde durabilmek için Tanrının bütün silahlarını kuşanın."));
trsuperobject.biblemap.put("b49_6_14-15", new trsuperobject(49,6,14-15,"Böylece, belinizi gerçekle kuşatmış, göğsünüze doğruluk zırhını takmış ve ayaklarınıza esenlik Müjdesini yayma hazırlığını giymiş olarak yerinizde durun."));
trsuperobject.biblemap.put("b49_6_16", new trsuperobject(49,6,16,"Bunların hepsine ek olarak, Şeytanın bütün ateşli oklarını söndürebileceğiniz iman kalkanını alın."));
trsuperobject.biblemap.put("b49_6_17", new trsuperobject(49,6,17,"Kurtuluş miğferini ve Ruhun kılıcını, yani Tanrı sözünü alın."));
trsuperobject.biblemap.put("b49_6_18", new trsuperobject(49,6,18,"Her türlü dua ve yalvarışla, her zaman Ruhun yönetiminde dua edin. Bu amaçla, bütün kutsallar için yalvarışta bulunarak tam bir adanmışlıkla uyanık durun."));
trsuperobject.biblemap.put("b49_6_19", new trsuperobject(49,6,19,"Ağzımı her açtığımda bana gerekli söz verilsin diye benim için de dua edin; öyle ki, Müjdenin sırrını cesaretle bildirebileyim."));
trsuperobject.biblemap.put("b49_6_20", new trsuperobject(49,6,20,"Uğruna zincire vurulmuş durumda elçilik ettiğim Müjdeyi gerektiği gibi cesaretle duyurabilmem için dua edin."));
trsuperobject.biblemap.put("b49_6_21", new trsuperobject(49,6,21,"Nasıl olduğumu, ne yaptığımı sizin de bilmeniz için sevgili kardeşimiz, Rabbin güvenilir hizmetkârı Tihikos size her şeyi bildirecektir."));
trsuperobject.biblemap.put("b49_6_22", new trsuperobject(49,6,22,"Kendisini bu amaçla, durumumuzu iletmesi ve yüreklerinize cesaret vermesi için size gönderiyorum."));
trsuperobject.biblemap.put("b49_6_23", new trsuperobject(49,6,23,"Baba Tanrıdan ve Rab İsa Mesihten kardeşlere imanla birlikte esenlik ve sevgi diliyorum."));
trsuperobject.biblemap.put("b49_6_24", new trsuperobject(49,6,24,"Tanrı'nın lütfu Rabbimiz İsa Mesih'i ölümsüz sevgiyle sevenlerin hepsiyle birlikte olsun."));

}

}