package en.bible;

public class enbible49 {

public enbible49() {

putmapbible49();

}

private void putmapbible49() {

ensuperobject.biblemap.put("b49_1_1", new ensuperobject(49,1,1,"Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus, and to the faithful in Christ Jesus:"));
ensuperobject.biblemap.put("b49_1_2", new ensuperobject(49,1,2,"Grace be to you, and peace, from God our Father, and from the Lord Jesus Christ."));
ensuperobject.biblemap.put("b49_1_3", new ensuperobject(49,1,3,"Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places in Christ:"));
ensuperobject.biblemap.put("b49_1_4", new ensuperobject(49,1,4,"According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love:"));
ensuperobject.biblemap.put("b49_1_5", new ensuperobject(49,1,5,"Having predestinated us unto the adoption of children by Jesus Christ to himself, according to the good pleasure of his will,"));
ensuperobject.biblemap.put("b49_1_6", new ensuperobject(49,1,6,"To the praise of the glory of his grace, wherein he hath made us accepted in the beloved."));
ensuperobject.biblemap.put("b49_1_7", new ensuperobject(49,1,7,"In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace;"));
ensuperobject.biblemap.put("b49_1_8", new ensuperobject(49,1,8,"Wherein he hath abounded toward us in all wisdom and prudence;"));
ensuperobject.biblemap.put("b49_1_9", new ensuperobject(49,1,9,"Having made known unto us the mystery of his will, according to his good pleasure which he hath purposed in himself:"));
ensuperobject.biblemap.put("b49_1_10", new ensuperobject(49,1,10,"That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; even in him:"));
ensuperobject.biblemap.put("b49_1_11", new ensuperobject(49,1,11,"In whom also we have obtained an inheritance, being predestinated according to the purpose of him who worketh all things after the counsel of his own will:"));
ensuperobject.biblemap.put("b49_1_12", new ensuperobject(49,1,12,"That we should be to the praise of his glory, who first trusted in Christ."));
ensuperobject.biblemap.put("b49_1_13", new ensuperobject(49,1,13,"In whom ye also trusted, after that ye heard the word of truth, the gospel of your salvation: in whom also after that ye believed, ye were sealed with that holy Spirit of promise,"));
ensuperobject.biblemap.put("b49_1_14", new ensuperobject(49,1,14,"Which is the earnest of our inheritance until the redemption of the purchased possession, unto the praise of his glory."));
ensuperobject.biblemap.put("b49_1_15", new ensuperobject(49,1,15,"Wherefore I also, after I heard of your faith in the Lord Jesus, and love unto all the saints,"));
ensuperobject.biblemap.put("b49_1_16", new ensuperobject(49,1,16,"Cease not to give thanks for you, making mention of you in my prayers;"));
ensuperobject.biblemap.put("b49_1_17", new ensuperobject(49,1,17,"That the God of our Lord Jesus Christ, the Father of glory, may give unto you the spirit of wisdom and revelation in the knowledge of him:"));
ensuperobject.biblemap.put("b49_1_18", new ensuperobject(49,1,18,"The eyes of your understanding being enlightened; that ye may know what is the hope of his calling, and what the riches of the glory of his inheritance in the saints,"));
ensuperobject.biblemap.put("b49_1_19", new ensuperobject(49,1,19,"And what is the exceeding greatness of his power to us-ward who believe, according to the working of his mighty power,"));
ensuperobject.biblemap.put("b49_1_20", new ensuperobject(49,1,20,"Which he wrought in Christ, when he raised him from the dead, and set him at his own right hand in the heavenly places,"));
ensuperobject.biblemap.put("b49_1_21", new ensuperobject(49,1,21,"Far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come:"));
ensuperobject.biblemap.put("b49_1_22", new ensuperobject(49,1,22,"And hath put all things under his feet, and gave him to be the head over all things to the church,"));
ensuperobject.biblemap.put("b49_1_23", new ensuperobject(49,1,23,"Which is his body, the fulness of him that filleth all in all."));
ensuperobject.biblemap.put("b49_2_1", new ensuperobject(49,2,1,"And you hath he quickened, who were dead in trespasses and sins;"));
ensuperobject.biblemap.put("b49_2_2", new ensuperobject(49,2,2,"Wherein in time past ye walked according to the course of this world, according to the prince of the power of the air, the spirit that now worketh in the children of disobedience:"));
ensuperobject.biblemap.put("b49_2_3", new ensuperobject(49,2,3,"Among whom also we all had our conversation in times past in the lusts of our flesh, fulfilling the desires of the flesh and of the mind; and were by nature the children of wrath, even as others."));
ensuperobject.biblemap.put("b49_2_4", new ensuperobject(49,2,4,"But God, who is rich in mercy, for his great love wherewith he loved us,"));
ensuperobject.biblemap.put("b49_2_5", new ensuperobject(49,2,5,"Even when we were dead in sins, hath quickened us together with Christ, (by grace ye are saved;)"));
ensuperobject.biblemap.put("b49_2_6", new ensuperobject(49,2,6,"And hath raised us up together, and made us sit together in heavenly places in Christ Jesus:"));
ensuperobject.biblemap.put("b49_2_7", new ensuperobject(49,2,7,"That in the ages to come he might shew the exceeding riches of his grace in his kindness toward us through Christ Jesus."));
ensuperobject.biblemap.put("b49_2_8", new ensuperobject(49,2,8,"For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:"));
ensuperobject.biblemap.put("b49_2_9", new ensuperobject(49,2,9,"Not of works, lest any man should boast."));
ensuperobject.biblemap.put("b49_2_10", new ensuperobject(49,2,10,"For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them."));
ensuperobject.biblemap.put("b49_2_11", new ensuperobject(49,2,11,"Wherefore remember, that ye being in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;"));
ensuperobject.biblemap.put("b49_2_12", new ensuperobject(49,2,12,"That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:"));
ensuperobject.biblemap.put("b49_2_13", new ensuperobject(49,2,13,"But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ."));
ensuperobject.biblemap.put("b49_2_14", new ensuperobject(49,2,14,"For he is our peace, who hath made both one, and hath broken down the middle wall of partition between us;"));
ensuperobject.biblemap.put("b49_2_15", new ensuperobject(49,2,15,"Having abolished in his flesh the enmity, even the law of commandments contained in ordinances; for to make in himself of twain one new man, so making peace;"));
ensuperobject.biblemap.put("b49_2_16", new ensuperobject(49,2,16,"And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby:"));
ensuperobject.biblemap.put("b49_2_17", new ensuperobject(49,2,17,"And came and preached peace to you which were afar off, and to them that were nigh."));
ensuperobject.biblemap.put("b49_2_18", new ensuperobject(49,2,18,"For through him we both have access by one Spirit unto the Father."));
ensuperobject.biblemap.put("b49_2_19", new ensuperobject(49,2,19,"Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God;"));
ensuperobject.biblemap.put("b49_2_20", new ensuperobject(49,2,20,"And are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone;"));
ensuperobject.biblemap.put("b49_2_21", new ensuperobject(49,2,21,"In whom all the building fitly framed together groweth unto an holy temple in the Lord:"));
ensuperobject.biblemap.put("b49_2_22", new ensuperobject(49,2,22,"In whom ye also are builded together for an habitation of God through the Spirit."));
ensuperobject.biblemap.put("b49_3_1", new ensuperobject(49,3,1,"For this cause I Paul, the prisoner of Jesus Christ for you Gentiles,"));
ensuperobject.biblemap.put("b49_3_2", new ensuperobject(49,3,2,"If ye have heard of the dispensation of the grace of God which is given me to you-ward:"));
ensuperobject.biblemap.put("b49_3_3", new ensuperobject(49,3,3,"How that by revelation he made known unto me the mystery; (as I wrote afore in few words,"));
ensuperobject.biblemap.put("b49_3_4", new ensuperobject(49,3,4,"Whereby, when ye read, ye may understand my knowledge in the mystery of Christ)"));
ensuperobject.biblemap.put("b49_3_5", new ensuperobject(49,3,5,"Which in other ages was not made known unto the sons of men, as it is now revealed unto his holy apostles and prophets by the Spirit;"));
ensuperobject.biblemap.put("b49_3_6", new ensuperobject(49,3,6,"That the Gentiles should be fellowheirs, and of the same body, and partakers of his promise in Christ by the gospel:"));
ensuperobject.biblemap.put("b49_3_7", new ensuperobject(49,3,7,"Whereof I was made a minister, according to the gift of the grace of God given unto me by the effectual working of his power."));
ensuperobject.biblemap.put("b49_3_8", new ensuperobject(49,3,8,"Unto me, who am less than the least of all saints, is this grace given, that I should preach among the Gentiles the unsearchable riches of Christ;"));
ensuperobject.biblemap.put("b49_3_9", new ensuperobject(49,3,9,"And to make all men see what is the fellowship of the mystery, which from the beginning of the world hath been hid in God, who created all things by Jesus Christ:"));
ensuperobject.biblemap.put("b49_3_10", new ensuperobject(49,3,10,"To the intent that now unto the principalities and powers in heavenly places might be known by the church the manifold wisdom of God,"));
ensuperobject.biblemap.put("b49_3_11", new ensuperobject(49,3,11,"According to the eternal purpose which he purposed in Christ Jesus our Lord:"));
ensuperobject.biblemap.put("b49_3_12", new ensuperobject(49,3,12,"In whom we have boldness and access with confidence by the faith of him."));
ensuperobject.biblemap.put("b49_3_13", new ensuperobject(49,3,13,"Wherefore I desire that ye faint not at my tribulations for you, which is your glory."));
ensuperobject.biblemap.put("b49_3_14", new ensuperobject(49,3,14,"For this cause I bow my knees unto the Father of our Lord Jesus Christ,"));
ensuperobject.biblemap.put("b49_3_15", new ensuperobject(49,3,15,"Of whom the whole family in heaven and earth is named,"));
ensuperobject.biblemap.put("b49_3_16", new ensuperobject(49,3,16,"That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man;"));
ensuperobject.biblemap.put("b49_3_17", new ensuperobject(49,3,17,"That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love,"));
ensuperobject.biblemap.put("b49_3_18", new ensuperobject(49,3,18,"May be able to comprehend with all saints what is the breadth, and length, and depth, and height;"));
ensuperobject.biblemap.put("b49_3_19", new ensuperobject(49,3,19,"And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God."));
ensuperobject.biblemap.put("b49_3_20", new ensuperobject(49,3,20,"Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us,"));
ensuperobject.biblemap.put("b49_3_21", new ensuperobject(49,3,21,"Unto him be glory in the church by Christ Jesus throughout all ages, world without end. Amen."));
ensuperobject.biblemap.put("b49_4_1", new ensuperobject(49,4,1,"I therefore, the prisoner of the Lord, beseech you that ye walk worthy of the vocation wherewith ye are called,"));
ensuperobject.biblemap.put("b49_4_2", new ensuperobject(49,4,2,"With all lowliness and meekness, with longsuffering, forbearing one another in love;"));
ensuperobject.biblemap.put("b49_4_3", new ensuperobject(49,4,3,"Endeavouring to keep the unity of the Spirit in the bond of peace."));
ensuperobject.biblemap.put("b49_4_4", new ensuperobject(49,4,4,"There is one body, and one Spirit, even as ye are called in one hope of your calling;"));
ensuperobject.biblemap.put("b49_4_5", new ensuperobject(49,4,5,"One Lord, one faith, one baptism,"));
ensuperobject.biblemap.put("b49_4_6", new ensuperobject(49,4,6,"One God and Father of all, who is above all, and through all, and in you all."));
ensuperobject.biblemap.put("b49_4_7", new ensuperobject(49,4,7,"But unto every one of us is given grace according to the measure of the gift of Christ."));
ensuperobject.biblemap.put("b49_4_8", new ensuperobject(49,4,8,"Wherefore he saith, When he ascended up on high, he led captivity captive, and gave gifts unto men."));
ensuperobject.biblemap.put("b49_4_9", new ensuperobject(49,4,9,"(Now that he ascended, what is it but that he also descended first into the lower parts of the earth?"));
ensuperobject.biblemap.put("b49_4_10", new ensuperobject(49,4,10,"He that descended is the same also that ascended up far above all heavens, that he might fill all things.)"));
ensuperobject.biblemap.put("b49_4_11", new ensuperobject(49,4,11,"And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers;"));
ensuperobject.biblemap.put("b49_4_12", new ensuperobject(49,4,12,"For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ:"));
ensuperobject.biblemap.put("b49_4_13", new ensuperobject(49,4,13,"Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:"));
ensuperobject.biblemap.put("b49_4_14", new ensuperobject(49,4,14,"That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men, and cunning craftiness, whereby they lie in wait to deceive;"));
ensuperobject.biblemap.put("b49_4_15", new ensuperobject(49,4,15,"But speaking the truth in love, may grow up into him in all things, which is the head, even Christ:"));
ensuperobject.biblemap.put("b49_4_16", new ensuperobject(49,4,16,"From whom the whole body fitly joined together and compacted by that which every joint supplieth, according to the effectual working in the measure of every part, maketh increase of the body unto the edifying of itself in love."));
ensuperobject.biblemap.put("b49_4_17", new ensuperobject(49,4,17,"This I say therefore, and testify in the Lord, that ye henceforth walk not as other Gentiles walk, in the vanity of their mind,"));
ensuperobject.biblemap.put("b49_4_18", new ensuperobject(49,4,18,"Having the understanding darkened, being alienated from the life of God through the ignorance that is in them, because of the blindness of their heart:"));
ensuperobject.biblemap.put("b49_4_19", new ensuperobject(49,4,19,"Who being past feeling have given themselves over unto lasciviousness, to work all uncleanness with greediness."));
ensuperobject.biblemap.put("b49_4_20", new ensuperobject(49,4,20,"But ye have not so learned Christ;"));
ensuperobject.biblemap.put("b49_4_21", new ensuperobject(49,4,21,"If so be that ye have heard him, and have been taught by him, as the truth is in Jesus:"));
ensuperobject.biblemap.put("b49_4_22", new ensuperobject(49,4,22,"That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts;"));
ensuperobject.biblemap.put("b49_4_23", new ensuperobject(49,4,23,"And be renewed in the spirit of your mind;"));
ensuperobject.biblemap.put("b49_4_24", new ensuperobject(49,4,24,"And that ye put on the new man, which after God is created in righteousness and true holiness."));
ensuperobject.biblemap.put("b49_4_25", new ensuperobject(49,4,25,"Wherefore putting away lying, speak every man truth with his neighbour: for we are members one of another."));
ensuperobject.biblemap.put("b49_4_26", new ensuperobject(49,4,26,"Be ye angry, and sin not: let not the sun go down upon your wrath:"));
ensuperobject.biblemap.put("b49_4_27", new ensuperobject(49,4,27,"Neither give place to the devil."));
ensuperobject.biblemap.put("b49_4_28", new ensuperobject(49,4,28,"Let him that stole steal no more: but rather let him labour, working with his hands the thing which is good, that he may have to give to him that needeth."));
ensuperobject.biblemap.put("b49_4_29", new ensuperobject(49,4,29,"Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace unto the hearers."));
ensuperobject.biblemap.put("b49_4_30", new ensuperobject(49,4,30,"And grieve not the holy Spirit of God, whereby ye are sealed unto the day of redemption."));
ensuperobject.biblemap.put("b49_4_31", new ensuperobject(49,4,31,"Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice:"));
ensuperobject.biblemap.put("b49_4_32", new ensuperobject(49,4,32,"And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you."));
ensuperobject.biblemap.put("b49_5_1", new ensuperobject(49,5,1,"Be ye therefore followers of God, as dear children;"));
ensuperobject.biblemap.put("b49_5_2", new ensuperobject(49,5,2,"And walk in love, as Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweetsmelling savour."));
ensuperobject.biblemap.put("b49_5_3", new ensuperobject(49,5,3,"But fornication, and all uncleanness, or covetousness, let it not be once named among you, as becometh saints;"));
ensuperobject.biblemap.put("b49_5_4", new ensuperobject(49,5,4,"Neither filthiness, nor foolish talking, nor jesting, which are not convenient: but rather giving of thanks."));
ensuperobject.biblemap.put("b49_5_5", new ensuperobject(49,5,5,"For this ye know, that no whoremonger, nor unclean person, nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ and of God."));
ensuperobject.biblemap.put("b49_5_6", new ensuperobject(49,5,6,"Let no man deceive you with vain words: for because of these things cometh the wrath of God upon the children of disobedience."));
ensuperobject.biblemap.put("b49_5_7", new ensuperobject(49,5,7,"Be not ye therefore partakers with them."));
ensuperobject.biblemap.put("b49_5_8", new ensuperobject(49,5,8,"For ye were sometimes darkness, but now are ye light in the Lord: walk as children of light:"));
ensuperobject.biblemap.put("b49_5_9", new ensuperobject(49,5,9,"(For the fruit of the Spirit is in all goodness and righteousness and truth;)"));
ensuperobject.biblemap.put("b49_5_10", new ensuperobject(49,5,10,"Proving what is acceptable unto the Lord."));
ensuperobject.biblemap.put("b49_5_11", new ensuperobject(49,5,11,"And have no fellowship with the unfruitful works of darkness, but rather reprove them."));
ensuperobject.biblemap.put("b49_5_12", new ensuperobject(49,5,12,"For it is a shame even to speak of those things which are done of them in secret."));
ensuperobject.biblemap.put("b49_5_13", new ensuperobject(49,5,13,"But all things that are reproved are made manifest by the light: for whatsoever doth make manifest is light."));
ensuperobject.biblemap.put("b49_5_14", new ensuperobject(49,5,14,"Wherefore he saith, Awake thou that sleepest, and arise from the dead, and Christ shall give thee light."));
ensuperobject.biblemap.put("b49_5_15", new ensuperobject(49,5,15,"See then that ye walk circumspectly, not as fools, but as wise,"));
ensuperobject.biblemap.put("b49_5_16", new ensuperobject(49,5,16,"Redeeming the time, because the days are evil."));
ensuperobject.biblemap.put("b49_5_17", new ensuperobject(49,5,17,"Wherefore be ye not unwise, but understanding what the will of the Lord is."));
ensuperobject.biblemap.put("b49_5_18", new ensuperobject(49,5,18,"And be not drunk with wine, wherein is excess; but be filled with the Spirit;"));
ensuperobject.biblemap.put("b49_5_19", new ensuperobject(49,5,19,"Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord;"));
ensuperobject.biblemap.put("b49_5_20", new ensuperobject(49,5,20,"Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ;"));
ensuperobject.biblemap.put("b49_5_21", new ensuperobject(49,5,21,"Submitting yourselves one to another in the fear of God."));
ensuperobject.biblemap.put("b49_5_22", new ensuperobject(49,5,22,"Wives, submit yourselves unto your own husbands, as unto the Lord."));
ensuperobject.biblemap.put("b49_5_23", new ensuperobject(49,5,23,"For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body."));
ensuperobject.biblemap.put("b49_5_24", new ensuperobject(49,5,24,"Therefore as the church is subject unto Christ, so let the wives be to their own husbands in every thing."));
ensuperobject.biblemap.put("b49_5_25", new ensuperobject(49,5,25,"Husbands, love your wives, even as Christ also loved the church, and gave himself for it;"));
ensuperobject.biblemap.put("b49_5_26", new ensuperobject(49,5,26,"That he might sanctify and cleanse it with the washing of water by the word,"));
ensuperobject.biblemap.put("b49_5_27", new ensuperobject(49,5,27,"That he might present it to himself a glorious church, not having spot, or wrinkle, or any such thing; but that it should be holy and without blemish."));
ensuperobject.biblemap.put("b49_5_28", new ensuperobject(49,5,28,"So ought men to love their wives as their own bodies. He that loveth his wife loveth himself."));
ensuperobject.biblemap.put("b49_5_29", new ensuperobject(49,5,29,"For no man ever yet hated his own flesh; but nourisheth and cherisheth it, even as the Lord the church:"));
ensuperobject.biblemap.put("b49_5_30", new ensuperobject(49,5,30,"For we are members of his body, of his flesh, and of his bones."));
ensuperobject.biblemap.put("b49_5_31", new ensuperobject(49,5,31,"For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh."));
ensuperobject.biblemap.put("b49_5_32", new ensuperobject(49,5,32,"This is a great mystery: but I speak concerning Christ and the church."));
ensuperobject.biblemap.put("b49_5_33", new ensuperobject(49,5,33,"Nevertheless let every one of you in particular so love his wife even as himself; and the wife see that she reverence her husband."));
ensuperobject.biblemap.put("b49_6_1", new ensuperobject(49,6,1,"Children, obey your parents in the Lord: for this is right."));
ensuperobject.biblemap.put("b49_6_2", new ensuperobject(49,6,2,"Honour thy father and mother; which is the first commandment with promise;"));
ensuperobject.biblemap.put("b49_6_3", new ensuperobject(49,6,3,"That it may be well with thee, and thou mayest live long on the earth."));
ensuperobject.biblemap.put("b49_6_4", new ensuperobject(49,6,4,"And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord."));
ensuperobject.biblemap.put("b49_6_5", new ensuperobject(49,6,5,"Servants, be obedient to them that are your masters according to the flesh, with fear and trembling, in singleness of your heart, as unto Christ;"));
ensuperobject.biblemap.put("b49_6_6", new ensuperobject(49,6,6,"Not with eyeservice, as menpleasers; but as the servants of Christ, doing the will of God from the heart;"));
ensuperobject.biblemap.put("b49_6_7", new ensuperobject(49,6,7,"With good will doing service, as to the Lord, and not to men:"));
ensuperobject.biblemap.put("b49_6_8", new ensuperobject(49,6,8,"Knowing that whatsoever good thing any man doeth, the same shall he receive of the Lord, whether he be bond or free."));
ensuperobject.biblemap.put("b49_6_9", new ensuperobject(49,6,9,"And, ye masters, do the same things unto them, forbearing threatening: knowing that your Master also is in heaven; neither is there respect of persons with him."));
ensuperobject.biblemap.put("b49_6_10", new ensuperobject(49,6,10,"Finally, my brethren, be strong in the Lord, and in the power of his might."));
ensuperobject.biblemap.put("b49_6_11", new ensuperobject(49,6,11,"Put on the whole armour of God, that ye may be able to stand against the wiles of the devil."));
ensuperobject.biblemap.put("b49_6_12", new ensuperobject(49,6,12,"For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places."));
ensuperobject.biblemap.put("b49_6_13", new ensuperobject(49,6,13,"Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day, and having done all, to stand."));
ensuperobject.biblemap.put("b49_6_14", new ensuperobject(49,6,14,"Stand therefore, having your loins girt about with truth, and having on the breastplate of righteousness;"));
ensuperobject.biblemap.put("b49_6_15", new ensuperobject(49,6,15,"And your feet shod with the preparation of the gospel of peace;"));
ensuperobject.biblemap.put("b49_6_16", new ensuperobject(49,6,16,"Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked."));
ensuperobject.biblemap.put("b49_6_17", new ensuperobject(49,6,17,"And take the helmet of salvation, and the sword of the Spirit, which is the word of God:"));
ensuperobject.biblemap.put("b49_6_18", new ensuperobject(49,6,18,"Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints;"));
ensuperobject.biblemap.put("b49_6_19", new ensuperobject(49,6,19,"And for me, that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel,"));
ensuperobject.biblemap.put("b49_6_20", new ensuperobject(49,6,20,"For which I am an ambassador in bonds: that therein I may speak boldly, as I ought to speak."));
ensuperobject.biblemap.put("b49_6_21", new ensuperobject(49,6,21,"But that ye also may know my affairs, and how I do, Tychicus, a beloved brother and faithful minister in the Lord, shall make known to you all things:"));
ensuperobject.biblemap.put("b49_6_22", new ensuperobject(49,6,22,"Whom I have sent unto you for the same purpose, that ye might know our affairs, and that he might comfort your hearts."));
ensuperobject.biblemap.put("b49_6_23", new ensuperobject(49,6,23,"Peace be to the brethren, and love with faith, from God the Father and the Lord Jesus Christ."));
ensuperobject.biblemap.put("b49_6_24", new ensuperobject(49,6,24,"Grace be with all them that love our Lord Jesus Christ in sincerity. Amen."));

}

}