package hu.bible;

public class hubible21 {

public hubible21() {

putmapbible21();

}

private void putmapbible21() {

husuperobject.biblemap.put("b21_1_1", new husuperobject(21,1,1,"A prédikátornak, Dávid fiának, Jeruzsálem királyának beszédei."));
husuperobject.biblemap.put("b21_1_2", new husuperobject(21,1,2,"Felette nagy hiábavalóság, azt mondja a prédikátor; felette nagy hiábavalóság! Minden hiábavalóság!"));
husuperobject.biblemap.put("b21_1_3", new husuperobject(21,1,3,"Micsoda haszna van az embernek minden õ munkájában, melylyel munkálkodik a nap alatt?"));
husuperobject.biblemap.put("b21_1_4", new husuperobject(21,1,4,"Egyik nemzetség elmegy, és a másik eljõ; a föld pedig mindörökké megmarad."));
husuperobject.biblemap.put("b21_1_5", new husuperobject(21,1,5,"És a nap feltámad, és elnyugszik a nap; és az õ helyére siet, a hol õ [ismét] feltámad."));
husuperobject.biblemap.put("b21_1_6", new husuperobject(21,1,6,"Siet délre, és átmegy észak felé; körbe-körbe siet a szél, és a maga keringéséhez visszatér a szél."));
husuperobject.biblemap.put("b21_1_7", new husuperobject(21,1,7,"Minden folyóvíz siet a tengerbe; mindazáltal a tenger mégis meg nem telik: akármicsoda helyre a folyóvizek siessenek, ugyanazon helyre térnek vissza."));
husuperobject.biblemap.put("b21_1_8", new husuperobject(21,1,8,"Minden dolgok [mint] fáradoznak, senki ki nem mondhatja; nem elégednék meg a szem látván, sem be nem teljesednék hallásával a fül."));
husuperobject.biblemap.put("b21_1_9", new husuperobject(21,1,9,"A mi volt, ugyanaz, a mi ezután is lesz, és a mi történt, ugyanaz, a mi ezután is történik; és semmi nincs új dolog a nap alatt."));
husuperobject.biblemap.put("b21_1_10", new husuperobject(21,1,10,"Van valami, a mirõl mondják: nézd ezt, új ez; régen volt már száz esztendõkön át, melyek mi elõttünk voltak."));
husuperobject.biblemap.put("b21_1_11", new husuperobject(21,1,11,"Nincs emlékezet az elõbbiekrõl; azonképen az utolsó dolgokról is, melyek jövendõk, nem lesz emlékezet azoknál, a kik azután lesznek."));
husuperobject.biblemap.put("b21_1_12", new husuperobject(21,1,12,"Én prédikátor, királya voltam Izráelnek Jeruzsálemben."));
husuperobject.biblemap.put("b21_1_13", new husuperobject(21,1,13,"És adám az én elmémet mindazok vizsgálására és bölcsen való tudakozására, melyek lesznek az ég alatt. Ez gonosz hiábavaló foglalatosság, melyet adott Isten az emberek fiainak, hogy gyötrõdjenek vele."));
husuperobject.biblemap.put("b21_1_14", new husuperobject(21,1,14,"Láttam minden dolgokat, melyek lesznek a nap alatt, és ímé minden csak hiábavalóság, és a léleknek gyötrelme!"));
husuperobject.biblemap.put("b21_1_15", new husuperobject(21,1,15,"Az egyenetlen meg nem egyenesíthetõ, és a fogyatkozás meg nem számlálható."));
husuperobject.biblemap.put("b21_1_16", new husuperobject(21,1,16,"Szóltam az én elmémmel, mondván: ímé, én nagygyá lettem, és gyûjtöttem bölcseséget mindazok felett, a kik fõk voltak én elõttem Jeruzsálemben, és az én elmém bõven látott bölcseséget és tudományt!"));
husuperobject.biblemap.put("b21_1_17", new husuperobject(21,1,17,"Adtam annakfelette az én elmémet a bölcseségnek tudására, és az esztelenségnek és bolondságnak megtudására. Megtudtam, hogy ez is a lélek gyötrelme."));
husuperobject.biblemap.put("b21_2_1", new husuperobject(21,2,1,"Mert a bölcsességnek sokaságában sok búsulás van, és valaki öregbíti a tudományt, öregbíti a gyötrelmet."));
husuperobject.biblemap.put("b21_2_2", new husuperobject(21,2,2,"Mondék az én szívemben: no, megpróbállak téged a vígan való lakásban, hogy lásd meg, mi a jó! És ímé, az is hiábavalóság!"));
husuperobject.biblemap.put("b21_2_3", new husuperobject(21,2,3,"A nevetésrõl azt mondom: bolondság! a vígasságról pedig: mit használ az?"));
husuperobject.biblemap.put("b21_2_4", new husuperobject(21,2,4,"Elvégezém az én szívemben, hogy boritalra adom magamat, (pedig szívem a bölcseséget követé) és elõveszem ezt a bolondságot, mígnem meglátom, hogy az emberek fiainak mi volna jó, a mit cselekedjenek az ég alatt, az életök napjainak száma szerint."));
husuperobject.biblemap.put("b21_2_5", new husuperobject(21,2,5,"Felette nagy dolgokat cselekedtem; építék magamnak házakat; ülteték magamnak szõlõket."));
husuperobject.biblemap.put("b21_2_6", new husuperobject(21,2,6,"Csinálék magamnak kerteket és ékességre való kerteket, és ülteték beléjök mindenféle gyümölcstermõ fákat."));
husuperobject.biblemap.put("b21_2_7", new husuperobject(21,2,7,"Csinálék magamnak víz[tartó] tavakat, hogy azokból öntözzem a fáknak sarjadó erdejét."));
husuperobject.biblemap.put("b21_2_8", new husuperobject(21,2,8,"Szerzék szolgákat és szolgálókat, házamnál nevekedett szolgáim is voltak nékem; öreg és apró barmoknak nyájaival is többel bírtam mindazoknál, a kik voltak én elõttem Jeruzsálemben."));
husuperobject.biblemap.put("b21_2_9", new husuperobject(21,2,9,"Gyûjték magamnak ezüstöt és aranyat is, és királyok drágaságait és tartományokat; szerzék magamnak éneklõ férfiakat és éneklõ asszonyokat, és az emberek fiainak gyönyörûségit, asszonyt és asszonyokat."));
husuperobject.biblemap.put("b21_2_10", new husuperobject(21,2,10,"És nagygyá levék és megnevekedém mindazok felett, a kik elõttem voltak Jeruzsálemben; az én bölcseségem is helyén volt."));
husuperobject.biblemap.put("b21_2_11", new husuperobject(21,2,11,"Valamit kivánnak vala az én szemeim: meg nem fogtam azoktól, meg sem tartóztattam az én szívemet semmi vígasságtól, hanem az én szívem örvendezett minden én munkám[mal gyûjtött jók]ban; mivelhogy ez volt az én részem minden én munkáimból."));
husuperobject.biblemap.put("b21_2_12", new husuperobject(21,2,12,"És tekinték minden dolgaimra, melyeket cselekedtek vala az én kezeim, és az én munkámra, mit fáradsággal végeztem vala; és ímé, az mind hiábavalóság és a léleknek gyötrelme, és nincsen annak semmi haszna a nap alatt!"));
husuperobject.biblemap.put("b21_2_13", new husuperobject(21,2,13,"Azért fordulék én, hogy lássak bölcseséget és bolondságot és esztelenséget, az az hogy mit [cselekesz]nek az emberek, a kik a király után következnek: azt, a mit régen cselekedtek."));
husuperobject.biblemap.put("b21_2_14", new husuperobject(21,2,14,"És látám, hogy hasznosb a bölcseség a bolondságnál, miképen hasznosb a világosság a setétségnél."));
husuperobject.biblemap.put("b21_2_15", new husuperobject(21,2,15,"A bölcsnek szemei [vannak] a fejében; a bolond pedig setétben jár; de ugyan én megismerém, hogy ugyanazon egy végök lesz mindezeknek."));
husuperobject.biblemap.put("b21_2_16", new husuperobject(21,2,16,"Annakokáért mondám az én elmémben: bolondnak állapotja szerint lesz az én állapotom is, miért valék tehát én is bölcsebb? és mondék az én elmémben: ez is hiábavalóság!"));
husuperobject.biblemap.put("b21_2_17", new husuperobject(21,2,17,"Mert nem lesz emlékezete sem a bölcsnek, sem a bolondnak mindörökké; mivelhogy a következendõ idõkben már mind elfelejtetnek: és miképen meghal a bölcs, azonképen meghal a bolond is."));
husuperobject.biblemap.put("b21_2_18", new husuperobject(21,2,18,"Azért gyûlöltem az életet; mert gonosznak látszék nékem a dolog, a mi történik a nap alatt; mert mindez hiábavalóság, és a léleknek gyötrelme!"));
husuperobject.biblemap.put("b21_2_19", new husuperobject(21,2,19,"Gyûlöltem én minden munkámat is, melyet munkálkodom a nap alatt; mivelhogy el kell hagynom azt oly embernek, a ki én utánam lesz."));
husuperobject.biblemap.put("b21_2_20", new husuperobject(21,2,20,"És ki tudja, ha bölcs lesz-é vagy bolond? és [mégis] uralkodik minden munkámon, a mit cselekedtem és bölcsen szerzettem a nap alatt! Ez is hiábavalóság!"));
husuperobject.biblemap.put("b21_2_21", new husuperobject(21,2,21,"Annakokáért elfordulék én, megfogván reménységtõl az én szívemet minden munkám felõl, melylyel munkálódtam a nap alatt."));
husuperobject.biblemap.put("b21_2_22", new husuperobject(21,2,22,"Mert van oly ember, a kinek munkája [elvégeztetett] bölcseséggel, tudománynyal és jó kimenetellel; és oly embernek adja azt örökségül, a ki abban semmit sem munkálkodott. Ez is hiábavalóság és nagy gonosz!"));
husuperobject.biblemap.put("b21_2_23", new husuperobject(21,2,23,"Mert micsoda marad meg az embernek minden õ munkájából és elméjének nyughatatlan fáradozásából, melylyel õ munkálódott a nap alatt?"));
husuperobject.biblemap.put("b21_2_24", new husuperobject(21,2,24,"Holott minden napja bánat, és búsulás az õ foglalatossága, még éjjel is nem nyugodott az õ elméje. Ez is hiábavalóság!"));
husuperobject.biblemap.put("b21_2_25", new husuperobject(21,2,25,"Nincsen csak e jó is az embernek hatalmában, hogy egyék, igyék, és azt cselekedje, hogy az õ szíve lakozzék gyönyörûséggel az õ munkájából; ezt is láttam én, hogy az Istennek kezében van."));
husuperobject.biblemap.put("b21_2_26", new husuperobject(21,2,26,"Mert kicsoda ehetnék és élhetne gyönyörûségére rajtam kivül? [ (Ecclesiastes 2:27) Mert az embernek, a ki jó az õ szemei elõtt, adott [Isten] bölcseséget és tudományt és örömöt; a bûnösnek pedig adott foglalatosságot az egybegyûjtésre és az egybehordásra, hogy adja annak, a ki jó az Isten elõtt. Ez is hiábavalóság és az elmének gyötrelme! ]"));
husuperobject.biblemap.put("b21_3_1", new husuperobject(21,3,1,"Mindennek rendelt ideje [van], és ideje [van] az ég alatt minden akaratnak."));
husuperobject.biblemap.put("b21_3_2", new husuperobject(21,3,2,"Ideje [van] a születésnek és ideje a meghalásnak; ideje az ültetésnek, ideje annak kiszaggatásának, a mi ültettetett."));
husuperobject.biblemap.put("b21_3_3", new husuperobject(21,3,3,"Ideje [van] a megölésnek és ideje a meggyógyításnak; ideje a rontásnak és ideje az építésnek."));
husuperobject.biblemap.put("b21_3_4", new husuperobject(21,3,4,"Ideje [van] a sírásnak és ideje a nevetésnek; ideje a jajgatásnak és ideje a szökdelésnek."));
husuperobject.biblemap.put("b21_3_5", new husuperobject(21,3,5,"Ideje [van] a kövek elhányásának és ideje a kövek egybegyûjtésének; ideje az ölelgetésnek és ideje az ölelgetéstõl való eltávozásnak."));
husuperobject.biblemap.put("b21_3_6", new husuperobject(21,3,6,"Ideje [van] a keresésnek és ideje a vesztésnek; ideje a megõrzésnek és ideje az eldobásnak."));
husuperobject.biblemap.put("b21_3_7", new husuperobject(21,3,7,"Ideje [van] a szakgatásnak és ideje a megvarrásnak; ideje a hallgatásnak és ideje a szólásnak."));
husuperobject.biblemap.put("b21_3_8", new husuperobject(21,3,8,"Ideje [van] a szeretésnek és ideje a gyûlölésnek; ideje a hadakozásnak és ideje a békességnek."));
husuperobject.biblemap.put("b21_3_9", new husuperobject(21,3,9,"Micsoda haszna van a munkásnak abban, a miben õ munkálkodik?"));
husuperobject.biblemap.put("b21_3_10", new husuperobject(21,3,10,"Láttam a foglalatosságot, melyet adott Isten az emberek fiainak, hogy fáradozzanak benne."));
husuperobject.biblemap.put("b21_3_11", new husuperobject(21,3,11,"Mindent szépen csinált az õ idejében, e világot is adta az [emberek ]elméjébe, csakhogy úgy, hogy az ember meg nem foghatja [mindazt] a dolgot, a mit az Isten cselekszik kezdettõl fogva mindvégig."));
husuperobject.biblemap.put("b21_3_12", new husuperobject(21,3,12,"Megismertem, hogy nem tehetnek jobbat, mint hogy örvendezzen [kiki,] és hogy [a maga] javát cselekedje az õ életében."));
husuperobject.biblemap.put("b21_3_13", new husuperobject(21,3,13,"De még az is, hogy az ember eszik és iszik, és jól él az õ egész munkájából, az Istennek ajándéka."));
husuperobject.biblemap.put("b21_3_14", new husuperobject(21,3,14,"Tudom, hogy valamit Isten cselekszik, az lesz örökké, ahhoz nincs mit adni és abból nincs mit elvenni; és az Isten ezt a végre míveli, hogy az õ orczáját rettegjék."));
husuperobject.biblemap.put("b21_3_15", new husuperobject(21,3,15,"A mi [most] történik, régen megvan, és a mi következik, immár megvolt, és az Isten visszahozza, a mi elmult."));
husuperobject.biblemap.put("b21_3_16", new husuperobject(21,3,16,"Láttam annakfelette a nap alatt, hogy az ítéletnek helyén hamisság, és az igazságnak helyén latorság van."));
husuperobject.biblemap.put("b21_3_17", new husuperobject(21,3,17,"És mondék magamban: az igazat és a hamisat megítéli az Isten; mert minden [ember] akaratjának ideje van, és minden dolognak õ nála."));
husuperobject.biblemap.put("b21_3_18", new husuperobject(21,3,18,"Így szólék azért magamban: az emberek fiai miatt [van ez így], hogy kiválogassa õket az Isten, és hogy meglássák, hogy õk magokban véve az oktalan állatok[hoz hasonlók]."));
husuperobject.biblemap.put("b21_3_19", new husuperobject(21,3,19,"Az emberek fiainak vége hasonló az oktalan állatnak végéhez, és egyenlõ végök van azoknak; a mint meghal egyik, úgy meghal a másik is, és ugyanazon egy lélek van mindenikben; és az embernek nagyobb méltósága nincs az oktalan állatoknál, mert minden hiábavalóság."));
husuperobject.biblemap.put("b21_3_20", new husuperobject(21,3,20,"Mindenik ugyanazon egy helyre megy; mindenik a porból való, és mindenik porrá lesz."));
husuperobject.biblemap.put("b21_3_21", new husuperobject(21,3,21,"Vajjon kicsoda vette eszébe az ember lelkét, hogy felmegy-é; és az oktalan állat lelkét, hogy a föld alá megy-é?"));
husuperobject.biblemap.put("b21_3_22", new husuperobject(21,3,22,"Azért úgy láttam, hogy semmi sincs jobb, mint hogy az ember örvendezzen az õ dolgaiban, mivelhogy ez az õ része [e világban:] mert ki hozhatja õt [vissza,] hogy lássa, mi lesz õ utána?"));
husuperobject.biblemap.put("b21_4_1", new husuperobject(21,4,1,"Viszont látám én mind a nyomorgatásokat, a melyek a nap alatt történnek, és ímé, [nyilván van] azoknak, a kik nyomorgattatnak, könnyhullatások, és vígasztalójok nincs nékik; és az õket nyomorgatóknak kezekbõl erõszaktételt [szenvednek], és vígasztalójuk nincs nékik."));
husuperobject.biblemap.put("b21_4_2", new husuperobject(21,4,2,"És dicsérém én a megholtakat, a kik már meghaltak vala, az élõk felett, a kik még élnek;"));
husuperobject.biblemap.put("b21_4_3", new husuperobject(21,4,3,"De mind a kettõnél boldogabbnak azt, a ki még nem lett, a ki nem látta azt a gonosz dolgot, a mely a nap alatt történik."));
husuperobject.biblemap.put("b21_4_4", new husuperobject(21,4,4,"És látám én, hogy minden dolgát és minden ügyes cselekedetét az ember az õ felebarátja iránt való irígységbõl [rendeli;] annakokáért ez is hiábavalóság és lélek-fájdalom!"));
husuperobject.biblemap.put("b21_4_5", new husuperobject(21,4,5,"A bolond egybekapcsolja a kezeit, és megemészti a maga testét."));
husuperobject.biblemap.put("b21_4_6", new husuperobject(21,4,6,"Jobb egy teljes marok nyugalommal, mint mind a két maroknak teljessége nagy munkával és lelki gyötrelemmel."));
husuperobject.biblemap.put("b21_4_7", new husuperobject(21,4,7,"Viszont láték a nap alatt [más] hiábavalóságot."));
husuperobject.biblemap.put("b21_4_8", new husuperobject(21,4,8,"Van [oly ember], a ki egymaga van és nincs [vele] másik, sem fia, sem atyjafia nincs; mindazáltal nincs vége minden õ fáradságának, és az õ szeme is meg nem elégszik gazdagsággal, [hogy azt mondaná:] vajjon kinek munkálkodom, hogy az én lelkemet [minden] jótól megfosztom? Ez is hiábavalóság és gonosz foglalatosság!"));
husuperobject.biblemap.put("b21_4_9", new husuperobject(21,4,9,"Sokkal jobban van dolga a kettõnek, hogynem az egynek; mert azoknak jó jutalmok vala az õ munkájokból."));
husuperobject.biblemap.put("b21_4_10", new husuperobject(21,4,10,"Mert ha elesnek is, az egyik felemeli a társát. Jaj pedig az egyedülvalónak, ha elesik, és nincsen, a ki õt felemelje."));
husuperobject.biblemap.put("b21_4_11", new husuperobject(21,4,11,"Hogyha együtt feküsznek is ketten, megmelegszenek; az egyedülvaló pedig mimódon melegedhetik meg?"));
husuperobject.biblemap.put("b21_4_12", new husuperobject(21,4,12,"Ha az egyiket megtámadja is valaki, ketten ellene állhatnak annak; és a hármas kötél nem hamar szakad el."));
husuperobject.biblemap.put("b21_4_13", new husuperobject(21,4,13,"Jobb a szûkölködõ, de bölcs gyermek a vén és bolond királynál, a ki nem szenvedi el az intést többé."));
husuperobject.biblemap.put("b21_4_14", new husuperobject(21,4,14,"Mert [az] a fogságból [is] uralkodásra megy, holott [ennek] országában szegénységben született."));
husuperobject.biblemap.put("b21_4_15", new husuperobject(21,4,15,"Láttam a nap alatt járó minden élõket a második gyermek mellett; a ki amannak helyére lépendõ vala."));
husuperobject.biblemap.put("b21_4_16", new husuperobject(21,4,16,"[És hogy] az egész sokaságnak nincs vége, mindazoknak, a kiknek õ élén volt; mindazáltal az utánok valók már semmit nem örvendeztek õ benne. Mert ez is hiábavalóság és lelki gyötrelem!"));
husuperobject.biblemap.put("b21_5_1", new husuperobject(21,5,1,"Õrizd meg lábaidat, mikor az Istennek házához mégy, mert hallgatás végett közeledned jobb, hogynem a bolondok módja szerint áldozatot adni; mert ezek nem tudják, hogy gonoszt cselekesznek."));
husuperobject.biblemap.put("b21_5_2", new husuperobject(21,5,2,"Ne gyorsalkodjál a te száddal, és a te elméd ne siessen valamit szólni Isten elõtt; mert az Isten mennyben van, te pedig e földön, azért a te beszéded kevés legyen;"));
husuperobject.biblemap.put("b21_5_3", new husuperobject(21,5,3,"Mert álom szokott következni a sok foglalatosságból; és a sok beszédbõl bolond beszéd."));
husuperobject.biblemap.put("b21_5_4", new husuperobject(21,5,4,"Mikor Istennek fogadást téssz, ne halogasd annak megadását; mert nem gyönyörködik a bolondokban. A mit fogadsz, megteljesítsd!"));
husuperobject.biblemap.put("b21_5_5", new husuperobject(21,5,5,"Jobb hogy ne fogadj, hogynem mint fogadj és ne teljesítsd be."));
husuperobject.biblemap.put("b21_5_6", new husuperobject(21,5,6,"Ne engedd a te szádnak, hogy bûnre kötelezze testedet, és ne mondd az angyal elõtt, hogy tévedésbõl [esett] ez; hogy az Isten a te beszéded miatt fel ne háborodjék, és el ne veszesse a te kezeidnek munkáját."));
husuperobject.biblemap.put("b21_5_7", new husuperobject(21,5,7,"Mert a sok álomban a hiábavalóság is és a beszéd is sok; hanem az Istent féljed."));
husuperobject.biblemap.put("b21_5_8", new husuperobject(21,5,8,"Ha a szegényeknek nyomoríttatását, és a törvénynek és igazságnak elfordíttatását látod a tartományban: ne csudálkozzál e dolgon; mert [egyik] felsõrendû vigyáz a [másik] felsõrendûre, és ezek felett [még] felsõbbrendûek [vannak.]"));
husuperobject.biblemap.put("b21_5_9", new husuperobject(21,5,9,"Az ország haszna pedig mindenekfelett a földmívelést [kedvelõ ]király."));
husuperobject.biblemap.put("b21_5_10", new husuperobject(21,5,10,"A ki szereti a pénzt, nem telik be pénzzel, és a ki szereti a sokaságot [nem telik be] jövedelemmel. Ez is hiábavalóság."));
husuperobject.biblemap.put("b21_5_11", new husuperobject(21,5,11,"Mikor megszaporodik a jószág, megszaporodnak annak megemésztõi is; mi haszna van azért benne urának, hanem hogy csak reá néz szemeivel?"));
husuperobject.biblemap.put("b21_5_12", new husuperobject(21,5,12,"Édes az álom a munkásnak, akár sokat, akár keveset egyék; a gazdagnak pedig bõvölködése nem hagyja õt aludni."));
husuperobject.biblemap.put("b21_5_13", new husuperobject(21,5,13,"Van gonosz nyavalya, a melyet láttam a nap alatt: az õ urának veszedelmére tartott gazdagság;"));
husuperobject.biblemap.put("b21_5_14", new husuperobject(21,5,14,"Ugyanis az a gazdagság elvész valami szerencsétlen eset miatt, és ha fia született néki, annak kezében nem lesz semmi."));
husuperobject.biblemap.put("b21_5_15", new husuperobject(21,5,15,"A mint kijött az õ anyjának méhébõl, mezítelen megy ismét el, a mint jött vala: és semmit nem vesz el munkájáért, a mit kezében elvinne."));
husuperobject.biblemap.put("b21_5_16", new husuperobject(21,5,16,"Annakokáért ez is gonosz nyavalya, hogy a mint jött, a képen megy el. Mi haszna van néki abban, hogy a szélnek munkálkodott?"));
husuperobject.biblemap.put("b21_5_17", new husuperobject(21,5,17,"És hogy az õ teljes életében a setétben evett, sokszori haraggal, keserûséggel és búsulással?"));
husuperobject.biblemap.put("b21_5_18", new husuperobject(21,5,18,"Ez azért a jó, a melyet én láttam, hogy szép dolog enni és inni, és jól élni minden õ munkájából, a melylyel fárasztotta magát a nap alatt, az õ élete napjainak száma szerint, a melyeket adott néki az Isten; mert ez az õ része."));
husuperobject.biblemap.put("b21_5_19", new husuperobject(21,5,19,"És a mely embernek adott Isten gazdagságot és kincseket, és a kinek megengedte, hogy egyék abból és az õ részét elvegye, és örvendezzen az õ munkájának: ez az Istennek ajándéka!"));
husuperobject.biblemap.put("b21_5_20", new husuperobject(21,5,20,"Mert nem sokat emlékezik meg [az ilyen] az õ élete napjainak [számáról,] mivelhogy az õ szívének örömét az Isten kedveli."));
husuperobject.biblemap.put("b21_6_1", new husuperobject(21,6,1,"Van egy gonosz, a melyet láttam a nap alatt, és nagy [baj] az az emberen;"));
husuperobject.biblemap.put("b21_6_2", new husuperobject(21,6,2,"Mikor valakinek az Isten ád gazdagságot és kincseket és tisztességet, és semmi nélkül nem szûkölködik, valamit kivánhat lelkének, és az Isten nem engedi néki, hogy éljen azzal, hanem más ember él azzal: ez hiábavalóság és gonosz nyavalya!"));
husuperobject.biblemap.put("b21_6_3", new husuperobject(21,6,3,"Ha száz gyermeket szül is valaki, és sok esztendeig él, úgy hogy az õ esztendeinek napja sok, de az õ lelke a jóval meg nem elégszik, és nem lesz temetése néki: azt mondom, hogy jobb annál az idétlen gyermek,"));
husuperobject.biblemap.put("b21_6_4", new husuperobject(21,6,4,"Mert hiábavalóságra jött, setétségben megy el, és setétséggel fedeztetik be neve,"));
husuperobject.biblemap.put("b21_6_5", new husuperobject(21,6,5,"A napot sem látta és nem ismerte; tûrhetõbb ennek állapotja, hogynem amannak."));
husuperobject.biblemap.put("b21_6_6", new husuperobject(21,6,6,"Hogyha kétezer esztendõt élt volna is, és a jóval nem élt: avagy nem ugyanazon egy helyre megy-é minden?"));
husuperobject.biblemap.put("b21_6_7", new husuperobject(21,6,7,"Az embernek minden munkája szájáért van; mindazáltal az õ kívánsága be nem telik."));
husuperobject.biblemap.put("b21_6_8", new husuperobject(21,6,8,"Mert miben különbözik a bölcs a bolondtól, és miben a szegény, a ki az élõk elõtt járni tud?"));
husuperobject.biblemap.put("b21_6_9", new husuperobject(21,6,9,"Jobb, a mit ember szemmel lát, hogynem a lélek kivánsága; ez is hiábavalóság és a léleknek gyötrelme!"));
husuperobject.biblemap.put("b21_6_10", new husuperobject(21,6,10,"Valami van, régen ráadatott nevezete, és bizonyos dolog, hogy mi lesz az ember, és nem perlekedhetik azzal, a ki hatalmasb nálánál."));
husuperobject.biblemap.put("b21_6_11", new husuperobject(21,6,11,"Mert van sok beszéd, a mely a hiábavalóságot szaporítja; és mi haszna van az embernek [abban?]"));
husuperobject.biblemap.put("b21_6_12", new husuperobject(21,6,12,"Mert kicsoda tudhatja, mi legyen az embernek jó e világon, az õ hiábavaló élete napjainak száma szerint, a melyeket mintegy árnyékot tölt el? Kicsoda az, a ki megmondhatná az embernek, mi következik õ utána a nap alatt?"));
husuperobject.biblemap.put("b21_7_1", new husuperobject(21,7,1,"Jobb a jó hír a drága kenetnél; és a halálnak napja jobb az õ születésének napjánál."));
husuperobject.biblemap.put("b21_7_2", new husuperobject(21,7,2,"Jobb a siralmas házhoz menni, hogynem a lakodalomnak házához menni; mivelhogy minden embernek ez a vége, és az élõ ember megemlékezik arról."));
husuperobject.biblemap.put("b21_7_3", new husuperobject(21,7,3,"Jobb a szomorúság a nevetésnél; mert az orczának szomorúsága által jobbá lesz a szív."));
husuperobject.biblemap.put("b21_7_4", new husuperobject(21,7,4,"A bölcseknek elméje a siralmas házban [van], a bolondoknak pedig elméje a vígasságnak házában."));
husuperobject.biblemap.put("b21_7_5", new husuperobject(21,7,5,"Jobb a bölcsnek dorgálását hallani, hogynem valaki hallja a bolondoknak éneklését."));
husuperobject.biblemap.put("b21_7_6", new husuperobject(21,7,6,"Mert olyan a bolondnak nevetése, mint a tövisnek ropogása a fazék alatt; ez is hiábavalóság!"));
husuperobject.biblemap.put("b21_7_7", new husuperobject(21,7,7,"Mert a zsarolás megbolondítja a bölcs [embert] is, és az elmét elveszti az ajándék."));
husuperobject.biblemap.put("b21_7_8", new husuperobject(21,7,8,"Jobb akármi dolognak vége annak kezdetinél; jobb a tûrõ, hogynem a kevély."));
husuperobject.biblemap.put("b21_7_9", new husuperobject(21,7,9,"Ne légy hirtelen a lelkedben a haragra; mert a harag a bolondok kebelében nyugszik."));
husuperobject.biblemap.put("b21_7_10", new husuperobject(21,7,10,"Ne mondd ezt: mi az oka, hogy a régi napok jobbak voltak ezeknél? mert nem bölcseségbõl származik az ilyen kérdés."));
husuperobject.biblemap.put("b21_7_11", new husuperobject(21,7,11,"Jó a bölcseség az örökséggel, és elõmenetelökre van az [embereknek], a kik a napot látják."));
husuperobject.biblemap.put("b21_7_12", new husuperobject(21,7,12,"Mert a bölcseségnek árnyéka alatt, [és] a gazdagságnak árnyéka alatt [egyformán nyugszik az ember!] de a tudomány hasznosb, mivelhogy a bölcseség életet ád az õ urainak."));
husuperobject.biblemap.put("b21_7_13", new husuperobject(21,7,13,"Tekintsd meg az Istennek cselekedetit; mert kicsoda teheti egyenessé, a mit õ görbévé tett?"));
husuperobject.biblemap.put("b21_7_14", new husuperobject(21,7,14,"A jó szerencsének idején élj a jóval; a gonosz szerencsének idején pedig jusson eszedbe, hogy ezt is, épen úgy, mint azt, Isten szerzette, a végre, hogy az ember semmit [abból] eszébe ne vegyen, [a mi] reá következik."));
husuperobject.biblemap.put("b21_7_15", new husuperobject(21,7,15,"Mindent láttam az én hiábavalóságomnak napjain: van oly igaz, a ki az õ igazságában elvész; és van gonosz ember, a ki [az õ életének napjait] meghosszabbítja az õ gonoszságában."));
husuperobject.biblemap.put("b21_7_16", new husuperobject(21,7,16,"Ne légy felettébb igaz, és felettébb ne bölcselkedjél; miért keresnél magadnak veszedelmet?"));
husuperobject.biblemap.put("b21_7_17", new husuperobject(21,7,17,"Ne légy felettébb gonosz, és ne légy balgatag; miért halnál meg idõd elõtt?"));
husuperobject.biblemap.put("b21_7_18", new husuperobject(21,7,18,"Jobb, hogy ezt megfogd, és amattól is a te kezedet meg ne vond; mert a ki az Istent féli, mind ezektõl megszabadul!"));
husuperobject.biblemap.put("b21_7_19", new husuperobject(21,7,19,"A bölcseség megerõsíti a bölcset inkább, mint tíz hatalmas, a kik a városban vannak."));
husuperobject.biblemap.put("b21_7_20", new husuperobject(21,7,20,"Mert nincs egy igaz ember is a földön, a ki jót cselekednék és nem vétkeznék."));
husuperobject.biblemap.put("b21_7_21", new husuperobject(21,7,21,"Ne figyelmezz minden beszédre, melyet mondanak, hogy meg ne halld szolgádat, hogy átkoz téged."));
husuperobject.biblemap.put("b21_7_22", new husuperobject(21,7,22,"Mert sok esetben tudja a te lelked is, hogy te is gonoszt mondottál egyebeknek."));
husuperobject.biblemap.put("b21_7_23", new husuperobject(21,7,23,"Mind ezeket megpróbáltam az én bölcseségem által. [Mikor] azt gondolám, [hogy] bölcs vagyok, én tõlem a [bölcseség] távol vala."));
husuperobject.biblemap.put("b21_7_24", new husuperobject(21,7,24,"Felette igen messze van, a mi van, és felette mélységes; kicsoda tudhatja meg azt?"));
husuperobject.biblemap.put("b21_7_25", new husuperobject(21,7,25,"Fordítám én magamat és az én szívemet a bölcseségnek és az okoskodásnak tudására, kutatására és keresésére; azonképen hogy megtudjam a bolondságnak gonoszságát, és a tévelygésnek balgatagságát."));
husuperobject.biblemap.put("b21_7_26", new husuperobject(21,7,26,"És találtam [egy dolgot,] mely keservesb a halálnál; tudniillik az olyan asszonyt, a kinek a szíve olyan, mint a tõr és a háló, kezei pedig olyanok, mint a kötelek. A ki Isten elõtt kedves, megszabadul attól; a bûnös pedig megfogattatik attól."));
husuperobject.biblemap.put("b21_7_27", new husuperobject(21,7,27,"Lásd, ezt találtam, azt mondja a prédikátor; mikor gyakorta nagy szorgalmassággal keresém a megfejtést,"));
husuperobject.biblemap.put("b21_7_28", new husuperobject(21,7,28,"A mit az én lelkem folyton keresett, és nem találtam. Ezer közül egy embert találtam; de asszonyt mind ezekben nem találtam."));
husuperobject.biblemap.put("b21_7_29", new husuperobject(21,7,29,"Hanem lásd, ezt találtam, hogy az Isten teremtette az embert igaznak; õk pedig kerestek sok kigondolást."));
husuperobject.biblemap.put("b21_8_1", new husuperobject(21,8,1,"Kicsoda hasonló a bölcshöz, és ki tudja a dolgok magyarázatát? Az embernek bölcsesége megvilágosítja az õ orczáját; és az õ ábrázatjának erõssége megváltozik."));
husuperobject.biblemap.put("b21_8_2", new husuperobject(21,8,2,"Én [mondom,] hogy a királynak parancsolatját meg kell õrizni, és pedig az Istenre való esküvés miatt."));
husuperobject.biblemap.put("b21_8_3", new husuperobject(21,8,3,"Ne siess elmenni az õ orczája elõl, ne állj rá a gonosz dologra; mert valamit akar, megcselekszi."));
husuperobject.biblemap.put("b21_8_4", new husuperobject(21,8,4,"Mivelhogy a király szava hatalmas; és kicsoda merné néki ezt mondani: mit mívelsz?"));
husuperobject.biblemap.put("b21_8_5", new husuperobject(21,8,5,"A ki megtartja a parancsolatot, nem ismer nyomorúságot, és a bölcsnek elméje megért mind idõt, mind ítéletet;"));
husuperobject.biblemap.put("b21_8_6", new husuperobject(21,8,6,"Mert minden akaratnak van ideje és ítélete; mert az embernek nyomorúsága sok õ rajta;"));
husuperobject.biblemap.put("b21_8_7", new husuperobject(21,8,7,"Mert nem tudja azt, a mi következik; mert ki mondja meg néki, mimódon lesz az?"));
husuperobject.biblemap.put("b21_8_8", new husuperobject(21,8,8,"Egy ember sem uralkodhatik a szélen, hogy feltartsa a szelet; és semmi hatalmasság nincs a halálnak napja felett, és az ütközetben senkit el nem bocsátanak; és a gonoszság nem szabadítja meg azt, a ki azzal él."));
husuperobject.biblemap.put("b21_8_9", new husuperobject(21,8,9,"Mindezt láttam, és megfigyeltem minden dolgot, a mely történik a nap alatt, oly idõben, a melyben uralkodik az ember az emberen maga kárára."));
husuperobject.biblemap.put("b21_8_10", new husuperobject(21,8,10,"És azután láttam, hogy a gonoszok eltemettettek és [nyugalomra ]mentek; viszont a szent helyrõl kimentek, és elfelejttettek a városban [olyanok,] a kik becsületesen cselekedtek. Ez is hiábavalóság!"));
husuperobject.biblemap.put("b21_8_11", new husuperobject(21,8,11,"Mivelhogy hamar a szentenczia nem végeztetik el a gonoszságnak cselekedõjén, egészen arra van az emberek fiainak szíve õ bennök, hogy gonoszt cselekedjenek."));
husuperobject.biblemap.put("b21_8_12", new husuperobject(21,8,12,"Bár meghosszabbítja [életét] a bûnös, a ki százszor is vétkezik; mégis tudom én, hogy az istenfélõknek lészen jól dolgok, a kik az õ orczáját félik;"));
husuperobject.biblemap.put("b21_8_13", new husuperobject(21,8,13,"A hitetlennek pedig nem lesz jó dolga, és nem hosszabbítja meg az õ életét, [olyan lesz], mint az árnyék, mert nem rettegi az Istennek orczáját."));
husuperobject.biblemap.put("b21_8_14", new husuperobject(21,8,14,"Van hiábavalóság, a mely e földön történik; az, hogy vannak oly igazak, a kiknek dolga a gonoszoknak cselekedetei szerint lesz; és vannak gonoszok, a kiknek dolga az igazaknak cselekedetei szerint lesz; mondám, hogy ez is hiábavalóság."));
husuperobject.biblemap.put("b21_8_15", new husuperobject(21,8,15,"Annakokáért dicsérem vala én a vígasságot, hogy nincsen embernek jobb e világon, hanem hogy egyék, igyék és vígadjon; és ez kisérje õt munkájában az õ életének napjaiban, a melyeket ád néki Isten a nap alatt."));
husuperobject.biblemap.put("b21_9_1", new husuperobject(21,9,1,"Mikor adám az én szívemet a bölcseségnek megtudására, és hogy megvizsgáljak [minden] fáradságot, a mely e földön történik, (mert sem éjjel, sem nappal [az emberek] szeme álmot nem lát):"));
husuperobject.biblemap.put("b21_9_2", new husuperobject(21,9,2,"Akkor eszembe vevém az Istennek minden dolgát, hogy az ember nem mehet végére a dolognak, a mely a nap alatt történik; mert fáradozik az ember, hogy annak végére menjen, de nem mehet végére: sõt ha azt mondja is a bölcs ember, hogy tudja, nem mehet végére."));
husuperobject.biblemap.put("b21_9_3", new husuperobject(21,9,3,"Mert mindezt szívemre vettem, és pedig azért, hogy megvizsgáljam mindezt: hogy az igazak és bölcsek és azoknak minden cselekedetei Isten kezében vannak; szeretet is, gyûlölet is, nem tudják az emberek, mind ez elõttük van."));
husuperobject.biblemap.put("b21_9_4", new husuperobject(21,9,4,"Minden olyan, hogy mindenkit [érhet], egyazon szerencséje van az igaznak és gonosznak, jónak vagy tisztának és tisztátalannak, mind annak, a ki áldozik, mind a ki nem áldozik, úgy a jónak, mint a bûnösnek, az esküvõnek úgy, mint a ki féli az esküvést."));
husuperobject.biblemap.put("b21_9_5", new husuperobject(21,9,5,"Mind az ég alatt való dolgokban e gonosz van, hogy mindeneknek egyenlõ szerencséjök van; és az emberek fiainak szíve is teljes gonoszsággal, és elméjökben minden bolondság van, a míg élnek, azután pedig a halottak közé [mennek.]"));
husuperobject.biblemap.put("b21_9_6", new husuperobject(21,9,6,"Mert akárkinek, valaki minden élõk közé csatlakozik, van reménysége; mert jobb az élõ eb, hogynem a megholt oroszlán."));
husuperobject.biblemap.put("b21_9_7", new husuperobject(21,9,7,"Mert az élõk tudják, hogy meghalnak; de a halottak semmit nem tudnak, és azoknak semmi jutalmok nincs többé; mivelhogy emlékezetök elfelejtetett."));
husuperobject.biblemap.put("b21_9_8", new husuperobject(21,9,8,"Mind szeretetök, mind gyûlöletök, mind gerjedezésök immár elveszett; és többé semmi részök nincs semmi dologban, a mely a nap alatt történik."));
husuperobject.biblemap.put("b21_9_9", new husuperobject(21,9,9,"No azért egyed vígassággal a te kenyeredet, és igyad jó szívvel a te borodat; mert immár kedvesek Istennek a te cselekedetid!"));
husuperobject.biblemap.put("b21_9_10", new husuperobject(21,9,10,"A te ruháid mindenkor legyenek fejérek, és az olaj a te fejedrõl el ne fogyatkozzék."));
husuperobject.biblemap.put("b21_9_11", new husuperobject(21,9,11,"Éld életedet a te feleségeddel, a kit szeretsz, a te hiábavaló életednek minden napjaiban, a melyeket [Isten] adott néked a nap alatt, a te hiábavalóságodnak minden napjaiban; mert ez a te részed a te életedben és a te munkádban, melylyel munkálódol a nap alatt."));
husuperobject.biblemap.put("b21_9_12", new husuperobject(21,9,12,"Valamit hatalmadban van cselekedni erõd szerint, azt cselekedjed; mert semmi cselekedet, okoskodás, tudomány és bölcseség nincs a Seolban, a hová menendõ vagy."));
husuperobject.biblemap.put("b21_9_13", new husuperobject(21,9,13,"Fordítván magamat látám a nap alatt, hogy nem a gyorsaké a futás, és nem az erõseké a viadal, és nem a bölcseké a kenyér, és nem az okosoké a gazdagság, és nem a tudósoké a kedvesség; hanem idõ szerint és történetbõl lesznek mindezek."));
husuperobject.biblemap.put("b21_9_14", new husuperobject(21,9,14,"Mert nem is tudja az ember az õ idejét; mint a halak, melyek megfogatnak a gonosz hálóban, és mint a madarak, melyek megfogatnak a tõrben, miképen ezek, azonképen megfogatnak az emberek fiai a gonosznak idején, mikor az eljõ reájok hirtelenséggel."));
husuperobject.biblemap.put("b21_9_15", new husuperobject(21,9,15,"Ezt is bölcseségnek láttam a nap alatt, és ez én elõttem nagy volt."));
husuperobject.biblemap.put("b21_9_16", new husuperobject(21,9,16,"[Tudniillik, hogy egy] kicsiny város [volt,] és abban kevés ember [volt,] és eljött az ellen hatalmas király, és azt körülvette, és az ellen nagy erõsségeket épített."));
husuperobject.biblemap.put("b21_9_17", new husuperobject(21,9,17,"És találtatott abban [egy] szegény ember, a ki bölcs volt, és az õ bölcseségével a várost megszabadította; de senki meg nem emlékezett arról a szegény emberrõl."));
husuperobject.biblemap.put("b21_9_18", new husuperobject(21,9,18,"Akkor én azt mondám: jobb a bölcseség az erõsségnél; de a szegénynek bölcsesége útálatos, és az õ beszédit nem hallgatják meg. [ (Ecclesiastes 9:19) A bölcseknek nyugodt beszédét inkább meghallgatják, mint a bolondok közt uralkodónak kiáltását. ] [ (Ecclesiastes 9:20) Jobb a bölcsesség a hadakozó szerszámoknál; és egy bûnös sok jót veszt el. ] [ (Ecclesiastes 9:21) A megholt legyek a patikáriusnak kenetit megbüdösítik, megerjesztik; [azonképen] hathatósabb a bölcseségnél, tisztességnél egy kicsiny balgatagság. ] [ (Ecclesiastes 9:22) A bölcs embernek szíve az õ jobbkezénél [van;] a bolondnak pedig szíve balkezénél. ] [ (Ecclesiastes 9:23) A bolond, mikor az úton jár is, az õ elméje hiányos, és mindennek hirdeti, hogy õ bolond. ]"));
husuperobject.biblemap.put("b21_10_1", new husuperobject(21,10,1,"Mikor a fejedelemnek haragja felgerjed te ellened, a te helyedet el ne hagyjad; mert a szelídség nagy bûnöket lecsendesít."));
husuperobject.biblemap.put("b21_10_2", new husuperobject(21,10,2,"Van egy gonosz, a melyet láttam a nap alatt, mintha tévedés volna, a mely a fejedelemtõl származik."));
husuperobject.biblemap.put("b21_10_3", new husuperobject(21,10,3,"[Hogy] a bolondság nagy méltóságra helyeztetett, a gazdagok pedig alacsony [sors]ban ülnek."));
husuperobject.biblemap.put("b21_10_4", new husuperobject(21,10,4,"Láttam, hogy a szolgák lovakon [ültek;] a fejedelmek pedig gyalog mentek a földön, mint a szolgák."));
husuperobject.biblemap.put("b21_10_5", new husuperobject(21,10,5,"A ki vermet ás, abba beesik; és a ki a gyepût elhányja, megmarja azt a kígyó."));
husuperobject.biblemap.put("b21_10_6", new husuperobject(21,10,6,"A ki a köveket helyökbõl kihányja, fájdalmat szenved azok miatt; a ki hasogatja a fát, veszedelemben forog a miatt."));
husuperobject.biblemap.put("b21_10_7", new husuperobject(21,10,7,"Ha a vas megtompul, és annak élit meg nem köszörüli az ember, akkor erejét kell megfeszíteni; a bölcseség pedig [minden dolognak] eligazítására nagy elõmenetel."));
husuperobject.biblemap.put("b21_10_8", new husuperobject(21,10,8,"Ha megharap a kígyó, a míg meg nem varázsoltatott, azután semmi haszna nincsen a varázslónak."));
husuperobject.biblemap.put("b21_10_9", new husuperobject(21,10,9,"A bölcs ember szájának beszédei kedvesek; a bolondnak pedig ajkai elnyelik õt."));
husuperobject.biblemap.put("b21_10_10", new husuperobject(21,10,10,"Az õ szája beszédinek kezdete bolondság, és az õ szája [beszédinek] vége gonosz balgatagság."));
husuperobject.biblemap.put("b21_10_11", new husuperobject(21,10,11,"És a bolond szaporítja a szót, [pedig] nem tudja az ember, a mi következik, és a mi utána lesz, kicsoda mondja meg azt néki?"));
husuperobject.biblemap.put("b21_10_12", new husuperobject(21,10,12,"A bolondnak munkája elfárasztja õt, mert a városba sem tud menni."));
husuperobject.biblemap.put("b21_10_13", new husuperobject(21,10,13,"Jaj néked ország, kinek a te királyod gyermek; és a te fejedelmid reggel esznek."));
husuperobject.biblemap.put("b21_10_14", new husuperobject(21,10,14,"Boldog vagy te ország, kinek a te királyod nemes ember, és a te fejedelmid idejében esznek a [testnek] erejéért és nem az italért."));
husuperobject.biblemap.put("b21_10_15", new husuperobject(21,10,15,"A restség miatt elhanyatlik a házfedél, és a kezek restsége miatt csepeg a ház."));
husuperobject.biblemap.put("b21_10_16", new husuperobject(21,10,16,"Vígasságnak okáért szereznek lakodalmat, és a bor vídámítja meg az élõket: és a pénz szerzi meg mindezeket."));
husuperobject.biblemap.put("b21_10_17", new husuperobject(21,10,17,"Még a te gondolatodban is a királyt ne átkozd, és a te ágyasházadban is gonoszt a gazdagnak ne mondj: mert az égi madár is elviszi a szót, és a szárnyas állat is bevádolná a te beszédedet."));
husuperobject.biblemap.put("b21_11_1", new husuperobject(21,11,1,"Vesd a te kenyeredet a víz színére, mert sok nap mulva megtalálod azt."));
husuperobject.biblemap.put("b21_11_2", new husuperobject(21,11,2,"Adj részt hétnek vagy nyolcznak is; mert nem tudod, micsoda veszedelem következik a földre."));
husuperobject.biblemap.put("b21_11_3", new husuperobject(21,11,3,"Mikor a sûrû fellegek megtelnek, esõt adnak a földre; és ha leesik a fa délre vagy északra, a mely helyre leesik a fa, ott marad."));
husuperobject.biblemap.put("b21_11_4", new husuperobject(21,11,4,"A ki a szelet nézi, nem vet az; és a ki sûrû fellegre néz, nem arat."));
husuperobject.biblemap.put("b21_11_5", new husuperobject(21,11,5,"Miképen hogy nem tudod, melyik a szélnek útja, és miképen vannak a csontok a terhes asszony méhében; azonképen nem tudod az Istennek dolgát, a ki mindeneket cselekszik."));
husuperobject.biblemap.put("b21_11_6", new husuperobject(21,11,6,"Reggel vesd el a te magodat, és este se pihentesd kezedet; mert nem tudod, melyik jobb, ez-é vagy amaz, vagy ha mind a kettõ jó lesz egyszersmind."));
husuperobject.biblemap.put("b21_11_7", new husuperobject(21,11,7,"Valóban, édes a világosság és jó a mi szemeinkkel néznünk a napot."));
husuperobject.biblemap.put("b21_11_8", new husuperobject(21,11,8,"Mert ha sok esztendeig él is az ember, mindazokban örvendezzen; és megemlékezzék a setétségnek napjairól, mert az sok lesz. Valami eljövendõ, mind hiábavalóság."));
husuperobject.biblemap.put("b21_12_1", new husuperobject(21,12,1,"Örvendezz a te ifjuságodban, és vídámítson meg téged a te szíved a te ifjúságodnak idejében, és járj a te szívednek útaiban, és szemeidnek látásiban; de megtudd, hogy mindezekért az Isten tégedet ítéletre von!"));
husuperobject.biblemap.put("b21_12_2", new husuperobject(21,12,2,"Vesd el a haragot a te szívedbõl, és vesd el a gonoszt a te testedbõl; mert az ifjúság és a hajnal hiábavalóság."));
husuperobject.biblemap.put("b21_12_3", new husuperobject(21,12,3,"És emlékezzél meg a te Teremtõdrõl a te ifjúságodnak idejében, míg a veszedelemnek napjai el nem jõnek, és míg el nem jõnek az esztendõk, melyekrõl azt mondod: nem szeretem ezeket!"));
husuperobject.biblemap.put("b21_12_4", new husuperobject(21,12,4,"A míg a nap meg nem setétedik, a világossággal, a holddal és csillagokkal egybe; és a sûrû felhõk ismét visszatérnek az esõ után."));
husuperobject.biblemap.put("b21_12_5", new husuperobject(21,12,5,"Az idõben, mikor megremegnek a háznak õrizõi, és megrogynak az erõs férfiak, és megállanak az õrlõ leányok, mert megkevesbedtek, és meghomályosodnak az ablakon kinézõk."));
husuperobject.biblemap.put("b21_12_6", new husuperobject(21,12,6,"És az ajtók kivül bezáratnak, a mikor is a malom zúgása halkabbá lesz; és felkelnek a madár szóra, és halkabbakká lesznek minden éneklõ leányok."));
husuperobject.biblemap.put("b21_12_7", new husuperobject(21,12,7,"Minden halmocskától is félnek, és [mindenféle] ijedelmek vannak az úton, és a mandolafa megvirágzik, és a sáska [nehezen ]vonszolja magát, és kipattan a kapor; mert elmegy az ember az õ örökös házába, és az utczán körül járnak a sírók."));
husuperobject.biblemap.put("b21_12_8", new husuperobject(21,12,8,"Minekelõtte elszakadna az ezüst kötél és megromolna az arany palaczkocska, és a veder eltörnék a forrásnál, és beletörnék a kerék a kútba,"));
husuperobject.biblemap.put("b21_12_9", new husuperobject(21,12,9,"És a por földdé lenne, mint azelõtt volt; a lélek pedig megtérne Istenhez, a ki adta volt azt."));
husuperobject.biblemap.put("b21_12_10", new husuperobject(21,12,10,"Felette nagy hiábavalóságok, azt mondja a prédikátor, mindezek hiábavalóságok!"));
husuperobject.biblemap.put("b21_12_11", new husuperobject(21,12,11,"És azonfelül, hogy a prédikátor bölcs volt, még a népet is tudományra tanította, és fontolgatott, és tudakozott, és írt sok bölcs mondást."));
husuperobject.biblemap.put("b21_12_12", new husuperobject(21,12,12,"És igyekezett a prédikátor megtudni sok kivánságos beszédeket, igaz írást és igaz beszédeket."));
husuperobject.biblemap.put("b21_12_13", new husuperobject(21,12,13,"A bölcseknek beszédei hasonlatosak az ösztökéhez, és mint a szegek, erõsen le vannak verve a gyülekezetek tanítóinak [szavai;] melyek egy pásztortól adattak."));
husuperobject.biblemap.put("b21_12_14", new husuperobject(21,12,14,"Mindezekbõl, fiam, intessél meg: a sok könyvek írásának nincs vége, és a sok tanulás fáradságára van a testnek. [ (Ecclesiastes 12:15) A dolognak summája, mindezeket hallván, [ez:] az Istent féljed, és az õ parancsolatit megtartsad; mert ez az embernek fõdolga! ] [ (Ecclesiastes 12:16) Mert minden cselekedetet az Isten ítéletre elõhoz, minden titkos dologgal, akár jó, akár gonosz [legyen az.] ]"));

}

}