package hu.bible;

public class hubible58 {

public hubible58() {

putmapbible58();

}

private void putmapbible58() {

husuperobject.biblemap.put("b58_1_1", new husuperobject(58,1,1,"Minekutána az Isten sok rendben és sokféleképen szólott hajdan az atyáknak a próféták által, ez utolsó idõkben szólott nékünk Fia által,"));
husuperobject.biblemap.put("b58_1_2", new husuperobject(58,1,2,"A kit tett mindennek örökösévé, a ki által a világot is teremtette,"));
husuperobject.biblemap.put("b58_1_3", new husuperobject(58,1,3,"A ki az õ dicsõségének visszatükrözõdése, és az õ valóságának képmása, a ki hatalma szavával fentartja a mindenséget, a ki minket bûneinktõl megtisztítván, üle a Felségnek jobbjára a magasságban,"));
husuperobject.biblemap.put("b58_1_4", new husuperobject(58,1,4,"Annyival kiválóbb lévén az angyaloknál, a mennyivel különb nevet örökölt azoknál."));
husuperobject.biblemap.put("b58_1_5", new husuperobject(58,1,5,"Mert kinek mondotta valaha az angyalok közül: Én Fiam vagy te, én ma szûltelek téged? és ismét: Én leszek néki Atyja és õ lesz nékem Fiam?"));
husuperobject.biblemap.put("b58_1_6", new husuperobject(58,1,6,"Viszont mikor behozza az õ elsõszülöttét a világba, így szól: És imádják õt az Istennek minden angyalai."));
husuperobject.biblemap.put("b58_1_7", new husuperobject(58,1,7,"És bár az angyalokról [így] szól: Ki az õ angyalait szelekké teszi és az õ szolgáit tûz lángjává,"));
husuperobject.biblemap.put("b58_1_8", new husuperobject(58,1,8,"Ámde a Fiúról [így]: A te királyi széked óh Isten örökkön örökké. Igazságnak pálczája a te országodnak pálczája."));
husuperobject.biblemap.put("b58_1_9", new husuperobject(58,1,9,"Szeretted az igazságot és gyûlölted a hamisságot: annakokáért felkent téged az Isten, a te Istened, örömnek olajával a te társaid felett."));
husuperobject.biblemap.put("b58_1_10", new husuperobject(58,1,10,"És: Te Uram kezdetben alapítottad a földet és a te kezeidnek mûvei az egek;"));
husuperobject.biblemap.put("b58_1_11", new husuperobject(58,1,11,"Azok elvesznek, de te megmaradsz, és mindazok, mint a ruha megavulnak."));
husuperobject.biblemap.put("b58_1_12", new husuperobject(58,1,12,"És palástként összehajtod azokat és elváltoznak, te pedig ugyanaz vagy és a te esztendeid el nem fogynak."));
husuperobject.biblemap.put("b58_1_13", new husuperobject(58,1,13,"Melyik angyalnak mondotta pedig valaha: Ülj az én jobbkezem felõl, míglen ellenségeidet lábaidnak zsámolyává teszem?"));
husuperobject.biblemap.put("b58_1_14", new husuperobject(58,1,14,"Avagy nem szolgáló lelkek-é mindazok, elküldve szolgálatra azokért, a kik örökölni fogják az idvességet?"));
husuperobject.biblemap.put("b58_2_1", new husuperobject(58,2,1,"Annakokáért annál is inkább szükséges nékünk a hallottakra figyelmeznünk, hogy valaha el ne sodortassunk."));
husuperobject.biblemap.put("b58_2_2", new husuperobject(58,2,2,"Mert ha az angyaloktól hirdetett beszéd erõs volt és minden bûn és engedetlenség elvette igazságos büntetését:"));
husuperobject.biblemap.put("b58_2_3", new husuperobject(58,2,3,"Mimódon menekedünk meg mi, hogyha nem törõdünk ily nagy idvességgel? a melyet, miután kezdetben hirdetett az Úr, azok, a kik hallották, biztosítottak számunkra,"));
husuperobject.biblemap.put("b58_2_4", new husuperobject(58,2,4,"Velök együtt bizonyságot tevén arról az Isten, jelekkel meg csodákkal és sokféle erõkkel s a Szent Léleknek közléseivel az õ akarata szerint."));
husuperobject.biblemap.put("b58_2_5", new husuperobject(58,2,5,"Mert nem angyaloknak vetette alá a jövendõ világot, a melyrõl szólunk."));
husuperobject.biblemap.put("b58_2_6", new husuperobject(58,2,6,"Sõt bizonyságot tett valahol valaki, mondván: Micsoda az ember, hogy megemlékezel õ róla, avagy az embernek fia, hogy gondod van reá?"));
husuperobject.biblemap.put("b58_2_7", new husuperobject(58,2,7,"Kisebbé tetted õt rövid idõre az angyaloknál, dicsõséggel és tisztességgel megkoronáztad õt és úrrá tetted kezeid munkáin,"));
husuperobject.biblemap.put("b58_2_8", new husuperobject(58,2,8,"Mindent lábai alá vetettél. Mert azzal, hogy néki mindent alávetett, semmit sem hagyott alávetetlenül: de most még nem látjuk, hogy néki minden alávettetett."));
husuperobject.biblemap.put("b58_2_9", new husuperobject(58,2,9,"Azt azonban látjuk, hogy Jézus, a ki egy kevés idõre kisebbé tétetett az angyaloknál, a halál elszenvedéséért dicsõséggel és tisztességgel koronáztatott meg, hogy az Isten kegyelmébõl mindenkiért megízlelje a halált."));
husuperobject.biblemap.put("b58_2_10", new husuperobject(58,2,10,"Mert illendõ vala, hogy a kiért minden és a ki által minden, sok fiakat vezérelvén dicsõségre, az õ idvességök fejedelmét szenvedések által tegye tökéletessé."));
husuperobject.biblemap.put("b58_2_11", new husuperobject(58,2,11,"Mert a megszentelõ és a megszenteltek egytõl valók mindnyájan, a mely oknál fogva nem szégyenli õket atyjafiainak hívni,"));
husuperobject.biblemap.put("b58_2_12", new husuperobject(58,2,12,"Mondván: Hirdetem a te nevedet az én atyámfiainak, az anyaszentegyháznak közepette dícséretet mondok néked."));
husuperobject.biblemap.put("b58_2_13", new husuperobject(58,2,13,"És ismét: Én õ benne bízom; és ismét: Ímhol vagyok én és a gyermekek, a kiket az Isten nékem adott."));
husuperobject.biblemap.put("b58_2_14", new husuperobject(58,2,14,"Mivel tehát a gyermekek testbõl és vérbõl valók, õ is hasonlatosképen részese lett azoknak, hogy a halál által megsemmisítse azt, a kinek hatalma van a halálon, tudniillik az ördögöt,"));
husuperobject.biblemap.put("b58_2_15", new husuperobject(58,2,15,"És megszabadítsa azokat, a kik a haláltól való félelem miatt teljes életökben rabok valának."));
husuperobject.biblemap.put("b58_2_16", new husuperobject(58,2,16,"Mert nyilván nem angyalokat karolt fel, hanem az Ábrahám magvát karolta fel."));
husuperobject.biblemap.put("b58_2_17", new husuperobject(58,2,17,"Annakokáért mindenestõl fogva hasonlatosnak kellett lennie az atyafiakhoz, hogy könyörülõ legyen és hív fõpap az Isten elõtt való dolgokban, hogy engesztelést szerezzen a nép bûneiért."));
husuperobject.biblemap.put("b58_2_18", new husuperobject(58,2,18,"Mert a mennyiben szenvedett, õ maga is megkísértetvén, segíthet azokon, a kik megkísértetnek."));
husuperobject.biblemap.put("b58_3_1", new husuperobject(58,3,1,"Annakokáért szent atyafiak, mennyei elhívásnak részesei, figyelmezzetek, a mi vallásunknak apostolára és fõpapjára, Krisztus Jézusra,"));
husuperobject.biblemap.put("b58_3_2", new husuperobject(58,3,2,"A ki hû ahhoz, a ki õt rendelte, valamint Mózes is az õ egész házában."));
husuperobject.biblemap.put("b58_3_3", new husuperobject(58,3,3,"Mert ez nagyobb dicsõségre méltattatott, mint Mózes, a mennyiben a ház építõjének nagyobb a tisztessége, mint a háznak."));
husuperobject.biblemap.put("b58_3_4", new husuperobject(58,3,4,"Mert minden háznak van építõje, a ki pedig mindent elkészített, az Isten az."));
husuperobject.biblemap.put("b58_3_5", new husuperobject(58,3,5,"Mózes is hû volt ugyan az õ egész házában, mint szolga, a hirdetendõknek bizonyságára,"));
husuperobject.biblemap.put("b58_3_6", new husuperobject(58,3,6,"Krisztus ellenben mint Fiú a maga háza felett, a kinek háza mi vagyunk, ha a bizodalmat és a reménységnek dicsekedését mind végig erõsen megtartjuk."));
husuperobject.biblemap.put("b58_3_7", new husuperobject(58,3,7,"Annakokáéért a mint a Szent Lélek mondja: Ma, ha az õ szavát halljátok,"));
husuperobject.biblemap.put("b58_3_8", new husuperobject(58,3,8,"Meg ne keményítsétek a ti szíveteket, mint az elkeseredéskor, a kísértés ama napján a pusztában,"));
husuperobject.biblemap.put("b58_3_9", new husuperobject(58,3,9,"A hol a ti atyáitok próbára tevéssel megkísértének engem és látták az én cselekedeteimet negyven esztendeig."));
husuperobject.biblemap.put("b58_3_10", new husuperobject(58,3,10,"Azért megharagudtam arra a nemzetségre és mondám: mindig tévelyegnek szivökben; õk pedig nem ismerték meg az én útaimat."));
husuperobject.biblemap.put("b58_3_11", new husuperobject(58,3,11,"Úgy hogy megesküdtem haragomban, hogy nem fognak bemenni az én nyugodalmamba."));
husuperobject.biblemap.put("b58_3_12", new husuperobject(58,3,12,"Vigyázzatok atyámfiai, hogy valaha ne legyen bármelyikõtöknek hitetlen gonosz szíve, hogy az élõ Istentõl elszakadjon;"));
husuperobject.biblemap.put("b58_3_13", new husuperobject(58,3,13,"Hanem intsétek egymást minden napon, míg tart a ma, hogy egyikõtök se keményíttessék meg a bûnnek csalárdsága által:"));
husuperobject.biblemap.put("b58_3_14", new husuperobject(58,3,14,"Mert részeseivé lettünk Krisztusnak, ha ugyan az elkezdett bizodalmat mindvégig erõsen megtartjuk."));
husuperobject.biblemap.put("b58_3_15", new husuperobject(58,3,15,"E mondás szerint: Ma, ha az õ szavát halljátok, meg ne keményítsétek a ti szíveiteket, mint az elkeseredéskor."));
husuperobject.biblemap.put("b58_3_16", new husuperobject(58,3,16,"Mert kik keseredtek el, mikor ezt hallák? Nemde mindazok, a kik kijövének Égyiptomból Mózes által?"));
husuperobject.biblemap.put("b58_3_17", new husuperobject(58,3,17,"Kikre haragudott vala pedig meg negyven esztendeig? avagy nem azokra-é, a kik vétkeztek, a kiknek testei elhullottak a pusztában?"));
husuperobject.biblemap.put("b58_3_18", new husuperobject(58,3,18,"Kiknek esküdött pedig meg, hogy nem mennek be az õ nyugodalmába, hanemha az engedetleneknek?"));
husuperobject.biblemap.put("b58_3_19", new husuperobject(58,3,19,"Látjuk is, hogy nem mehettek be hitetlenség miatt."));
husuperobject.biblemap.put("b58_4_1", new husuperobject(58,4,1,"Óvakodjunk tehát, hogy mivel megvan az õ nyugodalmába való bemenetel ígérete, valaki közületek fogyatkozásban levõnek ne láttassék."));
husuperobject.biblemap.put("b58_4_2", new husuperobject(58,4,2,"Mert nékünk is hirdettetett az evangyéliom, miképen azoknak: de nem használt nékik a hallott beszéd, mivel nem párosították hittel azok, a kik hallották."));
husuperobject.biblemap.put("b58_4_3", new husuperobject(58,4,3,"Mert mi, hívõk, bemegyünk a nyugodalomba, miképen megmondotta: A mint megesküdtem az én haragomban, nem fognak bemenni az én nyugodalmamba; jóllehet munkáit a világ megalapításától kezdve bevégezte."));
husuperobject.biblemap.put("b58_4_4", new husuperobject(58,4,4,"Mert valahol a hetedik napról ekképen szólott: És megnyugovék Isten a hetedik napon minden õ cselekedeteitõl."));
husuperobject.biblemap.put("b58_4_5", new husuperobject(58,4,5,"És ugyanabban ismét: Nem mennek be az én nyugodalmamba."));
husuperobject.biblemap.put("b58_4_6", new husuperobject(58,4,6,"Mivelhogy annakokáért áll az, hogy némelyek bemennek abba, és a kiknek elõször hirdettetett az evangyéliom, nem mentek be engedetlenség miatt:"));
husuperobject.biblemap.put("b58_4_7", new husuperobject(58,4,7,"Ismét határoz egy napot: Ma, szólván Dávid által annnyi idõ multán, a mint elõbb mondva volt. Ma, ha az õ szavát halljátok, meg ne keményítsétek a ti szíveiteket."));
husuperobject.biblemap.put("b58_4_8", new husuperobject(58,4,8,"Mert ha õket Józsué nyugodalomba helyezte volna, nem szólana azok után más napról."));
husuperobject.biblemap.put("b58_4_9", new husuperobject(58,4,9,"Annakokáért megvan a szombatja az Isten népének."));
husuperobject.biblemap.put("b58_4_10", new husuperobject(58,4,10,"Mert a ki bement az õ nyugodalmába, az maga is megnyugodott cselekedeteitõl, a miképen Isten is a magáéitól,"));
husuperobject.biblemap.put("b58_4_11", new husuperobject(58,4,11,"Igyekezzünk tehát bemenni abba a nyugodalomba, hogy valaki a hitetlenségnek ugyanazon példájába ne essék."));
husuperobject.biblemap.put("b58_4_12", new husuperobject(58,4,12,"Mert az Istennek beszéde élõ és ható, és élesebb minden kétélû fegyvernél, és elhat a szívnek és léleknek, az ízeknek és a velõknek megoszlásáig, és megítéli a gondolatokat és a szívnek indulatait."));
husuperobject.biblemap.put("b58_4_13", new husuperobject(58,4,13,"És nincsen oly teremtmény, a mely nyilvánvaló nem volna elõtte, sõt mindenek meztelenek és leplezetlenek annak szemei elõtt, a kirõl mi beszélünk."));
husuperobject.biblemap.put("b58_4_14", new husuperobject(58,4,14,"Lévén annakokáért nagy fõpapunk, a ki áthatolt az egeken, Jézus, az Istennek Fia, ragaszkodjunk vallásunkhoz."));
husuperobject.biblemap.put("b58_4_15", new husuperobject(58,4,15,"Mert nem oly fõpapunk van, a ki nem tudna megindulni gyarlóságainkon, hanem a ki megkísértetett mindenekben, hozzánk hasonlóan, kivéve a bûnt."));
husuperobject.biblemap.put("b58_4_16", new husuperobject(58,4,16,"Járuljunk azért bizodalommal a kegyelem királyi székéhez, hogy irgalmasságot nyerjünk és kegyelmet találjunk, alkalmas idõben való segítségül."));
husuperobject.biblemap.put("b58_5_1", new husuperobject(58,5,1,"Mert minden fõpap emberek közül választatván, emberekért rendeltetik az Isten elõtt való dolgokban, hogy ajándékokat és áldozatokat vigyen a bûnökért,"));
husuperobject.biblemap.put("b58_5_2", new husuperobject(58,5,2,"A ki képes együttérezni a tudatlanokkal és tévelygõkkel, mivelhogy maga is körül van véve gyarlósággal."));
husuperobject.biblemap.put("b58_5_3", new husuperobject(58,5,3,"És ezért köteles, miképen a népért, azonképen önmagáért is áldozni a bûnökért."));
husuperobject.biblemap.put("b58_5_4", new husuperobject(58,5,4,"És senki sem veszi magának e tisztességet, hanem a [kit] Isten hív el, miként Áront is."));
husuperobject.biblemap.put("b58_5_5", new husuperobject(58,5,5,"Hasonnlóképen Krisztus sem maga dicsõítette meg magát azzal, hogy fõpap lett, hanem az, a ki így szólott hozzá: Én Fiam vagy te, ma szûltelek téged."));
husuperobject.biblemap.put("b58_5_6", new husuperobject(58,5,6,"Miképen másutt is mondja: Te örökké való pap vagy, Melkisédek rendje szerint."));
husuperobject.biblemap.put("b58_5_7", new husuperobject(58,5,7,"Ki az õ testének napjaiban könyörgésekkel és esedezésekkel, erõs kiáltás és könyhullatás közben járult ahhoz, a ki képes megszabadítani õt a halálból, és meghallgattatott az õ istenfélelméért,"));
husuperobject.biblemap.put("b58_5_8", new husuperobject(58,5,8,"Ámbár Fiú, megtanulta azokból, a miket szenvedett, az engedelmességet;"));
husuperobject.biblemap.put("b58_5_9", new husuperobject(58,5,9,"És tökéletességre jutván, örök idvesség szerzõje lett mindazokra nézve, a kik neki engedelmeskednek,"));
husuperobject.biblemap.put("b58_5_10", new husuperobject(58,5,10,"Neveztetvén az Istentõl Melkisédek rendje szerint való fõpapnak."));
husuperobject.biblemap.put("b58_5_11", new husuperobject(58,5,11,"A kirõl nekünk sok és nehezen megmagyarázható mondani valónk van, mivel restek lettetek a hallásra."));
husuperobject.biblemap.put("b58_5_12", new husuperobject(58,5,12,"Mert noha ez idõ szerint tanítóknak kellene lennetek, ismét arra van szükségetek, hogy az Isten beszédeinek kezdõ elemeire tanítson valaki titeket; és olyanok lettetek, a kiknek tejre van szükségetek és nem kemény eledelre."));
husuperobject.biblemap.put("b58_5_13", new husuperobject(58,5,13,"Mert mindaz, a ki tejjel él, járatlan az igazságnak beszédiben, mivelhogy kiskorú:"));
husuperobject.biblemap.put("b58_5_14", new husuperobject(58,5,14,"Az érettkorúaknak pedig kemény eledel való, mint a kiknek mivoltuknál fogva gyakorlottak az érzékeik a jó és rossz között való különbségtételre."));
husuperobject.biblemap.put("b58_6_1", new husuperobject(58,6,1,"Annakokáért elhagyván a Krisztusról való kezdetleges beszédet, törekedjünk tökéletességre, nem rakosgatván le újra alapját a holt cselekedetekbõl való megtérésnek és az Istenben való hitnek,"));
husuperobject.biblemap.put("b58_6_2", new husuperobject(58,6,2,"A mosakodásoknak, tanításnak, kezek rátevésének, holtak feltámadásának és az örök ítéletnek."));
husuperobject.biblemap.put("b58_6_3", new husuperobject(58,6,3,"És ezt megcselekeszszük, ha az Isten megengedi."));
husuperobject.biblemap.put("b58_6_4", new husuperobject(58,6,4,"Mert lehetetlen dolog, hogy a kik egyszer megvilágosíttattak, megízlelvén a mennyei ajándékot, és részeseivé lettek a Szent Léleknek,"));
husuperobject.biblemap.put("b58_6_5", new husuperobject(58,6,5,"És megízlelték az Istennek jó beszédét és a jövendõ világnak erõit,"));
husuperobject.biblemap.put("b58_6_6", new husuperobject(58,6,6,"És elestek, ismét megújuljanak a megtérésre, mint a kik önmagoknak feszítik meg az Istennek ama Fiát, és meggyalázzák õt."));
husuperobject.biblemap.put("b58_6_7", new husuperobject(58,6,7,"Mert a föld, a mely beiszsza a gyakorta reá hulló esõt és hasznos füvet terem azoknak, a kikért mûveltetik, áldást nyer Istentõl;"));
husuperobject.biblemap.put("b58_6_8", new husuperobject(58,6,8,"A mely pedig töviseket és bojtorjánokat terem, megvetett és közel van az átokhoz, annak vége megégetés."));
husuperobject.biblemap.put("b58_6_9", new husuperobject(58,6,9,"De ti felõletek szerelmeseim, ezeknél jobb és idvességesebb dolgokról vagyunk meggyõzõdve, ha így szólunk is."));
husuperobject.biblemap.put("b58_6_10", new husuperobject(58,6,10,"Mert nem igazságtalan az Isten, hogy elfelejtkezzék a ti cselekedeteitekrõl és a szeretetrõl, melyet tanúsítottatok az õ neve iránt, mint a kik szolgáltatok és szolgáltok a szenteknek."));
husuperobject.biblemap.put("b58_6_11", new husuperobject(58,6,11,"Kívánjuk pedig, hogy közületek kiki ugyanazon buzgóságot tanusítsa a reménységnek bizonyossága iránt mindvégiglen."));
husuperobject.biblemap.put("b58_6_12", new husuperobject(58,6,12,"Hogy ne legyetek restek, hanem követõi azoknak, a kik hit és békességes tûrés által öröklik az ígéreteket."));
husuperobject.biblemap.put("b58_6_13", new husuperobject(58,6,13,"Mert az Isten, mikor ígéretet tett Ábrahámnak, mivelhogy nem esküdhetett nagyobbra, önmagára esküdött."));
husuperobject.biblemap.put("b58_6_14", new husuperobject(58,6,14,"Mondván: Bizony megáldván megáldalak téged, és megsokasítván megsokasítalak téged."));
husuperobject.biblemap.put("b58_6_15", new husuperobject(58,6,15,"És ekképen, békességestûrõ lévén, megnyerte az ígéretet."));
husuperobject.biblemap.put("b58_6_16", new husuperobject(58,6,16,"Mert az emberek nagyobbra esküsznek, és nálok minden versengésnek vége megerõsítésül az eskü;"));
husuperobject.biblemap.put("b58_6_17", new husuperobject(58,6,17,"Miért is az Isten, kiválóbban megakarván mutatni az ígéret örököseinek az õ végzése változhatatlan voltát, esküvéssel lépett közbe,"));
husuperobject.biblemap.put("b58_6_18", new husuperobject(58,6,18,"Hogy két változhatatlan tény által, melyekre nézve lehetetlen, hogy az Isten hazudjon, erõs vígasztalásunk legyen minékünk, mint a kik oda menekültünk, hogy megragadjuk az elõttünk levõ reménységet,"));
husuperobject.biblemap.put("b58_6_19", new husuperobject(58,6,19,"Mely lelkünknek mintegy bátorságos és erõs horgonya és beljebb hatol a kárpítnál,"));
husuperobject.biblemap.put("b58_6_20", new husuperobject(58,6,20,"A hová útnyitóul bement érettünk Jézus, a ki örökké való fõpap lett Melkisédek rendje szerint."));
husuperobject.biblemap.put("b58_7_1", new husuperobject(58,7,1,"Mert ez a Melkisédek Sálem királya, a felséges Isten papja, a ki a királyok leverésébõl visszatérõ Ábrahámmal találkozván, õt megáldotta,"));
husuperobject.biblemap.put("b58_7_2", new husuperobject(58,7,2,"A kinek tizedet is adott Ábrahám mindenbõl: a ki elsõben is magyarázat szerint igazság királya, azután pedig Sálem királya is, azaz békesség királya,"));
husuperobject.biblemap.put("b58_7_3", new husuperobject(58,7,3,"Apa nélkül, anya nélkül, nemzetség nélkül való; sem napjainak kezdete, sem életének vége nincs, de hasonlóvá tétetvén az Isten Fiához, pap marad örökké."));
husuperobject.biblemap.put("b58_7_4", new husuperobject(58,7,4,"Nézzétek meg pedig, mily nagy ez, a kinek a zsákmányból tizedet is adott Ábrahám, a pátriárka;"));
husuperobject.biblemap.put("b58_7_5", new husuperobject(58,7,5,"És bár azoknak, kik a Lévi fiai közül nyerik el a papságot, parancsolatjok van, hogy törvény szerint tizedet szedjenek a néptõl, azaz az õ atyafiaiktól, jóllehet õk is az Ábrahám ágyékából származtak;"));
husuperobject.biblemap.put("b58_7_6", new husuperobject(58,7,6,"De az, a kinek nemzetsége nem azok közül való, tizedet vett Ábrahámtól, és az ígéretek birtokosát megáldotta,"));
husuperobject.biblemap.put("b58_7_7", new husuperobject(58,7,7,"Pedig minden ellenmondás nélkül való, hogy a nagyobb áldja meg a kisebbet."));
husuperobject.biblemap.put("b58_7_8", new husuperobject(58,7,8,"És itt halandó emberek szednek tizedet, ott ellenben az, a ki bizonyság szerint él:"));
husuperobject.biblemap.put("b58_7_9", new husuperobject(58,7,9,"És hogy úgy szóljak, Ábrahámnál fogva tized vétetett Lévitõl is, a tizedszedõtõl,"));
husuperobject.biblemap.put("b58_7_10", new husuperobject(58,7,10,"Mert õ még az atyja ágyékában vala, a mikor annak elébe ment Melkisédek."));
husuperobject.biblemap.put("b58_7_11", new husuperobject(58,7,11,"Ha tehát a lévitai papság által volna a tökéletesség (mert a nép ez alatt nyerte a törvényt): mi szükség tovább is mondogatni, hogy más pap támadjon a Melkisédek rendje szerint és ne az Áron rendje szerint?"));
husuperobject.biblemap.put("b58_7_12", new husuperobject(58,7,12,"Mert a papság megváltozásával szükségképen megváltozik a törvény is."));
husuperobject.biblemap.put("b58_7_13", new husuperobject(58,7,13,"Mert a kirõl ezek mondatnak, az más nemzetségbõl származott, a melybõl senki sem szolgált az oltár körül;"));
husuperobject.biblemap.put("b58_7_14", new husuperobject(58,7,14,"Mert nyilvánvaló, hogy a mi Urunk Júdából támadott, a mely nemzetségre nézve semmit sem szólott Mózes a papságról."));
husuperobject.biblemap.put("b58_7_15", new husuperobject(58,7,15,"És még inkább nyilvánvaló az, ha a Melkisédek hasonlatossága szerint áll elõ más pap,"));
husuperobject.biblemap.put("b58_7_16", new husuperobject(58,7,16,"A ki nem testi parancsolatnak törvénye szerint, hanem enyészhetetlen életnek ereje szerint lett."));
husuperobject.biblemap.put("b58_7_17", new husuperobject(58,7,17,"Mert ez a bizonyságtétel: Te pap vagy örökké, Melkisédek rendje szerint."));
husuperobject.biblemap.put("b58_7_18", new husuperobject(58,7,18,"Mert az elõbbi parancsolat eltöröltetik, mivelhogy erõtelen és haszontalan,"));
husuperobject.biblemap.put("b58_7_19", new husuperobject(58,7,19,"Minthogy a törvény semmiben sem szerzett tökéletességet; de beáll a jobb reménység, a mely által közeledünk az Istenhez."));
husuperobject.biblemap.put("b58_7_20", new husuperobject(58,7,20,"És a mennyiben nem esküvés nélkül való, mert amazok esküvés nélkül lettek papokká,"));
husuperobject.biblemap.put("b58_7_21", new husuperobject(58,7,21,"De ez esküvéssel, az által, a ki azt mondá néki: Megesküdött az Úr, és nem bánja meg, te pap vagy örökké, Melkisédek rendje szerint:"));
husuperobject.biblemap.put("b58_7_22", new husuperobject(58,7,22,"Annyiban jobb szövetségnek lett kezesévé Jézus."));
husuperobject.biblemap.put("b58_7_23", new husuperobject(58,7,23,"És amazok jóllehet többen lettek papokká, mert a halál miatt meg nem maradhattak:"));
husuperobject.biblemap.put("b58_7_24", new husuperobject(58,7,24,"De ennek, minthogy örökké megmarad, változhatatlan a papsága."));
husuperobject.biblemap.put("b58_7_25", new husuperobject(58,7,25,"Ennekokáért õ mindenképen idvezítheti is azokat, a kik õ általa járulnak Istenhez, mert mindenha él, hogy esedezzék érettök."));
husuperobject.biblemap.put("b58_7_26", new husuperobject(58,7,26,"Mert ilyen fõpap illet vala minket, szent, ártatlan, szeplõtelen, a bûnösöktõl elválasztott, és a ki az egeknél magasságosabb lõn,"));
husuperobject.biblemap.put("b58_7_27", new husuperobject(58,7,27,"A kinek nincs szüksége, mint a fõpapoknak, hogy napról-napra elõbb a saját bûneiért vigyen áldozatot, azután a népéiért, mert ezt egyszer megcselekedte, maga-magát megáldozván."));
husuperobject.biblemap.put("b58_7_28", new husuperobject(58,7,28,"Mert a törvény gyarló embereket rendel fõpapokká, de a törvény után való esküvés beszéde örök tökéletes Fiút."));
husuperobject.biblemap.put("b58_8_1", new husuperobject(58,8,1,"Fõdolog pedig azokra nézve, a miket mondunk, az, hogy olyan fõpapunk van, a ki a mennyei Felség királyi székének jobbjára üle,"));
husuperobject.biblemap.put("b58_8_2", new husuperobject(58,8,2,"Mint a szent helynek és amaz igazi sátornak szolgája, a melyet az Úr és nem ember épített."));
husuperobject.biblemap.put("b58_8_3", new husuperobject(58,8,3,"Mert minden fõpap ajándékok meg áldozatok vitelére rendeltetik, a miért szükséges, hogy legyen valamije ennek is, a mit áldozatul vigyen."));
husuperobject.biblemap.put("b58_8_4", new husuperobject(58,8,4,"Ha tehát a földön volna, még csak pap sem volna, lévén olyan papok, a kik a törvény szerint áldoznak ajándékokkal,"));
husuperobject.biblemap.put("b58_8_5", new husuperobject(58,8,5,"A kik a mennyei dolgok ábrázolatának és árnyékának szolgálnak, a mint Isten mondotta Mózesnek, mikor be akarta végezni a sátort: Meglásd, úgymond, hogy mindeneket azon minta szerint készíts, a mely a hegyen mutattatott néked."));
husuperobject.biblemap.put("b58_8_6", new husuperobject(58,8,6,"Most azonban annyival kiválóbb szolgálatot nyert, a mennyivel jobb szövetségnek közbenjárója, a mely jobb ígéretek alapján köttetett."));
husuperobject.biblemap.put("b58_8_7", new husuperobject(58,8,7,"Mert ha az az elsõ kifogástalan volt volna, nem kerestetett volna hely a másodiknak."));
husuperobject.biblemap.put("b58_8_8", new husuperobject(58,8,8,"Mert dorgálván õket, így szól: Ímé napok jõnek, ezt mondja az Úr, és az Izráel házával és Júdának házával új szövetséget kötök."));
husuperobject.biblemap.put("b58_8_9", new husuperobject(58,8,9,"Nem azon szövetség szerint, a melyet kötöttem az õ atyáikkal ama napon, mikor kézen fogtam õket, hogy kivezessem Égyiptomból, mert õk nem maradtak meg abban az én szövetségemben, azért én sem gondoltam velök, mondja az Úr."));
husuperobject.biblemap.put("b58_8_10", new husuperobject(58,8,10,"Mert ez az a szövetség, melyet kötök az Izráel házával, ama napok multán, mond az Úr: Adom az én törvényemet az õ elméjökbe, és az õ szívökbe írom azokat, és leszek nekik Istenök és õk lesznek nekem népem."));
husuperobject.biblemap.put("b58_8_11", new husuperobject(58,8,11,"És nem tanítja kiki az õ felebarátját és kiki az õ atyafiát, mondván: Ismerd meg az Urat; mert mindnyájan megismernek engem a kicsinytõl nagyig."));
husuperobject.biblemap.put("b58_8_12", new husuperobject(58,8,12,"Mert megkegyelmezek álnokságaiknak, és az õ bûneikrõl és gonoszságaikról meg nem emlékezem."));
husuperobject.biblemap.put("b58_8_13", new husuperobject(58,8,13,"Mikor újról beszél, óvá tette az elsõt; a mi pedig megavul és megvénhedik, közel van az enyészethez."));
husuperobject.biblemap.put("b58_9_1", new husuperobject(58,9,1,"Annakokáért voltak ugyan az elsõ [szövetségnek] is istentiszteletei rendtartásai, mint szintén világi szenthelye."));
husuperobject.biblemap.put("b58_9_2", new husuperobject(58,9,2,"Mert sátor építtetett, az elsõ, a melyben [vala] a gyertyatartó, meg az asztal és a kenyerek felrakása; ezt nevezték szenthelynek."));
husuperobject.biblemap.put("b58_9_3", new husuperobject(58,9,3,"A második kárpiton túl pedig az a sátor, melyet neveztek szentek szentének,"));
husuperobject.biblemap.put("b58_9_4", new husuperobject(58,9,4,"Melyben vala az arany füstölõ oltár és a szövetség ládája beborítva minden felõl aranynyal, ebben a mannás aranykorsó és Áron kihajtott vesszeje meg a szövetség táblái,"));
husuperobject.biblemap.put("b58_9_5", new husuperobject(58,9,5,"Fölötte pedig a dicsõség kérubjai, beárnyékolva a fedelet, a mikrõl most nem szükséges külön szólani."));
husuperobject.biblemap.put("b58_9_6", new husuperobject(58,9,6,"Ezek pedig ekképen levén elrendezve; az elsõ sátorba ugyan mindenkor bejárnak a papok az istentisztelet elvégzésére,"));
husuperobject.biblemap.put("b58_9_7", new husuperobject(58,9,7,"A másodikba azonban egy-egy évben egyszer csak maga a fõpap, vérrel, melyet magáért és a nép bûneiért áldoz."));
husuperobject.biblemap.put("b58_9_8", new husuperobject(58,9,8,"Azt jelentvén ki ezzel a Szent Lélek, hogy még nem nyilt meg a szentély útja, fennállván még az elsõ sátor."));
husuperobject.biblemap.put("b58_9_9", new husuperobject(58,9,9,"A mi példázat a jelenkori idõre, mikor áldoznak oly ajándékokkal és áldozatokkal, melyek nem képesek lelkiismeret szerint tökéletessé tenni a szolgálattevõt,"));
husuperobject.biblemap.put("b58_9_10", new husuperobject(58,9,10,"Csakis ételekkel meg italokkal és különbözõ mosakodásokkal - melyek testi rendszabályok - a megjobbulás idejéig kötelezõk."));
husuperobject.biblemap.put("b58_9_11", new husuperobject(58,9,11,"Krisztus pedig megjelenvén, mint a jövendõ javaknak fõpapja, a nagyobb és tökéletesebb, nem kézzel csinált, azaz nem e világból való sátoron keresztül,"));
husuperobject.biblemap.put("b58_9_12", new husuperobject(58,9,12,"És nem bakok és tulkok vére által, hanem az õ tulajdon vére által ment be egyszer s mindenkorra a szentélybe, örök váltságot szerezve."));
husuperobject.biblemap.put("b58_9_13", new husuperobject(58,9,13,"Mert ha a bakoknak és bikáknak a vére, meg a tehén hamva, a tisztátalanokra hintetvén, megszentel a testnek tisztaságára:"));
husuperobject.biblemap.put("b58_9_14", new husuperobject(58,9,14,"Mennyivel inkább Krisztusnak a vére, a ki örökké való Lélek által önmagát áldozta fel ártatlanul Istennek: megtisztítja a ti lelkiismereteteket a holt cselekedetektõl, hogy szolgáljatok az élõ Istennek."));
husuperobject.biblemap.put("b58_9_15", new husuperobject(58,9,15,"És ezért új szövetségnek a közbenjárója õ, hogy meghalván az elsõ szövetségbeli bûnök váltságáért, a hivatottak elnyerjék az örökkévaló örökségnek ígéretét."));
husuperobject.biblemap.put("b58_9_16", new husuperobject(58,9,16,"Mert a hol végrendelet van, szükséges, hogy a végrendelkezõ halála bekövetkezzék."));
husuperobject.biblemap.put("b58_9_17", new husuperobject(58,9,17,"Mivel a végrendelet holtak után jogerõs, különben pedig, ha él a végrendelkezõ, épen nem érvényes."));
husuperobject.biblemap.put("b58_9_18", new husuperobject(58,9,18,"Innét van, hogy az elsõ sem szenteltetett meg vér nélkül."));
husuperobject.biblemap.put("b58_9_19", new husuperobject(58,9,19,"Mert mikor Mózes a törvény szerint minden parancsolatot elmondott az egész népnek, vevén a borjúknak és a bakoknak vérét, vízzel és vörös gyapjúval meg izsóppal együtt, magát a könyvet is és az egész népet meghintette,"));
husuperobject.biblemap.put("b58_9_20", new husuperobject(58,9,20,"Mondván: Ez azon szövetség vére, a melyet Isten számotokra rendelt."));
husuperobject.biblemap.put("b58_9_21", new husuperobject(58,9,21,"Majd a sátort is és az istentiszteletre való összes edényeket hasonlóképen meghintette vérrel."));
husuperobject.biblemap.put("b58_9_22", new husuperobject(58,9,22,"És csaknem minden vérrel tisztíttatik meg a törvény szerint, és vérontás nélkül nincsen bûnbocsánat."));
husuperobject.biblemap.put("b58_9_23", new husuperobject(58,9,23,"Annakokáért szükséges, hogy a mennyei dolgoknak ábrázolatai effélékkel tisztíttassanak meg, magok a mennyei dolgok azonban ezeknél különb áldozatokkal."));
husuperobject.biblemap.put("b58_9_24", new husuperobject(58,9,24,"Mert nem kézzel csinált szentélybe, az igazinak csak másolatába ment be Krisztus, hanem magába a mennybe, hogy most Isten színe elõtt megjelenjék érettünk."));
husuperobject.biblemap.put("b58_9_25", new husuperobject(58,9,25,"Nem is, hogy sokszor adja magát áldozatul, mint a hogy a fõpap évenként bemegy a szentélybe idegen vérrel;"));
husuperobject.biblemap.put("b58_9_26", new husuperobject(58,9,26,"Mert különben sokszor kellett volna szenvednie a világ teremtetése óta; így pedig csak egyszer jelent meg az idõknek végén, hogy áldozatával eltörölje a bûnt."));
husuperobject.biblemap.put("b58_9_27", new husuperobject(58,9,27,"És miképen elvégezett dolog, hogy az emberek egyszer meghaljanak, azután az ítélet:"));
husuperobject.biblemap.put("b58_9_28", new husuperobject(58,9,28,"Azonképen Krisztus is egyszer megáldoztatván sokak bûneinek eltörlése végett, másodszor bûn nélkül jelen meg azoknak, a kik õt várják idvességökre."));
husuperobject.biblemap.put("b58_10_1", new husuperobject(58,10,1,"Minthogy a törvényben a jövendõ jóknak árnyéka, nem maga a dolgok képe van meg, ennélfogva azokkal az áldozatokkal, a melyeket esztendõnként szünetlenül visznek, sohasem képes tökéletességre juttatni az odajárulókat;"));
husuperobject.biblemap.put("b58_10_2", new husuperobject(58,10,2,"Különben megszûnt volna az áldozás, mivelhogy az egyszer megtisztult áldozók többé semminemû bûntudattal nem bírtak volna."));
husuperobject.biblemap.put("b58_10_3", new husuperobject(58,10,3,"De azok esztendõnként bûnre emlékeztetnek."));
husuperobject.biblemap.put("b58_10_4", new husuperobject(58,10,4,"Mert lehetetlen, hogy a bikák és bakok vére eltörölje a bûnöket."));
husuperobject.biblemap.put("b58_10_5", new husuperobject(58,10,5,"Azért a világba bejövetelekor így szól: Áldozatot és ajándékot nem akartál, de testet alkottál nékem,"));
husuperobject.biblemap.put("b58_10_6", new husuperobject(58,10,6,"Égõ és bûnért való áldozatokat nem kedveltél."));
husuperobject.biblemap.put("b58_10_7", new husuperobject(58,10,7,"Akkor mondám: Ímé itt vagyok, (a könyv fejezetében írva vagyon rólam), hogy cselekedjem óh Isten a te akaratodat."));
husuperobject.biblemap.put("b58_10_8", new husuperobject(58,10,8,"Fentebb mondván, hogy áldozatot és ajándékot és égõ, meg bûnért való áldozatokat nem akartál, sem nem kedveltél a melyeket a törvény szerint visznek,"));
husuperobject.biblemap.put("b58_10_9", new husuperobject(58,10,9,"Ekkor ezt mondotta: Ímé itt vagyok, hogy cselekedjem a te akaratodat. Eltörli az elsõt, hogy meghagyja a másodikat,"));
husuperobject.biblemap.put("b58_10_10", new husuperobject(58,10,10,"A mely akarattal szenteltettünk meg egyszer s mindenkorra, a Jézus Krisztus testének megáldozása által."));
husuperobject.biblemap.put("b58_10_11", new husuperobject(58,10,11,"És minden pap naponként szolgálatban áll és gyakorta viszi ugyanazokat az áldozatokat, a melyek sohasem képesek eltörölni a bûnöket."));
husuperobject.biblemap.put("b58_10_12", new husuperobject(58,10,12,"Õ azonban, egy áldozattal áldozván a bûnökért, mindörökre ûle az Istennek jobbjára,"));
husuperobject.biblemap.put("b58_10_13", new husuperobject(58,10,13,"Várván ímmár, míg lábainak zsámolyául vettetnek az õ ellenségei."));
husuperobject.biblemap.put("b58_10_14", new husuperobject(58,10,14,"Mert egyetlenegy áldozatával örökre tökéletesekké tette a megszentelteket."));
husuperobject.biblemap.put("b58_10_15", new husuperobject(58,10,15,"Bizonyságot tesz pedig errõl mi nékünk a Szent Lélek is, mert minekutána elõre mondotta:"));
husuperobject.biblemap.put("b58_10_16", new husuperobject(58,10,16,"Ez az a szövetség, melyet kötök velök ama napok után, mondja az Úr: Adom az én törvényemet az õ szíveikbe, és az õ elméjökbe írom be azokat,"));
husuperobject.biblemap.put("b58_10_17", new husuperobject(58,10,17,"[Azután így szól:] És az õ bûneikrõl és álnokságaikról többé meg nem emlékezem."));
husuperobject.biblemap.put("b58_10_18", new husuperobject(58,10,18,"A hol pedig bûnök bocsánata vagyon, ott nincs többé bûnért való áldozat."));
husuperobject.biblemap.put("b58_10_19", new husuperobject(58,10,19,"Mivelhogy azért atyámfiai bizodalmunk van a szentélybe való bemenetelre a Jézus vére által,"));
husuperobject.biblemap.put("b58_10_20", new husuperobject(58,10,20,"Azon az úton, a melyet õ szentelt nékünk új és élõ [út] gyanánt, a kárpit, azaz az õ teste által,"));
husuperobject.biblemap.put("b58_10_21", new husuperobject(58,10,21,"És lévén nagy papunk az Isten háza felett:"));
husuperobject.biblemap.put("b58_10_22", new husuperobject(58,10,22,"Járuljunk hozzá igaz szívvel, hitnek teljességével, mint a kiknek szívök tiszta a gonosz lelkiismerettõl,"));
husuperobject.biblemap.put("b58_10_23", new husuperobject(58,10,23,"És testök meg van mosva tiszta vízzel; tartsuk meg a reménységnek vallását tántoríthatatlanul, mert hû az, a ki ígéretet tett,"));
husuperobject.biblemap.put("b58_10_24", new husuperobject(58,10,24,"És ügyeljünk egymásra, a szeretetre és jó cselekedetekre való felbuzdulás végett,"));
husuperobject.biblemap.put("b58_10_25", new husuperobject(58,10,25,"El nem hagyván a magunk gyülekezetét, a miképen szokásuk némelyeknek, hanem intvén egymást annyival inkább, mivel látjátok, hogy ama nap közelget."));
husuperobject.biblemap.put("b58_10_26", new husuperobject(58,10,26,"Mert ha szándékosan vétkezünk, az igazság megismerésére való eljutás után, akkor többé nincs bûnökért való áldozat,"));
husuperobject.biblemap.put("b58_10_27", new husuperobject(58,10,27,"Hanem az ítéletnek valami rettenetes várása és a tûznek lángja, a mely megemészti az ellenszegülõket."));
husuperobject.biblemap.put("b58_10_28", new husuperobject(58,10,28,"A ki megveti a Mózes törvényét, két vagy három tanubizonyságra irgalom nélkül meghal;"));
husuperobject.biblemap.put("b58_10_29", new husuperobject(58,10,29,"Gondoljátok meg, mennyivel súlyosabb büntetésre méltónak ítéltetik az, a ki az Isten Fiát megtapodja, és a szövetségnek vérét, melylyel megszenteltetett, tisztátalannak tartja, és a kegyelemnek Lelkét bántalmazza?"));
husuperobject.biblemap.put("b58_10_30", new husuperobject(58,10,30,"Mert ismerjük azt, a ki így szólt: Enyém a bosszúállás, én megfizetek, ezt mondja az Úr. És ismét: Az Úr megítéli az õ népét."));
husuperobject.biblemap.put("b58_10_31", new husuperobject(58,10,31,"Rettenetes dolog az élõ Istennek kezébe esni."));
husuperobject.biblemap.put("b58_10_32", new husuperobject(58,10,32,"Emlékezzetek pedig vissza a régebbi napokra, a melyekben, minekutána megvilágosíttattatok, sok szenvedésteljes küzdelmet állottatok ki,"));
husuperobject.biblemap.put("b58_10_33", new husuperobject(58,10,33,"Midõn egyfelõl gyalázásokkal és nyomorgattatásokkal nyilvánosság elé hurczoltak titeket, másfelõl társai lettetek azoknak, a kik így jártak."));
husuperobject.biblemap.put("b58_10_34", new husuperobject(58,10,34,"Mert a foglyokkal is együtt szenvedtetek, és vagyonotok elrablását örömmel fogadtátok, tudván, hogy néktek jobb és maradandó vagyonotok van a mennyekben."));
husuperobject.biblemap.put("b58_10_35", new husuperobject(58,10,35,"Ne dobjátok el hát bizodalmatokat, melynek nagy jutalma van."));
husuperobject.biblemap.put("b58_10_36", new husuperobject(58,10,36,"Mert békességes tûrésre van szükségetek, hogy az Isten akaratát cselekedvén, elnyerjétek az ígéretet."));
husuperobject.biblemap.put("b58_10_37", new husuperobject(58,10,37,"Mert még vajmi kevés idõ, és a ki eljövendõ, eljõ és nem késik."));
husuperobject.biblemap.put("b58_10_38", new husuperobject(58,10,38,"Az igaz pedig hitbõl él. És a ki meghátrál, abban nem gyönyörködik a lelkem."));
husuperobject.biblemap.put("b58_10_39", new husuperobject(58,10,39,"De mi nem vagyunk meghátrálás [emberei], hogy elvesszünk, hanem hitéi, hogy életet nyerjünk."));
husuperobject.biblemap.put("b58_11_1", new husuperobject(58,11,1,"A hit pedig a reménylett dolgoknak valósága, és a nem látott dolgokról való meggyõzõdés."));
husuperobject.biblemap.put("b58_11_2", new husuperobject(58,11,2,"Mert ezzel szereztek [jó] bizonyságot a régebbiek."));
husuperobject.biblemap.put("b58_11_3", new husuperobject(58,11,3,"Hit által értjük meg, hogy a világ Isten beszéde által teremtetett, hogy a mi látható, a láthatatlanból állott elõ."));
husuperobject.biblemap.put("b58_11_4", new husuperobject(58,11,4,"Hit által vitt Ábel becsesebb áldozatot Istennek, mint Kain, a mi által bizonyságot nyert a felõl, hogy igaz, bizonyságot tevén az õ ajándékairól Isten, és az által még holta után is beszél."));
husuperobject.biblemap.put("b58_11_5", new husuperobject(58,11,5,"Hit által vitetett fel Énokh, hogy ne lásson halált, és nem találták meg, mert az Isten felvitte õt. Mert felvitetése elõtt bizonyságot nyert a felõl, hogy kedves volt Istennek."));
husuperobject.biblemap.put("b58_11_6", new husuperobject(58,11,6,"Hit nélkül pedig lehetetlen Istennek tetszeni; mert a ki Isten elé járul, hinnie kell, hogy õ létezik és megjutalmazza azokat, a kik õt keresik."));
husuperobject.biblemap.put("b58_11_7", new husuperobject(58,11,7,"Hit által tisztelte Istent Noé, mikor megintetvén a még nem látott dolgok felõl, házanépe megtartására bárkát készített, a mely által kárhoztatá e világot és a hitbõl való igazságnak örökösévé lett."));
husuperobject.biblemap.put("b58_11_8", new husuperobject(58,11,8,"Hit által engedelmeskedett Ábrahám, mikor elhívatott, hogy menjen ki arra a helyre, a melyet örökölendõ vala, és kiméne, nem tudván, hová megy."));
husuperobject.biblemap.put("b58_11_9", new husuperobject(58,11,9,"Hit által lakott az ígéret földén, mint idegenben, sátorokban lakván Izsákkal és Jákóbbal, ugyanazon ígéretnek örökös társaival."));
husuperobject.biblemap.put("b58_11_10", new husuperobject(58,11,10,"Mert várja vala az alapokkal bíró várost, melynek építõje és alkotója az Isten."));
husuperobject.biblemap.put("b58_11_11", new husuperobject(58,11,11,"Hit által nyert erõt Sára is az õ méhében való foganásra, és életkora ellenére szûlt, minthogy hûnek tartotta azt, a ki az ígéretet tette."));
husuperobject.biblemap.put("b58_11_12", new husuperobject(58,11,12,"Azért is egytõl, még pedig mintegy kihalttól annyian származtak, mint az égnek csillagai sokaságra nézve, és mint a tenger partja mellett a fövény, mely megszámlálhatatlan."));
husuperobject.biblemap.put("b58_11_13", new husuperobject(58,11,13,"Hitben haltak meg mindezek, nem nyerve meg az ígéreteket, hanem [csak] távolról látva és üdvözölve azokat, és vallást tevén arról, hogy idegenek és vándorok a földön."));
husuperobject.biblemap.put("b58_11_14", new husuperobject(58,11,14,"Mert a kik így szólnak, nyilván jelentik, hogy hazát keresnek."));
husuperobject.biblemap.put("b58_11_15", new husuperobject(58,11,15,"És hogyha eszökbe jutott volna az, a melybõl kijöttek, volt volna idejök a visszatérésre."));
husuperobject.biblemap.put("b58_11_16", new husuperobject(58,11,16,"Így azonban jobb után vágyódnak, tudniillik mennyei után; azért nem szégyenli õket az Isten, hogy Istenöknek neveztessék, mert készített nékik várost."));
husuperobject.biblemap.put("b58_11_17", new husuperobject(58,11,17,"Hit által áldozta meg Ábrahám Izsákot, próbára tétetvén, és az egyszülöttet vitte áldozatul, õ, ki az ígéreteket nyerte,"));
husuperobject.biblemap.put("b58_11_18", new husuperobject(58,11,18,"A kinek meg volt mondva: Izsákban neveztetik néked mag;"));
husuperobject.biblemap.put("b58_11_19", new husuperobject(58,11,19,"Úgy gondolkozván, hogy az Isten a halálból is képes feltámasztani, miért is õt példaképen visszanyerte."));
husuperobject.biblemap.put("b58_11_20", new husuperobject(58,11,20,"Hit által áldá meg a jövendõkre nézve Izsák Jákóbot és Ézsaut."));
husuperobject.biblemap.put("b58_11_21", new husuperobject(58,11,21,"Hit által áldá meg a haldokló Jákób a József fiainak mindenikét, és botja végére hajolva imádkozott."));
husuperobject.biblemap.put("b58_11_22", new husuperobject(58,11,22,"Hit által emlékezett meg élete végén József az Izráel fiainak kimenetelérõl, és az õ tetemeirõl rendelkezett."));
husuperobject.biblemap.put("b58_11_23", new husuperobject(58,11,23,"Hit által rejtegették Mózest az õ szülei születése után három hónapig, mivel látták, hogy kellemes a gyermek, és nem féltek a király parancsától."));
husuperobject.biblemap.put("b58_11_24", new husuperobject(58,11,24,"Hit által tiltakozott Mózes, midõn felnövekedett, hogy a Faraó leánya fiának mondják,"));
husuperobject.biblemap.put("b58_11_25", new husuperobject(58,11,25,"Inkább választván az Isten népével való együttnyomorgást, mint a bûnnek ideig-óráig való gyönyörûségét;"));
husuperobject.biblemap.put("b58_11_26", new husuperobject(58,11,26,"Égyiptom kincseinél nagyobb gazdagságnak tartván Krisztus gyalázatát, mert a megjutalmazásra tekintett."));
husuperobject.biblemap.put("b58_11_27", new husuperobject(58,11,27,"Hit által hagyta oda Égyiptomot, nem félvén a király haragjától; mert erõs szívû volt, mintha látta volna a láthatatlant."));
husuperobject.biblemap.put("b58_11_28", new husuperobject(58,11,28,"Hit által rendelte a páskát és a vérnek kiontását, hogy az öldöklõ ne illesse az õ elsõszülötteiket."));
husuperobject.biblemap.put("b58_11_29", new husuperobject(58,11,29,"Hit által keltek át a veres tengeren, mint valami szárazföldön, a mit megpróbálván az égyiptomiak, elnyelettek."));
husuperobject.biblemap.put("b58_11_30", new husuperobject(58,11,30,"Hit által omlottak le Jérikónak kõfalai, midõn hét napig köröskörül járták."));
husuperobject.biblemap.put("b58_11_31", new husuperobject(58,11,31,"Hit által nem veszett el Ráháb, a parázna nõ az engedetlenekkel együtt, befogadván a kémeket békességgel."));
husuperobject.biblemap.put("b58_11_32", new husuperobject(58,11,32,"És mit mondjak még? Hiszen kifogynék az idõbõl, ha szólnék Gedeonról, Bárákról, Sámsonról, Jeftérõl, Dávidról, Sámuelrõl és a prófétákról;"));
husuperobject.biblemap.put("b58_11_33", new husuperobject(58,11,33,"A kik hit által országokat gyõztek le, igazságot cselekedtek, az ígéreteket elnyerték, az oroszlánok száját betömték."));
husuperobject.biblemap.put("b58_11_34", new husuperobject(58,11,34,"Megoltották a tûznek erejét, megmenekedtek a kard élitõl, felerõsödtek a betegségbõl, erõsek lettek a háborúban, megszalasztották az idegenek táborait."));
husuperobject.biblemap.put("b58_11_35", new husuperobject(58,11,35,"Asszonyok feltámadás útján visszanyerték halottjaikat; mások kínpadra vonattak, visszautasítván a szabadulást, hogy becsesebb feltámadásban részesüljenek."));
husuperobject.biblemap.put("b58_11_36", new husuperobject(58,11,36,"Mások pedig megcsúfoltatások és megostoroztatások próbáját állották ki, sõt még bilincseket és börtönt is;"));
husuperobject.biblemap.put("b58_11_37", new husuperobject(58,11,37,"Megköveztettek, kínpróbát szenvedtek, szétfûrészeltettek, kardra hányattak, juhoknak és kecskéknek bõrében bujdostak, nélkülözve, nyomorgattatva, gyötörtetve,"));
husuperobject.biblemap.put("b58_11_38", new husuperobject(58,11,38,"A kikre nem volt méltó e világ, bujdosva pusztákon és hegyeken, meg barlangokban és a földnek hasadékaiban."));
husuperobject.biblemap.put("b58_11_39", new husuperobject(58,11,39,"És mindezek, noha hit által jó bizonyságot nyertek, nem kapták meg az ígéretet."));
husuperobject.biblemap.put("b58_11_40", new husuperobject(58,11,40,"Mivel Isten mi felõlünk valami jobbról gondoskodott, hogy nálunk nélkül tökéletességre ne jussanak."));
husuperobject.biblemap.put("b58_12_1", new husuperobject(58,12,1,"Annakokáért mi is, kiket a bizonyságoknak ily nagy fellege vesz körül, félretéve minden akadályt és a megkörnyékezõ bûnt, kitartással fussuk meg az elõttünk levõ küzdõ tért."));
husuperobject.biblemap.put("b58_12_2", new husuperobject(58,12,2,"Nézvén a hitnek fejedelmére és bevégezõjére Jézusra, a ki az elõtte levõ öröm helyett, megvetve a gyalázatot, keresztet szenvedett, s az Isten királyi székének jobbjára ült."));
husuperobject.biblemap.put("b58_12_3", new husuperobject(58,12,3,"Gondoljátok meg azért, hogy õ ily ellene való támadást szenvedett el a bûnösöktõl, hogy el ne csüggedjetek lelkeitekben elalélván."));
husuperobject.biblemap.put("b58_12_4", new husuperobject(58,12,4,"Mert még végig nem állottatok ellent, tusakodván a bûn ellen."));
husuperobject.biblemap.put("b58_12_5", new husuperobject(58,12,5,"És elfeledkeztetek-é az intésrõl, a mely néktek mint fiaknak szól: Fiam, ne vesd meg az Úrnak fenyítését, se meg ne lankadj, ha õ dorgál téged;"));
husuperobject.biblemap.put("b58_12_6", new husuperobject(58,12,6,"Mert a kit szeret az Úr, megdorgálja, megostoroz pedig mindent, a kit fiává fogad."));
husuperobject.biblemap.put("b58_12_7", new husuperobject(58,12,7,"Ha a fenyítést elszenveditek, akkor veletek úgy bánik az Isten, mint fiaival; mert melyik fiú az, a kit meg nem fenyít az apa?"));
husuperobject.biblemap.put("b58_12_8", new husuperobject(58,12,8,"Ha pedig fenyítés nélkül valók vagytok, melyben mindenek részesültek, korcsok vagytok és nem fiak."));
husuperobject.biblemap.put("b58_12_9", new husuperobject(58,12,9,"Aztán, a mi testi apáink fenyítettek minket és becsültük õket; avagy nem sokkal inkább engedelmeskedünk-é a lelkek Atyjának, és élünk!"));
husuperobject.biblemap.put("b58_12_10", new husuperobject(58,12,10,"Mert ám azok kevés ideig, tetszésök szerint fenyítettek; õ pedig javunkra, hogy szentségében részesüljünk."));
husuperobject.biblemap.put("b58_12_11", new husuperobject(58,12,11,"Bármely fenyítés ugyan jelenleg nem látszik örvendetesnek, hanem keservesnek, ámde utóbb az igazságnak békességes gyümölcsével fizet azoknak, a kik általa gyakoroltatnak."));
husuperobject.biblemap.put("b58_12_12", new husuperobject(58,12,12,"Annakokáért a lecsüggesztett kezeket és az ellankadt térdeket egyenesítsétek föl,"));
husuperobject.biblemap.put("b58_12_13", new husuperobject(58,12,13,"És lábaitokkal egyenesen járjatok, hogy a sánta el ne hajoljon, sõt inkább meggyógyuljon."));
husuperobject.biblemap.put("b58_12_14", new husuperobject(58,12,14,"Kövessétek mindenki irányában a békességet és a szentséget, a mely nélkül senki sem látja meg az Urat:"));
husuperobject.biblemap.put("b58_12_15", new husuperobject(58,12,15,"Vigyázván arra, hogy az Isten kegyelmétõl senki el ne szakadjon; nehogy a keserûségnek bármely gyökere, fölnevekedvén, megzavarjon, és ez által sokan megfertõztettessenek."));
husuperobject.biblemap.put("b58_12_16", new husuperobject(58,12,16,"Ne legyen senki parázna vagy istentelen, mint Ézsau, a ki egy ételért eladta elsõ szülöttségi jogát."));
husuperobject.biblemap.put("b58_12_17", new husuperobject(58,12,17,"Mert tudjátok, hogy azután is, mikor akarta örökölni az áldást, megvettetett; mert nem találta meg a megbánás helyét, noha könyhullatással kereste azt [az áldást]."));
husuperobject.biblemap.put("b58_12_18", new husuperobject(58,12,18,"Mert nem járultatok megtapintható hegyhez, és lángoló tûzhöz, és sûrû homályhoz, és sötétséghez, és szélvészhez,"));
husuperobject.biblemap.put("b58_12_19", new husuperobject(58,12,19,"És trombita harsogásához, és a mondásoknak szavához, melyet a kik hallottak, kérték, hogy ne intéztessék hozzájok szó;"));
husuperobject.biblemap.put("b58_12_20", new husuperobject(58,12,20,"Mert nem bírták ki, a mi parancsolva volt: Még ha oktalan állat ér is a hegyhez, megköveztessék, vagy nyillal lövettessék le;"));
husuperobject.biblemap.put("b58_12_21", new husuperobject(58,12,21,"És oly rettenetes volt a látomány, hogy Mózes is mondá: Megijedtem és remegek:"));
husuperobject.biblemap.put("b58_12_22", new husuperobject(58,12,22,"Hanem járultatok Sion hegyéhez, és az élõ Istennek városához, a mennyei Jeruzsálemhez, és az angyalok ezreihez,"));
husuperobject.biblemap.put("b58_12_23", new husuperobject(58,12,23,"Az elsõszülöttek seregéhez és egyházához, a kik be vannak írva a mennyekben, és mindenek bírájához Istenhez, és a tökéletes igazak lelkeihez,"));
husuperobject.biblemap.put("b58_12_24", new husuperobject(58,12,24,"És az újszövetség közbenjárójához Jézushoz, és a meghintésnek véréhez, mely jobbat beszél, mint az Ábel vére."));
husuperobject.biblemap.put("b58_12_25", new husuperobject(58,12,25,"Vigyázzatok, meg ne vessétek azt, a ki szól; mert ha azok meg nem menekültek, a kik a földön szólót megvetették, sokkal kevésbbé mi, ha elfordulunk attól, a ki a mennyekbõl vagyon,"));
husuperobject.biblemap.put("b58_12_26", new husuperobject(58,12,26,"Kinek szava akkor megrendítette a földet, most pedig ígéretet tesz, mondván: Még egyszer megrázom nemcsak a földet, hanem az eget is."));
husuperobject.biblemap.put("b58_12_27", new husuperobject(58,12,27,"Az a még egyszer pedig jelenti az állhatatlan dolgoknak mint teremtményeknek megváltozását, hogy a rendíthetetlen dolgok maradjanak meg."));
husuperobject.biblemap.put("b58_12_28", new husuperobject(58,12,28,"Annakokáért mozdíthatatlan országot nyervén, legyünk háládatosak, melynél fogva szolgáljunk az Istennek tetszõ módon kegyességgel és félelemmel."));
husuperobject.biblemap.put("b58_12_29", new husuperobject(58,12,29,"Mert a mi Istenünk megemésztõ tûz."));
husuperobject.biblemap.put("b58_13_1", new husuperobject(58,13,1,"Az atyafiúi szeretet maradjon meg."));
husuperobject.biblemap.put("b58_13_2", new husuperobject(58,13,2,"A vendégszeretetrõl el ne felejtkezzetek, mert ez által némelyek, tudtokon kívül, angyalokat vendégeltek meg."));
husuperobject.biblemap.put("b58_13_3", new husuperobject(58,13,3,"Emlékezzetek meg a foglyokról, mint fogolytársak, a gyötrõdõkrõl, mint a kik magatok is testben vagytok."));
husuperobject.biblemap.put("b58_13_4", new husuperobject(58,13,4,"Tisztességes minden tekintetben a házasság és a szeplõtelen házaságy; a paráznákat pedig és a házasságrontókat megítéli az Isten."));
husuperobject.biblemap.put("b58_13_5", new husuperobject(58,13,5,"Fösvénység nélkül való legyen a magatok viselete; elégedjetek meg azzal, a mitek van; mert Õ mondotta: Nem hagylak el, sem el nem távozom tõled;"));
husuperobject.biblemap.put("b58_13_6", new husuperobject(58,13,6,"Úgy hogy bízvást mondjuk: Az Úr az én segítségem, nem félek; ember mit árthat én nékem?"));
husuperobject.biblemap.put("b58_13_7", new husuperobject(58,13,7,"Emlékezzetek meg a ti elõljáróitokról, a kik szólották néktek az Isten beszédét, és figyelmezvén az õ életök végére, kövessétek hitöket."));
husuperobject.biblemap.put("b58_13_8", new husuperobject(58,13,8,"Jézus Krisztus tegnap és ma és örökké ugyanaz."));
husuperobject.biblemap.put("b58_13_9", new husuperobject(58,13,9,"Különbözõ és idegen tudományok által ne hagyjátok magatokat félrevezettetni; mert jó dolog, hogy kegyelemmel erõsíttessék meg a szív, nem ennivalókkal, a melyeknek semmi hasznát sem veszik azok, a kik azok körül járnak."));
husuperobject.biblemap.put("b58_13_10", new husuperobject(58,13,10,"Van oltárunk, a melyrõl nincs joguk enni azoknak, a kik a sátornak szolgálnak."));
husuperobject.biblemap.put("b58_13_11", new husuperobject(58,13,11,"Mert a mely állatok vérét a fõpap beviszi a szentélybe a bûnért, azoknak testét megégetik a táboron kívül."));
husuperobject.biblemap.put("b58_13_12", new husuperobject(58,13,12,"Annakokáért Jézus is, hogy megszentelje az õ tulajdon vére által a népet, a kapun kívül szenvedett."));
husuperobject.biblemap.put("b58_13_13", new husuperobject(58,13,13,"Menjünk ki tehát õ hozzá a táboron kívül, az õ gyalázatát hordozván."));
husuperobject.biblemap.put("b58_13_14", new husuperobject(58,13,14,"Mert nincsen itt maradandó városunk, hanem a jövendõt keressük."));
husuperobject.biblemap.put("b58_13_15", new husuperobject(58,13,15,"Annakokáért õ általa vigyünk dícséretnek áldozatát mindenkor Isten elé, azaz az õ nevérõl vallást tevõ ajkaknak gyümölcsét."));
husuperobject.biblemap.put("b58_13_16", new husuperobject(58,13,16,"A jótékonyságról pedig és az adakozásról el ne felejtkezzetek, mert ilyen áldozatokban gyönyörködik az Isten."));
husuperobject.biblemap.put("b58_13_17", new husuperobject(58,13,17,"Engedelmeskedjetek elõljáróitoknak és fogadjatok szót, mert õk vigyáznak lelkeitekre, mint számadók; hogy ezt örömmel míveljék és nem bánkódva, mert ez néktek nem használ."));
husuperobject.biblemap.put("b58_13_18", new husuperobject(58,13,18,"Imádkozzatok érettünk. Mert úgy vagyunk meggyõzõdve, hogy jó lelkiismeretünk van, igyekezvén mindenekben tisztességesen forgolódni."));
husuperobject.biblemap.put("b58_13_19", new husuperobject(58,13,19,"Kiváltképen pedig arra kérlek, hogy ezt cselekedjétek, hogy mihamarább visszaadhassam néktek."));
husuperobject.biblemap.put("b58_13_20", new husuperobject(58,13,20,"A békesség Istene pedig, a ki kihozta a halálból a juhoknak nagy pásztorát, örök szövetség vére által, a mi Urunkat Jézust,"));
husuperobject.biblemap.put("b58_13_21", new husuperobject(58,13,21,"Tegyen készségesekké titeket minden jóra, hogy cselekedjétek az õ akaratát, azt munkálván ti bennetek, a mi kedves õ elõtte a Jézus Krisztus által, a kinek dicsõség örökkön örökké. Ámen."));
husuperobject.biblemap.put("b58_13_22", new husuperobject(58,13,22,"Kérlek pedig titeket atyámfiai, szívleljétek meg ez intõ beszédet, hiszen röviden is írtam néktek."));
husuperobject.biblemap.put("b58_13_23", new husuperobject(58,13,23,"Legyen tudtotokra, hogy a mi atyánkfia Timótheus kiszabadult, a kivel ha csakhamar eljõ, meglátogatlak titeket."));
husuperobject.biblemap.put("b58_13_24", new husuperobject(58,13,24,"Köszöntsétek minden elõljárótokat és a szenteket mind. Köszöntenek titeket az Olaszországból valók."));
husuperobject.biblemap.put("b58_13_25", new husuperobject(58,13,25,"Kegyelem mindnyájatokkal! Ámen!"));

}

}