package hu.bible;

public class hubible47 {

public hubible47() {

putmapbible47();

}

private void putmapbible47() {

husuperobject.biblemap.put("b47_1_1", new husuperobject(47,1,1,"Pál, Jézus Krisztus apostola az Isten akaratjából, és Timótheus az atyafi, az Isten gyülekezetének, a mely Korinthusban van, mindama szentekkel egybe, a kik egész Akhájában vannak:"));
husuperobject.biblemap.put("b47_1_2", new husuperobject(47,1,2,"Kegyelem néktek és békesség Istentõl a mi Atyánktól és az Úr Jézus Krisztustól."));
husuperobject.biblemap.put("b47_1_3", new husuperobject(47,1,3,"Áldott az Isten és a mi Urunk Jézus Krisztusnak Atyja, az irgalmasságnak atyja és minden vígasztalásnak Istene;"));
husuperobject.biblemap.put("b47_1_4", new husuperobject(47,1,4,"A ki megvígasztal minket minden nyomorúságunkban, hogy mi is megvígasztalhassunk bármely nyomorúságba [esteket] azzal a vígasztalással, a mellyel Isten vígasztal minket."));
husuperobject.biblemap.put("b47_1_5", new husuperobject(47,1,5,"Mert a mint bõséggel kijutott nékünk a Krisztus szenvedéseibõl, úgy bõséges a mi vígasztalásunk is Krisztus által."));
husuperobject.biblemap.put("b47_1_6", new husuperobject(47,1,6,"De akár nyomorgattatunk, a ti vígasztalástokért és üdvösségtekért [van az], mely hathatós ugyanazon szenvedések elviselésére, a melyeket mi is szenvedünk; akár megvígasztaltatunk a ti vígasztalástokért és üdvösségtekért [van az.] És a mi reménységünk erõs felõletek."));
husuperobject.biblemap.put("b47_1_7", new husuperobject(47,1,7,"Tudván, hogy a miképen társaink vagytok a szenvedésben, azonképen a vígasztalásban is."));
husuperobject.biblemap.put("b47_1_8", new husuperobject(47,1,8,"Mert nem akarjuk, hogy ne tudjatok atyámfiai a mi nyomorúságunk felõl, a mely Ázsiában esett rajtunk, hogy felette igen, erõnk felett megterheltettünk, úgy hogy életünk felõl is kétségben valánk:"));
husuperobject.biblemap.put("b47_1_9", new husuperobject(47,1,9,"Sõt magunk is halálra szántuk magunkat, hogy ne bizakodnánk mi magunkban, hanem Istenben, a ki feltámasztja a holtakat:"));
husuperobject.biblemap.put("b47_1_10", new husuperobject(47,1,10,"A ki ilyen nagy halálból megszabadított és szabadít minket: a kiben reménykedünk, hogy ezután is meg fog szabadítani;"));
husuperobject.biblemap.put("b47_1_11", new husuperobject(47,1,11,"Velünk együtt munkálkodván ti is az érettünk való könyörgésben, hogy a sokak által nékünk adatott kegyelmi ajándék sokak által háláltassék meg mi érettünk."));
husuperobject.biblemap.put("b47_1_12", new husuperobject(47,1,12,"Mert a mi dicsekedésünk ez, lelkiismeretünk bizonysága, hogy isteni õszinteséggel és tisztasággal, nem testi bölcseséggel, hanem Isten kegyelmével forgolódtunk a világon, kiváltképen pedig ti köztetek."));
husuperobject.biblemap.put("b47_1_13", new husuperobject(47,1,13,"Mert nem egyebet írunk néktek, hanem a mit olvastok, vagy el is ismertek, sõt reménylem, hogy el is fogtok ismerni mindvégig;"));
husuperobject.biblemap.put("b47_1_14", new husuperobject(47,1,14,"A minthogy némi részben el is ismertétek rólunk, hogy dicsekvéstek vagyunk, a miképen ti is nékünk az Úr Jézus napján."));
husuperobject.biblemap.put("b47_1_15", new husuperobject(47,1,15,"És ezzel a bizodalommal akartam elõbb hozzátok menni, hogy másodízben nyerjetek kegyelmet;"));
husuperobject.biblemap.put("b47_1_16", new husuperobject(47,1,16,"És köztetek általmenni Macedóniába, és Macedóniából ismét hozzátok térni vissza, és tõletek elkísértetni Júdeába."));
husuperobject.biblemap.put("b47_1_17", new husuperobject(47,1,17,"Hát ezt akarva, vajjon könnyelmûen cselekedtem-é? vagy a mit akarok, test szerint akarom-é, hogy nálam az igen igen, és a nem nem legyen?"));
husuperobject.biblemap.put("b47_1_18", new husuperobject(47,1,18,"De hû az Isten, hogy a mi beszédünk hozzátok nem volt igen és nem."));
husuperobject.biblemap.put("b47_1_19", new husuperobject(47,1,19,"Mert az Isten Fia Jézus Krisztus, a kit köztetek mi hirdettünk, én és Silvánus és Timótheus, nem volt igen és nem, hanem [az] igen lett õ benne."));
husuperobject.biblemap.put("b47_1_20", new husuperobject(47,1,20,"Mert Istennek valamennyi igérete õ benne [lett] igenné [és] õ benne [lett] Ámenné az Isten dicsõségére mi általunk."));
husuperobject.biblemap.put("b47_1_21", new husuperobject(47,1,21,"A ki pedig minket ti veletek egybe Krisztusban megerõsít és megken minket, az Isten az;"));
husuperobject.biblemap.put("b47_1_22", new husuperobject(47,1,22,"A ki el is pecsételt minket, és a léleknek zálogát adta a mi szíveinkbe."));
husuperobject.biblemap.put("b47_1_23", new husuperobject(47,1,23,"Én pedig az Istent hívom bizonyságul az én lelkemre, hogy titeket kímélve nem mentem el eddig Korinthusba."));
husuperobject.biblemap.put("b47_1_24", new husuperobject(47,1,24,"Nem hogy uralkodnánk a ti hiteteken, hanem munkatársai vagyunk a ti örömeteknek; mert hitben állotok."));
husuperobject.biblemap.put("b47_2_1", new husuperobject(47,2,1,"Azt tettem pedig fel magamban, hogy nem megyek közétek ismét szomorúsággal."));
husuperobject.biblemap.put("b47_2_2", new husuperobject(47,2,2,"Mert ha én megszomorítlak titeket, ugyan ki az, a ki megvídámít engem, hanemha a kit én megszomorítok?"));
husuperobject.biblemap.put("b47_2_3", new husuperobject(47,2,3,"És azért írtam néktek éppen azt, hogy mikor oda megyek, meg ne szomoríttassam azok miatt, a kiknek örülnöm kellene; meg lévén gyõzõdve mindenitek felõl, hogy az én örömöm mindnyájatoké."));
husuperobject.biblemap.put("b47_2_4", new husuperobject(47,2,4,"Mert sok szorongattatás és szívbeli háborgás között írtam néktek sok könyhullatással, nem hogy megszomoríttassatok, hanem hogy megismerjétek azt a szeretetet, a mellyel kiváltképen irántatok viseltetem."));
husuperobject.biblemap.put("b47_2_5", new husuperobject(47,2,5,"Ha pedig valaki megszomorított, nem engem szomorított meg, hanem részben, hogy [azt] ne terheljem, titeket mindnyájatokat."));
husuperobject.biblemap.put("b47_2_6", new husuperobject(47,2,6,"Elég az ilyennek a többség részérõl való ilyen megbüntetése:"));
husuperobject.biblemap.put("b47_2_7", new husuperobject(47,2,7,"Annyira, hogy éppen ellenkezõleg ti inkább bocsássatok meg néki és vígasztaljátok, hogy valamiképen a felettébb való bánat meg ne eméssze az ilyet."));
husuperobject.biblemap.put("b47_2_8", new husuperobject(47,2,8,"Azért kérlek titeket, hogy tanusítsatok iránta szeretetet."));
husuperobject.biblemap.put("b47_2_9", new husuperobject(47,2,9,"Mert azért írtam is, hogy bizonyosan megtudjam felõletek, ha mindenben engedelmesek vagytok-é?"));
husuperobject.biblemap.put("b47_2_10", new husuperobject(47,2,10,"A kinek pedig megbocsáttok valamit, én is: mert ha én is megbocsátottam valamit, ha valakinek megbocsátottam, ti érettetek [cselekedtem] Krisztus színe elõtt; hogy meg ne csaljon minket a Sátán:"));
husuperobject.biblemap.put("b47_2_11", new husuperobject(47,2,11,"Mert jól ismerjük az õ szándékait."));
husuperobject.biblemap.put("b47_2_12", new husuperobject(47,2,12,"Mikor pedig Troásba mentem a Krisztus evangyélioma ügyében és kapu nyittatott nékem az Úrban, nem volt lelkemnek nyugodalma, mivelhogy nem találtam Titust, az én atyámfiát;"));
husuperobject.biblemap.put("b47_2_13", new husuperobject(47,2,13,"Hanem elbúcsúzván tõlük, elmentem Macedóniába."));
husuperobject.biblemap.put("b47_2_14", new husuperobject(47,2,14,"Hála pedig az Istennek, a ki mindenkor diadalra vezet minket a Krisztusban, és az õ ismeretének illatját minden helyen megjelenti mi általunk."));
husuperobject.biblemap.put("b47_2_15", new husuperobject(47,2,15,"Mert Krisztus jó illatja vagyunk Istennek, mind az üdvözülõk, mind az elkárhozók között;"));
husuperobject.biblemap.put("b47_2_16", new husuperobject(47,2,16,"Ezeknek halál illatja halálra; amazoknak pedig élet illatja életre. És ezekre kicsoda alkalmatos?"));
husuperobject.biblemap.put("b47_2_17", new husuperobject(47,2,17,"Mert mi nem olyanok vagyunk, mint sokan, a kik meghamisítják az Isten ígéjét; hanem tisztán, sõt szinte Istenbõl szólunk az Isten elõtt a Krisztusban."));
husuperobject.biblemap.put("b47_3_1", new husuperobject(47,3,1,"Elkezdjük-é ismét ajánlgatni magunkat? Vagy talán szükségünk van, mint némelyeknek, ajánló levelekre hozzátok, avagy tõletek?"));
husuperobject.biblemap.put("b47_3_2", new husuperobject(47,3,2,"A mi levelünk ti vagytok, beírva a mi szívünkbe, a melyet ismer és olvas minden ember;"));
husuperobject.biblemap.put("b47_3_3", new husuperobject(47,3,3,"A kik felõl nyilvánvaló, hogy Krisztusnak a mi szolgálatunk által szerzett levele vagytok, nem tentával, hanem az élõ Isten Lelkével írva; nem kõtáblákra, hanem a szívnek hústábláira."));
husuperobject.biblemap.put("b47_3_4", new husuperobject(47,3,4,"Ilyen bizodalmunk pedig Isten iránt a Krisztus által van."));
husuperobject.biblemap.put("b47_3_5", new husuperobject(47,3,5,"Nem mintha magunktól volnánk alkalmatosak valamit gondolni, úgy mint magunkból; ellenkezõleg a mi alkalmatos voltunk az Istentõl van:"));
husuperobject.biblemap.put("b47_3_6", new husuperobject(47,3,6,"A ki alkalmatosokká tett minket arra, hogy új szövetség szolgái []legyünk, nem betûé, hanem léleké; mert a betû megöl, a lélek pedig megelevenít."));
husuperobject.biblemap.put("b47_3_7", new husuperobject(47,3,7,"Ha pedig a halálnak betûkkel kövekbe vésett szolgálata dicsõséges vala, úgyhogy Izráel fiai nem is nézhettek Mózes orczájára arczának elmúló dicsõsége miatt:"));
husuperobject.biblemap.put("b47_3_8", new husuperobject(47,3,8,"Hogyne volna még inkább dicsõséges a léleknek szolgálata?"));
husuperobject.biblemap.put("b47_3_9", new husuperobject(47,3,9,"Mert ha a kárhoztatás szolgálata dicsõséges, mennyivel inkább dicsõséges az igazság szolgálata?"));
husuperobject.biblemap.put("b47_3_10", new husuperobject(47,3,10,"Sõt a dicsõített nem is dicsõséges ebben a részben az õt meghaladó dicsõség miatt."));
husuperobject.biblemap.put("b47_3_11", new husuperobject(47,3,11,"Mert ha dicsõséges az elmulandó, sokkal inkább dicsõséges, a mi megmarad."));
husuperobject.biblemap.put("b47_3_12", new husuperobject(47,3,12,"Azért ilyen reménységben nagy nyiltsággal szólunk;"));
husuperobject.biblemap.put("b47_3_13", new husuperobject(47,3,13,"És nem, miként Mózes, [a ki] leplet borított az orczájára, hogy ne lássák Izráel fiai az elmulandónak végét."));
husuperobject.biblemap.put("b47_3_14", new husuperobject(47,3,14,"De megtompultak az õ elméik. Mert ugyanaz a lepel mind e mai napig ott van az ó szövetség olvasásánál felfedetlenül, mivelhogy a Krisztusban tûnik el;"));
husuperobject.biblemap.put("b47_3_15", new husuperobject(47,3,15,"Sõt mind máig, a mikor csak olvassák Mózest, lepel borul az õ szívökre."));
husuperobject.biblemap.put("b47_3_16", new husuperobject(47,3,16,"Mikor pedig megtér az Úrhoz, lehull a lepel."));
husuperobject.biblemap.put("b47_3_17", new husuperobject(47,3,17,"Az Úr pedig a Lélek; és a hol az Úrnak Lelke, ott a szabadság."));
husuperobject.biblemap.put("b47_3_18", new husuperobject(47,3,18,"Mi pedig az Úrnak dicsõségét mindnyájan fedetlen arczczal szemlélvén, ugyanazon ábrázatra elváltozunk, dicsõségrõl dicsõségre, úgy mint az Úrnak Lelkétõl."));
husuperobject.biblemap.put("b47_4_1", new husuperobject(47,4,1,"Annakokáért, mivelhogy ilyen szolgálatban vagyunk, a mint a kegyelmet nyertük, nem csüggedünk el;"));
husuperobject.biblemap.put("b47_4_2", new husuperobject(47,4,2,"Hanem lemondtunk a szégyen takargatásáról, mint a kik nem járunk ravaszságban, és nem is hamisítjuk meg az Isten ígéjét, de a nyilvánvaló igazsággal kelletjük magunkat minden ember lelkiismeretének az Isten elõtt."));
husuperobject.biblemap.put("b47_4_3", new husuperobject(47,4,3,"Ha mégis leplezett a mi evangyéliomunk, azoknak leplezett, a kik elvesznek:"));
husuperobject.biblemap.put("b47_4_4", new husuperobject(47,4,4,"A kikben e világ Istene megvakította a hitetlenek elméit, hogy ne lássák a Krisztus dicsõséges evangyéliomának világosságát, a ki az Isten képe."));
husuperobject.biblemap.put("b47_4_5", new husuperobject(47,4,5,"Mert nem magunkat prédikáljuk, hanem az Úr Jézus Krisztust; magunkat pedig, mint a ti szolgáitokat, a Jézusért."));
husuperobject.biblemap.put("b47_4_6", new husuperobject(47,4,6,"Mert az Isten, a ki szólt: setétségbõl világosság ragyogjon, õ gyújtott világosságot a mi szívünkben az Isten dicsõsége ismeretének a Jézus Krisztus arczán való világoltatása végett."));
husuperobject.biblemap.put("b47_4_7", new husuperobject(47,4,7,"Ez a kincsünk pedig cserépedényekben van, hogy amaz erõnek nagy volta Istené legyen, és nem magunktól való."));
husuperobject.biblemap.put("b47_4_8", new husuperobject(47,4,8,"Mindenütt nyomorgattatunk, de meg nem szoríttatunk; kétségeskedünk, de nem esünk kétségbe;"));
husuperobject.biblemap.put("b47_4_9", new husuperobject(47,4,9,"Üldöztetünk, de el nem hagyatunk; tiportatunk, de el nem veszünk;"));
husuperobject.biblemap.put("b47_4_10", new husuperobject(47,4,10,"Mindenkor testünkben hordozzuk az Úr Jézus halálát, hogy a Jézusnak élete is látható legyen a mi testünkben."));
husuperobject.biblemap.put("b47_4_11", new husuperobject(47,4,11,"Mert mi, a kik élünk, mindenkor halálra adatunk a Jézusért, hogy a Jézus élete is látható legyen a mi halandó testünkben."));
husuperobject.biblemap.put("b47_4_12", new husuperobject(47,4,12,"Azért a halál mi bennünk munkálkodik, az élet pedig ti bennetek."));
husuperobject.biblemap.put("b47_4_13", new husuperobject(47,4,13,"Mivelhogy pedig a hitnek mi bennünk is ugyanaz a lelke van meg, a mint írva van: Hittem és azért szóltam; hiszünk mi is, és azért szólunk;"));
husuperobject.biblemap.put("b47_4_14", new husuperobject(47,4,14,"Tudván, hogy a ki feltámasztotta az Úr Jézust, Jézus által minket is feltámaszt, és veletek együtt elõállít."));
husuperobject.biblemap.put("b47_4_15", new husuperobject(47,4,15,"Mert minden ti érettetek [van,] hogy a kegyelem sokasodva sokak által a hálaadást bõségessé tegye az Isten dicsõségére."));
husuperobject.biblemap.put("b47_4_16", new husuperobject(47,4,16,"Azért nem csüggedünk; sõt ha a mi külsõ emberünk megromol is, a belsõ mindazáltal napról-napra újul."));
husuperobject.biblemap.put("b47_4_17", new husuperobject(47,4,17,"Mert a mi pillanatnyi könnyû szenvedésünk igen-igen nagy örök dicsõséget szerez nékünk;"));
husuperobject.biblemap.put("b47_4_18", new husuperobject(47,4,18,"Mivelhogy nem a láthatókra nézünk, hanem a láthatatlanokra; mert a láthatók ideig valók, a láthatatlanok pedig örökkévalók."));
husuperobject.biblemap.put("b47_5_1", new husuperobject(47,5,1,"Mert tudjuk, hogy ha e mi földi sátorházunk elbomol, épületünk van Istentõl, nem kézzel csinált, örökké való házunk a mennyben."));
husuperobject.biblemap.put("b47_5_2", new husuperobject(47,5,2,"Azért is sóhajtozunk ebben, óhajtván felöltözni erre a mi mennyei hajlékunkat;"));
husuperobject.biblemap.put("b47_5_3", new husuperobject(47,5,3,"Ha ugyan felöltözötten is mezíteleneknek nem találtatunk!"));
husuperobject.biblemap.put("b47_5_4", new husuperobject(47,5,4,"Mert a kik e sátorban vagyunk is, sóhajtozunk megterheltetvén; mivelhogy nem kívánunk levetkõztetni, hanem felöltöztetni, hogy a mi halandó, elnyelje azt az élet."));
husuperobject.biblemap.put("b47_5_5", new husuperobject(47,5,5,"A ki pedig minket erre elkészített, az Isten [az,] a ki a Lélek zálogát is adta minékünk."));
husuperobject.biblemap.put("b47_5_6", new husuperobject(47,5,6,"Azért mivelhogy mindenkor bízunk, és tudjuk, hogy e testben lakván, távol vagyunk az Úrtól."));
husuperobject.biblemap.put("b47_5_7", new husuperobject(47,5,7,"(Mert hitben járunk, nem látásban );"));
husuperobject.biblemap.put("b47_5_8", new husuperobject(47,5,8,"Bizodalmunk pedig van, azért inkább szeretnénk kiköltözni e testbõl, és elköltözni az Úrhoz."));
husuperobject.biblemap.put("b47_5_9", new husuperobject(47,5,9,"Azért igyekezünk is, hogy akár itt lakunk, akár elköltözünk, néki kedvesek legyünk."));
husuperobject.biblemap.put("b47_5_10", new husuperobject(47,5,10,"Mert nékünk mindnyájunknak meg kell jelennünk a Krisztus ítélõszéke elõtt, hogy kiki megjutalmaztassék a szerint, a miket e testben cselekedett, vagy jót, vagy gonoszt."));
husuperobject.biblemap.put("b47_5_11", new husuperobject(47,5,11,"Ismervén tehát az Úrnak félelmét, embereket térítünk, Isten elõtt pedig nyilván vagyunk; reménylem azonban, hogy a ti lelkiesméretetek elõtt is nyilván vagyunk."));
husuperobject.biblemap.put("b47_5_12", new husuperobject(47,5,12,"Mert nem ajánljuk ismét magunkat néktek, hanem alkalmat adunk ti néktek a velünk való dicsekedésre, hogy legyen mit felelnetek a színbõl és nem szívbõl dicsekedõknek."));
husuperobject.biblemap.put("b47_5_13", new husuperobject(47,5,13,"Ha azért bolondok vagyunk, Istenért; ha eszesek vagyunk, érettetek van [az.]"));
husuperobject.biblemap.put("b47_5_14", new husuperobject(47,5,14,"Mert a Krisztusnak szerelme szorongat minket,"));
husuperobject.biblemap.put("b47_5_15", new husuperobject(47,5,15,"Úgy vélekedvén, hogy ha egy meghalt mindenkiért, tehát mindazok meghaltak; és azért halt meg mindenkiért, hogy a kik élnek, ezután ne magoknak éljenek, hanem annak, a ki érettök meghalt és feltámasztatott."));
husuperobject.biblemap.put("b47_5_16", new husuperobject(47,5,16,"Azért mi ezentúl senkit sem ismerünk test szerint; sõt ha ismertük is Krisztust test szerint, de már többé nem ismerjük."));
husuperobject.biblemap.put("b47_5_17", new husuperobject(47,5,17,"Azért ha valaki Krisztusban van, új teremtés [az]; a régiek elmúltak, ímé, újjá lett minden."));
husuperobject.biblemap.put("b47_5_18", new husuperobject(47,5,18,"Mindez pedig Istentõl van, a ki minket magával megbékéltetett a Jézus Krisztus által, és a ki nékünk adta a békéltetés szolgálatát;"));
husuperobject.biblemap.put("b47_5_19", new husuperobject(47,5,19,"Minthogy az Isten volt az, a ki Krisztusban megbékéltette magával a világot, nem tulajdonítván nékik az õ bûneiket, és reánk bízta a békéltetésnek ígéjét."));
husuperobject.biblemap.put("b47_5_20", new husuperobject(47,5,20,"Krisztusért járván tehát követségben, mintha Isten kérne mi általunk: Krisztusért kérünk, béküljetek meg az Istennel."));
husuperobject.biblemap.put("b47_5_21", new husuperobject(47,5,21,"Mert azt, a ki bûnt nem ismert, bûnné tette értünk, hogy mi Isten igazsága legyünk õ benne."));
husuperobject.biblemap.put("b47_6_1", new husuperobject(47,6,1,"Mint együttmunkálkodók intünk is, hogy hiába ne vettétek légyen az Isten kegyelmét."));
husuperobject.biblemap.put("b47_6_2", new husuperobject(47,6,2,"Mert õ mondja: Kellemetes idõben meghallgattalak, és az üdvösség napján megsegítettelek. Ímé itt a kellemetes idõ, ímé itt az üdvösség napja."));
husuperobject.biblemap.put("b47_6_3", new husuperobject(47,6,3,"Senkit semmiben meg ne botránkoztassunk, hogy a szolgálatunk ne szidalmaztassék."));
husuperobject.biblemap.put("b47_6_4", new husuperobject(47,6,4,"Hanem ajánljuk magunkat mindenben, mint Isten szolgái; sok tûrésben, nyomorúságban, szükségben, szorongattatásban."));
husuperobject.biblemap.put("b47_6_5", new husuperobject(47,6,5,"Vereségben, tömlöczben, háborúságban, küzködésben, virrasztásban, bõjtölésben."));
husuperobject.biblemap.put("b47_6_6", new husuperobject(47,6,6,"Tisztaságban, tudományban, hosszútûrésben, szívességben, Szent Lélekben, tettetés nélkül való szeretetben,"));
husuperobject.biblemap.put("b47_6_7", new husuperobject(47,6,7,"Igazmondásban, Isten erejében; az igazságnak jobb és bal felõl való fegyvereivel;"));
husuperobject.biblemap.put("b47_6_8", new husuperobject(47,6,8,"Dicsõség és gyalázat által, rossz és jó hír által; mint hitetõk, és igazak;"));
husuperobject.biblemap.put("b47_6_9", new husuperobject(47,6,9,"Mint ismeretlenek, és mégis ismeretesek; mint megholtak, és ím élõk; mint ostorozottak, és meg nem ölöttek;"));
husuperobject.biblemap.put("b47_6_10", new husuperobject(47,6,10,"Mint bánkódók, noha mindig örvendezõk; mint szegények, de sokakat gazdagítók; mint semmi nélkül valók, és mindennel bírók."));
husuperobject.biblemap.put("b47_6_11", new husuperobject(47,6,11,"A mi szánk megnyílt ti néktek, korinthusiak, a mi szívünk kitárult."));
husuperobject.biblemap.put("b47_6_12", new husuperobject(47,6,12,"Nem mi bennünk vagytok szorosságban, hanem szorosságban vagytok a ti szívetekben."));
husuperobject.biblemap.put("b47_6_13", new husuperobject(47,6,13,"Viszonzásul (mint gyermekeimnek szólok) tárjátok ki ti is szíveteket."));
husuperobject.biblemap.put("b47_6_14", new husuperobject(47,6,14,"Ne legyetek hitetlenekkel felemás igában; mert mi szövetsége van igazságnak és hamisságnak? vagy mi közössége a világosságnak a sötétséggel?"));
husuperobject.biblemap.put("b47_6_15", new husuperobject(47,6,15,"És mi egyezsége Krisztusnak Béliállal? vagy mi köze hívõnek hitetlenhez?"));
husuperobject.biblemap.put("b47_6_16", new husuperobject(47,6,16,"Vagy mi egyezése Isten templomának bálványokkal? Mert ti az élõ Istennek temploma vagytok, a mint az Isten mondotta: Lakozom bennök és közöttük járok; és leszek nékik Istenök, és õk én népem lesznek."));
husuperobject.biblemap.put("b47_6_17", new husuperobject(47,6,17,"Annakokáért menjetek ki közülök, és szakadjatok el, azt mondja az Úr, és tisztátalant ne illessetek; és én magamhoz fogadlak titeket,"));
husuperobject.biblemap.put("b47_6_18", new husuperobject(47,6,18,"És leszek néktek Atyátok, és ti lesztek fiaimmá, és leányaimmá, azt mondja a mindenható Úr."));
husuperobject.biblemap.put("b47_7_1", new husuperobject(47,7,1,"Mivelhogy azért ilyen ígéreteink vannak, szeretteim, tisztítsuk meg magunkat minden testi és lelki tisztátalanságtól, Isten félelmében vivén véghez a mi megszentelésünket."));
husuperobject.biblemap.put("b47_7_2", new husuperobject(47,7,2,"Fogadjatok be minket; senkit meg nem bántottunk, senkit meg nem rontottunk, senkit meg nem csaltunk."));
husuperobject.biblemap.put("b47_7_3", new husuperobject(47,7,3,"Nem vádképen mondom; hisz elõbb mondottam, hogy szívünkben vagytok, hogy együtt haljunk, együtt éljünk."));
husuperobject.biblemap.put("b47_7_4", new husuperobject(47,7,4,"Nagy az én bizodalmam hozzátok, nagy az én dicsekvésem felõletek; telve vagyok vígasztalódással, felettébb való az én örömem minden mi nyomorúságunk mellett."));
husuperobject.biblemap.put("b47_7_5", new husuperobject(47,7,5,"Mert mikor Macedóniába jöttünk, sem volt semmi nyugodalma a mi testünknek, sõt mindenképen nyomorogtunk; kívül harcz, belõl félelem."));
husuperobject.biblemap.put("b47_7_6", new husuperobject(47,7,6,"De az Isten, a megalázottak vígasztalója, minket is megvígasztalt Titus megjöttével."));
husuperobject.biblemap.put("b47_7_7", new husuperobject(47,7,7,"Sõt nem megjöttével csupán, hanem azzal a vígasztalással is, a melylyel ti vígasztaltátok meg, hírül hozván nékünk a ti kivánkozástokat, a ti kesergésteket, a ti hozzám való ragaszkodástokat; úgyhogy én mégjobban örvendeztem."));
husuperobject.biblemap.put("b47_7_8", new husuperobject(47,7,8,"Hát ha megszomorítottalak is titeket azzal a levéllel, nem bánom, noha bántam; mert látom, hogy az a levél, ha ideig-óráig is, megszomorított titeket."));
husuperobject.biblemap.put("b47_7_9", new husuperobject(47,7,9,"Most örülök, nem azért, hogy megszomorodtatok, hanem hogy megtérésre szomorodtatok meg. Mert Isten szerint szomorodtatok meg, hogy miattunk semmiben kárt ne valljatok."));
husuperobject.biblemap.put("b47_7_10", new husuperobject(47,7,10,"Mert az Isten szerint való szomorúság üdvösségre való megbánhatatlan megtérést szerez; a világ szerint való szomorúság pedig halált szerez."));
husuperobject.biblemap.put("b47_7_11", new husuperobject(47,7,11,"Mert ímé ez a ti Isten szerint való megszomorodástok milyen nagy buzgóságot keltett ti bennetek, sõt védekezést, sõt bosszankodást, sõt félelmet, sõt kívánkozást, sõt buzgóságot, sõt bosszúállást. Mindenképen bebizonyítottátok, hogy tiszták vagytok e dologban."));
husuperobject.biblemap.put("b47_7_12", new husuperobject(47,7,12,"Ha tehát írtam is néktek, nem a sértõ miatt, sem a sértett miatt; hanem hogy nyilvánvaló legyen nálatok a mi irántatok való buzgóságunk Isten elõtt."));
husuperobject.biblemap.put("b47_7_13", new husuperobject(47,7,13,"Annakokáért megvígasztalódtunk a ti vígasztalástokon; de sokkal inkább örültünk a Titus örömén, hogy az õ lelkét ti mindnyájan megnyugtattátok:"));
husuperobject.biblemap.put("b47_7_14", new husuperobject(47,7,14,"Mert ha dicsekedtem valamit néki felõletek, nem maradtam szégyenben; de a mint ti néktek mindent igazán szólottam, azonképen a mi Titus elõtt való dicsekvésünk is igazsággá lett."));
husuperobject.biblemap.put("b47_7_15", new husuperobject(47,7,15,"És õ még jobb szívvel van irántatok, visszaemlékezvén mindnyájatoknak engedelmességére, hogy félelemmel és rettegéssel fogadtátok õt."));
husuperobject.biblemap.put("b47_7_16", new husuperobject(47,7,16,"Örülök, hogy mindenképen bízhatom bennetek."));
husuperobject.biblemap.put("b47_8_1", new husuperobject(47,8,1,"Tudtotokra adjuk pedig, atyámfiai, Istennek azt a kegyelmét, a melyet Macedónia gyülekezeteivel közlött."));
husuperobject.biblemap.put("b47_8_2", new husuperobject(47,8,2,"Hogy a nyomorúság sok próbái közt [is] bõséges az õ örömük és igen nagy szegénységük jószívûségük gazdagságává növekedett."));
husuperobject.biblemap.put("b47_8_3", new husuperobject(47,8,3,"Mert, bizonyság vagyok rá, erejük szerint, sõt erejük felett is adakoznak,"));
husuperobject.biblemap.put("b47_8_4", new husuperobject(47,8,4,"Sok könyörgéssel kérvén minket, hogy a szentek iránt való szolgálat jótéteményébe és közösségébe fogadjuk be õket."));
husuperobject.biblemap.put("b47_8_5", new husuperobject(47,8,5,"És nem a miképen reméltük, hanem önmagukat adták elõször az Úrnak, és nekünk [is] az Isten akaratjából."));
husuperobject.biblemap.put("b47_8_6", new husuperobject(47,8,6,"Hogy kérnünk kellett Titust, hogy a miképen elkezdette, azonképen végezze is be nálatok ezt a jótéteményt is."));
husuperobject.biblemap.put("b47_8_7", new husuperobject(47,8,7,"Azért, miképen mindenben bõvölködtök, hitben, beszédben, ismeretben és minden buzgóságban és hozzánk való szeretetben, úgy e jótéteményben is bõvölködjetek."));
husuperobject.biblemap.put("b47_8_8", new husuperobject(47,8,8,"Nem parancsképen mondom, hanem hogy a mások buzgósága által a ti szeretetetek valódiságát is kipróbáljam."));
husuperobject.biblemap.put("b47_8_9", new husuperobject(47,8,9,"Mert ismeritek a mi Urunk Jézus Krisztusnak jótéteményét, hogy gazdag lévén, szegénnyé lett érettetek, hogy ti az õ szegénysége által meggazdagodjatok."));
husuperobject.biblemap.put("b47_8_10", new husuperobject(47,8,10,"Tanácsot is adok e dologban; mert hasznos az néktek, a kik nemcsak a cselekvést, hanem az akarást is elkezdtétek tavaly óta."));
husuperobject.biblemap.put("b47_8_11", new husuperobject(47,8,11,"Most hát a cselekvést is vigyétek végbe; hogy a miképen az akarás készsége, azonképen a végrehajtás is ahhoz képest [legyen,] a mitek van."));
husuperobject.biblemap.put("b47_8_12", new husuperobject(47,8,12,"Mert ha a készség megvan, a szerint kedves az, a mije kinek-kinek van, [és] nem a szerint, a mije nincs."));
husuperobject.biblemap.put("b47_8_13", new husuperobject(47,8,13,"Mert nem úgy, hogy másoknak könnyebbségük, néktek pedig nyomorúságtok [legyen,] hanem egyenlõség szerint; e mostani idõben a ti bõségtek [pótolja] amazoknak fogyatkozását;"));
husuperobject.biblemap.put("b47_8_14", new husuperobject(47,8,14,"Hogy amazoknak bõsége is pótolhassa a ti fogyatkozástokat, hogy [így] egyenlõség legyen;"));
husuperobject.biblemap.put("b47_8_15", new husuperobject(47,8,15,"A mint megvan írva: a ki sokat [szedett,] nem volt többje; és a ki keveset, nem volt kevesebbje."));
husuperobject.biblemap.put("b47_8_16", new husuperobject(47,8,16,"Hála pedig az Istennek, ki ugyanazt a buzgóságot oltotta értetek a Titus szívébe."));
husuperobject.biblemap.put("b47_8_17", new husuperobject(47,8,17,"Mivelhogy intésünket ugyan elfogadta, de nagy buzgóságában önként ment hozzátok."));
husuperobject.biblemap.put("b47_8_18", new husuperobject(47,8,18,"Elküldöttük pedig vele együtt amaz atyafit is, a ki az összes gyülekezetekben dícséretes az evangyéliomért;"));
husuperobject.biblemap.put("b47_8_19", new husuperobject(47,8,19,"Nemcsak pedig, hanem a gyülekezetek útitársunknak is megválaszták ebben a jó ügyben, a melyet mi szolgálunk magának az Úrnak dicsõségére és a ti készségetekre;"));
husuperobject.biblemap.put("b47_8_20", new husuperobject(47,8,20,"Óvakodván, hogy senki se ócsárolhasson minket a mi szolgálatunk által való bõséges jótétemény miatt;"));
husuperobject.biblemap.put("b47_8_21", new husuperobject(47,8,21,"Mert gondunk van a tisztességre nemcsak az Úr elõtt, hanem az emberek elõtt is."));
husuperobject.biblemap.put("b47_8_22", new husuperobject(47,8,22,"Sõt elküldöttük velök a mi atyánkfiát is, a kinek buzgó voltát sok dologban sokszor kipróbáltuk, most pedig még sokkal buzgóbb, irántatok való nagy bizodalmánál fogva."));
husuperobject.biblemap.put("b47_8_23", new husuperobject(47,8,23,"Akár Titusról [van szó,] õ az én társam és ti köztetek segítségem; akár a mi atyánkfiai felõl, õk a gyülekezetek követei, Krisztus dicsõsége:"));
husuperobject.biblemap.put("b47_8_24", new husuperobject(47,8,24,"Adjátok azért szereteteteknek és felõletek való dicsekvésünknek, bizonyságát irántuk a gyülekezetek elõtt is."));
husuperobject.biblemap.put("b47_9_1", new husuperobject(47,9,1,"A szentek iránt való szolgálatról felesleges is néktek írnom."));
husuperobject.biblemap.put("b47_9_2", new husuperobject(47,9,2,"Hiszen ismerem a ti készségteket a melylyel dicsekszem felõletek a macedónoknak, hogy Akhája kész a mult esztendõ óta; és a ti buzgóságtok, sokakat magával ragadt."));
husuperobject.biblemap.put("b47_9_3", new husuperobject(47,9,3,"Mindamellett elküldöttem az atyafiakat, hogy a mi felõletek való dicsekedésünk ebben a részben hiábavaló ne legyen; hogy, a mint mondám, készen legyetek."));
husuperobject.biblemap.put("b47_9_4", new husuperobject(47,9,4,"Hogy aztán, ha a macedónok velem együtt odajutnak és titeket készületlenül találnak, valamiképen szégyent ne valljunk mi, hogy ne mondjam ti, ebben a dologban."));
husuperobject.biblemap.put("b47_9_5", new husuperobject(47,9,5,"Szükségesnek véltem azért utasítani az atyafiakat, hogy elõre menjenek el hozzátok, és készítsék el elõre a ti elõre megígért adományotokat, hogy az úgy legyen készen, mint adomány, és nem mint ragadomány."));
husuperobject.biblemap.put("b47_9_6", new husuperobject(47,9,6,"Azt [mondom] pedig: A ki szûken vet, szûken is arat; és a ki bõven vet, bõven is arat."));
husuperobject.biblemap.put("b47_9_7", new husuperobject(47,9,7,"Kiki a mint eltökélte szívében, nem szomorúságból, vagy kénytelenségbõl; mert a jókedvû adakozót szereti az Isten."));
husuperobject.biblemap.put("b47_9_8", new husuperobject(47,9,8,"Az Isten pedig hatalmas arra, hogy rátok áraszsza minden kegyelmét; hogy mindenben, mindenkor teljes elégségtek lévén, minden jótéteményre bõségben legyetek,"));
husuperobject.biblemap.put("b47_9_9", new husuperobject(47,9,9,"A mint meg van írva: Szórt, adott a szegényeknek; az õ igazsága örökké megmarad."));
husuperobject.biblemap.put("b47_9_10", new husuperobject(47,9,10,"A ki pedig magot ád a magvetõnek és kenyeret eleségül, ád és megsokasítja a ti vetésteket és megnöveli a ti igazságtoknak gyümölcsét,"));
husuperobject.biblemap.put("b47_9_11", new husuperobject(47,9,11,"Hogy mindenben meggazdagodjatok a teljes jószívûségre, a mely általunk hálaadást szerez az Istennek."));
husuperobject.biblemap.put("b47_9_12", new husuperobject(47,9,12,"Mert e tisztnek szolgálata nemcsak a szenteknek szükségét elégíti ki, hanem sok hálaadással bõséges az Isten elõtt;"));
husuperobject.biblemap.put("b47_9_13", new husuperobject(47,9,13,"A mennyiben e szolgálatnak próbája által dicsõítik az Istent a ti Krisztus evangyéliomát valló engedelmességtekért, és a ti hozzájuk és mindenekhez való adakozó jószívûségtekért."));
husuperobject.biblemap.put("b47_9_14", new husuperobject(47,9,14,"Mikor érettetek könyörögve õk is vágyakoznak utánatok az Istennek rajtatok való bõséges kegyelme miatt."));
husuperobject.biblemap.put("b47_9_15", new husuperobject(47,9,15,"Az Istennek pedig [legyen] hála az õ kimondhatatlan ajándékáért."));
husuperobject.biblemap.put("b47_10_1", new husuperobject(47,10,1,"Magam pedig, én Pál, kérlek titeket a Krisztus szelídségére és engedelmességére, a ki szemtõl szemben ugyan alázatos vagyok közöttetek, de távol bátor vagyok irántatok;"));
husuperobject.biblemap.put("b47_10_2", new husuperobject(47,10,2,"Kérlek pedig, hogy a mikor jelen leszek, ne kelljen bátornak lennem ama bizodalomnál fogva, a melylyel úgy gondolom bátor lehetek némelyekkel szemben, a kik úgy gondolkodnak felõlünk, mintha mi test szerint élnénk."));
husuperobject.biblemap.put("b47_10_3", new husuperobject(47,10,3,"Mert noha testben élünk, de nem test szerint vitézkedünk."));
husuperobject.biblemap.put("b47_10_4", new husuperobject(47,10,4,"Mert a mi vitézkedésünk fegyverei nem testiek, hanem erõsek az Istennek, erõsségek lerontására;"));
husuperobject.biblemap.put("b47_10_5", new husuperobject(47,10,5,"Lerontván okoskodásokat és minden magaslatot, a mely Isten ismerete ellen emeltetett, és foglyul ejtvén minden gondolatot, hogy engedelmeskedjék a Krisztusnak;"));
husuperobject.biblemap.put("b47_10_6", new husuperobject(47,10,6,"És készen állván megbüntetni minden engedetlenséget, mihelyst teljessé lesz a ti engedelmességtek."));
husuperobject.biblemap.put("b47_10_7", new husuperobject(47,10,7,"A szem elõtt valókra néztek? Ha valaki azt hiszi magáról, hogy õ a Krisztusé, viszont azt is gondolja meg önmagában, hogy a mint õ maga a Krisztusé, azonképen mi is a Krisztuséi [vagyunk.]"));
husuperobject.biblemap.put("b47_10_8", new husuperobject(47,10,8,"Mert ha még egy kissé felettébb dicsekedem is a mi hatalmunkkal, a melyet az Úr a ti építéstekre és nem megrontásotokra adott, én nem vallok szégyent;"));
husuperobject.biblemap.put("b47_10_9", new husuperobject(47,10,9,"Hogy ne láttassam, mintha csak ijesztgetnélek a leveleim által."));
husuperobject.biblemap.put("b47_10_10", new husuperobject(47,10,10,"Mert, úgy mondják, a levelei ugyan súlyosak és kemények; de a maga jelenvolta erõtelen, és beszéde silány."));
husuperobject.biblemap.put("b47_10_11", new husuperobject(47,10,11,"Gondolja meg azt, a ki ilyen, hogy a milyenek vagyunk távol, a levelek által való beszédben, éppen olyanok [leszünk,] ha megjelenünk, cselekedetben is."));
husuperobject.biblemap.put("b47_10_12", new husuperobject(47,10,12,"Mert nem merjük magunkat azokhoz számítani, vagy hasonlítani, a kik magukat ajánlják; de azok magukat magukhoz mérvén és magukhoz hasonlítván magukat, nem okosan cselekesznek."));
husuperobject.biblemap.put("b47_10_13", new husuperobject(47,10,13,"De mi nem dicsekszünk mértéktelenül, hanem ama mérõzsinór mértéke szerint, a melyet Isten adott nékünk mértékül, hogy hozzátok is elérjünk."));
husuperobject.biblemap.put("b47_10_14", new husuperobject(47,10,14,"Mert nem feszítjük túl magunkat, mintha nem értünk volna el hozzátok; hiszen hozzátok is eljutottunk a Krisztus evangyéliomával."));
husuperobject.biblemap.put("b47_10_15", new husuperobject(47,10,15,"A kik nem dicsekeszünk mértéktelenül mások munkájával, de reméljük, hogy hitetek megnõttével nagyokká leszünk köztetek a mi mérõzsinórunk szerint bõségesen."));
husuperobject.biblemap.put("b47_10_16", new husuperobject(47,10,16,"Hogy rajtatok túl is hirdessük az evangyéliomot, nem dicsekedvén más mértéke szerint a készszel."));
husuperobject.biblemap.put("b47_10_17", new husuperobject(47,10,17,"A ki pedig dicsekszik, az Úrban dicsekedjék."));
husuperobject.biblemap.put("b47_10_18", new husuperobject(47,10,18,"Mert nem az a kipróbált, a ki magát ajánlja, hanem a kit az Úr ajánl."));
husuperobject.biblemap.put("b47_11_1", new husuperobject(47,11,1,"Vajha elszenvednétek tõlem egy kevés balgatagságot! Sõt szenvedjetek el engem is."));
husuperobject.biblemap.put("b47_11_2", new husuperobject(47,11,2,"Mert isteni buzgósággal buzgok értetek; hisz eljegyeztelek titeket egy férfiúnak, hogy mint szeplõtlen szûzet állítsalak a Krisztus elé."));
husuperobject.biblemap.put("b47_11_3", new husuperobject(47,11,3,"Félek azonban, hogy a miként a kígyó a maga álnokságával megcsalta Évát, akként a ti gondolataitok is megrontatnak [és eltávolodnak] a Krisztus iránt való egyenességtõl."));
husuperobject.biblemap.put("b47_11_4", new husuperobject(47,11,4,"Mert hogyha az, a ki jõ, más Jézust prédikál, a kit nem prédikáltunk, vagy más lelket vesztek, a mit nem vettetek, vagy más evangyéliomot, a mit be nem fogadtatok, szépen eltûrnétek."));
husuperobject.biblemap.put("b47_11_5", new husuperobject(47,11,5,"Mert én azt gondolom, hogy semmiben sem vagyok alábbvaló a fõ-fõ apostoloknál."));
husuperobject.biblemap.put("b47_11_6", new husuperobject(47,11,6,"Ha pedig avatatlan [vagyok ]is a beszédben, de nem az ismeretben; sõt mindenben, mindenképen nyilvánvalókká lettünk elõttetek."));
husuperobject.biblemap.put("b47_11_7", new husuperobject(47,11,7,"Avagy vétkeztem-é, mikor magamat megaláztam, hogy ti felmagasztaltassatok, hogy ingyen hírdettem néktek az Isten evangyéliomát?"));
husuperobject.biblemap.put("b47_11_8", new husuperobject(47,11,8,"Más gyülekezeteket fosztottam meg, zsoldot vévén, hogy néktek szolgáljak; és mikor nálatok voltam és szûkölködtem, nem voltam terhére senkinek."));
husuperobject.biblemap.put("b47_11_9", new husuperobject(47,11,9,"Mert az én szükségemet kipótolták a Macedóniából jött atyafiak; és rajta voltam és rajta is leszek, hogy semmiben se legyek terhetekre."));
husuperobject.biblemap.put("b47_11_10", new husuperobject(47,11,10,"Krisztus igazsága bennem, hogy én ettõl a dicsekvéstõl nem esem el Akhája vidékén."));
husuperobject.biblemap.put("b47_11_11", new husuperobject(47,11,11,"Miért? Hogy nem szeretlek titeket? Tudja az Isten."));
husuperobject.biblemap.put("b47_11_12", new husuperobject(47,11,12,"De a mit cselekszem, cselekedni is fogom, hogy elvágjam az alkalmat az alkalomkeresõk elõl; hogy a mivel dicsekesznek, olyanoknak találtassanak [abban], mint mi is."));
husuperobject.biblemap.put("b47_11_13", new husuperobject(47,11,13,"Mert az ilyenek hamis apostolok, álnok munkások, a kik a Krisztus apostolaivá változtatják át magukat."));
husuperobject.biblemap.put("b47_11_14", new husuperobject(47,11,14,"Nem is csoda; hisz maga a Sátán is átváltoztatja magát világosság angyalává."));
husuperobject.biblemap.put("b47_11_15", new husuperobject(47,11,15,"Nem nagy dolog azért, ha az õ szolgái is átváltoztatják magokat az igazság szolgáivá; a kiknek végök az õ cselekedeteik szerint lészen."));
husuperobject.biblemap.put("b47_11_16", new husuperobject(47,11,16,"Ismét mondom: ne tartson engem senki esztelennek; de ha mégis, fogadjatok be mint esztelent is, hogy egy kicsit én is dicsekedhessem."));
husuperobject.biblemap.put("b47_11_17", new husuperobject(47,11,17,"A mit mondok, nem az Úr szerint mondom, hanem mintegy esztelenül a dicsekvésnek ezzel a merészségével,"));
husuperobject.biblemap.put("b47_11_18", new husuperobject(47,11,18,"Mivelhogy sokan dicsekesznek test szerint, dicsekeszem én is."));
husuperobject.biblemap.put("b47_11_19", new husuperobject(47,11,19,"Hisz okosak lévén, örömest eltûritek az eszteleneket."));
husuperobject.biblemap.put("b47_11_20", new husuperobject(47,11,20,"Mert eltûritek, ha valaki leigáz titeket, ha valaki felfal, ha valaki megfog, ha valaki felfuvalkodik, ha valaki arczul ver titeket."));
husuperobject.biblemap.put("b47_11_21", new husuperobject(47,11,21,"Szégyenkezve mondom, mivelhogy mi erõtelenek voltunk; de a miben merész valaki, esztelenül szólok, merész vagyok én is."));
husuperobject.biblemap.put("b47_11_22", new husuperobject(47,11,22,"Héberek õk? Én is. Izráeliták-é? Én is. Ábrahám magva-é? Én is."));
husuperobject.biblemap.put("b47_11_23", new husuperobject(47,11,23,"Krisztus szolgái-é? (balgatagul szólok) én méginkább; több fáradság, több vereség, több börtön, gyakorta való halálos [veszedelem] által."));
husuperobject.biblemap.put("b47_11_24", new husuperobject(47,11,24,"A zsidóktól ötször kaptam negyvenet egy híján."));
husuperobject.biblemap.put("b47_11_25", new husuperobject(47,11,25,"Háromszor megostoroztak, egyszer megköveztek, háromszor hajótörést szenvedtem, éjt-napot a mélységben töltöttem;"));
husuperobject.biblemap.put("b47_11_26", new husuperobject(47,11,26,"Gyakorta való utazásban, veszedelemben folyó vizeken, veszedelemben rablók közt, veszedelemben népem között, veszedelemben pogányok között, veszedelemben városban, veszedelemben pusztában, veszedelemben tengeren, veszedelemben hamis atyafiak közt;"));
husuperobject.biblemap.put("b47_11_27", new husuperobject(47,11,27,"Fáradságban és nyomorúságban, gyakorta való virrasztásban, éhségben és szomjúságban, gyakorta való bõjtölésben, hidegben és mezítelenségben."));
husuperobject.biblemap.put("b47_11_28", new husuperobject(47,11,28,"Mindezeken kívül van az én naponkénti zaklattatásom, az összes gyülekezetek gondja."));
husuperobject.biblemap.put("b47_11_29", new husuperobject(47,11,29,"Ki beteg, hogy én is beteg ne volnék? Ki botránkozik meg, hogy én is ne égnék?"));
husuperobject.biblemap.put("b47_11_30", new husuperobject(47,11,30,"Ha dicsekednem kell, az én gyengeségemmel dicsekszem."));
husuperobject.biblemap.put("b47_11_31", new husuperobject(47,11,31,"Az Isten és a mi Urunk Jézus Krisztusnak Atyja, a ki mindörökké áldott, tudja, hogy nem hazudom."));
husuperobject.biblemap.put("b47_11_32", new husuperobject(47,11,32,"Damaskusban Aretás király helytartója õrzette a damaskusiak városát, akarván engem megfogni;"));
husuperobject.biblemap.put("b47_11_33", new husuperobject(47,11,33,"És az ablakon át, kosárban bocsátottak le a kõfalon, és megmenekültem kezei közül."));
husuperobject.biblemap.put("b47_12_1", new husuperobject(47,12,1,"A dicsekvés azonban nem használ nékem; rátérek azért a látomásokra és az Úrnak kijelentéseire."));
husuperobject.biblemap.put("b47_12_2", new husuperobject(47,12,2,"Ismerek egy embert a Krisztusban, a ki tizennégy évvel ezelõtt (ha testben-é, nem tudom; ha testen kívül-é, nem tudom; az Isten tudja) elragadtatott a harmadik égig."));
husuperobject.biblemap.put("b47_12_3", new husuperobject(47,12,3,"És tudom, hogy az az ember, (ha testben-é, ha testen kívül-é, nem tudom; az Isten tudja),"));
husuperobject.biblemap.put("b47_12_4", new husuperobject(47,12,4,"Elragadtatott a paradicsomba, és hallott kimondhatatlan beszédeket, a melyeket nem szabad embernek kibeszélnie."));
husuperobject.biblemap.put("b47_12_5", new husuperobject(47,12,5,"Az ilyennel dicsekeszem; magammal pedig nem dicsekeszem, ha csak az én gyengeségeimmel nem."));
husuperobject.biblemap.put("b47_12_6", new husuperobject(47,12,6,"Mert ha dicsekedni akarok, nem leszek esztelen; mert igazságot mondok; de megtürtõztetem magamat, hogy valaki többnek ne tartson, mint a minek lát, vagy a mit hall tõlem."));
husuperobject.biblemap.put("b47_12_7", new husuperobject(47,12,7,"És hogy a kijelentések nagysága miatt el ne bizakodjam, tövis adatott nékem a testembe, a Sátán angyala, hogy gyötörjön engem, hogy felettébb el ne bizakodjam."));
husuperobject.biblemap.put("b47_12_8", new husuperobject(47,12,8,"Ezért háromszor könyörögtem az Úrnak, hogy távozzék el [ez] tõlem;"));
husuperobject.biblemap.put("b47_12_9", new husuperobject(47,12,9,"És ezt mondá nékem: Elég néked az én kegyelmem; mert az én erõm erõtlenség által végeztetik el. Nagy örömest dicsekeszem azért az én erõtelenségeimmel, hogy a Krisztus ereje lakozzék én bennem."));
husuperobject.biblemap.put("b47_12_10", new husuperobject(47,12,10,"Annakokáért gyönyörködöm az erõtlenségekben, bántalmazásokban, nyomorúságokban, üldözésekben és szorongattatásokban Krisztusért; mert a mikor erõtelen vagyok, akkor vagyok erõs."));
husuperobject.biblemap.put("b47_12_11", new husuperobject(47,12,11,"Dicsekedvén, balgataggá lettem; ti kényszerítettetek reá. Mert néktek kellett volna engem ajánlanotok; mert semmiben sem vagyok alábbvaló a fõ-fõ apostoloknál, noha semmi vagyok."));
husuperobject.biblemap.put("b47_12_12", new husuperobject(47,12,12,"Apostolságomnak jelei megbizonyosodtak közöttetek sok tûrésben, jelekben, csodákban és erõkben is."));
husuperobject.biblemap.put("b47_12_13", new husuperobject(47,12,13,"Mert micsoda az, a miben megkárosodtatok a többi gyülekezetek mellett, hanem ha az, hogy én magam nem voltam néktek terhetekre? Bocsássátok meg nékem ezt az igazságtalanságot!"));
husuperobject.biblemap.put("b47_12_14", new husuperobject(47,12,14,"Ímé harmadízben is kész vagyok hozzátok menni, és nem leszek terhetekre; mert nem azt keresem, a mi a tiétek, hanem titeket magatokat. Mert nem a gyermekek tartoznak kincseket gyûjteni a szülõknek, hanem a szülõk a gyermekeknek."));
husuperobject.biblemap.put("b47_12_15", new husuperobject(47,12,15,"Én pedig nagy örömest áldozok és esem áldozatul a ti lelketekért; még ha ti, a kiket én igen szeretek, kevésbbé szerettek is engem."));
husuperobject.biblemap.put("b47_12_16", new husuperobject(47,12,16,"De ám legyen, hogy én nem voltam terhetekre; hanem álnok lévén ravaszsággal fogtalak meg titeket."));
husuperobject.biblemap.put("b47_12_17", new husuperobject(47,12,17,"Avagy a kiket hozzátok küldtem, azok közül valamelyik által kifosztottalak-é titeket?"));
husuperobject.biblemap.put("b47_12_18", new husuperobject(47,12,18,"Megkértem Titust, és vele együtt elküldtem amaz atyafit; csak nem fosztott ki titeket Titus? Nem egyazon Lélek szerint jártunk-é? Nem azokon a nyomokon-é?"));
husuperobject.biblemap.put("b47_12_19", new husuperobject(47,12,19,"Azt hiszitek megint, hogy elõttetek mentegetjük magunkat. Az Isten elõtt Krisztusban szólunk; mindezt pedig, szeretteim, a ti épüléstekért."));
husuperobject.biblemap.put("b47_12_20", new husuperobject(47,12,20,"Mert félek azon, hogy ha odamegyek, nem talállak majd olyanoknak, a milyeneknek szeretnélek, és engem is olyannak találtok, a milyennek nem szeretnétek; hogy valamiképen versengések, irígységek, indulatoskodások, visszavonások, rágalmazások, fondorkodások, felfuvalkodások, pártoskodások lesznek köztetek;"));
husuperobject.biblemap.put("b47_12_21", new husuperobject(47,12,21,"Hogy mikor újra odamegyek, megaláz engem az én Istenem ti köztetek, és sokakat megsiratok azok közül, a kik ezelõtt vétkeztek és meg nem tértek a tisztátalanságból, paráznaságból és bujaságból, a mit elkövettek."));
husuperobject.biblemap.put("b47_13_1", new husuperobject(47,13,1,"Ezúttal harmadszor megyek hozzátok. Két vagy három tanú vallomása alapján megáll minden dolog."));
husuperobject.biblemap.put("b47_13_2", new husuperobject(47,13,2,"Elõre megmondtam és elõre mondom, mint másodszori ottlétemkor, és most is távollétemben írom azoknak, a kik ezelõtt vétkeztek, és a többieknek mind, hogy ha ismét odamegyek, nem leszek kíméletes;"));
husuperobject.biblemap.put("b47_13_3", new husuperobject(47,13,3,"Mert hát az általam szóló Krisztusnak bizonyságát keresitek, a ki irányotokban nem erõtelen, hanem erõs ti bennetek."));
husuperobject.biblemap.put("b47_13_4", new husuperobject(47,13,4,"Mert noha megfeszíttetett erõtelenségbõl, mindazáltal él Istennek hatalmából. És noha mi erõtelenek vagyunk benne, de vele együtt élünk majd Isten erejébõl ti nálatok."));
husuperobject.biblemap.put("b47_13_5", new husuperobject(47,13,5,"Kísértsétek meg magatokat, ha a hitben vagytok-é? magatokat próbáljátok meg. Avagy nem ismeritek-é magatokat, hogy a Jézus Krisztus bennetek van? Kivévén, ha méltatlanok vagytok."));
husuperobject.biblemap.put("b47_13_6", new husuperobject(47,13,6,"De reménylem, hogy megismeritek, hogy mi nem vagyunk méltatlanok."));
husuperobject.biblemap.put("b47_13_7", new husuperobject(47,13,7,"Az Istent pedig kérem, hogy semmi gonoszt ne cselekedjetek; nem hogy mi méltóknak láttassunk, hanem hogy ti a jót cselekedjétek, mi pedig mintegy méltatlanok legyünk."));
husuperobject.biblemap.put("b47_13_8", new husuperobject(47,13,8,"Mert semmit sem cselekedhetünk az igazság ellen, hanem [csak] az igazságért."));
husuperobject.biblemap.put("b47_13_9", new husuperobject(47,13,9,"Mert örvendünk, ha mi erõtelenek vagyunk, ti meg erõsek vagytok; ezt pedig kérjük is, a ti tökéletesedésetekért."));
husuperobject.biblemap.put("b47_13_10", new husuperobject(47,13,10,"Azért írom ezeket távollétemben, hogy jelenlétemben ne kelljen keményen viselkednem ama hatalom szerint, a melyet az Úr adott nékem építésre és nem rontásra."));
husuperobject.biblemap.put("b47_13_11", new husuperobject(47,13,11,"Végezetre, atyámfiai, legyetek jó egészségben, épüljetek, vígasztalódjatok, egy értelemben legyetek, békességben éljetek; és a szeretetnek és békességnek Istene lészen veletek."));
husuperobject.biblemap.put("b47_13_12", new husuperobject(47,13,12,"Köszöntsétek egymást szent csókkal. Köszöntenek titeket a szentek mindnyájan."));
husuperobject.biblemap.put("b47_13_13", new husuperobject(47,13,13,"Az Úr Jézus Krisztusnak kegyelme, és az Istennek szeretete, és a Szent Léleknek közössége mindnyájatokkal. Ámen."));

}

}