package hu.bible;

public class hubible30 {

public hubible30() {

putmapbible30();

}

private void putmapbible30() {

husuperobject.biblemap.put("b30_1_1", new husuperobject(30,1,1,"Ámós beszédei, a ki a Tékoabeli pásztorok közt volt, [azokról,] a miket Izráel felõl látott Uzziásnak, Júda királyának idejében, és Jeroboámnak, a Jóás fiának, Izráel királyának idejében, két esztendõvel a földindulás elõtt."));
husuperobject.biblemap.put("b30_1_2", new husuperobject(30,1,2,"És mondá: A Sionról megharsan az Úr és Jeruzsálembõl megzendül, és elhervadnak a pásztorok legelõi, és megszárad a Kármel teteje."));
husuperobject.biblemap.put("b30_1_3", new husuperobject(30,1,3,"Így szól az Úr: Három bûne miatt Damaskusnak, sõt négy miatt, nem fordítom el, mert vas-cséplõkkel cséplették meg a Gileádot."));
husuperobject.biblemap.put("b30_1_4", new husuperobject(30,1,4,"Tüzet vetek azért Hazáel házára, és az emészti meg a Ben-Hadad palotáit."));
husuperobject.biblemap.put("b30_1_5", new husuperobject(30,1,5,"És összetöröm Damaskus zárját, és kivágom a lakót Avennek völgyébõl és a királyi pálcza tartóját Beth-Édenbõl, és Aramnak népe Kirbe fogva vitetik, [ezt] mondja az Úr."));
husuperobject.biblemap.put("b30_1_6", new husuperobject(30,1,6,"Így szól az Úr: Három bûne miatt Gázának, sõt négy miatt, nem fordítom el, mert az egész népet rabságra vitték, hogy az Edomitáknak adják el õket."));
husuperobject.biblemap.put("b30_1_7", new husuperobject(30,1,7,"Tüzet vetek azért Gáza kõfalára, és az emészti meg az õ palotáit."));
husuperobject.biblemap.put("b30_1_8", new husuperobject(30,1,8,"És kivágom a lakót Asdódból, és a királyi pálcza tartóját Askelonból, és Akronra is majd rávetem kezemet és a Filiszteusok maradéka elvész, azt mondja az én Uram, az Úr."));
husuperobject.biblemap.put("b30_1_9", new husuperobject(30,1,9,"Így szól az Úr: Három bûne miatt Tírusnak, sõt négy miatt, nem fordítom el, mert az egész rabnépet Edomnak adták át, és nem emlékeztek meg a testvéri frigyrõl."));
husuperobject.biblemap.put("b30_1_10", new husuperobject(30,1,10,"Tüzet vetek azért Tírus kõfalára, és az emészti meg az õ palotáit."));
husuperobject.biblemap.put("b30_1_11", new husuperobject(30,1,11,"Így szól az Úr: Három bûne miatt Edomnak, sõt négy miatt, nem fordítom el, mert fegyverrel ûzte saját atyjafiát, és elfojtá [szívében] az irgalmasságot, és haragja szüntelen tépett, és dühösködését mindvégig fentartotta."));
husuperobject.biblemap.put("b30_1_12", new husuperobject(30,1,12,"Tüzet vetek azért Témánra, és az emészti majd meg Boczra palotáit."));
husuperobject.biblemap.put("b30_1_13", new husuperobject(30,1,13,"Így szól az Úr: Három bûne miatt Ammon fiainak, sõt négy miatt, nem fordítom el; mert széthasogatták Gileád terhes asszonyait, hogy kiszélesíthessék az õ határokat."));
husuperobject.biblemap.put("b30_1_14", new husuperobject(30,1,14,"Tüzet vetek azért Rabba kõfalára, és az emészti meg az õ palotáit; [harczi] kiáltással a háború napján, [pusztító ]viharral a szélvésznek napján."));
husuperobject.biblemap.put("b30_1_15", new husuperobject(30,1,15,"És számkivetésbe megy az õ királyuk; õ maga és vele fejedelmei is, [ezt] mondja az Úr!"));
husuperobject.biblemap.put("b30_2_1", new husuperobject(30,2,1,"Így szól az Úr: Három bûne miatt a Moábnak, sõt négy miatt, nem fordítom el; mert mészszé égette Edom királyának csontjait!"));
husuperobject.biblemap.put("b30_2_2", new husuperobject(30,2,2,"Tüzet vetek azért Moábra, és az emészti meg Kerijjoth palotáit, és meghal Moáb a zajban, [hadi] lárma közt, a kürt zengése közben."));
husuperobject.biblemap.put("b30_2_3", new husuperobject(30,2,3,"Kivágom a birót közüle, és minden fejedelmit megölöm vele egyetemben, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_2_4", new husuperobject(30,2,4,"Így szól az Úr: Három bûne miatt a Júdának, sõt négy miatt, nem fordítom el; mert megvetették az Úrnak törvényét és nem tartották meg rendeléseit. Eltévelyítették õket az õ hazugságaik, a melyeket az õ atyáik követtek."));
husuperobject.biblemap.put("b30_2_5", new husuperobject(30,2,5,"Tüzet vetek azért Júdára, és az emészti meg Jeruzsálem palotáit."));
husuperobject.biblemap.put("b30_2_6", new husuperobject(30,2,6,"Így szól az Úr: Három bûne miatt az Izráelnek, sõt négy miatt, nem fordítom el; mert pénzért adták el az igazat, a szegényt pedig egy öltõ saruért."));
husuperobject.biblemap.put("b30_2_7", new husuperobject(30,2,7,"A kik a föld porát áhítják a szegények fejére, és a nyomorultak útját elfordítják. Fiú és az atyja [egy] leányhoz járnak, hogy megfertõztessék az én szent nevemet."));
husuperobject.biblemap.put("b30_2_8", new husuperobject(30,2,8,"Zálogos ruhákon nyujtózkodnak minden oltár mellett, és az elítéltek borát iszszák az õ istenök házában."));
husuperobject.biblemap.put("b30_2_9", new husuperobject(30,2,9,"Pedig én irtottam ki elõlük az Emoreusokat, a kik magasak voltak, mint a czédrusok, erõsek, mint a cserfák. Mégis kiirtottam gyümölcsét felül és gyökerét alul."));
husuperobject.biblemap.put("b30_2_10", new husuperobject(30,2,10,"És én hoztalak fel Égyiptom földérõl, és negyven esztendeig én hordoztalak a pusztában titeket, hogy bírjátok az Emoreusok földét."));
husuperobject.biblemap.put("b30_2_11", new husuperobject(30,2,11,"És prófétákat támasztottam a ti fiaitok közül és nazirokat ifjaitok közül. Nem így van-é vajjon, Izráel fiai? ezt mondja az Úr."));
husuperobject.biblemap.put("b30_2_12", new husuperobject(30,2,12,"De a nazirokat borral itattátok, és a prófétákra ráparancsoltatok, mondván: Ne prófétáljatok!"));
husuperobject.biblemap.put("b30_2_13", new husuperobject(30,2,13,"Ímé, én [is] lenyomlak titeket, ott a hol vagytok, mint a [cséplõ] szekér lenyomja a kévékkel teli [szérût.]"));
husuperobject.biblemap.put("b30_2_14", new husuperobject(30,2,14,"Elvész azért a futás a gyorstól, és nem erõsíti meg az erõst az õ ereje, és a hõs sem menekedhetik."));
husuperobject.biblemap.put("b30_2_15", new husuperobject(30,2,15,"Nem állja meg [helyét] az íjj-hordozó sem, nem menekülhet el még a gyorslábú sem, és a lovon ülõ sem menekedhetik."));
husuperobject.biblemap.put("b30_2_16", new husuperobject(30,2,16,"És a bátor szívû is a hõsök között meztelenül fut el azon a napon, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_3_1", new husuperobject(30,3,1,"Halljátok meg e beszédet, melyet az Úr szól ti felõletek, Izráel fiai; mindama nemzetség felõl, a melyet felhoztam Égyiptom földérõl, ezt mondván:"));
husuperobject.biblemap.put("b30_3_2", new husuperobject(30,3,2,"Csak titeket választottalak magamnak e földnek minden nemzetségei közül; azért büntetlek meg titeket minden gonoszságtokért."));
husuperobject.biblemap.put("b30_3_3", new husuperobject(30,3,3,"Vajjon járnak-é ketten együtt, ha nem egyeztek meg egymással?"));
husuperobject.biblemap.put("b30_3_4", new husuperobject(30,3,4,"Ordít-é az oroszlán az erdõben, ha nincs mit ragadoznia? Hallatja-é hangját barlangjából a kölyök-oroszlán, ha semmit nem fogott?!"));
husuperobject.biblemap.put("b30_3_5", new husuperobject(30,3,5,"Tõrbe esik-é a madár a földön, ha nincs tõr [vetve] néki? Felpattan-é a tõr a földrõl, ha fogni nem fogott?"));
husuperobject.biblemap.put("b30_3_6", new husuperobject(30,3,6,"Ha megharsan a kürt a városban, nem riad-é meg a nép? Vajjon lehet-é baj a városban, a mit nem az Úr szerezne?"));
husuperobject.biblemap.put("b30_3_7", new husuperobject(30,3,7,"Mert semmit sem cselekszik az én Uram, az Úr, míg meg nem jelenti titkát az õ szolgáinak, a prófétáknak."));
husuperobject.biblemap.put("b30_3_8", new husuperobject(30,3,8,"Ordít az oroszlán: ki ne rettegne? Az én Uram, az Úr szólt: ki ne prófétálna?"));
husuperobject.biblemap.put("b30_3_9", new husuperobject(30,3,9,"Adjatok hírt Asdód palotáiban és az Égyiptom földében való palotákban, és így szóljatok: Gyûljetek össze Samariának hegyein, és lássátok meg benne a sok háborgást, és az elnyomottakat az õ keblében."));
husuperobject.biblemap.put("b30_3_10", new husuperobject(30,3,10,"Mert nem tudnak igazán cselekedni, azt mondja az Úr, õk, a kik halomra gyûjtik az erõszakosságot és zsarolást az õ palotáikban."));
husuperobject.biblemap.put("b30_3_11", new husuperobject(30,3,11,"Annakokáért ezt mondja az Úr Isten: Ellenség [jön] és körülveszi [e] földet; ledönti hatalmadat és feldúlatnak a te palotáid."));
husuperobject.biblemap.put("b30_3_12", new husuperobject(30,3,12,"Ezt mondja az Úr: A mint a pásztor az oroszlán szájából csak a két lábszárt menti meg, vagy a fül hegyét; akképen menekülnek meg Izráel fiai, a kik Samariában pamlag szegletében ülnek és a nyugágynak selymén."));
husuperobject.biblemap.put("b30_3_13", new husuperobject(30,3,13,"Halljátok meg és adjátok tudtára a Jákób házának, azt mondja az Úr Isten, a Seregek Istene,"));
husuperobject.biblemap.put("b30_3_14", new husuperobject(30,3,14,"Hogy a mely napon megbüntetem Izráelt az õ vétkeiért, Béth-El oltáraiért is büntetek, és letöretnek az oltár szarvai, és a földre omlanak."));
husuperobject.biblemap.put("b30_3_15", new husuperobject(30,3,15,"És ledöntöm a téli házat a nyári házzal együtt, és elpusztulnak az elefántcsont-házak is, megsemmisülnek a nagy házak, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_1", new husuperobject(30,4,1,"Halljátok meg e beszédet Básánnak ünõi, a kik Samaria hegyén vagytok; a kik nyomorgatjátok a szegényeket, megrontjátok az ügyefogyottakat, a kik azt mondják az õ uroknak: Hozd elõ, hadd igyunk!"));
husuperobject.biblemap.put("b30_4_2", new husuperobject(30,4,2,"Megesküdt az Úr Isten az õ szentségére, hogy ímé napok következnek reátok, a mikor szigonyokkal visznek el titeket, és a ti maradékotokat halászó horgokkal."));
husuperobject.biblemap.put("b30_4_3", new husuperobject(30,4,3,"És a réseken mentek ki, mindenikõtök egyenest; és a Hermónba vettettek, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_4", new husuperobject(30,4,4,"Menjetek Béth-Elbe és vétkezzetek, szaporítsátok a vétkeket Gilgálban. Vigyétek fel reggelente áldozataitokat, és harmad-naponként tizedeiteket."));
husuperobject.biblemap.put("b30_4_5", new husuperobject(30,4,5,"Kovászosból gyújtsatok hálaáldozatot; ajánljatok önkéntes áldozatokat, híreszteljétek; mert így szeretitek, Izráel fiai, azt mondja az Úr Isten."));
husuperobject.biblemap.put("b30_4_6", new husuperobject(30,4,6,"De én is bocsátottam rátok fogak tisztaságát minden városaitokban és kenyérszükséget minden helységeitekben, és még sem tértetek vissza hozzám, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_7", new husuperobject(30,4,7,"De én is megvontam tõletek az esõt, három hónappal az aratás elõtt, és esõt adtam egy városra, más városra pedig nem adtam esõt. Az egyik rész esõt kapott, az a rész pedig, a melyre nem esett esõ, megszáradott."));
husuperobject.biblemap.put("b30_4_8", new husuperobject(30,4,8,"És két-három város tántorgott egy-egy városba, vizet inni, de meg nem elégíttettek; és még sem tértetek vissza hozzám, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_9", new husuperobject(30,4,9,"Megvertelek titeket szárazsággal és ragyával; kerteiteknek, szõlõiteknek, fügefáitoknak és olajfáitoknak nagy részét megette a sáska; és még sem tértetek vissza én hozzám, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_10", new husuperobject(30,4,10,"Döghalált bocsátottam rátok, mint Égyiptomra; fegyverrel öltem ifjaitokat, fogságra [vitettem] lovaitokat; és táborotok bûzét egész orrotokig emeltem, és még sem tértetek vissza hozzám, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_11", new husuperobject(30,4,11,"Felforgattam közületek [többeket,] a mint felforgatta Isten Sodomát és Gomorát, és olyanokká lettetek, mint a tûzbõl kikapott üszök; és még sem tértetek vissza hozzám, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_4_12", new husuperobject(30,4,12,"Azért hát ekképen cselekeszem veled Izráel! Minthogy pedig ekképen cselekeszem veled, készülj Istened elé, oh Izráel!"));
husuperobject.biblemap.put("b30_4_13", new husuperobject(30,4,13,"Mert ímé, a ki hegyeket alkotott és a szelet teremtette, és a ki megjelenti az embernek az õ gondolatját, a ki a hajnalt sötétséggé változtatja és a föld magaslatain lépdel: az Úr õ, a Seregeknek Istene az õ neve."));
husuperobject.biblemap.put("b30_5_1", new husuperobject(30,5,1,"Halljátok meg e beszédet, a melyet síródalként szólok ti rólatok, Izráelnek háza!"));
husuperobject.biblemap.put("b30_5_2", new husuperobject(30,5,2,"Elesett, nem kel fel többé Izráelnek szûze; végig terült az õ földén, és nincs, a ki felemelné."));
husuperobject.biblemap.put("b30_5_3", new husuperobject(30,5,3,"Bizony így szól az Úr Isten: A mely város ezerrel indult ki, százzal marad csak meg; a mely pedig százzal indult ki, tízzel marad csak meg Izráel házául."));
husuperobject.biblemap.put("b30_5_4", new husuperobject(30,5,4,"Bizony így szól az Úr az Izráel házához: Engem keressetek, és éltek!"));
husuperobject.biblemap.put("b30_5_5", new husuperobject(30,5,5,"És ne keressétek Béth-Elt; Gilgálba se menjetek; Beér-Sebába se menjetek át. Mert Gilgál fogságba megy. Béth-El pedig semmivé lesz."));
husuperobject.biblemap.put("b30_5_6", new husuperobject(30,5,6,"Keressétek az Urat, és éltek, különben reátör, mint a tûz, a József házára és megemészti Béth-Elt, és nem lesz, a ki megoltsa."));
husuperobject.biblemap.put("b30_5_7", new husuperobject(30,5,7,"A kik ürömmé változtatják az ítéletet és az igazságot földre tiporják."));
husuperobject.biblemap.put("b30_5_8", new husuperobject(30,5,8,"A ki a fiastyúkot és a kaszáscsillagot teremtette; a ki reggellé változtatja a homályt és a nappalt éjszakává sötétíti; a ki hívja a tenger vizeit és kiönti azokat a földnek színére: az Úr annak a neve."));
husuperobject.biblemap.put("b30_5_9", new husuperobject(30,5,9,"A ki pusztulással sujtja a hatalmasokat, és pusztulás száll az erõsségekre."));
husuperobject.biblemap.put("b30_5_10", new husuperobject(30,5,10,"Gyûlölik azt, a ki feddõzik a kapuban, és útálják azt, a ki feddhetetlenül beszél."));
husuperobject.biblemap.put("b30_5_11", new husuperobject(30,5,11,"Annakokáért, mivelhogy tiportátok a szegényt és gabona-ajándékot vesztek tõle: bár faragott kõbõl építtetek házakat, de nem lakoztok azokban, bár gyönyörûséges szõlõket plántáltok, de nem isztok azoknak borából."));
husuperobject.biblemap.put("b30_5_12", new husuperobject(30,5,12,"Mert tudom, hogy sok a ti bûnötök, és nagyok a ti vétkeitek! Igazak nyomorgatói, váltságdíj-szedõk [vagytok;] és elnyomják a szegényeket a kapuban!"));
husuperobject.biblemap.put("b30_5_13", new husuperobject(30,5,13,"Azért hallgat az eszes ebben az idõben, mert gonosz idõ ez."));
husuperobject.biblemap.put("b30_5_14", new husuperobject(30,5,14,"Keressétek a jót és ne a gonoszt, hogy éljetek, és akkor veletek lesz az Úr, a Seregek Istene, a mint mondjátok."));
husuperobject.biblemap.put("b30_5_15", new husuperobject(30,5,15,"Gyûlöljétek a gonoszt és szeressétek a jót; állítsátok [vissza] a kapuban az igazságot; talán megkegyelmez az Úr, a Seregek Istene a József maradékinak."));
husuperobject.biblemap.put("b30_5_16", new husuperobject(30,5,16,"Azt mondja azért az Úr, a Seregek Istene, az én Uram: Minden térségen siralom lesz és minden utczán ezt mondják: jaj, jaj! s a szántóvetõt [is] gyászra hívják, s a sírni tudókat siralomra;"));
husuperobject.biblemap.put("b30_5_17", new husuperobject(30,5,17,"És minden szõlõben siralom lesz, mert átmegyek te közötted, ezt mondja az Úr."));
husuperobject.biblemap.put("b30_5_18", new husuperobject(30,5,18,"Jaj azoknak, a kik kívánják az Úrnak napját! Mire való néktek az Úrnak napja? Sötétség az és nem világosság."));
husuperobject.biblemap.put("b30_5_19", new husuperobject(30,5,19,"Mintha valaki oroszlán elõl szaladna, és medve bukkanna rá; vagy pedig bemenne a házba és kezét a falhoz támasztaná, és kígyó marná meg."));
husuperobject.biblemap.put("b30_5_20", new husuperobject(30,5,20,"Nem sötétség lesz-é az Úrnak napja és nem világosság?! Sötétség lesz az, s még hajnalfénye sem lesz."));
husuperobject.biblemap.put("b30_5_21", new husuperobject(30,5,21,"Gyûlölöm, megvetem a ti ünnepeiteket, és nem gyönyörködöm a ti összejöveteleitekben."));
husuperobject.biblemap.put("b30_5_22", new husuperobject(30,5,22,"Még ha égõáldozatokkal áldoztok is nékem, sõt ételáldozataitokat sem kedvelem; kövér hálaáldozataitokra rá se tekintek."));
husuperobject.biblemap.put("b30_5_23", new husuperobject(30,5,23,"Távoztasd el tõlem énekeid zaját, hárfáid pengését sem hallgathatom."));
husuperobject.biblemap.put("b30_5_24", new husuperobject(30,5,24,"Hanem folyjon az ítélet, mint a víz, és az igazság, mint a bõvizû patak."));
husuperobject.biblemap.put("b30_5_25", new husuperobject(30,5,25,"Járultatok-é hozzám véres áldozatokkal s ételáldozatokkal a pusztában negyven éven át, oh Izráel háza?!"));
husuperobject.biblemap.put("b30_5_26", new husuperobject(30,5,26,"Majd viszitek hát Szikkútot, a ti királyotokat és Kijjunt, a ti képeiteket, a ti isteneitek csillagát, a melyet ti csináltatok magatoknak."));
husuperobject.biblemap.put("b30_5_27", new husuperobject(30,5,27,"És Damaskuson túlra számûzlek titeket, azt mondja az Úr, a kinek neve Seregeknek Istene."));
husuperobject.biblemap.put("b30_6_1", new husuperobject(30,6,1,"Jaj azoknak, a kik gondtalanul élnek a Sionon, és a kik elbizakodnak Samaria hegyén; a kik a népek elejének elei, és a kikhez jõ az Izráelnek háza!"));
husuperobject.biblemap.put("b30_6_2", new husuperobject(30,6,2,"Menjetek át Kalnéba, és nézzetek [szét;] onnan pedig menjetek a nagy Hamátba, és szálljatok le a Filiszteusok Gáthjába; vajjon jobbak-é azok, mint ezek az országok, és vajjon szélesebb-é azoknak határa a ti határotoknál?"));
husuperobject.biblemap.put("b30_6_3", new husuperobject(30,6,3,"A kik a veszedelem napját messze gondoljátok, és az erõszaknak széket emeltek;"));
husuperobject.biblemap.put("b30_6_4", new husuperobject(30,6,4,"A kik elefántcsont pamlagon hevernek, és az õ nyoszolyáikban elnyújtózkodnak, és a nyáj legjavából és a kihízlalt borjakból lakmároznak;"));
husuperobject.biblemap.put("b30_6_5", new husuperobject(30,6,5,"A kik hárfa mellett dalolgatnak, és azt hiszik, hogy hangszereik a Dávidéi;"));
husuperobject.biblemap.put("b30_6_6", new husuperobject(30,6,6,"A kik a bort serlegekkel iszszák, és szín-olajjal kenegetõznek, és nem búsulnak a József romlásán:"));
husuperobject.biblemap.put("b30_6_7", new husuperobject(30,6,7,"Most azért [is] õk vitetnek el a számûzöttek élén, és vége szakad a nyújtózkodók dáridózásának."));
husuperobject.biblemap.put("b30_6_8", new husuperobject(30,6,8,"Megesküdt az Úr Isten az õ életére; ezt mondja az Úr, a Seregek Istene: Útálom a Jákób kevélységét és gyûlölöm az õ palotáit; azért prédára vetem a várost mindenestõl."));
husuperobject.biblemap.put("b30_6_9", new husuperobject(30,6,9,"És ha egy házban tíz ember maradna is meg, még az is meghal;"));
husuperobject.biblemap.put("b30_6_10", new husuperobject(30,6,10,"És mikor felemeli õt az õ barátja és megégetõje, hogy kivigye a holttetemeket a házból, azt mondja annak, a ki a ház belsejében lesz: Van-é még valaki veled? az pedig azt mondja: Nincs, és ezt [is] mondja: Csitt! mert nem szabad említeni az Úrnak nevét!"));
husuperobject.biblemap.put("b30_6_11", new husuperobject(30,6,11,"Mert ímé, parancsol az Úr és megveri a nagy házat repedezésekkel, és a kicsiny házat hasadozásokkal."));
husuperobject.biblemap.put("b30_6_12", new husuperobject(30,6,12,"Vajjon futhatnak-é a lovak a sziklán? felszánthatja-é azt valaki ökrökön? hogy az ítéletet bürökké tettétek, az igazság gyümölcsét pedig ürömmé?!"));
husuperobject.biblemap.put("b30_6_13", new husuperobject(30,6,13,"A kik örültök a hiábavaló dolognak, [és] a kik ezt mondjátok: Nem a magunk erejével szereztünk-é magunknak a szarvakat?"));
husuperobject.biblemap.put("b30_6_14", new husuperobject(30,6,14,"Ímé, bizony népet indítok ellened, oh Izráel háza, azt mondja az Úr, a Seregek Istene, és az sanyargat titeket a hámáti úttól az Arába patakjáig."));
husuperobject.biblemap.put("b30_7_1", new husuperobject(30,7,1,"Ily dolgot láttatott velem az Úr Isten; Ímé, teremte sáskát a sarjúfakadás kezdetén, és ímé sarjú vala a királyi kaszálás után!"));
husuperobject.biblemap.put("b30_7_2", new husuperobject(30,7,2,"És lõn, hogy a mint felemésztette a földnek füvét, azt mondám: Uram, Isten! légy kegyelmes, kérlek! Hogyan állhasson meg Jákób, hiszen kicsiny?!"));
husuperobject.biblemap.put("b30_7_3", new husuperobject(30,7,3,"Megengesztelõdék az Úr e dologban: Nem lesz meg! mondá az Úr."));
husuperobject.biblemap.put("b30_7_4", new husuperobject(30,7,4,"Ily dolgot láttatott velem az Úr Isten: Ímé, tüzet híva elõ ítéletre az Úr Isten, és megemészté [az] a nagy mélységet, és megemészté az országot."));
husuperobject.biblemap.put("b30_7_5", new husuperobject(30,7,5,"De mondám: Uram, Isten! hagyd abba, kérlek! Hogyan állhatna meg Jákób; hiszen kicsiny?!"));
husuperobject.biblemap.put("b30_7_6", new husuperobject(30,7,6,"Megengesztelõdék az Úr e dologban: Ez sem lészen meg, mondá az Úr Isten!"));
husuperobject.biblemap.put("b30_7_7", new husuperobject(30,7,7,"Ily dolgot láttatott velem: Ímé, ott állott az Úr egy függõleges kõfalon, és a kezében mérõ-zsinór vala."));
husuperobject.biblemap.put("b30_7_8", new husuperobject(30,7,8,"És monda az Úr nékem: Mit látsz Ámós? Én pedig mondám: Mérõzsinórt. És mondá az Úr: Ímé, mérõzsinórral mérek népemnek, az Izráelnek közepette, és nem bocsátok meg néki többé."));
husuperobject.biblemap.put("b30_7_9", new husuperobject(30,7,9,"Bizony elpusztulnak Izsáknak magaslatai, és romba dõlnek Izráel szent helyei; és fegyverrel támadok a Jeroboám háza ellen."));
husuperobject.biblemap.put("b30_7_10", new husuperobject(30,7,10,"És elkülde Amáziás, Béth-El papja Jeroboámhoz, Izráel királyához, ezt üzenvén: Pártot ütött ellened Ámós az Izráel házában; nem tûrheti az ország az õ mindenféle beszédét."));
husuperobject.biblemap.put("b30_7_11", new husuperobject(30,7,11,"Mert így beszél Ámós: Fegyver által hal meg Jeroboám, az Izráel pedig fogságba vitetik az õ földérõl!"));
husuperobject.biblemap.put("b30_7_12", new husuperobject(30,7,12,"Ámósnak pedig így szólt Amáziás: Menj el, próféta! Fuss el a Júda földére; ott egyed kenyered és ottan prófétálj!"));
husuperobject.biblemap.put("b30_7_13", new husuperobject(30,7,13,"Béth-Elben pedig ne prófétálj többé; mert a király szenthelye és az ország székháza ez!"));
husuperobject.biblemap.put("b30_7_14", new husuperobject(30,7,14,"És felele Ámós, és mondá Amáziásnak: Nem vagyok próféta, sem prófétának fia; barom-pásztor vagyok és vad fügét szedek;"));
husuperobject.biblemap.put("b30_7_15", new husuperobject(30,7,15,"De elhívott engem az Úr a nyáj mellõl, és mondá nékem az Úr: Menj el és prófétálj az én népemnek, az Izráelnek!"));
husuperobject.biblemap.put("b30_7_16", new husuperobject(30,7,16,"Most azért halld meg az Úrnak beszédét! Te azt mondod: Ne prófétálj az Izráel ellen, és ne szólj az Izsák háza ellen!"));
husuperobject.biblemap.put("b30_7_17", new husuperobject(30,7,17,"Azért így szól az Úr: Feleséged paráznává lesz a városban; fiaid és leányaid fegyver által hullnak el; földedet felosztják kötéllel, és te magad tisztátalan földön halsz meg; az Izráel pedig fogságba vitetik az õ földérõl."));
husuperobject.biblemap.put("b30_8_1", new husuperobject(30,8,1,"Ily dolgot láttatott velem az Úr Isten: Ímé, egy kosár érett gyümölcs."));
husuperobject.biblemap.put("b30_8_2", new husuperobject(30,8,2,"És mondá: Mit látsz Ámós? És mondám: Egy kosár érett gyümölcsöt. És mondá az Úr nékem: Eljött vége az én népemnek, az Izráelnek; nem bocsátok meg néki többé!"));
husuperobject.biblemap.put("b30_8_3", new husuperobject(30,8,3,"Azon a napon jajjá változnak a templomi énekek, így szól az Úr Isten, és temérdek lesz a hulla; szó nélkül hányák mindenüvé."));
husuperobject.biblemap.put("b30_8_4", new husuperobject(30,8,4,"Halljátok meg ezt ti, kik a szegényre törtök, és e föld szegényeinek kipusztítására."));
husuperobject.biblemap.put("b30_8_5", new husuperobject(30,8,5,"Mondván: Mikor múlik el az újhold, hogy gabonát árulhassunk? és a szombat, hogy megnyithassuk a gabonás [házat?] hogy megkisebbítsük a vékát, és megnagyobbítsuk az árát, és hamis mértékkel csalhassunk?!"));
husuperobject.biblemap.put("b30_8_6", new husuperobject(30,8,6,"Hogy megvegyük a szegényeket pénzen, és a szûkölködõt egy öltõ saruért, és eladhassuk a gabona hulladékát?!"));
husuperobject.biblemap.put("b30_8_7", new husuperobject(30,8,7,"Megesküdt az Úr a Jákób büszkeségére: Soha el nem felejtem semmi cselekedetöket!"));
husuperobject.biblemap.put("b30_8_8", new husuperobject(30,8,8,"Ne rendüljön-é meg e miatt a föld? És ne búsuljon-é annak minden lakosa?! Bizony felindul egészen, mint a folyam, és dagad és apad, mint Égyiptom folyója."));
husuperobject.biblemap.put("b30_8_9", new husuperobject(30,8,9,"És lészen azon a napon, azt mondja az Úr Isten: Lenyugtatom a napot délben, és besötétítem a földet fényes nappal."));
husuperobject.biblemap.put("b30_8_10", new husuperobject(30,8,10,"Ünnepeiteket búra változtatom; és minden dalotokat szomorú énekké! Gyászruhát borítok minden derékra, és kopaszságot minden fejre, és olyanná teszem, mint a ki egyetlen fiát siratja; a vége pedig, mint a keserûség napja!"));
husuperobject.biblemap.put("b30_8_11", new husuperobject(30,8,11,"Ímé, napok jõnek, azt mondja az Úr Isten, és éhséget bocsátok e földre; nem kenyér után való éhséget, sem víz után való szomjúságot, hanem az Úr beszédének hallgatása után."));
husuperobject.biblemap.put("b30_8_12", new husuperobject(30,8,12,"És vándorolni fognak tengertõl tengerig és északtól fogva napkeletig. Futkosnak, hogy keressék az Úrnak beszédét, de nem találják meg."));
husuperobject.biblemap.put("b30_8_13", new husuperobject(30,8,13,"Azon a napon elepednek a deli szûzek, meg az ifjak is, a szomjúság miatt!"));
husuperobject.biblemap.put("b30_8_14", new husuperobject(30,8,14,"A kik Samaria bûnére esküsznek, és ezt mondják: Él a te istened, oh Dán: és él a te útad, oh Beérseba! Bizony elhullanak és nem kelnek fel többé!"));
husuperobject.biblemap.put("b30_9_1", new husuperobject(30,9,1,"Látám az Urat állani az oltáron, és mondá: Üsd meg az oszlop fejét, hadd rendüljenek meg a küszöbök, és döntsd azokat mindnyájok fejére. A megmaradókat pedig fegyverrel ölöm meg. Nem fog elfutni közülök a futó, és nem menekül meg közülök a menekülõ."));
husuperobject.biblemap.put("b30_9_2", new husuperobject(30,9,2,"Ha a Seolba ássák is be magokat, kezem onnan is kiragadja õket; és ha az égbe hágnának is fel, onnan is levonszom õket!"));
husuperobject.biblemap.put("b30_9_3", new husuperobject(30,9,3,"És ha a Kármel tetején rejtõznének is el, onnan is elõkeresem és elhozom õket; és ha szemeim elõl a tenger fenekére bújnának is, ott is parancsolok a kígyónak és megmarja õket."));
husuperobject.biblemap.put("b30_9_4", new husuperobject(30,9,4,"És ha fogságba mennek is ellenségeik elõtt, ott is parancsolok a fegyvernek és megöli õket; és reájok fordítom szemeimet, vesztökre és nem javokra."));
husuperobject.biblemap.put("b30_9_5", new husuperobject(30,9,5,"Mert az Úr, a Seregek Ura az, a ki megérinti a földet és elolvad [az,] és jajgat annak minden lakója, és feldagad egészen, mint a folyam, meg elapad, mint Égyiptom folyója."));
husuperobject.biblemap.put("b30_9_6", new husuperobject(30,9,6,"A ki fenn az égben építé az õ boltozatát, és annak íveit a földre alapítá; a ki elõhívja a tenger vizeit s kiönti azokat a földnek színére: az Úr az õ neve."));
husuperobject.biblemap.put("b30_9_7", new husuperobject(30,9,7,"Nem olyanok vagytok-é ti elõttem, oh Izráel fiai, mint a Kusiták fiai?! ezt mondja az Úr. Nem én hoztam-é ki Izráelt Égyiptom földérõl, és a Filiszteusokat Kaftorból, és a Siriabelieket Kirbõl?!"));
husuperobject.biblemap.put("b30_9_8", new husuperobject(30,9,8,"Ímé, az Úr Isten szemmel tartja a bûnös országot, és eltörlöm azt a földnek színérõl. Mindazáltal még sem pusztítom el egészen a Jákóbnak házát, ezt mondja az Úr!"));
husuperobject.biblemap.put("b30_9_9", new husuperobject(30,9,9,"Mert ímé, én parancsolok és szétrázom Izráel házát minden népek között, a mint a rostával rázogatnak; de nem esik a földre egy szemecske sem."));
husuperobject.biblemap.put("b30_9_10", new husuperobject(30,9,10,"Fegyver által halnak meg az én népemnek minden bûnösei, a kik azt mondják: Nem ér el minket és nem jõ reánk a veszedelem."));
husuperobject.biblemap.put("b30_9_11", new husuperobject(30,9,11,"Azon a napon felemelem a Dávid leomlott sátorát, és kijavítom repedezéseit, és felemelem omladékait, és megépítem azt, mint volt hajdanán."));
husuperobject.biblemap.put("b30_9_12", new husuperobject(30,9,12,"Hogy örökségképen bírják az Edom maradékát és mindama népeket, a kik az én nevemrõl neveztetnek, ezt mondja az Úr, a ki megcselekszi ezt!"));
husuperobject.biblemap.put("b30_9_13", new husuperobject(30,9,13,"Ímé, napok jõnek, ezt mondja az Úr, és ott éri a szántó az aratót, a szõlõtaposó a magvetõt. És a hegyek musttal csepegnek, a halmok pedig mind megáradnak."));
husuperobject.biblemap.put("b30_9_14", new husuperobject(30,9,14,"És hazahozom a fogságból az én népemet, az Izráelt, és fölépítik az elpusztult városokat, és lakoznak bennök. Szõlõket plántálnak és iszszák azok borát, és kerteket csinálnak és eszik azoknak gyümölcsét."));
husuperobject.biblemap.put("b30_9_15", new husuperobject(30,9,15,"És elplántálom õket az õ földjökbe; és nem szaggattatnak ki többé az õ földjökbõl, a melyet adtam nékik, azt mondja az Úr, a te Istened!"));

}

}