package hu.bible;

public class hubible38 {

public hubible38() {

putmapbible38();

}

private void putmapbible38() {

husuperobject.biblemap.put("b38_1_1", new husuperobject(38,1,1,"Dárius második esztendejében, a nyolczadik hónapban szóla az Úr Zakariáshoz, a Berekiás fiához, a ki Iddó próféta fia, mondván:"));
husuperobject.biblemap.put("b38_1_2", new husuperobject(38,1,2,"Igen megharagudott az Úr a ti atyáitokra."));
husuperobject.biblemap.put("b38_1_3", new husuperobject(38,1,3,"Mondjad azért nékik: Ezt mondja a Seregeknek Ura: Térjetek hozzám, szól a Seregeknek Ura, és hozzátok térek, mond a Seregeknek Ura."));
husuperobject.biblemap.put("b38_1_4", new husuperobject(38,1,4,"Ne legyetek olyanok, mint atyáitok, a kikhez az elébbi próféták kiáltottak, mondván: Ezt mondja a Seregeknek Ura: Térjetek meg kérlek a ti gonosz útaitokról, és a ti gonosz cselekedeteitekbõl, de nem hallgattak meg, és nem figyelmeztek reám, szól az Úr."));
husuperobject.biblemap.put("b38_1_5", new husuperobject(38,1,5,"Atyáitok? Hol vannak õk? És a próféták örökké élnek-é?"));
husuperobject.biblemap.put("b38_1_6", new husuperobject(38,1,6,"De az én beszédeim és végzéseim, a melyeket szolgáim, a próféták által hirdettem: nem beteljesedtek-é a ti atyáitokon? És megtértek és azt mondták: A mint elhatározta vala a Seregeknek Ura, hogy a mi útaink és cselekedeteink szerint bánik velünk: úgy bánt velünk."));
husuperobject.biblemap.put("b38_1_7", new husuperobject(38,1,7,"A tizenegyedik hónapnak, azaz a Sebat hónapnak huszonnegyedik napján, Dáriusnak második esztendejében, szóla az Úr Zakariáshoz, a Berekiás fiához, a ki Iddó próféta fia, mondván:"));
husuperobject.biblemap.put("b38_1_8", new husuperobject(38,1,8,"Látám éjszaka, hogy ímé, egy férfiú veres lovon ül vala, és áll vala a mirtus-fák között, a melyek egy árnyas völgyben valának; háta megett pedig veres, tarka és fehér lovak."));
husuperobject.biblemap.put("b38_1_9", new husuperobject(38,1,9,"És mondám: Mik ezek Uram? És mondá nékem az angyal, a ki beszél vala nékem: Én megmutatom néked: mik ezek."));
husuperobject.biblemap.put("b38_1_10", new husuperobject(38,1,10,"Akkor felele az a férfiú, a ki a mirtus-fák között áll vala, és mondá: Azok ezek, a kiket az Úr küldött, hogy járják be e földet;"));
husuperobject.biblemap.put("b38_1_11", new husuperobject(38,1,11,"És felelének az Úr angyalának, a ki a mirtus-fák között áll vala, és mondák: Bejártuk a földet, és ímé, az egész föld vesztegel és nyugodt."));
husuperobject.biblemap.put("b38_1_12", new husuperobject(38,1,12,"Az Úr angyala pedig felele, és mondá: Seregeknek Ura! Meddig nem könyörülsz még Jeruzsálemen és Júdának városain, a melyekre haragszol immár hetven esztendõ óta?"));
husuperobject.biblemap.put("b38_1_13", new husuperobject(38,1,13,"És nyájas szavakkal, vígasztaló szókkal felele az Úr az angyalnak, a ki beszél vala velem."));
husuperobject.biblemap.put("b38_1_14", new husuperobject(38,1,14,"És mondá nékem az angyal, a ki beszél vala velem: Kiálts, ezt mondván: Ezt mondja a Seregeknek Ura: szeretem Jeruzsálemet és a Siont nagy szeretettel!"));
husuperobject.biblemap.put("b38_1_15", new husuperobject(38,1,15,"De nagy haraggal haragszom én a hivalkodó népekre, a kikre kevéssé haragudtam [ugyan,] de õk gonoszra törtek."));
husuperobject.biblemap.put("b38_1_16", new husuperobject(38,1,16,"Azt mondja azért az Úr: könyörületességgel fordulok Jeruzsálemhez; benne építtetik meg az én házam, szól a Seregeknek Ura, és mérõzsinór nyujtatik ki Jeruzsálem felett."));
husuperobject.biblemap.put("b38_1_17", new husuperobject(38,1,17,"Mégis kiálts, mondván: Ezt mondja a Seregeknek Ura: Bõvelkedni fognak még városaim a jóban, mert megvígasztalja még az Úr a Siont, és magáévá fogadja még Jeruzsálemet!"));
husuperobject.biblemap.put("b38_1_18", new husuperobject(38,1,18,"Majd felemelém szemeimet, és ímé, négy szarvat láték."));
husuperobject.biblemap.put("b38_1_19", new husuperobject(38,1,19,"És mondám az angyalnak, a ki beszél vala velem: Mik ezek? És monda nékem: Ezek azok a szarvak, a melyek szétszórták Júdát, Izráelt és Jeruzsálemet."));
husuperobject.biblemap.put("b38_1_20", new husuperobject(38,1,20,"Azután mutata nékem az Úr négy mesterembert."));
husuperobject.biblemap.put("b38_1_21", new husuperobject(38,1,21,"És mondám: Mit jöttek ezek cselekedni? Õ pedig szóla, mondván: Ezek azok a szarvak, a melyek szétszórták Júdát annyira, hogy senki sem emelheti vala fel fejét: de eljöttek ezek, hogy elrettentsék õket, hogy letörjék a pogányok szarvait, a kik szarvakkal támadtak vala Júda földe ellen, hogy szétszórják azt."));
husuperobject.biblemap.put("b38_2_1", new husuperobject(38,2,1,"Felemelém ismét szemeimet, és ímé, láték egy férfiút és a kezében mérõ- kötelet."));
husuperobject.biblemap.put("b38_2_2", new husuperobject(38,2,2,"És mondám: Hová mégy te? És mondá nékem: Megmérni Jeruzsálemet, hogy lássam: mennyi a széle és mennyi a hossza?"));
husuperobject.biblemap.put("b38_2_3", new husuperobject(38,2,3,"És ímé, az angyal, a ki beszél vala velem, kijöve, és más angyal [is] kijöve eléje."));
husuperobject.biblemap.put("b38_2_4", new husuperobject(38,2,4,"És monda annak: Fuss, és szólj e gyermekhez, mondván: Kerítetlenül fogják lakni Jeruzsálemet a benne levõ emberek és barmok sokasága miatt."));
husuperobject.biblemap.put("b38_2_5", new husuperobject(38,2,5,"Én pedig, szól az Úr, tûz-fal leszek körülötte és megdicsõítem magamat õ benne!"));
husuperobject.biblemap.put("b38_2_6", new husuperobject(38,2,6,"Jaj, jaj! Fussatok ki az északi földrõl, így szól az Úr, mert az ég négy szele felé szórtalak szét titeket, szól az Úr."));
husuperobject.biblemap.put("b38_2_7", new husuperobject(38,2,7,"Jaj Sion! Szabadítsd ki magadat, ki Babilon leányánál lakozol."));
husuperobject.biblemap.put("b38_2_8", new husuperobject(38,2,8,"Mert így szól a Seregeknek Ura: Dicsõség után küldött engem a pogányokhoz, a kik fosztogatnak titeket, mert a ki titeket bánt, az õ szemefényét bántja."));
husuperobject.biblemap.put("b38_2_9", new husuperobject(38,2,9,"Mert ímé én felemelem kezemet ellenök, és saját szolgáik prédájává lesznek, és megtudjátok, hogy a Seregeknek Ura küldött el engem."));
husuperobject.biblemap.put("b38_2_10", new husuperobject(38,2,10,"Örülj és örvendezz, Sionnak leánya, mert ímé elmegyek és közötted lakozom! így szól az Úr."));
husuperobject.biblemap.put("b38_2_11", new husuperobject(38,2,11,"És sok pogány csatlakozik azon a napon az Úrhoz, és népemmé lesznek, és közötted lakozom, és megtudod, hogy a Seregeknek Ura küldött hozzád engem."));
husuperobject.biblemap.put("b38_2_12", new husuperobject(38,2,12,"És birtokba veszi az Úr Júdát, mint az õ osztályrészét a szent földön, és újra magáévá fogadja Jeruzsálemet."));
husuperobject.biblemap.put("b38_2_13", new husuperobject(38,2,13,"Hallgasson minden test az Úr elõtt: mert felkelt az õ szentséges helyérõl."));
husuperobject.biblemap.put("b38_3_1", new husuperobject(38,3,1,"Azután megmutatá nékem Jósuát, a fõpapot, a ki az Úr angyala elõtt álla, és a Sátánt, a ki jobb keze felõl álla, hogy vádolja õt."));
husuperobject.biblemap.put("b38_3_2", new husuperobject(38,3,2,"És mondá az Úr a Sátánnak: Dorgáljon meg téged az Úr, te Sátán; dorgáljon meg az Úr, a ki magáévá fogadja Jeruzsálemet. Avagy nem tûzbõl kikapott üszög-é ez?"));
husuperobject.biblemap.put("b38_3_3", new husuperobject(38,3,3,"Jósua pedig szennyes ruhába vala öltöztetve, és áll vala az angyal elõtt."));
husuperobject.biblemap.put("b38_3_4", new husuperobject(38,3,4,"És szóla és monda az elõtte állóknak, mondván: Vegyétek le róla a szennyes ruhákat! És monda néki: Lásd! Levettem rólad a te álnokságodat, és ünnepi ruhákba öltöztetlek téged!"));
husuperobject.biblemap.put("b38_3_5", new husuperobject(38,3,5,"Azután mondám: Tegyenek fejére tiszta süveget! Feltevék azért fejére a tiszta süveget, és ruhákba öltözteték õt, az Úrnak angyala pedig [ott] áll vala."));
husuperobject.biblemap.put("b38_3_6", new husuperobject(38,3,6,"És bizonyságot tõn az Úrnak angyala Jósuának, mondván:"));
husuperobject.biblemap.put("b38_3_7", new husuperobject(38,3,7,"Ezt mondja a Seregeknek Ura: Ha az én útaimban jársz, és ha parancsolataimat magtartod: te is ítélõje leszel az én házamnak, sõt õrizni fogod az én pitvaraimat, és ki- s bejárást engedek néked ez itt állók között."));
husuperobject.biblemap.put("b38_3_8", new husuperobject(38,3,8,"Halld meg Jósua, te fõpap; te és barátaid, a kik elõtted ülnek, mert jelképes férfiak ezek: Ímé, bizony elõhozom az én szolgámat, Csemetét!"));
husuperobject.biblemap.put("b38_3_9", new husuperobject(38,3,9,"Mert ímé e kõ az, a melyet Jósua elé helyezek; egy kövön hét szem; ímé, én faragom annak faragványait, így szól a Seregeknek Ura, és eltörlöm e földnek álnokságait egy napon."));
husuperobject.biblemap.put("b38_3_10", new husuperobject(38,3,10,"Azon a napon, így szól a Seregeknek Ura, kiki hívja majd a maga felebarátját a szõlõtõ alá és a fügefa alá."));
husuperobject.biblemap.put("b38_4_1", new husuperobject(38,4,1,"Majd visszatére az angyal, a ki beszél vala velem, és felkölte engem, mint mikor valaki álmából költetik fel."));
husuperobject.biblemap.put("b38_4_2", new husuperobject(38,4,2,"És mondá nékem: Mit látsz te? És mondám: Látok ímé egy merõ arany gyertyatartót, tetején az olajtartója, rajta pedig annak hét szövétneke, és hét csõ a szövétnekekhez, a melyek a tetején vannak;"));
husuperobject.biblemap.put("b38_4_3", new husuperobject(38,4,3,"És mellette két olajfa: egyik az olajtartó jobb oldalán, a másik pedig annak bal oldalán."));
husuperobject.biblemap.put("b38_4_4", new husuperobject(38,4,4,"És felelék, és mondám az angyalnak, a ki beszél vala velem, mondván: Mik ezek, Uram?"));
husuperobject.biblemap.put("b38_4_5", new husuperobject(38,4,5,"És felele az angyal, a ki beszél vala velem, és mondá nékem: Hát nem tudod-é, mik ezek? És mondám: Nem, Uram!"));
husuperobject.biblemap.put("b38_4_6", new husuperobject(38,4,6,"És felele, és szóla nékem, mondván: Az Úrnak beszéde ez Zorobábelhez, mondván: Nem erõvel, sem hatalommal, hanem az én lelkemmel! azt mondja a Seregeknek Ura."));
husuperobject.biblemap.put("b38_4_7", new husuperobject(38,4,7,"Ki vagy te, te nagy hegy? Lapálylyá [leszel] Zorobábel elõtt, és felviszi a csúcs-követ, [és ilyen] kiáltás [támad:] Áldás, áldás reá!"));
husuperobject.biblemap.put("b38_4_8", new husuperobject(38,4,8,"És szóla hozzám az Úr, mondván:"));
husuperobject.biblemap.put("b38_4_9", new husuperobject(38,4,9,"A Zorobábel kezei veték meg e ház alapját, és az õ kezei végzik el azt, és megtudod, hogy a Seregeknek Ura küldött el engem hozzátok."));
husuperobject.biblemap.put("b38_4_10", new husuperobject(38,4,10,"Mert a kik csúfolták a kicsiny kezdetet, örülni fognak, ha meglátják Zorobábel kezében az ónkövet. Hét van ilyen, az Úrnak szemei ezek, a melyek átpillantják az egész földet."));
husuperobject.biblemap.put("b38_4_11", new husuperobject(38,4,11,"És felelék, és mondám néki: Mi ez a két olajfa a gyertyatartó jobb és bal oldalán?"));
husuperobject.biblemap.put("b38_4_12", new husuperobject(38,4,12,"És másodszor is felelék, és mondám néki: Micsoda az olajfának az a két ága, a melyek a két arany csõ mellett vannak, és öntik magukból az aranyat?"));
husuperobject.biblemap.put("b38_4_13", new husuperobject(38,4,13,"És szóla nékem, mondván: Hát nem tudod-é, mik ezek? És mondám: Nem, Uram!"));
husuperobject.biblemap.put("b38_4_14", new husuperobject(38,4,14,"És mondá nékem: Ezek ketten az olajjal felkenettek, a kik az egész föld Ura mellett állnak."));
husuperobject.biblemap.put("b38_5_1", new husuperobject(38,5,1,"Azután ismét felemelém szemeimet, és látám, hogy ímé, egy könyv repül vala."));
husuperobject.biblemap.put("b38_5_2", new husuperobject(38,5,2,"És monda nékem: Mit látsz te? És én mondám: Látok egy repülõ könyvet, húsz sing a hossza és tíz sing a széle."));
husuperobject.biblemap.put("b38_5_3", new husuperobject(38,5,3,"És monda nékem: Ez az átok, a mely kihat az egész föld színére; mert mindaz, a ki lop, ehhez képest fog innen kiirtatni, és mindaz, a ki [hamisan] esküszik, ehhez képest fog innen kiirtatni."));
husuperobject.biblemap.put("b38_5_4", new husuperobject(38,5,4,"Kibocsátom ezt, szól a Seregeknek Ura, és bemegy a lopónak házába, és annak házába, a ki hamisan esküszik az én nevemre, és ott marad annak házában, és megemészti azt, s annak fáit és köveit."));
husuperobject.biblemap.put("b38_5_5", new husuperobject(38,5,5,"Majd kijöve az angyal, a ki beszél vala velem, és monda nékem: Emeld csak fel szemeidet, és lásd meg: micsoda az, a mi kijön?"));
husuperobject.biblemap.put("b38_5_6", new husuperobject(38,5,6,"És mondám: Micsoda ez? Õ pedig mondá: Az, a mi kijön, mérõedény. És mondá: Ilyen a formájok az egész földön."));
husuperobject.biblemap.put("b38_5_7", new husuperobject(38,5,7,"És ímé, egy kerek ón-darab repül vala, és ül vala egy asszony a mérõ- edény közepében."));
husuperobject.biblemap.put("b38_5_8", new husuperobject(38,5,8,"És mondá: Ez az istentelenség. És veté ezt a mérõ-edény közepébe, a darab ónt pedig veté annak szájára."));
husuperobject.biblemap.put("b38_5_9", new husuperobject(38,5,9,"És felemelém szemeimet, és látám, hogy ímé, két asszony jöve elõ, és szél vala szárnyaikban, és szárnyaik olyanok, mint az eszterágnak szárnyai, és felemelék a mérõ-edényt a föld és az ég közé."));
husuperobject.biblemap.put("b38_5_10", new husuperobject(38,5,10,"És mondám az angyalnak, a ki beszél vala velem: Hová viszik ezek a mérõ- edényt?"));
husuperobject.biblemap.put("b38_5_11", new husuperobject(38,5,11,"És mondá nékem: Hogy házat építsenek annak a Sineár földén, és oda erõsítsék, és ott hagyják azt a maga helyén."));
husuperobject.biblemap.put("b38_6_1", new husuperobject(38,6,1,"Majd megfordulék és felemelém szemeimet, és látám, hogy ímé négy szekér jön vala ki két hegy közül, és azok a hegyek ércz-hegyek."));
husuperobject.biblemap.put("b38_6_2", new husuperobject(38,6,2,"Az elsõ szekérben veres lovak, a második szekérben fekete lovak;"));
husuperobject.biblemap.put("b38_6_3", new husuperobject(38,6,3,"És a harmadik szekérben fehér lovak; a negyedik szekérben pedig tarka lovak, erõsek."));
husuperobject.biblemap.put("b38_6_4", new husuperobject(38,6,4,"És megszólalék, és mondám az angyalnak, a ki beszél vala velem: Mik ezek, Uram?"));
husuperobject.biblemap.put("b38_6_5", new husuperobject(38,6,5,"Az angyal felele, és mondá nékem: Ezek az égnek négy szele, jõnek az egész föld Ura mellett való szolgálatukból."));
husuperobject.biblemap.put("b38_6_6", new husuperobject(38,6,6,"A melyben a fekete lovak vannak, észak földére mennek, és a fehérek mennek utánok, a tarkák pedig a dél földére mennek;"));
husuperobject.biblemap.put("b38_6_7", new husuperobject(38,6,7,"Az erõsek is mennek és kivánják eljárni a földet. És mondá: Menjetek, járjátok el a földet; és eljárák a földet."));
husuperobject.biblemap.put("b38_6_8", new husuperobject(38,6,8,"Majd híva engem, és beszéle velem, mondván: Lásd! Az észak földére menõk lecsendesíték lelkemet északnak földén."));
husuperobject.biblemap.put("b38_6_9", new husuperobject(38,6,9,"És szóla az Úr hozzám, mondván:"));
husuperobject.biblemap.put("b38_6_10", new husuperobject(38,6,10,"Végy a számkivetésbõl valóktól: Heldaitól, Tóbiástól és Jedajától; és menj be azon a napon, menj be Jósiának, a Sefániás fiának házába, a kik Babilonból jöttenek,"));
husuperobject.biblemap.put("b38_6_11", new husuperobject(38,6,11,"Végy ugyanis ezüstöt és aranyat, és csinálj koronákat, és tedd Jósuának, a Jehosadák fiának, a fõpapnak fejére!"));
husuperobject.biblemap.put("b38_6_12", new husuperobject(38,6,12,"És szólj néki, mondván: Ezt mondja a Seregeknek Ura, mondván: Ímé, egy férfiú, a neve Csemete, mert csemete támad belõle, és megépíti az Úrnak templomát!"));
husuperobject.biblemap.put("b38_6_13", new husuperobject(38,6,13,"Mert õ fogja megépíteni az Úrnak templomát, és nagy lesz az õ dicsõsége, és ülni és uralkodni fog az õ székében, és pap is lesz az õ székében, és békesség tanácsa lesz kettõjük között."));
husuperobject.biblemap.put("b38_6_14", new husuperobject(38,6,14,"És a koronák legyenek Hélemnek, Tóbiásnak, Jedajának és Hénnek, a Sefániás fiának emlékjelei az Úr templomában."));
husuperobject.biblemap.put("b38_6_15", new husuperobject(38,6,15,"És a messzelakók eljõnek és építenek az Úr templomában, és megtudjátok, hogy a Seregeknek Ura küldött el engem hozzátok. Így lesz, ha hallgattok az Úrnak, a ti Isteneteknek szavára!"));
husuperobject.biblemap.put("b38_7_1", new husuperobject(38,7,1,"És lõn a Dárius király negyedik esztendejében, hogy szóla az Úr Zakariáshoz a kilenczedik hónapnak, a Kiszlévnek negyedikén,"));
husuperobject.biblemap.put("b38_7_2", new husuperobject(38,7,2,"Mikor elküldék az Isten házába Saréczert és Régem-Méleket és társait, hogy esedezzenek az Úr színe elõtt,"));
husuperobject.biblemap.put("b38_7_3", new husuperobject(38,7,3,"[És] hogy megkérdezzék a papokat, a kik a Seregek Urának házában vannak, és megkérdezzék a prófétákat is: Sírjak-é az ötödik hónapban [és] bõjtöljek-é, a mint cselekedtem azt néhány esztendõ óta?"));
husuperobject.biblemap.put("b38_7_4", new husuperobject(38,7,4,"Szóla ekkor a Seregeknek Ura nékem, mondván:"));
husuperobject.biblemap.put("b38_7_5", new husuperobject(38,7,5,"Szólj az ország minden népének és a papoknak, mondván: Mikor bõjtöltetek és gyászoltatok az ötödik és hetedik [hónap]ban, és pedig hetven esztendeig: avagy bõjtölvén, nékem bõjtöltetek-é?"));
husuperobject.biblemap.put("b38_7_6", new husuperobject(38,7,6,"És mikor ettetek, és mikor ittatok: avagy nem magatoknak ettetek és magatoknak ittatok-é?"));
husuperobject.biblemap.put("b38_7_7", new husuperobject(38,7,7,"Avagy nem [ezek] a beszédek-é [azok,] a melyeket szólott vala az Úr az elõbbi próféták által, mikor még Jeruzsálem népes és gazdag vala a körülte levõ városokkal együtt, és mind a déli táj, mind a lapály-föld népes vala?"));
husuperobject.biblemap.put("b38_7_8", new husuperobject(38,7,8,"És szóla az Úr Zakariásnak, mondván:"));
husuperobject.biblemap.put("b38_7_9", new husuperobject(38,7,9,"Így szólt a Seregeknek Ura, mondván: Igaz ítélettel ítéljetek, és irgalmasságot és könyörületességet gyakoroljon kiki az õ felebarátjával!"));
husuperobject.biblemap.put("b38_7_10", new husuperobject(38,7,10,"Özvegyet és árvát, jövevényt és szegényt meg ne sarczoljatok, és egymás ellen még szívetekben se gondoljatok gonoszt."));
husuperobject.biblemap.put("b38_7_11", new husuperobject(38,7,11,"De nem akarák meghallani, sõt vállaikat vonogaták, és bedugák füleiket, hogy ne halljanak."));
husuperobject.biblemap.put("b38_7_12", new husuperobject(38,7,12,"Szívöket is megkeményíték, hogy ne hallják a törvényt és az igéket, a melyeket a Seregeknek Ura küldött vala az õ lelke által, az elébbi próféták által. És igen felgerjedt vala a Seregeknek Ura."));
husuperobject.biblemap.put("b38_7_13", new husuperobject(38,7,13,"És lõn, hogy a mint én kiáltottam és nem hallották meg: úgy kiáltottak, de nem hallottam meg, azt mondja a Seregeknek Ura;"));
husuperobject.biblemap.put("b38_7_14", new husuperobject(38,7,14,"Hanem szétszórtam õket mindenféle nemzetek közé, a kik nem ismerték õket, és puszta lõn utánok a föld, hogy senki [azon] sem át nem megy, sem meg nem tér. Így tevék pusztává a kívánatos földet."));
husuperobject.biblemap.put("b38_8_1", new husuperobject(38,8,1,"Majd szóla a Seregeknek Ura, mondván:"));
husuperobject.biblemap.put("b38_8_2", new husuperobject(38,8,2,"Ezt mondja a Seregeknek Ura: Nagy gerjedezéssel gerjedeztem a Sionért, és nagy haragra gerjedtem ellene."));
husuperobject.biblemap.put("b38_8_3", new husuperobject(38,8,3,"Ezt mondja az Úr: Megtértem a Sionhoz, és Jeruzsálem közepette lakozom, és Jeruzsálem igazság városának neveztetik, a Seregek Urának hegye pedig szent hegynek."));
husuperobject.biblemap.put("b38_8_4", new husuperobject(38,8,4,"Ezt mondja a Seregeknek Ura: Agg férfiak és agg nõk ülnek majd Jeruzsálem utczáin, és kinek-kinek pálcza lesz kezében a napok sokasága miatt."));
husuperobject.biblemap.put("b38_8_5", new husuperobject(38,8,5,"És megtelnek a város utczái fiúkkal és leányokkal, a kik játszadoznak annak utczáin."));
husuperobject.biblemap.put("b38_8_6", new husuperobject(38,8,6,"Ezt mondja a Seregeknek Ura: Ha [ez] csoda lészen e nép maradékának szemei elõtt azokban a napokban, vajjon az én szemeim elõtt is csoda lészen-é? így szól a Seregeknek Ura."));
husuperobject.biblemap.put("b38_8_7", new husuperobject(38,8,7,"Ezt mondja a Seregeknek Ura: Ímé, én megszabadítom az én népemet a nap keltének földérõl és a nap nyugtának földérõl."));
husuperobject.biblemap.put("b38_8_8", new husuperobject(38,8,8,"És elhozom õket és Jeruzsálemben lakoznak, és népemmé lesznek, én pedig Istenökké leszek hûséggel és igazsággal."));
husuperobject.biblemap.put("b38_8_9", new husuperobject(38,8,9,"Ezt mondja a Seregeknek Ura: Erõsödjenek meg kezeitek, a kik hallottátok e napokban e beszédeket a próféták szájából, a kik [szóltak,] mikor megvetteték a Seregek Ura házának alapja, hogy megépíttessék a templom."));
husuperobject.biblemap.put("b38_8_10", new husuperobject(38,8,10,"Mert e napok elõtt nem volt az embernek bére, és a baromnak sem volt bére, sem a kimenõnek, sem a bejövõnek nem volt békessége a háborúság miatt, mert minden embert felindítottam: kit-kit az õ felebarátja ellen."));
husuperobject.biblemap.put("b38_8_11", new husuperobject(38,8,11,"De most nem olyan leszek e nép maradékához, mint az elébbi napokban voltam, így szól a Seregeknek Ura."));
husuperobject.biblemap.put("b38_8_12", new husuperobject(38,8,12,"Mert a vetés békességes [lészen,] a szõlõtõ megadja gyümölcsét, a föld is megadja termését, az egek is megadják harmatjokat, és örökössé teszem mindezeken e nép maradékát."));
husuperobject.biblemap.put("b38_8_13", new husuperobject(38,8,13,"És lészen, hogy a miképen átok valátok a pogányok között, oh Júda háza és Izráel háza: azonképen megszabadítlak titeket, és áldássá lesztek. Ne féljetek! Erõsödjenek meg kezeitek!"));
husuperobject.biblemap.put("b38_8_14", new husuperobject(38,8,14,"Mert ezt mondja a Seregeknek Ura: A miképen elgondoltam vala, hogy veszedelmet hozok reátok, mikor atyáitok megharagítottak vala engem, így szól a Seregeknek Ura, és nem könyörültem:"));
husuperobject.biblemap.put("b38_8_15", new husuperobject(38,8,15,"Azonképen megtértem [és] elgondoltam e napokban, hogy jót teszek Jeruzsálemmel és Júda házával; ne féljetek!"));
husuperobject.biblemap.put("b38_8_16", new husuperobject(38,8,16,"Ezek azok a dolgok, a melyeket cselekedjetek: Igazságot szóljon ki-ki az õ felebarátjával: igazságos és békességes ítélettel ítéljetek a ti kapuitokban."));
husuperobject.biblemap.put("b38_8_17", new husuperobject(38,8,17,"És senki ne gondoljon az õ szívében gonoszt az õ felebarátja ellen; s a hamis esküvést se szeressétek, mert ezek azok, a miket én mind gyûlölök, így szól az Úr."));
husuperobject.biblemap.put("b38_8_18", new husuperobject(38,8,18,"Majd szóla hozzám a Seregeknek Ura, mondván:"));
husuperobject.biblemap.put("b38_8_19", new husuperobject(38,8,19,"Ezt mondja a Seregeknek Ura: A negyedik [hónapnak] bõjtje, az ötödiknek bõjtje, a hetediknek bõjtje és a tizediknek bõjtje vígalommá, örvendezéssé és kedves ünnepekké lesznek Júda házában. Csak a hûséget és a békességet szeressétek."));
husuperobject.biblemap.put("b38_8_20", new husuperobject(38,8,20,"Ezt mondja a Seregeknek Ura: Még lesz [idõ,] a mikor népek jõnek el, és sok városoknak lakói."));
husuperobject.biblemap.put("b38_8_21", new husuperobject(38,8,21,"És egyiknek lakói a másikhoz mennek, mondván: Menten menjünk el az Úr orczájának engesztelésére, és a Seregek Urának keresésére; én is elmegyek!"));
husuperobject.biblemap.put("b38_8_22", new husuperobject(38,8,22,"És eljõnek sok népek és erõs nemzetek Jeruzsálembe a Seregek Urának keresésére, és az Úr orczájának engesztelésére."));
husuperobject.biblemap.put("b38_8_23", new husuperobject(38,8,23,"Ezt mondja a Seregeknek Ura: E napokban lesz az, hogy a minden nyelvû pogányok közül tíz ember ragad egy zsidó férfiúba s ragad annak ruhája szélébe, mondván: Hadd menjünk veletek, mert hallottuk, hogy veletek van az Isten!"));
husuperobject.biblemap.put("b38_9_1", new husuperobject(38,9,1,"Az Úr igéjének terhe a Kadrák földe ellen; Damaskus lesz pedig annak nyugvóhelye (mert az Úr szemmel tartja az embereket és Izráelnek minden törzsét);"));
husuperobject.biblemap.put("b38_9_2", new husuperobject(38,9,2,"És Hámát is, a mely szomszédos vele; Tírus és Sídon, noha igen okosak!"));
husuperobject.biblemap.put("b38_9_3", new husuperobject(38,9,3,"Várat épített magának Tírus, és annyi az ezüstje rakáson, mint a por, és az aranya, mint az utczák sara."));
husuperobject.biblemap.put("b38_9_4", new husuperobject(38,9,4,"Ímé szegénynyé teszi õt az Úr, és megrontja hatalmát a tengeren, magát pedig tûz emészti meg."));
husuperobject.biblemap.put("b38_9_5", new husuperobject(38,9,5,"Meglátja [ezt] Askalon és megretten; Gáza is és igen bánkódik; Ekron is, mert megszégyenült reménységében. Mert kivész a király Gázából, és Askalon lakatlan marad."));
husuperobject.biblemap.put("b38_9_6", new husuperobject(38,9,6,"Asdódban pedig idegenek laknak, és a Filiszteusok kevélységét megtöröm."));
husuperobject.biblemap.put("b38_9_7", new husuperobject(38,9,7,"Kivonszom a vért szájukból és útálatosságaikat fogaik közül, és õ is a mi Istenünké marad; és olyan lesz, mint egy fejedelem Júdában, Ekron pedig, mint a Jebuzeus."));
husuperobject.biblemap.put("b38_9_8", new husuperobject(38,9,8,"És tábort járok házam körül, [mint] a sereg ellen, az ide-oda kóborlók ellen, és nem megy át többé rajtok a sarczoló, mert most szemmel tartom õt."));
husuperobject.biblemap.put("b38_9_9", new husuperobject(38,9,9,"Örülj nagyon, Sionnak leánya, örvendezz, Jeruzsálem leánya! Ímé, jön néked a te királyod; igaz és szabadító õ; szegény és szamárháton ülõ, azaz nõstényszamárnak vemhén."));
husuperobject.biblemap.put("b38_9_10", new husuperobject(38,9,10,"És kivesztem a szekeret Efraimból és a lovat Jeruzsálembõl, kivesztem a harczi kézívet is, és békességet hirdet a pogányoknak; és uralkodik tengertõl tengerig, és a folyamtól a föld határáig."));
husuperobject.biblemap.put("b38_9_11", new husuperobject(38,9,11,"Sõt a veled való szövetségnek véréért a te foglyaidat is kibocsátom a kútból, a melyben nincs víz."));
husuperobject.biblemap.put("b38_9_12", new husuperobject(38,9,12,"Térjetek vissza az erõsséghez, reménységnek foglyai! Ma is azt hirdetem [néktek:] kétszeresen megfizetek néked!"));
husuperobject.biblemap.put("b38_9_13", new husuperobject(38,9,13,"Mert kifeszítem Júdát magamnak [mintegy] kézívet [és] megtöltöm Efraimot; és felindítom fiaidat, oh Sion, a te fiaid ellen, oh Jáván, és olyanná teszlek, mint a hõs fegyvere."));
husuperobject.biblemap.put("b38_9_14", new husuperobject(38,9,14,"És megjelen felettök az Úr, és nyila repül mint a villámlás; az Úr Isten kürtöt fuvall, és déli szelekben nyomul elõ."));
husuperobject.biblemap.put("b38_9_15", new husuperobject(38,9,15,"A Seregeknek Ura megoltalmazza õket; megemésztik és letapossák a parittya-köveket, és isznak [és] zajongnak, mint a bortól, és megtelnek, mint a csészék [és] mint az oltár szegletei."));
husuperobject.biblemap.put("b38_9_16", new husuperobject(38,9,16,"És megsegíti õket az Úr, az õ Istenök ama napon, mint az õ népének nyáját, és mint korona-kövek ragyognak az õ földén."));
husuperobject.biblemap.put("b38_9_17", new husuperobject(38,9,17,"Oh, mily nagy az õ jósága és mily nagy az õ kedvessége! Ifjakat tesz virágzóvá a gabona, és leányokat a must."));
husuperobject.biblemap.put("b38_10_1", new husuperobject(38,10,1,"Kérjetek esõt az Úrtól a késõi esõ idején! Az Úr villámlást szerez, és záporesõt ad nékik, [és] kinek-kinek füvet a mezõn."));
husuperobject.biblemap.put("b38_10_2", new husuperobject(38,10,2,"Mert a bálványok hazugságot szólnak, a varázslók pedig hamisságot látnak és üres álmokat beszélnek, hiábavalósággal vígasztalnak; azért elszélednek, mint a juhnyáj, a mely sanyarog, mert nincs pásztora."));
husuperobject.biblemap.put("b38_10_3", new husuperobject(38,10,3,"Haragra gerjedtem a pásztorok ellen, és megfenyítem a bakokat. Bizony megfenyíti a Seregeknek Ura az õ nyáját, a Júda házát, és olyanokká teszi õket, a milyen a harczra felékesített ló."));
husuperobject.biblemap.put("b38_10_4", new husuperobject(38,10,4,"Közülök támad a szegletkõ, közülök a szeg, közülök a harczi ív, közülök egyszersmind minden sarczoló."));
husuperobject.biblemap.put("b38_10_5", new husuperobject(38,10,5,"És olyanok lesznek, mint a hõsök, a kik az utczák sarát tapodják a harczban, és harczolnak, mert velök van az Úr, és megszégyenítik a lovon ülõket."));
husuperobject.biblemap.put("b38_10_6", new husuperobject(38,10,6,"És megerõsítem a Júda házát, és a József házát megsegítem, és visszahozom õket, mert szánom õket, és olyanokká lesznek, mintha el sem vetettem volna õket; mert én vagyok az Úr, az õ Istenök, és meghallgatom õket."));
husuperobject.biblemap.put("b38_10_7", new husuperobject(38,10,7,"Efraim is olyan lesz, mint egy hõs, és örvendeznek majd mintegy bortól [ittasodva,] és látják fiaik és örvendeznek; örvend az õ szívök az Úrban."));
husuperobject.biblemap.put("b38_10_8", new husuperobject(38,10,8,"Süvöltök nékik és egybegyûjtöm õket, mert megszabadítom õket, és megsokasulnak, a mint megsokasultak vala."));
husuperobject.biblemap.put("b38_10_9", new husuperobject(38,10,9,"És széthintem õket a népek között, hogy a messze földeken [is ]emlegessenek engem, és fiakat neveljenek és visszatérjenek."));
husuperobject.biblemap.put("b38_10_10", new husuperobject(38,10,10,"Mert visszatérítem õket, Égyiptom földérõl, Assiriából is összegyûjtöm õket, és behozom õket Gileád és Libánon földjére, és elég sem lesz nékik."));
husuperobject.biblemap.put("b38_10_11", new husuperobject(38,10,11,"És átvonulnak a nyomor tengerén, és megveri a tenger hullámait, és kiszáradnak a folyam örvényei, letöretik Assiriának kevélysége, és Égyiptom királyi pálczája elvész."));
husuperobject.biblemap.put("b38_10_12", new husuperobject(38,10,12,"És megerõsítem õket az Úrban, és az õ nevében járnak, így szól az Úr."));
husuperobject.biblemap.put("b38_11_1", new husuperobject(38,11,1,"Nyisd meg kapuidat, oh Libánon, hogy tûz emészszen czédrusaid közt!"));
husuperobject.biblemap.put("b38_11_2", new husuperobject(38,11,2,"Jajgass te cziprus, mert esik a czédrus, leomlott, a mi legjava! Jajgassatok ti Básán tölgyei, mert pusztul a rengeteg erdõ."));
husuperobject.biblemap.put("b38_11_3", new husuperobject(38,11,3,"Hangzik a pásztorok jajja, mert elpusztult az õ büszkeségök! Hangzik az oroszlán ordítása, mert elpusztult a Jordán kevélysége!"));
husuperobject.biblemap.put("b38_11_4", new husuperobject(38,11,4,"Ezt mondja az Úr, az én Istenem: Legeltesd a leölésre szánt juhokat,"));
husuperobject.biblemap.put("b38_11_5", new husuperobject(38,11,5,"A melyeket leölnek az õ tulajdonosaik, a nélkül, hogy bûnnek tartanák, eladóik pedig ezt mondják: Áldott az Úr, mert meggazdagodtam! és pásztoraik sem kimélik õket."));
husuperobject.biblemap.put("b38_11_6", new husuperobject(38,11,6,"Bizony nem kimélem többé e föld lakosait, ezt mondja az Úr; sõt ímé odaadok minden embert a felebarátja kezébe és az õ királya kezébe, és megrontják e földet, és nem szabadítom ki kezökbõl!"));
husuperobject.biblemap.put("b38_11_7", new husuperobject(38,11,7,"Legeltetém hát a leölésre szánt juhokat, azaz a megnyomorgatott juhokat, és választék magamnak két pálczát, az egyiket nevezém szépségnek, a másikat nevezém egyességnek; így legeltetém a juhokat."));
husuperobject.biblemap.put("b38_11_8", new husuperobject(38,11,8,"És három pásztort vertem el egy hónap alatt, mert elkeseredék a lelkem miattok, és az õ lelkök is megútála engem."));
husuperobject.biblemap.put("b38_11_9", new husuperobject(38,11,9,"És mondám: Nem õrizlek én titeket, haljon meg a halálra való és vágattassék ki a kivágni való, a megmaradottak pedig egyék meg egymásnak húsát."));
husuperobject.biblemap.put("b38_11_10", new husuperobject(38,11,10,"És vevém [egyik] pálczámat, a szépséget, és eltörém azt, hogy felbontsam az én szövetségemet, a melyet az összes népekkel kötöttem."));
husuperobject.biblemap.put("b38_11_11", new husuperobject(38,11,11,"És felbomla [az] azon a napon, és így tudták meg az elsanyargatott juhok, a kik ragaszkodnak vala hozzám, hogy az Úr dolga [ez]."));
husuperobject.biblemap.put("b38_11_12", new husuperobject(38,11,12,"És mondám nékik: Ha jónak tetszik néktek, adjátok meg az én béremet; ha pedig nem: hagyjátok abba! És harmincz ezüst pénzt fizettek béremül."));
husuperobject.biblemap.put("b38_11_13", new husuperobject(38,11,13,"És monda az Úr nékem: Vesd a fazekas elé! Nagy jutalom, a melyre becsültek engem. Vevém azért a harmincz ezüst pénzt, és vetém azt az Úrnak házába, a fazekas elé."));
husuperobject.biblemap.put("b38_11_14", new husuperobject(38,11,14,"Majd eltörém a másik pálczámat [is,] az egyességet, hogy felbontsam a testvérséget Júda között és Izráel között."));
husuperobject.biblemap.put("b38_11_15", new husuperobject(38,11,15,"És mondá az Úr nékem: Most már szerezz magadnak bolond pásztornak való szerszámot."));
husuperobject.biblemap.put("b38_11_16", new husuperobject(38,11,16,"Mert ímé, én pásztort állítok e földre, a ki az elveszetteket meg nem keresi, a gyöngével nem törõdik, a megtépettet meg nem gyógyítja, a jó karban levõt nem táplálja, a kövérinek húsát megeszi, és körmeiket széttördeli."));
husuperobject.biblemap.put("b38_11_17", new husuperobject(38,11,17,"Jaj a mihaszna pásztornak, a ki elhagyja a juhokat! Fegyver a karjára és jobb szemére. Karja szárazra száradjon és jobb szeme sötétre sötétedjék."));
husuperobject.biblemap.put("b38_12_1", new husuperobject(38,12,1,"Az Úr igéjének terhe Izráel ellen. Így szól az Úr, a ki az egeket kiterjesztette, a földet fundálta, és az ember keblébe lelket alkotott:"));
husuperobject.biblemap.put("b38_12_2", new husuperobject(38,12,2,"Ímé, én részegítõ pohárrá teszem Jeruzsálemet minden körülte való népnek; Júdának is az lesz, mikor ostromolják Jeruzsálemet."));
husuperobject.biblemap.put("b38_12_3", new husuperobject(38,12,3,"És azon a napon lesz, hogy nyomtatókõvé teszem Jeruzsálemet minden népnek; a ki emelni akarja azt, mind szakadva-szakad meg, noha összegyül ellene a föld minden pogánya."));
husuperobject.biblemap.put("b38_12_4", new husuperobject(38,12,4,"Azon a napon, így szól az Úr, megverek minden lovat rettegéssel, a lovagját pedig õrültséggel; de a Júda házát nyitott szemmel nézem, a népeknek pedig minden lovát vaksággal verem meg."));
husuperobject.biblemap.put("b38_12_5", new husuperobject(38,12,5,"És azt mondják szívökben Júda fejedelmei: Az én erõsségem Jeruzsálemnek lakói, az õ Istenökkel, a Seregek Urával."));
husuperobject.biblemap.put("b38_12_6", new husuperobject(38,12,6,"Azon a napon olyanokká teszem Júda fejedelmeit, mint a milyen a tüzes serpenyõ a fák között, és a milyen a tüzes fáklya a kévék között: megemésztenek jobb és bal felõl minden körülvaló népet; de Jeruzsálem tovább is a helyén marad Jeruzsálemben!"));
husuperobject.biblemap.put("b38_12_7", new husuperobject(38,12,7,"És megoltalmazza az Úr Júdának sátrait, [mint] azelõtt, hogy ne legyen nagyobb Dávid házának dicsõsége és Jeruzsálem lakosának dicsõsége, mint a Júdáé."));
husuperobject.biblemap.put("b38_12_8", new husuperobject(38,12,8,"Azon a napon oltalma lészen az Úr Jeruzsálem lakosának, és azon a napon olyan lesz köztök a legalábbvaló, mint Dávid, a Dávid háza pedig, mint az Isten, mint az Úrnak angyala õ elõttök."));
husuperobject.biblemap.put("b38_12_9", new husuperobject(38,12,9,"És azon a napon lesz, hogy kész leszek elveszteni minden pogányt, a kik Jeruzsálemre támadnak;"));
husuperobject.biblemap.put("b38_12_10", new husuperobject(38,12,10,"A Dávid házára és Jeruzsálem lakosaira pedig kiöntöm a kegyelemnek és könyörületességnek lelkét, és reám tekintenek, a kit átszegeztek, és siratják õt, a mint siratják az egyetlen fiút, és keseregnek utána, a mint keseregnek az elsõszülött után."));
husuperobject.biblemap.put("b38_12_11", new husuperobject(38,12,11,"Azon a napon nagy siralom lesz Jeruzsálemben, a milyen volt a hadadrimmoni siralom a Megiddo völgyében."));
husuperobject.biblemap.put("b38_12_12", new husuperobject(38,12,12,"És sír a föld: nemzetségek [és] nemzetségek külön; külön a Dávid házának nemzetsége, feleségeik is külön; külön a Nátán házának nemzetsége, és feleségeik is külön;"));
husuperobject.biblemap.put("b38_12_13", new husuperobject(38,12,13,"Külön a Lévi házának nemzetsége, és feleségeik is külön; külön a Sémei nemzetsége, feleségeik is külön."));
husuperobject.biblemap.put("b38_12_14", new husuperobject(38,12,14,"A többi nemzetségek mind; nemzetségek [és] nemzetségek külön, feleségeik is külön."));
husuperobject.biblemap.put("b38_13_1", new husuperobject(38,13,1,"Azon a napon kútfõ fakad a Dávid házának és Jeruzsálem lakosainak a bûn és tisztátalanság ellen."));
husuperobject.biblemap.put("b38_13_2", new husuperobject(38,13,2,"És lészen azon a napon, így szól a Seregeknek Ura: Kivesztem a bálványok neveit e földrõl, és emlegetni sem fogják többé; sõt a prófétákat és a fertelmes lelket is kiszaggatom e földrõl."));
husuperobject.biblemap.put("b38_13_3", new husuperobject(38,13,3,"És úgy lesz, ha prófétálni fog még valaki, azt mondják annak az õ apja és anyja, az õ szülõi: Ne élj, mert hazugságot szóltál az Úr nevében! És általverik õt az õ apja és anyja, az õ szülõi, az õ prófétálása közben."));
husuperobject.biblemap.put("b38_13_4", new husuperobject(38,13,4,"És azon a napon megszégyenülnek a próféták, kiki az õ látása miatt az õ prófétálásaik közben, és nem öltözködnek szõrös ruhába, hogy hazudjanak."));
husuperobject.biblemap.put("b38_13_5", new husuperobject(38,13,5,"Hanem ezt mondja [kiki:] Nem vagyok én próféta, szántóvetõ ember vagyok én, sõt más szolgájává lettem én gyermekségem óta."));
husuperobject.biblemap.put("b38_13_6", new husuperobject(38,13,6,"És ha mondja néki [valaki:] Micsoda ütések ezek a kezeiden? azt mondja: A miket az én barátaim házában ütöttek rajtam."));
husuperobject.biblemap.put("b38_13_7", new husuperobject(38,13,7,"Fegyver, serkenj fel az én pásztorom ellen és a férfiú ellen, a ki nékem társam! így szól a Seregeknek Ura. Verd meg a pásztort és elszélednek a juhok, én pedig a kicsinyek ellen fordítom kezemet."));
husuperobject.biblemap.put("b38_13_8", new husuperobject(38,13,8,"És lészen az egész földön, így szól az Úr: a két rész kivágattatik azon [és] meghal, de a harmadik megmarad rajta."));
husuperobject.biblemap.put("b38_13_9", new husuperobject(38,13,9,"És beviszem a harmadrészt a tûzbe, és megtisztítom õket, a mint tisztítják az ezüstöt és megpróbálom õket, a mint próbálják az aranyat; õ segítségül hívja az én nevemet és én felelni fogok néki; ezt mondom: Népem õ! Õ pedig ezt mondja: Az Úr az én Istenem!"));
husuperobject.biblemap.put("b38_14_1", new husuperobject(38,14,1,"Ímé, eljön az Úrnak napja, és a te prédádat felosztják benned."));
husuperobject.biblemap.put("b38_14_2", new husuperobject(38,14,2,"Mert minden népet ütközetre gyûjtök Jeruzsálemhez, és megszállják a várost, és kirabolják a házakat, megszeplõsítik az asszonyokat; és a város fele számkivetésbe megy, de a nép maradéka nem gyomláltatik ki a városból."));
husuperobject.biblemap.put("b38_14_3", new husuperobject(38,14,3,"Mert eljön az Úr, és harczol azok ellen a népek ellen, a mint harczolt vala ama napon, a harcznak napján."));
husuperobject.biblemap.put("b38_14_4", new husuperobject(38,14,4,"És azon a napon az Olajfák hegyére veti lábait, a mely szemben van Jeruzsálemmel napkelet felõl, és az Olajfák hegye közepén ketté válik, kelet felé és nyugot felé, igen nagy völgygyé, és a hegynek fele észak felé, fele pedig dél felé szakad."));
husuperobject.biblemap.put("b38_14_5", new husuperobject(38,14,5,"És az én hegyem völgyébe futtok, mert a hegyközi völgy Azálig nyúlik, és úgy futtok, a mint futottatok a földindulás elõl Uzziásnak, Júda királyának napjaiban. Bizony eljõ az Úr, az én Istenem, [és ]minden szent vele."));
husuperobject.biblemap.put("b38_14_6", new husuperobject(38,14,6,"És úgy lesz azon a napon: Nem lesz világosság, a ragyogó testek összezsugorodnak."));
husuperobject.biblemap.put("b38_14_7", new husuperobject(38,14,7,"De lesz egy nap, a melyet az Úr tud, se nappal, se éjszaka, és világosság lesz az estvének idején."));
husuperobject.biblemap.put("b38_14_8", new husuperobject(38,14,8,"És e napon lesz, hogy élõ vizek jõnek ki Jeruzsálembõl, felerészök a napkeleti tenger felé, felerészök pedig a nyugoti tenger felé, [és ]nyárban és télben [is úgy] lesz."));
husuperobject.biblemap.put("b38_14_9", new husuperobject(38,14,9,"És az Úr lesz az egész földnek királya, e napon egy Úr lészen, és a neve is egy."));
husuperobject.biblemap.put("b38_14_10", new husuperobject(38,14,10,"Az egész föld síksággá változik Gebától kezdve Rimmonig, déli irányban Jeruzsálem felé, és felmagasztaltatik és a maga helyén marad a Benjámin kapujától az elsõ kapu helyéig, a szegletkapuig, és a Hananéel tornyától a király sajtójáig."));
husuperobject.biblemap.put("b38_14_11", new husuperobject(38,14,11,"És lakni fognak benne, és nem éri többé pusztulás, és bátorságban lakoznak Jeruzsálemben."));
husuperobject.biblemap.put("b38_14_12", new husuperobject(38,14,12,"És ez lesz a csapás, a melylyel megcsapkod az Úr minden népet, a melyek Jeruzsálem ellen gyülekeznek: Megsenyved a húsok és pedig a míg lábaikon állnak, szemeik is megsenyvednek gödreikben, nyelvök is megsenyved szájokban."));
husuperobject.biblemap.put("b38_14_13", new husuperobject(38,14,13,"És azon a napon lesz, hogy az Úr nagy háborúságot támaszt közöttök, úgy, hogy kiki a maga társának kezét ragadja meg, és a maga társának keze ellen emeli fel kezét."));
husuperobject.biblemap.put("b38_14_14", new husuperobject(38,14,14,"Sõt még Júda is harczolni fog Jeruzsálem ellen, és összegyûjtetik a köröskörül lakó népek minden gazdagsága: arany, ezüst és igen sok ruha."));
husuperobject.biblemap.put("b38_14_15", new husuperobject(38,14,15,"És éppen olyan csapás lesz a lovakon, öszvéreken, tevéken, szamarakon és mindenféle barmokon, a melyek e táborban lesznek, a milyen ez a csapás."));
husuperobject.biblemap.put("b38_14_16", new husuperobject(38,14,16,"És lészen, hogy a kik megmaradnak mindama népek közül, a melyek Jeruzsálem ellen jõnek: esztendõrõl esztendõre mind felmennek, hogy hódoljanak a királynak, a Seregek Urának, és megünnepeljék a sátorok ünnepét."));
husuperobject.biblemap.put("b38_14_17", new husuperobject(38,14,17,"És lészen, hogy a ki nem megy fel e föld nemzetségei közül Jeruzsálembe, hogy hódoljon a királynak, a Seregek Urának: nem lészen azokra esõ."));
husuperobject.biblemap.put("b38_14_18", new husuperobject(38,14,18,"És ha nem megy fel, vagy nem jön fel az égyiptomi nemzetség, õ rájok sem lészen; [de] lészen az a csapás, a melylyel megcsapkodja az Úr a népeket, a kik nem mennek fel a sátorok ünnepét megünnepelni."));
husuperobject.biblemap.put("b38_14_19", new husuperobject(38,14,19,"Ez lészen Égyiptomnak büntetése, és mindama népek büntetése, a kik nem mennek fel a sátorok ünnepét megünnepelni."));
husuperobject.biblemap.put("b38_14_20", new husuperobject(38,14,20,"Azon a napon a lovak csengettyûin is ez lesz: Az Úrnak szenteltetett. És a fazekak az Úrnak házában olyanokká lesznek, mint az oltár elõtt való medenczék."));
husuperobject.biblemap.put("b38_14_21", new husuperobject(38,14,21,"És Jeruzsálemben és Júdában minden fazék a Seregek Urának szenteltetik, és eljõnek mind, a kik áldozni akarnak, és választanak közülök és fõznek azokban; és nem lészen többé Kananeus a Seregek Urának házában e napon."));

}

}