package hu.bible;

public class hubible45 {

public hubible45() {

putmapbible45();

}

private void putmapbible45() {

husuperobject.biblemap.put("b45_1_1", new husuperobject(45,1,1,"Pál, Jézus Krisztusnak szolgája, elhívott apostol, elválasztva Isten evangyéliomá[nak hirdetésére.]"));
husuperobject.biblemap.put("b45_1_2", new husuperobject(45,1,2,"Melyet eleve megígért az õ prófétái által a szentírásokban,"));
husuperobject.biblemap.put("b45_1_3", new husuperobject(45,1,3,"Az õ Fia felõl, a ki Dávid magvából lett test szerint,"));
husuperobject.biblemap.put("b45_1_4", new husuperobject(45,1,4,"A ki megbizonyíttatott hatalmasan Isten Fiának a szentség Lelke szerint, a halálból való feltámadás által, a mi Urunk Jézus Krisztus felõl,"));
husuperobject.biblemap.put("b45_1_5", new husuperobject(45,1,5,"A ki által vettük a kegyelmet és az apostolságot a hitben való engedelmességnek okáért, minden pogányok között, az õ nevéért;"));
husuperobject.biblemap.put("b45_1_6", new husuperobject(45,1,6,"Kik között vagytok ti is, Jézus Krisztusnak hivatalosai:"));
husuperobject.biblemap.put("b45_1_7", new husuperobject(45,1,7,"Mindeneknek, a kik Rómában vagytok, Isten szerelmeseinek, hivatalos szenteknek: Kegyelem néktek és békesség Istentõl, a mi Atyánktól és az Úr Jézus Krisztustól."));
husuperobject.biblemap.put("b45_1_8", new husuperobject(45,1,8,"Elõször hálát adok az én Istenemnek a Jézus Krisztus által mindnyájatokért, hogy a ti hiteteknek az egész világon híre van;"));
husuperobject.biblemap.put("b45_1_9", new husuperobject(45,1,9,"Mert bizonyságom nékem az Isten, kinek lelkem szerint szolgálok az õ Fiának evangyéliomában, hogy szüntelen emlékezem felõletek,"));
husuperobject.biblemap.put("b45_1_10", new husuperobject(45,1,10,"Imádkozásaimban mindenkor könyörögvén, vajha egyszer már jó szerencsés út adódnék nékem Istennek akaratából, hogy hozzátok mehessek;"));
husuperobject.biblemap.put("b45_1_11", new husuperobject(45,1,11,"Mert kívánlak titeket látni, hogy valami lelki ajándékot közölhessek veletek a ti megerõsítésetekre,"));
husuperobject.biblemap.put("b45_1_12", new husuperobject(45,1,12,"Azaz, hogy együtt felbuzduljunk ti nálatok egymás hite által, a tiétek meg az enyém által."));
husuperobject.biblemap.put("b45_1_13", new husuperobject(45,1,13,"Nem akarom pedig, hogy ne tudjátok atyámfiai, hogy én gyakran elvégeztem magamban, hogy elmegyek hozzátok (de mindez ideig megakadályoztattam), hogy köztetek is nyerjek valami lelki gyümölcsöt, mint a többi pogányok közt is."));
husuperobject.biblemap.put("b45_1_14", new husuperobject(45,1,14,"Mind a görögöknek, mind a barbároknak, mind a bölcseknek, mind a tudatlanoknak köteles vagyok."));
husuperobject.biblemap.put("b45_1_15", new husuperobject(45,1,15,"Azért a mi rajtam áll, kész vagyok néktek is, a kik Rómában vagytok, az evangyéliomot hirdetni."));
husuperobject.biblemap.put("b45_1_16", new husuperobject(45,1,16,"Mert nem szégyenlem a Krisztus evangyéliomát; mert Istennek hatalma az minden hívõnek idvességére, zsidónak elõször meg görögnek."));
husuperobject.biblemap.put("b45_1_17", new husuperobject(45,1,17,"Mert az Istennek igazsága jelentetik ki abban hitbõl hitbe, miképen meg van írva: Az igaz ember pedig hitbõl él."));
husuperobject.biblemap.put("b45_1_18", new husuperobject(45,1,18,"Mert nyilván van az Istennek haragja mennybõl, az embereknek minden hitetlensége és hamissága ellen, kik az igazságot hamissággal feltartóztatják."));
husuperobject.biblemap.put("b45_1_19", new husuperobject(45,1,19,"Mert a mi az Isten felõl tudható nyilván van õ bennök; mert az Isten megjelentette nékik:"));
husuperobject.biblemap.put("b45_1_20", new husuperobject(45,1,20,"Mert a mi Istenben láthatatlan, tudniillik az õ örökké való hatalma és istensége, a világ teremtésétõl fogva az õ alkotásaiból megértetvén megláttatik; úgy, hogy õk menthetetlenek."));
husuperobject.biblemap.put("b45_1_21", new husuperobject(45,1,21,"Mert bár az Istent megismerték, mindazáltal nem mint Istent dicsõítették õt, sem néki hálákat nem adtak; hanem az õ okoskodásaikban hiábavalókká lettek, és az õ balgatag szívök megsötétedett."));
husuperobject.biblemap.put("b45_1_22", new husuperobject(45,1,22,"Magokat bölcseknek vallván, balgatagokká lettek;"));
husuperobject.biblemap.put("b45_1_23", new husuperobject(45,1,23,"És az örökkévaló Istennek dicsõségét felcserélték a mulandó embereknek és madaraknak és négylábú állatoknak és csúszó-mászó állatoknak képmásával."));
husuperobject.biblemap.put("b45_1_24", new husuperobject(45,1,24,"Annakokáért adta is õket az Isten szívök kivánságaiban tisztátalanságra, hogy egymás testét megszeplõsítsék;"));
husuperobject.biblemap.put("b45_1_25", new husuperobject(45,1,25,"Mint a kik az Isten igazságát hazugsággá változtatták, és a teremtett dolgokat tisztelték és szolgálták a teremtõ helyett, a ki mind örökké áldott. Ámen."));
husuperobject.biblemap.put("b45_1_26", new husuperobject(45,1,26,"Annakokáért adta õket az Isten tisztátalan indulatokra; mert az õ asszonynépeik is elváltoztatták a természet folyását természetellenesre:"));
husuperobject.biblemap.put("b45_1_27", new husuperobject(45,1,27,"Hasonlóképen a férfiak is elhagyván az asszonynéppel való természetes élést, egymásra gerjedtek bujaságukban, férfiak férfiakkal fertelmeskedvén, és az õ tévelygésöknek méltó jutalmát elvevén önmagokban."));
husuperobject.biblemap.put("b45_1_28", new husuperobject(45,1,28,"És a miképen nem méltatták az Istent arra, hogy ismeretökben megtartsák, azonképen oda adták õket az Isten méltatlan gondolkozásra, hogy illetlen dolgokat cselekedjenek;"));
husuperobject.biblemap.put("b45_1_29", new husuperobject(45,1,29,"A kik teljesek minden hamissággal, paráznasággal, gonoszsággal, kapzsisággal, rosszasággal; rakvák, írigységgel, gyilkossággal, versengéssel, álnoksággal, rossz erkölcscsel;"));
husuperobject.biblemap.put("b45_1_30", new husuperobject(45,1,30,"Súsárlók, rágalmazók, istengyûlölõk, dölyfösek, kevélyek, dicsekedõk, rosszban mesterkedõk, szüleiknek engedetlenek,"));
husuperobject.biblemap.put("b45_1_31", new husuperobject(45,1,31,"Balgatagok, összeférhetetlenek, szeretet nélkül valók, engesztelhetetlenek, irgalmatlanok."));
husuperobject.biblemap.put("b45_1_32", new husuperobject(45,1,32,"Kik jóllehet az Isten végzését ismerik, hogy a kik ilyeneket cselekesznek, méltók a halálra, mégis nemcsak cselekszik azokat, hanem az akképen cselekvõkkel egyet is értenek."));
husuperobject.biblemap.put("b45_2_1", new husuperobject(45,2,1,"Annakokáért menthetetlen vagy óh ember, bárki légy, a ki ítélsz: mert a miben mást megítélsz, önmagadat kárhoztatod; mivel ugyanazokat míveled te, a ki ítélsz."));
husuperobject.biblemap.put("b45_2_2", new husuperobject(45,2,2,"Tudjuk pedig, hogy az Istennek ítélete igazság szerint van azokon, a kik ilyeneket cselekesznek."));
husuperobject.biblemap.put("b45_2_3", new husuperobject(45,2,3,"Vagy azt gondolod, óh ember, a ki megítéled azokat, a kik ilyeneket cselekesznek, és te is azokat cselekszed, hogy te elkerülöd az Istennek ítéletét?"));
husuperobject.biblemap.put("b45_2_4", new husuperobject(45,2,4,"Avagy megveted az õ jóságának, elnézésének és hosszútûrésének gazdagságát, nem tudván, hogy az Istennek jósága téged megtérésre indít?"));
husuperobject.biblemap.put("b45_2_5", new husuperobject(45,2,5,"De te a te keménységed és meg nem tért szíved szerint gyûjtesz magadnak haragot a haragnak és az Isten igaz ítélete kijelentésének napjára."));
husuperobject.biblemap.put("b45_2_6", new husuperobject(45,2,6,"A ki megfizet mindenkinek az õ cselekedetei szerint:"));
husuperobject.biblemap.put("b45_2_7", new husuperobject(45,2,7,"Azoknak, a kik a jó cselekedetben való állhatatossággal dicsõséget, tisztességet és halhatatlanságot keresnek, örök élettel;"));
husuperobject.biblemap.put("b45_2_8", new husuperobject(45,2,8,"Azoknak pedig, a kik versengõk és a kik nem engednek az igazságnak, hanem engednek a hamisságnak, búsulással és haraggal."));
husuperobject.biblemap.put("b45_2_9", new husuperobject(45,2,9,"Nyomorúság és ínség minden gonoszt cselekedõ ember lelkének, zsidónak elõször meg görögnek;"));
husuperobject.biblemap.put("b45_2_10", new husuperobject(45,2,10,"Dicsõség pedig, tisztesség és békesség minden jót cselekedõnek, zsidónak elõször meg görögnek:"));
husuperobject.biblemap.put("b45_2_11", new husuperobject(45,2,11,"Mert nincsen Isten elõtt személyválogatás."));
husuperobject.biblemap.put("b45_2_12", new husuperobject(45,2,12,"Mert a kik törvény nélkül vétkeztek, törvény nélkül vesznek is el: és a kik a törvény alatt vétkeztek, törvény által ítéltetnek meg,"));
husuperobject.biblemap.put("b45_2_13", new husuperobject(45,2,13,"(Mert nem azok igazak Isten elõtt, a kik a törvényt hallgatják, hanem azok fognak megigazulni, a kik a törvényt betöltik."));
husuperobject.biblemap.put("b45_2_14", new husuperobject(45,2,14,"Mert mikor a pogányok, a kiknek törvényök nincsen, természettõl a törvény dolgait cselekszik, akkor õk, törvényök nem lévén, önmagoknak törvényök:"));
husuperobject.biblemap.put("b45_2_15", new husuperobject(45,2,15,"Mint a kik megmutatják, hogy a törvény cselekedete be van írva az õ szívökbe, egyetemben bizonyságot tévén arról az õ lelkiismeretök és gondolataik, a melyek egymást kölcsönösen vádolják vagy mentegetik.)"));
husuperobject.biblemap.put("b45_2_16", new husuperobject(45,2,16,"Azon a napon, melyen az Isten megítéli az emberek titkait az én evangyéliomom szerint a Jézus Krisztus által."));
husuperobject.biblemap.put("b45_2_17", new husuperobject(45,2,17,"Ímé, te zsidónak neveztetel, és a törvényre támaszkodol, és Istennel dicsekedel."));
husuperobject.biblemap.put("b45_2_18", new husuperobject(45,2,18,"És ismered az õ akaratát, és választást tudsz tenni azok között, a melyek különböznek [attól,] mivelhogy a törvénybõl megtaníttattál;"));
husuperobject.biblemap.put("b45_2_19", new husuperobject(45,2,19,"És azt hiszed magadról, hogy te a vakoknak vezetõje, a sötétségben levõknek világossága,"));
husuperobject.biblemap.put("b45_2_20", new husuperobject(45,2,20,"A balgatagok tanítója, a kiskorúak mestere vagy, bírván a törvényben az ismeret és igazság formáját."));
husuperobject.biblemap.put("b45_2_21", new husuperobject(45,2,21,"A ki azért mást tanítasz, magadat nem tanítod-é? a ki azt hirdeted, hogy ne lopj, lopsz-é?"));
husuperobject.biblemap.put("b45_2_22", new husuperobject(45,2,22,"A ki azt mondod, ne paráználkodjál, paráználkodol-é? a ki útálod a bálványokat, szentségtörõ vagy-é?"));
husuperobject.biblemap.put("b45_2_23", new husuperobject(45,2,23,"Ki a törvényben dicsekszel, a törvénynek megrontása által az Istent gyalázod-é?"));
husuperobject.biblemap.put("b45_2_24", new husuperobject(45,2,24,"Mert az Istennek neve miattatok káromoltatik a pogányok között, a mint meg van írva."));
husuperobject.biblemap.put("b45_2_25", new husuperobject(45,2,25,"Mert használ ugyan a körülmetélkedés, ha a törvényt megtartod; de ha a törvényt áthágod, a te körülmetélkedésed körülmetéletlenséggé lett."));
husuperobject.biblemap.put("b45_2_26", new husuperobject(45,2,26,"Ha tehát a körülmetéletlen pogány megtartja a törvénynek parancsolatait, az õ körülmetéletlensége nem körülmetélkedésül tulajdoníttatik-é néki?"));
husuperobject.biblemap.put("b45_2_27", new husuperobject(45,2,27,"És a természettõl fogva körülmetéletlen ember, ha a törvényt megtartja, megítél téged, a ki a betû és körülmetélkedés mellett is a törvényeknek megrontója vagy."));
husuperobject.biblemap.put("b45_2_28", new husuperobject(45,2,28,"Mert nem az a zsidó, a ki külsõképen az; sem nem az a körülmetélés, a mi a testen külsõképen van:"));
husuperobject.biblemap.put("b45_2_29", new husuperobject(45,2,29,"Hanem az a zsidó, a ki belsõképen az; és a szívnek lélekben, nem betû szerint való körülmetélése [az igazi körülmetélkedés;] a melynek dícsérete nem emberektõl, hanem Istentõl van."));
husuperobject.biblemap.put("b45_3_1", new husuperobject(45,3,1,"Mi tekintetben különb hát a zsidó? vagy micsoda haszna van a körülmetélkedésnek?"));
husuperobject.biblemap.put("b45_3_2", new husuperobject(45,3,2,"Minden tekintetben sok. Mindenek elõtt, hogy az Isten reájok bízta az õ beszédeit."));
husuperobject.biblemap.put("b45_3_3", new husuperobject(45,3,3,"De hát hogy ha némelyek nem hittek? Vajjon azoknak hitetlensége nem teszi-é hiábavalóvá az Istennek hûségét?"));
husuperobject.biblemap.put("b45_3_4", new husuperobject(45,3,4,"Távol legyen. Sõt inkább az Isten legyen igaz, minden ember pedig hazug, a mint meg van írva: Hogy igaznak ítéltessél a te beszédeidben, és gyõzedelmes légy, mikor vádolnak téged."));
husuperobject.biblemap.put("b45_3_5", new husuperobject(45,3,5,"Ha pedig a mi igazságtalanságunk az Istennek igazságát mutatja meg, mit mondjunk? Vajjon igazságtalan-é az Isten, hogy minket büntet? Emberi módon szólok."));
husuperobject.biblemap.put("b45_3_6", new husuperobject(45,3,6,"Távol legyen! Mert akkor mi módon ítéli meg az Isten a világot?"));
husuperobject.biblemap.put("b45_3_7", new husuperobject(45,3,7,"Mert ha az Istennek igazsága az én hazugságom által öregbült az õ dicsõségére, miért kárhoztattatom még én is, mint bûnös?"));
husuperobject.biblemap.put("b45_3_8", new husuperobject(45,3,8,"Sõt inkább ne cselekedjük-é a rosszat, hogy [abból] jó származzék? - a mint minket rágalmaznak, és a mint némelyek mondogatják, hogy mi így beszélünk, a kiknek kárhoztatása igazságos."));
husuperobject.biblemap.put("b45_3_9", new husuperobject(45,3,9,"Micsoda tehát? Különbek vagyunk-é? Semmiképen nem. Mert az elébb megmutattuk nyilván, hogy zsidók és görögök mindnyájan bûn alatt vannak;"));
husuperobject.biblemap.put("b45_3_10", new husuperobject(45,3,10,"A mint meg van írva, hogy nincsen csak egy igaz is;"));
husuperobject.biblemap.put("b45_3_11", new husuperobject(45,3,11,"Nincs, a ki megértse, nincs, a ki keresse az Istent."));
husuperobject.biblemap.put("b45_3_12", new husuperobject(45,3,12,"Mindnyájan elhajlottak, egyetemben haszontalanokká lettek; nincs, a ki jót cselekedjék, nincsen csak egy is."));
husuperobject.biblemap.put("b45_3_13", new husuperobject(45,3,13,"Nyitott sír az õ torkuk; nyelvökkel álnokságot szólnak; áspis kígyó mérge van ajkaik alatt."));
husuperobject.biblemap.put("b45_3_14", new husuperobject(45,3,14,"Szájok telve átkozódással és keserûséggel."));
husuperobject.biblemap.put("b45_3_15", new husuperobject(45,3,15,"Lábaik gyorsak a vérontásra."));
husuperobject.biblemap.put("b45_3_16", new husuperobject(45,3,16,"Útjaikon romlás és nyomorúság van."));
husuperobject.biblemap.put("b45_3_17", new husuperobject(45,3,17,"És a békességnek útját nem ismerik."));
husuperobject.biblemap.put("b45_3_18", new husuperobject(45,3,18,"Nincs isteni félelem az õ szemök elõtt."));
husuperobject.biblemap.put("b45_3_19", new husuperobject(45,3,19,"Tudjuk pedig, hogy a mit a törvény mond, azoknak mondja, a kik a törvény alatt vannak; hogy minden száj bedugassék, és az egész világ Isten ítélete alá essék."));
husuperobject.biblemap.put("b45_3_20", new husuperobject(45,3,20,"Annakokáért a törvénynek cselekedeteibõl egy test sem igazul meg õ elõtte: mert a bûn ismerete a törvény által vagyon."));
husuperobject.biblemap.put("b45_3_21", new husuperobject(45,3,21,"Most pedig törvény nélkül jelent meg az Istennek igazsága, a melyrõl tanúbizonyságot tesznek a törvény és a próféták;"));
husuperobject.biblemap.put("b45_3_22", new husuperobject(45,3,22,"Istennek igazsága pedig a Jézus Krisztusban való hit által mindazokhoz és mindazoknak, a kik hisznek. Mert nincs különbség,"));
husuperobject.biblemap.put("b45_3_23", new husuperobject(45,3,23,"Mert mindnyájan vétkeztek, és szûkölködnek az Isten dicsõsége nélkül."));
husuperobject.biblemap.put("b45_3_24", new husuperobject(45,3,24,"Megigazulván ingyen az õ kegyelmébõl a Krisztus Jézusban való váltság által,"));
husuperobject.biblemap.put("b45_3_25", new husuperobject(45,3,25,"Kit az Isten eleve rendelt engesztelõ áldozatul, hit által, az õ vérében, hogy megmutassa az õ igazságát az elõbb elkövetett bûnöknek elnézése miatt,"));
husuperobject.biblemap.put("b45_3_26", new husuperobject(45,3,26,"Az Isten hosszútûrésénél fogva, az õ igazságának megbizonyítására, a mostani idõben, hogy igaz legyen Õ és megigazítsa azt, a ki a Jézus hitébõl való."));
husuperobject.biblemap.put("b45_3_27", new husuperobject(45,3,27,"Hol van tehát a dicsekedés? Kirekesztetett. Mely törvény által? A cselekedeteké által? Nem; hanem a hit törvénye által."));
husuperobject.biblemap.put("b45_3_28", new husuperobject(45,3,28,"Azt tartjuk tehát, hogy az ember hit által igazul meg, a törvény cselekedetei nélkül."));
husuperobject.biblemap.put("b45_3_29", new husuperobject(45,3,29,"Avagy Isten csak a zsidóké-e? Avagy nem a pogányoké is? Bizony a pogányoké is."));
husuperobject.biblemap.put("b45_3_30", new husuperobject(45,3,30,"Mivelhogy egy az Isten, a ki megigazítja a zsidót hitbõl és a pogányt hit által."));
husuperobject.biblemap.put("b45_3_31", new husuperobject(45,3,31,"A törvényt tehát hiábavalóvá tesszük-é a hit által? Távol legyen! Sõt inkább a törvényt megerõsítjük."));
husuperobject.biblemap.put("b45_4_1", new husuperobject(45,4,1,"Mit mondunk tehát, hogy Ábrahám a mi atyánk nyert volna test szerint?"));
husuperobject.biblemap.put("b45_4_2", new husuperobject(45,4,2,"Mert ha Ábrahám cselekedetekbõl igazult meg, van mivel dicsekedjék, de nem az Isten elõtt."));
husuperobject.biblemap.put("b45_4_3", new husuperobject(45,4,3,"Mert mit mond az írás: Hitt pedig Ábrahám az Istennek, és tulajdoníttaték az õ néki igazságul."));
husuperobject.biblemap.put("b45_4_4", new husuperobject(45,4,4,"Annak pedig, a ki munkálkodik, a jutalom nem tulajdoníttatik kegyelembõl, hanem tartozás szerint;"));
husuperobject.biblemap.put("b45_4_5", new husuperobject(45,4,5,"Ellenben annak, a ki nem munkálkodik, hanem hisz abban, a ki az istentelent megigazítja, az õ hite tulajdoníttatik igazságul."));
husuperobject.biblemap.put("b45_4_6", new husuperobject(45,4,6,"A mint Dávid is boldognak mondja azt az embert, a kinek az Isten igazságot tulajdonít cselekedetek nélkül."));
husuperobject.biblemap.put("b45_4_7", new husuperobject(45,4,7,"Boldogok, a kiknek megbocsáttattak az õ hamisságaik, és a kiknek elfedeztettek az õ bûneik."));
husuperobject.biblemap.put("b45_4_8", new husuperobject(45,4,8,"Boldog ember az, a kinek az Úr bûnt nem tulajdonít."));
husuperobject.biblemap.put("b45_4_9", new husuperobject(45,4,9,"Ez a boldogság tehát a zsidónak, vagy a pogánynak is [tulajdoníttatik- ]é? Mert azt mondjuk, hogy Ábrahámnak a hit tulajdoníttaték igazságul."));
husuperobject.biblemap.put("b45_4_10", new husuperobject(45,4,10,"Miképen tulajdoníttaték tehát? Körülmetélt vagy körülmetéletlen állapotában? Nem körülmetélt, hanem körülmetéletlen állapotában."));
husuperobject.biblemap.put("b45_4_11", new husuperobject(45,4,11,"És a körülmetélkedés jegyét körülmetéletlenségében [tanusított] hite igazságának pecsétjéül nyerte: hogy atyja legyen mindazoknak, a kik körülmetéletlen létökre hisznek, hogy azoknak is tulajdoníttassék az igazság;"));
husuperobject.biblemap.put("b45_4_12", new husuperobject(45,4,12,"És [hogy] atyja [legyen] a körülmetélteknek is, azoknak, a kik nemcsak körülmetélkednek, hanem követik is a mi atyánknak Ábrahámnak körülmetéletlenségében [tanusított] hitének nyomdokait."));
husuperobject.biblemap.put("b45_4_13", new husuperobject(45,4,13,"Mert nem a törvény által adatott az ígéret Ábrahámnak, vagy az õ magvának, hogy e világnak örököse lesz, hanem a hitnek igazsága által."));
husuperobject.biblemap.put("b45_4_14", new husuperobject(45,4,14,"Mert ha azok az örökösök, kik a törvénybõl valók, hiábavalóvá lett a hit, és haszontalanná az ígéret:"));
husuperobject.biblemap.put("b45_4_15", new husuperobject(45,4,15,"Mert a törvény haragot nemz: a hol pedig nincsen törvény, ott törvény ellen való cselekedet sincsen."));
husuperobject.biblemap.put("b45_4_16", new husuperobject(45,4,16,"Azért hitbõl, hogy kegyelembõl [legyen;] hogy erõs legyen az ígéret az egész magnak; nemcsak a törvénybõl valónak, hanem az Ábrahám hitébõl valónak is, a ki mindnyájunknak atyánk"));
husuperobject.biblemap.put("b45_4_17", new husuperobject(45,4,17,"(A mint meg van írva, hogy sok nép atyjává tettelek téged ) az elõtt, az Isten elõtt, a kiben hitt, a ki a holtakat megeleveníti, és azokat, a melyek nincsenek, elõszólítja mint meglevõket."));
husuperobject.biblemap.put("b45_4_18", new husuperobject(45,4,18,"A ki reménység ellenére reménykedve hitte, hogy sok népnek atyjává lesz, a szerint, a mint megmondatott: Így lészen a te magod."));
husuperobject.biblemap.put("b45_4_19", new husuperobject(45,4,19,"És hitében erõs lévén, nem gondolt az õ már elhalt testére, mintegy százesztendõs lévén, sem Sárának elhalt méhére;"));
husuperobject.biblemap.put("b45_4_20", new husuperobject(45,4,20,"Az Istennek ígéretében sem kételkedett hitetlenséggel, hanem erõs volt a hitben, dicsõséget adván az Istennek,"));
husuperobject.biblemap.put("b45_4_21", new husuperobject(45,4,21,"És teljesen elhitte, hogy a mit õ ígért, meg is cselekedheti."));
husuperobject.biblemap.put("b45_4_22", new husuperobject(45,4,22,"Azért is tulajdoníttaték néki igazságul."));
husuperobject.biblemap.put("b45_4_23", new husuperobject(45,4,23,"De nemcsak õ érette iratott meg, hogy tulajdoníttaték néki [igazságul,]"));
husuperobject.biblemap.put("b45_4_24", new husuperobject(45,4,24,"Hanem mi érettünk is, a kiknek majd tulajdoníttatik, azoknak tudniillik, a kik hisznek Abban, a ki feltámasztotta a mi Urunkat a Jézust a halálból,"));
husuperobject.biblemap.put("b45_4_25", new husuperobject(45,4,25,"Ki a mi bûneinkért [halálra] adatott, és feltámasztatott a mi megigazulásunkért."));
husuperobject.biblemap.put("b45_5_1", new husuperobject(45,5,1,"Megigazulván azért hit által, békességünk van Istennel, a mi Urunk Jézus Krisztus által,"));
husuperobject.biblemap.put("b45_5_2", new husuperobject(45,5,2,"A ki által van a menetelünk is hitben ahhoz a kegyelemhez, a melyben állunk; és dicsekedünk az Isten dicsõségének reménységében."));
husuperobject.biblemap.put("b45_5_3", new husuperobject(45,5,3,"Nemcsak pedig, hanem dicsekedünk a háborúságokban is, tudván, hogy a háborúság békességes tûrést nemz,"));
husuperobject.biblemap.put("b45_5_4", new husuperobject(45,5,4,"A békességes tûrés pedig próbatételt, a próbatétel pedig reménységet,"));
husuperobject.biblemap.put("b45_5_5", new husuperobject(45,5,5,"A reménység pedig nem szégyenít meg; mert az Istennek szerelme kitöltetett a mi szívünkbe a Szent Lélek által, ki adatott nékünk."));
husuperobject.biblemap.put("b45_5_6", new husuperobject(45,5,6,"Mert Krisztus, mikor még erõtelenek valánk, a maga idejében meghalt a gonoszokért."));
husuperobject.biblemap.put("b45_5_7", new husuperobject(45,5,7,"Bizonyára igazért [is] alig hal meg valaki; ám a jóért talán csak meg merne halni valaki."));
husuperobject.biblemap.put("b45_5_8", new husuperobject(45,5,8,"Az Isten pedig a mi hozzánk való szerelmét abban mutatta meg, hogy mikor még bûnösök voltunk, Krisztus érettünk meghalt."));
husuperobject.biblemap.put("b45_5_9", new husuperobject(45,5,9,"Minekutána azért most megigazultunk az õ vére által, sokkal inkább megtartatunk a harag ellen õ általa."));
husuperobject.biblemap.put("b45_5_10", new husuperobject(45,5,10,"Mert ha, mikor ellenségei voltunk, megbékéltünk Istennel az õ Fiának halála által, sokkal inkább megtartatunk az õ élete által minekutána megbékéltünk vele."));
husuperobject.biblemap.put("b45_5_11", new husuperobject(45,5,11,"Nemcsak pedig, hanem dicsekedünk is az Istenben a mi Urunk Jézus Krisztus által, a ki által most a megbékélést nyertük."));
husuperobject.biblemap.put("b45_5_12", new husuperobject(45,5,12,"Annakokáért, miképen egy ember által jött be a világra a bûn és a bûn által a halál, és akképen a halál minden emberre elhatott, mivelhogy mindenek vétkeztek;"));
husuperobject.biblemap.put("b45_5_13", new husuperobject(45,5,13,"Mert a törvényig vala bûn a világon; a bûn azonban nem számíttatik be, ha nincsen törvény."));
husuperobject.biblemap.put("b45_5_14", new husuperobject(45,5,14,"Úgyde a halál uralkodott Ádámtól Mózesig azokon is, a kik nem az Ádám esetének hasonlatossága szerint vétkeztek, a ki ama következendõnek kiábrázolása vala."));
husuperobject.biblemap.put("b45_5_15", new husuperobject(45,5,15,"De a kegyelmi ajándék nem úgy [van,] mint a bûneset; mert ha amaz egynek esete miatt sokan haltak meg, az Isten kegyelme és a kegyelembõl való ajándék, mely az egy ember Jézus Krisztusé, sokkal inkább elhatott sokakra."));
husuperobject.biblemap.put("b45_5_16", new husuperobject(45,5,16,"És az ajándék sem úgy [van,] mint egy vétkezõ által; mert az ítélet egybõl [lett] kárhozottá, az ajándék pedig sok bûnbõl [van] igazulásra."));
husuperobject.biblemap.put("b45_5_17", new husuperobject(45,5,17,"Mert ha az egynek bûnesete miatt uralkodott a halál az egy által: sokkal inkább az életben uralkodnak az egy Jézus Krisztus által azok, kik a kegyelemnek és az igazság ajándékának bõvölködésében részesültek."));
husuperobject.biblemap.put("b45_5_18", new husuperobject(45,5,18,"Bizonyára azért, miképen egynek bûnesete által minden emberre [elhatott] a kárhozat: azonképen egynek igazsága által minden emberre [elhatott] az életnek megigazulása."));
husuperobject.biblemap.put("b45_5_19", new husuperobject(45,5,19,"Mert miképen egy embernek engedetlensége által sokan bûnösökké lettek: azonképen egynek engedelmessége által sokan igazakká lesznek."));
husuperobject.biblemap.put("b45_5_20", new husuperobject(45,5,20,"A törvény pedig bejött, hogy a bûn megnövekedjék; de a hol megnövekedik a bûn, ott a kegyelem sokkal inkább bõvölködik:"));
husuperobject.biblemap.put("b45_5_21", new husuperobject(45,5,21,"Hogy miképen uralkodott a bûn a halálra, azonképen a kegyelem is uralkodjék igazság által az örök életre a mi Urunk Jézus Krisztus által."));
husuperobject.biblemap.put("b45_6_1", new husuperobject(45,6,1,"Mit mondunk tehát? Megmaradjunk-é a bûnben, hogy a kegyelem annál nagyobb legyen?"));
husuperobject.biblemap.put("b45_6_2", new husuperobject(45,6,2,"Távol legyen: a kik meghaltunk a bûnnek, mimódon élnénk még abban?"));
husuperobject.biblemap.put("b45_6_3", new husuperobject(45,6,3,"Avagy nem tudjátok-é, hogy a kik megkeresztelkedtünk Krisztus Jézusba, az õ halálába keresztelkedtünk meg?"));
husuperobject.biblemap.put("b45_6_4", new husuperobject(45,6,4,"Eltemettettünk azért õ vele együtt a keresztség által a halálba: hogy miképen feltámasztatott Krisztus a halálból az Atyának dicsõsége által, azonképen mi is új életben járjunk."));
husuperobject.biblemap.put("b45_6_5", new husuperobject(45,6,5,"Mert ha az õ halálának hasonlatossága szerint vele egygyé lettünk, bizonyára feltámadásáé szerint is [azok] leszünk."));
husuperobject.biblemap.put("b45_6_6", new husuperobject(45,6,6,"Tudván azt, hogy a mi ó emberünk õ vele megfeszíttetett, hogy megerõtelenüljön a bûnnek teste, hogy ezután ne szolgáljunk a bûnnek:"));
husuperobject.biblemap.put("b45_6_7", new husuperobject(45,6,7,"Mert a ki meghalt, felszabadult a bûn alól."));
husuperobject.biblemap.put("b45_6_8", new husuperobject(45,6,8,"Hogyha pedig meghaltunk Krisztussal, hiszszük, hogy élünk is õ vele."));
husuperobject.biblemap.put("b45_6_9", new husuperobject(45,6,9,"Tudván, hogy Krisztus, a ki feltámadott a halálból, többé meg nem hal; a halál többé rajta nem uralkodik,"));
husuperobject.biblemap.put("b45_6_10", new husuperobject(45,6,10,"Mert hogy meghalt, a bûnnek halt meg egyszer; hogy pedig él, az Istennek él."));
husuperobject.biblemap.put("b45_6_11", new husuperobject(45,6,11,"Ezenképen gondoljátok ti is, hogy meghaltatok a bûnnek, de éltek az Istennek a mi Urunk Jézus Krisztusban."));
husuperobject.biblemap.put("b45_6_12", new husuperobject(45,6,12,"Ne uralkodjék tehát a bûn a ti halandó testetekben, hogy engedjetek néki az õ kívánságaiban:"));
husuperobject.biblemap.put("b45_6_13", new husuperobject(45,6,13,"Se ne szánjátok oda a ti tagjaitokat hamisságnak fegyvereiül a bûnnek; hanem szánjátok oda magatokat az Istennek, mint a kik a halálból életre keltetek, és a ti tagjaitokat igazságnak fegyvereiül az Istennek."));
husuperobject.biblemap.put("b45_6_14", new husuperobject(45,6,14,"Mert a bûn ti rajtatok nem uralkodik; mert nem vagytok törvény alatt, hanem kegyelem alatt."));
husuperobject.biblemap.put("b45_6_15", new husuperobject(45,6,15,"Mit is tehát? Vétkezzünk-é mivelhogy nem vagyunk törvény alatt, hanem kegyelem alatt? Távol legyen."));
husuperobject.biblemap.put("b45_6_16", new husuperobject(45,6,16,"Avagy nem tudjátok, hogy a kinek oda szánjátok magatokat szolgákul az engedelmességre, annak vagytok szolgái, a kinek engedelmeskedtek: vagy a bûnnek halálra, vagy az engedelmességnek igazságra?"));
husuperobject.biblemap.put("b45_6_17", new husuperobject(45,6,17,"De hála az Istennek, hogy [jóllehet] a bûn szolgái voltatok, de szívetek szerint engedelmeskedtek a tudomány azon alakjának, a melyre adattatok."));
husuperobject.biblemap.put("b45_6_18", new husuperobject(45,6,18,"Felszabadulván pedig a bûn alól, az igazságnak szolgáivá lettetek."));
husuperobject.biblemap.put("b45_6_19", new husuperobject(45,6,19,"Emberi módon szólok a ti testeteknek erõtlensége miatt. Mert a miképen oda szántátok a ti tagjaitokat a tisztátalanságnak és a hamisságnak szolgáiul a hamisságra: azonképen szánjátok oda most a ti tagjaitokat szolgáiul az igazságnak a megszenteltetésre."));
husuperobject.biblemap.put("b45_6_20", new husuperobject(45,6,20,"Mert mikor a bûn szolgái valátok, az igazságtól szabadok valátok."));
husuperobject.biblemap.put("b45_6_21", new husuperobject(45,6,21,"Micsoda gyümölcsét vettétek azért akkor azoknak, a miket most szégyenletek? mert azoknak a vége halál."));
husuperobject.biblemap.put("b45_6_22", new husuperobject(45,6,22,"Most pedig, minekutána felszabadultatok a bûn alól, szolgáivá lettetek pedig az Istennek: megvan a gyümölcsötök a megszenteltetésre, a vége pedig örök élet."));
husuperobject.biblemap.put("b45_6_23", new husuperobject(45,6,23,"Mert a bûn zsoldja halál; az Isten kegyelmi ajándéka pedig örök élet a mi Urunk Krisztus Jézusban."));
husuperobject.biblemap.put("b45_7_1", new husuperobject(45,7,1,"Avagy nem tudjátok-é atyámfiai, mert törvényismerõkhöz szólok, hogy a törvény uralkodik az emberen, a míg él?"));
husuperobject.biblemap.put("b45_7_2", new husuperobject(45,7,2,"Mert a férjes asszony, míg él a férj, ehhez van kötve törvény szerint, de ha meghal a férj, felszabadul [az asszony] a férj törvénye alól."));
husuperobject.biblemap.put("b45_7_3", new husuperobject(45,7,3,"Azért tehát az õ férjének életében paráznának mondatik, ha más férfihoz megy; ha azonban meghal a férje, szabaddá lesz a törvénytõl, úgy hogy nem lesz parázna, ha más férfihoz megy."));
husuperobject.biblemap.put("b45_7_4", new husuperobject(45,7,4,"Azért atyámfiai, ti is meghaltatok a törvénynek a Krisztus teste által, hogy legyetek máséi, azéi, a ki a halálból feltámasztatott, hogy gyümölcsöt teremjünk Istennek."));
husuperobject.biblemap.put("b45_7_5", new husuperobject(45,7,5,"Mert mikor a testben voltunk, a bûnök indulatai a törvény által dolgoztak a mi tagjainkban, hogy gyümölcsözzenek a halálnak;"));
husuperobject.biblemap.put("b45_7_6", new husuperobject(45,7,6,"Most pedig megszabadultunk a törvénytõl, minekutána meghaltunk arra nézve, a mely által lekötve tartattunk; hogy szolgáljunk a léleknek újságában és nem a betû óságában."));
husuperobject.biblemap.put("b45_7_7", new husuperobject(45,7,7,"Mit mondunk tehát? A törvény bûn-é? Távol legyen: sõt inkább a bûnt nem ismertem, hanem csak a törvény által; mert a kívánságról sem tudtam volna, ha a törvény nem mondaná: Ne kívánjad."));
husuperobject.biblemap.put("b45_7_8", new husuperobject(45,7,8,"De a bûn alkalmat vévén, a parancsolat által nemzett bennem minden kívánságot; mert törvény nélkül holt a bûn."));
husuperobject.biblemap.put("b45_7_9", new husuperobject(45,7,9,"Én pedig éltem régen a törvény nélkül: de ama parancsolatnak eljövetelével felelevenedék a bûn,"));
husuperobject.biblemap.put("b45_7_10", new husuperobject(45,7,10,"Én pedig meghalék; és úgy találtaték, hogy az a parancsolat, mely életre való, nékem halálomra van."));
husuperobject.biblemap.put("b45_7_11", new husuperobject(45,7,11,"Mert a bûn alkalmat vévén, ama parancsolat által megcsalt engem, és megölt általa."));
husuperobject.biblemap.put("b45_7_12", new husuperobject(45,7,12,"Azért ám a törvény szent, és a parancsolat szent és igaz és jó."));
husuperobject.biblemap.put("b45_7_13", new husuperobject(45,7,13,"Tehát a jó nékem halálom lett-é? Távol legyen: sõt inkább a bûn [az,] hogy megtessék a bûn, mely a jó által nékem halált szerez, hogy felette igen bûnös legyen a bûn a parancsolat által."));
husuperobject.biblemap.put("b45_7_14", new husuperobject(45,7,14,"Mert tudjuk, hogy a törvény lelki; de én testi vagyok, a bûn alá rekesztve."));
husuperobject.biblemap.put("b45_7_15", new husuperobject(45,7,15,"Mert a mit cselekeszem, nem ismerem: mert nem azt mívelem, a mit akarok, hanem a mit gyûlölök, azt cselekeszem."));
husuperobject.biblemap.put("b45_7_16", new husuperobject(45,7,16,"Ha pedig azt cselekszem, a mit nem akarok, megegyezem a törvénnyel, hogy jó."));
husuperobject.biblemap.put("b45_7_17", new husuperobject(45,7,17,"Most azért már nem én cselekszem azt, hanem a bennem lakozó bûn."));
husuperobject.biblemap.put("b45_7_18", new husuperobject(45,7,18,"Mert tudom, hogy nem lakik én bennem, azaz a testemben jó; mert az akarás megvan bennem, de a jó véghezvitelét nem találom."));
husuperobject.biblemap.put("b45_7_19", new husuperobject(45,7,19,"Mert nem a jót cselekeszem, melyet akarok; hanem a gonoszt cselekeszem, melyet nem akarok."));
husuperobject.biblemap.put("b45_7_20", new husuperobject(45,7,20,"Ha pedig én azt cselekeszem, a mit nem akarok, nem én mívelem már azt, hanem a bennem lakozó bûn."));
husuperobject.biblemap.put("b45_7_21", new husuperobject(45,7,21,"Megtalálom azért magamban, ki a jót akarom cselekedni, ezt a törvényt, hogy a bûn megvan bennem."));
husuperobject.biblemap.put("b45_7_22", new husuperobject(45,7,22,"Mert gyönyörködöm az Isten törvényében a belsõ ember szerint;"));
husuperobject.biblemap.put("b45_7_23", new husuperobject(45,7,23,"De látok egy másik törvényt az én tagjaimban, mely ellenkezik az elmém törvényével, és engem rabul ád a bûn törvényének, mely van az én tagjaimban."));
husuperobject.biblemap.put("b45_7_24", new husuperobject(45,7,24,"Óh én nyomorult ember! Kicsoda szabadít meg engem e halálnak testébõl?"));
husuperobject.biblemap.put("b45_7_25", new husuperobject(45,7,25,"Hálát adok Istennek a mi Urunk Jézus Krisztus által. Azért jóllehet én az elmémmel az Isten törvényének, de testemmel a bûn törvényének szolgálok."));
husuperobject.biblemap.put("b45_8_1", new husuperobject(45,8,1,"Nincsen azért immár semmi kárhoztatásuk azoknak, a kik Krisztus Jézusban vannak, kik nem test szerint járnak, hanem Lélek szerint."));
husuperobject.biblemap.put("b45_8_2", new husuperobject(45,8,2,"Mert a Jézus Krisztusban való élet lelkének törvénye megszabadított engem a bûn és a halál törvényétõl."));
husuperobject.biblemap.put("b45_8_3", new husuperobject(45,8,3,"Mert a mi a törvénynek lehetetlen vala, mivelhogy erõtelen vala a test miatt, az Isten az õ Fiát elbocsátván bûn testének hasonlatosságában és a bûnért, kárhoztatá a bûnt a testben."));
husuperobject.biblemap.put("b45_8_4", new husuperobject(45,8,4,"Hogy a törvénynek igazsága beteljesüljön bennünk, kik nem test szerint járunk, hanem Lélek szerint."));
husuperobject.biblemap.put("b45_8_5", new husuperobject(45,8,5,"Mert a test szerint valók a test dolgaira gondolnak; a Lélek szerint valók pedig a Lélek dolgaira."));
husuperobject.biblemap.put("b45_8_6", new husuperobject(45,8,6,"Mert a testnek gondolata halál; a Lélek gondolata pedig élet és békesség."));
husuperobject.biblemap.put("b45_8_7", new husuperobject(45,8,7,"Mert a test gondolata ellenségeskedés Isten ellen; minthogy az Isten törvényének nem engedelmeskedik, mert nem is teheti."));
husuperobject.biblemap.put("b45_8_8", new husuperobject(45,8,8,"A kik pedig testben vannak, nem lehetnek kedvesek Isten elõtt."));
husuperobject.biblemap.put("b45_8_9", new husuperobject(45,8,9,"De ti nem vagytok testben, hanem lélekben, ha ugyan az Isten Lelke lakik bennetek. A kiben pedig nincs a Krisztus Lelke, az nem az övé."));
husuperobject.biblemap.put("b45_8_10", new husuperobject(45,8,10,"Hogyha pedig Krisztus ti bennetek [van,] jóllehet a test holt a bûn miatt, a lélek ellenben élet az igazságért."));
husuperobject.biblemap.put("b45_8_11", new husuperobject(45,8,11,"De ha Annak a Lelke lakik bennetek, a ki feltámasztotta Jézust a halálból, ugyanaz, a ki feltámasztotta Krisztus Jézust a halálból, megeleveníti a ti halandó testeiteket is az õ ti bennetek lakozó Lelke által."));
husuperobject.biblemap.put("b45_8_12", new husuperobject(45,8,12,"Annakokáért atyámfiai, nem vagyunk adósok a testnek, hogy test szerint éljünk:"));
husuperobject.biblemap.put("b45_8_13", new husuperobject(45,8,13,"Mert, ha test szerint éltek, meghaltok; de ha a test cselekedeteit a lélekkel megöldökölitek, éltek."));
husuperobject.biblemap.put("b45_8_14", new husuperobject(45,8,14,"Mert a kiket Isten Lelke vezérel, azok Istennek fiai."));
husuperobject.biblemap.put("b45_8_15", new husuperobject(45,8,15,"Mert nem kaptatok szolgaság lelkét ismét a félelemre, hanem a fiúságnak Lelkét kaptátok, a ki által kiáltjuk: Abbá, Atyám!"));
husuperobject.biblemap.put("b45_8_16", new husuperobject(45,8,16,"Ez a Lélek bizonyságot tesz a mi lelkünkkel együtt, hogy Isten gyermekei vagyunk."));
husuperobject.biblemap.put("b45_8_17", new husuperobject(45,8,17,"Ha pedig gyermekek, örökösök is; örökösei Istennek, örököstársai pedig Krisztusnak; ha ugyan vele együtt szenvedünk, hogy vele együtt is dicsõüljünk meg."));
husuperobject.biblemap.put("b45_8_18", new husuperobject(45,8,18,"Mert azt tartom, hogy a miket most szenvedünk, nem hasonlíthatók ahhoz a dicsõséghez, mely nékünk megjelentetik."));
husuperobject.biblemap.put("b45_8_19", new husuperobject(45,8,19,"Mert a teremtett világ sóvárogva várja az Isten fiainak megjelenését."));
husuperobject.biblemap.put("b45_8_20", new husuperobject(45,8,20,"Mert a teremtett világ hiábavalóság alá vettetett, nem önként, hanem azért, a ki az alá vetette."));
husuperobject.biblemap.put("b45_8_21", new husuperobject(45,8,21,"Azzal a reménységgel, hogy maga a teremtett világ is megszabadul a rothadandóság rabságától az Isten fiai dicsõségének szabadságára."));
husuperobject.biblemap.put("b45_8_22", new husuperobject(45,8,22,"Mert tudjuk, hogy az egész teremtett világ egyetemben fohászkodik és nyög mind idáig."));
husuperobject.biblemap.put("b45_8_23", new husuperobject(45,8,23,"Nemcsak [ez] pedig, hanem magok a Lélek zsengéjének birtokosai, mi magunk is fohászkodunk magunkban, várván a fiúságot, a mi testünknek megváltását."));
husuperobject.biblemap.put("b45_8_24", new husuperobject(45,8,24,"Mert reménységben tartattunk meg; a reménység pedig, ha láttatik, nem reménység; mert a mit lát valaki, miért reményli is [azt?]"));
husuperobject.biblemap.put("b45_8_25", new husuperobject(45,8,25,"Ha pedig, a mit nem látunk, azt reméljük, békességes tûréssel várjuk."));
husuperobject.biblemap.put("b45_8_26", new husuperobject(45,8,26,"Hasonlatosképen pedig a Lélek is segítségére van a mi erõtelenségünknek. Mert azt, a mit kérnünk kell, a mint kellene, nem tudjuk; de maga a Lélek esedezik mi érettünk kimondhatatlan fohászkodásokkal."));
husuperobject.biblemap.put("b45_8_27", new husuperobject(45,8,27,"A ki pedig a szíveket vizsgálja, tudja, mi a Lélek gondolata, mert Isten szerint esedezik a szentekért."));
husuperobject.biblemap.put("b45_8_28", new husuperobject(45,8,28,"Tudjuk pedig, hogy azoknak, a kik Istent szeretik, minden javokra van, mint a kik [az] [õ] végzése szerint hivatalosak."));
husuperobject.biblemap.put("b45_8_29", new husuperobject(45,8,29,"Mert a kiket eleve ismert, eleve el is rendelte, hogy azok az õ Fia ábrázatához hasonlatosak legyenek, hogy õ legyen elsõszülött sok atyafi között."));
husuperobject.biblemap.put("b45_8_30", new husuperobject(45,8,30,"A kiket pedig eleve elrendelt, azokat el is hívta; és a kiket elhívott, azokat meg is igazította; a kiket pedig megigazított, azokat meg is dicsõítette."));
husuperobject.biblemap.put("b45_8_31", new husuperobject(45,8,31,"Mit mondunk azért ezekre? Ha az Isten velünk, kicsoda ellenünk?"));
husuperobject.biblemap.put("b45_8_32", new husuperobject(45,8,32,"A ki az õ tulajdon Fiának nem kedvezett, hanem õt mindnyájunkért odaadta, mimódon ne ajándékozna vele együtt mindent minékünk?"));
husuperobject.biblemap.put("b45_8_33", new husuperobject(45,8,33,"Kicsoda vádolja az Isten választottait? Isten az, a ki megigazít;"));
husuperobject.biblemap.put("b45_8_34", new husuperobject(45,8,34,"Kicsoda az, a ki kárhoztat? Krisztus az, a ki meghalt, sõt a ki fel is támadott, a ki az Isten jobbján van, a ki esedezik is érettünk:"));
husuperobject.biblemap.put("b45_8_35", new husuperobject(45,8,35,"Kicsoda szakaszt el minket a Krisztus szerelmétõl? nyomorúság vagy szorongattatás, vagy üldözés, vagy éhség, vagy meztelenség, vagy veszedelem, vagy fegyver-é?"));
husuperobject.biblemap.put("b45_8_36", new husuperobject(45,8,36,"A mint megvan írva, hogy: Te éretted gyilkoltatunk minden napon; olybá tekintenek mint vágó juhokat."));
husuperobject.biblemap.put("b45_8_37", new husuperobject(45,8,37,"De mindezekben felettébb diadalmaskodunk, Az által, a ki minket szeretett,"));
husuperobject.biblemap.put("b45_8_38", new husuperobject(45,8,38,"Mert meg vagyok gyõzõdve, hogy sem halál, sem élet, sem angyalok, sem fejedelemségek, sem hatalmasságok, sem jelenvalók, sem következendõk,"));
husuperobject.biblemap.put("b45_8_39", new husuperobject(45,8,39,"Sem magasság, sem mélység, sem semmi más teremtmény nem szakaszthat el minket az Istennek szerelmétõl, mely vagyon a mi Urunk Jézus Krisztusban."));
husuperobject.biblemap.put("b45_9_1", new husuperobject(45,9,1,"Igazságot szólok Krisztusban, nem hazudok, lelkiismeretem velem együtt tesz bizonyságot a Szent Lélek által,"));
husuperobject.biblemap.put("b45_9_2", new husuperobject(45,9,2,"Hogy nagy az én szomorúságom és szüntelen való az én szívemnek fájdalma;"));
husuperobject.biblemap.put("b45_9_3", new husuperobject(45,9,3,"Mert kívánnám, hogy én magam átok legyek, [elszakasztva] a Krisztustól az én atyámfiaiért, a kik rokonaim test szerint;"));
husuperobject.biblemap.put("b45_9_4", new husuperobject(45,9,4,"A kik izráeliták, a kiké a fiúság és a dicsõség és a szövetségek, meg a törvényadás és az isteni tisztelet és az ígéretek;"));
husuperobject.biblemap.put("b45_9_5", new husuperobject(45,9,5,"A kiké az atyák, és a kik közül való test szerint a Krisztus, a ki mindeneknek felette örökké áldandó Isten. Ámen."));
husuperobject.biblemap.put("b45_9_6", new husuperobject(45,9,6,"Nem lehet pedig, hogy meghiúsult legyen az Isten beszéde. Mert nem mindnyájan izráeliták azok, kik Izráeltõl valók;"));
husuperobject.biblemap.put("b45_9_7", new husuperobject(45,9,7,"Sem nem mindnyájan fiak, kik az Ábrahám magvából valók; hanem: Izsákban neveztetik néked a te magod."));
husuperobject.biblemap.put("b45_9_8", new husuperobject(45,9,8,"Azaz, nem a testnek fiai az Isten fiai; hanem az ígéret fiait tekinti magul."));
husuperobject.biblemap.put("b45_9_9", new husuperobject(45,9,9,"Mert ígéretnek beszéde ez: Ez idõ tájban eljövök, és Sárának fia lesz."));
husuperobject.biblemap.put("b45_9_10", new husuperobject(45,9,10,"Nemcsak pedig, hanem Rebeka is, ki egytõl fogant méhében, Izsáktól a mi atyánktól:"));
husuperobject.biblemap.put("b45_9_11", new husuperobject(45,9,11,"Mert mikor még meg sem születtek, sem semmi jót vagy gonoszt nem cselekedtek, hogy az Istennek kiválasztás szerint való végzése megmaradjon, nem cselekedetekbõl, hanem az elhívótól,"));
husuperobject.biblemap.put("b45_9_12", new husuperobject(45,9,12,"Megmondatott néki, hogy: A nagyobbik szolgál a kisebbiknek."));
husuperobject.biblemap.put("b45_9_13", new husuperobject(45,9,13,"Miképen meg van írva: Jákóbot szerettem, Ézsaut pedig gyûlöltem."));
husuperobject.biblemap.put("b45_9_14", new husuperobject(45,9,14,"Mit mondunk tehát: Vajjon nem igazságtalanság-é [ez] az Istentõl? Távol legyen!"));
husuperobject.biblemap.put("b45_9_15", new husuperobject(45,9,15,"Mert Mózesnek ezt mondja: Könyörülök azon, a kin könyörülök, és kegyelmezek annak, a kinek kegyelmezek."));
husuperobject.biblemap.put("b45_9_16", new husuperobject(45,9,16,"Annakokáért tehát nem azé, a ki akarja, sem nem azé, a ki fut, hanem a könyörülõ Istené."));
husuperobject.biblemap.put("b45_9_17", new husuperobject(45,9,17,"Mert azt mondja az írás a Faraónak, hogy: Azért támasztottalak téged, hogy megmutassam benned az én hatalmamat, és hogy hirdessék az én nevemet az egész földön."));
husuperobject.biblemap.put("b45_9_18", new husuperobject(45,9,18,"Annakokáért a kin akar könyörül, a kit pedig akar, megkeményít."));
husuperobject.biblemap.put("b45_9_19", new husuperobject(45,9,19,"Mondod azért nékem: Miért fedd hát [engem?] [Hiszen] az õ akaratának kicsoda áll ellene?"));
husuperobject.biblemap.put("b45_9_20", new husuperobject(45,9,20,"Sõt inkább kicsoda vagy te óh ember, hogy versengsz az Istennel? Avagy mondja-é a készítmény a készítõnek: Miért csináltál engem így?"));
husuperobject.biblemap.put("b45_9_21", new husuperobject(45,9,21,"Avagy nincsen-é a fazekasnak hatalma az agyagon, hogy ugyanazon gyuradékból némely edényt tisztességre, némelyt pedig becstelenségre csináljon?"));
husuperobject.biblemap.put("b45_9_22", new husuperobject(45,9,22,"Ha pedig az Isten az õ haragját megmutatni és hatalmát megismertetni kívánván, nagy békességes tûréssel elszenvedte a harag edényeit, melyek veszedelemre készíttettek,"));
husuperobject.biblemap.put("b45_9_23", new husuperobject(45,9,23,"És hogy megismertesse az õ dicsõségének gazdagságát az irgalom edényein, melyeket eleve elkészített a dicsõségre, [mit szólhatsz ellene?]"));
husuperobject.biblemap.put("b45_9_24", new husuperobject(45,9,24,"A kikül el is hívott minket nemcsak a zsidók, hanem a pogányok közül is,"));
husuperobject.biblemap.put("b45_9_25", new husuperobject(45,9,25,"A mint Hóseásnál is mondja: Hívom a nem én népemet én népemnek; és a nem szerettet szeretettnek."));
husuperobject.biblemap.put("b45_9_26", new husuperobject(45,9,26,"És lészen, hogy azon a helyen, a hol ez mondatott nékik: Ti nem vagytok az én népem, ott az élõ Isten fiainak fognak hívatni."));
husuperobject.biblemap.put("b45_9_27", new husuperobject(45,9,27,"Ésaiás pedig ezt kiáltja Izráel felõl: Ha Izráel fiainak száma [annyi] volna is, mint a tenger fövenye, a maradék tartatik meg."));
husuperobject.biblemap.put("b45_9_28", new husuperobject(45,9,28,"Mert a dolgot bevégezi és rövidre metszi igazságban; mivel rövidesen végez az Úr a földön."));
husuperobject.biblemap.put("b45_9_29", new husuperobject(45,9,29,"És a mint Ésaiás elõre megmondotta: Ha a Seregeknek Ura nem hagyott volna nékünk magot, olyanokká lettünk volna, mint Sodoma, és Gomorához volnánk hasonlók."));
husuperobject.biblemap.put("b45_9_30", new husuperobject(45,9,30,"Mit mondunk hát? Azt, hogy a pogányok, a kik az igazságot nem követték, az igazságot elnyerték, még pedig a hitbõl való igazságot;"));
husuperobject.biblemap.put("b45_9_31", new husuperobject(45,9,31,"Izráel ellenben, mely az igazság törvényét követte, nem jutott el az igazság törvényére."));
husuperobject.biblemap.put("b45_9_32", new husuperobject(45,9,32,"Miért? Azért, mert nem hitbõl [keresték,] hanem mintha a törvény cselekedeteibõl volna. Mert beleütköztek a beleütközés kövébe,"));
husuperobject.biblemap.put("b45_9_33", new husuperobject(45,9,33,"A mint meg van írva: Ímé beleütközés kövét és megbotránkozás szikláját teszem Sionba; és a ki hisz benne, nem szégyenül meg."));
husuperobject.biblemap.put("b45_10_1", new husuperobject(45,10,1,"Atyámfiai, szívem szerint kívánom és Istentõl könyörgöm az Izráel idvességét."));
husuperobject.biblemap.put("b45_10_2", new husuperobject(45,10,2,"Mert bizonyságot teszek felõlök, hogy Isten iránt való buzgóság van bennök, de nem megismerés szerint."));
husuperobject.biblemap.put("b45_10_3", new husuperobject(45,10,3,"Mert az Isten igazságát nem ismervén, és az õ tulajdon igazságukat igyekezvén érvényesíteni, az Isten igazságának nem engedelmeskedtek."));
husuperobject.biblemap.put("b45_10_4", new husuperobject(45,10,4,"Mert a törvény vége Krisztus minden hívõnek igazságára."));
husuperobject.biblemap.put("b45_10_5", new husuperobject(45,10,5,"Mert Mózes a törvénybõl való igazságról [azt] írja, hogy a ki azokat cselekeszi, él azok által."));
husuperobject.biblemap.put("b45_10_6", new husuperobject(45,10,6,"A hitbõl való igazság pedig így szól: Ne mondd a te szívedben: Kicsoda megy föl a mennybe? (azaz, hogy Krisztus aláhozza;)"));
husuperobject.biblemap.put("b45_10_7", new husuperobject(45,10,7,"Avagy: Kicsoda száll le a mélységbe? (azaz, hogy Krisztust a halálból felhozza.)"));
husuperobject.biblemap.put("b45_10_8", new husuperobject(45,10,8,"De mit mond? Közel hozzád a beszéd, a szádban és a szívedben van: azaz a hit beszéde, a melyet mi hirdetünk."));
husuperobject.biblemap.put("b45_10_9", new husuperobject(45,10,9,"Mert ha a te száddal vallást teszel az Úr Jézusról, és szívedben hiszed, hogy az Isten feltámasztotta õt a halálból, megtartatol."));
husuperobject.biblemap.put("b45_10_10", new husuperobject(45,10,10,"Mert szívvel hiszünk az igazságra, szájjal teszünk pedig vallást az idvességre."));
husuperobject.biblemap.put("b45_10_11", new husuperobject(45,10,11,"Mert azt mondja az írás: Valaki hisz õ benne, meg nem szégyenül."));
husuperobject.biblemap.put("b45_10_12", new husuperobject(45,10,12,"Mert nincs különbség zsidó meg görög között; mert ugyanaz az Ura mindeneknek, a ki kegyelemben gazdag mindenekhez, a kik õt segítségül hívják."));
husuperobject.biblemap.put("b45_10_13", new husuperobject(45,10,13,"Mert minden, a ki segítségül hívja az Úr nevét, megtartatik."));
husuperobject.biblemap.put("b45_10_14", new husuperobject(45,10,14,"Mimódon hívják azért segítségül [azt,] a kiben nem hisznek? Mimódon hisznek pedig [abban], a ki felõl nem hallottak? Mimódon hallanának pedig prédikáló nélkül?"));
husuperobject.biblemap.put("b45_10_15", new husuperobject(45,10,15,"Mimódon prédikálnak pedig, ha el nem küldetnek? A miképen meg van írva: Mely szépek a békesség hirdetõknek lábai, a kik jókat hirdetnek!"));
husuperobject.biblemap.put("b45_10_16", new husuperobject(45,10,16,"De nem mindenek engedelmeskedtek az evangyéliomnak. Mert Ésaiás azt mondja: Uram! Kicsoda hitt a mi beszédünknek?"));
husuperobject.biblemap.put("b45_10_17", new husuperobject(45,10,17,"Azért a hit hallásból van, a hallás pedig Isten ígéje által."));
husuperobject.biblemap.put("b45_10_18", new husuperobject(45,10,18,"De mondom: Avagy nem hallották-é? Sõt inkább az egész földre elhatott az õ hangjok, és a lakóföld véghatáráig az õ beszédök."));
husuperobject.biblemap.put("b45_10_19", new husuperobject(45,10,19,"De mondom: Avagy nem ismerte-é Izráel? Elõször Mózes mondja: Én titeket felingerellek egy nem néppel, értelmetlen néppel haragítalak meg titeket."));
husuperobject.biblemap.put("b45_10_20", new husuperobject(45,10,20,"Ésaiás pedig bátorságosan ezt mondja: Megtaláltak azok, a kik engem nem keresnek; nyilvánvaló lettem azoknak, a kik felõlem nem kérdezõsködtek."));
husuperobject.biblemap.put("b45_10_21", new husuperobject(45,10,21,"Az Izráelrõl pedig ezt mondja: Egész napon kiterjesztettem kezeimet az engedetlenkedõ és ellenmondó néphez."));
husuperobject.biblemap.put("b45_11_1", new husuperobject(45,11,1,"Mondom tehát: Avagy elvetette-é Isten az õ népét? Távol legyen; mert én is izráelita vagyok, az Ábrahám magvából, Benjámin nemzetségébõl való."));
husuperobject.biblemap.put("b45_11_2", new husuperobject(45,11,2,"Nem vetette el Isten az õ népét, melyet eleve ismert. Avagy nem tudjátok-é, mit mond az írás Illésrõl? a mint könyörög Istenhez Izráel ellen, mondván:"));
husuperobject.biblemap.put("b45_11_3", new husuperobject(45,11,3,"Uram, a te prófétáidat megölték, és a te oltáraidat lerombolták; és csak én egyedül maradtam, és engem is halálra keresnek."));
husuperobject.biblemap.put("b45_11_4", new husuperobject(45,11,4,"De mit mond néki az isteni felelet? Meghagytam magamnak hétezer embert, a kik nem hajtottak térdet a Baálnak."));
husuperobject.biblemap.put("b45_11_5", new husuperobject(45,11,5,"Ekképen azért most is van maradék a kegyelembõl való választás szerint."));
husuperobject.biblemap.put("b45_11_6", new husuperobject(45,11,6,"Hogyha pedig kegyelembõl, akkor nem cselekedetekbõl: különben a kegyelem nem volna többé kegyelem. Hogyha pedig cselekedetekbõl, akkor nem kegyelembõl: különben a cselekedet nem volna többé cselekedet."));
husuperobject.biblemap.put("b45_11_7", new husuperobject(45,11,7,"Micsoda tehát? A mit Izráel keres, azt nem nyerte meg: a választottak ellenben megnyerték, a többiek pedig megkeményíttettek:"));
husuperobject.biblemap.put("b45_11_8", new husuperobject(45,11,8,"A mint meg van írva: Az Isten kábultság lelkét adta nékik; szemeket, hogy ne lássanak, füleket, hogy ne halljanak, mind e mai napig."));
husuperobject.biblemap.put("b45_11_9", new husuperobject(45,11,9,"Dávid is ezt mondja: Legyen az õ asztaluk tõrré, hálóvá, botránkozássá és megtorlássá."));
husuperobject.biblemap.put("b45_11_10", new husuperobject(45,11,10,"Sötétüljenek meg az õ szemeik, hogy ne lássanak, és az õ hátokat mindenkorra görbítsd meg."));
husuperobject.biblemap.put("b45_11_11", new husuperobject(45,11,11,"Annakokáért mondom: Avagy azért botlottak-é meg, hogy elessenek? Távol legyen; hanem az õ esetük folytán [lett] az idvesség a pogányoké, hogy õk felingereltessenek."));
husuperobject.biblemap.put("b45_11_12", new husuperobject(45,11,12,"Ha pedig az õ esetök világnak gazdagsága, és az õ veszteségök pogányok gazdagsága, mennyivel inkább az õ teljességök?"));
husuperobject.biblemap.put("b45_11_13", new husuperobject(45,11,13,"Mert néktek mondom a pogányoknak, a mennyiben hát én pogányok apostola vagyok, a szolgálatomat dicsõítem,"));
husuperobject.biblemap.put("b45_11_14", new husuperobject(45,11,14,"Ha ugyan felingerelhetném az én atyámfiait, és megtarthatnék közülök némelyeket."));
husuperobject.biblemap.put("b45_11_15", new husuperobject(45,11,15,"Mert ha az õ elvettetésök a világnak megbékélése, micsoda [lesz] a felvételök hanemha élet a halálból?"));
husuperobject.biblemap.put("b45_11_16", new husuperobject(45,11,16,"Ha pedig a zsenge szent, akkor a tészta is; és ha a gyökér szent, az ágak is [azok.]"));
husuperobject.biblemap.put("b45_11_17", new husuperobject(45,11,17,"Ha pedig némely ágak kitörettek, te pedig vadolajfa létedre beoltattál azok közé, és részese lettél az olajfa gyökerének és zsírjának;"));
husuperobject.biblemap.put("b45_11_18", new husuperobject(45,11,18,"Ne kevélykedjél az ágak ellenében: ha pedig kevélykedel, nem te hordozod a gyökeret, hanem a gyökér téged."));
husuperobject.biblemap.put("b45_11_19", new husuperobject(45,11,19,"Azt mondod azért: Kitörettek [az] ágak, hogy én oltassam be."));
husuperobject.biblemap.put("b45_11_20", new husuperobject(45,11,20,"Úgy van; hitetlenség miatt törettek ki, te pedig hit által állasz; fel ne fuvalkodjál, hanem félj;"));
husuperobject.biblemap.put("b45_11_21", new husuperobject(45,11,21,"Mert ha az Isten a természet szerint való ágaknak nem kedvezett, majd néked sem kedvez."));
husuperobject.biblemap.put("b45_11_22", new husuperobject(45,11,22,"Tekintsd meg azért az Istennek kegyességét és keménységét: azok iránt a kik elestek, keménységét; irántad pedig a kegyességét, ha megmaradsz a kegyességben; különben te is kivágatol."));
husuperobject.biblemap.put("b45_11_23", new husuperobject(45,11,23,"Sõt azok is, ha meg nem maradnak a hitetlenségben, beoltatnak; mert az Isten ismét beolthatja õket."));
husuperobject.biblemap.put("b45_11_24", new husuperobject(45,11,24,"Mert ha te a természet szerint való vadolajfából kivágattál, és természet ellenére beoltattál a szelid olajfába: mennyivel inkább beoltatnak ezek a természet szerint valók az õ saját olajfájokba."));
husuperobject.biblemap.put("b45_11_25", new husuperobject(45,11,25,"Mert nem akarom, hogy ne tudjátok atyámfiai ezt a titkot, hogy magatokat el ne higyjétek, hogy a megkeményedés Izráelre nézve [csak] részben történt, a meddig a pogányok teljessége bemegyen."));
husuperobject.biblemap.put("b45_11_26", new husuperobject(45,11,26,"És így az egész Izráel megtartatik, a mint meg van írva: Eljõ Sionból a Szabadító, és elfordítja Jákóbtól a gonoszságokat:"));
husuperobject.biblemap.put("b45_11_27", new husuperobject(45,11,27,"És ez nékik az én szövetségem, midõn eltörlöm az õ bûneiket."));
husuperobject.biblemap.put("b45_11_28", new husuperobject(45,11,28,"Az evangyéliomra nézve ugyan ellenségek ti érettetek; de a választásra nézve szerelmetesek az atyákért."));
husuperobject.biblemap.put("b45_11_29", new husuperobject(45,11,29,"Mert megbánhatatlanok az Istennek ajándékai és az õ elhívása."));
husuperobject.biblemap.put("b45_11_30", new husuperobject(45,11,30,"Mert miképen ti egykor engedetlenkedtetek az Istennek, most pedig irgalmasságot nyertetek az õ engedetlenségök miatt:"));
husuperobject.biblemap.put("b45_11_31", new husuperobject(45,11,31,"Azonképen õk is most engedetlenkedtek, hogy a ti irgalmasságba jutásotok folytán õk is irgalmasságot nyerjenek;"));
husuperobject.biblemap.put("b45_11_32", new husuperobject(45,11,32,"Mert az Isten mindeneket engedetlenség alá rekesztett, hogy mindeneken könyörüljön."));
husuperobject.biblemap.put("b45_11_33", new husuperobject(45,11,33,"Óh Isten gazdagságának, bölcseségének és tudományának mélysége! Mely igen kikutathatatlanok az õ ítéletei s kinyomozhatatlanok az õ útai!"));
husuperobject.biblemap.put("b45_11_34", new husuperobject(45,11,34,"Mert kicsoda ismerte meg az Úr értelmét? vagy kicsoda volt néki tanácsosa?"));
husuperobject.biblemap.put("b45_11_35", new husuperobject(45,11,35,"Avagy kicsoda adott elõbb néki, hogy annak visszafizesse azt?"));
husuperobject.biblemap.put("b45_11_36", new husuperobject(45,11,36,"Mert õ tõle, õ általa és õ reá nézve vannak mindenek. Övé a dicsõség mindörökké. Ámen."));
husuperobject.biblemap.put("b45_12_1", new husuperobject(45,12,1,"Kérlek azért titeket atyámfiai az Istennek irgalmasságára, hogy szánjátok oda a ti testeiteket élõ, szent és Istennek kedves áldozatul, mint a ti okos tiszteleteteket."));
husuperobject.biblemap.put("b45_12_2", new husuperobject(45,12,2,"És ne szabjátok magatokat e világhoz, hanem változzatok el a ti elméteknek megújulása által, hogy megvizsgáljátok, mi az Istennek jó, kedves és tökéletes akarata."));
husuperobject.biblemap.put("b45_12_3", new husuperobject(45,12,3,"Mert a nékem adott kegyelem által mondom mindenkinek közöttetek, hogy feljebb ne bölcselkedjék, mint a hogy kell bölcselkedni; hanem józanon bölcselkedjék, a mint az Isten adta kinek-kinek a hit mértékét."));
husuperobject.biblemap.put("b45_12_4", new husuperobject(45,12,4,"Mert miképen egy testben sok tagunk van, minden tagnak pedig nem ugyanazon cselekedete van:"));
husuperobject.biblemap.put("b45_12_5", new husuperobject(45,12,5,"Azonképen sokan egy test vagyunk a Krisztusban, egyenként pedig egymásnak tagjai [vagyunk.]"));
husuperobject.biblemap.put("b45_12_6", new husuperobject(45,12,6,"Minthogy azért külön-külön ajándékaink vannak a nékünk adott kegyelem szerint, akár írásmagyarázás, a hitnek szabálya szerint [teljesítsük;]"));
husuperobject.biblemap.put("b45_12_7", new husuperobject(45,12,7,"Akár szolgálat, a szolgálatban; akár tanító, a tanításban;"));
husuperobject.biblemap.put("b45_12_8", new husuperobject(45,12,8,"Akár intõ, az intésben; az adakozó szelídségben; az elõljáró szorgalmatossággal; a könyörülõ vídámsággal [mívelje.]"));
husuperobject.biblemap.put("b45_12_9", new husuperobject(45,12,9,"A szeretet képmutatás nélkül való legyen. Iszonyodjatok a gonosztól, ragaszkodjatok a jóhoz."));
husuperobject.biblemap.put("b45_12_10", new husuperobject(45,12,10,"Atyafiúi szeretettel egymás iránt gyöngédek; a tiszteletadásban egymást megelõzõk [legyetek.]"));
husuperobject.biblemap.put("b45_12_11", new husuperobject(45,12,11,"Az igyekezetben ne [legyetek] restek; lélekben buzgók [legyetek;] az Úrnak szolgáljatok."));
husuperobject.biblemap.put("b45_12_12", new husuperobject(45,12,12,"A reménységben örvendezõk; a háborúságban tûrõk; a könyörgésben állhatatosak;"));
husuperobject.biblemap.put("b45_12_13", new husuperobject(45,12,13,"A szentek szükségeire adakozók [legyetek;] a vendégszeretetet gyakoroljátok."));
husuperobject.biblemap.put("b45_12_14", new husuperobject(45,12,14,"Áldjátok azokat, a kik titeket kergetnek; áldjátok és ne átkozzátok."));
husuperobject.biblemap.put("b45_12_15", new husuperobject(45,12,15,"Örüljetek az örülõkkel, és sírjatok a sírókkal."));
husuperobject.biblemap.put("b45_12_16", new husuperobject(45,12,16,"Egymás iránt ugyanazon indulattal legyetek; ne kevélykedjetek, hanem az alázatosakhoz szabjátok magatokat. Ne legyetek bölcsek timagatokban."));
husuperobject.biblemap.put("b45_12_17", new husuperobject(45,12,17,"Senkinek gonoszért gonoszszal ne fizessetek. A tisztességre gondotok legyen minden ember elõtt."));
husuperobject.biblemap.put("b45_12_18", new husuperobject(45,12,18,"Ha lehetséges, a mennyire rajtatok áll, minden emberrel békességesen éljetek."));
husuperobject.biblemap.put("b45_12_19", new husuperobject(45,12,19,"Magatokért bosszút ne álljatok szerelmeseim, hanem adjatok helyet ama haragnak; mert meg van írva: Enyém a bosszúállás, én megfizetek, ezt mondja az Úr."));
husuperobject.biblemap.put("b45_12_20", new husuperobject(45,12,20,"Azért, ha éhezik a te ellenséged, adj ennie; ha szomjuhozik, adj innia; mert ha ezt míveled, eleven szenet gyûjtesz az õ fejére."));
husuperobject.biblemap.put("b45_12_21", new husuperobject(45,12,21,"Ne gyõzettessél meg a gonosztól, hanem a gonoszt jóval gyõzd meg."));
husuperobject.biblemap.put("b45_13_1", new husuperobject(45,13,1,"Minden lélek engedelmeskedjék a felsõ hatalmasságoknak; mert nincsen hatalmasság, hanem csak Istentõl: és a mely hatalmasságok vannak, az Istentõl rendeltettek."));
husuperobject.biblemap.put("b45_13_2", new husuperobject(45,13,2,"Azért, a ki ellene támad a hatalmasságnak, az Isten rendelésének támad ellene; a kik pedig ellene támadnak, önmagoknak ítéletet szereznek."));
husuperobject.biblemap.put("b45_13_3", new husuperobject(45,13,3,"Mert a fejedelmek nem a jó, hanem a rossz cselekedetnek rettegésére vannak. Akarod-é pedig, hogy ne félj a hatalmasságtól? Cselekedjed a jót, és dícséreted lesz attól."));
husuperobject.biblemap.put("b45_13_4", new husuperobject(45,13,4,"Mert Isten szolgája õ a te javadra. Ha pedig a gonoszt cselekszed, félj: mert nem ok nélkül viseli a fegyvert: mert Isten szolgája, bosszúálló a haragra annak, a ki gonoszt cselekszik."));
husuperobject.biblemap.put("b45_13_5", new husuperobject(45,13,5,"Annakokáért szükség engedelmeskedni, nem csak a haragért, hanem a lelkiismeretért is."));
husuperobject.biblemap.put("b45_13_6", new husuperobject(45,13,6,"Mert azért fizettek adót is; mivelhogy Istennek szolgái, kik ugyanabban foglalatoskodnak."));
husuperobject.biblemap.put("b45_13_7", new husuperobject(45,13,7,"Adjátok meg azért mindenkinek, a mivel tartoztok: a kinek az adóval, az adót; a kinek a vámmal, a vámot; a kinek a félelemmel, a félelmet; a kinek a tisztességgel, a tisztességet."));
husuperobject.biblemap.put("b45_13_8", new husuperobject(45,13,8,"Senkinek semmivel ne tartozzatok, hanem csak [azzal,] hogy egymást szeressétek; mert a ki szereti a felebarátját, a törvényt betöltötte."));
husuperobject.biblemap.put("b45_13_9", new husuperobject(45,13,9,"Mert ez: Ne paráználkodjál, ne ölj, ne orozz, hamis tanubizonyságot ne szólj, ne kívánj, és ha valamely más parancsolat van, ebben az ígében foglaltatik egybe: Szeressed felebarátodat mint temagadat."));
husuperobject.biblemap.put("b45_13_10", new husuperobject(45,13,10,"A szeretet nem illeti gonoszszal a felebarátot. Annakokáért a törvénynek betöltése a szeretet."));
husuperobject.biblemap.put("b45_13_11", new husuperobject(45,13,11,"Ezt pedig cselekedjétek, tudván az idõt, hogy ideje már, hogy az álomból felserkenjünk; mert most közelebb van hozzánk az idvesség, mint a mikor hívõkké lettünk."));
husuperobject.biblemap.put("b45_13_12", new husuperobject(45,13,12,"Az éjszaka elmúlt, a nap pedig elközelgett; vessük el azért a sötétségnek cselekedeteit, és öltözzük fel a világosság fegyvereit."));
husuperobject.biblemap.put("b45_13_13", new husuperobject(45,13,13,"Mint nappal, ékesen járjunk, nem dobzódásokban és részegségekben, nem bujálkodásokban és feslettségekben, nem versengésben és írigységben:"));
husuperobject.biblemap.put("b45_13_14", new husuperobject(45,13,14,"Hanem öltözzétek fel az Úr Jézus Krisztust, és a testet ne tápláljátok a kívánságokra."));
husuperobject.biblemap.put("b45_14_1", new husuperobject(45,14,1,"A hitben erõtelent fogadjátok be, nem ítélgetvén vélekedéseit."));
husuperobject.biblemap.put("b45_14_2", new husuperobject(45,14,2,"Némely ember azt hiszi, hogy mindent megehetik; a [hitben] erõtelen pedig zöldséget eszik."));
husuperobject.biblemap.put("b45_14_3", new husuperobject(45,14,3,"A ki eszik, ne vesse meg azt, a ki nem eszik; és a ki nem eszik, ne kárhoztassa azt, a ki eszik. Mert az Isten befogadta õt."));
husuperobject.biblemap.put("b45_14_4", new husuperobject(45,14,4,"Te kicsoda vagy, hogy kárhoztatod a más szolgáját? Az õ tulajdon urának áll vagy esik. De meg fog állani, mert az Úr által képes, hogy megálljon."));
husuperobject.biblemap.put("b45_14_5", new husuperobject(45,14,5,"Emez az egyik napot különbnek tartja a másiknál: amaz pedig minden napot [egyformának] tart. Ki-ki a maga értelme felõl legyen meggyõzõdve."));
husuperobject.biblemap.put("b45_14_6", new husuperobject(45,14,6,"A ki ügyel a napra, az Úrért ügyel: és a ki nem ügyel a napra, az Úrért nem ügyel. A ki eszik, az Úrért eszik, mert hálákat ád az Istennek: és a ki nem eszik, az Úrért nem eszik, és hálákat ád az Istennek."));
husuperobject.biblemap.put("b45_14_7", new husuperobject(45,14,7,"Mert közülünk senki sem él önmagának, és senki sem hal önmagának:"));
husuperobject.biblemap.put("b45_14_8", new husuperobject(45,14,8,"Mert ha élünk, az Úrnak élünk; ha meghalunk, az Úrnak halunk meg. Azért akár éljünk, akár haljunk, az Úréi vagyunk."));
husuperobject.biblemap.put("b45_14_9", new husuperobject(45,14,9,"Mert azért halt meg és támadott fel és elevenedett meg Krisztus, hogy mind holtakon mind élõkön uralkodjék."));
husuperobject.biblemap.put("b45_14_10", new husuperobject(45,14,10,"Te pedig miért kárhoztatod a te atyádfiát? avagy te is miért veted meg a te atyádfiát? Hiszen mindnyájan oda állunk majd a Krisztus ítélõszéke elé."));
husuperobject.biblemap.put("b45_14_11", new husuperobject(45,14,11,"Mert meg van írva: Élek én, mond az Úr, mert nékem hajol meg minden térd, és minden nyelv Istent magasztalja."));
husuperobject.biblemap.put("b45_14_12", new husuperobject(45,14,12,"Azért hát mindenikünk maga ad számot magáról az Istennek."));
husuperobject.biblemap.put("b45_14_13", new husuperobject(45,14,13,"Annakokáért egymást többé ne kárhoztassuk: hanem inkább azt tartsátok, hogy a ti atyátokfiának ne szerezzetek megütközést vagy megbotránkozást."));
husuperobject.biblemap.put("b45_14_14", new husuperobject(45,14,14,"Tudom és meg vagyok gyõzõdve az Úr Jézusban, hogy semmi sem tisztátalan önmagában: hanem bármi annak tisztátalan, a ki tisztátalannak tartja."));
husuperobject.biblemap.put("b45_14_15", new husuperobject(45,14,15,"De ha a te atyádfia az ételért megszomorodik, akkor te nem szeretet szerint cselekszel. Ne veszítsd el azt a te ételeddel, a kiért Krisztus meghalt."));
husuperobject.biblemap.put("b45_14_16", new husuperobject(45,14,16,"Ne káromoltassék azért a ti javatok."));
husuperobject.biblemap.put("b45_14_17", new husuperobject(45,14,17,"Mert az Isten országa nem evés, nem ivás, hanem igazság, békesség és Szent Lélek által való öröm."));
husuperobject.biblemap.put("b45_14_18", new husuperobject(45,14,18,"Mert a ki ezekben szolgál a Krisztusnak, kedves Istennek, és az emberek elõtt megpróbált."));
husuperobject.biblemap.put("b45_14_19", new husuperobject(45,14,19,"Azért tehát törekedjünk azokra, a mik a békességre és az egymás épülésére valók."));
husuperobject.biblemap.put("b45_14_20", new husuperobject(45,14,20,"Ne rontsd le az ételért az Isten munkáját. Minden tiszta ugyan, de rossz annak az embernek, a ki botránkozással eszi."));
husuperobject.biblemap.put("b45_14_21", new husuperobject(45,14,21,"Jó nem enni húst és nem inni bort, sem semmit nem [tenni,] a miben a te atyádfia megütközik vagy megbotránkozik, vagy erõtelen."));
husuperobject.biblemap.put("b45_14_22", new husuperobject(45,14,22,"Te néked hited van: tartsd meg magadban Isten elõtt. Boldog, a ki nem kárhoztatja magát abban, a mit helyesel."));
husuperobject.biblemap.put("b45_14_23", new husuperobject(45,14,23,"A ki pedig kételkedik, ha eszik, kárhoztatva van, mert nem hitbõl [eszik.] A mi pedig hitbõl nincs, bûn az."));
husuperobject.biblemap.put("b45_15_1", new husuperobject(45,15,1,"Tartozunk pedig mi az erõsek, hogy az erõtelenek erõtlenségeit hordozzuk, és ne magunknak kedveskedjünk."));
husuperobject.biblemap.put("b45_15_2", new husuperobject(45,15,2,"Mindenikünk tudniillik az õ felebarátjának kedveskedjék annak javára, épülésére."));
husuperobject.biblemap.put("b45_15_3", new husuperobject(45,15,3,"Mert Krisztus sem önmagának kedveskedett, hanem a mint meg van írva: A te gyalázóidnak gyalázásai hullottak reám."));
husuperobject.biblemap.put("b45_15_4", new husuperobject(45,15,4,"Mert a melyek régen megirattak, a mi tanulságunkra irattak meg: hogy békességes tûrés által és az írásoknak vígasztalása által reménységünk legyen."));
husuperobject.biblemap.put("b45_15_5", new husuperobject(45,15,5,"A békességes tûrésnek és vígasztalásnak Istene pedig adja néktek, hogy ugyanazon indulat legyen bennetek egymás iránt Krisztus Jézus szerint:"));
husuperobject.biblemap.put("b45_15_6", new husuperobject(45,15,6,"Hogy egy szívvel, egy szájjal dicsõítsétek az Istent és a mi Urunk Jézus Krisztusnak Atyját."));
husuperobject.biblemap.put("b45_15_7", new husuperobject(45,15,7,"Azért fogadjátok be egymást, miképen Krisztus is befogadott minket az Isten dicsõségére."));
husuperobject.biblemap.put("b45_15_8", new husuperobject(45,15,8,"Mondom pedig, hogy Jézus Krisztus szolgája lett a körülmetélkedésnek az Isten igazságáért, hogy megerõsítse az atyák ígéreteit;"));
husuperobject.biblemap.put("b45_15_9", new husuperobject(45,15,9,"A pogányok pedig irgalmasságáért dicsõítik Istent, a mint meg van írva: Annakokáért vallást teszek rólad a pogányok között, és dícséretet éneklek a te nevednek."));
husuperobject.biblemap.put("b45_15_10", new husuperobject(45,15,10,"És ismét azt mondja: Örüljetek pogányok az õ népével együtt."));
husuperobject.biblemap.put("b45_15_11", new husuperobject(45,15,11,"És ismét: Dícsérjétek az Urat minden pogányok, és magasztaljátok õt minden népek."));
husuperobject.biblemap.put("b45_15_12", new husuperobject(45,15,12,"És viszont Ésaiás így szól: Lészen a Jessének gyökere, és a ki felkel, hogy uralkodjék a pogányokon; õ benne reménykednek a pogányok."));
husuperobject.biblemap.put("b45_15_13", new husuperobject(45,15,13,"A reménységnek Istene pedig töltsön be titeket minden örömmel és békességgel a hivésben, hogy bõvölködjetek a reménységben a Szent Lélek ereje által."));
husuperobject.biblemap.put("b45_15_14", new husuperobject(45,15,14,"Meg vagyok pedig gyõzõdve atyámfiai én magam is ti felõletek, hogy teljesek vagytok minden jósággal, betöltve minden ismerettel, képesek lévén egymást is inteni."));
husuperobject.biblemap.put("b45_15_15", new husuperobject(45,15,15,"Bátorságosabban írtam pedig néktek atyámfiai, részben, mintegy emlékeztetvén titeket az Istentõl nékem adott kegyelem által,"));
husuperobject.biblemap.put("b45_15_16", new husuperobject(45,15,16,"Hogy legyek a Jézus Krisztus szolgája a pogányok között, munkálkodván az Isten evangyéliomában, hogy legyen a pogányoknak áldozata kedves [és] a Szent Lélek által megszentelt."));
husuperobject.biblemap.put("b45_15_17", new husuperobject(45,15,17,"Van azért mivel dicsekedjem a Jézus Krisztusban, az Istenre tartozó dolgokban."));
husuperobject.biblemap.put("b45_15_18", new husuperobject(45,15,18,"Mert nem merek szólni semmirõl, a mit nem Krisztus cselekedett volna általam a pogányoknak engedelmességére, szóval és tettel."));
husuperobject.biblemap.put("b45_15_19", new husuperobject(45,15,19,"Jelek és csodák ereje által, az Isten Lelkének ereje által; úgyannyira, hogy én Jeruzsálemtõl és környékétõl fogva Illyriáig betöltöttem a Krisztus evangyéliomát."));
husuperobject.biblemap.put("b45_15_20", new husuperobject(45,15,20,"Ekképen pedig tisztességbeli dolog, hogy ne ott hirdessem az evangyéliomot, ahol neveztetett Krisztus, hogy ne más alapra építsek:"));
husuperobject.biblemap.put("b45_15_21", new husuperobject(45,15,21,"Hanem a mint meg van írva: A kiknek nem hirdettetett õ felõle, azok meglátják; és a kik nem hallották, megértik."));
husuperobject.biblemap.put("b45_15_22", new husuperobject(45,15,22,"Annakokáért meg is akadályoztattam gyakran a hozzátok való menetelben."));
husuperobject.biblemap.put("b45_15_23", new husuperobject(45,15,23,"Most pedig, mivelhogy nincs már helyem e tartományokban, vágyódván pedig sok esztendõ óta, hogy elmenjek hozzátok:"));
husuperobject.biblemap.put("b45_15_24", new husuperobject(45,15,24,"Ha Hispániába megyek, elmegyek ti hozzátok. Mert remélem, hogy átutazóban meglátlak titeket, és ti elkísértek oda, ha elõbb részben beteljesedem veletek."));
husuperobject.biblemap.put("b45_15_25", new husuperobject(45,15,25,"Most pedig megyek Jeruzsálembe, szolgálván a szenteknek."));
husuperobject.biblemap.put("b45_15_26", new husuperobject(45,15,26,"Mert tetszett Macedóniának és Akhájának, hogy a Jeruzsálembeli szentek szegényei részére némileg adakozzanak."));
husuperobject.biblemap.put("b45_15_27", new husuperobject(45,15,27,"Mert tetszett nékik, és tartoznak is vele. Mert ha a pogányok azoknak a lelki javaiban részesültek, tartoznak nékik viszont szolgálni a testiekben."));
husuperobject.biblemap.put("b45_15_28", new husuperobject(45,15,28,"Ezt azért ha majd elvégezem, és nékik e gyümölcsöt átadom, elmegyek közöttetek által Hispániába."));
husuperobject.biblemap.put("b45_15_29", new husuperobject(45,15,29,"Tudom pedig, hogy mikor hozzátok megyek, a Krisztus evangyélioma áldásának teljességével megyek."));
husuperobject.biblemap.put("b45_15_30", new husuperobject(45,15,30,"Kérlek pedig titeket atyámfiai a mi Urunk Jézus Krisztusra és a Lélek szerelmére, tusakodjatok velem együtt az imádkozásokban, én érettem Isten elõtt,"));
husuperobject.biblemap.put("b45_15_31", new husuperobject(45,15,31,"Hogy szabaduljak meg azoktól, a kik engedetlenek Júdeában, és hogy az én Jeruzsálemben való szolgálatom legyen kedves a szentek elõtt;"));
husuperobject.biblemap.put("b45_15_32", new husuperobject(45,15,32,"Hogy örömmel menjek hozzátok az Isten akaratából, és veletek együtt megújuljak."));
husuperobject.biblemap.put("b45_15_33", new husuperobject(45,15,33,"A békességnek Istene pedig legyen mindnyájan ti veletek! Ámen."));
husuperobject.biblemap.put("b45_16_1", new husuperobject(45,16,1,"Ajánlom pedig néktek Fébét, a mi nénénket, ki a Kenkhréabeli gyülekezetnek szolgálója:"));
husuperobject.biblemap.put("b45_16_2", new husuperobject(45,16,2,"Hogy fogadjátok õt az Úrban szentekhez illendõen, és legyetek mellette, ha valami dologban rátok szorul. Mert õ is sokaknak pártfogója volt, nékem magamnak is."));
husuperobject.biblemap.put("b45_16_3", new husuperobject(45,16,3,"Köszöntsétek Priscillát és Akvilát, kik nékem munkatársaim Krisztus Jézusban."));
husuperobject.biblemap.put("b45_16_4", new husuperobject(45,16,4,"A kik az én életemért a saját nyakukat tették le; a kiknek nemcsak én mondok köszönetet, hanem a pogányok minden gyülekezete is."));
husuperobject.biblemap.put("b45_16_5", new husuperobject(45,16,5,"És köszöntsétek azt a gyülekezetet, mely az õ házokban van. Köszöntsétek az én szerelmetes Epenétusomat, a ki Akhája zsengéje a Krisztusban."));
husuperobject.biblemap.put("b45_16_6", new husuperobject(45,16,6,"Köszöntsétek Máriát, ki sokat munkálkodott körülöttünk."));
husuperobject.biblemap.put("b45_16_7", new husuperobject(45,16,7,"Köszöntsétek Andronikust és Juniát az én rokonaimat és az én fogolytársaimat, a kik híresek az apostolok között, a kik nálamnál is elõbb voltak a Krisztusban."));
husuperobject.biblemap.put("b45_16_8", new husuperobject(45,16,8,"Köszöntsétek Ampliást, ki nékem szerelmesem az Úrban."));
husuperobject.biblemap.put("b45_16_9", new husuperobject(45,16,9,"Köszöntsétek Orbánt, a mi munkatársunkat a Krisztusban, és Stakhist az én szerelmesemet."));
husuperobject.biblemap.put("b45_16_10", new husuperobject(45,16,10,"Köszöntsétek Apellest, ki a Krisztusban megpróbáltatott. Köszöntsétek az Aristóbulus [háznépébõl valókat.]"));
husuperobject.biblemap.put("b45_16_11", new husuperobject(45,16,11,"Köszöntsétek Heródiont az én rokonomat. Köszöntsétek a Nárcissus [háznépébõl] azokat, a kik az Úrban vannak."));
husuperobject.biblemap.put("b45_16_12", new husuperobject(45,16,12,"Köszöntsétek Trifénát és Trifósát, kik munkálódnak az Úrban. Köszöntsétek a szerelmetes Persist, ki sokat munkálódott az Úrban."));
husuperobject.biblemap.put("b45_16_13", new husuperobject(45,16,13,"Köszöntsétek Rufust, ki kiválasztott az Úrban, és az õ anyját, a ki az enyém is."));
husuperobject.biblemap.put("b45_16_14", new husuperobject(45,16,14,"Köszöntsétek Ásinkritust, Flégont, Hermást, Pátrobást, Merkuriust, és az atyafiakat, kik velök vannak."));
husuperobject.biblemap.put("b45_16_15", new husuperobject(45,16,15,"Köszöntsétek Filológust és Juliát, Néreust és az õ nénjét, és Olimpást és minden szenteket, kik velök vannak."));
husuperobject.biblemap.put("b45_16_16", new husuperobject(45,16,16,"Köszöntsétek egymást szent csókolással. Köszöntenek titeket a Krisztus gyülekezetei."));
husuperobject.biblemap.put("b45_16_17", new husuperobject(45,16,17,"Kérlek pedig titeket atyámfiai, vigyázzatok azokra, a kik szakadásokat és botránkozásokat okoznak a tudomány körül, melyet tanultatok; és azoktól hajoljatok el."));
husuperobject.biblemap.put("b45_16_18", new husuperobject(45,16,18,"Mert az ilyenek a mi Urunk Jézus Krisztusnak nem szolgálnak, hanem az õ hasuknak; és nyájas beszéddel, meg hizelkedéssel megcsalják az ártatlanoknak szívét."));
husuperobject.biblemap.put("b45_16_19", new husuperobject(45,16,19,"Mert a ti engedelmességetek mindenekhez eljutott. Örülök azért rajtatok; de akarom, hogy bölcsek legyetek a jóban, ártatlanok pedig a rosszban."));
husuperobject.biblemap.put("b45_16_20", new husuperobject(45,16,20,"A békességnek Istene megrontja a Sátánt a ti lábaitok alatt hamar. A mi Urunk Jézus Krisztus kegyelme veletek. Ámen."));
husuperobject.biblemap.put("b45_16_21", new husuperobject(45,16,21,"Köszöntenek titeket Timótheus, az én munkatársam, és Luczius, Jáson, és Sosipáter az én rokonaim."));
husuperobject.biblemap.put("b45_16_22", new husuperobject(45,16,22,"Köszöntelek titeket az Úrban én Tertius, ki e levelet írtam."));
husuperobject.biblemap.put("b45_16_23", new husuperobject(45,16,23,"Köszönt titeket Gájus, a ki nékem és az egész gyülekezetnek gazdája. Köszönt titeket Erástus a városnak kincstartója, és Kvártus atyafi."));
husuperobject.biblemap.put("b45_16_24", new husuperobject(45,16,24,"A mi Urunk Jézus Krisztus kegyelme mindnyájan ti veletek. Ámen."));
husuperobject.biblemap.put("b45_16_25", new husuperobject(45,16,25,"Annak pedig, a ki titeket megerõsíthet az én evangyéliomom és a Jézus Krisztus hirdetése szerint, ama titoknak kijelentése folytán, mely örök idõtõl fogva el volt hallgatva,"));
husuperobject.biblemap.put("b45_16_26", new husuperobject(45,16,26,"Most pedig megjelentetett a prófétai írások által, az örök Isten parancsolata szerint, a hitben való engedelmesség végett minden pogányoknak tudomására adatván,"));
husuperobject.biblemap.put("b45_16_27", new husuperobject(45,16,27,"Az egyedül bölcs Istennek a Jézus Krisztus által dicsõség mindörökké. Ámen."));

}

}