package hu.bible;

public class hubible48 {

public hubible48() {

putmapbible48();

}

private void putmapbible48() {

husuperobject.biblemap.put("b48_1_1", new husuperobject(48,1,1,"Pál, apostol (nem emberektõl, sem nem ember által, hanem Jézus Krisztus által és az Atya Isten által, a ki feltámasztotta õt a halálból);"));
husuperobject.biblemap.put("b48_1_2", new husuperobject(48,1,2,"És a velem levõ összes atyafiak, Galátzia gyülekezeteinek:"));
husuperobject.biblemap.put("b48_1_3", new husuperobject(48,1,3,"Kegyelem néktek és békesség az Atya Istentõl, és a mi Urunk Jézus Krisztustól,"));
husuperobject.biblemap.put("b48_1_4", new husuperobject(48,1,4,"A ki adta önmagát a mi bûneinkért hogy kiszabadítson minket e jelenvaló gonosz világból, az Istennek és a mi Atyánknak akarata szerint."));
husuperobject.biblemap.put("b48_1_5", new husuperobject(48,1,5,"A kinek dicsõség örökkön örökké! Ámen."));
husuperobject.biblemap.put("b48_1_6", new husuperobject(48,1,6,"Csodálkozom, hogy Attól, a ki titeket Krisztus kegyelme által elhívott, ily hamar más evangyéliomra hajlotok."));
husuperobject.biblemap.put("b48_1_7", new husuperobject(48,1,7,"Holott nincs más; de némelyek zavarnak titeket, és el akarják ferdíteni a Krisztus evangyéliomát."));
husuperobject.biblemap.put("b48_1_8", new husuperobject(48,1,8,"De ha szinte mi, avagy mennybõl való angyal hirdetne is néktek valamit azon kívül, a mit néktek hirdettünk, legyen átok."));
husuperobject.biblemap.put("b48_1_9", new husuperobject(48,1,9,"A mint elõbb mondottuk, most is ismét mondom: Ha valaki néktek hirdet valamit azon kívül, a mit elfogadtatok, átok legyen."));
husuperobject.biblemap.put("b48_1_10", new husuperobject(48,1,10,"Mert most embereknek engedek-é, avagy az Istennek? Vagy embereknek igyekezem-é tetszeni? Bizonyára, ha még embereknek igyekezném tetszeni, Krisztus szolgája nem volnék."));
husuperobject.biblemap.put("b48_1_11", new husuperobject(48,1,11,"Tudtotokra adom pedig atyámfiai, hogy az az evangyéliom, melyet én hirdettem, nem ember szerint való;"));
husuperobject.biblemap.put("b48_1_12", new husuperobject(48,1,12,"Mert én sem embertõl vettem azt, sem nem tanítottak arra, hanem a Jézus Krisztus kijelentése által."));
husuperobject.biblemap.put("b48_1_13", new husuperobject(48,1,13,"Mert hallottátok, mint forgolódtam én egykor a zsidóságban, hogy én felette igen háborgattam az Isten anyaszentegyházát, és pusztítottam azt."));
husuperobject.biblemap.put("b48_1_14", new husuperobject(48,1,14,"És felülmultam a zsidóságban nemzetembeli sok kortársamat, szerfelett rajongván atyai hagyományaimért."));
husuperobject.biblemap.put("b48_1_15", new husuperobject(48,1,15,"De mikor az Istennek tetszett, ki elválasztott engem az én anyám méhétõl fogva és elhívott az õ kegyelme által,"));
husuperobject.biblemap.put("b48_1_16", new husuperobject(48,1,16,"Hogy kijelentse az õ Fiát én bennem, hogy hirdessem õt a pogányok között: azonnal nem tanácskoztam testtel és vérrel,"));
husuperobject.biblemap.put("b48_1_17", new husuperobject(48,1,17,"Sem nem mentem Jeruzsálembe az elõttem való apostolokhoz, hanem elmentem Arábiába, és ismét visszatértem Damaskusba."));
husuperobject.biblemap.put("b48_1_18", new husuperobject(48,1,18,"Azután három esztendõ mulva fölmentem Jeruzsálembe, hogy Pétert meglátogassam, és nála maradtam tizenöt napig."));
husuperobject.biblemap.put("b48_1_19", new husuperobject(48,1,19,"Az apostolok közül pedig mást nem láttam, hanem [csak] Jakabot, az Úr atyjafiát."));
husuperobject.biblemap.put("b48_1_20", new husuperobject(48,1,20,"A miket pedig néktek írok, ímé Isten elõtt [mondom,] hogy nem hazudom."));
husuperobject.biblemap.put("b48_1_21", new husuperobject(48,1,21,"Azután mentem Siriának és Ciliciának tartományaiba."));
husuperobject.biblemap.put("b48_1_22", new husuperobject(48,1,22,"Ismeretlen valék pedig személyesen a Júdeában levõ keresztyén gyülekezetek elõtt;"));
husuperobject.biblemap.put("b48_1_23", new husuperobject(48,1,23,"Hanem csak hallották, hogy: A ki minket üldözött egykor, most hirdeti azt a hitet, a melyet egykor pusztított."));
husuperobject.biblemap.put("b48_1_24", new husuperobject(48,1,24,"És dicsõíték bennem az Istent."));
husuperobject.biblemap.put("b48_2_1", new husuperobject(48,2,1,"Azután tizennégy esztendõ mulva ismét fölmentem Jeruzsálembe Barnabással együtt, elvivén Titust is."));
husuperobject.biblemap.put("b48_2_2", new husuperobject(48,2,2,"Fölmentem pedig kijelentés következtében és eléjök adtam az evangyéliomot, melyet hirdetek a pogányok között, de külön a tekintélyeseknek, hogy valami módon hiába ne fussak, avagy ne futottam légyen."));
husuperobject.biblemap.put("b48_2_3", new husuperobject(48,2,3,"De még a velem levõ Titus sem kényszeríttetett a körülmetélkedésre, noha görög vala,"));
husuperobject.biblemap.put("b48_2_4", new husuperobject(48,2,4,"Tudniillik a belopózkodott hamis atyafiakért, a kik alattomban közénk jöttek, hogy kikémleljék a mi szabadságunkat, melylyel bírunk a Krisztus Jézusban, hogy minket szolgákká tegyenek:"));
husuperobject.biblemap.put("b48_2_5", new husuperobject(48,2,5,"Kiknek egy pillanatra sem adtuk meg magunkat, hogy az evangyéliom igazsága megmaradjon számotokra."));
husuperobject.biblemap.put("b48_2_6", new husuperobject(48,2,6,"A tekintélyesektõl pedig, (bárminõk valának régen, azzal nem törõdöm; Isten nem nézi az embernek személyét : mert velem a tekintélyesek semmit sem közöltek;"));
husuperobject.biblemap.put("b48_2_7", new husuperobject(48,2,7,"Sõt ellenkezõleg, mikor látták, hogy én reám van bízva a körülmetéletlenség evangyélioma, mint Péterre a körülmetélésé;"));
husuperobject.biblemap.put("b48_2_8", new husuperobject(48,2,8,"(Mert a ki erõs volt Péterben a körülmetélkedés apostolságára, bennem is erõs volt a pogányok között)."));
husuperobject.biblemap.put("b48_2_9", new husuperobject(48,2,9,"És elismervén a nékem adatott kegyelmet, Jakab és Kéfás, meg János, kik oszlopokul tekintetnek, bajtársi jobbjukat nyujták nékem és Barnabásnak, hogy mi a pogányok között, õk pedig a körülmetélés között [prédikáljunk:]"));
husuperobject.biblemap.put("b48_2_10", new husuperobject(48,2,10,"Csakhogy a szegényekrõl megemlékezzünk; a mit is én igyekeztem megcselekedni."));
husuperobject.biblemap.put("b48_2_11", new husuperobject(48,2,11,"Mikor pedig Péter Antiókhiába jött, szemtõl szembe ellene állottam, mivel panasz volt rá."));
husuperobject.biblemap.put("b48_2_12", new husuperobject(48,2,12,"Mert mielõtt némelyek oda jöttek Jakabtól, a pogányokkal együtt evett; mikor pedig oda jöttek, félrevonult és elkülönítette magát, félvén a körülmetélkedésbõl valóktól."));
husuperobject.biblemap.put("b48_2_13", new husuperobject(48,2,13,"És vele képmutatóskodtak a többi zsidók is, úgy hogy Barnabás szintén elcsábíttatott az õ tettetésök által."));
husuperobject.biblemap.put("b48_2_14", new husuperobject(48,2,14,"De mikor láttam, hogy nem egyenesen járnak az evangyéliom igazságához képest, mondék Péternek mindnyájok elõtt: Ha te zsidó létedre pogány módra élsz és nem zsidó módra, miként kényszeríted a pogányokat, hogy zsidó módra éljenek?"));
husuperobject.biblemap.put("b48_2_15", new husuperobject(48,2,15,"Mi, természet szerint zsidók és nem pogányok közül való bûnösök,"));
husuperobject.biblemap.put("b48_2_16", new husuperobject(48,2,16,"Tudván azt, hogy az ember nem igazul meg a törvény cselekedeteibõl, hanem a Jézus Krisztusban való hit által, mi is Krisztus Jézusban hittünk, hogy megigazuljunk a Krisztusban való hitbõl és nem a törvény cselekedeteibõl; Mivel a törvény cselekedeteibõl nem igazul meg egy test sem."));
husuperobject.biblemap.put("b48_2_17", new husuperobject(48,2,17,"Ha pedig Krisztusban keresvén a megigazulást, mimagunk is bûnösöknek találtatunk, avagy Krisztus bûnnek szolgája-é? Távol legyen."));
husuperobject.biblemap.put("b48_2_18", new husuperobject(48,2,18,"Mert, ha a miket elrontottam, azokat ismét fölépítem, önmagamat teszem bûnössé."));
husuperobject.biblemap.put("b48_2_19", new husuperobject(48,2,19,"Mert én a törvény által meghaltam a törvénynek, hogy Istennek éljek."));
husuperobject.biblemap.put("b48_2_20", new husuperobject(48,2,20,"Krisztussal együtt megfeszíttettem. Élek pedig többé nem én, hanem él bennem a Krisztus; a mely életet pedig most testben élek, az Isten Fiában való hitben élem, a ki szeretett engem és önmagát adta érettem."));
husuperobject.biblemap.put("b48_2_21", new husuperobject(48,2,21,"Nem törlöm el az Isten kegyelmét; mert ha a törvény által [van] az igazság, tehát Krisztus ok nélkül halt meg."));
husuperobject.biblemap.put("b48_3_1", new husuperobject(48,3,1,"Óh balgatag Galátziabeliek, kicsoda ígézett meg titeket, hogy ne engedelmeskedjetek az igazságnak, kiknek szemei elõtt a Jézus Krisztus úgy íratott le, [mintha] ti köztetek feszíttetett [volna] meg?"));
husuperobject.biblemap.put("b48_3_2", new husuperobject(48,3,2,"Csak azt akarom megtudni tõletek: a törvény cselekedeteibõl kaptátok-é a Lelket, avagy a hit hallásából?"));
husuperobject.biblemap.put("b48_3_3", new husuperobject(48,3,3,"Ennyire esztelenek vagytok? A mit Lélekben kezdtetek el, most testben fejeznétek be?"));
husuperobject.biblemap.put("b48_3_4", new husuperobject(48,3,4,"Annyit szenvedtetek hiába? ha ugyan hiába."));
husuperobject.biblemap.put("b48_3_5", new husuperobject(48,3,5,"Annakokáért, a ki a Lelket szolgáltatja néktek, és hatalmas dolgokat mûvel bennetek, a törvény cselekedeteibõl, vagy a hit hallásából [cselekeszi-é?]"));
husuperobject.biblemap.put("b48_3_6", new husuperobject(48,3,6,"Miképen Ábrahám hitt az Istennek, és tulajdoníttatott néki igazságul."));
husuperobject.biblemap.put("b48_3_7", new husuperobject(48,3,7,"Értsétek meg tehát, hogy a kik hitbõl vannak, azok az Ábrahám fiai."));
husuperobject.biblemap.put("b48_3_8", new husuperobject(48,3,8,"Elõre látván pedig az Írás, hogy Isten hitbõl fogja megigazítani a pogányokat, eleve hirdette Ábrahámnak, hogy: Te benned fognak megáldatni minden népek."));
husuperobject.biblemap.put("b48_3_9", new husuperobject(48,3,9,"Ekként a hitbõl valók áldatnak meg a hívõ Ábrahámmal."));
husuperobject.biblemap.put("b48_3_10", new husuperobject(48,3,10,"Mert a kik törvény cselekedeteibõl vannak, átok alatt vannak; minthogy meg van írva: Átkozott minden, a ki meg nem marad mindazokban, a mik megirattak a törvény könyvében, hogy azokat cselekedje."));
husuperobject.biblemap.put("b48_3_11", new husuperobject(48,3,11,"Hogy pedig a törvény által senki sem igazul meg Isten elõtt, nyilvánvaló, mert az igaz ember hitbõl él."));
husuperobject.biblemap.put("b48_3_12", new husuperobject(48,3,12,"A törvény pedig nincs hitbõl, hanem a mely ember cselekeszi azokat, élni fog azok által."));
husuperobject.biblemap.put("b48_3_13", new husuperobject(48,3,13,"Krisztus váltott meg minket a törvény átkától, átokká levén érettünk; mert meg van írva: Átkozott minden, a ki fán függ:"));
husuperobject.biblemap.put("b48_3_14", new husuperobject(48,3,14,"Hogy az Ábrahám áldása Krisztus Jézusban legyen a pogányokon, hogy a Lélek ígéretét elnyerjük hit által."));
husuperobject.biblemap.put("b48_3_15", new husuperobject(48,3,15,"Atyámfiai! ember szerint szólok. Lám az embernek megerõsített testámentomát senki erõtelenné nem teszi, sem ahhoz hozzá nem ád."));
husuperobject.biblemap.put("b48_3_16", new husuperobject(48,3,16,"Az ígéretek pedig Ábrahámnak adattak és az õ magvának. Nem mondja: És a magvaknak, mint sokról; hanem mint egyrõl. És a te magodnak, a ki a Krisztus."));
husuperobject.biblemap.put("b48_3_17", new husuperobject(48,3,17,"Ezt mondom pedig, hogy a kötést, melyet Isten elõször megerõsített a Krisztusra nézve, a négyszázharmincz esztendõ multán keletkezett törvény nem teszi erõtelenné, hogy megsemmisítse az ígéretet."));
husuperobject.biblemap.put("b48_3_18", new husuperobject(48,3,18,"Mert ha törvénybõl [van] az örökség, akkor többé nem ígéretbõl; Ábrahámnak pedig ígéret által ajándékozta azt az Isten."));
husuperobject.biblemap.put("b48_3_19", new husuperobject(48,3,19,"Micsoda tehát a törvény? A bûnök okáért adatott, a míg eljõ a Mag, a kinek tétetett az ígéret; rendeltetvén angyalok által, közbenjáró kezében."));
husuperobject.biblemap.put("b48_3_20", new husuperobject(48,3,20,"A közbenjáró pedig nem egyé, Isten ellenben egy."));
husuperobject.biblemap.put("b48_3_21", new husuperobject(48,3,21,"A törvény tehát az Isten ígéretei ellen van-é? Távol legyen! Mert ha olyan törvény adatott volna, a mely képes megeleveníteni, valóban a törvénybõl volna az igazság."));
husuperobject.biblemap.put("b48_3_22", new husuperobject(48,3,22,"De az Írás mindent bûn alá rekesztett, hogy az ígéret Jézus Krisztusban való hitbõl adassék a hívõknek."));
husuperobject.biblemap.put("b48_3_23", new husuperobject(48,3,23,"Minekelõtte pedig eljött a hit, törvény alatt õriztettünk, egybezárva az eljövendõ hit kinyilatkoztatásáig."));
husuperobject.biblemap.put("b48_3_24", new husuperobject(48,3,24,"Ekként a törvény Krisztusra vezérlõ mesterünkké lett, hogy hitbõl igazuljunk meg."));
husuperobject.biblemap.put("b48_3_25", new husuperobject(48,3,25,"De minekutána eljött a hit, nem vagyunk többé a vezérlõ mester alatt."));
husuperobject.biblemap.put("b48_3_26", new husuperobject(48,3,26,"Mert mindnyájan Isten fiai vagytok a Krisztus Jézusban való hit által."));
husuperobject.biblemap.put("b48_3_27", new husuperobject(48,3,27,"Mert a kik Krisztusba keresztelkedtetek meg, Krisztust öltöztétek fel."));
husuperobject.biblemap.put("b48_3_28", new husuperobject(48,3,28,"Nincs zsidó, sem görög; nincs szolga, sem szabad; nincs férfi, sem nõ; mert ti mindnyájan egyek vagytok a Krisztus Jézusban."));
husuperobject.biblemap.put("b48_3_29", new husuperobject(48,3,29,"Ha pedig Krisztuséi vagytok, tehát az Ábrahám magva vagytok, és ígéret szerint örökösök."));
husuperobject.biblemap.put("b48_4_1", new husuperobject(48,4,1,"Mondom pedig, hogy a meddig az örökös kiskorú, semmiben sem különbözik a szolgától, jóllehet ura mindennek;"));
husuperobject.biblemap.put("b48_4_2", new husuperobject(48,4,2,"Hanem gyámok és gondviselõk alatt van az atyjától rendelt ideig."));
husuperobject.biblemap.put("b48_4_3", new husuperobject(48,4,3,"Azonképen mi is, mikor kiskorúak valánk, a világ elemei alá voltunk vettetve szolgaként:"));
husuperobject.biblemap.put("b48_4_4", new husuperobject(48,4,4,"Mikor pedig eljött az idõnek teljessége, kibocsátotta Isten az õ Fiát, a ki asszonytól lett, a ki törvény alatt lett,"));
husuperobject.biblemap.put("b48_4_5", new husuperobject(48,4,5,"Hogy a törvény alatt levõket megváltsa, hogy elnyerjük a fiúságot."));
husuperobject.biblemap.put("b48_4_6", new husuperobject(48,4,6,"Minthogy pedig fiak vagytok, kibocsátotta az Isten az õ Fiának Lelkét a ti szíveitekbe, ki ezt kiáltja: Abba, Atya!"));
husuperobject.biblemap.put("b48_4_7", new husuperobject(48,4,7,"Azért nem vagy többé szolga, hanem fiú; ha pedig fiú, Istennek örököse is Krisztus által."));
husuperobject.biblemap.put("b48_4_8", new husuperobject(48,4,8,"Ámde akkor, mikor még nem ismertétek az Istent, azoknak szolgáltatok, a mik természet szerint nem istenek;"));
husuperobject.biblemap.put("b48_4_9", new husuperobject(48,4,9,"Most azonban, hogy megismertétek az Istent, sõt hogy megismert titeket az Isten, miként tértek vissza ismét az erõtelen és gyarló elemekhez, a melyeknek megint újból szolgálni akartok?"));
husuperobject.biblemap.put("b48_4_10", new husuperobject(48,4,10,"Megtartjátok a napokat és hónapokat és idõket, meg az esztendõket."));
husuperobject.biblemap.put("b48_4_11", new husuperobject(48,4,11,"Féltelek titeket, hogy hiába fáradoztam körültetek."));
husuperobject.biblemap.put("b48_4_12", new husuperobject(48,4,12,"Legyetek olyanok, mint én; mert én is olyanná lettem, mint ti: atyámfiai, kérlek titeket, semmivel sem bántottatok meg engem."));
husuperobject.biblemap.put("b48_4_13", new husuperobject(48,4,13,"Tudjátok pedig, hogy testem erõtelensége miatt hirdettem néktek az evangyéliomot elõször."));
husuperobject.biblemap.put("b48_4_14", new husuperobject(48,4,14,"És megkísértetvén testemben, nem vetettetek meg, sem nem útáltatok meg engem, hanem úgy fogadtatok, mint Istennek angyalát, mint Krisztus Jézust."));
husuperobject.biblemap.put("b48_4_15", new husuperobject(48,4,15,"Hová lõn tehát a ti boldogságotok? Mert bizonyságot teszek néktek, hogy ti, ha lehetséges volt volna, szemeiteket kivájván, nékem adtátok volna."));
husuperobject.biblemap.put("b48_4_16", new husuperobject(48,4,16,"Tehát ellenségetek lettem-é, megmondván néktek az igazat?"));
husuperobject.biblemap.put("b48_4_17", new husuperobject(48,4,17,"Nem szépen buzgolkodnak érettetek, sõt minket ki akarnak rekeszteni, hogy mellettök buzgolkodjatok."));
husuperobject.biblemap.put("b48_4_18", new husuperobject(48,4,18,"Szép dolog pedig fáradozni a jóban mindenkor, és nem csupán akkor, ha köztetek vagyok."));
husuperobject.biblemap.put("b48_4_19", new husuperobject(48,4,19,"Gyermekeim! kiket ismét fájdalommal szûlök, míglen kiábrázolódik bennetek Krisztus."));
husuperobject.biblemap.put("b48_4_20", new husuperobject(48,4,20,"Szeretnék pedig most köztetek jelen lenni és változtatni a hangomon; mert bizonytalanságban vagyok felõletek."));
husuperobject.biblemap.put("b48_4_21", new husuperobject(48,4,21,"Mondjátok meg nékem, kik a törvény alatt akartok lenni: nem halljátok-é a törvényt?"));
husuperobject.biblemap.put("b48_4_22", new husuperobject(48,4,22,"Mert meg van írva, hogy Ábrahámnak két fia volt; egyik a szolgálótól, és a másik a szabadostól."));
husuperobject.biblemap.put("b48_4_23", new husuperobject(48,4,23,"De a szolgálótól való test szerint született; a szabadostól való pedig az ígéret által."));
husuperobject.biblemap.put("b48_4_24", new husuperobject(48,4,24,"Ezek mást példáznak: mert azok [az] [asszonyok] a két szövetség, az egyik a Sinai hegyrõl való, szolgaságra szûlõ, ez Hágár,"));
husuperobject.biblemap.put("b48_4_25", new husuperobject(48,4,25,"Mert Hágár a Sinai hegy Arábiában, hasonlatos pedig a mostani Jeruzsálemhez, nevezetesen fiaival együtt szolgál."));
husuperobject.biblemap.put("b48_4_26", new husuperobject(48,4,26,"De a magasságos Jeruzsálem szabad, ez mindnyájunknak anyja,"));
husuperobject.biblemap.put("b48_4_27", new husuperobject(48,4,27,"Mert meg van írva: Ujjongj te meddõ, ki nem szûlsz; vígadozzál és kiálts, ki nem vajudol; mert sokkal több az elhagyottnak magzatja, mint a kinek férje vagyon."));
husuperobject.biblemap.put("b48_4_28", new husuperobject(48,4,28,"Mi pedig, atyámfiai, Izsák szerint, ígéretnek gyermekei vagyunk."));
husuperobject.biblemap.put("b48_4_29", new husuperobject(48,4,29,"De valamint akkor a test szerint született üldözte a Lélek szerint valót, úgy most is."));
husuperobject.biblemap.put("b48_4_30", new husuperobject(48,4,30,"De mit mond az Írás? Ûzd ki a szolgálót és az õ fiát; mert a szolgáló fia nem örököl a szabad nõ fiával."));
husuperobject.biblemap.put("b48_4_31", new husuperobject(48,4,31,"Annakokáért, atyámfiai, nem vagyunk a szolgáló fiai, hanem a szabadoséi."));
husuperobject.biblemap.put("b48_5_1", new husuperobject(48,5,1,"Annakokáért a szabadságban, melyre minket Krisztus megszabadított, álljatok meg, és ne kötelezzétek meg ismét magatokat szolgaságnak igájával."));
husuperobject.biblemap.put("b48_5_2", new husuperobject(48,5,2,"Ímé, én Pál mondom néktek, hogy ha körülmetélkedtek, Krisztus néktek semmit sem használ."));
husuperobject.biblemap.put("b48_5_3", new husuperobject(48,5,3,"Bizonyságot teszek pedig ismét minden embernek, a ki körülmetélkedik, hogy köteles az egész törvényt megtartani."));
husuperobject.biblemap.put("b48_5_4", new husuperobject(48,5,4,"Elszakadtatok Krisztustól, a kik a törvény által akartok megigazulni, a kegyelembõl kiestetek."));
husuperobject.biblemap.put("b48_5_5", new husuperobject(48,5,5,"Mert mi a Lélek által, hitbõl várjuk az igazság reménységét."));
husuperobject.biblemap.put("b48_5_6", new husuperobject(48,5,6,"Mert Krisztus Jézusban sem a körülmetélkedés nem ér semmit, sem a körülmetélkedetlenség, hanem a szeretet által munkálkodó hit."));
husuperobject.biblemap.put("b48_5_7", new husuperobject(48,5,7,"Jól futottatok; kicsoda gátolt meg titeket, hogy ne engedelmeskedjetek az igazságnak?"));
husuperobject.biblemap.put("b48_5_8", new husuperobject(48,5,8,"Ez a hitetés nem attól van, a ki titeket hív."));
husuperobject.biblemap.put("b48_5_9", new husuperobject(48,5,9,"Kis kovász az egész tésztát megkeleszti."));
husuperobject.biblemap.put("b48_5_10", new husuperobject(48,5,10,"Bizodalmam van az Úrban ti hozzátok, hogy más értelemben nem lesztek; de a ki titeket megzavar, elveszi az ítéletet, bárki legyen."));
husuperobject.biblemap.put("b48_5_11", new husuperobject(48,5,11,"Én pedig atyámfiai, ha még a körülmetélést hirdetem, miért üldöztetem mégis? Akkor eltöröltetett a kereszt botránya."));
husuperobject.biblemap.put("b48_5_12", new husuperobject(48,5,12,"Bárcsak ki is metszetnék magukat, a kik titeket bujtogatnak."));
husuperobject.biblemap.put("b48_5_13", new husuperobject(48,5,13,"Mert ti szabadságra hivattatok atyámfiai; csakhogy a szabadság ürügy ne legyen a testnek, sõt szeretettel szolgáljatok egymásnak."));
husuperobject.biblemap.put("b48_5_14", new husuperobject(48,5,14,"Mert az egész törvény ez egy ígében teljesedik be: Szeresd felebarátodat, mint magadat."));
husuperobject.biblemap.put("b48_5_15", new husuperobject(48,5,15,"Ha pedig egymást marjátok és faljátok, vigyázzatok, hogy egymást fel ne emészszétek."));
husuperobject.biblemap.put("b48_5_16", new husuperobject(48,5,16,"Mondom pedig, Lélek szerint járjatok, és a testnek kívánságát véghez ne vigyétek."));
husuperobject.biblemap.put("b48_5_17", new husuperobject(48,5,17,"Mert a test a lélek ellen törekedik, a lélek pedig a test ellen; ezek pedig egymással ellenkeznek, hogy ne azokat cselekedjétek, a miket akartok."));
husuperobject.biblemap.put("b48_5_18", new husuperobject(48,5,18,"Ha azonban a Lélektõl vezéreltettek, nem vagytok a törvény alatt."));
husuperobject.biblemap.put("b48_5_19", new husuperobject(48,5,19,"A testnek cselekedetei pedig nyilvánvalók, melyek [ezek]: házasságtörés, paráznaság, tisztátalanság, bujálkodás."));
husuperobject.biblemap.put("b48_5_20", new husuperobject(48,5,20,"Bálványimádás, varázslás, ellenségeskedések, versengések, gyûlölködések, harag, patvarkodások, viszszavonások, pártütések,"));
husuperobject.biblemap.put("b48_5_21", new husuperobject(48,5,21,"Irígységek, gyilkosságok, részegségek, dobzódások és ezekhez hasonlók: melyekrõl elõre mondom néktek, a miképen már ezelõtt is mondottam, hogy a kik ilyeneket cselekesznek, Isten országának örökösei nem lesznek."));
husuperobject.biblemap.put("b48_5_22", new husuperobject(48,5,22,"De a Léleknek gyümölcse: szeretet, öröm, békesség, béketûrés, szívesség, jóság, hûség, szelídség, mértékletesség."));
husuperobject.biblemap.put("b48_5_23", new husuperobject(48,5,23,"Az ilyenek ellen nincs törvény."));
husuperobject.biblemap.put("b48_5_24", new husuperobject(48,5,24,"A kik pedig Krisztuséi, a testet megfeszítették indulataival és kívánságaival együtt."));
husuperobject.biblemap.put("b48_5_25", new husuperobject(48,5,25,"Ha Lélek szerint élünk, Lélek szerint is járjunk."));
husuperobject.biblemap.put("b48_5_26", new husuperobject(48,5,26,"Ne legyünk hiú dicsõség kívánók, egymást ingerlõk, egymásra irígykedõk."));
husuperobject.biblemap.put("b48_6_1", new husuperobject(48,6,1,"Atyámfiai, még ha elõfogja is az embert valami bûn, ti lelkiek, igazítsátok útba az olyant szelídségnek lelkével, ügyelvén magadra, hogy meg ne kísértessél te magad is."));
husuperobject.biblemap.put("b48_6_2", new husuperobject(48,6,2,"Egymás terhét hordozzátok, és úgy töltsétek be a Krisztus törvényét."));
husuperobject.biblemap.put("b48_6_3", new husuperobject(48,6,3,"Mert ha valaki azt véli, hogy õ valami, holott semmi, önmagát csalja meg."));
husuperobject.biblemap.put("b48_6_4", new husuperobject(48,6,4,"Minden ember pedig az õ maga cselekedetét vizsgálja meg, és akkor csakis önmagára nézve lesz dicsekedése és nem másra nézve."));
husuperobject.biblemap.put("b48_6_5", new husuperobject(48,6,5,"Mert kiki a maga terhét hordozza."));
husuperobject.biblemap.put("b48_6_6", new husuperobject(48,6,6,"A ki pedig az ígére taníttatik, közölje minden javát tanítójával."));
husuperobject.biblemap.put("b48_6_7", new husuperobject(48,6,7,"Ne tévelyegjetek, Isten nem csúfoltatik meg; mert a mit vet az ember, azt aratándja is."));
husuperobject.biblemap.put("b48_6_8", new husuperobject(48,6,8,"Mert a ki vet az õ testének, a testbõl arat veszedelmet; a ki pedig vet a léleknek, a lélekbõl arat örök életet."));
husuperobject.biblemap.put("b48_6_9", new husuperobject(48,6,9,"A jótéteményben pedig meg ne restüljünk, mert a maga idejében aratunk, ha el nem lankadunk."));
husuperobject.biblemap.put("b48_6_10", new husuperobject(48,6,10,"Annakokáért míg idõnk van, cselekedjünk jót mindenekkel, kiváltképen pedig a mi hitünknek cselédeivel."));
husuperobject.biblemap.put("b48_6_11", new husuperobject(48,6,11,"Látjátok, mekkora betûkkel írok néktek a saját kezemmel!"));
husuperobject.biblemap.put("b48_6_12", new husuperobject(48,6,12,"A kik testre szépek szeretnének lenni, azok kényszerítenek titeket a körülmetélkedésre; csak azért, hogy a Krisztus keresztjéért ne üldöztessenek."));
husuperobject.biblemap.put("b48_6_13", new husuperobject(48,6,13,"Mert magok a körülmetélkedettek sem tartják meg a törvényt; hanem azért akarják, hogy ti körülmetélkedjetek, hogy a ti testetekkel dicsekedjenek."));
husuperobject.biblemap.put("b48_6_14", new husuperobject(48,6,14,"Nékem pedig ne legyen másban dicsekedésem, hanem a mi Urunk Jézus Krisztus keresztjében, a ki által nékem megfeszíttetett a világ, és én is a világnak."));
husuperobject.biblemap.put("b48_6_15", new husuperobject(48,6,15,"Mert Krisztus Jézusban sem a körülmetélkedés, sem a körülmetéletlenség nem használ semmit, hanem az új teremtés."));
husuperobject.biblemap.put("b48_6_16", new husuperobject(48,6,16,"És a kik e szabály szerint élnek, békesség és irgalmasság azokon, és az Istennek Izráelén."));
husuperobject.biblemap.put("b48_6_17", new husuperobject(48,6,17,"Ennekutána senki nékem bántásomra ne legyen; mert én az Úr Jézusnak bélyegeit hordozom az én testemben."));
husuperobject.biblemap.put("b48_6_18", new husuperobject(48,6,18,"A mi Urunk Jézus Krisztusnak kegyelme legyen a ti lelketekkel atyámfiai! Ámen."));

}

}