package hu.bible;

public class hubible16 {

public hubible16() {

putmapbible16();

}

private void putmapbible16() {

husuperobject.biblemap.put("b16_1_1", new husuperobject(16,1,1,"Nehémiásnak, a Hakália fiának beszédei."));
husuperobject.biblemap.put("b16_1_2", new husuperobject(16,1,2,"És jöve hozzám Hanáni, egy az én atyámfiai közül, és vele együtt férfiak Júdából, és tudakozódtam tõlök a fogságból megszabadult maradék zsidók felõl és Jeruzsálem felõl."));
husuperobject.biblemap.put("b16_1_3", new husuperobject(16,1,3,"És mondának nékem: A fogságból megszabadult maradék zsidók ott abban a tartományban nagy nyomorúságban és gyalázatban vannak; és azonfelül Jeruzsálem kõfala lerontatott, s kapui tûzben égtek meg!"));
husuperobject.biblemap.put("b16_1_4", new husuperobject(16,1,4,"Hogy pedig meghallám e beszédeket, leültem és sírtam és keseregtem napokon át, s bõjtölék és imádkozám a mennynek Istene elõtt;"));
husuperobject.biblemap.put("b16_1_5", new husuperobject(16,1,5,"És mondék: Kérlek Uram, mennynek Istene, nagy és rettenetes Isten! Ki megtartja a szövetséget és irgalmasságot az õt szeretõknek és az õ parancsolatait megtartóknak;"));
husuperobject.biblemap.put("b16_1_6", new husuperobject(16,1,6,"Oh, legyen figyelmetes a te füled, és szemeid legyenek nyitva, hogy meghallgassad a te szolgádnak könyörgését, melylyel én könyörgök most elõtted nappal és éjjel Izráel fiaiért, szolgáidért, és vallást tészek az Izráel fiainak bûneirõl, melyekkel vétkeztünk te ellened, én is s az én atyámnak háza vétkeztünk!"));
husuperobject.biblemap.put("b16_1_7", new husuperobject(16,1,7,"Felette igen vétkeztünk ellened, és nem tartottuk meg a parancsolatokat, és a rendeléseket és a törvényeket, melyeket parancsoltál volt Mózesnek a te szolgádnak."));
husuperobject.biblemap.put("b16_1_8", new husuperobject(16,1,8,"Oh, emlékezzél meg arról a beszédrõl, melyet parancsoltál Mózesnek, a te szolgádnak, mondván: [Ha] ti vétkeztek, én [meg] elszélesztelek titeket a népek között;"));
husuperobject.biblemap.put("b16_1_9", new husuperobject(16,1,9,"Ha pedig megtérendetek hozzám és megtartjátok parancsolataimat és cselekeszitek azokat: még ha az égnek utolsó szélén volnának is szétszórt [gyermekeitek,] onnan is összegyûjtöm õket és beviszem arra a helyre, melyet választottam, hogy lakozzék ott az én nevem!"));
husuperobject.biblemap.put("b16_1_10", new husuperobject(16,1,10,"És õk a te szolgáid és a te néped, a kiket megszabadítottál a te nagy erõd által és a te erõs kezed által!"));
husuperobject.biblemap.put("b16_1_11", new husuperobject(16,1,11,"Kérlek oh Uram, legyen figyelmetes a te füled a te szolgádnak könyörgésére és szolgáidnak könyörgésökre, a kik kívánják félni a te nevedet, és adj, kérlek, jó szerencsét most a te szolgádnak, és engedd, hogy kegyelmet találjon ama férfiú elõtt. Én ugyanis a királynak pohárnoka voltam."));
husuperobject.biblemap.put("b16_2_1", new husuperobject(16,2,1,"És lõn a Niszán [nevû] hóban, Artaxerxes királynak huszadik esztendejében, bor vala õ elõtte és én fölvevém a bort, adám a királynak; [azelõtt] pedig nem voltam szomorú õ elõtte."));
husuperobject.biblemap.put("b16_2_2", new husuperobject(16,2,2,"És monda nékem a király: Miért szomorú a te orczád, holott te beteg nem vagy? Nem egyéb ez, hanem szívednek szomorúsága! És felette igen megfélemlém."));
husuperobject.biblemap.put("b16_2_3", new husuperobject(16,2,3,"Akkor mondék a királynak: Örökké éljen a király! Miért nem volna szomorú az én orczám, hiszen a város, az én atyáim sírjainak helye, pusztán hever és kapui megemésztettek tûzben?!"));
husuperobject.biblemap.put("b16_2_4", new husuperobject(16,2,4,"És monda nékem a király: Mi az, a mit kívánsz? És könyörgék a menny Istenéhez."));
husuperobject.biblemap.put("b16_2_5", new husuperobject(16,2,5,"És mondék a királynak: Ha tetszik a királynak és ha kedves elõtted a te szolgád, [azt kérem], hogy bocsáss el engem Júdába, atyáim sírjainak városába, hogy megépítsem azt!"));
husuperobject.biblemap.put("b16_2_6", new husuperobject(16,2,6,"És monda nékem a király (felesége pedig mellette ül vala): Meddig lészen utazásod és mikorra jösz vissza? És tetszék a királynak engem elbocsátani, miután én tudattam vele az idõt."));
husuperobject.biblemap.put("b16_2_7", new husuperobject(16,2,7,"És mondék a királynak: Ha tetszik a királynak, adasson nékem leveleket a folyóvizen túl lakó tiszttartókhoz, hogy hagyjanak engem utazni, míg Júdába érek;"));
husuperobject.biblemap.put("b16_2_8", new husuperobject(16,2,8,"És [adasson] egy levelet Ászáfhoz, a király erdeje õréhez, hogy adjon nékem fákat gerendákul a templom várának kapuihoz, és a város kõfalához, és a házhoz, melybe költözni fogok. És megadá nékem a király, az én Istenemnek rajtam nyugvó jó kegyelme szerint."));
husuperobject.biblemap.put("b16_2_9", new husuperobject(16,2,9,"És megérkezém a folyóvizen túl való tiszttartókhoz és átadám nékik a király leveleit. Bocsátott vala pedig velem a király fõembereket a seregbõl és lovagokat."));
husuperobject.biblemap.put("b16_2_10", new husuperobject(16,2,10,"Mikor pedig a Horonból való Szanballat és az Ammonita Tóbiás, a szolga, meghallották ezt, nagy bosszúságot okozott nékik, hogy jött valaki, a ki Izráel fiainak javokat keresi."));
husuperobject.biblemap.put("b16_2_11", new husuperobject(16,2,11,"Azután elmenék Jeruzsálembe, és ott pihenék három napig."));
husuperobject.biblemap.put("b16_2_12", new husuperobject(16,2,12,"És fölkelék éjszaka, én és velem néhány férfi, mert nem jelentém meg senkinek, hogy mire indítá az én Istenem az én szívemet, hogy azt Jeruzsálemért megcselekedjem, és barom sem vala velem, csak az, melyen ülök vala,"));
husuperobject.biblemap.put("b16_2_13", new husuperobject(16,2,13,"És kimenék a völgynek kapuján éjjel, és pedig a sárkányok forrása felé, majd a szemét-kapuhoz, és vizsgálgatám Jeruzsálem kõfalait, melyek elrontattak vala, és kapuit, melyek tûz által megemésztetének."));
husuperobject.biblemap.put("b16_2_14", new husuperobject(16,2,14,"Azután átmenék a forrás kapujához és a király tavához, holott nem vala hely a baromnak, hogy velem átmenjen."));
husuperobject.biblemap.put("b16_2_15", new husuperobject(16,2,15,"Azért [gyalog] menék fel a völgyben éjjel és vizsgálgatám a kõfalat, azután megfordultam és bementem a völgy kapuján, és hazatértem."));
husuperobject.biblemap.put("b16_2_16", new husuperobject(16,2,16,"A fõemberek pedig nem tudták vala, hova mentem, és hogy mit akarok cselekedni, és sem a zsidóknak, sem a papoknak, sem az elõljáróknak, sem a fõembereknek, sem a többi munkásoknak ez ideig nem jelentettem meg."));
husuperobject.biblemap.put("b16_2_17", new husuperobject(16,2,17,"Ekkor mondék nékik: Ti látjátok a nyomorúságot, a melyben mi vagyunk, hogy Jeruzsálem pusztán hever és kapui tûzben égtek meg; jertek, építsük meg Jeruzsálem kõfalát, és ne legyünk többé gyalázatul!"));
husuperobject.biblemap.put("b16_2_18", new husuperobject(16,2,18,"És megjelentém nékik az én Istenemnek rajtam nyugvó jó kegyelmét, és a király beszédit is, a melyeket nékem szólt, és mondának: Keljünk fel és építsük meg! És megerõsíték kezeiket a jóra."));
husuperobject.biblemap.put("b16_2_19", new husuperobject(16,2,19,"Mikor meghallák ezt a Horonból való Szanballat és az Ammonita Tóbiás, a szolga, és az arab Gesem, gúnyoltak és lenéztek minket, mondván: Micsoda ez, a mit míveltek? Talán bizony a király ellen akartok pártot ütni?"));
husuperobject.biblemap.put("b16_2_20", new husuperobject(16,2,20,"Kiknek felelék, és mondék: A mennynek Istene, õ ad jó szerencsét nékünk, és mi mint az õ szolgái kelünk föl és építünk, néktek pedig részetek és jogotok és emlékezetetek nincsen Jeruzsálemben!"));
husuperobject.biblemap.put("b16_3_1", new husuperobject(16,3,1,"És fölkele Eliásib, a fõpap és atyjafiai, a papok és építék a juhok kapuját; õk szentelék meg azt és állíták fel annak ajtait; [építék] pedig a kõfalat a Meáh toronyig, a melyet megszentelének, s azután Hanánel tornyáig;"));
husuperobject.biblemap.put("b16_3_2", new husuperobject(16,3,2,"És õ mellette építének a Jerikóbeliek, ezek mellett pedig épített Zakkur az Imri fia;"));
husuperobject.biblemap.put("b16_3_3", new husuperobject(16,3,3,"A halaknak kapuját pedig építék a Hasszenáa fiai, õk gerendázák be azt és állíták fel annak ajtait, kapcsait és závárait;"));
husuperobject.biblemap.put("b16_3_4", new husuperobject(16,3,4,"Mellettök javítgatá a kõfalat Merémóth, Uriásnak, a Hakkós fiának fia, mellette pedig javítgatott Mesullám, Berekiásnak, a Mesézabéel fiának a fia, és õ mellette javítgatott Sádók, Baána fia."));
husuperobject.biblemap.put("b16_3_5", new husuperobject(16,3,5,"Ezek mellett pedig javítgatának a Tékoabeliek, a kiknek elõkelõi azonban nem hajták nyakukat az õ Urok munkájának [jármába.]"));
husuperobject.biblemap.put("b16_3_6", new husuperobject(16,3,6,"Az ó-[város] kapuját pedig javítgaták Jójada, a Pászéah fia és Mesullám, a Beszódia fia; õk gerendázák be azt és állíták fel annak ajtait, kapcsait és závárait;"));
husuperobject.biblemap.put("b16_3_7", new husuperobject(16,3,7,"És mellettök javítgatott a Gibeonból való Melátia és a Meronothból való Jádón, Gibeonnak és Mispának lakosai, a folyóvizen túl való helytartónak hivatala helyéig;"));
husuperobject.biblemap.put("b16_3_8", new husuperobject(16,3,8,"Mellettök javítgatott Uzziel, Harhajának fia az ötvösök[kel,] és õ mellette javítgatott Hanánia, a kenet-készítõk egyike, és megerõsíték Jeruzsálemet mind a széles kõfalig;"));
husuperobject.biblemap.put("b16_3_9", new husuperobject(16,3,9,"Mellettök javítgatott Refája, Húr fia, a ki a Jeruzsálemhez tartozó tartomány felének fejedelme vala;"));
husuperobject.biblemap.put("b16_3_10", new husuperobject(16,3,10,"Mellette javítgatott Jedája, Harumáf fia, és pedig a maga háza ellenébe, és mellette javítgatott Hattus, Hasabneja fia."));
husuperobject.biblemap.put("b16_3_11", new husuperobject(16,3,11,"A kõfal másik darabját javítgatá Malkija, Hárim fia és Hassub, a Pahath-Moáb fia, és a kemenczéknek tornyát."));
husuperobject.biblemap.put("b16_3_12", new husuperobject(16,3,12,"És mellettök javítgatott Sallum, Hallóhés fia, a ki fejedelme vala a Jeruzsálemhez tartozó tartomány [másik] felének, õ és az õ leányai."));
husuperobject.biblemap.put("b16_3_13", new husuperobject(16,3,13,"A völgy kapuját javítgaták Hánun és Zánoah lakói, õk építék meg azt és állíták fel annak ajtait, kapcsait és závárait; és a kõfalból ezer singet a szemét-kapuig."));
husuperobject.biblemap.put("b16_3_14", new husuperobject(16,3,14,"A szemét-kaput pedig javítgatá Malkija, Rékáb fia, Beth-Hakkerem tartományának fejedelme, õ építé meg azt és állítá fel ajtait, kapcsait és závárait."));
husuperobject.biblemap.put("b16_3_15", new husuperobject(16,3,15,"És a forrásnak kapuját javítgatá Sallum, a Kól-Hóze fia, Mispa tartományának fejedelme, õ építé meg és héjazá be azt és állítá fel ajtait, kapcsait és závárait; és a Selah tó kõfalát a király kertje felé, mind a garádicsokig, melyeken a Dávid városából alájõnek."));
husuperobject.biblemap.put("b16_3_16", new husuperobject(16,3,16,"Õ utána javítgata Nehémiás, Azbuk fia, Béth-Sur tartománya felének fejedelme, a Dávid sírjai ellenébe való helyig, és az [újonnan] készült tóig, és a vitézek házáig."));
husuperobject.biblemap.put("b16_3_17", new husuperobject(16,3,17,"Õ utána javítgatának a Léviták: Rehum, Báni fia, a ki mellett javítgata Hasábia, Kéila tartománya felének fejedelme, tartománya [lakosai]val;"));
husuperobject.biblemap.put("b16_3_18", new husuperobject(16,3,18,"Õ utána javítgatának atyjokfiai: Bavvai, a Hénadád fia, Kéila tartománya [másik] felének fejedelme;"));
husuperobject.biblemap.put("b16_3_19", new husuperobject(16,3,19,"Javítgatá pedig õ mellette Ézer, Jésuának fia, Mispa fejedelme, a kõfal egy másik darabját, a szegleten levõ fegyveresház felmenetelének ellenébe;"));
husuperobject.biblemap.put("b16_3_20", new husuperobject(16,3,20,"Õ utána Bárukh, Zakkai fia javítgatá buzgósággal a kõfal egy másik darabját, a szeglettõl fogva Eliásib fõpap házának ajtajáig:"));
husuperobject.biblemap.put("b16_3_21", new husuperobject(16,3,21,"Õ utána javítgata Merémóth Uriásnak fia, a ki Hakkós fia vala, egy másik darabot, Eliásib házának ajtajától Eliásib házának végéig;"));
husuperobject.biblemap.put("b16_3_22", new husuperobject(16,3,22,"Õ utána javítgatának a papok, a környék férfiai;"));
husuperobject.biblemap.put("b16_3_23", new husuperobject(16,3,23,"Ezek után javítgata Benjámin és Hassub, az õ házok ellenébe, utánok pedig javítgata Azariás, Maaséja fia - a ki Ananiás fia vala - az õ háza mellett;"));
husuperobject.biblemap.put("b16_3_24", new husuperobject(16,3,24,"Õ utánok javítgata Binnui, a Hénadád fia egy másik darabot, Azáriás házától mind a zugig és szegletig;"));
husuperobject.biblemap.put("b16_3_25", new husuperobject(16,3,25,"[Továbbá] Palál, az Uzai fia, a szegletnek és a felsõ toronynak ellenébe, mely a király házából a tömlöcz udvaránál emelkedik ki; utána pedig Pedája, a Parós fia;"));
husuperobject.biblemap.put("b16_3_26", new husuperobject(16,3,26,"(A Léviták szolgái pedig laknak vala az Ófelben, a vizek kapujának ellenéig napkelet felé és a kiemelkedõ torony ellenéig;)"));
husuperobject.biblemap.put("b16_3_27", new husuperobject(16,3,27,"Õ utána javítgatának a Tékoabeliek egy másik darabot a kiemelkedõ nagy toronynak ellenétõl fogva az Ófel kõfaláig;"));
husuperobject.biblemap.put("b16_3_28", new husuperobject(16,3,28,"A lovak kapuján felül javítgatának a papok, kiki az õ házának ellenébe;"));
husuperobject.biblemap.put("b16_3_29", new husuperobject(16,3,29,"Utánok javítgata Sádók, Immér fia az õ háza ellenébe; és õ utána javítgata Semája, Sekaniás fia, a napkeleti kapu õrizõje;"));
husuperobject.biblemap.put("b16_3_30", new husuperobject(16,3,30,"Õ utána javítgata Hananiás, Selemiás fia és Hánun, Sáláfnak hatodik fia egy másik darabot; utánok javítgata Mesullám, Berekiás fia, az õ szobája ellenébe;"));
husuperobject.biblemap.put("b16_3_31", new husuperobject(16,3,31,"Utána javítgata Malkija, az ötvösök egyike, a Léviták szolgáinak és a kereskedõknek házáig, a törvénytevõ ház kapujának ellenébe, a szegletnek hágójáig;"));
husuperobject.biblemap.put("b16_3_32", new husuperobject(16,3,32,"A szeglet hágója és a juhok kapuja között pedig javítgatának az ötvösök és a kereskedõk."));
husuperobject.biblemap.put("b16_4_1", new husuperobject(16,4,1,"Lõn pedig, mikor meghallotta Szanballat, hogy mi építjük a kõfalat, haragra gerjede és felette igen bosszankodék, és gúnyolá a zsidókat;"));
husuperobject.biblemap.put("b16_4_2", new husuperobject(16,4,2,"És szóla az õ atyjafiai és a samáriai sereg elõtt, és ezt mondá: Mit mûvelnek e nyomorult zsidók? Vajjon megengedik-é ezt nékik? Talán áldozni fognak? Hát bevégezik ma? Avagy megelevenítik a köveket a porhalmazból, holott azok elégtek?!"));
husuperobject.biblemap.put("b16_4_3", new husuperobject(16,4,3,"Az Ammonita Tóbiás pedig mellette [állván], mondá: Bármit építsenek, ha egy róka lép fel reá, összezúzza köveiknek falát."));
husuperobject.biblemap.put("b16_4_4", new husuperobject(16,4,4,"Halld meg, oh mi istenünk! hogy csúffá lettünk, fordítsad gyalázásukat az õ fejökre, és add õket prédára a rabságnak földében;"));
husuperobject.biblemap.put("b16_4_5", new husuperobject(16,4,5,"Ne fedezd el az õ hamisságokat és az õ bûnök a te orczád elõl el ne töröltessék, mert [téged] bosszantának az építõk elõtt!"));
husuperobject.biblemap.put("b16_4_6", new husuperobject(16,4,6,"És építõk a falat annyira, hogy elkészült az egész fal félmagasságban, mert a nép nagy kedvvel dolgozott."));
husuperobject.biblemap.put("b16_4_7", new husuperobject(16,4,7,"Mikor pedig meghallotta Szanballat és Tóbiás, továbbá az Arábiabeliek, az Ammoniták és az Asdódeusok, hogy javítgattatnak Jeruzsálem kõfalai, és hogy a törések betömése megkezdõdött, felette nagy haragra gerjedének;"));
husuperobject.biblemap.put("b16_4_8", new husuperobject(16,4,8,"És összeesküvének mindnyájan egyenlõ akarattal, hogy eljõnek Jeruzsálemet megostromolni és [népét] megrémíteni."));
husuperobject.biblemap.put("b16_4_9", new husuperobject(16,4,9,"De mi imádkozánk a mi Istenünkhöz, és állítánk ellenök õrséget nappal és éjjel, mivelhogy féltünk tõlök."));
husuperobject.biblemap.put("b16_4_10", new husuperobject(16,4,10,"És mondák a zsidók: Fogytán van ereje a tereh-hordónak, a rom pedig sok, és mi képtelenek vagyunk építeni a kõfalat."));
husuperobject.biblemap.put("b16_4_11", new husuperobject(16,4,11,"A mi ellenségeink pedig ezt mondották: Ingyen se tudják meg, se ne lássák, míg közikbe bemegyünk és õket leöljük, és megszüntetjük a munkát."));
husuperobject.biblemap.put("b16_4_12", new husuperobject(16,4,12,"És lõn, hogy eljöttek hozzánk mindenfelõl a zsidók, a kik õ mellettök laknak vala és nékünk tízszer is mondották: Térjetek haza!"));
husuperobject.biblemap.put("b16_4_13", new husuperobject(16,4,13,"Azért állítám a hely alsó és nyilt részeire a kõfal mögé, odaállítám a népet nemzetségek szerint, fegyvereikkel, dárdáikkal és kézíveikkel."));
husuperobject.biblemap.put("b16_4_14", new husuperobject(16,4,14,"És körültekintvén, fölkeltem és így szóltam az elõljárókhoz, a fõemberekhez és a többi néphez: Ne féljetek tõlök! A nagy és rettenetes Úrra emlékezzetek, és harczoljatok testvéreitekért, fiaitokért, leányaitokért, feleségeitekért és házaitokért!"));
husuperobject.biblemap.put("b16_4_15", new husuperobject(16,4,15,"És lõn, hogy meghallották a mi ellenségeink, hogy megtudtuk [az õ szándékukat], és hogy Isten semmivé tette az õ tanácsokat: megtérénk mi mindnyájan a kõfalhoz, kiki az õ munkájához;"));
husuperobject.biblemap.put("b16_4_16", new husuperobject(16,4,16,"De azon naptól fogva legényeim egyik része munkálkodik vala, a másik része pedig tart vala dárdákat, paizsokat, kézíveket és pánczélokat, és a fejedelmek ott állának az egész Júda háznépe mögött."));
husuperobject.biblemap.put("b16_4_17", new husuperobject(16,4,17,"A kõfalon munkálkodók közül a tehernek hordói egyik kezökkel, a mely a munkát végezé, rakodának, másik kezök pedig a fegyvert tartja vala,"));
husuperobject.biblemap.put("b16_4_18", new husuperobject(16,4,18,"A kik pedig építének, azoknak fegyverök derekokra vala felkötve és így építének; a trombitás pedig mellettem állt."));
husuperobject.biblemap.put("b16_4_19", new husuperobject(16,4,19,"És így szóltam az elõljárókhoz, a fõemberekhez és a többi néphez: A munka felette sok és messzeterjedõ és mi elszéledvén a kõfalon, egymástól messze esünk;"));
husuperobject.biblemap.put("b16_4_20", new husuperobject(16,4,20,"Azért oda gyûljetek hozzánk, hol a trombita szavát hallándjátok, a mi Istenünk hadakozik érettünk!"));
husuperobject.biblemap.put("b16_4_21", new husuperobject(16,4,21,"Ekképen munkálkodunk vala; és [legényeimnek] fele dárdákat tart vala hajnalhasadtától fogva mind a csillagoknak feltámadásáig."));
husuperobject.biblemap.put("b16_4_22", new husuperobject(16,4,22,"Ugyanekkor megparancsolám a népnek, hogy minden ember legényével Jeruzsálemben háljon, hogy éjszaka õrködjenek felettünk és nappal dolgozzanak."));
husuperobject.biblemap.put("b16_4_23", new husuperobject(16,4,23,"És sem én, sem az én atyámfiai, sem legényeim, sem az õrizõk, a kik én utánam valának, nem vetjük vala le ruháinkat; kiki csak mosódáskor teszi vala le fegyverét."));
husuperobject.biblemap.put("b16_5_1", new husuperobject(16,5,1,"Lõn pedig nagy kiáltása a népnek és feleségeiknek az õ atyjokfiai, a zsidók ellen."));
husuperobject.biblemap.put("b16_5_2", new husuperobject(16,5,2,"Valának, a kik ezt mondják vala: Fiainkkal és leányainkkal együtt sokadmagunkkal vagyunk, nékünk gabona kell, hogy együnk és éljünk."));
husuperobject.biblemap.put("b16_5_3", new husuperobject(16,5,3,"És valának, a kik ezt mondják vala: Mind mezeinket, mind szõlõinket, mind házainkat zálogba kell adogatnunk, nékünk gabona kell, mert éhezünk."));
husuperobject.biblemap.put("b16_5_4", new husuperobject(16,5,4,"Viszontag valának, a kik ezt mondják vala: Kölcsön vettünk pénzt a király adójáért a mi mezeinkre és szõlõinkre;"));
husuperobject.biblemap.put("b16_5_5", new husuperobject(16,5,5,"És ímé, bár a mi testünk épen olyan, mint a mi atyánkfiainak testök, s a mi fiaink olyanok, mint az õ fiaik, mi nékünk mégis rabság alá kell adnunk fiainkat és leányainkat, sõt vannak már rabszolga leányaink is, és nincs erõnk arra, [hogy õket megválthatnók,] hisz mezeink és szõlõink másokéi már!"));
husuperobject.biblemap.put("b16_5_6", new husuperobject(16,5,6,"Felette nagy haragra gerjedtem azért, mikor kiáltásukat s e dolgokat hallottam;"));
husuperobject.biblemap.put("b16_5_7", new husuperobject(16,5,7,"És magamba [szállva,] gondolkodtam errõl, és megfeddém az elõljárókat és fõembereket, ezt mondván nékik: Ti a ti atyátokfiaival szemben uzsoráskodtok! És szerzék õ ellenök nagy gyûlést;"));
husuperobject.biblemap.put("b16_5_8", new husuperobject(16,5,8,"És mondám nékik: Mi megváltottuk a mi atyánkfiait, a zsidókat, a kik a pogányoknak eladattak vala, a mi tehetségünk szerint; és ti is meg akarjátok venni a ti atyátokfiait, s õk nékünk adják el magokat?! És hallgatának és nem tudának felelni semmit."));
husuperobject.biblemap.put("b16_5_9", new husuperobject(16,5,9,"És mondék: Nem jó dolog ez, a mit ti cselekesztek. Hát nem fogtok a mi Istenünk félelmében járni, hogy [valahára] ne gyalázzanak [már] minket a pogányok, a mi ellenségeink?"));
husuperobject.biblemap.put("b16_5_10", new husuperobject(16,5,10,"Hiszen én, atyámfiai és legényeim is pénzt és gabonát kölcsönöztünk nékik; engedjük el, kérlek, e tartozást!"));
husuperobject.biblemap.put("b16_5_11", new husuperobject(16,5,11,"Adjátok vissza, kérlek, nékik még ma az õ mezeiket, szõlõiket, olajkerteiket és házaikat; ennekfelette, a kölcsönadott pénznek, gabonának, bornak és olajnak századát [engedjétek el.]"));
husuperobject.biblemap.put("b16_5_12", new husuperobject(16,5,12,"És felelének: Visszaadjuk és tõlök nem veszünk semmit; úgy cselekszünk, a mint te mondod. Ekkor egybehívám a papokat és megeskettetém õket, hogy e beszéd szerint fognak cselekedni."));
husuperobject.biblemap.put("b16_5_13", new husuperobject(16,5,13,"Ruhámat is megrázám és mondék: Épen így rázzon ki az Isten minden embert az õ házából és vagyonából, és épen így legyen kirázatott és üres, valaki meg nem teljesíti e beszédet. És monda az egész gyülekezet: Ámen. És dícsérék az Urat, és e beszéd szerint cselekedett a nép."));
husuperobject.biblemap.put("b16_5_14", new husuperobject(16,5,14,"Sõt azon naptól fogva, melyen Júdának földére helytartójukul rendeltettem, Artaxerxes királynak huszadik esztendejétõl fogva harminczkettedik esztendejéig, azaz tizenkét esztendeig, sem én, sem az én atyámfiai a helytartónak járó kenyeret nem evénk."));
husuperobject.biblemap.put("b16_5_15", new husuperobject(16,5,15,"Holott az elõbbi helytartók, a kik én elõttem valának, terhelék a népet és vevének tõlök kenyérért és borért negyven ezüst sikluson felül; sõt még legényeik is zsarnokoskodának a népen. De én nem cselekedém így az Isten félelme miatt."));
husuperobject.biblemap.put("b16_5_16", new husuperobject(16,5,16,"Sõt még e kõfalon is dolgoztam; mezõt sem szereztünk; s minden én legényeim egybegyûltenek ott a munkára."));
husuperobject.biblemap.put("b16_5_17", new husuperobject(16,5,17,"Annakfelette a zsidók, továbbá a másfélszáz fõember és a kik jõnek vala mi hozzánk a körültünk lakó pogányok közül, az én asztalomnál [esznek] [vala.]"));
husuperobject.biblemap.put("b16_5_18", new husuperobject(16,5,18,"A mit minden napra készítenek vala: egy ökröt, hat kövér juhot, és madarakat is készítének nékem, minden tíz napra vala mindenféle bor bõségesen; és mindemellett sem kivántam be a helytartó kenyerét, mert nehéz vala a szolgálat ezen a népen."));
husuperobject.biblemap.put("b16_5_19", new husuperobject(16,5,19,"Emlékezzél meg rólam, én Istenem, javamra, mindarról, a mit én e néppel cselekedtem!"));
husuperobject.biblemap.put("b16_6_1", new husuperobject(16,6,1,"És lõn, hogy mikor meghallá Szanballat, Tóbiás, az Arábiabeli Gesem és a mi többi ellenségeink, hogy megépítettem a kõfalat, s hogy nem maradt azon semmi romlás, jóllehet még az ideig ajtókat nem állíttattam a kapukra:"));
husuperobject.biblemap.put("b16_6_2", new husuperobject(16,6,2,"Külde Szanballat és Gesem hozzám ilyen izenettel: Jer és találkozzunk a faluk [egyikében,] az Onó-völgyében; holott õk gonoszt gondoltak ellenem."));
husuperobject.biblemap.put("b16_6_3", new husuperobject(16,6,3,"Küldék azért követeket hozzájok ilyen izenettel: Nagy dolgot cselekszem én, azért nem mehetek alá; megszünnék e munka, ha attól eltávozván, hozzátok mennék."));
husuperobject.biblemap.put("b16_6_4", new husuperobject(16,6,4,"És küldének hozzám ilyen módon négy ízben, és én ilyen módon felelék nékik."));
husuperobject.biblemap.put("b16_6_5", new husuperobject(16,6,5,"Küldé továbbá hozzám Szanballat ilyen módon ötödször az õ legényét, a kinek kezében egy felnyitott levél vala,"));
husuperobject.biblemap.put("b16_6_6", new husuperobject(16,6,6,"Melyben ez vala írva: A szomszéd népek közt ez a hír és Gasmu is mondja, hogy te és a zsidók pártot akartok ütni, annakokáért építed te a kõfalat; és hogy te leszel az õ királyok, e beszédek szerint."));
husuperobject.biblemap.put("b16_6_7", new husuperobject(16,6,7,"Sõt még prófétákat is rendelél, a kik hirdetnék te felõled Jeruzsálemben, ezt mondván: Király van Júdában! És most e dolgoknak híre a királyhoz is elérkezik, annakokáért jer és tanácskozzunk együtt!"));
husuperobject.biblemap.put("b16_6_8", new husuperobject(16,6,8,"Én pedig küldék õ hozzá ilyen izenettel: Nem történt semmi olyan, a minõt te mondasz, hanem csak magadtól gondoltad mindazt a te szívedben."));
husuperobject.biblemap.put("b16_6_9", new husuperobject(16,6,9,"Mert mindezek el akarnak vala minket rettenteni, ezt mondván: Leveszik kezöket a munkáról és az félben marad! Azért hát, [oh] [Uram!] erõsítsd meg az én kezeimet."));
husuperobject.biblemap.put("b16_6_10", new husuperobject(16,6,10,"És én elmentem Semájának, a Delája fiának házába, a ki Mehétabeél fia vala, és õt bezárkózva [találtam,] és monda: Menjünk az Isten házába, a templom belsejébe és zárjuk be a templomnak ajtait, mert eljõnek, hogy megöljenek téged, és pedig éjjel jõnek el, hogy megöljenek."));
husuperobject.biblemap.put("b16_6_11", new husuperobject(16,6,11,"Én pedig mondék: Avagy ily férfiúnak, mint én vagyok, [illik]-é futni? Hát ilyen lévén mint én, beléphet-é valaki a templomba, élvén? Nem megyek!"));
husuperobject.biblemap.put("b16_6_12", new husuperobject(16,6,12,"És megismerém, hogy nem az Isten küldötte õt, hanem azt a prófécziát azért mondá nékem, mert Tóbiás és Szanballat felbérelték õt."));
husuperobject.biblemap.put("b16_6_13", new husuperobject(16,6,13,"Azért vala pedig felbérelve, hogy én megrettenjek és akképen cselekedvén, vétkezzem, hogy így rossz híremet költhessék és rágalmazhassanak."));
husuperobject.biblemap.put("b16_6_14", new husuperobject(16,6,14,"Emlékezzél meg én Istenem Tóbiásról és Szanballatról ezen cselekedeteik szerint, és a jövendõmondó Noádja asszonyról és a többi jövendõmondókról is, a kik rémítgetének engem."));
husuperobject.biblemap.put("b16_6_15", new husuperobject(16,6,15,"Elvégezteték pedig a kõfal Elul hónap huszonötödik napján, ötvenkét nap alatt."));
husuperobject.biblemap.put("b16_6_16", new husuperobject(16,6,16,"És lõn, hogy midõn meghallák minden mi ellenségeink, megfélemlének minden pogányok, a kik körültünk valának, és igen összeestek a saját szemeikben, és megismerék, hogy a mi Istenünktõl vitetett végbe e munka."));
husuperobject.biblemap.put("b16_6_17", new husuperobject(16,6,17,"E napokban is sok levelet küldének némely zsidó elõljárók Tóbiásnak, és viszont Tóbiástól sok jöve hozzájok."));
husuperobject.biblemap.put("b16_6_18", new husuperobject(16,6,18,"Mert sokan Júdában õ hozzá esküdtek, mivelhogy õ veje vala Sekániának, az Arah fiának, és Jóhanán, az õ fia, Mesullámnak, a Berékia fiának leányát vette volt el."));
husuperobject.biblemap.put("b16_6_19", new husuperobject(16,6,19,"Sõt még jó szándékait is emlegetik vala elõttem, és az én beszédeimet megvivék néki. Leveleket pedig Tóbiás [folyton] küldött, hogy engem elrettentene."));
husuperobject.biblemap.put("b16_7_1", new husuperobject(16,7,1,"És lõn, hogy midõn megépítteték a kõfal, felállítám az ajtókat és kirendeltetének a kapunállók, az énekesek és a Léviták [õrizetre;]"));
husuperobject.biblemap.put("b16_7_2", new husuperobject(16,7,2,"És [hadnagyokká] tevém Jeruzsálem fölött Hanánit, testvéremet és Hanániást, a vár fejedelmét, mivel hogy õ hûségesebb és istenfélõbb vala sokaknál."));
husuperobject.biblemap.put("b16_7_3", new husuperobject(16,7,3,"És mondék nékik: Meg ne nyittassanak Jeruzsálem kapui mindaddig, míg a nap melegen nem süt, és míg [az õrök] ott állanak, addig tegyék be az ajtókat és zárjátok be azokat; azután állítsatok õrizõket Jeruzsálem lakosai közül, némelyeket az õ vigyázó helyökre, s másokat az õ házok ellenébe."));
husuperobject.biblemap.put("b16_7_4", new husuperobject(16,7,4,"A város pedig felette igen széles vala és nagy, s a nép kevés lévén benne, házak nem épültek."));
husuperobject.biblemap.put("b16_7_5", new husuperobject(16,7,5,"Felindítá azért az én Istenem szívemet, hogy egybegyûjtsem az elõljárókat, a fõembereket és a népet, hogy felírattassanak; és megtalálám azok nemzetségének könyvét, a kik elõször jöttek vala fel Babilóniából, melyben ily írást találék:"));
husuperobject.biblemap.put("b16_7_6", new husuperobject(16,7,6,"Ezek a tartománynak fiai, a kik feljöttek vala a rabság foglyai közül, a kiket fogva vitetett Nabukodonozor, Babilónia királya, s most visszajövének Jeruzsálembe és Júdába, kiki az õ városába."));
husuperobject.biblemap.put("b16_7_7", new husuperobject(16,7,7,"Kik jövének Zorobábellel: Jésua, Nehémiás, Azariás, Raámia, Nahamáni, Mordokhai, Bilsán, Miszpereth, Bigvai, Nehum, Baána. Izráel népe férfiainak számok [ez:]"));
husuperobject.biblemap.put("b16_7_8", new husuperobject(16,7,8,"Parós fiai: kétezerszázhetvenkettõ;"));
husuperobject.biblemap.put("b16_7_9", new husuperobject(16,7,9,"Sefátja fiai: háromszázhetvenkettõ;"));
husuperobject.biblemap.put("b16_7_10", new husuperobject(16,7,10,"Arah fiai: hatszázötvenkettõ;"));
husuperobject.biblemap.put("b16_7_11", new husuperobject(16,7,11,"Pahath-Moáb fiai, Jésua és Joáb fiaitól: kétezernyolczszáztizennyolcz;"));
husuperobject.biblemap.put("b16_7_12", new husuperobject(16,7,12,"Elám fiai: ezerkétszázötvennégy;"));
husuperobject.biblemap.put("b16_7_13", new husuperobject(16,7,13,"Zattu fiai: nyolczszáznegyvenöt;"));
husuperobject.biblemap.put("b16_7_14", new husuperobject(16,7,14,"Zakkai fiai: hétszázhatvan;"));
husuperobject.biblemap.put("b16_7_15", new husuperobject(16,7,15,"Binnui fiai: hatszáznegyvennyolcz;"));
husuperobject.biblemap.put("b16_7_16", new husuperobject(16,7,16,"Bébai fiai: hatszázhuszonnyolcz;"));
husuperobject.biblemap.put("b16_7_17", new husuperobject(16,7,17,"Azgád fiai: kétezerháromszázhuszonkettõ;"));
husuperobject.biblemap.put("b16_7_18", new husuperobject(16,7,18,"Adónikám fiai: hatszázhatvanhét;"));
husuperobject.biblemap.put("b16_7_19", new husuperobject(16,7,19,"Bigvai fiai: kétezerhatvanhét;"));
husuperobject.biblemap.put("b16_7_20", new husuperobject(16,7,20,"Adin fiai: hatszázötvenöt;"));
husuperobject.biblemap.put("b16_7_21", new husuperobject(16,7,21,"Áter fiai, Ezékiástól: kilenczvennyolcz;"));
husuperobject.biblemap.put("b16_7_22", new husuperobject(16,7,22,"Hásum fiai: háromszázhuszonnyolcz;"));
husuperobject.biblemap.put("b16_7_23", new husuperobject(16,7,23,"Bésai fiai: háromszázhuszonnégy;"));
husuperobject.biblemap.put("b16_7_24", new husuperobject(16,7,24,"Hárif fiai: száztizenkettõ;"));
husuperobject.biblemap.put("b16_7_25", new husuperobject(16,7,25,"Gibeon fiai: kilenczvenöt;"));
husuperobject.biblemap.put("b16_7_26", new husuperobject(16,7,26,"Bethlehem és Netófa férfiai: száznyolczvannyolcz;"));
husuperobject.biblemap.put("b16_7_27", new husuperobject(16,7,27,"Anathóth férfiai: százhuszonnyolcz;"));
husuperobject.biblemap.put("b16_7_28", new husuperobject(16,7,28,"Beth-Azmáveth férfiai: negyvenkettõ;"));
husuperobject.biblemap.put("b16_7_29", new husuperobject(16,7,29,"Kirjáth-Jeárim, Kefira és Beéróth férfiai: hétszáznegyvenhárom;"));
husuperobject.biblemap.put("b16_7_30", new husuperobject(16,7,30,"Ráma és Géba férfiai: hatszázhuszonegy;"));
husuperobject.biblemap.put("b16_7_31", new husuperobject(16,7,31,"Mikmás férfiai: százhuszonkettõ;"));
husuperobject.biblemap.put("b16_7_32", new husuperobject(16,7,32,"Béthel és Ai férfiai: százhuszonhárom;"));
husuperobject.biblemap.put("b16_7_33", new husuperobject(16,7,33,"A másik Nébó férfiai: ötvenkettõ;"));
husuperobject.biblemap.put("b16_7_34", new husuperobject(16,7,34,"A másik Elám fiai: ezerkétszázötvennégy;"));
husuperobject.biblemap.put("b16_7_35", new husuperobject(16,7,35,"Hárim fiai: háromszázhúsz;"));
husuperobject.biblemap.put("b16_7_36", new husuperobject(16,7,36,"Jerikó fiai: háromszáznegyvenöt;"));
husuperobject.biblemap.put("b16_7_37", new husuperobject(16,7,37,"Lód, Hádid és Ónó fiai: hétszázhuszonegy;"));
husuperobject.biblemap.put("b16_7_38", new husuperobject(16,7,38,"Szenáa fiai: háromezerkilenczszázharmincz;"));
husuperobject.biblemap.put("b16_7_39", new husuperobject(16,7,39,"A papok: Jedája fiai Jésua családjából: kilenczszázhetvenhárom;"));
husuperobject.biblemap.put("b16_7_40", new husuperobject(16,7,40,"Immér fiai: ezerötvenkettõ;"));
husuperobject.biblemap.put("b16_7_41", new husuperobject(16,7,41,"Pashur fiai: ezerkétszáznegyvenhét;"));
husuperobject.biblemap.put("b16_7_42", new husuperobject(16,7,42,"Hárim fiai: ezertizenhét;"));
husuperobject.biblemap.put("b16_7_43", new husuperobject(16,7,43,"A Léviták: Jésua [és] Kadmiel fiai, Hódávia fiaitól: hetvennégy;"));
husuperobject.biblemap.put("b16_7_44", new husuperobject(16,7,44,"Az énekesek: Asáf fiai: száznegyvennyolcz;"));
husuperobject.biblemap.put("b16_7_45", new husuperobject(16,7,45,"A kapunállók: Sallum fiai, Áter fiai, Talmón fiai, Akkub fiai, Hatita fiai, Sóbai fiai: százharmincznyolcz;"));
husuperobject.biblemap.put("b16_7_46", new husuperobject(16,7,46,"A Léviták szolgái: Siha fiai, Hasufa fiai, Tabbaóth fiai,"));
husuperobject.biblemap.put("b16_7_47", new husuperobject(16,7,47,"Kérósz fiai, Szia fiai, Pádón fiai,"));
husuperobject.biblemap.put("b16_7_48", new husuperobject(16,7,48,"Lebána fiai, Hagába fiai, Salmai fiai,"));
husuperobject.biblemap.put("b16_7_49", new husuperobject(16,7,49,"Hanán fiai, Giddél fiai, Gahar fiai,"));
husuperobject.biblemap.put("b16_7_50", new husuperobject(16,7,50,"Reája fiai, Resin fiai, Nekóda fiai,"));
husuperobject.biblemap.put("b16_7_51", new husuperobject(16,7,51,"Gazzám fiai, Uzza fiai, Pászéah fiai,"));
husuperobject.biblemap.put("b16_7_52", new husuperobject(16,7,52,"Bészai fiai, Meunim fiai, Nefiszim fiai,"));
husuperobject.biblemap.put("b16_7_53", new husuperobject(16,7,53,"Bakbuk fiai, Hakufa fiai, Harhur fiai,"));
husuperobject.biblemap.put("b16_7_54", new husuperobject(16,7,54,"Basluth fiai, Mehida fiai, Harsa fiai,"));
husuperobject.biblemap.put("b16_7_55", new husuperobject(16,7,55,"Barkósz fiai, Sziszera fiai, Temah fiai,"));
husuperobject.biblemap.put("b16_7_56", new husuperobject(16,7,56,"Nesiah fiai, Hatifa fiai;"));
husuperobject.biblemap.put("b16_7_57", new husuperobject(16,7,57,"A Salamon szolgáinak fiai: Szótai fiai, Szófereth fiai, Perida fiai,"));
husuperobject.biblemap.put("b16_7_58", new husuperobject(16,7,58,"Jaalá fiai, Darkón fiai, Giddél fiai,"));
husuperobject.biblemap.put("b16_7_59", new husuperobject(16,7,59,"Sefátia fiai, Hattil fiai, Pókhereth-Hassebaim fiai, Ámon fiai;"));
husuperobject.biblemap.put("b16_7_60", new husuperobject(16,7,60,"Összesen a Léviták szolgái és a Salamon szolgáinak fiai, háromszázkilenczvenkettõ."));
husuperobject.biblemap.put("b16_7_61", new husuperobject(16,7,61,"És ezek, a kik feljövének Tel-Melahból, Tel-Harsából, Kerub-Addán- Immérbõl, de nem mondhatták meg családjukat és eredetüket, hogy Izráelbõl valók-é?"));
husuperobject.biblemap.put("b16_7_62", new husuperobject(16,7,62,"Delája fiai, Tóbiás fiai, Nekóda fiai, hatszáznegyvenkettõ;"));
husuperobject.biblemap.put("b16_7_63", new husuperobject(16,7,63,"És a papok közül: Habája fiai, Hakkós fiai, Barzillai fiai, a ki a Gileádbeli Barzillai leányai közül vett magának feleséget és ezek nevérõl nevezteték;"));
husuperobject.biblemap.put("b16_7_64", new husuperobject(16,7,64,"Ezek keresték írásukat, tudniillik nemzetségök könyvét, de nem találák, miért is kirekesztetének a papságból;"));
husuperobject.biblemap.put("b16_7_65", new husuperobject(16,7,65,"És megmondá nékik a király helytartója, hogy ne egyenek a szentséges áldozatból, mígnem a pap ítél az Urimmal és Tummimmal;"));
husuperobject.biblemap.put("b16_7_66", new husuperobject(16,7,66,"Mind az egész gyülekezet együtt negyvenkétezerháromszázhatvan."));
husuperobject.biblemap.put("b16_7_67", new husuperobject(16,7,67,"Szolgáikon és szolgálóikon kivül - ezek valának hétezerháromszázharminczheten - valának nékik énekes férfiaik és asszonyaik kétszáznegyvenöten;"));
husuperobject.biblemap.put("b16_7_68", new husuperobject(16,7,68,"Lovaik hétszázharminczhat, öszvéreik kétszáznegyvenöt;"));
husuperobject.biblemap.put("b16_7_69", new husuperobject(16,7,69,"Tevéik négyszázharminczöt, szamaraik hatezerhétszázhúsz."));
husuperobject.biblemap.put("b16_7_70", new husuperobject(16,7,70,"Némelyek pedig a családfõk közül adakozának az építésre: a király helytartója ada a kincsekhez aranyban ezer dárikot, ötven medenczét, ötszázharmincz papi ruhát;"));
husuperobject.biblemap.put("b16_7_71", new husuperobject(16,7,71,"A többi családfõk pedig adának az építés költségére aranyban húszezer dárikot, és ezüstben kétezerkétszáz mánét;"));
husuperobject.biblemap.put("b16_7_72", new husuperobject(16,7,72,"És a mit a többi nép ada, az aranyban húszezer dárik, és ezüstben kétezer máne, és hatvanhét papiruha vala."));
husuperobject.biblemap.put("b16_7_73", new husuperobject(16,7,73,"És lakozának mind a papok, mind a Léviták, mind a kapunállók, mind az énekesek, mind a nép fiai, mind a Léviták szolgái, szóval az egész Izráel a magok városaikban."));
husuperobject.biblemap.put("b16_8_1", new husuperobject(16,8,1,"Mikor pedig eljöve a hetedik hónap, és Izráel fiai az õ városaikban lakozának; felgyûle az egész nép egyenlõképen a piaczra, mely a vizek kapuja elõtt vala, és mondák az írástudó Ezsdrásnak, hogy hozza elõ a Mózes törvényének könyvét, melyet parancsolt vala az Úr Izráelnek."));
husuperobject.biblemap.put("b16_8_2", new husuperobject(16,8,2,"Elõhozá azért Ezsdrás pap a törvényt a gyülekezet eleibe, [melyben együtt valának] férfiak és asszonyok és mindazok, a kik azt értelemmel hallgathaták, a hetedik hónap elsõ napján."));
husuperobject.biblemap.put("b16_8_3", new husuperobject(16,8,3,"És olvasa abból a piaczon, mely a vizek kapuja elõtt vala, kora reggeltõl fogva mind délig, a férfiak és az asszonyok elõtt és mindazok elõtt, a kik azt érthetik vala, mivel az egész nép nagy figyelemmel hallgatá a törvényt."));
husuperobject.biblemap.put("b16_8_4", new husuperobject(16,8,4,"Áll vala pedig az írástudó Ezsdrás egy ezen czélra csinált faemelvényen, és mellette álla jobb keze felõl Mattithia, Sema, Anája, Uriás, Hilkiás, Maaszéja, balkeze felõl pedig: Pedája, Misáel, Malkija, Hásum, Hasbaddána, Zakariás, Mesullám."));
husuperobject.biblemap.put("b16_8_5", new husuperobject(16,8,5,"És felnyitá Ezsdrás a könyvet az egész nép szemei elõtt, mert fölötte vala az egész népnek; és mikor fölnyitá, felálla az egész nép."));
husuperobject.biblemap.put("b16_8_6", new husuperobject(16,8,6,"És áldá Ezsdrás az Urat, a nagy Istent, és felele rá az egész nép felemelt kezekkel: Ámen! Ámen! És meghajtván magukat, leborulának az Úr elõtt arczczal a földre."));
husuperobject.biblemap.put("b16_8_7", new husuperobject(16,8,7,"Jésua, Báni, Serébia, Jámin, Akkub, Sabbethai, Hódija, Maaszéja, Kelita, Azáriás, Józabád, Hanán, Pelája Léviták pedig magyarázzák vala a népnek a törvényt, s a nép a maga helyén áll vala."));
husuperobject.biblemap.put("b16_8_8", new husuperobject(16,8,8,"Olvasának pedig a könyvbõl, Isten törvényébõl világosan, s azután magyarázának, és a nép megérté az olvasottakat."));
husuperobject.biblemap.put("b16_8_9", new husuperobject(16,8,9,"Ekkor Nehémiás, a király helytartója és Ezsdrás, a pap, az írástudó és a Léviták, a kik magyaráznak vala a népnek, így szólának az egész néphez: E nap szent az Úrnak, a ti Isteneteknek, ne keseregjetek és ne sírjatok, mert sír vala az egész nép, mikor a törvény beszédeit hallá."));
husuperobject.biblemap.put("b16_8_10", new husuperobject(16,8,10,"És õ mondá nékik: Menjetek, egyetek kövért és igyatok édest és küldjetek belõle részt annak, a kinek semmi nem készíttetett, mert szent e nap a mi Urunknak, és ne bánkódjatok, mert az Úrnak öröme a ti erõsségtek."));
husuperobject.biblemap.put("b16_8_11", new husuperobject(16,8,11,"A Léviták is csendesíték vala az egész népet, mondván: Hallgassatok, mert e nap szent és ne bánkódjatok!"));
husuperobject.biblemap.put("b16_8_12", new husuperobject(16,8,12,"Elméne azért mind az egész nép enni és inni és részt küldeni és szerezni nagy vígasságot, mert megértették a beszédeket, a melyekre õket tanították vala."));
husuperobject.biblemap.put("b16_8_13", new husuperobject(16,8,13,"Másod napon pedig összegyûlének az egész népnek, a papoknak és Lévitáknak családfõi Ezsdráshoz, az írástudóhoz, hogy megértenék a törvénynek beszédit."));
husuperobject.biblemap.put("b16_8_14", new husuperobject(16,8,14,"Találák pedig írva a törvényben, melyet parancsolt vala az Úr Mózes által, hogy Izráel fiainak leveles színekben kell lakozniok az ünnepen, a hetedik hónapban,"));
husuperobject.biblemap.put("b16_8_15", new husuperobject(16,8,15,"És hogy nékik tudatniok kell és ki kell hirdettetniök minden városaikban és Jeruzsálemben ezt: Menjetek ki a hegyre, és hozzatok lombokat a nemes és vad olajfáról, mirtus és pálmalombokat, [szóval akármely] sûrû levelû fáról lombokat, hogy csináljatok leveles színeket, a mint meg van írva."));
husuperobject.biblemap.put("b16_8_16", new husuperobject(16,8,16,"Kiméne azért a nép, és hozának [lombokat,] és csinálának magoknak leveles színeket, kiki a maga háza tetején és pitvaraikban, továbbá az Isten háza pitvariban, a vizek kapujának piaczán és Efraim kapujának piaczán."));
husuperobject.biblemap.put("b16_8_17", new husuperobject(16,8,17,"Csinála pedig az egész gyülekezet, mely hazatért a fogságból, leveles színeket, és lakának a leveles színekben; mert nem cselekedtek vala így Józsuénak, a Nún fiának idejétõl fogva Izráel fiai mind az napiglan, és lõn felette igen nagy öröm[ük.]"));
husuperobject.biblemap.put("b16_8_18", new husuperobject(16,8,18,"És olvasának az Isten törvényének könyvébõl minden napon, az elsõ naptól fogva mind az utolsó napig, és ünneplének hét napon át; a nyolczadik napon pedig egybegyülekezés tartatott a törvény szerint."));
husuperobject.biblemap.put("b16_9_1", new husuperobject(16,9,1,"Azután ugyanezen hónak huszonnegyedik napján egybegyûlének Izráel fiai és bõjtölének, gyászba öltözvén és port hintvén fejökre."));
husuperobject.biblemap.put("b16_9_2", new husuperobject(16,9,2,"És elválának az Izráel magvából valók minden idegenektõl, és elõállván, vallást tõnek az õ bûneikrõl és atyáik hamisságairól."));
husuperobject.biblemap.put("b16_9_3", new husuperobject(16,9,3,"És megállának helyökön, és olvasának az Úrnak, az õ Istenöknek törvénye könyvébõl a nap negyedrésze alatt, negyedrésze alatt pedig vallást tõnek és leborulának az Úr elõtt, az õ Istenök elõtt."));
husuperobject.biblemap.put("b16_9_4", new husuperobject(16,9,4,"És felálla a Léviták emelvényére Jésua, Báni, Kadmiel, Sebánia, Bunni, Serébia, Báni és Kenáni és kiáltának nagy felszóval az Úrhoz, az õ Istenökhöz."));
husuperobject.biblemap.put("b16_9_5", new husuperobject(16,9,5,"És mondának a Léviták, Jésua, Kadmiel, Báni, Hasabnéja, Serébia, Hódija, Sebánia, Petáhia: Nosza áldjátok az Urat, a ti Isteneteket öröktõl fogva mindörökké; és áldják a te dicsõséges nevedet, mely magasabb minden áldásnál és dícséretnél!"));
husuperobject.biblemap.put("b16_9_6", new husuperobject(16,9,6,"Te vagy egyedül az Úr! Te teremtetted az eget, az egeknek egeit és minden seregöket, a földet és mindent, a mi rajta van, a tengereket minden bennök valókkal együtt; és te adsz életet mindnyájoknak, és az égnek serege elõtted borul le."));
husuperobject.biblemap.put("b16_9_7", new husuperobject(16,9,7,"Te vagy az Úr, az Isten, a ki választottad Ábrámot és kihozád õt a Káldeusoknak Úr [nevû városából], és nevezéd õt Ábrahámnak."));
husuperobject.biblemap.put("b16_9_8", new husuperobject(16,9,8,"És találád az õ szívét hûnek te elõtted és szerzél vele szövetséget, hogy adod a Kananeusok, Hitteusok, Emoreusok, Perizeusok, Jebuzeusok, Girgázeusok földét, hogy adod az õ magvának; és megteljesítéd beszédeidet, mert igaz vagy te!"));
husuperobject.biblemap.put("b16_9_9", new husuperobject(16,9,9,"Megtekintéd annakfelette a mi atyáinknak Égyiptomban való nyomorúságát, és az õ kiáltásukat meghallád a Veres tengernél,"));
husuperobject.biblemap.put("b16_9_10", new husuperobject(16,9,10,"És tevél jeleket és csodákat a Faraón és minden szolgáin és földének egész népén, mert tudtad, hogy kevélyen cselekedtek a te néped ellen; és szerzél magadnak nevet, mint e mai napság [is] van."));
husuperobject.biblemap.put("b16_9_11", new husuperobject(16,9,11,"És a tengert kétfelé választád õ elõttök és szárazon menének át a tenger közepén; üldözõiket pedig mélységbe borítád, mint követ nagy vizekbe."));
husuperobject.biblemap.put("b16_9_12", new husuperobject(16,9,12,"És felhõnek oszlopában vezetéd õket nappal s tûznek oszlopában éjjel, hogy megvilágosítsd nékik az utat, melyen menjenek."));
husuperobject.biblemap.put("b16_9_13", new husuperobject(16,9,13,"És a Sinai hegyre leszállál, s szólál velök az égbõl, s adál nékik helyes végzéseket, igaz törvényeket, jó rendeléseket és parancsolatokat."));
husuperobject.biblemap.put("b16_9_14", new husuperobject(16,9,14,"A te szent szombatodat is megjelentéd nékik, és parancsolatokat, rendeléseket és törvényt parancsolál nékik szolgád, Mózes által."));
husuperobject.biblemap.put("b16_9_15", new husuperobject(16,9,15,"És kenyeret az égbõl adál nékik éhségökben, és vizet a kõsziklából hozál ki nékik szomjúságokban; és mondád nékik, hogy menjenek be és bírják a földet, melyre nézve fölemelted kezedet, hogy nékik adod."));
husuperobject.biblemap.put("b16_9_16", new husuperobject(16,9,16,"Õk pedig, a mi atyáink, felfuvalkodának, és megkeményíték nyakukat és nem hallgaták parancsolataidat;"));
husuperobject.biblemap.put("b16_9_17", new husuperobject(16,9,17,"És vonakodának engedelmeskedni, és meg nem emlékezének a te csudatételeidrõl, a melyeket velök cselekedtél, hanem megkeményíték nyakukat, és [arra ]adák fej[ök]et, hogy visszatérnek rabságukba az õ makacskodásukban; de te bûnbocsánatnak Istene vagy, könyörülõ és irgalmas, hosszútûrõ és nagy kegyelmességû, és el nem hagytad õket."));
husuperobject.biblemap.put("b16_9_18", new husuperobject(16,9,18,"Sõt még borjúképet is csinálának magoknak, és ezt mondják: Ez a te Istened, a ki kihozott téged Égyiptomból, és nagy bosszúsággal illettek téged;"));
husuperobject.biblemap.put("b16_9_19", new husuperobject(16,9,19,"És te nagy irgalmasságodban nem hagyád el õket a pusztában; a felhõnek oszlopa nem távozék el felõlök nappal, hogy vezérlené õket az úton, és a tûznek oszlopa éjjel, hogy világítana nékik az úton, melyen menének."));
husuperobject.biblemap.put("b16_9_20", new husuperobject(16,9,20,"És a te jó lelkedet adád nékik, hogy õket oktatná; és mannádat nem vonád meg szájoktól, s vizet adál nékik szomjúságokban."));
husuperobject.biblemap.put("b16_9_21", new husuperobject(16,9,21,"És negyven esztendeig tápláltad õket a pusztában, fogyatkozásuk nem vala, ruháik el nem nyûttenek és lábaik meg nem dagadának."));
husuperobject.biblemap.put("b16_9_22", new husuperobject(16,9,22,"Adál annakfelette nékik országokat és népeket, és elosztád ezeket határok szerint és õk elfoglalák Sihón földét, és Hesbon királyának földét, és Ógnak, Básán királyának földét."));
husuperobject.biblemap.put("b16_9_23", new husuperobject(16,9,23,"Fiaikat pedig megsokasítád, mint az ég csillagait, és bevivéd õket a földre, mely felõl megmondád atyáiknak, hogy bemennek arra, hogy bírják azt."));
husuperobject.biblemap.put("b16_9_24", new husuperobject(16,9,24,"És bemenének a fiak és elfoglalák a földet, és megalázád elõttök a földnek lakóit, a Kananeusokat, s kezökbe adád õket, mind királyaikat, mind a föld népeit, hogy cselekedjenek velök kedvök szerint."));
husuperobject.biblemap.put("b16_9_25", new husuperobject(16,9,25,"És megvevének erõs városokat és kövér földet, s elfoglalának minden jóval teljes házakat, kõbõl vágott kutakat, szõlõs és olajfás kerteket és sok gyümölcsfát, s evének és megelégedének és meghízának, s gyönyörködének a te nagy jóvoltodban."));
husuperobject.biblemap.put("b16_9_26", new husuperobject(16,9,26,"Makacskodának pedig és pártot ütének ellened, és veték törvényedet hátuk mögé; prófétáidat is meggyilkolák, a kik bizonyságot tõnek ellenök, hogy õket te hozzád térítenék, és nagy bosszúsággal illettek téged."));
husuperobject.biblemap.put("b16_9_27", new husuperobject(16,9,27,"Annakokáért adád õket nyomorgatóik kezébe és megnyomorgaták õket; de nyomorúságok idején hozzád kiáltának, és te az égbõl meghallgatád és nagy irgalmasságod szerint adál nékik szabadítókat, és megszabadíták õket nyomorgatóik kezébõl."));
husuperobject.biblemap.put("b16_9_28", new husuperobject(16,9,28,"És mikor megnyugodtak vala, ismét gonoszt cselekvének elõtted, és te átadád õket ellenségeik kezébe, a kik uralkodának rajtok; s midõn ismét hozzád kiáltának, te az égbõl meghallgatád és megszabadítád õket irgalmasságod szerint sokszor."));
husuperobject.biblemap.put("b16_9_29", new husuperobject(16,9,29,"És bizonyságot tevél ellenök, hogy visszatérítsd õket törvényedhez; de õk felfuvalkodának s nem hallgaták parancsolatidat, és végzéseid ellen vétkezének, melyeket ha valaki megtart, él azok által; és makacskodva hátat fordítának, s nyakukat megkeményíték és nem engedelmeskedének."));
husuperobject.biblemap.put("b16_9_30", new husuperobject(16,9,30,"És mégis meghosszabbítád felettök [kegyelmedet] sok esztendõkön át, s bizonyságot tevél ellenök lelkeddel, prófétáid által, de nem figyelmezének; annakokáért adád õket a föld népeinek kezébe."));
husuperobject.biblemap.put("b16_9_31", new husuperobject(16,9,31,"De nagy irgalmasságod szerint meg nem emésztéd õket, sem el nem hagyád õket, mert te könyörülõ és irgalmas Isten vagy."));
husuperobject.biblemap.put("b16_9_32", new husuperobject(16,9,32,"Most annakokáért, oh mi Istenünk, nagy, erõs és rettenetes Isten, a ki megõrized a szövetséget és irgalmasságot, ne legyen kicsiny elõtted mindaz a nyomorúság, a mely utolért minket, királyainkat, fejedelmeinket, papjainkat, prófétáinkat, atyáinkat és egész népedet, Assiria királyainak napjaitól fogva mind e mai napig."));
husuperobject.biblemap.put("b16_9_33", new husuperobject(16,9,33,"Hiszen te igaz vagy mindenekben, valamelyek reánk jövének; mert te igazságot mûveltél, mi pedig hamisságot cselekvénk!"));
husuperobject.biblemap.put("b16_9_34", new husuperobject(16,9,34,"Hiszen a mi királyaink, fejedelmeink, papjaink és atyáink nem cselekedték törvényedet és nem figyelmeztek parancsolataidra és bizonyságtételeidre, melyek által bizonyságot tettél õ ellenök;"));
husuperobject.biblemap.put("b16_9_35", new husuperobject(16,9,35,"És õk az õ országokban s a te nagy jóvoltodban, melylyel megáldád õket, s a széles és kövér földön, melyet nékik adál, nem akartak szolgáid lenni; és nem tértek meg gonosz cselekedeteikbõl."));
husuperobject.biblemap.put("b16_9_36", new husuperobject(16,9,36,"És ímé mi most szolgák vagyunk azon a földön, melyet a mi atyáinknak adál, hogy ennék annak gyümölcsét és javát, ímé mi szolgák vagyunk azon;"));
husuperobject.biblemap.put("b16_9_37", new husuperobject(16,9,37,"És termését bõven hozza a királyoknak, a kiket fölibünk helyezél a mi bûneinkért, s testeinken uralkodnak és barmainkon az õ kedvök szerint; és mi nagy nyomorúságban vagyunk!"));
husuperobject.biblemap.put("b16_9_38", new husuperobject(16,9,38,"És mindemellett mi erõs kötést szerzénk és azt aláírtuk, melyet megpecsételének a mi fejedelmeink, Lévitáink és papjaink."));
husuperobject.biblemap.put("b16_10_1", new husuperobject(16,10,1,"A megpecsételt [kötése]ken pedig ott valának: Nehémiás, a király helytartója, a Hakhalia fia és Sédékiás;"));
husuperobject.biblemap.put("b16_10_2", new husuperobject(16,10,2,"Serája, Azariás, Jeremiás,"));
husuperobject.biblemap.put("b16_10_3", new husuperobject(16,10,3,"Pashur, Amaria, Malakiás,"));
husuperobject.biblemap.put("b16_10_4", new husuperobject(16,10,4,"Hattus, Sebánia, Malluk,"));
husuperobject.biblemap.put("b16_10_5", new husuperobject(16,10,5,"Hárim, Merémóth, Abdiás,"));
husuperobject.biblemap.put("b16_10_6", new husuperobject(16,10,6,"Dániel, Ginnethón, Bárukh,"));
husuperobject.biblemap.put("b16_10_7", new husuperobject(16,10,7,"Mesullám, Abija, Mijámin,"));
husuperobject.biblemap.put("b16_10_8", new husuperobject(16,10,8,"Maazia, Bilgai, Semája; ezek papok voltak."));
husuperobject.biblemap.put("b16_10_9", new husuperobject(16,10,9,"A Léviták pedig [ezek:] Jésua, Azania fia, Binnui, a Hénadád fiai közül, Kadmiel,"));
husuperobject.biblemap.put("b16_10_10", new husuperobject(16,10,10,"És atyjafiaik: Sebánia, Hódija, Kelita, Pelája, Hanán,"));
husuperobject.biblemap.put("b16_10_11", new husuperobject(16,10,11,"Mika, Rehób, Hasábia,"));
husuperobject.biblemap.put("b16_10_12", new husuperobject(16,10,12,"Zakkur, Serébia, Sebánia,"));
husuperobject.biblemap.put("b16_10_13", new husuperobject(16,10,13,"Hódija, Báni, Beninu."));
husuperobject.biblemap.put("b16_10_14", new husuperobject(16,10,14,"A nép fejei [pedig ezek:] Parós Pahath-Moáb, Elám, Zattu, Báni,"));
husuperobject.biblemap.put("b16_10_15", new husuperobject(16,10,15,"Bunni, Azgád, Bébai,"));
husuperobject.biblemap.put("b16_10_16", new husuperobject(16,10,16,"Adonija, Bigvai, Adin,"));
husuperobject.biblemap.put("b16_10_17", new husuperobject(16,10,17,"Áter, Ezékiás, Azzur,"));
husuperobject.biblemap.put("b16_10_18", new husuperobject(16,10,18,"Hódija, Hásum, Bésai,"));
husuperobject.biblemap.put("b16_10_19", new husuperobject(16,10,19,"Hárif, Anathóth, Nébai,"));
husuperobject.biblemap.put("b16_10_20", new husuperobject(16,10,20,"Magpiás, Mesullám, Hézir,"));
husuperobject.biblemap.put("b16_10_21", new husuperobject(16,10,21,"Mesézabel, Sádók, Jaddua,"));
husuperobject.biblemap.put("b16_10_22", new husuperobject(16,10,22,"Pelátia, Hanán, Anája,"));
husuperobject.biblemap.put("b16_10_23", new husuperobject(16,10,23,"Hóseás, Hanánia, Hásub,"));
husuperobject.biblemap.put("b16_10_24", new husuperobject(16,10,24,"Hallóhes, Pilha, Sóbek,"));
husuperobject.biblemap.put("b16_10_25", new husuperobject(16,10,25,"Rehum, Hasabná, Maaszéja,"));
husuperobject.biblemap.put("b16_10_26", new husuperobject(16,10,26,"És Ahija, Hanán, Anán,"));
husuperobject.biblemap.put("b16_10_27", new husuperobject(16,10,27,"Mallukh, Hárim, Baána."));
husuperobject.biblemap.put("b16_10_28", new husuperobject(16,10,28,"És a nép többi része, a papok, a Léviták, a kapunállók, az énekesek, a Léviták szolgái és mindenki, a ki elkülöníté magát a tartományok népeitõl, az Isten törvényéhez [állván,] feleségeik, fiaik, leányaik, mindenki, a kinek értelme és okossága vala,"));
husuperobject.biblemap.put("b16_10_29", new husuperobject(16,10,29,"Csatlakozának atyjokfiaihoz, elõljáróikhoz, és átok mellett esküt tevének, hogy az Isten törvényében járnak, a mely Mózes által az Isten szolgája által adatott vala ki; s hogy megõrzik és cselekeszik az Úrnak, a mi Urunknak minden parancsolatait, végzéseit és rendeléseit;"));
husuperobject.biblemap.put("b16_10_30", new husuperobject(16,10,30,"És hogy nem fogjuk adni leányainkat feleségül a föld népeinek, sem az õ leányaikat nem fogjuk venni a mi fiainknak,"));
husuperobject.biblemap.put("b16_10_31", new husuperobject(16,10,31,"És hogy a föld népeitõl, akik árúkat és mindenféle gabonát hoznak szombatnapon eladni, nem fogunk venni tõlök szombaton és [egyéb] szent napon, és hogy nem fogjuk bevetni a földet a hetedik esztendõben, és elengedünk minden tartozást."));
husuperobject.biblemap.put("b16_10_32", new husuperobject(16,10,32,"És megállapítánk magunkra nézve parancsolatokat: hogy vetünk magunkra harmadrész siklust esztendõnként a mi Istenünk házának szolgálatára,"));
husuperobject.biblemap.put("b16_10_33", new husuperobject(16,10,33,"A szent kenyerekre, a szüntelen való ételáldozatra és a szüntelen való égõáldozatra, a szombatokon, újholdak napján [viendõ áldozatokra,] az ünnepnapokra, a szent dolgokra, a bûnért való áldozatokra, hogy [mindezek] megtisztítsák Izráelt; és a mi Istenünk házának minden munkájára;"));
husuperobject.biblemap.put("b16_10_34", new husuperobject(16,10,34,"Sorsot veténk továbbá a fa hozása felõl a papok, Léviták és a nép között, hogy hordjuk azt a mi Istenünk házába családaink szerint bizonyos idõkben esztendõnként, hogy égjen az Úrnak, a mi Istenünknek oltárán, a mint meg van írva a törvényben,"));
husuperobject.biblemap.put("b16_10_35", new husuperobject(16,10,35,"És hogy felviszszük földünknek elsõ zsengéjét és minden fa gyümölcsének elsõ zsengéjét esztendõnként az Úr házába;"));
husuperobject.biblemap.put("b16_10_36", new husuperobject(16,10,36,"Annakfelette fiainknak, barmainknak elsõ fiait, a mint meg van írva a törvényben; továbbá, hogy elviszszük szarvasmarháinknak és juhainknak elsõ fajzásait a mi Istenünk házába a papoknak, a kik szolgálnak a mi Istenünk házában."));
husuperobject.biblemap.put("b16_10_37", new husuperobject(16,10,37,"És a mi lisztjeinknek, felemelt áldozatainknak, minden fa gyümölcsének, mustnak és olajnak zsengéjét felviszszük a papoknak, a mi Istenünk házának kamaráiba, földünknek tizedét pedig a Lévitákhoz; mert õk, a Léviták szedik be a tizedet minden földmûveléssel foglalatoskodó városainkban."));
husuperobject.biblemap.put("b16_10_38", new husuperobject(16,10,38,"És legyen a pap, Áron fia a Lévitákkal, midõn a Léviták a tizedet beszedik; és a Léviták vigyék fel a tizednek tizedét a mi Istenünk házába, a tárháznak kamaráiba;"));
husuperobject.biblemap.put("b16_10_39", new husuperobject(16,10,39,"Mert a kamarákba kell hozniok Izráel fiainak és Lévi fiainak a gabonának, a mustnak és az olajnak ajándékát, holott vannak a szent edények és az [Istennek] szolgáló papok, a kapunállók és az énekesek; és mi nem hagyjuk el a mi Istenünknek házát."));
husuperobject.biblemap.put("b16_11_1", new husuperobject(16,11,1,"És lakozának a nép fejedelmei Jeruzsálemben, a többi nép pedig sorsot vete, hogy minden tíz emberbõl vinnének egyet Jeruzsálembe, a szent városba lakóul, a többi kilencz pedig [marad a maga] városában."));
husuperobject.biblemap.put("b16_11_2", new husuperobject(16,11,2,"És áldá a nép mindazon férfiakat, a kik önkéntesen vállalkozának arra, hogy Jeruzsálemben lakoznak."));
husuperobject.biblemap.put("b16_11_3", new husuperobject(16,11,3,"Ezek pedig a tartomány fejei, a kik Jeruzsálemben megtelepedének; de Júda városaiban lakozék kiki az õ örökségében, városaikban: az Izráel, a papok, a Léviták, a Léviták szolgái és Salamon szolgáinak fiai."));
husuperobject.biblemap.put("b16_11_4", new husuperobject(16,11,4,"Jeruzsálemben azért megtelepedének a Júda fiai közül és Benjámin fiai közül: Júda fiai közül: Athája, Uzzija fia, ki Zakariás fia, ki Amaria fia, ki Sefátia fia, ki Mahalalél fia vala, a Pérecz fiai közül,"));
husuperobject.biblemap.put("b16_11_5", new husuperobject(16,11,5,"És Maaszéja, Báruk fia, ki Kolhóze fia, ki Hazája fia, ki Adája fia, ki Jójárib fia, ki Zakariás fia, ki Hasilóni fia vala."));
husuperobject.biblemap.put("b16_11_6", new husuperobject(16,11,6,"Pérecz fiai összesen, a kik Jeruzsálemben laknak vala, négyszázhatvannyolcz erõs férfi;"));
husuperobject.biblemap.put("b16_11_7", new husuperobject(16,11,7,"Benjámin fiai pedig ezek: Szallu, Mesullám fia, ki Jóed fia, ki Pedája fia, ki Kólája fia, ki Maaszéja fia, ki Ithiel fia, ki Ézsaiás fia vala,"));
husuperobject.biblemap.put("b16_11_8", new husuperobject(16,11,8,"És õ utána Gabbai, Szallai, kilenczszázhuszonnyolczan;"));
husuperobject.biblemap.put("b16_11_9", new husuperobject(16,11,9,"És Jóel, a Zikri fia elõljárójok volt ezeknek, Júda pedig, a Hasszenua fia, a város másodrendû elõljárója."));
husuperobject.biblemap.put("b16_11_10", new husuperobject(16,11,10,"A papok közül: Jedája, Jójárib fia, Jákhin,"));
husuperobject.biblemap.put("b16_11_11", new husuperobject(16,11,11,"Serája pedig, a Hilkiás fia, ki Mesullám fia, ki Sádók fia, ki Merájóth fia, ki Akhitúb fia volt, az Isten házának fejedelme vala,"));
husuperobject.biblemap.put("b16_11_12", new husuperobject(16,11,12,"És atyjokfiai, a kik a ház munkáját teljesítik vala, nyolczszázhuszonketten; és Adája, a Jeróhám fia, ki Pelália fia, ki Amsi fia, ki Zakariás fia, ki Pashur fia, ki Malkija fia vala,"));
husuperobject.biblemap.put("b16_11_13", new husuperobject(16,11,13,"És az õ atyjafiai, a családfõk kétszáznegyvenketten, és Amasszai, Azarél fia, ki Ahzai fia, ki Mesillémóth fia, ki Immér fia vala,"));
husuperobject.biblemap.put("b16_11_14", new husuperobject(16,11,14,"És az õ atyjokfiai, vitéz férfiak, százhuszonnyolczan, elõljárójok volt pedig Zabdiel, a Haggedólim fia."));
husuperobject.biblemap.put("b16_11_15", new husuperobject(16,11,15,"A Léviták közül pedig: Semája, Hassub fia, ki Azrikám fia, ki Hasábia fia, ki Bunni fia vala."));
husuperobject.biblemap.put("b16_11_16", new husuperobject(16,11,16,"És Sabbethai és Józabád, az Isten házának külsõ munkája felett felügyelõk valának a Léviták fejei közül,"));
husuperobject.biblemap.put("b16_11_17", new husuperobject(16,11,17,"És Mattánia, - a Mika fia, ki Zabdi fia, ki Asáf fia vala, - a ki vezetõje volt a hálaadó éneklésnek, s elkezdé azt az imádság után, és Bakbukia, a ki másodrendû vala atyjafiai között, és Abda, Sammua fia, ki Gálál fia, ki Jeduthun fia vala;"));
husuperobject.biblemap.put("b16_11_18", new husuperobject(16,11,18,"A Léviták összesen a szent városban: kétszáznyolczvannégyen."));
husuperobject.biblemap.put("b16_11_19", new husuperobject(16,11,19,"A kapunállók pedig: Akkub, Talmón és atyjokfiai, a kapukat õrizõk százhetvenketten."));
husuperobject.biblemap.put("b16_11_20", new husuperobject(16,11,20,"A többi Izráeliták pedig, a papok, a Léviták [lakozának] Júdának minden városaiban, kiki az õ örökségében."));
husuperobject.biblemap.put("b16_11_21", new husuperobject(16,11,21,"A Léviták szolgái pedig lakozának az Ófelben, és Siha és Gipsa valának elõljáróik a Léviták szolgáinak."));
husuperobject.biblemap.put("b16_11_22", new husuperobject(16,11,22,"A Léviták elõljárója vala Jeruzsálemben, az Isten háza szolgálatjánál, Uzzi, a Báni fia, - ki Hasábia fia, ki Mattánia fia, ki Mika fia volt, - Asáf fiai, az énekesek közül;"));
husuperobject.biblemap.put("b16_11_23", new husuperobject(16,11,23,"Mert õk, [a Léviták], a király parancsolata szerint, az énekesek pedig kötés szerint [végezék] naponként való teendõjüket;"));
husuperobject.biblemap.put("b16_11_24", new husuperobject(16,11,24,"Petáhja pedig, a Mesézabel fia, Júda fiának, Zerahnak fiai közül, a király oldala mellett vala a nép minden dolgában."));
husuperobject.biblemap.put("b16_11_25", new husuperobject(16,11,25,"A falukban, ezek határaiban pedig Júda fiai közül lakozának Kirjáth- Arbában és mezõvárosaiban, Dibonban és mezõvárosaiban, Jekabseélben és faluiban."));
husuperobject.biblemap.put("b16_11_26", new husuperobject(16,11,26,"Jésuában, Móladában és Beth-Péletben."));
husuperobject.biblemap.put("b16_11_27", new husuperobject(16,11,27,"Hasár-Suálban, Beér-Sebában és mezõvárosaiban,"));
husuperobject.biblemap.put("b16_11_28", new husuperobject(16,11,28,"Siklágban, Mekónában és mezõvárosaiban,"));
husuperobject.biblemap.put("b16_11_29", new husuperobject(16,11,29,"En-Rimmonban, Sorában, Jarmuthban,"));
husuperobject.biblemap.put("b16_11_30", new husuperobject(16,11,30,"Zánoáhban, Adullámban és faluiban, Lákisban és határaiban, Azékában és mezõvárosaiban, - ekként laknak vala Beér-Sebától mind a Hinnóm völgyéig."));
husuperobject.biblemap.put("b16_11_31", new husuperobject(16,11,31,"Benjámin fiai pedig laknak vala Gebától fogva Mikmásban, Ajában, Béthelben és mezõvárosaiban."));
husuperobject.biblemap.put("b16_11_32", new husuperobject(16,11,32,"Anatótban, Nóbban, Anániában,"));
husuperobject.biblemap.put("b16_11_33", new husuperobject(16,11,33,"Hásórban, Rámában, Gittajimban,"));
husuperobject.biblemap.put("b16_11_34", new husuperobject(16,11,34,"Hádidban, Sebóimban, Neballátban,"));
husuperobject.biblemap.put("b16_11_35", new husuperobject(16,11,35,"Lódban, Onóban, s a mesteremberek völgyében."));
husuperobject.biblemap.put("b16_11_36", new husuperobject(16,11,36,"A Léviták közül pedig némely júdai osztályok Benjáminhoz [csatlakozának]."));
husuperobject.biblemap.put("b16_12_1", new husuperobject(16,12,1,"Ezek pedig a papok és Léviták, a kik feljövének Zorobábellel, Sealtiél fiával és Jésuával: Serája, Jeremiás, Ezsdrás."));
husuperobject.biblemap.put("b16_12_2", new husuperobject(16,12,2,"Amária, Mallukh, Hattus,"));
husuperobject.biblemap.put("b16_12_3", new husuperobject(16,12,3,"Sekánia, Rehum, Meremóth,"));
husuperobject.biblemap.put("b16_12_4", new husuperobject(16,12,4,"Iddó, Ginnethói, Abija,"));
husuperobject.biblemap.put("b16_12_5", new husuperobject(16,12,5,"Mijámin, Maádia, Bilga,"));
husuperobject.biblemap.put("b16_12_6", new husuperobject(16,12,6,"Semája, Jójárib, Jedája,"));
husuperobject.biblemap.put("b16_12_7", new husuperobject(16,12,7,"Szallu, Ámók, Hilkija, Jedája, - ezek valának fejei a papoknak és atyjokfiainak Jésua napjaiban."));
husuperobject.biblemap.put("b16_12_8", new husuperobject(16,12,8,"A Léviták pedig ezek: Jésua, Binnui, Kadmiel, Serébia, Jehuda, Mattánia, - ki vezetõje vala hálaadó éneklésnek, atyjafiaival."));
husuperobject.biblemap.put("b16_12_9", new husuperobject(16,12,9,"És Bakbukia, s Unni, az õ atyjokfiai velök szemben, tisztök szerint."));
husuperobject.biblemap.put("b16_12_10", new husuperobject(16,12,10,"És Jésua nemzé Jojákimot, s Jojákim nemzé Eliásibot, s Eliásib nemzé Jójadát,"));
husuperobject.biblemap.put("b16_12_11", new husuperobject(16,12,11,"És Jójada nemzé Jónathánt, s Jónathán nemzé Jadduát."));
husuperobject.biblemap.put("b16_12_12", new husuperobject(16,12,12,"Jójákim napjaiban pedig papok, családfõk valának: Serája családjában Merája, Jerémiáséban Hanánia,"));
husuperobject.biblemap.put("b16_12_13", new husuperobject(16,12,13,"Ezsdráséban Mesullám, Amáriáéban Jóhanán,"));
husuperobject.biblemap.put("b16_12_14", new husuperobject(16,12,14,"Melikuéban Jónathán, Sebaniáéban József,"));
husuperobject.biblemap.put("b16_12_15", new husuperobject(16,12,15,"Háriméban Adna, Merajóthéban Helkai,"));
husuperobject.biblemap.put("b16_12_16", new husuperobject(16,12,16,"Iddóéban Zakhariás, Ginnethónéban Mesullám,"));
husuperobject.biblemap.put("b16_12_17", new husuperobject(16,12,17,"Abijáéban Zikri, Minjáminéban és Móadiáéban Piltai,"));
husuperobject.biblemap.put("b16_12_18", new husuperobject(16,12,18,"Bilgáéban Sammua, Semájáéban Jónathán,"));
husuperobject.biblemap.put("b16_12_19", new husuperobject(16,12,19,"Jójáribéban Mattenai, Jedajáéban Uzzi,"));
husuperobject.biblemap.put("b16_12_20", new husuperobject(16,12,20,"Szallaiéban Kallai, Amókéban Éber,"));
husuperobject.biblemap.put("b16_12_21", new husuperobject(16,12,21,"Hilkijáéban Hasábia, Jedajáéban Nethanéel."));
husuperobject.biblemap.put("b16_12_22", new husuperobject(16,12,22,"A Léviták közül Eliásib, Jójada, Jóhanán és Jaddua napjaiban felírattak a családfõk, a papok pedig mind a persiai Dárius országlásáig."));
husuperobject.biblemap.put("b16_12_23", new husuperobject(16,12,23,"A Léviták családfõi felírattattak a krónikák könyvében Jóhanánnak, Eliásib fiának napjaiig;"));
husuperobject.biblemap.put("b16_12_24", new husuperobject(16,12,24,"A Léviták családfõi [valának:] Hasábia, Serébia, Jésua a Kadmiel fia, és az õ atyjokfiai velök szemben a dícsérõ és hálaadó éneklésre, Dávidnak, az Isten emberének parancsolata szerint, mint egy éneklõ sereg együtt a másikkal."));
husuperobject.biblemap.put("b16_12_25", new husuperobject(16,12,25,"Mattánia, Bakbukia, Obádia, Mesullám, Talmón, Akkub pedig kapunállók, õrt állván a kapuk kincses házainál."));
husuperobject.biblemap.put("b16_12_26", new husuperobject(16,12,26,"Ezek valának Jojákim napjaiban, ki Jésua fia, ki Jósadák fia volt, és Nehémiásnak, a helytartónak és Ezsdrásnak, a törvénytudó papnak napjaiban."));
husuperobject.biblemap.put("b16_12_27", new husuperobject(16,12,27,"Jeruzsálem kõfalának felszentelésekor pedig fölkeresék a Lévitákat minden õ helyeiken, hogy behozzák õket Jeruzsálembe, hogy véghezvigyék a felszentelést örömmel és hálaadással és énekléssel, czimbalmokkal, lantokkal és cziterákkal."));
husuperobject.biblemap.put("b16_12_28", new husuperobject(16,12,28,"És összegyûlének az énekesek fiai mind Jeruzsálem környékérõl, mind pedig a Netófátiak faluiból."));
husuperobject.biblemap.put("b16_12_29", new husuperobject(16,12,29,"Mind Beth-Gilgálból, mind Geba és Azmáveth határaiból, mert falukat építének magoknak az énekesek Jeruzsálem körül."));
husuperobject.biblemap.put("b16_12_30", new husuperobject(16,12,30,"És minekutána megtisztíták magokat a papok és a Léviták, megtisztíták a népet is, s a kapukat és a kõfalat."));
husuperobject.biblemap.put("b16_12_31", new husuperobject(16,12,31,"Azután felvivém Júda fejedelmeit a kõfalhoz és rendelék két nagy hálaadást éneklõ sereget és csapatokat; [az egyik] jobbkéz felé [méne] a kõfal mellett a szemétkapu felé,"));
husuperobject.biblemap.put("b16_12_32", new husuperobject(16,12,32,"És utánok méne Hósaája és Júda fejedelmeinek fele,"));
husuperobject.biblemap.put("b16_12_33", new husuperobject(16,12,33,"És Azária, Ezsdrás és Mesullám,"));
husuperobject.biblemap.put("b16_12_34", new husuperobject(16,12,34,"Júda és Benjámin, Semája és Jeremiás,"));
husuperobject.biblemap.put("b16_12_35", new husuperobject(16,12,35,"A papok fiai közül kürtökkel; és Zakariás, a Jónathán fia, ki Semája fia, ki Mattánia fia, ki Mikája fia, ki Zakkur fia, ki Asáf fia vala,"));
husuperobject.biblemap.put("b16_12_36", new husuperobject(16,12,36,"És az õ atyjafiai: Semája, Azarél, Milalai, Gilalai, Máaj, Nethanéel, Júda és Hanáni, Dávidnak, az Isten emberének éneklõszerszámaival; Ezsdrás pedig, az írástudó elõttök megy vala;"));
husuperobject.biblemap.put("b16_12_37", new husuperobject(16,12,37,"[Méne pedig e sereg] a forrás kapuja felé, s egyenesen fölmenének Dávid városának lépcsõin a kõfalhoz vezetõ lépcsõre, s menének Dávid háza mellett s a vizek kapujáig napkelet felé."));
husuperobject.biblemap.put("b16_12_38", new husuperobject(16,12,38,"A hálaadást éneklõ második sereg pedig, mely átellenben megy vala - én pedig és a népnek fele utánok - [méne] a kõfal mellett, a kemenczék tornya mellett, mind a széles kõfalig."));
husuperobject.biblemap.put("b16_12_39", new husuperobject(16,12,39,"És az Efraim kapuja mellett és az ó város kapuja mellett és a halaknak kapuja mellett és a Hananél tornya és a Meáh torony mellett mind a juhok kapujáig, s megállának a tömlöcz kapujában."));
husuperobject.biblemap.put("b16_12_40", new husuperobject(16,12,40,"És megálla a hálaadást éneklõ mindkét sereg az Isten házánál, és én s a fejedelmeknek fele velem,"));
husuperobject.biblemap.put("b16_12_41", new husuperobject(16,12,41,"És a papok: Eljákim, Maaséja, Minjámin, Mikája, Eljoénai, Zakariás, Hanánia kürtökkel,"));
husuperobject.biblemap.put("b16_12_42", new husuperobject(16,12,42,"És Maaséja, Semája, Eleázár, Uzzi, Jóhanán, Malkija, Elám és Ezer; és zengedeznek vala az énekesek, és Jizrahia az elõljáró."));
husuperobject.biblemap.put("b16_12_43", new husuperobject(16,12,43,"És áldozának azon napon nagy áldozatokkal, és vigadának, mert az Isten megvidámítá õket nagy örömmel, sõt az asszonyok és gyermekek is vigadának; és Jeruzsálemnek öröme nagy messze hallatott."));
husuperobject.biblemap.put("b16_12_44", new husuperobject(16,12,44,"És rendeltetének ama napon férfiak a kincseknek, felemelt áldozatoknak, elsõ zsengéknek és a tizedeknek tárházai fölé, hogy összegyûjtsék azokba a városok határaiból a törvény szerint való részöket a papoknak és a Lévitáknak, mert örvendeze Júda a papokon és a Lévitákon, a kik ott állának [tisztökben,]"));
husuperobject.biblemap.put("b16_12_45", new husuperobject(16,12,45,"Mint a kik megõrzik Istenök rendtartását s a tisztaság rendtartását, és az énekesek és a kapunállók [is ott állának tisztökben], Dávidnak és az õ fiának, Salamonnak parancsolatja szerint;"));
husuperobject.biblemap.put("b16_12_46", new husuperobject(16,12,46,"Mert Dávidnak napjaiban Asáf vala régtõl fogva az énekesek és az Istennek hálát adó és õt dícsérõ éneklésnek vezetõje."));
husuperobject.biblemap.put("b16_12_47", new husuperobject(16,12,47,"És a Zorobábel és Nehémiás napjaiban megadja vala az egész Izráel az énekeseknek és kapunállóknak az õ részöket naponként, nevezetesen oda szentelik vala azt a Lévitáknak, a Léviták pedig az Áron fiainak."));
husuperobject.biblemap.put("b16_13_1", new husuperobject(16,13,1,"Azon a napon olvasának a Mózes könyvébõl a népnek hallatára és írva találák benne, hogy Ammón és Moáb soha be ne menjen az Isten gyülekezetébe,"));
husuperobject.biblemap.put("b16_13_2", new husuperobject(16,13,2,"Mivelhogy nem mentek vala eleikbe Izráel fiainak kenyérrel és vízzel, sõt bérbe fogadták ellenök Bálámot, hogy õket megátkozná, de a mi Istenünk az átkot áldásra fordítá."));
husuperobject.biblemap.put("b16_13_3", new husuperobject(16,13,3,"És lõn, hogy mikor hallották e törvényt, kirekesztének Izráel közül minden elegy-belegy népet."));
husuperobject.biblemap.put("b16_13_4", new husuperobject(16,13,4,"Ennekelõtte pedig Eliásib, a pap, ki Istenünk házának kamarái fölé rendelteték, rokonságba jutott Tóbiással;"));
husuperobject.biblemap.put("b16_13_5", new husuperobject(16,13,5,"És átengedett néki egy nagy kamarát, holott abban annakelõtte az ételáldozatot, a tömjént, az edényeket és az olajnak, mustnak és gabonának tizedét, mint a kapunállóknak, énekeseknek és Lévitáknak törvény szerint való részét és a papoknak ajándékát helyeztetik vala el."));
husuperobject.biblemap.put("b16_13_6", new husuperobject(16,13,6,"Mind ennek történtekor én nem valék Jeruzsálemben, mert Artaxerxes babilóniai királynak harminczkettedik esztendejében visszamentem vala a királyhoz, s napok múltán [újra szabadságot] kértem a királytól."));
husuperobject.biblemap.put("b16_13_7", new husuperobject(16,13,7,"És visszatérék Jeruzsálembe, és megértém e gonoszt, melyet Eliásib cselekedett vala Tóbiásért, hogy átengedett néki egy kamarát az Isten házának pitvaraiban."));
husuperobject.biblemap.put("b16_13_8", new husuperobject(16,13,8,"Igen gonosznak tetszék pedig ez nékem s kivettetém Tóbiás házának minden edényeit abból a kamarából;"));
husuperobject.biblemap.put("b16_13_9", new husuperobject(16,13,9,"És parancsolatomra megtisztíták a kamarákat, és visszahordatám azokba Isten házának edényeit, az ételáldozatot és a tömjént."));
husuperobject.biblemap.put("b16_13_10", new husuperobject(16,13,10,"Megtudtam azt is, hogy a Léviták részeit nem adták meg; ennek miatta kiki az õ mezejére szélede el az Isten házában szolgáló Léviták és énekesek közül."));
husuperobject.biblemap.put("b16_13_11", new husuperobject(16,13,11,"És megfeddém a fejedelmeket, és mondék: Miért hagyatott el az Isten háza? És egybegyûjtvén a [Lévitákat,] helyökre állítám õket;"));
husuperobject.biblemap.put("b16_13_12", new husuperobject(16,13,12,"Az egész Júda pedig meghozá az olajnak, a mustnak és a gabonának tizedét a tárházakba."));
husuperobject.biblemap.put("b16_13_13", new husuperobject(16,13,13,"És felügyelõkké rendelém a tárházak fölé Selemiát, a papot, Sádókot, az írástudót és Pedáját a Léviták közül, és melléjök Hanánt, ki Zakkur fia, ki Mattánia fia vala, mivelhogy híveknek ítéltettek volt és az õ tisztök vala kiosztani atyjokfiainak [részét.]"));
husuperobject.biblemap.put("b16_13_14", new husuperobject(16,13,14,"Emlékezzél meg én rólam én Istenem ezért, és ne engedd, hogy eltöröltessenek az én jótéteményeim, melyeket cselekedtem vala az én Istenem házával és rendtartásaival!"));
husuperobject.biblemap.put("b16_13_15", new husuperobject(16,13,15,"Azon napokban láttam Júdában, hogy sajtót taposnak szombaton és gabonát hoznak be, szamarakra rakván, sõt bort, szõlõt és olajat is és mindenféle terhet behoznak Jeruzsálembe szombat napon, és bizonyságot tevék [ellenök,] a mely napon eleséget árulnak vala."));
husuperobject.biblemap.put("b16_13_16", new husuperobject(16,13,16,"Tírusiak is lakozának [a város]ban, a kik hoznak vala halat és mindenféle árút, melyeket eladnak vala szombat napon Júda fiainak Jeruzsálemben."));
husuperobject.biblemap.put("b16_13_17", new husuperobject(16,13,17,"Annakokáért megfeddém Júda elõljáróit, és mondám nékik: Micsoda gonosz dolog ez, a mit ti cselekesztek, hogy megfertõztetitek a szombatnak napját?"));
husuperobject.biblemap.put("b16_13_18", new husuperobject(16,13,18,"Avagy nem így cselekedtek-é a ti atyáitok, s a mi Istenünk reánk hozá mindezen gonoszt és e városra?! És ti mégis növelitek [Isten ]haragját Izráel fölött, megfertõztetvén a szombatot!"));
husuperobject.biblemap.put("b16_13_19", new husuperobject(16,13,19,"Lõn annakokáért, hogy midõn megárnyékosodtak Jeruzsálem kapui a szombat elõtt, parancsolatomra bezáratának az ajtók, s megparancsolám, hogy meg ne nyissák azokat szombat utánig, annakfelette legényeim közül a kapukhoz rendelék, [mondván:] Nem fog bejõni teher a szombatnak napján!"));
husuperobject.biblemap.put("b16_13_20", new husuperobject(16,13,20,"Annakokáért a kereskedõk és minden árúk árúsai kivül hálának Jeruzsálemen egyszer vagy kétszer;"));
husuperobject.biblemap.put("b16_13_21", new husuperobject(16,13,21,"És bizonyságot tevék ellenök, és mondám nékik: Miért háltok ti e kõfal elõtt? Ha ezt ismételitek, kezet vetek reátok! Az idõtõl fogva nem jöttenek szombaton."));
husuperobject.biblemap.put("b16_13_22", new husuperobject(16,13,22,"És megparancsolám a Lévitáknak, hogy magokat megtisztítsák, s hogy menjenek el és õrizzék a kapukat, hogy megszenteljék a szombatot. Ezért is emlékezzél meg rólam én Istenem és kedvezz nékem, kegyelmességednek nagy volta szerint!"));
husuperobject.biblemap.put("b16_13_23", new husuperobject(16,13,23,"Ugyanazon napokban meglátogatám azokat a zsidókat, kik asdódi, Ammonita és Moábita asszonyokat vettek feleségül."));
husuperobject.biblemap.put("b16_13_24", new husuperobject(16,13,24,"És fiaik felerésze asdódi nyelven beszél vala, és nem tudnak vala beszélni zsidóul, hanem egyik vagy másik nép nyelvén."));
husuperobject.biblemap.put("b16_13_25", new husuperobject(16,13,25,"Annakokáért feddõdém velök, és megátkozám õket, és megverék közülök néhányat, és megtépém õket, és megesketém õket Istenre: Bizony ne adjátok leányaitokat az õ fiaiknak, és ne vegyetek leányaik közül feleséget fiaitoknak és magatoknak."));
husuperobject.biblemap.put("b16_13_26", new husuperobject(16,13,26,"Avagy nem ebben vétkezett-é Salamon Izráel királya? Noha nem volt sok nép között hozzá hasonlatos király, a kit szeret vala az õ Istene és királylyá tette vala õt Isten egész Izráel fölött; õt is bûnre vivék az idegen asszonyok:"));
husuperobject.biblemap.put("b16_13_27", new husuperobject(16,13,27,"És néktek engedjünk-é, hogy cselekedjétek mindezen nagy gonoszságot, vétkezzetek Istenünk ellen, idegen asszonyokat vévén feleségül?"));
husuperobject.biblemap.put("b16_13_28", new husuperobject(16,13,28,"Jójadának (ki Eliásib fõpapnak fia vala) fiai közül is egy veje vala a Horonitbeli Szanballatnak, elûzém azért õt tõlem."));
husuperobject.biblemap.put("b16_13_29", new husuperobject(16,13,29,"Emlékezzél meg õ rólok én Istenem, a papságnak és a papság szövetségének és a Lévitáknak ilyen megfertõztetéséért!"));
husuperobject.biblemap.put("b16_13_30", new husuperobject(16,13,30,"És megtisztítám õket minden idegenektõl és rendtartást szabék a papoknak és a Lévitáknak, kinek-kinek az õ dolgában,"));
husuperobject.biblemap.put("b16_13_31", new husuperobject(16,13,31,"A fa hozására is bizonyos idõkben és az elsõ zsengékre. Emlékezzél meg én Istenem az én javamra!"));

}

}