package du.bible;

public class dubible37 {

public dubible37() {

putmapbible37();

}

private void putmapbible37() {

dusuperobject.biblemap.put("b37_1_1", new dusuperobject(37,1,1,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_2", new dusuperobject(37,1,2,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_3", new dusuperobject(37,1,3,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_4", new dusuperobject(37,1,4,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_5", new dusuperobject(37,1,5,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_6", new dusuperobject(37,1,6,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_7", new dusuperobject(37,1,7,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_8", new dusuperobject(37,1,8,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_9", new dusuperobject(37,1,9,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_10", new dusuperobject(37,1,10,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_11", new dusuperobject(37,1,11,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_12", new dusuperobject(37,1,12,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_13", new dusuperobject(37,1,13,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_14", new dusuperobject(37,1,14,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_1_15", new dusuperobject(37,1,15,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_1", new dusuperobject(37,2,1,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_2", new dusuperobject(37,2,2,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_3", new dusuperobject(37,2,3,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_4", new dusuperobject(37,2,4,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_5", new dusuperobject(37,2,5,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_6", new dusuperobject(37,2,6,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_7", new dusuperobject(37,2,7,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_8", new dusuperobject(37,2,8,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_9", new dusuperobject(37,2,9,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_10", new dusuperobject(37,2,10,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_11", new dusuperobject(37,2,11,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_12", new dusuperobject(37,2,12,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_13", new dusuperobject(37,2,13,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_14", new dusuperobject(37,2,14,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_15", new dusuperobject(37,2,15,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_16", new dusuperobject(37,2,16,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_17", new dusuperobject(37,2,17,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_18", new dusuperobject(37,2,18,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_19", new dusuperobject(37,2,19,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_20", new dusuperobject(37,2,20,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_21", new dusuperobject(37,2,21,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_22", new dusuperobject(37,2,22,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));
dusuperobject.biblemap.put("b37_2_23", new dusuperobject(37,2,23,"Dit is die stad, die opspringt van vreugde, die zeker woont, die in haar hart zegt: Ik ben het, en buiten mij is geen meer; hoe is zij geworden tot woestheid, een rustplaats van het gedierte! Een ieder, die daardoor trekt, zal ze aanfluiten, hij zal zijn hand bewegen."));

}

}