package du.bible;

public class dubible49 {

public dubible49() {

putmapbible49();

}

private void putmapbible49() {

dusuperobject.biblemap.put("b49_1_1", new dusuperobject(49,1,1,"Paulus, een apostel van Jezus Christus, door den wil van God, aan de heiligen, die te Efeze zijn, en gelovigen in Christus Jezus:"));
dusuperobject.biblemap.put("b49_1_2", new dusuperobject(49,1,2,"Genade zij u en vrede van God, onzen Vader, en den Heere Jezus Christus."));
dusuperobject.biblemap.put("b49_1_3", new dusuperobject(49,1,3,"Gezegend zij de God en Vader van onzen Heere Jezus Christus, Die ons gezegend heeft met alle geestelijke zegening in den hemel in Christus."));
dusuperobject.biblemap.put("b49_1_4", new dusuperobject(49,1,4,"Gelijk Hij ons uitverkoren heeft in Hem, voor de grondlegging der wereld, opdat wij zouden heilig en onberispelijk zijn voor Hem in de liefde;"));
dusuperobject.biblemap.put("b49_1_5", new dusuperobject(49,1,5,"Die ons te voren verordineerd heeft tot aanneming tot kinderen, door Jezus Christus, in Zichzelven, naar het welbehagen van Zijn wil."));
dusuperobject.biblemap.put("b49_1_6", new dusuperobject(49,1,6,"Tot prijs der heerlijkheid Zijner genade, door welke Hij ons begenadigd heeft in den Geliefde;"));
dusuperobject.biblemap.put("b49_1_7", new dusuperobject(49,1,7,"In Welken wij hebben de verlossing door Zijn bloed, namelijk de vergeving der misdaden, naar den rijkdom Zijner genade,"));
dusuperobject.biblemap.put("b49_1_8", new dusuperobject(49,1,8,"Met welke Hij overvloedig is geweest over ons in alle wijsheid en voorzichtigheid;"));
dusuperobject.biblemap.put("b49_1_9", new dusuperobject(49,1,9,"Ons bekend gemaakt hebbende de verborgenheid van Zijn wil, naar Zijn welbehagen, hetwelk Hij voorgenomen had in Zichzelven."));
dusuperobject.biblemap.put("b49_1_10", new dusuperobject(49,1,10,"Om in de bedeling van de volheid der tijden, wederom alles tot een te vergaderen in Christus, beide dat in den hemel is, en dat op de aarde is;"));
dusuperobject.biblemap.put("b49_1_11", new dusuperobject(49,1,11,"In Hem, in Welken wij ook een erfdeel geworden zijn, wij, die te voren verordineerd waren naar het voornemen Desgenen, Die alle dingen werkt naar den raad van Zijn wil;"));
dusuperobject.biblemap.put("b49_1_12", new dusuperobject(49,1,12,"Opdat wij zouden zijn tot prijs Zijner heerlijkheid, wij, die eerst in Christus gehoopt hebben."));
dusuperobject.biblemap.put("b49_1_13", new dusuperobject(49,1,13,"In Welken ook gij zijt, nadat gij het woord der waarheid, namelijk het Evangelie uwer zaligheid gehoord hebt; in Welken gij ook, nadat gij geloofd hebt, zijt verzegeld geworden met den Heiligen Geest der belofte;"));
dusuperobject.biblemap.put("b49_1_14", new dusuperobject(49,1,14,"Die het onderpand is van onze erfenis, tot de verkregene verlossing, tot prijs Zijner heerlijkheid."));
dusuperobject.biblemap.put("b49_1_15", new dusuperobject(49,1,15,"Daarom ook ik, gehoord hebbende het geloof in den Heere Jezus, dat onder u is, en de liefde tot al de heiligen,"));
dusuperobject.biblemap.put("b49_1_16", new dusuperobject(49,1,16,"Houde niet op voor u te danken, gedenkende uwer in mijn gebeden;"));
dusuperobject.biblemap.put("b49_1_17", new dusuperobject(49,1,17,"Opdat de God van onzen Heere Jezus Christus, de Vader der heerlijkheid, u geve den Geest der wijsheid en der openbaring in Zijn kennis;"));
dusuperobject.biblemap.put("b49_1_18", new dusuperobject(49,1,18,"Namelijk verlichte ogen uws verstands, opdat gij moogt weten, welke zij de hoop van Zijn roeping, en welke de rijkdom zij der heerlijkheid van Zijn erfenis in de heiligen;"));
dusuperobject.biblemap.put("b49_1_19", new dusuperobject(49,1,19,"En welke de uitnemende grootheid Zijner kracht zij aan ons, die geloven, naar de werking der sterkte Zijner macht,"));
dusuperobject.biblemap.put("b49_1_20", new dusuperobject(49,1,20,"Die Hij gewrocht heeft in Christus, als Hij Hem uit de doden heeft opgewekt; en heeft Hem gezet tot Zijn rechter hand in den hemel;"));
dusuperobject.biblemap.put("b49_1_21", new dusuperobject(49,1,21,"Verre boven alle overheid, en macht, en kracht, en heerschappij, en allen naam, die genaamd wordt, niet alleen in deze wereld, maar ook in de toekomende;"));
dusuperobject.biblemap.put("b49_1_22", new dusuperobject(49,1,22,"En heeft alle dingen Zijn voeten onderworpen, en heeft Hem der Gemeente gegeven tot een Hoofd boven alle dingen;"));
dusuperobject.biblemap.put("b49_1_23", new dusuperobject(49,1,23,"Welke Zijn lichaam is, en de vervulling Desgenen, Die alles in allen vervult."));
dusuperobject.biblemap.put("b49_2_1", new dusuperobject(49,2,1,"En u heeft Hij mede levend gemaakt, daar gij dood waart door de misdaden en de zonden;"));
dusuperobject.biblemap.put("b49_2_2", new dusuperobject(49,2,2,"In welke gij eertijds gewandeld hebt, naar de eeuw dezer wereld, naar den overste van de macht der lucht, van den geest, die nu werkt in de kinderen der ongehoorzaamheid;"));
dusuperobject.biblemap.put("b49_2_3", new dusuperobject(49,2,3,"Onder dewelke ook wij allen eertijds verkeerd hebben in de begeerlijkheden onzes vleses, doende den wil des vleses en der gedachten; en wij waren van nature kinderen des toorns, gelijk ook de anderen;"));
dusuperobject.biblemap.put("b49_2_4", new dusuperobject(49,2,4,"Maar God, Die rijk is in barmhartigheid door Zijn grote liefde, waarmede Hij ons liefgehad heeft,"));
dusuperobject.biblemap.put("b49_2_5", new dusuperobject(49,2,5,"Ook toen wij dood waren door de misdaden, heeft ons levend gemaakt met Christus; (uit genade zijt gij zalig geworden)"));
dusuperobject.biblemap.put("b49_2_6", new dusuperobject(49,2,6,"En heeft ons mede opgewekt, en heeft ons mede gezet in den hemel in Christus Jezus;"));
dusuperobject.biblemap.put("b49_2_7", new dusuperobject(49,2,7,"Opdat Hij zou betonen in de toekomende eeuwen den uitnemenden rijkdom Zijner genade, door de goedertierenheid over ons in Christus Jezus."));
dusuperobject.biblemap.put("b49_2_8", new dusuperobject(49,2,8,"Want uit genade zijt gij zalig geworden door het geloof; en dat niet uit u, het is Gods gave;"));
dusuperobject.biblemap.put("b49_2_9", new dusuperobject(49,2,9,"Niet uit de werken, opdat niemand roeme."));
dusuperobject.biblemap.put("b49_2_10", new dusuperobject(49,2,10,"Want wij zijn Zijn maaksel, geschapen in Christus Jezus tot goede werken, welke God voorbereid heeft, opdat wij in dezelve zouden wandelen."));
dusuperobject.biblemap.put("b49_2_11", new dusuperobject(49,2,11,"Daarom gedenkt, dat gij, die eertijds heidenen waart in het vlees, en die voorhuid genaamd werdt van degenen, die genaamd zijn besnijdenis in het vlees, die met handen geschiedt;"));
dusuperobject.biblemap.put("b49_2_12", new dusuperobject(49,2,12,"Dat gij in dien tijd waart zonder Christus, vervreemd van het burgerschap Israels, en vreemdelingen van de verbonden der belofte, geen hoop hebbende, en zonder God in de wereld."));
dusuperobject.biblemap.put("b49_2_13", new dusuperobject(49,2,13,"Maar nu in Christus Jezus, zijt gij, die eertijds verre waart, nabij geworden door het bloed van Christus."));
dusuperobject.biblemap.put("b49_2_14", new dusuperobject(49,2,14,"Want Hij is onze vrede, Die deze beiden een gemaakt heeft, en den middelmuur des afscheidsels gebroken hebbende,"));
dusuperobject.biblemap.put("b49_2_15", new dusuperobject(49,2,15,"Heeft Hij de vijandschap in Zijn vlees te niet gemaakt, namelijk de wet der geboden in inzettingen bestaande; opdat Hij die twee in Zichzelven tot een nieuwen mens zou scheppen, vrede makende;"));
dusuperobject.biblemap.put("b49_2_16", new dusuperobject(49,2,16,"En opdat Hij die beiden met God in een lichaam zou verzoenen door het kruis, de vijandschap aan hetzelve gedood hebbende."));
dusuperobject.biblemap.put("b49_2_17", new dusuperobject(49,2,17,"En komende, heeft Hij door het Evangelie vrede verkondigd u, die verre waart, en dien, die nabij waren."));
dusuperobject.biblemap.put("b49_2_18", new dusuperobject(49,2,18,"Want door Hem hebben wij beiden den toegang door een Geest tot den Vader."));
dusuperobject.biblemap.put("b49_2_19", new dusuperobject(49,2,19,"Zo zijt gij dan niet meer vreemdelingen en bijwoners, maar medeburgers der heiligen, en huisgenoten Gods;"));
dusuperobject.biblemap.put("b49_2_20", new dusuperobject(49,2,20,"Gebouwd op het fondament der apostelen en profeten, waarvan Jezus Christus is de uiterste Hoeksteen;"));
dusuperobject.biblemap.put("b49_2_21", new dusuperobject(49,2,21,"Op Welken het gehele gebouw, bekwamelijk samengevoegd zijnde, opwast tot een heiligen tempel in den Heere;"));
dusuperobject.biblemap.put("b49_2_22", new dusuperobject(49,2,22,"Op Welken ook gij mede gebouwd wordt tot een woonstede Gods in den Geest."));
dusuperobject.biblemap.put("b49_3_1", new dusuperobject(49,3,1,"Om deze oorzaak ben ik Paulus de gevangene van Christus Jezus, voor u, die heidenen zijt."));
dusuperobject.biblemap.put("b49_3_2", new dusuperobject(49,3,2,"Indien gij maar gehoord hebt van de bedeling der genade Gods, die mij gegeven is aan u;"));
dusuperobject.biblemap.put("b49_3_3", new dusuperobject(49,3,3,"Dat Hij mij door openbaring heeft bekend gemaakt deze verborgenheid, (gelijk ik met weinige woorden te voren geschreven heb;"));
dusuperobject.biblemap.put("b49_3_4", new dusuperobject(49,3,4,"Waaraan gij, dit lezende, kunt bemerken mijn wetenschap, in deze verborgenheid van Christus),"));
dusuperobject.biblemap.put("b49_3_5", new dusuperobject(49,3,5,"Welke in andere eeuwen den kinderen der mensen niet is bekend gemaakt, gelijk zij nu is geopenbaard aan Zijn heilige apostelen en profeten, door den Geest;"));
dusuperobject.biblemap.put("b49_3_6", new dusuperobject(49,3,6,"Namelijk dat de heidenen zijn medeerfgenamen, en van hetzelfde lichaam, en mededeelgenoten Zijner belofte in Christus, door het Evangelie;"));
dusuperobject.biblemap.put("b49_3_7", new dusuperobject(49,3,7,"Waarvan ik een dienaar geworden ben, naar de gave der genade Gods, die mij gegeven is, naar de werking Zijner kracht."));
dusuperobject.biblemap.put("b49_3_8", new dusuperobject(49,3,8,"Mij, den allerminste van al de heiligen, is deze genade gegeven, om onder de heidenen door het Evangelie te verkondigen den onnaspeurlijken rijkdom van Christus,"));
dusuperobject.biblemap.put("b49_3_9", new dusuperobject(49,3,9,"En allen te verlichten, dat zij mogen verstaan, welke de gemeenschap der verborgenheid zij, die van alle eeuwen verborgen is geweest in God, Welke alle dingen geschapen heeft door Jezus Christus;"));
dusuperobject.biblemap.put("b49_3_10", new dusuperobject(49,3,10,"Opdat nu, door de Gemeente, bekend gemaakt worde aan de overheden en de machten in den hemel de veelvuldige wijsheid Gods;"));
dusuperobject.biblemap.put("b49_3_11", new dusuperobject(49,3,11,"Naar het eeuwig voornemen, dat Hij gemaakt heeft in Christus Jezus, onzen Heere;"));
dusuperobject.biblemap.put("b49_3_12", new dusuperobject(49,3,12,"In Denwelken wij hebben de vrijmoedigheid, en den toegang met vertrouwen, door het geloof aan Hem."));
dusuperobject.biblemap.put("b49_3_13", new dusuperobject(49,3,13,"Daarom bid ik, dat gij niet vertraagt in mijn verdrukkingen voor u, hetwelke is uw heerlijkheid."));
dusuperobject.biblemap.put("b49_3_14", new dusuperobject(49,3,14,"Om deze oorzaak buig ik mijn knieen tot den Vader van onzen Heere Jezus Christus,"));
dusuperobject.biblemap.put("b49_3_15", new dusuperobject(49,3,15,"Uit Welken al het geslacht in de hemelen en op de aarde genoemd wordt,"));
dusuperobject.biblemap.put("b49_3_16", new dusuperobject(49,3,16,"Opdat Hij u geve, naar den rijkdom Zijner heerlijkheid, met kracht versterkt te worden door Zijn Geest in den inwendigen mens;"));
dusuperobject.biblemap.put("b49_3_17", new dusuperobject(49,3,17,"Opdat Christus door het geloof in uw harten wone, en gij in de liefde geworteld en gegrond zijt;"));
dusuperobject.biblemap.put("b49_3_18", new dusuperobject(49,3,18,"Opdat gij ten volle kondet begrijpen met al de heiligen, welke de breedte, en lengte, en diepte, en hoogte zij,"));
dusuperobject.biblemap.put("b49_3_19", new dusuperobject(49,3,19,"En bekennen de liefde van Christus, die de kennis te boven gaat, opdat gij vervuld wordt tot al de volheid Gods."));
dusuperobject.biblemap.put("b49_3_20", new dusuperobject(49,3,20,"Hem nu, Die machtig is meer dan overvloediglijk te doen, boven al wat wij bidden of denken, naar de kracht, die in ons werkt,"));
dusuperobject.biblemap.put("b49_3_21", new dusuperobject(49,3,21,"Hem, zeg ik, zij de heerlijkheid in de Gemeente, door Christus Jezus, in alle geslachten, tot alle eeuwigheid. Amen."));
dusuperobject.biblemap.put("b49_4_1", new dusuperobject(49,4,1,"Zo bid ik u dan, ik, de gevangene in den Heere, dat gij wandelt waardiglijk der roeping, met welke gij geroepen zijt;"));
dusuperobject.biblemap.put("b49_4_2", new dusuperobject(49,4,2,"Met alle ootmoedigheid en zachtmoedigheid, met lankmoedigheid, verdragende elkander in liefde;"));
dusuperobject.biblemap.put("b49_4_3", new dusuperobject(49,4,3,"U benaarstigende te behouden de enigheid des Geestes door den band des vredes."));
dusuperobject.biblemap.put("b49_4_4", new dusuperobject(49,4,4,"Een lichaam is het, en een Geest, gelijkerwijs gij ook geroepen zijt tot een hoop uwer roeping;"));
dusuperobject.biblemap.put("b49_4_5", new dusuperobject(49,4,5,"Een Heere, een geloof, een doop,"));
dusuperobject.biblemap.put("b49_4_6", new dusuperobject(49,4,6,"Een God en Vader van allen, Die daar is boven allen, en door allen, en in u allen."));
dusuperobject.biblemap.put("b49_4_7", new dusuperobject(49,4,7,"Maar aan elkeen van ons is de genade gegeven, naar de maat der gave van Christus."));
dusuperobject.biblemap.put("b49_4_8", new dusuperobject(49,4,8,"Daarom zegt Hij: Als Hij opgevaren is in de hoogte, heeft Hij de gevangenis gevangen genomen, en heeft den mensen gaven gegeven."));
dusuperobject.biblemap.put("b49_4_9", new dusuperobject(49,4,9,"Nu dit: Hij is opgevaren; wat is het, dan dat Hij ook eerst is nedergedaald in de nederste delen der aarde?"));
dusuperobject.biblemap.put("b49_4_10", new dusuperobject(49,4,10,"Die nedergedaald is, is Dezelfde ook, Die opgevaren is verre boven al de hemelen, opdat Hij alle dingen vervullen zou."));
dusuperobject.biblemap.put("b49_4_11", new dusuperobject(49,4,11,"En Dezelfde heeft gegeven sommigen tot apostelen, en sommigen tot profeten, en sommigen tot evangelisten, en sommigen tot herders en leraars;"));
dusuperobject.biblemap.put("b49_4_12", new dusuperobject(49,4,12,"Tot de volmaking der heiligen, tot het werk der bediening, tot opbouwing des lichaams van Christus;"));
dusuperobject.biblemap.put("b49_4_13", new dusuperobject(49,4,13,"Totdat wij allen zullen komen tot de enigheid des geloofs en der kennis van den Zoon Gods, tot een volkomen man, tot de mate van de grootte der volheid van Christus;"));
dusuperobject.biblemap.put("b49_4_14", new dusuperobject(49,4,14,"Opdat wij niet meer kinderen zouden zijn, die als de vloed bewogen en omgevoerd worden met allen wind der leer, door de bedriegerij der mensen, door arglistigheid, om listiglijk tot dwaling te brengen;"));
dusuperobject.biblemap.put("b49_4_15", new dusuperobject(49,4,15,"Maar de waarheid betrachtende in liefde, alleszins zouden opwassen in Hem, Die het Hoofd is, namelijk Christus;"));
dusuperobject.biblemap.put("b49_4_16", new dusuperobject(49,4,16,"Uit Welken het gehele lichaam bekwamelijk samengevoegd en samen vastgemaakt zijnde, door alle voegselen der toebrenging, naar de werking van een iegelijk deel in zijn maat, den wasdom des lichaams bekomt, tot zijns zelfs opbouwing in de liefde."));
dusuperobject.biblemap.put("b49_4_17", new dusuperobject(49,4,17,"Ik zeg dan dit, en betuig het in den Heere, dat gij niet meer wandelt, gelijk als de andere heidenen wandelen in de ijdelheid huns gemoeds."));
dusuperobject.biblemap.put("b49_4_18", new dusuperobject(49,4,18,"Verduisterd in het verstand, vervreemd zijnde van het leven Gods, door de onwetendheid, die in hen is, door de verharding huns harten;"));
dusuperobject.biblemap.put("b49_4_19", new dusuperobject(49,4,19,"Welke, ongevoelig geworden zijnde, zichzelven hebben overgegeven tot ontuchtigheid, om alle onreinigheid gieriglijk te bedrijven."));
dusuperobject.biblemap.put("b49_4_20", new dusuperobject(49,4,20,"Doch gij hebt Christus alzo niet geleerd;"));
dusuperobject.biblemap.put("b49_4_21", new dusuperobject(49,4,21,"Indien gij naar Hem gehoord hebt, en door Hem geleerd zijt, gelijk de waarheid in Jezus is;"));
dusuperobject.biblemap.put("b49_4_22", new dusuperobject(49,4,22,"Te weten dat gij zoudt afleggen, aangaande de vorige wandeling, den ouden mens, die verdorven wordt door de begeerlijkheden der verleiding;"));
dusuperobject.biblemap.put("b49_4_23", new dusuperobject(49,4,23,"En dat gij zoudt vernieuwd worden in den geest uws gemoeds,"));
dusuperobject.biblemap.put("b49_4_24", new dusuperobject(49,4,24,"En den nieuwen mens aandoen, die naar God geschapen is in ware rechtvaardigheid en heiligheid."));
dusuperobject.biblemap.put("b49_4_25", new dusuperobject(49,4,25,"Daarom legt af de leugen, en spreekt de waarheid, een iegelijk met zijn naaste; want wij zijn elkanders leden."));
dusuperobject.biblemap.put("b49_4_26", new dusuperobject(49,4,26,"Wordt toornig, en zondigt niet; de zon ga niet onder over uw toornigheid;"));
dusuperobject.biblemap.put("b49_4_27", new dusuperobject(49,4,27,"En geeft den duivel geen plaats."));
dusuperobject.biblemap.put("b49_4_28", new dusuperobject(49,4,28,"Die gestolen heeft, stele niet meer, maar arbeide liever, werkende dat goed is met de handen, opdat hij hebbe mede te delen dengene, die nood heeft."));
dusuperobject.biblemap.put("b49_4_29", new dusuperobject(49,4,29,"Geen vuile rede ga uit uw mond, maar zo er enige goede rede is tot nuttige stichting, opdat zij genade geve dien, die dezelve horen."));
dusuperobject.biblemap.put("b49_4_30", new dusuperobject(49,4,30,"En bedroeft den Heiligen Geest Gods niet, door Welken gij verzegeld zijt tot den dag der verlossing."));
dusuperobject.biblemap.put("b49_4_31", new dusuperobject(49,4,31,"Alle bitterheid, en toornigheid, en gramschap, en geroep, en lastering zij van u geweerd, met alle boosheid;"));
dusuperobject.biblemap.put("b49_4_32", new dusuperobject(49,4,32,"Maar zijt jegens elkander goedertieren, barmhartig, vergevende elkander, gelijkerwijs ook God in Christus ulieden vergeven heeft."));
dusuperobject.biblemap.put("b49_5_1", new dusuperobject(49,5,1,"Zijt dan navolgers Gods, als geliefde kinderen;"));
dusuperobject.biblemap.put("b49_5_2", new dusuperobject(49,5,2,"En wandelt in de liefde, gelijkerwijs ook Christus ons liefgehad heeft, en Zichzelven voor ons heeft overgegeven tot een offerande en een slachtoffer, Gode tot een welriekenden reuk."));
dusuperobject.biblemap.put("b49_5_3", new dusuperobject(49,5,3,"Maar hoererij en alle onreinigheid, of gierigheid, laat ook onder u niet genoemd worden, gelijkerwijs het den heiligen betaamt,"));
dusuperobject.biblemap.put("b49_5_4", new dusuperobject(49,5,4,"Noch oneerbaarheid, noch zot geklap, of gekkernij, welke niet betamen; maar veelmeer dankzegging."));
dusuperobject.biblemap.put("b49_5_5", new dusuperobject(49,5,5,"Want dit weet gij, dat geen hoereerder, of onreine, of gierigaard, die een afgodendienaar is, erfenis heeft in het Koninkrijk van Christus en van God."));
dusuperobject.biblemap.put("b49_5_6", new dusuperobject(49,5,6,"Dat u niemand verleide met ijdele woorden; want om deze dingen komt de toorn Gods over de kinderen der ongehoorzaamheid."));
dusuperobject.biblemap.put("b49_5_7", new dusuperobject(49,5,7,"Zo zijt dan hun medegenoten niet."));
dusuperobject.biblemap.put("b49_5_8", new dusuperobject(49,5,8,"Want gij waart eertijds duisternis, maar nu zijt gij licht in den Heere; wandelt als kinderen des lichts."));
dusuperobject.biblemap.put("b49_5_9", new dusuperobject(49,5,9,"(Want de vrucht des Geestes is in alle goedigheid, en rechtvaardigheid, en waarheid),"));
dusuperobject.biblemap.put("b49_5_10", new dusuperobject(49,5,10,"Beproevende wat den Heere welbehagelijk zij."));
dusuperobject.biblemap.put("b49_5_11", new dusuperobject(49,5,11,"En hebt geen gemeenschap met de onvruchtbare werken der duisternis, maar bestraft ze ook veeleer."));
dusuperobject.biblemap.put("b49_5_12", new dusuperobject(49,5,12,"Want hetgeen heimelijk van hen geschiedt, is schandelijk ook te zeggen."));
dusuperobject.biblemap.put("b49_5_13", new dusuperobject(49,5,13,"Maar al deze dingen, van het licht bestraft zijnde, worden openbaar; want al wat openbaar maakt, is licht."));
dusuperobject.biblemap.put("b49_5_14", new dusuperobject(49,5,14,"Daarom zegt Hij: Ontwaakt, gij, die slaapt, en staat op uit de doden; en Christus zal over u lichten."));
dusuperobject.biblemap.put("b49_5_15", new dusuperobject(49,5,15,"Ziet dan, hoe gij voorzichtiglijk wandelt, niet als onwijzen, maar als wijzen."));
dusuperobject.biblemap.put("b49_5_16", new dusuperobject(49,5,16,"Den tijd uitkopende, dewijl de dagen boos zijn."));
dusuperobject.biblemap.put("b49_5_17", new dusuperobject(49,5,17,"Daarom zijt niet onverstandig, maar verstaat, welke de wil des Heeren zij."));
dusuperobject.biblemap.put("b49_5_18", new dusuperobject(49,5,18,"En wordt niet dronken in wijn, waarin overdaad is, maar wordt vervuld met den Geest;"));
dusuperobject.biblemap.put("b49_5_19", new dusuperobject(49,5,19,"Sprekende onder elkander met psalmen, en lofzangen, en geestelijke liederen, zingende en psalmende den Heere in uw hart;"));
dusuperobject.biblemap.put("b49_5_20", new dusuperobject(49,5,20,"Dankende te allen tijd over alle dingen God en den Vader, in den Naam van onzen Heere Jezus Christus;"));
dusuperobject.biblemap.put("b49_5_21", new dusuperobject(49,5,21,"Elkander onderdanig zijnde in de vreze Gods."));
dusuperobject.biblemap.put("b49_5_22", new dusuperobject(49,5,22,"Gij vrouwen, weest aan uw eigen mannen onderdanig, gelijk aan den Heere;"));
dusuperobject.biblemap.put("b49_5_23", new dusuperobject(49,5,23,"Want de man is het hoofd der vrouw, gelijk ook Christus het Hoofd der Gemeente is; en Hij is de Behouder des lichaams."));
dusuperobject.biblemap.put("b49_5_24", new dusuperobject(49,5,24,"Daarom, gelijk de Gemeente aan Christus onderdanig is, alzo ook de vrouwen aan haar eigen mannen in alles."));
dusuperobject.biblemap.put("b49_5_25", new dusuperobject(49,5,25,"Gij mannen, hebt uw eigen vrouwen lief, gelijk ook Christus de Gemeente liefgehad heeft, en Zichzelven voor haar heeft overgegeven;"));
dusuperobject.biblemap.put("b49_5_26", new dusuperobject(49,5,26,"Opdat Hij haar heiligen zou, haar gereinigd hebbende met het bad des waters door het Woord;"));
dusuperobject.biblemap.put("b49_5_27", new dusuperobject(49,5,27,"Opdat Hij haar Zichzelven heerlijk zou voorstellen, een Gemeente, die geen vlek of rimpel heeft, of iets dergelijks, maar dat zij zou heilig zijn en onberispelijk."));
dusuperobject.biblemap.put("b49_5_28", new dusuperobject(49,5,28,"Alzo zijn de mannen schuldig hun eigen vrouwen lief te hebben, gelijk hun eigen lichamen. Die zijn eigen vrouw liefheeft, die heeft zichzelven lief."));
dusuperobject.biblemap.put("b49_5_29", new dusuperobject(49,5,29,"Want niemand heeft ooit zijn eigen vlees gehaat, maar hij voedt het, en onderhoudt het, gelijkerwijs ook de Heere de Gemeente."));
dusuperobject.biblemap.put("b49_5_30", new dusuperobject(49,5,30,"Want wij zijn leden Zijns lichaams, van Zijn vlees en van Zijn benen."));
dusuperobject.biblemap.put("b49_5_31", new dusuperobject(49,5,31,"Daarom zal een mens zijn vader en moeder verlaten, en zal zijn vrouw aanhangen; en zij twee zullen tot een vlees wezen."));
dusuperobject.biblemap.put("b49_5_32", new dusuperobject(49,5,32,"Deze verborgenheid is groot; doch ik zeg dit, ziende op Christus en op de Gemeente."));
dusuperobject.biblemap.put("b49_5_33", new dusuperobject(49,5,33,"Zo dan ook gijlieden, elk in het bijzonder, een iegelijk hebbe zijn eigen vrouw, alzo lief als zichzelven; en de vrouw zie, dat zij den man vreze."));
dusuperobject.biblemap.put("b49_6_1", new dusuperobject(49,6,1,"Gij kinderen, zijt uw ouderen gehoorzaam in den Heere; want dat is recht."));
dusuperobject.biblemap.put("b49_6_2", new dusuperobject(49,6,2,"Eert uw vader en moeder (hetwelk het eerste gebod is met een belofte),"));
dusuperobject.biblemap.put("b49_6_3", new dusuperobject(49,6,3,"Opdat het u welga, en dat gij lang leeft op de aarde."));
dusuperobject.biblemap.put("b49_6_4", new dusuperobject(49,6,4,"En gij vaders, verwekt uw kinderen niet tot toorn, maar voedt hen op in de lering en vermaning des Heeren."));
dusuperobject.biblemap.put("b49_6_5", new dusuperobject(49,6,5,"Gij dienstknechten, zijt gehoorzaam uw heren naar het vlees, met vreze en beven, in eenvoudigheid uws harten, gelijk als aan Christus;"));
dusuperobject.biblemap.put("b49_6_6", new dusuperobject(49,6,6,"Niet naar ogendienst, als mensenbehagers, maar als dienstknechten van Christus, doende den wil van God van harte;"));
dusuperobject.biblemap.put("b49_6_7", new dusuperobject(49,6,7,"Dienende met goedwilligheid den Heere, en niet de mensen;"));
dusuperobject.biblemap.put("b49_6_8", new dusuperobject(49,6,8,"Wetende, dat zo wat goed een iegelijk gedaan zal hebben, hij datzelve van den Heere zal ontvangen, hetzij dienstknecht, hetzij vrije."));
dusuperobject.biblemap.put("b49_6_9", new dusuperobject(49,6,9,"En gij heren, doet hetzelfde bij hen, nalatende de dreiging; als die weet, dat ook uw eigen Heere in de hemelen is, en dat geen aanneming des persoons bij Hem is."));
dusuperobject.biblemap.put("b49_6_10", new dusuperobject(49,6,10,"Voorts, mijn broeders, wordt krachtig in den Heere, en in de sterkte Zijner macht."));
dusuperobject.biblemap.put("b49_6_11", new dusuperobject(49,6,11,"Doet aan de gehele wapenrusting Gods, opdat gij kunt staan tegen de listige omleidingen des duivels."));
dusuperobject.biblemap.put("b49_6_12", new dusuperobject(49,6,12,"Want wij hebben den strijd niet tegen vlees en bloed, maar tegen de overheden, tegen de machten, tegen de geweldhebbers der wereld, der duisternis dezer eeuw, tegen de geestelijke boosheden in de lucht."));
dusuperobject.biblemap.put("b49_6_13", new dusuperobject(49,6,13,"Daarom neemt aan de gehele wapenrusting Gods, opdat gij kunt wederstaan in den bozen dag, en alles verricht hebbende, staande blijven."));
dusuperobject.biblemap.put("b49_6_14", new dusuperobject(49,6,14,"Staat dan, uw lenden omgord hebbende met de waarheid, en aangedaan hebbende het borstwapen der gerechtigheid;"));
dusuperobject.biblemap.put("b49_6_15", new dusuperobject(49,6,15,"En de voeten geschoeid hebbende met bereidheid van het Evangelie des vredes;"));
dusuperobject.biblemap.put("b49_6_16", new dusuperobject(49,6,16,"Bovenal aangenomen hebbende het schild des geloofs, met hetwelk gij al de vurige pijlen des bozen zult kunnen uitblussen."));
dusuperobject.biblemap.put("b49_6_17", new dusuperobject(49,6,17,"En neemt den helm der zaligheid, en het zwaard des Geestes, hetwelk is Gods Woord."));
dusuperobject.biblemap.put("b49_6_18", new dusuperobject(49,6,18,"Met alle bidding en smeking, biddende te allen tijd in den Geest, en tot hetzelve wakende met alle gedurigheid en smeking voor al de heiligen;"));
dusuperobject.biblemap.put("b49_6_19", new dusuperobject(49,6,19,"En voor mij, opdat mij het Woord gegeven worde in de opening mijns monds met vrijmoedigheid, om de verborgenheid van het Evangelie bekend te maken;"));
dusuperobject.biblemap.put("b49_6_20", new dusuperobject(49,6,20,"Waarover ik een gezant ben in een keten, opdat ik in hetzelve vrijmoediglijk moge spreken, gelijk mij betaamt te spreken."));
dusuperobject.biblemap.put("b49_6_21", new dusuperobject(49,6,21,"En opdat ook gij moogt weten hetgeen mij aangaat; en wat ik doe, dat alles zal u Tychikus, de geliefde broeder en getrouwe dienaar in den Heere, bekend maken;"));
dusuperobject.biblemap.put("b49_6_22", new dusuperobject(49,6,22,"Denwelken ik tot datzelfde einde tot u gezonden heb, opdat gij onze zaken zoudt weten, en hij uw harten zou vertroosten."));
dusuperobject.biblemap.put("b49_6_23", new dusuperobject(49,6,23,"Vrede zij den broederen, en liefde met geloof, van God den Vader, en den Heere Jezus Christus."));
dusuperobject.biblemap.put("b49_6_24", new dusuperobject(49,6,24,"De genade zij met al degenen, die onzen Heere Jezus Christus liefhebben in onverderfelijkheid. Amen."));

}

}