package du.bible;

public class dubible25 {

public dubible25() {

putmapbible25();

}

private void putmapbible25() {

dusuperobject.biblemap.put("b25_1_1", new dusuperobject(25,1,1,"Aleph. Hoe zit die stad zo eenzaam, die vol volks was, zij is als een weduwe geworden, zij, die groot was onder de heidenen, een vorstin onder de landschappen, is cijnsbaar geworden."));
dusuperobject.biblemap.put("b25_1_2", new dusuperobject(25,1,2,"Beth. Zij weent steeds des nachts, en haar tranen lopen over haar kinnebakken; zij heeft geen trooster onder al haar liefhebbers; al haar vrienden hebben trouwelooslijk met haar gehandeld, zij zijn haar tot vijanden geworden."));
dusuperobject.biblemap.put("b25_1_3", new dusuperobject(25,1,3,"Gimel. Juda is in gevangenis gegaan vanwege de ellende, en vanwege de veelheid der dienstbaarheid; zij woont onder de heidenen, zij vindt geen rust; al haar vervolgers achterhalen ze tussen de engten."));
dusuperobject.biblemap.put("b25_1_4", new dusuperobject(25,1,4,"Daleth. De wegen Sions treuren, omdat niemand op het feest komt; al haar poorten zijn woest, haar priesters zuchten: haar jonkvrouwen zijn bedroefd, en zij zelve is in bitterheid."));
dusuperobject.biblemap.put("b25_1_5", new dusuperobject(25,1,5,"He. Haar tegenpartijders zijn ten hoofd geworden, haar vijanden zijn gerust; omdat haar de HEERE bedroefd heeft, vanwege de veelheid harer overtredingen; haar kinderkens gaan henen in de gevangenis voor het aangezicht des tegenpartijders."));
dusuperobject.biblemap.put("b25_1_6", new dusuperobject(25,1,6,"Vau. En van de dochter Sions is al haar sieraad weggegaan; haar vorsten zijn als de herten, die geen weide vinden, en zij gaan krachteloos henen voor het aangezicht des vervolgers."));
dusuperobject.biblemap.put("b25_1_7", new dusuperobject(25,1,7,"Zain. Jeruzalem is, in de dagen harer ellende en harer veelvuldige ballingschap, indachtig aan al haar gewenste dingen, die zij van oude dagen af gehad heeft; dewijl haar volk door de hand des tegenpartijders valt, en zij geen helper heeft; de tegenpartijders zien haar aan, zij spotten met haar rustdagen."));
dusuperobject.biblemap.put("b25_1_8", new dusuperobject(25,1,8,"Cheth. Jeruzalem heeft zwaarlijk gezondigd, daarom is zij als een afgezonderde vrouw geworden; allen, die haar eerden, achten haar onwaard, dewijl zij haar naaktheid gezien hebben; zij zucht ook, en zij is achterwaarts gekeerd."));
dusuperobject.biblemap.put("b25_1_9", new dusuperobject(25,1,9,"Teth. Haar onreinheid is in haar zomen, zij heeft niet gedacht aan haar uiterste, daarom is zij wonderbaarlijk omlaag gedaald; zij heeft geen trooster. HEERE, zie mijn ellende aan, want de vijand maakt zich groot."));
dusuperobject.biblemap.put("b25_1_10", new dusuperobject(25,1,10,"Jod. De tegenpartijder heeft zijn hand aan al haar gewenste dingen uitgebreid; immers heeft zij aangezien, dat de heidenen in haar heiligdom gingen, waarvan Gij geboden hadt, dat zij in Uw gemeente niet komen zouden."));
dusuperobject.biblemap.put("b25_1_11", new dusuperobject(25,1,11,"Caph. Al haar volk zucht, brood zoekende, zij hebben hun gewenste dingen voor spijs gegeven, om de ziel te verkwikken. Zie, HEERE, en aanschouw, dat ik onwaard geworden ben."));
dusuperobject.biblemap.put("b25_1_12", new dusuperobject(25,1,12,"Lamed. Gaat het ulieden niet aan, gij allen, die over weg gaat? Schouwt het aan en ziet, of er een smart zij gelijk mijn smart, die mij aangedaan is, waarmede de HEERE mij bedroefd heeft ten dage der hittigheid Zijns toorns."));
dusuperobject.biblemap.put("b25_1_13", new dusuperobject(25,1,13,"Mem. Van de hoogte heeft Hij een vuur in mijn beenderen gezonden, waarover Hij geheerst heeft; Hij heeft voor mijn voeten een net uitgebreid, Hij heeft mij achterwaarts doen keren, Hij heeft mij woest en ziek gemaakt den gansen dag."));
dusuperobject.biblemap.put("b25_1_14", new dusuperobject(25,1,14,"Nun. Het juk mijner overtredingen is aangebonden door Zijn hand, zij zijn samengevlochten, zij zijn op mijn hals geklommen; Hij heeft mijn kracht doen vervallen; de HEERE heeft mij in hun handen gegeven, ik kan niet opstaan."));
dusuperobject.biblemap.put("b25_1_15", new dusuperobject(25,1,15,"Samech. De Heere heeft al mijn sterken in het midden van mij vertreden; Hij heeft een bijeenkomst over mij uitgeroepen, om mijn jongelingen te verbreken; de Heere heeft de wijnpers der jonkvrouw, der dochter van Juda, getreden."));
dusuperobject.biblemap.put("b25_1_16", new dusuperobject(25,1,16,"Ain. Om dezer dingen wille ween ik; mijn oog, mijn oog vliet af van water, omdat de trooster, die mijn ziel zou verkwikken, verre van mij is; mijn kinderen zijn verwoest, omdat de vijand de overhand heeft."));
dusuperobject.biblemap.put("b25_1_17", new dusuperobject(25,1,17,"Pe. Sion breidt haar handen uit, daar is geen trooster voor haar; de HEERE heeft van Jakob geboden, dat die rondom hem zijn, zijn tegenpartijders zouden zijn; Jeruzalem is als een afgezonderde vrouw onder hen."));
dusuperobject.biblemap.put("b25_1_18", new dusuperobject(25,1,18,"Tsade. De HEERE is rechtvaardig, want ik ben Zijn mond wederspannig geweest; hoort toch, alle gij volken, en ziet mijn smart; mijn jonkvrouwen en mijn jongelingen zijn in de gevangenis gegaan."));
dusuperobject.biblemap.put("b25_1_19", new dusuperobject(25,1,19,"Koph. Ik riep tot mijn liefhebbers, maar zij hebben mij bedrogen; mijn priesters en mijn oudsten hebben in de stad den geest gegeven, als zij spijze voor zich zochten, opdat zij hun ziel mochten verkwikken."));
dusuperobject.biblemap.put("b25_1_20", new dusuperobject(25,1,20,"Resch. Aanzie, HEERE, want mij is bange; mijn ingewand is beroerd, mijn hart heeft zich omgekeerd in het binnenste van mij, want ik ben zeer wederspannig geweest; van buiten heeft mij het zwaard van kinderen beroofd, van binnen is als de dood."));
dusuperobject.biblemap.put("b25_1_21", new dusuperobject(25,1,21,"Schin. Zij horen, dat ik zucht, maar ik heb geen trooster; al mijn vijanden horen mijn kwaad; en zij zijn vrolijk, dat Gij het gedaan hebt; als Gij den dag zult voortgebracht hebben, dien Gij uitgeroepen hebt, zo zullen zij zijn, gelijk ik ben."));
dusuperobject.biblemap.put("b25_1_22", new dusuperobject(25,1,22,"Thau. Laat al hun kwaad voor Uw aangezicht komen, en doe hun, gelijk als Gij mij gedaan hebt vanwege al mijn overtredingen; want mijn zuchtingen zijn vele, en mijn hart is mat."));
dusuperobject.biblemap.put("b25_2_1", new dusuperobject(25,2,1,"Aleph. Hoe heeft de Heere de dochter Sions in Zijn toorn bewolkt? Hij heeft de heerlijkheid van Israel van den hemel op de aarde nedergeworpen; en Hij heeft aan de voetbank Zijner voeten niet gedacht in den dag Zijns toorns."));
dusuperobject.biblemap.put("b25_2_2", new dusuperobject(25,2,2,"Beth. De Heere heeft al de woningen Jakobs verslonden, en heeft ze niet verschoond; Hij heeft de vastigheden der dochter van Juda afgebroken in Zijn verbolgenheid, Hij heeft gemaakt, dat zij de aarde raken; Hij heeft het koninkrijk en deszelfs vorsten ontheiligd."));
dusuperobject.biblemap.put("b25_2_3", new dusuperobject(25,2,3,"Gimel. Hij heeft, in ontsteking des toorns, den gehelen hoorn Israels afgehouwen; Hij heeft Zijn rechterhand achterwaarts getrokken, toen de vijand kwam, en Hij is tegen Jakob ontstoken als een vlammend vuur, dat rondom verteert."));
dusuperobject.biblemap.put("b25_2_4", new dusuperobject(25,2,4,"Daleth. Hij heeft Zijn boog gespannen als een vijand; Hij heeft zich met Zijn rechterhand gesteld als een tegenpartijder, dat Hij doodde al de begeerlijke dingen der ogen; Hij heeft Zijn grimmigheid in de tent der dochter Sions uitgestort als een vuur."));
dusuperobject.biblemap.put("b25_2_5", new dusuperobject(25,2,5,"He. De Heere is geworden als een vijand; Hij heeft Israel verslonden, Hij heeft al haar paleizen verslonden. Hij heeft deszelfs vastigheden verdorven; en Hij heeft bij de dochter van Juda het klagen en kermen vermenigvuldigd."));
dusuperobject.biblemap.put("b25_2_6", new dusuperobject(25,2,6,"Vau. En Hij heeft Zijn hut met geweld afgerukt, als een hof, Hij heeft Zijn vergaderplaats verdorven; de HEERE heeft in Sion doen vergeten den hoogtijd en den sabbat, en Hij heeft in de gramschap Zijns toorns den koning en den priester smadelijk verworpen."));
dusuperobject.biblemap.put("b25_2_7", new dusuperobject(25,2,7,"Zain. De Heere heeft Zijn altaar verstoten. Hij heeft Zijn heiligdom te niet gedaan, Hij heeft de muren harer paleizen in des vijands hand overgegeven; zij hebben in het huis des HEEREN een stem verheven als op den dag eens gezetten hoogtijds."));
dusuperobject.biblemap.put("b25_2_8", new dusuperobject(25,2,8,"Cheth. De HEERE heeft gedacht te verderven den muur der dochter Sions; Hij heeft het richtsnoer daarover getogen, Hij heeft Zijn hand niet afgewend, dat Hij ze niet verslonde; en Hij heeft den voormuur en den muur te zamen treurig gemaakt, zij zijn verzwakt."));
dusuperobject.biblemap.put("b25_2_9", new dusuperobject(25,2,9,"Teth. Haar poorten zijn in de aarde verzonken; Hij heeft haar grendelen verdorven en gebroken; haar koning en haar vorsten zijn onder de heidenen; er is geen wet; haar profeten vinden ook geen gezicht van den HEERE."));
dusuperobject.biblemap.put("b25_2_10", new dusuperobject(25,2,10,"Jod. De oudsten der dochter Sions zitten op de aarde, zij zwijgen stil, zij werpen stof op hun hoofd, zij hebben zakken aangegord; de jonge dochters van Jeruzalem laten haar hoofd ter aarde hangen."));
dusuperobject.biblemap.put("b25_2_11", new dusuperobject(25,2,11,"Caph. Mijn ogen zijn verteerd door tranen, mijn ingewand wordt beroerd; mijn lever is ter aarde uitgeschud, vanwege de breuk der dochter mijns volks; omdat het kind en de zuigeling op de straten der stad in onmacht zinken;"));
dusuperobject.biblemap.put("b25_2_12", new dusuperobject(25,2,12,"Lamed. Als zij tot hun moeders zeggen: Waar is koren en wijn, als zij op de straten der stad in onmacht zinken, als de verslagenen; als zich hun ziel uitschudt in den schoot hunner moeders."));
dusuperobject.biblemap.put("b25_2_13", new dusuperobject(25,2,13,"Mem. Wat getuigen zal ik u brengen, wat zal ik bij u vergelijken, gij dochter Jeruzalems? Wat zal ik bij u vergelijken, dat ik u trooste, gij jonkvrouw, dochter Sions, want uw breuk is zo groot als de zee, wie kan u helen?"));
dusuperobject.biblemap.put("b25_2_14", new dusuperobject(25,2,14,"Nun. Uw profeten hebben u ijdelheid en ongerijmdheid gezien, en zij hebben u uw ongerechtigheid niet geopenbaard, om uw gevangenis af te wenden, maar zij hebben voor u gezien ijdele lasten en uitstotingen."));
dusuperobject.biblemap.put("b25_2_15", new dusuperobject(25,2,15,"Samech. Allen, die over weg gaan, klappen met de handen over u, zij fluiten en schudden hun hoofd over de dochter Jeruzalems, zeggende: Is dit die stad, waar men van zeide, dat zij volkomen van schoonheid was, een vreugde der ganse aarde?"));
dusuperobject.biblemap.put("b25_2_16", new dusuperobject(25,2,16,"Pe. Al uw vijanden sperren hun mond op over u, zij fluiten en knersen met de tanden, zij zeggen: Wij hebben haar verslonden; dit is immers de dag, dien wij verwacht hebben, wij hebben hem gevonden, wij hebben hem gezien."));
dusuperobject.biblemap.put("b25_2_17", new dusuperobject(25,2,17,"Ain. De HEERE heeft gedaan, wat Hij gedacht had, Hij heeft Zijn woord vervuld, dat Hij bevolen had van oude dagen; Hij heeft afgebroken en niet gespaard; en Hij heeft den vijand over u verblijd, Hij heeft den hoorn uwer tegenpartijders verhoogd."));
dusuperobject.biblemap.put("b25_2_18", new dusuperobject(25,2,18,"Tsade. Hun hart schreeuwde tot den Heere: O gij muur der dochter Sions, laat dag en nacht tranen afvlieten als een beek; geef uzelve geen rust, uw oogappel houde niet op!"));
dusuperobject.biblemap.put("b25_2_19", new dusuperobject(25,2,19,"Koph. Maak u op, maak geschrei des nachts in het begin der nachtwaken, stort uw hart uit voor het aangezicht des Heeren als water; hef uw handen tot Hem op voor de ziel uwer kinderkens, die in onmacht gevallen zijn van honger, vooraan op alle straten."));
dusuperobject.biblemap.put("b25_2_20", new dusuperobject(25,2,20,"Resch. Zie, HEERE, aanschouw toch, aan wien Gij alzo gedaan hebt; zullen dan de vrouwen haar vrucht eten, de kinderkens, die men op de handen draagt? Zullen dan de profeet en de priester in het heiligdom des Heeren gedood worden?"));
dusuperobject.biblemap.put("b25_2_21", new dusuperobject(25,2,21,"Schin. De jongen en de ouden liggen op de aarde op de straten; mijn jonkvrouwen en mijn jongelingen zijn door het zwaard gevallen; Gij hebt ze in den dag Uws toorns gedood, Gij hebt ze geslacht en niet verschoond."));
dusuperobject.biblemap.put("b25_2_22", new dusuperobject(25,2,22,"Thau. Gij hebt mijn verschrikkingen van rondom geroepen, als tot een dag eens gezetten hoogtijds; en er is niemand aan den dag des toorns des HEEREN ontkomen of overgebleven; die ik op de handen gedragen en opgetogen heb, die heeft mijn vijand omgebracht."));
dusuperobject.biblemap.put("b25_3_1", new dusuperobject(25,3,1,"Aleph. Ik ben de man, die ellende gezien heeft door de roede Zijner verbolgenheid."));
dusuperobject.biblemap.put("b25_3_2", new dusuperobject(25,3,2,"Aleph. Hij heeft mij geleid en gevoerd in de duisternis, en niet in het licht."));
dusuperobject.biblemap.put("b25_3_3", new dusuperobject(25,3,3,"Aleph. Hij heeft Zich immers tegen mij gewend, Hij heeft Zijn hand den gansen dag veranderd."));
dusuperobject.biblemap.put("b25_3_4", new dusuperobject(25,3,4,"Beth. Hij heeft mijn vlees en mijn huid oud gemaakt, Hij heeft mijn beenderen gebroken."));
dusuperobject.biblemap.put("b25_3_5", new dusuperobject(25,3,5,"Beth. Hij heeft tegen mij gebouwd, en Hij heeft mij met galle en moeite omringd."));
dusuperobject.biblemap.put("b25_3_6", new dusuperobject(25,3,6,"Beth. Hij heeft mij gezet in duistere plaatsen, als degenen, die over lang dood zijn."));
dusuperobject.biblemap.put("b25_3_7", new dusuperobject(25,3,7,"Gimel. Hij heeft mij toegemuurd, dat ik er niet uit gaan kan; Hij heeft mijn koperen boeien verzwaard."));
dusuperobject.biblemap.put("b25_3_8", new dusuperobject(25,3,8,"Gimel. Ook wanneer ik roep en schreeuw, sluit Hij de oren voor mijn gebed."));
dusuperobject.biblemap.put("b25_3_9", new dusuperobject(25,3,9,"Gimel. Hij heeft mij wegen toegemuurd met uitgehouwen stenen, Hij heeft mijn paden verkeerd."));
dusuperobject.biblemap.put("b25_3_10", new dusuperobject(25,3,10,"Daleth. Hij is mij een loerende beer, een leeuw in verborgen plaatsen."));
dusuperobject.biblemap.put("b25_3_11", new dusuperobject(25,3,11,"Daleth. Hij heeft mijn wegen afgewend; en Hij heeft mij in stukken gebroken; Hij heeft mij woest gemaakt."));
dusuperobject.biblemap.put("b25_3_12", new dusuperobject(25,3,12,"Daleth. Hij heeft Zijn boog gespannen, en Hij heeft mij den pijl als ten doel gesteld."));
dusuperobject.biblemap.put("b25_3_13", new dusuperobject(25,3,13,"He. Hij heeft Zijn pijlen in mijn nieren doen ingaan."));
dusuperobject.biblemap.put("b25_3_14", new dusuperobject(25,3,14,"He. Ik ben al mijn volk tot belaching geworden, hun snarenspel den gansen dag."));
dusuperobject.biblemap.put("b25_3_15", new dusuperobject(25,3,15,"He. Hij heeft mij met bitterheden verzadigd, Hij heeft mij met alsem dronken gemaakt."));
dusuperobject.biblemap.put("b25_3_16", new dusuperobject(25,3,16,"Vau. Hij heeft mijn tanden met zandsteentjes verbrijzeld, Hij heeft mij in de as nedergedrukt."));
dusuperobject.biblemap.put("b25_3_17", new dusuperobject(25,3,17,"Vau. En Gij hebt mijn ziel verre van den vrede verstoten, ik heb het goede vergeten."));
dusuperobject.biblemap.put("b25_3_18", new dusuperobject(25,3,18,"Vau. Toen zeide ik: Mijn sterkte is vergaan, en mijn hoop van den HEERE."));
dusuperobject.biblemap.put("b25_3_19", new dusuperobject(25,3,19,"Zain. Gedenk aan mijn ellende en aan mijn ballingschap, aan den alsem en galle."));
dusuperobject.biblemap.put("b25_3_20", new dusuperobject(25,3,20,"Zain. Mijn ziel gedenkt er wel terdege aan, en zij bukt zich neder in mij."));
dusuperobject.biblemap.put("b25_3_21", new dusuperobject(25,3,21,"Zain. Dit zal ik mij ter harte nemen, daarom zal ik hopen;"));
dusuperobject.biblemap.put("b25_3_22", new dusuperobject(25,3,22,"Cheth. Het zijn de goedertierenheden des HEEREN, dat wij niet vernield zijn, dat Zijn barmhartigheden geen einde hebben;"));
dusuperobject.biblemap.put("b25_3_23", new dusuperobject(25,3,23,"Cheth. Zij zijn allen morgen nieuw, Uw trouw is groot."));
dusuperobject.biblemap.put("b25_3_24", new dusuperobject(25,3,24,"Cheth. De HEERE is mijn Deel, zegt mijn ziel, daarom zal ik op Hem hopen."));
dusuperobject.biblemap.put("b25_3_25", new dusuperobject(25,3,25,"Teth. De HEERE is goed dengenen, die Hem verwachten, der ziele, die Hem zoekt."));
dusuperobject.biblemap.put("b25_3_26", new dusuperobject(25,3,26,"Teth. Het is goed, dat men hope, en stille zij op het heil des HEEREN."));
dusuperobject.biblemap.put("b25_3_27", new dusuperobject(25,3,27,"Teth. Het is goed voor een man, dat hij het juk in zijn jeugd draagt."));
dusuperobject.biblemap.put("b25_3_28", new dusuperobject(25,3,28,"Jod. Hij zitte eenzaam, en zwijge stil, omdat Hij het hem opgelegd heeft."));
dusuperobject.biblemap.put("b25_3_29", new dusuperobject(25,3,29,"Jod. Hij steke zijn mond in het stof, zeggende: Misschien is er verwachting."));
dusuperobject.biblemap.put("b25_3_30", new dusuperobject(25,3,30,"Jod. Hij geve zijn wang dien, die hem slaat, hij worde zat van smaad."));
dusuperobject.biblemap.put("b25_3_31", new dusuperobject(25,3,31,"Caph. Want de Heere zal niet verstoten in eeuwigheid."));
dusuperobject.biblemap.put("b25_3_32", new dusuperobject(25,3,32,"Caph. Maar als Hij bedroefd heeft, zo zal Hij Zich ontfermen, naar de grootheid Zijner goedertierenheden."));
dusuperobject.biblemap.put("b25_3_33", new dusuperobject(25,3,33,"Caph. Want Hij plaagt of bedroeft des mensenkinderen niet van harte."));
dusuperobject.biblemap.put("b25_3_34", new dusuperobject(25,3,34,"Lamed. Dat men al de gevangenen der aarde onder Zijn voeten verbrijzelt;"));
dusuperobject.biblemap.put("b25_3_35", new dusuperobject(25,3,35,"Lamed. Dat men het recht eens mans buigt voor het aangezicht des Allerhoogsten;"));
dusuperobject.biblemap.put("b25_3_36", new dusuperobject(25,3,36,"Lamed. Dat men een mens verongelijkt in zijn twistzaak; zou het de Heere niet zien?"));
dusuperobject.biblemap.put("b25_3_37", new dusuperobject(25,3,37,"Mem. Wie zegt wat, hetwelk geschiedt, zo het de Heere niet beveelt?"));
dusuperobject.biblemap.put("b25_3_38", new dusuperobject(25,3,38,"Mem. Gaat niet uit den mond des Allerhoogsten het kwade en het goede?"));
dusuperobject.biblemap.put("b25_3_39", new dusuperobject(25,3,39,"Mem. Wat klaagt dan een levend mens? Een ieder klage vanwege zijn zonden."));
dusuperobject.biblemap.put("b25_3_40", new dusuperobject(25,3,40,"Nun. Laat ons onze wegen onderzoeken en doorzoeken, en laat ons wederkeren tot den HEERE."));
dusuperobject.biblemap.put("b25_3_41", new dusuperobject(25,3,41,"Nun. Laat ons onze harten opheffen, mitsgaders de handen, tot God in den hemel, zeggende:"));
dusuperobject.biblemap.put("b25_3_42", new dusuperobject(25,3,42,"Nun. Wij hebben overtreden, en wij zijn wederspannig geweest, daarom hebt Gij niet gespaard."));
dusuperobject.biblemap.put("b25_3_43", new dusuperobject(25,3,43,"Samech. Gij hebt ons met toorn bedekt, en Gij hebt ons vervolgd; Gij hebt ons gedood, Gij hebt niet verschoond."));
dusuperobject.biblemap.put("b25_3_44", new dusuperobject(25,3,44,"Samech. Gij hebt U met een wolk bedekt, zodat er geen gebed doorkwam."));
dusuperobject.biblemap.put("b25_3_45", new dusuperobject(25,3,45,"Samech. Gij hebt ons tot een uitvaagsel en wegwerpsel gesteld, in het midden der volken."));
dusuperobject.biblemap.put("b25_3_46", new dusuperobject(25,3,46,"Pe. Al onze vijanden hebben hun mond tegen ons opgesperd."));
dusuperobject.biblemap.put("b25_3_47", new dusuperobject(25,3,47,"Pe. De vreze en de kuil zijn over ons gekomen, de verwoesting en de verbreking."));
dusuperobject.biblemap.put("b25_3_48", new dusuperobject(25,3,48,"Pe. Met waterbeken loopt mijn oog neder, vanwege de breuk der dochter mijns volks."));
dusuperobject.biblemap.put("b25_3_49", new dusuperobject(25,3,49,"Ain. Mijn oog vliet, en kan niet ophouden, omdat er geen rust is;"));
dusuperobject.biblemap.put("b25_3_50", new dusuperobject(25,3,50,"Ain. Totdat het de HEERE van den hemel aanschouwe, en het zie."));
dusuperobject.biblemap.put("b25_3_51", new dusuperobject(25,3,51,"Ain. Mijn oog doet mijn ziele moeite aan, vanwege al de dochteren mijner stad."));
dusuperobject.biblemap.put("b25_3_52", new dusuperobject(25,3,52,"Tsade. Die mijn vijanden zijn zonder oorzaak, hebben mij als een vogeltje dapperlijk gejaagd."));
dusuperobject.biblemap.put("b25_3_53", new dusuperobject(25,3,53,"Tsade. Zij hebben mijn leven in een kuil uitgeroeid, en zij hebben een steen op mij geworpen."));
dusuperobject.biblemap.put("b25_3_54", new dusuperobject(25,3,54,"Tsade. De wateren zwommen over mijn hoofd; ik zeide: Ik ben afgesneden!"));
dusuperobject.biblemap.put("b25_3_55", new dusuperobject(25,3,55,"Koph. HEERE! Ik heb Uw Naam aangeroepen uit den ondersten kuil."));
dusuperobject.biblemap.put("b25_3_56", new dusuperobject(25,3,56,"Koph. Gij hebt mijn stem gehoord, verberg Uw oor niet voor mijn zuchten, voor mijn roepen."));
dusuperobject.biblemap.put("b25_3_57", new dusuperobject(25,3,57,"Koph. Gij hebt U genaderd ten dage, als ik U aanriep; Gij hebt gezegd: Vrees niet!"));
dusuperobject.biblemap.put("b25_3_58", new dusuperobject(25,3,58,"Resch. Heere! Gij hebt de twistzaken mijner ziel getwist, Gij hebt mijn leven verlost."));
dusuperobject.biblemap.put("b25_3_59", new dusuperobject(25,3,59,"Resch. Heere! Gij hebt gezien de verkeerdheid, die men mij aangedaan heeft, oordeel mijn rechtzaak."));
dusuperobject.biblemap.put("b25_3_60", new dusuperobject(25,3,60,"Resch. Gij hebt al hun wraak gezien, al hun gedachten tegen mij."));
dusuperobject.biblemap.put("b25_3_61", new dusuperobject(25,3,61,"Schin. HEERE! Gij hebt hun smaden gehoord, en al hun gedachten tegen mij;"));
dusuperobject.biblemap.put("b25_3_62", new dusuperobject(25,3,62,"Schin. De lippen dergenen, die tegen mij opstaan, en hun dichten tegen mij den gansen dag."));
dusuperobject.biblemap.put("b25_3_63", new dusuperobject(25,3,63,"Schin. Aanschouw hun zitten en opstaan; ik ben hun snarenspel."));
dusuperobject.biblemap.put("b25_3_64", new dusuperobject(25,3,64,"Thau. HEERE! geef hun weder die vergelding, naar het werk hunner handen."));
dusuperobject.biblemap.put("b25_3_65", new dusuperobject(25,3,65,"Thau. Geef hun een deksel des harten; Uw vloek zij over hen!"));
dusuperobject.biblemap.put("b25_3_66", new dusuperobject(25,3,66,"Thau. Vervolg ze met toorn, en verdelg ze van onder den hemel des HEEREN."));
dusuperobject.biblemap.put("b25_4_1", new dusuperobject(25,4,1,"Aleph. Hoe is het goud zo verdonkerd, het goede fijne goud zo veranderd! Hoe zijn de stenen des heiligdoms vooraan op alle straten verworpen!"));
dusuperobject.biblemap.put("b25_4_2", new dusuperobject(25,4,2,"Beth. De kostelijke kinderen Sions, tegen fijn goud geschat, hoe zijn zij nu gelijk gerekend aan de aarden flessen, het werk van de handen eens pottenbakkers!"));
dusuperobject.biblemap.put("b25_4_3", new dusuperobject(25,4,3,"Gimel. Zelfs laten de zeekalveren de borsten neder, zij zogen hun welpen; maar de dochter mijns volks is als een wrede geworden, gelijk de struisen in de woestijn."));
dusuperobject.biblemap.put("b25_4_4", new dusuperobject(25,4,4,"Daleth. De tong van het zoogkind kleeft aan zijn gehemelte van dorst; de kinderkens eisen brood, er is niemand, die het hun mededeelt."));
dusuperobject.biblemap.put("b25_4_5", new dusuperobject(25,4,5,"He. Die lekkernijen aten, versmachten nu op de straten; die in karmozijn opgetrokken zijn, omhelzen den drek."));
dusuperobject.biblemap.put("b25_4_6", new dusuperobject(25,4,6,"Vau. En de ongerechtigheid der dochter mijns volks is groter dan de zonden van Sodom, dat als in een ogenblik omgekeerd werd, en geen handen hadden arbeid over haar."));
dusuperobject.biblemap.put("b25_4_7", new dusuperobject(25,4,7,"Zain. Haar bijzondersten waren reiner dan de sneeuw, zij waren witter dan melk; zij waren roder van lichaam dan robijnen, gladder dan een saffier."));
dusuperobject.biblemap.put("b25_4_8", new dusuperobject(25,4,8,"Cheth. Maar nu is hun gedaante verduisterd van zwartigheid, men kent hen niet op de straten; hun huid kleeft aan hun beenderen, zij is verdord, zij is geworden als een hout."));
dusuperobject.biblemap.put("b25_4_9", new dusuperobject(25,4,9,"Teth. De verslagenen van het zwaard zijn gelukkiger dan de verslagenen van den honger; want die vlieten daarhenen, als doorstoken zijnde, omdat er geen vruchten der velden zijn."));
dusuperobject.biblemap.put("b25_4_10", new dusuperobject(25,4,10,"Jod. De handen der barmhartige vrouwen hebben haar kinderen gekookt; zij zijn haar tot spijze geworden in de verbreking der dochter mijns volks."));
dusuperobject.biblemap.put("b25_4_11", new dusuperobject(25,4,11,"Caph. De HEERE heeft Zijn grimmigheid volbracht, Hij heeft de hittigheid Zijns toorns uitgestort; en Hij heeft te Sion een vuur aangestoken, hetwelk haar fondamenten verteerd heeft."));
dusuperobject.biblemap.put("b25_4_12", new dusuperobject(25,4,12,"Lamed. De koningen der aarde zouden het niet geloofd hebben, noch al de inwoners der wereld, dat de tegenpartijder en vijand tot de poorten van Jeruzalem zou ingaan."));
dusuperobject.biblemap.put("b25_4_13", new dusuperobject(25,4,13,"Mem. Het is vanwege de zonden harer profeten, en de misdaden harer priesteren, die in het midden van haar het bloed der rechtvaardigen vergoten hebben."));
dusuperobject.biblemap.put("b25_4_14", new dusuperobject(25,4,14,"Nun. Zij zwierven als blinden op de straten, zij waren met bloed besmet, zodat men niet kon zien, of men raakte hun klederen aan."));
dusuperobject.biblemap.put("b25_4_15", new dusuperobject(25,4,15,"Samech. Zij riepen tot hen: Wijkt, hier is een onreine wijkt, wijkt, roert niet aan! Zekerlijk, zij zijn weggevlogen, ja, weggezworven; zij zeiden onder de heidenen: Zij zullen er niet langer wonen."));
dusuperobject.biblemap.put("b25_4_16", new dusuperobject(25,4,16,"Pe. Des HEEREN aangezicht heeft ze verdeeld. Hij zal ze voortaan niet meer aanzien; zij hebben het aangezicht der priesteren niet geeerd, zij hebben den ouden geen genade bewezen."));
dusuperobject.biblemap.put("b25_4_17", new dusuperobject(25,4,17,"Ain. Nog bezweken ons onze ogen, ziende naar onze ijdele hulp; wij gaapten met ons gapen op een volk, dat niet kon verlossen."));
dusuperobject.biblemap.put("b25_4_18", new dusuperobject(25,4,18,"Tsade. Zij hebben onze gangen nagespeurd, dat wij op onze straten niet gaan konden; ons einde is genaderd, onze dagen zijn vervuld, ja, ons einde is gekomen."));
dusuperobject.biblemap.put("b25_4_19", new dusuperobject(25,4,19,"Koph. Onze vervolgers zijn sneller geweest dan de arenden des hemels; zij hebben ons op de bergen hittiglijk vervolgd, in de woestijn hebben zij ons lagen gelegd."));
dusuperobject.biblemap.put("b25_4_20", new dusuperobject(25,4,20,"Resch. De adem onzer neuzen, de gezalfde des HEEREN, is gevangen in hun groeven; van welken wij zeiden: Wij zullen onder zijn schaduw leven onder de heidenen!"));
dusuperobject.biblemap.put("b25_4_21", new dusuperobject(25,4,21,"Schin. Wees vrolijk, en verblijd u, gij dochter Edoms, die in het land Uz woont! doch de beker zal ook tot u komen, gij zult dronken worden, en ontbloot worden."));
dusuperobject.biblemap.put("b25_4_22", new dusuperobject(25,4,22,"Thau. Uw ongerechtigheid heeft een einde, o gij dochter Sions! Hij zal u niet meer gevankelijk doen wegvoeren; maar uw ongerechtigheid, o gij dochter Edoms! zal Hij bezoeken; Hij zal uw zonden ontdekken."));
dusuperobject.biblemap.put("b25_5_1", new dusuperobject(25,5,1,"Gedenk, HEERE, wat ons geschied is, aanschouw het, en zie onzen smaad aan."));
dusuperobject.biblemap.put("b25_5_2", new dusuperobject(25,5,2,"Ons erfdeel is tot de vreemdelingen gewend, onze huizen tot de uitlanders."));
dusuperobject.biblemap.put("b25_5_3", new dusuperobject(25,5,3,"Wij zijn wezen zonder vader, onze moeders zijn als de weduwen."));
dusuperobject.biblemap.put("b25_5_4", new dusuperobject(25,5,4,"Ons water moeten wij voor geld drinken; ons hout komt ons op prijs te staan."));
dusuperobject.biblemap.put("b25_5_5", new dusuperobject(25,5,5,"Wij lijden vervolging op onze halzen; zijn wij woede, men laat ons geen rust."));
dusuperobject.biblemap.put("b25_5_6", new dusuperobject(25,5,6,"Wij hebben den Egyptenaar de hand gegeven, en den Assyrier, om met brood verzadigd te worden."));
dusuperobject.biblemap.put("b25_5_7", new dusuperobject(25,5,7,"Onze vaders hebben gezondigd, en zijn niet meer, en wij dragen hun ongerechtigheden."));
dusuperobject.biblemap.put("b25_5_8", new dusuperobject(25,5,8,"Knechten heersen over ons; er is niemand, die ons uit hun hand rukke."));
dusuperobject.biblemap.put("b25_5_9", new dusuperobject(25,5,9,"Wij moeten ons brood met gevaar onzes levens halen, vanwege het zwaard der woestijn."));
dusuperobject.biblemap.put("b25_5_10", new dusuperobject(25,5,10,"Onze huid is zwart geworden gelijk een oven, vanwege den geweldigen storm des hongers."));
dusuperobject.biblemap.put("b25_5_11", new dusuperobject(25,5,11,"Zij hebben de vrouwen te Sion verkracht, en de jonge dochters in de steden van Juda."));
dusuperobject.biblemap.put("b25_5_12", new dusuperobject(25,5,12,"De vorsten zijn door hunlieder hand opgehangen; de aangezichten der ouden zijn niet geeerd geweest."));
dusuperobject.biblemap.put("b25_5_13", new dusuperobject(25,5,13,"Zij hebben de jongelingen weggenomen, om te malen, en de jongens struikelen onder het hout."));
dusuperobject.biblemap.put("b25_5_14", new dusuperobject(25,5,14,"De ouden houden op van de poort, de jongelingen van hun snarenspel."));
dusuperobject.biblemap.put("b25_5_15", new dusuperobject(25,5,15,"De vreugde onzes harten houdt op, onze rei is in treurigheid veranderd."));
dusuperobject.biblemap.put("b25_5_16", new dusuperobject(25,5,16,"De kroon onzes hoofds is afgevallen; o wee nu onzer, dat wij zo gezondigd hebben!"));
dusuperobject.biblemap.put("b25_5_17", new dusuperobject(25,5,17,"Daarom is ons hart mat, om deze dingen zijn onze ogen duister geworden."));
dusuperobject.biblemap.put("b25_5_18", new dusuperobject(25,5,18,"Om des bergs Sions wil, die verwoest is, waar de vossen op lopen."));
dusuperobject.biblemap.put("b25_5_19", new dusuperobject(25,5,19,"Gij, o HEERE, zit in eeuwigheid, Uw troon is van geslacht tot geslacht."));
dusuperobject.biblemap.put("b25_5_20", new dusuperobject(25,5,20,"Waarom zoudt Gij ons steeds vergeten? Waarom zoudt Gij ons zo langen tijd verlaten?"));
dusuperobject.biblemap.put("b25_5_21", new dusuperobject(25,5,21,"HEERE, bekeer ons tot U, zo zullen wij bekeerd zijn; vernieuw onze dagen als van ouds."));
dusuperobject.biblemap.put("b25_5_22", new dusuperobject(25,5,22,"Want zoudt Gij ons ganselijk verwerpen? Zoudt Gij zozeer tegen ons verbolgen zijn?"));

}

}