package du.bible;

public class dubible47 {

public dubible47() {

putmapbible47();

}

private void putmapbible47() {

dusuperobject.biblemap.put("b47_1_1", new dusuperobject(47,1,1,"Paulus, een apostel van Jezus Christus, door den wil van God, en Timotheus, de broeder, aan de Gemeente Gods, die te Korinthe is, met al de heiligen, die in geheel Achaje zijn:"));
dusuperobject.biblemap.put("b47_1_2", new dusuperobject(47,1,2,"Genade zij u en vrede van God, onzen Vader, en den Heere Jezus Christus."));
dusuperobject.biblemap.put("b47_1_3", new dusuperobject(47,1,3,"Geloofd zij de God en Vader van onzen Heere Jezus Christus, de Vader der barmhartigheden, en de God aller vertroosting;"));
dusuperobject.biblemap.put("b47_1_4", new dusuperobject(47,1,4,"Die ons vertroost in al onze verdrukking, opdat wij zouden kunnen vertroosten degenen, die in allerlei verdrukking zijn, door de vertroosting, met welke wij zelven van God vertroost worden."));
dusuperobject.biblemap.put("b47_1_5", new dusuperobject(47,1,5,"Want gelijk het lijden van Christus overvloedig is in ons, alzo is ook door Christus onze vertroosting overvloedig."));
dusuperobject.biblemap.put("b47_1_6", new dusuperobject(47,1,6,"Doch hetzij dat wij verdrukt worden, het is tot uw vertroosting en zaligheid, die gewrocht wordt in de lijdzaamheid van hetzelfde lijden, hetwelk wij ook lijden; hetzij dat wij vertroost worden, het is tot uw vertroosting en zaligheid;"));
dusuperobject.biblemap.put("b47_1_7", new dusuperobject(47,1,7,"En onze hoop van u is vast, als die weten, dat, gelijk gij gemeenschap hebt aan het lijden, gij ook alzo gemeenschap hebt aan de vertroosting."));
dusuperobject.biblemap.put("b47_1_8", new dusuperobject(47,1,8,"Want wij willen niet, broeders, dat gij onwetende zijt van onze verdrukking, die ons in Azie overkomen is, dat wij uitnemend zeer bezwaard zijn geweest boven onze macht, alzo dat wij zeer in twijfel waren, ook van het leven."));
dusuperobject.biblemap.put("b47_1_9", new dusuperobject(47,1,9,"Ja, wij hadden al zelven in onszelven het vonnis des doods, opdat wij niet op onszelven vertrouwen zouden, maar op God, Die de doden verwekt;"));
dusuperobject.biblemap.put("b47_1_10", new dusuperobject(47,1,10,"Die ons uit zo groten dood verlost heeft, en nog verlost; op Welken wij hopen, dat Hij ons ook nog verlossen zal."));
dusuperobject.biblemap.put("b47_1_11", new dusuperobject(47,1,11,"Alzo gijlieden ook medearbeidt voor ons door het gebed, opdat over de gave, door vele personen aan ons teweeggebracht ook voor ons dankzegging door velen gedaan worde."));
dusuperobject.biblemap.put("b47_1_12", new dusuperobject(47,1,12,"Want onze roem is deze, namelijk de getuigenis van ons geweten, dat wij in eenvoudigheid en oprechtheid Gods, niet in vleselijke wijsheid, maar in de genade Gods, in de wereld verkeerd hebben, en allermeest bij ulieden."));
dusuperobject.biblemap.put("b47_1_13", new dusuperobject(47,1,13,"Want wij schrijven u geen andere dingen, dan die gij kent, of ook erkent; en ik hoop, dat gij ze ook tot het einde toe erkennen zult;"));
dusuperobject.biblemap.put("b47_1_14", new dusuperobject(47,1,14,"Gelijkerwijs gij ook ten dele ons erkend hebt, dat wij uw roem zijn, gelijk gij ook de onze zijt, in den dag van den Heere Jezus."));
dusuperobject.biblemap.put("b47_1_15", new dusuperobject(47,1,15,"En op dit betrouwen wilde ik te voren tot u komen, opdat gij een tweede genade zoudt hebben;"));
dusuperobject.biblemap.put("b47_1_16", new dusuperobject(47,1,16,"En door uw stad naar Macedonie gaan, en wederom van Macedonie tot u komen, en van ulieden naar Judea geleid worden."));
dusuperobject.biblemap.put("b47_1_17", new dusuperobject(47,1,17,"Als ik dan dit voorgenomen heb, heb ik ook lichtvaardigheid gebruikt? Of neem ik het naar het vlees voor, hetgeen ik voorneem, opdat bij mij zou wezen, ja, ja, en neen, neen?"));
dusuperobject.biblemap.put("b47_1_18", new dusuperobject(47,1,18,"Doch God is getrouw, dat ons woord, hetwelk tot u is geschied, niet is geweest ja en neen."));
dusuperobject.biblemap.put("b47_1_19", new dusuperobject(47,1,19,"Want de Zoon van God, Jezus Christus, Die onder u door ons is gepredikt, namelijk door mij, en Silvanus, en Timotheus, was niet ja en neen, maar is geweest ja in Hem."));
dusuperobject.biblemap.put("b47_1_20", new dusuperobject(47,1,20,"Want zovele beloften Gods als er zijn, die zijn in Hem ja, en zijn in Hem amen, Gode tot heerlijkheid door ons."));
dusuperobject.biblemap.put("b47_1_21", new dusuperobject(47,1,21,"Maar Die ons met u bevestigt in Christus, en Die ons gezalfd heeft, is God;"));
dusuperobject.biblemap.put("b47_1_22", new dusuperobject(47,1,22,"Die ons ook heeft verzegeld, en het onderpand des Geestes in onze harten gegeven."));
dusuperobject.biblemap.put("b47_1_23", new dusuperobject(47,1,23,"Doch ik aanroepe God tot een Getuige over mijn ziel, dat ik, om u te sparen, nog te Korinthe niet ben gekomen."));
dusuperobject.biblemap.put("b47_1_24", new dusuperobject(47,1,24,"Niet dat wij heerschappij voeren over uw geloof, maar wij zijn medewerkers uwer blijdschap; want gij staat door het geloof."));
dusuperobject.biblemap.put("b47_2_1", new dusuperobject(47,2,1,"Maar ik heb dit bij mijzelven voorgenomen, dat ik niet wederom in droefheid tot u komen zou."));
dusuperobject.biblemap.put("b47_2_2", new dusuperobject(47,2,2,"Want indien ik ulieden bedroef, wie is het toch, die mij zal vrolijk maken, dan degene, die van mij bedroefd is geworden?"));
dusuperobject.biblemap.put("b47_2_3", new dusuperobject(47,2,3,"En ditzelfde heb ik u geschreven, opdat ik, daar komende, niet zou droefheid hebben van degenen, van welke ik moest verblijd worden; vertrouwende van u allen, dat mijn blijdschap uw aller blijdschap is."));
dusuperobject.biblemap.put("b47_2_4", new dusuperobject(47,2,4,"Want ik heb ulieden uit vele verdrukking en benauwdheid des harten, met vele tranen geschreven, niet opdat gij zoudt bedroefd worden, maar opdat gij de liefde zoudt verstaan, die ik overvloediglijk tot u heb."));
dusuperobject.biblemap.put("b47_2_5", new dusuperobject(47,2,5,"Doch indien iemand bedroefd heeft, die heeft niet mij bedroefd, maar ten dele (opdat ik hem niet bezware) ulieden allen."));
dusuperobject.biblemap.put("b47_2_6", new dusuperobject(47,2,6,"Den zodanige is deze bestraffing genoeg, die van velen geschied is."));
dusuperobject.biblemap.put("b47_2_7", new dusuperobject(47,2,7,"Alzo dat gij daarentegen hem liever moet vergeven en vertroosten, opdat de zodanige door al te overvloedige droefheid niet enigszins worde verslonden."));
dusuperobject.biblemap.put("b47_2_8", new dusuperobject(47,2,8,"Daarom bid ik u, dat gij de liefde aan hem bevestigt."));
dusuperobject.biblemap.put("b47_2_9", new dusuperobject(47,2,9,"Want daartoe heb ik ook geschreven, opdat ik uw beproeving mocht verstaan, of gij in alles gehoorzaam zijt."));
dusuperobject.biblemap.put("b47_2_10", new dusuperobject(47,2,10,"Dien gij nu iets vergeeft, dien vergeef ik ook; want zo ik ook iets vergeven heb, dien ik vergeven heb, heb ik het vergeven om uwentwil, voor het aangezicht van Christus, opdat de satan over ons geen voordeel krijge;"));
dusuperobject.biblemap.put("b47_2_11", new dusuperobject(47,2,11,"Want zijn gedachten zijn ons niet onbekend."));
dusuperobject.biblemap.put("b47_2_12", new dusuperobject(47,2,12,"Voorts, als ik te Troas kwam, om het Evangelie van Christus te prediken, en als mij een deur geopend was in den Heere, zo heb ik geen rust gehad voor mijn geest, omdat ik Titus, mijn broeder, niet vond;"));
dusuperobject.biblemap.put("b47_2_13", new dusuperobject(47,2,13,"Maar, afscheid van hen genomen hebbende, vertrok ik naar Macedonie."));
dusuperobject.biblemap.put("b47_2_14", new dusuperobject(47,2,14,"En Gode zij dank, Die ons allen tijd doet triomferen in Christus, en den reuk Zijner kennis door ons openbaar maakt in alle plaatsen."));
dusuperobject.biblemap.put("b47_2_15", new dusuperobject(47,2,15,"Want wij zijn Gode een goede reuk van Christus, in degenen, die zalig worden, en in degenen, die verloren gaan;"));
dusuperobject.biblemap.put("b47_2_16", new dusuperobject(47,2,16,"Dezen wel een reuk des doods ten dode; maar genen een reuk des levens ten leven. En wie is tot deze dingen bekwaam?"));
dusuperobject.biblemap.put("b47_2_17", new dusuperobject(47,2,17,"Want wij dragen niet, gelijk velen, het Woord Gods te koop, maar als uit oprechtheid, maar als uit God, in de tegenwoordigheid Gods, spreken wij het in Christus."));
dusuperobject.biblemap.put("b47_3_1", new dusuperobject(47,3,1,"Beginnen wij onszelven wederom u aan te prijzen? Of behoeven wij ook, gelijk sommigen, brieven van voorschrijving aan u, of brieven van voorschrijving van u?"));
dusuperobject.biblemap.put("b47_3_2", new dusuperobject(47,3,2,"Gijlieden zijt onze brief, geschreven in onze harten, bekend en gelezen van alle mensen;"));
dusuperobject.biblemap.put("b47_3_3", new dusuperobject(47,3,3,"Als die openbaar zijt geworden, dat gij een brief van Christus zijt, en door onzen dienst bereid, die geschreven is niet met inkt, maar door den Geest des levenden Gods, niet in stenen tafelen, maar in vlezen tafelen des harten."));
dusuperobject.biblemap.put("b47_3_4", new dusuperobject(47,3,4,"En zodanig een vertrouwen hebben wij door Christus bij God."));
dusuperobject.biblemap.put("b47_3_5", new dusuperobject(47,3,5,"Niet dat wij van onszelven bekwaam zijn iets te denken, als uit onszelven; maar onze bekwaamheid is uit God;"));
dusuperobject.biblemap.put("b47_3_6", new dusuperobject(47,3,6,"Die ons ook bekwaam gemaakt heeft, om te zijn dienaars des Nieuwen Testaments, niet der letter, maar des Geestes; want de letter doodt, maar de Geest maakt levend."));
dusuperobject.biblemap.put("b47_3_7", new dusuperobject(47,3,7,"En indien de bediening des doods in letteren bestaande, en in stenen ingedrukt, in heerlijkheid is geweest, alzo dat de kinderen Israels het aangezicht van Mozes niet konden sterk aanzien, om de heerlijkheid zijns aangezichts, die te niet gedaan zou worden,"));
dusuperobject.biblemap.put("b47_3_8", new dusuperobject(47,3,8,"Hoe zal niet veel meer de bediening des Geestes in heerlijkheid zijn?"));
dusuperobject.biblemap.put("b47_3_9", new dusuperobject(47,3,9,"Want indien de bediening der verdoemenis heerlijkheid geweest is, veel meer is de bediening der rechtvaardigheid overvloedig in heerlijkheid."));
dusuperobject.biblemap.put("b47_3_10", new dusuperobject(47,3,10,"Want ook het verheerlijkte is zelfs niet verheerlijkt in dezen dele, ten aanzien van deze uitnemende heerlijkheid."));
dusuperobject.biblemap.put("b47_3_11", new dusuperobject(47,3,11,"Want indien hetgeen te niet gedaan wordt, in heerlijkheid was, veel meer is hetgeen blijft, in heerlijkheid."));
dusuperobject.biblemap.put("b47_3_12", new dusuperobject(47,3,12,"Dewijl wij dan zodanige hoop hebben, zo gebruiken wij vele vrijmoedigheid in het spreken;"));
dusuperobject.biblemap.put("b47_3_13", new dusuperobject(47,3,13,"En doen niet gelijkerwijs Mozes, die een deksel op zijn aangezicht legde, opdat de kinderen Israels niet zouden sterk zien op het einde van hetgeen te niet gedaan wordt."));
dusuperobject.biblemap.put("b47_3_14", new dusuperobject(47,3,14,"Maar hun zinnen zijn verhard geworden; want tot op den dag van heden blijft hetzelfde deksel in het lezen des Ouden Testaments, zonder ontdekt te worden, hetwelk door Christus te niet gedaan wordt."));
dusuperobject.biblemap.put("b47_3_15", new dusuperobject(47,3,15,"Maar tot den huidigen dag toe, wanneer Mozes gelezen wordt, ligt een deksel op hun hart."));
dusuperobject.biblemap.put("b47_3_16", new dusuperobject(47,3,16,"Doch zo wanneer het tot den Heere zal bekeerd zijn, zo wordt het deksel weggenomen."));
dusuperobject.biblemap.put("b47_3_17", new dusuperobject(47,3,17,"De Heere nu is de Geest; en waar de Geest des Heeren is, aldaar is vrijheid."));
dusuperobject.biblemap.put("b47_3_18", new dusuperobject(47,3,18,"En wij allen, met ongedekten aangezichte de heerlijkheid des Heeren als in een spiegel aanschouwende, worden naar hetzelfde beeld in gedaante veranderd, van heerlijkheid tot heerlijkheid, als van des Heeren Geest."));
dusuperobject.biblemap.put("b47_4_1", new dusuperobject(47,4,1,"Daarom dewijl wij deze bediening hebben, naar de barmhartigheid, die ons geschied is, zo vertragen wij niet;"));
dusuperobject.biblemap.put("b47_4_2", new dusuperobject(47,4,2,"Maar wij hebben verworpen de bedekselen der schande, niet wandelende in arglistigheid, noch het Woord Gods vervalsende, maar door openbaring der waarheid onszelven aangenaam makende bij alle gewetens der mensen, in de tegenwoordigheid Gods."));
dusuperobject.biblemap.put("b47_4_3", new dusuperobject(47,4,3,"Doch indien ook ons Evangelie bedekt is, zo is het bedekt in degenen, die verloren gaan;"));
dusuperobject.biblemap.put("b47_4_4", new dusuperobject(47,4,4,"In dewelke de god dezer eeuw de zinnen verblind heeft, namelijk der ongelovigen, opdat hen niet bestrale de verlichting van het Evangelie der heerlijkheid van Christus, Die het Beeld Gods is."));
dusuperobject.biblemap.put("b47_4_5", new dusuperobject(47,4,5,"Want wij prediken niet onszelven, maar Christus Jezus, den Heere; en onszelven, dat wij uw dienaars zijn om Jezus' wil."));
dusuperobject.biblemap.put("b47_4_6", new dusuperobject(47,4,6,"Want God, Die gezegd heeft, dat het licht uit de duisternis zou schijnen, is Degene, Die in onze harten geschenen heeft, om te geven verlichting der kennis der heerlijkheid Gods in het aangezicht van Jezus Christus."));
dusuperobject.biblemap.put("b47_4_7", new dusuperobject(47,4,7,"Maar wij hebben dezen schat in aarden vaten, opdat de uitnemendheid der kracht zij van God, en niet uit ons;"));
dusuperobject.biblemap.put("b47_4_8", new dusuperobject(47,4,8,"Als die in alles verdrukt worden, doch niet benauwd; twijfelmoedig, doch niet mismoedig;"));
dusuperobject.biblemap.put("b47_4_9", new dusuperobject(47,4,9,"Vervolgd, doch niet daarin verlaten; nedergeworpen, doch niet verdorven;"));
dusuperobject.biblemap.put("b47_4_10", new dusuperobject(47,4,10,"Altijd de doding van den Heere Jezus in het lichaam omdragende, opdat ook het leven van Jezus in ons lichaam zou geopenbaard worden."));
dusuperobject.biblemap.put("b47_4_11", new dusuperobject(47,4,11,"Want wij, die leven, worden altijd in den dood overgegeven om Jezus' wil; opdat ook het leven van Jezus in ons sterfelijk vlees zou geopenbaard worden."));
dusuperobject.biblemap.put("b47_4_12", new dusuperobject(47,4,12,"Zo dan, de dood werkt wel in ons, maar het leven in ulieden."));
dusuperobject.biblemap.put("b47_4_13", new dusuperobject(47,4,13,"Dewijl wij nu denzelfden Geest des geloofs hebben, gelijk er geschreven is: Ik heb geloofd, daarom heb ik gesproken; zo geloven wij ook, daarom spreken wij ook;"));
dusuperobject.biblemap.put("b47_4_14", new dusuperobject(47,4,14,"Wetende, dat Hij, Die den Heere Jezus opgewekt heeft, ook ons door Jezus zal opwekken, en met ulieden daar zal stellen."));
dusuperobject.biblemap.put("b47_4_15", new dusuperobject(47,4,15,"Want al deze dingen zijn om uwentwil, opdat de vermenigvuldigde genade, door de dankzegging van velen, overvloedig worde ter heerlijkheid Gods."));
dusuperobject.biblemap.put("b47_4_16", new dusuperobject(47,4,16,"Daarom vertragen wij niet; maar hoewel onze uitwendige mens verdorven wordt, zo wordt nochtans de inwendige vernieuwd van dag tot dag."));
dusuperobject.biblemap.put("b47_4_17", new dusuperobject(47,4,17,"Want onze lichte verdrukking, die zeer haast voorbij gaat, werkt ons een gans zeer uitnemend eeuwig gewicht der heerlijkheid;"));
dusuperobject.biblemap.put("b47_4_18", new dusuperobject(47,4,18,"Dewijl wij niet aanmerken de dingen, die men ziet, maar de dingen, die men niet ziet; want de dingen, die men ziet, zijn tijdelijk, maar de dingen, die men niet ziet, zijn eeuwig."));
dusuperobject.biblemap.put("b47_5_1", new dusuperobject(47,5,1,"Want wij weten, dat, zo ons aardse huis dezes tabernakels gebroken wordt, wij een gebouw van God hebben, een huis niet met handen gemaakt, maar eeuwig in de hemelen."));
dusuperobject.biblemap.put("b47_5_2", new dusuperobject(47,5,2,"Want ook in dezen zuchten wij, verlangende met onze woonstede, die uit den hemel is, overkleed te worden."));
dusuperobject.biblemap.put("b47_5_3", new dusuperobject(47,5,3,"Zo wij ook bekleed en niet naakt zullen gevonden worden."));
dusuperobject.biblemap.put("b47_5_4", new dusuperobject(47,5,4,"Want ook wij, die in dezen tabernakel zijn, zuchten, bezwaard zijnde; nademaal wij niet willen ontkleed, maar overkleed worden, opdat het sterfelijke van het leven verslonden worde."));
dusuperobject.biblemap.put("b47_5_5", new dusuperobject(47,5,5,"Die ons nu tot ditzelfde bereid heeft, is God, Die ons ook het onderpand des Geestes gegeven heeft."));
dusuperobject.biblemap.put("b47_5_6", new dusuperobject(47,5,6,"Wij hebben dan altijd goeden moed, en weten, dat wij, inwonende in het lichaam, uitwonen van den Heere;"));
dusuperobject.biblemap.put("b47_5_7", new dusuperobject(47,5,7,"(Want wij wandelen door geloof en niet door aanschouwen.)"));
dusuperobject.biblemap.put("b47_5_8", new dusuperobject(47,5,8,"Maar wij hebben goeden moed, en hebben meer behagen om uit het lichaam uit te wonen, en bij den Heere in te wonen."));
dusuperobject.biblemap.put("b47_5_9", new dusuperobject(47,5,9,"Daarom zijn wij ook zeer begerig, hetzij inwonende, hetzij uitwonende, om Hem welbehagelijk te zijn."));
dusuperobject.biblemap.put("b47_5_10", new dusuperobject(47,5,10,"Want wij allen moeten geopenbaard worden voor den rechterstoel van Christus, opdat een iegelijk wegdrage, hetgeen door het lichaam geschiedt, naardat hij gedaan heeft, hetzij goed, hetzij kwaad."));
dusuperobject.biblemap.put("b47_5_11", new dusuperobject(47,5,11,"Wij dan, wetende den schrik des Heeren, bewegen de mensen tot het geloof, en zijn Gode openbaar geworden; doch ik hoop ook in uw gewetens geopenbaard te zijn."));
dusuperobject.biblemap.put("b47_5_12", new dusuperobject(47,5,12,"Want wij prijzen onszelven u niet wederom aan, maar wij geven u oorzaak van roem over ons, opdat gij stof zoudt hebben tegen degenen, die in het aangezicht roemen en niet in het hart."));
dusuperobject.biblemap.put("b47_5_13", new dusuperobject(47,5,13,"Want hetzij dat wij uitzinnig zijn, wij zijn het Gode; hetzij dat wij gematigd van zinnen zijn, wij zijn het ulieden."));
dusuperobject.biblemap.put("b47_5_14", new dusuperobject(47,5,14,"Want de liefde van Christus dringt ons;"));
dusuperobject.biblemap.put("b47_5_15", new dusuperobject(47,5,15,"Als die dit oordelen, dat, indien Een voor allen gestorven is, zij dan allen gestorven zijn. En Hij is voor allen gestorven, opdat degenen, die leven, niet meer zichzelven zouden leven, maar Dien, Die voor hen gestorven en opgewekt is."));
dusuperobject.biblemap.put("b47_5_16", new dusuperobject(47,5,16,"Zo dan, wij kennen van nu aan niemand naar het vlees; en indien wij ook Christus naar het vlees gekend hebben, nochtans kennen wij Hem nu niet meer naar het vlees."));
dusuperobject.biblemap.put("b47_5_17", new dusuperobject(47,5,17,"Zo dan, indien iemand in Christus is, die is een nieuw schepsel; het oude is voorbijgegaan, ziet, het is alles nieuw geworden."));
dusuperobject.biblemap.put("b47_5_18", new dusuperobject(47,5,18,"En al deze dingen zijn uit God, Die ons met Zichzelven verzoend heeft door Jezus Christus, en ons de bediening der verzoening gegeven heeft."));
dusuperobject.biblemap.put("b47_5_19", new dusuperobject(47,5,19,"Want God was in Christus de wereld met Zichzelven verzoenende, hun zonden hun niet toerekenende; en heeft het woord der verzoening in ons gelegd."));
dusuperobject.biblemap.put("b47_5_20", new dusuperobject(47,5,20,"Zo zijn wij dan gezanten van Christus wege, alsof God door ons bade; wij bidden van Christus wege: laat u met God verzoenen."));
dusuperobject.biblemap.put("b47_5_21", new dusuperobject(47,5,21,"Want Dien, Die geen zonde gekend heeft, heeft Hij zonde voor ons gemaakt, opdat wij zouden worden rechtvaardigheid Gods in Hem."));
dusuperobject.biblemap.put("b47_6_1", new dusuperobject(47,6,1,"En wij, als medearbeidende, bidden u ook, dat gij de genade Gods niet tevergeefs moogt ontvangen hebben."));
dusuperobject.biblemap.put("b47_6_2", new dusuperobject(47,6,2,"Want Hij zegt: In den aangenamen tijd heb Ik u verhoord, en in den dag der zaligheid heb Ik u geholpen. Ziet, nu is het de welaangename tijd, ziet, nu is het de dag der zaligheid!"));
dusuperobject.biblemap.put("b47_6_3", new dusuperobject(47,6,3,"Wij geven geen aanstoot in enig ding, opdat de bediening niet gelasterd worde."));
dusuperobject.biblemap.put("b47_6_4", new dusuperobject(47,6,4,"Maar wij, als dienaars van God, maken onszelven in alles aangenaam, in vele verdraagzaamheid, in verdrukkingen, in noden, in benauwdheden,"));
dusuperobject.biblemap.put("b47_6_5", new dusuperobject(47,6,5,"In slagen, in gevangenissen, in beroerten, in arbeid, in waken, in vasten,"));
dusuperobject.biblemap.put("b47_6_6", new dusuperobject(47,6,6,"In reinheid, in kennis, in lankmoedigheid, in goedertierenheid, in den Heiligen Geest, in ongeveinsde liefde,"));
dusuperobject.biblemap.put("b47_6_7", new dusuperobject(47,6,7,"In het woord der waarheid, in de kracht van God, door de wapenen der gerechtigheid aan de rechter en aan de linker zijde;"));
dusuperobject.biblemap.put("b47_6_8", new dusuperobject(47,6,8,"Door eer en oneer, door kwaad gerucht en goed gerucht; als verleiders, en nochtans waarachtigen;"));
dusuperobject.biblemap.put("b47_6_9", new dusuperobject(47,6,9,"Als onbekenden, en nochtans bekend; als stervenden, en ziet, wij leven; als getuchtigd, en niet gedood;"));
dusuperobject.biblemap.put("b47_6_10", new dusuperobject(47,6,10,"Als droevig zijnde, doch altijd blijde; als arm, doch velen rijk makende; als niets hebbende, en nochtans alles bezittende."));
dusuperobject.biblemap.put("b47_6_11", new dusuperobject(47,6,11,"Onze mond is opengedaan tegen u, o Korinthiers, ons hart is uitgebreid."));
dusuperobject.biblemap.put("b47_6_12", new dusuperobject(47,6,12,"Gij zijt niet nauw in ons, maar gij zijt nauw in uw ingewanden."));
dusuperobject.biblemap.put("b47_6_13", new dusuperobject(47,6,13,"Nu, om dezelfde vergelding te doen,, ik spreek als tot mijn kinderen) zo wordt gij ook uitgebreid."));
dusuperobject.biblemap.put("b47_6_14", new dusuperobject(47,6,14,"Trekt niet een ander juk aan met de ongelovigen; want wat mededeel heeft de gerechtigheid met de ongerechtigheid, en wat gemeenschap heeft het licht met de duisternis?"));
dusuperobject.biblemap.put("b47_6_15", new dusuperobject(47,6,15,"En wat samenstemming heeft Christus met Belial, of wat deel heeft de gelovige met den ongelovige?"));
dusuperobject.biblemap.put("b47_6_16", new dusuperobject(47,6,16,"Of wat samenvoeging heeft de tempel Gods met de afgoden? Want gij zijt de tempel des levenden Gods; gelijkerwijs God gezegd heeft: Ik zal in hen wonen, en Ik zal onder hen wandelen; en Ik zal hun God zijn, en zij zullen Mij een volk zijn."));
dusuperobject.biblemap.put("b47_6_17", new dusuperobject(47,6,17,"Daarom gaat uit het midden van hen, en scheidt u af, zegt de Heere, en raakt niet aan hetgeen onrein is, en Ik zal ulieden aannemen."));
dusuperobject.biblemap.put("b47_6_18", new dusuperobject(47,6,18,"En Ik zal u tot een Vader zijn, en gij zult Mij tot zonen en dochteren zijn, zegt de Heere, de Almachtige."));
dusuperobject.biblemap.put("b47_7_1", new dusuperobject(47,7,1,"Dewijl wij dan deze beloften hebben, geliefden, laat ons onszelven reinigen van alle besmetting des vleses en des geestes, voleindigende de heiligmaking in de vreze Gods."));
dusuperobject.biblemap.put("b47_7_2", new dusuperobject(47,7,2,"Geeft ons plaats; wij hebben niemand verongelijkt, wij hebben niemand verdorven, wij hebben bij niemand ons voordeel gezocht."));
dusuperobject.biblemap.put("b47_7_3", new dusuperobject(47,7,3,"Ik zeg dit niet tot uw veroordeling; want ik heb te voren gezegd, dat gij in onze harten zijt, om samen te sterven en samen te leven."));
dusuperobject.biblemap.put("b47_7_4", new dusuperobject(47,7,4,"Ik heb vele vrijmoedigheid in het spreken tegen u, ik heb veel roems over u; ik ben vervuld met vertroosting; ik ben zeer overvloedig van blijdschap in al onze verdrukking."));
dusuperobject.biblemap.put("b47_7_5", new dusuperobject(47,7,5,"Want ook, als wij in Macedonie gekomen zijn, zo heeft ons vlees geen rust gehad; maar wij waren in alles verdrukt; van buiten was strijd, van binnen vrees."));
dusuperobject.biblemap.put("b47_7_6", new dusuperobject(47,7,6,"Doch God, Die de nederigen vertroost, heeft ons getroost door de komst van Titus."));
dusuperobject.biblemap.put("b47_7_7", new dusuperobject(47,7,7,"En niet alleen door zijn komst, maar ook door de vertroosting, met welke hij over u vertroost is geweest, als hij ons verhaalde uw verlangen, uw kermen, uw ijver voor mij; alzo dat ik te meer verblijd ben geweest."));
dusuperobject.biblemap.put("b47_7_8", new dusuperobject(47,7,8,"Want hoewel ik u in den zendbrief bedroefd heb, het berouwt mij niet, hoewel het mij berouwd heeft; want ik zie, dat dezelve zendbrief, hoewel voor een kleinen tijd, u bedroefd heeft."));
dusuperobject.biblemap.put("b47_7_9", new dusuperobject(47,7,9,"Nu verblijde ik mij, niet omdat gij bedroefd zijt geweest, maar omdat gij bedroefd zijt geweest tot bekering; want gij zijt bedroefd geweest naar God, zodat gij in geen ding schade van ons geleden hebt."));
dusuperobject.biblemap.put("b47_7_10", new dusuperobject(47,7,10,"Want de droefheid naar God werkt een onberouwelijke bekering tot zaligheid; maar de droefheid der wereld werkt den dood."));
dusuperobject.biblemap.put("b47_7_11", new dusuperobject(47,7,11,"Want ziet, ditzelfde dat gij naar God zijt bedroefd geworden, hoe grote naarstigheid heeft het in u gewrocht? Ja, verantwoording, ja, onlust, ja, vrees, ja, verlangen, ja, ijver, ja, wraak; in alles hebt gij uzelven bewezen rein te zijn in deze zaak."));
dusuperobject.biblemap.put("b47_7_12", new dusuperobject(47,7,12,"Hoewel ik dan aan u geschreven heb, dat is niet om diens wil, die onrecht gedaan had, noch om diens wil, die onrecht gedaan was; maar opdat onze vlijtigheid voor u bij u openbaar zou worden, in de tegenwoordigheid Gods."));
dusuperobject.biblemap.put("b47_7_13", new dusuperobject(47,7,13,"Daarom zijn wij vertroost geworden over uw vertroosting; en zijn nog overvloediger verblijd geworden over de blijdschap van Titus, omdat zijn geest van u allen verkwikt is geworden."));
dusuperobject.biblemap.put("b47_7_14", new dusuperobject(47,7,14,"Want indien ik iets bij hem over u geroemd heb, zo ben ik niet beschaamd geworden; maar gelijk wij alles met waarheid tot u gesproken hebben, alzo is ook onze roem, dien ik bij Titus geroemd heb, waarheid geworden."));
dusuperobject.biblemap.put("b47_7_15", new dusuperobject(47,7,15,"En zijn innerlijke bewegingen zijn te overvloediger jegens u, als hij uw aller gehoorzaamheid overdenkt, hoe gij hem met vreze en beven hebt ontvangen."));
dusuperobject.biblemap.put("b47_7_16", new dusuperobject(47,7,16,"Ik verblijde mij dan, dat ik in alles van u vertrouwen mag hebben."));
dusuperobject.biblemap.put("b47_8_1", new dusuperobject(47,8,1,"Voorts maken wij u bekend, broeders, de genade van God, die in de Gemeenten van Macedonie gegeven is."));
dusuperobject.biblemap.put("b47_8_2", new dusuperobject(47,8,2,"Dat in vele beproeving der verdrukking de overvloed hunner blijdschap, en hun zeer diepe armoede overvloedig geweest is tot den rijkdom hunner goeddadigheid."));
dusuperobject.biblemap.put("b47_8_3", new dusuperobject(47,8,3,"Want zij zijn naar vermogen (ik betuig het), ja, boven vermogen gewillig geweest;"));
dusuperobject.biblemap.put("b47_8_4", new dusuperobject(47,8,4,"Ons met vele vermaning biddende, dat wij wilden aannemen de gave en de gemeenschap dezer bediening, die voor de heiligen geschiedt."));
dusuperobject.biblemap.put("b47_8_5", new dusuperobject(47,8,5,"En zij deden niet alleen, gelijk wij gehoopt hadden, maar gaven zichzelven eerst aan den Heere en daarna aan ons, door den wil van God."));
dusuperobject.biblemap.put("b47_8_6", new dusuperobject(47,8,6,"Alzo dat wij Titus vermaanden, dat, gelijk hij te voren begonnen had, hij ook alzo nog deze gave bij u voleinden zou."));
dusuperobject.biblemap.put("b47_8_7", new dusuperobject(47,8,7,"Zo dan, gelijk gij in alles overvloedig zijt, in geloof, en in woord, en in kennis, en in alle naarstigheid, en in uw liefde tot ons, ziet, dat gij ook in deze gave overvloedig zijt."));
dusuperobject.biblemap.put("b47_8_8", new dusuperobject(47,8,8,"Ik zeg dit niet als gebiedende, maar als door de naarstigheid van anderen ook de oprechtheid uwer liefde beproevende."));
dusuperobject.biblemap.put("b47_8_9", new dusuperobject(47,8,9,"Want gij weet de genade van onzen Heere Jezus Christus, dat Hij om uwentwil is arm geworden, daar Hij rijk was, opdat gij door Zijn armoede zoudt rijk worden."));
dusuperobject.biblemap.put("b47_8_10", new dusuperobject(47,8,10,"En ik zeg in dezen mijn mening; want dit is u oorbaar, als die niet alleen het doen, maar ook het willen van over een jaar te voren hebt begonnen."));
dusuperobject.biblemap.put("b47_8_11", new dusuperobject(47,8,11,"Maar nu voleindigt ook het doen; opdat, gelijk als er geweest is de volvaardigheid des gemoeds om te willen, er ook alzo zij het voleindigen uit hetgeen gij hebt."));
dusuperobject.biblemap.put("b47_8_12", new dusuperobject(47,8,12,"Want indien te voren de volvaardigheid des gemoeds daar is, zo is iemand aangenaam naar hetgeen hij heeft, niet naar hetgeen hij niet heeft."));
dusuperobject.biblemap.put("b47_8_13", new dusuperobject(47,8,13,"Want dit zeg ik niet, opdat anderen zouden verlichting hebben, en gij verdrukking;"));
dusuperobject.biblemap.put("b47_8_14", new dusuperobject(47,8,14,"Maar opdat uit gelijkheid, in dezen tegenwoordigen tijd, uw overvloed zij om hun gebrek te vervullen; opdat ook hun overvloed zij om uw gebrek te vervullen, opdat er gelijkheid worde."));
dusuperobject.biblemap.put("b47_8_15", new dusuperobject(47,8,15,"Gelijk geschreven is: Die veel verzameld had, had niet over; en die weinig verzameld had, had niet te weinig."));
dusuperobject.biblemap.put("b47_8_16", new dusuperobject(47,8,16,"Doch Gode zij dank, Die dezelfde naarstigheid voor u in het hart van Titus gegeven heeft;"));
dusuperobject.biblemap.put("b47_8_17", new dusuperobject(47,8,17,"Dat hij de vermaning heeft aangenomen, en zeer naarstig zijnde, gewillig tot u gereisd is."));
dusuperobject.biblemap.put("b47_8_18", new dusuperobject(47,8,18,"En wij hebben ook met hem gezonden den broeder, die lof heeft in het Evangelie door al de Gemeenten;"));
dusuperobject.biblemap.put("b47_8_19", new dusuperobject(47,8,19,"En dat niet alleen, maar hij is ook van de Gemeenten verkoren, om met ons te reizen met deze gave, die van ons bediend wordt tot de heerlijkheid des Heeren Zelven, en de volvaardigheid uws gemoeds;"));
dusuperobject.biblemap.put("b47_8_20", new dusuperobject(47,8,20,"Dit verhoedende, dat ons niemand moge lasteren in dezen overvloed, die van ons wordt bediend;"));
dusuperobject.biblemap.put("b47_8_21", new dusuperobject(47,8,21,"Als die bezorgen, hetgeen eerlijk is, niet alleen voor den Heere, maar ook voor de mensen."));
dusuperobject.biblemap.put("b47_8_22", new dusuperobject(47,8,22,"Wij hebben ook met hen gezonden onzen broeder, welken wij in vele dingen dikmaals beproefd hebben, dat hij naarstig is; en nu veel naarstiger, door het groot vertrouwen, dat hij heeft tot ulieden."));
dusuperobject.biblemap.put("b47_8_23", new dusuperobject(47,8,23,"Hetzij dan Titus, hij is mijn metgezel en medearbeider bij u; hetzij onze broeders, zij zijn afgezanten der Gemeenten, en een eer van Christus."));
dusuperobject.biblemap.put("b47_8_24", new dusuperobject(47,8,24,"Bewijst dan aan hen de bewijzing uwer liefde, en van onzen roem van u, ook voor het aangezicht der Gemeenten."));
dusuperobject.biblemap.put("b47_9_1", new dusuperobject(47,9,1,"Want van de bediening, die voor de heiligen geschiedt, is mij onnodig aan u te schrijven."));
dusuperobject.biblemap.put("b47_9_2", new dusuperobject(47,9,2,"Want ik weet de volvaardigheid uws gemoeds, van welke ik roem over u bij de Macedoniers, dat Achaje van over een jaar bereid is geweest; en de ijver, van u begonnen, heeft er velen verwekt."));
dusuperobject.biblemap.put("b47_9_3", new dusuperobject(47,9,3,"Maar ik heb deze broeders gezonden, opdat onze roem, dien wij over u hebben, niet zou ijdel gemaakt worden in dezen dele; opdat (gelijk ik gezegd heb) gij bereid moogt zijn;"));
dusuperobject.biblemap.put("b47_9_4", new dusuperobject(47,9,4,"En dat niet mogelijk, zo de Macedoniers met mij kwamen, en u onbereid vonden, wij (opdat wij niet zeggen: gij) beschaamd worden in deze vasten grond der roeming."));
dusuperobject.biblemap.put("b47_9_5", new dusuperobject(47,9,5,"Ik heb dan nodig geacht deze broeders te vermanen, dat zij eerst tot u zouden komen, en voorbereiden uw te voren aangedienden zegen; opdat die gereed zij, alzo als een zegen, en niet als een vrekheid."));
dusuperobject.biblemap.put("b47_9_6", new dusuperobject(47,9,6,"En dit zeg ik: Die spaarzamelijk zaait, zal ook spaarzamelijk maaien; en die in zegeningen zaait, zal ook in zegeningen maaien."));
dusuperobject.biblemap.put("b47_9_7", new dusuperobject(47,9,7,"Een iegelijk doe, gelijk hij in zijn hart voorneemt; niet uit droefheid, of uit nooddwang; want God heeft een blijmoedigen gever lief."));
dusuperobject.biblemap.put("b47_9_8", new dusuperobject(47,9,8,"En God is machtig alle genade te doen overvloedig zijn in u; opdat gij in alles te allen tijd, alle genoegzaamheid hebbende, tot alle goed werk overvloedig moogt zijn."));
dusuperobject.biblemap.put("b47_9_9", new dusuperobject(47,9,9,"Gelijk er geschreven is: Hij heeft gestrooid, hij heeft den armen gegeven; Zijn gerechtigheid blijft in der eeuwigheid."));
dusuperobject.biblemap.put("b47_9_10", new dusuperobject(47,9,10,"Doch Die het zaad den zaaier verleent, Die verlene ook brood tot spijze, en vermenigvuldige uw gezaaisel, en vermeerdere de vruchten uwer gerechtigheid;"));
dusuperobject.biblemap.put("b47_9_11", new dusuperobject(47,9,11,"Dat gij in alles rijk wordt tot alle goeddadigheid, welke door ons werkt dankzegging tot God."));
dusuperobject.biblemap.put("b47_9_12", new dusuperobject(47,9,12,"Want de bediening van dezen dienst vervult niet alleen het gebrek der heiligen, maar is ook overvloedig door vele dankzeggingen tot God;"));
dusuperobject.biblemap.put("b47_9_13", new dusuperobject(47,9,13,"Dewijl zij door de beproeving dezer bediening God verheerlijken over de onderwerping uwer belijdenis onder het Evangelie van Christus, en over de goeddadigheid der mededeling aan hen en aan allen;"));
dusuperobject.biblemap.put("b47_9_14", new dusuperobject(47,9,14,"En door hun gebed voor u, welke naar u verlangen, om de uitnemende genade Gods over u."));
dusuperobject.biblemap.put("b47_9_15", new dusuperobject(47,9,15,"Doch Gode zij dank voor Zijn onuitsprekelijke gave."));
dusuperobject.biblemap.put("b47_10_1", new dusuperobject(47,10,1,"Voorts ik Paulus zelf bid u, door de zachtmoedigheid en goedertierenheid van Christus, die, tegenwoordig zijnde, wel gering ben onder u, maar afwezend stout ben tegen u;"));
dusuperobject.biblemap.put("b47_10_2", new dusuperobject(47,10,2,"Ik bid dan, dat ik, tegenwoordig zijnde, niet stout moge zijn met die vrijmoedigheid, waarmede ik geacht word stoutelijk gehandeld te hebben tegen sommigen, die ons achten, alsof wij naar het vlees wandelden."));
dusuperobject.biblemap.put("b47_10_3", new dusuperobject(47,10,3,"Want wandelende in het vlees, voeren wij den krijg niet naar het vlees;"));
dusuperobject.biblemap.put("b47_10_4", new dusuperobject(47,10,4,"Want de wapenen van onzen krijg zijn niet vleselijk, maar krachtig door God, tot nederwerping der sterkten;"));
dusuperobject.biblemap.put("b47_10_5", new dusuperobject(47,10,5,"Dewijl wij de overleggingen ter nederwerpen, en alle hoogte, die zich verheft tegen de kennis van God, en alle gedachte gevangen leiden tot de gehoorzaamheid van Christus;"));
dusuperobject.biblemap.put("b47_10_6", new dusuperobject(47,10,6,"En gereed hebben, hetgeen dient om te wreken alle ongehoorzaamheid, wanneer uw gehoorzaamheid zal vervuld zijn."));
dusuperobject.biblemap.put("b47_10_7", new dusuperobject(47,10,7,"Ziet gij aan wat voor ogen is? Indien iemand bij zichzelven betrouwt, dat hij van Christus is, die denke dit wederom uit zichzelven, dat gelijkerwijs hij van Christus is, alzo ook wij van Christus zijn."));
dusuperobject.biblemap.put("b47_10_8", new dusuperobject(47,10,8,"Want indien ik ook iets overvloediger zou roemen van onze macht, welke de Heere ons gegeven heeft tot stichting, en niet tot uw nederwerping, zo zal ik niet beschaamd worden;"));
dusuperobject.biblemap.put("b47_10_9", new dusuperobject(47,10,9,"Opdat ik niet zou schijnen, alsof ik u door de brieven wilde verschrikken."));
dusuperobject.biblemap.put("b47_10_10", new dusuperobject(47,10,10,"Want de brieven (zeggen zij) zijn wel gewichtig en krachtig; maar de tegenwoordigheid des lichaams is zwak, en de rede is verachtelijk."));
dusuperobject.biblemap.put("b47_10_11", new dusuperobject(47,10,11,"Dezulke bedenke dit, dat hoedanigen wij zijn in het woord door brieven, als wij afwezig zijn, wij ook zodanigen zijn inderdaad, als wij tegenwoordig zijn."));
dusuperobject.biblemap.put("b47_10_12", new dusuperobject(47,10,12,"Want wij durven onszelven niet rekenen of vergelijken met sommigen, die zichzelven prijzen; maar deze verstaan niet, dat zij zichzelven met zichzelven meten, en zichzelven met zichzelven vergelijken."));
dusuperobject.biblemap.put("b47_10_13", new dusuperobject(47,10,13,"Doch wij zullen niet roemen buiten de maat; maar dat wij, naar de maat des regels, welke maat ons God toegedeeld heeft, ook tot u toe zijn gekomen."));
dusuperobject.biblemap.put("b47_10_14", new dusuperobject(47,10,14,"Want wij strekken onszelven niet te wijd uit, als die tot u niet zouden komen; want wij zijn ook gekomen tot u toe, in het Evangelie van Christus;"));
dusuperobject.biblemap.put("b47_10_15", new dusuperobject(47,10,15,"Niet roemende buiten de maat in anderer lieden arbeid, maar hebbende hoop, als uw geloof zal gewassen zijn, dat wij onder ulieden overvloediglijk zullen vergroot worden naar onzen regel;"));
dusuperobject.biblemap.put("b47_10_16", new dusuperobject(47,10,16,"Om het Evangelie te verkondigen in de plaatsen, die op gene zijde van u gelegen zijn; niet om te roemen in eens anders regel over hetgeen alrede bereid is."));
dusuperobject.biblemap.put("b47_10_17", new dusuperobject(47,10,17,"Doch wie roemt, die roeme in den Heere."));
dusuperobject.biblemap.put("b47_10_18", new dusuperobject(47,10,18,"Want niet die zichzelven prijst, maar dien de Heere prijst, die is beproefd."));
dusuperobject.biblemap.put("b47_11_1", new dusuperobject(47,11,1,"Och, of gij mij een weinig verdroegt in de onwijsheid; ja ook, verdraagt mij!"));
dusuperobject.biblemap.put("b47_11_2", new dusuperobject(47,11,2,"Want ik ben ijverig over u met een ijver Gods; want ik heb ulieden toebereid, om u als een reine maagd aan een man voor te stellen, namelijk aan Christus."));
dusuperobject.biblemap.put("b47_11_3", new dusuperobject(47,11,3,"Doch ik vrees, dat niet enigszins, gelijk de slang Eva door haar arglistigheid bedrogen heeft, alzo uw zinnen bedorven worden, om af te wijken van de eenvoudigheid, die in Christus is."));
dusuperobject.biblemap.put("b47_11_4", new dusuperobject(47,11,4,"Want indien degene, die komt, een anderen Jezus predikte, dien wij niet gepredikt hebben, of indien gij een anderen geest ontvingt, dien gij niet hebt ontvangen, of een ander Evangelie, dat gij niet hebt aangenomen, zo verdroegt gij hem met recht."));
dusuperobject.biblemap.put("b47_11_5", new dusuperobject(47,11,5,"Want ik acht, dat ik nergens minder in ben geweest dan de uitnemendste apostelen."));
dusuperobject.biblemap.put("b47_11_6", new dusuperobject(47,11,6,"En indien ik ook slecht ben in woorden, nochtans ben ik het niet in wetenschap; maar alleszins zijn wij in alle dingen onder u openbaar geworden."));
dusuperobject.biblemap.put("b47_11_7", new dusuperobject(47,11,7,"Heb ik zonde gedaan, als ik mijzelven vernederd heb, opdat gij zoudt verhoogd worden, overmits ik u het Evangelie Gods om niet verkondigd heb?"));
dusuperobject.biblemap.put("b47_11_8", new dusuperobject(47,11,8,"Ik heb andere Gemeenten beroofd, bezoldiging van haar nemende, om u te bedienen; en als ik bij u tegenwoordig was en gebrek had, ben ik niemand lastig gevallen."));
dusuperobject.biblemap.put("b47_11_9", new dusuperobject(47,11,9,"Want mijn gebrek hebben de broeders vervuld, die van Macedonie kwamen; en ik heb mijzelven in alles gehouden zonder u te bezwaren, en zal mij nog alzo houden."));
dusuperobject.biblemap.put("b47_11_10", new dusuperobject(47,11,10,"De waarheid van Christus is in mij, dat deze roem in de gewesten van Achaje aan mij niet zal verhinderd worden."));
dusuperobject.biblemap.put("b47_11_11", new dusuperobject(47,11,11,"Waarom? Is het, omdat ik u niet liefheb? God weet het!"));
dusuperobject.biblemap.put("b47_11_12", new dusuperobject(47,11,12,"Maar wat ik doe, dat zal ik nog doen, om de oorzaak af te snijden dengenen, die oorzaak hebben willen, opdat zij in hetgeen zij roemen, bevonden mochten worden gelijk als wij."));
dusuperobject.biblemap.put("b47_11_13", new dusuperobject(47,11,13,"Want zulke valse apostelen zijn bedriegelijke arbeiders, zich veranderende in apostelen van Christus."));
dusuperobject.biblemap.put("b47_11_14", new dusuperobject(47,11,14,"En het is geen wonder; want de satan zelf verandert zich in een engel des lichts."));
dusuperobject.biblemap.put("b47_11_15", new dusuperobject(47,11,15,"Zo is het dan niets groots, indien ook zijn dienaars zich veranderen, als waren zij dienaars der gerechtigheid; van welke het einde zal zijn naar hun werken."));
dusuperobject.biblemap.put("b47_11_16", new dusuperobject(47,11,16,"Ik zeg wederom, dat niemand mene, dat ik onwijs ben; doch zo niet, neemt mij dan aan als een onwijze, opdat ik ook een weinig moge roemen."));
dusuperobject.biblemap.put("b47_11_17", new dusuperobject(47,11,17,"Dat ik spreek, spreek ik niet naar den Heere, maar als in onwijsheid, in deze vasten grond der roeming."));
dusuperobject.biblemap.put("b47_11_18", new dusuperobject(47,11,18,"Dewijl velen roemen naar het vlees, zo zal ik ook roemen."));
dusuperobject.biblemap.put("b47_11_19", new dusuperobject(47,11,19,"Want gij verdraagt gaarne de onwijzen, dewijl gij wijs zijt."));
dusuperobject.biblemap.put("b47_11_20", new dusuperobject(47,11,20,"Want gij verdraagt het, zo u iemand dienstbaar maakt, zo u iemand opeet, zo iemand van u neemt, zo zich iemand verheft, zo u iemand in het aangezicht slaat."));
dusuperobject.biblemap.put("b47_11_21", new dusuperobject(47,11,21,"Ik zeg dit naar oneer, gelijk of wij zwak waren geweest; maar waarin iemand stout is (ik spreek in onwijsheid), daarin ben ik ook stout."));
dusuperobject.biblemap.put("b47_11_22", new dusuperobject(47,11,22,"Zijn zij Hebreen? Ik ook. Zijn zij Israelieten? Ik ook. Zijn zij het zaad van Abraham? Ik ook."));
dusuperobject.biblemap.put("b47_11_23", new dusuperobject(47,11,23,"Zijn zij dienaars van Christus? (ik spreek onwijs zijnde) ik ben boven hen; in arbeid overvloediger, in slagen uitnemender, in gevangenissen overvloediger, in doods gevaar menigmaal."));
dusuperobject.biblemap.put("b47_11_24", new dusuperobject(47,11,24,"Van de Joden heb ik veertig slagen min een, vijfmaal ontvangen."));
dusuperobject.biblemap.put("b47_11_25", new dusuperobject(47,11,25,"Driemaal ben ik met roeden gegeseld geweest, eens ben ik gestenigd, driemaal heb ik schipbreuk geleden, een gansen nacht en dag heb ik in de diepte doorgebracht."));
dusuperobject.biblemap.put("b47_11_26", new dusuperobject(47,11,26,"In het reizen menigmaal in gevaren van rivieren, in gevaren van moordenaars, in gevaren van mijn geslacht, in gevaren van de heidenen, in gevaren in de stad, in gevaren in de woestijn, in gevaren op de zee, in gevaren onder de valse broeders;"));
dusuperobject.biblemap.put("b47_11_27", new dusuperobject(47,11,27,"In arbeid en moeite, in waken menigmaal, in honger en dorst, in vasten menigmaal, in koude en naaktheid."));
dusuperobject.biblemap.put("b47_11_28", new dusuperobject(47,11,28,"Zonder de dingen, die van buiten zijn, overvalt mij dagelijks de zorg van al de Gemeenten."));
dusuperobject.biblemap.put("b47_11_29", new dusuperobject(47,11,29,"Wie is er zwak, dat ik niet zwak ben? Wie wordt er geergerd, dat ik niet brande?"));
dusuperobject.biblemap.put("b47_11_30", new dusuperobject(47,11,30,"Indien men moet roemen, zo zal ik roemen de dingen mijner zwakheid."));
dusuperobject.biblemap.put("b47_11_31", new dusuperobject(47,11,31,"De God en Vader van onzen Heere Jezus Christus, Die geprezen is in der eeuwigheid, weet, dat ik niet lieg."));
dusuperobject.biblemap.put("b47_11_32", new dusuperobject(47,11,32,"De stadhouder van den koning Aretas in Damaskus, bezette de stad der Damaskenen, willende mij vangen;"));
dusuperobject.biblemap.put("b47_11_33", new dusuperobject(47,11,33,"En ik werd door een venster in een mand over den muur nedergelaten, en ontvlood zijn handen."));
dusuperobject.biblemap.put("b47_12_1", new dusuperobject(47,12,1,"Te roemen is mij waarlijk niet oorbaar; want ik zal komen tot gezichten en openbaringen des Heeren."));
dusuperobject.biblemap.put("b47_12_2", new dusuperobject(47,12,2,"Ik ken een mens in Christus, voor veertien jaren (of het geschied zij in het lichaam, weet ik niet, of buiten het lichaam, weet ik niet, God weet het), dat de zodanige opgetrokken is geweest tot in den derden hemel;"));
dusuperobject.biblemap.put("b47_12_3", new dusuperobject(47,12,3,"En ik ken een zodanig mens (of het in het lichaam, of buiten het lichaam geschied zij, weet ik niet, God weet het),"));
dusuperobject.biblemap.put("b47_12_4", new dusuperobject(47,12,4,"Dat hij opgetrokken is geweest in het paradijs, en gehoord heeft onuitsprekelijke woorden, die het een mens niet geoorloofd is te spreken."));
dusuperobject.biblemap.put("b47_12_5", new dusuperobject(47,12,5,"Van den zodanige zal ik roemen, doch van mijzelven zal ik niet roemen, dan in mijn zwakheden."));
dusuperobject.biblemap.put("b47_12_6", new dusuperobject(47,12,6,"Want zo ik roemen wil, ik zal niet onwijs zijn, want ik zal de waarheid zeggen; maar ik houde daarvan af, opdat niemand van mij denke boven hetgeen hij ziet, dat ik ben, of dat hij uit mij hoort."));
dusuperobject.biblemap.put("b47_12_7", new dusuperobject(47,12,7,"En opdat ik mij door de uitnemendheid der openbaringen niet zou verheffen, zo is mij gegeven een scherpe doorn in het vlees, namelijk een engel des satans, dat hij mij met vuisten slaan zou, opdat ik mij niet zou verheffen."));
dusuperobject.biblemap.put("b47_12_8", new dusuperobject(47,12,8,"Hierover heb ik den Heere driemaal gebeden, opdat hij van mij zou wijken."));
dusuperobject.biblemap.put("b47_12_9", new dusuperobject(47,12,9,"En Hij heeft tot mij gezegd: Mijn genade is u genoeg; want Mijn kracht wordt in zwakheid volbracht. Zo zal ik dan veel liever roemen in mijn zwakheden, opdat de kracht van Christus in mij wone."));
dusuperobject.biblemap.put("b47_12_10", new dusuperobject(47,12,10,"Daarom heb ik een welbehagen in zwakheden, in smaadheden, in noden, in vervolgingen, in benauwdheden, om Christus' wil; want als ik zwak ben, dan ben ik machtig."));
dusuperobject.biblemap.put("b47_12_11", new dusuperobject(47,12,11,"Ik ben roemende onwijs geworden; gij hebt mij genoodzaakt, want ik behoorde van u geprezen te zijn; want ik ben in geen ding minder geweest dan de uitnemendste apostelen, hoewel ik niets ben."));
dusuperobject.biblemap.put("b47_12_12", new dusuperobject(47,12,12,"De merktekenen van een apostel zijn onder u betoond in alle lijdzaamheid, met tekenen, en wonderen, en krachten."));
dusuperobject.biblemap.put("b47_12_13", new dusuperobject(47,12,13,"Want wat is er, waarin gij minder geweest zijt dan de andere Gemeenten, anders, dan dat ikzelf u niet lastig ben geweest? Vergeeft mij dit ongelijk."));
dusuperobject.biblemap.put("b47_12_14", new dusuperobject(47,12,14,"Ziet, ik ben ten derden male gereed, om tot u te komen, en zal u niet lastig zijn; want ik zoek niet het uwe, maar u; want de kinderen moeten niet schatten vergaderen voor de ouders, maar de ouders voor de kinderen."));
dusuperobject.biblemap.put("b47_12_15", new dusuperobject(47,12,15,"En ik zal zeer gaarne de kosten doen, en voor uw zielen ten koste gegeven worden; hoewel ik, u overvloediger beminnende, weiniger bemind worde."));
dusuperobject.biblemap.put("b47_12_16", new dusuperobject(47,12,16,"Doch het zij zo, ik heb u niet bezwaard; maar alzo ik listig was, heb ik u met bedrog gevangen."));
dusuperobject.biblemap.put("b47_12_17", new dusuperobject(47,12,17,"Heb ik door iemand dergenen, die ik tot u gezonden heb, van u mijn voordeel gezocht?"));
dusuperobject.biblemap.put("b47_12_18", new dusuperobject(47,12,18,"Ik heb Titus gebeden, en den broeder medegezonden; heeft ook Titus van u zijn voordeel gezocht? Hebben wij niet in denzelfden geest gewandeld? Hebben wij niet gewandeld in dezelfde voetstappen?"));
dusuperobject.biblemap.put("b47_12_19", new dusuperobject(47,12,19,"Meent gij wederom, dat wij ons bij u verontschuldigen? Wij spreken in de tegenwoordigheid van God in Christus; en dit alles, geliefden, tot uw stichting."));
dusuperobject.biblemap.put("b47_12_20", new dusuperobject(47,12,20,"Want ik vrees, dat als ik gekomen zal zijn, ik u niet enigszins zal vinden zodanigen als ik wil, en dat ik van u zal gevonden worden zodanig als gij niet wilt; dat er niet enigszins zijn twisten, nijdigheden, toorn, gekijf, achterklap, oorblazingen, opgeblazenheden, beroerten;"));
dusuperobject.biblemap.put("b47_12_21", new dusuperobject(47,12,21,"Opdat wederom, als ik zal gekomen zijn, mijn God mij niet vernedere bij u, en ik rouw hebbe over velen, die te voren gezondigd hebben, en die zich niet bekeerd zullen hebben van de onreinigheid, en hoererij, en ontuchtigheid, die zij gedaan hebben."));
dusuperobject.biblemap.put("b47_13_1", new dusuperobject(47,13,1,"Dit is de derde maal, dat ik tot u kom; in den mond van twee of drie getuigen zal alle woord bestaan."));
dusuperobject.biblemap.put("b47_13_2", new dusuperobject(47,13,2,"Ik heb het te voren gezegd, en zeg het te voren als tegenwoordig zijnde de tweede maal, en ik schrijf het nu afwezende aan degenen, die te voren gezondigd hebben, en aan al de anderen, dat, zo ik wederom kom, ik hen niet zal sparen;"));
dusuperobject.biblemap.put("b47_13_3", new dusuperobject(47,13,3,"Dewijl gij zoekt een proeve van Christus, Die in mij spreekt, Welke in u niet zwak is, maar krachtig is onder u."));
dusuperobject.biblemap.put("b47_13_4", new dusuperobject(47,13,4,"Want hoewel Hij gekruist is door zwakheid, zo leeft Hij nochtans door de kracht Gods. Want ook wij zijn zwak in Hem, maar zullen met Hem leven door de kracht Gods in u."));
dusuperobject.biblemap.put("b47_13_5", new dusuperobject(47,13,5,"Onderzoekt uzelven, of gij in het geloof zijt, beproeft uzelven. Of kent gij uzelven niet, dat Jezus Christus in u is? tenzij dat gij enigszins verwerpelijk zijt."));
dusuperobject.biblemap.put("b47_13_6", new dusuperobject(47,13,6,"Doch ik hoop, dat gij zult verstaan, dat wij niet verwerpelijk zijn."));
dusuperobject.biblemap.put("b47_13_7", new dusuperobject(47,13,7,"En ik wens van God, dat gij geen kwaad doet; niet opdat wij beproefd zouden bevonden worden, maar opdat gij het goede zoudt doen, en wij als verwerpelijk zouden zijn."));
dusuperobject.biblemap.put("b47_13_8", new dusuperobject(47,13,8,"Want wij vermogen niets tegen de waarheid, maar voor de waarheid."));
dusuperobject.biblemap.put("b47_13_9", new dusuperobject(47,13,9,"Want wij verblijden ons, wanneer wij zwak zijn, en gij sterk zijt. En wij wensen ook dit, namelijk uw volmaking."));
dusuperobject.biblemap.put("b47_13_10", new dusuperobject(47,13,10,"Daarom schrijf ik, afwezende, deze dingen, opdat ik niet, tegenwoordig zijnde, strengheid zou gebruiken, naar de macht, die mij de Heere gegeven heeft tot opbouwing, en niet tot nederwerping."));
dusuperobject.biblemap.put("b47_13_11", new dusuperobject(47,13,11,"Voorts, broeders, zijt blijde, wordt volmaakt, zijt getroost, zijt eensgezind, leeft in vrede; en de God der liefde en des vredes zal met u zijn."));
dusuperobject.biblemap.put("b47_13_12", new dusuperobject(47,13,12,"Groet elkander met een heiligen kus. U groeten al de heiligen."));
dusuperobject.biblemap.put("b47_13_13", new dusuperobject(47,13,13,"De genade van den Heere Jezus Christus, en de liefde van God, en de gemeenschap des Heiligen Geestes, zij met u allen. Amen."));

}

}