package vi.bible;

public class vibible47 {

public vibible47() {

putmapbible47();

}

private void putmapbible47() {

visuperobject.biblemap.put("b47_1_1", new visuperobject(47,1,1,"Phao-lô, theo ý muốn Ðức Chúa Trời, làm sứ đồ Ðức Chúa Jêsus Christ, cùng người anh em chúng ta là Ti-mô-thê, gởi cho Hội thánh của Ðức Chúa Trời ở thành Cô-rinh-tô, và cho hết thảy thánh đồ ở khắp xứ A-chai:"));
visuperobject.biblemap.put("b47_1_2", new visuperobject(47,1,2,"nguyền xin anh em được ân điển và sự bình an ban cho bởi Ðức Chúa Trời, Cha chúng ta, và bởi Ðức Chúa Jêsus Christ!"));
visuperobject.biblemap.put("b47_1_3", new visuperobject(47,1,3,"Chúc tạ Ðức Chúa Trời, Cha Ðức Chúa Jêsus Christ chúng ta, là Cha hay thương xót, là Ðức Chúa Trời ban mọi sự yên ủi."));
visuperobject.biblemap.put("b47_1_4", new visuperobject(47,1,4,"Ngài yên ủi chúng tôi trong mọi sự khốn nạn, hầu cho nhơn sự yên ủi mà Ngài đã yên ủi chúng tôi, thì chúng tôi cũng có thể yên ủi kẻ khác trong sự khốn nạn nào họ gặp!"));
visuperobject.biblemap.put("b47_1_5", new visuperobject(47,1,5,"Vì như những sự đau đớn của Ðấng Christ chan chứa trong chúng tôi thể nào, thì sự yên ủi của chúng tôi bởi Ðấng Christ mà chứa chan cũng thể ấy."));
visuperobject.biblemap.put("b47_1_6", new visuperobject(47,1,6,"Như vậy, hoặc chúng tôi gặp hoạn nạn, ấy là cho anh em được yên ủi và được rỗi; hoặc chúng tôi được yên ủi, ấy là cho anh em yên ủi, mà sự yên ủi đó được hiện ra bởi anh em chịu cách nhịn nhục những sự đau đớn mà chúng tôi cùng chịu."));
visuperobject.biblemap.put("b47_1_7", new visuperobject(47,1,7,"Sự trông cậy của chúng tôi về anh em thật vững vàng; vì biết rằng bởi anh em có phần trong sự đau đớn, thì cùng có phần trong sự yên ủi vậy."));
visuperobject.biblemap.put("b47_1_8", new visuperobject(47,1,8,"Vả, hỡi anh em, chúng tôi không muốn để anh em chẳng biết sự khổ nạn đã xảy đến cho chúng tôi trong xứ A-si, và chúng tôi đã bị đè nén quá chừng, quá sức mình, đến nỗi mất lòng trông cậy giữ sự sống."));
visuperobject.biblemap.put("b47_1_9", new visuperobject(47,1,9,"Chúng tôi lại hình như đã nhận án xử tử, hầu cho chúng tôi không cậy mình, nhưng cậy Ðức Chúa Trời là Ðấng khiến kẻ chết sống lại."));
visuperobject.biblemap.put("b47_1_10", new visuperobject(47,1,10,"Ấy chính Ngài đã cứu chúng tôi khỏi sự chết lớn dường ấy, và sẽ cứu chúng tôi; phải, chúng tôi còn mong Ngài sẽ cứu chúng tôi nữa."));
visuperobject.biblemap.put("b47_1_11", new visuperobject(47,1,11,"Chính anh em lấy lời cầu nguyện mà giúp đỡ chúng tôi, hầu cho chúng tôi nhờ nhiều người cầu nguyện mà được ơn, thì cũng nên dịp cho nhiều người vì cớ chúng tôi mà tạ ơn nữa."));
visuperobject.biblemap.put("b47_1_12", new visuperobject(47,1,12,"Còn như cái điều làm vẻ vang cho chúng tôi, ấy là lương tâm chúng tôi làm chứng rằng mình lấy sự thánh sạch và thật thà đến bởi Ðức Chúa Trời mà ăn ở với anh em, không cậy sự khôn ngoan theo tánh xác thịt, nhưng cậy ơn của Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_1_13", new visuperobject(47,1,13,"Vì chúng tôi chẳng viết cho anh em sự gì khác hơn những điều anh em đọc trong thơ chúng tôi và chính mình anh em nhận biết; và tôi lại mong anh em nhận biết cho đến cuối cùng,"));
visuperobject.biblemap.put("b47_1_14", new visuperobject(47,1,14,"cũng như anh em đã nhận biết ít nhiều rồi: ấy là chúng tôi làm vẻ vang cho anh em, khác nào anh em cũng làm vẻ vang cho chúng tôi trong ngày Ðức Chúa Jêsus chúng ta."));
visuperobject.biblemap.put("b47_1_15", new visuperobject(47,1,15,"Bởi sự trông cậy đó, trước đây tôi có định đi thăm anh em, hầu giúp cho anh em được ơn bội phần."));
visuperobject.biblemap.put("b47_1_16", new visuperobject(47,1,16,"Tôi định trải qua nơi anh em rồi đi xứ Ma-xê-đoan, lại Ma-xê-đoan trở về nơi anh em, tại nơi đó, anh em cho đưa tôi qua xứ Giu-đê."));
visuperobject.biblemap.put("b47_1_17", new visuperobject(47,1,17,"Tôi định ý như vậy, nào có phải bởi tôi nhẹ dạ sao? Hãy là tôi theo xác thịt mà quyết định, đến nỗi nơi tôi khi thì phải khi thì chăng sao?"));
visuperobject.biblemap.put("b47_1_18", new visuperobject(47,1,18,"Thật như Ðức Chúa Trời là thành tín, lời chúng tôi nói với anh em cũng chẳng phải khi thì phải khi thì chăng vậy."));
visuperobject.biblemap.put("b47_1_19", new visuperobject(47,1,19,"Con Ðức Chúa Trời, là Ðức Chúa Jêsus Christ, mà chúng ta tức là tôi với Sin-vanh và Ti-mô-thê, đã giảng ra trong anh em, chẳng phải là vừa phải vừa chăng đâu; nhưng trong Ngài chỉ có phải mà thôi."));
visuperobject.biblemap.put("b47_1_20", new visuperobject(47,1,20,"Vì chưng cũng như các lời hứa của Ðức Chúa Trời đều là phải trong Ngài cả, ấy cũng bởi Ngài mà chúng tôi nói A-men, làm sáng danh Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_1_21", new visuperobject(47,1,21,"Vả, Ðấng làm cho bền vững chúng tôi với anh em trong Ðấng Christ, và đã xức dầu cho chúng tôi, ấy là Ðức Chúa Trời;"));
visuperobject.biblemap.put("b47_1_22", new visuperobject(47,1,22,"Ngài cũng lấy ấn mình mà đóng cho chúng tôi và ban của tin Ðức Thánh Linh trong lòng chúng tôi."));
visuperobject.biblemap.put("b47_1_23", new visuperobject(47,1,23,"Tôi cầu Ðức Chúa Trời lấy linh hồn tôi làm chứng rằng, ấy là tại nể anh em mà tôi chưa đi đến thành Cô-rinh-tô;"));
visuperobject.biblemap.put("b47_1_24", new visuperobject(47,1,24,"chớ không phải chúng tôi muốn cai trị đức tin anh em, nhưng chúng tôi muốn giúp thêm sự vui của anh em, vì anh em đứng vững vàng trong đức tin."));
visuperobject.biblemap.put("b47_2_1", new visuperobject(47,2,1,"Vậy, chính tôi đã quyết định không trở lại cùng anh em để làm cho anh em buồn rầu;"));
visuperobject.biblemap.put("b47_2_2", new visuperobject(47,2,2,"vì nếu tôi làm cho anh em buồn rầu, thì thể nào tôi được trông cậy sự vui bởi kẻ mà chính tôi đã làm cho buồn rầu?"));
visuperobject.biblemap.put("b47_2_3", new visuperobject(47,2,3,"Tôi đã biết cho anh em như thế, hầu cho khi tôi đến nơi, sẽ không buồn bởi kẻ đáng làm tôi vui: tôi tin cậy ở hết thảy anh em rằng, anh em ai nấy đều lấy sự vui của tôi mà làm vui mình."));
visuperobject.biblemap.put("b47_2_4", new visuperobject(47,2,4,"Vả, ấy là đương trong cơn khốn nạn lớn, tấm lòng quặn thắt, nước mắt dầm dề, mà tôi đã viết thơ cho anh em, nào phải để cho anh em âu sầu, nhưng để làm cho anh em biết tình yêu dấu riêng của tôi đối với anh em vậy."));
visuperobject.biblemap.put("b47_2_5", new visuperobject(47,2,5,"Nếu kẻ nào làm cớ buồn rầu, ấy chẳng phải chỉ làm cho tôi buồn rầu mà thôi, nhưng đã làm cho anh em thảy đều buồn rầu ít nhiều, tôi chẳng muốn nói quá làm gì."));
visuperobject.biblemap.put("b47_2_6", new visuperobject(47,2,6,"Kẻ đó đã bị phần nhiều người trong anh em quở trách, ấy là đủ rồi;"));
visuperobject.biblemap.put("b47_2_7", new visuperobject(47,2,7,"thà nay anh em tha thứ yên ủi, hầu cho người khỏi bị sa ngã vì sự buồn rầu quá lớn."));
visuperobject.biblemap.put("b47_2_8", new visuperobject(47,2,8,"Vậy tôi xin anh em hãy bày tỏ lòng yêu thương đối với người đó."));
visuperobject.biblemap.put("b47_2_9", new visuperobject(47,2,9,"Bởi chưng tôi viết thơ cho anh em, cốt để thử anh em xem có vâng lời trong cả mọi sự cùng chăng."));
visuperobject.biblemap.put("b47_2_10", new visuperobject(47,2,10,"Nhưng anh em tha thứ ai, thì tôi cũng tha thứ. Vả, nếu tôi đã tha, là vì anh em mà tha, ở trước mặt Ðấng Christ,"));
visuperobject.biblemap.put("b47_2_11", new visuperobject(47,2,11,"hầu đừng để cho quỉ Sa-tan thắng chúng ta, vì chúng ta chẳng phải là không biết mưu chước của nó."));
visuperobject.biblemap.put("b47_2_12", new visuperobject(47,2,12,"Lại khi tôi đã đến thành Trô-ách đặng giảng Tin Lành của Ðấng Christ, dầu Chúa đã mở cửa cho tôi ở đó,"));
visuperobject.biblemap.put("b47_2_13", new visuperobject(47,2,13,"mà vì tôi không gặp anh em tôi là Tít, nên chẳng được yên lòng. Vậy sau khi từ giã các tín đồ, thì tôi qua xứ Ma-xê-đoan."));
visuperobject.biblemap.put("b47_2_14", new visuperobject(47,2,14,"Song tạ ơn Ðức Chúa Trời, Ngài làm cho chúng tôi được thắng trong Ðấng Christ luôn luôn, và bởi chúng tôi, Ngài rải mùi thơm về sự nhận biết Ngài khắp chốn!"));
visuperobject.biblemap.put("b47_2_15", new visuperobject(47,2,15,"Vì chúng tôi ở trước mặt Ðức Chúa Trời là mùi thơm của Ðấng Christ, ở giữa kẻ được cứu, và ở giữa kẻ bị hư mất;"));
visuperobject.biblemap.put("b47_2_16", new visuperobject(47,2,16,"cho kẻ nầy, mùi của sự chết làm cho chết; cho kẻ kia, mùi của sự sống làm cho sống. Ai xứng đáng cho những sự nầy?"));
visuperobject.biblemap.put("b47_2_17", new visuperobject(47,2,17,"Vả, chúng tôi chẳng giả mạo lời của Ðức Chúa Trời như nhiều kẻ khác; nhưng chúng tôi lấy lòng chân thật, theo như đạo từ Ðức Chúa Trời đến thể nào, thì giảng ra thể ấy trước mặt Ðức Chúa Trời, trong Ðấng Christ."));
visuperobject.biblemap.put("b47_3_1", new visuperobject(47,3,1,"Chúng tôi há lại bắt đầu tự phô mình, hay là như người khác cần có thơ gởi gắm cho anh em, hoặc nhờ thơ gởi gắm của anh em sao?"));
visuperobject.biblemap.put("b47_3_2", new visuperobject(47,3,2,"Ấy chính anh em là thơ gởi gắm của chúng tôi, viết trong lòng chúng tôi, mọi người đều biết và đều đọc."));
visuperobject.biblemap.put("b47_3_3", new visuperobject(47,3,3,"Vả, rõ thật rằng anh em là bức thơ của Ðấng Christ, bởi chức vụ chúng tôi viết ra, chẳng phải viết bằng mực, nhưng bằng Thánh Linh của Ðức Chúa Trời hằng sống, chẳng phải viết trên bảng đá, nhưng trên bảng thịt, tức là trên lòng anh em."));
visuperobject.biblemap.put("b47_3_4", new visuperobject(47,3,4,"Nầy là sự tin chắc của chúng tôi nhờ Ðấng Christ mà có trong Ðức Chúa Trời:"));
visuperobject.biblemap.put("b47_3_5", new visuperobject(47,3,5,"không phải tự mình chúng tôi có tài năng mà nghĩ việc gì như bởi chính mình chúng tôi, nhưng tài năng của chúng tôi đến từ Ðức Chúa Trời;"));
visuperobject.biblemap.put("b47_3_6", new visuperobject(47,3,6,"và ấy là Ngài đã ban tài năng cho chúng tôi giúp việc giao ước mới, chẳng phải giao ước về chữ, bèn là giao ước về Thánh Linh; vì chữ làm cho chết, song Thánh Linh làm cho sống."));
visuperobject.biblemap.put("b47_3_7", new visuperobject(47,3,7,"Vả, nếu chức vụ về sự chết, chạm chữ trên bảng đá, đã là vinh hiển lắm đến nỗi con cái Y-sơ-ra-ên không có thể ngó trên mặt Môi-se, vì cớ sự sáng láng trên mặt người, dầu là tạm,"));
visuperobject.biblemap.put("b47_3_8", new visuperobject(47,3,8,"phương chi chức vụ của Thánh Linh càng vinh hiển hơn biết bao!"));
visuperobject.biblemap.put("b47_3_9", new visuperobject(47,3,9,"Vậy, nếu chức vụ về sự định tội còn được vinh hiển, thì chức vụ về sự công bình được vinh hiển hơn bội phần."));
visuperobject.biblemap.put("b47_3_10", new visuperobject(47,3,10,"Vả lại, cái điều được bồi hoàn trong chức vụ thứ nhứt biến đi bởi sự vinh hiển rất cao hơn của chức vụ thứ nhì;"));
visuperobject.biblemap.put("b47_3_11", new visuperobject(47,3,11,"vì nếu sự phải qua đi còn có lúc vinh hiển thay, phương chi sự bền ở sẽ có vinh hiển dường nào nữa!"));
visuperobject.biblemap.put("b47_3_12", new visuperobject(47,3,12,"Vậy, chúng ta có sự trông cậy dường ấy, nên được rất tự do,"));
visuperobject.biblemap.put("b47_3_13", new visuperobject(47,3,13,"chúng ta chẳng làm như Môi-se lấy màn che mặt mình, hầu cho con cái Y-sơ-ra-ên không trông thấy cuối cùng của sự sáng láng phải qua."));
visuperobject.biblemap.put("b47_3_14", new visuperobject(47,3,14,"Nhưng lòng họ đã cứng cỏi; vì đến ngày nay, khi họ đọc Cựu Ước, cái màn ấy vẫn còn chưa cất khỏi, bởi chưng ấy là trong Ðấng Christ mà màn đó biến đi."));
visuperobject.biblemap.put("b47_3_15", new visuperobject(47,3,15,"Ấy vậy, cho đến ngày nay, mỗi lần người ta đọc sách Môi-se cho họ, cái màn ấy vẫn còn ở trên lòng họ."));
visuperobject.biblemap.put("b47_3_16", new visuperobject(47,3,16,"Khi họ sẽ trở lại cùng Chúa, thì màn ấy mới cất khỏi."));
visuperobject.biblemap.put("b47_3_17", new visuperobject(47,3,17,"Vả, Chúa tức là Thánh Linh, Thánh Linh của Chúa ở đâu, thì sự tự do cũng ở đó."));
visuperobject.biblemap.put("b47_3_18", new visuperobject(47,3,18,"Chúng ta ai nấy đều để mặt trần mà nhìn xem vinh hiển Chúa như trong gương, thì hóa nên cũng một ảnh tượng Ngài, từ vinh hiển qua vinh hiển, như bởi Chúa, là Thánh Linh."));
visuperobject.biblemap.put("b47_4_1", new visuperobject(47,4,1,"Vậy nên, chúng tôi nhờ sự thương xót đã ban cho, mà được chức vụ nầy, thì chúng tôi chẳng ngã lòng;"));
visuperobject.biblemap.put("b47_4_2", new visuperobject(47,4,2,"nhưng chúng tôi từ bỏ mọi điều hổ thẹn giấu kín. Chúng tôi chẳng theo sự dối gạt, và chẳng giả mạo lời Ðức Chúa Trời, nhưng trước mặt Ðức Chúa Trời chúng tôi tỏ bày lẽ thật, khiến lương tâm mọi người cho chúng tôi là đáng chuộng."));
visuperobject.biblemap.put("b47_4_3", new visuperobject(47,4,3,"Nếu Tin Lành của chúng tôi còn che khuất, là chỉ che khuất cho những kẻ hư mất,"));
visuperobject.biblemap.put("b47_4_4", new visuperobject(47,4,4,"cho những kẻ chẳng tin mà chúa đời nầy đã làm mù lòng họ, hầu cho họ không trông thấy sự vinh hiển chói lói của Tin Lành Ðấng Christ, là ảnh tượng của Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_4_5", new visuperobject(47,4,5,"Vả, chúng tôi chẳng rao giảng chính mình chúng tôi, nhưng rao giảng Ðức Chúa Jêsus Christ, tức là Chúa; và vì tình yêu mến Ðức Chúa Jêsus mà chúng tôi xưng mình là tôi tớ của anh em."));
visuperobject.biblemap.put("b47_4_6", new visuperobject(47,4,6,"Vì Ðức Chúa Trời, là Ðấng có phán: Sự sáng phải soi từ trong sự tối tăm! đã làm cho sự sáng Ngài chói lòa trong lòng chúng tôi, đặng sự thông biết về vinh hiển Ðức Chúa Trời soi sáng nơi mặt Ðức Chúa Jêsus Christ."));
visuperobject.biblemap.put("b47_4_7", new visuperobject(47,4,7,"Nhưng chúng tôi đựng của quí nầy trong chậu bằng đất, hầu cho tỏ quyền phép lớn dường ấy là bởi Ðức Chúa Trời mà ra, chớ chẳng phải bởi chúng tôi."));
visuperobject.biblemap.put("b47_4_8", new visuperobject(47,4,8,"Chúng tôi bị ép đủ cách, nhưng không đến cùng; bị túng thế nhưng không ngã lòng;"));
visuperobject.biblemap.put("b47_4_9", new visuperobject(47,4,9,"bị bắt bớ, nhưng không đến bỏ; bị đánh đập, nhưng không đến chết mất."));
visuperobject.biblemap.put("b47_4_10", new visuperobject(47,4,10,"Chúng tôi thường mang sự chết của Ðức Chúa Jêsus trong thân thể mình, hầu cho sự sống của Ðức Chúa Jêsus cũng tỏ ra trong thân thể chúng tôi."));
visuperobject.biblemap.put("b47_4_11", new visuperobject(47,4,11,"Bởi chúng tôi là kẻ sống, vì cớ Ðức Chúa Jêsus mà hằng bị nộp cho sự chết, hầu cho sự sống của Ðức Chúa Jêsus cũng được tỏ ra trong xác thịt hay chết của chúng tôi;"));
visuperobject.biblemap.put("b47_4_12", new visuperobject(47,4,12,"vậy thì sự chết làm trong chúng tôi, còn sự sống trong anh em."));
visuperobject.biblemap.put("b47_4_13", new visuperobject(47,4,13,"Vì chúng tôi có đồng một lòng tin, y như lời Kinh Thánh rằng: Ta đã tin, cho nên ta nói, cũng vậy, chúng tôi tin, cho nên mới nói,"));
visuperobject.biblemap.put("b47_4_14", new visuperobject(47,4,14,"vì biết rằng Ðấng đã khiến Ðức Chúa Jêsus sống lại, cũng sẽ làm cho chúng tôi sống lại với Ðức Chúa Jêsus, và làm cho chúng tôi ứng hầu với anh em trước mặt Ngài."));
visuperobject.biblemap.put("b47_4_15", new visuperobject(47,4,15,"Bởi chưng mọi điều đó xảy đến vì cớ anh em, hầu cho ân điển rải ra cách dư dật, khiến sự tạ ơn nơi nhiều người hơn cũng dư dật, mà thêm vinh hiển cho Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_4_16", new visuperobject(47,4,16,"Vậy nên chúng ta chẳng ngã lòng, dầu người bề ngoài hư nát, nhưng người bề trong cứ đổi mới càng ngày càng hơn."));
visuperobject.biblemap.put("b47_4_17", new visuperobject(47,4,17,"Vì sự hoạn nạn nhẹ và tạm của chúng ta sanh cho chúng ta sự vinh hiển cao trọng đời đời, vô lượng, vô biên,"));
visuperobject.biblemap.put("b47_4_18", new visuperobject(47,4,18,"bởi chúng ta chẳng chăm sự thấy được; vì những sự thấy được chỉ là tạm thời, mà sự không thấy được là đời đời không cùng vậy."));
visuperobject.biblemap.put("b47_5_1", new visuperobject(47,5,1,"Vả, chúng ta biết rằng nếu nhà tạm của chúng ta dưới đất đổ nát, thì chúng ta lại có nhà đời đời trên trời, bởi Ðức Chúa Trời, không phải bởi tay người làm ra."));
visuperobject.biblemap.put("b47_5_2", new visuperobject(47,5,2,"Vì chúng ta thật than thở trong nhà tạm nầy, mà hết sức mong được mặc lấy nhà chúng ta từ trên trời,"));
visuperobject.biblemap.put("b47_5_3", new visuperobject(47,5,3,"miễn là gặp thấy chúng ta đang mặc áo, không trần truồng."));
visuperobject.biblemap.put("b47_5_4", new visuperobject(47,5,4,"Bởi chưng chúng ta ở trong nhà tạm nầy, than thở dưới gánh nặng, vì chúng ta không cầu cho bị lột trần, song cầu cho được mặc lại, để sự gì hay chết trong chúng ta bị sự sống nuốt đi."));
visuperobject.biblemap.put("b47_5_5", new visuperobject(47,5,5,"Ðấng đã gây dựng chúng ta cho được sự ấy, ấy là Ðức Chúa Trời, đã ban của tin của Ðức Thánh Linh cho chúng ta."));
visuperobject.biblemap.put("b47_5_6", new visuperobject(47,5,6,"Vậy, chúng ta hằng đầy lòng tin cậy, và biết rằng khi chúng ta đang ở trong thân thể nầy thì cách xa Chúa"));
visuperobject.biblemap.put("b47_5_7", new visuperobject(47,5,7,"vì chúng ta bước đi bởi đức tin, chớ chẳng phải bởi mắt thấy."));
visuperobject.biblemap.put("b47_5_8", new visuperobject(47,5,8,"Vậy tôi nói, chúng ta đầy lòng tin cậy, muốn lìa bỏ thân thể nầy đặng ở cùng Chúa thì hơn."));
visuperobject.biblemap.put("b47_5_9", new visuperobject(47,5,9,"Cho nên chúng ta dầu ở trong thân thể nầy, dầu ra khỏi, cũng làm hết sức để được đẹp lòng Chúa."));
visuperobject.biblemap.put("b47_5_10", new visuperobject(47,5,10,"Bởi vì chúng ta thảy đều phải ứng hầu trước tòa án Ðấng Christ, hầu cho mỗi người nhận lãnh tùy theo điều thiện hay điều ác mình đã làm lúc còn trong xác thịt."));
visuperobject.biblemap.put("b47_5_11", new visuperobject(47,5,11,"Vậy chúng tôi biết Chúa đáng kính sợ, nên tìm cách làm cho người ta đều tin; Ðức Chúa Trời biết chúng tôi, và tôi mong anh em cũng biết chúng tôi trong lương tâm mình."));
visuperobject.biblemap.put("b47_5_12", new visuperobject(47,5,12,"Chúng tôi chẳng lại phô mình cùng anh em, nhưng muốn trao cho anh em cái dịp khoe mình về chúng tôi, đặng anh em có thể đối đáp lại cùng những kẻ chỉ khoe mình về bề ngoài, mà không về sự trong lòng."));
visuperobject.biblemap.put("b47_5_13", new visuperobject(47,5,13,"Vả, hoặc chúng tôi cuồng, ấy là vì Ðức Chúa Trời; hoặc chúng tôi dè giữ, ấy là vì anh em."));
visuperobject.biblemap.put("b47_5_14", new visuperobject(47,5,14,"Vì tình yêu thương của Ðấng Christ cảm động chúng tôi, và chúng tôi tưởng rằng nếu có một người chết vì mọi người, thì mọi người đều chết,"));
visuperobject.biblemap.put("b47_5_15", new visuperobject(47,5,15,"lại Ngài đã chết vì mọi người, hầu cho những kẻ còn sống không vì chính mình mà sống nữa, nhưng sống vì Ðấng đã chết và sống lại cho mình."));
visuperobject.biblemap.put("b47_5_16", new visuperobject(47,5,16,"Bởi đó, từ rày về sau, chúng tôi không theo xác thịt mà nhận biết ai nữa; và, dẫu chúng tôi từng theo xác thịt mà nhận biết Ðấng Christ, song cũng chẳng còn nhận biết Ngài cách ấy đâu."));
visuperobject.biblemap.put("b47_5_17", new visuperobject(47,5,17,"Vậy, nếu ai ở trong Ðấng Christ, thì nấy là người dựng nên mới; những sự cũ đã qua đi, nầy mọi sự đều trở nên mới."));
visuperobject.biblemap.put("b47_5_18", new visuperobject(47,5,18,"Mọi điều đó đến bởi Ðức Chúa Trời, Ngài đã làm cho chúng ta nhờ Ðấng Christ mà được hòa thuận lại cùng Ngài, và giao chức vụ giảng hòa cho chúng ta."));
visuperobject.biblemap.put("b47_5_19", new visuperobject(47,5,19,"Vì chưng Ðức Chúa Trời vốn ở trong Ðấng Christ, làm cho thế gian lại hòa với Ngài, chẳng kể tội lỗi cho loài người, và đã phó đạo giảng hòa cho chúng tôi."));
visuperobject.biblemap.put("b47_5_20", new visuperobject(47,5,20,"Vậy chúng tôi làm chức khâm sai của Ðấng Christ, cũng như Ðức Chúa Trời bởi chúng tôi mà khuyên bảo. Chúng tôi nhơn danh Ðấng Christ mà nài xin anh em: hãy hòa thuận lại với Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_5_21", new visuperobject(47,5,21,"Ðức Chúa Trời đã làm cho Ðấng vốn chẳng biết tội lỗi trở nên tội lỗi vì chúng ta, hầu cho chúng ta nhờ Ðấng đó mà được trở nên sự công bình của Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_6_1", new visuperobject(47,6,1,"Ấy vậy, vì chúng tôi làm việc với Chúa, nên xin anh em chớ chịu ơn Ðức Chúa Trời luống không."));
visuperobject.biblemap.put("b47_6_2", new visuperobject(47,6,2,"Vì Ngài phán rằng: Ta đã nhậm lời ngươi trong thì thuận tiện, Ta đã phù hộ ngươi trong ngày cứu rỗi. Kìa, hiện nay là thì thuận tiện; kìa, hiện nay là ngày cứu rỗi!"));
visuperobject.biblemap.put("b47_6_3", new visuperobject(47,6,3,"Chúng tôi chẳng làm cho ai vấp phạm, hầu cho chức vụ của mình khỏi bị một tiếng chê bai nào."));
visuperobject.biblemap.put("b47_6_4", new visuperobject(47,6,4,"Nhưng chúng tôi làm cho mình đáng trượng trong mọi sự, như kẻ hầu việc Ðức Chúa Trời, bởi lòng nhịn nhục lắm trong những sự hoạn nạn, thiếu thốn, khốn khổ,"));
visuperobject.biblemap.put("b47_6_5", new visuperobject(47,6,5,"đòn vọt, lao tù, rối loạn, khó nhọc, tỉnh thức, kiêng ăn;"));
visuperobject.biblemap.put("b47_6_6", new visuperobject(47,6,6,"bởi sự thanh sạch, thông biết, khoan nhẫn, nhơn từ, bởi Ðức Thánh Linh, bởi lòng yêu thương thật tình,"));
visuperobject.biblemap.put("b47_6_7", new visuperobject(47,6,7,"bởi lời chơn thật, bởi quyền phép Ðức Chúa Trời, cầm những khí giới công bình ở tay hữu và tay tả;"));
visuperobject.biblemap.put("b47_6_8", new visuperobject(47,6,8,"dầu vinh dầu nhục, dầu mang tiếng xấu, dầu được tiếng tốt;"));
visuperobject.biblemap.put("b47_6_9", new visuperobject(47,6,9,"ngó như kẻ phỉnh dỗ, nhưng là kẻ thật thà; ngó như kẻ xa lạ, nhưng là kẻ quen biết lắm; ngó như gần chết, mà nay vẫn sống; ngó như bị sửa phạt, mà không đến chịu giết;"));
visuperobject.biblemap.put("b47_6_10", new visuperobject(47,6,10,"ngó như buồn rầu, mà thường được vui mừng; ngó như nghèo ngặt, mà thật làm cho nhiều người được giàu có ngó như không có gì cả, mà có đủ mọi sự!"));
visuperobject.biblemap.put("b47_6_11", new visuperobject(47,6,11,"Hỡi người Cô-rinh-tô, miệng chúng tôi hả ra vì anh em, lòng chúng tôi mở rộng."));
visuperobject.biblemap.put("b47_6_12", new visuperobject(47,6,12,"Chẳng phải chúng tôi hẹp hòi đãi anh em, nhưng ấy là lòng anh em tự làm nên hẹp hòi."));
visuperobject.biblemap.put("b47_6_13", new visuperobject(47,6,13,"Hãy báo đáp chúng tôi như vậy, tôi nói với anh em như nói với con cái mình, cũng hãy mở rộng lòng anh em!"));
visuperobject.biblemap.put("b47_6_14", new visuperobject(47,6,14,"Chớ mang ách chung với kẻ chẳng tin. Bởi vì công bình với gian ác có hòa hiệp nhau được chăng? Sự sáng với sự tối có thông đồng nhau được chăng?"));
visuperobject.biblemap.put("b47_6_15", new visuperobject(47,6,15,"Ðấng Christ và Bê-li-an nào có hòa hiệp chi, hay là kẻ tin có phần gì với kẻ chẳng tin?"));
visuperobject.biblemap.put("b47_6_16", new visuperobject(47,6,16,"Có thể nào hiệp đền thờ Ðức Chúa Trời lại với hình tượng tà thần? Vì chúng ta là đền thờ của Ðức Chúa Trời hằng sống, như Ðức Chúa Trời đã phán rằng: Ta sẽ ở và đi lại giữa họ; ta sẽ làm Ðức Chúa Trời của họ, và họ làm dân ta."));
visuperobject.biblemap.put("b47_6_17", new visuperobject(47,6,17,"Bởi vậy Chúa phán rằng: Hãy ra khỏi giữa chúng nó, hãy phân rẽ ra khỏi chúng nó, đừng đá động đến đồ ô uế, Thì ta sẽ tiếp nhận các ngươi:"));
visuperobject.biblemap.put("b47_6_18", new visuperobject(47,6,18,"Ta sẽ làm Chúa các ngươi, Các ngươi làm con trai con gái ta, Chúa Toàn năng phán như vậy."));
visuperobject.biblemap.put("b47_7_1", new visuperobject(47,7,1,"Hỡi những kẻ rất yêu dấu của tôi, chúng ta đã có lời hứa dường ấy, thì hãy làm cho mình sạch khỏi mọi sự dơ bẩn phần xác thịt và phần thần linh, lại lấy sự kính sợ Ðức Chúa Trời mà làm cho trọn việc nên thánh của chúng ta."));
visuperobject.biblemap.put("b47_7_2", new visuperobject(47,7,2,"Hãy mở lòng anh em cho chúng tôi: chúng tôi chẳng có làm hại ai, lừa dối ai; thủ lợi ai."));
visuperobject.biblemap.put("b47_7_3", new visuperobject(47,7,3,"Tôi chẳng nói điều đó để buộc tội anh em; vì tôi đã nói rằng lòng chúng tôi thuộc về anh em, dầu sống hay chết cũng vậy."));
visuperobject.biblemap.put("b47_7_4", new visuperobject(47,7,4,"Tôi nói với anh em cách bạo dạn; tôi được đầy sự yên ủi, tôi được vui mừng quá bội ở giữa mọi sự khó khăn."));
visuperobject.biblemap.put("b47_7_5", new visuperobject(47,7,5,"Vả, khi chúng tôi đến trong xứ Ma-xê-đoan, xác thịt chẳng được yên nghỉ chút nào. Chúng tôi khốn đốn đủ mọi cách: ngoài thì có sự chiến trận, trong thì có sự lo sợ."));
visuperobject.biblemap.put("b47_7_6", new visuperobject(47,7,6,"Nhưng Ðức Chúa Trời là Ðấng yên ủi kẻ ngã lòng, đã yên ủi tôi bởi Tít đến nơi;"));
visuperobject.biblemap.put("b47_7_7", new visuperobject(47,7,7,"không những bởi người đến mà thôi, nhưng lại bởi sự yên ủi người đã nhận lãnh nơi anh em nữa: người có nói cho chúng tôi biết anh em rất ao ước, khóc lóc, và có lòng sốt sắng đối với tôi, điều đó làm cho tôi càng vui mừng thêm."));
visuperobject.biblemap.put("b47_7_8", new visuperobject(47,7,8,"Dầu nhơn bức thơ tôi, đã làm cho anh em buồn rầu, thì tôi chẳng lấy làm phàn nàn; mà nếu trước đã phàn nàn (vì tôi thấy bức thơ ấy ít nữa cũng làm cho anh em buồn rầu trong một lúc),"));
visuperobject.biblemap.put("b47_7_9", new visuperobject(47,7,9,"nay tôi lại mừng, không phải mừng về sự anh em đã phải buồn rầu, song mừng về sự buồn rầu làm cho anh em sanh lòng hối cải. Thật, anh em đã buồn rầu theo ý Ðức Chúa Trời, đến nỗi chưa chịu thiệt hại bởi chúng tôi chút nào."));
visuperobject.biblemap.put("b47_7_10", new visuperobject(47,7,10,"Vì sự buồn rầu theo ý Ðức Chúa Trời sanh ra sự hối cải, và sự hối cải dẫn đến sự rỗi linh hồn; về sự đó người ta chẳng hề ăn năn, còn sự buồn rầu theo thế gian sanh ra sự chết."));
visuperobject.biblemap.put("b47_7_11", new visuperobject(47,7,11,"Vậy, hãy xem, sự buồn rầu theo ý Ðức Chúa Trời sanh ra sự ân cần trong anh em là dường nào! Lại có sự chữa chối, buồn giận, răn sợ, sốt sắng, nông nả, trách phạt là dường nào! Anh em đã tỏ ra cho ai nấy đều biết rằng mình vốn là thanh sạch trong việc đó."));
visuperobject.biblemap.put("b47_7_12", new visuperobject(47,7,12,"Lại còn, nếu tôi đã viết thơ cho anh em, ấy không phải vì cớ kẻ làm sự trái nghịch, cũng không phải vì cớ kẻ chịu sự trái nghịch; nhưng hầu cho lòng anh em yêu chuộng chúng tôi được tỏ ra giữa anh em ở trước mặt Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_7_13", new visuperobject(47,7,13,"Ấy là điều đã yên ủi chúng tôi. Nhơn sự yên ủi đó chúng tôi lại được sự vui mừng càng lớn hơn nữa, khi thấy sự vui mừng của Tít; vì anh em thảy đều đã để cho tâm thần người được yên lặng."));
visuperobject.biblemap.put("b47_7_14", new visuperobject(47,7,14,"Nếu tôi đã khoe mình với Tít về anh em trong sự gì, thì tôi cũng chẳng hổ thẹn; nhưng vì chúng tôi đã thường nói điều thật với anh em, nên lời khen về anh em mà chúng tôi khoe với Tít cũng thấy là thật."));
visuperobject.biblemap.put("b47_7_15", new visuperobject(47,7,15,"Khi người nhớ đến sự vâng lời của anh em hết thảy, và anh em tiếp người cách sợ sệt run rẩy dường nào, thì tình yêu thương của người đối với anh em càng bội lên."));
visuperobject.biblemap.put("b47_7_16", new visuperobject(47,7,16,"Tôi vui mừng vì có thể tin cậy anh em trong mọi sự."));
visuperobject.biblemap.put("b47_8_1", new visuperobject(47,8,1,"Hỡi anh em, chúng tôi muốn anh em biết ơn Ðức Chúa Trời đã làm cho các Hội thánh ở xứ Ma-xê-đoan:"));
visuperobject.biblemap.put("b47_8_2", new visuperobject(47,8,2,"đang khi họ chịu nhiều hoạn nạn thử thách, thì lòng quá vui mừng, và cơn rất nghèo khó của họ đã rải rộng ra sự dư dật của lòng rộng rãi mình."));
visuperobject.biblemap.put("b47_8_3", new visuperobject(47,8,3,"Vì tôi làm chứng cho họ rằng họ đã tự ý quyên tiền theo sức mình, hoặc cũng quá sức nữa,"));
visuperobject.biblemap.put("b47_8_4", new visuperobject(47,8,4,"và nài xin chúng tôi làm ơn cho họ có phần vào sự giùm giúp các thánh đồ."));
visuperobject.biblemap.put("b47_8_5", new visuperobject(47,8,5,"Họ lại làm quá lòng trông cậy của chúng tôi, vì trước hết đã dâng chính mình cho Chúa, và sau lại cho chúng tôi, theo ý muốn Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_8_6", new visuperobject(47,8,6,"Vậy nên chúng tôi đã khuyên Tít đi đến nơi anh em để làm trọn việc nhơn đức nầy, như người đã khởi sự làm."));
visuperobject.biblemap.put("b47_8_7", new visuperobject(47,8,7,"Vậy thì, như anh em đều trổi hơn về mọi việc, tức là về đức tin, về lời giảng, về sự vâng lời, về mọi sự sốt sắng, về tình yêu chúng tôi, thì cũng hãy chủ ý làm cho trổi hơn về việc nhơn đức nầy."));
visuperobject.biblemap.put("b47_8_8", new visuperobject(47,8,8,"Tôi nói điều đó chẳng phải truyền dạy anh em; nhưng bởi kẻ khác làm gương sốt sắng, thì tôi cũng muốn thử xem sự thành thực của lòng yêu thương anh em là thể nào."));
visuperobject.biblemap.put("b47_8_9", new visuperobject(47,8,9,"Vì anh em biết ơn của Ðức Chúa Jêsus Christ chúng ta, Ngài vốn giàu, vì anh em mà tự làm nên nghèo, hầu cho bởi sự nghèo của Ngài, anh em được nên giàu."));
visuperobject.biblemap.put("b47_8_10", new visuperobject(47,8,10,"Ấy là ý tôi ngỏ cho anh em; ý đó có ích cho anh em, vì từ năm trước, anh em đã là người thứ nhứt, chẳng người ra tay làm việc nầy, lại vui lòng mà làm nữa."));
visuperobject.biblemap.put("b47_8_11", new visuperobject(47,8,11,"Vậy bây giờ, hãy làm trọn công việc của anh em, hầu cho như anh em đã sẵn lòng thể nào thì làm cho trọn theo tài năng mình."));
visuperobject.biblemap.put("b47_8_12", new visuperobject(47,8,12,"Vì nếu mình lấy lòng tốt mà làm, thì được đẹp ý theo điều mình có, chớ chẳng theo điều mình không có."));
visuperobject.biblemap.put("b47_8_13", new visuperobject(47,8,13,"Tôi chẳng khuyên bảo anh em chịu túng tíu để giúp đỡ kẻ khác, nhưng tôi muốn có sự bằng nhau."));
visuperobject.biblemap.put("b47_8_14", new visuperobject(47,8,14,"Theo cảnh bây giờ, anh em có dư thì bù cho họ lúc túng thiếu, hầu cho họ có dư cũng bù lại lúc túng thiếu cho anh em, như vậy là bằng nhau,"));
visuperobject.biblemap.put("b47_8_15", new visuperobject(47,8,15,"theo lời chép rằng: Kẻ đã thâu nhiều cũng chẳng dư, kẻ thâu ít cũng chẳng thiếu chi."));
visuperobject.biblemap.put("b47_8_16", new visuperobject(47,8,16,"Tạ ơn Ðức Chúa Trời về sự Ngài đã xui lòng Tít cũng ân cần với anh em thể ấy;"));
visuperobject.biblemap.put("b47_8_17", new visuperobject(47,8,17,"vì người nghe lời tôi khuyên, và cũng bởi sốt sắng, thì người tự ý đi đến thăm anh em."));
visuperobject.biblemap.put("b47_8_18", new visuperobject(47,8,18,"Chúng tôi có sai một người anh em cùng đi, là người có tiếng khen đồn khắp trong các Hội thánh, tại những điều người đã làm vì đạo Tin Lành."));
visuperobject.biblemap.put("b47_8_19", new visuperobject(47,8,19,"Vả lại, người đã được các Hội thánh chọn lựa, để làm bạn đi đường cùng chúng tôi trong việc nhơn đức nầy, là việc chúng tôi làm trọn để tỏ vinh hiển chính mình Chúa ra, và để làm chứng về ý tốt của chúng tôi."));
visuperobject.biblemap.put("b47_8_20", new visuperobject(47,8,20,"Chúng tôi nhờ đó tránh khỏi tiếng trách móc về sự dùng tiền góp nhiều như vậy;"));
visuperobject.biblemap.put("b47_8_21", new visuperobject(47,8,21,"vì chúng tôi tìm tòi điều lành, chẳng những ở trước mặt Chúa, mà cũng ở trước mặt người ta nữa."));
visuperobject.biblemap.put("b47_8_22", new visuperobject(47,8,22,"Chúng tôi lại sai một người trong anh em chúng tôi đi với họ, là người có lòng sốt sắng mà đòi phen chúng tôi đã thử thách trong nhiều dịp; lần nầy, vì cớ người có lòng rất tin cậy anh em, thì chắc là càng sốt sắng hơn."));
visuperobject.biblemap.put("b47_8_23", new visuperobject(47,8,23,"Ấy vậy, nói về Tít, thì là bạn bè tôi, và là người cùng làm việc với tôi ở nơi anh em; còn như hai anh em kia, là sứ giả của các Hội thánh, tức là sự vinh hiển của Ðấng Christ."));
visuperobject.biblemap.put("b47_8_24", new visuperobject(47,8,24,"Vậy, anh em ở trước mặt các Hội thánh, hãy tỏ chứng cớ của sự yêu thương mình, và bày ra cho họ biết chúng tôi có cớ khoe mình nơi họ vì anh em."));
visuperobject.biblemap.put("b47_9_1", new visuperobject(47,9,1,"Vả lại, về sự giúp đỡ thánh đồ, thì không cần viết thêm cho anh em nữa."));
visuperobject.biblemap.put("b47_9_2", new visuperobject(47,9,2,"Vì tôi biết anh em sẵn lòng, và tôi khoe mình về anh em với người Ma-xê-đoan, nói rằng người A-chai đã sắm sẵn từ năm ngoái; lòng sốt sắng của anh em lại đã giục lòng nhiều người khác."));
visuperobject.biblemap.put("b47_9_3", new visuperobject(47,9,3,"Song tôi đã sai các anh em kia đến cùng anh em, hầu cho lời tôi khen anh em khỏi ra vô ích trong điều nầy, và hầu cho anh em sẵn sàng như lời tôi đã nói."));
visuperobject.biblemap.put("b47_9_4", new visuperobject(47,9,4,"Tôi e rằng nếu người Ma-xê-đoan đến với tôi, thấy anh em không sẵn, thì sự tin cậy đó đổi nên điều hổ thẹn cho chúng tôi chăng, còn anh em không kể đến."));
visuperobject.biblemap.put("b47_9_5", new visuperobject(47,9,5,"Vậy tôi nghĩ cần phải xin các anh em kia đi trước chúng tôi đến cùng anh em, và cần phải sắm sẵn của bố thí mà anh em đã hứa, hầu cho của ấy sẵn sàng như một việc bởi lòng thành, chẳng phải bởi ý gắng gượng."));
visuperobject.biblemap.put("b47_9_6", new visuperobject(47,9,6,"Hãy biết rõ điều đó, hễ ai gieo ít thì gặt ít, ai gieo nhiều thì gặt nhiều."));
visuperobject.biblemap.put("b47_9_7", new visuperobject(47,9,7,"Mỗi người nên tùy theo lòng mình đã định mà quyên ra, không phải phàn nàn hay vì ép uổng; vì Ðức Chúa Trời yêu kẻ thí của cách vui lòng."));
visuperobject.biblemap.put("b47_9_8", new visuperobject(47,9,8,"Ðức Chúa Trời có quyền ban cho anh em đủ mọi thứ ơn đầy dẫy, hầu cho anh em hằng đủ điều cần dùng trong mọi sự, lại còn có rời rộng nữa để làm các thứ việc lành,"));
visuperobject.biblemap.put("b47_9_9", new visuperobject(47,9,9,"như có chép rằng: Người đã rải ra, đã thí cho kẻ nghèo; Sự công bình của người có đời đời."));
visuperobject.biblemap.put("b47_9_10", new visuperobject(47,9,10,"Ðấng phát hột giống cho kẻ gieo giống và bánh để nuôi mình, cũng sẽ phát hột giống cho anh em và làm cho sanh hóa ra nhiều, Ngài lại sẽ thêm nhiều trái của sự công bình anh em nữa."));
visuperobject.biblemap.put("b47_9_11", new visuperobject(47,9,11,"Như vậy, anh em được giàu trong mọi sự, để làm đủ mọi cách bố thí, hầu cho người khác bởi chúng tôi mà tạ ơn Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_9_12", new visuperobject(47,9,12,"Vì việc phát tiền bố thí dường ấy chẳng những dỡ ngặt cho các thánh đồ mà thôi, lại xui nhiều người càng thêm lòng tạ ơn Ðức Chúa Trời."));
visuperobject.biblemap.put("b47_9_13", new visuperobject(47,9,13,"Bởi việc đó họ đã biết lòng rộng rãi của anh em, thì ngợi khen Ðức Chúa Trời vì anh em từng vâng phục trong sự làm chứng về đạo Tin Lành của Ðấng Christ, và vì cớ lòng rộng rãi về sự bố thí của anh em đối với họ cùng với mọi người."));
visuperobject.biblemap.put("b47_9_14", new visuperobject(47,9,14,"Họ lại cầu nguyện cho anh em, yêu anh em cách âu yếm, vì cớ Ðức Chúa Trời đã ban cho anh em ân điển quá đỗi."));
visuperobject.biblemap.put("b47_9_15", new visuperobject(47,9,15,"Tạ ơn Ðức Chúa Trời, vì sự ban cho của Ngài không xiết kể!"));
visuperobject.biblemap.put("b47_10_1", new visuperobject(47,10,1,"Tôi là Phao-lô, bởi sự nhu mì, nhơn từ của Ðấng Christ mà xin anh em, tôi là người hèn hạ lắm trong khi gặp mặt giữa anh em nhưng lúc vắng mặt, đối với anh em, tỏ ra biết bao là dạn dĩ!"));
visuperobject.biblemap.put("b47_10_2", new visuperobject(47,10,2,"tôi nài xin anh em chớ ép tôi, khi tôi sẽ có mặt, phải dùng sự dạn dĩ mà tôi toan dùng nghịch cùng mấy kẻ kia tưởng chúng tôi ăn ở theo xác thịt."));
visuperobject.biblemap.put("b47_10_3", new visuperobject(47,10,3,"Vì chúng tôi dầu sống trong xác thịt, chớ chẳng tranh chiến theo xác thịt."));
visuperobject.biblemap.put("b47_10_4", new visuperobject(47,10,4,"Vả, những khí giới mà chúng tôi dùng để chiến tranh là không phải thuộc về xác thịt đâu, bèn là bởi quyền năng của Ðức Chúa Trời, có sức mạnh để đạp đổ các đồn lũy:"));
visuperobject.biblemap.put("b47_10_5", new visuperobject(47,10,5,"nhờ khí giới đó chúng tôi đánh đổ các lý luận, mọi sự cao tự nổi lên nghịch cùng sự hiểu biết Ðức Chúa Trời, và bắt hết các ý tưởng làm tôi vâng phục Ðấng Christ."));
visuperobject.biblemap.put("b47_10_6", new visuperobject(47,10,6,"Cũng nhờ khí giới đó, chúng tôi sẵn sàng phạt mọi kẻ chẳng phục, khi anh em đã chịu lụy trọn rồi."));
visuperobject.biblemap.put("b47_10_7", new visuperobject(47,10,7,"Anh em cứ xem bề ngoài sao? Bằng có ai quyết mình thuộc về Ðấng Christ, hãy ngẫm nghĩ rằng nếu người thuộc về Ðấng Christ, thì chúng tôi cũng thuộc về Ngài."));
visuperobject.biblemap.put("b47_10_8", new visuperobject(47,10,8,"Dầu khi tôi khoe mình khí quá về quyền phép Chúa đã ban cho chúng tôi, để gây dựng anh em, chớ chẳng phải để hủy diệt, thì tôi sự không hổ thẹn;"));
visuperobject.biblemap.put("b47_10_9", new visuperobject(47,10,9,"song tôi chẳng muốn làm bộ dọa anh em bằng thơ từ của tôi."));
visuperobject.biblemap.put("b47_10_10", new visuperobject(47,10,10,"Có người nói rằng các thơ của người nặng lời và bạo mạnh; nhưng đến khi có mặt thì người yếu đuối và lời nói chẳng có giá gì."));
visuperobject.biblemap.put("b47_10_11", new visuperobject(47,10,11,"Kẻ nói như vậy, hãy nghĩ rằng khi chúng tôi vắng mặt, lời trong thơ thể nào, thì khi có mặt, việc làm cũng thể ấy."));
visuperobject.biblemap.put("b47_10_12", new visuperobject(47,10,12,"Thật chúng tôi không dám bằng vai hoặc sánh mình với những người kia, là kẻ hay tự phô mình. Nhưng lấy mình đo mình, lấy mình so sánh với mình, thì họ tỏ ra ít trí khôn."));
visuperobject.biblemap.put("b47_10_13", new visuperobject(47,10,13,"Về phần chúng tôi, chẳng muốn khoe mình quá mực, chỉ theo mực về địa phận mà Ðức Chúa Trời đã chỉ định cho chúng tôi tới đến anh em."));
visuperobject.biblemap.put("b47_10_14", new visuperobject(47,10,14,"Bởi chưng chúng tôi chẳng vượt quá mực mình, như thể chúng tôi không đến cùng anh em, vì thật chúng tôi đã đem Tin Lành của Ðấng Christ mà đến nơi anh em trước hết."));
visuperobject.biblemap.put("b47_10_15", new visuperobject(47,10,15,"Chúng tôi không khoe mình quá mực, cũng không khoe về việc người khác làm; nhưng mong rằng đức tin của anh em thêm lên, thì công việc chúng tôi cũng sẽ lớn lên thêm giữa anh em, theo giới hạn đã định cho chúng tôi, và công việc ấy càng mở mang,"));
visuperobject.biblemap.put("b47_10_16", new visuperobject(47,10,16,"cho đến nỗi chúng tôi sẽ có thể truyền Tin Lành ra đến các xứ xa hơn xứ anh em, song chúng tôi không hề khoe mình về việc đã làm trong địa phận của người khác."));
visuperobject.biblemap.put("b47_10_17", new visuperobject(47,10,17,"Nhưng ai khoe mình, hãy khoe mình trong Chúa."));
visuperobject.biblemap.put("b47_10_18", new visuperobject(47,10,18,"Vì ấy chẳng phải là kẻ tự phô mình đáng được ưng chịu, bèn là kẻ mà Chúa gởi gắm."));
visuperobject.biblemap.put("b47_11_1", new visuperobject(47,11,1,"Ôi! Chớ chi anh em dung chịu sự dồ dại của tôi một ít! Phải, anh em nên dung chịu."));
visuperobject.biblemap.put("b47_11_2", new visuperobject(47,11,2,"Vì về anh em, tôi rất sốt sắng như sự sốt sắng của Ðức Chúa Trời, bởi tôi đã gả anh em cho một chồng mà thôi, dâng anh em như người trinh nữ tinh sạch cho Ðấng Christ."));
visuperobject.biblemap.put("b47_11_3", new visuperobject(47,11,3,"Nhưng tôi ngại rằng như xưa Ê-va bị cám dỗ bởi mưu chước con rắn kia, thì ý tưởng anh em cũng hư đi, mà dời đổi lòng thật thà tinh sạch đối với Ðấng Christ chăng."));
visuperobject.biblemap.put("b47_11_4", new visuperobject(47,11,4,"Vì nếu có người đến giảng cho anh em một Jêsus khác với Jêsus chúng tôi đã giảng, hoặc anh em nhận một Thánh Linh khác với Thánh Linh anh em đã nhận, hoặc được một Tin Lành khác với Tin Lành anh em đã được, thì anh em chắc dung chịu!"));
visuperobject.biblemap.put("b47_11_5", new visuperobject(47,11,5,"Nhưng tôi tưởng rằng dầu các sứ đồ ấy tôn trọng đến đâu, tôi cũng chẳng thua kém chút nào."));
visuperobject.biblemap.put("b47_11_6", new visuperobject(47,11,6,"Về lời nói, tôi dầu là người thường, nhưng về sự thông biết, tôi chẳng phải là người thường: đối với anh em, chúng tôi đã tỏ điều đó ra giữa mọi người và trong mọi sự."));
visuperobject.biblemap.put("b47_11_7", new visuperobject(47,11,7,"Tôi đã rao giảng Tin Lành của Ðức Chúa Trời cho anh em một cách nhưng không, hạ mình xuống cho anh em được cao lên, vậy thì tôi có phạm lỗi gì chăng?"));
visuperobject.biblemap.put("b47_11_8", new visuperobject(47,11,8,"Tôi đã nhận lương hướng, vét lấy của Hội thánh khác đặng giúp việc anh em."));
visuperobject.biblemap.put("b47_11_9", new visuperobject(47,11,9,"Khi tôi ở cùng anh em, gặp phải lúc thiếu thốn, thì không lụy đến ai cả; vì các anh em ở xứ Ma-xê-đoan đến, đã bù lại sự thiếu thốn cho tôi. Không cứ việc gì, tôi đã giữ mình cho khỏi lụy đến anh em, tôi lại cũng sẽ giữ mình như vậy nữa."));
visuperobject.biblemap.put("b47_11_10", new visuperobject(47,11,10,"Như chắc rằng sự chơn thật của Ðấng Christ ở trong tôi, thì trong các miền xứ A-chai không ai cất lấy sự tôi khoe mình đó được."));
visuperobject.biblemap.put("b47_11_11", new visuperobject(47,11,11,"Sao vậy? Vì tôi không yêu anh em chăng? Ðã có Ðức Chúa Trời biết!"));
visuperobject.biblemap.put("b47_11_12", new visuperobject(47,11,12,"Song điều tôi làm, tôi còn làm nữa, để cất mọi mưu của kẻ tìm mưu, hầu cho trong những sự họ lấy mà khoe mình, chẳng có một sự nào trổi hơn chúng tôi được."));
visuperobject.biblemap.put("b47_11_13", new visuperobject(47,11,13,"Vì mấy người như vậy là sứ đồ giả, là kẻ làm công lừa dối, mạo chức sứ đồ của Ðấng Christ."));
visuperobject.biblemap.put("b47_11_14", new visuperobject(47,11,14,"Nào có lạ gì, chính quỉ Sa-tan mạo làm thiên sứ sáng láng."));
visuperobject.biblemap.put("b47_11_15", new visuperobject(47,11,15,"Vậy thì những kẻ giúp việc nó mạo làm kẻ giúp việc công bình cũng chẳng lại gì; nhưng sự cuối cùng họ sẽ y theo việc làm."));
visuperobject.biblemap.put("b47_11_16", new visuperobject(47,11,16,"Tôi lại nói rằng: chớ có ai xem tôi như kẻ dại dột; nếu vậy thì hãy nhận tôi như kẻ dại dột, hầu cho tôi cũng khoe mình ít nhiều."));
visuperobject.biblemap.put("b47_11_17", new visuperobject(47,11,17,"Ðiều tôi nói, là khi tôi lấy sự quả quyết dường ấy mà khoe mình, thì chẳng phải nói theo Chúa song như kẻ dại dột vậy."));
visuperobject.biblemap.put("b47_11_18", new visuperobject(47,11,18,"Bởi có nhiều người khoe mình theo xác thịt, tôi cũng sẽ khoe mình."));
visuperobject.biblemap.put("b47_11_19", new visuperobject(47,11,19,"Vì anh em là kẻ khôn ngoan lại vui mừng dung chịu kẻ dại dột."));
visuperobject.biblemap.put("b47_11_20", new visuperobject(47,11,20,"Phải, anh em hay chịu người ta bắt mình làm tôi tớ, hay là nuốt sống, hay là cướp bóc, hay là tự cao mà khinh dể anh em, vả trên mặt anh em."));
visuperobject.biblemap.put("b47_11_21", new visuperobject(47,11,21,"Tôi làm hổ thẹn cho chúng tôi nói lời nầy, chúng tôi đã tỏ mình ra yếu đuối. Nhưng, ví bằng có ai dám khoe mình về sự gì tôi nói như kẻ dại dột thì tôi cũng dám khoe mình."));
visuperobject.biblemap.put("b47_11_22", new visuperobject(47,11,22,"Họ là người Hê-bơ-rơ phải chăng? Tôi cũng vậy. Họ là người Y-sơ-ra-ên phải chăng? Tôi cũng vậy. Họ là dòng dõi của Áp-ra-ham phải chăng? Tôi cũng vậy."));
visuperobject.biblemap.put("b47_11_23", new visuperobject(47,11,23,"Họ là kẻ hầu việc của Ðấng Christ phải chăng? Ừ, tôi nói như kẻ dại dột, tôi lại là kẻ hầu việc nhiều hơn! Tôi đã chịu khó nhọc nhiều hơn, tù rạc nhiều hơn, đòn vọt quá chừng. Ðòi phen tôi gần phải bị chết;"));
visuperobject.biblemap.put("b47_11_24", new visuperobject(47,11,24,"năm lần bị người Giu-đa đánh roi, mỗi lần thiếu một roi đầy bốn chục;"));
visuperobject.biblemap.put("b47_11_25", new visuperobject(47,11,25,"ba lần bị đánh đòn; một lần bị ném đá; ba lần bị chìm tàu. Tôi đã ở trong biển sâu một ngày một đêm."));
visuperobject.biblemap.put("b47_11_26", new visuperobject(47,11,26,"Lại nhiều lần tôi đi đường nguy trên sông bến, nguy với trộm cướp, nguy với giữa dân mình, nguy với dân ngoại, nguy trong các thành, nguy trong các đồng vắng, nguy trên biển, nguy với anh em giả dối;"));
visuperobject.biblemap.put("b47_11_27", new visuperobject(47,11,27,"chịu khó chịu nhọc, lắm lúc thức đêm, chịu đói khát, thường khi phải nhịn ăn, chịu lạnh và lõa lồ."));
visuperobject.biblemap.put("b47_11_28", new visuperobject(47,11,28,"Còn chưa kể mọi sự khác, là mỗi ngày tôi phải lo lắng về hết thảy các Hội thánh."));
visuperobject.biblemap.put("b47_11_29", new visuperobject(47,11,29,"Nào có ai yếu đuối mà tôi chẳng yếu đuối ư? Nào có ai vấp ngã mà tôi chẳng như nung như đốt ư?"));
visuperobject.biblemap.put("b47_11_30", new visuperobject(47,11,30,"Vì phải khoe mình, thì tôi sẽ khoe mình về sự yếu đuối tôi."));
visuperobject.biblemap.put("b47_11_31", new visuperobject(47,11,31,"Ðức Chúa Trời là Cha Ðức Chúa Jêsus, là Ðấng đáng ngợi khen đời đời vô cùng, biết rằng tôi không nói dối đâu."));
visuperobject.biblemap.put("b47_11_32", new visuperobject(47,11,32,"Ở thành Ða-mách, quan tổng đốc của vua A-rê-ta giữ thành của người Ða-mách để bắt tôi."));
visuperobject.biblemap.put("b47_11_33", new visuperobject(47,11,33,"Có người từ cửa sổ dòng tôi xuống, bằng một cái giỏ, dọc theo lưng thành, ấy vậy là tôi thoát khỏi tay họ."));
visuperobject.biblemap.put("b47_12_1", new visuperobject(47,12,1,"Tôi cần phải khoe mình, dầu chẳng có ích gì; nhưng tôi sẽ nói đến các sự hiện thấy và sự Chúa đã tỏ ra."));
visuperobject.biblemap.put("b47_12_2", new visuperobject(47,12,2,"Tôi biết một người trong Ðấng Christ, cách mười bốn năm trước, đã được đem lên đến từng trời thứ ba (hoặc trong thân thể người, hoặc ngoài thân thể người, tôi chẳng biết, có Ðức Chúa Trời biết)."));
visuperobject.biblemap.put("b47_12_3", new visuperobject(47,12,3,"Tôi biết người đó (hoặc trong thân thể người, hoặc ngoài thân thể người, tôi chẳng biết, có Ðức Chúa Trời biết)"));
visuperobject.biblemap.put("b47_12_4", new visuperobject(47,12,4,"được đem lên đến chốn Ba-ra-đi, ở đó, nghe những lời không thể nói, mà không có phép cho người nào nói ra."));
visuperobject.biblemap.put("b47_12_5", new visuperobject(47,12,5,"Về người đó, tôi sẽ khoe mình; nhưng về chính mình tôi, tôi không khoe, chỉ khoe về sự yếu đuối của tôi mà thôi."));
visuperobject.biblemap.put("b47_12_6", new visuperobject(47,12,6,"Dầu tôi muốn khoe mình, thì cũng không phải là một người dại dột, vì tôi sẽ nói thật; nhưng tôi giữ, không nói, hầu cho chẳng ai nghĩ tôi vượt quá sự họ thấy ở nơi tôi và nghe tôi nói."));
visuperobject.biblemap.put("b47_12_7", new visuperobject(47,12,7,"Vậy nên, e rằng tôi lên mình kiêu ngạo bởi sự cao trọng cả thể của những sự tỏ ra ấy chăng, thì đã cho một cái giằm xóc vào thịt tôi, tức là quỉ sứ của Sa-tan, để vả tôi, và làm cho tôi đừng kiêu ngạo."));
visuperobject.biblemap.put("b47_12_8", new visuperobject(47,12,8,"Ðã ba lần tôi cầu nguyện Chúa cho nó lìa xa tôi."));
visuperobject.biblemap.put("b47_12_9", new visuperobject(47,12,9,"Nhưng Chúa phán rằng: Aân điển ta đủ cho ngươi rồi, vì sức mạnh của ta nên trọn vẹn trong sự yếu đuối. Vậy, tôi sẽ rất vui lòng khoe mình về sự yếu đuối tôi, hầu cho sức mạnh của Ðấng Christ ở trong tôi."));
visuperobject.biblemap.put("b47_12_10", new visuperobject(47,12,10,"Cho nên tôi vì Ðấng Christ mà đành chịu trong sự yếu đuối, nhuốc nha, túng ngặt, bắt bớ, khốn khó; vì khi tôi yếu đuối, ấy là lúc tôi mạnh mẽ."));
visuperobject.biblemap.put("b47_12_11", new visuperobject(47,12,11,"Tôi đã nên dại dột bởi anh em ép uổng tôi; lẽ thì anh em khen lao tôi mới phải, vì dầu tôi không ra gì, cũng chẳng kém các sứ đồ rất lớn kia chút nào."));
visuperobject.biblemap.put("b47_12_12", new visuperobject(47,12,12,"Các bằng cớ về chức sứ đồ tôi đã tỏ ra trong anh em bởi sự nhịn nhục mọi đàng, bởi các phép lạ."));
visuperobject.biblemap.put("b47_12_13", new visuperobject(47,12,13,"Vả, nếu trừ ra sự chính tôi không làm lụy cho anh em, thì anh em có việc gì mà chẳng bằng các Hội thánh khác? Xin tha thứ cho tôi sự không công bình đó!"));
visuperobject.biblemap.put("b47_12_14", new visuperobject(47,12,14,"Nầy là lần thứ ba tôi sẵn sàng đi đến cùng anh em, và tôi sẽ chẳng làm lụy cho anh em đâu, vì không phải tôi tìm của cải anh em, bèn là tìm chính anh em vậy; thật, chẳng phải con cái nên chứa của quí cho cha mẹ, nhưng thà cha mẹ chứa cho con cái thì hơn."));
visuperobject.biblemap.put("b47_12_15", new visuperobject(47,12,15,"Về phần tôi, tôi rất vui lòng phí của và phí trọn cả mình tôi vì linh hồn anh em, dẫu rằng tôi yêu anh em thêm, mà cần phải bị anh em yêu tôi kém."));
visuperobject.biblemap.put("b47_12_16", new visuperobject(47,12,16,"Tuy rằng tôi chưa từng làm lụy cho anh em, nhưng tôi là người khôn khéo, đã dùng mưu kế mà bắt lấy anh em!"));
visuperobject.biblemap.put("b47_12_17", new visuperobject(47,12,17,"Vậy tôi há đã dùng một người nào trong những kẻ tôi sai đến cùng anh em mà lấy lợi của anh em chăng?"));
visuperobject.biblemap.put("b47_12_18", new visuperobject(47,12,18,"Tôi đã xin Tít đi thăm anh em, lại đã sai một người trong anh em chúng tôi cùng đi với người. Có phải là Tít đã lấy lợi của anh em không? Chúng tôi há chẳng bước đi bởi một Thánh Linh, theo cùng một dấu chơn sao?"));
visuperobject.biblemap.put("b47_12_19", new visuperobject(47,12,19,"Ðã lâu nay, anh em tưởng rằng chúng tôi tìm cách chữa mình trước mặt anh em. Ấy là trong Ðấng Christ, trước mặt Ðức Chúa Trời mà chúng tôi nói; hỡi những kẻ rất yêu dấu, mọi điều đó thảy vì sự gây dựng cho anh em."));
visuperobject.biblemap.put("b47_12_20", new visuperobject(47,12,20,"Vì tôi e rằng khi tôi đến, chẳng thấy anh em như tôi ước ao, lại về phần anh em, chẳng thấy tôi như anh em đã ước ao chăng. Tôi còn e rằng trong các anh em có những điều rầy rà, ghen ghét, nóng giận, bất hòa, nói hành, nói gần nói xa, kiêu căng, hỗn loạn chăng."));
visuperobject.biblemap.put("b47_12_21", new visuperobject(47,12,21,"Có lẽ nào khi tôi đến nơi anh em, Ðức Chúa Trời lại làm cho tôi phải hạ mình xuống về việc anh em một lần nữa, và tôi sẽ phải khóc lóc về nhiều kẻ trước đã phạm tội mà không ăn năn về những sự ô uế, gian dâm, luông tuồng họ đã phạm, hay sao?"));
visuperobject.biblemap.put("b47_13_1", new visuperobject(47,13,1,"Nầy là lần thứ ba mà tôi sẽ đi đến nơi anh em. Mọi việc sẽ định cứ lời khai của hai hoặc ba người làm chứng."));
visuperobject.biblemap.put("b47_13_2", new visuperobject(47,13,2,"Ðiều đó tôi đã nói rồi, bây giờ lại nói rồi nữa, ngày nay tôi dầu vắng mặt, nhưng không khác lúc tôi ở với anh em lần thứ hai: tôi rao cho kẻ trước có phạm tội và cho mọi kẻ khác rằng, nếu tôi lại đến, thì chẳng dung thứ chi hết,"));
visuperobject.biblemap.put("b47_13_3", new visuperobject(47,13,3,"vì anh em phải có một bằng cớ rằng Ðấng Christ phán bởi tôi, tức là Ðấng đối với anh em chẳng phải là yếu đuối đâu, bèn là mạnh mẽ ở giữa anh em vậy."));
visuperobject.biblemap.put("b47_13_4", new visuperobject(47,13,4,"Bởi vì, dầu Ngài nhơn sự yếu đuối đã bị đóng đinh vào thập tự giá, nhưng Ngài sống bởi quyền phép Ðức Chúa Trời; chúng tôi cũng vậy, dầu là yếu đuối trong Ngài, nhưng nhờ quyền phép Ðức Chúa Trời thì cũng sẽ sống với Ngài, đặng làm việc giữa anh em."));
visuperobject.biblemap.put("b47_13_5", new visuperobject(47,13,5,"Chính anh em hãy tự xét để xem mình có đức tin chăng. Hãy tự thử mình: anh em há không nhận biết rằng có Ðức Chúa Jêsus Christ ở trong anh em sao? miễn là anh em không đáng bị bỏ."));
visuperobject.biblemap.put("b47_13_6", new visuperobject(47,13,6,"Song tôi mong anh em nhận biết rằng chúng tôi chẳng đáng bị bỏ."));
visuperobject.biblemap.put("b47_13_7", new visuperobject(47,13,7,"Nhưng chúng ta cầu xin Ðức Chúa Trời cho anh em đừng làm việc ác nào, chẳng phải để tỏ ra chính chúng tôi được ưng chịu, song hầu cho anh em làm điều thiện, mặt dầu chúng tôi như đáng bị bỏ."));
visuperobject.biblemap.put("b47_13_8", new visuperobject(47,13,8,"Vì chúng tôi chẳng có thể nghịch cùng lẽ thật, nhưng chỉ có thể thuận theo lẽ thật."));
visuperobject.biblemap.put("b47_13_9", new visuperobject(47,13,9,"Dầu chúng tôi yếu đuối, miễn là anh em được mạnh mẽ thì chúng tôi cũng vui mừng; và điều chúng tôi cầu xin, ấy là cho anh em được nên trọn vẹn."));
visuperobject.biblemap.put("b47_13_10", new visuperobject(47,13,10,"Vậy nên khi vắng mặt, tôi viết những điều nầy, để khi tôi có mặt, không dùng thẳng phép, theo quyền Chúa ban cho tôi, để gây dựng chớ không phải để hủy diệt."));
visuperobject.biblemap.put("b47_13_11", new visuperobject(47,13,11,"Rốt lại, hỡi anh em, hãy mừng rỡ; khá theo đến sự trọn lành; hãy yên ủi mình, hiệp một tâm tình, ở cho hòa thuận, thì Ðức Chúa Trời sự yêu thương và sự bình an sẽ ở cùng anh em."));
visuperobject.biblemap.put("b47_13_12", new visuperobject(47,13,12,"Hãy lấy cái hôn thành mà chào nhau."));
visuperobject.biblemap.put("b47_13_13", new visuperobject(47,13,13,"Hết thảy thánh đồ chào anh em."));
visuperobject.biblemap.put("b47_13_14", new visuperobject(47,13,14,"Nguyền xin ơn của Ðức Chúa Jêsus Christ, sự yêu thương của Ðức Chúa Trời, và sự giao thông của Ðức Thánh Linh ở với anh em hết thảy!"));

}

}