package vi.bible;

public class vibible48 {

public vibible48() {

putmapbible48();

}

private void putmapbible48() {

visuperobject.biblemap.put("b48_1_1", new visuperobject(48,1,1,"Phao-lô, làm sứ đồ, chẳng phải bởi loài người, cũng không nhờ một người nào, bèn là bởi Ðức Chúa Jêsus Christ và Ðức Chúa Trời, tức là Cha, Ðấng đã khiến Ngài từ kẻ chết sống lại,"));
visuperobject.biblemap.put("b48_1_2", new visuperobject(48,1,2,"cùng hết thảy anh em ở với tôi, gởi cho các Hội thánh ở xứ Ga-la-ti:"));
visuperobject.biblemap.put("b48_1_3", new visuperobject(48,1,3,"nguyền xin anh em được ân điển và sự bình an ban cho bởi Ðức Chúa Jêsus Christ, là Chúa chúng ta,"));
visuperobject.biblemap.put("b48_1_4", new visuperobject(48,1,4,"là Ðấng phó mình vì tội lỗi chúng ta, hầu cho cứu chúng ta khỏi đời ác nầy, y theo ý muốn Ðức Chúa Trời, là Cha chúng ta,"));
visuperobject.biblemap.put("b48_1_5", new visuperobject(48,1,5,"nguyền Ngài được vinh hiển đời đời vô cùng! A-men."));
visuperobject.biblemap.put("b48_1_6", new visuperobject(48,1,6,"Tôi lấy làm lạ cho anh em đã vội bỏ Ðấng gọi anh em bởi ơn Ðức Chúa Jêsus Christ, đặng theo tin lành khác."));
visuperobject.biblemap.put("b48_1_7", new visuperobject(48,1,7,"Thật chẳng phải có tin lành khác, nhưng có mấy kẻ làm rối trí anh em, và muốn đánh đổ Tin Lành của Ðấng Christ."));
visuperobject.biblemap.put("b48_1_8", new visuperobject(48,1,8,"Nhưng nếu có ai, hoặc chính chúng tôi, hoặc thiên sứ trên trời, truyền cho anh em một tin lành nào khác với Tin Lành đã truyền cho anh em, thì người ấy đáng bị a-na-them!"));
visuperobject.biblemap.put("b48_1_9", new visuperobject(48,1,9,"Tôi đã nói rồi, nay lại nói lần nữa: Nếu ai truyền cho anh em một tin lành nào khác với Tin Lành anh em đã nhận, thì người ấy đáng bị a-na-them!"));
visuperobject.biblemap.put("b48_1_10", new visuperobject(48,1,10,"Còn bây giờ, có phải tôi mong người ta ưng chịu tôi hay là Ðức Chúa Trời? Hay là tôi muốn đẹp lòng loài người chăng? Ví bằng tôi còn làm cho đẹp lòng loài người, thì tôi chẳng phải là tôi tớ của Ðấng Christ."));
visuperobject.biblemap.put("b48_1_11", new visuperobject(48,1,11,"Hỡi anh em, tôi nói cho anh em rằng, Tin Lành mà tôi đã truyền, chẳng phải đến từ loài người đâu;"));
visuperobject.biblemap.put("b48_1_12", new visuperobject(48,1,12,"vì tôi không nhận và cũng không học Tin Lành đó với một người nào, nhưng đã nhận lấy bởi sự tỏ ra của Ðức Chúa Jêsus Christ."));
visuperobject.biblemap.put("b48_1_13", new visuperobject(48,1,13,"Vả, anh em đã nghe lúc trước tôi theo giáo Giu-đa, cách cư xử của tôi là thể nào, tôi bắt bớ và phá tan Hội thánh của Ðức Chúa Trời quá chừng;"));
visuperobject.biblemap.put("b48_1_14", new visuperobject(48,1,14,"tôi tấn tới trong giáo Giu-đa hơn nhiều người cùng tuổi cùng nước với tôi, tôi là người sốt sắng quá đỗi về cựu truyền của tổ phụ tôi."));
visuperobject.biblemap.put("b48_1_15", new visuperobject(48,1,15,"Nhưng khi Ðức Chúa Trời, là Ðấng đã để riêng tôi ra từ lúc còn trong lòng mẹ, và lấy ân điển gọi tôi, vui lòng"));
visuperobject.biblemap.put("b48_1_16", new visuperobject(48,1,16,"bày tỏ Con của Ngài ra trong tôi, hầu cho tôi rao truyền Con đó ra trong người ngoại đạo, thì lập tức tôi chẳng bàn với thịt và máu."));
visuperobject.biblemap.put("b48_1_17", new visuperobject(48,1,17,"Tôi cũng không lên thành Giê-ru-sa-lem, đến cùng những người đã làm sứ đồ trước tôi, song tôi đi qua xứ A-ra-bi; sau rồi trở về thành Ða-mách."));
visuperobject.biblemap.put("b48_1_18", new visuperobject(48,1,18,"Kế đó, mãn ba năm, tôi lên thành Giê-ru-sa-lem, đặng làm quen với Sê-pha, và tôi ở với người mười lăm ngày;"));
visuperobject.biblemap.put("b48_1_19", new visuperobject(48,1,19,"nhưng tôi không thấy một sứ đồ nào khác, trừ ra Gia-cơ là anh em của Chúa."));
visuperobject.biblemap.put("b48_1_20", new visuperobject(48,1,20,"Thật, trước mặt Ðức Chúa Trời, tôi quyết rằng điều tôi viết cho anh em đây chẳng phải là điều dối."));
visuperobject.biblemap.put("b48_1_21", new visuperobject(48,1,21,"Sau lại, tôi đi qua các miền thuộc xứ Sy-ri và xứ Si-li-si,"));
visuperobject.biblemap.put("b48_1_22", new visuperobject(48,1,22,"bấy giờ tôi còn là kẻ lạ mặt trong các Hội thánh tại xứ Giu-đê, là các hội ở trong Ðấng Christ."));
visuperobject.biblemap.put("b48_1_23", new visuperobject(48,1,23,"chỉn các hội đó có nghe rằng: Người đã bắt bớ chúng ta ngày trước, nay đương truyền đạo mà lúc bấy giờ người cố sức phá."));
visuperobject.biblemap.put("b48_1_24", new visuperobject(48,1,24,"Vậy thì, các hội đó vì cớ tôi khen ngợi Ðức Chúa Trời."));
visuperobject.biblemap.put("b48_2_1", new visuperobject(48,2,1,"Sau đó mười bốn năm, tôi lại lên thành Giê-ru-sa-lem với Ba-na-ba, có đem Tít cùng đi nữa."));
visuperobject.biblemap.put("b48_2_2", new visuperobject(48,2,2,"Tôi vâng theo lời tỏ ra mà lên đó, phô bày Tin Lành mà tôi đã giảng trong người ngoại đạo ra cho anh em; lại phô bày riêng cho những kẻ có danh vọng hơn hết, kẻo sự chạy của tôi trước kia và bây giờ hóa ra vô ích chăng."));
visuperobject.biblemap.put("b48_2_3", new visuperobject(48,2,3,"Dầu Tít, kẻ cùng đi với tôi, là người Gờ-réc, cũng không bị ép phải cắt bì."));
visuperobject.biblemap.put("b48_2_4", new visuperobject(48,2,4,"Chúng tôi đã làm như vậy, vì cớ mấy người anh em giả, lẻn vào trong vòng chúng tôi, để rình xem sự tự do mà chúng tôi được trong Ðức Chúa Jêsus Christ, đặng bắt chúng tôi làm tôi mọi."));
visuperobject.biblemap.put("b48_2_5", new visuperobject(48,2,5,"Chúng tôi không nhường họ một giây phút nào, chối chẳng chịu thuộc dưới quyền họ, hầu cho lẽ thật của Tin Lành được vững bền trong anh em."));
visuperobject.biblemap.put("b48_2_6", new visuperobject(48,2,6,"Còn như những kẻ mà người ta tôn trọng lắm, (trước kia là kẻ thể nào, thì chẳng can dự gì với tôi, Ðức Chúa Trời không tây vị ai hết), tôi nói, những kẻ đó dầu tôn trọng lắm, cũng chẳng làm cho tôi thêm ích chút nào."));
visuperobject.biblemap.put("b48_2_7", new visuperobject(48,2,7,"Trái lại, họ thấy sự giảng Tin Lành cho kẻ không chịu phép cắt bì đã giao cho tôi, cũng như sự giảng Tin Lành cho người chịu phép cắt bì đã giao cho Phi -e-rơ vậy,"));
visuperobject.biblemap.put("b48_2_8", new visuperobject(48,2,8,"vì Ðấng đã cảm động trong Phi -e-rơ để sai người làm sứ đồ cho những kẻ chịu cắt bì, cũng cảm động trong tôi để sai tôi làm sứ đồ cho dân ngoại,"));
visuperobject.biblemap.put("b48_2_9", new visuperobject(48,2,9,"và nhận biết ân điển đã ban cho tôi, thì Gia-cơ, Sê-pha, Giăng là những người được tôn như cột trụ, trao tay hữu giao kết với chúng tôi, tức là Ba-na-ba và tôi, hầu cho chúng tôi đi đến cùng dân ngoại, còn các người ấy thì đến cùng những kẻ chịu phép cắt bì."));
visuperobject.biblemap.put("b48_2_10", new visuperobject(48,2,10,"Các người ấy chỉ dặn dò tôi phải nhớ đến kẻ nghèo nàn, là điều tôi cũng đã ân cần làm lắm."));
visuperobject.biblemap.put("b48_2_11", new visuperobject(48,2,11,"Nhưng khi Sê-pha đến thành An-ti-ốt, tôi có ngăn can trước mặt người, vì là đáng trách lắm."));
visuperobject.biblemap.put("b48_2_12", new visuperobject(48,2,12,"Bởi trước lúc mấy kẻ của Gia-cơ sai đi chưa đến, thì người ăn chung với người ngoại; vừa khi họ đã đến thì người lui đứng riêng ra, bởi sợ những kẻ chịu phép cắt bì."));
visuperobject.biblemap.put("b48_2_13", new visuperobject(48,2,13,"Các người Giu-đa khác cũng dùng một cách giả dối như vậy, đến nỗi chính Ba-na-ba cũng bị sự giả hình của họ dẫn dụ."));
visuperobject.biblemap.put("b48_2_14", new visuperobject(48,2,14,"Nhưng khi tôi thấy họ không đi ngay thẳng theo lẽ thật của Tin Lành, thì nói với Sê-pha trước mặt mọi người rằng: nếu anh là người Giu-đa, mà ăn ở theo cách dân ngoại, không theo cách người Giu-đa, thì làm sao anh ép dân ngoại phải theo thói Giu-đa?"));
visuperobject.biblemap.put("b48_2_15", new visuperobject(48,2,15,"Về phần chúng tôi, thì sanh ra là người Giu-đa, không phải là kẻ có tội từ trong dân ngoại."));
visuperobject.biblemap.put("b48_2_16", new visuperobject(48,2,16,"Dầu vậy, đã biết rằng người ta được xưng công bình, chẳng phải bởi các việc luật pháp đâu, bèn là cậy đức tin trong Ðức Chúa Jêsus Christ, nên chính chúng tôi đã tin Ðức Chúa Jêsus Christ, để được xưng công bình bởi đức tin trong Ðấng Christ, chớ chẳng bởi các việc luật pháp; vì chẳng có ai được xưng công bình bởi các việc luật pháp."));
visuperobject.biblemap.put("b48_2_17", new visuperobject(48,2,17,"Nhưng nếu đang khi chúng tôi tìm cách được xưng công bình trong Ðấng Christ, mà chính chúng tôi bị nhận là kẻ có tội, vậy thì Ðấng Christ chẳng là làm tôi của tội lỗi sao? Chẳng hề như vậy!"));
visuperobject.biblemap.put("b48_2_18", new visuperobject(48,2,18,"Thật thế, nếu tôi lập lại điều tôi đã phá hủy, thì tôi sẽ tỏ ra chính tôi là người phạm phép."));
visuperobject.biblemap.put("b48_2_19", new visuperobject(48,2,19,"Vả, bởi luật pháp, tôi đã chết cho luật pháp, để sống cho Ðức Chúa Trời."));
visuperobject.biblemap.put("b48_2_20", new visuperobject(48,2,20,"Tôi đã bị đóng đinh vào thập tự giá với Ðấng Christ, mà tôi sống, không phải là tôi sống nữa, nhưng Ðấng Christ sống trong tôi; nay tôi còn sống trong xác thịt, ấy là tôi sống trong đức tin của Con Ðức Chúa Trời, là Ðấng đã yêu tôi, và đã phó chính mình Ngài vì tôi."));
visuperobject.biblemap.put("b48_2_21", new visuperobject(48,2,21,"Tôi không muốn làm cho ân điển Ðức Chúa Trời ra vô ích; vì nếu bởi luật pháp mà được sự công bình, thì Ðấng Christ chịu chết là vô ích."));
visuperobject.biblemap.put("b48_3_1", new visuperobject(48,3,1,"Hỡi người Ga-la-ti ngu muội kia, ai bùa ếm anh em là người Ðức Chúa Jêsus Christ bị đóng đinh trên thập tự giá?"));
visuperobject.biblemap.put("b48_3_2", new visuperobject(48,3,2,"Tôi chỉ hỏi anh em một câu nầy: Ấy là cậy các việc luật pháp hay là bởi nghe và tin mà anh em đã nhận được Ðức Thánh Linh?"));
visuperobject.biblemap.put("b48_3_3", new visuperobject(48,3,3,"Sao anh em ngu muội dường ấy? Sau khi đã khởi sự nhờ Ðức Thánh Linh, nay sao lại cậy xác thịt mà làm cho trọn?"));
visuperobject.biblemap.put("b48_3_4", new visuperobject(48,3,4,"Anh em há luống công mà chịu sự khốn khổ dường ấy sao? nếu quả là luống công!"));
visuperobject.biblemap.put("b48_3_5", new visuperobject(48,3,5,"Ðấng ban Ðức Thánh Linh cho anh em và làm các phép lạ trong anh em, thì làm bởi các việc luật pháp, hay là bởi đã nghe mà tin?"));
visuperobject.biblemap.put("b48_3_6", new visuperobject(48,3,6,"Như Áp-ra-ham tin Ðức Chúa Trời, thì đã kể là công bình cho người,"));
visuperobject.biblemap.put("b48_3_7", new visuperobject(48,3,7,"vậy anh em hãy nhận biết rằng những kẻ có đức tin là con cháu thật của Áp-ra-ham."));
visuperobject.biblemap.put("b48_3_8", new visuperobject(48,3,8,"Kinh Thánh cũng biết trước rằng Ðức Chúa Trời sẽ xưng dân ngoại là công bình bởi đức tin, nên đã rao truyền trước cho Áp-ra-ham tin lành nầy: Các dân sẽ nhờ ngươi mà được phước."));
visuperobject.biblemap.put("b48_3_9", new visuperobject(48,3,9,"Ấy vậy, ai tin thì nấy được phước với Áp-ra-ham, là người có lòng tin."));
visuperobject.biblemap.put("b48_3_10", new visuperobject(48,3,10,"Vì mọi kẻ cậy các việc luật pháp, thì bị rủa sả, bởi có chép rằng: Ðáng rủa thay là kẻ không bền đỗ trong mọi sự đã chép ở sách luật, đặng làm theo những sự ấy!"));
visuperobject.biblemap.put("b48_3_11", new visuperobject(48,3,11,"Vả lại chẳng hề có ai cậy luật pháp mà được xưng công bình trước mặt Ðức Chúa Trời, điều đó là rõ ràng lắm, vì người công bình sẽ sống bởi đức tin."));
visuperobject.biblemap.put("b48_3_12", new visuperobject(48,3,12,"Vả, luật pháp vốn không phải đồng một thứ với đức tin, nhưng luật pháp có chép rằng: Người nào vâng giữ các điều răn thì sẽ nhờ đó mà sống."));
visuperobject.biblemap.put("b48_3_13", new visuperobject(48,3,13,"Ðấng Christ đã chuộc chúng ta khỏi sự rủa sả của luật pháp, bởi Ngài đã nên sự rủa sả vì chúng ta, vì có lời chép: Ðáng rủa thay là kẻ bị treo trên cây gỗ,"));
visuperobject.biblemap.put("b48_3_14", new visuperobject(48,3,14,"hầu cho phước lành ban cho Áp-ra-ham nhờ Ðức Chúa Jêsus Christ mà được rải khắp trên dân ngoại, lại hầu cho chúng ta cậy đức tin mà nhận lãnh Ðức Thánh Linh đã hứa cho."));
visuperobject.biblemap.put("b48_3_15", new visuperobject(48,3,15,"Hỡi Anh em, tôi nói theo thói quen người ta rằng: Khi một người đã làm tờ giao ước thành rồi, thì không ai có phép được xóa đi hay thêm vào sự gì."));
visuperobject.biblemap.put("b48_3_16", new visuperobject(48,3,16,"Vả, các lời hứa đã được phán cho Áp-ra-ham và cho dòng dõi người. không nói: Và cho các dòng dõi người, như chỉ về nhiều người; nhưng nói: Và cho dòng dõi ngươi, như chỉ về một người mà thôi, tức là Ðấng Christ."));
visuperobject.biblemap.put("b48_3_17", new visuperobject(48,3,17,"Vậy thì tôi nói rằng: Lời giao ước mà Ðức Chúa Trời trước kia đã kết lập thành rồi, thì không có thể bị hủy đi, và lời hứa cũng không có thể bị bỏ đi bởi luật pháp, là sự cách sau bốn trăm ba mươi năm mới có."));
visuperobject.biblemap.put("b48_3_18", new visuperobject(48,3,18,"Vì, nếu cơ nghiệp được ban cho bởi luật pháp, thì không bởi lời hứa nữa. Nhưng Ðức Chúa Trời đã dùng lời hứa mà ban cơ nghiệp cho Áp-ra-ham."));
visuperobject.biblemap.put("b48_3_19", new visuperobject(48,3,19,"Vậy thì làm sao có luật pháp? luật pháp đã đặt thêm, vì cớ những sự phạm phép, cho tới chừng nào người dòng dõi đến, là người mà lời hứa đã hứa cho; luật pháp được ban ra bởi mấy thiên sứ và truyền ra bởi một người trung bảo."));
visuperobject.biblemap.put("b48_3_20", new visuperobject(48,3,20,"Vả, người trung bảo chẳng phải là người trung bảo về một bề mà thôi, nhưng Ðức Chúa Trời chỉ có một."));
visuperobject.biblemap.put("b48_3_21", new visuperobject(48,3,21,"Vậy thì luật pháp nghịch cùng lời hứa của Ðức Chúa Trời hay sao? chẳng hề như vậy; vì nếu đã ban cho một luật pháp có thể làm cho sống, thì sự công bình chắc bởi luật pháp mà đến."));
visuperobject.biblemap.put("b48_3_22", new visuperobject(48,3,22,"Nhưng Kinh Thánh đã nhốt hết thảy mọi sự dưới tội lỗi, hầu cho điều chi đã hứa, bởi đức tin trong Ðức Chúa Jêsus Christ mà được ban cho những kẻ tin."));
visuperobject.biblemap.put("b48_3_23", new visuperobject(48,3,23,"Trước khi đức tin chưa đến, chúng ta bị nhốt dưới sự canh giữ của luật pháp mà chờ đức tin phải bày ra."));
visuperobject.biblemap.put("b48_3_24", new visuperobject(48,3,24,"Ấy vậy, luật pháp đã như thầy giáo đặng dẫn chúng ta đến Ðấng Christ, hầu cho chúng ta bởi đức tin mà được xưng công bình."));
visuperobject.biblemap.put("b48_3_25", new visuperobject(48,3,25,"Song khi đức tin đã đến, chúng ta không còn phục dưới thầy giáo ấy nữa."));
visuperobject.biblemap.put("b48_3_26", new visuperobject(48,3,26,"Vì chưng anh em bởi tin Ðức Chúa Jêsus Christ, nên hết thảy đều là con trai của Ðức Chúa Trời."));
visuperobject.biblemap.put("b48_3_27", new visuperobject(48,3,27,"Vả, anh em thảy đều chịu phép báp tem trong Ðấng Christ, đều mặc lấy Ðấng Christ vậy."));
visuperobject.biblemap.put("b48_3_28", new visuperobject(48,3,28,"Tại đây không còn chia ra người Giu-đa hoặc người Gờ-réc; không còn người tôi mọi hoặc người tự chủ; không còn đờn ông hoặc đờn bà; vì trong Ðức Chúa Jêsus Christ, anh em thảy đều làm một."));
visuperobject.biblemap.put("b48_3_29", new visuperobject(48,3,29,"Lại nếu anh em thuộc về Ðấng Christ, thì anh em là dòng dõi của Áp-ra-ham, tức là kẻ kế tự theo lời hứa."));
visuperobject.biblemap.put("b48_4_1", new visuperobject(48,4,1,"Vả, tôi nói rằng người kế tự dầu là chủ của mọi vật, mà đương còn thơ ấu, thì chẳng khác chi kẻ tôi mọi;"));
visuperobject.biblemap.put("b48_4_2", new visuperobject(48,4,2,"phải ở dưới quyền kẻ bảo hộ và kẻ coi giữ, cho đến kỳ người cha đã định."));
visuperobject.biblemap.put("b48_4_3", new visuperobject(48,4,3,"Chúng ta cũng như vậy, khi còn thơ ấu, phải phục dưới các lề thói của thế gian."));
visuperobject.biblemap.put("b48_4_4", new visuperobject(48,4,4,"Nhưng khi kỳ hạn đã được trọn, Ðức Chúa Trời bèn sai Con Ngài bởi một người nữ sanh ra, sanh ra dưới luật pháp,"));
visuperobject.biblemap.put("b48_4_5", new visuperobject(48,4,5,"để chuộc những kẻ ở dưới luật pháp, và cho chúng ta được làm con nuôi Ngài."));
visuperobject.biblemap.put("b48_4_6", new visuperobject(48,4,6,"Lại vì anh em là con, nên Ðức Chúa Trời đã sai Thánh Linh của Con Ngài vào lòng chúng ta, kêu rằng: A-ba! Cha!"));
visuperobject.biblemap.put("b48_4_7", new visuperobject(48,4,7,"Dường ấy, người không phải là tôi mọi nữa, bèn là con; và nếu ngươi là con, thì cũng là kẻ kế tự bởi ơn của Ðức Chúa Trời."));
visuperobject.biblemap.put("b48_4_8", new visuperobject(48,4,8,"Xưa kia, anh em chẳng biết Ðức Chúa Trời chi hết, thì làm tôi các thần vốn không phải là thần."));
visuperobject.biblemap.put("b48_4_9", new visuperobject(48,4,9,"Nhưng hiện nay anh em biết Ðức Chúa Trời lại được Ðức Chúa Trời biết đến nữa, sao còn trở hướng về lề thói hèn yếu nghèo nàn đó mà suy phục nữa ư?"));
visuperobject.biblemap.put("b48_4_10", new visuperobject(48,4,10,"anh em hãy còn giữ ngày tháng, mùa, năm ư!"));
visuperobject.biblemap.put("b48_4_11", new visuperobject(48,4,11,"Tôi lo cho anh em, e tôi đã làm việc luống công giữa anh em."));
visuperobject.biblemap.put("b48_4_12", new visuperobject(48,4,12,"Hỡi anh em, tôi xin anh em hãy giống như tôi; vì tôi cũng như anh em. Anh em không làm hại gì cho tôi."));
visuperobject.biblemap.put("b48_4_13", new visuperobject(48,4,13,"Anh em biết rằng ấy là đương lúc xác thịt yếu đuối mà tôi truyền Tin Lành cho anh em lần thứ nhứt,"));
visuperobject.biblemap.put("b48_4_14", new visuperobject(48,4,14,"vì xác thịt tôi yếu đuối sanh ra sự rèn thử cho anh em mặc dầu, anh em cũng chẳng khinh tôi, chẳng chối tôi, mà lại tiếp rước tôi như một vị thiên sứ của Ðức Chúa Trời, thật như chính mình Ðức Chúa Jêsus Christ."));
visuperobject.biblemap.put("b48_4_15", new visuperobject(48,4,15,"Vậy thì sự vui mừng của anh em đã trở nên thể nào? Vì tôi làm chứng cho anh em rằng, lúc bấy giờ, nếu có thể được thì anh em cũng móc con mắt mà cho tôi."));
visuperobject.biblemap.put("b48_4_16", new visuperobject(48,4,16,"Tôi lấy lẽ thật bảo anh em, lại trở nên kẻ thù nghịch của anh em sao?"));
visuperobject.biblemap.put("b48_4_17", new visuperobject(48,4,17,"Những người đó vì anh em mà sốt sắng, thì không phải là ý tốt; nhưng họ muốn anh em lìa bỏ chúng tôi, hầu cho anh em sốt sắng vì họ."));
visuperobject.biblemap.put("b48_4_18", new visuperobject(48,4,18,"Có lòng sốt sắng vì điều thiện thì tốt lắm, lúc nào cũng thế, không những khi tôi có mặt giữa anh em."));
visuperobject.biblemap.put("b48_4_19", new visuperobject(48,4,19,"Hỡi các con, vì các con mà ta lại chịu đau đớn của sự sanh nở, cho đến chừng nào Ðấng Christ thành hình trong các con,"));
visuperobject.biblemap.put("b48_4_20", new visuperobject(48,4,20,"ta muốn ở cùng các con và thay đổi cách nói; vì về việc các con, ta rất là bối rối khó xử."));
visuperobject.biblemap.put("b48_4_21", new visuperobject(48,4,21,"Hãy nói cho tôi, anh em là kẻ ưa phục dưới luật pháp, há không nghe luật pháp sao?"));
visuperobject.biblemap.put("b48_4_22", new visuperobject(48,4,22,"Vì có chép rằng Áp-ra-ham có hai con trai: một là con của người nữ tôi mọi, một là con của người nữ tự chủ."));
visuperobject.biblemap.put("b48_4_23", new visuperobject(48,4,23,"Nhưng con của người nữ tôi mọi sanh ra theo xác thịt, con của người nữ tự chủ sanh ra theo lời hứa."));
visuperobject.biblemap.put("b48_4_24", new visuperobject(48,4,24,"Cả điều đó có một nghĩa bóng: hai người nữ đó tức là hai lời giao ước, một là lời giao ước tại núi Si-na -i, sanh con ra để làm tôi mọi ấy là nàng A-ga."));
visuperobject.biblemap.put("b48_4_25", new visuperobject(48,4,25,"Vả, A-ga, ấy là núi Si-na -i, trong xứ A-ra-bi; khác nào như thành Giê-ru-sa-lem bây giờ, thành đó với con cái mình đều làm tôi mọi."));
visuperobject.biblemap.put("b48_4_26", new visuperobject(48,4,26,"Nhưng thành Giê-ru-sa-lem ở trên cao là tự do, và ấy là mẹ chúng ta."));
visuperobject.biblemap.put("b48_4_27", new visuperobject(48,4,27,"Vì có lời chép: Hỡi đờn bà son, ngươi là kẻ chẳng sanh nở chi hết, hãy vui mừng; Ngươi là kẻ chẳng từng chịu đau đớn sanh đẻ, hãy nức lòng mừng rỡ và bựt tiếng reo cười, Vì của cải của vợ bị để sẽ đông hơn con cái của người nữ có chồng."));
visuperobject.biblemap.put("b48_4_28", new visuperobject(48,4,28,"Hỡi anh em, về phần chúng ta, chúng ta cũng như Y-sác, là con của lời hứa."));
visuperobject.biblemap.put("b48_4_29", new visuperobject(48,4,29,"Nhưng, như bây giờ, kẻ sanh ra theo xác thịt bắt bớ kẻ sanh ra theo Thánh Linh, thì hiện nay cũng còn là thể ấy."));
visuperobject.biblemap.put("b48_4_30", new visuperobject(48,4,30,"Song Kinh Thánh, có nói gì? Hãy đuổi người nữ tôi mọi và con trai nó; vì con trai của người nữ tôi mọi sẽ không được kế tự với con trai của người nữ tự chủ."));
visuperobject.biblemap.put("b48_4_31", new visuperobject(48,4,31,"Ấy vậy, hỡi anh em, chúng ta chẳng phải là con cái của người nữ tôi mọi, bèn là người nữ tự chủ."));
visuperobject.biblemap.put("b48_5_1", new visuperobject(48,5,1,"Ðấng Christ đã buông tha chúng ta cho được tự do; vậy hãy đứng vững, chớ lại để mình dưới ách tôi mọi nữa."));
visuperobject.biblemap.put("b48_5_2", new visuperobject(48,5,2,"Tôi là Phao-lô nói với anh em rằng, nếu anh em chịu làm phép cắt bì, thì Ðấng Christ không bổ ích chi cho anh em hết."));
visuperobject.biblemap.put("b48_5_3", new visuperobject(48,5,3,"Tôi lại rao cho mọi người chịu cắt bì rằng, họ buộc phải vâng giữ trọn cả luật pháp."));
visuperobject.biblemap.put("b48_5_4", new visuperobject(48,5,4,"Anh em thảy đều muốn cậy luật pháp cho được xưng công bình, thì đã lìa khỏi Ðấng Christ, mất ân điển rồi."));
visuperobject.biblemap.put("b48_5_5", new visuperobject(48,5,5,"Về phần chúng ta, ấy là bởi đức tin và nhờ Thánh Linh mà chúng ta được nhận lãnh sự trông cậy của sự công bình."));
visuperobject.biblemap.put("b48_5_6", new visuperobject(48,5,6,"Vì trong Ðức Chúa Jêsus Christ, cái điều có giá trị, không phải tại chịu phép cắt bì hoặc không chịu phép cắt bì, nhưng tại đức tin hay làm ra bởi sự yêu thương vậy."));
visuperobject.biblemap.put("b48_5_7", new visuperobject(48,5,7,"Anh em chạy giỏi; ai đã ngăn trở anh em đặng không cho vâng phục lẽ thật?"));
visuperobject.biblemap.put("b48_5_8", new visuperobject(48,5,8,"Sự xui giục đó không phải đến từ Ðấng gọi anh em."));
visuperobject.biblemap.put("b48_5_9", new visuperobject(48,5,9,"Một ít men làm cho dậy cả đống bột."));
visuperobject.biblemap.put("b48_5_10", new visuperobject(48,5,10,"Trong Chúa, tôi đối với anh em có lòng tin cậy nầy, là anh em chắc không có ý khác; nhưng kẻ làm rối trí anh em, bất luận người nào, sẽ chịu hình phạt về điều đó."));
visuperobject.biblemap.put("b48_5_11", new visuperobject(48,5,11,"Hỡi anh em, về phần tôi, nếu tôi còn giảng phép cắt bì, thì sao tôi còn bị bắt bớ nữa? Sự vấp phạm về thập tự giá há chẳng phải bỏ hết rồi sao?"));
visuperobject.biblemap.put("b48_5_12", new visuperobject(48,5,12,"Nguyền cho kẻ gieo sự rối loạn trong anh em thà họ tự chặt mình là hơn!"));
visuperobject.biblemap.put("b48_5_13", new visuperobject(48,5,13,"Hỡi anh em, anh em đã được gọi đến sự tự do, song chớ lấy sự tự do đó làm dịp cho anh em ăn ở theo tánh xác thịt, nhưng hãy lấy lòng yêu thương làm đầy tớ lẫn nhau."));
visuperobject.biblemap.put("b48_5_14", new visuperobject(48,5,14,"Vì cả luật pháp chỉ tóm lại trong một lời nầy: Ngươi hãy yêu kẻ lân cận như mình."));
visuperobject.biblemap.put("b48_5_15", new visuperobject(48,5,15,"Nhưng nếu anh em cắn nuốt nhau, thì hãy giữ, kẻo kẻ nầy bị diệt mất bởi kẻ khác."));
visuperobject.biblemap.put("b48_5_16", new visuperobject(48,5,16,"Vậy tôi nói rằng: Hãy bước đi theo Thánh Linh, chớ hề làm trọn những điều ưa muốn của xác thịt."));
visuperobject.biblemap.put("b48_5_17", new visuperobject(48,5,17,"Vì xác thịt có những điều ưa muốn trái với của Thánh Linh, Thánh Linh có những điều ưa muốn trái với của xác thịt; hai bên trái nhau dường ấy, nên anh em không làm được điều mình muốn làm."));
visuperobject.biblemap.put("b48_5_18", new visuperobject(48,5,18,"Nhưng, ví bằng anh em nhờ Thánh Linh chỉ dẫn, thì chẳng hề ở dưới luật pháp."));
visuperobject.biblemap.put("b48_5_19", new visuperobject(48,5,19,"Vả, các việc làm của xác thịt là rõ ràng lắm: ấy là gian dâm, ô uế, luông tuồng,"));
visuperobject.biblemap.put("b48_5_20", new visuperobject(48,5,20,"thờ hình tượng, phù phép, thù oán, tranh đấu, ghen ghét, buồn giận, cãi lẫy, bất bình, bè đảng,"));
visuperobject.biblemap.put("b48_5_21", new visuperobject(48,5,21,"ganh gổ, say sưa, mê ăn uống, cùng các sự khác giống như vậy. Tôi nói trước cho anh em, như tôi đã nói rồi: hễ ai phạm những việc thể ấy thì không được hưởng nước Ðức Chúa Trời."));
visuperobject.biblemap.put("b48_5_22", new visuperobject(48,5,22,"Nhưng trái của Thánh Linh, ấy là lòng yêu thương, sự vui mừng, bình an, nhịn nhục, nhơn từ, hiền lành, trung tín, mềm mại, tiết độ:"));
visuperobject.biblemap.put("b48_5_23", new visuperobject(48,5,23,"không có luật pháp nào cấm các sự đó."));
visuperobject.biblemap.put("b48_5_24", new visuperobject(48,5,24,"Vả, những kẻ thuộc về Ðức Chúa Jêsus Christ đã đóng đinh xác thịt với tình dục và dâm dục mình trên thập tự giá rồi."));
visuperobject.biblemap.put("b48_5_25", new visuperobject(48,5,25,"Nếu chúng ta nhờ Thánh Linh mà sống, thì cũng hãy bước theo Thánh Linh vậy."));
visuperobject.biblemap.put("b48_5_26", new visuperobject(48,5,26,"Chớ tìm kiếm danh vọng giả dối mà trêu chọc nhau và ghen ghét nhau."));
visuperobject.biblemap.put("b48_6_1", new visuperobject(48,6,1,"Hỡi anh em, vì bằng có người nào tình cờ phạm lỗi gì, anh em là kẻ có Ðức Chúa Trời, hãy lấy lòng mềm mại mà sửa họ lại; chính mình anh em lại phải giữ, e cũng bị dỗ dành chẳng."));
visuperobject.biblemap.put("b48_6_2", new visuperobject(48,6,2,"Hãy mang lấy gánh nặng cho nhau, như vậy anh em sẽ làm trọn luật pháp của Ðấng Christ."));
visuperobject.biblemap.put("b48_6_3", new visuperobject(48,6,3,"Vì, nếu có ai, dầu mình không ra chi hết, mà cũng tưởng mình ra chi ấy là mình dối lấy mình."));
visuperobject.biblemap.put("b48_6_4", new visuperobject(48,6,4,"Mỗi người phải thử xét việc làm của mình, thì sự khoe mình chỉ tại mình thôi, chớ chẳng phải tại kẻ khác."));
visuperobject.biblemap.put("b48_6_5", new visuperobject(48,6,5,"Vì ai sẽ gánh lấy riêng phần nấy."));
visuperobject.biblemap.put("b48_6_6", new visuperobject(48,6,6,"Kẻ nào mà người ta dạy đạo cho, phải lấy trong hết thảy của cải mình mà chia cho người dạy đó."));
visuperobject.biblemap.put("b48_6_7", new visuperobject(48,6,7,"Chớ hề dối mình; Ðức Chúa Trời không chịu khinh dể đâu; vì ai gieo giống chi, lại gặt giống ấy."));
visuperobject.biblemap.put("b48_6_8", new visuperobject(48,6,8,"Kẻ gieo cho xác thịt, sẽ bởi xác thịt mà gặt sự hư nát; song kẻ gieo cho Thánh Linh, sẽ bởi Thánh Linh mà gặt sự sống đời đời."));
visuperobject.biblemap.put("b48_6_9", new visuperobject(48,6,9,"Chớ mệt nhọc về sự làm lành, vì nếu chúng ta không trễ nải, thì đến kỳ chúng ta sẽ gặt."));
visuperobject.biblemap.put("b48_6_10", new visuperobject(48,6,10,"Vậy, đương lúc có dịp tiện, hãy làm điều thiện cho mọi người, nhứt là cho anh em chúng ta trong đức tin."));
visuperobject.biblemap.put("b48_6_11", new visuperobject(48,6,11,"Hãy xem chính tay tôi viết thơ nầy cho anh em, chữ lớn là dường nào."));
visuperobject.biblemap.put("b48_6_12", new visuperobject(48,6,12,"Hết thảy những kẻ muốn cho mình đẹp lòng người theo phần xác, ép anh em chịu cắt bì, hầu cho họ khỏi vì thập tự giá của Ðấng Christ mà bị bắt bớ đó thôi."));
visuperobject.biblemap.put("b48_6_13", new visuperobject(48,6,13,"Vì chính những kẻ đó đã chịu cắt bì, không vâng giữ luật pháp đâu, nhưng họ muốn anh em chịu cắt bì, hầu để khoe mình trong phần xác của anh em."));
visuperobject.biblemap.put("b48_6_14", new visuperobject(48,6,14,"Còn như tôi, tôi hẳn chẳng khoe mình, trừ ra khoe về thập tự giá của Ðức Chúa Jêsus Christ chúng ta, bởi thập tự giá ấy, thế gian đối với tôi đã bị đóng đinh, và tôi đối với thế gian cũng vậy!"));
visuperobject.biblemap.put("b48_6_15", new visuperobject(48,6,15,"Vì điều yếu cần, chẳng phải sự chịu cắt bì, hay là sự chẳng chịu cắt bì, bèn là trở nên người mới."));
visuperobject.biblemap.put("b48_6_16", new visuperobject(48,6,16,"Nguyền xin sự bình an và sự thương xót giáng trên hết thảy những kẻ noi theo mẫu mực nầy, lại giáng trên dân Y-sơ-ra-ên của Ðức Chúa Trời nữa!"));
visuperobject.biblemap.put("b48_6_17", new visuperobject(48,6,17,"Ước gì từ nay về sau, chẳng ai làm khó cho tôi, vì trong mình tôi có đốt dấu vết của Ðức Chúa Jêsus vậy."));
visuperobject.biblemap.put("b48_6_18", new visuperobject(48,6,18,"Hỡi anh em, nguyền xin ân điển của Ðức Chúa Jêsus Christ chúng ta ở với tâm thần anh em! A-men."));

}

}