package vi.bible;

public class vibible46 {

public vibible46() {

putmapbible46();

}

private void putmapbible46() {

visuperobject.biblemap.put("b46_1_1", new visuperobject(46,1,1,"Phao-lô, theo ý Ðức Chúa Trời, được gọi làm sứ đồ của Ðức Chúa Jêsus Christ, cùng Sốt-then, anh em chúng tôi,"));
visuperobject.biblemap.put("b46_1_2", new visuperobject(46,1,2,"gởi cho Hội thánh Ðức Chúa Trời tại thành Cô-rinh-tô, tức là cho những người đã được nên thánh trong Ðức Chúa Jêsus Christ, được gọi làm thánh đồ, lại cho mọi người bất luận nơi nào, cầu khẩn danh Ðức Chúa Jêsus Christ chúng ta, là Chúa của những người ấy và của chúng ta:"));
visuperobject.biblemap.put("b46_1_3", new visuperobject(46,1,3,"nguyền xin anh em được ân điển và sự bình an ban cho bởi Ðức Chúa Trời, Cha chúng ta, và bởi Ðức Chúa Jêsus Christ!"));
visuperobject.biblemap.put("b46_1_4", new visuperobject(46,1,4,"Tôi hằng vì anh em tạ ơn Ðức Chúa Trời, bởi cớ anh em đã được Ðức Chúa Trời ban ơn trong Ðức Chúa Jêsus Christ;"));
visuperobject.biblemap.put("b46_1_5", new visuperobject(46,1,5,"vì chưng anh em đã được dư dật về mọi điều ban cho, cả lời nói và sự hiểu biết,"));
visuperobject.biblemap.put("b46_1_6", new visuperobject(46,1,6,"như lời chứng về Ðấng Christ đã được vững bền giữa anh em."));
visuperobject.biblemap.put("b46_1_7", new visuperobject(46,1,7,"Anh em đang trông đợi kỳ Ðức Chúa Jêsus Christ chúng ta hiện đến, cũng chẳng thiếu một ơn nào."));
visuperobject.biblemap.put("b46_1_8", new visuperobject(46,1,8,"Ngài sẽ khiến anh em được vững bền đến cuối cùng, để khỏi bị quở trách trong ngày của Ðức Chúa Jêsus Christ chúng ta."));
visuperobject.biblemap.put("b46_1_9", new visuperobject(46,1,9,"Ðức Chúa Trời là thành tín, Ngài đã gọi anh em được thông công với Con Ngài là Ðức Chúa Jêsus Christ, Chúa chúng ta."));
visuperobject.biblemap.put("b46_1_10", new visuperobject(46,1,10,"Hỡi Anh em, tôi nhơn danh Ðức Chúa Jêsus Christ chúng ta, khuyên anh em thảy đều phải đồng một tiếng nói với nhau, chớ phân rẽ nhau ra, nhưng phải hiệp một ý một lòng cùng nhau."));
visuperobject.biblemap.put("b46_1_11", new visuperobject(46,1,11,"Vì, hỡi anh em, bởi người nhà Cơ-lô-ê, tôi có được tin rằng trong anh em có sự tranh cạnh."));
visuperobject.biblemap.put("b46_1_12", new visuperobject(46,1,12,"Tôi có ý nói rằng trong anh em mỗi người nói như vầy: Ta là môn đồ của Phao-lô; ta là của A-bô-lô, ta là của Sê-pha, ta là của Ðấng Christ."));
visuperobject.biblemap.put("b46_1_13", new visuperobject(46,1,13,"Ðấng Christ bị phân rẽ ra sao? Có phải Phao-lô đã chịu đóng đinh trên cây thập tự thế cho anh em, hay là anh em đã nhơn danh Phao-lô mà chịu phép báp tem sao?"));
visuperobject.biblemap.put("b46_1_14", new visuperobject(46,1,14,"Tôi tạ ơn Ðức Chúa Trời, vì ngoài Cơ-rít-bu và Gai-út, tôi chưa từng làm phép báp tem cho ai trong anh em,"));
visuperobject.biblemap.put("b46_1_15", new visuperobject(46,1,15,"hầu cho chẳng ai nói rằng anh em đã nhơn danh tôi mà chịu phép báp tem."));
visuperobject.biblemap.put("b46_1_16", new visuperobject(46,1,16,"Tôi cũng đã làm phép báp tem cho người nhà Sê-pha-na; ngoài nhà đó, tôi chẳng biết mình đã làm phép báp tem cho ai nữa."));
visuperobject.biblemap.put("b46_1_17", new visuperobject(46,1,17,"Thật vậy, Ðấng Christ đã sai tôi, chẳng phải để làm phép báp-tem đâu, nhưng để rao giảng Tin Lành, và chẳng dùng sự khôn khéo mà giảng, kẻo thập tự giá của Ðấng Christ ra vô ích."));
visuperobject.biblemap.put("b46_1_18", new visuperobject(46,1,18,"Bởi vì lời giảng về thập tự giá, thì những người hư mất cho là điên dại; song về phần chúng ta, là kẻ được cứu chuộc, thì cho là quyền phép của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_1_19", new visuperobject(46,1,19,"cũng có lời chép rằng: Ta sẽ hủy phá sự khôn ngoan của người khôn ngoan, Tiêu trừ sự thạo biết của người thạo biết."));
visuperobject.biblemap.put("b46_1_20", new visuperobject(46,1,20,"Người khôn ngoan ở đâu? Thầy thông giáo ở đâu? Người biện luận đời nay ở đâu? Có phải Ðức Chúa Trời đã làm cho sự khôn ngoan của thế gian ra dồ dại không?"));
visuperobject.biblemap.put("b46_1_21", new visuperobject(46,1,21,"Vì, tại thế gian cậy sự khôn ngoan mình, chẳng nhờ sự khôn ngoan Ðức Chúa Trời mà nhận biết Ðức Chúa Trời, nên Ngài đành lòng dùng sự giảng dồ dại của chúng ta mà cứu rỗi những người tin cậy."));
visuperobject.biblemap.put("b46_1_22", new visuperobject(46,1,22,"Vả, đương khi người Giu-đa đòi phép lạ, người Gờ-réc tìm sự khôn ngoan,"));
visuperobject.biblemap.put("b46_1_23", new visuperobject(46,1,23,"thì chúng ta giảng Ðấng Christ bị đóng đinh trên cây thập tự, là sự người Giu-đa lấy làm gương xấu, dân ngoại cho là dồ dại;"));
visuperobject.biblemap.put("b46_1_24", new visuperobject(46,1,24,"song le, về những người được gọi, bất luận người Giu-đa hay người Gờ-réc, thì Ðấng Christ là quyền phép của Ðức Chúa Trời và sự khôn ngoan của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_1_25", new visuperobject(46,1,25,"Bởi vì sự dồ dại của Ðức Chúa Trời là khôn sáng hơn người ta, và sự yếu đuối của Ðức Chúa Trời là mạnh hơn người ta."));
visuperobject.biblemap.put("b46_1_26", new visuperobject(46,1,26,"Hỡi Anh em, hãy suy xét rằng ở giữa anh em là kẻ đã được gọi, không có nhiều người khôn ngoan theo xác thịt, chẳng nhiều kẻ quyền thế, chẳng nhiều kẻ sang trọng."));
visuperobject.biblemap.put("b46_1_27", new visuperobject(46,1,27,"Nhưng Ðức Chúa Trời đã chọn những sự dại ở thế gian để làm hổ thẹn những sự mạnh;"));
visuperobject.biblemap.put("b46_1_28", new visuperobject(46,1,28,"Ðức Chúa Trời đã chọn những sự hèn hạ và khinh bỉ ở thế gian, cùng những sự không có, hầu cho làm những sự có ra không có,"));
visuperobject.biblemap.put("b46_1_29", new visuperobject(46,1,29,"để chẳng ai khoe mình trước một Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_1_30", new visuperobject(46,1,30,"Vả, ấy là nhờ Ngài mà anh em ở trong Ðức Chúa Jêsus Christ, là Ðấng mà Ðức Chúa Trời đã làm nên sự khôn ngoan, sự công bình, sự nên thánh, và sự cứu chuộc cho chúng ta;"));
visuperobject.biblemap.put("b46_1_31", new visuperobject(46,1,31,"hầu cho, như có lời chép rằng: Ai khoe mình, hãy khoe mình trong Chúa."));
visuperobject.biblemap.put("b46_2_1", new visuperobject(46,2,1,"Hỡi Anh em, về phần tôi, khi tôi đến cùng anh em, chẳng dùng lời cao xa hay là khôn sáng mà rao giảng cho anh em biết chứng cớ của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_2_2", new visuperobject(46,2,2,"Vì tôi đã đoán định rằng ở giữa anh em, tôi chẳng biết sự gì khác ngoài Ðức Chúa Jêsus Christ, và Ðức Chúa Jêsus Christ bị đóng đinh trên cây thập tự."));
visuperobject.biblemap.put("b46_2_3", new visuperobject(46,2,3,"Chính tôi đã ở giữa anh em, bộ yếu đuối, sợ hãi, run rẩy lắm."));
visuperobject.biblemap.put("b46_2_4", new visuperobject(46,2,4,"Lời nói và sự giảng của tôi chẳng phải bằng bài diễn thuyết khéo léo của sự khôn ngoan, nhưng tại sự tỏ ra Thánh Linh và quyền phép;"));
visuperobject.biblemap.put("b46_2_5", new visuperobject(46,2,5,"hầu cho anh em chớ lập đức tin mình trên sự khôn ngoan loài người, bèn là trên quyền phép Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_2_6", new visuperobject(46,2,6,"Dầu vậy, chúng tôi giảng sự khôn ngoan cho những kẻ trọn vẹn, song chẳng phải sự khôn ngoan thuộc về đời nầy, cũng không phải của các người cai quản đời nầy, là kẻ sẽ bị hư mất."));
visuperobject.biblemap.put("b46_2_7", new visuperobject(46,2,7,"Chúng tôi giảng sự khôn ngoan của Ðức Chúa Trời, là sự mầu nhiệm kín giấu, mà từ trước các đời, Ðức Chúa Trời đã định sẵn cho sự vinh hiển chúng ta."));
visuperobject.biblemap.put("b46_2_8", new visuperobject(46,2,8,"Trong những người cai quản đời nầy chẳng ai từng biết sự đó; bởi chưng, nếu đã biết thì họ chẳng đóng đinh Chúa vinh hiển trên cây thập tự đâu."));
visuperobject.biblemap.put("b46_2_9", new visuperobject(46,2,9,"Song le, như có chép rằng: Ấy là sự mắt chưa thấy, tai chưa nghe, Và lòng người chưa nghĩ đến, Nhưng Ðức Chúa Trời đã sắm sẵn điều ấy cho những người yêu mến Ngài."));
visuperobject.biblemap.put("b46_2_10", new visuperobject(46,2,10,"Ðức Chúa Trời đã dùng Ðức Thánh Linh để bày tỏ những sự đó cho chúng ta, vì Ðức Thánh Linh dò xét mọi sự, cả đến sự sâu nhiệm của Ðức Chúa Trời nữa."));
visuperobject.biblemap.put("b46_2_11", new visuperobject(46,2,11,"Vả, nếu không phải là thần linh trong lòng người, thì ai biết sự trong lòng người? Cũng một lẽ ấy, nếu không phải là Thánh Linh của Ðức Chúa Trời, thì chẳng ai biết sự trong Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_2_12", new visuperobject(46,2,12,"Về phần chúng ta, chúng ta chẳng nhận lấy thần thế gian, nhưng đã nhận lấy Thánh Linh từ Ðức Chúa Trời đến, hầu cho được hiểu biết những ơn mà chúng ta nhận lãnh bởi Ðức Chúa Trời;"));
visuperobject.biblemap.put("b46_2_13", new visuperobject(46,2,13,"chúng ta nói về ơn đó, không cậy lời nói mà sự khôn ngoan của loài người đã dạy đâu, song cậy sự khôn ngoan mà Ðức Thánh Linh đã dạy, dùng tiếng thiêng liêng để giải bày sự thiêng liêng."));
visuperobject.biblemap.put("b46_2_14", new visuperobject(46,2,14,"Vả, người có tánh xác thịt không nhận được những sự thuộc về Thánh Linh của Ðức Chúa Trời; bởi chưng người đó coi sự ấy như là sự dồ dại, và không có thể hiểu được, vì phải xem xét cách thiêng liêng."));
visuperobject.biblemap.put("b46_2_15", new visuperobject(46,2,15,"Nhưng người có tánh thiêng liêng xử đoán mọi sự, và chính mình không bị ai xử đoán."));
visuperobject.biblemap.put("b46_2_16", new visuperobject(46,2,16,"Vì ai đã biết ý Chúa, đặng dạy dỗ Ngài? Nhưng phần chúng ta, thì có ý của Ðấng Christ."));
visuperobject.biblemap.put("b46_3_1", new visuperobject(46,3,1,"Hỡi anh em, về phần tôi, tôi chẳng có thể nói với anh em như với người thiêng liêng, nhưng như với người xác thịt, như với các con đỏ trong Ðấng Christ vậy."));
visuperobject.biblemap.put("b46_3_2", new visuperobject(46,3,2,"Tôi lấy sữa nuôi anh em, chớ chẳng lấy đồ ăn cứng, vì anh em không chịu nổi; đến bây giờ cũng chưa chịu được, vì anh em hãy còn thuộc về xác thịt."));
visuperobject.biblemap.put("b46_3_3", new visuperobject(46,3,3,"Thật, bởi trong anh em có sự ghen ghét và tranh cạnh, anh em há chẳng phải là tánh xác thịt ăn ở như người thế gian sao?"));
visuperobject.biblemap.put("b46_3_4", new visuperobject(46,3,4,"Có người thì nói: Ta là môn đồ của Phao-lô; kẻ thì rằng: Ta là của A-bô-lô, vậy anh em há chẳng phải là người cũng như kẻ khác sao?"));
visuperobject.biblemap.put("b46_3_5", new visuperobject(46,3,5,"Thế thì, A-bô-lô là ai, và Phao-lô là ai? Ấy là kẻ tôi tớ, mà bởi kẻ đó anh em đã tin cậy, y theo Chúa đã ban cho mọi người."));
visuperobject.biblemap.put("b46_3_6", new visuperobject(46,3,6,"Tôi đã trồng, A-bô-lô đã tưới, nhưng Ðức Chúa Trời đã làm cho lớn lên."));
visuperobject.biblemap.put("b46_3_7", new visuperobject(46,3,7,"Vậy, người trồng kẻ tưới, đều không ra gì, song Ðức Chúa Trời là Ðấng làm cho lớn lên."));
visuperobject.biblemap.put("b46_3_8", new visuperobject(46,3,8,"Người trồng, kẻ tưới, đều bằng nhau; ai nấy sẽ nhận phần thưởng tùy theo việc mình đã làm."));
visuperobject.biblemap.put("b46_3_9", new visuperobject(46,3,9,"Vả, chúng tôi là bạn cùng làm việc với Ðức Chúa Trời; anh em là ruộng Ðức Chúa Trời cày, nhà của Ðức Chúa Trời xây."));
visuperobject.biblemap.put("b46_3_10", new visuperobject(46,3,10,"Theo ơn Ðức Chúa Trời ban cho tôi, tôi đã lập nên như một tay thợ khéo, mà có kẻ khác cất lên trên; nhưng ai nấy phải cẩn thận về sự mình xây trên nền đó."));
visuperobject.biblemap.put("b46_3_11", new visuperobject(46,3,11,"Vì, chẳng ai có thể lập một nền khác ngoài nền đã lập, là Ðức Chúa Jêsus Christ."));
visuperobject.biblemap.put("b46_3_12", new visuperobject(46,3,12,"Nếu có kẻ lấy vàng, bạc, bửu thạch, gỗ, cỏ khô, rơm rạ mà xây trên nền ấy,"));
visuperobject.biblemap.put("b46_3_13", new visuperobject(46,3,13,"thì công việc của mỗi người sẽ bày tỏ ra. Ngày đến sẽ tỏ tường công việc đó; nó sẽ trình ra trong lửa, và công việc của mỗi người đáng giá nào, lửa sẽ chỉ ra."));
visuperobject.biblemap.put("b46_3_14", new visuperobject(46,3,14,"Ví bằng công việc của ai xây trên nền được còn lại, thì thợ đó sẽ lãnh phần thưởng mình."));
visuperobject.biblemap.put("b46_3_15", new visuperobject(46,3,15,"Nếu công việc họ bị thiêu hủy, thì mất phần thưởng. Còn về phần người đó, sẽ được cứu, song dường như qua lửa vậy."));
visuperobject.biblemap.put("b46_3_16", new visuperobject(46,3,16,"Anh em há chẳng biết mình là đền thờ của Ðức Chúa Trời, và Thánh Linh Ðức Chúa Trời ở trong anh em sao?"));
visuperobject.biblemap.put("b46_3_17", new visuperobject(46,3,17,"Vì có ai phá hủy đền thờ của Ðức Chúa Trời, thì Ðức Chúa Trời sẽ phá hủy họ; vì đền thờ của Ðức Chúa Trời là thánh, mà chính anh em là đền thờ."));
visuperobject.biblemap.put("b46_3_18", new visuperobject(46,3,18,"Chớ ai tự dối mình: nếu có ai trong vòng anh em tưởng mình khôn ngoan theo cách đời nầy, hãy trở nên dại dột, để được nên khôn ngoan;"));
visuperobject.biblemap.put("b46_3_19", new visuperobject(46,3,19,"vì sự khôn ngoan đời nầy trước mặt Ðức Chúa Trời là sự dại dột. Như có chép rằng: Ấy là Chúa bắt những kẻ khôn ngoan trong mưu kế họ."));
visuperobject.biblemap.put("b46_3_20", new visuperobject(46,3,20,"Lại rằng: Chúa thông biết ý tưởng của người khôn ngoan; Ngài biết ý tưởng họ đều là vô ích."));
visuperobject.biblemap.put("b46_3_21", new visuperobject(46,3,21,"Vậy, chớ ai khoe mình về loài người, vì mọi sự đều thuộc về anh em:"));
visuperobject.biblemap.put("b46_3_22", new visuperobject(46,3,22,"hoặc Phao-lô, hoặc A-bô-lô, hoặc Sê-pha, hoặc thế gian, không có sự sống, hoặc sự chết hoặc những sự bây giờ, hoặc những sự hầu đến. Hết thảy mọi sự đều thuộc về anh em,"));
visuperobject.biblemap.put("b46_3_23", new visuperobject(46,3,23,"anh em thuộc về Ðấng Christ, Ðấng Christ thuộc về Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_4_1", new visuperobject(46,4,1,"Vậy, ai nấy hãy coi chúng tôi như đầy tớ của Ðấng Christ, và kẻ quản trị những sự mầu nhiệm của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_4_2", new visuperobject(46,4,2,"Vả lại, cái điều người ta trông mong nơi người quản trị là phải trung thành."));
visuperobject.biblemap.put("b46_4_3", new visuperobject(46,4,3,"Về phần tôi, hoặc bị anh em xử đoán, hoặc bị tòa án nào của loài người xử đoán, tôi cũng chẳng lấy làm quan hệ gì. Chính tôi chẳng tự xử đoán mình nữa;"));
visuperobject.biblemap.put("b46_4_4", new visuperobject(46,4,4,"vì tôi chẳng thấy mình có điều gì đáng tội, nhưng tôi cũng không nhờ sự đó mà được xưng là công bình: Ðấng xử đoán tôi, ấy là Chúa."));
visuperobject.biblemap.put("b46_4_5", new visuperobject(46,4,5,"Vậy, chớ xét đoán sớm quá, hãy đợi Chúa đến; chính Chúa sẽ tỏ những sự giấu trong nơi tối ra nơi sáng, và bày ra những sự toan định trong lòng người; bấy giờ, ai nấy sẽ bởi Ðức Chúa Trời mà lãnh sự khen ngợi mình đáng lãnh."));
visuperobject.biblemap.put("b46_4_6", new visuperobject(46,4,6,"Hỡi anh em, ấy là vì cớ anh em, tôi đã dùng những lẽ thật, nầy chỉ về chính mình tôi và A-bô-lô, hầu cho anh em học đòi hai chúng tôi, chớ vượt qua lời đã chép, và chớ sanh lòng kiêu ngạo, theo phe người nầy nghịch cùng kẻ khác."));
visuperobject.biblemap.put("b46_4_7", new visuperobject(46,4,7,"Bởi vì, ai phân biệt ngươi với người khác? Ngươi há có điều chi mà chẳng đã nhận lãnh sao? Nếu ngươi đã nhận lãnh, thì sao còn khoe mình như chẳng từng nhận lãnh?"));
visuperobject.biblemap.put("b46_4_8", new visuperobject(46,4,8,"Anh em được no đủ, được giàu có rồi, chẳng nhờ chúng tôi, anh em đã khởi sự cai trị; thật mong cho anh em được cai trị, hầu cho chúng tôi cũng cai trị với anh em!"));
visuperobject.biblemap.put("b46_4_9", new visuperobject(46,4,9,"Vì chưng Ðức Chúa Trời dường đã phơi chúng tôi là các sứ đồ ra, giống như tù phải tội chết, làm trò cho thế gian, thiên sứ, loài người cùng xem vậy."));
visuperobject.biblemap.put("b46_4_10", new visuperobject(46,4,10,"Chúng tôi là kẻ ngu dại vì cớ Ðấng Christ, nhưng anh em được khôn ngoan trong Ðấng Christ; chúng tôi yếu đuối, anh em mạnh mẽ; anh em quí trọng, chúng tôi khinh hèn."));
visuperobject.biblemap.put("b46_4_11", new visuperobject(46,4,11,"Cho đến bây giờ, chúng tôi vẫn chịu đói khát, trần mình, bị người ta vả trên mặt, lưu lạc rày đây mai đó."));
visuperobject.biblemap.put("b46_4_12", new visuperobject(46,4,12,"Chúng tôi dùng chính tay mình làm việc khó nhọc; khi bị rủa sả, chúng tôi chúc phước; khi bị bắt bớ, chúng tôi nhịn nhục;"));
visuperobject.biblemap.put("b46_4_13", new visuperobject(46,4,13,"khi bị vu oan, chúng tôi khuyên dỗ; chúng tôi giống như rác rến của thế gian, cặn bả của loài người, cho đến ngày nay."));
visuperobject.biblemap.put("b46_4_14", new visuperobject(46,4,14,"Tôi viết những điều nầy, chẳng phải để làm cho anh em hổ ngươi đâu; nhưng để khuyên bảo anh em, cũng như con cái yêu dấu của tôi vậy."));
visuperobject.biblemap.put("b46_4_15", new visuperobject(46,4,15,"Bởi chưng, dẫu anh em có một vạn thầy giáo trong Ðấng Christ, nhưng chẳng có nhiều cha; vì tôi đã dùng Tin Lành mà sanh anh em ra trong Ðức Chúa Jêsus Christ."));
visuperobject.biblemap.put("b46_4_16", new visuperobject(46,4,16,"Vậy, tôi lấy điều đó khuyên anh em: hãy bắt chước tôi."));
visuperobject.biblemap.put("b46_4_17", new visuperobject(46,4,17,"Vì cớ đó, tôi đã sai Ti-mô-thê, là con yêu dấu của tôi, cùng là trung thành trong Chúa, đến cùng anh em; người sẽ nhắc lại cho anh em biết đường lối tôi trong Ðấng Christ, và tôi dạy dỗ cách nào trong các Hội thánh khắp các nơi."));
visuperobject.biblemap.put("b46_4_18", new visuperobject(46,4,18,"Có mấy kẻ lên mình kiêu ngạo, ngờ tôi chẳng còn đến cùng anh em nữa."));
visuperobject.biblemap.put("b46_4_19", new visuperobject(46,4,19,"Nhưng nếu Chúa khứng cho, thì chẳng bao lâu tôi sẽ tới cùng anh em, và xét cho biết, chẳng phải xét lời nói của những kẻ kiêu ngạo đó, bèn là năng lực họ thể nào."));
visuperobject.biblemap.put("b46_4_20", new visuperobject(46,4,20,"Vì nước Ðức Chúa Trời chẳng ở tại lời nói, mà ở tại năng lực."));
visuperobject.biblemap.put("b46_4_21", new visuperobject(46,4,21,"Anh em muốn điều gì hơn: muốn tôi cầm roi mà đến cùng anh em, hay là lấy tình yêu thương và ý nhu mì?"));
visuperobject.biblemap.put("b46_5_1", new visuperobject(46,5,1,"Có tin đồn ra khắp nơi rằng trong anh em có sự dâm loạn, dâm loạn đến thế, dẫu người ngoại đạo cũng chẳng có giống như vậy: là đến nỗi trong anh em có kẻ lấy vợ của cha mình."));
visuperobject.biblemap.put("b46_5_2", new visuperobject(46,5,2,"Anh em còn lên mình kiêu ngạo! Anh em chẳng từng buồn rầu, hầu cho kẻ phạm tội đó bị trừ bỏ khỏi vòng anh em thì hơn!"));
visuperobject.biblemap.put("b46_5_3", new visuperobject(46,5,3,"Về phần tôi, thân dầu xa cách mà lòng ở tại đó, (vì anh em và lòng tôi được hội hiệp với quyền phép của Ðức Chúa Jêsus, là Chúa chúng ta),"));
visuperobject.biblemap.put("b46_5_4", new visuperobject(46,5,4,"nên tôi đã dường như có mặt ở đó, nhơn danh Ðức Chúa Jêsus là Chúa chúng ta, tuyên án kẻ phạm tội đó"));
visuperobject.biblemap.put("b46_5_5", new visuperobject(46,5,5,"rằng, một người như thế phải phó cho quỉ Sa tan, để hủy hoại phần xác thịt, hầu cho linh hồn được cứu trong ngày Ðức Chúa Jêsus."));
visuperobject.biblemap.put("b46_5_6", new visuperobject(46,5,6,"Thật anh em chẳng có cớ mà khoe mình đâu! Anh em há chẳng biết rằng một chút men làm cho cả đống bột dậy lên sao?"));
visuperobject.biblemap.put("b46_5_7", new visuperobject(46,5,7,"Hãy làm cho mình sạch men cũ đi, hầu cho anh em trở nên bột nhồi mới không men, như anh em là bánh không men vậy. Vì Ðấng Christ là con sinh lễ Vượt Qua của chúng ta, đã bị giết rồi."));
visuperobject.biblemap.put("b46_5_8", new visuperobject(46,5,8,"Vậy thì, chúng ta hãy giữ lễ, chớ dùng men cũ, chớ dùng men gian ác, độc dữ, nhưng dùng bánh không men của sự thật thà và của lẽ thật."));
visuperobject.biblemap.put("b46_5_9", new visuperobject(46,5,9,"Trong thơ tôi viết cho anh em, có dặn đừng làm bạn với kẻ gian dâm,"));
visuperobject.biblemap.put("b46_5_10", new visuperobject(46,5,10,"đó tôi chẳng có ý nói chung về kẻ gian dâm đời nầy, hay là kẻ tham lam, kẻ chắt bóp, kẻ thờ hình tượng, vì nếu vậy thì anh em phải lìa khỏi thế gian."));
visuperobject.biblemap.put("b46_5_11", new visuperobject(46,5,11,"Nhưng tôi viết khuyên anh em đừng làm bạn với kẻ nào tự xưng là anh em, mà là gian dâm, hoặc tham lam, hoặc thờ hình tượng, hoặc chưởi rủa, hoặc say sưa, hoặc chắt bóp, cũng không nên ăn chung với người thể ấy."));
visuperobject.biblemap.put("b46_5_12", new visuperobject(46,5,12,"Vì chưng có phải tôi nên đoán xét kẻ ở ngoài sao? Há chẳng phải anh em nên đoán xét những người ở trong sao?"));
visuperobject.biblemap.put("b46_5_13", new visuperobject(46,5,13,"Còn như kẻ ở ngoài, thì Ðức Chúa Trời sẽ đoán xét họ. Hãy trừ bỏ kẻ gian ác khỏi anh em."));
visuperobject.biblemap.put("b46_6_1", new visuperobject(46,6,1,"Khi trong anh em ai có sự nghịch cùng người khác, sao dám để cho kẻ không công bình đoán xét hơn là cho các thánh đồ?"));
visuperobject.biblemap.put("b46_6_2", new visuperobject(46,6,2,"Anh em há chẳng biết các thánh đồ sẽ xét đoán thế gian sao? Ví bằng thế gian sẽ bị anh em xét đoán, thì anh em há chẳng đáng xét đoán việc nhỏ mọn hơn sao?"));
visuperobject.biblemap.put("b46_6_3", new visuperobject(46,6,3,"Anh em chẳng biết chúng ta sẽ xét đoán các thiên sứ sao? Huống chi việc đời nầy!"));
visuperobject.biblemap.put("b46_6_4", new visuperobject(46,6,4,"Vậy khi anh em có sự nghịch cùng nhau về việc đời nầy, sao lấy những kẻ không kể ra chi trong Hội thánh làm người xét đoán!"));
visuperobject.biblemap.put("b46_6_5", new visuperobject(46,6,5,"Tôi nói thế làm cho anh em hổ thẹn. Ấy vậy, trong vòng anh em chẳng có một kẻ khôn ngoan nào phân xử được giữa anh em mình hay sao?"));
visuperobject.biblemap.put("b46_6_6", new visuperobject(46,6,6,"Nhưng anh em kiện anh em, lại đem đến trước mặt kẻ chẳng tin!"));
visuperobject.biblemap.put("b46_6_7", new visuperobject(46,6,7,"Thật vậy, anh em có sự kiện cáo nhau, là phải tội rồi. Sao chẳng chịu sự trái lẽ là hơn? Sao chẳng đành sự gian lận là hơn!"));
visuperobject.biblemap.put("b46_6_8", new visuperobject(46,6,8,"Nhưng chính anh em làm ra sự trái lẽ, chính anh em gian lận, lại làm thể ấy cho người anh em nữa!"));
visuperobject.biblemap.put("b46_6_9", new visuperobject(46,6,9,"Anh em há chẳng biết những kẻ không công bình chẳng bao giờ hưởng được nước Ðức Chúa Trời sao?"));
visuperobject.biblemap.put("b46_6_10", new visuperobject(46,6,10,"Chớ tự dối mình: phàm những kẻ tà dâm, kẻ thờ hình tượng, kẻ ngoại tình, kẻ làm giáng yểu điệu, kẻ đắm nam sắc, kẻ trộm cướp, kẻ hà tiện, kẻ say sưa, kẻ chưởi rủa, kẻ chắt bóp, đều chẳng hưởng được nước Ðức Chúa Trời đâu."));
visuperobject.biblemap.put("b46_6_11", new visuperobject(46,6,11,"Trước kia anh em ít nữa cũng có một đôi người như thế; nhưng nhơn danh Ðức Chúa Jêsus Christ, và nhờ Thánh Linh của Ðức Chúa Trời chúng ta, thì anh em được rửa sạch, được nên thánh, được xưng công bình rồi."));
visuperobject.biblemap.put("b46_6_12", new visuperobject(46,6,12,"Mọi sự tôi có phép làm, nhưng chẳng phải mọi sự đều có ích; mọi sự tôi có phép làm, nhưng chẳng để sự gì bắt phục được tôi."));
visuperobject.biblemap.put("b46_6_13", new visuperobject(46,6,13,"Ðồ ăn vì bụng, bụng vì đồ ăn, Ðức Chúa Trời sẽ hủy hoại cái nọ và cái kia. Nhưng thân thể chẳng phải vì sự dâm dục đâu, bèn là vì Chúa, và Chúa vì thân thể;"));
visuperobject.biblemap.put("b46_6_14", new visuperobject(46,6,14,"và Ðức Chúa Trời là Ðấng đã khiến Chúa sống lại, cũng sẽ lấy quyền phép mình khiến chúng ta sống lại nữa."));
visuperobject.biblemap.put("b46_6_15", new visuperobject(46,6,15,"Anh em há chẳng biết thân thể mình là chi thể của Ðấng Christ sao? Vậy thì mình có nên lấy chi thể của Ðấng Christ mà làm thành chi thể của điếm đĩ chăng? Ðức Chúa Trời nào nỡ vậy!"));
visuperobject.biblemap.put("b46_6_16", new visuperobject(46,6,16,"Anh em há chẳng biết người nào kết hiệp với điếm đĩ, thì trở nên một xác với nó sao? Vì có chép rằng: Hai người sẽ đồng nên một thịt."));
visuperobject.biblemap.put("b46_6_17", new visuperobject(46,6,17,"Còn ai kết hiệp với Chúa thì trở nên một tánh thiêng liêng cùng Ngài."));
visuperobject.biblemap.put("b46_6_18", new visuperobject(46,6,18,"Hãy tránh sự dâm dục. Mặc dầu người ta phạm tội gì, tội ấy còn là ngoài thân thể; nhưng kẻ buông mình vào sự dâm dục, thì phạm đến chính thân thể mình."));
visuperobject.biblemap.put("b46_6_19", new visuperobject(46,6,19,"Anh em há chẳng biết rằng thân thể mình là đền thờ của Ðức Thánh Linh đang ngự trong anh em, là Ðấng mà anh em đã nhận bởi Ðức Chúa Trời, và anh em chẳng phải thuộc về chính mình sao?"));
visuperobject.biblemap.put("b46_6_20", new visuperobject(46,6,20,"Vì chưng anh em đã được chuộc bằng giá cao rồi. Vậy, hãy lấy thân thể mình làm sáng danh Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_7_1", new visuperobject(46,7,1,"Luận đến các điều hỏi trong thơ anh em, tôi tưởng rằng đờn ông không đụng đến đờn bà là hay hơn."));
visuperobject.biblemap.put("b46_7_2", new visuperobject(46,7,2,"Song, cho được tránh khỏi mọi sự dâm dục, thì mỗi người đờn ông phải có vợ, mỗi người đờn bà phải có chồng."));
visuperobject.biblemap.put("b46_7_3", new visuperobject(46,7,3,"Chồng phải làm hết bổn phận đối với vợ, và đối với chồng cũng vậy."));
visuperobject.biblemap.put("b46_7_4", new visuperobject(46,7,4,"Vợ không có quyền tự chủ về thân mình, bèn là chồng; chồng cũng vậy, không có quyền tự chủ về thân mình bèn là vợ."));
visuperobject.biblemap.put("b46_7_5", new visuperobject(46,7,5,"Ðừng từ chối nhau, trừ ra khi hai bên ưng thuận tạm thời, để chuyên việc cầu nguyện; rồi trở lại hiệp cùng nhau, kẻo quỉ Sa-tan thừa khi anh em không thìn mình mà cám dỗ chăng."));
visuperobject.biblemap.put("b46_7_6", new visuperobject(46,7,6,"Ấy đó là sự tôi thuận cho phép, chớ chẳng phải sự tôi truyền biểu."));
visuperobject.biblemap.put("b46_7_7", new visuperobject(46,7,7,"Tôi muốn mọi người đều được giống như tôi; song mỗi người đã được ban riêng cho mình bởi Ðức Chúa Trời, người nầy thể nầy, kẻ kia thể khác."));
visuperobject.biblemap.put("b46_7_8", new visuperobject(46,7,8,"Vậy, tôi nói với những kẻ chưa cưới gả, và kẻ góa bụa rằng ở được như tôi thì hơn."));
visuperobject.biblemap.put("b46_7_9", new visuperobject(46,7,9,"Song nếu họ chẳng thìn mình được, thì hãy cưới gả; vì thà cưới gả còn hơn để cho lửa tình un đốt."));
visuperobject.biblemap.put("b46_7_10", new visuperobject(46,7,10,"Về những kẻ đã cưới gả rồi, thì tôi, nhưng chẳng phải tôi, bèn là Chúa, truyền rằng vợ không nên lìa bỏ chồng,"));
visuperobject.biblemap.put("b46_7_11", new visuperobject(46,7,11,"(ví bằng đã phân rẽ nhau, thì nên ở vậy đừng lấy chồng khác; hay là phải lại hòa thuận với chồng mình), còn chồng cũng không nên để vợ."));
visuperobject.biblemap.put("b46_7_12", new visuperobject(46,7,12,"Ðến như những kẻ khác, chẳng phải Chúa, song là chính tôi bảo họ rằng: Nếu người anh em nào có vợ ngoại đạo bằng lòng ở đời với mình, thì không nên để bỏ."));
visuperobject.biblemap.put("b46_7_13", new visuperobject(46,7,13,"Lại nếu một người đờn bà có chồng ngoại đạo bằng lòng ở đời với mình, thì vợ cũng không nên lìa chồng."));
visuperobject.biblemap.put("b46_7_14", new visuperobject(46,7,14,"Bởi vì, chồng không tin Chúa, nhơn vợ mình được nên thánh, vợ không tin Chúa, nhơn chồng mình tin Chúa được nên thánh; bằng chẳng vậy, con cái anh em nên chẳng sạch, song nay đều là thánh."));
visuperobject.biblemap.put("b46_7_15", new visuperobject(46,7,15,"Nếu kẻ không tin Chúa muốn phân rẽ, thì cho phân rẽ: trong cơn đó, người anh em hay là người chị em chẳng phải cầm buộc gì. Ðức Chúa Trời đã gọi anh em ăn ở trong sự bình an."));
visuperobject.biblemap.put("b46_7_16", new visuperobject(46,7,16,"Hỡi kẻ làm vợ kia, biết đâu ngươi sẽ cứu được chồng mình? Hỡi kẻ làm chồng kia, biết đâu ngươi sẽ cứu được vợ mình?"));
visuperobject.biblemap.put("b46_7_17", new visuperobject(46,7,17,"Rốt lại, ai nấy phải ăn ở theo ơn Chúa đã ban cho mình, và theo như Ðức Chúa Trời đã gọi. Ấy đó là điều tôi dạy trong hết thảy các Hội thánh."));
visuperobject.biblemap.put("b46_7_18", new visuperobject(46,7,18,"Có người nào đã chịu phép cắt bì rồi được gọi chăng? nên cứ giữ cắt bì vậy. Có người nào chưa chịu phép cắt bì mà được gọi chăng? thì chớ chịu phép cắt bì."));
visuperobject.biblemap.put("b46_7_19", new visuperobject(46,7,19,"Chịu cắt bì chẳng hề gì, không chịu cắt bì cũng chẳng hề gì; sự quan hệ là giữ các điều răn của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_7_20", new visuperobject(46,7,20,"Ai nầy khi được gọi ở đấng bậc nào, thì phải cứ theo đấng bậc ấy."));
visuperobject.biblemap.put("b46_7_21", new visuperobject(46,7,21,"Ngươi đương làm tôi mọi mà được gọi chăng? Chớ lấy làm lo; song nếu ngươi có thể được tự do, thì hãy nhơn dịp đó là hơn."));
visuperobject.biblemap.put("b46_7_22", new visuperobject(46,7,22,"Vì kẻ tôi mọi được Chúa gọi, ấy là kẻ Chúa đã buông tha; cũng một lẽ ấy, ai đương tự do mà được gọi, thì làm tôi mọi của Ðấng Christ."));
visuperobject.biblemap.put("b46_7_23", new visuperobject(46,7,23,"Anh em đã được chuộc bằng giá cao, chớ trở nên tôi mọi của người ta làm chi."));
visuperobject.biblemap.put("b46_7_24", new visuperobject(46,7,24,"Hỡi anh em, ai nầy khi được gọi ở đấng bậc nào, thì phải cứ ở theo đấng bậc ấy trước mặt Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_7_25", new visuperobject(46,7,25,"Về những kẻ đồng thân, tôi chẳng có lời Chúa truyền; song nhờ ơn thương xót của Chúa, tôi được làm người đáng tin, nên tôi ban lời khuyên bảo."));
visuperobject.biblemap.put("b46_7_26", new visuperobject(46,7,26,"Vậy tôi tưởng vì cớ tai vạ hầu đến, một người nam cứ ở vậy là nên."));
visuperobject.biblemap.put("b46_7_27", new visuperobject(46,7,27,"Có phải ngươi đã bị vấn vương với vợ chăng? Chớ tìm cách mà lìa mình ra. Có phải ngươi chưa bị vấn vương với vợ chăng? Ðừng kiếm vợ."));
visuperobject.biblemap.put("b46_7_28", new visuperobject(46,7,28,"Nhưng nếu ngươi lấy vợ, thì chẳng phạm tội gì; và nếu người nữ đồng trinh lấy chồng, thì cũng chẳng phạm tội gì. Song những người cưới gả sẽ có sự khó khăn về xác thịt, và tôi muốn cho anh em khỏi sự đó."));
visuperobject.biblemap.put("b46_7_29", new visuperobject(46,7,29,"Hỡi anh em, vậy thì tôi bảo nầy: thì giờ ngắn ngủi. Từ nay về sau, kẻ có vợ hãy nên như kẻ không có;"));
visuperobject.biblemap.put("b46_7_30", new visuperobject(46,7,30,"kẻ đương khóc, nên như kẻ không khóc; kẻ đương vui, nên như kẻ chẳng vui; kẻ đương mua, nên như kẻ chẳng được của gì;"));
visuperobject.biblemap.put("b46_7_31", new visuperobject(46,7,31,"và kẻ dùng của thế gian, nên như kẻ chẳng dùng vậy; vì hình trạng thế gian nầy qua đi."));
visuperobject.biblemap.put("b46_7_32", new visuperobject(46,7,32,"Vả, tôi muốn anh em được thong thả chẳng phải lo lắng gì. Ai không cưới vợ thì chăm lo việc Chúa, tìm phương cho Chúa đẹp lòng."));
visuperobject.biblemap.put("b46_7_33", new visuperobject(46,7,33,"Song ai cưới vợ rồi thì chăm lo việc đời nầy, tìm cách cho vợ mình thỏa dạ."));
visuperobject.biblemap.put("b46_7_34", new visuperobject(46,7,34,"Người nữ có chồng và đồng trinh cũng khác nhau như vậy: ai không chồng thì chăm lo việc Chúa, đặng cho thân thể và tinh thần đều được thánh; nhưng ai có chồng thì chăm lo các việc đời nầy, tìm cách cho đẹp lòng chồng mình."));
visuperobject.biblemap.put("b46_7_35", new visuperobject(46,7,35,"Tôi nói điều đó vì sự ích lợi cho anh em, chớ chẳng phải để gài bẫy, song để dắt anh em theo lẽ phải, hầu cho không phân tâm mà hầu việc Chúa."));
visuperobject.biblemap.put("b46_7_36", new visuperobject(46,7,36,"Nếu có ai tưởng chẳng nên cho con gái đồng trinh mình lỡ thì, và phải gả đi, thì người đó có thể tùy ý mình mà làm, không phạm tội gì; trong cơn đó, người con gái nên lấy chồng."));
visuperobject.biblemap.put("b46_7_37", new visuperobject(46,7,37,"Song có ai được tự chủ về việc mình làm, không bị sự gì bắt buộc, mà trong lòng đã quyết định cách vững vàng giữ con gái mình đồng trinh, thì nấy làm phải lẽ mà cứ theo như mình đã quyết chí."));
visuperobject.biblemap.put("b46_7_38", new visuperobject(46,7,38,"Thế thì kẻ gả con gái mình làm phải lẽ; song kẻ không gả, còn làm phải lẽ hơn nữa."));
visuperobject.biblemap.put("b46_7_39", new visuperobject(46,7,39,"Chồng còn sống bao lâu, thì vợ phải buột chặt với chồng bấy lâu; nếu chồng chết, vợ được tự do, muốn lấy ai tùy ý, miễn là theo ý Chúa."));
visuperobject.biblemap.put("b46_7_40", new visuperobject(46,7,40,"Nhưng, theo ý tôi, nếu cứ ở vậy, thì có phước hơn. Vả, tôi tưởng tôi cũng có Thánh Linh của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_8_1", new visuperobject(46,8,1,"Luận đến của cùng các thần tượng thì chúng ta biết mình đều có sự hay biết cả. Song sự hay biết sanh kiêu căng, còn sự yêu thương làm gương tốt."));
visuperobject.biblemap.put("b46_8_2", new visuperobject(46,8,2,"Nếu có ai tưởng mình biết điều gì, thật người ấy chưa biết như mình nên biết."));
visuperobject.biblemap.put("b46_8_3", new visuperobject(46,8,3,"Nhưng nếu có một người yêu mến Ðức Chúa Trời, thì Ðức Chúa Trời biết người đó."));
visuperobject.biblemap.put("b46_8_4", new visuperobject(46,8,4,"Vậy, về sự ăn ở của cúng tế các thần tượng, chúng ta biết thần tượng trong thế gian thật là hư không, chỉ có một Ðức Chúa Trời, chớ không có thần nào khác."));
visuperobject.biblemap.put("b46_8_5", new visuperobject(46,8,5,"Thật người ta xưng có các thần khác, hoặc ở trên trời, hoặc ở dưới đất, (bởi đó họ thờ nhiều thần nhiều Chúa),"));
visuperobject.biblemap.put("b46_8_6", new visuperobject(46,8,6,"về phần chúng ta, chỉ có một Ðức Chúa Trời mà thôi, là Ðức Chúa Cha, muôn vật bởi Ngài mà ra, và chúng ta hướng về Ngài; lại chỉ có một Chúa mà thôi, là Ðức Chúa Jêsus Christ, muôn vật đều nhờ Ngài mà có, và chúng ta cũng vậy."));
visuperobject.biblemap.put("b46_8_7", new visuperobject(46,8,7,"Nhưng chẳng phải mọi người đều có sự hay biết đó. Một đôi người vì nghĩ thường có thần tượng, nên khi ăn của cúng tế đó cho là của cúng tế thần tượng; thì lương tâm yếu đuối của họ bởi đó ra ô uế."));
visuperobject.biblemap.put("b46_8_8", new visuperobject(46,8,8,"Vả, ấy chẳng phải là đồ ăn làm cho chúng ta được đẹp lòng Ðức Chúa Trời; nếu chúng ta ăn, chẳng được ích gì, bằng không ăn, cũng chẳng tổn gì."));
visuperobject.biblemap.put("b46_8_9", new visuperobject(46,8,9,"Nhưng hãy giữ lấy, kẻo sự tự do mình làm dịp cho kẻ yếu đuối vấp phạm."));
visuperobject.biblemap.put("b46_8_10", new visuperobject(46,8,10,"Bởi vì, nếu có kẻ lương tâm yếu đuối thấy ngươi là người có sự hay biết ngồi ăn trong miếu tà thần, thì há chẳng cũng bắt chước mà ăn của cúng tế sao?"));
visuperobject.biblemap.put("b46_8_11", new visuperobject(46,8,11,"Thế thì ngươi lấy sự hay biết mình mà làm hư mất kẻ yếu đuối, là người anh em mà Ðấng Christ đã chết thế cho!"));
visuperobject.biblemap.put("b46_8_12", new visuperobject(46,8,12,"Khi nào mình phạm tội cùng anh em như vậy, làm cho lương tâm yếu đuối của họ bị thương, thì là phạm tội cùng Ðấng Christ."));
visuperobject.biblemap.put("b46_8_13", new visuperobject(46,8,13,"Cho nên, nếu đồ ăn xui anh em tôi vấp phạm, thì tôi sẽ chẳng hề ăn thịt, hầu cho khỏi làm dịp vấp phạm cho anh em tôi."));
visuperobject.biblemap.put("b46_9_1", new visuperobject(46,9,1,"Tôi chẳng được tự do sao? Tôi chẳng phải là sứ đồ sao? Tôi há chẳng từng thấy Ðức Chúa Jêsus là Chúa chúng ta sao? Anh em há chẳng phải là công việc tôi trong Chúa sao?"));
visuperobject.biblemap.put("b46_9_2", new visuperobject(46,9,2,"Nếu tôi không phải là sứ đồ cho kẻ khác, ít nữa cũng là sứ đồ cho anh em; vì chính anh em là ấn tín của chức sứ đồ tôi trong Chúa."));
visuperobject.biblemap.put("b46_9_3", new visuperobject(46,9,3,"Ấy là lẽ binh vực của tôi đối với kẻ kiện cáo mình."));
visuperobject.biblemap.put("b46_9_4", new visuperobject(46,9,4,"Chúng tôi há không có phép ăn uống sao?"));
visuperobject.biblemap.put("b46_9_5", new visuperobject(46,9,5,"Há không có phép dắt một người chị em làm vợ đi khắp nơi với chúng tôi như các sứ đồ khác cùng các anh em Chúa và Sê-pha đã làm, hay sao?"));
visuperobject.biblemap.put("b46_9_6", new visuperobject(46,9,6,"Hay là chỉ một tôi với Ba-na-ba không có phép được khỏi làm việc?"));
visuperobject.biblemap.put("b46_9_7", new visuperobject(46,9,7,"Vậy thì có ai ăn lương nhà mà đi đánh giặc? Có ai trồng vườn nho mà không ăn trái? Hay là có ai chăn bầy vật mà không dùng sữa nó để nuôi mình?"));
visuperobject.biblemap.put("b46_9_8", new visuperobject(46,9,8,"Tôi nói vậy, nào phải chỉ theo thói người ta quen nói đâu? Luật pháp há chẳng nói như vậy sao?"));
visuperobject.biblemap.put("b46_9_9", new visuperobject(46,9,9,"Vì chưng có chép trong luật pháp Môi-se rằng: Ngươi chớ khớp miệng con bò đang đạp lúa. Há phải Ðức Chúa Trời lo cho bò sao?"));
visuperobject.biblemap.put("b46_9_10", new visuperobject(46,9,10,"Quả thật Ngài nói câu đó về chúng ta mà có chép rằng ai cày ruộng phải trông cậy mình sẽ có phần mà đạp lúa."));
visuperobject.biblemap.put("b46_9_11", new visuperobject(46,9,11,"Nếu chúng tôi đã gieo của thiêng liêng cho anh em, mà muốn thâu lại của vật chất của anh em, thì nào có phải một việc quá lẽ đâu?"));
visuperobject.biblemap.put("b46_9_12", new visuperobject(46,9,12,"Người khác còn có quyền ấy trên anh em, huống chi là chúng tôi? Dầu vậy, chúng tôi chẳng từng dùng quyền ấy; nhưng chúng tôi chịu mọi sự, hầu cho khỏi làm ngăn trở Tin Lành của Ðấng Christ chút nào."));
visuperobject.biblemap.put("b46_9_13", new visuperobject(46,9,13,"Anh em há chẳng biết rằng ai hầu việc thánh thì ăn của dâng trong đền thờ, còn ai hầu việc nơi bàn thờ thì có phần nơi bàn thờ sao?"));
visuperobject.biblemap.put("b46_9_14", new visuperobject(46,9,14,"Cũng vậy, Chúa có truyền rằng ai rao giảng Tin Lành thì được nuôi mình bởi Tin Lành."));
visuperobject.biblemap.put("b46_9_15", new visuperobject(46,9,15,"Phần tôi thì chẳng từng dùng quyền ấy chút nào, và viết thơ nầy chẳng phải để đòi quyền ấy lại; vì tôi thà chết còn hơn là chịu ai cất lấy cớ khoe mình nầy đi."));
visuperobject.biblemap.put("b46_9_16", new visuperobject(46,9,16,"Ví bằng tôi rao truyền Tin Lành, tôi chẳng có cớ khoe mình, vì có lẽ cần buộc tôi; còn không rao truyền Tin Lành, thì khốn khó cho tôi thay."));
visuperobject.biblemap.put("b46_9_17", new visuperobject(46,9,17,"Nếu tôi vui lòng làm việc đó, thì được thưởng; lại nếu tôi không vui lòng mà làm, thì cái chức vụ cũng vẫn phó thác cho tôi."));
visuperobject.biblemap.put("b46_9_18", new visuperobject(46,9,18,"Thế thì phần thưởng của tôi là gì? Ấy là khi giảng Tin Lành, thì giảng nhưng không, chẳng dùng quyền tôi có như người giảng Tin Lành."));
visuperobject.biblemap.put("b46_9_19", new visuperobject(46,9,19,"Vả, tôi đối với ai vẫn cũng là được tự do, mà tôi đành phục mọi người, hầu cho tôi được nhiều người hơn."));
visuperobject.biblemap.put("b46_9_20", new visuperobject(46,9,20,"Với người Giu-đa, tôi ở như một người Giu-đa, hầu được những người Giu-đa; với những người dưới quyền luật pháp, (dầu chính tôi chẳng ở dưới quyền luật pháp), tôi cũng ở như kẻ dưới quyền luật pháp, hầu được những người dưới quyền luật pháp;"));
visuperobject.biblemap.put("b46_9_21", new visuperobject(46,9,21,"với những người không luật pháp, (dầu đối với Ðức Chúa Trời tôi không phải là không luật pháp, vì tôi ở dưới luật pháp của Ðấng Christ), song tôi cũng ở như người không luật pháp."));
visuperobject.biblemap.put("b46_9_22", new visuperobject(46,9,22,"Tôi ở yếu đuối với những người yếu đuối, hầu được những người yếu đuối; tôi đã trở nên mọi cách cho mọi người, để cứu chuộc được một vài người không cứ cách nào."));
visuperobject.biblemap.put("b46_9_23", new visuperobject(46,9,23,"Mọi điều tôi làm, thì làm vì cớ Tin Lành, hầu cho tôi cũng có phần trong đó."));
visuperobject.biblemap.put("b46_9_24", new visuperobject(46,9,24,"Anh em há Chúa Jêsus biết rằng trong cuộc chạy thi nơi trường đua, hết thảy đều chạy, nhưng chỉ một người được thưởng sao? Vậy, anh em hãy chạy cách nào cho được thưởng."));
visuperobject.biblemap.put("b46_9_25", new visuperobject(46,9,25,"Hết thảy những người đua tranh, tự mình chịu lấy mọi sự kiêng kỵ, họ chịu vậy để được mão triều thiên hay hư nát. Nhưng chúng ta chịu vậy để được mão triều thiên không hay hư nát."));
visuperobject.biblemap.put("b46_9_26", new visuperobject(46,9,26,"Vậy thì, tôi chạy, chẳng phải là chạy bá vơ; tôi đánh, chẳng phải là đánh gió;"));
visuperobject.biblemap.put("b46_9_27", new visuperobject(46,9,27,"song tôi đãi thân thể mình cách nghiêm khắc, bắt nó phải phục, e rằng sau khi tôi đã giảng dạy kẻ khác, mà chính mình phải bị bỏ chăng."));
visuperobject.biblemap.put("b46_10_1", new visuperobject(46,10,1,"Vả, hỡi anh em, tôi chẳng muốn cho anh em không biết tổ phụ chúng ta đều đã ở dưới đám mây, đi ngang qua biển,"));
visuperobject.biblemap.put("b46_10_2", new visuperobject(46,10,2,"chịu Môi-se làm phép báp tem trong đám mây và dưới biển,"));
visuperobject.biblemap.put("b46_10_3", new visuperobject(46,10,3,"ăn một thứ ăn thiêng liêng;"));
visuperobject.biblemap.put("b46_10_4", new visuperobject(46,10,4,"và uống một thứ uống thiêng liêng; vì họ uống nơi một hòn đá thiêng liêng theo mình và đá ấy tức là Ðấng Christ."));
visuperobject.biblemap.put("b46_10_5", new visuperobject(46,10,5,"Song phần nhiều trong vòng họ không đẹp lòng Ðức Chúa Trời, nên đã ngã chết nơi đồng vắng."));
visuperobject.biblemap.put("b46_10_6", new visuperobject(46,10,6,"Mọi điều đó đã xảy ra để làm gương cho chúng ta, hầu cho chúng ta chớ buông mình theo tình dục xấu, như chính tổ phụ chúng ta đã buông mình."));
visuperobject.biblemap.put("b46_10_7", new visuperobject(46,10,7,"Cũng đừng thờ hình tượng nữa, như mấy người trong họ, theo lời chép rằng: Dân sự ngồi mà ăn uống, rồi đứng dậy mà chơi dỡn."));
visuperobject.biblemap.put("b46_10_8", new visuperobject(46,10,8,"Chúng ta chớ dâm dục như mấy người trong họ đã dâm dục, mà trong một ngày có hai vạn ba ngàn người bị bỏ mạng."));
visuperobject.biblemap.put("b46_10_9", new visuperobject(46,10,9,"Cũng chớ thử thách Chúa như mấy người trong họ đã thử thách mà bị loài rắn hủy diệt."));
visuperobject.biblemap.put("b46_10_10", new visuperobject(46,10,10,"Lại cũng chớ lằm bằm như nấy người trong họ đã lằm bằm mà bị chết bởi kẻ hủy diệt."));
visuperobject.biblemap.put("b46_10_11", new visuperobject(46,10,11,"Những sự ấy có nghĩa hình bóng, và họ đã lưu truyền để khuyên bảo chúng ta là kẻ ở gần cuối cùng các đời."));
visuperobject.biblemap.put("b46_10_12", new visuperobject(46,10,12,"Vậy thì, ai tưởng mình đứng, hãy giữ kẻo ngã."));
visuperobject.biblemap.put("b46_10_13", new visuperobject(46,10,13,"Những sự cám dỗ đến cho anh em, chẳng có sự nào quá sức loài người. Ðức Chúa Trời là thành tín, Ngài chẳng hề cho anh em bị cám dỗ quá sức mình đâu; nhưng trong sự cám dỗ, Ngài cũng mở đàng cho ra khỏi, để anh em có thể chịu được."));
visuperobject.biblemap.put("b46_10_14", new visuperobject(46,10,14,"Hỡi kẻ yêu dấu của tôi, vậy nên hãy tránh khỏi sự thờ lạy hình tượng."));
visuperobject.biblemap.put("b46_10_15", new visuperobject(46,10,15,"Tôi nói với anh em cũng như nói với kẻ thông minh; chính anh em hãy suy xét điều tôi nói."));
visuperobject.biblemap.put("b46_10_16", new visuperobject(46,10,16,"Cái chén phước lành mà chúng ta chúc phước, há chẳng phải là thông với huyết của Ðấng Christ sao? Cái bánh mà chúng ta bẻ, há chẳng phải là thông với thân thể của Ðấng Christ sao?"));
visuperobject.biblemap.put("b46_10_17", new visuperobject(46,10,17,"Vì chỉ có một cái bánh, chúng ta dầu nhiều, cũng chỉ một thân thể; bởi chưng chúng ta đều có phần chung trong một cái bánh."));
visuperobject.biblemap.put("b46_10_18", new visuperobject(46,10,18,"Hãy xem dân Y-sơ-ra-ên theo phần xác; những kẻ ăn thịt con sinh tế, há không thông đồng với bàn thờ sao?"));
visuperobject.biblemap.put("b46_10_19", new visuperobject(46,10,19,"Nói vậy có ý chi? Của cùng thần tượng có ra gì chẳng?"));
visuperobject.biblemap.put("b46_10_20", new visuperobject(46,10,20,"Chắc là không; nhưng đồ người ngoại đạo cúng tế là cúng tế các quỉ, chớ không phải cúng tế Ðức Chúa Trời. Vậy, tôi không muốn anh em thông đồng với các quỉ."));
visuperobject.biblemap.put("b46_10_21", new visuperobject(46,10,21,"Anh em chẳng có thể uống chén của Chúa và cũng uống chén của các quỉ; chẳng có thể dự tiệc của Chúa, lại dự tiệc của các quỉ."));
visuperobject.biblemap.put("b46_10_22", new visuperobject(46,10,22,"Hay là chúng ta muốn trêu lòng Chúa ghen chăng? Chúng ta há mạnh hơn Ngài sao?"));
visuperobject.biblemap.put("b46_10_23", new visuperobject(46,10,23,"Mọi sự đều có phép làm, nhưng chẳng phải mọi sự đều có ích; mọi sự đều có phép làm, nhưng chẳng phải mọi sự đều làm gương tốt."));
visuperobject.biblemap.put("b46_10_24", new visuperobject(46,10,24,"Chớ ai tìm lợi riêng cho mình, nhưng ai nấy hãy tìm cho kẻ khác."));
visuperobject.biblemap.put("b46_10_25", new visuperobject(46,10,25,"Phàm vật gì bán ở hàng thịt, hãy ăn, đừng vì cớ lương tâm mà hỏi chi về việc đó;"));
visuperobject.biblemap.put("b46_10_26", new visuperobject(46,10,26,"bởi chưng đất và mọi vật chứa trong đất đều thuộc về Chúa."));
visuperobject.biblemap.put("b46_10_27", new visuperobject(46,10,27,"Nếu có người chẳng tin mời anh em, và anh em muốn đi, thì không cứ họ dọn ra đồ gì, hãy ăn đi hết thảy, đừng vì cớ lương tâm mà hỏi chi hết."));
visuperobject.biblemap.put("b46_10_28", new visuperobject(46,10,28,"Song nếu có ai nói với anh em rằng: Cái nầy đã dâng làm của cúng, thì chớ ăn, vì cớ người đã bảo trước mình, lại vì cớ lương tâm:"));
visuperobject.biblemap.put("b46_10_29", new visuperobject(46,10,29,"tôi chẳng nói về lương tâm anh em, nhưng về lương tâm người đó. Vả, vì cớ nào sự tự do tôi phải bị lương tâm kẻ khác đoán xét?"));
visuperobject.biblemap.put("b46_10_30", new visuperobject(46,10,30,"Nếu tôi tạ ơn rồi ăn, cớ nào vì một bữa ăn đã cảm ơn mà lại bị chê bai?"));
visuperobject.biblemap.put("b46_10_31", new visuperobject(46,10,31,"Vậy, anh em hoặc ăn, hoặc uống, hay là làm sự chi khác, hãy vì sự vinh hiển Ðức Chúa Trời mà làm."));
visuperobject.biblemap.put("b46_10_32", new visuperobject(46,10,32,"Ðừng làm gương xấu cho người Giu-đa, người Gờ-réc, hay là Hội thánh của Ðức Chúa Trời;"));
visuperobject.biblemap.put("b46_10_33", new visuperobject(46,10,33,"hãy như tôi gắng sức đẹp lòng mọi người trong mọi việc, chẳng tìm ích lợi riêng cho mình, nhưng cho phần nhiều người, để họ được cứu."));
visuperobject.biblemap.put("b46_11_1", new visuperobject(46,11,1,"Hãy bắt chước tôi, cũng như chính mình tôi bắt chước Ðấng Christ vậy."));
visuperobject.biblemap.put("b46_11_2", new visuperobject(46,11,2,"Tôi khen anh em vì hay nhớ đến tôi trong mọi dịp, và lấy lòng trung tín mà giữ những điều tôi đã dạy dỗ anh em."));
visuperobject.biblemap.put("b46_11_3", new visuperobject(46,11,3,"Dầu vậy, tôi muốn anh em biết Ðấng Christ là đầu mọi người; người đờn ông là đầu người đờn bà; và Ðức Chúa Trời là đầu của Ðấng Christ."));
visuperobject.biblemap.put("b46_11_4", new visuperobject(46,11,4,"Phàm người đờn ông cầu nguyện hoặc giảng đạo mà trùm đầu lại, thì làm nhục đầu mình."));
visuperobject.biblemap.put("b46_11_5", new visuperobject(46,11,5,"Nhưng phàm người đờn bà cầu nguyện hoặc giảng đạo mà không trùm đầu lại, thì làm nhục đầu mình: thật chẳng khác gì đã cạo đầu vậy."));
visuperobject.biblemap.put("b46_11_6", new visuperobject(46,11,6,"Ví bằng người đờn bà không trùm đầu, thì cũng nên hớt tóc đi. Song nếu người đờn bà lấy sự hớt tóc hoặc cạo đầu làm xấu hổ, thì hãy trùm đầu lại."));
visuperobject.biblemap.put("b46_11_7", new visuperobject(46,11,7,"Vả, đờn ông là hình ảnh và sự vinh hiển của Ðức Chúa Trời, thì không nên trùm đầu; nhưng đờn bà là sự vinh hiển của đờn ông."));
visuperobject.biblemap.put("b46_11_8", new visuperobject(46,11,8,"Bởi chưng không phải đờn ông ra từ đờn bà, bèn là đờn bà ra từ đờn ông;"));
visuperobject.biblemap.put("b46_11_9", new visuperobject(46,11,9,"không phải đờn ông vì cớ đờn bà mà được dựng nên, bèn là đờn bà vì cớ đờn ông vậy."));
visuperobject.biblemap.put("b46_11_10", new visuperobject(46,11,10,"Bởi đó, vì cớ các thiên sứ, đờn bà phải có dấu hiệu trên đầu chỉ về quyền phép mình nương cậy."));
visuperobject.biblemap.put("b46_11_11", new visuperobject(46,11,11,"Song trong Chúa thì chẳng phải đờn bà ngoại đờn ông, cũng chẳng phải đờn ông ngoại đờn bà;"));
visuperobject.biblemap.put("b46_11_12", new visuperobject(46,11,12,"vì, như đờn bà đã ra từ đờn ông, thì đờn ông cũng sanh bởi đờn bà, và cả thảy đều ra bởi Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_11_13", new visuperobject(46,11,13,"Chính anh em hãy đoán xét điều nầy: đờn bà cầu nguyện Ðức Chúa Trời mà không trùm đầu là hiệp lẽ chăng?"));
visuperobject.biblemap.put("b46_11_14", new visuperobject(46,11,14,"Chính lẽ tự nhiên há chẳng dạy cho anh em biết đờn ông để tóc dài thì lấy làm hổ thẹn sao?"));
visuperobject.biblemap.put("b46_11_15", new visuperobject(46,11,15,"Nhưng, nếu đờn bà để tóc dài thì là lịch sự cho mình, và đã ban tóc dài cho người, dường như khăn trùm vậy."));
visuperobject.biblemap.put("b46_11_16", new visuperobject(46,11,16,"Bằng có ai muốn cãi lẽ, thì chúng tôi không có thói quen ấy, mà các Hội thánh Ðức Chúa Trời cũng không có nữa."));
visuperobject.biblemap.put("b46_11_17", new visuperobject(46,11,17,"Trong khi tôi truyền lời cáo dụ nầy, chẳng phải khen anh em, vì sự nhóm lại của anh em không làm cho mình hay hơn mà làm cho mình dở hơn."));
visuperobject.biblemap.put("b46_11_18", new visuperobject(46,11,18,"Trước hết, tôi nghe rằng khi anh em có sự nhóm họp Hội thánh, thì sanh ra sự phân rẽ; tôi cũng hơi tin điều đó."));
visuperobject.biblemap.put("b46_11_19", new visuperobject(46,11,19,"Vì chắc trong vòng anh em phải có bè đảng, hầu cho được nhận biết trong anh em những kẻ nào thật là trung thành."));
visuperobject.biblemap.put("b46_11_20", new visuperobject(46,11,20,"Vậy, khi anh em nhóm nhau lại một chỗ, ấy chẳng còn phải là Tiệc thánh của Chúa mà anh em ăn;"));
visuperobject.biblemap.put("b46_11_21", new visuperobject(46,11,21,"bởi vì lúc ngồi ăn, ai cũng nôn nả mà ăn bữa riêng mình, đến nỗi người nọ chịu đói, còn kẻ kia thì quá độ."));
visuperobject.biblemap.put("b46_11_22", new visuperobject(46,11,22,"Anh em há chẳng có nhà để ăn uống sao? Hay là anh em khinh bỉ Hội thánh của Ðức Chúa Trời, muốn làm cho những kẻ không có gì phải hổ thẹn? Tôi nên nói chi với anh em? Có nên khen anh em không? Trong việc nầy tôi chẳng khen đâu."));
visuperobject.biblemap.put("b46_11_23", new visuperobject(46,11,23,"Vả, tôi có nhận nơi Chúa điều tôi đã dạy cho anh em: ấy là Ðức Chúa Jêsus, trong đêm Ngài bị nộp, lấy bánh,"));
visuperobject.biblemap.put("b46_11_24", new visuperobject(46,11,24,"tạ ơn, rồi bẻ ra mà phán rằng: Nầy là thân thể ta, vì các ngươi mà phó cho; hãy làm điều nầy để nhớ ta."));
visuperobject.biblemap.put("b46_11_25", new visuperobject(46,11,25,"Cũng một lẽ ấy, sai khi ăn bữa tối rồi, Ngài lấy chén và phán rằng: Chén nầy là sự giao ước mới trong huyết ta; hễ khi nào các ngươi uống, hãy làm điều nầy để nhớ ta."));
visuperobject.biblemap.put("b46_11_26", new visuperobject(46,11,26,"Ấy vậy, mỗi lần anh em ăn bánh nầy, uống chén nầy, thì rao sự chết của Chúa cho tới lúc Ngài đến."));
visuperobject.biblemap.put("b46_11_27", new visuperobject(46,11,27,"Bởi đó, ai ăn bánh hoặc uống chén của Chúa cách không xứng đáng, thì sẽ mắc tội với thân và huyết của Chúa."));
visuperobject.biblemap.put("b46_11_28", new visuperobject(46,11,28,"Vậy mỗi người phải tự xét lấy mình, và như thế mới ăn bánh uống chén ấy;"));
visuperobject.biblemap.put("b46_11_29", new visuperobject(46,11,29,"vì người nào không phân biệt thân Chúa mà ăn bánh uống chén đó, tức là ăn uống sự xét đoán cho mình."));
visuperobject.biblemap.put("b46_11_30", new visuperobject(46,11,30,"Ấy vì cớ đó mà trong anh em có nhiều kẻ tật nguyền, đau ốm, và có lắm kẻ ngủ."));
visuperobject.biblemap.put("b46_11_31", new visuperobject(46,11,31,"Nếu chúng ta biết xét đoán lấy mình, thì khỏi bị xét đoán."));
visuperobject.biblemap.put("b46_11_32", new visuperobject(46,11,32,"Song khi chúng ta bị Chúa xét đoán, thì bị Ngài sửa phạt, hầu cho khỏi bị án làm một với người thế gian."));
visuperobject.biblemap.put("b46_11_33", new visuperobject(46,11,33,"Hỡi anh em, vậy thì lúc anh em hội lại để ăn chung với nhau, hãy chờ đợi nhau."));
visuperobject.biblemap.put("b46_11_34", new visuperobject(46,11,34,"Ví bằng có ai đói, hãy ăn tại nhà mình, hầu cho anh em không nhóm lại để mà chuốc lấy sự đoán xét. Còn các việc khác, lúc tôi đến sẽ đoán định."));
visuperobject.biblemap.put("b46_12_1", new visuperobject(46,12,1,"Hỡi anh em, tôi không muốn anh em chẳng biết về các sự ban cho thiêng liêng."));
visuperobject.biblemap.put("b46_12_2", new visuperobject(46,12,2,"Anh em biết khi mình còn là người ngoại đạo, bị khuyên dỗ hướng về các thần tượng câm, tùy ý người ta dẫn dụ mình."));
visuperobject.biblemap.put("b46_12_3", new visuperobject(46,12,3,"Bởi đó, tôi tỏ cùng anh em, chẳng ai cảm Thánh Linh của Ðức Chúa Trời, mà nói rằng: Ðức Chúa Jêsus đáng nguyền rủa! Nếu không cảm Ðức Thánh Linh, cũng chẳng ai xưng Ðức Chúa Jêsus là Chúa!"));
visuperobject.biblemap.put("b46_12_4", new visuperobject(46,12,4,"Vả, có các sự ban cho khác nhau, nhưng chỉ có một Ðức Thánh Linh."));
visuperobject.biblemap.put("b46_12_5", new visuperobject(46,12,5,"Có các chức vụ khác nhau, nhưng chỉ có một Chúa."));
visuperobject.biblemap.put("b46_12_6", new visuperobject(46,12,6,"Có các việc làm khác nhau, nhưng chỉ có một Ðức Chúa Trời, là Ðấng làm mọi việc trong mọi người."));
visuperobject.biblemap.put("b46_12_7", new visuperobject(46,12,7,"Ðức Thánh Linh tỏ ra trong mỗi một người, cho ai nấy đều được sự ích chung."));
visuperobject.biblemap.put("b46_12_8", new visuperobject(46,12,8,"Vả, người nầy nhờ Ðức Thánh Linh, được lời nói khôn ngoan; kẻ kia nhờ một Ðức Thánh Linh ấy, cũng được lời nói có tri thức."));
visuperobject.biblemap.put("b46_12_9", new visuperobject(46,12,9,"Bởi một Ðức Thánh Linh, cho người nầy được đức tin; cũng bởi một Ðức Thánh Linh ấy, cho kẻ kia được ơn chữa tật bịnh;"));
visuperobject.biblemap.put("b46_12_10", new visuperobject(46,12,10,"người thì được làm phép lạ; kẻ thì được nói tiên tri; người thì được phân biệt các thần; kẻ thì được nói nhiều thứ tiếng khác nhau, người thì được thông giải các thứ tiếng ấy."));
visuperobject.biblemap.put("b46_12_11", new visuperobject(46,12,11,"Mọi điều đó là công việc của đồng một Ðức Thánh Linh mà thôi, theo ý Ngài muốn, phân phát sự ban cho riêng cho mỗi người."));
visuperobject.biblemap.put("b46_12_12", new visuperobject(46,12,12,"Vả, như thân là một, mà có nhiều chi thể, và như các chi thể của thân dầu có nhiều, cũng chỉ hiệp thành một thân mà thôi, Ðấng Christ khác nào như vậy."));
visuperobject.biblemap.put("b46_12_13", new visuperobject(46,12,13,"Vì chưng chúng ta hoặc người Giu-đa, hoặc người Gờ-réc, hoặc tôi mọi, hoặc tự chủ, đều đã chịu phép báp-tem chung một Thánh Linh để hiệp làm một thân; và chúng tôi đều đã chịu uống chung một Thánh Linh nữa."));
visuperobject.biblemap.put("b46_12_14", new visuperobject(46,12,14,"Thân cũng chẳng phải có một chi thể, bèn là nhiều chi thể."));
visuperobject.biblemap.put("b46_12_15", new visuperobject(46,12,15,"Nếu chơn rằng: vì ta chẳng phải là tay, nên ta không thuộc về thân, thì chẳng phải bởi đó chơn không có phần trong thân."));
visuperobject.biblemap.put("b46_12_16", new visuperobject(46,12,16,"Và nếu tai rằng: Vì ta chẳng phải là mắt, nên ta không thuộc về thân, thì tai chẳng phải bởi đó không có phần trong thân."));
visuperobject.biblemap.put("b46_12_17", new visuperobject(46,12,17,"Ví bằng cả thân đều là mắt, thì sự nghe ở đâu? Nếu cả thân đều là tai, thì sự ngửi ở đâu?"));
visuperobject.biblemap.put("b46_12_18", new visuperobject(46,12,18,"Nhưng bây giờ, Ðức Chúa Trời đã sắp đặt các chi thể của thân chúng ta, ban cho mỗi một chi thể cái địa vị theo ý Ngài lấy làm tốt mà chỉ định."));
visuperobject.biblemap.put("b46_12_19", new visuperobject(46,12,19,"Nếu chỉ có một chi thể mà thôi, thì cái thân ở đâu?"));
visuperobject.biblemap.put("b46_12_20", new visuperobject(46,12,20,"vậy, có nhiều chi thể, song chỉ có một thân."));
visuperobject.biblemap.put("b46_12_21", new visuperobject(46,12,21,"Mắt không được nói với bàn tay rằng: Ta chẳng cần đến mầy; đầu cũng chẳng được nói với chơn rằng: Ta chẳng cần đến bay."));
visuperobject.biblemap.put("b46_12_22", new visuperobject(46,12,22,"Trái lại, các chi thể của thân xem ra rất yếu đuối lại là cần dùng."));
visuperobject.biblemap.put("b46_12_23", new visuperobject(46,12,23,"Chi thể nào trong thân chúng ta nghĩ là hèn hạ hơn, thì chúng ta tôn trọng hơn; chi thể nào chẳng đẹp, thì chúng ta lại trau giồi hơn,"));
visuperobject.biblemap.put("b46_12_24", new visuperobject(46,12,24,"còn như cái nào đã đẹp rồi, thì không cần trau giồi. Nhưng Ðức Chúa Trời đã sắp đặt thân người, để chi thể nào thiếu thốn thì được quí trọng hơn,"));
visuperobject.biblemap.put("b46_12_25", new visuperobject(46,12,25,"hầu cho trong thân không có sự phân rẽ, mà các chi thể phải đồng lo tưởng đến nhau."));
visuperobject.biblemap.put("b46_12_26", new visuperobject(46,12,26,"Lại, trong các chi thể, khi có một cái nào chịu đau đớn, thì các cái khác đều cùng chịu; và khi một cái nào được tôn trọng, thì các cái khác cùng vui mừng."));
visuperobject.biblemap.put("b46_12_27", new visuperobject(46,12,27,"Vả, anh em là thân của Ðấng Christ, và là chi thể của thân, ai riêng phần nấy."));
visuperobject.biblemap.put("b46_12_28", new visuperobject(46,12,28,"Ðức Chúa Trời đã lập trong Hội thánh, thứ nhứt là sứ đồ, thứ nhì là đấng tiên tri, thứ ba là thầy giáo, kế đến kẻ làm phép lạ, rồi kẻ được ơn chữa bịnh, cứu giúp, cai quản, nói các thứ tiếng."));
visuperobject.biblemap.put("b46_12_29", new visuperobject(46,12,29,"Có phải cả thảy là sứ đồ sao? Cả thảy là tiên tri sao? Cả thảy đều là thầy giáo sao? Cả thảy đều làm phép lạ sao?"));
visuperobject.biblemap.put("b46_12_30", new visuperobject(46,12,30,"Cả thảy đều được ơn chữa bịnh sao? Cả thảy đều nói tiếng lạ sao? Cả thảy đều thông giải tiếng lạ sao?"));
visuperobject.biblemap.put("b46_12_31", new visuperobject(46,12,31,"Hãy ước ao cho được sự ban cho lớn hơn hết. Bây giờ, tôi sẽ chỉ dẫn cho anh em con đường tốt lành hơn."));
visuperobject.biblemap.put("b46_13_1", new visuperobject(46,13,1,"Dầu tôi nói được các thứ tiếng loài người và thiên sứ, nếu không có tình yêu thương, thì tôi chỉ như đồng kêu lên hay là chập chỏa vang tiếng."));
visuperobject.biblemap.put("b46_13_2", new visuperobject(46,13,2,"Dầu tôi được ơn nói tiên tri, cùng biết đủ các sự mầu nhiệm, và mọi sự hay biết; dầu tôi có cả đức tin đến nỗi dời núi được, nhưng không có tình yêu thương, thì tôi chẳng ra gì."));
visuperobject.biblemap.put("b46_13_3", new visuperobject(46,13,3,"Dầu tôi phân phát gia tài để nuôi kẻ nghèo khó, lại bỏ thân mình để chịu đốt, song không có tình yêu thương, thì điều đó chẳng ích chi cho tôi."));
visuperobject.biblemap.put("b46_13_4", new visuperobject(46,13,4,"Tình yêu thương hay nhịn nhục; tình yêu thương hay nhơn từ; tình yêu thương chẳng ghen tị, chẳng khoe mình, chẳng lên mình kiêu ngạo,"));
visuperobject.biblemap.put("b46_13_5", new visuperobject(46,13,5,"chẳng làm điều trái phép, chẳng kiếm tư lợi, chẳng nóng giận, chẳng nghi ngờ sự dữ,"));
visuperobject.biblemap.put("b46_13_6", new visuperobject(46,13,6,"chẳng vui về điều không công bình, nhưng vui trong lẽ thật."));
visuperobject.biblemap.put("b46_13_7", new visuperobject(46,13,7,"Tình yêu thương hay dung thứ mọi sự, tin mọi sự, trông cậy mọi sự, nín chịu mọi sự."));
visuperobject.biblemap.put("b46_13_8", new visuperobject(46,13,8,"Tình yêu thương chẳng hề hư mất bao giờ. Các lời tiên tri sẽ hết, sự ban cho nói tiếng lạ sẽ thôi, sự thông biết hầu bị bỏ."));
visuperobject.biblemap.put("b46_13_9", new visuperobject(46,13,9,"Vì chưng chúng ta hiểu biết chưa trọn vẹn, nói tiên tri cũng chưa trọn vẹn;"));
visuperobject.biblemap.put("b46_13_10", new visuperobject(46,13,10,"song lúc sự trọn lành đã đến, thì sự chưa được trọn lành sẽ bị bỏ."));
visuperobject.biblemap.put("b46_13_11", new visuperobject(46,13,11,"Khi tôi còn trẻ, tôi nói như con trẻ, tư tưởng như con trẻ, suy xét như con trẻ; khi tôi đã thành nhơn bèn bỏ những điều thuộc về con trẻ."));
visuperobject.biblemap.put("b46_13_12", new visuperobject(46,13,12,"Ngày nay chúng ta xem như trong một cái gương, cách mập mờ: đến bấy giờ chúng ta sẽ thấy hai mặt đối nhau; ngày nay tôi biết chưa hết: đến bấy giờ tôi sẽ biết như Chúa đã biết tôi vậy."));
visuperobject.biblemap.put("b46_13_13", new visuperobject(46,13,13,"Nên bây giờ còn có ba điều nầy: đức tin, sự trông cậy, tình yêu thương; nhưng điều trọng hơn trong ba điều đó là tình yêu thương."));
visuperobject.biblemap.put("b46_14_1", new visuperobject(46,14,1,"Hãy nôn nả tìm kiếm tình yêu thương. Cũng hãy ước ao các sự ban cho thiêng liêng, nhứt là sự ban cho nói tiên tri."));
visuperobject.biblemap.put("b46_14_2", new visuperobject(46,14,2,"Vì người nào nói tiếng lạ, thì không phải nói với người ta, bèn là với Ðức Chúa Trời, bởi chẳng có ai hiểu (ấy là trong tâm thần mà người kia nói lời mầu nhiệm);"));
visuperobject.biblemap.put("b46_14_3", new visuperobject(46,14,3,"còn như kẻ nói tiên tri, thì nói với người ta để gây dựng, khuyên bảo và yên ủi."));
visuperobject.biblemap.put("b46_14_4", new visuperobject(46,14,4,"Kẻ nói tiếng lạ, tự gây dựng lấy mình; song kẻ nói tiên tri, gây dựng cho Hội thánh."));
visuperobject.biblemap.put("b46_14_5", new visuperobject(46,14,5,"Tôi ước ao anh em đều nói tiếng lạ cả, song tôi còn ước ao hơn nữa là anh em nói tiên tri. Người nói tiên tri là trọng hơn kẻ nói tiếng lạ mà không giải nghĩa để cho Hội thánh được gây dựng."));
visuperobject.biblemap.put("b46_14_6", new visuperobject(46,14,6,"Hỡi anh em, vì bằng tôi đến cùng anh em, nói các thứ tiếng lạ, mà lời nói tôi chẳng tỏ sự mầu nhiệm, chẳng có sự thông biết, chẳng có lời tiên tri, chẳng có sự khuyên dạy, thì ích gì đến anh em?"));
visuperobject.biblemap.put("b46_14_7", new visuperobject(46,14,7,"Vậy, dẫu vật không linh tánh phát ra tiếng, như ống tiêu, đờn cầm: nếu không có âm điệu phân biệt nhau, thể nào nhận biết được ống tiêu hay là đờn cầm thổi và khảy cái chi?"));
visuperobject.biblemap.put("b46_14_8", new visuperobject(46,14,8,"Lại nếu kèn trổi tiếng lộn xộn, thì ai sửa soạn mà ra trận?"));
visuperobject.biblemap.put("b46_14_9", new visuperobject(46,14,9,"Anh em cũng vậy, nếu dùng lưỡi nói chẳng rõ ràng cho người ta nghe, thì làm sao họ được biết điều anh em nói? Vì anh em nói bông lông."));
visuperobject.biblemap.put("b46_14_10", new visuperobject(46,14,10,"Trong thế gian có lắm thứ tiếng, mỗi thứ đều có nghĩa."));
visuperobject.biblemap.put("b46_14_11", new visuperobject(46,14,11,"Vậy nếu tôi chẳng biết nghĩa của tiếng nói đó, thì người nói tiếng đó sẽ coi tôi là mọi, và tôi cũng coi họ là mọi nữa."));
visuperobject.biblemap.put("b46_14_12", new visuperobject(46,14,12,"Ấy vậy, vì anh em nôn nả ước ao các sự ban cho thiêng liêng, hãy tìm cho được dư dật đặng gây dựng Hội thánh."));
visuperobject.biblemap.put("b46_14_13", new visuperobject(46,14,13,"Bởi đó, kẻ nói tiếng lạ, hãy cầu nguyện để được thông giải tiếng ấy."));
visuperobject.biblemap.put("b46_14_14", new visuperobject(46,14,14,"Vì nếu tôi cầu nguyện bằng tiếng lạ, thì tâm thần tôi cầu nguyện, nhưng trí khôn tôi lơ lửng."));
visuperobject.biblemap.put("b46_14_15", new visuperobject(46,14,15,"Vậy thì tôi sẽ làm thể nào? Tôi sẽ cầu nguyện theo tâm thần, nhưng cũng cầu nguyện bằng trí khôn. Tôi sẽ hát theo tâm thần, nhưng cũng hát bằng trí khôn."));
visuperobject.biblemap.put("b46_14_16", new visuperobject(46,14,16,"Bằng không, nếu ngươi chỉ lấy tâm thần mà chúc tạ, thì người tầm thường ngồi nghe, chẳng hiểu ngươi nói gì, thể nào họ theo lời chúc tạ mình mà đáp lại A-men được?"));
visuperobject.biblemap.put("b46_14_17", new visuperobject(46,14,17,"Thật vậy, lời chúc tạ của ngươi vẫn tốt lành; song kẻ khác chẳng nhờ đó mà được gây dựng."));
visuperobject.biblemap.put("b46_14_18", new visuperobject(46,14,18,"Tôi tạ ơn Ðức Chúa Trời, vì đã được ơn nói tiếng lạ nhiều hơn hết thảy anh em;"));
visuperobject.biblemap.put("b46_14_19", new visuperobject(46,14,19,"nhưng thà tôi lấy năm lời bằng trí khôn mình mà rao giảng trong Hội thánh, để được dạy bảo kẻ khác, hơn là lấy một vạn lời bằng tiếng lạ."));
visuperobject.biblemap.put("b46_14_20", new visuperobject(46,14,20,"Hỡi Anh em, về sự khôn sáng, chớ nên như trẻ con; nhưng về sự gian ác, thật hãy nên như trẻ con vậy. Còn về sự khôn sáng, hãy nên như kẻ thành nhơn."));
visuperobject.biblemap.put("b46_14_21", new visuperobject(46,14,21,"Trong luật pháp có chép rằng: Chúa phán: Ta sẽ nhờ những người nói tiếng lạ, và môi miệng người ngoại quốc mà phán cho dân nầy; dầu vậy họ cũng chẳng nghe ta."));
visuperobject.biblemap.put("b46_14_22", new visuperobject(46,14,22,"Thế thì, các thứ tiếng là một dấu, chẳng cho người tin Chúa, song cho người chẳng tin; còn như lời tiên tri là một dấu, chẳng phải cho người không tin, song cho người tin Chúa."));
visuperobject.biblemap.put("b46_14_23", new visuperobject(46,14,23,"Vậy thì cả Hội thánh nhóm lại một nơi, nếu ai nấy đều nói tiếng lạ, mà có kẻ tầm thường hoặc người chẳng tin vào nghe, họ há chẳng nói anh em là điên cuồng sao?"));
visuperobject.biblemap.put("b46_14_24", new visuperobject(46,14,24,"Song nếu ai nấy đều nói tiên tri, mà có người chẳng tin hoặc kẻ tầm thường vào nghe, thì họ sẽ bị mọi người bắt phục, và bị mọi người xét đoán,"));
visuperobject.biblemap.put("b46_14_25", new visuperobject(46,14,25,"sự kín giấu trong lòng họ đã tỏ ra; họ bèn sấp mặt xuống đất, thờ lạy Ðức Chúa Trời, và nói rằng thật có Ðức Chúa Trời ở giữa anh em."));
visuperobject.biblemap.put("b46_14_26", new visuperobject(46,14,26,"Hỡi Anh em, nên nói thể nào? Khi Anh em nhóm lại với nhau, trong anh em, ai có bài ca, hoặc bài giảng dạy, hoặc lời tỏ sự kín nhiệm, hoặc nói tiếng lạ, hoặc giải tiếng lạ chăng? Hãy làm hết thảy cho được gây dựng."));
visuperobject.biblemap.put("b46_14_27", new visuperobject(46,14,27,"Ví bằng có người nói tiếng lạ, chỉ nên hai hoặc ba người là cùng; mỗi người phải nói theo lượt mình, và phải có một người thông giải."));
visuperobject.biblemap.put("b46_14_28", new visuperobject(46,14,28,"Nếu không có ai thông giải, thì người đó phải làm thinh ở trong Hội thánh, mình nói với mình và với Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_14_29", new visuperobject(46,14,29,"Người nói tiên tri cũng chỉ nên có hai hoặc ba người nói mà thôi, còn những kẻ khác thì suy xét."));
visuperobject.biblemap.put("b46_14_30", new visuperobject(46,14,30,"Song, nếu một người trong bọn người ngồi, có lời tỏ kín nhiệm, thì người thứ nhất phải nín lặng."));
visuperobject.biblemap.put("b46_14_31", new visuperobject(46,14,31,"Bởi vì anh em đều cứ lần lượt mà nói tiên tri được cả, để ai nấy đều được dạy bảo, ai nấy đều được khuyên lơn."));
visuperobject.biblemap.put("b46_14_32", new visuperobject(46,14,32,"Tâm thần của các đấng tiên tri suy phục các đấng tiên tri."));
visuperobject.biblemap.put("b46_14_33", new visuperobject(46,14,33,"Vả, Ðức Chúa Trời chẳng phải là Chúa của sự loạn lạc, bèn là Chúa sự hòa bình. Hãy làm như trong cả Hội thánh của các thánh đồ,"));
visuperobject.biblemap.put("b46_14_34", new visuperobject(46,14,34,"đờn bà phải nín lặng trong đám hội của anh em: họ không có phép nói tại nơi đó, nhưng phải phục tùng cũng như luật pháp dạy."));
visuperobject.biblemap.put("b46_14_35", new visuperobject(46,14,35,"Nhược bằng họ muốn học khôn điều gì, thì mỗi người trong đám họ phải hỏi chồng mình ở nhà; bởi vì đờn bà nói lên trong Hội thánh là không hiệp lẽ."));
visuperobject.biblemap.put("b46_14_36", new visuperobject(46,14,36,"Có phải là đạo Ðức Chúa Trời ra từ nơi anh em, hoặc chỉ đến cùng anh em mà thôi chăng?"));
visuperobject.biblemap.put("b46_14_37", new visuperobject(46,14,37,"Nếu ai tưởng mình là tiên tri, hay là được Ðức Thánh Linh soi sáng, thì người ấy hãy biết rằng đều tôi viết cho anh em đây là mạng lịnh của Chúa."));
visuperobject.biblemap.put("b46_14_38", new visuperobject(46,14,38,"Mà nếu ai muốn bỏ qua thì mặc họ bỏ qua!"));
visuperobject.biblemap.put("b46_14_39", new visuperobject(46,14,39,"Ấy vậy, hỡi anh em, hãy trông mong ơn nói tiên tri, và đừng ngăn trở chi về điều nói tiếng lạ."));
visuperobject.biblemap.put("b46_14_40", new visuperobject(46,14,40,"Nhưng mọi sự đều nên làm cho phải phép và theo thứ tự."));
visuperobject.biblemap.put("b46_15_1", new visuperobject(46,15,1,"Hỡi anh em, tôi nhắc lại cho anh em Tin Lành mà tôi đã rao giảng và anh em đã nhận lấy, cùng đứng vững vàng trong đạo ấy,"));
visuperobject.biblemap.put("b46_15_2", new visuperobject(46,15,2,"và nhờ đạo ấy, anh em được cứu rỗi, miễn là anh em giữ lấy y như tôi đã giảng cho; bằng không, thì anh em dầu có tin cũng vô ích."));
visuperobject.biblemap.put("b46_15_3", new visuperobject(46,15,3,"Vả trước hết tôi đã dạy dỗ anh em điều mà chính tôi đã nhận lãnh, ấy là Ðấng Christ chịu chết vì tội chúng ta theo lời Kinh Thánh;"));
visuperobject.biblemap.put("b46_15_4", new visuperobject(46,15,4,"Ngài đã bị chôn, đến ngày thứ ba, Ngài sống lại, theo lời Kinh Thánh;"));
visuperobject.biblemap.put("b46_15_5", new visuperobject(46,15,5,"và Ngài đã hiện ra cho Sê-pha, sau lại hiện ra cho mười hai sứ đồ."));
visuperobject.biblemap.put("b46_15_6", new visuperobject(46,15,6,"Rồi đó, cùng trong một lần, Ngài hiện ra cho hơn năm trăm anh em xem thấy, phần nhiều người trong số ấy hiện bây giờ còn sống, nhưng có mấy người đã ngủ rồi."));
visuperobject.biblemap.put("b46_15_7", new visuperobject(46,15,7,"Ðoạn, Ngài hiện ra cho Gia-cơ, rồi cho các sứ đồ."));
visuperobject.biblemap.put("b46_15_8", new visuperobject(46,15,8,"Rồi lại, sau những người ấy, Ngài cũng hiện ra cho tôi xem, như cho một thai sanh non vậy."));
visuperobject.biblemap.put("b46_15_9", new visuperobject(46,15,9,"Vì tôi là rất hèn mọn trong các sứ đồ, không đáng gọi là sứ đồ, bởi tôi đã bắt bớ Hội thánh của Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_15_10", new visuperobject(46,15,10,"Nhưng tôi nay là người thể nào, là nhờ ơn Ðức Chúa Trời, và ơn Ngài ban cho tôi cũng không phải là uổng vậy. Trái lại, tôi đã làm nhiều việc hơn các người khác, nhưng nào phải tôi, bèn là ơn Ðức Chúa Trời đã ở cùng tôi."));
visuperobject.biblemap.put("b46_15_11", new visuperobject(46,15,11,"Ấy vậy, dầu tôi, dầu các người khác, đó là điều chúng tôi giảng dạy, và là điều anh em đã tin."));
visuperobject.biblemap.put("b46_15_12", new visuperobject(46,15,12,"Vả, nếu giảng dạy rằng Ðấng Christ đã từ kẻ chết sống lại, thì sao trong anh em có kẻ nói rằng những kẻ chết chẳng sống lại?"));
visuperobject.biblemap.put("b46_15_13", new visuperobject(46,15,13,"Nếu những kẻ không sống lại, thì Ðấng Christ cũng đã chẳng sống lại nữa."));
visuperobject.biblemap.put("b46_15_14", new visuperobject(46,15,14,"Lại nếu Ðấng Christ đã chẳng sống lại, thì sự giảng dạy của chúng tôi ra luống công, và đức tin anh em cũng vô ích."));
visuperobject.biblemap.put("b46_15_15", new visuperobject(46,15,15,"Lại nếu kẻ chết quả thật không sống lại, thì Ðức Chúa Trời đã chẳng khiến Ðấng Christ sống lại, mà chúng tôi đã làm chứng trái với Ðức Chúa Trời rằng Ngài đã làm cho Ðấng Christ sống lại, té ra chúng tôi làm chứng dối cho Ðức Chúa Trời."));
visuperobject.biblemap.put("b46_15_16", new visuperobject(46,15,16,"Vì nếu kẻ chết chẳng sống lại, thì Ðấng Christ cũng đã chẳng sống lại nữa."));
visuperobject.biblemap.put("b46_15_17", new visuperobject(46,15,17,"Và nếu Ðấng Christ đã chẳng sống lại, thì đức tin anh em cũng vô ích, anh em còn ở trong tội lỗi mình."));
visuperobject.biblemap.put("b46_15_18", new visuperobject(46,15,18,"Vậy, những kẻ ngủ trong Ðấng Christ cũng phải hư mất đời đời."));
visuperobject.biblemap.put("b46_15_19", new visuperobject(46,15,19,"Nếu chúng ta chỉ có sự trông cậy trong Ðấng Christ về đời nầy mà thôi, thì trong cả mọi người, chúng ta là kẻ khốn nạn hơn hết."));
visuperobject.biblemap.put("b46_15_20", new visuperobject(46,15,20,"Nhưng bây giờ, Ðấng Christ đã từ kẻ chết sống lại, Ngài là trái đầu mùa của những kẻ ngủ."));
visuperobject.biblemap.put("b46_15_21", new visuperobject(46,15,21,"Vả, vì chưng bởi một người mà có sự chết, thì cũng bởi một người mà có sự sống lại của những kẻ chết."));
visuperobject.biblemap.put("b46_15_22", new visuperobject(46,15,22,"Như trong A-đam mọi người đều chết, thì cũng một lẽ ấy, trong Ðấng Christ mọi người đều sẽ sống lại,"));
visuperobject.biblemap.put("b46_15_23", new visuperobject(46,15,23,"nhưng mỗi người theo thứ tự riêng của mình: Ðấng Christ là trái đầu mùa; rồi tới ngày Ðấng Christ đến, những kẻ thuộc về Ngài sẽ sống lại."));
visuperobject.biblemap.put("b46_15_24", new visuperobject(46,15,24,"Kế đó, cuối cùng sẽ đến là lúc Ngài sẽ giao nước lại cho Ðức Chúa Trời là Cha, sau khi Ngài đã phá diệt mọi đế quốc, mọi quyền cai trị, và mọi thế lực;"));
visuperobject.biblemap.put("b46_15_25", new visuperobject(46,15,25,"vì Ngài phải cầm quyền cho đến chừng đặt những kẻ thù nghịch dưới chơn mình."));
visuperobject.biblemap.put("b46_15_26", new visuperobject(46,15,26,"Kẻ thù bị hủy diệt sau cùng, tức là sự chết."));
visuperobject.biblemap.put("b46_15_27", new visuperobject(46,15,27,"Vả, Ðức Chúa Trời đã để muôn vật dưới chơn Ngài; mà đã nói rằng muôn vật phục Ngài, thì chắc phải trừ ra Ðấng làm cho muôn vật phục Ngài."));
visuperobject.biblemap.put("b46_15_28", new visuperobject(46,15,28,"Khi muôn vật đã phục Ngài, thì bấy giờ chính mình Con sẽ phục Ðấng đã làm cho muôn vật phục mình, hầu cho Ðức Chúa Trời làm muôn sự trong muôn sự."));
visuperobject.biblemap.put("b46_15_29", new visuperobject(46,15,29,"Bằng chẳng vậy, những người vì kẻ chết chịu phép báp tem sẽ làm chi? Nếu kẻ chết quả thật không sống lại, thì sao họ vì những kẻ ấy mà chịu phép báp tem?"));
visuperobject.biblemap.put("b46_15_30", new visuperobject(46,15,30,"Lại sao chính mình chúng tôi giờ nào cũng ở trong sự nguy hiểm?"));
visuperobject.biblemap.put("b46_15_31", new visuperobject(46,15,31,"Hỡi anh em, tôi chết hằng ngày, thật cũng như anh em là sự vinh hiển cho tôi trong Ðức Chúa Jêsus Christ, là Chúa chúng ta."));
visuperobject.biblemap.put("b46_15_32", new visuperobject(46,15,32,"Nếu tôi theo cách loài người mà đã đánh cùng các loài thú ở thành Ê-phê-sô, thì có ích gì cho tôi? Nếu kẻ chết chẳng sống lại, thì hãy ăn, hãy uống, vì ngày mai chúng ta sẽ chết!"));
visuperobject.biblemap.put("b46_15_33", new visuperobject(46,15,33,"Anh em chớ mắc lừa: bạn bè xấu làm hư thói nết tốt."));
visuperobject.biblemap.put("b46_15_34", new visuperobject(46,15,34,"Hãy tỉnh biết, theo các công bình, và chớ phạm tội; vì có người không biết Ðức Chúa Trời chút nào, tôi nói vậy để anh em hổ thẹn."));
visuperobject.biblemap.put("b46_15_35", new visuperobject(46,15,35,"Nhưng có kẻ sẽ nói rằng: Người chết sống lại thể nào, lấy xác nào mà trở lại?"));
visuperobject.biblemap.put("b46_15_36", new visuperobject(46,15,36,"Hỡi kẻ dại kia, vật gì ngươi gieo, nếu không chết đi trước đã, thì không sống lại được."));
visuperobject.biblemap.put("b46_15_37", new visuperobject(46,15,37,"Còn như vật ngươi gieo, ấy không phải là chính hình thể sẽ sanh ra, chẳng qua là một cái hột, như hột lúa mì hay là hột giống nào khác."));
visuperobject.biblemap.put("b46_15_38", new visuperobject(46,15,38,"Ðức Chúa Trời cho nó hình thể tùy ý Ngài lấy làm tốt, mỗi một hột giống, cho một hình thể riêng."));
visuperobject.biblemap.put("b46_15_39", new visuperobject(46,15,39,"Mọi xác thịt chẳng phải là đồng một xác thịt; nhưng xác thịt loài người khác, xác thịt loài thú khác, loài chim khác, loài cá khác."));
visuperobject.biblemap.put("b46_15_40", new visuperobject(46,15,40,"Lại cũng có hình thể thuộc về trời, hình thể thuộc về đất, nhưng vinh quang của hình thể thuộc về trời với vinh quang của hình thể thuộc về đất thì khác nhau."));
visuperobject.biblemap.put("b46_15_41", new visuperobject(46,15,41,"Vinh quang của mặt trời khác, vinh quang của mặt trăng khác, vinh quang của ngôi sao khác; vinh quang của ngôi sao nầy với vinh quang của ngôi sao kia cũng khác."));
visuperobject.biblemap.put("b46_15_42", new visuperobject(46,15,42,"Sự sống lại của kẻ chết cũng như vậy. Thân thể đã gieo ra là hay hư nát, mà sống lại là không hay hư nát;"));
visuperobject.biblemap.put("b46_15_43", new visuperobject(46,15,43,"đã gieo ra là nhục, mà sống lại là vinh; đã gieo ra là yếu, mà sống lại là mạnh;"));
visuperobject.biblemap.put("b46_15_44", new visuperobject(46,15,44,"đã gieo ra là thể huyết khí, mà sống lại là thể thiêng liêng. Nếu đã có thể huyết khí, thì cũng có thể thiêng liêng;"));
visuperobject.biblemap.put("b46_15_45", new visuperobject(46,15,45,"ấy vậy, có lời chép rằng: Người thứ nhứt là A-đam đã nên linh hồn sống. A-đam sau hết là thần ban sự sống."));
visuperobject.biblemap.put("b46_15_46", new visuperobject(46,15,46,"Nhưng chẳng phải thể thiêng liêng đến trước, ấy là thể huyết khí; rồi thể thiêng liêng đến sau."));
visuperobject.biblemap.put("b46_15_47", new visuperobject(46,15,47,"Người thứ nhứt bởi đất mà ra, là thuộc về đất, người thứ hai bởi trời mà ra."));
visuperobject.biblemap.put("b46_15_48", new visuperobject(46,15,48,"Người thuộc về đất thể nào, thì những kẻ thuộc về đất cũng thể ấy; người thuộc về trời thể nào, thì những kẻ thuộc về trời cũng thể ấy."));
visuperobject.biblemap.put("b46_15_49", new visuperobject(46,15,49,"Như chúng ta đã mang ảnh tượng của người thuộc về đất, thì chúng ta cũng sẽ mang ảnh tượng của người thuộc về trời."));
visuperobject.biblemap.put("b46_15_50", new visuperobject(46,15,50,"Hỡi anh em, tôi đoán quyết rằng thịt và máu chẳng hưởng nước Ðức Chúa Trời được, và sự hay hư nát không hưởng sự không hay hư nát được."));
visuperobject.biblemap.put("b46_15_51", new visuperobject(46,15,51,"Nầy là sự mầu nhiệm tôi tỏ cho anh em: Chúng ta không ngủ hết, nhưng hết thảy đều sẽ biến hóa,"));
visuperobject.biblemap.put("b46_15_52", new visuperobject(46,15,52,"trong giây phút, trong nháy mắt, lúc tiếng kèn chót; vì kèn sẽ thổi, kẻ chết đều sống lại được không hay hư nát, và chúng ta đều sẽ biến hóa."));
visuperobject.biblemap.put("b46_15_53", new visuperobject(46,15,53,"Vả, thể hay hư nát nầy phải mặc lấy sự không hay hư nát, và thể hay chết nầy phải mặc lấy sự không hay chết."));
visuperobject.biblemap.put("b46_15_54", new visuperobject(46,15,54,"Khi nào thể hay hư nát nầy mặc lấy sự không hay hư nát, thể hay chết nầy mặc lấy sự không hay chết, thì được ứng nghiệm lời Kinh Thánh rằng: Sự chết đã bị nuốt mất trong sự thắng."));
visuperobject.biblemap.put("b46_15_55", new visuperobject(46,15,55,"Hỡi sự chết, sự thắng của mầy ở đâu? Hỡi sự chết, cái nọc của mầy ở đâu?"));
visuperobject.biblemap.put("b46_15_56", new visuperobject(46,15,56,"Cái nọc sự chết là tội lỗi, sức mạnh tội lỗi là luật pháp."));
visuperobject.biblemap.put("b46_15_57", new visuperobject(46,15,57,"Nhưng, tạ ơn Ðức Chúa Trời đã cho chúng ta sự thắng, nhờ Ðức Chúa Jêsus Christ chúng ta."));
visuperobject.biblemap.put("b46_15_58", new visuperobject(46,15,58,"Vậy, hỡi anh em yêu dấu của tôi, hãy vững vàng, chớ rúng động, hãy làm công việc Chúa cách dư dật luôn, vì biết rằng công khó của anh em trong Chúa chẳng phải là vô ích đâu."));
visuperobject.biblemap.put("b46_16_1", new visuperobject(46,16,1,"Về việc góp tiền cho thánh đồ, thì anh em cũng hãy theo như tôi đã định liệu cho các Hội thánh xứ Ga-la-ti."));
visuperobject.biblemap.put("b46_16_2", new visuperobject(46,16,2,"Cứ ngày đầu tuần lễ. mỗi một người trong anh em khá tùy sức mình chắt lót được bao nhiêu thì để dành tại nhà mình, hầu cho khỏi đợi khi tôi đến rồi mới góp."));
visuperobject.biblemap.put("b46_16_3", new visuperobject(46,16,3,"Khi tôi đến, tôi sẽ sai những kẻ mà anh em đã chọn cầm thơ tôi đi, đặng đem tiền bố thí của anh em đến thành Giê-ru-sa-lem."));
visuperobject.biblemap.put("b46_16_4", new visuperobject(46,16,4,"Ví bằng việc đáng chính mình tôi phải đi, thì những kẻ ấy sẽ đi với tôi."));
visuperobject.biblemap.put("b46_16_5", new visuperobject(46,16,5,"Vậy, tôi sẽ đến cùng anh em sau khi ghé qua xứ Ma-xê-đoan, vì tôi phải ghé qua xứ Ma-xê-đoan."));
visuperobject.biblemap.put("b46_16_6", new visuperobject(46,16,6,"Có lẽ tôi trú lại nơi anh em, hoặc cũng ở trọn mùa đông tại đó nữa, để anh em đưa tôi đến nơi tôi muốn đi."));
visuperobject.biblemap.put("b46_16_7", new visuperobject(46,16,7,"Lần nầy tôi chẳng muốn chỉ gặp anh em trong khi ghé qua mà thôi; nếu Chúa cho phép, thì tôi rất mong ở cùng anh em ít lâu."));
visuperobject.biblemap.put("b46_16_8", new visuperobject(46,16,8,"Nhưng tôi sẽ ở lại thành Ê-phê-sô cho đến lễ Ngũ Tuần,"));
visuperobject.biblemap.put("b46_16_9", new visuperobject(46,16,9,"vì tại đó có một cái cửa lớn mở toang ra cho công việc tôi, lại có nhiều kẻ đối địch."));
visuperobject.biblemap.put("b46_16_10", new visuperobject(46,16,10,"Nếu Ti-mô-thê đến thăm anh em, hãy giữ cho người khói sợ sệt gì trong anh em: vì người cũng làm việc cho Chúa như chính mình tôi vậy."));
visuperobject.biblemap.put("b46_16_11", new visuperobject(46,16,11,"Nên chớ có ai khinh người, hãy đưa người đi về bình an, hầu cho người đến cùng tôi, vì tôi đương đợi người đồng đến với anh em."));
visuperobject.biblemap.put("b46_16_12", new visuperobject(46,16,12,"Còn như anh em chúng ta là A-bô-lô tôi thường cố khuyên người đi với anh em đây mà đến cùng các anh em, nhưng hiện nay người chắc chưa khứng đi; người sẽ đi trong khi có dịp tiện."));
visuperobject.biblemap.put("b46_16_13", new visuperobject(46,16,13,"Anh em hãy tỉnh thức, hãy vững vàng trong đức tin, hãy dốc chí trượng phu và mạnh mẽ."));
visuperobject.biblemap.put("b46_16_14", new visuperobject(46,16,14,"Mọi điều anh em làm, hãy lấy lòng yêu thương mà làm."));
visuperobject.biblemap.put("b46_16_15", new visuperobject(46,16,15,"Hỡi anh em, còn một lời dặn nữa: anh em biết rằng nhà Sê-pha-na là trái đầu mùa của xứ A-chai, và biết rằng nhà ấy hết lòng hầu việc các thánh đồ."));
visuperobject.biblemap.put("b46_16_16", new visuperobject(46,16,16,"Vậy, hãy kính phục những người thể ấy, và kính phục cả mọi người cùng làm việc, cùng khó nhọc với chúng ta."));
visuperobject.biblemap.put("b46_16_17", new visuperobject(46,16,17,"Sê-pha-na, Phốt-tu-na và A-chai-cơ đến đây, tôi lấy làm vui mừng lắm; các người ấy đã bù lại sự anh em thiếu thốn,"));
visuperobject.biblemap.put("b46_16_18", new visuperobject(46,16,18,"vì các người ấy đã làm cho yên lặng tâm thần của tôi và của anh em. Hãy biết quí trọng những người dường ấy."));
visuperobject.biblemap.put("b46_16_19", new visuperobject(46,16,19,"Các Hội thánh ở xứ A-si chào thăm anh em. A-qui-la và Bê-rít-sin gởi lời chào anh em trong Chúa, Hội thánh hiệp trong nhà hai người ấy cũng vậy."));
visuperobject.biblemap.put("b46_16_20", new visuperobject(46,16,20,"Hết thảy anh em đây chào thăm các anh em. Hãy lấy cái hôn thánh mà chào nhau."));
visuperobject.biblemap.put("b46_16_21", new visuperobject(46,16,21,"Tôi là Phao-lô, chính tay tôi viết chào thăm anh em."));
visuperobject.biblemap.put("b46_16_22", new visuperobject(46,16,22,"Bằng có ai không kính mến Chúa, thì phải bị a-na-them! Ma-ra-na-tha."));
visuperobject.biblemap.put("b46_16_23", new visuperobject(46,16,23,"Nguyền xin ơn của Ðức Chúa Jêsus Christ ở với anh em!"));
visuperobject.biblemap.put("b46_16_24", new visuperobject(46,16,24,"Lòng yêu thương của tôi ở với hết thảy anh em trong Ðức Chúa Jêsus Christ."));

}

}