package vi.bible;

public class vibible45 {

public vibible45() {

putmapbible45();

}

private void putmapbible45() {

visuperobject.biblemap.put("b45_1_1", new visuperobject(45,1,1,"Phao-lô, tôi tớ Ðức Chúa Trời, được gọi làm sứ đồ, để riêng ra đặng giảng Tin Lành Ðức Chúa Trời,"));
visuperobject.biblemap.put("b45_1_2", new visuperobject(45,1,2,"là Tin Lành xưa kia Ðức Chúa Trời đã dùng các đấng tiên tri Ngài mà hứa trong Kinh Thánh,"));
visuperobject.biblemap.put("b45_1_3", new visuperobject(45,1,3,"về Con Ngài, theo xác thịt thì bởi dòng dõi vua Ða-vít sanh ra,"));
visuperobject.biblemap.put("b45_1_4", new visuperobject(45,1,4,"theo thần linh của thánh đức, thì bởi sự sống lại của Ngài từ trong kẻ chết, được tỏ ra là Con Ðức Chúa Trời có quyền phép, tức là Ðức Chúa Jêsus Christ, Chúa chúng ta,"));
visuperobject.biblemap.put("b45_1_5", new visuperobject(45,1,5,"nhờ Ngài chúng ta đã nhận lãnh ân điển và chức sứ đồ, để đem mọi dân ngoại đến sự vâng phục của đức tin, vì danh Ngài,"));
visuperobject.biblemap.put("b45_1_6", new visuperobject(45,1,6,"trong các dân ấy anh em cũng đã được gọi bởi Ðức Chúa Jêsus Christ;"));
visuperobject.biblemap.put("b45_1_7", new visuperobject(45,1,7,"gởi cho hết thảy những người yêu dấu của Ðức Chúa Trời tại thành Rô-ma, được gọi làm thánh đồ. Nguyền cho anh em được ân điển và sự bình an từ nơi Ðức Chúa Trời, Cha chúng ta, và từ nơi Ðức Chúa Jêsus Christ!"));
visuperobject.biblemap.put("b45_1_8", new visuperobject(45,1,8,"Trước hết, tôi nhờ Ðức Chúa Jêsus Christ, vì hết thảy anh em mà tạ ơn Ðức Chúa Trời tôi về đức tin anh em đã đồn khắp cả thế gian."));
visuperobject.biblemap.put("b45_1_9", new visuperobject(45,1,9,"Vì Ðức Chúa Trời mà tôi lấy tâm thần hầu việc, bởi sự giảng Tin Lành của Con Ngài, làm chứng cho tôi rằng tôi nhắc đến anh em không thôi"));
visuperobject.biblemap.put("b45_1_10", new visuperobject(45,1,10,"trong mọi khi tôi cầu nguyện thường xin Ðức Chúa Trời, bởi ý muốn Ngài, sau lại có thể gặp dịp tiện đi đến nơi anh em."));
visuperobject.biblemap.put("b45_1_11", new visuperobject(45,1,11,"Thật vậy, tôi rất mong mỏi đến thăm anh em, đặng thông đồng sự ban cho thiêng liêng cùng anh em, hầu cho anh em được vững vàng,"));
visuperobject.biblemap.put("b45_1_12", new visuperobject(45,1,12,"tức là tôi ở giữa anh em, để chúng ta cùng nhau giục lòng mạnh mẽ bởi đức tin chung của chúng ta, nghĩa là của anh em và của tôi."));
visuperobject.biblemap.put("b45_1_13", new visuperobject(45,1,13,"Vả, hỡi anh em, tôi chẳng muốn anh em không biết rằng đã ghe phen tôi toan đi thăm anh em, đặng hái trái trong anh em cũng như trong dân ngoại khác; song về sự đó tôi bị ngăn trở cho đến bây giờ."));
visuperobject.biblemap.put("b45_1_14", new visuperobject(45,1,14,"Tôi mắc nợ cả người Gờ-réc lẫn người giã man, cả người thông thái lẫn người ngu dốt."));
visuperobject.biblemap.put("b45_1_15", new visuperobject(45,1,15,"Ấy vậy, hễ thuộc về tôi, thì tôi cũng sẵn lòng rao Tin Lành cho anh em, là người ở thành Rô-ma."));
visuperobject.biblemap.put("b45_1_16", new visuperobject(45,1,16,"Thật vậy, tôi không hổ thẹn về Tin Lành đâu, vì là quyền phép của Ðức Chúa Trời để cứu mọi kẻ tin, trước là người Giu-đa, sau là người Gờ-réc;"));
visuperobject.biblemap.put("b45_1_17", new visuperobject(45,1,17,"vì trong Tin Lành nầy có bày tỏ sự công bình của Ðức Chúa Trời, bởi đức tin mà được, lại dẫn đến đức tin nữa, như có chép rằng: Người công bình sẽ sống bởi đức tin."));
visuperobject.biblemap.put("b45_1_18", new visuperobject(45,1,18,"Vả, cơn giận của Ðức Chúa Trời từ trên trời tỏ ra nghịch cùng mọi sự không tin kính và mọi sự không công bình của những người dùng sự không công bình mà bắt hiếp lẽ thật."));
visuperobject.biblemap.put("b45_1_19", new visuperobject(45,1,19,"Vì điều chi có thể biết được về Ðức Chúa Trời thì đã trình bày ra cho họ, Ðức Chúa Trời đã tỏ điều đó cho họ rồi,"));
visuperobject.biblemap.put("b45_1_20", new visuperobject(45,1,20,"bởi những sự trọn lành của Ngài mắt không thấy được, tức là quyền phép đời đời và bổn tánh Ngài, thì từ buổi sáng thế vẫn sờ sờ như mắt xem thấy, khi người ta xem xét công việc của Ngài. Cho nên họ không thể chữa mình được,"));
visuperobject.biblemap.put("b45_1_21", new visuperobject(45,1,21,"vì họ dẫu biết Ðức Chúa Trời, mà không làm sáng danh Ngài là Ðức Chúa Trời, và không tạ ơn Ngài nữa; song cứ lầm lạc trong lý tưởng hư không, và lòng ngu dốt đầy những sự tối tăm."));
visuperobject.biblemap.put("b45_1_22", new visuperobject(45,1,22,"Họ tự xưng mình là khôn ngoan, mà trở nên điên dại;"));
visuperobject.biblemap.put("b45_1_23", new visuperobject(45,1,23,"họ đã đổi vinh hiển của Ðức Chúa Trời không hề hư nát lấy hình tượng của loài người hay hư nát, hoặc của điểu, thú, côn trùng."));
visuperobject.biblemap.put("b45_1_24", new visuperobject(45,1,24,"Cho nên Ðức Chúa Trời đã phó họ sa vào sự ô uế theo lòng ham muốn mình, đến nỗi tự làm nhục thân thể mình nữa,"));
visuperobject.biblemap.put("b45_1_25", new visuperobject(45,1,25,"vì họ đã đổi lẽ thật Ðức Chúa Trời lấy sự dối trá, kính thờ và hầu việc loài chịu dựng nên thế cho Ðấng dựng nên, là Ðấng đáng khen ngợi đời đời! A-men."));
visuperobject.biblemap.put("b45_1_26", new visuperobject(45,1,26,"Ấy vì cớ đó mà Ðức Chúa Trời đã phó họ cho sự tình dục xấu hổ; vì trong vòng họ, những người đờn bà đã đổi cách dùng tự nhiên ra cách khác nghịch với tánh tự nhiên."));
visuperobject.biblemap.put("b45_1_27", new visuperobject(45,1,27,"Những người đờn ông cũng vậy, bỏ cách dùng tự nhiên của người đờn bà mà un đốt tình dục người nầy với kẻ kia, đờn ông cùng đờn ông phạm sự xấu hổ, và chính mình họ phải chịu báo ứng xứng với điều lầm lỗi của mình."));
visuperobject.biblemap.put("b45_1_28", new visuperobject(45,1,28,"Tại họ không lo nhìn biết Ðức Chúa Trời, nên Ðức Chúa Trời đã phó họ theo lòng hư xấu, đặng phạm những sự chẳng xứng đáng."));
visuperobject.biblemap.put("b45_1_29", new visuperobject(45,1,29,"Họ đầy dẫy mọi sự không công bình, độc ác, tham lam, hung dữ; chan chứa những điều ghen ghét, giết người, cãi lẫy, dối trá, giận dữ;"));
visuperobject.biblemap.put("b45_1_30", new visuperobject(45,1,30,"hay mách, gièm chê, chẳng tin kính, xấc xược, kiêu ngạo, khoe khoang, khôn khéo về sự làm dữ, không vâng lời cha mẹ;"));
visuperobject.biblemap.put("b45_1_31", new visuperobject(45,1,31,"dại dột, trái lời giao ước, không có tình nghĩa tự nhiên, không có lòng thương xót."));
visuperobject.biblemap.put("b45_1_32", new visuperobject(45,1,32,"Dầu họ biết mạng lịnh Ðức Chúa Trời tỏ ra những người phạm các tội dường ấy là đáng chết, thế mà chẳng những họ tự làm thôi đâu, lại còn ưng thuận cho kẻ khác phạm các điều ấy nữa."));
visuperobject.biblemap.put("b45_2_1", new visuperobject(45,2,1,"Vậy hỡi người kia, ngươi là ai mặc lòng, hễ đoán xét kẻ khác thì không thể chữa mình được; vì trong khi đoán xét họ, ngươi cũng lên án cho chính mình ngươi nữa, bởi ngươi đoán xét họ, mà cũng làm các việc như họ."));
visuperobject.biblemap.put("b45_2_2", new visuperobject(45,2,2,"Vả, Chúng ta biết rằng sự phán xét của Ðức Chúa Trời đối với kẻ làm những việc như thế, là hiệp với lẽ thật."));
visuperobject.biblemap.put("b45_2_3", new visuperobject(45,2,3,"Hỡi người đoán xét kẻ phạm những việc dường ấy mà mình cũng phạm kia, vậy ngươi tưởng rằng chính mình ngươi sẽ tránh khỏi sự phán xét của Ðức Chúa Trời sao?"));
visuperobject.biblemap.put("b45_2_4", new visuperobject(45,2,4,"Hay là ngươi khinh dể sự dư dật của lòng nhơn từ, nhịn nhục, khoan dung Ngài, mà không nhận biết lòng nhơn từ của Ðức Chúa Trời đem ngươi đến sự ăn năn sao?"));
visuperobject.biblemap.put("b45_2_5", new visuperobject(45,2,5,"Bởi lòng ngươi cứng cỏi, không ăn năn, thì tự chấp chứa cho mình sự giận về ngày thạnh nộ, khi sẽ hiện ra sự phán xét công bình của Ðức Chúa Trời,"));
visuperobject.biblemap.put("b45_2_6", new visuperobject(45,2,6,"là Ðấng sẽ trả lại cho mỗi người tùy theo công việc họ làm:"));
visuperobject.biblemap.put("b45_2_7", new visuperobject(45,2,7,"ai bền lòng làm lành, tìm sự vinh hiển, sự tôn trọng và sự chẳng hề chết, thì báo cho sự sống đời đời;"));
visuperobject.biblemap.put("b45_2_8", new visuperobject(45,2,8,"còn ai có lòng chống trả không vâng phục lẽ thật, mà vâng phục sự không công bình, thì báo cho họ sự giận và cơn thạnh nộ."));
visuperobject.biblemap.put("b45_2_9", new visuperobject(45,2,9,"Sự hoạn nạn khốn khó giáng cho mọi người làm ác, trước cho người Giu-đa, sau cho người Gờ-réc;"));
visuperobject.biblemap.put("b45_2_10", new visuperobject(45,2,10,"nhưng vinh hiển, tôn trọng, cùng sự bình an cho mọi người làm lành, trước cho người Giu-đa, sau cho người Gờ-réc."));
visuperobject.biblemap.put("b45_2_11", new visuperobject(45,2,11,"Vì trước mặt Ðức Chúa Trời, chẳng vị nể ai đâu."));
visuperobject.biblemap.put("b45_2_12", new visuperobject(45,2,12,"Phàm những kẻ không luật pháp mà phạm tội, cũng sẽ không luật pháp mà hư mất; còn những kẻ có luật pháp mà phạm tội, thì sẽ bị luật pháp đoán xét;"));
visuperobject.biblemap.put("b45_2_13", new visuperobject(45,2,13,"Vì chẳng phải kẻ nghe đọc luật pháp là người công bình trước mặt Ðức Chúa Trời, bèn là kẻ làm theo luật pháp được xưng công bình vậy."));
visuperobject.biblemap.put("b45_2_14", new visuperobject(45,2,14,"Vả, dân ngoại vốn không có luật pháp, khi họ tự nhiên làm những việc luật pháp dạy biểu, thì những người ấy dầu không có luật pháp, cũng tự nên luật pháp cho mình."));
visuperobject.biblemap.put("b45_2_15", new visuperobject(45,2,15,"Họ tỏ ra rằng việc mà luật pháp dạy biểu đã ghi trong lòng họ: chính lương tâm mình làm chứng cho luật pháp, còn ý tưởng mình khi thì cáo giác mình, khi thì binh vực mình."));
visuperobject.biblemap.put("b45_2_16", new visuperobject(45,2,16,"Ấy là điều sẽ hiện ra trong ngày Ðức Chúa Trời bởi Ðức Chúa Jêsus Christ mà xét đoán những việc kín nhiệm của loài người, y theo Tin Lành tôi."));
visuperobject.biblemap.put("b45_2_17", new visuperobject(45,2,17,"Còn ngươi, mang lấy danh người Giu-đa, yên nghỉ trên luật pháp, khoe mình về Ðức Chúa Trời ngươi,"));
visuperobject.biblemap.put("b45_2_18", new visuperobject(45,2,18,"hiểu ý muốn Ngài và biết phân biệt phải trái, vì ngươi đã được luật pháp dạy;"));
visuperobject.biblemap.put("b45_2_19", new visuperobject(45,2,19,"khoe mình làm người dẫn đường cho kẻ mù, làm sự sáng cho kẻ ở nơi tối tăm,"));
visuperobject.biblemap.put("b45_2_20", new visuperobject(45,2,20,"làm thầy kẻ ngu, làm người dạy kẻ tầm thường, trong luật pháp có mẫu mực của sự thông biết và của lẽ thật,"));
visuperobject.biblemap.put("b45_2_21", new visuperobject(45,2,21,"vậy ngươi dạy dỗ kẻ khác mà không dạy dỗ chính mình ngươi sao! Ngươi giảng rằng chớ nên ăn cắp, mà ngươi ăn cắp!"));
visuperobject.biblemap.put("b45_2_22", new visuperobject(45,2,22,"Ngươi nói rằng chớ nên phạm tội tà dâm, mà ngươi phạm tội tà dâm! Ngươi gớm ghét hình tượng mà cướp lấy đồ vật của hình tượng!"));
visuperobject.biblemap.put("b45_2_23", new visuperobject(45,2,23,"Ngươi khoe mình về luật pháp mà bởi luật pháp làm nhục đến Ðức Chúa Trời!"));
visuperobject.biblemap.put("b45_2_24", new visuperobject(45,2,24,"Vì bởi cớ các ngươi nên danh Ðức Chúa Trời bị nói phạm trong vòng người ngoại, như lời đã chép."));
visuperobject.biblemap.put("b45_2_25", new visuperobject(45,2,25,"Thật thế, nếu ngươi làm theo luật pháp, thì phép cắt bì có ích; còn nếu ngươi phạm luật pháp, thì dầu chịu cắt bì cũng như không."));
visuperobject.biblemap.put("b45_2_26", new visuperobject(45,2,26,"Vậy nếu kẻ chưa chịu cắt bì giữ các điều răn của luật pháp thì sự chưa chịu cắt bì đó há chẳng cầm như đã chịu sao?"));
visuperobject.biblemap.put("b45_2_27", new visuperobject(45,2,27,"Kẻ vốn không chịu cắt bì, mà làm trọn luật pháp sẽ đoán xét ngươi, là kẻ dẫu có chữ của luật pháp và phép cắt bì, lại phạm luật pháp."));
visuperobject.biblemap.put("b45_2_28", new visuperobject(45,2,28,"Vì người nào chỉ bề ngoài là người Giu-đa, thì không phải là người Giu-đa, còn phép cắt bì làm về xác thịt ở ngoài, thì không phải là phép cắt bì;"));
visuperobject.biblemap.put("b45_2_29", new visuperobject(45,2,29,"nhưng bề trong là người Giu-đa mới là người Giu-đa, phép cắt bì bởi trong lòng, làm theo cách thiêng liêng, không theo chữ nghĩa, mới là phép cắt bì thật. Một người Giu-đa như vậy được khen ngợi, chẳng phải bởi loài người, bèn là bởi Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_3_1", new visuperobject(45,3,1,"Vậy thì, sự trổi hơn của người Giu-đa là thể nào, hay là phép cắt bì có ích gì chăng?"));
visuperobject.biblemap.put("b45_3_2", new visuperobject(45,3,2,"Ích lớn đủ mọi đàng. Trước hết là điều nầy: ấy là lời phán của Ðức Chúa Trời đã phó cho dân Giu-đa."));
visuperobject.biblemap.put("b45_3_3", new visuperobject(45,3,3,"Mà làm sao! nếu một vài người trong bọn họ không thành tín, thì sự không thành tín của họ có làm cho sự thành tín của Ðức Chúa Trời ra hư không sao?"));
visuperobject.biblemap.put("b45_3_4", new visuperobject(45,3,4,"chẳng hề như vậy! Thà xưng Ðức Chúa Trời là thật và loài người là giả dối, như có chép rằng: Ấy vậy Chúa sẽ được xưng công bình trong lời phán của Ngài, Và sẽ được thắng khi chịu xét đoán."));
visuperobject.biblemap.put("b45_3_5", new visuperobject(45,3,5,"Song nếu sự không công bình của chúng ta tỏ ra sự công bình của Ðức Chúa Trời, thì sẽ nói làm sao? Khi Ðức Chúa Trời giáng cơn giận thì Ngài không công bình sao? (Tôi nói như cách người ta nói)."));
visuperobject.biblemap.put("b45_3_6", new visuperobject(45,3,6,"Chẳng hề như vậy! Nếu vậy thì Ðức Chúa Trời đoán xét thế gian thể nào?"));
visuperobject.biblemap.put("b45_3_7", new visuperobject(45,3,7,"Nhưng, nếu lẽ thật Ðức Chúa Trời bởi sự nói dối của tôi mà được sự vinh hiển lớn hơn, thì sao tôi còn bị đoán xét như kẻ có tội?"));
visuperobject.biblemap.put("b45_3_8", new visuperobject(45,3,8,"vậy thì, sao chúng ta không làm sự dữ cho được sự lành, như kẻ gièm pha đã cáo và quyết rằng chúng ta dạy điều ấy? Sự đoán phạt những người đó là công bình."));
visuperobject.biblemap.put("b45_3_9", new visuperobject(45,3,9,"Thế nào! Chúng ta có điều gì hơn chăng? Chẳng có, vì chúng ta đã tỏ ra rằng người Giu-đa và người Gờ-réc thảy đều phục dưới quyền tội lỗi,"));
visuperobject.biblemap.put("b45_3_10", new visuperobject(45,3,10,"như có chép rằng: Chẳng có một người công bình nào hết, dẫu một người cũng không."));
visuperobject.biblemap.put("b45_3_11", new visuperobject(45,3,11,"Chẳng có một người nào hiểu biết, Chẳng có một người nào tìm kiếm Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_3_12", new visuperobject(45,3,12,"Chúng nó đều sai lạc cả, thảy cùng nhau ra vô ích; Chẳng có một người làm điều lành, dẫu một người cũng không."));
visuperobject.biblemap.put("b45_3_13", new visuperobject(45,3,13,"Họng chúng nó như huyệt mả mở ra; Dùng lưỡi mình để phỉnh gạt; Dưới môi chúng nó có nọc rắn hổ mang."));
visuperobject.biblemap.put("b45_3_14", new visuperobject(45,3,14,"Miệng chúng nó đầy những lời nguyền rủa và cay đắng."));
visuperobject.biblemap.put("b45_3_15", new visuperobject(45,3,15,"Chúng nó có chơn nhẹ nhàng đặng làm cho đổ máu."));
visuperobject.biblemap.put("b45_3_16", new visuperobject(45,3,16,"Trên đường lối chúng nó rặc những sự tàn hại và khổ nạn,"));
visuperobject.biblemap.put("b45_3_17", new visuperobject(45,3,17,"Chúng nó chẳng hề biết con đường bình an."));
visuperobject.biblemap.put("b45_3_18", new visuperobject(45,3,18,"Chẳng có sự kính sợ Ðức Chúa Trời ở trước mặt chúng nó."));
visuperobject.biblemap.put("b45_3_19", new visuperobject(45,3,19,"Vả, chúng ta biết rằng những điều mà luật pháp nói, là nói cho mọi kẻ ở dưới luật pháp, hầu cho miệng nào cũng phải ngậm lại, cả thiên hạ đều nhận tội trước mặt Ðức Chúa Trời;"));
visuperobject.biblemap.put("b45_3_20", new visuperobject(45,3,20,"vì chẳng có một người nào bởi việc làm theo luật pháp mà sẽ được xưng công bình trước mặt Ngài, vì luật pháp cho người ta biết tội lỗi."));
visuperobject.biblemap.put("b45_3_21", new visuperobject(45,3,21,"Nhưng hiện bây giờ, sự công bình của Ðức Chúa Trời, mà luật pháp và các đấng tiên tri đều làm chứng cho, đã bày tỏ ra ngoài luật pháp;"));
visuperobject.biblemap.put("b45_3_22", new visuperobject(45,3,22,"tức là sự công bình của Ðức Chúa Trời, bởi sự tin đến Ðức Chúa Jêsus Christ, cho mọi người nào tin, chẳng có phân biệt chi hết,"));
visuperobject.biblemap.put("b45_3_23", new visuperobject(45,3,23,"vì mọi người đều đã phạm tội, thiếu mất sự vinh hiển của Ðức Chúa Trời,"));
visuperobject.biblemap.put("b45_3_24", new visuperobject(45,3,24,"và họ nhờ ân điển Ngài mà được xưng công bình nhưng không, bởi sự chuộc tội đã làm trọn trong Ðức Chúa Jêsus Christ,"));
visuperobject.biblemap.put("b45_3_25", new visuperobject(45,3,25,"là Ðấng Ðức Chúa Trời đã lập làm của lễ chuộc tội, bởi đức tin trong huyết Ðấng ấy. Ngài đã bày tỏ sự công bình mình như vậy, vì đã bỏ qua các tội phạm trước kia,"));
visuperobject.biblemap.put("b45_3_26", new visuperobject(45,3,26,"trong buổi Ngài nhịn nhục; tức là Ngài đã tỏ ra sự công bình Ngài trong thời hiện tại, tỏ ra mình là công bình và xưng công bình kẻ nào tin đến Ðức Chúa Jêsus."));
visuperobject.biblemap.put("b45_3_27", new visuperobject(45,3,27,"Vậy thì sự khoe mình ở đâu? Ðã bị trừ bỏ rồi. Bởi luật pháp nào? Luật pháp của việc làm chăng? Không phải, nhưng bởi luật pháp của đức tin;"));
visuperobject.biblemap.put("b45_3_28", new visuperobject(45,3,28,"vì chúng ta kể rằng người ta được xưng công bình bởi đức tin, chớ không bởi việc làm theo luật pháp."));
visuperobject.biblemap.put("b45_3_29", new visuperobject(45,3,29,"Hay là, Ðức Chúa Trời chỉ là Ðức Chúa Trời của dân Giu-đa sao? Há chẳng phải cũng là Ðức Chúa Trời của dân ngoại ư? Phải, Ngài cũng là của dân ngoại nữa;"));
visuperobject.biblemap.put("b45_3_30", new visuperobject(45,3,30,"Vì chỉ có một Ðức Chúa Trời, là Ðấng làm cho kẻ chịu cắt bì được xưng công bình bởi đức tin, cũng làm cho kẻ không chịu cắt bì được xưng công bình bởi đức tin nữa."));
visuperobject.biblemap.put("b45_3_31", new visuperobject(45,3,31,"Vậy, chúng ta nhơn đức tin mà bỏ luật pháp hay sao? Chẳng hề như vậy! Trái lại, chúng ta làm vững bền luật pháp."));
visuperobject.biblemap.put("b45_4_1", new visuperobject(45,4,1,"Vậy, chúng ta sẽ nói Áp-ra-ham, tổ phụ chúng ta, theo xác thịt đã được ích gì?"));
visuperobject.biblemap.put("b45_4_2", new visuperobject(45,4,2,"Thật thế nếu Áp-ra-ham đã được xưng công bình bởi việc làm, thì có cớ khoe mình; nhưng trước mặt Ðức Chúa Trời không có như vậy."));
visuperobject.biblemap.put("b45_4_3", new visuperobject(45,4,3,"Vì Kinh Thánh có dạy chi? Áp-ra-ham tin Ðức Chúa Trời, và điều đó kể là công bình cho người."));
visuperobject.biblemap.put("b45_4_4", new visuperobject(45,4,4,"Vả, đối với kẻ nào làm việc, thì tiền công không kể là ơn, nhưng kể như là nợ,"));
visuperobject.biblemap.put("b45_4_5", new visuperobject(45,4,5,"còn kẻ chẳng làm việc chi hết, nhưng tin Ðấng xưng người có tội là công bình, thì đức tin của kẻ ấy kể là công bình cho mình."));
visuperobject.biblemap.put("b45_4_6", new visuperobject(45,4,6,"Ấy vậy, vua Ða-vít cũng tỏ ra cái phước của người mà Ðức Chúa Trời kể cho là công bình chẳng bởi việc làm, mà rằng:"));
visuperobject.biblemap.put("b45_4_7", new visuperobject(45,4,7,"Phước thay cho kẻ, lỗi mình được tha thứ, Tội mình được che đậy!"));
visuperobject.biblemap.put("b45_4_8", new visuperobject(45,4,8,"Phước thay cho người mà Chúa chẳng kể tội lỗi cho!"));
visuperobject.biblemap.put("b45_4_9", new visuperobject(45,4,9,"Vậy, lời luận về phước đó chỉ chuyên về kẻ chịu cắt bì mà thôi sao? Cũng cho kẻ không chịu cắt bì nữa. Vả, chúng ta nói rằng đức tin của Áp-ra-ham được kể là công bình cho người."));
visuperobject.biblemap.put("b45_4_10", new visuperobject(45,4,10,"Nhưng được kể thế nào? Khi người đã chịu cắt bì rồi, hay là khi người chưa chịu cắt bì? Ấy không phải sau khi người chịu cắt bì, bèn là trước."));
visuperobject.biblemap.put("b45_4_11", new visuperobject(45,4,11,"Vậy, người đã nhận lấy dấu cắt bì, như dấu ấn của sự công bình mà người đã được bởi đức tin, khi chưa chịu cắt bì; hầu cho làm cha hết thảy những kẻ tin mà không chịu cắt bì, đặng họ được kể là công bình,"));
visuperobject.biblemap.put("b45_4_12", new visuperobject(45,4,12,"và cũng làm cha những kẻ chịu cắt bì, tức là cha những kẻ không những chịu cắt bì thôi, lại cũng noi theo dấu đức tin mà Áp-ra-ham, tổ phụ chúng ta, đã có trước khi chưa chịu cắt bì vậy."));
visuperobject.biblemap.put("b45_4_13", new visuperobject(45,4,13,"Vả, ấy chẳng phải bởi luật pháp mà có lời hứa cho Áp-ra-ham hoặc dòng dõi người lấy thế gian làm gia nghiệp, bèn là bởi sự công bình của đức tin."));
visuperobject.biblemap.put("b45_4_14", new visuperobject(45,4,14,"Vì, nếu bởi luật pháp mà được hưởng gia nghiệp, thì đức tin ra vô ích, lời hứa cũng bỏ rồi,"));
visuperobject.biblemap.put("b45_4_15", new visuperobject(45,4,15,"vì luật pháp sanh ra sự giận; song đâu không có luật pháp, thì đó cũng không có sự phạm luật pháp."));
visuperobject.biblemap.put("b45_4_16", new visuperobject(45,4,16,"Vậy nên, bởi đức tin mà người ta trở nên kẻ ăn gia tài, hầu cho sự ấy được bởi ân điển, và cho lời hứa được chắc chắn cho cả dòng dõi Áp-ra-ham, chẳng những cho dòng dõi dưới quyền luật pháp, mà cũng cho dòng dõi có đức tin của Áp-ra-ham, là tổ phụ hết thảy chúng ta,"));
visuperobject.biblemap.put("b45_4_17", new visuperobject(45,4,17,"y như lời chép rằng: Ta đã lập ngươi làm cha nhiều dân tộc, thật người là cha chúng ta trước mặt Ðức Chúa Trời, tức là Ðấng người đã tin, là Ðấng ban sự sống cho kẻ chết, gọi những sự không có như có rồi."));
visuperobject.biblemap.put("b45_4_18", new visuperobject(45,4,18,"Người cậy trông khi chẳng còn lẽ trông cậy, cứ tin, và trở nên cha của nhiều dân tộc, theo lời đã phán cho người rằng: Dòng dõi ngươi sẽ như thể ấy."));
visuperobject.biblemap.put("b45_4_19", new visuperobject(45,4,19,"Người thấy thân thể mình hao mòn, vì đã gần đầy trăm tuổi, và thấy Sa-ra không thể sanh đẻ được nữa, song đức tin chẳng kém."));
visuperobject.biblemap.put("b45_4_20", new visuperobject(45,4,20,"Người chẳng có lưỡng lự hoặc hoài nghi về lời hứa Ðức Chúa Trời, nhưng càng mạnh mẽ trong đức tin, và ngợi khen Ðức Chúa Trời,"));
visuperobject.biblemap.put("b45_4_21", new visuperobject(45,4,21,"vì tin chắc rằng điều chi Ðức Chúa Trời đã hứa, Ngài cũng có quyền làm trọn được."));
visuperobject.biblemap.put("b45_4_22", new visuperobject(45,4,22,"Cho nên đức tin của người được kể cho là công bình."));
visuperobject.biblemap.put("b45_4_23", new visuperobject(45,4,23,"Vả, ấy chẳng phải chỉ vì một mình người mà có chép rằng đức tin người đã được kể cho là công bình,"));
visuperobject.biblemap.put("b45_4_24", new visuperobject(45,4,24,"nhưng cũng vì chúng ta nữa, đức tin sự được kể là công bình cho chúng ta, là kẻ tin Ðấng đã làm cho Ðức Chúa Jêsus, Chúa chúng ta, sống lại từ trong kẻ chết,"));
visuperobject.biblemap.put("b45_4_25", new visuperobject(45,4,25,"Ngài đã bị nộp vì tội lỗi chúng ta, và sống lại vì sự xưng công bình của chúng ta."));
visuperobject.biblemap.put("b45_5_1", new visuperobject(45,5,1,"Vậy chúng ta đã được xưng công bình bởi đức tin, thì được hòa thuận với Ðức Chúa Trời, bởi Ðức Chúa Jêsus Christ chúng ta,"));
visuperobject.biblemap.put("b45_5_2", new visuperobject(45,5,2,"là Ðấng đã làm cho chúng ta cậy đức tin vào trong ơn nầy là ơn chúng ta hiện đương đứng vững; và chúng ta khoe mình trong sự trông cậy về vinh hiển Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_5_3", new visuperobject(45,5,3,"Nào những thế thôi, nhưng chúng ta cũng khoe mình trong hoạn nạn nữa, vì biết rằng hoạn nạn sanh sự nhịn nhục,"));
visuperobject.biblemap.put("b45_5_4", new visuperobject(45,5,4,"sự nhịn nhục sanh sự rèn tập, sự rèn tập sanh sự trông cậy."));
visuperobject.biblemap.put("b45_5_5", new visuperobject(45,5,5,"Vả, sự trông cậy không làm cho hổ thẹn, vì sự yêu thương của Ðức Chúa Trời rải khắp trong lòng chúng ta bởi Ðức Thánh Linh đã được ban cho chúng ta."));
visuperobject.biblemap.put("b45_5_6", new visuperobject(45,5,6,"Thật vậy, khi chúng ta còn yếu đuối, Ðấng Christ đã theo kỳ hẹn chịu chết vì kẻ có tội."));
visuperobject.biblemap.put("b45_5_7", new visuperobject(45,5,7,"Vả, họa mới có kẻ chịu chết vì người nghĩa; dễ thường cũng có kẻ bằng lòng chết vì người lành."));
visuperobject.biblemap.put("b45_5_8", new visuperobject(45,5,8,"Nhưng Ðức Chúa Trời tỏ lòng yêu thương Ngài đối với chúng ta, khi chúng ta còn là người có tội, thì Ðấng Christ vì chúng ta chịu chết."));
visuperobject.biblemap.put("b45_5_9", new visuperobject(45,5,9,"Huống chi nay chúng ta nhờ huyết Ngài được xưng công bình, thì sẽ nhờ Ngài được cứu khỏi cơn thạnh nộ là dường nào!"));
visuperobject.biblemap.put("b45_5_10", new visuperobject(45,5,10,"Vì nếu khi chúng ta còn là thù nghịch cùng Ðức Chúa Trời, mà đã được hòa thuận với Ngài bởi sự chết của Con Ngài, thì huống chi nay đã hòa thuận rồi, chúng ta sẽ nhờ sự sống của Con ấy mà được cứu là dường nào!"));
visuperobject.biblemap.put("b45_5_11", new visuperobject(45,5,11,"Nào những thế thôi, chúng ta lại còn khoe mình trong Ðức Chúa Trời bởi Ðức Chúa Jêsus Christ chúng ta, nhờ Ngài mà chúng ta hiện nay đã được sự hòa thuận."));
visuperobject.biblemap.put("b45_5_12", new visuperobject(45,5,12,"Cho nên, như bởi một người mà tội lỗi vào trong thế gian, lại bởi tội lỗi mà có sự chết, thì sự chết đã trải qua trên hết thảy mọi người như vậy, vì mọi người đều phạm tội."));
visuperobject.biblemap.put("b45_5_13", new visuperobject(45,5,13,"Vì, trước khi chưa có luật pháp, tội lỗi đã có trong thế gian, song chưa có luật pháp, thì cũng không kể là tội lỗi."));
visuperobject.biblemap.put("b45_5_14", new visuperobject(45,5,14,"Nhưng từ A-đam cho đến Môi-se, sự chết đã cai trị cả đến những kẻ chẳng phạm tội giống như tội của A-đam, là người làm hình bóng của Ðấng phải đến."));
visuperobject.biblemap.put("b45_5_15", new visuperobject(45,5,15,"Song tội lỗi chẳng phải như sự ban cho của ân điển. Vì nếu bởi tội lỗi của chỉ một người mà mọi kẻ khác đều phải chết, thì huống chi ơn của Ðức Chúa Trời và sự ban cho trong ơn Ngài tỏ ra bởi một người là Ðức Chúa Jêsus Christ, chan chứa cho hết thảy mọi người khác là dường nào!"));
visuperobject.biblemap.put("b45_5_16", new visuperobject(45,5,16,"Lại sự ban cho nầy chẳng phải như việc xảy đến bởi một người phạm tội đâu: sự phán xét bởi chỉ một tội mà làm nên đoán phạt; nhưng sự ban cho của ân điển thì sau nhiều tội rồi, dẫn đến sự xưng công bình."));
visuperobject.biblemap.put("b45_5_17", new visuperobject(45,5,17,"Vả, nếu bởi tội một người mà sự chết đã cai trị bởi một người ấy, thì huống chi những kẻ nhận ân điển và sự ban cho của sự công bình cách dư dật, họ sẽ nhờ một mình Ðức Chúa Jêsus Christ mà cai trị trong sự sống là dường nào!"));
visuperobject.biblemap.put("b45_5_18", new visuperobject(45,5,18,"Vậy, như bởi chỉ một tội mà sự đoán phạt rải khắp hết thảy mọi người thể nào, thì bởi chỉ một việc công bình mà sự xưng công bình, là sự ban sự sống, cũng rải khắp cho mọi người thể ấy."));
visuperobject.biblemap.put("b45_5_19", new visuperobject(45,5,19,"Vì, như bởi sự không vâng phục của một người mà mọi người khác đều thành ra kẻ có tội, thì cũng một lẽ ấy, bởi sự vâng phục của một người mà mọi người khác sẽ đều thành ra công bình."));
visuperobject.biblemap.put("b45_5_20", new visuperobject(45,5,20,"Vả, luật pháp đã xen vào, hầu cho tội lỗi gia thêm; nhưng nơi nào tội lỗi đã gia thêm, thì ân điển lại càng dư dật hơn nữa,"));
visuperobject.biblemap.put("b45_5_21", new visuperobject(45,5,21,"hầu cho tội lỗi đã cai trị làm nên sự chết thể nào, thì ân điển cũng cai trị bởi sự công bình thể ấy, đặng ban cho sự sống đời đời bởi Ðức Chúa Jêsus Christ, là Chúa chúng ta."));
visuperobject.biblemap.put("b45_6_1", new visuperobject(45,6,1,"Vậy chúng ta sẽ nói làm sao? Chúng ta phải cứ ở trong tội lỗi, hầu cho ân điển được dư dật chăng?"));
visuperobject.biblemap.put("b45_6_2", new visuperobject(45,6,2,"Chẳng hề như vậy! Chúng ta đã chết về tội lỗi, lẽ nào còn sống trong tội lỗi nữa?"));
visuperobject.biblemap.put("b45_6_3", new visuperobject(45,6,3,"Hay là, anh em chẳng biết rằng chúng ta thảy đều đã chịu phép báp tem trong Ðức Chúa Jêsus Christ, tức là chịu phép báp tem trong sự chết Ngài sao?"));
visuperobject.biblemap.put("b45_6_4", new visuperobject(45,6,4,"Vậy chúng ta đã bị chôn với Ngài bởi phép báp tem trong sự chết Ngài, hầu cho Ðấng Christ nhờ vinh hiển của Cha được từ kẻ chết sống lại thể nào, thì chúng ta cũng sống trong đời mới thể ấy."));
visuperobject.biblemap.put("b45_6_5", new visuperobject(45,6,5,"Vì nếu chúng ta làm một cùng Ngài bởi sự chết giống như sự chết của Ngài, thì chúng ta cũng sẽ làm một cùng Ngài bởi sự sống lại giống nhau:"));
visuperobject.biblemap.put("b45_6_6", new visuperobject(45,6,6,"vì biết rõ rằng người cũ của chúng ta đã bị đóng đinh trên thập tự giá với Ngài, hầu cho thân thể của tội lỗi bị tiêu diệt đi, và chúng ta không phục dưới tội lỗi nữa."));
visuperobject.biblemap.put("b45_6_7", new visuperobject(45,6,7,"Vì ai đã chết thì được thoát khỏi tội lỗi."));
visuperobject.biblemap.put("b45_6_8", new visuperobject(45,6,8,"Vả, nếu chúng ta đã cùng chết với Ðấng Christ, thì chúng ta tin rằng mình cũng sẽ sống lại với Ngài,"));
visuperobject.biblemap.put("b45_6_9", new visuperobject(45,6,9,"bởi biết rằng Ðấng Christ đã từ kẻ chết sống lại, thì chẳng chết nữa; sự chết không còn cai trị trên Ngài."));
visuperobject.biblemap.put("b45_6_10", new visuperobject(45,6,10,"Vì nếu Ngài đã chết, ấy là chết cho tội lỗi một lần đủ cả; nhưng hiện nay Ngài sống, ấy là sống cho Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_6_11", new visuperobject(45,6,11,"Vậy anh em cũng hãy coi mình như chết về tội lỗi và như sống cho Ðức Chúa Trời trong Ðức Chúa Jêsus Christ."));
visuperobject.biblemap.put("b45_6_12", new visuperobject(45,6,12,"Vậy, chớ để tội lỗi cai trị trong xác hay chết của anh em, và chớ chiều theo tư dục nó."));
visuperobject.biblemap.put("b45_6_13", new visuperobject(45,6,13,"Chớ nộp chi thể mình cho tội lỗi, như là đồ dùng gian ác, nhưng hãy phó chính mình anh em cho Ðức Chúa Trời, dường như đã chết mà nay trở nên sống, và dâng chi thể mình cho Ðức Chúa Trời như là đồ dùng về sự công bình."));
visuperobject.biblemap.put("b45_6_14", new visuperobject(45,6,14,"Vì tội lỗi không cai trị trên anh em đâu; bởi anh em chẳng thuộc dưới luật pháp, mà thuộc dưới ân điển."));
visuperobject.biblemap.put("b45_6_15", new visuperobject(45,6,15,"Vậy thì làm sao! Vì chúng ta không thuộc dưới luật pháp, nhưng thuộc dưới ân điển, thì chúng ta sẽ phạm tội hay sao? Chẳng hề như vậy!"));
visuperobject.biblemap.put("b45_6_16", new visuperobject(45,6,16,"Anh em há chẳng biết rằng nếu anh em đã nộp mình làm tôi mọi đặng vâng phục kẻ nào, thì là tôi mọi của kẻ mình vâng phục, hoặc của tội lỗi đến sự chết, hoặc của sự vâng phục để được nên công bình hay sao?"));
visuperobject.biblemap.put("b45_6_17", new visuperobject(45,6,17,"Nhưng, tạ ơn Ðức Chúa Trời, vì sau khi anh em làm tôi mọi tội lỗi, thì đã từ lòng vâng phục đạo lý là sự đã ban làm mực thước cho mình!"));
visuperobject.biblemap.put("b45_6_18", new visuperobject(45,6,18,"Vậy, anh em đã được buông tha khỏi tội lỗi, trở nên tôi mọi của sự công bình rồi."));
visuperobject.biblemap.put("b45_6_19", new visuperobject(45,6,19,"Tôi nói theo cách loài người, vì xác thịt của anh em là yếu đuối. Vậy, anh em từng đặt chi thể mình làm tôi sự ô uế gian ác đặng làm tội ác thể nào, thì bây giờ, hãy đặt chi thể mình làm tôi sự công bình đặng làm nên thánh cũng thể ấy."));
visuperobject.biblemap.put("b45_6_20", new visuperobject(45,6,20,"Vả, khi anh em còn làm tôi mọi tội lỗi, thì đối với sự công bình anh em được tự do."));
visuperobject.biblemap.put("b45_6_21", new visuperobject(45,6,21,"Thế thì anh em đã được kết quả gì? Ấy là quả mà anh em hiện nay đương hổ thẹn; vì sự cuối cùng của những điều đó tứ là sự chết."));
visuperobject.biblemap.put("b45_6_22", new visuperobject(45,6,22,"Nhưng bây giờ đã được buông tha khỏi tội lỗi và trở nên tôi mọi của Ðức Chúa Trời rồi, thì anh em được lấy sự nên thánh làm kết quả, và sự sống đời đời làm cuối cùng."));
visuperobject.biblemap.put("b45_6_23", new visuperobject(45,6,23,"Vì tiền công của tội lỗi là sự chết; nhưng sự ban cho của Ðức Chúa Trời là sự sống đời đời trong Ðức Chúa Jêsus Christ, Chúa chúng ta."));
visuperobject.biblemap.put("b45_7_1", new visuperobject(45,7,1,"Hỡi anh em (vì tôi nói với những kẻ biết luật pháp), vậy anh em há chẳng biết rằng luật pháp chỉ cai trị người ta khi còn sống hay sao?"));
visuperobject.biblemap.put("b45_7_2", new visuperobject(45,7,2,"Cho nên, đờn bà có chồng, hễ chồng còn sống bao lâu, thì luật pháp buộc phải theo chồng bấy lâu; nhưng nếu chồng chết, thì người vợ được thoát khỏi luật pháp đã buộc mình với chồng."));
visuperobject.biblemap.put("b45_7_3", new visuperobject(45,7,3,"Vậy nếu đương lúc chồng còn sống, mà vợ đi lấy người khác, thì phải bị kêu là đờn bà ngoại tình; nhưng nếu chồng chết, thì vợ được buông tha khỏi luật pháp, dầu lấy người khác cũng chẳng phải là đờn bà ngoại tình vậy."));
visuperobject.biblemap.put("b45_7_4", new visuperobject(45,7,4,"Hỡi anh em ta, anh em cũng như vậy, bởi thân thể của Ðấng Christ, anh em đã chết về luật pháp, đặng thuộc về người khác, tức là người đã từ kẻ chết sống lại, hầu cho chúng ta được kết quả cho Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_7_5", new visuperobject(45,7,5,"Vì khi chúng ta còn sống theo xác thịt, thì các tình dục xấu xa bị luật pháp xui khiến, hành động trong chi thể chúng ta và kết quả cho sự chết."));
visuperobject.biblemap.put("b45_7_6", new visuperobject(45,7,6,"Nhưng bây giờ chúng ta đã chết về luật pháp, là điều bắt buộc mình, thì được buông tha khỏi luật pháp đặng hầu việc Ðức Chúa Trời theo cách mới của Thánh Linh, chớ không theo cách cũ của văn tự."));
visuperobject.biblemap.put("b45_7_7", new visuperobject(45,7,7,"Vậy chúng ta sẽ nói làm sao? Luật pháp há là tội lỗi sao? Chẳng hề như vậy! Nhưng tôi chỉ bởi luật pháp mà biết tội lỗi; vì nếu luật pháp không nói: Người chớ tham lam, thì tôi đã không biết sự tham lam."));
visuperobject.biblemap.put("b45_7_8", new visuperobject(45,7,8,"Ấy là tội lỗi đã nhơn dịp, bởi điều răn mà sanh ra mọi thứ ham muốn trong lòng tôi: vì không có luật pháp thì tội lỗi chết đi."));
visuperobject.biblemap.put("b45_7_9", new visuperobject(45,7,9,"Ngày xưa tôi không có luật pháp mà tôi sống; như khi điều răn đến, thì tội lỗi lại sống,"));
visuperobject.biblemap.put("b45_7_10", new visuperobject(45,7,10,"còn tôi thì chết; vậy thì té ra điều răn vốn nên làm cho tôi sống, đã dắt tôi đến sự chết."));
visuperobject.biblemap.put("b45_7_11", new visuperobject(45,7,11,"Vì tội lỗi đã nhơn dịp, dùng điều răn dỗ dành tôi và nhơn đó làm cho tôi chết."));
visuperobject.biblemap.put("b45_7_12", new visuperobject(45,7,12,"Ấy vậy, luật pháp là thánh, điều răn cũng là thánh, công bình và tốt lành."));
visuperobject.biblemap.put("b45_7_13", new visuperobject(45,7,13,"Vậy thì điều lành trở làm cớ cho tôi chết sao? Chẳng hề như vậy! Nhưng ấy là tội lỗi đã làm cho tôi chết, hầu khi nó nhơn điều lành làm chết tôi, tự bày ra nói là tội lỗi; đến nỗi tội lỗi nhơn điều răn trở nên cực ác."));
visuperobject.biblemap.put("b45_7_14", new visuperobject(45,7,14,"Vả, chúng ta biết luật pháp là thiêng liêng; nhưng tôi là tánh xác thịt đã bị bán cho tội lỗi."));
visuperobject.biblemap.put("b45_7_15", new visuperobject(45,7,15,"Vì tôi không hiểu điều mình làm: tôi chẳng làm điều mình muốn, nhưng làm điều mình ghét."));
visuperobject.biblemap.put("b45_7_16", new visuperobject(45,7,16,"Song nếu tôi làm điều mình chẳng muốn, thì bởi đó nhận biết luật pháp là tốt lành."));
visuperobject.biblemap.put("b45_7_17", new visuperobject(45,7,17,"Bấy giờ chẳng phải tôi làm điều đó nữa, nhưng ấy là tội lỗi ở trong tôi."));
visuperobject.biblemap.put("b45_7_18", new visuperobject(45,7,18,"Vả, tôi biết điều lành chẳng ở trong tôi đâu, nghĩa là trong xác thịt tôi, bởi tôi có ý muốn làm điều lành, nhưng không có quyền làm trọn;"));
visuperobject.biblemap.put("b45_7_19", new visuperobject(45,7,19,"vì tôi không làm điều lành mình muốn, nhưng làm điều dữ mình không muốn."));
visuperobject.biblemap.put("b45_7_20", new visuperobject(45,7,20,"Ví bằng tôi làm điều mình không muốn, ấy chẳng phải là tôi làm điều đó nữa, nhưng là tội lỗi ở trong tôi vậy."));
visuperobject.biblemap.put("b45_7_21", new visuperobject(45,7,21,"Vậy tôi thấy có luật nầy trong tôi: khi tôi muốn làm điều lành, thì điều dữ dính dấp theo tôi."));
visuperobject.biblemap.put("b45_7_22", new visuperobject(45,7,22,"Vì theo người bề trong, tôi vẫn lấy luật pháp Ðức Chúa Trời làm đẹp lòng;"));
visuperobject.biblemap.put("b45_7_23", new visuperobject(45,7,23,"nhưng tôi cảm biết trong chi thể mình có một luật khác giao chiến với luật trong trí mình, bắt mình phải làm phu tù cho luật của tội lỗi, tức là luật ở trong chi thể tôi vậy."));
visuperobject.biblemap.put("b45_7_24", new visuperobject(45,7,24,"Khốn nạn cho tôi! Ai sẽ cứu tôi thoát khỏi thân thể hay chết nầy?"));
visuperobject.biblemap.put("b45_7_25", new visuperobject(45,7,25,"Cảm tạ Ðức Chúa Trời, nhờ Ðức Chúa Jêsus Christ, là Chúa chúng ta! Như vậy, thì chính mình tôi lấy trí khôn phục luật pháp của Ðức Chúa Trời, nhưng lấy xác thịt phục luật pháp của tội lỗi."));
visuperobject.biblemap.put("b45_8_1", new visuperobject(45,8,1,"Cho nên hiện nay chẳng còn có sự đoán phạt nào cho những kẻ ở trong Ðức Chúa Jêsus Christ;"));
visuperobject.biblemap.put("b45_8_2", new visuperobject(45,8,2,"vì luật pháp của Thánh Linh sự sống đã nhờ Ðức Chúa Jêsus Christ buông tha tôi khỏi luật pháp của sự tội và sự chết."));
visuperobject.biblemap.put("b45_8_3", new visuperobject(45,8,3,"Vì điều chi luật pháp không làm nổi, tại xác thịt làm cho luật pháp ra yếu đuối, thì Ðức Chúa Trời đã làm rồi: Ngài đã vì cớ tội lỗi sai chính Con mình lấy xác thịt giống như xác thịt tội lỗi chúng ta, và đã đoán phạt tội lỗi trong xác thịt,"));
visuperobject.biblemap.put("b45_8_4", new visuperobject(45,8,4,"hầu cho sự công bình mà luật pháp buộc phải làm được trọn trong chúng ta, là kẻ chẳng noi theo xác thịt, nhưng noi theo Thánh Linh."));
visuperobject.biblemap.put("b45_8_5", new visuperobject(45,8,5,"Thật thế, kẻ sống theo xác thịt thì chăm những sự thuộc về xác thịt; còn kẻ sống theo Thánh Linh thì chăm những sự thuộc về Thánh Linh."));
visuperobject.biblemap.put("b45_8_6", new visuperobject(45,8,6,"Vả, chăm về xác thịt sanh ra sự chết, còn chăm về Thánh Linh sanh ra sự sống và bình an;"));
visuperobject.biblemap.put("b45_8_7", new visuperobject(45,8,7,"vì sự chăm về xác thịt nghịch với Ðức Chúa Trời, bởi nó không phục dưới luật pháp Ðức Chúa Trời, lại cũng không thể phục được."));
visuperobject.biblemap.put("b45_8_8", new visuperobject(45,8,8,"Vả, những kẻ sống theo xác thịt, thì không thể đẹp lòng Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_8_9", new visuperobject(45,8,9,"Về phần anh em, nếu thật quả Thánh Linh Ðức Chúa Trời ở trong mình, thì không sống theo xác thịt đâu, nhưng theo Thánh Linh; song nếu ai không có Thánh Linh của Ðấng Christ, thì người ấy chẳng thuộc về Ngài."));
visuperobject.biblemap.put("b45_8_10", new visuperobject(45,8,10,"Vậy nếu Ðấng Christ ở trong anh em, thì thân thể chết nhơn cớ tội lỗi, mà thần linh sống nhơn cớ sự công bình."));
visuperobject.biblemap.put("b45_8_11", new visuperobject(45,8,11,"Lại nếu Thánh Linh của Ðấng làm cho Ðức Chúa Jêsus sống lại từ trong kẻ chết ở trong anh em, thì Ðấng làm cho Ðức Chúa Jêsus Christ sống lại từ trong kẻ chết cũng sẽ nhờ Thánh Linh Ngài ở trong anh em mà khiến thân thể hay chết của anh em lại sống."));
visuperobject.biblemap.put("b45_8_12", new visuperobject(45,8,12,"Vậy, hỡi anh em, chúng ta chẳng mắc nợ xác thịt đâu, đặng sống theo xác thịt."));
visuperobject.biblemap.put("b45_8_13", new visuperobject(45,8,13,"Thật thế, nếu anh em sống theo xác thịt thì phải chết; song nếu nhờ Thánh Linh, làm cho chết các việc của thân thể, thì anh em sẽ sống."));
visuperobject.biblemap.put("b45_8_14", new visuperobject(45,8,14,"Vì hết thảy kẻ nào được Thánh Linh của Ðức Chúa Trời dắt dẫn, đều là con của Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_8_15", new visuperobject(45,8,15,"Thật anh em đã chẳng nhận lấy thần trí của tôi mọi đặng còn ở trong sự sợ hãi; nhưng đã nhận lấy thần trí của sự làm con nuôi, và nhờ đó chúng ta kêu rằng: A-ba! Cha!"));
visuperobject.biblemap.put("b45_8_16", new visuperobject(45,8,16,"Chính Ðức Thánh Linh làm chứng cho lòng chúng ta rằng chúng ta là con cái Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_8_17", new visuperobject(45,8,17,"Lại nếu chúng ta là con cái, thì cũng là kẻ kế tự: kẻ kế tự Ðức Chúa Trời và là kẻ đồng kế tự với Ðấng Christ, miễn chúng ta đều chịu đau đớn với Ngài, hầu cho cũng được vinh hiển với Ngài."));
visuperobject.biblemap.put("b45_8_18", new visuperobject(45,8,18,"Vả, tôi tưởng rằng những sự đau đớn bây giờ chẳng đáng so sánh với sự vinh hiển hầu đến, là sự sẽ được bày ra trong chúng ta."));
visuperobject.biblemap.put("b45_8_19", new visuperobject(45,8,19,"Thật thế, muôn vật ước ao, nóng nảy mà trông đợi con cái Ðức Chúa Trời được tỏ ra."));
visuperobject.biblemap.put("b45_8_20", new visuperobject(45,8,20,"Vì muôn vật đã bị bắt phục sự hư không, chẳng phải tự ý mình, bèn là bởi cớ Ðấng bắt phục."));
visuperobject.biblemap.put("b45_8_21", new visuperobject(45,8,21,"Muôn vật mong rằng mình cũng sẽ được giải cứu khỏi làm tôi sự hư nát, đặng dự phần trong sự tự do vinh hiển của con cái Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_8_22", new visuperobject(45,8,22,"Vì chúng ta biết rằng muôn vật đều than thở và chịu khó nhọc cho đến ngày nay;"));
visuperobject.biblemap.put("b45_8_23", new visuperobject(45,8,23,"không những muôn vật thôi, lại chúng ta, là kẻ có trái đầu mùa của Ðức Thánh Linh, cũng than thở trong lòng đang khi trông đợi sự làm con nuôi, tức là sự cứu chuộc thân thể chúng ta vậy."));
visuperobject.biblemap.put("b45_8_24", new visuperobject(45,8,24,"Vì chúng ta được cứu trong sự trông cậy, nhưng khi người ta đã thấy điều mình trông cậy rồi, ấy không phải là trông nữa: mình thấy rồi, sao còn trông làm chi?"));
visuperobject.biblemap.put("b45_8_25", new visuperobject(45,8,25,"Song nếu chúng ta trông điều mình không thấy, ấy là chúng ta chờ đợi điều đó cách nhịn nhục."));
visuperobject.biblemap.put("b45_8_26", new visuperobject(45,8,26,"Cũng một lẽ ấy, Ðức Thánh Linh giúp cho sự yếu đuối chúng ta. Vì chúng ta chẳng biết sự mình phải xin đặng cầu nguyện cho xứng đáng; nhưng chính Ðức Thánh Linh lấy sự thở than không thể nói ra được mà cầu khẩn thay cho chúng ta."));
visuperobject.biblemap.put("b45_8_27", new visuperobject(45,8,27,"Ðấng dò xét lòng người hiểu biết ý tưởng của Thánh Linh là thể nào, vì ấy là theo ý Ðức Chúa Trời mà Ngài cầu thế cho các thánh đồ vậy."));
visuperobject.biblemap.put("b45_8_28", new visuperobject(45,8,28,"Vả, chúng ta biết rằng mọi sự hiệp lại làm ích cho kẻ yêu mến Ðức Chúa Trời, tức là cho kẻ được gọi theo ý muốn Ngài đã định."));
visuperobject.biblemap.put("b45_8_29", new visuperobject(45,8,29,"Vì Ngài cũng đã định sẵn để nên giống như hình bóng Con Ngài, hầu cho Con nầy được làm Con cả ở giữa nhiều anh em;"));
visuperobject.biblemap.put("b45_8_30", new visuperobject(45,8,30,"còn những kẻ Ngài đã định sẵn, thì Ngài cũng đã gọi, những kẻ Ngài đã gọi, thì Ngài cũng đã xưng là công bình, và những kẻ Ngài đã xưng là công bình, thì Ngài cũng đã làm cho vinh hiển."));
visuperobject.biblemap.put("b45_8_31", new visuperobject(45,8,31,"Ðã vậy thì chúng ta sẽ nói làm sao? Nếu Ðức Chúa Trời vùa giúp chúng ta, thì còn ai nghịch với chúng ta?"));
visuperobject.biblemap.put("b45_8_32", new visuperobject(45,8,32,"Ngài đã không tiếc chính Con mình, nhưng vì chúng ta hết thảy mà phó Con ấy cho, thì Ngài há chẳng cũng sẽ ban mọi sự luôn với Con ấy cho chúng ta sao?"));
visuperobject.biblemap.put("b45_8_33", new visuperobject(45,8,33,"Ai sẽ kiện kẻ lựa chọn của Ðức Chúa Trời: Ðức Chúa Trời là Ðấng xưng công bình những kẻ ấy."));
visuperobject.biblemap.put("b45_8_34", new visuperobject(45,8,34,"Ai sẽ lên án họ ư? Ðức Chúa Jêsus Christ là Ðấng đã chết, và cũng đã sống lại nữa. Ngài đang ngự bên hữu Ðức Chúa Trời, cầu nguyện thế cho chúng ta."));
visuperobject.biblemap.put("b45_8_35", new visuperobject(45,8,35,"Ai sẽ phân rẽ chúng ta khỏi sự yêu thương của Ðấng Christ? có phải hoạn nạn, khốn cùng, bắt bớ, đói khát, trần truồng, nguy hiểm, hay là gươm giáo chăng?"));
visuperobject.biblemap.put("b45_8_36", new visuperobject(45,8,36,"Như có chép rằng: Vì cớ Ngài, chúng tôi bị giết cả ngày; Họ coi chúng tôi như chiên định đem đến hàng làm thịt."));
visuperobject.biblemap.put("b45_8_37", new visuperobject(45,8,37,"Trái lại, trong mọi sự đó, chúng ta nhờ Ðấng yêu thương mình mà thắng hơn bội phần."));
visuperobject.biblemap.put("b45_8_38", new visuperobject(45,8,38,"Vì tôi chắc rằng bất kỳ sự chết, sự sống, các thiên sứ, các kẻ cầm quyền, việc bây giờ, việc hầu đến, quyền phép,"));
visuperobject.biblemap.put("b45_8_39", new visuperobject(45,8,39,"bề cao, hay là bề sâu, hoặc một vật nào, chẳng có thể phân rẽ chúng ta khỏi sự yêu thương mà Ðức Chúa Trời đã chứng cho chúng ta trong Ðức Chúa Jêsus Christ, là Chúa chúng ta."));
visuperobject.biblemap.put("b45_9_1", new visuperobject(45,9,1,"Tôi nói thật trong Ðấng Christ, tôi không nói dối, lương tâm tôi làm chứng cho tôi bởi Ðức Chúa Trời:"));
visuperobject.biblemap.put("b45_9_2", new visuperobject(45,9,2,"tôi buồn bực lắm, lòng tôi hằng đau đớn."));
visuperobject.biblemap.put("b45_9_3", new visuperobject(45,9,3,"Bởi tôi ước ao có thể chính mình bị dứt bỏ, lìa khỏi Ðấng Christ, vì anh em bà con tôi theo phần xác,"));
visuperobject.biblemap.put("b45_9_4", new visuperobject(45,9,4,"tức dân Y-sơ-ra-ên, là dân được những sự làm con nuôi, sự vinh hiển, lời giao ước, luật pháp, sự thờ phượng và lời hứa;"));
visuperobject.biblemap.put("b45_9_5", new visuperobject(45,9,5,"là dân sanh hạ bởi các tổ phụ, và theo phần xác, bởi dân ấy sanh ra Ðấng Christ, là Ðấng trên hết mọi sự, tức là Ðức Chúa Trời đáng ngợi khen đời đời. A-men."));
visuperobject.biblemap.put("b45_9_6", new visuperobject(45,9,6,"Ấy chẳng phải lời Ðức Chúa Trời là vô ích. Vì những kẻ bởi Y-sơ-ra-ên sanh hạ, chẳng phải vì đó mà hết thảy đều là người Y-sơ-ra-ên."));
visuperobject.biblemap.put("b45_9_7", new visuperobject(45,9,7,"cũng không phải vì là dòng dõi Áp-ra-ham thì hết thảy đều là con cái người; nhưng có chép rằng: Ấy là bởi Y-sác mà ngươi sẽ có một dòng dõi gọi theo tên ngươi;"));
visuperobject.biblemap.put("b45_9_8", new visuperobject(45,9,8,"nghĩa là chẳng phải con cái thuộc về xác thịt là con cái Ðức Chúa Trời, nhưng con cái thuộc về lời hứa thì được kể là dòng dõi Áp-ra-ham vậy."));
visuperobject.biblemap.put("b45_9_9", new visuperobject(45,9,9,"Vả, lời nầy thật là một lời hứa: Cũng kỳ nầy ta sẽ lại đến, Sa-ra sẽ có một con trai."));
visuperobject.biblemap.put("b45_9_10", new visuperobject(45,9,10,"Nào những thế thôi, về phần Rê-be-ca, khi bà ấy bởi tổ phụ chúng ta là Y-sác mà có thai đôi cũng vậy."));
visuperobject.biblemap.put("b45_9_11", new visuperobject(45,9,11,"Vì, khi hai con chưa sanh ra, chưa làm điều chi lành hay dữ hầu cho được giữ vững ý chỉ Ðức Chúa Trời, là ý định sẵn bởi sự kén chọn tự do của Ngài, chẳng cứ việc làm, nhưng cứ Ðấng kêu gọi"));
visuperobject.biblemap.put("b45_9_12", new visuperobject(45,9,12,"thì có lời phán cho mẹ của hai con rằng: Ðứa lớn sẽ làm tôi đứa nhỏ;"));
visuperobject.biblemap.put("b45_9_13", new visuperobject(45,9,13,"như có chép rằng: Ta yêu Gia-cốp và ghét Ê-sau."));
visuperobject.biblemap.put("b45_9_14", new visuperobject(45,9,14,"Vậy chúng ta sẽ nói làm sao? Có sự không công bình trong Ðức Chúa Trời sao? Chẳng hề như vậy!"));
visuperobject.biblemap.put("b45_9_15", new visuperobject(45,9,15,"Vì Ngài phán cùng Môi-se rằng: Ta sẽ làm ơn cho kẻ ta làm ơn, ta sẽ thương xót kẻ ta thương xót."));
visuperobject.biblemap.put("b45_9_16", new visuperobject(45,9,16,"Vậy điều đó chẳng phải bởi người nào ao ước hay người nào bôn ba mà được, bèn là bởi Ðức Chúa Trời thương xót."));
visuperobject.biblemap.put("b45_9_17", new visuperobject(45,9,17,"Trong Kinh Thánh cũng có phán cùng Pha-ra-ôn rằng: Nầy là cớ vì sao ta đã dấy ngươi lên, ấy là để tỏ quyền phép ta ra trong ngươi, hầu cho danh ta được truyền ra khắp đất."));
visuperobject.biblemap.put("b45_9_18", new visuperobject(45,9,18,"Như vậy, Ngài muốn thương xót ai thì thương xót, và muốn làm cứng lòng ai thì làm."));
visuperobject.biblemap.put("b45_9_19", new visuperobject(45,9,19,"Vậy thì người sẽ hỏi ta rằng: Sao Ngài còn quở trách? Vì có ai chống lại ý muốn Ngài được chăng?"));
visuperobject.biblemap.put("b45_9_20", new visuperobject(45,9,20,"Nhưng, hỡi người, ngươi là ai, mà dám cãi lại cùng Ðức Chúa Trời? Có lẽ nào cái bình bằng đất sét lại nói với kẻ nắn nên mình rằng: Sao ngươi đã làm nên ta như vậy?"));
visuperobject.biblemap.put("b45_9_21", new visuperobject(45,9,21,"Người thợ gốm há chẳng có quyền trên đất sét, cùng trong một đống mà làm ra hạng bình để dùng việc sang trọng, lại hạng bình khác để dùng việc hèn hạ sao?"));
visuperobject.biblemap.put("b45_9_22", new visuperobject(45,9,22,"Nếu Ðức Chúa Trời muốn tỏ ra cơn thạnh nộ và làm cho bởi thế quyền phép Ngài, đã lấy lòng khoan nhẫn lớn chịu những bình đáng giận sẵn cho sự hư mất,"));
visuperobject.biblemap.put("b45_9_23", new visuperobject(45,9,23,"để cũng làm cho biết sự giàu có của vinh hiển Ngài bởi những bình đáng thương xót mà Ngài đã định sẵn cho sự vinh hiển, thì còn nói chi được ư?"));
visuperobject.biblemap.put("b45_9_24", new visuperobject(45,9,24,"Ðó tôi nói về chúng ta, là kẻ Ngài đã gọi, chẳng những từ trong dân ngoại nữa."));
visuperobject.biblemap.put("b45_9_25", new visuperobject(45,9,25,"Như Ngài phán trong sách Ô-sê rằng: Ta sẽ gọi kẻ chẳng phải dân ta là dân ta, Kẻ chẳng được yêu dấu là yêu dấu;"));
visuperobject.biblemap.put("b45_9_26", new visuperobject(45,9,26,"Lại xảy ra trong nơi Ngài phán cùng họ rằng: Các ngươi chẳng phải là dân ta đâu, Cũng lại nơi đó họ sẽ được xưng là con của Ðức Chúa Trời hằng sống."));
visuperobject.biblemap.put("b45_9_27", new visuperobject(45,9,27,"Còn Ê-sai nói về dân Y-sơ-ra-ên mà kêu lên rằng: Dầu số con cái Y-sơ-ra-ên như cát dưới biển, chỉ một phần sót lại sẽ được cứu mà thôi;"));
visuperobject.biblemap.put("b45_9_28", new visuperobject(45,9,28,"vì Chúa sẽ làm ứng nghiệm lời Ngài cách trọn vẹn và vội vàng trên đất."));
visuperobject.biblemap.put("b45_9_29", new visuperobject(45,9,29,"Lại như Ê-sai đã nói tiên tri rằng: Nếu Chúa vạn quân chẳng để lại một cái mầm của dòng giống chúng ta, Thì chúng ta đã trở nên như thành Sô-đôm và giống như thành Gô-mô-rơ vậy."));
visuperobject.biblemap.put("b45_9_30", new visuperobject(45,9,30,"Vậy chúng ta sự nói làm sao? Những dân ngoại chẳng tìm sự công bình, thì đã được sự công bình, nhưng là sự công bình đến bởi Ðức Chúa Trời;"));
visuperobject.biblemap.put("b45_9_31", new visuperobject(45,9,31,"còn như dân Y-sơ-ra-ên tìm luật pháp của sự công bình, thì không đạt đến luật pháp ấy."));
visuperobject.biblemap.put("b45_9_32", new visuperobject(45,9,32,"Tại sao? Tại họ chẳng bởi đức tin mà tìm, nhưng bởi việc làm. Họ đã vấp phải hòn đá ngăn trở,"));
visuperobject.biblemap.put("b45_9_33", new visuperobject(45,9,33,"như có chép rằng: Nầy ta để tại Si-ôn một hòn đá ngăn trở, tức là hòn đá lớn làm cho vấp ngã; Hễ ai tin đến thì khỏi bị hổ thẹn."));
visuperobject.biblemap.put("b45_10_1", new visuperobject(45,10,1,"Hỡi anh em, sự ước ao trong lòng tôi và lời tôi vì dân Y-sơ-ra-ên cầu nguyện cùng Ðức Chúa Trời, ấy là cho họ được cứu."));
visuperobject.biblemap.put("b45_10_2", new visuperobject(45,10,2,"Vì tôi làm chứng cho họ rằng họ có lòng sốt sắng về Ðức Chúa Trời, nhưng lòng sốt sắng đó là không phải theo trí khôn."));
visuperobject.biblemap.put("b45_10_3", new visuperobject(45,10,3,"Bởi họ không nhận biết sự công bình của Ðức Chúa Trời và tìm cách lập sự công bình riêng của mình, nên không chịu phục sự công bình của Ðức Chúa Trời;"));
visuperobject.biblemap.put("b45_10_4", new visuperobject(45,10,4,"vì Ðấng Christ là sự cuối cùng của luật pháp, đặng xưng mọi kẻ tin là công bình."));
visuperobject.biblemap.put("b45_10_5", new visuperobject(45,10,5,"Vả, Môi-se luận sự công bình đến bởi luật pháp cách nầy: Hễ ai làm theo điều đó thì nhờ đó mà sống."));
visuperobject.biblemap.put("b45_10_6", new visuperobject(45,10,6,"Nhưng sự công bình đến bởi đức tin, thì nói như vầy: Chớ nói trong lòng ngươi rằng: Ai sẽ lên trời? ấy là để đem Ðấng Christ xuống;"));
visuperobject.biblemap.put("b45_10_7", new visuperobject(45,10,7,"hay là: Ai sẽ xuống vực sâu? ấy là để đem Ðấng Christ từ trong kẻ chết lại lên."));
visuperobject.biblemap.put("b45_10_8", new visuperobject(45,10,8,"Nhưng nói làm sao? Ðạo ở gần ngươi, ở trong miệng và trong lòng ngươi. Ấy là đạo đức tin và chúng ta giảng dạy."));
visuperobject.biblemap.put("b45_10_9", new visuperobject(45,10,9,"Vậy nếu miệng ngươi xưng Ðức Chúa Jêsus ra và lòng ngươi tin rằng Ðức Chúa Trời đã khiến Ngài từ kẻ chết sống lại, thì ngươi sẽ được cứu;"));
visuperobject.biblemap.put("b45_10_10", new visuperobject(45,10,10,"vì tin bởi trong lòng mà được sự công bình, còn bởi miệng làm chứng mà được sự cứu rỗi."));
visuperobject.biblemap.put("b45_10_11", new visuperobject(45,10,11,"Vả, Kinh-Thánh nói rằng: Kẻ nào tin Ngài sẽ chẳng bị hổ thẹn."));
visuperobject.biblemap.put("b45_10_12", new visuperobject(45,10,12,"Trong người Giu-đa và người Gờ-réc không có sự phân biệt gì hết, vì họ có chung một Chúa, giàu ơn đối với mọi kẻ kêu xin Ngài."));
visuperobject.biblemap.put("b45_10_13", new visuperobject(45,10,13,"Vì ai kêu cầu danh Chúa thì sẽ được cứu."));
visuperobject.biblemap.put("b45_10_14", new visuperobject(45,10,14,"Nhưng họ chưa tin Ngài thì kêu cầu sao được? Chưa nghe nói về Ngài thì làm thể nào mà tin? Nếu chẳng ai rao giảng, thì nghe làm sao?"));
visuperobject.biblemap.put("b45_10_15", new visuperobject(45,10,15,"Lại nếu chẳng ai được sai đi, thì rao giảng thể nào? như có chép rằng: Những bàn chơn kẻ rao truyền tin Lành là tốt đẹp biết bao!"));
visuperobject.biblemap.put("b45_10_16", new visuperobject(45,10,16,"Nhưng chẳng phải mọi người đều nghe theo tin lành đâu; vì Ê-sai có nói rằng: Lạy Chúa, ai tin lời chúng tôi rao giảng?"));
visuperobject.biblemap.put("b45_10_17", new visuperobject(45,10,17,"Như vậy, đức tin đến bởi sự người ta nghe, mà người ta nghe, là khi lời của Ðấng Christ được rao giảng."));
visuperobject.biblemap.put("b45_10_18", new visuperobject(45,10,18,"Nhưng tôi hỏi: Có phải là họ chưa nghe chăng? Trái lại, Tiếng của các sứ giả đã vang khắp đất, Và lời của sứ giả đã đạt đến cùng thế gian."));
visuperobject.biblemap.put("b45_10_19", new visuperobject(45,10,19,"Tôi lại hỏi: Thế mà dân Y-sơ-ra-ên chẳng biết chi hết sao? Môi-se đã nói rằng: Ta sẽ giục lòng ganh tị các ngươi bởi kẻ chẳng phải là dân; Ta sẽ chọc giận các ngươi bởi một dân ngu dốt."));
visuperobject.biblemap.put("b45_10_20", new visuperobject(45,10,20,"Lại Ê-sai nói cách bạo dạn rằng: Những kẻ chẳng tìm kiếm ta thì đã gặp thấy ta, Ta đã tỏ mình ra cho kẻ chẳng hỏi han ta."));
visuperobject.biblemap.put("b45_10_21", new visuperobject(45,10,21,"Song về dân Y-sơ-ra-ên, thì rằng: Ta đã giơ tay ra cả ngày hướng về dân bội nghịch và hay nói trái."));
visuperobject.biblemap.put("b45_11_1", new visuperobject(45,11,1,"Vậy tôi nói: Ðức Chúa Trời có bỏ dân Ngài chăng? Chẳng hề như vậy; vì chính tôi là dân Y-sơ-ra-ên, dòng dõi Áp-ra-ham, về chi phái Bên-gia-min."));
visuperobject.biblemap.put("b45_11_2", new visuperobject(45,11,2,"Ðức Chúa Trời chẳng từng bỏ dân Ngài đã biết trước. Anh em há chẳng biết Kinh Thánh chép về chuyện Ê-li sao? thể nào người kiện dân Y-sơ-ra-ên trước mặt Ðức Chúa Trời mà rằng:"));
visuperobject.biblemap.put("b45_11_3", new visuperobject(45,11,3,"Lạy Chúa, họ đã giết tiên tri Ngài, hủy phá bàn thờ Ngài; tôi còn lại một mình, và họ tìm giết tôi."));
visuperobject.biblemap.put("b45_11_4", new visuperobject(45,11,4,"Nhưng Ðức Chúa Trời đáp lại thể nào? Ta đã để dành cho ta bảy ngàn người nam chẳng hề quì gối trước mặt Ba-anh."));
visuperobject.biblemap.put("b45_11_5", new visuperobject(45,11,5,"Ngày nay cũng vậy, có một phần còn sót lại theo sự lựa chọn của ân điển."));
visuperobject.biblemap.put("b45_11_6", new visuperobject(45,11,6,"Nhưng nếu bởi ơn thì chẳng phải bởi việc làm nữa; bằng chẳng, thì ơn không còn phải là ơn."));
visuperobject.biblemap.put("b45_11_7", new visuperobject(45,11,7,"Vậy thì làm sao? Ấy là dân Y-sơ-ra-ên chẳng được điều mình tìm; song những kẻ lựa chọn thì đã được, và những kẻ khác thì bị cứng lòng,"));
visuperobject.biblemap.put("b45_11_8", new visuperobject(45,11,8,"như có chép rằng: Ðức Chúa Trời đã cho họ mờ tối, con mắt chẳng thấy, lỗ tai chẳng nghe, cho đến ngày nay."));
visuperobject.biblemap.put("b45_11_9", new visuperobject(45,11,9,"Lại, Ða vít có nói: Ước gì bàn tiệc của họ trở nên bẫy Lưới, nên dịp vấp chơn và sự phạt công bình cho họ;"));
visuperobject.biblemap.put("b45_11_10", new visuperobject(45,11,10,"Ước gì mắt họ mù không thấy được, Và lưng họ cứ khom luôn."));
visuperobject.biblemap.put("b45_11_11", new visuperobject(45,11,11,"Tôi lại hỏi rằng: Có phải dân Y-sơ-ra-ên vấp chơn dường ấy hầu cho té xuống chăng? Chẳng hề như vậy! Nhưng ấy là bởi tội lỗi họ mà sự cứu đã đến cho dân ngoại, hầu để giục lòng tranh đua của họ."));
visuperobject.biblemap.put("b45_11_12", new visuperobject(45,11,12,"Vả, nếu tội lỗi họ đã làm giàu cho thế gian, sự kém sút họ đã làm giàu cho dân ngoại, thì huống chi là sự thạnh vượng của họ!"));
visuperobject.biblemap.put("b45_11_13", new visuperobject(45,11,13,"Tôi nói cùng anh em là người ngoại: bấy lâu tôi làm sứ đồ cho dân ngoại, tôi làm vinh hiển chức vụ mình,"));
visuperobject.biblemap.put("b45_11_14", new visuperobject(45,11,14,"cố sức để giục lòng tranh đua của những kẻ đồng tộc tôi, và để cứu nấy người trong đám họ."));
visuperobject.biblemap.put("b45_11_15", new visuperobject(45,11,15,"Vì nếu sự dứt bỏ họ ra đã làm sự hòa thuận cho thiên hạ, thì sự họ trở lại trong ân điển há chẳng phải là sự sống lại từ trong kẻ chết sao?"));
visuperobject.biblemap.put("b45_11_16", new visuperobject(45,11,16,"Vả, nếu trái đầu mùa là thánh, thì cả đồng cũng thánh; và nếu rễ là thánh, thì các nhánh cũng thánh."));
visuperobject.biblemap.put("b45_11_17", new visuperobject(45,11,17,"Ví bằng có một hai nhánh bị cắt đi, và ngươi vốn là cây ô-li-ve hoang được tháp vào chỗ các nhánh ấy để có phần về nhựa và rễ của cây ô-li-ve,"));
visuperobject.biblemap.put("b45_11_18", new visuperobject(45,11,18,"thì chớ khoe mình hơn các nhánh đó. Nhưng nếu ngươi khoe mình, thì hãy biết rằng ấy chẳng phải là ngươi chịu đựng cái rễ, bèn là cái rễ chịu đựng ngươi."));
visuperobject.biblemap.put("b45_11_19", new visuperobject(45,11,19,"Ngươi sẽ nói rằng: Các nhánh đã bị cắt đi, để ta được tháp vào chỗ nó."));
visuperobject.biblemap.put("b45_11_20", new visuperobject(45,11,20,"Phải lắm; các nhánh đó đã bị cắt bởi cớ chẳng tin, và ngươi nhờ đức tin mà còn; chớ kiêu ngạo, hãy sợ hãi."));
visuperobject.biblemap.put("b45_11_21", new visuperobject(45,11,21,"Vì nếu Ðức Chúa Trời chẳng tiếc các nhánh nguyên, thì Ngài cũng chẳng tiếc ngươi nữa."));
visuperobject.biblemap.put("b45_11_22", new visuperobject(45,11,22,"Vậy hãy xem sự nhơn từ và sự nghiêm nhặt của Ðức Chúa Trời: sự nghiêm nhặt đối với họ là kẻ đã ngã xuống, còn sự nhơn từ đối với ngươi, miễn là ngươi cầm giữ mình trong sự nhơn từ Ngài: bằng chẳng, ngươi cũng sẽ bị chặt."));
visuperobject.biblemap.put("b45_11_23", new visuperobject(45,11,23,"Về phần họ, nếu không ghì mài trong sự chẳng tin, thì cũng sẽ được tháp; vì Ðức Chúa Trời có quyền lại tháp họ vào."));
visuperobject.biblemap.put("b45_11_24", new visuperobject(45,11,24,"Nếu chính ngươi đã bị cắt khỏi cây ô-li-ve hoang thuận tánh mình, mà được tháp vào cây ô-li-ve tốt nghịch tánh, thì huống chi những kẻ ấy là nhánh nguyên sẽ được tháp vào chính cây ô-li-ve mình!"));
visuperobject.biblemap.put("b45_11_25", new visuperobject(45,11,25,"Vả, hỡi anh em, tôi không muốn anh em chẳng biết sự mầu nhiệm nầy, e anh em khoe mình khôn ngoan chăng: ấy là một phần dân Y-sơ-ra-ên đã sa vào sự cứng lòng, cho đến chừng nào số dân ngoại nhập vào được đầy đủ;"));
visuperobject.biblemap.put("b45_11_26", new visuperobject(45,11,26,"vậy thì cả dân Y-sơ-ra-ên sẽ được cứu, như có chép rằng: Ðấng Giải cứu sẽ đến từ Si-ôn, Cất sự vô đạo ra khỏi Gia-cốp;"));
visuperobject.biblemap.put("b45_11_27", new visuperobject(45,11,27,"Ấy là sự giao ước mà ta sẽ lập với họ, Khi ta xóa tội lỗi họ rồi."));
visuperobject.biblemap.put("b45_11_28", new visuperobject(45,11,28,"Nếu luận về Tin Lành thì họ là nghịch thù bởi cớ anh em, còn luận về sự lựa chọn, thì họ được yêu thương bởi cớ các tổ phụ;"));
visuperobject.biblemap.put("b45_11_29", new visuperobject(45,11,29,"vì các sự ban cho và sự kêu gọi của Ðức Chúa Trời chẳng hề đổi lại được bao giờ."));
visuperobject.biblemap.put("b45_11_30", new visuperobject(45,11,30,"Lại như khi trước anh em đã nghịch cùng Ðức Chúa Trời, mà bây giờ được thương xót bởi sự nghịch của họ,"));
visuperobject.biblemap.put("b45_11_31", new visuperobject(45,11,31,"thì cũng một thể ấy, bây giờ họ đã nghịch, hầu cho cũng được thương xót bởi sự thương xót đã tỏ ra với anh em."));
visuperobject.biblemap.put("b45_11_32", new visuperobject(45,11,32,"Vì Ðức Chúa Trời đã nhốt mọi người trong sự bạn nghịch, đặng thương xót hết thảy."));
visuperobject.biblemap.put("b45_11_33", new visuperobject(45,11,33,"Ôi! sâu nhiệm thay là sự giàu có, khôn ngoan và thông biết của Ðức Chúa Trời! Sự phán xét của Ngài nào ai thấu được, đường nẻo của Ngài nào ai hiểu được!"));
visuperobject.biblemap.put("b45_11_34", new visuperobject(45,11,34,"Vì, ai biết ý tưởng Chúa, ai là kẻ bàn luận của Ngài?"));
visuperobject.biblemap.put("b45_11_35", new visuperobject(45,11,35,"Hay là ai đã cho Chúa trước, đặng nhận lấy điều gì Ngài báo lại?"));
visuperobject.biblemap.put("b45_11_36", new visuperobject(45,11,36,"Vì muôn vật đều là từ Ngài, và hướng về Ngài. Vinh hiển cho Ngài đời đời, vô cùng! A-men."));
visuperobject.biblemap.put("b45_12_1", new visuperobject(45,12,1,"Vậy, hỡi anh em, tôi lấy sự thương xót của Ðức Chúa Trời khuyên anh em dâng thân thể mình làm của lễ sống và thánh, đẹp lòng Ðức Chúa Trời, ấy là sự thờ phượng phải lẽ của anh em."));
visuperobject.biblemap.put("b45_12_2", new visuperobject(45,12,2,"Ðừng làm theo đời nầy, nhưng hãy biến hóa bởi sự đổi mới của tâm thần mình, để thử cho biết ý muốn tốt lành, đẹp lòng và trọn vẹn của Ðức Chúa Trời là thể nào."));
visuperobject.biblemap.put("b45_12_3", new visuperobject(45,12,3,"Vậy, nhờ ơn đã ban cho tôi, tôi nói với mỗi người trong anh em chớ có tư tưởng cao quá lẽ, nhưng phải có tâm tình tầm thường, y theo lượng đức tin mà Ðức Chúa Trời đã phú cho từng người."));
visuperobject.biblemap.put("b45_12_4", new visuperobject(45,12,4,"Vả, như trong một thân chúng ta có nhiều chi thể, và các chi thể không làm một việc giống nhau,"));
visuperobject.biblemap.put("b45_12_5", new visuperobject(45,12,5,"thì cũng vậy, chúng ta là nhiều người mà hiệp nên một thân trong Ðấng Christ, và hết thảy chúng ta đều là các phần chi thể của nhau."));
visuperobject.biblemap.put("b45_12_6", new visuperobject(45,12,6,"Vì chúng ta có các sự ban cho khác nhau, tùy theo ơn đã ban cho chúng ta, ai được ban cho nói tiên tri, hãy tập nói theo lượng đức tin;"));
visuperobject.biblemap.put("b45_12_7", new visuperobject(45,12,7,"ai được gọi đến làm chức vụ, hãy buộc mình vào chức vụ; ai dạy dỗ, hãy chăm mà dạy dỗ;"));
visuperobject.biblemap.put("b45_12_8", new visuperobject(45,12,8,"ai gánh việc khuyên bảo, hãy khuyên bảo; ai bố thí, hãy lấy lòng rộng rãi mà bố thí; ai cai trị, hãy siêng năng mà cai trị; ai làm sự thương xót, hãy lấy lòng vui mà làm."));
visuperobject.biblemap.put("b45_12_9", new visuperobject(45,12,9,"Lòng yêu thương phải cho thành thật. Hãy gớm sự dữ mà mến sự lành."));
visuperobject.biblemap.put("b45_12_10", new visuperobject(45,12,10,"Hãy lấy lòng yêu thương mềm mại mà yêu nhau như anh em; hãy lấy lẽ kính nhường nhau."));
visuperobject.biblemap.put("b45_12_11", new visuperobject(45,12,11,"Hãy siêng năng mà chớ làm biếng; phải có lòng sốt sắng; phải hầu việc Chúa."));
visuperobject.biblemap.put("b45_12_12", new visuperobject(45,12,12,"Hãy vui mừng trong sự trông cậy, nhịn nhục trong sự hoạn nạn, bền lòng mà cầu nguyện."));
visuperobject.biblemap.put("b45_12_13", new visuperobject(45,12,13,"Hãy cung cấp sự cần dùng cho các thánh đồ; hãy ân cần tiếp khách."));
visuperobject.biblemap.put("b45_12_14", new visuperobject(45,12,14,"Hãy chúc phước cho kẻ bắt bớ anh em; hãy chúc phước, chớ nguyền rủa."));
visuperobject.biblemap.put("b45_12_15", new visuperobject(45,12,15,"Hãy vui với kẻ vui, khóc với kẻ khóc."));
visuperobject.biblemap.put("b45_12_16", new visuperobject(45,12,16,"Trong vòng anh em phải ở cho hiệp ý nhau; đừng ước ao sự cao sang, nhưng phải ưa thích sự khiêm nhường. Chớ cho mình là khôn ngoan."));
visuperobject.biblemap.put("b45_12_17", new visuperobject(45,12,17,"Chớ lấy ác trả ác cho ai; phải chăm tìm điều thiện trước mặt mọi người."));
visuperobject.biblemap.put("b45_12_18", new visuperobject(45,12,18,"Nếu có thể được, thì hãy hết sức mình mà hòa thuận với mọi người."));
visuperobject.biblemap.put("b45_12_19", new visuperobject(45,12,19,"Hỡi kẻ rất yêu dấu của tôi ơi, chính mình chớ trả thù ai, nhưng hãy nhường cho cơn thạnh nộ của Ðức Chúa Trời; vì có chép lời Chúa phán rằng: Sự trả thù thuộc về ta, ta sẽ báo ứng."));
visuperobject.biblemap.put("b45_12_20", new visuperobject(45,12,20,"Vậy nếu kẻ thù mình có đói, hãy cho ăn; có khát, hãy cho uống; vì làm như vậy, khác nào mình lấy những than lửa đỏ mà chất trên đầu người."));
visuperobject.biblemap.put("b45_12_21", new visuperobject(45,12,21,"Ðừng để điều ác thắng mình, nhưng hãy lấy điều thiện thắng điều ác."));
visuperobject.biblemap.put("b45_13_1", new visuperobject(45,13,1,"Mọi người phải vâng phục các đấng cầm quyền trên mình; vì chẳng có quyền nào mà chẳng đến bởi Ðức Chúa Trời, các quyền đều bởi Ðức Chúa Trời chỉ định."));
visuperobject.biblemap.put("b45_13_2", new visuperobject(45,13,2,"Cho nên ai chống cự quyền phép, tức là đối địch với mạng lịnh Ðức Chúa Trời đã lập; và những kẻ đối địch thì chuốc lấy sự phán xét vào mình."));
visuperobject.biblemap.put("b45_13_3", new visuperobject(45,13,3,"Vả, các quan quyền không phải để cho người làm lành sợ, mà để cho người làm dữ sợ. Ngươi muốn không sợ quyền phép chăng? Hãy làm điều lành, sẽ được khen thưởng;"));
visuperobject.biblemap.put("b45_13_4", new visuperobject(45,13,4,"vì quan quyền là chức việc của Ðức Chúa Trời để làm ích cho ngươi. Song nếu ngươi làm ác, thì hãy sợ, vì người cầm gươm chẳng phải là vô cớ; người là chức việc của Ðức Chúa Trời để làm ra sự công bình và phạt kẻ làm dữ."));
visuperobject.biblemap.put("b45_13_5", new visuperobject(45,13,5,"Vậy nên cần phải vâng phục, chẳng những vì sợ hình phạt thôi, nhưng cũng vì cớ lương tâm."));
visuperobject.biblemap.put("b45_13_6", new visuperobject(45,13,6,"Ấy cũng bởi lẽ đó mà anh em nộp thuế, vì các quan quyền là đầy tớ của Ðức Chúa Trời, hằng giữ việc ấy."));
visuperobject.biblemap.put("b45_13_7", new visuperobject(45,13,7,"Phải trả cho mọi người điều mình đã mắc: nộp thuế cho kẻ mình phải nộp thuế; đóng góp cho kẻ mình phải đóng góp; sợ kẻ mình đáng sợ; kính kẻ mình đáng kính."));
visuperobject.biblemap.put("b45_13_8", new visuperobject(45,13,8,"Ðừng mắc nợ ai chi hết, chỉ mắc nợ về sự yêu thương nhau mà thôi, vì ai yêu kẻ lân cận mình, ấy là đã làm trọn luật pháp."));
visuperobject.biblemap.put("b45_13_9", new visuperobject(45,13,9,"Vả, những điều răn nầy: Ngươi chớ phạm tội tà dâm, chớ giết người, chớ trộm cướp, chớ tham lam, mà mọi điều răn khác nữa, bất luận điều nào, đều tóm lại trong một lời nầy: Ngươi phải yêu kẻ lân cận mình như mình."));
visuperobject.biblemap.put("b45_13_10", new visuperobject(45,13,10,"Sự yêu thương chẳng hề làm hại kẻ lân cận; vậy yêu thương là sự làm trọn luật pháp."));
visuperobject.biblemap.put("b45_13_11", new visuperobject(45,13,11,"Hãy ăn ở như vậy, vì biết thời kỳ đương lúc chúng ta đây: giờ anh em từ ngủ thức dậy đã đến, bởi sự cứu hiện nay đã gần chúng ta hơn lúc chúng ta mới tin."));
visuperobject.biblemap.put("b45_13_12", new visuperobject(45,13,12,"Ðêm đã khuya, ngày gần đến; vậy chúng ta hãy lột bỏ những việc tối tăm mà mặc lấy áo giáp sáng láng."));
visuperobject.biblemap.put("b45_13_13", new visuperobject(45,13,13,"Hãy bước đi cách hẳn hoi như giữa ban ngày. Chớ nộp mình vào sự quá độ và say sưa, buông tuồng và bậy bạ, rầy rà và ghen ghét;"));
visuperobject.biblemap.put("b45_13_14", new visuperobject(45,13,14,"nhưng hãy mặc lấy Ðức Chúa Jêsus Christ, chớ chăm nom về xác thịt mà làm cho phỉ lòng dục nó."));
visuperobject.biblemap.put("b45_14_1", new visuperobject(45,14,1,"Hãy bằng lòng tiếp lấy kẻ kém đức tin, chớ cãi lẫy về sự nghi ngờ."));
visuperobject.biblemap.put("b45_14_2", new visuperobject(45,14,2,"Người nầy tin có thể ăn được cả mọi thứ; người kia là kẻ yếu đuối, chỉ ăn rau mà thôi."));
visuperobject.biblemap.put("b45_14_3", new visuperobject(45,14,3,"Người ăn chớ khinh dể kẻ không ăn; và người không ăn chớ xét đoán kẻ ăn, vì Ðức Chúa Trời đã tiếp lấy người."));
visuperobject.biblemap.put("b45_14_4", new visuperobject(45,14,4,"Ngươi là ai mà dám xét đoán tôi tớ của kẻ khác? Nó đứng hay ngã, ấy là việc chủ nó; song nó sẽ đứng, vì Chúa có quyền cho nó đứng vững vàng."));
visuperobject.biblemap.put("b45_14_5", new visuperobject(45,14,5,"Người nầy tưởng ngày nầy hơn ngày khác, kẻ kia tưởng mọi ngày đều bằng nhau; ai nấy hãy tin chắc ở trí mình."));
visuperobject.biblemap.put("b45_14_6", new visuperobject(45,14,6,"Kẻ giữ ngày là giữ vì Chúa; kẻ ăn là ăn vì Chúa, vì họ tạ ơn Ðức Chúa Trời; kẻ chẳng ăn cũng chẳng ăn vì Chúa, họ cũng tạ ơn Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_14_7", new visuperobject(45,14,7,"Vả, chẳng có người nào trong chúng ta vì chính mình mà sống, cũng chẳng có người nào trong chúng ta vì chính mình mà chết;"));
visuperobject.biblemap.put("b45_14_8", new visuperobject(45,14,8,"vì nếu chúng ta sống, là sống cho Chúa, và nếu chúng ta chết, là chết cho Chúa. Vậy nên chúng ta hoặc sống hoặc chết, đều thuộc về Chúa cả."));
visuperobject.biblemap.put("b45_14_9", new visuperobject(45,14,9,"Ðấng Christ đã chết và sống lại, ấy là để làm Chúa kẻ chết và kẻ sống."));
visuperobject.biblemap.put("b45_14_10", new visuperobject(45,14,10,"Nhưng ngươi, sao xét đoán anh em mình? Còn ngươi, sao khinh dể anh em mình? Vì chúng ta hết thảy sẽ ứng hầu trước tòa án Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_14_11", new visuperobject(45,14,11,"Bởi có chép rằng: Chúa phán: Thật như ta hằng sống, mọi đầu gối sẽ quì trước mặt ta, Và mọi lưỡi sẽ ngợi khen Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_14_12", new visuperobject(45,14,12,"Như vậy, mỗi người trong chúng ta sẽ khai trình việc mình với Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_14_13", new visuperobject(45,14,13,"Vậy chúng ta chớ xét đoán nhau; nhưng thà nhứt định đừng để hòn đá vấp chơn trước mặt anh em mình, và đừng làm dịp cho người sa ngã."));
visuperobject.biblemap.put("b45_14_14", new visuperobject(45,14,14,"Tôi biết và tin chắc trong Ðức Chúa Jêsus rằng, chẳng có vật gì vốn là dơ dáy; chỉn có ai tưởng vật nào là dơ dáy, thì nó là dơ dáy cho người ấy mà thôi."));
visuperobject.biblemap.put("b45_14_15", new visuperobject(45,14,15,"Vả, nếu vì một thức ăn, ngươi làm cho anh em mình lo buồn, thì ngươi chẳng còn cư xử theo đức yêu thương nữa. Chớ nhơn thức ăn làm hư mất người mà Ðấng Christ đã chịu chết cho."));
visuperobject.biblemap.put("b45_14_16", new visuperobject(45,14,16,"Vậy chớ để sự lành mình trở nên cớ gièm chê."));
visuperobject.biblemap.put("b45_14_17", new visuperobject(45,14,17,"Vì nước Ðức Chúa Trời chẳng tại sự ăn uống, nhưng tại sự công bình, bình an, vui vẻ bởi Ðức Thánh Linh vậy."));
visuperobject.biblemap.put("b45_14_18", new visuperobject(45,14,18,"Ai dùng cách ấy mà hầu việc Ðấng Christ, thì đẹp lòng Ðức Chúa Trời và được người ta khen."));
visuperobject.biblemap.put("b45_14_19", new visuperobject(45,14,19,"Vậy chúng ta hãy tìm cách làm nên hòa thuận và làm gương sáng cho nhau."));
visuperobject.biblemap.put("b45_14_20", new visuperobject(45,14,20,"Chớ vì một thức ăn mà hủy hoại việc Ðức Chúa Trời. Thật mọi vật là thánh sạch; nhưng ăn lấy mà làm dịp cho kẻ khác vấp phạm, thì là ác."));
visuperobject.biblemap.put("b45_14_21", new visuperobject(45,14,21,"Ðiều thiện ấy là đừng ăn thịt, đừng uống rượu, và kiêng cữ mọi sự chi làm dịp vấp phạm cho anh em mình."));
visuperobject.biblemap.put("b45_14_22", new visuperobject(45,14,22,"Ngươi có đức tin chừng nào, hãy vì chính mình ngươi mà giữ lấy trước mặt Ðức Chúa Trời. Phước thay cho kẻ không định tội cho mình trong sự mình đã ưng!"));
visuperobject.biblemap.put("b45_14_23", new visuperobject(45,14,23,"Nhưng ai có lòng ngần ngại về thức ăn nào, thì bị định tội rồi, vì chẳng bởi đức tin mà làm; vả, phàm làm điều chi không bởi đức tin thì điều đó là tội lỗi."));
visuperobject.biblemap.put("b45_15_1", new visuperobject(45,15,1,"Vậy chúng ta là kẻ mạnh, phải gánh vác sự yếu đuối cho những kẻ kém sức, chớ làm cho đẹp lòng mình."));
visuperobject.biblemap.put("b45_15_2", new visuperobject(45,15,2,"Mỗi người trong chúng ta nên làm đẹp lòng kẻ lân cận mình, đặng làm điều ích và nên gương tốt."));
visuperobject.biblemap.put("b45_15_3", new visuperobject(45,15,3,"Vì Ðấng Christ cũng không làm cho đẹp lòng mình, như có chép rằng: Lời của những kẻ nguyền rủa Chúa đã đổ trên mình tôi."));
visuperobject.biblemap.put("b45_15_4", new visuperobject(45,15,4,"Vả, mọi sự đã chép từ xưa đều để dạy dỗ chúng ta, hầu cho bởi sự nhịn nhục và sự yên ủi của Kinh Thánh dạy mà chúng ta được sự trông cậy."));
visuperobject.biblemap.put("b45_15_5", new visuperobject(45,15,5,"Xin Ðức Chúa Trời hay nhịn nhục và yên ủi ban cho anh em được đồng lòng ở với nhau theo Ðức Chúa Jêsus Christ;"));
visuperobject.biblemap.put("b45_15_6", new visuperobject(45,15,6,"để anh em lấy một lòng một miệng mà ngợi khen Ðức Chúa Trời, là Cha của Ðức Chúa Jêsus Christ chúng ta."));
visuperobject.biblemap.put("b45_15_7", new visuperobject(45,15,7,"Vậy thì, anh em hãy tiếp lấy nhau, cũng như Ðấng Christ đã tiếp anh em, để Ðức Chúa Trời được vinh hiển."));
visuperobject.biblemap.put("b45_15_8", new visuperobject(45,15,8,"Vả, tôi nói rằng Ðức Chúa Jêsus Christ đã làm chức vụ mình nơi người chịu cắt bì, đặng tỏ bày sự thành tín của Ðức Chúa Trời, và làm quả quyết lời hứa cùng các tổ phụ chúng ta,"));
visuperobject.biblemap.put("b45_15_9", new visuperobject(45,15,9,"lại khiến dân ngoại khen ngợi Ðức Chúa Trời vì sự thương xót của Ngài, như có chép rằng: Bởi đó tôi sẽ ngợi khen Chúa giữa các dân ngoại, Và ca tụng danh Ngài."));
visuperobject.biblemap.put("b45_15_10", new visuperobject(45,15,10,"Lại có chép rằng: Hỡi dân ngoại, hãy đồng vui cùng dân Chúa."));
visuperobject.biblemap.put("b45_15_11", new visuperobject(45,15,11,"Lại rằng: Hỡi hết thảy dân ngoại, Hãy khen ngợi Chúa, muôn dân nên ngợi khen Ngài!"));
visuperobject.biblemap.put("b45_15_12", new visuperobject(45,15,12,"Ê-sai cũng nói rằng: Từ cội rễ Gie-sê Sẽ nứt lên cái chồi cai trị dân ngoại, Dân ngoại sẽ trông cậy chồi ấy."));
visuperobject.biblemap.put("b45_15_13", new visuperobject(45,15,13,"Vậy xin Ðức Chúa Trời của sự trông cậy, làm cho anh em đầy dẫy mọi điều vui vẻ và mọi điều bình an trong đức tin, hầu cho anh em nhờ quyền phép Ðức Thánh Linh được dư dật sự trông cậy!"));
visuperobject.biblemap.put("b45_15_14", new visuperobject(45,15,14,"Hỡi anh em, về phần anh em, tôi cũng tin chắc rằng anh em có đầy lòng nhơn từ, đủ điều thông biết trọn vẹn, lại có tài khuyên bảo nhau."));
visuperobject.biblemap.put("b45_15_15", new visuperobject(45,15,15,"Nếu tôi đã lấy lòng thật dạn dĩ mà viết thơ nói điều nầy điều kia với anh em, ấy là để nhắc lại cho anh em nhớ, bởi ơn Ðức Chúa Trời đã làm cho tôi"));
visuperobject.biblemap.put("b45_15_16", new visuperobject(45,15,16,"nên chức việc của Ðức Chúa Jêsus Christ giữa dân ngoại, làm chức tế lễ của Tin Lành Ðức Chúa Trời, hầu cho dân ngoại được làm của lễ vừa ý Chúa, nên thánh bởi Ðức Thánh Linh."));
visuperobject.biblemap.put("b45_15_17", new visuperobject(45,15,17,"Vậy tôi có cớ khoe mình trong Ðức Chúa Jêsus Christ về điều hầu việc Ðức Chúa Trời."));
visuperobject.biblemap.put("b45_15_18", new visuperobject(45,15,18,"Vì tôi chẳng dám nói những sự khác hơn sự mà Ðấng Christ cậy tôi làm ra để khiến dân ngoại vâng phục Ngài, bởi lời nói và bởi việc làm,"));
visuperobject.biblemap.put("b45_15_19", new visuperobject(45,15,19,"bởi quyền phép của dấu kỳ phép lạ, bằng quyền phép của Thánh Linh Ðức Chúa Trời. Ấy là từ thành Giê-ru-sa-lem và các miền xung quanh cho đến xứ I-ly-ri, tôi đã đem đạo Tin Lành của Ðấng Christ đi khắp chốn."));
visuperobject.biblemap.put("b45_15_20", new visuperobject(45,15,20,"Nhưng tôi lấy làm vinh mà rao Tin Lành ở nơi nào danh Ðấng Christ chưa được truyền ra, để cho khỏi lập lên trên nền người khác,"));
visuperobject.biblemap.put("b45_15_21", new visuperobject(45,15,21,"như có chép rằng: Những kẻ chưa được tin báo về Ngài thì sẽ thấy Ngài, những kẻ chưa nghe nói về Ngài thì sẽ biết Ngài."));
visuperobject.biblemap.put("b45_15_22", new visuperobject(45,15,22,"Ấy cũng là điều đã nhiều lần ngăn trở tôi đi đến thăm anh em."));
visuperobject.biblemap.put("b45_15_23", new visuperobject(45,15,23,"Nhưng bây giờ chẳng còn có chi cầm buộc tôi lại trong các miền nầy nữa; vả lại, đã mấy năm nay, tôi rất ước ao đến cùng anh em;"));
visuperobject.biblemap.put("b45_15_24", new visuperobject(45,15,24,"vậy nếu tôi có thể đi xứ Y-pha-nho được, thì mong rằng sẽ tiện đàng ghé thăm anh em; sau khi được chút thỏa lòng ở với anh em rồi, thì nhờ anh em sai đưa tôi qua xứ ấy."));
visuperobject.biblemap.put("b45_15_25", new visuperobject(45,15,25,"Nay tôi qua thành Giê-ru-sa-lem đặng giúp việc các thánh đồ."));
visuperobject.biblemap.put("b45_15_26", new visuperobject(45,15,26,"Vì người xứ Ma-xê-đoan và xứ A-chai vui lòng quyên tiền để giúp những thánh đồ ở thành Giê-ru-sa-lem đang nghèo túng."));
visuperobject.biblemap.put("b45_15_27", new visuperobject(45,15,27,"Họ vui lòng làm sự đó, và cũng mắc nợ các người đó nữa; vì nếu người ngoại đã có phần về của cải thiêng liêng người Giu-đa, thì cũng phải lấy của cải thuộc về phần đời mà giúp cho người Giu-đa."));
visuperobject.biblemap.put("b45_15_28", new visuperobject(45,15,28,"Vậy khi tôi làm xong việc ấy, và giao quả phước nầy cho họ rồi, tôi sẽ ghé nơi anh em đặng đi đến sứ Y-pha-nho."));
visuperobject.biblemap.put("b45_15_29", new visuperobject(45,15,29,"Tôi biết khi tôi sang với anh em, thì sẽ đem ơn phước dồi dào của Ðấng Christ cùng đến."));
visuperobject.biblemap.put("b45_15_30", new visuperobject(45,15,30,"Vậy, hỡi anh em, nhờ Ðức Chúa Jêsus Christ chúng ta, và nhờ sự yêu thương sanh bởi Ðức Thánh Linh, tôi khuyên anh em phải cùng tôi chiến đấu trong những lời cầu nguyện mà anh em vì tôi trình cùng Ðức Chúa Trời,"));
visuperobject.biblemap.put("b45_15_31", new visuperobject(45,15,31,"hầu để tôi được thoát khỏi những người chẳng tin trong xứ Giu-đê, và của làm phải mà tôi đem qua thành Giê-ru-sa-lem sẽ được các thánh đồ vui lòng nhậm lấy."));
visuperobject.biblemap.put("b45_15_32", new visuperobject(45,15,32,"Bấy giờ tôi có thể vui mừng đi đến anh em, và nếu vừa ý Ðức Chúa Trời, cũng nếm mùi an nghĩ với anh em nữa."));
visuperobject.biblemap.put("b45_15_33", new visuperobject(45,15,33,"Nguyền xin Ðức Chúa Trời bình an ở với anh em hết thảy! A-men."));
visuperobject.biblemap.put("b45_16_1", new visuperobject(45,16,1,"Tôi gởi gắm Phê-bê, người chị em chúng ta cho anh em, người làm nữ chấp sự của Hội thánh Xen-cơ-rê."));
visuperobject.biblemap.put("b45_16_2", new visuperobject(45,16,2,"Hãy ân cần tiếp rước người trong Chúa chúng ta, một cách xứng đáng với thánh đồ, và hãy giúp đỡ người trong mọi dịp mà người sẽ cần đến anh em; vì chính người đã giúp nhiều kẻ, và cũng giúp tôi nữa."));
visuperobject.biblemap.put("b45_16_3", new visuperobject(45,16,3,"Hãy chào Bê-rít-sin và A-qui-la, kẻ cùng làm việc với tôi trong Ðức Chúa Jêsus Christ,"));
visuperobject.biblemap.put("b45_16_4", new visuperobject(45,16,4,"là hai người liều chết để cứu sự sống tôi; ấy chẳng những một mình tôi tạ ơn hai người, nhưng cả các Hội thánh của dân ngoại nữa."));
visuperobject.biblemap.put("b45_16_5", new visuperobject(45,16,5,"Cũng hãy chào Hội thánh nhóm tại nhà hai người. Hãy chào Ê-bai-nết, là người rất thiết với tôi, và đã nên trái đầu mùa trong xứ A-si cho Ðấng Christ."));
visuperobject.biblemap.put("b45_16_6", new visuperobject(45,16,6,"Hãy chào Ma-ri, là người có nhiều công khó vì anh em."));
visuperobject.biblemap.put("b45_16_7", new visuperobject(45,16,7,"Hãy chào An-trô-ni-cơ và Giu-ni-a, tức là bà con và bạn đồng tù với tôi, là hai người có danh vọng trong các sứ đồ và thuộc về Ðấng Christ trước tôi vậy."));
visuperobject.biblemap.put("b45_16_8", new visuperobject(45,16,8,"Hãy chào Am-li-a, người rất yêu dấu của tôi trong Chúa."));
visuperobject.biblemap.put("b45_16_9", new visuperobject(45,16,9,"Hãy chào U-rơ-banh, bạn cùng làm việc với tôi trong Ðấng Christ, và Eâch-ta-chy, là kẻ rất thiết với tôi."));
visuperobject.biblemap.put("b45_16_10", new visuperobject(45,16,10,"Hãy chào A-be-lơ, người được tiếp nạp trong Ðấng Christ. Hãy chào các ngươi ở nhà A-rích-tô-bu."));
visuperobject.biblemap.put("b45_16_11", new visuperobject(45,16,11,"Hãy chào Hê-rô-đi-ôn, là bà con tôi. Hãy chào các người ở trong nhà Nạt-xít, là những kẻ ở trong Chúa."));
visuperobject.biblemap.put("b45_16_12", new visuperobject(45,16,12,"Hãy chào Try-phe-nơ và Try-phô-sơ, là hai người làm việc cho Chúa. Hãy chào Bẹt-si-đơ, người rất thân với tôi, và đã làm việc nhiều cho Chúa."));
visuperobject.biblemap.put("b45_16_13", new visuperobject(45,16,13,"Hãy chào Ru-phu, người được chọn của Chúa, và chào mẹ người, cũng là mẹ tôi."));
visuperobject.biblemap.put("b45_16_14", new visuperobject(45,16,14,"Hãy chào A-sin-cơ-rích, Phơ-lê-gôn, Hẹt-me, Ba-trô-ba, Hẹt-ma, và các anh em ở với họ."));
visuperobject.biblemap.put("b45_16_15", new visuperobject(45,16,15,"Hãy chào Phi-lô-lô-gơ và Giu-li, Nê-rê và chị người, Ô-lim, và hết thảy các thánh đồ ở với họ."));
visuperobject.biblemap.put("b45_16_16", new visuperobject(45,16,16,"Anh em hãy lấy cái hôn thánh mà chào nhau. Hết thảy các Hội thánh của Ðấng Christ chào anh em."));
visuperobject.biblemap.put("b45_16_17", new visuperobject(45,16,17,"Hỡi anh em, tôi khuyên anh em coi chừng những kẻ gây nên bè đảng và làm gương xấu, nghịch cùng sự dạy dỗ mà anh em đã nhận. Phải tránh xa họ đi,"));
visuperobject.biblemap.put("b45_16_18", new visuperobject(45,16,18,"vì những kẻ đó chẳng hầu việc Ðấng Christ, Chúa chúng ta, song hầu việc cái bụng họ, và lấy những lời ngọt ngào dua nịnh dỗ dành lòng kẻ thật thà."));
visuperobject.biblemap.put("b45_16_19", new visuperobject(45,16,19,"Sự anh em vâng phục thì ai ai cũng biết rồi, vậy tôi vì anh em vui mừng, mong rằng anh em khôn ngoan về điều lành, và thanh sạch đối với điều dữ."));
visuperobject.biblemap.put("b45_16_20", new visuperobject(45,16,20,"Ðức Chúa Trời bình an sẽ kíp giày đạp quỉ Sa-tan dưới chơn anh em. Nguyền xin ân điển của Ðức Chúa Jêsus chúng ta ở cùng anh em!"));
visuperobject.biblemap.put("b45_16_21", new visuperobject(45,16,21,"Ti-mô-thê, kẻ cùng làm việc với tôi chào anh em, Lu-si-út, Gia-sôn và Sô-xi-ba-tê, là bà con tôi cũng vậy."));
visuperobject.biblemap.put("b45_16_22", new visuperobject(45,16,22,"Tôi là Tẹt-tiu, người chép bức thơ nầy, chào thăm anh em trong Chúa."));
visuperobject.biblemap.put("b45_16_23", new visuperobject(45,16,23,"Gai-út là người tiếp đãi tôi cùng tiếp đãi cả Hội thánh, chào anh em."));
visuperobject.biblemap.put("b45_16_24", new visuperobject(45,16,24,"Ê-rát, quan kho bạc thành phố, và Qua-rơ-tu, người anh em chúng ta, cũng chào anh em nữa."));
visuperobject.biblemap.put("b45_16_25", new visuperobject(45,16,25,"Ngợi khen Ðấng có quyền làm cho vững chí anh em theo Tin Lành của tôi và lời giảng Ðức Chúa Jêsus Christ, theo sự tỏ ra về lẽ mầu nhiệm, là lẽ đã giấu kín từ mọi đời trước,"));
visuperobject.biblemap.put("b45_16_26", new visuperobject(45,16,26,"mà bây giờ được bày ra, và theo lịnh Ðức Chúa Trời hằng sống, bởi các sách tiên tri, bày ra cho mọi dân đều biết, đặng đem họ đến sự vâng phục của đức tin,"));
visuperobject.biblemap.put("b45_16_27", new visuperobject(45,16,27,"nhơn Ðức Chúa Jêsus Christ, nguyền xin vinh hiển về nơi Ðức Chúa Trời khôn ngoan có một, đời đời vô cùng! A-men."));

}

}