package vi.bible;

public class vibible28 {

public vibible28() {

putmapbible28();

}

private void putmapbible28() {

visuperobject.biblemap.put("b28_1_1", new visuperobject(28,1,1,"Có lời Ðức Giê-hô-va phán cùng Ô-sê, con trai Bê-ê-ri, về đời ô-xia, Giô-tham, A-cha, Ê-xê-chia là các vua của Giu-đa, và về đời Giê-rô-bô-am, con trai Giô-ách, vua Y-sơ-ra-ên."));
visuperobject.biblemap.put("b28_1_2", new visuperobject(28,1,2,"Khi Ðức Giê-hô-va bắt đầu phán cùng Ô-sê, Ðức Giê-hô-va bảo người rằng: Hãy đi, lấy một người vợ gian dâm, và con cái ngoại tình; vì đất nầy chỉ phạm sự tà dâm, lìa bỏ Ðức Giê-hô-va."));
visuperobject.biblemap.put("b28_1_3", new visuperobject(28,1,3,"Vậy Ô-sê đi cưới Gô-me, con gái của Ðíp-la-im. Nàng chịu thai và sanh cho người một trai."));
visuperobject.biblemap.put("b28_1_4", new visuperobject(28,1,4,"Bấy giờ Ðức Giê-hô-va phán cùng người rằng: Hãy đặt tên nó là Gít-rê-ên, vì còn ít lâu nữa, ta sẽ báo thù cho huyết của Gít-rê-ên nơi nhà Giê-hu, và sẽ dứt nước của nhà Y-sơ-ra-ên."));
visuperobject.biblemap.put("b28_1_5", new visuperobject(28,1,5,"Trong ngày đó, ta sẽ bẻ cung của Y-sơ-ra-ên trong trũng Gít-rê-ên."));
visuperobject.biblemap.put("b28_1_6", new visuperobject(28,1,6,"Nàng lại chịu thai và sanh một gái, thì Ðức Giê-hô-va phán cùng Ô-sê rằng: Hãy đặt tên nó là Lô-Ru-ha-ma; vì ta sẽ không thương xót nhà Y-sơ-ra-ên nữa."));
visuperobject.biblemap.put("b28_1_7", new visuperobject(28,1,7,"Nhưng ta sẽ thương xót nhà Giu-đa; sẽ giải cứu chúng nó bởi Giê-hô-va Ðức Chúa Trời của chúng nó; và ta sẽ không cứu chúng nó bởi cung, hoặc bởi gươm, hoặc bởi chiến trận, hoặc bởi ngựa, hoặc bởi người cưỡi ngựa."));
visuperobject.biblemap.put("b28_1_8", new visuperobject(28,1,8,"Sau khi Lô-Ru-ha-ma thôi bú, nàng chịu thai và sanh một trai."));
visuperobject.biblemap.put("b28_1_9", new visuperobject(28,1,9,"Ðức Giê-hô-va phán rằng: Hãy đặt tên nó là Lô-Am-mi; vì các ngươi chẳng phải là dân ta nữa, và ta sẽ không làm Ðức Chúa Trời các ngươi nữa."));
visuperobject.biblemap.put("b28_1_10", new visuperobject(28,1,10,"Dầu vậy, số con cái Y-sơ-ra-ên sẽ giống như cát bờ biển, không thể lường, không thể đếm; và chính nơi mà đã bảo chúng nó rằng: Các ngươi chẳng phải là dân ta, sẽ lại bảo rằng: Các ngươi là con trai của Ðức Chúa Trời hằng sống."));
visuperobject.biblemap.put("b28_1_11", new visuperobject(28,1,11,"Con cái Giu-đa và con cái Y-sơ-ra-ên sẽ hiệp nhau lại; sẽ lập cho mình một quan trưởng chung, và sẽ trở lên từ đất nầy, vì ngày của Gít-rê-ên sẽ là ngày lớn."));
visuperobject.biblemap.put("b28_2_1", new visuperobject(28,2,1,"Hãy xưng anh em các ngươi là Am-mi; và chị em các ngươi là Ru-ha-ma."));
visuperobject.biblemap.put("b28_2_2", new visuperobject(28,2,2,"Hãy kiện mẹ các ngươi, hãy kiện đi; vì nó chẳng phải là vợ ta, còn ta chẳng phải là chồng nó! Nó hãy cất bỏ sự dâm loạn khỏi trước mặt nó, và sự ngoại tình khỏi giữa vú nó đi;"));
visuperobject.biblemap.put("b28_2_3", new visuperobject(28,2,3,"kẻo ta sẽ lột trần nó, để nó như ngày mới sanh ra, và làm cho nó ra như đồng vắng, như đất khô, khiến nó chết khát."));
visuperobject.biblemap.put("b28_2_4", new visuperobject(28,2,4,"Ta sẽ không thương xót con cái nó, vì ấy là con cái của sự gian dâm."));
visuperobject.biblemap.put("b28_2_5", new visuperobject(28,2,5,"Thật vậy, mẹ chúng nó làm sự gian dâm, kẻ mang thai chúng nó đã làm sự ô nhục. Vì nó rằng: Ta sẽ đi theo các tình nhơn ta, là kẻ ban bánh, nước, lông chiên, vải, dầu và đồ uống cho ta."));
visuperobject.biblemap.put("b28_2_6", new visuperobject(28,2,6,"Vậy nên, nầy, ta sẽ lấy gai gốc rấp đường ngươi; sẽ xây một bức tường nghịch cùng nó, và nó không thể tìm lối mình được nữa."));
visuperobject.biblemap.put("b28_2_7", new visuperobject(28,2,7,"Nó sẽ đuổi theo tình nhơn mình mà không kịp, tìm mà không gặp đâu. Ðoạn nó sẽ rằng: Ta sẽ trở về cùng chồng thứ nhứt của ta; vì lúc đó ta sung sướng hơn bây giờ."));
visuperobject.biblemap.put("b28_2_8", new visuperobject(28,2,8,"Thật nó chưa từng nhận biết rằng chính ta là Ðấng đã ban lúa mì, rượu mới và dầu cho nó, đã thêm nhiều bạc và vang mà chúng nó dùng cho Ba-anh."));
visuperobject.biblemap.put("b28_2_9", new visuperobject(28,2,9,"Vậy nên ta sẽ lấy lại lúa mì ta trong kỳ nó và rượu mới ta trong mùa nó, ta sẽ cướp lại nhung và vải ta là đồ che sự trần truồng nó."));
visuperobject.biblemap.put("b28_2_10", new visuperobject(28,2,10,"Ấy vậy, ta sẽ to sự xấu xa nó ra trước mặt tình nhơn nó, và chẳng ai sẽ cứu nó được khỏi tay ta."));
visuperobject.biblemap.put("b28_2_11", new visuperobject(28,2,11,"Ta sẽ dứt cả sự vui của nó, những ngày lễ, ngày trăng mới, ngày Sa-bát và hết thảy những ngày lễ trọng thể của nó"));
visuperobject.biblemap.put("b28_2_12", new visuperobject(28,2,12,"Ta sẽ phá những cây nho và cây vả nó, về các cây ấy nó nói rằng: Nầy là tiền công của các tình nhơn ta cho ta. Ta sẽ làm cho những cây ấy nên rừng, và các thú đồng sẽ ăn đi."));
visuperobject.biblemap.put("b28_2_13", new visuperobject(28,2,13,"Ta sẽ thăm phạt nó vì những ngày mà nó dâng hương cho các tượng Ba-anh, trang sức những hoa tai và đồ châu báu, nó đi theo tình nhơn mình, còn ta thì nó quên đi! Ðức Giê-hô-va phán vậy."));
visuperobject.biblemap.put("b28_2_14", new visuperobject(28,2,14,"Cho nên, nầy, ta sẽ dẫn dụ nó, dẫn nó vào đồng vắng, và lấy lời ngọt ngào nói cùng nó."));
visuperobject.biblemap.put("b28_2_15", new visuperobject(28,2,15,"Ta lại sẽ ban vườn nho cho nó từ nơi đó, và trũng A-cô sẽ trở nên cửa trông cậy. Nó sẽ trả lời tại đó như trong ngày trẻ tuổi nó, và như trong ngày nó ra khỏi đất Ê-díp-tô."));
visuperobject.biblemap.put("b28_2_16", new visuperobject(28,2,16,"Ðức Giê-hô-va phán rằng: Trong ngày đó ngươi sẽ gọi ta là: Chồng tôi, và sẽ không gọi ta là: Chủ tôi nữa."));
visuperobject.biblemap.put("b28_2_17", new visuperobject(28,2,17,"Vì ta sẽ cất tên của các tượng Ba-anh khỏi miệng nó; và không ai nói đến tên chúng nó nữa."));
visuperobject.biblemap.put("b28_2_18", new visuperobject(28,2,18,"Trong ngày đó, ta sẽ vì chúng nó lập ước cùng những thú đồng, những chim trời, và côn trùng trên đất. Ta sẽ bẻ gãy và làm cho biến mất khỏi đất nầy những cung, những gươm, và giặc giã; và sẽ khiến dân sự được nằm yên ổn."));
visuperobject.biblemap.put("b28_2_19", new visuperobject(28,2,19,"Ta sẽ cưới ngươi cho ta đời đời; ta sẽ cưới ngươi cho ta trong sự công bình và chánh trực, nhơn từ và thương xót."));
visuperobject.biblemap.put("b28_2_20", new visuperobject(28,2,20,"Phải, ta sẽ cưới ngươi cho ta trong sự thành tín, và ngươi sẽ biết Ðức Giê-hô-va."));
visuperobject.biblemap.put("b28_2_21", new visuperobject(28,2,21,"Ðức Giê-hô-va phán: Trong ngày đó, ta sẽ trả lời, ta sẽ trả lời cho các từng trời, các từng trời sẽ trả lời cho đất."));
visuperobject.biblemap.put("b28_2_22", new visuperobject(28,2,22,"Ðất sẽ trả lời cho lúa mì, cho rượu mới, cho dầu, và ba thứ nầy sẽ trả lời cho Gít-rê-ên."));
visuperobject.biblemap.put("b28_2_23", new visuperobject(28,2,23,"Ðoạn ta sẽ gieo nó cho ta trong đất, và sẽ làm sự thương xót cho kẻ chưa được thương xót. Ta sẽ nói cùng những kẻ chưa làm dân ta rằng: Ngươi là dân ta, và nó sẽ trả lời rằng: Ngài là Ðức Chúa Trời tôi."));
visuperobject.biblemap.put("b28_3_1", new visuperobject(28,3,1,"Ðức Giê-hô-va bảo ta rằng: Hãy đi, lại yêu một người đờn bà tà dâm đã có bạn yêu mình, theo như Ðức Giê-hô-va vẫn yêu con cái Y-sơ-ra-ên, dầu chúng nó xây về các thần khác, và ưa bánh ngọt bằng trái nho."));
visuperobject.biblemap.put("b28_3_2", new visuperobject(28,3,2,"Vậy ta đã mua đờn bà ấy bằng mười lăm miếng bạc và một hô-me rưỡi mạch nha."));
visuperobject.biblemap.put("b28_3_3", new visuperobject(28,3,3,"Rồi ta bảo nó rằng: Ngươi khá chờ đợi ta lâu ngày; đừng làm sự gian dâm và chớ làm vợ cho người nam nào, thì ta đối với ngươi cũng sẽ làm như vậy."));
visuperobject.biblemap.put("b28_3_4", new visuperobject(28,3,4,"Vì con cái Y-sơ-ra-ên sẽ trải qua nhiều ngày, không vua, không quan trưởng, không của lễ, không trụ tượng, không ê-phót, và không thê-ra-phim."));
visuperobject.biblemap.put("b28_3_5", new visuperobject(28,3,5,"Nhưng, rồi đó, con cái Y-sơ-ra-ên sẽ trở lại tìm kiếm Giê-hô-va Ðức Chúa Trời mình, và Ða-vít vua mình. Chúng nó sẽ kính sợ mà trở về cùng Ðức Giê-hô-va, và được ơn Ngài trong những ngày sau rốt."));
visuperobject.biblemap.put("b28_4_1", new visuperobject(28,4,1,"Hỡi con cái Y-sơ-ra-ên, hãy nghe lời của Ðức Giê-hô-va; vì Ðức Giê-hô-va có sự kiện cáo với dân đất nầy, bởi trong đất nầy chẳng có lẽ thật, chẳng có nhơn từ, cũng chẳng có sự nhận biết Ðức Chúa Trời."));
visuperobject.biblemap.put("b28_4_2", new visuperobject(28,4,2,"Ở đó chỉ thấy những sự thề gian, thất tín, giết người, ăn trộm, và tà dâm; chúng nó làm sự tàn bạo, máu chồng trên máu."));
visuperobject.biblemap.put("b28_4_3", new visuperobject(28,4,3,"Vậy nên, đất ấy sẽ sầu thảm; hết thảy người ở đó sẽ hao mòn, những thú đồng và chim trời cũng vậy; những cá biển cũng sẽ bị lấy đi."));
visuperobject.biblemap.put("b28_4_4", new visuperobject(28,4,4,"Dầu vậy, chớ có ai biện luận, chớ có ai quở trách! Vì dân ngươi giống như những người cãi lẫy thầy tế lễ."));
visuperobject.biblemap.put("b28_4_5", new visuperobject(28,4,5,"Ngươi sẽ vấp ngã giữa ban ngày; chính mình kẻ tiên tri cũng sẽ vấp ngã với ngươi trong ban đêm, và ta sẽ diệt mẹ ngươi."));
visuperobject.biblemap.put("b28_4_6", new visuperobject(28,4,6,"Dân ta bị diệt vì cớ thiếu sự thông biết. Bởi ngươi bỏ sự thông biết thì ta cũng bỏ ngươi, đặng ngươi không làm thầy tế lễ cho ta nữa; bởi ngươi đã quên luật pháp của Ðức Chúa Trời mình, thì ta cũng sẽ quên con cái ngươi."));
visuperobject.biblemap.put("b28_4_7", new visuperobject(28,4,7,"Chúng nó sanh sản nhiều ra bao nhiêu, thì chúng nó lại phạm tội nghịch cùng ta bấy nhiêu: ta sẽ đổi sự vinh hiển của chúng nó ra sỉ nhục."));
visuperobject.biblemap.put("b28_4_8", new visuperobject(28,4,8,"Chúng nó ăn tội lỗi dân ta; ham hố sự gian ác của nó."));
visuperobject.biblemap.put("b28_4_9", new visuperobject(28,4,9,"Sẽ xảy ra dân thể nào thì thầy tế lễ cũng thể ấy: ta sẽ phạt nó vì đường lối nó và sẽ trả cho nó tùy việc nó làm."));
visuperobject.biblemap.put("b28_4_10", new visuperobject(28,4,10,"Chúng nó sẽ ăn mà không được no, hành dâm mà không sanh sản thêm, vì chúng nó đã bỏ Ðức Giê-hô-va không nghĩ đến Ngài nữa."));
visuperobject.biblemap.put("b28_4_11", new visuperobject(28,4,11,"Sự dâm dục, rượu cũ và rượu mới cất lấy hết trí khôn chúng nó."));
visuperobject.biblemap.put("b28_4_12", new visuperobject(28,4,12,"Dân ta hỏi tượng gỗ nó, thì gậy nó trả lời; vì lòng dâm làm lầm lạc chúng nó, và chúng nó phạm tội tà dâm mà lìa bỏ Ðức Chúa Trời mình."));
visuperobject.biblemap.put("b28_4_13", new visuperobject(28,4,13,"Chúng nó dâng tế lễ trên các chót núi; đốt hương trên các đồi, dưới những cây dẽ, cây liễu, cây thông, vì bóng nó mát mẻ lắm. Vậy nên, con gái các ngươi hành dâm, và dâu các ngươi phạm tội ngoại tình."));
visuperobject.biblemap.put("b28_4_14", new visuperobject(28,4,14,"Ta sẽ không phạt con gái các ngươi bởi cớ hành dâm, cũng không phạt dâu các ngươi bởi cớ ngoại tình; vì những đờn ông đi riêng với đồ điếm đĩ, và dâng của lễ với đờn bà dâm đãng. Vậy nên dân sự chẳng hiểu biết sẽ bị úp đổ."));
visuperobject.biblemap.put("b28_4_15", new visuperobject(28,4,15,"Hỡi Y-sơ-ra-ên, dầu ngươi tà dâm, Giu-đa cũng không nên phạm tội! Vậy chớ vào nơi Ghinh-ganh! Chớ lên nơi Bết-a-ven! Chớ có thề mà rằng: Thật như Ðức Giê-hô-va hằng sống."));
visuperobject.biblemap.put("b28_4_16", new visuperobject(28,4,16,"Vì Y-sơ-ra-ên đã bạn nghịch như con bò cái tơ bất trị, nên bây giờ Ðức Giê-hô-va cho chúng nó ăn cỏ như chiên con thả trong đồng rộng."));
visuperobject.biblemap.put("b28_4_17", new visuperobject(28,4,17,"Ép-ra-im sa mê thần tượng, hãy để mặc nó!"));
visuperobject.biblemap.put("b28_4_18", new visuperobject(28,4,18,"Ðồ chúng nó uống đã chua đi; chúng nó làm sự gian dâm chẳng thôi. Các quan trưởng nó vui lòng trong sự sỉ nhục."));
visuperobject.biblemap.put("b28_4_19", new visuperobject(28,4,19,"Gió đã lấy cánh cuốn nó, và chúng nó sẽ mang xấu hổ vì của lễ mình."));
visuperobject.biblemap.put("b28_5_1", new visuperobject(28,5,1,"Hỡi các thầy tế lễ, hãy nghe điều nầy; hỡi nhà Y-sơ-ra-ên, khá để ý; hỡi nhà vua, hãy lắng tai! Sự phán xét có quan hệ với các ngươi, vì các ngươi là bẫy ở Mích-ba, và giăng lưới trên Tha-bô."));
visuperobject.biblemap.put("b28_5_2", new visuperobject(28,5,2,"Chúng nó là kẻ bạn nghịch đã vào sâu trong sự giết lát, nhưng ta sẽ quở trách chúng nó hết thảy."));
visuperobject.biblemap.put("b28_5_3", new visuperobject(28,5,3,"Ta biết Ép-ra-im, và Y-sơ-ra-ên không giấu với ta. Vả, hỡi Ép-ra-im, ngươi đã phạm tội tà dâm! Y-sơ-ra-ên bị ô uế!"));
visuperobject.biblemap.put("b28_5_4", new visuperobject(28,5,4,"Công việc chúng nó làm ngăn trở chúng nó về cùng Ðức Chúa Trời mình; vì lòng dâm trong chúng nó, và chúng nó không nhận biết Ðức Giê-hô-va."));
visuperobject.biblemap.put("b28_5_5", new visuperobject(28,5,5,"Sự kiêu ngạo của Y-sơ-ra-ên làm chứng tận mặt nó, nên Y-sơ-ra-ên và Ép-ra-im sẽ ngã xuống vì cớ tội lỗi mình; Giu-đa cũng sẽ ngã xuống với chúng nó."));
visuperobject.biblemap.put("b28_5_6", new visuperobject(28,5,6,"Chúng nó sẽ đi với các bầy chiên bầy bò mình, đặng tìm kiếm Ðức Giê-hô-va; song không thấy Ngài! Ngài đã lìa khỏi chúng nó."));
visuperobject.biblemap.put("b28_5_7", new visuperobject(28,5,7,"Chúng nó đã phỉnh dối Ðức Giê-hô-va, vì đã sanh những con cái ngoại tình. Ðến ngày trăng mới, chúng nó sẽ cùng sản nghiệp mình đều bị nuốt đi!"));
visuperobject.biblemap.put("b28_5_8", new visuperobject(28,5,8,"Hãy thổi kèn ở Ghi-bê-a, hãy thổi loa ở Ra-ma! Hãy la lối ở Bết-a-ven! Hỡi Bên-gia-min, nó ở đằng sau ngươi!"));
visuperobject.biblemap.put("b28_5_9", new visuperobject(28,5,9,"Ép-ra-im sẽ nên hoang vu trong ngày quở trách; ta rao ra cho các chi phái Y-sơ-ra-ên một sự chắc sẽ xảy đến."));
visuperobject.biblemap.put("b28_5_10", new visuperobject(28,5,10,"Các quan trưởng Giu-đa giống như kẻ lấn địa giới; ta sẽ đổ cơn giận ta trên chúng nó như trút nước."));
visuperobject.biblemap.put("b28_5_11", new visuperobject(28,5,11,"Ép-ra-im bị hà hiếp, bị nghiền nát trong sự đoán xét, vì nó đã bằng lòng theo điều răn của loài người."));
visuperobject.biblemap.put("b28_5_12", new visuperobject(28,5,12,"Vậy nên, ta giống như con mọt cho Ép-ra-im, và như sự mục nát cho nhà Giu-đa."));
visuperobject.biblemap.put("b28_5_13", new visuperobject(28,5,13,"Khi Ép-ra-im đã biết bịnh mình, thì Ép-ra-im đi đến cùng người A-si-ri, và sai đến cùng vua Gia-rép. Nhưng nó không thể chữa lành các ngươi, và không buộc vết thương cho các ngươi."));
visuperobject.biblemap.put("b28_5_14", new visuperobject(28,5,14,"Vì ta sẽ như một con sư tử cho Ép-ra-im, như một sư tử con cho nhà Giu-đa. Thật, chính ta, chính ta sẽ cắn xé rồi đi luôn; ta sẽ bắt đem đi và chẳng ai có thể giải cứu."));
visuperobject.biblemap.put("b28_5_15", new visuperobject(28,5,15,"Ta sẽ đi, sẽ vào nơi ta, cho đến chừng nào chúng nó nhận biết mình phạm tội và tìm kiếm mặt ta. Trong cơn khốn nạn, chúng nó sẽ cố tìm ta."));
visuperobject.biblemap.put("b28_6_1", new visuperobject(28,6,1,"Hãy đến, chúng ta hãy trở về cùng Ðức Giê-hô-va; vì Ngài đã xé chúng ta, song Ngài sẽ chữa lành cho; Ngài đã đánh chúng ta, song sẽ buộc vết tích."));
visuperobject.biblemap.put("b28_6_2", new visuperobject(28,6,2,"Trong hai ngày, Ngài sẽ khiến chúng ta tỉnh lại; ngày thứ ba, Ngài sẽ dựng chúng ta dậy, chúng ta sẽ sống trước mặt Ngài."));
visuperobject.biblemap.put("b28_6_3", new visuperobject(28,6,3,"Chúng ta khá nhận biết Ðức Giê-hô-va; chúng ta khá gắng sức nhận biết Ngài. Sự hiện ra của Ngài là chắc chắn như sự hiện ra của mặt trời sớm mai, Ngài sẽ đến cùng chúng ta như mua, như mua cuối mùa tưới đất."));
visuperobject.biblemap.put("b28_6_4", new visuperobject(28,6,4,"Ta sẽ làm gì cho ngươi, hỡi Ép-ra-im? Ta sẽ làm gì cho ngươi, hỡi Giu-đa? Vì lòng nhơn từ của các ngươi giống như mây buổi sáng, như móc tan ra vừa lúc sớm mai."));
visuperobject.biblemap.put("b28_6_5", new visuperobject(28,6,5,"Vậy nên ta đã dùng các tiên tri sửa phạt chúng nó; ta đã giết chúng nó bởi lời nói từ miệng ta: những sự phán xét của ta mọc lên như ánh sáng."));
visuperobject.biblemap.put("b28_6_6", new visuperobject(28,6,6,"Vì ta ưa sự nhơn từ và không ưa của lễ, ưa sự nhận biết Ðức Chúa Trời hơn là ưa của lễ thiêu."));
visuperobject.biblemap.put("b28_6_7", new visuperobject(28,6,7,"Nhưng, theo cách người ta, chúng nó đã phạm lời giao ước, và ở đó chúng nó đã phỉnh dối ta."));
visuperobject.biblemap.put("b28_6_8", new visuperobject(28,6,8,"Ga-la-át là thành của kẻ làm ác, đầy những dấu máu."));
visuperobject.biblemap.put("b28_6_9", new visuperobject(28,6,9,"Như bọn trộm cướp rình người đi qua, thì bọn thầy tế lễ cũng giết người trên con đường đi về Si-chem, chúng nó phạm biết bao là tội ác!"));
visuperobject.biblemap.put("b28_6_10", new visuperobject(28,6,10,"Trong nhà Y-sơ-ra-ên, ta đã thấy một việc gớm ghiếc, ở đó Ép-ra-im thì làm sự gian dâm, Y-sơ-ra-ên thì bị ô uế!"));
visuperobject.biblemap.put("b28_6_11", new visuperobject(28,6,11,"Hỡi Giu-đa, ngươi cũng vậy, có mùa gặt đã định cho ngươi, khi ta đem phu tù của dân ta trở về."));
visuperobject.biblemap.put("b28_7_1", new visuperobject(28,7,1,"Khi ta muốn chữa lành cho Y-sơ-ra-ên, thì tội lỗi của Ép-ra-im và sự gian ác của Sa-ma-ri bày tỏ; vì chúng nó đã làm sự giả dối; kẻ trộm vào trong và bọn cướp đánh giựt ở ngoài."));
visuperobject.biblemap.put("b28_7_2", new visuperobject(28,7,2,"Chúng nó không nghĩ trong lòng rằng ta nhớ mọi sự gian ác của chúng nó. Bây giờ tội phạm chúng nó ràng rịt lấy mình; chúng nó ở trước mặt ta."));
visuperobject.biblemap.put("b28_7_3", new visuperobject(28,7,3,"Chúng nó lấy sự gian ác mình làm vui lòng vua, lấy sự dối trá mình làm đẹp lòng các quan trưởng."));
visuperobject.biblemap.put("b28_7_4", new visuperobject(28,7,4,"Hết thảy chúng nó đều tà dâm, giống như lò của người nướng bánh đốt lửa, thôi chụm lửa từ khi nhồi bột cho đến chừng bột dậy men."));
visuperobject.biblemap.put("b28_7_5", new visuperobject(28,7,5,"Ðến ngày vua chúng ta, các quan trưởng vì sự nóng của rượu mà đau ốm: vua cũng bắt tay những kẻ hay nhạo báng."));
visuperobject.biblemap.put("b28_7_6", new visuperobject(28,7,6,"Chúng nó rình rập, lòng cháy như là lửa mà kẻ nướng bánh đã ngủ cả đêm; đến sáng sớm thì lò chánh như lửa phun ra những ngọn."));
visuperobject.biblemap.put("b28_7_7", new visuperobject(28,7,7,"Chúng nó thảy đều nóng hừng như lò lửa, nuốt các quan xét mình. Hết thảy các vua chúng nó đều bị úp đổ, và trong đám họ chẳng ai kêu với ta."));
visuperobject.biblemap.put("b28_7_8", new visuperobject(28,7,8,"Ép-ra-im xen lộn với các dân khác; Ép-ra-im khác nào bánh chưa quay."));
visuperobject.biblemap.put("b28_7_9", new visuperobject(28,7,9,"Các dân ngoại đã nuốt sức mạnh nó, mà nó không biết! Tọc đầu nó bạc lém đém, mà nó chẳng ngờ!"));
visuperobject.biblemap.put("b28_7_10", new visuperobject(28,7,10,"Sự kiêu ngạo của Y-sơ-ra-ên làm chứng trước mặt nó; chúng nó dầu gặp sự đó cũng không trở lại cùng Giê-hô-va Ðức Chúa Trời mình, và cũng chẳng tìm kiếm Ngài!"));
visuperobject.biblemap.put("b28_7_11", new visuperobject(28,7,11,"Ép-ra-im như bò câu ngây dại, không có trí khôn: vì chúng nó kêu Ê-díp-tô, đi đến cùng A-si-ri."));
visuperobject.biblemap.put("b28_7_12", new visuperobject(28,7,12,"Ðang khi chúng nó đi đó, ta sẽ giăng lưới trên chúng nó, ta sẽ làm cho chúng nó ngã xuống như những chim trời; ta sẽ sửa phạt chúng nó y như giữa hội chúng nó đã nghe."));
visuperobject.biblemap.put("b28_7_13", new visuperobject(28,7,13,"Khốn cho chúng nó! vì chúng nó lìa xa ta; nguyền sự hư nát đổ trên chúng nó! vì chúng nó đã phạm tội nghịch cùng ta: dầu ta muốn cứu chuộc chúng nó, nhưng chúng nó nói những điều dối trá nghịch cùng ta."));
visuperobject.biblemap.put("b28_7_14", new visuperobject(28,7,14,"Chúng nó chẳng lấy lòng kêu cầu ta, song chúng nó kêu van trên giường mình; chúng nó thâu mùa lúa mì và rượu mới của mình, và bạn nghịch cùng ta."));
visuperobject.biblemap.put("b28_7_15", new visuperobject(28,7,15,"chính ta đã dạy chúng nó, đã làm cho mạnh cánh tay chúng nó, dầu vậy, chúng nó cũng toan sự dữ nghịch cùng ta."));
visuperobject.biblemap.put("b28_7_16", new visuperobject(28,7,16,"Chúng nó xây lại, song không hướng về Ðấng Rất Cao. Chúng nó giống như cung giở trái. Quan trưởng chúng nó sẽ ngã bởi gươm, vì lưỡi chúng nó nổi giận. Kìa, chúng nó sẽ làm trò cười trong đất Ê-díp-tô."));
visuperobject.biblemap.put("b28_8_1", new visuperobject(28,8,1,"Miệng ngươi khá thổi kèn! Nó như chim ưng đến nghịch cùng nhà Ðức Giê-hô-va, vì chúng nó đã trái lời giao ước ta, va đã phạm luật pháp ta."));
visuperobject.biblemap.put("b28_8_2", new visuperobject(28,8,2,"Chúng nó sẽ kêu đến ta rằng: Hỡi Ðức Chúa Trời tôi, chúng tôi là Y-sơ-ra-ên, nhận biết Ngài!"));
visuperobject.biblemap.put("b28_8_3", new visuperobject(28,8,3,"Y-sơ-ra-ên đã bỏ điều lành, kẻ nghịch sẽ đuổi theo nó."));
visuperobject.biblemap.put("b28_8_4", new visuperobject(28,8,4,"Chúng nó đã lập vua mà không bởi ta, lập quan trọng mà ta không biết. Chúng nó lấy bạc vàng của mình làm thần tượng cho mình, để chúng nó bị dứt đi."));
visuperobject.biblemap.put("b28_8_5", new visuperobject(28,8,5,"Hỡi Sa-ma-ri, bò con của ngươi đã bị bỏ rồi! Cơn giận của ta đã phừng lên nghịch cùng chúng nó. Chúng nó chẳng được khỏi tội cho đến khi nào?"));
visuperobject.biblemap.put("b28_8_6", new visuperobject(28,8,6,"Vì bò con đó thật là việc của Y-sơ-ra-ên làm ra; một người thợ đã chế ra, nó không phải là Ðức Chúa Trời. Thật, bò con của Sa-ma-ri sẽ bị bể nát."));
visuperobject.biblemap.put("b28_8_7", new visuperobject(28,8,7,"Vì chúng nó đã gieo gió và sẽ gặt bão lốc. Chúng nó không có lúa đứng; cây lúa sẽ không sanh ra bột; mà dầu có sanh ra nữa, thì dân ngoại sẽ nuốt lấy."));
visuperobject.biblemap.put("b28_8_8", new visuperobject(28,8,8,"Y-sơ-ra-ên đã bị nuốt. Bây giờ chúng nó ở giữa các dân, như khí mạnh chẳng ai ưa thích."));
visuperobject.biblemap.put("b28_8_9", new visuperobject(28,8,9,"Vì chúng nó đã lên A-si-ri, như con lừa rừng đi một mình; Ép-ra-im đã hối lộ cho những kẻ yêu nó."));
visuperobject.biblemap.put("b28_8_10", new visuperobject(28,8,10,"Dầu chúng nó hối lộ giữa các nước, nay ta sẽ nhóm họp chúng nó; chúng nó bắt đầu giảm bớt đi, vì cớ sự gánh nặng bởi vua của các quan trưởng."));
visuperobject.biblemap.put("b28_8_11", new visuperobject(28,8,11,"Vì Ép-ra-im đã thêm nhiều bàn thờ đặng phạm tội, thì những bàn thờ nó đã khiến nó sa vào tội lỗi."));
visuperobject.biblemap.put("b28_8_12", new visuperobject(28,8,12,"Ta đã chép lệ luật ta cho nó một vạn điều, nhưng nó coi những chẳng can gì đến mình."));
visuperobject.biblemap.put("b28_8_13", new visuperobject(28,8,13,"Còn như của lễ dâng cho ta, thì chúng nó dâng thịt và ăn; nhưng Ðức Giê-hô-va chẳng nhận chúng nó đâu. Bây giờ Ngài nhớ lại sự gian ác chúng nó, và sẽ thăm phạt tội lỗi chúng nó; chúng nó sẽ trở về trong Ê-díp-tô!"));
visuperobject.biblemap.put("b28_8_14", new visuperobject(28,8,14,"Y-sơ-ra-ên đã quên Ðấng tạo mình, và dựng những cung đền; Giu-đa đã thêm nhiều các thành bền vững. Nhưng ta sẽ sai lửa trên các thành nó, và lửa ấy sẽ thiêu cháy cung đền nó."));
visuperobject.biblemap.put("b28_9_1", new visuperobject(28,9,1,"Hỡi Y-sơ-ra-ên, chớ vui mừng; chớ nức lòng mừng rỡ như các dân; vì ngươi đã phạm tội tà dâm và cách xa Ðức Chúa Trời ngươi. ngươi đã ưa thích tiền công mình trên mọi sân đạp lúa"));
visuperobject.biblemap.put("b28_9_2", new visuperobject(28,9,2,"Hoặc sân đạp lúa, hoặc hầm ép rượu, cũng được chẳng nuôi chúng nó; rượu mới sẽ thiếu thốn cho nó."));
visuperobject.biblemap.put("b28_9_3", new visuperobject(28,9,3,"Chúng nó sẽ không ở trong đất của Ðức Giê-hô-va nữa; nhưng Ép-ra-im sẽ trở về Ê-díp-tô, và sẽ ăn đồ ăn ô uế trong A-si-ri."));
visuperobject.biblemap.put("b28_9_4", new visuperobject(28,9,4,"Chúng nó sẽ không làm lễ quán bằng rượu cho Ðức Giê-hô-va nữa, và các của lễ chúng nó cũng sẽ chẳng đẹp lòng Ngài; song sẽ như bánh kẻ có tang: hễ ai ăn đến thì bị ô uế; vì bánh chúng nó sẽ đỡ đói cho chúng nó, chẳng được vào nhà Ðức Giê-hô-va."));
visuperobject.biblemap.put("b28_9_5", new visuperobject(28,9,5,"Các ngươi sẽ làm gì trong ngày lễ trọng thể, trong ngày lễ của Ðức Giê-hô-va?"));
visuperobject.biblemap.put("b28_9_6", new visuperobject(28,9,6,"Thật, nầy, chúng nó đã đi trốn khỏi tai họa. Ê-díp-tô sẽ liệm chúng nó, Mem-phi sẽ chôn chúng nó. Những đồ bằng bạc rất quí của chúng nó sẽ trở nên mồi của chà-chuôm; gai gốc sẽ loán nơi nhà tạm chúng nó."));
visuperobject.biblemap.put("b28_9_7", new visuperobject(28,9,7,"Những ngày thăm phạt đã đến rồi! Những ngày báo trả đã tới rồi! Y-sơ-ra-ên sẽ biết. Kẻ tiên tri là dư dật, người được cảm động bởi thần linh là điên cuồng, vì sự gian ác dư dật của ngươi, và sự hờn ghét lớn lắm."));
visuperobject.biblemap.put("b28_9_8", new visuperobject(28,9,8,"Ép-ra-im là kẻ rình nghịch cùng Ðức Chúa Trời ta; còn kẻ tiên tri là lưới bắt chim trên mọi đường lối mình, nó là sự ghen ghét trong nhà Ðức Chúa Trời mình."));
visuperobject.biblemap.put("b28_9_9", new visuperobject(28,9,9,"Chúng nó bại hoại rất sâu như đương những ngày Ghi-bê-a. Ðức Chúa Trời sẽ nhớ lại sự gian ác chúng nó, sẽ thăm phạt tội lỗi chúng nó."));
visuperobject.biblemap.put("b28_9_10", new visuperobject(28,9,10,"Ta đã gặp Y-sơ-ra-ên, như gặp trái nho trong đồng vắng; ta đã thấy tổ phụ các ngươi như trái chín đầu trên cây vả tơ. Nhưng chúng nó đã vào nơi Ba-anh-Phê-rô; dâng mình cho vật xấu hổ, và cũng trở nên gớm ghiếc như vật chúng nó đã yêu."));
visuperobject.biblemap.put("b28_9_11", new visuperobject(28,9,11,"Sự vinh hiển của Ép-ra-im sẽ bay đi như chim: sẽ không đẻ, không thai, không nghén nữa!"));
visuperobject.biblemap.put("b28_9_12", new visuperobject(28,9,12,"Vì dầu chúng nó được nuôi con cái, ta cũng cất lấy đi, đến nỗi không một người nam nào còn lại. Thật, khi ta lìa bỏ chúng nó, thì kinh niên thay cho chúng nó!"));
visuperobject.biblemap.put("b28_9_13", new visuperobject(28,9,13,"Ép-ra-im được trồng trong nơi xinh tốt, như ta đã xem thấy Ty-rơ; dầu vậy, Ép-ra-im sẽ dắt các con cái nó đến kẻ giết lát!"));
visuperobject.biblemap.put("b28_9_14", new visuperobject(28,9,14,"Hỡi Ðức Giê-hô-va, xin hãy ban cho chúng nó. Ngài sẽ cho chúng nó cái gì? Hãy cho chúng nó cái dạ sút sảo vào vú khô khan!"));
visuperobject.biblemap.put("b28_9_15", new visuperobject(28,9,15,"Cả sự hung ác chúng nó đều ở Ghinh-ganh; ấy tại đó mà ta ghét chúng nó. Vì cớ những việc ác chúng nó, ta sẽ đuổi chúng nó khỏi nhà ta; ta sẽ chẳng thương yêu chúng nó nữa. Hết thảy quan trưởng chúng nó là kẻ bạn nghịch."));
visuperobject.biblemap.put("b28_9_16", new visuperobject(28,9,16,"Ép-ra-im bị đánh; rễ nó đã khô. Chúng nó sẽ không ra trái nữa; dầu đẻ ra, ta cũng sẽ giết trái thương yêu của bụng chúng nó."));
visuperobject.biblemap.put("b28_9_17", new visuperobject(28,9,17,"Ðức Chúa Trời ta sẽ bỏ chúng nó, vì chúng nó không nghe Ngài; và chúng nó sẽ đi dông dài trong các nước."));
visuperobject.biblemap.put("b28_10_1", new visuperobject(28,10,1,"Y-sơ-ra-ên là một cây nho tươi tốt, sanh ra trái nó. Trái nó càng sai tríu chừng nào, nó càng thêm nhiều bàn thờ ra chừng nấy; đất nó càng tốt bao nhiêu, những trụ tượng nó lập lên càng đẹp bấy nhiêu."));
visuperobject.biblemap.put("b28_10_2", new visuperobject(28,10,2,"Lòng chúng nó phân hai; bây giờ chúng nó sẽ bị định tội. Ðức Chúa Trời sẽ đánh bàn thờ chúng nó; sẽ phá trụ tượng chúng nó."));
visuperobject.biblemap.put("b28_10_3", new visuperobject(28,10,3,"Chắc bây giờ chúng nó sẽ nói rằng: Chúng ta không có vua, vì chúng ta không kính sợ Ðức Giê-hô-va; và vua, vua có thể làm gì cho chúng ta?"));
visuperobject.biblemap.put("b28_10_4", new visuperobject(28,10,4,"Chúng nó nói những lời hư không và thề dối khi lập giao ước; cho nên sự đoán phạt sẽ nứt mầm, nhạy như có độc mọc lên trong luống cày nơi ruộng."));
visuperobject.biblemap.put("b28_10_5", new visuperobject(28,10,5,"Dân cư Sa-ma-ri sẽ kinh hãi vì những bò con của Bết-a-ven; dân sự sẽ vì nó than khóc, các thầy tế lễ nó vốn ưa thích nó cũng vậy, vì sự vinh hiển nó đã biến mất khỏi nó."));
visuperobject.biblemap.put("b28_10_6", new visuperobject(28,10,6,"Nó cũng được bị dời qua A-si-ri lảm lễ vật dâng cho vua Gia-rép. Bấy giờ Ép-ra-im sẽ mang xấu hổ, Y-sơ-ra-ên sẽ hổ thẹn về mưu kế mình."));
visuperobject.biblemap.put("b28_10_7", new visuperobject(28,10,7,"Về phần Sa-ma-ri, vua nó bị trừ đi giống như bọt trên mặt nước."));
visuperobject.biblemap.put("b28_10_8", new visuperobject(28,10,8,"Các nơi cao của A-ven, tức là tội lỗi của Y-sơ-ra-ên, sẽ bị phá hủy; gai gốc và chà chuôm sẽ mọc trên các bàn thờ chúng nó. Bấy giờ người ta sẽ nói cùng các núi rằng: Hãy bao bọc lấy chúng ta! và nói với các đồi rằng: Hãy đổ xuống trên chúng ta!"));
visuperobject.biblemap.put("b28_10_9", new visuperobject(28,10,9,"Hỡi Y-sơ-ra-ên, từ ngày Ghi-bê-a, ngươi đã phạm tội rồi! Chúng nó đều đứng đó; sự tranh chiến nghịch cùng con cái sự gian ác chẳng theo kịp chúng nó trong Ghi-bê-a."));
visuperobject.biblemap.put("b28_10_10", new visuperobject(28,10,10,"Ta sẽ sửa phạt chúng nó khi ta muốn, và các dân sẽ nhóm lại nghịch cùng chúng nó, khi chúng nó bị buộc vào hai tội mình."));
visuperobject.biblemap.put("b28_10_11", new visuperobject(28,10,11,"Ép-ra-im như bò cái tơ khéo dạy, ưa thích đạp lúa; nhưng ta đã qua trên cổ béo tốt nó. Ta sẽ đặt người cỡi trên Ép-ra-im; Giu-đa sẽ cày, và Gia-cốp sẽ đập vỡ cục đất."));
visuperobject.biblemap.put("b28_10_12", new visuperobject(28,10,12,"Hãy gieo cho mình trong sự công bình, hãy gặt theo sự nhơn từ; hãy vỡ đất mới! Vì là kỳ tìm kiếm Ðức Giê-hô-va, cho đến chừng nào Ngài đến và sa mưa công bình trên các ngươi."));
visuperobject.biblemap.put("b28_10_13", new visuperobject(28,10,13,"Các ngươi đã cày sự gian ác, gặt sự gian ác, ăn trái của sự nói dối; vì ngươi đã nhờ cậy trong đường lối ngươi, trong muôn vàn người mạnh bạo của ngươi."));
visuperobject.biblemap.put("b28_10_14", new visuperobject(28,10,14,"Vậy nên sự rối loạn sẽ sanh ra trong dân ngươi: người ta sẽ hủy phá mọi đồn lũy của ngươi, như San-man đã hủy phá Bết-Aït-bên, trong ngày có trận đánh mà mẹ bị nghiền nát với các con cái."));
visuperobject.biblemap.put("b28_10_15", new visuperobject(28,10,15,"Bê-tên cũng sẽ làm cho các ngươi như vậy, vì sự gian ác lớn lắm của các ngươi. Vua Y-sơ-ra-ên sẽ bị diệt cả trong khi hừng sáng."));
visuperobject.biblemap.put("b28_11_1", new visuperobject(28,11,1,"Khi Y-sơ-ra-ên còn thơ ấy, ta yêu dấu nó; ta gọi con trai ta ra khỏi Ê-díp-tô."));
visuperobject.biblemap.put("b28_11_2", new visuperobject(28,11,2,"Các tiên tri càng gọi nó chừng nào, nó càng trốn tránh chừng nấy. Chúng nó đã dâng của lễ cho các tượng Ba-anh, và đốt hương cho tượng chạm."));
visuperobject.biblemap.put("b28_11_3", new visuperobject(28,11,3,"Dầu vậy, ta đã dạy Ép-ra-im bước đi, lấy cánh tay mà nâng đỡ nó. Song chúng nó chẳng hiểu biết rằng ta đã chữa lành cho."));
visuperobject.biblemap.put("b28_11_4", new visuperobject(28,11,4,"Ta đã dùng dây nhơn tình, dùng xích yêu thương kéo chúng nó đến. Ta đã như những kẻ cởi ách khỏi hàm chúng nó, và để đồ ăn trước mặt chúng nó."));
visuperobject.biblemap.put("b28_11_5", new visuperobject(28,11,5,"Chúng nó sẽ không trở về trong đất Ê-díp-tô nữa, nhưng người A-si-ri sẽ làm vua chúng nó, vì chúng nó chẳng khứng trở lại với ta."));
visuperobject.biblemap.put("b28_11_6", new visuperobject(28,11,6,"Gươm sẽ rơi trên các thành chúng nó, hủy phá then cửa chúng nó, nuốt hết chúng nó, vì cớ mưu chước chúng nó."));
visuperobject.biblemap.put("b28_11_7", new visuperobject(28,11,7,"Thật, dân ta quyết ý trái bỏ ta. Người ta khuyên chúng nó đến cùng Ðấng cao; song trong chúng nó chẳng một người nào dấy lên."));
visuperobject.biblemap.put("b28_11_8", new visuperobject(28,11,8,"Hỡi Ép-ra-im, thể nào ta bỏ được ngươi? Hỡi Y-sơ-ra-ên, thể nào ta lìa được ngươi? Thể nào ta sẽ đãi ngươi được như Át-ma, hay là làm cho ngươi như Sê-bô-im? Lòng ta rung động trong ta; lòng thương xót của ta cả đều nóng nảy."));
visuperobject.biblemap.put("b28_11_9", new visuperobject(28,11,9,"Ta cầm sự nóng giận lại, và sẽ chẳng lại hủy diệt Ép-ra-im. Vì ta là Ðức Chúa Trời, không phải là người; ta là Ðấng Thánh ở giữa ngươi, chẳng lấy cơn giận đến cùng ngươi."));
visuperobject.biblemap.put("b28_11_10", new visuperobject(28,11,10,"Chúng nó sẽ theo sau Ðức Giê-hô-va, Ngài gầm thét như sư tử; Ngài sẽ gầm thét, các con cái sẽ từ phương tây run rẩy mà đến."));
visuperobject.biblemap.put("b28_11_11", new visuperobject(28,11,11,"Chúng nó sẽ run rẩy mà đến từ Ê-díp-tô như chim bay, và từ đất A-si-ri như bò câu; và ta sẽ khiến chúng nó ở trong các nhà chúng nó, Ðức Giê-hô-va phán vậy."));
visuperobject.biblemap.put("b28_11_12", new visuperobject(28,11,12,"(12:1) Ép-ra-im lấy sự nói dối bao bọc ta, còn nhà Y-sơ-ra-ên thì lấy sự lừa phỉnh; Giu-đa cai trị với Ðức Chúa Trời, và có lòng trung tín với Ðấng Thánh."));
visuperobject.biblemap.put("b28_12_1", new visuperobject(28,12,1,"(12:2) Ép-ra-im ăn gió, chạy theo sau gió đông. Mỗi ngày, nó thêm nhiều sự nói dối và sự hoang vu; nó lập giao ước với A-si-ri, và đem dầu vào Ê-díp-tô."));
visuperobject.biblemap.put("b28_12_2", new visuperobject(28,12,2,"(12:3) Ðức Giê-hô-va cũng có sự khẩn cầu với Giu-đa, và Ngài sẽ phạt Gia-cốp theo đường lối nó; Ngài sẽ báo trả nó theo việc nó lam."));
visuperobject.biblemap.put("b28_12_3", new visuperobject(28,12,3,"(12:4) Vừa lúc ở trong lòng mẹ, Gia-cốp nắm gót chơn anh mình; và đến tuổi trưởng thành, có quyền nơi Ðức Chúa Trời."));
visuperobject.biblemap.put("b28_12_4", new visuperobject(28,12,4,"(12:5) Người có quyền hơn thiên sứ, và được thắng; khóc lóc và khẩn cầu người. Ngài đã gặp người tại Bê-tên, và ấy đó là nơi Ngài phán cùng chúng ta,"));
visuperobject.biblemap.put("b28_12_5", new visuperobject(28,12,5,"(12:6) tức là Giê-hô-va Ðức Chúa Trời vạn quân; danh kỷ niệm Ngài là Ðức Giê-hô-va."));
visuperobject.biblemap.put("b28_12_6", new visuperobject(28,12,6,"(12:7) Vậy ngươi khá trở lại cùng Ðức Chúa Trời ngươi; giữ sự nhơn từ và sự công bình, luôn luôn trông đợi Ðức Chúa Trời ngươi."));
visuperobject.biblemap.put("b28_12_7", new visuperobject(28,12,7,"(12:8) Nó là người buôn bán cầm những cân dối trá trong tay mình; nó ưa gian lận."));
visuperobject.biblemap.put("b28_12_8", new visuperobject(28,12,8,"(12:9) Phải, Ép-ra-im nói rằng: Thật, ta đã trở nên giàu; ta đã được của cải. Trong mọi việc ta làm chẳng hề thấy một việc gian ác gì là tội lỗi."));
visuperobject.biblemap.put("b28_12_9", new visuperobject(28,12,9,"(12:10) Ta là Ðức Giê-hô-va, làm Ðức Chúa Trời ngươi từ khi ngươi ra khỏi đất Ê-díp-tô, ta sẽ còn làm cho ngươi dưới các trại như trong những ngày lễ trọng thể."));
visuperobject.biblemap.put("b28_12_10", new visuperobject(28,12,10,"(12:11) ta cũng đã phán cho các kẻ tiên tri; đã thêm nhiều sự hiện thấy và đã cậy chức vụ các kẻ tiên tri mà dùng thí dụ."));
visuperobject.biblemap.put("b28_12_11", new visuperobject(28,12,11,"(12:12) Ga-la-át là gian ác, chúng nó chỉ là giả dối. Chúng nó dâng những bò đực trong Ghinh-ganh; nên những bàn thờ chúng nó giống như những đống trong luống cày nơi ruộng."));
visuperobject.biblemap.put("b28_12_12", new visuperobject(28,12,12,"(12:13) Gia-cốp trốn đến ruộng A-ram; Y-sơ-ra-ên làm tôi để được vợ, và vì được vợ mà người chăn các bầy."));
visuperobject.biblemap.put("b28_12_13", new visuperobject(28,12,13,"(12:14) Ðoạn, Ðức Giê-hô-va nhờ một đấng tiên tri đem Y-sơ-ra-ên khỏi Ê-díp-tô; và nhờ đấng tiên tri gìn giữ nó."));
visuperobject.biblemap.put("b28_12_14", new visuperobject(28,12,14,"(12:15) Ép-ra-im chọc cho ta phát cơn giận đắng cay; nên máu nó sẽ đổ lại trên nó, và Chúa sẽ trả sự sỉ nhục cho nó nữa."));
visuperobject.biblemap.put("b28_13_1", new visuperobject(28,13,1,"Vừa khi Ép-ra-im nói ra, người ta run rẩy. Nó đã lên mình trong Y-sơ-ra-ên. Nhưng sau khi vì cớ Ba-anh mà phạm tội thì nó chết mất."));
visuperobject.biblemap.put("b28_13_2", new visuperobject(28,13,2,"Vả, bây giờ chúng nó cứ phạm tội càng ngày càng thêm; dùng bạc làm những tượng đúc cho mình, những hình tượng theo trí khôn mình; cả sự đó là công việc của thợ khéo! Người ta nói về chúng nó rằng: Ðể mặc kẻ dâng của lễ hôn bò con."));
visuperobject.biblemap.put("b28_13_3", new visuperobject(28,13,3,"Vậy nên, chúng nó sẽ giống như mây ban mai, như móc buổi sáng tan đi lúc sớm, như rơm rác bị gió lốc đùa khỏi sân đạp lúa, như khói bởi ống khói thoát ra!"));
visuperobject.biblemap.put("b28_13_4", new visuperobject(28,13,4,"Nhưng mà, ấy chính ta là Giê-hô-va Ðức Chúa Trời ngươi từ khi ngươi ra khỏi đất Ê-díp-tô, và ngoài ta, ngươi chớ nên nhận biết thần nào khác: ngoài ta không có đấng cứu nào khác!"));
visuperobject.biblemap.put("b28_13_5", new visuperobject(28,13,5,"Ta đã biết ngươi trong đồng vắng, trong đất khô khan."));
visuperobject.biblemap.put("b28_13_6", new visuperobject(28,13,6,"Chúng nó đã được no nê theo đồng cỏ; và được no nê rồi, thì chúng nó sanh lòng kiêu ngạo; vậy nên chúng nó đã quên ta."));
visuperobject.biblemap.put("b28_13_7", new visuperobject(28,13,7,"Vì thế, ta đối với chúng nó sẽ như là sư tử. Ta sẽ như con beo rình chúng nó trên đường."));
visuperobject.biblemap.put("b28_13_8", new visuperobject(28,13,8,"Ta sẽ vồ trên chúng nó như con gấu cái bị cướp mất con nó. Ta sẽ xé cái bọc lòng chúng nó, và sẽ nuốt chúng nó ở đó như sư tử cái. Thú rừng sẽ xé chúng nó."));
visuperobject.biblemap.put("b28_13_9", new visuperobject(28,13,9,"Hỡi Y-sơ-ra-ên, sự bại hoại của ngươi, ấy là tại ngươi dấy loạn nghịch cùng ta, tức là Ðấng giúp ngươi."));
visuperobject.biblemap.put("b28_13_10", new visuperobject(28,13,10,"Vậy vua ngươi ở đâu? hầu cho người giải cứu ngươi trong hết thảy các thành! nào những quan xét ngươi là những người mà ngươi nói với rằng: Hãy cho tôi một vua và các quan trưởng!"));
visuperobject.biblemap.put("b28_13_11", new visuperobject(28,13,11,"Ta đã nhơn cơn giận mà ban cho ngươi một vua, và đã nhơn cơn giận mà cất đi."));
visuperobject.biblemap.put("b28_13_12", new visuperobject(28,13,12,"Sự gian ác của Ép-ra-im đã ràng buộc, tội lỗi nó đã giấu để."));
visuperobject.biblemap.put("b28_13_13", new visuperobject(28,13,13,"Sự đau đớn của đờn bà đẻ sẽ đến trên nó. Nhưng nó là con trai không khôn ngoan; vì, đến kỳ rồi, nó không nên chậm trễ ở trong dạ con."));
visuperobject.biblemap.put("b28_13_14", new visuperobject(28,13,14,"Ta sẽ cứu chúng nó khỏi quyền lực của âm phủ, và chuộc chúng nó ra khỏi sự chết. Hỡi sự chết, nào tai vạ mầy ở đâu? Hỡi âm phủ, nào sự hủy hoại mầy ở đâu? ôi! sự ăn năn sẽ bị giấu khỏi mắt ta."));
visuperobject.biblemap.put("b28_13_15", new visuperobject(28,13,15,"Ví dầu Ép-ra-im có đậu trái giữa anh em nó, nhưng gió đông sự dậy; tức là hơi thở của Ðức Giê-hô-va lên từ đồng vắng, sẽ đến làm khô các suối và cạn các mạch nước. Kẻ nghịch sẽ cướp những kho tàng chứa mọi khí mạnh quí báu."));
visuperobject.biblemap.put("b28_13_16", new visuperobject(28,13,16,"Sa-ma-ri sẽ mang tội nó, vì nó đã dấy loạn nghịch cùng Ðức Chúa Trời mình! Chúng nó sẽ ngã bởi gươm; các con trẻ chúng nó sẽ bị dập nát, và những đờn bà của chúng nó có chửa sẽ bị mổ bụng."));
visuperobject.biblemap.put("b28_14_1", new visuperobject(28,14,1,"Hỡi Y-sơ-ra-ên, hãy trở lại cùng Giê-hô-va Ðức Chúa Trời ngươi, vì ấy là tại tội lỗi ngươi làm cho ngươi sa ngã."));
visuperobject.biblemap.put("b28_14_2", new visuperobject(28,14,2,"Các ngươi khá lấy lời nói trở lại cùng Ngài rằng: Xin cất mọi sự gian ác đi, và nhậm sự tốt lành, vậy chúng ta sẽ dâng lời ngợi khen ở môi chúng tôi thay vì con bò đực."));
visuperobject.biblemap.put("b28_14_3", new visuperobject(28,14,3,"A-si-ri sẽ không giải cứu chúng tôi, chúng tôi sẽ không cỡi ngựa chiến nữa, không nói với đồ bởi tay chúng tôi làm ra mà rằng: Các ngài là thần của chúng tôi! Vì ấy là trong Ngài mà kẻ mồ côi tìm thấy sự thương xót!"));
visuperobject.biblemap.put("b28_14_4", new visuperobject(28,14,4,"Ta sẽ chữa lành sự bội nghịch của chúng nó. Ta sẽ lấy lòng tốt yêu chúng nó; vì cơn giận của ta đã xây khỏi nó rồi."));
visuperobject.biblemap.put("b28_14_5", new visuperobject(28,14,5,"Ta sẽ như là sương móc cho Y-sơ-ra-ên; nó trổ hoa như bông huệ, và đâm rễ như Li-ban."));
visuperobject.biblemap.put("b28_14_6", new visuperobject(28,14,6,"Những nhánh nó giang ra tận xa; sự xinh tốt của nó sẽ giống như sự xinh tốt của cây ô-li-ve, mùi thơm của nó như mùi thơm của Li-ban."));
visuperobject.biblemap.put("b28_14_7", new visuperobject(28,14,7,"Những kẻ ngồi dưới bóng nó sẽ trở về; chúng nó sẽ tỉnh lại như cây lúa. Chúng nó sẽ trổ hoa như cây nho, và mùi thơm chúng nó sẽ như rượu Li-ban."));
visuperobject.biblemap.put("b28_14_8", new visuperobject(28,14,8,"Ép-ra-im sẽ nói: Ta với những thần tượng có sự thông đồng gì được nữa sao? Ta đã trả lời và sẽ đoái xem nó. Ta như là một cây tùng xanh; bởi ta mà sanh ra hoa trái ngươi."));
visuperobject.biblemap.put("b28_14_9", new visuperobject(28,14,9,"Ai là khôn ngoan mà hiểu những sự nầy? Ai là giỏi giang mà biết những sự đó? Vì các đường lối của Ðức Giê-hô-va là ngay thẳng; những kẻ công bình sẽ bước đi trong đó, còn những kẻ phạm phép thì vấp ngã trong đó."));

}

}