package ara.bible;

public class arabible21 {

public arabible21() {

putmapbible21();

}

private void putmapbible21() {

arasuperobject.biblemap.put("b21_1_1", new arasuperobject(21,1,1,"كلام الجامعة ابن داود الملك في اورشليم"));
arasuperobject.biblemap.put("b21_1_2", new arasuperobject(21,1,2,"باطل الاباطيل قال الجامعة. باطل الاباطيل الكل باطل"));
arasuperobject.biblemap.put("b21_1_3", new arasuperobject(21,1,3,"ما الفائدة للانسان من كل تعبه الذي يتعبه تحت الشمس"));
arasuperobject.biblemap.put("b21_1_4", new arasuperobject(21,1,4,"دور يمضي ودور يجيء والارض قائمة الى الابد"));
arasuperobject.biblemap.put("b21_1_5", new arasuperobject(21,1,5,"والشمس تشرق والشمس تغرب وتسرع الى موضعها حيث تشرق"));
arasuperobject.biblemap.put("b21_1_6", new arasuperobject(21,1,6,"الريح تذهب الى الجنوب وتدور الى الشمال. تذهب دائرة دورانا والى مداراتها ترجع الريح"));
arasuperobject.biblemap.put("b21_1_7", new arasuperobject(21,1,7,"كل الانهار تجري الى البحر والبحر ليس بملآن. الى المكان الذي جرت منه الانهار الى هناك تذهب راجعة"));
arasuperobject.biblemap.put("b21_1_8", new arasuperobject(21,1,8,"كل الكلام يقصر. لا يستطيع الانسان ان يخبر بالكل. العين لا تشبع من النظر والاذن لا تمتلئ من السمع"));
arasuperobject.biblemap.put("b21_1_9", new arasuperobject(21,1,9,"ما كان فهو ما يكون والذي صنع فهو الذي يصنع فليس تحت الشمس جديد"));
arasuperobject.biblemap.put("b21_1_10", new arasuperobject(21,1,10,"ان وجد شيء يقال عنه انظر. هذا جديد. فهو منذ زمان كان في الدهور التي كانت قبلنا"));
arasuperobject.biblemap.put("b21_1_11", new arasuperobject(21,1,11,"ليس ذكر للاولين. والآخرون ايضا الذين سيكونون لا يكون لهم ذكر عند الذين يكونون بعدهم"));
arasuperobject.biblemap.put("b21_1_12", new arasuperobject(21,1,12,"انا الجامعة كنت ملكا على اسرائيل في اورشليم"));
arasuperobject.biblemap.put("b21_1_13", new arasuperobject(21,1,13,"ووجهت قلبي للسؤال والتفتيش بالحكمة عن كل ما عمل تحت السموات. هو عناء رديء جعلها الله لبني البشر ليعنوا فيه"));
arasuperobject.biblemap.put("b21_1_14", new arasuperobject(21,1,14,"رأيت كل الاعمال التي عملت تحت الشمس فاذا الكل باطل وقبض الريح"));
arasuperobject.biblemap.put("b21_1_15", new arasuperobject(21,1,15,"الاعوج لا يمكن ان يقوّم والنقص لا يمكن ان يجبر"));
arasuperobject.biblemap.put("b21_1_16", new arasuperobject(21,1,16,"انا ناجيت قلبي قائلا ها انا قد عظمت وازددت حكمة اكثر من كل من كان قبلي على اورشليم وقد رأى قلبي كثيرا من الحكمة والمعرفة"));
arasuperobject.biblemap.put("b21_1_17", new arasuperobject(21,1,17,"ووجهت قلبي لمعرفة الحكمة ولمعرفة الحماقة والجهل. فعرفت ان هذا ايضا قبض الريح"));
arasuperobject.biblemap.put("b21_1_18", new arasuperobject(21,1,18,"لان في كثرة الحكمة كثرة الغم والذي يزيد علما يزيد حزنا"));
arasuperobject.biblemap.put("b21_2_1", new arasuperobject(21,2,1,"قلت انا في قلبي هلم امتحنك بالفرح فترى خيرا. واذا هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_2_2", new arasuperobject(21,2,2,"للضحك قلت مجنون وللفرح ماذا يفعل"));
arasuperobject.biblemap.put("b21_2_3", new arasuperobject(21,2,3,"افتكرت في قلبي ان اعلل جسدي بالخمر وقلبي يلهج بالحكمة وان آخذ بالحماقة حتى ارى ما هو الخير لبني البشر حتى يفعلوه تحت السموات مدة ايام حياتهم"));
arasuperobject.biblemap.put("b21_2_4", new arasuperobject(21,2,4,"فعظمت عملي. بنيت لنفسي بيوتا غرست لنفسي كروما"));
arasuperobject.biblemap.put("b21_2_5", new arasuperobject(21,2,5,"عملت لنفسي جنات وفراديس وغرست فيها اشجارا من كل نوع ثمر"));
arasuperobject.biblemap.put("b21_2_6", new arasuperobject(21,2,6,"عملت لنفسي برك مياه لتسقى بها المغارس المنبتة الشجر"));
arasuperobject.biblemap.put("b21_2_7", new arasuperobject(21,2,7,"قنيت عبيدا وجواري وكان لي ولدان البيت. وكانت لي ايضا قنية بقر وغنم اكثر من جميع الذين كانوا في اورشليم قبلي"));
arasuperobject.biblemap.put("b21_2_8", new arasuperobject(21,2,8,"جمعت لنفسي ايضا فضة وذهبا وخصوصيات الملوك والبلدان. اتخذت لنفسي مغنين ومغنيات وتنعمات بني البشر سيدة وسيدات"));
arasuperobject.biblemap.put("b21_2_9", new arasuperobject(21,2,9,"فعظمت وازددت اكثر من جميع الذين كانوا قبلي في اورشليم وبقيت ايضا حكمتي معي"));
arasuperobject.biblemap.put("b21_2_10", new arasuperobject(21,2,10,"ومهما اشتهته عيناي لم امسكه عنهما. لم امنع قلبي من كل فرح. لان قلبي فرح بكل تعبي وهذا كان نصيبي من كل تعبي"));
arasuperobject.biblemap.put("b21_2_11", new arasuperobject(21,2,11,"ثم التفت انا الى كل اعمالي التي عملتها يداي والى التعب الذي تعبته في عمله فاذا الكل باطل وقبض الريح ولا منفعة تحت الشمس"));
arasuperobject.biblemap.put("b21_2_12", new arasuperobject(21,2,12,"ثم التفت لانظر الحكمة والحماقة والجهل. فما الانسان الذي يأتي وراء الملك الذي نصبوه منذ زمان"));
arasuperobject.biblemap.put("b21_2_13", new arasuperobject(21,2,13,"فرأيت ان للحكمة منفعة اكثر من الجهل كما ان للنور منفعة اكثر من الظلمة"));
arasuperobject.biblemap.put("b21_2_14", new arasuperobject(21,2,14,"الحكيم عيناه في راسه. اما الجاهل فيسلك في الظلام. وعرفت انا ايضا ان حادثة واحدة تحدث لكليهما"));
arasuperobject.biblemap.put("b21_2_15", new arasuperobject(21,2,15,"فقلت في قلبي كما يحدث للجاهل كذلك يحدث ايضا لي انا. واذ ذاك فلماذا انا اوفر حكمة. فقلت في قلبي هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_2_16", new arasuperobject(21,2,16,"لانه ليس ذكر للحكيم ولا للجاهل الى الابد. كما منذ زمان كذا الايام الآتية الكل ينسى. وكيف يموت الحكيم. كالجاهل"));
arasuperobject.biblemap.put("b21_2_17", new arasuperobject(21,2,17,"فكرهت الحياة. لانه رديء عندي العمل الذي عمل تحت الشمس لان الكل باطل وقبض الريح"));
arasuperobject.biblemap.put("b21_2_18", new arasuperobject(21,2,18,"فكرهت كل تعبي الذي تعبت فيه تحت الشمس حيث اتركه للانسان الذي يكون بعدي"));
arasuperobject.biblemap.put("b21_2_19", new arasuperobject(21,2,19,"ومن يعلم هل يكون حكيما او جاهلا. ويستولي على كل تعبي الذي تعبت فيه واظهرت فيه حكمتي تحت الشمس. هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_2_20", new arasuperobject(21,2,20,"فتحولت لكي اجعل قلبي ييئس من كل التعب الذي تعبت فيه تحت الشمس"));
arasuperobject.biblemap.put("b21_2_21", new arasuperobject(21,2,21,"لانه قد يكون انسان تعبه بالحكمة والمعرفة وبالفلاح فيتركه نصيبا لانسان لم يتعب فيه. هذا ايضا باطل وشر عظيم"));
arasuperobject.biblemap.put("b21_2_22", new arasuperobject(21,2,22,"لانه ماذا للانسان من كل تعبه ومن اجتهاد قلبه الذي تعب فيه تحت الشمس"));
arasuperobject.biblemap.put("b21_2_23", new arasuperobject(21,2,23,"لان كل ايامه احزان وعمله غم. ايضا بالليل لا يستريح قلبه. هذا ايضا باطل هو"));
arasuperobject.biblemap.put("b21_2_24", new arasuperobject(21,2,24,"ليس للانسان خير من ان يأكل ويشرب ويري نفسه خيرا في تعبه. رأيت هذا ايضا انه من يد الله"));
arasuperobject.biblemap.put("b21_2_25", new arasuperobject(21,2,25,"لانه من يأكل ومن يلتذ غيري"));
arasuperobject.biblemap.put("b21_2_26", new arasuperobject(21,2,26,"لانه يؤتي الانسان الصالح قدامه حكمة ومعرفة وفرحا. اما الخاطئ فيعطيه شغل الجمع والتكويم ليعطي للصالح قدام الله. هذا ايضا باطل وقبض الريح"));
arasuperobject.biblemap.put("b21_3_1", new arasuperobject(21,3,1,"لكل شيء زمان ولكل امر تحت السموات وقت"));
arasuperobject.biblemap.put("b21_3_2", new arasuperobject(21,3,2,"للولادة وقت وللموت وقت. للغرس وقت ولقلع المغروس وقت"));
arasuperobject.biblemap.put("b21_3_3", new arasuperobject(21,3,3,"للقتل وقت وللشفاء وقت. للهدم وقت وللبناء وقت"));
arasuperobject.biblemap.put("b21_3_4", new arasuperobject(21,3,4,"للبكاء وقت وللضحك وقت. للنوح وقت وللرقص وقت"));
arasuperobject.biblemap.put("b21_3_5", new arasuperobject(21,3,5,"لتفريق الحجارة وقت ولجمع الحجارة وقت. للمعانقة وقت وللانفصال عن المعانقة وقت"));
arasuperobject.biblemap.put("b21_3_6", new arasuperobject(21,3,6,"للكسب وقت وللخسارة وقت. للصيانة وقت وللطرح وقت"));
arasuperobject.biblemap.put("b21_3_7", new arasuperobject(21,3,7,"للتمزيق وقت وللتخييط وقت للسكوت وقت وللتكلم وقت"));
arasuperobject.biblemap.put("b21_3_8", new arasuperobject(21,3,8,"للحب وقت وللبغضة وقت. للحرب وقت وللصلح وقت"));
arasuperobject.biblemap.put("b21_3_9", new arasuperobject(21,3,9,"فاي منفعة لمن يتعب مما يتعب به"));
arasuperobject.biblemap.put("b21_3_10", new arasuperobject(21,3,10,"قد رأيت الشغل الذي اعطاه الله بني البشر ليشتغلوا به"));
arasuperobject.biblemap.put("b21_3_11", new arasuperobject(21,3,11,"صنع الكل حسنا في وقته وايضا جعل الابدية في قلبهم التي بلاها لا يدرك الانسان العمل الذي يعمله الله من البداية الى النهاية"));
arasuperobject.biblemap.put("b21_3_12", new arasuperobject(21,3,12,"عرفت انه ليس لهم خير الا ان يفرحوا ويفعلوا خيرا في حياتهم"));
arasuperobject.biblemap.put("b21_3_13", new arasuperobject(21,3,13,"وايضا ان يأكل كل انسان ويشرب ويرى خيرا من كل تعبه فهو عطية الله"));
arasuperobject.biblemap.put("b21_3_14", new arasuperobject(21,3,14,"قد عرفت ان كل ما يعمله الله انه يكون الى الابد. لا شيء يزاد عليه ولا شيء ينقص منه وان الله عمله حتى يخافوا امامه"));
arasuperobject.biblemap.put("b21_3_15", new arasuperobject(21,3,15,"ما كان فمن القدم هو. وما يكون فمن القدم قد كان. والله يطلب ما قد مضى"));
arasuperobject.biblemap.put("b21_3_16", new arasuperobject(21,3,16,"وايضا رايت تحت الشمس موضع الحق هناك الظلم وموضع العدل هناك الجور"));
arasuperobject.biblemap.put("b21_3_17", new arasuperobject(21,3,17,"فقلت في قلبي الله يدين الصدّيق والشرير. لان لكل أمر ولكل عمل وقتا هناك"));
arasuperobject.biblemap.put("b21_3_18", new arasuperobject(21,3,18,"قلت في قلبي من جهة امور بني البشر ان الله يمتحنهم ليريهم انه كما البهيمة هكذا هم"));
arasuperobject.biblemap.put("b21_3_19", new arasuperobject(21,3,19,"لان ما يحدث لبني البشر يحدث للبهيمة وحادثة واحدة لهم. موت هذا كموت ذاك ونسمة واحدة للكل فليس للانسان مزية على البهيمة لان كليهما باطل"));
arasuperobject.biblemap.put("b21_3_20", new arasuperobject(21,3,20,"يذهب كلاهما الى مكان واحد. كان كلاهما من التراب والى التراب يعود كلاهما"));
arasuperobject.biblemap.put("b21_3_21", new arasuperobject(21,3,21,"من يعلم روح بني البشر هل هي تصعد الى فوق وروح البهيمة هل هي تنزل الى اسفل الى الارض"));
arasuperobject.biblemap.put("b21_3_22", new arasuperobject(21,3,22,"فرأيت انه لا شيء خير من ان يفرح الانسان باعماله لان ذلك نصيبه. لانه من يأتي به ليرى ما سيكون بعده"));
arasuperobject.biblemap.put("b21_4_1", new arasuperobject(21,4,1,"ثم رجعت ورأيت كل المظالم التي تجرى تحت الشمس فهوذا دموع المظلومين ولا معزّ لهم ومن يد ظالميهم قهر. اما هم فلا معزّ لهم"));
arasuperobject.biblemap.put("b21_4_2", new arasuperobject(21,4,2,"فغبطت انا الاموات الذين قد ماتوا منذ زمان اكثر من الاحياء الذين هم عائشون بعد"));
arasuperobject.biblemap.put("b21_4_3", new arasuperobject(21,4,3,"وخير من كليهما الذي لم يولد بعد الذي لم ير العمل الرديء الذي عمل تحت الشمس"));
arasuperobject.biblemap.put("b21_4_4", new arasuperobject(21,4,4,"ورأيت كل التعب وكل فلاح عمل انه حسد الانسان من قريبه. وهذا ايضا باطل وقبض الريح"));
arasuperobject.biblemap.put("b21_4_5", new arasuperobject(21,4,5,"الكسلان ياكل لحمه وهو طاو يديه"));
arasuperobject.biblemap.put("b21_4_6", new arasuperobject(21,4,6,"حفنة راحة خير من حفنتي تعب وقبض الريح"));
arasuperobject.biblemap.put("b21_4_7", new arasuperobject(21,4,7,"ثم عدت ورأيت باطلا تحت الشمس"));
arasuperobject.biblemap.put("b21_4_8", new arasuperobject(21,4,8,"يوجد واحد ولا ثاني له وليس له ابن ولا اخ ولا نهاية لكل تعبه ولا تشبع عينه من الغنى. فلمن اتعب انا واحرم نفسي الخير. هذا ايضا باطل وامر رديء هو"));
arasuperobject.biblemap.put("b21_4_9", new arasuperobject(21,4,9,"اثنان خير من واحد لان لهما اجرة لتعبهما صالحة"));
arasuperobject.biblemap.put("b21_4_10", new arasuperobject(21,4,10,"لانه ان وقع احدهما يقيمه رفيقه. وويل لمن هو وحده ان وقع اذ ليس ثان ليقيمه"));
arasuperobject.biblemap.put("b21_4_11", new arasuperobject(21,4,11,"ايضا ان اضطجع اثنان يكون لهما دفء. اما الوحد فكيف يدفأ"));
arasuperobject.biblemap.put("b21_4_12", new arasuperobject(21,4,12,"وان غلب احد على الواحد يقف مقابله الاثنان والخيط المثلوث لا ينقطع سريعا"));
arasuperobject.biblemap.put("b21_4_13", new arasuperobject(21,4,13,"ولد فقير وحكيم خير من ملك شيخ جاهل الذي لا يعرف ان يحذر بعد"));
arasuperobject.biblemap.put("b21_4_14", new arasuperobject(21,4,14,"لانه من السجن خرج الى الملك والمولود ملكا قد يفتقر"));
arasuperobject.biblemap.put("b21_4_15", new arasuperobject(21,4,15,"رأيت كل الاحياء السائرين تحت الشمس مع الولد الثاني الذي يقوم عوضا عنه"));
arasuperobject.biblemap.put("b21_4_16", new arasuperobject(21,4,16,"لا نهاية لكل الشعب لكل الذين كان امامهم. ايضا المتأخرون لا يفرحون به. فهذا ايضا باطل وقبض الريح"));
arasuperobject.biblemap.put("b21_5_1", new arasuperobject(21,5,1,"احفظ قدمك حين تذهب الى بيت الله فالاستماع اقرب من تقديم ذبيحة الجهال لانهم لا يبالون بفعل الشر"));
arasuperobject.biblemap.put("b21_5_2", new arasuperobject(21,5,2,"لا تستعجل فمك ولا يسرع قلبك الى نطق كلام قدام الله. لان الله في السموات وانت على الارض فلذلك لتكن كلماتك قليلة"));
arasuperobject.biblemap.put("b21_5_3", new arasuperobject(21,5,3,"لان الحلم يأتي من كثرة الشغل وقول الجهل من كثرة الكلام"));
arasuperobject.biblemap.put("b21_5_4", new arasuperobject(21,5,4,"اذا نذرت نذرا لله فلا تتأخر عن الوفاء به. لانه لا يسرّ بالجهال. فاوف بما نذرته"));
arasuperobject.biblemap.put("b21_5_5", new arasuperobject(21,5,5,"ان لا تنذر خير من ان تنذر ولا تفي"));
arasuperobject.biblemap.put("b21_5_6", new arasuperobject(21,5,6,"لا تدع فمك يجعل جسدك يخطئ. ولا تقل قدام الملاك انه سهو. لماذا يغضب الله على قولك ويفسد عمل يديك"));
arasuperobject.biblemap.put("b21_5_7", new arasuperobject(21,5,7,"لان ذلك من كثرة الاحلام والاباطيل وكثرة الكلام. ولكن اخش الله"));
arasuperobject.biblemap.put("b21_5_8", new arasuperobject(21,5,8,"ان رأيت ظلم الفقير ونزع الحق والعدل في البلاد فلا ترتع من الأمر. لان فوق العالي عاليا يلاحظ والاعلى فوقهما"));
arasuperobject.biblemap.put("b21_5_9", new arasuperobject(21,5,9,"ومنفعة الارض للكل. الملك مخدوم من الحقل"));
arasuperobject.biblemap.put("b21_5_10", new arasuperobject(21,5,10,"من يحب الفضة لا يشبع من الفضة ومن يحب الثروة لا يشبع من دخل. هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_5_11", new arasuperobject(21,5,11,"اذا كثرت الخيرات كثر الذين يأكلونها واي منفعة لصاحبها الا رؤيتها بعينيه"));
arasuperobject.biblemap.put("b21_5_12", new arasuperobject(21,5,12,"نوم المشتغل حلو ان اكل قليلا او كثيرا ووفر الغني لا يريحه حتى ينام"));
arasuperobject.biblemap.put("b21_5_13", new arasuperobject(21,5,13,"يوجد شر خبيث رأيته تحت الشمس. ثروة مصونة لصاحبها لضرره"));
arasuperobject.biblemap.put("b21_5_14", new arasuperobject(21,5,14,"فهلكت تلك الثروة بامر سيء ثم ولد ابنا وما بيده شيء"));
arasuperobject.biblemap.put("b21_5_15", new arasuperobject(21,5,15,"كما خرج من بطن امه عريانا يرجع ذاهبا كما جاء ولا يأخذ شيئا من تعبه فيذهب به في يده"));
arasuperobject.biblemap.put("b21_5_16", new arasuperobject(21,5,16,"وهذا ايضا مصيبة رديئة. في كل شيء كما جاء هكذا يذهب فايّة منفعة له للذي تعب للريح"));
arasuperobject.biblemap.put("b21_5_17", new arasuperobject(21,5,17,"ايضا يأكل كل ايامه في الظلام ويغتم كثيرا مع حزن وغيظ"));
arasuperobject.biblemap.put("b21_5_18", new arasuperobject(21,5,18,"هوذا الذي رأيته انا خيرا الذي هو حسن. ان يأكل الانسان ويشرب ويرى خيرا من كل تعبه الذي يتعب فيه تحت الشمس مدة ايام حياته التي اعطاه الله اياها لانه نصيبه"));
arasuperobject.biblemap.put("b21_5_19", new arasuperobject(21,5,19,"ايضا كل انسان اعطاه الله غنى ومالا وسلّطه عليه حتى ياكل منه وياخذ نصيبه ويفرح بتعبه فهذا هو عطية الله"));
arasuperobject.biblemap.put("b21_5_20", new arasuperobject(21,5,20,"لانه لا يذكر ايام حياته كثيرا لان الله ملهيه بفرح قلبه"));
arasuperobject.biblemap.put("b21_6_1", new arasuperobject(21,6,1,"يوجد شر قد رأيته تحت الشمس وهو كثير بين الناس"));
arasuperobject.biblemap.put("b21_6_2", new arasuperobject(21,6,2,"رجل اعطاه الله غنى ومالا وكرامة وليس لنفسه عوز من كل ما يشتهيه ولم يعطه الله استطاعة على ان يأكل منه بل يأكله انسان غريب. هذا باطل ومصيبة رديئة هو"));
arasuperobject.biblemap.put("b21_6_3", new arasuperobject(21,6,3,"ان ولد انسان مئة وعاش سنين كثيرة حتى تصير ايام سنيه كثيرة ولم تشبع نفسه من الخير وليس له ايضا دفن فاقول ان السقط خير منه"));
arasuperobject.biblemap.put("b21_6_4", new arasuperobject(21,6,4,"لانه في الباطل يجيء وفي الظلام يذهب واسمه يغطّى بالظلام"));
arasuperobject.biblemap.put("b21_6_5", new arasuperobject(21,6,5,"وايضا لم ير الشمس ولم يعلم. فهذا له راحة اكثر من ذاك"));
arasuperobject.biblemap.put("b21_6_6", new arasuperobject(21,6,6,"وان عاش الف سنة مضاعفة ولم ير خيرا أليس الى موضع واحد يذهب الجميع"));
arasuperobject.biblemap.put("b21_6_7", new arasuperobject(21,6,7,"كل تعب الانسان لفمه ومع ذلك فالنفس لا تمتلئ"));
arasuperobject.biblemap.put("b21_6_8", new arasuperobject(21,6,8,"لانه ماذا يبقى للحكيم اكثر من الجاهل. ماذا للفقير العارف السلوك امام الاحياء"));
arasuperobject.biblemap.put("b21_6_9", new arasuperobject(21,6,9,"رؤية العيون خير من شهوة النفس. هذا ايضا باطل وقبض الريح"));
arasuperobject.biblemap.put("b21_6_10", new arasuperobject(21,6,10,"الذي كان فقد دعي باسم منذ زمان وهو معروف انه انسان ولا يستطيع ان يخاصم من هو اقوى منه"));
arasuperobject.biblemap.put("b21_6_11", new arasuperobject(21,6,11,"لانه توجد امور كثيرة تزيد الباطل. فاي فضل للانسان"));
arasuperobject.biblemap.put("b21_6_12", new arasuperobject(21,6,12,"لانه من يعرف ما هو خير للانسان في الحياة مدة ايام حياة باطله التي يقضيها كالظل. لانه من يخبر الانسان بما يكون بعده تحت الشمس"));
arasuperobject.biblemap.put("b21_7_1", new arasuperobject(21,7,1,"الصيت خير من الدهن الطيّب ويوم الممات خير من يوم الولادة"));
arasuperobject.biblemap.put("b21_7_2", new arasuperobject(21,7,2,"الذهاب الى بيت النوح خير من الذهاب الى بيت الوليمة لان ذاك نهاية كل انسان والحي يضعه في قلبه"));
arasuperobject.biblemap.put("b21_7_3", new arasuperobject(21,7,3,"الحزن خير من الضحك لانه بكآبة الوجه يصلح القلب"));
arasuperobject.biblemap.put("b21_7_4", new arasuperobject(21,7,4,"قلب الحكماء في بيت النوح وقلب الجهال في بيت الفرح"));
arasuperobject.biblemap.put("b21_7_5", new arasuperobject(21,7,5,"سمع الانتهار من الحكيم خير للانسان من سمع غناء الجهال"));
arasuperobject.biblemap.put("b21_7_6", new arasuperobject(21,7,6,"لانه كصوت الشوك تحت القدر هكذا ضحك الجهال. هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_7_7", new arasuperobject(21,7,7,"لان الظلم يحمق الحكيم والعطية تفسد القلب"));
arasuperobject.biblemap.put("b21_7_8", new arasuperobject(21,7,8,"نهاية امر خير من بدايته. طول الروح خير من تكبر الروح"));
arasuperobject.biblemap.put("b21_7_9", new arasuperobject(21,7,9,"لا تسرع بروحك الى الغضب لان الغضب يستقر في حضن الجهال"));
arasuperobject.biblemap.put("b21_7_10", new arasuperobject(21,7,10,"لا تقل لماذا كانت الايام الاولى خيرا من هذه. لانه ليس عن حكمة تسأل عن هذا"));
arasuperobject.biblemap.put("b21_7_11", new arasuperobject(21,7,11,"الحكمة صالحة مثل الميراث بل افضل لناظري الشمس"));
arasuperobject.biblemap.put("b21_7_12", new arasuperobject(21,7,12,"لان الذي في ظل الحكمة هو في ظل الفضة وفضل المعرفة هو ان الحكمة تحيي اصحابها"));
arasuperobject.biblemap.put("b21_7_13", new arasuperobject(21,7,13,"انظر عمل الله لانه من يقدر على تقويم ما قد عوّجه"));
arasuperobject.biblemap.put("b21_7_14", new arasuperobject(21,7,14,"في يوم الخير كن بخير وفي يوم الشر اعتبر. ان الله جعل هذا مع ذاك لكيلا يجد الانسان شيئا بعده"));
arasuperobject.biblemap.put("b21_7_15", new arasuperobject(21,7,15,"قد رأيت الكل في ايام بطلي. قد يكون بار يبيد في بره وقد يكون شرير يطول في شره"));
arasuperobject.biblemap.put("b21_7_16", new arasuperobject(21,7,16,"لا تكن بارا كثيرا ولا تكن حكيما بزيادة. لماذا تخرب نفسك"));
arasuperobject.biblemap.put("b21_7_17", new arasuperobject(21,7,17,"لا تكن شريرا كثيرا ولا تكن جاهلا. لماذا تموت في غير وقتك"));
arasuperobject.biblemap.put("b21_7_18", new arasuperobject(21,7,18,"حسن ان تتمسك بهذا وايضا ان لا ترخي يدك عن ذاك. لان متقي الله يخرج منهما كليهما"));
arasuperobject.biblemap.put("b21_7_19", new arasuperobject(21,7,19,"الحكمة تقوي الحكيم اكثر من عشرة مسلطين الذين هم في المدينة"));
arasuperobject.biblemap.put("b21_7_20", new arasuperobject(21,7,20,"لانه لا انسان صدّيق في الارض يعمل صلاحا ولا يخطئ"));
arasuperobject.biblemap.put("b21_7_21", new arasuperobject(21,7,21,"ايضا لا تضع قلبك على كل الكلام الذي يقال لئلا تسمع عبدك يسبّك"));
arasuperobject.biblemap.put("b21_7_22", new arasuperobject(21,7,22,"لان قلبك ايضا يعلم انك انت كذلك مرارا كثيرة سببت آخرين"));
arasuperobject.biblemap.put("b21_7_23", new arasuperobject(21,7,23,"كل هذا امتحنته بالحكمة. قلت اكون حكيما. اما هي فبعيدة عني"));
arasuperobject.biblemap.put("b21_7_24", new arasuperobject(21,7,24,"بعيد ما كان بعيدا والعميق العميق من يجده"));
arasuperobject.biblemap.put("b21_7_25", new arasuperobject(21,7,25,"درت انا وقلبي لأعلم ولأبحث ولأطلب حكمة وعقلا ولاعرف الشر انه جهالة والحماقة انها جنون"));
arasuperobject.biblemap.put("b21_7_26", new arasuperobject(21,7,26,"فوجدت امرّ من الموت المرأة التي هي شباك وقلبها اشراك ويداها قيود. الصالح قدام الله ينجو منها. اما الخاطئ فيؤخذ بها"));
arasuperobject.biblemap.put("b21_7_27", new arasuperobject(21,7,27,"انظر. هذا وجدته قال الجامعة. واحدة فواحدة لاجد النتيجة"));
arasuperobject.biblemap.put("b21_7_28", new arasuperobject(21,7,28,"التي لم تزل نفسي تطلبها فلم اجدها. رجلا واحدا بين الف وجدت. اما امرأة فبين كل اولئك لم اجد"));
arasuperobject.biblemap.put("b21_7_29", new arasuperobject(21,7,29,"انظر. هذا وجدت فقط ان الله صنع الانسان مستقيما. اما هم فطلبوا اختراعات كثيرة"));
arasuperobject.biblemap.put("b21_8_1", new arasuperobject(21,8,1,"من كالحكيم ومن يفهم تفسير امر. حكمة الانسان تنير وجهه وصلابة وجهه تتغيّر"));
arasuperobject.biblemap.put("b21_8_2", new arasuperobject(21,8,2,"انا اقول احفظ امر الملك وذلك بسبب يمين الله"));
arasuperobject.biblemap.put("b21_8_3", new arasuperobject(21,8,3,"لا تعجل الى الذهاب من وجهه. لا تقف في أمر شاق لانه يفعل كل ما شاء"));
arasuperobject.biblemap.put("b21_8_4", new arasuperobject(21,8,4,"حيث تكون كلمة الملك فهناك سلطان. ومن يقول له ماذا تفعل"));
arasuperobject.biblemap.put("b21_8_5", new arasuperobject(21,8,5,"حافظ الوصية لا يشعر بامر شاق وقلب الحكيم يعرف الوقت والحكم"));
arasuperobject.biblemap.put("b21_8_6", new arasuperobject(21,8,6,"لان لكل أمر وقتا وحكما لان شر الانسان عظيم عليه"));
arasuperobject.biblemap.put("b21_8_7", new arasuperobject(21,8,7,"لانه لا يعلم ما سيكون. لانه من يخبره كيف يكون"));
arasuperobject.biblemap.put("b21_8_8", new arasuperobject(21,8,8,"ليس لانسان سلطان على الروح ليمسك الروح ولا سلطان على يوم الموت ولا تخلية في الحرب ولا ينجي الشر اصحابه"));
arasuperobject.biblemap.put("b21_8_9", new arasuperobject(21,8,9,"كل هذا رأيته اذ وجهت قلبي لكل عمل عمل تحت الشمس وقتما يتسلط انسان على انسان لضرر نفسه"));
arasuperobject.biblemap.put("b21_8_10", new arasuperobject(21,8,10,"وهكذا رأيت اشرارا يدفنون وضمّوا والذين عملوا بالحق ذهبوا من مكان القدس ونسوا في المدينة. هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_8_11", new arasuperobject(21,8,11,"لان القضاء على العمل الرديء لا يجرى سريعا فلذلك قد امتلأ قلب بني البشر فيهم لفعل الشر"));
arasuperobject.biblemap.put("b21_8_12", new arasuperobject(21,8,12,"الخاطئ وان عمل شرا مئة مرة وطالت ايامه الا اني اعلم انه يكون خير للمتقين الله الذين يخافون قدامه"));
arasuperobject.biblemap.put("b21_8_13", new arasuperobject(21,8,13,"ولا يكون خير للشرير وكالظل لا يطيل ايامه لانه لا يخشى قدام الله"));
arasuperobject.biblemap.put("b21_8_14", new arasuperobject(21,8,14,"يوجد باطل يجرى على الارض. ان يوجد صديقون يصيبهم مثل عمل الاشرار ويوجد اشرار يصيبهم مثل عمل الصديقين. فقلت ان هذا ايضا باطل"));
arasuperobject.biblemap.put("b21_8_15", new arasuperobject(21,8,15,"فمدحت الفرح لانه ليس للانسان خير تحت الشمس الا ان يأكل ويشرب ويفرح وهذا يبقى له في تعبه مدة ايام حياته التي يعطيه الله اياها تحت الشمس"));
arasuperobject.biblemap.put("b21_8_16", new arasuperobject(21,8,16,"لما وجهت قلبي لاعرف الحكمة وانظر العمل الذي عمل على الارض وانه نهارا وليلا لا يرى النوم بعينيه"));
arasuperobject.biblemap.put("b21_8_17", new arasuperobject(21,8,17,"رأيت كل عمل الله ان الانسان لا يستطيع ان يجد العمل الذي عمل تحت الشمس. مهما تعب الانسان في الطلب فلا يجده والحكيم ايضا وان قال بمعرفته لا يقدر ان يجده"));
arasuperobject.biblemap.put("b21_9_1", new arasuperobject(21,9,1,"لان هذا كله جعلته في قلبي وامتحنت هذا كله ان الصديقين والحكماء واعمالهم في يد الله. الانسان لا يعلم حبا ولا بغضا. الكل امامهم"));
arasuperobject.biblemap.put("b21_9_2", new arasuperobject(21,9,2,"الكل على ما للكل. حادثة واحدة للصديق وللشرير للصالح وللطاهر وللنجس. للذابح وللذي لا يذبح. كالصالح الخاطئ. الحالف كالذي يخاف الحلف"));
arasuperobject.biblemap.put("b21_9_3", new arasuperobject(21,9,3,"هذا اشر كل ما عمل تحت الشمس ان حادثة واحدة للجميع وايضا قلب بني البشر ملآن من الشر والحماقة في قلبهم وهم احياء وبعد ذلك يذهبون الى الاموات"));
arasuperobject.biblemap.put("b21_9_4", new arasuperobject(21,9,4,"لانه من يستثنى. لكل الاحياء يوجد رجاء فان الكلب الحي خير من الاسد الميت"));
arasuperobject.biblemap.put("b21_9_5", new arasuperobject(21,9,5,"لان الاحياء يعلمون انهم سيموتون. اما الموتى فلا يعلمون شيئا وليس لهم اجر بعد لان ذكرهم نسي"));
arasuperobject.biblemap.put("b21_9_6", new arasuperobject(21,9,6,"ومحبتهم وبغضتهم وحسدهم هلكت منذ زمان ولا نصيب لهم الى الابد في كل ما عمل تحت الشمس"));
arasuperobject.biblemap.put("b21_9_7", new arasuperobject(21,9,7,"اذهب كل خبزك بفرح واشرب خمرك بقلب طيب لان الله منذ زمان قد رضي عملك"));
arasuperobject.biblemap.put("b21_9_8", new arasuperobject(21,9,8,"لتكن ثيابك في كل حين بيضاء ولا يعوز راسك الدهن"));
arasuperobject.biblemap.put("b21_9_9", new arasuperobject(21,9,9,"التذّ عيشا مع المرأة التي احببتها كل ايام حياة باطلك التي اعطاك اياها تحت الشمس كل ايام باطلك لان ذلك نصيبك في الحياة وفي تعبك الذي تتعبه تحت الشمس"));
arasuperobject.biblemap.put("b21_9_10", new arasuperobject(21,9,10,"كل ما تجده يدك لتفعله فافعله بقوتك لانه ليس من عمل ولا اختراع ولا معرفة ولا حكمة في الهاوية التي انت ذاهب اليها"));
arasuperobject.biblemap.put("b21_9_11", new arasuperobject(21,9,11,"فعدت ورأيت تحت الشمس ان السعي ليس للخفيف ولا الحرب للاقوياء ولا الخبز للحكماء ولا الغنى للفهماء ولا النعمة لذوي المعرفة لانه الوقت والعرض يلاقيانهم كافة"));
arasuperobject.biblemap.put("b21_9_12", new arasuperobject(21,9,12,"لان الانسان ايضا لا يعرف وقته. كالاسماك التي تؤخذ بشبكة مهلكة وكالعصافير التي تؤخذ بالشرك كذلك تقتنص بنو البشر في وقت شر اذ يقع عليهم بغتة"));
arasuperobject.biblemap.put("b21_9_13", new arasuperobject(21,9,13,"هذه الحكمة رايتها ايضا تحت الشمس وهي عظيمة عندي"));
arasuperobject.biblemap.put("b21_9_14", new arasuperobject(21,9,14,"مدينة صغيرة فيها اناس قليلون. فجاء عليها ملك عظيم وحاصرها وبنى عليها ابراجا عظيمة"));
arasuperobject.biblemap.put("b21_9_15", new arasuperobject(21,9,15,"ووجد فيها رجل مسكين حكيم فنجى هو المدينة بحكمته. وما احد ذكر ذلك الرجل المسكين"));
arasuperobject.biblemap.put("b21_9_16", new arasuperobject(21,9,16,"فقلت الحكمة خير من القوة اما حكمة المسكين فمحتقرة وكلامه لا يسمع"));
arasuperobject.biblemap.put("b21_9_17", new arasuperobject(21,9,17,"كلمات الحكماء تسمع في الهدوء اكثر من صراخ المتسلط بين الجهال"));
arasuperobject.biblemap.put("b21_9_18", new arasuperobject(21,9,18,"الحكمة خير من ادوات الحرب. اما خاطئ واحد فيفسد خيرا جزيلا"));
arasuperobject.biblemap.put("b21_10_1", new arasuperobject(21,10,1,"الذباب الميت ينتن ويخمر طيب العطّار. جهالة قليلة اثقل من الحكمة ومن الكرامة"));
arasuperobject.biblemap.put("b21_10_2", new arasuperobject(21,10,2,"قلب الحكيم عن يمينه وقلب الجاهل عن يساره"));
arasuperobject.biblemap.put("b21_10_3", new arasuperobject(21,10,3,"ايضا اذا مشى الجاهل في الطريق ينقص فهمه ويقول لكل واحد انه جاهل"));
arasuperobject.biblemap.put("b21_10_4", new arasuperobject(21,10,4,"ان صعدت عليك روح المتسلط فلا تترك مكانك لان الهدوء يسكّن خطايا عظيمة"));
arasuperobject.biblemap.put("b21_10_5", new arasuperobject(21,10,5,"يوجد شر رأيته تحت الشمس كسهو صادر من قبل المتسلط"));
arasuperobject.biblemap.put("b21_10_6", new arasuperobject(21,10,6,"الجهالة جعلت في معالي كثيرة والاغنياء يجلسون في السافل"));
arasuperobject.biblemap.put("b21_10_7", new arasuperobject(21,10,7,"قد رأيت عبيدا على الخيل ورؤساء ماشين على الارض كالعبيد"));
arasuperobject.biblemap.put("b21_10_8", new arasuperobject(21,10,8,"من يحفر هوة يقع فيها ومن ينقض جدارا تلدغه حية"));
arasuperobject.biblemap.put("b21_10_9", new arasuperobject(21,10,9,"من يقلع حجارة يوجع بها. من يشقق حطبا يكون في خطر منه"));
arasuperobject.biblemap.put("b21_10_10", new arasuperobject(21,10,10,"ان كلّ الحديد ولم يسنن هو حده فليزد القوة. اما الحكمة فنافعة للانجاح"));
arasuperobject.biblemap.put("b21_10_11", new arasuperobject(21,10,11,"ان لدغت الحية بلا رقية فلا منفعة للراقي"));
arasuperobject.biblemap.put("b21_10_12", new arasuperobject(21,10,12,"كلمات فم الحكيم نعمة وشفتا الجاهل تبتلعانه"));
arasuperobject.biblemap.put("b21_10_13", new arasuperobject(21,10,13,"ابتداء كلام فمه جهالة وآخر فمه جنون رديء"));
arasuperobject.biblemap.put("b21_10_14", new arasuperobject(21,10,14,"والجاهل يكثر الكلام. لا يعلم انسان ما يكون وماذا يصير بعده من يخبره"));
arasuperobject.biblemap.put("b21_10_15", new arasuperobject(21,10,15,"تعب الجهلاء يعييهم لانه لا يعلم كيف يذهب الى المدينة"));
arasuperobject.biblemap.put("b21_10_16", new arasuperobject(21,10,16,"ويل لك ايتها الارض اذا كان ملكك ولدا ورؤساؤك ياكلون في الصباح"));
arasuperobject.biblemap.put("b21_10_17", new arasuperobject(21,10,17,"طوبى لك ايتها الارض اذا كان ملكك ابن شرفاء ورؤساؤك يأكلون في الوقت للقوة لا للسكر"));
arasuperobject.biblemap.put("b21_10_18", new arasuperobject(21,10,18,"بالكسل الكثير يهبط السقف وبتدلي اليدين يكف البيت"));
arasuperobject.biblemap.put("b21_10_19", new arasuperobject(21,10,19,"للضحك يعملون وليمة والخمر تفرح العيش اما الفضة فتحصّل الكل"));
arasuperobject.biblemap.put("b21_10_20", new arasuperobject(21,10,20,"لا تسبّ الملك ولا في فكرك. ولا تسبّ الغني في مضجعك. لان طير السماء ينقل الصوت وذو الجناح يخبر بالامر"));
arasuperobject.biblemap.put("b21_11_1", new arasuperobject(21,11,1,"ارم خبزك على وجه المياه فانك تجده بعد ايام كثيرة"));
arasuperobject.biblemap.put("b21_11_2", new arasuperobject(21,11,2,"اعط نصيبا لسبعة ولثمانية ايضا لانك لست تعلم اي شر يكون على الارض"));
arasuperobject.biblemap.put("b21_11_3", new arasuperobject(21,11,3,"اذا امتلأت السحب مطرا تريقه على الارض. واذا وقعت الشجرة نحو الجنوب او نحو الشمال ففي الموضع حيث تقع الشجرة هناك تكون"));
arasuperobject.biblemap.put("b21_11_4", new arasuperobject(21,11,4,"من يرصد الريح لا يزرع ومن يراقب السحب لا يحصد"));
arasuperobject.biblemap.put("b21_11_5", new arasuperobject(21,11,5,"كما انك لست تعلم ما هي طريق الريح ولا كيف العظام في بطن الحبلى كذلك لا تعلم اعمال الله الذي يصنع الجميع"));
arasuperobject.biblemap.put("b21_11_6", new arasuperobject(21,11,6,"في الصباح ازرع زرعك وفي المساء لا ترخ يدك لانك لا تعلم ايهما ينمو هذا او ذاك او ان يكون كلاهما جيدين سواء"));
arasuperobject.biblemap.put("b21_11_7", new arasuperobject(21,11,7,"النور حلو وخير للعينين ان تنظرا الشمس"));
arasuperobject.biblemap.put("b21_11_8", new arasuperobject(21,11,8,"لانه ان عاش الانسان سنين كثيرة فليفرح فيها كلها وليتذكر ايام الظلمة لانها تكون كثيرة. كل ما ياتي باطل"));
arasuperobject.biblemap.put("b21_11_9", new arasuperobject(21,11,9,"افرح ايها الشاب في حداثتك وليسرّك قلبك في ايام شبابك واسلك في طرق قلبك وبمرأى عينيك واعلم انه على هذه الأمور كلها يأتي بك الله الى الدينونة"));
arasuperobject.biblemap.put("b21_11_10", new arasuperobject(21,11,10,"فانزع الغم من قلبك وابعد الشر عن لحمك لان الحداثة والشباب باطلان"));
arasuperobject.biblemap.put("b21_12_1", new arasuperobject(21,12,1,"فاذكر خالقك في ايام شبابك قبل ان تأتي ايام الشر او تجيء السنون اذ تقول ليس لي فيها سرور"));
arasuperobject.biblemap.put("b21_12_2", new arasuperobject(21,12,2,"قبلما تظلم الشمس والنور والقمر والنجوم وترجع السحب بعد المطر"));
arasuperobject.biblemap.put("b21_12_3", new arasuperobject(21,12,3,"في يوم يتزعزع فيه حفظة البيت وتتلوى رجال القوة وتبطل الطواحن لانها قلّت وتظلم النواظر من الشبابيك"));
arasuperobject.biblemap.put("b21_12_4", new arasuperobject(21,12,4,"وتغلق الابواب في السوق. حين ينخفض صوت المطحنة ويقوم لصوت العصفور وتحط كل بنات الغناء"));
arasuperobject.biblemap.put("b21_12_5", new arasuperobject(21,12,5,"وايضا يخافون من العالي وفي الطريق اهوال واللوز يزهر والجندب يستثقل والشهوة تبطل لان الانسان ذاهب الى بيته الابدي والنادبون يطوفون في السوق"));
arasuperobject.biblemap.put("b21_12_6", new arasuperobject(21,12,6,"قبلما ينفصم حبل الفضة او ينسحق كوز الذهب او تنكسر الجرة على العين او تنقصف البكرة عند البئر"));
arasuperobject.biblemap.put("b21_12_7", new arasuperobject(21,12,7,"فيرجع التراب الى الارض كما كان وترجع الروح الى الله الذي اعطاها"));
arasuperobject.biblemap.put("b21_12_8", new arasuperobject(21,12,8,"باطل الاباطيل قال الجامعة الكل باطل"));
arasuperobject.biblemap.put("b21_12_9", new arasuperobject(21,12,9,"بقي ان الجامعة كان حكيما وايضا علّم الشعب علما ووزن وبحث واتقن امثالا كثيرة"));
arasuperobject.biblemap.put("b21_12_10", new arasuperobject(21,12,10,"الجامعة طلب ان يجد كلمات مسرة مكتوبة بالاستقامة كلمات حق"));
arasuperobject.biblemap.put("b21_12_11", new arasuperobject(21,12,11,"كلام الحكماء كالمناسيس وكاوتاد منغرزة ارباب الجماعات قد أعطيت من راع واحد"));
arasuperobject.biblemap.put("b21_12_12", new arasuperobject(21,12,12,"وبقي فمن هذا يا ابني تحذر. لعمل كتب كثيرة لا نهاية والدرس الكثير تعب للجسد"));
arasuperobject.biblemap.put("b21_12_13", new arasuperobject(21,12,13,"فلنسمع ختام الأمر كله. اتّق الله واحفظ وصاياه لان هذا هو الانسان كله"));
arasuperobject.biblemap.put("b21_12_14", new arasuperobject(21,12,14,"لان الله يحضر كل عمل الى الدينونة على كل خفي ان كان خيرا او شرا"));

}

}