package ara.bible;

public class arabible7 {

public arabible7() {

putmapbible7();

}

private void putmapbible7() {

arasuperobject.biblemap.put("b7_1_1", new arasuperobject(7,1,1,"وكان بعد موت يشوع ان بني اسرائيل سألوا الرب قائلين من منّا يصعد الى الكنعانيين اولا لمحاربتهم"));
arasuperobject.biblemap.put("b7_1_2", new arasuperobject(7,1,2,"فقال الرب يهوذا يصعد. هوذا قد دفعت الارض ليده"));
arasuperobject.biblemap.put("b7_1_3", new arasuperobject(7,1,3,"فقال يهوذا لشمعون اخيه اصعد معي في قرعتي لكي نحارب الكنعانيين فاصعد انا ايضا معك في قرعتك. فذهب شمعون معه"));
arasuperobject.biblemap.put("b7_1_4", new arasuperobject(7,1,4,"فصعد يهوذا. ودفع الرب الكنعانيين والفرزّيين بيدهم فضربوا منهم في بازق عشرة آلاف رجل"));
arasuperobject.biblemap.put("b7_1_5", new arasuperobject(7,1,5,"ووجدوا ادوني بازق في بازق فحاربوه وضربوا الكنعانيين والفرزّيين"));
arasuperobject.biblemap.put("b7_1_6", new arasuperobject(7,1,6,"فهرب ادوني بازق. فتبعوه وامسكوه وقطعوا أباهم يديه ورجليه"));
arasuperobject.biblemap.put("b7_1_7", new arasuperobject(7,1,7,"فقال ادوني بازق سبعون ملكا مقطوعة أباهم ايديهم وارجلهم كانوا يلتقطون تحت مائدتي. كما فعلت كذلك جازاني الله. وأتوا به الى اورشليم فمات هناك"));
arasuperobject.biblemap.put("b7_1_8", new arasuperobject(7,1,8,"وحارب بنو يهوذا اورشليم واخذوها وضربوها بحد السيف واشعلوا المدينة بالنار"));
arasuperobject.biblemap.put("b7_1_9", new arasuperobject(7,1,9,"وبعد ذلك نزل بنو يهوذا لمحاربة الكنعانيين سكان الجبل والجنوب والسهل"));
arasuperobject.biblemap.put("b7_1_10", new arasuperobject(7,1,10,"وسار يهوذا على الكنعانيين الساكنين في حبرون. وكان اسم حبرون قبلا قرية اربع. وضربوا شيشاي واخيمان وتلماي"));
arasuperobject.biblemap.put("b7_1_11", new arasuperobject(7,1,11,"وسار من هناك على سكان دبير. واسم دبير قبلا قرية سفر"));
arasuperobject.biblemap.put("b7_1_12", new arasuperobject(7,1,12,"فقال كالب. الذي يضرب قرية سفر وياخذها اعطيه عكسة ابنتي امرأة"));
arasuperobject.biblemap.put("b7_1_13", new arasuperobject(7,1,13,"فأخذها عثنيئيل بن قناز اخو كالب الاصغر منه. فاعطاه عكسة ابنته امرأة"));
arasuperobject.biblemap.put("b7_1_14", new arasuperobject(7,1,14,"وكان عند دخولها انها غرّته بطلب حقل من ابيها. فنزلت عن الحمار فقال لها كالب ما لك"));
arasuperobject.biblemap.put("b7_1_15", new arasuperobject(7,1,15,"فقالت له اعطني بركة. لانك اعطيتني ارض الجنوب فاعطني ينابيع ماء. فاعطاها كالب الينابيع العليا والينابيع السفلى"));
arasuperobject.biblemap.put("b7_1_16", new arasuperobject(7,1,16,"وبنو القيني حمي موسى صعدوا من مدينة النخل مع بني يهوذا الى برية يهوذا التي في جنوبي عراد وذهبوا وسكنوا مع الشعب"));
arasuperobject.biblemap.put("b7_1_17", new arasuperobject(7,1,17,"وذهب يهوذا مع شمعون اخيه وضربوا الكنعانيين سكان صفاة وحرّموها ودعوا اسم المدينة حرمة"));
arasuperobject.biblemap.put("b7_1_18", new arasuperobject(7,1,18,"واخذ يهوذا غزة وتخومها واشقلون وتخومها وعقرون وتخومها"));
arasuperobject.biblemap.put("b7_1_19", new arasuperobject(7,1,19,"وكان الرب مع يهوذا فملك الجبل ولكن لم يطرد سكان الوادي لان لهم مركبات حديد"));
arasuperobject.biblemap.put("b7_1_20", new arasuperobject(7,1,20,"واعطوا لكالب حبرون كما تكلم موسى. فطرد من هناك بني عناق الثلاثة"));
arasuperobject.biblemap.put("b7_1_21", new arasuperobject(7,1,21,"وبنو بنيامين لم يطردوا اليبوسيين سكان اورشليم فسكن اليبوسيون مع بني بنيامين في اورشليم الى هذا اليوم"));
arasuperobject.biblemap.put("b7_1_22", new arasuperobject(7,1,22,"وصعد بيت يوسف ايضا الى بيت ايل والرب معهم"));
arasuperobject.biblemap.put("b7_1_23", new arasuperobject(7,1,23,"واستكشف بيت يوسف عن بيت ايل. وكان اسم المدينة قبلا لوز"));
arasuperobject.biblemap.put("b7_1_24", new arasuperobject(7,1,24,"فرأى المراقبون رجلا خارجا من المدينة فقالوا له ارنا مدخل المدينة فنعمل معك معروفا"));
arasuperobject.biblemap.put("b7_1_25", new arasuperobject(7,1,25,"فأراهم مدخل المدينة فضربوا المدينة بحد السيف واما الرجل وكل عشيرته فاطلقوهم"));
arasuperobject.biblemap.put("b7_1_26", new arasuperobject(7,1,26,"فانطلق الرجل الى ارض الحثيين وبنى مدينة ودعا اسمها لوز وهو اسمها الى هذا اليوم"));
arasuperobject.biblemap.put("b7_1_27", new arasuperobject(7,1,27,"ولم يطرد منسّى اهل بيت شان وقراها ولا اهل تعنك وقراها ولا سكان دور وقراها ولا سكان يبلعام وقراها ولا سكان مجدو وقراها. فعزم الكنعانيون على السكن في تلك الارض"));
arasuperobject.biblemap.put("b7_1_28", new arasuperobject(7,1,28,"وكان لما تشدد اسرائيل انه وضع الكنعانيين تحت الجزية ولم يطردهم طردا"));
arasuperobject.biblemap.put("b7_1_29", new arasuperobject(7,1,29,"وافرايم لم يطرد الكنعانيين الساكنين في جازر فسكن الكنعانيون في وسطه في جازر"));
arasuperobject.biblemap.put("b7_1_30", new arasuperobject(7,1,30,"زبولون لم يطرد سكان قطرون ولا سكان نهلول فسكن الكنعانيون في وسطه وكانوا تحت الجزية"));
arasuperobject.biblemap.put("b7_1_31", new arasuperobject(7,1,31,"ولم يطرد اشير سكان عكّو ولا سكان صيدون واحلب واكزيب وحلبة وافيق ورحوب"));
arasuperobject.biblemap.put("b7_1_32", new arasuperobject(7,1,32,"فسكن الاشيريون في وسط الكنعانيين سكان الارض لانهم لم يطردوهم"));
arasuperobject.biblemap.put("b7_1_33", new arasuperobject(7,1,33,"ونفتالي لم يطرد سكان بيت شمس ولا سكان بيت عناة بل سكن في وسط الكنعانيين سكان الارض. فكان سكان بيت شمس وبيت عناة تحت الجزية لهم"));
arasuperobject.biblemap.put("b7_1_34", new arasuperobject(7,1,34,"وحصر الاموريون بني دان في الجبل لانهم لم يدعوهم ينزلون الى الوادي"));
arasuperobject.biblemap.put("b7_1_35", new arasuperobject(7,1,35,"فعزم الاموريون على السكن في جبل حارس في أيلون وفي شعلبيم. وقويت يد بيت يوسف فكانوا تحت الجزية"));
arasuperobject.biblemap.put("b7_1_36", new arasuperobject(7,1,36,"وكان تخم الاموريين من عقبة عقربّيم من سالع فصاعدا"));
arasuperobject.biblemap.put("b7_2_1", new arasuperobject(7,2,1,"وصعد ملاك الرب من الجلجال الى بوكيم وقال. قد اصعدتكم من مصر وأتيت بكم الى الارض التي اقسمت لآبائكم وقلت لا انكث عهدي معكم الى الابد"));
arasuperobject.biblemap.put("b7_2_2", new arasuperobject(7,2,2,"وانتم فلا تقطعوا عهدا مع سكان هذه الارض. اهدموا مذابحهم. ولم تسمعوا لصوتي. فماذا عملتم"));
arasuperobject.biblemap.put("b7_2_3", new arasuperobject(7,2,3,"فقلت ايضا لا اطردهم من امامكم بل يكونون لكم مضايقين وتكون آلهتهم لكم شركا"));
arasuperobject.biblemap.put("b7_2_4", new arasuperobject(7,2,4,"وكان لما تكلم ملاك الرب بهذا الكلام الى جميع بني اسرائيل ان الشعب رفعوا صوتهم وبكوا"));
arasuperobject.biblemap.put("b7_2_5", new arasuperobject(7,2,5,"فدعوا اسم ذلك المكان بوكيم. وذبحوا هناك للرب"));
arasuperobject.biblemap.put("b7_2_6", new arasuperobject(7,2,6,"وصرف يشوع الشعب فذهب بنو اسرائيل كل واحد الى ملكه لاجل امتلاك الارض"));
arasuperobject.biblemap.put("b7_2_7", new arasuperobject(7,2,7,"وعبد الشعب الرب كل ايام يشوع وكل ايام الشيوخ الذين طالت ايامهم بعد يشوع الذين رأوا كل عمل الرب العظيم الذي عمل لاسرائيل"));
arasuperobject.biblemap.put("b7_2_8", new arasuperobject(7,2,8,"ومات يشوع بن نون عبد الرب ابن مئة وعشر سنين"));
arasuperobject.biblemap.put("b7_2_9", new arasuperobject(7,2,9,"فدفنوه في تخم ملكه في تمنة حارس في جبل افرايم شمالي جبل جاعش"));
arasuperobject.biblemap.put("b7_2_10", new arasuperobject(7,2,10,"وكل ذلك الجيل ايضا انضم الى آبائه وقام بعدهم جيل آخر لم يعرف الرب ولا العمل الذي عمل لاسرائيل"));
arasuperobject.biblemap.put("b7_2_11", new arasuperobject(7,2,11,"وفعل بنو اسرائيل الشر في عيني الرب وعبدوا البعليم"));
arasuperobject.biblemap.put("b7_2_12", new arasuperobject(7,2,12,"وتركوا الرب اله آبائهم الذي اخرجهم من ارض مصر وساروا وراء آلهة اخرى من آلهة الشعوب الذين حولهم وسجدوا لها واغاظوا الرب"));
arasuperobject.biblemap.put("b7_2_13", new arasuperobject(7,2,13,"تركوا الرب وعبدوا البعل وعشتاروث"));
arasuperobject.biblemap.put("b7_2_14", new arasuperobject(7,2,14,"فحمي غضب الرب على اسرائيل فدفعهم بايدي ناهبين نهبوهم وباعهم بيد اعدائهم حولهم ولم يقدروا بعد على الوقوف امام اعدائهم"));
arasuperobject.biblemap.put("b7_2_15", new arasuperobject(7,2,15,"حيثما خرجوا كانت يد الرب عليهم للشر كما تكلم الرب وكما اقسم الرب لهم. فضاق بهم الامر جدا"));
arasuperobject.biblemap.put("b7_2_16", new arasuperobject(7,2,16,"واقام الرب قضاة فخلصوهم من يد ناهبيهم"));
arasuperobject.biblemap.put("b7_2_17", new arasuperobject(7,2,17,"ولقضاتهم ايضا لم يسمعوا بل زنوا وراء آلهة اخرى وسجدوا لها. حادوا سريعا عن الطريق التي سار بها آباؤهم لسمع وصايا الرب. لم يفعلوا هكذا"));
arasuperobject.biblemap.put("b7_2_18", new arasuperobject(7,2,18,"وحينما اقام الرب لهم قضاة كان الرب مع القاضي وخلّصهم من يد اعدائهم كل ايام القاضي. لان الرب ندم من اجل انينهم بسبب مضايقيهم وزاحميهم"));
arasuperobject.biblemap.put("b7_2_19", new arasuperobject(7,2,19,"وعند موت القاضي كانوا يرجعون ويفسدون اكثر من آبائهم بالذهاب وراء آلهة اخرى ليعبدوها ويسجدوا لها. لم يكفّوا عن افعالهم وطريقهم القاسية"));
arasuperobject.biblemap.put("b7_2_20", new arasuperobject(7,2,20,"فحمي غضب الرب على اسرائيل وقال من اجل ان هذا الشعب قد تعدّوا عهدي الذي اوصيت به آباءهم ولم يسمعوا لصوتي"));
arasuperobject.biblemap.put("b7_2_21", new arasuperobject(7,2,21,"فانا ايضا لا اعود اطرد انسانا من امامهم من الامم الذين تركهم يشوع عند موته"));
arasuperobject.biblemap.put("b7_2_22", new arasuperobject(7,2,22,"لكي امتحن بهم اسرائيل أيحفظون طريق الرب ليسلكوا بها كما حفظها آباؤهم ام لا"));
arasuperobject.biblemap.put("b7_2_23", new arasuperobject(7,2,23,"فترك الرب اولئك الامم ولم يطردهم سريعا ولم يدفعهم بيد يشوع"));
arasuperobject.biblemap.put("b7_3_1", new arasuperobject(7,3,1,"فهؤلاء هم الامم الذين تركهم الرب ليمتحن بهم اسرائيل كل الذين لم يعرفوا جميع حروب كنعان"));
arasuperobject.biblemap.put("b7_3_2", new arasuperobject(7,3,2,"انما لمعرفة اجيال بني اسرائيل لتعليمهم الحرب. الذين لم يعرفوها قبل فقط"));
arasuperobject.biblemap.put("b7_3_3", new arasuperobject(7,3,3,"اقطاب الفلسطينيين الخمسة وجميع الكنعانيين والصيدونيين والحوّيين سكان جبل لبنان من جبل بعل حرمون الى مدخل حماة"));
arasuperobject.biblemap.put("b7_3_4", new arasuperobject(7,3,4,"كانوا لامتحان اسرائيل بهم لكي يعلم هل يسمعون وصايا الرب التي اوصى بها آباءهم عن يد موسى"));
arasuperobject.biblemap.put("b7_3_5", new arasuperobject(7,3,5,"فسكن بنو اسرائيل في وسط الكنعانيين والحثّيين والاموريين والفرزّيين والحوّيين واليبوسيين"));
arasuperobject.biblemap.put("b7_3_6", new arasuperobject(7,3,6,"واتخذوا بناتهم لانفسهم نساء واعطوا بناتهم لبنيهم وعبدوا آلهتهم"));
arasuperobject.biblemap.put("b7_3_7", new arasuperobject(7,3,7,"فعمل بنو اسرائيل الشر في عيني الرب ونسوا الرب الههم وعبدوا البعليم والسواري"));
arasuperobject.biblemap.put("b7_3_8", new arasuperobject(7,3,8,"فحمي غضب الرب على اسرائيل فباعهم بيد كوشان رشعتايم ملك ارام النهرين. فعبد بنو اسرائيل كوشان رشعتايم ثماني سنين"));
arasuperobject.biblemap.put("b7_3_9", new arasuperobject(7,3,9,"وصرخ بنو اسرائيل الى الرب فاقام الرب مخلّصا لبني اسرائيل فخلصهم. عثنيئيل بن قناز اخا كالب الاصغر"));
arasuperobject.biblemap.put("b7_3_10", new arasuperobject(7,3,10,"فكان عليه روح الرب وقضى لاسرائيل وخرج للحرب فدفع الرب ليده كوشان رشعتايم ملك ارام واعتزت يده على كوشان رشعتايم"));
arasuperobject.biblemap.put("b7_3_11", new arasuperobject(7,3,11,"واستراحت الارض اربعين سنة. ومات عثنيئيل بن قناز"));
arasuperobject.biblemap.put("b7_3_12", new arasuperobject(7,3,12,"وعاد بنو اسرائيل يعملون الشر في عيني الرب فشدد الرب عجلون ملك موآب على اسرائيل لانهم عملوا الشر في عيني الرب"));
arasuperobject.biblemap.put("b7_3_13", new arasuperobject(7,3,13,"فجمع اليه بني عمون وعماليق وسار وضرب اسرائيل وامتلكوا مدينة النخل"));
arasuperobject.biblemap.put("b7_3_14", new arasuperobject(7,3,14,"فعبد بنو اسرائيل عجلون ملك موآب ثماني عشرة سنة"));
arasuperobject.biblemap.put("b7_3_15", new arasuperobject(7,3,15,"وصرخ بنو اسرائيل الى الرب فاقام لهم الرب مخلّصا اهود بن جيرا البنياميني رجلا اعسر. فارسل بنو اسرائيل بيده هدية لعجلون ملك موآب"));
arasuperobject.biblemap.put("b7_3_16", new arasuperobject(7,3,16,"فعمل اهود لنفسه سيفا ذا حدين طوله ذراع وتقلده تحت ثيابه على فخذه اليمنى"));
arasuperobject.biblemap.put("b7_3_17", new arasuperobject(7,3,17,"وقدم الهدية لعجلون ملك موآب. وكان عجلون رجلا سمينا جدا"));
arasuperobject.biblemap.put("b7_3_18", new arasuperobject(7,3,18,"وكان لما انتهى من تقديم الهدية صرف القوم حاملي الهدية"));
arasuperobject.biblemap.put("b7_3_19", new arasuperobject(7,3,19,"واما هو فرجع من عند المنحوتات التي لدى الجلجال وقال. لي كلام سرّ اليك ايها الملك. فقال صه. وخرج من عنده جميع الواقفين لديه"));
arasuperobject.biblemap.put("b7_3_20", new arasuperobject(7,3,20,"فدخل اليه اهود وهو جالس في علية برود كانت له وحده. وقال اهود. عندي كلام الله اليك. فقام عن الكرسي"));
arasuperobject.biblemap.put("b7_3_21", new arasuperobject(7,3,21,"فمدّ اهود يده اليسرى واخذ السيف عن فخذه اليمنى وضربه في بطنه"));
arasuperobject.biblemap.put("b7_3_22", new arasuperobject(7,3,22,"فدخل القائم ايضا وراء النصل وطبق الشحم وراء النصل لانه لم يجذب السيف من بطنه. وخرج من الحتار"));
arasuperobject.biblemap.put("b7_3_23", new arasuperobject(7,3,23,"فخرج اهود من الرواق واغلق ابواب العلية وراءه واقفلها"));
arasuperobject.biblemap.put("b7_3_24", new arasuperobject(7,3,24,"ولما خرج جاء عبيده ونظروا واذا ابواب العلية مقفلة فقالوا انه مغط رجليه في مخدع البرود"));
arasuperobject.biblemap.put("b7_3_25", new arasuperobject(7,3,25,"فلبثوا حتى خجلوا واذا هو لا يفتح ابواب العلية فاخذوا المفتاح وفتحوا واذا سيدهم ساقط على الارض ميتا"));
arasuperobject.biblemap.put("b7_3_26", new arasuperobject(7,3,26,"واما اهود فنجا اذ هم مبهوتون وعبر المنحوتات ونجا الى سعيرة"));
arasuperobject.biblemap.put("b7_3_27", new arasuperobject(7,3,27,"وكان عند مجيئه انه ضرب بالبوق في جبل افرايم فنزل معه بنو اسرائيل عن الجبل وهو قدامهم"));
arasuperobject.biblemap.put("b7_3_28", new arasuperobject(7,3,28,"وقال لهم اتبعوني لان الرب قد دفع اعداءكم الموآبيين ليدكم فنزلوا وراءه واخذوا مخاوض الاردن الى موآب ولم يدعوا احدا يعبر"));
arasuperobject.biblemap.put("b7_3_29", new arasuperobject(7,3,29,"فضربوا من موآب في ذلك الوقت نحو عشرة آلاف رجل كل نشيط وكل ذي بأس ولم ينج احد"));
arasuperobject.biblemap.put("b7_3_30", new arasuperobject(7,3,30,"فذلّ الموآبيون في ذلك اليوم تحت يد اسرائيل. واستراحت الارض ثمانين سنة"));
arasuperobject.biblemap.put("b7_3_31", new arasuperobject(7,3,31,"وكان بعده شمجر بن عناة فضرب من الفلسطينيين ست مئة رجل بمنساس البقر وهو ايضا خلص اسرائيل"));
arasuperobject.biblemap.put("b7_4_1", new arasuperobject(7,4,1,"وعاد بنو اسرائيل يعملون الشر في عيني الرب بعد موت اهود"));
arasuperobject.biblemap.put("b7_4_2", new arasuperobject(7,4,2,"فباعهم الرب بيد يابين ملك كنعان الذي ملك في حاصور. ورئيس جيشه سيسرا وهو ساكن في حروشة الامم"));
arasuperobject.biblemap.put("b7_4_3", new arasuperobject(7,4,3,"فصرخ بنو اسرائيل الى الرب لانه كان له تسع مئة مركبة من حديد وهو ضايق بني اسرائيل بشدة عشرين سنة"));
arasuperobject.biblemap.put("b7_4_4", new arasuperobject(7,4,4,"ودبورة امرأة نبية زوجة لفيدوت هي قاضية اسرائيل في ذلك الوقت"));
arasuperobject.biblemap.put("b7_4_5", new arasuperobject(7,4,5,"وهي جالسة تحت نخلة دبورة بين الرامة وبيت ايل في جبل افرايم. وكان بنو اسرائيل يصعدون اليها للقضاء"));
arasuperobject.biblemap.put("b7_4_6", new arasuperobject(7,4,6,"فارسلت ودعت باراق بن ابينوعم من قادش نفتالي وقالت له ألم يامر الرب اله اسرائيل. اذهب وازحف الى جبل تابور وخذ معك عشرة آلاف رجل من بني نفتالي ومن بني زبولون"));
arasuperobject.biblemap.put("b7_4_7", new arasuperobject(7,4,7,"فأجذب اليك الى نهر قيشون سيسرا رئيس جيش يابين بمركباته وجمهوره وأدفعه ليدك"));
arasuperobject.biblemap.put("b7_4_8", new arasuperobject(7,4,8,"فقال لها باراق ان ذهبت معي اذهب. وان لم تذهبي معي فلا اذهب"));
arasuperobject.biblemap.put("b7_4_9", new arasuperobject(7,4,9,"فقالت اني اذهب معك غير انه لا يكون لك فخر في الطريق التي انت سائر فيها. لان الرب يبيع سيسرا بيد امرأة. فقامت دبورة وذهبت مع باراق الى قادش"));
arasuperobject.biblemap.put("b7_4_10", new arasuperobject(7,4,10,"ودعا باراق زبولون ونفتالي الى قادش وصعد ومعه عشرة آلاف رجل. وصعدت دبورة معه"));
arasuperobject.biblemap.put("b7_4_11", new arasuperobject(7,4,11,"وحابر القيني انفرد من قاين من بني حوباب حمي موسى وخيّم حتى الى بلوطة في صعنايم التي عند قادش"));
arasuperobject.biblemap.put("b7_4_12", new arasuperobject(7,4,12,"واخبروا سيسرا بانه قد صعد باراق بن ابينوعم الى جبل تابور"));
arasuperobject.biblemap.put("b7_4_13", new arasuperobject(7,4,13,"فدعا سيسرا جميع مركباته تسع مئة مركبة من حديد وجميع الشعب الذين معه من حروشة الامم الى نهر قيشون"));
arasuperobject.biblemap.put("b7_4_14", new arasuperobject(7,4,14,"فقالت دبورة لباراق قم. لان هذا هو اليوم الذي دفع فيه الرب سيسرا ليدك. ألم يخرج الرب قدامك. فنزل باراق من جبل تابور ووراءه عشرة آلاف رجل"));
arasuperobject.biblemap.put("b7_4_15", new arasuperobject(7,4,15,"فازعج الرب سيسرا وكل المركبات وكل الجيش بحد السيف امام باراق. فنزل سيسرا عن المركبة وهرب على رجليه"));
arasuperobject.biblemap.put("b7_4_16", new arasuperobject(7,4,16,"وتبع باراق المركبات والجيش الى حروشة الامم. وسقط كل جيش سيسرا بحد السيف لم يبق ولا واحد"));
arasuperobject.biblemap.put("b7_4_17", new arasuperobject(7,4,17,"واما سيسرا فهرب على رجليه الى خيمة ياعيل امرأة حابر القيني. لانه كان صلح بين يابين ملك حاصور وبيت حابر القيني"));
arasuperobject.biblemap.put("b7_4_18", new arasuperobject(7,4,18,"فخرجت ياعيل لاستقبال سيسرا وقالت له مل يا سيدي مل اليّ. لا تخف. فمال اليها الى الخيمة وغطته باللحاف"));
arasuperobject.biblemap.put("b7_4_19", new arasuperobject(7,4,19,"فقال لها اسقيني قليل ماء لاني قد عطشت. ففتحت وطب اللبن واسقته ثم غطته"));
arasuperobject.biblemap.put("b7_4_20", new arasuperobject(7,4,20,"فقال لها قفي بباب الخيمة ويكون اذا جاء احد وسألك أهنا رجل انك تقولين لا"));
arasuperobject.biblemap.put("b7_4_21", new arasuperobject(7,4,21,"فأخذت ياعيل امرأة حابر وتد الخيمة وجعلت الميتدة في يدها وقارت اليه وضربت الوتد في صدغه فنفذ الى الارض وهو متثقل في النوم ومتعب فمات"));
arasuperobject.biblemap.put("b7_4_22", new arasuperobject(7,4,22,"واذا بباراق يطارد سيسرا فخرجت ياعيل لاستقباله وقالت له تعال فاريك الرجل الذي انت طالبه. فجاء اليها واذا سيسرا ساقط ميتا والوتد في صدغه"));
arasuperobject.biblemap.put("b7_4_23", new arasuperobject(7,4,23,"فاذل الله في ذلك اليوم يابين ملك كنعان امام بني اسرائيل"));
arasuperobject.biblemap.put("b7_4_24", new arasuperobject(7,4,24,"واخذت يد بني اسرائيل تتزايد وتقسو على يابين ملك كنعان حتى قرضوا يابين ملك كنعان"));
arasuperobject.biblemap.put("b7_5_1", new arasuperobject(7,5,1,"فترنمت دبورة وباراق بن ابينوعم في ذلك اليوم قائلين"));
arasuperobject.biblemap.put("b7_5_2", new arasuperobject(7,5,2,"لاجل قيادة القواد في اسرائيل لاجل انتداب الشعب باركوا الرب"));
arasuperobject.biblemap.put("b7_5_3", new arasuperobject(7,5,3,"اسمعوا ايها الملوك واصغوا ايها العظماء. انا انا للرب اترنم. ازمّر للرب اله اسرائيل"));
arasuperobject.biblemap.put("b7_5_4", new arasuperobject(7,5,4,"يا رب بخروجك من سعير بصعودك من صحراء ادوم الارض ارتعدت. السموات ايضا قطرت. كذلك السحب قطرت ماء"));
arasuperobject.biblemap.put("b7_5_5", new arasuperobject(7,5,5,"تزلزلت الجبال من وجه الرب وسيناء هذا من وجه الرب اله اسرائيل"));
arasuperobject.biblemap.put("b7_5_6", new arasuperobject(7,5,6,"في ايام شمجر بن عناة في ايام ياعيل استراحت الطرق وعابرو السبل ساروا في مسالك معوجة"));
arasuperobject.biblemap.put("b7_5_7", new arasuperobject(7,5,7,"خذل الحكام في اسرائيل. خذلوا حتى قمت انا دبورة. قمت أمّا في اسرائيل"));
arasuperobject.biblemap.put("b7_5_8", new arasuperobject(7,5,8,"اختار آلهة حديثة. حينئذ حرب الابواب. هل كان يرى مجنّ او رمح في اربعين الفا من اسرائيل"));
arasuperobject.biblemap.put("b7_5_9", new arasuperobject(7,5,9,"قلبي نحو قضاة اسرائيل المنتدبين في الشعب. باركوا الرب"));
arasuperobject.biblemap.put("b7_5_10", new arasuperobject(7,5,10,"ايها الراكبون الاتن الصحر الجالسون على طنافس والسالكون في الطريق سبحوا"));
arasuperobject.biblemap.put("b7_5_11", new arasuperobject(7,5,11,"من صوت المحاصّين بين الاحواض هناك يثنون على حق الرب حق حكامه في اسرائيل. حينئذ نزل شعب الرب الى الابواب"));
arasuperobject.biblemap.put("b7_5_12", new arasuperobject(7,5,12,"استيقظي استيقظي يا دبورة استيقظي استيقظي وتكلمي بنشيد. قم يا باراق واسب سبيك يا ابن ابينوعم"));
arasuperobject.biblemap.put("b7_5_13", new arasuperobject(7,5,13,"حينئذ تسلط الشارد على عظماء الشعب. الرب سلّطني على الجبابرة"));
arasuperobject.biblemap.put("b7_5_14", new arasuperobject(7,5,14,"جاء من افرايم الذين مقرهم بين عماليق وبعدك بنيامين مع قومك. من ماكير نزل قضاة. ومن زبولون ماسكون بقضيب القائد"));
arasuperobject.biblemap.put("b7_5_15", new arasuperobject(7,5,15,"والرؤساء في يساكر مع دبورة وكما يساكر هكذا باراق. اندفع الى الوادي وراءه. على مساقي رأوبين اقضية قلب عظيمة"));
arasuperobject.biblemap.put("b7_5_16", new arasuperobject(7,5,16,"لماذا اقمت بين الحظائر لسمع الصفير للقطعان. لدى مساقي رأوبين مباحث قلب عظيمة"));
arasuperobject.biblemap.put("b7_5_17", new arasuperobject(7,5,17,"جلعاد في عبر الاردن سكن. ودان لماذا استوطن لدى السفن واشير اقام على ساحل البحر وفي فرضه سكن"));
arasuperobject.biblemap.put("b7_5_18", new arasuperobject(7,5,18,"زبولون شعب اهان نفسه الى الموت مع نفتالي على روابي الحقل"));
arasuperobject.biblemap.put("b7_5_19", new arasuperobject(7,5,19,"جاء ملوك. حاربوا. حينئذ حارب ملوك كنعان في تعنك على مياه مجدو. بضع فضة لم ياخذوا"));
arasuperobject.biblemap.put("b7_5_20", new arasuperobject(7,5,20,"من السموات حاربوا. الكواكب من حبكها حاربت سيسرا"));
arasuperobject.biblemap.put("b7_5_21", new arasuperobject(7,5,21,"نهر قيشون جرفهم. نهر وقائع نهر قيشون. دوسي يا نفسي بعزّ"));
arasuperobject.biblemap.put("b7_5_22", new arasuperobject(7,5,22,"حينئذ ضربت اعقاب الخيل من السوق سوق اقويائه"));
arasuperobject.biblemap.put("b7_5_23", new arasuperobject(7,5,23,"العنوا ميروز قال ملاك الرب. العنوا ساكنيها لعنا. لانهم لم ياتوا لمعونة الرب معونة الرب بين الجبابرة"));
arasuperobject.biblemap.put("b7_5_24", new arasuperobject(7,5,24,"تبارك على النساء ياعيل امرأة حابر القيني. على النساء في الخيام تبارك"));
arasuperobject.biblemap.put("b7_5_25", new arasuperobject(7,5,25,"طلب ماء فاعطته لبنا. في قصعة العظماء قدمت زبدة"));
arasuperobject.biblemap.put("b7_5_26", new arasuperobject(7,5,26,"مدت يدها الى الوتد ويمينها الى مضراب العملة وضربت سيسرا وسحقت راسه شدخت وخرقت صدغه"));
arasuperobject.biblemap.put("b7_5_27", new arasuperobject(7,5,27,"بين رجليها انطرح سقط اضطجع. بين رجليها انطرح سقط. حيث انطرح فهناك سقط مقتولا"));
arasuperobject.biblemap.put("b7_5_28", new arasuperobject(7,5,28,"من الكوّة اشرفت وولولت ام سيسرا من الشباك. لماذا ابطأت مركباته عن المجيء. لماذا تاخرت خطوات مراكبه"));
arasuperobject.biblemap.put("b7_5_29", new arasuperobject(7,5,29,"فاجابتها احكم سيداتها بل هي ردت جوابا لنفسها"));
arasuperobject.biblemap.put("b7_5_30", new arasuperobject(7,5,30,"ألم يجدوا ويقسموا الغنيمة. فتاة او فتاتين لكل رجل. غنيمة ثياب مصبوغة لسيسرا. غنيمة ثياب مصبوغة مطرزة. ثياب مصبوغة مطرزة الوجهين غنيمة لعنقي"));
arasuperobject.biblemap.put("b7_5_31", new arasuperobject(7,5,31,"هكذا يبيد جميع اعدائك يا رب. واحباؤه كخروج الشمس في جبروتها واستراحت الارض اربعين سنة"));
arasuperobject.biblemap.put("b7_6_1", new arasuperobject(7,6,1,"وعمل بنو اسرائيل الشر في عيني الرب فدفعهم الرب ليد مديان سبع سنين"));
arasuperobject.biblemap.put("b7_6_2", new arasuperobject(7,6,2,"فاعتزّت يد مديان على اسرائيل. بسبب المديانيين عمل بنو اسرائيل لانفسهم الكهوف التي في الجبال والمغاير والحصون"));
arasuperobject.biblemap.put("b7_6_3", new arasuperobject(7,6,3,"واذا زرع اسرائيل كان يصعد المديانيون والعمالقة وبنو المشرق يصعدون عليهم"));
arasuperobject.biblemap.put("b7_6_4", new arasuperobject(7,6,4,"وينزلون عليهم ويتلفون غلة الارض الى مجيئك الى غزة ولا يتركون لاسرائيل قوت الحياة ولا غنما ولا بقرا ولا حميرا"));
arasuperobject.biblemap.put("b7_6_5", new arasuperobject(7,6,5,"لانهم كانوا يصعدون بمواشيهم وخيامهم ويجيئون كالجراد في الكثرة وليس لهم ولجمالهم عدد. ودخلوا الارض لكي يخربوها"));
arasuperobject.biblemap.put("b7_6_6", new arasuperobject(7,6,6,"فذلّ اسرائيل جدا من قبل المديانيين. وصرخ بنو اسرائيل الى الرب"));
arasuperobject.biblemap.put("b7_6_7", new arasuperobject(7,6,7,"وكان لما صرخ بنو اسرائيل الى الرب بسبب المديانيين"));
arasuperobject.biblemap.put("b7_6_8", new arasuperobject(7,6,8,"ان الرب ارسل رجلا نبيا الى بني اسرائيل فقال لهم. هكذا قال الرب اله اسرائيل. اني قد اصعدتكم من مصر اخرجتكم من بيت العبودية"));
arasuperobject.biblemap.put("b7_6_9", new arasuperobject(7,6,9,"وانقذتكم من يد المصريين ومن يد جميع مضايقيكم وطردتهم من امامكم واعطيتكم ارضهم"));
arasuperobject.biblemap.put("b7_6_10", new arasuperobject(7,6,10,"وقلت لكم انا الرب الهكم. لا تخافوا آلهة الاموريين الذين انتم ساكنون ارضهم. ولم تسمعوا لصوتي"));
arasuperobject.biblemap.put("b7_6_11", new arasuperobject(7,6,11,"وأتى ملاك الرب وجلس تحت البطمة التى في عفرة التي ليوآش الابيعزري. وابنه جدعون كان يخبط حنطة في المعصرة لكي يهربها من المديانيين"));
arasuperobject.biblemap.put("b7_6_12", new arasuperobject(7,6,12,"فظهر له ملاك الرب وقال له. الرب معك يا جبار البأس"));
arasuperobject.biblemap.put("b7_6_13", new arasuperobject(7,6,13,"فقال له جدعون اسألك يا سيدي اذا كان الرب معنا فلماذا اصابتنا كل هذه واين كل عجائبه التي اخبرنا بها آباؤنا قائلين ألم يصعدنا الرب من مصر. والآن قد رفضنا الرب وجعلنا في كف مديان"));
arasuperobject.biblemap.put("b7_6_14", new arasuperobject(7,6,14,"التفت اليه الرب وقال اذهب بقوتك هذه وخلص اسرائيل من كفّ مديان. أما ارسلتك"));
arasuperobject.biblemap.put("b7_6_15", new arasuperobject(7,6,15,"فقال له اسألك يا سيدي بماذا اخلص اسرائيل. ها عشيرتي هي الذلّى في منسّى وانا الاصغر في بيت ابي"));
arasuperobject.biblemap.put("b7_6_16", new arasuperobject(7,6,16,"فقال له الرب اني اكون معك وستضرب المديانيين كرجل واحد"));
arasuperobject.biblemap.put("b7_6_17", new arasuperobject(7,6,17,"فقال له ان كنت قد وجدت نعمة في عينيك فاصنع لي علامة انك انت تكلمني"));
arasuperobject.biblemap.put("b7_6_18", new arasuperobject(7,6,18,"لا تبرح من ههنا حتى آتي اليك واخرج تقدمتي واضعها امامك. فقال اني ابقى حتى ترجع"));
arasuperobject.biblemap.put("b7_6_19", new arasuperobject(7,6,19,"فدخل جدعون وعمل جدي معزى وايفة دقيق فطيرا. اما اللحم فوضعه في سل واما المرق فوضعه في قدر وخرج بها اليه الى تحت البطمة وقدّمها"));
arasuperobject.biblemap.put("b7_6_20", new arasuperobject(7,6,20,"فقال له ملاك الله خذ اللحم والفطير وضعهما على تلك الصخرة واسكب المرق. ففعل كذلك"));
arasuperobject.biblemap.put("b7_6_21", new arasuperobject(7,6,21,"فمدّ ملاك الرب طرف العكاز الذي بيده ومس اللحم والفطير فصعدت نار من الصخرة واكلت اللحم والفطير. وذهب ملاك الرب عن عينيه"));
arasuperobject.biblemap.put("b7_6_22", new arasuperobject(7,6,22,"فرأى جدعون انه ملاك الرب فقال جدعون آه يا سيدي الرب لاني قد رأيت ملاك الرب وجها لوجه"));
arasuperobject.biblemap.put("b7_6_23", new arasuperobject(7,6,23,"فقال له الرب السلام لك. لا تخف. لا تموت"));
arasuperobject.biblemap.put("b7_6_24", new arasuperobject(7,6,24,"فبنى جدعون هناك مذبحا للرب ودعاه يهوه شلوم. الى هذا اليوم لم يزل في عفرة الابيعزريين"));
arasuperobject.biblemap.put("b7_6_25", new arasuperobject(7,6,25,"وكان في تلك الليلة ان الرب قال له خذ ثور البقر الذي لابيك وثورا ثانيا ابن سبع سنين واهدم مذبح البعل الذي لابيك واقطع السارية التي عنده"));
arasuperobject.biblemap.put("b7_6_26", new arasuperobject(7,6,26,"وابن مذبحا للرب الهك على راس هذا الحصن بترتيب وخذ الثور الثاني واصعد محرقة على حطب السارية التي تقطعها"));
arasuperobject.biblemap.put("b7_6_27", new arasuperobject(7,6,27,"فاخذ جدعون عشرة رجال من عبيده وعمل كما كلّمه الرب. واذ كان يخاف من بيت ابيه واهل المدينة ان يعمل ذلك نهارا فعمله ليلا"));
arasuperobject.biblemap.put("b7_6_28", new arasuperobject(7,6,28,"فبكر اهل المدينة في الغد واذا بمذبح البعل قد هدم والسارية التي عنده قد قطعت والثور الثاني قد أصعد على المذبح الذي بني"));
arasuperobject.biblemap.put("b7_6_29", new arasuperobject(7,6,29,"فقال الواحد لصاحبه من عمل هذا الامر. فسألوا وبحثوا فقالوا ان جدعون بن يوآش قد فعل هذا الامر"));
arasuperobject.biblemap.put("b7_6_30", new arasuperobject(7,6,30,"فقال اهل المدينة ليوآش اخرج ابنك لكي يموت لانه هدم مذبح البعل وقطع السارية التي عنده"));
arasuperobject.biblemap.put("b7_6_31", new arasuperobject(7,6,31,"فقال يوآش لجميع القائمين عليه انتم تقاتلون للبعل ام انتم تخلصونه. من يقاتل له يقتل في هذا الصباح. ان كان الها فليقاتل لنفسه لان مذبحه قد هدم"));
arasuperobject.biblemap.put("b7_6_32", new arasuperobject(7,6,32,"فدعاه في ذلك اليوم يربعل قائلا ليقاتله البعل لانه هدم مذبحه"));
arasuperobject.biblemap.put("b7_6_33", new arasuperobject(7,6,33,"واجتمع جميع المديانيين والعمالقة وبني المشرق معا وعبروا ونزلوا في وادي يزرعيل"));
arasuperobject.biblemap.put("b7_6_34", new arasuperobject(7,6,34,"ولبس روح الرب جدعون فضرب بالبوق فاجتمع ابيعزر وراءه"));
arasuperobject.biblemap.put("b7_6_35", new arasuperobject(7,6,35,"وارسل رسلا الى جميع منسّى فاجتمع هو ايضا وراءه وارسل رسلا الى اشير وزبولون ونفتالي فصعدوا للقائهم"));
arasuperobject.biblemap.put("b7_6_36", new arasuperobject(7,6,36,"وقال جدعون لله. ان كنت تخلص بيدي اسرائيل كما تكلمت"));
arasuperobject.biblemap.put("b7_6_37", new arasuperobject(7,6,37,"فها اني واضع جزّة الصوف في البيدر فان كان طل على الجزّة وحدها وجفاف على الارض كلها علمت انك تخلص بيدي اسرائيل كما تكلمت"));
arasuperobject.biblemap.put("b7_6_38", new arasuperobject(7,6,38,"وكان كذلك. فبكر في الغد وضغط الجزّة وعصر طلا من الجزّة ملء قصعة ماء"));
arasuperobject.biblemap.put("b7_6_39", new arasuperobject(7,6,39,"فقال جدعون لله لا يحم غضبك عليّ فاتكلم هذه المرة فقط. أمتحن هذه المرة فقط بالجزّة. فليكن جفاف في الجزّة وحدها وعلى كل الارض ليكن طل"));
arasuperobject.biblemap.put("b7_6_40", new arasuperobject(7,6,40,"ففعل الله كذلك في تلك الليلة. فكان جفاف في الجزّة وحدها وعلى الارض كلها كان طل"));
arasuperobject.biblemap.put("b7_7_1", new arasuperobject(7,7,1,"فبكر يربعل اي جدعون وكل الشعب الذي معه ونزلوا على عين حرود. وكان جيش المديانيين شماليهم عند تل مورة في الوادي"));
arasuperobject.biblemap.put("b7_7_2", new arasuperobject(7,7,2,"وقال الرب لجدعون ان الشعب الذي معك كثير عليّ لادفع المديانيين بيدهم لئلا يفتخر عليّ اسرائيل قائلا يدي خلصتني"));
arasuperobject.biblemap.put("b7_7_3", new arasuperobject(7,7,3,"والآن ناد في آذان الشعب قائلا من كان خائفا ومرتعدا فليرجع وينصرف من جبل جلعاد. فرجع من الشعب اثنان وعشرون الفا. وبقي عشرة آلاف"));
arasuperobject.biblemap.put("b7_7_4", new arasuperobject(7,7,4,"وقال الرب لجدعون لم يزل الشعب كثيرا. انزل بهم الى الماء فانقيهم لك هناك. ويكون ان الذي اقول لك عنه هذا يذهب معك فهو يذهب معك وكل من اقول لك عنه هذا لا يذهب معك فهو لا يذهب"));
arasuperobject.biblemap.put("b7_7_5", new arasuperobject(7,7,5,"فنزل بالشعب الى الماء. وقال الرب لجدعون كل من يلغ بلسانه من الماء كما يلغ الكلب فأوقفه وحده. وكذا كل من جثا على ركبتيه للشرب"));
arasuperobject.biblemap.put("b7_7_6", new arasuperobject(7,7,6,"وكان عدد الذين ولغوا بيدهم الى فمهم ثلاث مئة رجل. واما باقي الشعب جميعا فجثوا على ركبهم لشرب الماء"));
arasuperobject.biblemap.put("b7_7_7", new arasuperobject(7,7,7,"فقال الرب لجدعون بالثلاث مئة الرجل الذين ولغوا اخلصكم وادفع المديانيين ليدك. واما سائر الشعب فليذهبوا كل واحد الى مكانه"));
arasuperobject.biblemap.put("b7_7_8", new arasuperobject(7,7,8,"فاخذ الشعب زادا بيدهم مع ابواقهم. وارسل سائر رجال اسرائيل كل واحد الى خيمته وأمسك الثلاث مئة الرجل. وكانت محلّة المديانيين تحته في الوادي"));
arasuperobject.biblemap.put("b7_7_9", new arasuperobject(7,7,9,"وكان في تلك الليلة ان الرب قال له قم انزل الى المحلّة لاني قد دفعتها الى يدك"));
arasuperobject.biblemap.put("b7_7_10", new arasuperobject(7,7,10,"وان كنت خائفا من النزول فانزل انت وفورة غلامك الى المحلّة"));
arasuperobject.biblemap.put("b7_7_11", new arasuperobject(7,7,11,"وتسمع ما يتكلمون به وبعد تتشدد يداك وتنزل الى المحلّة. فنزل هو وفورة غلامه الى آخر المتجهزين الذين في المحلّة"));
arasuperobject.biblemap.put("b7_7_12", new arasuperobject(7,7,12,"وكان المديانيون والعمالقة وكل بني المشرق حالّين في الوادي كالجراد في الكثرة. وجمالهم لا عدد لها كالرمل الذي على شاطئ البحر في الكثرة"));
arasuperobject.biblemap.put("b7_7_13", new arasuperobject(7,7,13,"وجاء جدعون فاذا رجل يخبر صاحبه بحلم ويقول هوذا قد حلمت حلما واذا رغيف خبز شعير يتدحرج في محلّة المديانيين وجاء الى الخيمة وضربها فسقطت وقلبها الى فوق فسقطت الخيمة"));
arasuperobject.biblemap.put("b7_7_14", new arasuperobject(7,7,14,"فاجاب صاحبه وقال ليس ذلك الا سيف جدعون بن يوآش رجل اسرائيل. قد دفع الله الى يده المديانيين وكل الجيش"));
arasuperobject.biblemap.put("b7_7_15", new arasuperobject(7,7,15,"وكان لما سمع جدعون خبر الحلم وتفسيره انه سجد ورجع الى محلّة اسرائيل وقال قوموا لان الرب قد دفع الى يدكم جيش المديانيين"));
arasuperobject.biblemap.put("b7_7_16", new arasuperobject(7,7,16,"وقسم الثلاث مئة الرجل الى ثلاث فرق وجعل ابواقا في ايديهم كلهم وجرارا فارغة ومصابيح في وسط الجرار"));
arasuperobject.biblemap.put("b7_7_17", new arasuperobject(7,7,17,"وقال لهم انظروا اليّ وافعلوا كذلك. وها انا آت الى طرف المحلّة فيكون كما افعل انكم هكذا تفعلون"));
arasuperobject.biblemap.put("b7_7_18", new arasuperobject(7,7,18,"ومتى ضربت بالبوق انا وكل الذين معي فاضربوا انتم ايضا بالابواق حول كل المحلّة وقولوا للرب ولجدعون"));
arasuperobject.biblemap.put("b7_7_19", new arasuperobject(7,7,19,"فجاء جدعون والمئة الرجل الذين معه الى طرف المحلّة في اول الهزيع الاوسط وكانوا اذ ذاك قد اقاموا الحراس فضربوا بالابواق وكسروا الجرار التي بايديهم"));
arasuperobject.biblemap.put("b7_7_20", new arasuperobject(7,7,20,"فضربت الفرق الثلاث بالابواق وكسروا الجرار وامسكوا المصابيح بايديهم اليسرى والابواق بايديهم اليمنى ليضربوا بها وصرخوا سيف للرب ولجدعون"));
arasuperobject.biblemap.put("b7_7_21", new arasuperobject(7,7,21,"ووقفوا كل واحد في مكانه حول المحلّة فركض كل الجيش وصرخوا وهربوا"));
arasuperobject.biblemap.put("b7_7_22", new arasuperobject(7,7,22,"وضرب الثلاث المئين بالابواق وجعل الرب سيف كل واحد بصاحبه وبكل الجيش. فهرب الجيش الى بيت شطّة الى صردة حتى الى حافة آبل محولة الى طبّاة"));
arasuperobject.biblemap.put("b7_7_23", new arasuperobject(7,7,23,"فاجتمع رجال اسرائيل من نفتالي ومن اشير ومن كل منسّى وتبعوا المديانيين"));
arasuperobject.biblemap.put("b7_7_24", new arasuperobject(7,7,24,"فارسل جدعون رسلا الى كل جبل افرايم قائلا انزلوا للقاء المديانيين وخذوا منهم المياه الى بيت بارة والاردن. فاجتمع كل رجال افرايم واخذوا المياه الى بيت بارة والاردن"));
arasuperobject.biblemap.put("b7_7_25", new arasuperobject(7,7,25,"وامسكوا اميري المديانيين غرابا وذئبا وقتلوا غرابا على صخرة غراب واما ذئب فقتلوه في معصرة ذئب. وتبعوا المديانيين. واتوا براسي غراب وذئب الى جدعون من عبر الاردن"));
arasuperobject.biblemap.put("b7_8_1", new arasuperobject(7,8,1,"وقال له رجال افرايم ما هذا الامر الذي فعلت بنا اذ لم تدعنا عند ذهابك لمحاربة المديانيين. وخاصموه بشدة"));
arasuperobject.biblemap.put("b7_8_2", new arasuperobject(7,8,2,"فقال لهم ماذا فعلت الآن نظيركم. أليس خصاصة افرايم خيرا من قطاف ابيعزر"));
arasuperobject.biblemap.put("b7_8_3", new arasuperobject(7,8,3,"ليدكم دفع الله اميري المديانيين غرابا وذئبا. وماذا قدرت ان اعمل نظيركم. حينئذ ارتخت روحهم عنه عندما تكلم بهذا الكلام"));
arasuperobject.biblemap.put("b7_8_4", new arasuperobject(7,8,4,"وجاء جدعون الى الاردن وعبر هو والثلاث مئة الرجل الذين معه معيين ومطاردين"));
arasuperobject.biblemap.put("b7_8_5", new arasuperobject(7,8,5,"فقال لاهل سكوت اعطوا ارغفة خبز للقوم الذين معي لانهم معيون وانا ساع وراء زبح وصلمناع ملكي مديان"));
arasuperobject.biblemap.put("b7_8_6", new arasuperobject(7,8,6,"فقال رؤساء سكوت هل ايدي زبح وصلمناع بيدك الآن حتى نعطي جندك خبزا"));
arasuperobject.biblemap.put("b7_8_7", new arasuperobject(7,8,7,"فقال جدعون. لذلك عندما يدفع الرب زبح وصلمناع بيدي ادوس لحمكم مع اشواك البرية بالنوارج"));
arasuperobject.biblemap.put("b7_8_8", new arasuperobject(7,8,8,"وصعد من هناك الى فنوئيل وكلمهم هكذا. فاجابه اهل فنوئيل كما اجاب اهل سكوت"));
arasuperobject.biblemap.put("b7_8_9", new arasuperobject(7,8,9,"فكلم ايضا اهل فنوئيل قائلا عند رجوعي بسلام اهدم هذا البرج"));
arasuperobject.biblemap.put("b7_8_10", new arasuperobject(7,8,10,"وكان زبح وصلمناع في قرقر وجيشهما معهما نحو خمسة عشر الفا كل الباقين من جميع جيش بني المشرق. والذين سقطوا مئة وعشرون الف رجل مخترطي السيف"));
arasuperobject.biblemap.put("b7_8_11", new arasuperobject(7,8,11,"وصعد جدعون في طريق ساكني الخيام شرقي نوبح ويجبهة وضرب الجيش وكان الجيش مطمئنا"));
arasuperobject.biblemap.put("b7_8_12", new arasuperobject(7,8,12,"فهرب زبح وصلمناع فتبعهما وامسك ملكي مديان زبح وصلمناع وازعج كل الجيش"));
arasuperobject.biblemap.put("b7_8_13", new arasuperobject(7,8,13,"ورجع جدعون بن يواش من الحرب من عند عقبة حارس"));
arasuperobject.biblemap.put("b7_8_14", new arasuperobject(7,8,14,"وامسك غلاما من اهل سكوت وساله فكتب له رؤساء سكوت وشيوخها سبعة وسبعين رجلا"));
arasuperobject.biblemap.put("b7_8_15", new arasuperobject(7,8,15,"ودخل الى اهل سكوت وقال هوذا زبح وصلمناع اللذان عيرتموني بهما قائلين هل ايدي زبح صلمناع بيدك الآن حتى نعطي رجالك المعيين خبزا"));
arasuperobject.biblemap.put("b7_8_16", new arasuperobject(7,8,16,"واخذ شيوخ المدينة واشواك البرية والنوارج وعلّم بها اهل سكوت"));
arasuperobject.biblemap.put("b7_8_17", new arasuperobject(7,8,17,"وهدم برج فنوئيل وقتل رجال المدينة"));
arasuperobject.biblemap.put("b7_8_18", new arasuperobject(7,8,18,"وقال لزبح وصلمناع كيف الرجال الذين قتلتماهم في تابور. فقالا مثلهم مثلك. كل واحد كصورة اولاد ملك"));
arasuperobject.biblemap.put("b7_8_19", new arasuperobject(7,8,19,"فقال هم اخوتي بنو امي. حيّ هو الرب لو استحييتماهم لما قتلتكما"));
arasuperobject.biblemap.put("b7_8_20", new arasuperobject(7,8,20,"وقال ليثر بكره قم اقتلهما فلم يخترط الغلام سيفه لانه خاف بما انه فتى بعد"));
arasuperobject.biblemap.put("b7_8_21", new arasuperobject(7,8,21,"فقال زبح وصلمناع قم انت وقع علينا لانه مثل الرجل بطشه. فقام جدعون وقتل زبح وصلمناع واخذ الاهلّة التي في اعناق جمالهما"));
arasuperobject.biblemap.put("b7_8_22", new arasuperobject(7,8,22,"وقال رجال اسرائيل لجدعون تسلط علينا انت وابنك وابن ابنك لانك قد خلّصتنا من يد مديان"));
arasuperobject.biblemap.put("b7_8_23", new arasuperobject(7,8,23,"فقال لهم جدعون لا اتسلط انا عليكم ولا يتسلط ابني عليكم. الرب يتسلط عليكم"));
arasuperobject.biblemap.put("b7_8_24", new arasuperobject(7,8,24,"ثم قال لهم جدعون اطلب منكم طلبة ان تعطوني كل واحد اقراط غنيمته. لانه كان لهم اقراط ذهب لانهم اسمعيليون"));
arasuperobject.biblemap.put("b7_8_25", new arasuperobject(7,8,25,"فقالوا اننا نعطي. وفرشوا رداء وطرحوا عليه كل واحد اقراط غنيمته"));
arasuperobject.biblemap.put("b7_8_26", new arasuperobject(7,8,26,"وكان وزن اقراط الذهب التي طلب الفا وسبع مئة شاقل ذهبا ما عدا الاهلّة والحلق واثواب الارجوان التي على ملوك مديان وما عدا القلائد التي في اعناق جمالهم"));
arasuperobject.biblemap.put("b7_8_27", new arasuperobject(7,8,27,"فصنع جدعون منها افودا وجعله في مدينته في عفرة وزنى كل اسرائيل وراءه هناك فكان ذلك لجدعون وبيته فخا"));
arasuperobject.biblemap.put("b7_8_28", new arasuperobject(7,8,28,"وذلّ مديان امام بني اسرائيل ولم يعودوا يرفعون رؤسهم. واستراحت الارض اربعين سنة في ايام جدعون"));
arasuperobject.biblemap.put("b7_8_29", new arasuperobject(7,8,29,"وذهب يربعل بن يوآش واقام في بيته"));
arasuperobject.biblemap.put("b7_8_30", new arasuperobject(7,8,30,"وكان لجدعون سبعون ولدا خارجون من صلبه لانه كانت له نساء كثيرات"));
arasuperobject.biblemap.put("b7_8_31", new arasuperobject(7,8,31,"وسرّيته التي في شكيم ولدت له هي ايضا ابنا فسماه ابيمالك"));
arasuperobject.biblemap.put("b7_8_32", new arasuperobject(7,8,32,"ومات جدعون بن يوآش بشيبة صالحة ودفن في قبر يوآش ابيه في عفرة ابيعزر"));
arasuperobject.biblemap.put("b7_8_33", new arasuperobject(7,8,33,"وكان بعد موت جدعون ان بني اسرائيل رجعوا وزنوا وراء البعليم وجعلوا لهم بعل بريث الها"));
arasuperobject.biblemap.put("b7_8_34", new arasuperobject(7,8,34,"ولم يذكر بنو اسرائيل الرب الههم الذي انقذهم من يد جميع اعدائهم من حولهم"));
arasuperobject.biblemap.put("b7_8_35", new arasuperobject(7,8,35,"ولم يعملوا معروفا مع بيت يربعل جدعون نظير كل الخير الذي عمل مع اسرائيل"));
arasuperobject.biblemap.put("b7_9_1", new arasuperobject(7,9,1,"وذهب ابيمالك بن يربعل الى شكيم الى اخوة امه وكلمهم وجميع عشيرة بيت ابي امه قائلا"));
arasuperobject.biblemap.put("b7_9_2", new arasuperobject(7,9,2,"تكلموا الآن في آذان جميع اهل شكيم. ايما هو خير لكم. أأن يتسلط عليكم سبعون رجلا جميع بني يربعل ام ان يتسلط عليكم رجل واحد. واذكروا اني انا عظمكم ولحمكم"));
arasuperobject.biblemap.put("b7_9_3", new arasuperobject(7,9,3,"فتكلم اخوة امه عنه في آذان كل اهل شكيم بجميع هذا الكلام. فمال قلبهم وراء ابيمالك لانهم قالوا اخونا هو"));
arasuperobject.biblemap.put("b7_9_4", new arasuperobject(7,9,4,"واعطوه سبعين شاقل فضة من بيت بعل بريث فاستاجر بها ابيمالك رجالا بطالين طائشين فسعوا وراءه"));
arasuperobject.biblemap.put("b7_9_5", new arasuperobject(7,9,5,"ثم جاء الى بيت ابيه في عفرة وقتل اخوته بني يربعل سبعين رجلا على حجر واحد. وبقي يوثام بن يربعل الاصغر لانه اختبأ"));
arasuperobject.biblemap.put("b7_9_6", new arasuperobject(7,9,6,"فاجتمع جميع اهل شكيم وكل سكان القلعة وذهبوا وجعلوا ابيمالك ملكا عند بلوطة النصب الذي في شكيم"));
arasuperobject.biblemap.put("b7_9_7", new arasuperobject(7,9,7,"واخبروا يوثام فذهب ووقف على راس جبل جرزيم ورفع صوته ونادى وقال لهم. اسمعوا لي يا اهل شكيم يسمع لكم الله"));
arasuperobject.biblemap.put("b7_9_8", new arasuperobject(7,9,8,"مرّة ذهبت الاشجار لتمسح عليها ملكا. فقالت للزيتونة املكي علينا"));
arasuperobject.biblemap.put("b7_9_9", new arasuperobject(7,9,9,"فقالت لها الزيتونة أاترك دهني الذي به يكرمون بي الله والناس واذهب لكي املك على الاشجار"));
arasuperobject.biblemap.put("b7_9_10", new arasuperobject(7,9,10,"ثم قالت الاشجار للتينة تعالي انت واملكي علينا"));
arasuperobject.biblemap.put("b7_9_11", new arasuperobject(7,9,11,"فقالت لها التينة أأترك حلاوتي وثمري الطيب واذهب لكي املك على الاشجار"));
arasuperobject.biblemap.put("b7_9_12", new arasuperobject(7,9,12,"فقالت الاشجار للكرمة تعالي انت املكي علينا"));
arasuperobject.biblemap.put("b7_9_13", new arasuperobject(7,9,13,"فقالت لها الكرمة أاترك مسطاري الذي يفرح الله والناس واذهب لكي املك على الاشجار"));
arasuperobject.biblemap.put("b7_9_14", new arasuperobject(7,9,14,"ثم قالت جميع الاشجار للعوسج تعال انت واملك علينا"));
arasuperobject.biblemap.put("b7_9_15", new arasuperobject(7,9,15,"فقال العوسج للاشجار ان كنتم بالحق تمسحونني عليكم ملكا فتعالوا واحتموا تحت ظلي. والا فتخرج نار من العوسج وتأكل ارز لبنان"));
arasuperobject.biblemap.put("b7_9_16", new arasuperobject(7,9,16,"فالآن ان كنتم قد عملتم بالحق والصحة اذ جعلتم ابيمالك ملكا وان كنتم قد فعلتم خيرا مع يربعل ومع بيته وان كنتم قد فعلتم له حسب عمل يديه"));
arasuperobject.biblemap.put("b7_9_17", new arasuperobject(7,9,17,"لان ابي قد حارب عنكم وخاطر بنفسه وانقذكم من يد مديان"));
arasuperobject.biblemap.put("b7_9_18", new arasuperobject(7,9,18,"وانتم قد قمتم اليوم على بيت ابي وقتلتم بنيه سبعين رجلا على حجر واحد وملكتم ابيمالك ابن امته على اهل شكيم لانه اخوكم"));
arasuperobject.biblemap.put("b7_9_19", new arasuperobject(7,9,19,"فان كنتم قد عملتم بالحق والصحة مع يربعل ومع بيته في هذا اليوم فافرحوا انتم بابيمالك وليفرح هو ايضا بكم"));
arasuperobject.biblemap.put("b7_9_20", new arasuperobject(7,9,20,"والا فتخرج نار من ابيمالك وتأكل اهل شكيم وسكان القلعة وتخرج نار من اهل شكيم ومن سكان القلعة وتاكل ابيمالك"));
arasuperobject.biblemap.put("b7_9_21", new arasuperobject(7,9,21,"ثم هرب يوثام وفرّ وذهب الى بئر واقام هناك من وجه ابيمالك اخيه"));
arasuperobject.biblemap.put("b7_9_22", new arasuperobject(7,9,22,"فترأس ابيمالك على اسرائيل ثلاث سنين"));
arasuperobject.biblemap.put("b7_9_23", new arasuperobject(7,9,23,"وارسل الرب روحا رديا بين ابيمالك واهل شكيم فغدر اهل شكيم بابيمالك"));
arasuperobject.biblemap.put("b7_9_24", new arasuperobject(7,9,24,"ليأتي ظلم بني يربعل السبعين ويجلب دمهم على ابيمالك اخيهم الذي قتلهم وعلى اهل شكيم الذين شددوا يديه لقتل اخوته"));
arasuperobject.biblemap.put("b7_9_25", new arasuperobject(7,9,25,"فوضع له اهل شكيم كمينا على رؤوس الجبال وكانوا يستلبون كل من عبر بهم في الطريق. فأخبر ابيمالك"));
arasuperobject.biblemap.put("b7_9_26", new arasuperobject(7,9,26,"وجاء جعل بن عابد مع اخوته وعبروا الى شكيم فوثق به اهل شكيم"));
arasuperobject.biblemap.put("b7_9_27", new arasuperobject(7,9,27,"وخرجوا الى الحقل وقطفوا كرومهم وداسوا وصنعوا تمجيدا ودخلوا بيت الههم واكلوا وشربوا ولعنوا ابيمالك"));
arasuperobject.biblemap.put("b7_9_28", new arasuperobject(7,9,28,"فقال جعل بن عابد من هو ابيمالك ومن هو شكيم حتى نخدمه. أما هو ابن يربعل وزبول وكيله. اخدموا رجال حمور ابي شكيم. فلماذا نخدمه نحن"));
arasuperobject.biblemap.put("b7_9_29", new arasuperobject(7,9,29,"من يجعل هذا الشعب بيدي فاعزل ابيمالك. وقال لابيمالك كثر جندك واخرج"));
arasuperobject.biblemap.put("b7_9_30", new arasuperobject(7,9,30,"ولما سمع زبول رئيس المدينة كلام جعل بن عابد حمي غضبه"));
arasuperobject.biblemap.put("b7_9_31", new arasuperobject(7,9,31,"وارسل رسلا الى ابيمالك في ترمة يقول هوذا جعل بن عابد واخوته قد اتوا الى شكيم وها هم يهيجون المدينة ضدك"));
arasuperobject.biblemap.put("b7_9_32", new arasuperobject(7,9,32,"فالآن قم ليلا انت والشعب الذي معك واكمن في الحقل"));
arasuperobject.biblemap.put("b7_9_33", new arasuperobject(7,9,33,"ويكون في الصباح عند شروق الشمس انك تبكر وتقتحم المدينة. وها هو والشعب الذي معه يخرجون اليك فتفعل به حسبما تجده يدك"));
arasuperobject.biblemap.put("b7_9_34", new arasuperobject(7,9,34,"فقام ابيمالك وكل الشعب الذي معه ليلا وكمنوا لشكيم اربع فرق"));
arasuperobject.biblemap.put("b7_9_35", new arasuperobject(7,9,35,"فخرج جعل بن عابد ووقف في مدخل باب المدينة. فقام ابيمالك والشعب الذي معه من المكمن"));
arasuperobject.biblemap.put("b7_9_36", new arasuperobject(7,9,36,"ورأى جعل الشعب وقال لزبول هوذا شعب نازل عن رؤوس الجبال. فقال له زبول انك ترى ظل الجبال كانه اناس"));
arasuperobject.biblemap.put("b7_9_37", new arasuperobject(7,9,37,"فعاد جعل وتكلم ايضا قائلا هوذا شعب نازل من عند اعالي الارض وفرقة واحدة آتية عن طريق بلوطة العائفين"));
arasuperobject.biblemap.put("b7_9_38", new arasuperobject(7,9,38,"فقال له زبول اين الآن فوك الذي قلت به من هو ابيمالك حتى نخدمه. أليس هذا هو الشعب الذي رذلته. فاخرج الآن وحاربه"));
arasuperobject.biblemap.put("b7_9_39", new arasuperobject(7,9,39,"فخرج جعل امام اهل شكيم وحارب ابيمالك"));
arasuperobject.biblemap.put("b7_9_40", new arasuperobject(7,9,40,"فهزمه ابيمالك فهرب من قدامه وسقط قتلى كثيرون حتى عند مدخل الباب"));
arasuperobject.biblemap.put("b7_9_41", new arasuperobject(7,9,41,"فاقام ابيمالك في ارومة. وطرد زبول جعلا واخوته عن الاقامة في شكيم"));
arasuperobject.biblemap.put("b7_9_42", new arasuperobject(7,9,42,"وكان في الغد ان الشعب خرج الى الحقل واخبروا ابيمالك"));
arasuperobject.biblemap.put("b7_9_43", new arasuperobject(7,9,43,"فاخذ القوم وقسمهم الى ثلاث فرق وكمن في الحقل ونظر واذ الشعب يخرج من المدينة فقام عليهم وضربهم"));
arasuperobject.biblemap.put("b7_9_44", new arasuperobject(7,9,44,"وابيمالك والفرقة التي معه اقتحموا ووقفوا في مدخل باب المدينة. واما الفرقتان فهجمتا على كل من في الحقل وضربتاه"));
arasuperobject.biblemap.put("b7_9_45", new arasuperobject(7,9,45,"وحارب ابيمالك المدينة كل ذلك اليوم واخذ المدينة وقتل الشعب الذي بها وهدم المدينة وزرعها ملحا"));
arasuperobject.biblemap.put("b7_9_46", new arasuperobject(7,9,46,"وسمع كل اهل برج شكيم فدخلوا الى صرح بيت ايل بريث"));
arasuperobject.biblemap.put("b7_9_47", new arasuperobject(7,9,47,"فأخبر ابيمالك ان كل اهل برج شكيم قد اجتمعوا"));
arasuperobject.biblemap.put("b7_9_48", new arasuperobject(7,9,48,"فصعد ابيمالك الى جبل صلمون هو وكل الشعب الذي معه. واخذ ابيمالك الفؤوس بيده وقطع غصن شجر ورفعه ووضعه على كتفه وقال للشعب الذي معه ما رأيتموني افعله فاسرعوا افعلوا مثلي"));
arasuperobject.biblemap.put("b7_9_49", new arasuperobject(7,9,49,"فقطع الشعب ايضا كل واحد غصنا وساروا وراء ابيمالك ووضعوها على الصرح واحرقوا عليهم الصرح بالنار. فمات ايضا جميع اهل برج شكيم نحو الف رجل وامرأة"));
arasuperobject.biblemap.put("b7_9_50", new arasuperobject(7,9,50,"ثم ذهب ابيمالك الى تاباص ونزل في تاباص واخذها"));
arasuperobject.biblemap.put("b7_9_51", new arasuperobject(7,9,51,"وكان برج قوي في وسط المدينة فهرب اليه جميع الرجال والنساء وكل اهل المدينة واغلقوا ورائهم وصعدوا الى سطح البرج"));
arasuperobject.biblemap.put("b7_9_52", new arasuperobject(7,9,52,"فجاء ابيمالك الى البرج وحاربه واقترب الى باب البرج ليحرقه بالنار"));
arasuperobject.biblemap.put("b7_9_53", new arasuperobject(7,9,53,"فطرحت امرأة قطعة رحى على راس ابيمالك فشجت جمجمته"));
arasuperobject.biblemap.put("b7_9_54", new arasuperobject(7,9,54,"فدعا حالا الغلام حامل عدته وقال له اخترط سيفك واقتلني لئلا يقولوا عني قتلته امرأة. فطعنه الغلام فمات"));
arasuperobject.biblemap.put("b7_9_55", new arasuperobject(7,9,55,"ولما رأى رجال اسرائيل ان ابيمالك قد مات ذهب كل واحد الى مكانه"));
arasuperobject.biblemap.put("b7_9_56", new arasuperobject(7,9,56,"فرد الله شر ابيمالك الذي فعله بابيه لقتله اخوته السبعين"));
arasuperobject.biblemap.put("b7_9_57", new arasuperobject(7,9,57,"وكل شر اهل شكيم رده الله على رؤوسهم. وأتت عليهم لعنة يوثام بن يربعل"));
arasuperobject.biblemap.put("b7_10_1", new arasuperobject(7,10,1,"وقام بعد ابيمالك لتخليص اسرائيل تولع بن فواة بن دودو رجل من يساكر. كان ساكنا في شامير في جبل افرايم"));
arasuperobject.biblemap.put("b7_10_2", new arasuperobject(7,10,2,"فقضى لاسرائيل ثلاثا وعشرين سنة ومات ودفن في شامير"));
arasuperobject.biblemap.put("b7_10_3", new arasuperobject(7,10,3,"ثم قام بعده يائير الجلعادي فقضى لاسرائيل اثنتين وعشرين سنة"));
arasuperobject.biblemap.put("b7_10_4", new arasuperobject(7,10,4,"وكان له ثلاثون ولدا يركبون على ثلاثين جحشا ولهم ثلاثون مدينة. منهم يدعونها حووث يائير الى هذا اليوم. هي في ارض جلعاد"));
arasuperobject.biblemap.put("b7_10_5", new arasuperobject(7,10,5,"ومات يائير ودفن في قامون"));
arasuperobject.biblemap.put("b7_10_6", new arasuperobject(7,10,6,"وعاد بنو اسرائيل يعملون الشر في عيني الرب وعبدوا البعليم والعشتاروث وآلهة ارام وآلهة صيدون وآلهة موآب وآلهة بني عمون وآلهة الفلسطينيين وتركوا الرب ولم يعبدوه"));
arasuperobject.biblemap.put("b7_10_7", new arasuperobject(7,10,7,"فحمي غضب الرب على اسرائيل وباعهم بيد الفلسطينيين وبيد بني عمون"));
arasuperobject.biblemap.put("b7_10_8", new arasuperobject(7,10,8,"فحطّموا ورضّضوا بني اسرائيل في تلك السنة. ثماني عشرة سنة. جميع بني اسرائيل الذين في عبر الاردن في ارض الاموريين الذين في جلعاد"));
arasuperobject.biblemap.put("b7_10_9", new arasuperobject(7,10,9,"وعبر بنو عمون الاردن ليحاربوا ايضا يهوذا وبنيامين وبيت افرايم فتضايق اسرائيل جدا"));
arasuperobject.biblemap.put("b7_10_10", new arasuperobject(7,10,10,"فصرخ بنو اسرائيل الى الرب قائلين اخطأنا اليك لاننا تركنا الهنا وعبدنا البعليم"));
arasuperobject.biblemap.put("b7_10_11", new arasuperobject(7,10,11,"فقال الرب لبني اسرائيل أليس من المصريين والاموريين وبني عمون والفلسطينيين خلصتكم"));
arasuperobject.biblemap.put("b7_10_12", new arasuperobject(7,10,12,"والصيدونيون والعمالقة والمعونيين قد ضايقوكم فصرختم اليّ فخلصتكم من ايديهم"));
arasuperobject.biblemap.put("b7_10_13", new arasuperobject(7,10,13,"وانتم قد تركتموني وعبدتم آلهة اخرى. لذلك لا اعود اخلصكم"));
arasuperobject.biblemap.put("b7_10_14", new arasuperobject(7,10,14,"امضوا واصرخوا الى الآلهة التي اخترتموها. لتخلصكم هي في زمان ضيقكم"));
arasuperobject.biblemap.put("b7_10_15", new arasuperobject(7,10,15,"فقال بنو اسرائيل للرب اخطأنا فافعل بنا كل ما يحسن في عينيك. انما انقذنا هذا اليوم"));
arasuperobject.biblemap.put("b7_10_16", new arasuperobject(7,10,16,"وازالوا الآلهة الغريبة من وسطهم وعبدوا الرب فضاقت نفسه بسبب مشقة اسرائيل"));
arasuperobject.biblemap.put("b7_10_17", new arasuperobject(7,10,17,"فاجتمع بنو عمون ونزلوا في جلعاد واجتمع بنو اسرائيل ونزلوا في المصفاة"));
arasuperobject.biblemap.put("b7_10_18", new arasuperobject(7,10,18,"فقال الشعب رؤساء جلعاد الواحد لصاحبه ايّ هو الرجل الذي يبتدئ بمحاربة بني عمون فانه يكون راسا لجميع سكان جلعاد"));
arasuperobject.biblemap.put("b7_11_1", new arasuperobject(7,11,1,"وكان يفتاح الجلعادي جبار بأس وهو ابن امرأة زانية. وجلعاد ولد يفتاح"));
arasuperobject.biblemap.put("b7_11_2", new arasuperobject(7,11,2,"ثم ولدت امرأة جلعاد له بنين. فلما كبر بنو المرأة طردوا يفتاح وقالوا له لا ترث في بيت ابينا لانك انت ابن امرأة اخرى"));
arasuperobject.biblemap.put("b7_11_3", new arasuperobject(7,11,3,"فهرب يفتاح من وجه اخوته واقام في ارض طوب. فاجتمع الى يفتاح رجال بطالون وكانوا يخرجون معه"));
arasuperobject.biblemap.put("b7_11_4", new arasuperobject(7,11,4,"وكان بعد ايام ان بني عمون حاربوا اسرائيل"));
arasuperobject.biblemap.put("b7_11_5", new arasuperobject(7,11,5,"ولما حارب بنو عمون اسرائيل ذهب شيوخ جلعاد ليأتوا بيفتاح من ارض طوب"));
arasuperobject.biblemap.put("b7_11_6", new arasuperobject(7,11,6,"وقالوا ليفتاح تعال وكن لنا قائدا فنحارب بني عمون"));
arasuperobject.biblemap.put("b7_11_7", new arasuperobject(7,11,7,"فقال يفتاح لشيوخ جلعاد أما أبغضتموني انتم وطردتموني من بيت ابي. فلماذا اتيتم اليّ الآن اذ تضايقتم"));
arasuperobject.biblemap.put("b7_11_8", new arasuperobject(7,11,8,"فقال شيوخ جلعاد ليفتاح لذلك قد رجعنا الآن اليك لتذهب معنا وتحارب بني عمون وتكون لنا راسا لكل سكان جلعاد"));
arasuperobject.biblemap.put("b7_11_9", new arasuperobject(7,11,9,"فقال يفتاح لشيوخ جلعاد اذا ارجعتموني لمحاربة بني عمون ودفعهم الرب امامي فانا اكون لكم راسا"));
arasuperobject.biblemap.put("b7_11_10", new arasuperobject(7,11,10,"فقال شيوخ جلعاد ليفتاح الرب يكون سامعا بيننا ان كنا لا نفعل هكذا حسب كلامك"));
arasuperobject.biblemap.put("b7_11_11", new arasuperobject(7,11,11,"فذهب يفتاح مع شيوخ جلعاد. وجعله الشعب عليهم راسا وقائدا. فتكلم يفتاح بجميع كلامه امام الرب في المصفاة"));
arasuperobject.biblemap.put("b7_11_12", new arasuperobject(7,11,12,"فارسل يفتاح رسلا الى ملك بني عمون يقول ما لي ولك انك اتيت اليّ للمحاربة في ارضي"));
arasuperobject.biblemap.put("b7_11_13", new arasuperobject(7,11,13,"فقال ملك بني عمون لرسل يفتاح. لان اسرائيل قد اخذ ارضي عند صعوده من مصر من ارنون الى اليبّوق والى الاردن. فالآن ردها بسلام"));
arasuperobject.biblemap.put("b7_11_14", new arasuperobject(7,11,14,"وعاد ايضا يفتاح وارسل رسلا الى ملك بني عمون"));
arasuperobject.biblemap.put("b7_11_15", new arasuperobject(7,11,15,"وقال له هكذا يقول يفتاح. لم ياخذ اسرائيل ارض موآب ولا ارض بني عمون"));
arasuperobject.biblemap.put("b7_11_16", new arasuperobject(7,11,16,"لانه عند صعود اسرائيل من مصر سار في القفر الى بحر سوف واتى الى قادش"));
arasuperobject.biblemap.put("b7_11_17", new arasuperobject(7,11,17,"وارسل اسرائيل رسلا الى ملك ادوم قائلا دعني اعبر في ارضك. فلم يسمع ملك ادوم. فارسل ايضا الى ملك موآب فلم يرض. فاقام اسرائيل في قادش"));
arasuperobject.biblemap.put("b7_11_18", new arasuperobject(7,11,18,"وسار في القفر ودار بارض ادوم وارض موآب وأتى من مشرق الشمس الى ارض موآب ونزل في عبر ارنون ولم يأتوا الى تخم موآب لان ارنون تخم موآب"));
arasuperobject.biblemap.put("b7_11_19", new arasuperobject(7,11,19,"ثم ارسل اسرائيل رسلا الى سيحون ملك الاموريين ملك حشبون وقال له اسرائيل دعني اعبر في ارضك الى مكاني"));
arasuperobject.biblemap.put("b7_11_20", new arasuperobject(7,11,20,"ولم يأمن سيحون لاسرائيل ان يعبر في تخمه بل جمع سيحون كل شعبه ونزلوا في ياهص وحاربوا اسرائيل"));
arasuperobject.biblemap.put("b7_11_21", new arasuperobject(7,11,21,"فدفع الرب اله اسرائيل سيحون وكل شعبه ليد اسرائيل فضربوهم وامتلك اسرائيل كل ارض الاموريين سكان تلك الارض"));
arasuperobject.biblemap.put("b7_11_22", new arasuperobject(7,11,22,"فامتلكوا كل تخم الاموريين من ارنون الى اليبوق ومن القفر الى الاردن"));
arasuperobject.biblemap.put("b7_11_23", new arasuperobject(7,11,23,"والآن الرب اله اسرائيل قد طرد الاموريين من امام شعبه اسرائيل. أفانت تمتلكه"));
arasuperobject.biblemap.put("b7_11_24", new arasuperobject(7,11,24,"أليس ما يملّكك اياه كموش الهك تمتلك. وجميع الذين طردهم الرب الهنا من امامنا فاياهم نمتلك"));
arasuperobject.biblemap.put("b7_11_25", new arasuperobject(7,11,25,"والآن فهل انت خير من بالاق بن صفور ملك موآب فهل خاصم اسرائيل او حاربهم محاربة"));
arasuperobject.biblemap.put("b7_11_26", new arasuperobject(7,11,26,"حين اقام اسرائيل في حشبون وقراها وعروعير وقراها وكل المدن التي على جانب ارنون ثلاث مئة سنة فلماذا لم تستردها في تلك المدة"));
arasuperobject.biblemap.put("b7_11_27", new arasuperobject(7,11,27,"فانا لم اخطئ اليك واما انت فانك تفعل بي شرا بمحاربتي. ليقض الرب القاضي اليوم بين بني اسرائيل وبني عمون"));
arasuperobject.biblemap.put("b7_11_28", new arasuperobject(7,11,28,"فلم يسمع ملك بني عمون لكلام يفتاح الذي ارسل اليه"));
arasuperobject.biblemap.put("b7_11_29", new arasuperobject(7,11,29,"فكان روح الرب على يفتاح فعبر جلعاد ومنسّى وعبر مصفاة جلعاد ومن مصفاة جلعاد عبر الى بني عمون"));
arasuperobject.biblemap.put("b7_11_30", new arasuperobject(7,11,30,"ونذر يفتاح نذرا للرب قائلا. ان دفعت بني عمون ليدي"));
arasuperobject.biblemap.put("b7_11_31", new arasuperobject(7,11,31,"فالخارج الذي يخرج من ابواب بيتي للقائي عند رجوعي بالسلامة من عند بني عمون يكون للرب واصعده محرقة"));
arasuperobject.biblemap.put("b7_11_32", new arasuperobject(7,11,32,"ثم عبر يفتاح الى بني عمون لمحاربتهم. فدفعهم الرب ليده"));
arasuperobject.biblemap.put("b7_11_33", new arasuperobject(7,11,33,"فضربهم من عروعير الى مجيئك الى منّيت عشرين مدينة والى آبل الكروم ضربة عظيمة جدا. فذلّ بني عمون امام بني اسرائيل"));
arasuperobject.biblemap.put("b7_11_34", new arasuperobject(7,11,34,"ثم أتى يفتاح الى المصفاة الى بيته. واذا بابنته خارجة للقائه بدفوف ورقص. وهي وحيدة. لم يكن له ابن ولا ابنة غيرها"));
arasuperobject.biblemap.put("b7_11_35", new arasuperobject(7,11,35,"وكان لما رأها انه مزّق ثيابه وقال آه يا بنتي قد احزنتني حزنا وصرت بين مكدّريّ لاني قد فتحت فمي الى الرب ولا يمكنني الرجوع"));
arasuperobject.biblemap.put("b7_11_36", new arasuperobject(7,11,36,"فقالت له. يا ابي هل فتحت فاك الى الرب فافعل بي كما خرج من فيك بما ان الرب قد انتقم لك من اعدائك بني عمون"));
arasuperobject.biblemap.put("b7_11_37", new arasuperobject(7,11,37,"ثم قالت لابيها فليفعل لي هذا الأمر. اتركني شهرين فاذهب وانزل على الجبال وابكي عذراويتي انا وصاحباتي"));
arasuperobject.biblemap.put("b7_11_38", new arasuperobject(7,11,38,"فقال اذهبي وارسلها الى شهرين فذهبت هي وصاحباتها وبكت عذراويتها على الجبال"));
arasuperobject.biblemap.put("b7_11_39", new arasuperobject(7,11,39,"وكان عند نهاية الشهرين انها رجعت الى ابيها ففعل بها نذره الذي نذر وهي لم تعرف رجلا. فصارت عادة في اسرائيل"));
arasuperobject.biblemap.put("b7_11_40", new arasuperobject(7,11,40,"ان بنات اسرائيل يذهبن من سنة الى سنة لينحن على بنت يفتاح الجلعادي اربعة ايام في السنة"));
arasuperobject.biblemap.put("b7_12_1", new arasuperobject(7,12,1,"واجتمع رجال افرايم وعبروا الى جهة الشمال وقالوا ليفتاح لماذا عبرت لمحاربة بني عمون ولم تدعنا للذهاب معك. نحرق بيتك عليك بنار"));
arasuperobject.biblemap.put("b7_12_2", new arasuperobject(7,12,2,"فقال لهم يفتاح. صاحب خصام شديد كنت انا وشعبي مع بني عمون وناديتكم فلم تخلصوني من يدهم"));
arasuperobject.biblemap.put("b7_12_3", new arasuperobject(7,12,3,"ولما رأيت انكم لا تخلصون وضعت نفسي في يدي وعبرت الى بني عمون فدفعهم الرب ليدي. فلماذا صعدتم عليّ اليوم هذا لمحاربتي"));
arasuperobject.biblemap.put("b7_12_4", new arasuperobject(7,12,4,"وجمع يفتاح كل رجال جلعاد وحارب افرايم فضرب رجال جلعاد افرايم لانهم قالوا. انتم منفلتو افرايم. جلعاد بين افرايم ومنسّى"));
arasuperobject.biblemap.put("b7_12_5", new arasuperobject(7,12,5,"فاخذ الجلعاديون مخاوض الاردن لافرايم وكان اذ قال منفلتو افرايم دعوني اعبر. كان رجال جلعاد يقولون له أانت افرايمي فان قال لا"));
arasuperobject.biblemap.put("b7_12_6", new arasuperobject(7,12,6,"كانوا يقولون له قل اذا شبولت فيقول سبولت ولم يتحفظ للفظ بحق. فكانوا يأخذونه ويذبحونه على مخاوض الاردن. فسقط في ذلك الوقت من افرايم اثنان واربعون الفا"));
arasuperobject.biblemap.put("b7_12_7", new arasuperobject(7,12,7,"وقضى يفتاح لاسرائيل ست سنين. ومات يفتاح الجلعادي ودفن في احدى مدن جلعاد"));
arasuperobject.biblemap.put("b7_12_8", new arasuperobject(7,12,8,"وقضى بعده لاسرائيل ابصان من بيت لحم"));
arasuperobject.biblemap.put("b7_12_9", new arasuperobject(7,12,9,"وكان له ثلاثون ابنا وثلاثون ابنة ارسلهنّ الى الخارج وأتى من الخارج بثلاثين ابنة لبنيه وقضى لاسرائيل سبع سنين"));
arasuperobject.biblemap.put("b7_12_10", new arasuperobject(7,12,10,"ومات ابصان ودفن في بيت لحم"));
arasuperobject.biblemap.put("b7_12_11", new arasuperobject(7,12,11,"وقضى بعده لاسرائيل ايلون الزبولوني. قضى لاسرائيل عشر سنين"));
arasuperobject.biblemap.put("b7_12_12", new arasuperobject(7,12,12,"ومات ايلون الزبولوني ودفن في ايلون في ارض زبولون"));
arasuperobject.biblemap.put("b7_12_13", new arasuperobject(7,12,13,"وقضى بعده لاسرائيل عبدون بن هلّيل الفرعتوني"));
arasuperobject.biblemap.put("b7_12_14", new arasuperobject(7,12,14,"وكان له اربعون ابنا وثلاثون حفيدا يركبون على سبعين جحشا قضى لاسرائيل ثماني سنين"));
arasuperobject.biblemap.put("b7_12_15", new arasuperobject(7,12,15,"ومات عبدون بن هلّيل الفرعتوني ودفن في فرعتون في ارض افرايم في جبل العمالقة"));
arasuperobject.biblemap.put("b7_13_1", new arasuperobject(7,13,1,"ثم عاد بنو اسرائيل يعملون الشر في عيني الرب فدفعهم الرب ليد الفلسطينيين اربعين سنة"));
arasuperobject.biblemap.put("b7_13_2", new arasuperobject(7,13,2,"وكان رجل من صرعة من عشيرة الدانيين اسمه منوح وامرأته عاقر لم تلد"));
arasuperobject.biblemap.put("b7_13_3", new arasuperobject(7,13,3,"فتراءى ملاك الرب للمرأة وقال لها. ها انت عاقر لم تلدي. ولكنك تحبلين وتلدين ابنا"));
arasuperobject.biblemap.put("b7_13_4", new arasuperobject(7,13,4,"والآن فاحذري ولا تشربي خمرا ولا مسكرا ولا تأكلي شيئا نجسا"));
arasuperobject.biblemap.put("b7_13_5", new arasuperobject(7,13,5,"فها انك تحبلين وتلدين ابنا ولا يعل موسى رأسه لان الصبي يكون نذيرا لله من البطن وهو يبدأ يخلص اسرائيل من يد الفلسطينيين"));
arasuperobject.biblemap.put("b7_13_6", new arasuperobject(7,13,6,"فدخلت المرأة وكلمت رجلها قائلة. جاء اليّ رجل الله ومنظره كمنظر ملاك الله مرهب جدا. ولم اسأله من اين هو ولا هو اخبرني عن اسمه"));
arasuperobject.biblemap.put("b7_13_7", new arasuperobject(7,13,7,"وقال لي ها انت تحبلين وتلدين ابنا. والآن فلا تشربي خمرا ولا مسكرا ولا تأكلي شيئا نجسا. لان الصبي يكون نذيرا للّه من البطن الى يوم موته"));
arasuperobject.biblemap.put("b7_13_8", new arasuperobject(7,13,8,"فصلّى منوح الى الرب وقال اسألك يا سيدي ان يأتي ايضا الينا رجل الله الذي ارسلته ويعلمنا ماذا نعمل للصبي الذي يولد"));
arasuperobject.biblemap.put("b7_13_9", new arasuperobject(7,13,9,"فسمع الله لصوت منوح فجاء ملاك الله ايضا الى المرأة وهي جالسة في الحقل ومنوح رجلها ليس معها"));
arasuperobject.biblemap.put("b7_13_10", new arasuperobject(7,13,10,"فاسرعت المرأة وركضت واخبرت رجلها وقالت له هوذا قد تراءى لي الرجل الذي جاء اليّ ذلك اليوم"));
arasuperobject.biblemap.put("b7_13_11", new arasuperobject(7,13,11,"فقام منوح وسار وراء امرأته وجاء الى الرجل وقال له أانت الرجل الذي تكلم مع المرأة. فقال انا هو"));
arasuperobject.biblemap.put("b7_13_12", new arasuperobject(7,13,12,"فقال منوح. عند مجيء كلامك ماذا يكون حكم الصبي ومعاملته"));
arasuperobject.biblemap.put("b7_13_13", new arasuperobject(7,13,13,"فقال ملاك الرب لمنوح. من كل ما قلت للمرأة فلتحتفظ"));
arasuperobject.biblemap.put("b7_13_14", new arasuperobject(7,13,14,"من كل ما يخرج من جفنة الخمر لا تأكل وخمرا ومسكرا لا تشرب وكل نجس لا تأكل. لتحذر من كل ما اوصيتها"));
arasuperobject.biblemap.put("b7_13_15", new arasuperobject(7,13,15,"فقال منوح لملاك الرب دعنا نعوقك ونعمل لك جدي معزى"));
arasuperobject.biblemap.put("b7_13_16", new arasuperobject(7,13,16,"فقال ملاك الرب لمنوح ولو عوقتني لا آكل من خبزك وان عملت محرقة فللرب اصعدها. لان منوح لم يعلم انه ملاك الرب"));
arasuperobject.biblemap.put("b7_13_17", new arasuperobject(7,13,17,"فقال منوح لملاك الرب ما اسمك حتى اذا جاء كلامك نكرمك"));
arasuperobject.biblemap.put("b7_13_18", new arasuperobject(7,13,18,"فقال له ملاك الرب لماذا تسأل عن اسمي وهو عجيب"));
arasuperobject.biblemap.put("b7_13_19", new arasuperobject(7,13,19,"فاخذ منوح جدي المعزى والتقدمة واصعدهما على الصخرة للرب. فعمل عملا عجيبا ومنوح وامرأته ينظران"));
arasuperobject.biblemap.put("b7_13_20", new arasuperobject(7,13,20,"فكان عند صعود اللهيب عن المذبح نحو السماء ان ملاك الرب صعد في لهيب المذبح ومنوح وامرأته ينظران فسقطا على وجهيهما الى الارض"));
arasuperobject.biblemap.put("b7_13_21", new arasuperobject(7,13,21,"ولم يعد ملاك الرب يتراءى لمنوح وامرأته. حينئذ عرف منوح انه ملاك الرب"));
arasuperobject.biblemap.put("b7_13_22", new arasuperobject(7,13,22,"فقال منوح لامرأته نموت موتا لاننا قد رأينا الله"));
arasuperobject.biblemap.put("b7_13_23", new arasuperobject(7,13,23,"فقالت له امرأته لو اراد الرب ان يميتنا لما اخذ من يدنا محرقة وتقدمة ولما ارانا كل هذه ولما كان في مثل هذا الوقت اسمعنا مثل هذه"));
arasuperobject.biblemap.put("b7_13_24", new arasuperobject(7,13,24,"فولدت المرأة ابنا ودعت اسمه شمشون. فكبر الصبي وباركه الرب"));
arasuperobject.biblemap.put("b7_13_25", new arasuperobject(7,13,25,"وابتدأ روح الرب يحركه في محلّة دان بين صرعة واشتأول"));
arasuperobject.biblemap.put("b7_14_1", new arasuperobject(7,14,1,"ونزل شمشون الى تمنة ورأى امرأة في تمنة من بنات الفلسطينيين"));
arasuperobject.biblemap.put("b7_14_2", new arasuperobject(7,14,2,"فصعد واخبر اباه وامه وقال قد رأيت امرأة في تمنة من بنات الفلسطينيين فالآن خذاها لي امرأة"));
arasuperobject.biblemap.put("b7_14_3", new arasuperobject(7,14,3,"فقال له ابوه وامه أليس في بنات اخوتك وفي كل شعبي امرأة حتى انك ذاهب لتأخذ امرأة من الفلسطينيين الغلف. فقال شمشون لابيه اياها خذ لي لانها حسنت في عينيّ"));
arasuperobject.biblemap.put("b7_14_4", new arasuperobject(7,14,4,"ولم يعلم ابوه وامه ان ذلك من الرب لانه كان يطلب علّة على الفلسطينيين. وفي ذلك الوقت كان الفلسطينيون متسلطين على اسرائيل"));
arasuperobject.biblemap.put("b7_14_5", new arasuperobject(7,14,5,"فنزل شمشون وابوه وامه الى تمنة وأتوا الى كروم تمنة. واذا بشبل اسد يزمجر للقائه"));
arasuperobject.biblemap.put("b7_14_6", new arasuperobject(7,14,6,"فحلّ عليه روح الرب فشقه كشق الجدي وليس في يده شيء. ولم يخبر اباه وامه بما فعل"));
arasuperobject.biblemap.put("b7_14_7", new arasuperobject(7,14,7,"فنزل وكلم المرأة فحسنت في عيني شمشون"));
arasuperobject.biblemap.put("b7_14_8", new arasuperobject(7,14,8,"ولما رجع بعد ايام لكي ياخذها مال لكي يرى رمّة الاسد واذا دبر من النحل في جوف الاسد مع عسل"));
arasuperobject.biblemap.put("b7_14_9", new arasuperobject(7,14,9,"فاشتار منه على كفيه وكان يمشي وياكل وذهب الى ابيه وامه واعطاهما فأكلا ولم يخبرهما انه من جوف الاسد اشتار العسل"));
arasuperobject.biblemap.put("b7_14_10", new arasuperobject(7,14,10,"ونزل ابوه الى المرأة فعمل هناك شمشون وليمة لانه هكذا كان يفعل الفتيان"));
arasuperobject.biblemap.put("b7_14_11", new arasuperobject(7,14,11,"فلما رأوه احضروا ثلاثين من الاصحاب فكانوا معه"));
arasuperobject.biblemap.put("b7_14_12", new arasuperobject(7,14,12,"فقال لهم شمشون لأحاجينكم أحجية. فاذا حللتموها لي في سبعة ايام الوليمة واصبتموها اعطيكم ثلاثين قميصا وثلاثين حلّة ثياب"));
arasuperobject.biblemap.put("b7_14_13", new arasuperobject(7,14,13,"وان لم تقدروا ان تحلّوها لي تعطوني انتم ثلاثين قميصا وثلاثين حلّة ثياب. فقالوا له حاج أحجيتك فنسمعها"));
arasuperobject.biblemap.put("b7_14_14", new arasuperobject(7,14,14,"فقال لهم من الآكل خرج أكل ومن الجافي خرجت حلاوة. فلم يستطيعوا ان يحلّوا الاحجية في ثلاثة ايام"));
arasuperobject.biblemap.put("b7_14_15", new arasuperobject(7,14,15,"وكان في اليوم السابع انهم قالوا لامرأة شمشون تملقي رجلك لكي يظهر لنا الاحجية لئلا نحرقك وبيت ابيك بنار. ألتسلبونا دعوتمونا ام لا"));
arasuperobject.biblemap.put("b7_14_16", new arasuperobject(7,14,16,"فبكت امرأة شمشون لديه وقالت انما كرهتني ولا تحبني. قد حاجيت بني شعبي احجية واياي لم تخبر. فقال لها هوذا ابي وامي لم اخبرهما فهل اياك اخبر"));
arasuperobject.biblemap.put("b7_14_17", new arasuperobject(7,14,17,"فبكت لديه السبعة الايام التي فيها كانت لهم الوليمة وكان في اليوم السابع انه اخبرها لانها ضايقته فاظهرت الاحجية لبني شعبها"));
arasuperobject.biblemap.put("b7_14_18", new arasuperobject(7,14,18,"فقال له رجال المدينة في اليوم السابع قبل غروب الشمس اي شيء احلى من العسل وما اجفى من الاسد. فقال لهم لو لم تحرثوا على عجلتي لما وجدتم أحجيتي"));
arasuperobject.biblemap.put("b7_14_19", new arasuperobject(7,14,19,"وحلّ عليه روح الرب فنزل الى اشقلون وقتل منهم ثلاثين رجلا واخذ سلبهم واعطى الحلل لمظهري الاحجية. وحمي غضبه وصعد الى بيت ابيه"));
arasuperobject.biblemap.put("b7_14_20", new arasuperobject(7,14,20,"فصارت امرأة شمشون لصاحبه الذي كان يصاحبه"));
arasuperobject.biblemap.put("b7_15_1", new arasuperobject(7,15,1,"وكان بعد مدّة في ايام حصاد الحنطة ان شمشون افتقد امرأته بجدي معزى. وقال ادخل الى امرأتي الى حجرتها. ولكن اباها لم يدعه ان يدخل"));
arasuperobject.biblemap.put("b7_15_2", new arasuperobject(7,15,2,"وقال ابوها اني قلت انك قد كرهتها فاعطيتها لصاحبك. أليست اختها الصغيرة احسن منها. فلتكن لك عوضا عنها"));
arasuperobject.biblemap.put("b7_15_3", new arasuperobject(7,15,3,"فقال لهم شمشون اني بريء الآن من الفلسطينيين اذا عملت بهم شرا"));
arasuperobject.biblemap.put("b7_15_4", new arasuperobject(7,15,4,"وذهب شمشون وامسك ثلاث مئة ابن آوى واخذ مشاعل وجعل ذنبا الى ذنب ووضع مشعلا بين كل ذنبين في الوسط"));
arasuperobject.biblemap.put("b7_15_5", new arasuperobject(7,15,5,"ثم اضرم المشاعل نارا واطلقها بين زروع الفلسطينيين فاحرق الاكداس والزرع وكروم الزيتون"));
arasuperobject.biblemap.put("b7_15_6", new arasuperobject(7,15,6,"فقال الفلسطينيون من فعل هذا. فقالوا شمشون صهر التمنّي لانه اخذ امرأته واعطاها لصاحبه. فصعد الفلسطينيون واحرقوها واباها بالنار"));
arasuperobject.biblemap.put("b7_15_7", new arasuperobject(7,15,7,"فقال لهم شمشون ولو فعلتم هذا فاني انتقم منكم وبعد اكفّ"));
arasuperobject.biblemap.put("b7_15_8", new arasuperobject(7,15,8,"وضربهم ساقا على فخذ ضربا عظيما. ثم نزل واقام في شق صخر عيطم"));
arasuperobject.biblemap.put("b7_15_9", new arasuperobject(7,15,9,"وصعد الفلسطينيون ونزلوا في يهوذا وتفرّقوا في لحي"));
arasuperobject.biblemap.put("b7_15_10", new arasuperobject(7,15,10,"فقال رجال يهوذا لماذا صعدتم علينا. فقالوا صعدنا لكي نوثق شمشون لنفعل به كما فعل بنا"));
arasuperobject.biblemap.put("b7_15_11", new arasuperobject(7,15,11,"فنزل ثلاثة آلاف رجل من يهوذا الى شقّ صخر عيطم وقالوا لشمشون أما علمت ان الفلسطينيين متسلطون علينا. فماذا فعلت بنا. فقال لهم كما فعلوا بي هكذا فعلت بهم"));
arasuperobject.biblemap.put("b7_15_12", new arasuperobject(7,15,12,"فقالوا له نزلنا لكي نوثقك ونسلمك الى يد الفلسطينيين. فقال لهم شمشون احلفوا لي انكم انتم لا تقعون عليّ"));
arasuperobject.biblemap.put("b7_15_13", new arasuperobject(7,15,13,"فكلموه قائلين كلا. ولكننا نوثقك ونسلمك الى يدهم وقتلا لا نقتلك. فاوثقوه بحبلين جديدين واصعدوه من الصخرة"));
arasuperobject.biblemap.put("b7_15_14", new arasuperobject(7,15,14,"ولما جاء الى لحي صاح الفلسطينيين للقائه. فحلّ عليه روح الرب فكان الحبلان اللذان على ذراعيه ككتان احرق بالنار فانحلّ الوثاق عن يديه"));
arasuperobject.biblemap.put("b7_15_15", new arasuperobject(7,15,15,"ووجد لحي حمار طريّا فمدّ يده واخذه وضرب به الف رجل"));
arasuperobject.biblemap.put("b7_15_16", new arasuperobject(7,15,16,"فقال شمشون بلحي حمار كومة كومتين. بلحي حمار قتلت الف رجل"));
arasuperobject.biblemap.put("b7_15_17", new arasuperobject(7,15,17,"ولما فرغ من الكلام رمى اللحي من يده ودعا ذلك المكان رمت لحي"));
arasuperobject.biblemap.put("b7_15_18", new arasuperobject(7,15,18,"ثم عطش جدا فدعا الرب وقال انك قد جعلت بيد عبدك هذا الخلاص العظيم والآن اموت من العطش واسقط بيد الغلف"));
arasuperobject.biblemap.put("b7_15_19", new arasuperobject(7,15,19,"فشقّ الله الكفّة التي في لحي فخرج منها ماء فشرب ورجعت روحه فانتعش. لذلك دعا اسمه عين هقّوري التي في لحي الى هذا اليوم"));
arasuperobject.biblemap.put("b7_15_20", new arasuperobject(7,15,20,"وقضى لاسرائيل في ايام الفلسطينيين عشرين سنة"));
arasuperobject.biblemap.put("b7_16_1", new arasuperobject(7,16,1,"ثم ذهب شمشون الى غزّة ورأى هناك امرأة زانية فدخل اليها"));
arasuperobject.biblemap.put("b7_16_2", new arasuperobject(7,16,2,"فقيل للغزّيين قد اتى شمشون الى هنا. فاحاطوا به وكمنوا له الليل كله عند باب المدينة فهدأوا الليل كله قائلين عند ضوء الصباح نقتله"));
arasuperobject.biblemap.put("b7_16_3", new arasuperobject(7,16,3,"فاضطجع شمشون الى نصف الليل ثم قام في نصف الليل واخذ مصراعي باب المدينة والقائمتين وقلعهما مع العارضة ووضعها على كتفيه وصعد بها الى راس الجبل الذي مقابل حبرون"));
arasuperobject.biblemap.put("b7_16_4", new arasuperobject(7,16,4,"وكان بعد ذلك انه احب امرأة في وادي سورق اسمها دليلة"));
arasuperobject.biblemap.put("b7_16_5", new arasuperobject(7,16,5,"فصعد اليها اقطاب الفلسطينيين وقالوا لها تملقيه وانظري بماذا قوته العظيمة وبماذا نتمكن منه لكي نوثقه لاذلاله فنعطيك كل واحد الفا ومئة شاقل فضة"));
arasuperobject.biblemap.put("b7_16_6", new arasuperobject(7,16,6,"فقالت دليلة لشمشون اخبرني بماذا قوتك العظيمة وبماذا توثق لاذلالك"));
arasuperobject.biblemap.put("b7_16_7", new arasuperobject(7,16,7,"فقال لها شمشون اذا اوثقوني بسبعة اوتار طرية لم تجف اضعف واصير كواحد من الناس"));
arasuperobject.biblemap.put("b7_16_8", new arasuperobject(7,16,8,"فاصعد لها اقطاب الفلسطينيين سبعة اوتار طرية لم تجف فاوثقته بها"));
arasuperobject.biblemap.put("b7_16_9", new arasuperobject(7,16,9,"والكمين لابث عندها في الحجرة. فقالت له الفلسطينيون عليك يا شمشون. فقطع الاوتار كما يقطع فتيل المشاقة اذ شمّ النار ولم تعلم قوته"));
arasuperobject.biblemap.put("b7_16_10", new arasuperobject(7,16,10,"فقالت دليلة لشمشون ها قد ختلتني وكلمتني بالكذب. فاخبرني الآن بماذا توثق"));
arasuperobject.biblemap.put("b7_16_11", new arasuperobject(7,16,11,"فقال لها اذا اوثقوني بحبال جديدة لم تستعمل اضعف واصير كواحد من الناس"));
arasuperobject.biblemap.put("b7_16_12", new arasuperobject(7,16,12,"فأخذت دليلة حبالا جديدة واوثقته بها وقالت له الفلسطينيون عليك يا شمشون. والكمين لابث في الحجرة. فقطعها عن ذراعيه كخيط"));
arasuperobject.biblemap.put("b7_16_13", new arasuperobject(7,16,13,"فقالت دليلة لشمشون حتى الآن ختلتني وكلمتني بالكذب. فاخبرني بماذا توثق. فقال لها اذا ضفرت سبع خصل راسي مع السدى"));
arasuperobject.biblemap.put("b7_16_14", new arasuperobject(7,16,14,"فمكنتها بالوتد وقالت له الفلسطينيون عليك يا شمشون. فانتبه من نومه وقلع وتد النسيج والسدى"));
arasuperobject.biblemap.put("b7_16_15", new arasuperobject(7,16,15,"فقالت له كيف تقول احبك وقلبك ليس معي. هوذا ثلاث مرات قد ختلتني ولم تخبرني بماذا قوتك العظيمة"));
arasuperobject.biblemap.put("b7_16_16", new arasuperobject(7,16,16,"ولما كانت تضايقه بكلامها كل يوم والحّت عليه ضاقت نفسه الى الموت"));
arasuperobject.biblemap.put("b7_16_17", new arasuperobject(7,16,17,"فكشف لها كل قلبه وقال لها لم يعل موسى راسي لاني نذير الله من بطن امي. فان حلقت تفارقني قوتي واضعف واصير كاحد الناس"));
arasuperobject.biblemap.put("b7_16_18", new arasuperobject(7,16,18,"ولما رأت دليلة انه قد اخبرها بكل ما بقلبه ارسلت فدعت اقطاب الفلسطينيين وقالت اصعدوا هذه المرة فانه قد كشف لي كل قلبه. فصعد اليها اقطاب الفلسطينيين واصعدوا الفضة بيدهم"));
arasuperobject.biblemap.put("b7_16_19", new arasuperobject(7,16,19,"وانامته على ركبتيها ودعت رجلا وحلقت سبع خصل رأسه وابتدأت باذلاله وفارقته قوته"));
arasuperobject.biblemap.put("b7_16_20", new arasuperobject(7,16,20,"وقالت الفلسطينيون عليك يا شمشون. فانتبه من نومه وقال اخرج حسب كل مرة وانتفض. ولم يعلم ان الرب قد فارقه"));
arasuperobject.biblemap.put("b7_16_21", new arasuperobject(7,16,21,"فأخذه الفلسطينيون وقلعوا عينيه ونزلوا به الى غزّة واوثقوه بسلاسل نحاس وكان يطحن في بيت السجن"));
arasuperobject.biblemap.put("b7_16_22", new arasuperobject(7,16,22,"وابتدأ شعر راسه ينبت بعد ان حلق"));
arasuperobject.biblemap.put("b7_16_23", new arasuperobject(7,16,23,"واما اقطاب الفلسطينيين فاجتمعوا ليذبحوا ذبيحة عظيمة لداجون الههم ويفرحوا وقالوا قد دفع الهنا ليدنا شمشون عدونا"));
arasuperobject.biblemap.put("b7_16_24", new arasuperobject(7,16,24,"ولما رآه الشعب مجدوا الههم لانهم قالوا قد دفع الهنا ليدنا عدونا الذي خرب ارضنا وكثر قتلانا"));
arasuperobject.biblemap.put("b7_16_25", new arasuperobject(7,16,25,"وكان لما طابت قلوبهم انهم قالوا ادعوا شمشون ليلعب لنا. فدعوا شمشون من بيت السجن فلعب امامهم واوقفوه بين الاعمدة"));
arasuperobject.biblemap.put("b7_16_26", new arasuperobject(7,16,26,"فقال شمشون للغلام الماسك بيده دعني المس الاعمدة التي البيت قائم عليها لاستند عليها"));
arasuperobject.biblemap.put("b7_16_27", new arasuperobject(7,16,27,"وكان البيت مملوءا رجالا ونساء وكان هناك جميع اقطاب الفلسطينيين وعلى السطح نحو ثلاثة آلاف رجل وامرأة ينظرون لعب شمشون"));
arasuperobject.biblemap.put("b7_16_28", new arasuperobject(7,16,28,"فدعا شمشون الرب وقال يا سيدي الرب اذكرني وشددني يا الله هذه المرة فقط فانتقم نقمة واحدة عن عينيّ من الفلسطينيين"));
arasuperobject.biblemap.put("b7_16_29", new arasuperobject(7,16,29,"وقبض شمشون على العمودين المتوسطين اللذين كان البيت قائما عليهما واستند عليهما الواحد بيمينه والآخر بيساره"));
arasuperobject.biblemap.put("b7_16_30", new arasuperobject(7,16,30,"وقال شمشون لتمت نفسي مع الفلسطينيين. وانحنى بقوة فسقط البيت على الاقطاب وعلى كل الشعب الذي فيه فكان الموتى الذين اماتهم في موته اكثر من الذين اماتهم في حياته"));
arasuperobject.biblemap.put("b7_16_31", new arasuperobject(7,16,31,"فنزل اخوته وكل بيت ابيه وحملوه وصعدوا به ودفنوه بين صرعة واشتأول في قبر منوح ابيه. وهو قضى لاسرائيل عشرين سنة"));
arasuperobject.biblemap.put("b7_17_1", new arasuperobject(7,17,1,"وكان رجل من جبل افرايم اسمه ميخا"));
arasuperobject.biblemap.put("b7_17_2", new arasuperobject(7,17,2,"فقال لامه ان الالف والمئة شاقل الفضة التي أخذت منك وانت لعنت وقلت ايضا في اذنيّ. هوذا الفضة معي انا اخذتها. فقالت امه مبارك انت من الرب يا ابني"));
arasuperobject.biblemap.put("b7_17_3", new arasuperobject(7,17,3,"فرد الالف والمئة شاقل الفضة لامه فقالت امه تقديسا قدست الفضة للرب من يدي لابني لعمل تمثال منحوت وتمثال مسبوك. فالآن اردها لك"));
arasuperobject.biblemap.put("b7_17_4", new arasuperobject(7,17,4,"فرد الفضّة لامه فاخذت امه مئتي شاقل فضة واعطتها للصائغ فعملها تمثالا منحوتا وتمثالا مسبوكا وكانا في بيت ميخا"));
arasuperobject.biblemap.put("b7_17_5", new arasuperobject(7,17,5,"وكان للرجل ميخا بيت للآلهة فعمل افودا وترافيم وملأ يد واحد من بنيه فصار له كاهنا"));
arasuperobject.biblemap.put("b7_17_6", new arasuperobject(7,17,6,"وفي تلك الايام لم يكن ملك في اسرائيل. كان كل واحد يعمل ما يحسن في عينيه"));
arasuperobject.biblemap.put("b7_17_7", new arasuperobject(7,17,7,"وكان غلام من بيت لحم يهوذا من عشيرة يهوذا وهو لاوي متغرب هناك"));
arasuperobject.biblemap.put("b7_17_8", new arasuperobject(7,17,8,"فذهب الرجل من المدينة من بيت لحم يهوذا لكي يتغرب حيثما اتفق. فأتى الى جبل افرايم الى بيت ميخا وهو آخذ في طريقه"));
arasuperobject.biblemap.put("b7_17_9", new arasuperobject(7,17,9,"فقال له ميخا من اين اتيت. فقال له انا لاوي من بيت لحم يهوذا وانا ذاهب لكي اتغرب حيثما اتّفق"));
arasuperobject.biblemap.put("b7_17_10", new arasuperobject(7,17,10,"فقال له ميخا اقم عندي وكن لي ابا وكاهنا وانا اعطيك عشرة شواقل فضة في السنة وحلّة ثياب وقوتك. فذهب معه اللاوي"));
arasuperobject.biblemap.put("b7_17_11", new arasuperobject(7,17,11,"فرضي اللاوي بالاقامة مع الرجل وكان الغلام له كاحد بنيه"));
arasuperobject.biblemap.put("b7_17_12", new arasuperobject(7,17,12,"فملأ ميخا يد اللاوي وكان الغلام له كاهنا وكان في بيت ميخا"));
arasuperobject.biblemap.put("b7_17_13", new arasuperobject(7,17,13,"فقال ميخا الآن علمت ان الرب يحسن اليّ لانه صار لي اللاوي كاهنا"));
arasuperobject.biblemap.put("b7_18_1", new arasuperobject(7,18,1,"وفي تلك الايام لم يكن ملك في اسرائيل. وفي تلك الايام كان سبط الدانيين يطلب له ملكا للسكنى. لانه الى ذلك اليوم لم يقع له نصيب في وسط اسباط اسرائيل"));
arasuperobject.biblemap.put("b7_18_2", new arasuperobject(7,18,2,"فارسل بنو دان من عشيرتهم خمسة رجال منهم رجالا بني بأس من صرعة ومن اشتأول لتجسس الارض وفحصها. وقالوا لهم اذهبوا افحصوا الارض. فجاءوا الى جبل افرايم الى بيت ميخا وباتوا هناك"));
arasuperobject.biblemap.put("b7_18_3", new arasuperobject(7,18,3,"وبينما هم عند بيت ميخا عرفوا صوت الغلام اللاوي فمالوا الى هناك وقالوا له. من جاء بك الى هنا وماذا انت عامل في هذا المكان ومالك هنا"));
arasuperobject.biblemap.put("b7_18_4", new arasuperobject(7,18,4,"فقال لهم كذا وكذا عمل لي ميخا وقد استأجرني فصرت له كاهنا"));
arasuperobject.biblemap.put("b7_18_5", new arasuperobject(7,18,5,"فقالوا له اسأل اذن من الله لنعلم هل ينجح طريقنا الذي نحن سائرون فيه"));
arasuperobject.biblemap.put("b7_18_6", new arasuperobject(7,18,6,"فقال لهم الكاهن اذهبوا بسلام. امام الرب طريقكم الذي تسيرون فيه"));
arasuperobject.biblemap.put("b7_18_7", new arasuperobject(7,18,7,"فذهب الخمسة الرجال وجاءوا الى لايش ورأوا الشعب الذين فيها ساكنين بطمانينة كعادة الصيدونيين مستريحين مطمئنين وليس في الارض مؤذ بأمر وارث رياسة وهم بعيدون عن الصيدونيين وليس لهم امر مع انسان"));
arasuperobject.biblemap.put("b7_18_8", new arasuperobject(7,18,8,"وجاءوا الى اخوتهم الى صرعة واشتأول فقال لهم اخوتهم ما انتم"));
arasuperobject.biblemap.put("b7_18_9", new arasuperobject(7,18,9,"فقالوا قوموا نصعد اليهم لاننا رأينا الارض وهوذا هي جيدة جدا وانتم ساكتون. لا تتكاسلوا عن الذهاب لتدخلوا وتملكوا الارض"));
arasuperobject.biblemap.put("b7_18_10", new arasuperobject(7,18,10,"عند مجيئكم تاتون الى شعب مطمئن والارض واسعة الطرفين. ان الله قد دفعها ليدكم. مكان ليس فيه عوز لشيء مما في الارض"));
arasuperobject.biblemap.put("b7_18_11", new arasuperobject(7,18,11,"فارتحل من هناك من عشيرة الدانيين من صرعة ومن اشتأول ست مئة رجل متسلحين بعدة الحرب"));
arasuperobject.biblemap.put("b7_18_12", new arasuperobject(7,18,12,"وصعدوا وحلّوا في قرية يعاريم في يهوذا. لذلك دعوا ذلك المكان محلّة دان الى هذا اليوم. هوذا هي وراء قرية يعاريم"));
arasuperobject.biblemap.put("b7_18_13", new arasuperobject(7,18,13,"وعبروا من هناك الى جبل افرايم وجاءوا الى بيت ميخا"));
arasuperobject.biblemap.put("b7_18_14", new arasuperobject(7,18,14,"فاجاب الخمسة الرجال الذين ذهبوا لتجسّس ارض لايش وقالوا لاخوتهم أتعلمون ان في هذه البيوت افودا وترافيم وتمثالا منحوتا وتمثالا مسبوكا. فالآن اعلموا ما تفعلون"));
arasuperobject.biblemap.put("b7_18_15", new arasuperobject(7,18,15,"فمالوا الى هناك وجاءوا الى بيت الغلام اللاوي بيت ميخا وسلموا عليه"));
arasuperobject.biblemap.put("b7_18_16", new arasuperobject(7,18,16,"والست مئة الرجل المتسلحون بعدتهم للحرب واقفون عند مدخل الباب. هؤلاء من بني دان"));
arasuperobject.biblemap.put("b7_18_17", new arasuperobject(7,18,17,"فصعد الخمسة الرجال الذين ذهبوا لتجسّس الارض ودخلوا الى هناك واخذوا التمثال المنحوت والافود والترافيم والتمثال المسبوك. والكاهن واقف عند مدخل الباب مع الست مئة الرجل المتسلحين بعدة الحرب"));
arasuperobject.biblemap.put("b7_18_18", new arasuperobject(7,18,18,"وهؤلاء دخلوا بيت ميخا وأخذوا التمثال المنحوت والافود والترافيم والتمثال المسبوك. فقال لهم الكاهن ماذا تفعلون"));
arasuperobject.biblemap.put("b7_18_19", new arasuperobject(7,18,19,"فقالوا له اخرس. ضع يدك على فمك واذهب معنا وكن لنا ابا وكاهنا. أهو خير لك ان تكون كاهنا لبيت رجل واحد ام ان تكون كاهنا لسبط ولعشيرة في اسرائيل"));
arasuperobject.biblemap.put("b7_18_20", new arasuperobject(7,18,20,"فطاب قلب الكاهن واخذ الافود والترافيم والتمثال المنحوت ودخل في وسط الشعب"));
arasuperobject.biblemap.put("b7_18_21", new arasuperobject(7,18,21,"ثم انصرفوا وذهبوا ووضعوا الاطفال والماشية والثقل قدامهم"));
arasuperobject.biblemap.put("b7_18_22", new arasuperobject(7,18,22,"ولما ابتعدوا عن بيت ميخا اجتمع الرجال الذين في البيوت التي عند بيت ميخا وادركوا بني دان"));
arasuperobject.biblemap.put("b7_18_23", new arasuperobject(7,18,23,"وصاحوا الى بني دان فالتفتوا وقالوا لميخا ما لك صرخت"));
arasuperobject.biblemap.put("b7_18_24", new arasuperobject(7,18,24,"فقال. آلهتي التي عملت قد اخذتموها مع الكاهن وذهبتم فماذا لي بعد. وما هذا تقولون لي مالك"));
arasuperobject.biblemap.put("b7_18_25", new arasuperobject(7,18,25,"فقال له بنو دان لا تسمّع صوتك بيننا لئلا يقع بكم رجال انفسهم مرّة فتنزع نفسك وانفس بيتك"));
arasuperobject.biblemap.put("b7_18_26", new arasuperobject(7,18,26,"وسار بنو دان في طريقهم. ولما رأى ميخا انهم اشدّ منه انصرف ورجع الى بيته"));
arasuperobject.biblemap.put("b7_18_27", new arasuperobject(7,18,27,"واما هم فأخذوا ما صنع ميخا والكاهن الذي كان له وجاءوا الى لايش الى شعب مستريح مطمئن وضربوهم بحد السيف واحرقوا المدينة بالنار"));
arasuperobject.biblemap.put("b7_18_28", new arasuperobject(7,18,28,"ولم يكن من ينقذ لانها بعيدة عن صيدون ولم يكن لهم امر مع انسان وهي في الوادي الذي لبيت رحوب. فبنوا المدينة وسكنوا بها"));
arasuperobject.biblemap.put("b7_18_29", new arasuperobject(7,18,29,"ودعوا اسم المدينة دان باسم دان ابيهم الذي ولد لاسرائيل. ولكن اسم المدينة اولا لايش"));
arasuperobject.biblemap.put("b7_18_30", new arasuperobject(7,18,30,"واقام بنو دان لانفسهم التمثال المنحوت وكان يهوناثان ابن جرشوم بن منسّى هو وبنوه كهنة لسبط الدانيين الى يوم سبي الارض"));
arasuperobject.biblemap.put("b7_18_31", new arasuperobject(7,18,31,"ووضعوا لانفسهم تمثال ميخا المنحوت الذي عمله كل الايام التي كان فيها بيت الله في شيلوه"));
arasuperobject.biblemap.put("b7_19_1", new arasuperobject(7,19,1,"وفي تلك الايام حين لم يكن ملك في اسرائيل كان رجل لاوي متغربا في عقاب جبل افرايم. فاتخذ له امرأة سرية من بيت لحم يهوذا"));
arasuperobject.biblemap.put("b7_19_2", new arasuperobject(7,19,2,"فزنت عليه سريته وذهبت من عنده الى بيت ابيها في بيت لحم يهوذا وكانت هناك اياما اربعة اشهر"));
arasuperobject.biblemap.put("b7_19_3", new arasuperobject(7,19,3,"فقام رجلها وسار وراءها ليطيّب قلبها ويردّها ومعه غلامه وحماران. فادخلته بيت ابيها. فلما رآه ابو الفتاة فرح بلقائه"));
arasuperobject.biblemap.put("b7_19_4", new arasuperobject(7,19,4,"وامسكه حموه ابو الفتاة فمكث معه ثلاثة ايام فأكلوا وشربوا وباتوا هناك"));
arasuperobject.biblemap.put("b7_19_5", new arasuperobject(7,19,5,"وكان في اليوم الرابع انهم بكروا صباحا وقام للذهاب. فقال ابو الفتاة لصهره اسند قلبك بكسرة خبز وبعد تذهبون"));
arasuperobject.biblemap.put("b7_19_6", new arasuperobject(7,19,6,"فجلسا وأكلا كلاهما معا وشربا. وقال ابو الفتاة للرجل ارتض وبتّ وليطب قلبك"));
arasuperobject.biblemap.put("b7_19_7", new arasuperobject(7,19,7,"ولما قام الرجل للذهاب الحّ عليه حموه فعاد وبات هناك"));
arasuperobject.biblemap.put("b7_19_8", new arasuperobject(7,19,8,"ثم بكر في الغد في اليوم الخامس للذهاب فقال ابو الفتاة اسند قلبك. وتوانوا حتى يميل النهار. واكلا كلاهما"));
arasuperobject.biblemap.put("b7_19_9", new arasuperobject(7,19,9,"ثم قام الرجل للذهاب هو وسريته وغلامه فقال له حموه ابو الفتاة ان النهار قد مال الى الغروب. بيتوا الآن. هوذا آخر النهار. بتّ هنا وليطب قلبك وغدا تبكرون في طريقكم وتذهب الى خيمتك"));
arasuperobject.biblemap.put("b7_19_10", new arasuperobject(7,19,10,"فلم يرد الرجل ان يبيت بل قام وذهب وجاء الى مقابل يبوس. هي اورشليم. ومعه حماران مشدودان وسريته معه"));
arasuperobject.biblemap.put("b7_19_11", new arasuperobject(7,19,11,"وفيما هم عند يبوس والنهار قد انحدر جدا قال الغلام لسيده تعال نميل الى مدينة اليبوسيين هذه ونبيت فيها"));
arasuperobject.biblemap.put("b7_19_12", new arasuperobject(7,19,12,"فقال له سيده لا نميل الى مدينة غريبة حيث ليس احد من بني اسرائيل هنا. نعبر الى جبعة"));
arasuperobject.biblemap.put("b7_19_13", new arasuperobject(7,19,13,"وقال لغلامه تعال نتقدم الى احد الاماكن ونبيت في جبعة او في الرامة"));
arasuperobject.biblemap.put("b7_19_14", new arasuperobject(7,19,14,"فعبروا وذهبوا وغابت لهم الشمس عند جبعة التي لبنيامين"));
arasuperobject.biblemap.put("b7_19_15", new arasuperobject(7,19,15,"فمالوا الى هناك لكي يدخلوا ويبيتوا في جبعة. فدخل وجلس في ساحة المدينة ولم يضمّهم احد الى بيته للمبيت"));
arasuperobject.biblemap.put("b7_19_16", new arasuperobject(7,19,16,"واذا برجل شيخ جاء من شغله من الحقل عند المساء. والرجل من جبل افرايم وهو غريب في جبعة ورجال المكان بنيامينيون"));
arasuperobject.biblemap.put("b7_19_17", new arasuperobject(7,19,17,"فرفع عينيه ورأى الرجل المسافر في ساحة المدينة فقال الرجل الشيخ الى اين تذهب ومن اين اتيت"));
arasuperobject.biblemap.put("b7_19_18", new arasuperobject(7,19,18,"فقال له نحن عابرون من بيت لحم يهوذا الى عقاب جبل افرايم. انا من هناك وقد ذهبت الى بيت لحم يهوذا وانا ذاهب الى بيت الرب وليس احد يضّمني الى البيت"));
arasuperobject.biblemap.put("b7_19_19", new arasuperobject(7,19,19,"وايضا عندنا تبن وعلف لحميرنا وايضا خبز وخمر لي ولامتك وللغلام الذي مع عبيدك. ليس احتياج الى شيء"));
arasuperobject.biblemap.put("b7_19_20", new arasuperobject(7,19,20,"فقال الرجل الشيخ السلام لك. انما كل احتياجك عليّ ولكن لا تبت في الساحة"));
arasuperobject.biblemap.put("b7_19_21", new arasuperobject(7,19,21,"وجاء به الى بيته وعلف حميرهم فغسلوا ارجلهم وأكلوا وشربوا"));
arasuperobject.biblemap.put("b7_19_22", new arasuperobject(7,19,22,"وفيما هم يطيبون قلوبهم اذا برجال المدينة رجال بني بليعال احاطوا بالبيت قارعين الباب وكلموا الرجل صاحب البيت الشيخ قائلين اخرج الرجل الذي دخل بيتك فنعرفه"));
arasuperobject.biblemap.put("b7_19_23", new arasuperobject(7,19,23,"فخرج اليهم الرجل صاحب البيت وقال لهم لا يا اخوتي لا تفعلوا شرا. بعدما دخل هذا الرجل بيتي لا تفعلوا هذه القباحة"));
arasuperobject.biblemap.put("b7_19_24", new arasuperobject(7,19,24,"هوذا ابنتي العذراء وسريته دعوني اخرجهما فاذلوهما وافعلوا بهما ما يحسن في اعينكم واما هذا الرجل فلا تعملوا به هذا الامر القبيح"));
arasuperobject.biblemap.put("b7_19_25", new arasuperobject(7,19,25,"فلم يرد الرجال ان يسمعوا له. فامسك الرجل سريته واخرجها اليهم خارجا فعرفوها وتعللوا بها الليل كله الى الصباح وعند طلوع الفجر اطلقوها"));
arasuperobject.biblemap.put("b7_19_26", new arasuperobject(7,19,26,"فجاءت المرأة عند اقبال الصباح وسقطت عند باب بيت الرجل حيث سيدها هناك الى الضوء"));
arasuperobject.biblemap.put("b7_19_27", new arasuperobject(7,19,27,"فقام سيدها في الصباح وفتح ابواب البيت وخرج للذهاب في طريقه واذا بالمرأة سريته ساقطة على باب البيت ويداها على العتبة"));
arasuperobject.biblemap.put("b7_19_28", new arasuperobject(7,19,28,"فقال لها قومي نذهب. فلم يكن مجيب. فأخذها على الحمار وقام الرجل وذهب الى مكانه"));
arasuperobject.biblemap.put("b7_19_29", new arasuperobject(7,19,29,"ودخل بيته واخذ السكين وامسك سريته وقطعها مع عظامها الى اثنتي عشرة قطعة وارسلها الى جميع تخوم اسرائيل"));
arasuperobject.biblemap.put("b7_19_30", new arasuperobject(7,19,30,"وكل من رأى قال لم يكن ولم ير مثل هذا من يوم صعود بني اسرائيل من ارض مصر الى هذا اليوم. تبصّروا فيه وتشاوروا وتكلموا"));
arasuperobject.biblemap.put("b7_20_1", new arasuperobject(7,20,1,"فخرج جميع بني اسرائيل واجتمعت الجماعة كرجل واحد من دان الى بئر سبع مع ارض جلعاد الى الرب في المصفاة"));
arasuperobject.biblemap.put("b7_20_2", new arasuperobject(7,20,2,"ووقف وجوه جميع الشعب جميع اسباط اسرائيل في مجمع شعب الله اربع مئة الف راجل مخترطي السيف"));
arasuperobject.biblemap.put("b7_20_3", new arasuperobject(7,20,3,"فسمع بنو بنيامين ان بني اسرائيل قد صعدوا الى المصفاة. وقال بنو اسرائيل تكلموا. كيف كانت هذه القباحة"));
arasuperobject.biblemap.put("b7_20_4", new arasuperobject(7,20,4,"فاجاب الرجل اللاوي بعل المرأة المقتولة وقال دخلت انا وسريتي الى جبعة التي لبنيامين لنبيت"));
arasuperobject.biblemap.put("b7_20_5", new arasuperobject(7,20,5,"فقام عليّ اصحاب جبعة واحاطوا عليّ بالبيت ليلا وهموا بقتلي واذلّوا سريتي حتى ماتت"));
arasuperobject.biblemap.put("b7_20_6", new arasuperobject(7,20,6,"فامسكت سريتي وقطعتها وارسلتها الى جميع حقول ملك اسرائيل. لانهم فعلوا رذالة وقباحة في اسرائيل"));
arasuperobject.biblemap.put("b7_20_7", new arasuperobject(7,20,7,"هوذا كلكم بنو اسرائيل هاتوا حكمكم ورايكم ههنا"));
arasuperobject.biblemap.put("b7_20_8", new arasuperobject(7,20,8,"فقام جميع الشعب كرجل واحد وقالوا لا يذهب احد منا الى خيمته ولا يميل احد الى بيته"));
arasuperobject.biblemap.put("b7_20_9", new arasuperobject(7,20,9,"والآن هذا هو الامر الذي نعمله بجبعة. عليها بالقرعة"));
arasuperobject.biblemap.put("b7_20_10", new arasuperobject(7,20,10,"فنأخذ عشرة رجال من المئة من جميع اسباط اسرائيل ومئة من الالف والفا من الربوة لاجل اخذ زاد للشعب ليفعلوا عند دخولهم جبعة بنيامين حسب كل القباحة التي فعلت باسرائيل"));
arasuperobject.biblemap.put("b7_20_11", new arasuperobject(7,20,11,"فاجتمع جميع رجال اسرائيل على المدينة متّحدين كرجل واحد"));
arasuperobject.biblemap.put("b7_20_12", new arasuperobject(7,20,12,"وارسل اسباط اسرائيل رجالا الى جميع اسباط بنيامين قائلين ما هذا الشر الذي صار فيكم"));
arasuperobject.biblemap.put("b7_20_13", new arasuperobject(7,20,13,"فالآن سلموا القوم بني بليعال الذين في جبعة لكي نقتلهم وننزع الشر من اسرائيل. فلم يرد بنو بنيامين ان يسمعوا لصوت اخوتهم بني اسرائيل"));
arasuperobject.biblemap.put("b7_20_14", new arasuperobject(7,20,14,"فاجتمع بنو بنيامين من المدن الى جبعة لكي يخرجوا لمحاربة بني اسرائيل"));
arasuperobject.biblemap.put("b7_20_15", new arasuperobject(7,20,15,"وعدّ بنو بنيامين في ذلك اليوم من المدن ستة وعشرين الف رجل مخترطي السيف ما عدا سكان جبعة الذين عدّوا سبع مئة رجل منتخبين"));
arasuperobject.biblemap.put("b7_20_16", new arasuperobject(7,20,16,"من جميع هذا الشعب سبع مئة رجل منتخبين عسر. كل هؤلاء يرمون الحجر بالمقلاع على الشعرة ولا يخطئون"));
arasuperobject.biblemap.put("b7_20_17", new arasuperobject(7,20,17,"وعدّ رجال اسرائيل ما عدا بنيامين اربع مئة الف رجل مخترطي السيف. كل هؤلاء رجال حرب"));
arasuperobject.biblemap.put("b7_20_18", new arasuperobject(7,20,18,"فقاموا وصعدوا الى بيت ايل وسألوا الله وقال بنو اسرائيل من يصعد منا اولا لمحاربة بني بنيامين. فقال الرب يهوذا اولا"));
arasuperobject.biblemap.put("b7_20_19", new arasuperobject(7,20,19,"فقام بنو اسرائيل في الصباح ونزلوا على جبعة"));
arasuperobject.biblemap.put("b7_20_20", new arasuperobject(7,20,20,"وخرج رجال اسرائيل لمحاربة بنيامين وصف رجال اسرائيل انفسهم للحرب عند جبعة"));
arasuperobject.biblemap.put("b7_20_21", new arasuperobject(7,20,21,"فخرج بنو بنيامين من جبعة واهلكوا من اسرائيل في ذلك اليوم اثنين وعشرين الف رجل الى الارض"));
arasuperobject.biblemap.put("b7_20_22", new arasuperobject(7,20,22,"وتشدد الشعب رجال اسرائيل وعادوا فاصطفوا للحرب في المكان الذي اصطفوا فيه في اليوم الاول"));
arasuperobject.biblemap.put("b7_20_23", new arasuperobject(7,20,23,"ثم صعد بنو اسرائيل وبكوا امام الرب الى المساء وسألوا الرب قائلين هل اعود اتقدم لمحاربة بني بنيامين اخي. فقال الرب اصعدوا اليه"));
arasuperobject.biblemap.put("b7_20_24", new arasuperobject(7,20,24,"فتقدم بنو اسرائيل الى بني بنيامين في اليوم الثاني"));
arasuperobject.biblemap.put("b7_20_25", new arasuperobject(7,20,25,"فخرج بنيامين للقائهم من جبعة في اليوم الثاني واهلك من بني اسرائيل ايضا ثمانية عشر الف رجل الى الارض. كل هؤلاء مخترطوا السيف"));
arasuperobject.biblemap.put("b7_20_26", new arasuperobject(7,20,26,"فصعد جميع بني اسرائيل وكل الشعب وجاءوا الى بيت ايل وبكوا وجلسوا هناك امام الرب وصاموا ذلك اليوم الى المساء واصعدوا محرقات وذبائح سلامة امام الرب"));
arasuperobject.biblemap.put("b7_20_27", new arasuperobject(7,20,27,"وسأل بنو اسرائيل الرب. وهناك تابوت عهد الله في تلك الايام"));
arasuperobject.biblemap.put("b7_20_28", new arasuperobject(7,20,28,"وفينحاس بن العازار بن هرون واقف امامه في تلك الايام. قائلين أأعود ايضا للخروج لمحاربة بني بنيامين اخي ام اكفّ. فقال الرب اصعدوا لاني غدا ادفعهم ليدك"));
arasuperobject.biblemap.put("b7_20_29", new arasuperobject(7,20,29,"ووضع اسرائيل كمينا على جبعة محيطا"));
arasuperobject.biblemap.put("b7_20_30", new arasuperobject(7,20,30,"وصعد بنو اسرائيل على بني بنيامين في اليوم الثالث واصطفوا عند جبعة كالمرة الاولى والثانية"));
arasuperobject.biblemap.put("b7_20_31", new arasuperobject(7,20,31,"فخرج بنو بنيامين للقاء الشعب وانجذبوا عن المدينة واخذوا يضربون من الشعب قتلى كالمرة الاولى والثانية في السكك التي احداها تصعد الى بيت ايل والاخرى الى جبعة في الحقل نحو ثلاثين رجلا من اسرائيل"));
arasuperobject.biblemap.put("b7_20_32", new arasuperobject(7,20,32,"وقال بنو بنيامين انهم منهزمون امامنا كما في الاول. واما بنو اسرائيل فقالوا لنهرب ونجذبهم عن المدينة الى السكك"));
arasuperobject.biblemap.put("b7_20_33", new arasuperobject(7,20,33,"وقام جميع رجال اسرائيل من اماكنهم واصطفوا في بعل تامار وثار كمين اسرائيل من مكانه من عراء جبعة"));
arasuperobject.biblemap.put("b7_20_34", new arasuperobject(7,20,34,"وجاء من مقابل جبعة عشرة آلاف رجل منتخبون من كل اسرائيل وكانت الحرب شديدة وهم لم يعلموا ان الشر قد مسّهم"));
arasuperobject.biblemap.put("b7_20_35", new arasuperobject(7,20,35,"فضرب الرب بنيامين امام اسرائيل واهلك بنو اسرائيل من بنيامين في ذلك اليوم خمسة وعشرين الف رجل ومئة رجل. كل هؤلاء مخترطو السيف"));
arasuperobject.biblemap.put("b7_20_36", new arasuperobject(7,20,36,"ورأى بنو بنيامين انهم قد انكسروا. واعطى رجال اسرائيل مكانا لبنيامين لانهم اتكلوا على الكمين الذي وضعوه على جبعة"));
arasuperobject.biblemap.put("b7_20_37", new arasuperobject(7,20,37,"فاسرع الكمين واقتحموا جبعة وزحف الكمين وضرب المدينة كلها بحد السيف"));
arasuperobject.biblemap.put("b7_20_38", new arasuperobject(7,20,38,"وكان الميعاد بين رجال اسرائيل وبين الكمين اصعادهم بكثرة علامة الدخان من المدينة"));
arasuperobject.biblemap.put("b7_20_39", new arasuperobject(7,20,39,"ولما انقلب رجال اسرائيل في الحرب ابتدأ بنيامين يضربون قتلى من رجال اسرائيل نحو ثلاثين رجلا لانهم قالوا انما هم منهزمون من امامنا كالحرب الاولى"));
arasuperobject.biblemap.put("b7_20_40", new arasuperobject(7,20,40,"ولما ابتدأت العلامة تصعد من المدينة عمود دخان التفت بنيامين الى ورائه واذا بالمدينة كلها تصعد نحو السماء"));
arasuperobject.biblemap.put("b7_20_41", new arasuperobject(7,20,41,"ورجع رجال اسرائيل وهرب رجال بنيامين برعدة لانهم رأوا ان الشر قد مسّهم"));
arasuperobject.biblemap.put("b7_20_42", new arasuperobject(7,20,42,"ورجعوا امام بني اسرائيل في طريق البرية ولكن القتال ادركهم والذين من المدن اهلكوهم في وسطهم"));
arasuperobject.biblemap.put("b7_20_43", new arasuperobject(7,20,43,"فحاوطوا بنيامين وطاردوهم بسهولة وادركوهم مقابل جبعة لجهة شروق الشمس"));
arasuperobject.biblemap.put("b7_20_44", new arasuperobject(7,20,44,"فسقط من بنيامين ثمانية عشر الف رجل جميع هؤلاء ذوو بأس"));
arasuperobject.biblemap.put("b7_20_45", new arasuperobject(7,20,45,"فداروا وهربوا الى البرية الى صخرة رمّون. فالتقطوا منهم في السكك خمسة آلاف رجل وشدوا وراءهم الى جدعوم وقتلوا منهم الفي رجل"));
arasuperobject.biblemap.put("b7_20_46", new arasuperobject(7,20,46,"وكان جميع الساقطين من بنيامين خمسة وعشرين الف رجل مخترطي السيف في ذلك اليوم. جميع هؤلاء ذوو بأس"));
arasuperobject.biblemap.put("b7_20_47", new arasuperobject(7,20,47,"ودار وهرب الى البرية الى صخرة رمون ست مئة رجل واقاموا في صخرة رمون اربعة اشهر"));
arasuperobject.biblemap.put("b7_20_48", new arasuperobject(7,20,48,"ورجع رجال بني اسرائيل الى بني بنيامين وضربوهم بحد السيف من المدينة باسرها حتى البهائم حتى كل ما وجد وايضا جميع المدن التي وجدت احرقوها بالنار"));
arasuperobject.biblemap.put("b7_21_1", new arasuperobject(7,21,1,"ورجال اسرائيل حلفوا في المصفاة قائلين لا يسلم احد منا ابنته لبنيامين امرأة"));
arasuperobject.biblemap.put("b7_21_2", new arasuperobject(7,21,2,"وجاء الشعب الى بيت ايل واقاموا هناك الى المساء امام الله ورفعوا صوتهم وبكوا بكاء عظيما"));
arasuperobject.biblemap.put("b7_21_3", new arasuperobject(7,21,3,"وقالوا لماذا يا رب اله اسرائيل حدثت هذه في اسرائيل حتى يفقد اليوم من اسرائيل سبط"));
arasuperobject.biblemap.put("b7_21_4", new arasuperobject(7,21,4,"وفي الغد بكر الشعب وبنوا هناك مذبحا واصعدوا محرقات وذبائح سلامة"));
arasuperobject.biblemap.put("b7_21_5", new arasuperobject(7,21,5,"وقال بنو اسرائيل من هو الذي لم يصعد في المجمع من جميع اسباط اسرائيل الى الرب. لانه صار الحلف العظيم على الذي لم يصعد الى الرب الى المصفاة قائلا يمات موتا"));
arasuperobject.biblemap.put("b7_21_6", new arasuperobject(7,21,6,"وندم بنو اسرائيل على بنيامين اخيهم وقالوا قد انقطع اليوم سبط واحد من اسرائيل"));
arasuperobject.biblemap.put("b7_21_7", new arasuperobject(7,21,7,"ماذا نعمل للباقين منهم في امر النساء وقد حلفنا نحن بالرب ان لا نعطيهم من بناتنا نساء"));
arasuperobject.biblemap.put("b7_21_8", new arasuperobject(7,21,8,"وقالوا اي سبط من اسباط اسرائيل لم يصعد الى الرب الى المصفاة. وهوذا لم يات الى المحلّة رجل من يابيش جلعاد الى المجمع"));
arasuperobject.biblemap.put("b7_21_9", new arasuperobject(7,21,9,"فعد الشعب فلم يكن هناك رجل من سكان يابيش جلعاد"));
arasuperobject.biblemap.put("b7_21_10", new arasuperobject(7,21,10,"فارسلت الجماعة الى هناك اثني عشر الف رجل من بني البأس واوصوهم قائلين اذهبوا واضربوا سكان يابيش جلعاد بحد السيف مع النساء والاطفال"));
arasuperobject.biblemap.put("b7_21_11", new arasuperobject(7,21,11,"وهذا ما تعملونه. تحرّمون كل ذكر وكل امرأة عرفت اضطجاع ذكر"));
arasuperobject.biblemap.put("b7_21_12", new arasuperobject(7,21,12,"فوجدوا من سكان يابيش جلعاد اربع مئة فتاة عذارى لم يعرفن رجلا بالاضطجاع مع ذكر وجاءوا بهنّ الى المحلّة الى شيلوه التي في ارض كنعان"));
arasuperobject.biblemap.put("b7_21_13", new arasuperobject(7,21,13,"وارسلت الجماعة كلها وكلمت بني بنيامين الذين في صخرة رمون واستدعتهم الى الصلح"));
arasuperobject.biblemap.put("b7_21_14", new arasuperobject(7,21,14,"فرجع بنيامين في ذلك الوقت فاعطوهم النساء اللواتي استحيوهنّ من نساء يابيش جلعاد ولم يكفوهم هكذا"));
arasuperobject.biblemap.put("b7_21_15", new arasuperobject(7,21,15,"وندم الشعب من اجل بنيامين لان الرب جعل شقّا في اسباط اسرائيل"));
arasuperobject.biblemap.put("b7_21_16", new arasuperobject(7,21,16,"فقال شيوخ الجماعة ماذا نصنع بالباقين في امر النساء لانه قد انقطعت النساء من بنيامين"));
arasuperobject.biblemap.put("b7_21_17", new arasuperobject(7,21,17,"وقالوا ميراث نجاة لبنيامين ولا يمحى سبط من اسرائيل"));
arasuperobject.biblemap.put("b7_21_18", new arasuperobject(7,21,18,"ونحن لا نقدر ان نعطيهم نساء من بناتنا لان بني اسرائيل حلفوا قائلين ملعون من اعطى امرأة لبنيامين"));
arasuperobject.biblemap.put("b7_21_19", new arasuperobject(7,21,19,"ثم قالوا هوذا عيد الرب في شيلوه من سنة الى سنة شمالي بيت ايل شرقي الطريق الصاعدة من بيت ايل الى شكيم وجنوبي لبونة"));
arasuperobject.biblemap.put("b7_21_20", new arasuperobject(7,21,20,"واوصوا بني بنيامين قائلين امضوا واكمنوا في الكروم"));
arasuperobject.biblemap.put("b7_21_21", new arasuperobject(7,21,21,"وانظروا فاذا خرجت بنات شيلوه ليدرن في الرقص فاخرجوا انتم من الكروم واخطفوا لانفسكم كل واحد امرأته من بنات شيلوه واذهبوا الى ارض بنيامين"));
arasuperobject.biblemap.put("b7_21_22", new arasuperobject(7,21,22,"فاذا جاء آباؤهنّ او اخوتهنّ لكي يشكوا الينا نقول لهم تراءفوا عليهم لاجلنا لاننا لم ناخذ لكل واحد امرأته في الحرب لانكم انتم لم تعطوهم في الوقت حتى تكونوا قد اثمتم"));
arasuperobject.biblemap.put("b7_21_23", new arasuperobject(7,21,23,"ففعل هكذا بنو بنيامين واتخذوا نساء حسب عددهم من الراقصات اللواتي اختطفوهنّ وذهبوا ورجعوا الى ملكهم وبنوا المدن وسكنوا بها"));
arasuperobject.biblemap.put("b7_21_24", new arasuperobject(7,21,24,"فسار من هناك بنو اسرائيل في ذلك الوقت كل واحد الى سبطه وعشيرته وخرجوا من هناك كل واحد الى ملكه"));
arasuperobject.biblemap.put("b7_21_25", new arasuperobject(7,21,25,"في تلك الايام لم يكن ملك في اسرائيل. كل واحد عمل ما حسن في عينيه"));

}

}