package ara.bible;

public class arabible47 {

public arabible47() {

putmapbible47();

}

private void putmapbible47() {

arasuperobject.biblemap.put("b47_1_1", new arasuperobject(47,1,1,"بولس رسول يسوع المسيح بمشيئة الله وتيموثاوس الاخ الى كنيسة الله التي في كورنثوس مع القديسين اجمعين الذين في جميع اخائية"));
arasuperobject.biblemap.put("b47_1_2", new arasuperobject(47,1,2,"نعمة لكم وسلام من الله ابينا والرب يسوع المسيح"));
arasuperobject.biblemap.put("b47_1_3", new arasuperobject(47,1,3,"مبارك الله ابو ربنا يسوع المسيح ابو الرأفة واله كل تعزية"));
arasuperobject.biblemap.put("b47_1_4", new arasuperobject(47,1,4,"الذي يعزينا في كل ضيقتنا حتى نستطيع ان نعزي الذين هم في كل ضيقة بالتعزية التي نتعزى نحن بها من الله"));
arasuperobject.biblemap.put("b47_1_5", new arasuperobject(47,1,5,"لانه كما تكثر آلام المسيح فينا كذلك بالمسيح تكثر تعزيتنا ايضا"));
arasuperobject.biblemap.put("b47_1_6", new arasuperobject(47,1,6,"فان كنا نتضايق فلاجل تعزيتكم وخلاصكم العامل في احتمال نفس الآلام التي نتألم بها نحن ايضا. او نتعزى فلاجل تعزيتكم وخلاصكم"));
arasuperobject.biblemap.put("b47_1_7", new arasuperobject(47,1,7,"فرجاؤنا من اجلكم ثابت. عالمين انكم كما انتم شركاء في الآلام كذلك في التعزية ايضا"));
arasuperobject.biblemap.put("b47_1_8", new arasuperobject(47,1,8,"فاننا لا نريد ان تجهلوا ايها الاخوة من جهة ضيقتنا التي اصابتنا في اسيا اننا تثقلنا جدا فوق الطاقة حتى أيسنا من الحياة ايضا"));
arasuperobject.biblemap.put("b47_1_9", new arasuperobject(47,1,9,"لكن كان لنا في انفسنا حكم الموت لكي لا نكون متكلين على انفسنا بل على الله الذي يقيم الاموات"));
arasuperobject.biblemap.put("b47_1_10", new arasuperobject(47,1,10,"الذي نجانا من موت مثل هذا وهو ينجي. الذي لنا رجاء فيه انه سينجي ايضا فيما بعد"));
arasuperobject.biblemap.put("b47_1_11", new arasuperobject(47,1,11,"وانتم ايضا مساعدون بالصلاة لاجلنا لكي يؤدى شكر لاجلنا من اشخاص كثيرين على ما وهب لنا بواسطة كثيرين"));
arasuperobject.biblemap.put("b47_1_12", new arasuperobject(47,1,12,"لان فخرنا هو هذا شهادة ضميرنا اننا في بساطة وإخلاص الله لا في حكمة جسدية بل في نعمة الله تصرفنا في العالم ولا سيما من نحوكم"));
arasuperobject.biblemap.put("b47_1_13", new arasuperobject(47,1,13,"فاننا لا نكتب اليكم بشيء آخر سوى ما تقرأون او تعرفون. وانا ارجو انكم ستعرفون الى النهاية ايضا"));
arasuperobject.biblemap.put("b47_1_14", new arasuperobject(47,1,14,"كما عرفتمونا ايضا بعض المعرفة اننا فخركم كما انكم ايضا فخرنا في يوم الرب يسوع"));
arasuperobject.biblemap.put("b47_1_15", new arasuperobject(47,1,15,"وبهذه الثقة كنت اشاء ان آتي اليكم اولا لتكون لكم نعمة ثانية"));
arasuperobject.biblemap.put("b47_1_16", new arasuperobject(47,1,16,"وان امر بكم الى مكدونية وآتي ايضا من مكدونية اليكم واشيع منكم الى اليهودية"));
arasuperobject.biblemap.put("b47_1_17", new arasuperobject(47,1,17,"فاذ انا عازم على هذا ألعلي استعملت الخفة ام اعزم على ما اعزم بحسب الجسد كي يكون عندي نعم نعم ولا لا"));
arasuperobject.biblemap.put("b47_1_18", new arasuperobject(47,1,18,"لكن امين هو الله ان كلامنا لكم لم يكن نعم ولا"));
arasuperobject.biblemap.put("b47_1_19", new arasuperobject(47,1,19,"لان ابن الله يسوع المسيح الذي كرز به بينكم بواسطتنا انا وسلوانس وتيموثاوس لم يكن نعم ولا بل قد كان فيه نعم"));
arasuperobject.biblemap.put("b47_1_20", new arasuperobject(47,1,20,"لان مهما كانت مواعيد الله فهو فيه النعم وفيه الآمين لمجد الله بواسطتنا"));
arasuperobject.biblemap.put("b47_1_21", new arasuperobject(47,1,21,"ولكن الذي يثبتنا معكم في المسيح وقد مسحنا هو الله"));
arasuperobject.biblemap.put("b47_1_22", new arasuperobject(47,1,22,"الذي ختمنا ايضا واعطى عربون الروح في قلوبنا"));
arasuperobject.biblemap.put("b47_1_23", new arasuperobject(47,1,23,"ولكني استشهد الله على نفسي اني اشفاقا عليكم لم آت الى كورنثوس"));
arasuperobject.biblemap.put("b47_1_24", new arasuperobject(47,1,24,"ليس اننا نسود على ايمانكم بل نحن موازرون لسروركم. لانكم بالايمان تثبتون"));
arasuperobject.biblemap.put("b47_2_1", new arasuperobject(47,2,1,"ولكني جزمت بهذا في نفسي ان لا آتي اليكم ايضا في حزن"));
arasuperobject.biblemap.put("b47_2_2", new arasuperobject(47,2,2,"لانه ان كنت احزنكم انا فمن هو الذي يفرحني الا الذي احزنته"));
arasuperobject.biblemap.put("b47_2_3", new arasuperobject(47,2,3,"وكتبت لكم هذا عينه حتى اذا جئت لا يكون لي حزن من الذين كان يجب ان افرح بهم واثقا بجميعكم ان فرحي هو فرح جميعكم"));
arasuperobject.biblemap.put("b47_2_4", new arasuperobject(47,2,4,"لاني من حزن كثير وكأبة قلب كتبت اليكم بدموع كثيرة لا لكي تحزنوا بل لكي تعرفوا المحبة التي عندي ولا سيّما من نحوكم"));
arasuperobject.biblemap.put("b47_2_5", new arasuperobject(47,2,5,"ولكن ان كان احد قد احزن فانه لم يحزني بل احزن جميعكم بعض الحزن لكي لا اثقل"));
arasuperobject.biblemap.put("b47_2_6", new arasuperobject(47,2,6,"مثل هذا يكفيه هذا القصاص الذي من الاكثرين"));
arasuperobject.biblemap.put("b47_2_7", new arasuperobject(47,2,7,"حتى تكونوا بالعكس تسامحونه بالحري وتعزونه لئلا يبتلع مثل هذا من الحزن المفرط"));
arasuperobject.biblemap.put("b47_2_8", new arasuperobject(47,2,8,"لذلك اطلب ان تمكنوا له المحبة"));
arasuperobject.biblemap.put("b47_2_9", new arasuperobject(47,2,9,"لاني لهذا كتبت لكي اعرف تزكيتكم هل انتم طائعون في كل شيء"));
arasuperobject.biblemap.put("b47_2_10", new arasuperobject(47,2,10,"والذي تسامحونه بشيء فانا ايضا. لاني انا ما سامحت به ان كنت قد سامحت بشيء فمن اجلكم بحضرة المسيح"));
arasuperobject.biblemap.put("b47_2_11", new arasuperobject(47,2,11,"لئلا يطمع فينا الشيطان لاننا لا نجهل افكاره"));
arasuperobject.biblemap.put("b47_2_12", new arasuperobject(47,2,12,"ولكن لما جئت الى ترواس لاجل انجيل المسيح وانفتح لي باب في الرب"));
arasuperobject.biblemap.put("b47_2_13", new arasuperobject(47,2,13,"لم تكن لي راحة في روحي لاني لم اجد تيطس اخي. لكن ودعتهم فخرجت الى مكدونية"));
arasuperobject.biblemap.put("b47_2_14", new arasuperobject(47,2,14,"ولكن شكرا للّه الذي يقودنا في موكب نصرته في المسيح كل حين ويظهر بنا رائحة معرفته في كل مكان"));
arasuperobject.biblemap.put("b47_2_15", new arasuperobject(47,2,15,"لاننا رائحة المسيح الذكية للّه في الذين يخلصون وفي الذين يهلكون"));
arasuperobject.biblemap.put("b47_2_16", new arasuperobject(47,2,16,"لهؤلاء رائحة موت لموت ولاولئك رائحة حياة لحياة. ومن هو كفؤ لهذه الامور"));
arasuperobject.biblemap.put("b47_2_17", new arasuperobject(47,2,17,"لاننا لسنا كالكثيرين غاشين كلمة الله لكن كما من اخلاص بل كما من الله نتكلم امام الله في المسيح"));
arasuperobject.biblemap.put("b47_3_1", new arasuperobject(47,3,1,"أفنبتدئ نمدح انفسنا ام لعلنا نحتاج كقوم رسائل توصية اليكم او رسائل توصية منكم"));
arasuperobject.biblemap.put("b47_3_2", new arasuperobject(47,3,2,"انتم رسالتنا مكتوبة في قلوبنا معروفة ومقروءة من جميع الناس"));
arasuperobject.biblemap.put("b47_3_3", new arasuperobject(47,3,3,"ظاهرين انكم رسالة المسيح مخدومة منا مكتوبة لا بحبر بل بروح الله الحي . لا في الواح حجرية بل في الواح قلب لحمية"));
arasuperobject.biblemap.put("b47_3_4", new arasuperobject(47,3,4,"ولكن لنا ثقة مثل هذه بالمسيح لدى الله"));
arasuperobject.biblemap.put("b47_3_5", new arasuperobject(47,3,5,"ليس اننا كفاة من انفسنا ان نفتكر شيئا كانه من انفسنا بل كفايتنا من الله"));
arasuperobject.biblemap.put("b47_3_6", new arasuperobject(47,3,6,"الذي جعلنا كفاة لان نكون خدام عهد جديد. لا الحرف بل الروح. لان الحرف يقتل ولكن الروح يحيي"));
arasuperobject.biblemap.put("b47_3_7", new arasuperobject(47,3,7,"ثم ان كانت خدمة الموت المنقوشة باحرف في حجارة قد حصلت في مجد حتى لم يقدر بنو اسرائيل ان ينظروا الى وجه موسى لسبب مجد وجهه الزائل"));
arasuperobject.biblemap.put("b47_3_8", new arasuperobject(47,3,8,"فكيف لا تكون بالأولى خدمة الروح في مجد"));
arasuperobject.biblemap.put("b47_3_9", new arasuperobject(47,3,9,"لانه ان كانت خدمة الدينونة مجدا فبالأولى كثيرا تزيد خدمة البر في مجد"));
arasuperobject.biblemap.put("b47_3_10", new arasuperobject(47,3,10,"فان الممجد ايضا لم يمجد من هذا القبيل لسبب المجد الفائق"));
arasuperobject.biblemap.put("b47_3_11", new arasuperobject(47,3,11,"لانه ان كان الزائل في مجد فبالأولى كثيرا يكون الدائم في مجد"));
arasuperobject.biblemap.put("b47_3_12", new arasuperobject(47,3,12,"فاذ لنا رجاء مثل هذا نستعمل مجاهرة كثيرة"));
arasuperobject.biblemap.put("b47_3_13", new arasuperobject(47,3,13,"وليس كما كان موسى يضع برقعا على وجهه لكي لا ينظر بنو اسرائيل الى نهاية الزائل"));
arasuperobject.biblemap.put("b47_3_14", new arasuperobject(47,3,14,"بل أغلظت اذهانهم لانه حتى اليوم ذلك البرقع نفسه عند قراءة العهد العتيق باق غير منكشف الذي يبطل في المسيح"));
arasuperobject.biblemap.put("b47_3_15", new arasuperobject(47,3,15,"لكن حتى اليوم حين يقرأ موسى البرقع موضوع على قلبهم"));
arasuperobject.biblemap.put("b47_3_16", new arasuperobject(47,3,16,"ولكن عندما يرجع الى الرب يرفع البرقع"));
arasuperobject.biblemap.put("b47_3_17", new arasuperobject(47,3,17,"واما الرب فهو الروح وحيث روح الرب هناك حرية"));
arasuperobject.biblemap.put("b47_3_18", new arasuperobject(47,3,18,"ونحن جميعا ناظرين مجد الرب بوجه مكشوف كما في مرآة نتغيّر الى تلك الصورة عينها من مجد الى مجد كما من الرب الروح"));
arasuperobject.biblemap.put("b47_4_1", new arasuperobject(47,4,1,"من اجل ذلك اذ لنا هذه الخدمة كما رحمنا لا نفشل"));
arasuperobject.biblemap.put("b47_4_2", new arasuperobject(47,4,2,"بل قد رفضنا خفايا الخزي غير سالكين في مكر ولا غاشين كلمة الله بل باظهار الحق مادحين انفسنا لدى ضمير كل انسان قدام الله"));
arasuperobject.biblemap.put("b47_4_3", new arasuperobject(47,4,3,"ولكن ان كان انجيلنا مكتوما فانما هو مكتوم في الهالكين"));
arasuperobject.biblemap.put("b47_4_4", new arasuperobject(47,4,4,"الذين فيهم اله هذا الدهر قد اعمى اذهان غير المؤمنين لئلا تضيء لهم انارة انجيل مجد المسيح الذي هو صورة الله"));
arasuperobject.biblemap.put("b47_4_5", new arasuperobject(47,4,5,"فاننا لسنا نكرز بانفسنا بل بالمسيح يسوع ربا ولكن بانفسنا عبيدا لكم من اجل يسوع"));
arasuperobject.biblemap.put("b47_4_6", new arasuperobject(47,4,6,"لان الله الذي قال ان يشرق نور من ظلمة هو الذي اشرق في قلوبنا لانارة معرفة مجد الله في وجه يسوع المسيح"));
arasuperobject.biblemap.put("b47_4_7", new arasuperobject(47,4,7,"ولكن لنا هذا الكنز في اوان خزفية ليكون فضل القوة للّه لا منا"));
arasuperobject.biblemap.put("b47_4_8", new arasuperobject(47,4,8,"مكتئبين في كل شيء لكن غير متضايقين. متحيّرين لكن غير يائسين"));
arasuperobject.biblemap.put("b47_4_9", new arasuperobject(47,4,9,"مضطهدين لكن غير متروكين. مطروحين لكن غير هالكين"));
arasuperobject.biblemap.put("b47_4_10", new arasuperobject(47,4,10,"حاملين في الجسد كل حين اماتة الرب يسوع لكي تظهر حياة يسوع ايضا في جسدنا"));
arasuperobject.biblemap.put("b47_4_11", new arasuperobject(47,4,11,"لاننا نحن الاحياء نسلم دائما للموت من اجل يسوع لكي تظهر حياة يسوع ايضا في جسدنا المائت"));
arasuperobject.biblemap.put("b47_4_12", new arasuperobject(47,4,12,"اذا الموت يعمل فينا ولكن الحياة فيكم"));
arasuperobject.biblemap.put("b47_4_13", new arasuperobject(47,4,13,"فاذ لنا روح الايمان عينه حسب المكتوب آمنت لذلك تكلمت. نحن ايضا نؤمن ولذلك نتكلم ايضا"));
arasuperobject.biblemap.put("b47_4_14", new arasuperobject(47,4,14,"عالمين ان الذي اقام الرب يسوع سيقيمنا نحن ايضا بيسوع ويحضرنا معكم"));
arasuperobject.biblemap.put("b47_4_15", new arasuperobject(47,4,15,"لان جميع الاشياء هي من اجلكم لكي تكون النعمة وهي قد كثرت بالاكثرين تزيد الشكر لمجد الله"));
arasuperobject.biblemap.put("b47_4_16", new arasuperobject(47,4,16,"لذلك لا نفشل بل وان كان انساننا الخارج يفنى فالداخل يتجدد يوما فيوما"));
arasuperobject.biblemap.put("b47_4_17", new arasuperobject(47,4,17,"لان خفة ضيقتنا الوقتية تنشئ لنا اكثر فاكثر ثقل مجد ابديا"));
arasuperobject.biblemap.put("b47_4_18", new arasuperobject(47,4,18,"ونحن غير ناظرين الى الاشياء التي ترى بل الى التي لا ترى. لان التي ترى وقتية واما التي لا ترى فابدية"));
arasuperobject.biblemap.put("b47_5_1", new arasuperobject(47,5,1,"لاننا نعلم انه ان نقض بيت خيمتنا الارضي فلنا في السموات بناء من الله بيت غير مصنوع بيد ابدي"));
arasuperobject.biblemap.put("b47_5_2", new arasuperobject(47,5,2,"فاننا في هذه ايضا نئن مشتاقين الى ان نلبس فوقها مسكننا الذي من السماء"));
arasuperobject.biblemap.put("b47_5_3", new arasuperobject(47,5,3,"وان كنا لابسين لا نوجد عراة"));
arasuperobject.biblemap.put("b47_5_4", new arasuperobject(47,5,4,"فاننا نحن الذين في الخيمة نئن مثقلين اذ لسنا نريد ان نخلعها بل ان نلبس فوقها لكي يبتلع المائت من الحياة"));
arasuperobject.biblemap.put("b47_5_5", new arasuperobject(47,5,5,"ولكن الذي صنعنا لهذا عينه هو الله الذي اعطانا ايضا عربون الروح"));
arasuperobject.biblemap.put("b47_5_6", new arasuperobject(47,5,6,"فاذا نحن واثقون كل حين وعالمون اننا ونحن مستوطنون في الجسد فنحن متغربون عن الرب"));
arasuperobject.biblemap.put("b47_5_7", new arasuperobject(47,5,7,"لاننا بالايمان نسلك لا بالعيان"));
arasuperobject.biblemap.put("b47_5_8", new arasuperobject(47,5,8,"فنثق ونسرّ بالأولى ان نتغرب عن الجسد ونستوطن عند الرب"));
arasuperobject.biblemap.put("b47_5_9", new arasuperobject(47,5,9,"لذلك نحترس ايضا مستوطنين كنا او متغربين ان نكون مرضيين عنده"));
arasuperobject.biblemap.put("b47_5_10", new arasuperobject(47,5,10,"لانه لا بد اننا جميعا نظهر امام كرسي المسيح لينال كل واحد ما كان بالجسد بحسب ما صنع خيرا كان ام شرا"));
arasuperobject.biblemap.put("b47_5_11", new arasuperobject(47,5,11,"فاذ نحن عالمون مخافة الرب نقنع الناس. واما الله فقد صرنا ظاهرين له وارجو اننا قد صرنا ظاهرين في ضمائركم ايضا"));
arasuperobject.biblemap.put("b47_5_12", new arasuperobject(47,5,12,"لاننا لسنا نمدح انفسنا ايضا لديكم بل نعطيكم فرصة للافتخار من جهتنا ليكون لكم جواب على الذين يفتخرون بالوجه لا بالقلب"));
arasuperobject.biblemap.put("b47_5_13", new arasuperobject(47,5,13,"لاننا ان صرنا مختلين فللّه. او كنا عاقلين فلكم"));
arasuperobject.biblemap.put("b47_5_14", new arasuperobject(47,5,14,"لان محبة المسيح تحصرنا. اذ نحن نحسب هذا انه ان كان واحد قد مات لاجل الجميع فالجميع اذا ماتوا"));
arasuperobject.biblemap.put("b47_5_15", new arasuperobject(47,5,15,"وهو مات لاجل الجميع كي يعيش الاحياء فيما بعد لا لانفسهم بل للذي مات لاجلهم وقام"));
arasuperobject.biblemap.put("b47_5_16", new arasuperobject(47,5,16,"اذا نحن من الآن لا نعرف احدا حسب الجسد. وان كنا قد عرفنا المسيح حسب الجسد لكن الآن لا نعرفه بعد"));
arasuperobject.biblemap.put("b47_5_17", new arasuperobject(47,5,17,"اذا ان كان احد في المسيح فهو خليقة جديدة. الاشياء العتيقة قد مضت. هوذا الكل قد صار جديدا"));
arasuperobject.biblemap.put("b47_5_18", new arasuperobject(47,5,18,"ولكن الكل من الله الذي صالحنا لنفسه بيسوع المسيح واعطانا خدمة المصالحة"));
arasuperobject.biblemap.put("b47_5_19", new arasuperobject(47,5,19,"اي ان الله كان في المسيح مصالحا العالم لنفسه غير حاسب لهم خطاياهم وواضعا فينا كلمة المصالحة"));
arasuperobject.biblemap.put("b47_5_20", new arasuperobject(47,5,20,"اذا نسعى كسفراء عن المسيح كأن الله يعظ بنا. نطلب عن المسيح تصالحوا مع الله"));
arasuperobject.biblemap.put("b47_5_21", new arasuperobject(47,5,21,"لانه جعل الذي لم يعرف خطية خطية لاجلنا لنصير نحن بر الله فيه"));
arasuperobject.biblemap.put("b47_6_1", new arasuperobject(47,6,1,"فاذ نحن عاملون معه نطلب ان لا تقبلوا نعمة الله باطلا"));
arasuperobject.biblemap.put("b47_6_2", new arasuperobject(47,6,2,"لانه يقول. في وقت مقبول سمعتك وفي يوم خلاص اعنتك. هوذا الآن وقت مقبول. هوذا الآن يوم خلاص"));
arasuperobject.biblemap.put("b47_6_3", new arasuperobject(47,6,3,"ولسنا نجعل عثرة في شيء لئلا تلام الخدمة"));
arasuperobject.biblemap.put("b47_6_4", new arasuperobject(47,6,4,"بل في كل شيء نظهر انفسنا كخدام الله في صبر كثير في شدائد في ضرورات في ضيقات"));
arasuperobject.biblemap.put("b47_6_5", new arasuperobject(47,6,5,"في ضربات في سجون في اضطرابات في اتعاب في اسهار في اصوام"));
arasuperobject.biblemap.put("b47_6_6", new arasuperobject(47,6,6,"في طهارة في علم في اناة في لطف في الروح القدس في محبة بلا رياء"));
arasuperobject.biblemap.put("b47_6_7", new arasuperobject(47,6,7,"في كلام الحق في قوة الله بسلاح البر لليمين ولليسار"));
arasuperobject.biblemap.put("b47_6_8", new arasuperobject(47,6,8,"بمجد وهوان بصيت رديء وصيت حسن. كمضلين ونحن صادقون"));
arasuperobject.biblemap.put("b47_6_9", new arasuperobject(47,6,9,"كمجهولين ونحن معروفون. كمائتين وها نحن نحيا. كمؤدبين ونحن غير مقتولين"));
arasuperobject.biblemap.put("b47_6_10", new arasuperobject(47,6,10,"كحزانى ونحن دائما فرحون. كفقراء ونحن نغني كثيرين. كأن لا شيء لنا ونحن نملك كل شيء"));
arasuperobject.biblemap.put("b47_6_11", new arasuperobject(47,6,11,"فمنا مفتوح اليكم ايها الكورنثيون. قلبنا متسع"));
arasuperobject.biblemap.put("b47_6_12", new arasuperobject(47,6,12,"لستم متضيقين فينا بل متضيقين في احشائكم"));
arasuperobject.biblemap.put("b47_6_13", new arasuperobject(47,6,13,"فجزاء لذلك اقول كما لاولادي كونوا انتم ايضا متسعين"));
arasuperobject.biblemap.put("b47_6_14", new arasuperobject(47,6,14,"لا تكونوا تحت نير مع غير المؤمنين. لانه اية خلطة للبر والاثم. واية شركة للنور مع الظلمة"));
arasuperobject.biblemap.put("b47_6_15", new arasuperobject(47,6,15,"واي اتفاق للمسيح مع بليعال. واي نصيب للمؤمن مع غير المؤمن"));
arasuperobject.biblemap.put("b47_6_16", new arasuperobject(47,6,16,"واية موافقة لهيكل الله مع الاوثان. فانكم انتم هيكل الله الحي كما قال الله اني سأسكن فيهم واسير بينهم واكون لهم الها وهم يكونون لي شعبا"));
arasuperobject.biblemap.put("b47_6_17", new arasuperobject(47,6,17,"لذلك اخرجوا من وسطهم واعتزلوا يقول الرب ولا تمسوا نجسا فاقبلكم"));
arasuperobject.biblemap.put("b47_6_18", new arasuperobject(47,6,18,"واكون لكم ابا وانتم تكونون لي بنين وبنات يقول الرب القادر على كل شيء"));
arasuperobject.biblemap.put("b47_7_1", new arasuperobject(47,7,1,"فاذ لنا هذه المواعيد ايها الاحباء لنطهر ذواتنا من كل دنس الجسد والروح مكملين القداسة في خوف الله"));
arasuperobject.biblemap.put("b47_7_2", new arasuperobject(47,7,2,"اقبلونا. لم نظلم احدا. لم نفسد احدا. لم نطمع في احد"));
arasuperobject.biblemap.put("b47_7_3", new arasuperobject(47,7,3,"لا اقول هذا لاجل دينونة. لاني قد قلت سابقا انكم في قلوبنا لنموت معكم ونعيش معكم"));
arasuperobject.biblemap.put("b47_7_4", new arasuperobject(47,7,4,"لي ثقة كثيرة بكم. لي افتخار كثير من جهتكم. قد امتلأت تعزية وازددت فرحا جدا في جميع ضيقاتنا"));
arasuperobject.biblemap.put("b47_7_5", new arasuperobject(47,7,5,"لاننا لما أتينا الى مكدونية لم يكن لجسدنا شيء من الراحة بل كنا مكتئبين في كل شيء. من خارج خصومات. من داخل مخاوف"));
arasuperobject.biblemap.put("b47_7_6", new arasuperobject(47,7,6,"لكن الله الذي يعزي المتضعين عزانا بمجيء تيطس"));
arasuperobject.biblemap.put("b47_7_7", new arasuperobject(47,7,7,"وليس بمجيئه فقط بل ايضا بالتعزية التي تعزى بها بسببكم وهو يخبرنا بشوقكم ونوحكم وغيرتكم لاجلي حتى اني فرحت اكثر"));
arasuperobject.biblemap.put("b47_7_8", new arasuperobject(47,7,8,"لاني وان كنت قد احزنتكم بالرسالة لست اندم مع اني ندمت. فاني ارى ان تلك الرسالة احزنتكم ولو الى ساعة"));
arasuperobject.biblemap.put("b47_7_9", new arasuperobject(47,7,9,"الآن انا افرح لا لانكم حزنتم بل لانكم حزنتم للتوبة. لانكم حزنتم بحسب مشيئة الله لكي لا تتخسروا منا في شيء"));
arasuperobject.biblemap.put("b47_7_10", new arasuperobject(47,7,10,"لان الحزن الذي بحسب مشيئة الله ينشئ توبة لخلاص بلا ندامة. واما حزن العالم فينشئ موتا"));
arasuperobject.biblemap.put("b47_7_11", new arasuperobject(47,7,11,"فانه هوذا حزنكم هذا عينه بحسب مشيئة الله كم انشأ فيكم من الاجتهاد بل من الاحتجاج بل من الغيظ بل من الخوف بل من الشوق بل من الغيرة بل من الانتقام. في كل شيء اظهرتم انفسكم انكم ابرياء في هذا الامر"));
arasuperobject.biblemap.put("b47_7_12", new arasuperobject(47,7,12,"اذا وان كنت قد كتبت اليكم فليس لاجل المذنب ولا لاجل المذنب اليه بل لكي يظهر لكم امام الله اجتهادنا لاجلكم"));
arasuperobject.biblemap.put("b47_7_13", new arasuperobject(47,7,13,"من اجل هذا قد تعزينا بتعزيتكم. ولكن فرحنا اكثر جدا بسبب فرح تيطس لان روحه قد استراحت بكم جميعا"));
arasuperobject.biblemap.put("b47_7_14", new arasuperobject(47,7,14,"فاني ان كنت افتخرت شيئا لديه من جهتكم لم أخجل بل كما كلمناكم بكل شيء بالصدق كذلك افتخارنا ايضا لدى تيطس صار صادقا"));
arasuperobject.biblemap.put("b47_7_15", new arasuperobject(47,7,15,"واحشاؤه هي نحوكم بالزيادة متذكرا طاعة جميعكم كيف قبلتموه بخوف ورعدة"));
arasuperobject.biblemap.put("b47_7_16", new arasuperobject(47,7,16,"انا افرح اذا اني اثق بكم في كل شيء"));
arasuperobject.biblemap.put("b47_8_1", new arasuperobject(47,8,1,"ثم نعرفكم ايها الاخوة نعمة الله المعطاة في كنائس مكدونية"));
arasuperobject.biblemap.put("b47_8_2", new arasuperobject(47,8,2,"انه في اختبار ضيقة شديدة فاض وفور فرحهم وفقرهم العميق لغنى سخائهم"));
arasuperobject.biblemap.put("b47_8_3", new arasuperobject(47,8,3,"لانهم اعطوا حسب الطاقة انا اشهد وفوق الطاقة من تلقاء انفسهم"));
arasuperobject.biblemap.put("b47_8_4", new arasuperobject(47,8,4,"ملتمسين منا بطلبة كثيرة ان نقبل النعمة وشركة الخدمة التي للقديسين"));
arasuperobject.biblemap.put("b47_8_5", new arasuperobject(47,8,5,"وليس كما رجونا بل اعطوا انفسهم اولا للرب ولنا بمشيئة الله"));
arasuperobject.biblemap.put("b47_8_6", new arasuperobject(47,8,6,"حتى اننا طلبنا من تيطس انه كما سبق فابتدأ كذلك يتمم لكم هذه النعمة ايضا"));
arasuperobject.biblemap.put("b47_8_7", new arasuperobject(47,8,7,"لكن كما تزدادون في كل شيء في الايمان والكلام والعلم وكل اجتهاد ومحبتكم لنا ليتكم تزدادون في هذه النعمة ايضا"));
arasuperobject.biblemap.put("b47_8_8", new arasuperobject(47,8,8,"لست اقول على سبيل الامر بل باجتهاد آخرين مختبرا اخلاص محبتكم ايضا"));
arasuperobject.biblemap.put("b47_8_9", new arasuperobject(47,8,9,"فانكم تعرفون نعمة ربنا يسوع المسيح انه من اجلكم افتقر وهو غني لكي تستغنوا انتم بفقره"));
arasuperobject.biblemap.put("b47_8_10", new arasuperobject(47,8,10,"اعطي رأيا في هذا ايضا. لان هذا ينفعكم انتم الذين سبقتم فابتدأتم منذ العام الماضي ليس ان تفعلوا فقط بل ان تريدوا ايضا"));
arasuperobject.biblemap.put("b47_8_11", new arasuperobject(47,8,11,"ولكن الآن تمموا العمل ايضا حتى انه كما ان النشاط للارادة كذلك يكون التتميم ايضا حسب مالكم"));
arasuperobject.biblemap.put("b47_8_12", new arasuperobject(47,8,12,"لانه ان كان النشاط موجودا فهو مقبول على حسب ما للانسان لا على حسب ما ليس له"));
arasuperobject.biblemap.put("b47_8_13", new arasuperobject(47,8,13,"فانه ليس لكي يكون للآخرين راحة ولكم ضيق"));
arasuperobject.biblemap.put("b47_8_14", new arasuperobject(47,8,14,"بل بحسب المساواة. لكي تكون في هذا الوقت فضالتكم لاعوازهم كي تصير فضالتهم لاعوازكم حتى تحصل المساواة"));
arasuperobject.biblemap.put("b47_8_15", new arasuperobject(47,8,15,"كما هو مكتوب الذي جمع كثيرا لم يفضل والذي جمع قليلا لم ينقص"));
arasuperobject.biblemap.put("b47_8_16", new arasuperobject(47,8,16,"ولكن شكرا للّه الذي جعل هذا الاجتهاد عينه لاجلكم في قلب تيطس"));
arasuperobject.biblemap.put("b47_8_17", new arasuperobject(47,8,17,"لانه قبل الطلبة واذ كان اكثر اجتهادا مضى اليكم من تلقاء نفسه"));
arasuperobject.biblemap.put("b47_8_18", new arasuperobject(47,8,18,"وارسلنا معه الاخ الذي مدحه في الانجيل في جميع الكنائس"));
arasuperobject.biblemap.put("b47_8_19", new arasuperobject(47,8,19,"وليس ذلك فقط بل هو منتخب ايضا من الكنائس رفيقا لنا في السفر مع هذه النعمة المخدومة منا لمجد ذات الرب الواحد ولنشاطكم"));
arasuperobject.biblemap.put("b47_8_20", new arasuperobject(47,8,20,"متجنبين هذا ان يلومنا احد في جسامة هذه المخدومة منا"));
arasuperobject.biblemap.put("b47_8_21", new arasuperobject(47,8,21,"معتنين بامور حسنة ليس قدام الرب فقط بل قدام الناس ايضا"));
arasuperobject.biblemap.put("b47_8_22", new arasuperobject(47,8,22,"وارسلنا معهما اخانا الذي اختبرنا مرارا في امور كثيرة انه مجتهد ولكنه الآن اشد اجتهادا كثيرا بالثقة الكثيرة بكم"));
arasuperobject.biblemap.put("b47_8_23", new arasuperobject(47,8,23,"اما من جهة تيطس فهو شريك لي وعامل معي لاجلكم. واما اخوانا فهما رسولا الكنائس ومجد المسيح"));
arasuperobject.biblemap.put("b47_8_24", new arasuperobject(47,8,24,"فبينوا لهم وقدام الكنائس بينة محبتكم وافتخارنا من جهتكم"));
arasuperobject.biblemap.put("b47_9_1", new arasuperobject(47,9,1,"فانه من جهة الخدمة للقديسين هو فضول مني ان اكتب اليكم"));
arasuperobject.biblemap.put("b47_9_2", new arasuperobject(47,9,2,"لاني اعلم نشاطكم الذي افتخر به من جهتكم لدى المكدونيين ان اخائية مستعدة منذ العام الماضي. وغيرتكم قد حرّضت الاكثرين"));
arasuperobject.biblemap.put("b47_9_3", new arasuperobject(47,9,3,"ولكن ارسلت الاخوة لئلا يتعطل افتخارنا من جهتكم من هذا القبيل كي تكونوا مستعدين كما قلت"));
arasuperobject.biblemap.put("b47_9_4", new arasuperobject(47,9,4,"حتى اذا جاء معي مكدونيون ووجدوكم غير مستعدين لا نخجل نحن حتى لا اقول انتم في جسارة الافتخار هذه"));
arasuperobject.biblemap.put("b47_9_5", new arasuperobject(47,9,5,"فرأيت لازما ان اطلب الى الاخوة ان يسبقوا اليكم ويهيئوا قبلا بركتكم التي سبق التخبير بها لتكون هي معدة هكذا كانها بركة لا كانها بخل"));
arasuperobject.biblemap.put("b47_9_6", new arasuperobject(47,9,6,"هذا وان من يزرع بالشح فبالشح ايضا يحصد. ومن يزرع بالبركات فبالبركات ايضا يحصد"));
arasuperobject.biblemap.put("b47_9_7", new arasuperobject(47,9,7,"كل واحد كما ينوي بقلبه ليس عن حزن او اضطرار. لان المعطي المسرور يحبه الله"));
arasuperobject.biblemap.put("b47_9_8", new arasuperobject(47,9,8,"والله قادر ان يزيدكم كل نعمة لكي تكونوا ولكم كل اكتفاء كل حين في كل شيء تزدادون في كل عمل صالح"));
arasuperobject.biblemap.put("b47_9_9", new arasuperobject(47,9,9,"كما هو مكتوب فرق. اعطى المساكين. بره يبقى الى الابد"));
arasuperobject.biblemap.put("b47_9_10", new arasuperobject(47,9,10,"والذي يقدم بذارا للزارع وخبزا للأكل سيقدم ويكثر بذاركم وينمي غلات بركم"));
arasuperobject.biblemap.put("b47_9_11", new arasuperobject(47,9,11,"مستغنين في كل شيء لكل سخاء ينشئ بنا شكرا للّه"));
arasuperobject.biblemap.put("b47_9_12", new arasuperobject(47,9,12,"لان افتعال هذه الخدمة ليس يسد اعواز القديسين فقط بل يزيد بشكر كثير للّه"));
arasuperobject.biblemap.put("b47_9_13", new arasuperobject(47,9,13,"اذ هم باختبار هذه الخدمة يمجدون الله على طاعة اعترافكم لانجيل المسيح وسخاء التوزيع لهم وللجميع"));
arasuperobject.biblemap.put("b47_9_14", new arasuperobject(47,9,14,"وبدعائهم لاجلكم مشتاقين اليكم من اجل نعمة الله الفائقة لديكم"));
arasuperobject.biblemap.put("b47_9_15", new arasuperobject(47,9,15,"فشكرا للّه على عطيته التي لا يعبّر عنها"));
arasuperobject.biblemap.put("b47_10_1", new arasuperobject(47,10,1,"ثم اطلب اليكم بوداعة المسيح وحلمه انا نفسي بولس الذي في الحضرة ذليل بينكم واما في الغيبة فمتجاسر عليكم"));
arasuperobject.biblemap.put("b47_10_2", new arasuperobject(47,10,2,"ولكن اطلب ان لا اتجاسر وانا حاضر بالثقة التي بها ارى اني ساجترئ على قوم يحسبوننا كاننا نسلك حسب الجسد"));
arasuperobject.biblemap.put("b47_10_3", new arasuperobject(47,10,3,"لاننا وان كنا نسلك في الجسد لسنا حسب الجسد نحارب"));
arasuperobject.biblemap.put("b47_10_4", new arasuperobject(47,10,4,"اذ اسلحة محاربتنا ليست جسدية بل قادرة بالله على هدم حصون"));
arasuperobject.biblemap.put("b47_10_5", new arasuperobject(47,10,5,"هادمين ظنونا وكل علو يرتفع ضد معرفة الله ومستأسرين كل فكر الى طاعة المسيح"));
arasuperobject.biblemap.put("b47_10_6", new arasuperobject(47,10,6,"ومستعدين لان ننتقم على كل عصيان متى كملت طاعتكم"));
arasuperobject.biblemap.put("b47_10_7", new arasuperobject(47,10,7,"اتنظرون الى ما هو حسب الحضرة. ان وثق احد بنفسه انه للمسيح فليحسب هذا ايضا من نفسه انه كما هو للمسيح كذلك نحن ايضا للمسيح"));
arasuperobject.biblemap.put("b47_10_8", new arasuperobject(47,10,8,"فاني وان افتخرت شيئا اكثر بسلطاننا الذي اعطانا اياه الرب لبنيانكم لا لهدمكم لا أخجل"));
arasuperobject.biblemap.put("b47_10_9", new arasuperobject(47,10,9,"لئلا اظهر كاني اخيفكم بالرسائل"));
arasuperobject.biblemap.put("b47_10_10", new arasuperobject(47,10,10,"لانه يقول الرسائل ثقيلة وقوية واما حضور الجسد فضعيف والكلام حقير"));
arasuperobject.biblemap.put("b47_10_11", new arasuperobject(47,10,11,"مثل هذا فليحسب هذا اننا كما نحن في الكلام بالرسائل ونحن غائبون هكذا نكون ايضا بالفعل ونحن حاضرون"));
arasuperobject.biblemap.put("b47_10_12", new arasuperobject(47,10,12,"لاننا لا نجترئ ان نعد انفسنا بين قوم من الذين يمدحون انفسهم ولا ان نقابل انفسنا بهم. بل هم اذ يقيسون انفسهم على انفسهم ويقابلون انفسهم بانفسهم لا يفهمون"));
arasuperobject.biblemap.put("b47_10_13", new arasuperobject(47,10,13,"ولكن نحن لا نفتخر الى ما لا يقاس بل حسب قياس القانون الذي قسمه لنا الله قياسا للبلوغ اليكم ايضا"));
arasuperobject.biblemap.put("b47_10_14", new arasuperobject(47,10,14,"لاننا لا نمدد انفسنا كاننا لسنا نبلغ اليكم. اذ قد وصلنا اليكم ايضا في انجيل المسيح"));
arasuperobject.biblemap.put("b47_10_15", new arasuperobject(47,10,15,"غير مفتخرين الى ما لا يقاس في اتعاب آخرين بل راجين اذا نما ايمانكم ان نتعظم بينكم حسب قانوننا بزيادة"));
arasuperobject.biblemap.put("b47_10_16", new arasuperobject(47,10,16,"لنبشر الى ما وراءكم. لا لنفتخر بالامور المعدة في قانون غيرنا"));
arasuperobject.biblemap.put("b47_10_17", new arasuperobject(47,10,17,"واما من افتخر فليفتخر بالرب"));
arasuperobject.biblemap.put("b47_10_18", new arasuperobject(47,10,18,"لانه ليس من مدح نفسه هو المزكى بل من يمدحه الرب"));
arasuperobject.biblemap.put("b47_11_1", new arasuperobject(47,11,1,"ليتكم تحتملون غباوتي قليلا. بل انتم محتملي"));
arasuperobject.biblemap.put("b47_11_2", new arasuperobject(47,11,2,"فاني اغار عليكم غيرة الله لاني خطبتكم لرجل واحد لأقدم عذراء عفيفة للمسيح"));
arasuperobject.biblemap.put("b47_11_3", new arasuperobject(47,11,3,"ولكنني اخاف انه كما خدعت الحية حواء بمكرها هكذا تفسد اذهانكم عن البساطة التي في المسيح"));
arasuperobject.biblemap.put("b47_11_4", new arasuperobject(47,11,4,"فانه ان كان الآتي يكرز بيسوع آخر لم نكرز به او كنتم تأخذون روحا آخر لم تأخذوه او انجيلا آخر لم تقبلوه فحسنا كنتم تحتملون"));
arasuperobject.biblemap.put("b47_11_5", new arasuperobject(47,11,5,"لاني احسب اني لم انقص شيئا عن فائقي الرسل"));
arasuperobject.biblemap.put("b47_11_6", new arasuperobject(47,11,6,"وان كنت عاميا في الكلام فلست في العلم بل نحن في كل شيء ظاهرون لكم بين الجميع"));
arasuperobject.biblemap.put("b47_11_7", new arasuperobject(47,11,7,"ام اخطأت خطية اذ اذللت نفسي كي ترتفعوا انتم لاني بشرتكم مجانا بانجيل الله"));
arasuperobject.biblemap.put("b47_11_8", new arasuperobject(47,11,8,"سلبت كنائس اخرى آخذا اجرة لاجل خدمتكم. واذ كنت حاضرا عندكم واحتجت لم اثقل على احد"));
arasuperobject.biblemap.put("b47_11_9", new arasuperobject(47,11,9,"لان احتياجي سده الاخوة الذين أتوا من مكدونية. وفي كل شيء حفظت نفسي غير ثقيل عليكم وسأحفظها"));
arasuperobject.biblemap.put("b47_11_10", new arasuperobject(47,11,10,"حق المسيح فيّ. ان هذا الافتخار لا يسد عني في اقاليم اخائية"));
arasuperobject.biblemap.put("b47_11_11", new arasuperobject(47,11,11,"لماذا. ألاني لا احبكم. الله يعلم"));
arasuperobject.biblemap.put("b47_11_12", new arasuperobject(47,11,12,"ولكن ما افعله سافعله لاقطع فرصة الذين يريدون فرصة كي يوجدوا كما نحن ايضا في ما يفتخرون به"));
arasuperobject.biblemap.put("b47_11_13", new arasuperobject(47,11,13,"لان مثل هؤلاء هم رسل كذبة فعلة ماكرون مغيّرون شكلهم الى شبه رسل المسيح"));
arasuperobject.biblemap.put("b47_11_14", new arasuperobject(47,11,14,"ولا عجب. لان الشيطان نفسه يغيّر شكله الى شبه ملاك نور"));
arasuperobject.biblemap.put("b47_11_15", new arasuperobject(47,11,15,"فليس عظيما ان كان خدامه ايضا يغيّرون شكلهم كخدام للبر. الذين نهايتهم تكون حسب اعمالهم"));
arasuperobject.biblemap.put("b47_11_16", new arasuperobject(47,11,16,"اقول ايضا لا يظن احد اني غبي. وإلا فاقبلوني ولو كغبي لافتخر انا ايضا قليلا"));
arasuperobject.biblemap.put("b47_11_17", new arasuperobject(47,11,17,"الذي اتكلم به لست اتكلم به بحسب الرب بل كانه في غباوة في جسارة الافتخار هذه"));
arasuperobject.biblemap.put("b47_11_18", new arasuperobject(47,11,18,"بما ان كثيرين يفتخرون حسب الجسد افتخر انا ايضا"));
arasuperobject.biblemap.put("b47_11_19", new arasuperobject(47,11,19,"فانكم بسرور تحتملون الاغبياء اذ انتم عقلاء"));
arasuperobject.biblemap.put("b47_11_20", new arasuperobject(47,11,20,"لانكم تحتملون ان كان احد يستعبدكم. ان كان احد يأكلكم. ان كان احد يأخذكم. ان كان احد يرتفع. ان كان احد يضربكم على وجوهكم"));
arasuperobject.biblemap.put("b47_11_21", new arasuperobject(47,11,21,"على سبيل الهوان اقول كيف اننا كنا ضعفاء. ولكن الذي يجترئ فيه احد اقول في غباوة انا ايضا اجترئ فيه"));
arasuperobject.biblemap.put("b47_11_22", new arasuperobject(47,11,22,"أهم عبرانيون فانا ايضا. أهم اسرائليون فانا ايضا. أهم نسل ابراهيم فانا ايضا"));
arasuperobject.biblemap.put("b47_11_23", new arasuperobject(47,11,23,"أهم خدام المسيح. اقول كمختل العقل. فانا افضل. في الاتعاب اكثر. في الضربات اوفر. في السجون اكثر. في الميتات مرارا كثيرة"));
arasuperobject.biblemap.put("b47_11_24", new arasuperobject(47,11,24,"من اليهود خمس مرات قبلت اربعين جلدة الا واحدة"));
arasuperobject.biblemap.put("b47_11_25", new arasuperobject(47,11,25,"ثلاث مرات ضربت بالعصي. مرة رجمت. ثلاث مرات انكسرت بي السفينة. ليلا ونهارا قضيت في العمق"));
arasuperobject.biblemap.put("b47_11_26", new arasuperobject(47,11,26,"باسفار مرارا كثيرة. باخطار سيول. باخطار لصوص. باخطار من جنسي. باخطار من الامم. باخطار في المدينة. باخطار في البرية. باخطار في البحر. باخطار من اخوة كذبة"));
arasuperobject.biblemap.put("b47_11_27", new arasuperobject(47,11,27,"في تعب وكد. في اسهار مرارا كثيرة. في جوع وعطش. في اصوام مرارا كثيرة. في برد وعري"));
arasuperobject.biblemap.put("b47_11_28", new arasuperobject(47,11,28,"عدا ما هو دون ذلك. التراكم علي كل يوم. الاهتمام بجميع الكنائس"));
arasuperobject.biblemap.put("b47_11_29", new arasuperobject(47,11,29,"من يضعف وانا لا اضعف. من يعثر وانا لا التهب"));
arasuperobject.biblemap.put("b47_11_30", new arasuperobject(47,11,30,"ان كان يجب الافتخار فسأفتخر بامور ضعفي"));
arasuperobject.biblemap.put("b47_11_31", new arasuperobject(47,11,31,"الله ابو ربنا يسوع المسيح الذي هو مبارك الى الابد يعلم اني لست اكذب"));
arasuperobject.biblemap.put("b47_11_32", new arasuperobject(47,11,32,"في دمشق والي الحارث الملك كان يحرس مدينة الدمشقيين يريد ان يمسكني"));
arasuperobject.biblemap.put("b47_11_33", new arasuperobject(47,11,33,"فتدليت من طاقة في زنبيل من السور ونجوت من يديه"));
arasuperobject.biblemap.put("b47_12_1", new arasuperobject(47,12,1,"انه لا يوافقني ان افتخر. فاني آتي الى مناظر الرب واعلاناته"));
arasuperobject.biblemap.put("b47_12_2", new arasuperobject(47,12,2,"اعرف انسانا في المسيح قبل اربع عشرة سنة أفي الجسد لست اعلم ام خارج الجسد لست اعلم. الله يعلم. اختطف هذا الى السماء الثالثة"));
arasuperobject.biblemap.put("b47_12_3", new arasuperobject(47,12,3,"واعرف هذا الانسان أفي الجسد ام خارج الجسد لست اعلم. الله يعلم"));
arasuperobject.biblemap.put("b47_12_4", new arasuperobject(47,12,4,"انه اختطف الى الفردوس وسمع كلمات لا ينطق بها ولا يسوغ لانسان ان يتكلم بها"));
arasuperobject.biblemap.put("b47_12_5", new arasuperobject(47,12,5,"من جهة هذا افتخر. ولكن من جهة نفسي لا افتخر الا بضعفاتي"));
arasuperobject.biblemap.put("b47_12_6", new arasuperobject(47,12,6,"فاني ان اردت ان افتخر لا اكون غبيا لاني اقول الحق. ولكني اتحاشى لئلا يظن احد من جهتي فوق ما يراني او يسمع مني"));
arasuperobject.biblemap.put("b47_12_7", new arasuperobject(47,12,7,"ولئلا ارتفع بفرط الاعلانات اعطيت شوكة في الجسد ملاك الشيطان ليلطمني لئلا ارتفع"));
arasuperobject.biblemap.put("b47_12_8", new arasuperobject(47,12,8,"من جهة هذا تضرعت الى الرب ثلاث مرات ان يفارقني"));
arasuperobject.biblemap.put("b47_12_9", new arasuperobject(47,12,9,"فقال لي تكفيك نعمتي لان قوتي في الضعف تكمل. فبكل سرور افتخر بالحري في ضعفاتي لكي تحل علي قوة المسيح"));
arasuperobject.biblemap.put("b47_12_10", new arasuperobject(47,12,10,"لذلك اسر بالضعفات والشتائم والضرورات والاضطهادات والضيقات لاجل المسيح. لاني حينما انا ضعيف فحينئذ انا قوي"));
arasuperobject.biblemap.put("b47_12_11", new arasuperobject(47,12,11,"قد صرت غبيا وانا افتخر. انتم الزمتموني لانه كان ينبغي ان امدح منكم اذ لم انقص شيئا عن فائقي الرسل وان كنت لست شيئا"));
arasuperobject.biblemap.put("b47_12_12", new arasuperobject(47,12,12,"ان علامات الرسول صنعت بينكم في كل صبر بآيات وعجائب وقوات"));
arasuperobject.biblemap.put("b47_12_13", new arasuperobject(47,12,13,"لانه ما هو الذي نقصتم عن سائر الكنائس الا اني انا لم اثقل عليكم. سامحوني بهذا الظلم"));
arasuperobject.biblemap.put("b47_12_14", new arasuperobject(47,12,14,"هوذا المرة الثالثة انا مستعد ان آتي اليكم ولا اثقل عليكم. لاني لست اطلب ما هو لكم بل اياكم. لانه لا ينبغي ان الاولاد يذخرون للوالدين بل الوالدون للاولاد"));
arasuperobject.biblemap.put("b47_12_15", new arasuperobject(47,12,15,"واما انا فبكل سرور انفق وانفق لاجل انفسكم وان كنت كلما احبكم اكثر أحب اقل"));
arasuperobject.biblemap.put("b47_12_16", new arasuperobject(47,12,16,"فيلكن. انا لم اثقل عليكم لكن اذ كنت محتالا اخذتكم بمكر"));
arasuperobject.biblemap.put("b47_12_17", new arasuperobject(47,12,17,"هل طمعت فيكم باحد من الذين ارسلتهم اليكم"));
arasuperobject.biblemap.put("b47_12_18", new arasuperobject(47,12,18,"طلبت الى تيطس وارسلت معه الاخ. هل طمع فيكم تيطس. أما سلكنا بذات الروح الواحد. أما بذات الخطوات الواحدة"));
arasuperobject.biblemap.put("b47_12_19", new arasuperobject(47,12,19,"أتظنون ايضا اننا نحتج لكم. امام الله في المسيح نتكلم. ولكن الكل ايها الاحباء لاجل بنيانكم"));
arasuperobject.biblemap.put("b47_12_20", new arasuperobject(47,12,20,"لاني اخاف اذا جئت ان لا اجدكم كما اريد وأوجد منكم كما لا تريدون. ان توجد خصومات ومحاسدات وسخطات وتحزبات ومذمات ونميمات وتكبرات وتشويشات"));
arasuperobject.biblemap.put("b47_12_21", new arasuperobject(47,12,21,"ان يذلني الهي عندكم اذا جئت ايضا وانوح على كثيرين من الذين اخطأوا من قبل ولم يتوبوا عن النجاسة والزنى والعهارة التي فعلوها"));
arasuperobject.biblemap.put("b47_13_1", new arasuperobject(47,13,1,"هذه المرة الثالثة آتي اليكم. على فم شاهدين وثلاثة تقوم كل كلمة"));
arasuperobject.biblemap.put("b47_13_2", new arasuperobject(47,13,2,"قد سبقت فقلت واسبق فاقول كما وانا حاضر المرة الثانية وانا غائب الآن اكتب للذين اخطأوا من قبل ولجميع الباقين اني اذا جئت ايضا لا اشفق"));
arasuperobject.biblemap.put("b47_13_3", new arasuperobject(47,13,3,"اذ انتم تطلبون برهان المسيح المتكلم فيّ الذي ليس ضعيفا لكم بل قوي فيكم"));
arasuperobject.biblemap.put("b47_13_4", new arasuperobject(47,13,4,"لانه وان كان قد صلب من ضعف لكنه حيّ بقوة الله. فنحن ايضا ضعفاء فيه لكننا سنحيا معه بقوة الله من جهتكم"));
arasuperobject.biblemap.put("b47_13_5", new arasuperobject(47,13,5,"جربوا انفسكم هل انتم في الايمان. امتحنوا انفسكم. ام لستم تعرفون انفسكم ان يسوع المسيح هو فيكم ان لم تكونوا مرفوضين"));
arasuperobject.biblemap.put("b47_13_6", new arasuperobject(47,13,6,"لكنني ارجو انكم ستعرفون اننا نحن لسنا مرفوضين"));
arasuperobject.biblemap.put("b47_13_7", new arasuperobject(47,13,7,"واصلّي الى الله انكم لا تعملون شيئا رديّا ليس لكي نظهر نحن مزكين بل لكي تصنعوا انتم حسنا ونكون نحن كاننا مرفوضون"));
arasuperobject.biblemap.put("b47_13_8", new arasuperobject(47,13,8,"لاننا لا نستطيع شيئا ضد الحق بل لاجل الحق"));
arasuperobject.biblemap.put("b47_13_9", new arasuperobject(47,13,9,"لاننا نفرح حينما نكون نحن ضعفاء وانتم تكونون اقوياء. وهذا ايضا نطلبه كما لكم"));
arasuperobject.biblemap.put("b47_13_10", new arasuperobject(47,13,10,"لذلك اكتب بهذا وانا غائب لكي لا استعمل جزما وانا حاضر حسب السلطان الذي اعطاني اياه الرب للبنيان لا للهدم"));
arasuperobject.biblemap.put("b47_13_11", new arasuperobject(47,13,11,"اخيرا ايها الاخوة افرحوا. اكملوا. تعزوا. اهتموا اهتماما واحدا. عيشوا بالسلام واله المحبة والسلام سيكون معكم"));
arasuperobject.biblemap.put("b47_13_12", new arasuperobject(47,13,12,"سلموا بعضكم على بعض بقبلة مقدسة"));
arasuperobject.biblemap.put("b47_13_13", new arasuperobject(47,13,13,"يسلم عليكم جميع القديسين"));
arasuperobject.biblemap.put("b47_13_14", new arasuperobject(47,13,14,"نعمة ربنا يسوع المسيح ومحبة الله وشركة الروح القدس مع جميعكم. آمين"));

}

}