package ara.bible;

public class arabible28 {

public arabible28() {

putmapbible28();

}

private void putmapbible28() {

arasuperobject.biblemap.put("b28_1_1", new arasuperobject(28,1,1,"قول الرب الذي صار الى هوشع بن بئيري في ايام عزيا ويوثام وآحاز وحزقيا ملوك يهوذا وفي ايام يربعام بن يوآش ملك اسرائيل"));
arasuperobject.biblemap.put("b28_1_2", new arasuperobject(28,1,2,"اول ما كلّم الرب هوشع قال الرب لهوشع اذهب خذ لنفسك امرأة زنى واولاد زنى لان الارض قد زنت زنى تاركة الرب"));
arasuperobject.biblemap.put("b28_1_3", new arasuperobject(28,1,3,"فذهب واخذ جومر بنت دبلايم فحبلت وولدت له ابنا"));
arasuperobject.biblemap.put("b28_1_4", new arasuperobject(28,1,4,"فقال له الرب ادع اسمه يزرعيل لانني بعد قليل اعاقب بيت ياهو على دم يزرعيل وابيد مملكة بيت اسرائيل"));
arasuperobject.biblemap.put("b28_1_5", new arasuperobject(28,1,5,"ويكون في ذلك اليوم اني اكسر قوس اسرائيل في وادي يزرعيل"));
arasuperobject.biblemap.put("b28_1_6", new arasuperobject(28,1,6,"ثم حبلت ايضا وولدت بنتا فقال له ادع اسمها لورحامة لاني لا اعود ارحم بيت اسرائيل ايضا بل انزعهم نزعا"));
arasuperobject.biblemap.put("b28_1_7", new arasuperobject(28,1,7,"واما بيت يهوذا فارحمهم واخلّصهم بالرب الههم ولا اخلّصهم بقوس وبسيف وبحرب وبخيل وبفرسان"));
arasuperobject.biblemap.put("b28_1_8", new arasuperobject(28,1,8,"ثم فطمت لورحامة وحبلت فولدت ابنا"));
arasuperobject.biblemap.put("b28_1_9", new arasuperobject(28,1,9,"فقال ادع اسمه لوعمّي لانكم لستم شعبي وانا لا اكون لكم"));
arasuperobject.biblemap.put("b28_1_10", new arasuperobject(28,1,10,"لكن يكون عدد بني اسرائيل كرمل البحر الذي لا يكال ولا يعدّ ويكون عوضا عن ان يقال لهم لستم شعبي يقال لهم ابناء الله الحي"));
arasuperobject.biblemap.put("b28_1_11", new arasuperobject(28,1,11,"ويجمع بنو يهوذا وبنو اسرائيل معا ويجعلون لانفسهم راسا واحدا ويصعدون من الارض لان يوم يزرعيل عظيم"));
arasuperobject.biblemap.put("b28_2_1", new arasuperobject(28,2,1,"قولوا لاخواتكم عمّي ولاخوتكم رحامة"));
arasuperobject.biblemap.put("b28_2_2", new arasuperobject(28,2,2,"حاكموا امكم حاكموا لانها ليست امرأتي وانا لست رجلها لكي تعزل زناها عن وجهها وفسقها من بين ثدييها"));
arasuperobject.biblemap.put("b28_2_3", new arasuperobject(28,2,3,"لئلا اجرّدها عريانة واوقفها كيوم ولادتها واجعلها كقفر واصيرها كارض يابسة واميتها بالعطش"));
arasuperobject.biblemap.put("b28_2_4", new arasuperobject(28,2,4,"ولا ارحم اولادها لانهم اولاد زنى"));
arasuperobject.biblemap.put("b28_2_5", new arasuperobject(28,2,5,"لان امهم قد زنت. التي حبلت بهم صنعت خزيا. لانها قالت اذهب وراء محبيّ الذين يعطون خبزي ومائي صوفي وكتاني زيتي واشربتي"));
arasuperobject.biblemap.put("b28_2_6", new arasuperobject(28,2,6,"لذلك هانذا اسيج طريقك بالشوك وابني حائطها حتى لا تجد مسالكها"));
arasuperobject.biblemap.put("b28_2_7", new arasuperobject(28,2,7,"فتتبع محبيها ولا تدركهم وتفتش عليهم ولا تجدهم. فتقول اذهب وارجع الى رجلي الاول لانه حينئذ كان خير لي من الآن"));
arasuperobject.biblemap.put("b28_2_8", new arasuperobject(28,2,8,"وهي لم تعرف اني انا اعطيتها القمح والمسطار والزيت وكثّرت لها فضة وذهبا جعلوه لبعل"));
arasuperobject.biblemap.put("b28_2_9", new arasuperobject(28,2,9,"لذلك ارجع وآخذ قمحي في حينه ومسطاري في وقته وانزع صوفي وكتاني اللذين لستر عورتها"));
arasuperobject.biblemap.put("b28_2_10", new arasuperobject(28,2,10,"والآن اكشف عورتها امام عيون محبيها ولا ينقذها احد من يدي"));
arasuperobject.biblemap.put("b28_2_11", new arasuperobject(28,2,11,"وابطّل كل افراحها اعيادها ورؤوس شهورها وسبوتها وجميع مواسمها"));
arasuperobject.biblemap.put("b28_2_12", new arasuperobject(28,2,12,"واخرّب كرمها وتينها اللذين قالت هما اجرتي التي اعطانيها محبيّ واجعلهما وعرا فيأكلهما حيوان البرية"));
arasuperobject.biblemap.put("b28_2_13", new arasuperobject(28,2,13,"واعاقبها على ايام بعليم التي فيها كانت تبخر لهم وتتزين بخزائمها وحليها وتذهب وراء محبيها وتنساني انا يقول الرب"));
arasuperobject.biblemap.put("b28_2_14", new arasuperobject(28,2,14,"لكن هانذا اتملقها واذهب بها الى البرية والاطفها"));
arasuperobject.biblemap.put("b28_2_15", new arasuperobject(28,2,15,"واعطيها كرومها من هناك ووادي عخور بابا للرجاء وهي تغني هناك كايام صباها وكيوم صعودها من ارض مصر"));
arasuperobject.biblemap.put("b28_2_16", new arasuperobject(28,2,16,"ويكون في ذلك اليوم يقول الرب انك تدعينني رجلي ولا تدعينني بعد بعلي"));
arasuperobject.biblemap.put("b28_2_17", new arasuperobject(28,2,17,"وانزع اسماء البعليم من فمها فلا تذكر ايضا باسمائها"));
arasuperobject.biblemap.put("b28_2_18", new arasuperobject(28,2,18,"واقطع لهم عهدا في ذلك اليوم مع حيوان البرية وطيور السماء ودبابات الارض واكسر القوس والسيف والحرب من الارض واجعلهم يضطجعون آمنين"));
arasuperobject.biblemap.put("b28_2_19", new arasuperobject(28,2,19,"واخطبك لنفسي الى الابد واخطبك لنفسي بالعدل والحق والاحسان والمراحم"));
arasuperobject.biblemap.put("b28_2_20", new arasuperobject(28,2,20,"اخطبك لنفسي بالامانة فتعرفين الرب"));
arasuperobject.biblemap.put("b28_2_21", new arasuperobject(28,2,21,"ويكون في ذلك اليوم اني استجيب يقول الرب استجيب السموات وهي تستجيب الارض"));
arasuperobject.biblemap.put("b28_2_22", new arasuperobject(28,2,22,"والارض تستجيب القمح والمسطار والزيت وهي تستجيب يزرعيل"));
arasuperobject.biblemap.put("b28_2_23", new arasuperobject(28,2,23,"وازرعها لنفسي في الارض وارحم لورحامة واقول للوعمّي انت شعبي وهو يقول انت الهي"));
arasuperobject.biblemap.put("b28_3_1", new arasuperobject(28,3,1,"وقال الرب لي اذهب ايضا احبب امرأة حبيبة صاحب وزانية كمحبة الرب لبني اسرائيل وهم ملتفتون الى آلهة اخرى ومحبّون لاقراص الزبيب"));
arasuperobject.biblemap.put("b28_3_2", new arasuperobject(28,3,2,"فاشتريتها لنفسي بخمسة عشر شاقل فضة وبحومر ولثك شعير"));
arasuperobject.biblemap.put("b28_3_3", new arasuperobject(28,3,3,"وقلت لها تقعدين اياما كثيرة لا تزني ولا تكوني لرجل وانا كذلك لك"));
arasuperobject.biblemap.put("b28_3_4", new arasuperobject(28,3,4,"لان بني اسرائيل سيقعدون اياما كثيرة بلا ملك وبلا رئيس وبلا ذبيحة وبلا تمثال وبلا افود وترافيم"));
arasuperobject.biblemap.put("b28_3_5", new arasuperobject(28,3,5,"بعد ذلك يعود بنو اسرائيل ويطلبون الرب الههم وداود ملكهم ويفزعون الى الرب والى جوده في آخر الايام"));
arasuperobject.biblemap.put("b28_4_1", new arasuperobject(28,4,1,"اسمعوا قول الرب يا بني اسرائيل. ان للرب محاكمة مع سكان الارض لانه لا امانة ولا احسان ولا معرفة الله في الارض"));
arasuperobject.biblemap.put("b28_4_2", new arasuperobject(28,4,2,"لعن وكذب وقتل وسرقة وفسق. يعتنفون ودماء تلحق دماء"));
arasuperobject.biblemap.put("b28_4_3", new arasuperobject(28,4,3,"لذلك تنوح الارض ويذبل كل من يسكن فيها مع حيوان البرية وطيور السماء واسماك البحر ايضا تنتزع"));
arasuperobject.biblemap.put("b28_4_4", new arasuperobject(28,4,4,"ولكن لا يحاكم احد ولا يعاتب احد. وشعبك كمن يخاصم كاهنا"));
arasuperobject.biblemap.put("b28_4_5", new arasuperobject(28,4,5,"فتتعثر في النهار ويتعثر ايضا النبي معك في الليل وانا اخرب امّك"));
arasuperobject.biblemap.put("b28_4_6", new arasuperobject(28,4,6,"قد هلك شعبي من عدم المعرفة. لانك انت رفضت المعرفة ارفضك انا حتى لا تكهن لي. ولانك نسيت شريعة الهك انسى انا ايضا بنيك"));
arasuperobject.biblemap.put("b28_4_7", new arasuperobject(28,4,7,"على حسبما كثروا هكذا اخطأوا اليّ فابدل كرامتهم بهوان"));
arasuperobject.biblemap.put("b28_4_8", new arasuperobject(28,4,8,"يأكلون خطية شعبي والى اثمهم يحملون نفوسهم"));
arasuperobject.biblemap.put("b28_4_9", new arasuperobject(28,4,9,"فيكون كما الشعب هكذا الكاهن واعاقبهم على طرقهم وارد اعمالهم عليهم"));
arasuperobject.biblemap.put("b28_4_10", new arasuperobject(28,4,10,"فيأكلون ولا يشبعون ويزنون ولا يكثرون لانهم قد تركوا عبادة الرب"));
arasuperobject.biblemap.put("b28_4_11", new arasuperobject(28,4,11,"الزنى والخمر والسلافة تخلب القلب"));
arasuperobject.biblemap.put("b28_4_12", new arasuperobject(28,4,12,"شعبي يسأل خشبه وعصاه تخبره لان روح الزنى قد اضلّهم فزنوا من تحت الههم"));
arasuperobject.biblemap.put("b28_4_13", new arasuperobject(28,4,13,"يذبحون على رؤوس الجبال ويبخرون على التلال تحت البلوط واللبنى والبطم لان ظلها حسن. لذلك تزني بناتكم وتفسق كنّاتكم"));
arasuperobject.biblemap.put("b28_4_14", new arasuperobject(28,4,14,"لا اعاقب بناتكم لانهنّ يزنين ولا كنّاتكم لانهنّ يفسقن. لانهم يعتزلون مع الزانيات ويذبحون مع الناذرات الزنى. وشعب لا يعقل يصرع"));
arasuperobject.biblemap.put("b28_4_15", new arasuperobject(28,4,15,"ان كنت انت زانيا يا اسرائيل فلا يأثم يهوذا. ولا تأتوا الى الجلجال ولا تصعدوا الى بيت آون ولا تحلفوا حيّ هو الرب"));
arasuperobject.biblemap.put("b28_4_16", new arasuperobject(28,4,16,"انه قد جمح اسرائيل كبقرة جامحة. الآن يرعاهم الرب كخروف في مكان واسع"));
arasuperobject.biblemap.put("b28_4_17", new arasuperobject(28,4,17,"افرايم موثق بالاصنام. اتركوه"));
arasuperobject.biblemap.put("b28_4_18", new arasuperobject(28,4,18,"متى انتهت منادمتهم زنوا زنى. احب مجانّها احبوا الهوان"));
arasuperobject.biblemap.put("b28_4_19", new arasuperobject(28,4,19,"قد صرّتها الريح في اجنحتها وخجلوا من ذبائحهم"));
arasuperobject.biblemap.put("b28_5_1", new arasuperobject(28,5,1,"اسمعوا هذا ايها الكهنة وانصتوا يا بيت اسرائيل واصغوا يا بيت الملك لان عليكم القضاء اذ صرتم فخّا في مصفاة وشبكة مبسوطة على تابور"));
arasuperobject.biblemap.put("b28_5_2", new arasuperobject(28,5,2,"وقد توغّلوا في ذبائح الزيغان فانا تأديب لجميعهم"));
arasuperobject.biblemap.put("b28_5_3", new arasuperobject(28,5,3,"انا اعرف افرايم. واسرائيل ليس مخفيا عني. انك الآن زنيت يا افرايم. قد تنجس اسرائيل"));
arasuperobject.biblemap.put("b28_5_4", new arasuperobject(28,5,4,"افعالهم لا تدعهم يرجعون الى الههم لان روح الزنى في باطنهم وهم لا يعرفون الرب"));
arasuperobject.biblemap.put("b28_5_5", new arasuperobject(28,5,5,"وقد أذلّت عظمة اسرائيل في وجهه فيتعثر اسرائيل وافرايم في اثمهما ويتعثر يهوذا ايضا معهما"));
arasuperobject.biblemap.put("b28_5_6", new arasuperobject(28,5,6,"يذهبون بغنمهم وبقرهم ليطلبوا الرب ولا يجدونه. قد تنحى عنهم"));
arasuperobject.biblemap.put("b28_5_7", new arasuperobject(28,5,7,"قد غدروا بالرب. لانهم ولدوا اولادا اجنبيين. الآن يأكلهم شهر مع انصبتهم"));
arasuperobject.biblemap.put("b28_5_8", new arasuperobject(28,5,8,"اضربوا بالبوق في جبعة بالقرن في الرامة. اصرخوا في بيت آون. وراءك يا بنيامين"));
arasuperobject.biblemap.put("b28_5_9", new arasuperobject(28,5,9,"يصير افرايم خرابا في يوم التأديب. في اسباط اسرائيل اعلمت اليقين"));
arasuperobject.biblemap.put("b28_5_10", new arasuperobject(28,5,10,"صارت رؤساء يهوذا كناقلي التخوم فاسكب عليهم سخطي كالماء"));
arasuperobject.biblemap.put("b28_5_11", new arasuperobject(28,5,11,"افرايم مظلوم مسحوق القضاء لانه ارتضى ان يمضي وراء الوصية"));
arasuperobject.biblemap.put("b28_5_12", new arasuperobject(28,5,12,"فانا لافرايم كالعث ولبيت يهوذا كالسوس"));
arasuperobject.biblemap.put("b28_5_13", new arasuperobject(28,5,13,"ورأى افرايم مرضه ويهوذا جرحه فمضى افرايم الى اشور وارسل الى ملك عدو ولكنه لا يستطيع ان يشفيكم ولا ان يزيل منكم الجرح"));
arasuperobject.biblemap.put("b28_5_14", new arasuperobject(28,5,14,"لاني لافرايم كالاسد ولبيت يهوذا كشبل الاسد فاني انا افترس وامضي آخذ ولا منقذ"));
arasuperobject.biblemap.put("b28_5_15", new arasuperobject(28,5,15,"اذهب وارجع الى مكاني حتى يجازوا ويطلبوا وجهي. في ضيقهم يبكرون اليّ"));
arasuperobject.biblemap.put("b28_6_1", new arasuperobject(28,6,1,"هلم نرجع الى الرب لانه هو افترس فيشفينا. ضرب فيجبرنا"));
arasuperobject.biblemap.put("b28_6_2", new arasuperobject(28,6,2,"يحيينا بعد يومين. في اليوم الثالث يقيمنا فنحيا امامه"));
arasuperobject.biblemap.put("b28_6_3", new arasuperobject(28,6,3,"لنعرف فلنتتبع لنعرف الرب. خروجه يقين كالفجر. يأتي الينا كالمطر. كمطر متاخر يسقي الارض"));
arasuperobject.biblemap.put("b28_6_4", new arasuperobject(28,6,4,"ماذا اصنع بك يا افرايم. ماذا اصنع بك يا يهوذا. فان احسانكم كسحاب الصبح وكالندى الماضي باكرا"));
arasuperobject.biblemap.put("b28_6_5", new arasuperobject(28,6,5,"لذلك اقرضهم بالانبياء اقتلهم باقوال فمي والقضاء عليك كنور قد خرج"));
arasuperobject.biblemap.put("b28_6_6", new arasuperobject(28,6,6,"اني اريد رحمة لا ذبيحة ومعرفة الله اكثر من محرقات"));
arasuperobject.biblemap.put("b28_6_7", new arasuperobject(28,6,7,"ولكنهم كآدم تعدّوا العهد. هناك غدروا بي"));
arasuperobject.biblemap.put("b28_6_8", new arasuperobject(28,6,8,"جلعاد قرية فاعلي الاثم مدوسة بالدم"));
arasuperobject.biblemap.put("b28_6_9", new arasuperobject(28,6,9,"وكما يكمن لصوص لانسان كذلك زمرة الكهنة في الطريق يقتلون نحو شكيم. انهم قد صنعوا فاحشة"));
arasuperobject.biblemap.put("b28_6_10", new arasuperobject(28,6,10,"في بيت اسرائيل رأيت أمرا فظيعا. هناك زنى افرايم. تنجس اسرائيل"));
arasuperobject.biblemap.put("b28_6_11", new arasuperobject(28,6,11,"وانت ايضا يا يهوذا قد أعدّ لك حصاد عندما ارد سبي شعبي"));
arasuperobject.biblemap.put("b28_7_1", new arasuperobject(28,7,1,"حينما كنت اشفي اسرائيل أعلن اثم افرايم وشرور السامرة فانهم قد صنعوا غشا. السارق دخل والغزاة نهبوا في الخارج"));
arasuperobject.biblemap.put("b28_7_2", new arasuperobject(28,7,2,"ولا يفتكرون في قلوبهم اني قد تذكرت كل شرهم. الآن قد احاطت بهم افعالهم. صارت امام وجهي"));
arasuperobject.biblemap.put("b28_7_3", new arasuperobject(28,7,3,"بشرّهم يفرّحون الملك وبكذبهم الرؤساء"));
arasuperobject.biblemap.put("b28_7_4", new arasuperobject(28,7,4,"كلهم فاسقون كتنور محمى من الخباز. يبطّل الايقاد من وقتما يعجن العجين الى ان يختمر"));
arasuperobject.biblemap.put("b28_7_5", new arasuperobject(28,7,5,"يوم ملكنا يمرض الرؤساء من سورة الخمر. يبسط يده مع المستهزئين"));
arasuperobject.biblemap.put("b28_7_6", new arasuperobject(28,7,6,"لانهم يقربون قلوبهم في مكيدتهم كالتنور. كل الليل ينام خبازهم وفي الصباح يكون محمى كنار ملتهبة"));
arasuperobject.biblemap.put("b28_7_7", new arasuperobject(28,7,7,"كلهم حامون كالتنور واكلوا قضاتهم. جميع ملوكهم سقطوا. ليس بينهم من يدعو اليّ"));
arasuperobject.biblemap.put("b28_7_8", new arasuperobject(28,7,8,"افرايم يختلط بالشعوب. افرايم صار خبز ملّة لم يقلب"));
arasuperobject.biblemap.put("b28_7_9", new arasuperobject(28,7,9,"اكل الغرباء ثروته وهو لا يعرف وقد رشّ عليه الشيب وهو لا يعرف"));
arasuperobject.biblemap.put("b28_7_10", new arasuperobject(28,7,10,"وقد أذلّت عظمة اسرائيل في وجهه وهم لا يرجعون الى الرب الههم ولا يطلبونه مع كل هذا"));
arasuperobject.biblemap.put("b28_7_11", new arasuperobject(28,7,11,"وصار افرايم كحمامة رعناء بلا قلب. يدعون مصر. يمضون الى اشور"));
arasuperobject.biblemap.put("b28_7_12", new arasuperobject(28,7,12,"عندما يمضون ابسط عليهم شبكتي. القيهم كطيور السماء. أودّبهم بحسب خبر جماعتهم"));
arasuperobject.biblemap.put("b28_7_13", new arasuperobject(28,7,13,"ويل لهم لانهم هربوا عني. تبّا لهم لانهم اذنبوا اليّ. انا افديهم وهم تكلموا عليّ بكذب"));
arasuperobject.biblemap.put("b28_7_14", new arasuperobject(28,7,14,"ولا يصرخون اليّ بقلوبهم حينما يولولون على مضاجعهم. يتجمعون لاجل القمح والخمر ويرتدّون عني"));
arasuperobject.biblemap.put("b28_7_15", new arasuperobject(28,7,15,"وانا انذرتهم وشددت اذرعهم وهم يفكرون عليّ بالشر"));
arasuperobject.biblemap.put("b28_7_16", new arasuperobject(28,7,16,"يرجعون ليس الى العلي. قد صاروا كقوس مخطئة. يسقط رؤساؤهم بالسيف من اجل سخط ألسنتهم. هذا هزؤهم في ارض مصر"));
arasuperobject.biblemap.put("b28_8_1", new arasuperobject(28,8,1,"الى فمك بالبوق. كالنسر على بيت الرب. لانهم قد تجاوزوا عهدي وتعدّوا على شريعتي"));
arasuperobject.biblemap.put("b28_8_2", new arasuperobject(28,8,2,"اليّ يصرخون يا الهي نعرفك نحن اسرائيل"));
arasuperobject.biblemap.put("b28_8_3", new arasuperobject(28,8,3,"قد كره اسرائيل الصلاح فيتبعه العدو"));
arasuperobject.biblemap.put("b28_8_4", new arasuperobject(28,8,4,"هم اقاموا ملوكا وليس مني. اقاموا رؤساء وانا لم اعرف. صنعوا لانفسهم من فضتهم وذهبهم اصناما لكي ينقرضوا"));
arasuperobject.biblemap.put("b28_8_5", new arasuperobject(28,8,5,"قد زنخ عجلك يا سامرة. حمي غضبي عليهم. الى متى لا يستطيعون النقاوة"));
arasuperobject.biblemap.put("b28_8_6", new arasuperobject(28,8,6,"انه هو ايضا من اسرائيل. صنعه الصانع وليس هو الها. ان عجل السامرة يصير كسرا"));
arasuperobject.biblemap.put("b28_8_7", new arasuperobject(28,8,7,"انهم يزرعون الريح ويحصدون الزوبعة. زرع ليس له غلّة لا يصنع دقيقا. وان صنع فالغرباء تبتلعه"));
arasuperobject.biblemap.put("b28_8_8", new arasuperobject(28,8,8,"قد ابتلع اسرائيل. الآن صاروا بين الامم كاناء لا مسرّة فيه"));
arasuperobject.biblemap.put("b28_8_9", new arasuperobject(28,8,9,"لانهم صعدوا الى اشور مثل حمار وحشي معتزل بنفسه. استأجر افرايم محبين"));
arasuperobject.biblemap.put("b28_8_10", new arasuperobject(28,8,10,"اني وان كانوا يستأجرون بين الامم الآن اجمعهم فينفكّون قليلا من ثقل ملك الرؤساء"));
arasuperobject.biblemap.put("b28_8_11", new arasuperobject(28,8,11,"لان افرايم كثّر مذابح للخطية صارت له المذابح للخطية"));
arasuperobject.biblemap.put("b28_8_12", new arasuperobject(28,8,12,"اكتب له كثرة شرائعي فهي تحسب اجنبية"));
arasuperobject.biblemap.put("b28_8_13", new arasuperobject(28,8,13,"اما ذبائح تقدماتي فيذبحون لحما وياكلون. الرب لا يرتضيها. الآن يذكر اثمهم ويعاقب خطيتهم. انهم الى مصر يرجعون"));
arasuperobject.biblemap.put("b28_8_14", new arasuperobject(28,8,14,"وقد نسي اسرائيل صانعه وبنى قصورا وكثّر يهوذا مدنا حصينة. لكني ارسل على مدنه نارا فتأكل قصوره"));
arasuperobject.biblemap.put("b28_9_1", new arasuperobject(28,9,1,"لا تفرح يا اسرائيل طربا كالشعوب. لانك قد زنيت عن الهك. احببت الاجرة على جميع بيادر الحنطة"));
arasuperobject.biblemap.put("b28_9_2", new arasuperobject(28,9,2,"لا يطعمهم البيدر والمعصرة ويكذب عليهم المسطار"));
arasuperobject.biblemap.put("b28_9_3", new arasuperobject(28,9,3,"لا يسكنون في ارض الرب بل يرجع افرايم الى مصر ويأكلون النجس في اشور"));
arasuperobject.biblemap.put("b28_9_4", new arasuperobject(28,9,4,"لا يسكبون للرب خمرا ولا تسرّه ذبائحهم. انها لهم كخبز الحزن كل من اكله يتنجس. ان خبزهم لنفسهم. لا يدخل بيت الرب"));
arasuperobject.biblemap.put("b28_9_5", new arasuperobject(28,9,5,"ماذا تصنعون في يوم الموسم وفي يوم عيد الرب"));
arasuperobject.biblemap.put("b28_9_6", new arasuperobject(28,9,6,"انهم قد ذهبوا من الخراب. تجمعهم مصر. تدفنهم موف. يرث القريص نفائس فضتهم يكون العوسج في منازلهم"));
arasuperobject.biblemap.put("b28_9_7", new arasuperobject(28,9,7,"جاءت ايام العقاب. جاءت ايام الجزاء. سيعرف اسرائيل. النبي احمق. انسان الروح مجنون من كثرة اثمك وكثرة الحقد"));
arasuperobject.biblemap.put("b28_9_8", new arasuperobject(28,9,8,"افرايم منتظر عند الهي. النبي فخ صيّاد على جميع طرقه. حقد في بيت الهه"));
arasuperobject.biblemap.put("b28_9_9", new arasuperobject(28,9,9,"قد توغّلوا فسدوا كايام جبعة. سيذكر اثمهم. سيعاقب خطاياهم"));
arasuperobject.biblemap.put("b28_9_10", new arasuperobject(28,9,10,"وجدت اسرائيل كعنب في البرية. رأيت آباءكم كباكورة على تينة في اولها. اما هم فجاءوا الى بعل فغور ونذروا انفسهم للخزي وصاروا رجسا كما احبوا"));
arasuperobject.biblemap.put("b28_9_11", new arasuperobject(28,9,11,"افرايم تطير كرامتهم كطائر من الولادة ومن البطن ومن الحبل"));
arasuperobject.biblemap.put("b28_9_12", new arasuperobject(28,9,12,"وان ربّوا اولادهم اثكلهم اياهم حتى لا يكون انسان. ويل لهم ايضا متى انصرفت عنهم"));
arasuperobject.biblemap.put("b28_9_13", new arasuperobject(28,9,13,"افرايم كما ارى كصور مغروس في مرعى ولكن افرايم سيخرج بنيه الى القاتل"));
arasuperobject.biblemap.put("b28_9_14", new arasuperobject(28,9,14,"اعطهم يا رب. ماذا تعطي. اعطهم رحما مسقطا وثديين يبسين"));
arasuperobject.biblemap.put("b28_9_15", new arasuperobject(28,9,15,"كل شرهم في الجلجال. اني هناك ابغضتهم. من اجل سوء افعالهم اطردهم من بيتي. لا اعود احبهم. جميع رؤسائهم متمردون"));
arasuperobject.biblemap.put("b28_9_16", new arasuperobject(28,9,16,"افرايم مضروب. اصلهم قد جف. لا يصنعون ثمرا. وان ولدوا أميت مشتهيات بطونهم"));
arasuperobject.biblemap.put("b28_9_17", new arasuperobject(28,9,17,"يرفضهم الهي لانهم لم يسمعوا له. فيكونون تائهين بين الامم"));
arasuperobject.biblemap.put("b28_10_1", new arasuperobject(28,10,1,"اسرائيل جفنة ممتدّة. يخرج ثمرا لنفسه. على حسب كثرة ثمره قد كثّر المذابح. على حسب جودة ارضه اجاد الانصاب"));
arasuperobject.biblemap.put("b28_10_2", new arasuperobject(28,10,2,"قد قسموا قلوبهم. الآن يعاقبون. هو يحطم مذابحهم يخرب انصابهم"));
arasuperobject.biblemap.put("b28_10_3", new arasuperobject(28,10,3,"انهم الآن يقولون لا ملك لنا لاننا لا نخاف الرب فالملك ماذا يصنع بنا"));
arasuperobject.biblemap.put("b28_10_4", new arasuperobject(28,10,4,"يتكلمون كلاما باقسام باطلة يقطعون عهدا فينبت القضاء عليهم كالعلقم في اتلام الحقل"));
arasuperobject.biblemap.put("b28_10_5", new arasuperobject(28,10,5,"على عجول بيت آون يخاف سكان السامرة. ان شعبه ينوح عليه وكهنته عليه يرتعدون على مجده لانه انتفى عنه"));
arasuperobject.biblemap.put("b28_10_6", new arasuperobject(28,10,6,"وهو ايضا يجلب الى اشور هدية لملك عدو. يأخذ افرايم خزيا ويخجل اسرائيل على رأيه"));
arasuperobject.biblemap.put("b28_10_7", new arasuperobject(28,10,7,"السامرة ملكها يبيد كغثاء على وجه الماء"));
arasuperobject.biblemap.put("b28_10_8", new arasuperobject(28,10,8,"وتخرب شوامخ آون خطية اسرائيل. يطلع الشوك والحسك على مذابحهم ويقولون للجبال غطينا وللتلال اسقطي علينا"));
arasuperobject.biblemap.put("b28_10_9", new arasuperobject(28,10,9,"من ايام جبعة اخطأت يا اسرائيل. هناك وقفوا لم تدركهم في جبعة الحرب على بني الاثم"));
arasuperobject.biblemap.put("b28_10_10", new arasuperobject(28,10,10,"حينما اريد أودّبهم ويجتمع عليهم شعوب في ارتباطهم بإثميهم"));
arasuperobject.biblemap.put("b28_10_11", new arasuperobject(28,10,11,"وافرايم عجلة متمرنة تحب الدراس ولكني اجتاز على عنقها الحسن. اركب على افرايم. يفلح يهوذا. يمهد يعقوب"));
arasuperobject.biblemap.put("b28_10_12", new arasuperobject(28,10,12,"ازرعوا لانفسكم بالبر. احصدوا بحسب الصلاح احرثوا لانفسكم حرثا فانه وقت لطلب الرب حتى يأتي ويعلّمكم البر"));
arasuperobject.biblemap.put("b28_10_13", new arasuperobject(28,10,13,"قد حرثتم النفاق حصدتم الاثم. اكلتم ثمر الكذب. لانك وثقت بطريقك بكثرة ابطالك"));
arasuperobject.biblemap.put("b28_10_14", new arasuperobject(28,10,14,"يقوم ضجيج في شعوبك وتخرب جميع حصونك كاخراب شلمان بيت اربئيل في يوم الحرب. الام مع الاولاد حطّمت"));
arasuperobject.biblemap.put("b28_10_15", new arasuperobject(28,10,15,"هكذا تصنع بكم بيت ايل من اجل رداءة شركم. في الصبح يهلك ملك اسرائيل هلاكا"));
arasuperobject.biblemap.put("b28_11_1", new arasuperobject(28,11,1,"لما كان اسرائيل غلاما احببته ومن مصر دعوت ابني"));
arasuperobject.biblemap.put("b28_11_2", new arasuperobject(28,11,2,"كل ما دعوهم ذهبوا من امامهم يذبحون للبعليم ويبخّرون للتماثيل المنحوتة"));
arasuperobject.biblemap.put("b28_11_3", new arasuperobject(28,11,3,"وانا درّجت افرايم ممسكا اياهم باذرعهم فلم يعرفوا اني شفيتهم"));
arasuperobject.biblemap.put("b28_11_4", new arasuperobject(28,11,4,"كنت اجذبهم بحبال البشر بربط المحبة وكنت لهم كمن يرفع النير عن اعناقهم ومددت اليه مطعما اياه"));
arasuperobject.biblemap.put("b28_11_5", new arasuperobject(28,11,5,"لا يرجع الى ارض مصر بل اشور هو ملكه. لانهم أبوا ان يرجعوا"));
arasuperobject.biblemap.put("b28_11_6", new arasuperobject(28,11,6,"يثور السيف في مدنهم ويتلف عصيّها وياكلهم من اجل آرائهم"));
arasuperobject.biblemap.put("b28_11_7", new arasuperobject(28,11,7,"وشعبي جانحون الى الارتداد عني فيدعونهم الى العلي ولا احد يرفعه"));
arasuperobject.biblemap.put("b28_11_8", new arasuperobject(28,11,8,"كيف اجعلك يا افرايم. اصيّرك يا اسرائيل. كيف اجعلك كأدمة. اصنعك كصبوييم. قد انقلب عليّ قلبي. اضطرمت مراحمي جميعا"));
arasuperobject.biblemap.put("b28_11_9", new arasuperobject(28,11,9,"لا اجري حمو غضبي لا اعود اخرب افرايم لاني الله لا انسان القدوس في وسطك فلا آتي بسخط"));
arasuperobject.biblemap.put("b28_11_10", new arasuperobject(28,11,10,"وراء الرب يمشون. كاسد يزمجر. فانه يزمجر فيسرع البنون من البحر"));
arasuperobject.biblemap.put("b28_11_11", new arasuperobject(28,11,11,"يسرعون كعصفور من مصر وكحمامة من ارض اشور فأسكنهم في بيوتهم يقول الرب"));
arasuperobject.biblemap.put("b28_11_12", new arasuperobject(28,11,12,"قد احاط بي افرايم بالكذب وبيت اسرائيل بالمكر ولم يزل يهوذا شاردا عن الله وعن القدوس الامين"));
arasuperobject.biblemap.put("b28_12_1", new arasuperobject(28,12,1,"افرايم راعي الريح وتابع الريح الشرقية. كل يوم يكثر الكذب والاغتصاب ويقطعون مع اشور عهدا والزيت الى مصر يجلب"));
arasuperobject.biblemap.put("b28_12_2", new arasuperobject(28,12,2,"فللرب خصام مع يهوذا وهو مزمع ان يعاقب يعقوب بحسب طرقه. بحسب افعاله يرد عليه"));
arasuperobject.biblemap.put("b28_12_3", new arasuperobject(28,12,3,"في البطن قبض بعقب اخيه وبقوّته جاهد مع الله"));
arasuperobject.biblemap.put("b28_12_4", new arasuperobject(28,12,4,"جاهد مع الملاك وغلب. بكى واسترحمه. وجده في بيت ايل وهناك تكلم معنا"));
arasuperobject.biblemap.put("b28_12_5", new arasuperobject(28,12,5,"والرب اله الجنود يهوه اسمه"));
arasuperobject.biblemap.put("b28_12_6", new arasuperobject(28,12,6,"وانت فارجع الى الهك. احفظ الرحمة والحق وانتظر الهك دائما"));
arasuperobject.biblemap.put("b28_12_7", new arasuperobject(28,12,7,"مثل الكنعاني في يده موازين الغش. يحب ان يظلم"));
arasuperobject.biblemap.put("b28_12_8", new arasuperobject(28,12,8,"فقال افرايم اني صرت غنيا. وجدت لنفسي ثروة. جميع اتعابي لا يجدون لي فيها ذنبا هو خطية"));
arasuperobject.biblemap.put("b28_12_9", new arasuperobject(28,12,9,"وانا الرب الهك من ارض مصر حتى اسكنك الخيام كايام الموسم"));
arasuperobject.biblemap.put("b28_12_10", new arasuperobject(28,12,10,"وكلّمت الانبياء وكثّرت الرؤى وبيد الانبياء مثّلت امثالا"));
arasuperobject.biblemap.put("b28_12_11", new arasuperobject(28,12,11,"انهم في جلعاد قد صاروا اثما بطلا لا غير. في الجلجال ذبحوا ثيرانا ومذابحهم كرجم في اتلام الحقل"));
arasuperobject.biblemap.put("b28_12_12", new arasuperobject(28,12,12,"وهرب يعقوب الى صحراء ارام وخدم اسرائيل لاجل امرأة ولاجل امرأة رعى"));
arasuperobject.biblemap.put("b28_12_13", new arasuperobject(28,12,13,"وبنبيّ اصعد الرب اسرائيل من مصر وبنبيّ‎حفظ"));
arasuperobject.biblemap.put("b28_12_14", new arasuperobject(28,12,14,"اغاظه اسرائيل بمرارة فيترك دماءه عليه ويردّ سيده عاره عليه"));
arasuperobject.biblemap.put("b28_13_1", new arasuperobject(28,13,1,"لما تكلم افرايم برعدة ترفّع في اسرائيل. ولما اثم ببعل مات"));
arasuperobject.biblemap.put("b28_13_2", new arasuperobject(28,13,2,"والآن يزدادون خطية ويصنعون لانفسهم تماثيل مسبوكة من فضتهم اصناما بحذاقتهم كلها عمل الصناع. عنها هم يقولون ذابحو الناس يقبّلون العجول"));
arasuperobject.biblemap.put("b28_13_3", new arasuperobject(28,13,3,"لذلك يكونون كسحاب الصبح وكالندى الماضي باكرا. كعصافة تخطف من البيدر وكدخان من الكوّة"));
arasuperobject.biblemap.put("b28_13_4", new arasuperobject(28,13,4,"وانا الرب الهك من ارض مصر. والها سواي لست تعرف ولا مخلّص غيري"));
arasuperobject.biblemap.put("b28_13_5", new arasuperobject(28,13,5,"انا عرفتك في البرية في ارض العطش"));
arasuperobject.biblemap.put("b28_13_6", new arasuperobject(28,13,6,"لما رعوا شبعوا. شبعوا وارتفعت قلوبهم لذلك نسوني"));
arasuperobject.biblemap.put("b28_13_7", new arasuperobject(28,13,7,"فاكون لهم كاسد. ارصد على الطريق كنمر"));
arasuperobject.biblemap.put("b28_13_8", new arasuperobject(28,13,8,"اصدمهم كدبة مثكل واشق شغاف قلبهم وآكلهم هناك كلبوة يمزقهم وحش البرية"));
arasuperobject.biblemap.put("b28_13_9", new arasuperobject(28,13,9,"هلاكك يا اسرائيل أنّك عليّ على عونك"));
arasuperobject.biblemap.put("b28_13_10", new arasuperobject(28,13,10,"فاين هو ملكك حتى يخلصك في جميع مدنك وقضاتك حيث قلت اعطني ملكا ورؤساء"));
arasuperobject.biblemap.put("b28_13_11", new arasuperobject(28,13,11,"انا اعطيتك ملكا بغضبي واخذته بسخطي"));
arasuperobject.biblemap.put("b28_13_12", new arasuperobject(28,13,12,"اثم افرايم مصرور. خطيته مكنوزة"));
arasuperobject.biblemap.put("b28_13_13", new arasuperobject(28,13,13,"مخاض الوالدة يأتي عليه. هو ابن غير حكيم اذ لم يقف في الوقت في مولد البنين"));
arasuperobject.biblemap.put("b28_13_14", new arasuperobject(28,13,14,"من يد الهاوية افديهم من الموت اخلصهم. اين اوباؤك يا موت اين شوكتك يا هاوية. تختفي الندامة عن عينيّ"));
arasuperobject.biblemap.put("b28_13_15", new arasuperobject(28,13,15,"وان كان مثمرا بين اخوة تاتي ريح شرقية ريح الرب طالعة من القفر فتجف عينه وييبس ينبوعه. هي تنهب كنز كل متاع شهي"));
arasuperobject.biblemap.put("b28_13_16", new arasuperobject(28,13,16,"تجازى السامرة لانها قد تمردت على الهها. بالسيف يسقطون. تحطم اطفالهم والحوامل تشقّ"));
arasuperobject.biblemap.put("b28_14_1", new arasuperobject(28,14,1,"ارجع يا اسرائيل الى الرب الهك لانك قد تعثرت باثمك"));
arasuperobject.biblemap.put("b28_14_2", new arasuperobject(28,14,2,"خذوا معكم كلاما وارجعوا الى الرب. قولوا له ارفع كل اثم واقبل حسنا فنقدم عجول شفاهنا"));
arasuperobject.biblemap.put("b28_14_3", new arasuperobject(28,14,3,"لا يخلّصنا اشور. لا نركب على الخيل ولا نقول ايضا لعمل ايدينا آلهتنا. انه بك يرحم اليتيم"));
arasuperobject.biblemap.put("b28_14_4", new arasuperobject(28,14,4,"انا اشفي ارتدادهم. احبهم فضلا لان غضبي قد ارتد عنه"));
arasuperobject.biblemap.put("b28_14_5", new arasuperobject(28,14,5,"اكون لاسرائيل كالندى. يزهر كالسوسن ويضرب اصوله كلبنان"));
arasuperobject.biblemap.put("b28_14_6", new arasuperobject(28,14,6,"تمتد خراعيبه ويكون بهاؤه كالزيتونة وله رائحة كلبنان"));
arasuperobject.biblemap.put("b28_14_7", new arasuperobject(28,14,7,"يعود الساكنون في ظله يحيون حنطة ويزهرون كجفنة. يكون ذكرهم كخمر لبنان"));
arasuperobject.biblemap.put("b28_14_8", new arasuperobject(28,14,8,"يقول افرايم ما لي ايضا وللاصنام. انا قد اجبت فالاحظه. انا كسروة خضراء. من قبلي يوجد ثمرك"));
arasuperobject.biblemap.put("b28_14_9", new arasuperobject(28,14,9,"من هو حكيم حتى يفهم هذه الأمور وفهيم حتى يعرفها. فان طرق الرب مستقيمة والابرار يسلكون فيها. واما المنافقون فيعثرون فيها"));

}

}