package ara.bible;

public class arabible49 {

public arabible49() {

putmapbible49();

}

private void putmapbible49() {

arasuperobject.biblemap.put("b49_1_1", new arasuperobject(49,1,1,"بولس رسول يسوع المسيح بمشيئة الله الى القديسين الذين في افسس والمؤمنون في المسيح يسوع"));
arasuperobject.biblemap.put("b49_1_2", new arasuperobject(49,1,2,"نعمة لكم وسلام من الله ابينا والرب يسوع المسيح"));
arasuperobject.biblemap.put("b49_1_3", new arasuperobject(49,1,3,"مبارك الله ابو ربنا يسوع المسيح الذي باركنا بكل بركة روحية في السماويات في المسيح"));
arasuperobject.biblemap.put("b49_1_4", new arasuperobject(49,1,4,"كما اختارنا فيه قبل تأسيس العالم لنكون قديسين وبلا لوم قدامه في المحبة"));
arasuperobject.biblemap.put("b49_1_5", new arasuperobject(49,1,5,"اذ سبق فعيّننا للتبني بيسوع المسيح لنفسه حسب مسرة مشيئته"));
arasuperobject.biblemap.put("b49_1_6", new arasuperobject(49,1,6,"لمدح مجد نعمته التي انعم بها علينا في المحبوب"));
arasuperobject.biblemap.put("b49_1_7", new arasuperobject(49,1,7,"الذي فيه لنا الفداء بدمه غفران الخطايا حسب غنى نعمته"));
arasuperobject.biblemap.put("b49_1_8", new arasuperobject(49,1,8,"التي اجزلها لنا بكل حكمة وفطنة"));
arasuperobject.biblemap.put("b49_1_9", new arasuperobject(49,1,9,"اذ عرّفنا بسر مشيئته حسب مسرته التي قصدها في نفسه"));
arasuperobject.biblemap.put("b49_1_10", new arasuperobject(49,1,10,"لتدبير ملء الازمنة ليجمع كل شيء في المسيح ما في السموات وما على الارض في ذاك"));
arasuperobject.biblemap.put("b49_1_11", new arasuperobject(49,1,11,"الذي فيه ايضا نلنا نصيبا معيّنين سابقا حسب قصد الذي يعمل كل شيء حسب رأي مشيئته"));
arasuperobject.biblemap.put("b49_1_12", new arasuperobject(49,1,12,"لنكون لمدح مجده نحن الذين قد سبق رجاؤنا في المسيح"));
arasuperobject.biblemap.put("b49_1_13", new arasuperobject(49,1,13,"الذي فيه ايضا انتم اذ سمعتم كلمة الحق انجيل خلاصكم الذي فيه ايضا اذ آمنتم ختمتم بروح الموعد القدوس"));
arasuperobject.biblemap.put("b49_1_14", new arasuperobject(49,1,14,"الذي هو عربون ميراثنا لفداء المقتنى لمدح مجده"));
arasuperobject.biblemap.put("b49_1_15", new arasuperobject(49,1,15,"لذلك انا ايضا اذ قد سمعت بايمانكم بالرب يسوع ومحبتكم نحو جميع القديسين"));
arasuperobject.biblemap.put("b49_1_16", new arasuperobject(49,1,16,"لا ازال شاكرا لاجلكم ذاكرا اياكم في صلواتي"));
arasuperobject.biblemap.put("b49_1_17", new arasuperobject(49,1,17,"كي يعطيكم اله ربنا يسوع المسيح ابو المجد روح الحكمة والاعلان في معرفته"));
arasuperobject.biblemap.put("b49_1_18", new arasuperobject(49,1,18,"مستنيرة عيون اذهانكم لتعلموا ما هو رجاء دعوته وما هو غنى مجد ميراثه في القديسين"));
arasuperobject.biblemap.put("b49_1_19", new arasuperobject(49,1,19,"وما هي عظمة قدرته الفائقة نحونا نحن المؤمنين حسب عمل شدة قوته"));
arasuperobject.biblemap.put("b49_1_20", new arasuperobject(49,1,20,"الذي عمله في المسيح اذ اقامه من الاموات واجلسه عن يمينه في السماويات"));
arasuperobject.biblemap.put("b49_1_21", new arasuperobject(49,1,21,"فوق كل رياسة وسلطان وقوة وسيادة وكل اسم يسمى ليس في هذا الدهر فقط بل في المستقبل ايضا"));
arasuperobject.biblemap.put("b49_1_22", new arasuperobject(49,1,22,"واخضع كل شيء تحت قدميه واياه جعل راسا فوق كل شيء للكنيسة"));
arasuperobject.biblemap.put("b49_1_23", new arasuperobject(49,1,23,"التي هي جسده ملء الذي يملأ الكل في الكل"));
arasuperobject.biblemap.put("b49_2_1", new arasuperobject(49,2,1,"وانتم اذ كنتم امواتا بالذنوب والخطايا"));
arasuperobject.biblemap.put("b49_2_2", new arasuperobject(49,2,2,"التي سلكتم فيها قبلا حسب دهر هذا العالم حسب رئيس سلطان الهواء الروح الذي يعمل الآن في ابناء المعصية"));
arasuperobject.biblemap.put("b49_2_3", new arasuperobject(49,2,3,"الذين نحن ايضا جميعا تصرفنا قبلا بينهم في شهوات جسدنا عاملين مشيئات الجسد والافكار وكنا بالطبيعة ابناء الغضب كالباقين ايضا"));
arasuperobject.biblemap.put("b49_2_4", new arasuperobject(49,2,4,"الله الذي هو غني في الرحمة من اجل محبته الكثيرة التي احبنا بها"));
arasuperobject.biblemap.put("b49_2_5", new arasuperobject(49,2,5,"ونحن اموات بالخطايا احيانا مع المسيح. بالنعمة انتم مخلّصون"));
arasuperobject.biblemap.put("b49_2_6", new arasuperobject(49,2,6,"واقامنا معه واجلسنا معه في السماويات في المسيح يسوع"));
arasuperobject.biblemap.put("b49_2_7", new arasuperobject(49,2,7,"ليظهر في الدهور الآتية غنى نعمته الفائق باللطف علينا في المسيح يسوع"));
arasuperobject.biblemap.put("b49_2_8", new arasuperobject(49,2,8,"لانكم بالنعمة مخلّصون بالايمان وذلك ليس منكم. هو عطية الله"));
arasuperobject.biblemap.put("b49_2_9", new arasuperobject(49,2,9,"ليس من اعمال كي لا يفتخر احد"));
arasuperobject.biblemap.put("b49_2_10", new arasuperobject(49,2,10,"لاننا نحن عمله مخلوقين في المسيح يسوع لاعمال صالحة قد سبق الله فاعدها لكي نسلك فيها"));
arasuperobject.biblemap.put("b49_2_11", new arasuperobject(49,2,11,"لذلك اذكروا انكم انتم الامم قبلا في الجسد المدعوين غرلة من المدعو ختانا مصنوعا باليد في الجسد"));
arasuperobject.biblemap.put("b49_2_12", new arasuperobject(49,2,12,"انكم كنتم في ذلك الوقت بدون مسيح اجنبيين عن رعوية اسرائيل وغرباء عن عهود الموعد لا رجاء لكم وبلا اله في العالم"));
arasuperobject.biblemap.put("b49_2_13", new arasuperobject(49,2,13,"ولكن الآن في المسيح يسوع انتم الذين كنتم قبلا بعيدين صرتم قريبين بدم المسيح"));
arasuperobject.biblemap.put("b49_2_14", new arasuperobject(49,2,14,"لانه هو سلامنا الذي جعل الاثنين واحدا ونقض حائط السياج المتوسط"));
arasuperobject.biblemap.put("b49_2_15", new arasuperobject(49,2,15,"اي العداوة. مبطلا بجسده ناموس الوصايا في فرائض لكي يخلق الاثنين في نفسه انسانا واحدا جديدا صانعا سلاما"));
arasuperobject.biblemap.put("b49_2_16", new arasuperobject(49,2,16,"ويصالح الاثنين في جسد واحد مع الله بالصليب قاتلا العداوة به"));
arasuperobject.biblemap.put("b49_2_17", new arasuperobject(49,2,17,"فجاء وبشركم بسلام انتم البعيدين والقريبين"));
arasuperobject.biblemap.put("b49_2_18", new arasuperobject(49,2,18,"لان به لنا كلينا قدوما في روح واحد الى الآب"));
arasuperobject.biblemap.put("b49_2_19", new arasuperobject(49,2,19,"فلستم اذا بعد غرباء ونزلا بل رعية مع القديسين واهل بيت الله"));
arasuperobject.biblemap.put("b49_2_20", new arasuperobject(49,2,20,"مبنيين على اساس الرسل والانبياء ويسوع المسيح نفسه حجر الزاوية"));
arasuperobject.biblemap.put("b49_2_21", new arasuperobject(49,2,21,"الذي فيه كل البناء مركبا معا ينمو هيكلا مقدسا في الرب"));
arasuperobject.biblemap.put("b49_2_22", new arasuperobject(49,2,22,"الذي فيه انتم ايضا مبنيون معا مسكنا للّه في الروح"));
arasuperobject.biblemap.put("b49_3_1", new arasuperobject(49,3,1,"بسبب هذا انا بولس اسير المسيح يسوع لاجلكم ايها الامم"));
arasuperobject.biblemap.put("b49_3_2", new arasuperobject(49,3,2,"ان كنتم قد سمعتم بتدبير نعمة الله المعطاة لي لاجلكم"));
arasuperobject.biblemap.put("b49_3_3", new arasuperobject(49,3,3,"انه باعلان عرّفني بالسر. كما سبقت فكتبت بالايجاز"));
arasuperobject.biblemap.put("b49_3_4", new arasuperobject(49,3,4,"الذي بحسبه حينما تقرأونه تقدرون ان تفهموا درايتي بسر المسيح"));
arasuperobject.biblemap.put("b49_3_5", new arasuperobject(49,3,5,"الذي في اجيال أخر لم يعرف به بنو البشر كما قد أعلن الآن لرسله القديسين وانبيائه بالروح"));
arasuperobject.biblemap.put("b49_3_6", new arasuperobject(49,3,6,"ان الامم شركاء في الميراث والجسد ونوال موعده في المسيح بالانجيل"));
arasuperobject.biblemap.put("b49_3_7", new arasuperobject(49,3,7,"الذي صرت انا خادما له حسب موهبة نعمة الله المعطاة لي حسب فعل قوته"));
arasuperobject.biblemap.put("b49_3_8", new arasuperobject(49,3,8,"لي انا اصغر جميع القديسين أعطيت هذه النعمة ان ابشر بين الامم بغنى المسيح الذي لا يستقصى"));
arasuperobject.biblemap.put("b49_3_9", new arasuperobject(49,3,9,"وانير الجميع في ما هو شركة السر المكتوم منذ الدهور في الله خالق الجميع بيسوع المسيح"));
arasuperobject.biblemap.put("b49_3_10", new arasuperobject(49,3,10,"لكي يعرّف الآن عند الرؤساء والسلاطين في السماويات بواسطة الكنيسة بحكمة الله المتنوعة"));
arasuperobject.biblemap.put("b49_3_11", new arasuperobject(49,3,11,"حسب قصد الدهور الذي صنعه في المسيح يسوع ربنا"));
arasuperobject.biblemap.put("b49_3_12", new arasuperobject(49,3,12,"الذي به لنا جراءة وقدوم بايمانه عن ثقة"));
arasuperobject.biblemap.put("b49_3_13", new arasuperobject(49,3,13,"لذلك اطلب ان لا تكلّوا في شدائدي لاجلكم التي هي مجدكم"));
arasuperobject.biblemap.put("b49_3_14", new arasuperobject(49,3,14,"بسبب هذا احني ركبتيّ لدى ابي ربنا يسوع المسيح"));
arasuperobject.biblemap.put("b49_3_15", new arasuperobject(49,3,15,"الذي منه تسمى كل عشيرة في السموات وعلى الارض"));
arasuperobject.biblemap.put("b49_3_16", new arasuperobject(49,3,16,"لكي يعطيكم بحسب غنى مجده ان تتأيدوا بالقوة بروحه في الانسان الباطن"));
arasuperobject.biblemap.put("b49_3_17", new arasuperobject(49,3,17,"ليحل المسيح بالايمان في قلوبكم"));
arasuperobject.biblemap.put("b49_3_18", new arasuperobject(49,3,18,"وانتم متأصلون ومتأسسون في المحبة حتى تستطيعوا ان تدركوا مع جميع القديسين ما هو العرض والطول والعمق والعلو"));
arasuperobject.biblemap.put("b49_3_19", new arasuperobject(49,3,19,"وتعرفوا محبة المسيح الفائقة المعرفة لكي تمتلئوا الى كل ملء الله"));
arasuperobject.biblemap.put("b49_3_20", new arasuperobject(49,3,20,"والقادر ان يفعل فوق كل شيء اكثر جدا مما نطلب او نفتكر بحسب القوة التي تعمل فينا"));
arasuperobject.biblemap.put("b49_3_21", new arasuperobject(49,3,21,"له المجد في الكنيسة في المسيح يسوع الى جميع اجيال دهر الدهور. آمين"));
arasuperobject.biblemap.put("b49_4_1", new arasuperobject(49,4,1,"فاطلب اليكم انا الاسير في الرب ان تسلكوا كما يحق للدعوة التي دعيتم بها"));
arasuperobject.biblemap.put("b49_4_2", new arasuperobject(49,4,2,"بكل تواضع ووداعة وبطول اناة محتملين بعضكم بعضا في المحبة"));
arasuperobject.biblemap.put("b49_4_3", new arasuperobject(49,4,3,"مجتهدين ان تحفظوا وحدانية الروح برباط السلام"));
arasuperobject.biblemap.put("b49_4_4", new arasuperobject(49,4,4,"جسد واحد وروح واحد كما دعيتم ايضا في رجاء دعوتكم الواحد"));
arasuperobject.biblemap.put("b49_4_5", new arasuperobject(49,4,5,"رب واحد ايمان واحد معمودية واحدة"));
arasuperobject.biblemap.put("b49_4_6", new arasuperobject(49,4,6,"اله وآب واحد للكل الذي على الكل وبالكل وفي كلكم"));
arasuperobject.biblemap.put("b49_4_7", new arasuperobject(49,4,7,"ولكن لكل واحد منا اعطيت النعمة حسب قياس هبة المسيح"));
arasuperobject.biblemap.put("b49_4_8", new arasuperobject(49,4,8,"لذلك يقول. اذ صعد الى العلاء سبى سبيا واعطى الناس عطايا"));
arasuperobject.biblemap.put("b49_4_9", new arasuperobject(49,4,9,"واما انه صعد فما هو الا انه نزل ايضا اولا الى اقسام الارض السفلى"));
arasuperobject.biblemap.put("b49_4_10", new arasuperobject(49,4,10,"الذي نزل هو الذي صعد ايضا فوق جميع السموات لكي يملأ الكل"));
arasuperobject.biblemap.put("b49_4_11", new arasuperobject(49,4,11,"وهو اعطى البعض ان يكونوا رسلا والبعض انبياء والبعض مبشرين والبعض رعاة ومعلّمين"));
arasuperobject.biblemap.put("b49_4_12", new arasuperobject(49,4,12,"لاجل تكميل القديسين لعمل الخدمة لبنيان جسد المسيح"));
arasuperobject.biblemap.put("b49_4_13", new arasuperobject(49,4,13,"الى ان ننتهي جميعنا الى وحدانية الايمان ومعرفة ابن الله. الى انسان كامل. الى قياس قامة ملء المسيح"));
arasuperobject.biblemap.put("b49_4_14", new arasuperobject(49,4,14,"كي لا نكون فيما بعد اطفالا مضطربين ومحمولين بكل ريح تعليم بحيلة الناس بمكر الى مكيدة الضلال"));
arasuperobject.biblemap.put("b49_4_15", new arasuperobject(49,4,15,"بل صادقين في المحبة ننمو في كل شيء الى ذاك الذي هو الراس المسيح"));
arasuperobject.biblemap.put("b49_4_16", new arasuperobject(49,4,16,"الذي منه كل الجسد مركبا معا ومقترنا بموازرة كل مفصل حسب عمل على قياس كل جزء يحصّل نمو الجسد لبنيانه في المحبة"));
arasuperobject.biblemap.put("b49_4_17", new arasuperobject(49,4,17,"فاقول هذا واشهد في الرب ان لا تسلكوا في ما بعد كما يسلك سائر الامم ايضا ببطل ذهنهم"));
arasuperobject.biblemap.put("b49_4_18", new arasuperobject(49,4,18,"اذ هم مظلمو الفكر ومتجنبون عن حياة الله لسبب الجهل الذي فيهم بسبب غلاظة قلوبهم"));
arasuperobject.biblemap.put("b49_4_19", new arasuperobject(49,4,19,"الذين اذ هم قد فقدوا الحس اسلموا نفوسهم للدعارة ليعملوا كل نجاسة في الطمع"));
arasuperobject.biblemap.put("b49_4_20", new arasuperobject(49,4,20,"واما انتم فلم تتعلّموا المسيح هكذا"));
arasuperobject.biblemap.put("b49_4_21", new arasuperobject(49,4,21,"ان كنتم قد سمعتموه وعلمتم فيه كما هو حق في يسوع"));
arasuperobject.biblemap.put("b49_4_22", new arasuperobject(49,4,22,"ان تخلعوا من جهة التصرف السابق الانسان العتيق الفاسد بحسب شهوات الغرور"));
arasuperobject.biblemap.put("b49_4_23", new arasuperobject(49,4,23,"وتتجددوا بروح ذهنكم"));
arasuperobject.biblemap.put("b49_4_24", new arasuperobject(49,4,24,"وتلبسوا الانسان الجديد المخلوق بحسب الله في البر وقداسة الحق"));
arasuperobject.biblemap.put("b49_4_25", new arasuperobject(49,4,25,"لذلك اطرحوا عنكم الكذب وتكلموا بالصدق كل واحد مع قريبه. لاننا بعضنا اعضاء البعض"));
arasuperobject.biblemap.put("b49_4_26", new arasuperobject(49,4,26,"اغضبوا ولا تخطئوا. لا تغرب الشمس على غيظكم"));
arasuperobject.biblemap.put("b49_4_27", new arasuperobject(49,4,27,"ولا تعطوا ابليس مكانا"));
arasuperobject.biblemap.put("b49_4_28", new arasuperobject(49,4,28,"لا يسرق السارق في ما بعد بل بالحري يتعب عاملا الصالح بيديه ليكون له ان يعطي من له احتياج"));
arasuperobject.biblemap.put("b49_4_29", new arasuperobject(49,4,29,"لا تخرج كلمة رديّة من افواهكم بل كل ما كان صالحا للبنيان حسب الحاجة كي يعطي نعمة للسامعين"));
arasuperobject.biblemap.put("b49_4_30", new arasuperobject(49,4,30,"ولا تحزنوا روح الله القدوس الذي به ختمتم ليوم الفداء"));
arasuperobject.biblemap.put("b49_4_31", new arasuperobject(49,4,31,"ليرفع من بينكم كل مرارة وسخط وغضب وصياح وتجديف مع كل خبث"));
arasuperobject.biblemap.put("b49_4_32", new arasuperobject(49,4,32,"وكونوا لطفاء بعضكم نحو بعض شفوقين متسامحين كما سامحكم الله ايضا في المسيح"));
arasuperobject.biblemap.put("b49_5_1", new arasuperobject(49,5,1,"فكونوا متمثلين بالله كاولاد احباء"));
arasuperobject.biblemap.put("b49_5_2", new arasuperobject(49,5,2,"واسلكوا في المحبة كما احبنا المسيح ايضا واسلم نفسه لاجلنا قربانا وذبيحة للّه رائحة طيبة"));
arasuperobject.biblemap.put("b49_5_3", new arasuperobject(49,5,3,"واما الزنى وكل نجاسة او طمع فلا يسمّ بينكم كما يليق بقديسين"));
arasuperobject.biblemap.put("b49_5_4", new arasuperobject(49,5,4,"ولا القباحة ولا كلام السفاهة والهزل التي لا تليق بل بالحري الشكر"));
arasuperobject.biblemap.put("b49_5_5", new arasuperobject(49,5,5,"فانكم تعلمون هذا ان كل زان او نجس او طماع الذي هو عابد للاوثان ليس له ميراث في ملكوت المسيح والله"));
arasuperobject.biblemap.put("b49_5_6", new arasuperobject(49,5,6,"لا يغركم احد بكلام باطل لانه بسبب هذه الامور يأتي غضب الله على ابناء المعصية"));
arasuperobject.biblemap.put("b49_5_7", new arasuperobject(49,5,7,"فلا تكونوا شركاءهم"));
arasuperobject.biblemap.put("b49_5_8", new arasuperobject(49,5,8,"لانكم كنتم قبلا ظلمة واما الآن فنور في الرب. اسلكوا كاولاد نور"));
arasuperobject.biblemap.put("b49_5_9", new arasuperobject(49,5,9,"لان ثمر الروح هو في كل صلاح وبر وحق"));
arasuperobject.biblemap.put("b49_5_10", new arasuperobject(49,5,10,"مختبرين ما هو مرضي عند الرب"));
arasuperobject.biblemap.put("b49_5_11", new arasuperobject(49,5,11,"ولا تشتركوا في اعمال الظلمة غير المثمرة بل بالحري وبخوها"));
arasuperobject.biblemap.put("b49_5_12", new arasuperobject(49,5,12,"لان الامور الحادثة منهم سرّا ذكرها ايضا قبيح"));
arasuperobject.biblemap.put("b49_5_13", new arasuperobject(49,5,13,"ولكن الكل اذا توبخ يظهر بالنور. لان كل ما اظهر فهو نور"));
arasuperobject.biblemap.put("b49_5_14", new arasuperobject(49,5,14,"لذلك يقول استيقظ ايها النائم وقم من الاموات فيضيء لك المسيح"));
arasuperobject.biblemap.put("b49_5_15", new arasuperobject(49,5,15,"فانظروا كيف تسلكون بالتدقيق لا كجهلاء بل كحكماء"));
arasuperobject.biblemap.put("b49_5_16", new arasuperobject(49,5,16,"مفتدين الوقت لان الايام شريرة"));
arasuperobject.biblemap.put("b49_5_17", new arasuperobject(49,5,17,"من اجل ذلك لا تكونوا اغبياء بل فاهمين ما هي مشيئة الرب"));
arasuperobject.biblemap.put("b49_5_18", new arasuperobject(49,5,18,"ولا تسكروا بالخمر الذي فيه الخلاعة بل امتلئوا بالروح"));
arasuperobject.biblemap.put("b49_5_19", new arasuperobject(49,5,19,"مكلمين بعضكم بعضا بمزامير وتسابيح واغاني روحية مترنمين ومرتلين في قلوبكم للرب"));
arasuperobject.biblemap.put("b49_5_20", new arasuperobject(49,5,20,"شاكرين كل حين على كل شيء في اسم ربنا يسوع المسيح للّه والآب"));
arasuperobject.biblemap.put("b49_5_21", new arasuperobject(49,5,21,"خاضعين بعضكم لبعض في خوف الله"));
arasuperobject.biblemap.put("b49_5_22", new arasuperobject(49,5,22,"ايها النساء اخضعن لرجالكنّ كما للرب"));
arasuperobject.biblemap.put("b49_5_23", new arasuperobject(49,5,23,"لان الرجل هو راس المرأة كما ان المسيح ايضا راس الكنيسة. وهو مخلّص الجسد"));
arasuperobject.biblemap.put("b49_5_24", new arasuperobject(49,5,24,"ولكن كما تخضع الكنيسة للمسيح كذلك النساء لرجالهنّ في كل شيء"));
arasuperobject.biblemap.put("b49_5_25", new arasuperobject(49,5,25,"ايها الرجال احبوا نساءكم كما احب المسيح ايضا الكنيسة واسلم نفسه لاجلها"));
arasuperobject.biblemap.put("b49_5_26", new arasuperobject(49,5,26,"لكي يقدسها مطهرا اياها بغسل الماء بالكلمة"));
arasuperobject.biblemap.put("b49_5_27", new arasuperobject(49,5,27,"لكي يحضرها لنفسه كنيسة مجيدة لا دنس فيها ولا غضن او شيء من مثل ذلك بل تكون مقدسة وبلا عيب"));
arasuperobject.biblemap.put("b49_5_28", new arasuperobject(49,5,28,"كذلك يجب على الرجال ان يحبوا نساءهم كاجسادهم. من يحب امرأته يحب نفسه"));
arasuperobject.biblemap.put("b49_5_29", new arasuperobject(49,5,29,"فانه لم يبغض احد جسده قط بل يقوته ويربيه كما الرب ايضا للكنيسة"));
arasuperobject.biblemap.put("b49_5_30", new arasuperobject(49,5,30,"لاننا اعضاء جسمه من لحمه ومن عظامه"));
arasuperobject.biblemap.put("b49_5_31", new arasuperobject(49,5,31,"من اجل هذا يترك الرجل اباه وامه ويلتصق بامرأته ويكون الاثنان جسدا واحدا"));
arasuperobject.biblemap.put("b49_5_32", new arasuperobject(49,5,32,"هذا السر عظيم ولكنني انا اقول من نحو المسيح والكنيسة"));
arasuperobject.biblemap.put("b49_5_33", new arasuperobject(49,5,33,"واما انتم الافراد فليحب كل واحد امرأته هكذا كنفسه واما المرأة فلتهب رجلها"));
arasuperobject.biblemap.put("b49_6_1", new arasuperobject(49,6,1,"ايها الاولاد اطيعوا والديكم في الرب لان هذا حق"));
arasuperobject.biblemap.put("b49_6_2", new arasuperobject(49,6,2,"اكرم اباك وامك. التي هي اول وصية بوعد"));
arasuperobject.biblemap.put("b49_6_3", new arasuperobject(49,6,3,"لكي يكون لكم خير وتكونوا طوال الاعمار على الارض"));
arasuperobject.biblemap.put("b49_6_4", new arasuperobject(49,6,4,"وانتم ايها الآباء لا تغيظوا اولادكم بل ربوهم بتأديب الرب وانذاره"));
arasuperobject.biblemap.put("b49_6_5", new arasuperobject(49,6,5,"ايها العبيد اطيعوا سادتكم حسب الجسد بخوف ورعدة في بساطة قلوبكم كما للمسيح"));
arasuperobject.biblemap.put("b49_6_6", new arasuperobject(49,6,6,"لا بخدمة العين كمن يرضي الناس بل كعبيد المسيح عاملين مشيئة الله من القلب"));
arasuperobject.biblemap.put("b49_6_7", new arasuperobject(49,6,7,"خادمين بنيّة صالحة كما للرب ليس للناس"));
arasuperobject.biblemap.put("b49_6_8", new arasuperobject(49,6,8,"عالمين ان مهما عمل كل واحد من الخير فذلك يناله من الرب عبدا كان ام حرا"));
arasuperobject.biblemap.put("b49_6_9", new arasuperobject(49,6,9,"وانتم ايها السادة افعلوا لهم هذه الامور تاركين التهديد عالمين ان سيدكم انتم ايضا في السموات وليس عنده محاباة"));
arasuperobject.biblemap.put("b49_6_10", new arasuperobject(49,6,10,"اخيرا يا اخوتي تقووا في الرب وفي شدة قوته"));
arasuperobject.biblemap.put("b49_6_11", new arasuperobject(49,6,11,"البسوا سلاح الله الكامل لكي تقدروا ان تثبتوا ضد مكايد ابليس"));
arasuperobject.biblemap.put("b49_6_12", new arasuperobject(49,6,12,"فان مصارعتنا ليست مع دم ولحم بل مع الرؤساء مع السلاطين مع ولاة العالم على ظلمة هذا الدهر مع اجناد الشر الروحية في السماويات"));
arasuperobject.biblemap.put("b49_6_13", new arasuperobject(49,6,13,"من اجل ذلك احملوا سلاح الله الكامل لكي تقدروا ان تقاوموا في اليوم الشرير وبعد ان تتمموا كل شيء ان تثبتوا"));
arasuperobject.biblemap.put("b49_6_14", new arasuperobject(49,6,14,"فاثبتوا ممنطقين احقاءكم بالحق ولابسين درع البر"));
arasuperobject.biblemap.put("b49_6_15", new arasuperobject(49,6,15,"وحاذين ارجلكم باستعداد انجيل السلام"));
arasuperobject.biblemap.put("b49_6_16", new arasuperobject(49,6,16,"حاملين فوق الكل ترس الايمان الذي به تقدرون ان تطفئوا جميع سهام الشرير الملتهبة"));
arasuperobject.biblemap.put("b49_6_17", new arasuperobject(49,6,17,"وخذوا خوذة الخلاص وسيف الروح الذي هو كلمة الله"));
arasuperobject.biblemap.put("b49_6_18", new arasuperobject(49,6,18,"مصلّين بكل صلاة وطلبة كل وقت في الروح وساهرين لهذا بعينه بكل مواظبة وطلبة لاجل جميع القديسين"));
arasuperobject.biblemap.put("b49_6_19", new arasuperobject(49,6,19,"ولاجلي لكي يعطى لي كلام عند افتتاح فمي لاعلم جهارا بسر الانجيل"));
arasuperobject.biblemap.put("b49_6_20", new arasuperobject(49,6,20,"الذي لاجله انا سفير في سلاسل. لكي اجاهر فيه كما يجب ان اتكلم"));
arasuperobject.biblemap.put("b49_6_21", new arasuperobject(49,6,21,"ولكن لكي تعلموا انتم ايضا احوالي ماذا افعل يعرّفكم بكل شيء تيخيكس الاخ الحبيب والخادم الامين في الرب"));
arasuperobject.biblemap.put("b49_6_22", new arasuperobject(49,6,22,"الذي ارسلته اليكم لهذا بعينه لكي تعلموا احوالنا ولكي يعزي قلوبكم"));
arasuperobject.biblemap.put("b49_6_23", new arasuperobject(49,6,23,"سلام على الاخوة ومحبة بايمان من الله الآب والرب يسوع المسيح"));
arasuperobject.biblemap.put("b49_6_24", new arasuperobject(49,6,24,"النعمة مع جميع الذين يحبون ربنا يسوع المسيح في عدم فساد. آمين. كتبت الى اهل افسس من رومية على يد تيخيكس"));

}

}