package ara.bible;

public class arabible48 {

public arabible48() {

putmapbible48();

}

private void putmapbible48() {

arasuperobject.biblemap.put("b48_1_1", new arasuperobject(48,1,1,"بولس رسول لا من الناس ولا بانسان بل بيسوع المسيح والله الآب الذي اقامه من الاموات"));
arasuperobject.biblemap.put("b48_1_2", new arasuperobject(48,1,2,"وجميع الاخوة الذين معي الى كنائس غلاطية"));
arasuperobject.biblemap.put("b48_1_3", new arasuperobject(48,1,3,"نعمة لكم وسلام من الله الآب ومن ربنا يسوع المسيح"));
arasuperobject.biblemap.put("b48_1_4", new arasuperobject(48,1,4,"الذي بذل نفسه لاجل خطايانا لينقذنا من العالم الحاضر الشرير حسب ارادة الله وابينا"));
arasuperobject.biblemap.put("b48_1_5", new arasuperobject(48,1,5,"الذي له المجد الى ابد الآبدين. آمين"));
arasuperobject.biblemap.put("b48_1_6", new arasuperobject(48,1,6,"اني اتعجب انكم تنتقلون هكذا سريعا عن الذي دعاكم بنعمة المسيح الى انجيل آخر"));
arasuperobject.biblemap.put("b48_1_7", new arasuperobject(48,1,7,"ليس هو آخر غير انه يوجد قوم يزعجونكم ويريدون ان يحوّلوا انجيل المسيح"));
arasuperobject.biblemap.put("b48_1_8", new arasuperobject(48,1,8,"ولكن ان بشرناكم نحن او ملاك من السماء بغير ما بشرناكم فليكن اناثيما"));
arasuperobject.biblemap.put("b48_1_9", new arasuperobject(48,1,9,"كما سبقنا فقلنا اقول الآن ايضا ان كان احد يبشركم في غير ما قبلتم فليكن اناثيما"));
arasuperobject.biblemap.put("b48_1_10", new arasuperobject(48,1,10,"أفاستعطف الآن الناس ام الله. ام اطلب ان ارضي الناس. فلو كنت بعد ارضي الناس لم اكن عبدا للمسيح"));
arasuperobject.biblemap.put("b48_1_11", new arasuperobject(48,1,11,"واعرّفكم ايها الاخوة الانجيل الذي بشرت به انه ليس بحسب انسان"));
arasuperobject.biblemap.put("b48_1_12", new arasuperobject(48,1,12,"لاني لم اقبله من عند انسان ولا علّمته بل باعلان يسوع المسيح"));
arasuperobject.biblemap.put("b48_1_13", new arasuperobject(48,1,13,"فانكم سمعتم بسيرتي قبلا في الديانة اليهودية اني كنت اضطهد كنيسة الله بافراط واتلفها"));
arasuperobject.biblemap.put("b48_1_14", new arasuperobject(48,1,14,"وكنت اتقدم في الديانة اليهودية على كثيرين من اترابي في جنسي اذ كنت اوفر غيرة في تقليدات آبائي"));
arasuperobject.biblemap.put("b48_1_15", new arasuperobject(48,1,15,"ولكن لما سرّ الله الذي افرزني من بطن امي ودعاني بنعمته"));
arasuperobject.biblemap.put("b48_1_16", new arasuperobject(48,1,16,"ان يعلن ابنه فيّ لابشر به بين الامم للوقت لم استشر لحما ودما"));
arasuperobject.biblemap.put("b48_1_17", new arasuperobject(48,1,17,"ولا صعدت الى اورشليم الى الرسل الذين قبلي بل انطلقت الى العربية ثم رجعت ايضا الى دمشق"));
arasuperobject.biblemap.put("b48_1_18", new arasuperobject(48,1,18,"ثم بعد ثلاث سنين صعدت الى اورشليم لأتعرّف ببطرس فمكثت عنده خمسة عشر يوما"));
arasuperobject.biblemap.put("b48_1_19", new arasuperobject(48,1,19,"ولكنني لم ار غيره من الرسل الا يعقوب اخا الرب"));
arasuperobject.biblemap.put("b48_1_20", new arasuperobject(48,1,20,"والذي اكتب به اليكم هوذا قدّام الله اني لست اكذب فيه"));
arasuperobject.biblemap.put("b48_1_21", new arasuperobject(48,1,21,"وبعد ذلك جئت الى اقاليم سورية وكيليكية"));
arasuperobject.biblemap.put("b48_1_22", new arasuperobject(48,1,22,"ولكنني كنت غير معروف بالوجه عند كنائس اليهودية التي في المسيح"));
arasuperobject.biblemap.put("b48_1_23", new arasuperobject(48,1,23,"غير انهم كانوا يسمعون ان الذي كان يضطهدنا قبلا يبشر الآن بالايمان الذي كان قبلا يتلفه"));
arasuperobject.biblemap.put("b48_1_24", new arasuperobject(48,1,24,"فكانوا يمجدون الله فيّ"));
arasuperobject.biblemap.put("b48_2_1", new arasuperobject(48,2,1,"ثم بعد اربع عشرة سنة صعدت ايضا الى اورشليم مع برنابا آخذا معي تيطس ايضا"));
arasuperobject.biblemap.put("b48_2_2", new arasuperobject(48,2,2,"وانما صعدت بموجب اعلان وعرضت عليهم الانجيل الذي اكرز به بين الامم ولكن بالانفراد على المعتبرين لئلا اكون اسعى او قد سعيت باطلا"));
arasuperobject.biblemap.put("b48_2_3", new arasuperobject(48,2,3,"لكن لم يضطر ولا تيطس الذي كان معي وهو يوناني ان يختتن"));
arasuperobject.biblemap.put("b48_2_4", new arasuperobject(48,2,4,"ولكن بسبب الاخوة الكذبة المدخلين خفية الذين دخلوا اختلاسا ليتجسسوا حريتنا التي لنا في المسيح كي يستعبدونا"));
arasuperobject.biblemap.put("b48_2_5", new arasuperobject(48,2,5,"الذين لم نذعن لهم بالخضوع ولا ساعة ليبقى عندكم حق الانجيل"));
arasuperobject.biblemap.put("b48_2_6", new arasuperobject(48,2,6,"واما المعتبرون انهم شيء مهما كانوا لا فرق عندي. الله لا يأخذ بوجه انسان. فان هؤلاء المعتبرين لم يشيروا عليّ بشيء"));
arasuperobject.biblemap.put("b48_2_7", new arasuperobject(48,2,7,"بل بالعكس اذ رأوا اني اؤتمنت على انجيل الغرلة كما بطرس على انجيل الختان"));
arasuperobject.biblemap.put("b48_2_8", new arasuperobject(48,2,8,"فان الذي عمل في بطرس لرسالة الختان عمل فيّ ايضا للامم"));
arasuperobject.biblemap.put("b48_2_9", new arasuperobject(48,2,9,"فاذ علم بالنعمة المعطاة لي يعقوب وصفا ويوحنا المعتبرون انهم اعمدة اعطوني وبرنابا يمين الشركة لنكون نحن للامم واما هم فللختان"));
arasuperobject.biblemap.put("b48_2_10", new arasuperobject(48,2,10,"غير ان نذكر الفقراء. وهذا عينه كنت اعتنيت ان افعله"));
arasuperobject.biblemap.put("b48_2_11", new arasuperobject(48,2,11,"ولكن لما أتى بطرس الى انطاكية قاومته مواجهة لانه كان ملوما"));
arasuperobject.biblemap.put("b48_2_12", new arasuperobject(48,2,12,"لانه قبلما أتى قوم من عند يعقوب كان يأكل مع الامم ولكن لما أتوا كان يؤخر ويفرز نفسه خائفا من الذين هم من الختان"));
arasuperobject.biblemap.put("b48_2_13", new arasuperobject(48,2,13,"وراءى معه باقي اليهود ايضا حتى ان برنابا ايضا انقاد الى ريائهم"));
arasuperobject.biblemap.put("b48_2_14", new arasuperobject(48,2,14,"لكن لما رأيت انهم لا يسلكون باستقامة حسب حق الانجيل قلت لبطرس قدام الجميع ان كنت وانت يهودي تعيش امميا لا يهوديا فلماذا تلزم الامم ان يتهوّدوا"));
arasuperobject.biblemap.put("b48_2_15", new arasuperobject(48,2,15,"نحن بالطبيعة يهود ولسنا من الامم خطاة"));
arasuperobject.biblemap.put("b48_2_16", new arasuperobject(48,2,16,"اذ نعلم ان الانسان لا يتبرر باعمال الناموس بل بايمان يسوع المسيح آمنّا نحن ايضا بيسوع المسيح لنتبرر بايمان يسوع لا باعمال الناموس. لانه باعمال الناموس لا يتبرر جسد ما"));
arasuperobject.biblemap.put("b48_2_17", new arasuperobject(48,2,17,"فان كنا ونحن طالبون ان نتبرر في المسيح نوجد نحن انفسنا ايضا خطاة أفالمسيح خادم للخطية. حاشا"));
arasuperobject.biblemap.put("b48_2_18", new arasuperobject(48,2,18,"فاني ان كنت ابني ايضا هذا الذي قد هدمته فاني اظهر نفسي متعديا"));
arasuperobject.biblemap.put("b48_2_19", new arasuperobject(48,2,19,"لاني مت بالناموس للناموس لاحيا للّه"));
arasuperobject.biblemap.put("b48_2_20", new arasuperobject(48,2,20,"مع المسيح صلبت فاحيا لا انا بل المسيح يحيا فيّ. فما احياه الآن في الجسد فانما احياه في الايمان ايمان ابن الله الذي احبني واسلم نفسه لاجلي"));
arasuperobject.biblemap.put("b48_2_21", new arasuperobject(48,2,21,"لست ابطل نعمة الله. لانه ان كان بالناموس بر فالمسيح اذا مات بلا سبب"));
arasuperobject.biblemap.put("b48_3_1", new arasuperobject(48,3,1,"ايها الغلاطيون الاغبياء من رقاكم حتى لا تذعنوا للحق انتم الذين امام عيونكم قد رسم يسوع المسيح بينكم مصلوبا"));
arasuperobject.biblemap.put("b48_3_2", new arasuperobject(48,3,2,"اريد ان اتعلّم منكم هذا فقط أباعمال الناموس اخذتم الروح ام بخبر الايمان"));
arasuperobject.biblemap.put("b48_3_3", new arasuperobject(48,3,3,"أهكذا انتم اغبياء. أبعد ما أبتدأتم بالروح تكملون الآن بالجسد"));
arasuperobject.biblemap.put("b48_3_4", new arasuperobject(48,3,4,"أهذا المقدار احتملتم عبثا ان كان عبثا"));
arasuperobject.biblemap.put("b48_3_5", new arasuperobject(48,3,5,"فالذي يمنحكم الروح ويعمل قوات فيكم أباعمال الناموس ام بخبر الايمان"));
arasuperobject.biblemap.put("b48_3_6", new arasuperobject(48,3,6,"كما آمن ابراهيم بالله فحسب له برا"));
arasuperobject.biblemap.put("b48_3_7", new arasuperobject(48,3,7,"اعلموا اذا ان الذين هم من الايمان اولئك هم بنو ابراهيم"));
arasuperobject.biblemap.put("b48_3_8", new arasuperobject(48,3,8,"والكتاب اذ سبق فرأى ان الله بالايمان يبرر الامم سبق فبشر ابراهيم ان فيك تتبارك جميع الامم"));
arasuperobject.biblemap.put("b48_3_9", new arasuperobject(48,3,9,"اذا الذين هم من الايمان يتباركون مع ابراهيم المؤمن"));
arasuperobject.biblemap.put("b48_3_10", new arasuperobject(48,3,10,"لان جميع الذين هم من اعمال الناموس هم تحت لعنة لانه مكتوب ملعون كل من لا يثبت في جميع ما هو مكتوب في كتاب الناموس ليعمل به"));
arasuperobject.biblemap.put("b48_3_11", new arasuperobject(48,3,11,"ولكن ان ليس احد يتبرر بالناموس عند الله فظاهر لان البار بالايمان يحيا"));
arasuperobject.biblemap.put("b48_3_12", new arasuperobject(48,3,12,"ولكن الناموس ليس من الايمان بل الانسان الذي يفعلها سيحيا بها"));
arasuperobject.biblemap.put("b48_3_13", new arasuperobject(48,3,13,"المسيح افتدانا من لعنة الناموس اذ صار لعنة لاجلنا لانه مكتوب ملعون كل من علّق على خشبة"));
arasuperobject.biblemap.put("b48_3_14", new arasuperobject(48,3,14,"لتصير بركة ابراهيم للامم في المسيح يسوع لننال بالايمان موعد الروح"));
arasuperobject.biblemap.put("b48_3_15", new arasuperobject(48,3,15,"ايها الاخوة بحسب الانسان اقول ليس احد يبطّل عهدا قد تمكن ولو من انسان او يزيد عليه"));
arasuperobject.biblemap.put("b48_3_16", new arasuperobject(48,3,16,"واما المواعيد فقيلت في ابراهيم وفي نسله. لا يقول وفي الانسال كانه عن كثيرين بل كانه عن واحد وفي نسلك الذي هو المسيح"));
arasuperobject.biblemap.put("b48_3_17", new arasuperobject(48,3,17,"وانما اقول هذا ان الناموس الذي صار بعد اربع مئة وثلاثين سنة لا ينسخ عهدا قد سبق فتمكن من الله نحو المسيح حتى يبطّل الموعد"));
arasuperobject.biblemap.put("b48_3_18", new arasuperobject(48,3,18,"لانه ان كانت الوراثة من الناموس فلم تكن ايضا من موعد. ولكن الله وهبها لابراهيم بموعد"));
arasuperobject.biblemap.put("b48_3_19", new arasuperobject(48,3,19,"فلماذا الناموس. قد زيد بسبب التعديات الى ان يأتي النسل الذي قد وعد له مرتبا بملائكة في يد وسيط"));
arasuperobject.biblemap.put("b48_3_20", new arasuperobject(48,3,20,"واما الوسيط فلا يكون لواحد. ولكن الله واحد"));
arasuperobject.biblemap.put("b48_3_21", new arasuperobject(48,3,21,"فهل الناموس ضد مواعيد الله. حاشا. لانه لو أعطي ناموس قادر ان يحيي لكان بالحقيقة البر بالناموس"));
arasuperobject.biblemap.put("b48_3_22", new arasuperobject(48,3,22,"لكن الكتاب اغلق على الكل تحت الخطية ليعطى الموعد من ايمان يسوع المسيح للذين يؤمنون"));
arasuperobject.biblemap.put("b48_3_23", new arasuperobject(48,3,23,"ولكن قبلما جاء الايمان كنا محروسين تحت الناموس مغلقا علينا الى الايمان العتيد ان يعلن"));
arasuperobject.biblemap.put("b48_3_24", new arasuperobject(48,3,24,"اذا قد كان الناموس مؤدبنا الى المسيح لكي نتبرر بالايمان"));
arasuperobject.biblemap.put("b48_3_25", new arasuperobject(48,3,25,"ولكن بعد ما جاء الايمان لسنا بعد تحت مؤدب"));
arasuperobject.biblemap.put("b48_3_26", new arasuperobject(48,3,26,"لانكم جميعا ابناء الله بالايمان بالمسيح يسوع"));
arasuperobject.biblemap.put("b48_3_27", new arasuperobject(48,3,27,"لان كلكم الذين اعتمدتم بالمسيح قد لبستم المسيح"));
arasuperobject.biblemap.put("b48_3_28", new arasuperobject(48,3,28,"ليس يهودي ولا يوناني. ليس عبد ولا حر. ليس ذكر وانثى لانكم جميعا واحد في المسيح يسوع"));
arasuperobject.biblemap.put("b48_3_29", new arasuperobject(48,3,29,"فان كنتم للمسيح فانتم اذا نسل ابراهيم وحسب الموعد ورثة"));
arasuperobject.biblemap.put("b48_4_1", new arasuperobject(48,4,1,"وانما اقول ما دام الوارث قاصرا لا يفرق شيئا عن العبد مع كونه صاحب الجميع"));
arasuperobject.biblemap.put("b48_4_2", new arasuperobject(48,4,2,"بل هو تحت اوصياء ووكلاء الى الوقت المؤجل من ابيه"));
arasuperobject.biblemap.put("b48_4_3", new arasuperobject(48,4,3,"هكذا نحن ايضا لما كنا قاصرين كنا مستعبدين تحت اركان العالم"));
arasuperobject.biblemap.put("b48_4_4", new arasuperobject(48,4,4,"ولكن لما جاء ملء الزمان ارسل الله ابنه مولودا من امرأة مولودا تحت الناموس"));
arasuperobject.biblemap.put("b48_4_5", new arasuperobject(48,4,5,"ليفتدي الذين تحت الناموس لننال التبني"));
arasuperobject.biblemap.put("b48_4_6", new arasuperobject(48,4,6,"ثم بما انكم ابناء ارسل الله روح ابنه الى قلوبكم صارخا يا ابا الآب"));
arasuperobject.biblemap.put("b48_4_7", new arasuperobject(48,4,7,"اذا لست بعد عبدا بل ابنا وان كنت ابنا فوارث للّه بالمسيح"));
arasuperobject.biblemap.put("b48_4_8", new arasuperobject(48,4,8,"لكن حينئذ اذ كنتم لا تعرفون الله استعبدتم للذين ليسوا بالطبيعة آلهة"));
arasuperobject.biblemap.put("b48_4_9", new arasuperobject(48,4,9,"واما الآن اذ عرفتم الله بل بالحري عرفتم من الله فكيف ترجعون ايضا الى الاركان الضعيفة الفقيرة التي تريدون ان تستعبدوا لها من جديد"));
arasuperobject.biblemap.put("b48_4_10", new arasuperobject(48,4,10,"أتحفظون اياما وشهورا واوقاتا وسنين"));
arasuperobject.biblemap.put("b48_4_11", new arasuperobject(48,4,11,"اخاف عليكم ان اكون قد تعبت فيكم عبثا"));
arasuperobject.biblemap.put("b48_4_12", new arasuperobject(48,4,12,"اتضرع اليكم ايها الاخوة كونوا كما انا لاني انا ايضا كما انتم لم تظلموني شيئا"));
arasuperobject.biblemap.put("b48_4_13", new arasuperobject(48,4,13,"ولكنكم تعلمون اني بضعف الجسد بشرتكم في الاول"));
arasuperobject.biblemap.put("b48_4_14", new arasuperobject(48,4,14,"وتجربتي التي في جسدي لم تزدروا بها ولا كرهتموها بل كملاك من الله قبلتموني كالمسيح يسوع"));
arasuperobject.biblemap.put("b48_4_15", new arasuperobject(48,4,15,"فماذا كان اذا تطويبكم. لاني اشهد لكم انه لو امكن لقلعتم عيونكم واعطيتموني"));
arasuperobject.biblemap.put("b48_4_16", new arasuperobject(48,4,16,"أفقد صرت اذا عدوا لكم لاني اصدق لكم"));
arasuperobject.biblemap.put("b48_4_17", new arasuperobject(48,4,17,"يغارون لكم ليس حسنا بل يريدون ان يصدوكم لكي تغاروا لهم"));
arasuperobject.biblemap.put("b48_4_18", new arasuperobject(48,4,18,"حسنة هي الغيرة في الحسنى كل حين وليس حين حضوري عندكم فقط"));
arasuperobject.biblemap.put("b48_4_19", new arasuperobject(48,4,19,"يا اولادي الذين اتمخض بكم ايضا الى ان يتصور المسيح فيكم"));
arasuperobject.biblemap.put("b48_4_20", new arasuperobject(48,4,20,"ولكني كنت اريد ان اكون حاضرا عندكم الآن واغيّر صوتي لاني متحيّر فيكم"));
arasuperobject.biblemap.put("b48_4_21", new arasuperobject(48,4,21,"قولوا لي انتم الذين تريدون ان تكونوا تحت الناموس ألستم تسمعون الناموس"));
arasuperobject.biblemap.put("b48_4_22", new arasuperobject(48,4,22,"فانه مكتوب انه كان لابراهيم ابنان واحد من الجارية والآخر من الحرة"));
arasuperobject.biblemap.put("b48_4_23", new arasuperobject(48,4,23,"لكن الذي من الجارية ولد حسب الجسد واما الذي من الحرة فبالموعد"));
arasuperobject.biblemap.put("b48_4_24", new arasuperobject(48,4,24,"وكل ذلك رمز لان هاتين هما العهدان احداهما من جبل سيناء الوالد للعبودية الذي هو هاجر"));
arasuperobject.biblemap.put("b48_4_25", new arasuperobject(48,4,25,"لان هاجر جبل سيناء في العربية. ولكنه يقابل اورشليم الحاضرة فانها مستعبدة مع بنيها"));
arasuperobject.biblemap.put("b48_4_26", new arasuperobject(48,4,26,"واما اورشليم العليا التي هي امنا جميعا فهي حرة"));
arasuperobject.biblemap.put("b48_4_27", new arasuperobject(48,4,27,"لانه مكتوب افرحي ايتها العاقر التي لم تلد. اهتفي واصرخي ايتها التي لم تتمخض فان اولاد الموحشة اكثر من التي لها زوج"));
arasuperobject.biblemap.put("b48_4_28", new arasuperobject(48,4,28,"واما نحن ايها الاخوة فنظير اسحق اولاد الموعد"));
arasuperobject.biblemap.put("b48_4_29", new arasuperobject(48,4,29,"ولكن كما كان حينئذ الذي ولد حسب الجسد يضطهد الذي حسب الروح هكذا الآن ايضا"));
arasuperobject.biblemap.put("b48_4_30", new arasuperobject(48,4,30,"لكن ماذا يقول الكتاب. اطرد الجارية وابنها لانه لا يرث ابن الجارية مع ابن الحرة"));
arasuperobject.biblemap.put("b48_4_31", new arasuperobject(48,4,31,"اذا ايها الاخوة لسنا اولاد جارية بل اولاد الحرة"));
arasuperobject.biblemap.put("b48_5_1", new arasuperobject(48,5,1,"فاثبتوا اذا في الحرية التي قد حررنا المسيح بها ولا ترتبكوا ايضا بنير عبودية"));
arasuperobject.biblemap.put("b48_5_2", new arasuperobject(48,5,2,"ها انا بولس اقول لكم انه ان اختتنتم لا ينفعكم المسيح شيئا"));
arasuperobject.biblemap.put("b48_5_3", new arasuperobject(48,5,3,"لكن اشهد ايضا لكل انسان مختتن انه ملتزم ان يعمل بكل الناموس"));
arasuperobject.biblemap.put("b48_5_4", new arasuperobject(48,5,4,"قد تبطلتم عن المسيح ايها الذين تتبررون بالناموس. سقطتم من النعمة"));
arasuperobject.biblemap.put("b48_5_5", new arasuperobject(48,5,5,"فاننا بالروح من الايمان نتوقع رجاء بر"));
arasuperobject.biblemap.put("b48_5_6", new arasuperobject(48,5,6,"لانه في المسيح يسوع لا الختان ينفع شيئا ولا الغرلة بل الايمان العامل بالمحبة"));
arasuperobject.biblemap.put("b48_5_7", new arasuperobject(48,5,7,"كنتم تسعون حسنا. فمن صدكم حتى لا تطاوعوا للحق"));
arasuperobject.biblemap.put("b48_5_8", new arasuperobject(48,5,8,"هذه المطاوعة ليست من الذي دعاكم"));
arasuperobject.biblemap.put("b48_5_9", new arasuperobject(48,5,9,"خميرة صغيرة تخمّر العجين كله"));
arasuperobject.biblemap.put("b48_5_10", new arasuperobject(48,5,10,"ولكنني اثق بكم في الرب انكم لا تفتكرون شيئا آخر. ولكن الذي يزعجكم سيحمل الدينونة ايّ من كان"));
arasuperobject.biblemap.put("b48_5_11", new arasuperobject(48,5,11,"واما انا ايها الاخوة فان كنت بعد اكرز بالختان فلماذا أضطهد بعد. اذا عثرة الصليب قد بطلت"));
arasuperobject.biblemap.put("b48_5_12", new arasuperobject(48,5,12,"يا ليت الذين يقلقونكم يقطعون ايضا"));
arasuperobject.biblemap.put("b48_5_13", new arasuperobject(48,5,13,"فانكم انما دعيتم للحرية ايها الاخوة. غير انه لا تصيّروا الحرية فرصة للجسد بل بالمحبة اخدموا بعضكم بعضا"));
arasuperobject.biblemap.put("b48_5_14", new arasuperobject(48,5,14,"لان كل الناموس في كلمة واحده يكمل. تحب قريبك كنفسك"));
arasuperobject.biblemap.put("b48_5_15", new arasuperobject(48,5,15,"فاذا كنتم تنهشون وتأكلون بعضكم بعضا فانظروا لئلا تفنوا بعضكم بعضا"));
arasuperobject.biblemap.put("b48_5_16", new arasuperobject(48,5,16,"وانما اقول اسلكوا بالروح فلا تكملوا شهوة الجسد"));
arasuperobject.biblemap.put("b48_5_17", new arasuperobject(48,5,17,"لان الجسد يشتهي ضد الروح والروح ضد الجسد. وهذان يقاوم احدهما الآخر حتى تفعلون ما لا تريدون"));
arasuperobject.biblemap.put("b48_5_18", new arasuperobject(48,5,18,"ولكن اذا انقدتم بالروح فلستم تحت الناموس"));
arasuperobject.biblemap.put("b48_5_19", new arasuperobject(48,5,19,"واعمال الجسد ظاهرة التي هي زنى عهارة نجاسة دعارة"));
arasuperobject.biblemap.put("b48_5_20", new arasuperobject(48,5,20,"عبادة الاوثان سحر عداوة خصام غيرة سخط تحزب شقاق بدعة"));
arasuperobject.biblemap.put("b48_5_21", new arasuperobject(48,5,21,"حسد قتل سكر بطر وامثال هذه التي اسبق فاقول لكم عنها كما سبقت فقلت ايضا ان الذين يفعلون مثل هذه لا يرثون ملكوت الله"));
arasuperobject.biblemap.put("b48_5_22", new arasuperobject(48,5,22,"واما ثمر الروح فهو محبة فرح سلام طول اناة لطف صلاح ايمان"));
arasuperobject.biblemap.put("b48_5_23", new arasuperobject(48,5,23,"وداعة تعفف. ضد امثال هذه ليس ناموس"));
arasuperobject.biblemap.put("b48_5_24", new arasuperobject(48,5,24,"ولكن الذين هم للمسيح قد صلبوا الجسد مع الاهواء والشهوات"));
arasuperobject.biblemap.put("b48_5_25", new arasuperobject(48,5,25,"ان كنا نعيش بالروح فلنسلك ايضا بحسب الروح"));
arasuperobject.biblemap.put("b48_5_26", new arasuperobject(48,5,26,"لا نكن معجبين نغاضب بعضنا بعضا ونحسد بعضنا بعضا"));
arasuperobject.biblemap.put("b48_6_1", new arasuperobject(48,6,1,"ايها الاخوة ان انسبق انسان فأخذ في زلة ما فاصلحوا انتم الروحانيين مثل هذا بروح الوداعة ناظرا الى نفسك لئلا تجرب انت ايضا"));
arasuperobject.biblemap.put("b48_6_2", new arasuperobject(48,6,2,"احملوا بعضكم اثقال بعض وهكذا تمموا ناموس المسيح"));
arasuperobject.biblemap.put("b48_6_3", new arasuperobject(48,6,3,"لانه ان ظن احد انه شيء وهو ليس شيئا فانه يغش نفسه"));
arasuperobject.biblemap.put("b48_6_4", new arasuperobject(48,6,4,"ولكن ليمتحن كل واحد عمله وحينئذ يكون له الفخر من جهة نفسه فقط لا من جهة غيره"));
arasuperobject.biblemap.put("b48_6_5", new arasuperobject(48,6,5,"لان كل واحد سيحمل حمل نفسه"));
arasuperobject.biblemap.put("b48_6_6", new arasuperobject(48,6,6,"ولكن ليشارك الذي يتعلّم الكلمة المعلّم في جميع الخيرات"));
arasuperobject.biblemap.put("b48_6_7", new arasuperobject(48,6,7,"لا تضلوا. الله لا يشمخ عليه. فان الذي يزرعه الانسان اياه يحصد ايضا"));
arasuperobject.biblemap.put("b48_6_8", new arasuperobject(48,6,8,"لان من يزرع لجسده فمن الجسد يحصد فسادا. ومن يزرع للروح فمن الروح يحصد حياة ابدية"));
arasuperobject.biblemap.put("b48_6_9", new arasuperobject(48,6,9,"فلا نفشل في عمل الخير لاننا سنحصد في وقته ان كنا لا نكل"));
arasuperobject.biblemap.put("b48_6_10", new arasuperobject(48,6,10,"فاذا حسبما لنا فرصة فلنعمل الخير للجميع ولا سيما لاهل الايمان"));
arasuperobject.biblemap.put("b48_6_11", new arasuperobject(48,6,11,"انظروا ما اكبر الاحرف التي كتبتها اليكم بيدي"));
arasuperobject.biblemap.put("b48_6_12", new arasuperobject(48,6,12,"جميع الذين يريدون ان يعملوا منظرا حسنا في الجسد هؤلاء يلزمونكم ان تختتنوا لئلا يضطهدوا لاجل صليب المسيح فقط"));
arasuperobject.biblemap.put("b48_6_13", new arasuperobject(48,6,13,"لان الذين يختتنون هم لا يحفظون الناموس بل يريدون ان تختتنوا انتم لكي يفتخروا في جسدكم"));
arasuperobject.biblemap.put("b48_6_14", new arasuperobject(48,6,14,"واما من جهتي فحاشا لي ان افتخر الا بصليب ربنا يسوع المسيح الذي به قد صلب العالم لي وانا للعالم"));
arasuperobject.biblemap.put("b48_6_15", new arasuperobject(48,6,15,"لانه في المسيح يسوع ليس الختان ينفع شيئا ولا الغرلة بل الخليقة الجديدة"));
arasuperobject.biblemap.put("b48_6_16", new arasuperobject(48,6,16,"فكل الذين يسلكون بحسب هذا القانون عليهم سلام ورحمة وعلى اسرائيل الله"));
arasuperobject.biblemap.put("b48_6_17", new arasuperobject(48,6,17,"في ما بعد لا يجلب احد عليّ اتعابا لاني حامل في جسدي سمات الرب يسوع"));
arasuperobject.biblemap.put("b48_6_18", new arasuperobject(48,6,18,"نعمة ربنا يسوع المسيح مع روحكم ايها الاخوة. آمين"));

}

}