package ara.bible;

public class arabible30 {

public arabible30() {

putmapbible30();

}

private void putmapbible30() {

arasuperobject.biblemap.put("b30_1_1", new arasuperobject(30,1,1,"اقوال عاموس الذي كان بين الرعاة من تقوع التي رآها عن اسرائيل في ايام عزّيا ملك يهوذا وفي ايام يربعام بن يوآش ملك اسرائيل قبل الزلزلة بسنتين"));
arasuperobject.biblemap.put("b30_1_2", new arasuperobject(30,1,2,"فقال ان الرب يزمجر من صهيون ويعطي صوته من اورشليم فتنوح مراعي الرعاة وييبس راس الكرمل"));
arasuperobject.biblemap.put("b30_1_3", new arasuperobject(30,1,3,"هكذا قال الرب. من اجل ذنوب دمشق الثلاثة والاربعة لا ارجع عنه لانهم داسوا جلعاد بنوارج من حديد"));
arasuperobject.biblemap.put("b30_1_4", new arasuperobject(30,1,4,"فارسل نارا على بيت حزائيل فتأكل قصور بنهدد"));
arasuperobject.biblemap.put("b30_1_5", new arasuperobject(30,1,5,"واكسر مغلاق دمشق واقطع الساكن من بقعة آون وماسك القضيب من بيت عدن ويسبى شعب ارام الى قير قال الرب"));
arasuperobject.biblemap.put("b30_1_6", new arasuperobject(30,1,6,"هكذا قال الرب. من اجل ذنوب غزّة الثلاثة والاربعة لا ارجع عنه لانهم سبوا سبيا كاملا لكي يسلّموه الى ادوم"));
arasuperobject.biblemap.put("b30_1_7", new arasuperobject(30,1,7,"فارسل نارا على سور غزّة فتاكل قصورها"));
arasuperobject.biblemap.put("b30_1_8", new arasuperobject(30,1,8,"واقطع الساكن من اشدود وماسك القضيب من اشقلون وارد يدي على عقرون فتهلك بقية الفلسطنيين قال السيد الرب"));
arasuperobject.biblemap.put("b30_1_9", new arasuperobject(30,1,9,"هكذا قال الرب من اجل ذنوب صور الثلاثة والاربعة لا ارجع عنه لانهم سلّموا سبيا كاملا الى ادوم ولم يذكروا عهد الاخوة"));
arasuperobject.biblemap.put("b30_1_10", new arasuperobject(30,1,10,"فارسل نارا على سور صور فتاكل قصورها"));
arasuperobject.biblemap.put("b30_1_11", new arasuperobject(30,1,11,"هكذا قال الرب من اجل ذنوب ادوم الثلاثة والاربعة لا ارجع عنه لانه تبع بالسيف اخاه وافسد مراحمه وغضبه الى الدهر يفترس وسخطه يحفظه الى الابد"));
arasuperobject.biblemap.put("b30_1_12", new arasuperobject(30,1,12,"فارسل نارا على تيمان فتأكل قصور بصرة"));
arasuperobject.biblemap.put("b30_1_13", new arasuperobject(30,1,13,"هكذا قال الرب من اجل ذنوب بني عمون الثلاثة والاربعة لا ارجع عنه لانهم شقّوا حوامل جلعاد لكي يوسّعوا تخومهم"));
arasuperobject.biblemap.put("b30_1_14", new arasuperobject(30,1,14,"فأضرم نارا على سور ربّة فتاكل قصورها. بجلبة في يوم القتال بنوء في يوم الزوبعة"));
arasuperobject.biblemap.put("b30_1_15", new arasuperobject(30,1,15,"ويمضي ملكهم الى السبي هو ورؤساؤه جميعا قال الرب"));
arasuperobject.biblemap.put("b30_2_1", new arasuperobject(30,2,1,"هكذا قال الرب. من اجل ذنوب موآب الثلاثة والاربعة لا ارجع عنه لانهم احرقوا عظام ملك ادوم كلسا"));
arasuperobject.biblemap.put("b30_2_2", new arasuperobject(30,2,2,"فأرسل نارا على موآب فتاكل قصور قريوت ويموت موآب بضجيج بجلبة بصوت البوق"));
arasuperobject.biblemap.put("b30_2_3", new arasuperobject(30,2,3,"واقطع القاضي من وسطها واقتل جميع رؤسائها معه قال الرب"));
arasuperobject.biblemap.put("b30_2_4", new arasuperobject(30,2,4,"هكذا قال الرب. من اجل ذنوب يهوذا الثلاثة والاربعة لا ارجع عنه لانهم رفضوا ناموس الله ولم يحفظوا فرائضه واضلتهم اكاذيبهم التي سار آباؤهم وراءها"));
arasuperobject.biblemap.put("b30_2_5", new arasuperobject(30,2,5,"فأرسل نارا على يهوذا فتاكل قصور اورشليم"));
arasuperobject.biblemap.put("b30_2_6", new arasuperobject(30,2,6,"هكذا قال الرب. من اجل ذنوب اسرائيل الثلاثة والاربعة لا ارجع عنه لانهم باعوا البار بالفضة والبائس لاجل نعلين"));
arasuperobject.biblemap.put("b30_2_7", new arasuperobject(30,2,7,"الذين يتهمّمون تراب الارض على رؤوس المساكين ويصدّون سبيل البائسين ويذهب رجل وابوه الى صبية واحدة حتى يدنسوا اسم قدسي"));
arasuperobject.biblemap.put("b30_2_8", new arasuperobject(30,2,8,"ويتمدّدون على ثياب مرهونة بجانب كل مذبح ويشربون خمر المغرّمين في بيت آلهتهم"));
arasuperobject.biblemap.put("b30_2_9", new arasuperobject(30,2,9,"وانا قد ابدت من امامهم الاموري الذي قامته مثل قامة الارز وهو قوي كالبلوط. ابدت ثمره من فوق واصوله من تحت"));
arasuperobject.biblemap.put("b30_2_10", new arasuperobject(30,2,10,"وانا اصعدتكم من ارض مصر وسرت بكم في البرية اربعين سنة لترثوا ارض الاموري"));
arasuperobject.biblemap.put("b30_2_11", new arasuperobject(30,2,11,"واقمت من بنيكم انبياء ومن فتيانكم نذيرين. أليس هكذا يا بني اسرائيل يقول الرب"));
arasuperobject.biblemap.put("b30_2_12", new arasuperobject(30,2,12,"لكنكم سقيتم النذيرين خمرا واوصيتم الانبياء قائلين لا تتنبأوا"));
arasuperobject.biblemap.put("b30_2_13", new arasuperobject(30,2,13,"هانذا اضغط ما تحتكم كما تضغط العجلة الملآنة حزما"));
arasuperobject.biblemap.put("b30_2_14", new arasuperobject(30,2,14,"ويبيد المناص عن السريع والقوي لا يشدّد قوّته والبطل لا ينجّي نفسه"));
arasuperobject.biblemap.put("b30_2_15", new arasuperobject(30,2,15,"وماسك القوس لا يثبت وسريع الرجلين لا ينجو وراكب الخيل لا ينجّي نفسه"));
arasuperobject.biblemap.put("b30_2_16", new arasuperobject(30,2,16,"والقوي القلب بين الابطال يهرب عريانا في ذلك اليوم يقول الرب"));
arasuperobject.biblemap.put("b30_3_1", new arasuperobject(30,3,1,"اسمعوا هذا القول الذي تكلم به الرب عليكم يا بني اسرائيل على كل القبيلة التي اصعدتها من ارض مصر قائلا"));
arasuperobject.biblemap.put("b30_3_2", new arasuperobject(30,3,2,"اياكم فقط عرفت من جميع قبائل الارض لذلك اعاقبكم على جميع ذنوبكم"));
arasuperobject.biblemap.put("b30_3_3", new arasuperobject(30,3,3,"هل يسير اثنان معا ان لم يتواعدا"));
arasuperobject.biblemap.put("b30_3_4", new arasuperobject(30,3,4,"هل يزمجر الاسد في الوعر وليس له فريسة. هل يعطي شبل الاسد زئيره من خدره ان لم يخطف"));
arasuperobject.biblemap.put("b30_3_5", new arasuperobject(30,3,5,"هل يسقط عصفور في فخ الارض وليس له شرك. هل يرفع فخ عن الارض وهو لم يمسك شيئا"));
arasuperobject.biblemap.put("b30_3_6", new arasuperobject(30,3,6,"ام يضرب بالبوق في مدينة والشعب لا يرتعد. هل تحدث بلية في مدينة والرب لم يصنعها"));
arasuperobject.biblemap.put("b30_3_7", new arasuperobject(30,3,7,"ان السيد الرب لا يصنع امرا الا وهو يعلن سرّه لعبيده الانبياء"));
arasuperobject.biblemap.put("b30_3_8", new arasuperobject(30,3,8,"الاسد قد زمجر فمن لا يخاف. السيد الرب قد تكلم فمن لا يتنبأ"));
arasuperobject.biblemap.put("b30_3_9", new arasuperobject(30,3,9,"نادوا على القصور في اشدود وعلى القصور في ارض مصر وقولوا اجتمعوا على جبال السامرة وانظروا شغبا عظيما في وسطها ومظالم في داخلها"));
arasuperobject.biblemap.put("b30_3_10", new arasuperobject(30,3,10,"فانهم لا يعرفون ان يصنعوا الاستقامة يقول الرب. اولئك الذين يخزنون الظلم والاغتصاب في قصورهم"));
arasuperobject.biblemap.put("b30_3_11", new arasuperobject(30,3,11,"لذلك هكذا قال السيد الرب. ضيق حتى في كل ناحية من الارض فينزل عنك عزك وتنهب قصورك"));
arasuperobject.biblemap.put("b30_3_12", new arasuperobject(30,3,12,"هكذا قال الرب. كما ينزع الراعي من فم الاسد كراعين او قطعة اذن هكذا ينتزع بنو اسرائيل الجالسون في السامرة في زاوية السرير وعلى دمقس الفراش"));
arasuperobject.biblemap.put("b30_3_13", new arasuperobject(30,3,13,"اسمعوا واشهدوا على بيت يعقوب يقول السيد الرب اله الجنود"));
arasuperobject.biblemap.put("b30_3_14", new arasuperobject(30,3,14,"اني يوم معاقبتي اسرائيل على ذنوبه اعاقب مذابح بيت ايل فتقطع قرون المذبح وتسقط الى الارض"));
arasuperobject.biblemap.put("b30_3_15", new arasuperobject(30,3,15,"واضرب بيت الشتاء مع بيت الصيف فتبيد بيوت العاج وتضمحل البيوت العظيمة يقول الرب"));
arasuperobject.biblemap.put("b30_4_1", new arasuperobject(30,4,1,"اسمعي هذا القول يا بقرات باشان التي في جبل السامرة الظالمة المساكين الساحقة البائسين القائلة لسادتها هات لنشرب"));
arasuperobject.biblemap.put("b30_4_2", new arasuperobject(30,4,2,"قد اقسم السيد الرب بقدسه هوذا ايام تأتي عليكنّ ياخذونكنّ بخزائم وذرّيتكنّ بشصوص السمك"));
arasuperobject.biblemap.put("b30_4_3", new arasuperobject(30,4,3,"ومن الشقوق تخرجن كل واحدة على وجهها وتندفعن الى الحصن يقول الرب"));
arasuperobject.biblemap.put("b30_4_4", new arasuperobject(30,4,4,"هلم الى بيت ايل واذنبوا الى الجلجال واكثروا الذنوب وأحضروا كل صباح ذبائحكم وكل ثلاثة ايام عشوركم"));
arasuperobject.biblemap.put("b30_4_5", new arasuperobject(30,4,5,"واوقدوا من الخمير تقدمة شكر ونادوا بنوافل وسمّعوا. لانكم هكذا احببتم يا بني اسرائيل يقول السيد الرب"));
arasuperobject.biblemap.put("b30_4_6", new arasuperobject(30,4,6,"وانا ايضا اعطيتكم نظافة الاسنان في جميع مدنكم وعوز الخبز في جميع اماكنكم فلم ترجعوا اليّ يقول الرب"));
arasuperobject.biblemap.put("b30_4_7", new arasuperobject(30,4,7,"وانا ايضا منعت عنكم المطر اذ بقي ثلاثة اشهر للحصاد وامطرت على مدينة واحدة وعلى مدينة اخرى لم امطر. امطر على ضيعة واحدة والضيعة التي لم يمطر عليها جفّت"));
arasuperobject.biblemap.put("b30_4_8", new arasuperobject(30,4,8,"فجالت مدينتان او ثلاث الى مدينة واحدة لتشرب ماء ولم تشبع فلم ترجعوا اليّ يقول الرب"));
arasuperobject.biblemap.put("b30_4_9", new arasuperobject(30,4,9,"ضربتكم باللفح واليرقان. كثيرا ما اكل القمص جنّاتكم وكرومكم وتينكم وزيتونكم فلم ترجعوا اليّ يقول الرب"));
arasuperobject.biblemap.put("b30_4_10", new arasuperobject(30,4,10,"ارسلت بينكم وبأ على طريقة مصر. قتلت بالسيف فتيانكم مع سبي خيلكم واصعدت نتن محالّكم حتى الى انوفكم فلم ترجعوا اليّ يقول الرب"));
arasuperobject.biblemap.put("b30_4_11", new arasuperobject(30,4,11,"قلبت بعضكم كما قلب الله سدوم وعمورة فصرتم كشعلة منتشلة من الحريق فلم ترجعوا اليّ يقول الرب"));
arasuperobject.biblemap.put("b30_4_12", new arasuperobject(30,4,12,"لذلك هكذا اصنع بك يا اسرائيل. فمن اجل اني اصنع بك هذا فاستعد للقاء الهك يا اسرائيل"));
arasuperobject.biblemap.put("b30_4_13", new arasuperobject(30,4,13,"فانه هوذا الذي صنع الجبال وخلق الريح واخبر الانسان ما هو فكره الذي يجعل الفجر ظلاما ويمشي على مشارف الارض يهوه اله الجنود اسمه"));
arasuperobject.biblemap.put("b30_5_1", new arasuperobject(30,5,1,"اسمعوا هذا القول الذي انا انادي به عليكم مرثاة يا بيت اسرائيل"));
arasuperobject.biblemap.put("b30_5_2", new arasuperobject(30,5,2,"سقطت عذراء اسرائيل لا تعود تقوم. انطرحت على ارضها ليس من يقيمها"));
arasuperobject.biblemap.put("b30_5_3", new arasuperobject(30,5,3,"لانه هكذا قال السيد الرب. المدينة الخارجة بالف يبقى لها مئة والخارجة بمئة يبقى لها عشرة من بيت اسرائيل"));
arasuperobject.biblemap.put("b30_5_4", new arasuperobject(30,5,4,"لانه هكذا قال الرب لبيت اسرائيل اطلبوني فتحيوا"));
arasuperobject.biblemap.put("b30_5_5", new arasuperobject(30,5,5,"ولا تطلبوا بيت ايل والى الجلجال لا تذهبوا والى بئر سبع لا تعبروا. لان الجلجال تسبى سبيا وبيت ايل تصير عدما"));
arasuperobject.biblemap.put("b30_5_6", new arasuperobject(30,5,6,"اطلبوا الرب فتحيوا لئلا يقتحم بيت يوسف كنار تحرق ولا يكون من يطفئها من بيت ايل"));
arasuperobject.biblemap.put("b30_5_7", new arasuperobject(30,5,7,"يا ايها الذين يحوّلون الحق افسنتينا ويلقون البر الى الارض"));
arasuperobject.biblemap.put("b30_5_8", new arasuperobject(30,5,8,"الذي صنع الثريا والجبّار ويحوّل ظل الموت صبحا ويظلم النهار كالليل الذي يدعو مياه البحر ويصبها على وجه الارض يهوه اسمه"));
arasuperobject.biblemap.put("b30_5_9", new arasuperobject(30,5,9,"الذي يفلح الخرب على القوي فيأتي الخرب على الحصن"));
arasuperobject.biblemap.put("b30_5_10", new arasuperobject(30,5,10,"انهم في الباب يبغضون المنذر ويكرهون المتكلم بالصدق"));
arasuperobject.biblemap.put("b30_5_11", new arasuperobject(30,5,11,"لذلك من اجل انكم تدوسون المسكين وتاخذون منه هدية قمح بنيتم بيوتا من حجارة منحوتة ولا تسكنون فيها وغرستم كروما شهية ولا تشربون خمرها"));
arasuperobject.biblemap.put("b30_5_12", new arasuperobject(30,5,12,"لاني علمت ان ذنوبكم كثيرة وخطاياكم وافرة ايها المضايقون البار الآخذون الرشوة الصادّون البائسين في الباب"));
arasuperobject.biblemap.put("b30_5_13", new arasuperobject(30,5,13,"لذلك يصمت العاقل في ذلك الزمان لانه زمان رديء"));
arasuperobject.biblemap.put("b30_5_14", new arasuperobject(30,5,14,"اطلبوا الخير لا الشر لكي تحيوا فعلى هذا يكون الرب اله الجنود معكم كما قلتم"));
arasuperobject.biblemap.put("b30_5_15", new arasuperobject(30,5,15,"ابغضوا الشر واحبوا الخير وثبّتوا الحق في الباب لعل الرب اله الجنود يترأف على بقية يوسف"));
arasuperobject.biblemap.put("b30_5_16", new arasuperobject(30,5,16,"لذلك هكذا قال السيد الرب اله الجنود. في جميع الاسواق نحيب وفي جميع الازقة يقولون آه آه ويدعون الفلاح الى النوح وجميع عارفي الرثاء للندب"));
arasuperobject.biblemap.put("b30_5_17", new arasuperobject(30,5,17,"وفي جميع الكروم ندب لاني اعبر في وسطك قال الرب"));
arasuperobject.biblemap.put("b30_5_18", new arasuperobject(30,5,18,"ويل للذين يشتهون يوم الرب. لماذا لكم يوم الرب. هو ظلام لا نور"));
arasuperobject.biblemap.put("b30_5_19", new arasuperobject(30,5,19,"كما اذا هرب انسان من امام الاسد فصادفه الدب او دخل البيت ووضع يده على الحائط فلدغته الحيّة"));
arasuperobject.biblemap.put("b30_5_20", new arasuperobject(30,5,20,"أليس يوم الرب ظلاما لا نورا وقتاما لا نور له"));
arasuperobject.biblemap.put("b30_5_21", new arasuperobject(30,5,21,"بغضت كرهت اعيادكم ولست التذّ باعتكافاتكم"));
arasuperobject.biblemap.put("b30_5_22", new arasuperobject(30,5,22,"اني اذا قدمتم لي محرقاتكم وتقدماتكم لا ارتضي وذبائح السلامة من مسمّناتكم لا التفت اليها"));
arasuperobject.biblemap.put("b30_5_23", new arasuperobject(30,5,23,"ابعد عني ضجّة اغانيك ونغمة ربابك لا اسمع"));
arasuperobject.biblemap.put("b30_5_24", new arasuperobject(30,5,24,"وليجر الحق كالمياه والبرّ كنهر دائم"));
arasuperobject.biblemap.put("b30_5_25", new arasuperobject(30,5,25,"هل قدمتم لي ذبائح وتقدمات في البرية اربعين سنة يا بيت اسرائيل"));
arasuperobject.biblemap.put("b30_5_26", new arasuperobject(30,5,26,"بل حملتم خيمة ملكومكم وتمثال اصنامكم نجم الهكم الذي صنعتم لنفوسكم"));
arasuperobject.biblemap.put("b30_5_27", new arasuperobject(30,5,27,"فاسبيكم الى ما وراء دمشق قال الرب اله الجنود اسمه"));
arasuperobject.biblemap.put("b30_6_1", new arasuperobject(30,6,1,"ويل للمستريحين في صهيون والمطمئنين في جبل السامرة نقباء اوّل الامم. ياتي اليهم بيت اسرائيل"));
arasuperobject.biblemap.put("b30_6_2", new arasuperobject(30,6,2,"اعبروا الى كلنة وانظروا واذهبوا من هناك الى حماة العظيمة ثم انزلوا الى جتّ الفلسطينيين. أهي افضل من هذه الممالك ام تخمهم اوسع من تخمكم"));
arasuperobject.biblemap.put("b30_6_3", new arasuperobject(30,6,3,"انتم الذين تبعدون يوم البلية وتقربون مقعد الظلم"));
arasuperobject.biblemap.put("b30_6_4", new arasuperobject(30,6,4,"المضطجعون على اسرّة من العاج والمتمددون على فرشهم والآكلون خرافا من الغنم وعجولا من وسط الصيرة"));
arasuperobject.biblemap.put("b30_6_5", new arasuperobject(30,6,5,"الهاذرون مع صوت الرباب المخترعون لانفسهم آلات الغناء كداود"));
arasuperobject.biblemap.put("b30_6_6", new arasuperobject(30,6,6,"الشاربون من كؤوس الخمر والذين يدهنون بافضل الادهان ولا يغتمّون على انسحاق يوسف"));
arasuperobject.biblemap.put("b30_6_7", new arasuperobject(30,6,7,"لذلك الآن يسبون في اول المسبيّين ويزول صياح المتمددين"));
arasuperobject.biblemap.put("b30_6_8", new arasuperobject(30,6,8,"قد اقسم السيد الرب بنفسه يقول الرب اله الجنود اني اكره عظمة يعقوب وابغض قصوره فاسلّم المدينة وملأها"));
arasuperobject.biblemap.put("b30_6_9", new arasuperobject(30,6,9,"فيكون اذا بقي عشرة رجال في بيت واحد انهم يموتون"));
arasuperobject.biblemap.put("b30_6_10", new arasuperobject(30,6,10,"واذا حمل احدا عمّه ومحرقه ليخرج العظام من البيت وقال لمن هو في جوانب البيت أعندك بعد يقول ليس بعد. فيقول اسكت فانه لا يذكر اسم الرب"));
arasuperobject.biblemap.put("b30_6_11", new arasuperobject(30,6,11,"لانه هوذا الرب يأمر فيضرب البيت الكبير ردما والبيت الصغير شقوقا"));
arasuperobject.biblemap.put("b30_6_12", new arasuperobject(30,6,12,"هل تركض الخيل على الصخر او يحرث عليه بالبقر حتى حوّلتم الحق سمّا وثمر البرّ افسنتينا"));
arasuperobject.biblemap.put("b30_6_13", new arasuperobject(30,6,13,"انتم الفرحون بالبطل القائلون أليس بقوّتنا اتخذنا لانفسنا قرونا"));
arasuperobject.biblemap.put("b30_6_14", new arasuperobject(30,6,14,"لاني هانذا اقيم عليكم يا بيت اسرائيل يقول الرب اله الجنود امة فيضايقونكم من مدخل حماة الى وادي العربة"));
arasuperobject.biblemap.put("b30_7_1", new arasuperobject(30,7,1,"هكذا اراني السيد الرب واذا هو يصنع جرادا في اول طلوع خلف العشب. واذا خلف عشب بعد جزاز الملك"));
arasuperobject.biblemap.put("b30_7_2", new arasuperobject(30,7,2,"وحدث لما فرغ من اكل عشب الارض اني قلت ايها السيد الرب اصفح. كيف يقوم يعقوب فانه صغير"));
arasuperobject.biblemap.put("b30_7_3", new arasuperobject(30,7,3,"فندم الرب على هذا. لا يكون قال الرب"));
arasuperobject.biblemap.put("b30_7_4", new arasuperobject(30,7,4,"هكذا اراني السيد الرب واذا السيد الرب قد دعا للمحاكمة بالنار. فأكلت الغمر العظيم واكلت الحقل"));
arasuperobject.biblemap.put("b30_7_5", new arasuperobject(30,7,5,"فقلت ايها السيد الرب كف. كيف يقوم يعقوب فانه صغير"));
arasuperobject.biblemap.put("b30_7_6", new arasuperobject(30,7,6,"فندم الرب على هذا. فهو ايضا لا يكون قال السيد الرب"));
arasuperobject.biblemap.put("b30_7_7", new arasuperobject(30,7,7,"هكذا اراني واذا الرب واقف على حائط قائم وفي يده زيج"));
arasuperobject.biblemap.put("b30_7_8", new arasuperobject(30,7,8,"فقال لي الرب ما انت راء يا عاموس. فقلت زيجا. فقال السيد هانذا واضع زيجا في وسط شعبي اسرائيل. لا اعود اصفح له بعد"));
arasuperobject.biblemap.put("b30_7_9", new arasuperobject(30,7,9,"فتقفر مرتفعات اسحق وتخرب مقادس اسرائيل واقوم على بيت يربعام بالسيف"));
arasuperobject.biblemap.put("b30_7_10", new arasuperobject(30,7,10,"فارسل امصيا كاهن بيت ايل الى يربعام ملك اسرائيل قائلا قد فتن عليك عاموس في وسط بيت اسرائيل. لا تقدر الارض ان تطيق كل اقواله"));
arasuperobject.biblemap.put("b30_7_11", new arasuperobject(30,7,11,"لانه هكذا قال عاموس. يموت يربعام بالسيف ويسبى اسرائيل عن ارضه"));
arasuperobject.biblemap.put("b30_7_12", new arasuperobject(30,7,12,"فقال امصيا لعاموس ايها الرائي اذهب اهرب الى ارض يهوذا وكل هناك خبزا وهناك تنبأ"));
arasuperobject.biblemap.put("b30_7_13", new arasuperobject(30,7,13,"واما بيت ايل فلا تعد تتنبأ فيها بعد لانها مقدس الملك وبيت الملك"));
arasuperobject.biblemap.put("b30_7_14", new arasuperobject(30,7,14,"فاجاب عاموس وقال لامصيا. لست انا نبيا ولا انا ابن نبيّ بل انا راع وجاني جميّز"));
arasuperobject.biblemap.put("b30_7_15", new arasuperobject(30,7,15,"فاخذني الرب من وراء الضأن وقال لي الرب اذهب تنبأ لشعبي اسرائيل"));
arasuperobject.biblemap.put("b30_7_16", new arasuperobject(30,7,16,"فالآن اسمع قول الرب. انت تقول لا تتنبأ على اسرائيل ولا تتكلم على بيت اسحق"));
arasuperobject.biblemap.put("b30_7_17", new arasuperobject(30,7,17,"لذلك هكذا قال الرب امرأتك تزني في المدينة وبنوك وبناتك يسقطون بالسيف وارضك تقسم بالحبل وانت تموت في ارض نجسة واسرائيل يسبى سبيا عن ارضه"));
arasuperobject.biblemap.put("b30_8_1", new arasuperobject(30,8,1,"هكذا اراني السيد الرب واذا سلّة للقطاف"));
arasuperobject.biblemap.put("b30_8_2", new arasuperobject(30,8,2,"فقال ماذا انت راء يا عاموس. فقلت سلّة للقطاف. فقال لي الرب قد اتت النهاية على شعبي اسرائيل. لا اعود اصفح له بعد"));
arasuperobject.biblemap.put("b30_8_3", new arasuperobject(30,8,3,"فتصير اغاني القصر ولاول في ذلك اليوم يقول السيد الرب. الجثث كثيرة يطرحونها في كل موضع بالسكوت"));
arasuperobject.biblemap.put("b30_8_4", new arasuperobject(30,8,4,"اسمعوا هذا ايها المتهمّمون المساكين لكي تبيدوا بائسي الارض"));
arasuperobject.biblemap.put("b30_8_5", new arasuperobject(30,8,5,"قائلين متى يمضي راس الشهر لنبيع قمحا والسبت لنعرض حنطة. لنصغّر الإيفة ونكبر الشاقل ونعوّج موازين الغش"));
arasuperobject.biblemap.put("b30_8_6", new arasuperobject(30,8,6,"لنشتري الضعفاء بفضة والبائس بنعلين ونبيع نفاية القمح"));
arasuperobject.biblemap.put("b30_8_7", new arasuperobject(30,8,7,"قد اقسم الرب بفخر يعقوب اني لن انسى الى الابد جميع اعمالهم"));
arasuperobject.biblemap.put("b30_8_8", new arasuperobject(30,8,8,"أليس من اجل هذا ترتعد الارض وينوح كل ساكن فيها وتطمو كلها كنهر وتفيض وتنضب كنيل مصر"));
arasuperobject.biblemap.put("b30_8_9", new arasuperobject(30,8,9,"ويكون في ذلك اليوم يقول السيد الرب اني اغيّب الشمس في الظهر وأقتم الارض في يوم نور"));
arasuperobject.biblemap.put("b30_8_10", new arasuperobject(30,8,10,"واحوّل اعيادكم نوحا وجميع اغانيكم مراثي واصعد على كل الاحقاء مسحا وعلى كل راس قرعة واجعلها كمناحة الوحيد وآخرها يوما مرّا"));
arasuperobject.biblemap.put("b30_8_11", new arasuperobject(30,8,11,"هوذا ايام تأتي يقول السيد الرب ارسل جوعا في الارض لا جوعا للخبز ولا عطشا للماء بل لاستماع كلمات الرب ً"));
arasuperobject.biblemap.put("b30_8_12", new arasuperobject(30,8,12,"فيجولون من بحر الى بحر ومن الشمال الى المشرق يتطوّحون ليطلبوا كلمة الرب فلا يجدونها"));
arasuperobject.biblemap.put("b30_8_13", new arasuperobject(30,8,13,"في ذلك اليوم تذبل بالعطش العذارى الجميلات والفتيان"));
arasuperobject.biblemap.put("b30_8_14", new arasuperobject(30,8,14,"الذين يحلفون بذنب السامرة ويقولون حيّ الهك يا دان وحية طريقة بئر سبع فيسقطون ولا يقومون بعد"));
arasuperobject.biblemap.put("b30_9_1", new arasuperobject(30,9,1,"رأيت السيد قائما على المذبح فقال اضرب تاج العمود حتى ترجف الاعتاب وكسّرها على رؤوس جميعهم فأقتل آخرهم بالسيف. لا يهرب منهم هارب ولا يفلت منهم ناج"));
arasuperobject.biblemap.put("b30_9_2", new arasuperobject(30,9,2,"ان نقبوا الى الهاوية فمن هناك تاخذهم يدي وان صعدوا الى السماء فمن هناك انزلهم"));
arasuperobject.biblemap.put("b30_9_3", new arasuperobject(30,9,3,"وان اختبأوا في راس الكرمل فمن هناك افتش وآخذهم وان اختفوا من امام عينيّ في قعر البحر فمن هناك آمر الحيّة فتلدغهم"));
arasuperobject.biblemap.put("b30_9_4", new arasuperobject(30,9,4,"وان مضوا في السبي امام اعدائهم فمن هناك آمر السيف فيقتلهم واجعل عينيّ عليهم للشر لا للخير"));
arasuperobject.biblemap.put("b30_9_5", new arasuperobject(30,9,5,"والسيد رب الجنود الذي يمسّ الارض فتذوب وينوح الساكنون فيها وتطمو كلها كنهر وتنضب كنيل مصر"));
arasuperobject.biblemap.put("b30_9_6", new arasuperobject(30,9,6,"الذي بنى في السماء علاليه وأسّس على الارض قبّته الذي يدعو مياه البحر ويصبها على وجه الارض يهوه اسمه"));
arasuperobject.biblemap.put("b30_9_7", new arasuperobject(30,9,7,"ألستم لي كبني الكوشيين يا بني اسرائيل يقول الرب. ألم اصعد اسرائيل من ارض مصر والفلسطينيين من كفتور والاراميين من قير"));
arasuperobject.biblemap.put("b30_9_8", new arasuperobject(30,9,8,"هوذا عينا السيد الرب على المملكة الخاطئة وابيدها عن وجه الارض غير اني لا ابيد بيت يعقوب تماما يقول الرب"));
arasuperobject.biblemap.put("b30_9_9", new arasuperobject(30,9,9,"لانه هانذا آمر فاغربل بيت اسرائيل بين جميع الامم كما يغربل في الغربال وحبة لا تقع الى الارض"));
arasuperobject.biblemap.put("b30_9_10", new arasuperobject(30,9,10,"بالسيف يموت كل خاطئي شعبي القائلين لا يقترب الشر ولا يأتي بيننا"));
arasuperobject.biblemap.put("b30_9_11", new arasuperobject(30,9,11,"في ذلك اليوم اقيم مظلّة داود الساقطة واحصّن شقوقها واقيم ردمها وابنيها كايام الدهر"));
arasuperobject.biblemap.put("b30_9_12", new arasuperobject(30,9,12,"لكي يرثوا بقية ادوم وجميع الامم الذين دعي اسمي عليهم يقول الرب الصانع هذا"));
arasuperobject.biblemap.put("b30_9_13", new arasuperobject(30,9,13,"ها ايام تأتي يقول الرب يدرك الحارث الحاصد ودائس العنب باذر الزرع وتقطر الجبال عصيرا وتسيل جميع التلال"));
arasuperobject.biblemap.put("b30_9_14", new arasuperobject(30,9,14,"وارد سبي شعبي اسرائيل فيبنون مدنا خربة ويسكنون ويغرسون كروما ويشربون خمرها ويصنعون جنّات ويأكلون اثمارها"));
arasuperobject.biblemap.put("b30_9_15", new arasuperobject(30,9,15,"واغرسهم في ارضهم ولن يقلعوا بعد من ارضهم التي اعطيتهم قال الرب الهك"));

}

}