package ara.bible;

public class arabible15 {

public arabible15() {

putmapbible15();

}

private void putmapbible15() {

arasuperobject.biblemap.put("b15_1_1", new arasuperobject(15,1,1,"وفي السنة الاولى لكورش ملك فارس عند تمام كلام الرب بفم ارميا نبّه الرب روح كورش ملك فارس فاطلق نداء في كل مملكته وبالكتابة ايضا قائلا"));
arasuperobject.biblemap.put("b15_1_2", new arasuperobject(15,1,2,"هكذا قال كورش ملك فارس. جميع ممالك الارض دفعها لي الرب اله السماء وهو اوصاني ان ابني له بيتا في اورشليم التي في يهوذا"));
arasuperobject.biblemap.put("b15_1_3", new arasuperobject(15,1,3,"من منكم من كل شعبه****ليكن الهه معه ويصعد الى اورشليم التي في يهوذا فيبني بيت الرب اله اسرائيل. هو الاله. الذي في اورشليم"));
arasuperobject.biblemap.put("b15_1_4", new arasuperobject(15,1,4,"وكل من بقي في احد الاماكن حيث هو متغرب فلينجده اهل مكانه بفضة وبذهب وبامتعة وببهائم مع التبرع لبيت الرب الذي في اورشليم"));
arasuperobject.biblemap.put("b15_1_5", new arasuperobject(15,1,5,"فقام رؤوس آباء يهوذا وبنيامين والكهنة واللاويون مع كل من نبّه الله روحه ليصعدوا ليبنوا بيت الرب الذي في اورشليم"));
arasuperobject.biblemap.put("b15_1_6", new arasuperobject(15,1,6,"وكل الذين حولهم اعانوهم بآنية فضة وبذهب وبامتعة وببهائم وبتحف فضلا عن كل ما تبرع به"));
arasuperobject.biblemap.put("b15_1_7", new arasuperobject(15,1,7,"والملك كورش اخرج آنية بيت الرب التي اخرجها نبوخذناصّر من اورشليم وجعلها في بيت آلهته"));
arasuperobject.biblemap.put("b15_1_8", new arasuperobject(15,1,8,"اخرجها كورش ملك فارس عن يد مثرداث الخازن وعدّها لشيشبصّر رئيس يهوذا"));
arasuperobject.biblemap.put("b15_1_9", new arasuperobject(15,1,9,"وهذا عددها. ثلاثون طستا من ذهب والف طست من فضة وتسعة وعشرون سكينا"));
arasuperobject.biblemap.put("b15_1_10", new arasuperobject(15,1,10,"وثلاثون قدحا من ذهب واقداح فضة من الرتبة الثانية اربع مئة وعشرة والف من آنية اخرى"));
arasuperobject.biblemap.put("b15_1_11", new arasuperobject(15,1,11,"جميع الآنية من الذهب والفضة خمسة آلاف واربع مئة. الكل اصعده شيشبصّر عند اصعاد السبي من بابل الى اورشليم"));
arasuperobject.biblemap.put("b15_2_1", new arasuperobject(15,2,1,"وهؤلاء هم بنو الكورة الصاعدون من سبي المسبيين الذين سباهم نبوخذناصّر ملك بابل الى بابل ورجعوا الى اورشليم ويهوذا كل واحد الى مدينته"));
arasuperobject.biblemap.put("b15_2_2", new arasuperobject(15,2,2,"الذين جاءوا مع زربابل يشوع نحميا سرايا رعلايا مردخاي بلشان مسفار بغواي رحوم بعنة. عدد رجال شعب اسرائيل"));
arasuperobject.biblemap.put("b15_2_3", new arasuperobject(15,2,3,"بنو فرعوش الفان ومئة واثنان وسبعون"));
arasuperobject.biblemap.put("b15_2_4", new arasuperobject(15,2,4,"بنو شفطيا ثلاث مئة واثنان وسبعون"));
arasuperobject.biblemap.put("b15_2_5", new arasuperobject(15,2,5,"بنو آرح سبع مئة وخمسة وسبعون"));
arasuperobject.biblemap.put("b15_2_6", new arasuperobject(15,2,6,"بنو فحث موآب من بني يشوع ويوآب الفان وثمان مئة واثنا عشر"));
arasuperobject.biblemap.put("b15_2_7", new arasuperobject(15,2,7,"بنو عيلام الف ومئتان واربعة وخمسون"));
arasuperobject.biblemap.put("b15_2_8", new arasuperobject(15,2,8,"بنو زتو تسع مئة وخمسة واربعون"));
arasuperobject.biblemap.put("b15_2_9", new arasuperobject(15,2,9,"بنو زكاي سبع مئة وستون"));
arasuperobject.biblemap.put("b15_2_10", new arasuperobject(15,2,10,"بنو باني ست مئة واثنان واربعون"));
arasuperobject.biblemap.put("b15_2_11", new arasuperobject(15,2,11,"بنو باباي ست مئة وثلاثة وعشرون"));
arasuperobject.biblemap.put("b15_2_12", new arasuperobject(15,2,12,"بنو عرجد الف ومئتان واثنان وعشرون"));
arasuperobject.biblemap.put("b15_2_13", new arasuperobject(15,2,13,"بنو ادونيقام ست مئة وستة وستون"));
arasuperobject.biblemap.put("b15_2_14", new arasuperobject(15,2,14,"بنو بغواي الفان وستة وخمسون"));
arasuperobject.biblemap.put("b15_2_15", new arasuperobject(15,2,15,"بنو عادين اربع مئة واربعة وخمسون"));
arasuperobject.biblemap.put("b15_2_16", new arasuperobject(15,2,16,"بنو آطير من يحزقيا ثمانية وتسعون"));
arasuperobject.biblemap.put("b15_2_17", new arasuperobject(15,2,17,"بنو بيصاي ثلاث مئة وثلاثة وعشرون"));
arasuperobject.biblemap.put("b15_2_18", new arasuperobject(15,2,18,"بنو يورة مئة واثنا عشر"));
arasuperobject.biblemap.put("b15_2_19", new arasuperobject(15,2,19,"بنو حشوم مئتان وثلاثة وعشرون"));
arasuperobject.biblemap.put("b15_2_20", new arasuperobject(15,2,20,"بنو جبّار خمسة وتسعون"));
arasuperobject.biblemap.put("b15_2_21", new arasuperobject(15,2,21,"بنو بيت لحم مئة وثلاثة وعشرون"));
arasuperobject.biblemap.put("b15_2_22", new arasuperobject(15,2,22,"رجال نطوفة ستة وخمسون"));
arasuperobject.biblemap.put("b15_2_23", new arasuperobject(15,2,23,"رجال عناثوث مئة وثمانية وعشرون"));
arasuperobject.biblemap.put("b15_2_24", new arasuperobject(15,2,24,"بنو عزموت اثنان واربعون"));
arasuperobject.biblemap.put("b15_2_25", new arasuperobject(15,2,25,"بنو قرية عاريم كفيرة وبئيروت سبع مئة وثلاثة واربعون"));
arasuperobject.biblemap.put("b15_2_26", new arasuperobject(15,2,26,"بنو الرامة وجبع ست مئة وواحد وعشرون"));
arasuperobject.biblemap.put("b15_2_27", new arasuperobject(15,2,27,"رجال مخماس مئة واثنان وعشرون"));
arasuperobject.biblemap.put("b15_2_28", new arasuperobject(15,2,28,"رجال بيت ايل وعاي مئتان وثلاثة وعشرون"));
arasuperobject.biblemap.put("b15_2_29", new arasuperobject(15,2,29,"بنو نبو اثنان وخمسون"));
arasuperobject.biblemap.put("b15_2_30", new arasuperobject(15,2,30,"بنو مغبيش مئة وستة وخمسون"));
arasuperobject.biblemap.put("b15_2_31", new arasuperobject(15,2,31,"بنو عيلام الآخر الف ومئتان واربعة وخمسون"));
arasuperobject.biblemap.put("b15_2_32", new arasuperobject(15,2,32,"بنو حاريم ثلاث مئة وعشرون"));
arasuperobject.biblemap.put("b15_2_33", new arasuperobject(15,2,33,"بنو لود بنو حاديد واونو سبع مئة وخمسة وعشرون"));
arasuperobject.biblemap.put("b15_2_34", new arasuperobject(15,2,34,"بنو اريحا ثلاث مئة وخمسة واربعون"));
arasuperobject.biblemap.put("b15_2_35", new arasuperobject(15,2,35,"بنو سناءة ثلاثة آلاف وست مئة وثلاثون"));
arasuperobject.biblemap.put("b15_2_36", new arasuperobject(15,2,36,"اما الكهنة فبنو يدعيا من بيت يشوع تسع مئة وثلاثة وسبعون"));
arasuperobject.biblemap.put("b15_2_37", new arasuperobject(15,2,37,"بنو امّير الف واثنان وخمسون"));
arasuperobject.biblemap.put("b15_2_38", new arasuperobject(15,2,38,"بنو فشحور الف ومئتان وسبعة واربعون"));
arasuperobject.biblemap.put("b15_2_39", new arasuperobject(15,2,39,"بنو حاريم الف وسبعة عشر"));
arasuperobject.biblemap.put("b15_2_40", new arasuperobject(15,2,40,"اما اللاويون فبنو يشوع وقدميئيل من بني هودويا اربعة وسبعون"));
arasuperobject.biblemap.put("b15_2_41", new arasuperobject(15,2,41,"المغنون بنو آساف مئة وثمانية وعشرون"));
arasuperobject.biblemap.put("b15_2_42", new arasuperobject(15,2,42,"بنو البوابين بنو شلوم بنو آطير بنو طلمون بنو عقّوب بنو حطيطا بنو شوباي الجميع مئة وتسعة وثلاثون"));
arasuperobject.biblemap.put("b15_2_43", new arasuperobject(15,2,43,"النثينيم بنو صيحا بنو حسوفا بنو طباعوت"));
arasuperobject.biblemap.put("b15_2_44", new arasuperobject(15,2,44,"بنو قيروس بنو سيعها بنو فادون"));
arasuperobject.biblemap.put("b15_2_45", new arasuperobject(15,2,45,"بنو لبانة بنو حجابة بنو عقّوب"));
arasuperobject.biblemap.put("b15_2_46", new arasuperobject(15,2,46,"بنو حاجاب بنو شملاي بنو حانان"));
arasuperobject.biblemap.put("b15_2_47", new arasuperobject(15,2,47,"بنو جديل بنو حجر بنو رآيا"));
arasuperobject.biblemap.put("b15_2_48", new arasuperobject(15,2,48,"بنو رصين بنو نقودا بنو جزّام"));
arasuperobject.biblemap.put("b15_2_49", new arasuperobject(15,2,49,"بنو عزّا بنو فاسيح بنو بيساي"));
arasuperobject.biblemap.put("b15_2_50", new arasuperobject(15,2,50,"بنو اسنة بنو معونيم بنو نفوسيم"));
arasuperobject.biblemap.put("b15_2_51", new arasuperobject(15,2,51,"بنو بقبوق بنو حقوفا بنو حرحور"));
arasuperobject.biblemap.put("b15_2_52", new arasuperobject(15,2,52,"بنو بصلوت بنو محيدا بنو حرشا"));
arasuperobject.biblemap.put("b15_2_53", new arasuperobject(15,2,53,"بنو برقوس بنو سيسرا بنو ثامح"));
arasuperobject.biblemap.put("b15_2_54", new arasuperobject(15,2,54,"بنو نصيح بنو حطيفا"));
arasuperobject.biblemap.put("b15_2_55", new arasuperobject(15,2,55,"بنو عبيد سليمان بنو سوطاي بنو هسّوفرث بنو فرودا"));
arasuperobject.biblemap.put("b15_2_56", new arasuperobject(15,2,56,"بنو يعلة بنو درقون بنو جدّيل"));
arasuperobject.biblemap.put("b15_2_57", new arasuperobject(15,2,57,"بنو شفطيا بنو حطّيل بنو فوخرة الظباء بنو آمي"));
arasuperobject.biblemap.put("b15_2_58", new arasuperobject(15,2,58,"جميع النثينيم وبني عبيد سليمان ثلاث مئة واثنان وتسعون"));
arasuperobject.biblemap.put("b15_2_59", new arasuperobject(15,2,59,"وهؤلاء هم الذين صعدوا من تل ملح وتل حرشا كروب ادّان امّير. ولم يستطيعوا ان يبينوا بيوت آبائهم ونسلهم هل هم من اسرائيل"));
arasuperobject.biblemap.put("b15_2_60", new arasuperobject(15,2,60,"بنو دلايا بنو طوبيا بنو نقودا ست مئة واثنان وخمسون"));
arasuperobject.biblemap.put("b15_2_61", new arasuperobject(15,2,61,"ومن بني الكهنة بنو حبايا بنو هقوص بنو برزلاي الذي اخذ امرأة من بنات برزلاي الجلعادي وتسمى باسمهم"));
arasuperobject.biblemap.put("b15_2_62", new arasuperobject(15,2,62,"هؤلاء فتشوا على كتابة انسابهم فلم توجد فرذلوا من الكهنوت"));
arasuperobject.biblemap.put("b15_2_63", new arasuperobject(15,2,63,"وقال لهم الترشاثا ان لا يأكلوا من قدس الاقداس حتى يقوم كاهن للاوريم والتمّيم"));
arasuperobject.biblemap.put("b15_2_64", new arasuperobject(15,2,64,"كل الجمهور معا اثنان واربعون الفا وثلاث مئة وستون"));
arasuperobject.biblemap.put("b15_2_65", new arasuperobject(15,2,65,"فضلا عن عبيدهم وامائهم فهؤلاء كانوا سبعة آلاف وثلاث مئة وسبعة وثلاثين ولهم من المغنّين والمغنيات مئتان"));
arasuperobject.biblemap.put("b15_2_66", new arasuperobject(15,2,66,"خيلهم سبع مئة وستة وثلاثون. بغالهم مئتان وخمسة واربعون"));
arasuperobject.biblemap.put("b15_2_67", new arasuperobject(15,2,67,"جمالهم اربع مئة وخمسة وثلاثون. حميرهم ستة آلاف وسبع مئة وعشرون"));
arasuperobject.biblemap.put("b15_2_68", new arasuperobject(15,2,68,"والبعض من رؤوس الآباء عند مجيئهم الى بيت الرب الذي في اورشليم تبرعوا لبيت الرب لاقامته في مكانه"));
arasuperobject.biblemap.put("b15_2_69", new arasuperobject(15,2,69,"اعطوا حسب طاقتهم لخزانة العمل واحدا وستين الف درهم من الذهب وخمسة آلاف منّا من الفضة ومئة قميص للكهنة"));
arasuperobject.biblemap.put("b15_2_70", new arasuperobject(15,2,70,"فاقام الكهنة واللاويون وبعض الشعب والمغنون والبوابون والنثينيم في مدنهم وكل اسرائيل في مدنهم"));
arasuperobject.biblemap.put("b15_3_1", new arasuperobject(15,3,1,"ولما استهل الشهر السابع وبنو اسرائيل في مدنهم اجتمع الشعب كرجل واحد الى اورشليم"));
arasuperobject.biblemap.put("b15_3_2", new arasuperobject(15,3,2,"وقام يشوع بن يوصاداق واخوته الكهنة وزربابل بن شألتئيل واخوته وبنوا مذبح اله اسرائيل ليصعدوا عليه محرقات كما هو مكتوب في شريعة موسى رجل الله"));
arasuperobject.biblemap.put("b15_3_3", new arasuperobject(15,3,3,"واقاموا المذبح في مكانه لانه كان عليهم رعب من شعوب الاراضي واصعدوا عليه محرقات للرب محرقات الصباح والمساء"));
arasuperobject.biblemap.put("b15_3_4", new arasuperobject(15,3,4,"وحفظوا عيد المظال كما هو مكتوب ومحرقة يوم فيوم بالعدد كالمرسوم أمر اليوم بيومه"));
arasuperobject.biblemap.put("b15_3_5", new arasuperobject(15,3,5,"وبعد ذلك المحرقة الدائمة وللاهلّة ولجميع مواسم الرب المقدسة ولكل من تبرع بمتبرع للرب"));
arasuperobject.biblemap.put("b15_3_6", new arasuperobject(15,3,6,"ابتدأوا من اليوم الاول من الشهر السابع يصعدون محرقات للرب وهيكل الرب لم يكن قد تأسس"));
arasuperobject.biblemap.put("b15_3_7", new arasuperobject(15,3,7,"واعطوا فضة للنحاتين والنجارين ومأكلا ومشربا وزيتا للصيدونيين والصوريين ليأتوا بخشب ارز من لبنان الى بحر يافا حسب اذن كورش ملك فارس لهم"));
arasuperobject.biblemap.put("b15_3_8", new arasuperobject(15,3,8,"وفي السنة الثانية من مجيئهم الى بيت الله الى اورشليم في الشهر الثاني شرع زربابل بن شألتئيل ويشوع بن يوصاداق وبقية اخوتهم الكهنة واللاويين وجميع القادمين من السبي الى اورشليم واقاموا اللاويين من ابن عشرين سنة فما فوق للمناظرة على عمل بيت الرب"));
arasuperobject.biblemap.put("b15_3_9", new arasuperobject(15,3,9,"ووقف يشوع مع بنيه واخوته قدميئيل وبنيه بني يهوذا معا للمناظرة على عاملي الشغل في بيت الله وبني حيناداد مع بنيهم واخوتهم اللاويين"));
arasuperobject.biblemap.put("b15_3_10", new arasuperobject(15,3,10,"ولما أسّس البانون هيكل الرب اقاموا الكهنة بملابسهم بابواق واللاويين بني آساف بالصنوج لتسبيح الرب على ترتيب داود ملك اسرائيل"));
arasuperobject.biblemap.put("b15_3_11", new arasuperobject(15,3,11,"وغنوا بالتسبيح والحمد للرب لانه صالح لان الى الابد رحمته على اسرائيل. وكل الشعب هتفوا هتافا عظيما بالتسبيح للرب لاجل تأسيس بيت الرب"));
arasuperobject.biblemap.put("b15_3_12", new arasuperobject(15,3,12,"وكثيرون من الكهنة واللاويين ورؤوس الآباء الشيوخ الذين رأوا البيت الاول بكوا بصوت عظيم عند تأسيس هذا البيت امام اعينهم. وكثيرون كانوا يرفعون اصواتهم بالهتاف بفرح"));
arasuperobject.biblemap.put("b15_3_13", new arasuperobject(15,3,13,"ولم يكن الشعب يميز هتاف الفرح من صوت بكاء الشعب لان الشعب كان يهتف هتافا عظيما حتى ان الصوت سمع من بعد"));
arasuperobject.biblemap.put("b15_4_1", new arasuperobject(15,4,1,"ولما سمع اعداء يهوذا وبنيامين ان بني السبي يبنون هيكلا للرب اله اسرائيل"));
arasuperobject.biblemap.put("b15_4_2", new arasuperobject(15,4,2,"تقدموا الى زربابل ورؤوس الآباء وقالوا لهم نبني معكم لاننا نظيركم نطلب الهكم وله قد ذبحنا من ايام اسرحدّون ملك اشور الذي اصعدنا الى هنا"));
arasuperobject.biblemap.put("b15_4_3", new arasuperobject(15,4,3,"فقال لهم زربابل ويشوع وبقية رؤوس آباء اسرائيل ليس لكم ولنا ان نبني بيتا لالهنا ولكننا نحن وحدنا نبني للرب اله اسرائيل كما امرنا الملك كورش ملك فارس"));
arasuperobject.biblemap.put("b15_4_4", new arasuperobject(15,4,4,"وكان شعب الارض يرخون ايدي شعب يهوذا ويذعرونهم عن البناء"));
arasuperobject.biblemap.put("b15_4_5", new arasuperobject(15,4,5,"واستأجروا ضدّهم مشيرين ليبطلوا مشورتهم كل ايام كورش ملك فارس وحتى ملك داريوس ملك فارس"));
arasuperobject.biblemap.put("b15_4_6", new arasuperobject(15,4,6,"وفي ملك احشويروش في ابتداء ملكه كتبوا شكوى على سكان يهوذا واورشليم"));
arasuperobject.biblemap.put("b15_4_7", new arasuperobject(15,4,7,"وفي ايام ارتحششتا كتب بشلام ومثرداث وطبئيل وسائر رفقائهم الى ارتحششتا ملك فارس. وكتابة الرسالة مكتوبة بالارامية ومترجمة بالارامية"));
arasuperobject.biblemap.put("b15_4_8", new arasuperobject(15,4,8,"رحوم صاحب القضاء وشمشاي الكاتب كتبا رسالة ضد اورشليم الى ارتحششتا الملك هكذا"));
arasuperobject.biblemap.put("b15_4_9", new arasuperobject(15,4,9,"كتب حينئذ رحوم صاحب القضاء وشمشاي الكاتب وسائر رفقائهما الدينيين والافرستكيين والطرفليين والافرسيين والاركويين والبابليين والشوشنيين والدهويين والعيلاميين"));
arasuperobject.biblemap.put("b15_4_10", new arasuperobject(15,4,10,"وسائر الامم الذين سباهم أسنفّر العظيم الشريف واسكنهم مدن السامرة وسائر الذين في عبر النهر والى آخره"));
arasuperobject.biblemap.put("b15_4_11", new arasuperobject(15,4,11,"هذه صورة الرسالة التي ارسلوها اليه الى ارتحششتا الملك عبيدك القوم الذين في عبر النهر الى آخره"));
arasuperobject.biblemap.put("b15_4_12", new arasuperobject(15,4,12,"ليعلم الملك ان اليهود الذين صعدوا من عندك الينا قد أتوا الى اورشليم ويبنون المدينة العاصية الردية وقد اكملوا اسوارها ورمموا أسسها"));
arasuperobject.biblemap.put("b15_4_13", new arasuperobject(15,4,13,"ليكن الآن معلوما لدى الملك انه اذا بنيت هذه المدينة وأكملت اسوارها لا يؤدون جزية ولا خراجا ولا خفارة فاخيرا تضر الملوك"));
arasuperobject.biblemap.put("b15_4_14", new arasuperobject(15,4,14,"والآن بما اننا نأكل ملح دار الملك ولا يليق بنا ان نرى ضرر الملك لذلك ارسلنا فاعلمنا الملك"));
arasuperobject.biblemap.put("b15_4_15", new arasuperobject(15,4,15,"لكي يفتش في سفر اخبار آبائك فتجد في سفر الاخبار وتعلم ان هذه المدينة مدينة عاصية ومضرّة للملوك والبلاد وقد عملوا عصيانا في وسطها منذ الايام القديمة لذلك أخربت هذه المدينة"));
arasuperobject.biblemap.put("b15_4_16", new arasuperobject(15,4,16,"ونحن نعلم الملك انه اذا بنيت هذه المدينة وأكملت اسوارها لا يكون لك عند ذلك نصيب في عبر النهر"));
arasuperobject.biblemap.put("b15_4_17", new arasuperobject(15,4,17,"فارسل الملك جوابا الى رحوم صاحب القضاء وشمشاي الكاتب وسائر رفقائهما الساكنين في السامرة وباقي الذين في عبر النهر. سلام الى آخره"));
arasuperobject.biblemap.put("b15_4_18", new arasuperobject(15,4,18,"الرسالة التي ارسلتموها الينا قد قرئت بوضوح امامي"));
arasuperobject.biblemap.put("b15_4_19", new arasuperobject(15,4,19,"وقد خرج من عندي أمر ففتشوا ووجد ان هذه المدينة منذ الايام القديمة تقوم على الملوك وقد جرى فيها تمرد وعصيان"));
arasuperobject.biblemap.put("b15_4_20", new arasuperobject(15,4,20,"وقد كان ملوك مقتدرون على اورشليم وتسلطوا على جميع عبر النهر وقد أعطوا جزية وخراجا وخفارة"));
arasuperobject.biblemap.put("b15_4_21", new arasuperobject(15,4,21,"فالآن اخرجوا أمرا بتوقيف اولئك الرجال فلا تبنى هذه المدينة حتى يصدر مني أمر"));
arasuperobject.biblemap.put("b15_4_22", new arasuperobject(15,4,22,"فاحذروا من ان تقصروا عن عمل ذلك. لماذا يكثر الضرر لخسارة الملوك"));
arasuperobject.biblemap.put("b15_4_23", new arasuperobject(15,4,23,"حينئذ لما قرئت رسالة ارتحششتا الملك امام رحوم وشمشاي الكاتب ورفقائهما ذهبوا بسرعة الى اورشليم الى اليهود واوقفوهم بذراع وقوة"));
arasuperobject.biblemap.put("b15_4_24", new arasuperobject(15,4,24,"حنيئذ توقف عمل بيت الله الذي في اورشليم وكان متوقفا الى السنة الثانية من ملك داريوس ملك فارس"));
arasuperobject.biblemap.put("b15_5_1", new arasuperobject(15,5,1,"فتنبأ النبيان حجي النبي وزكريا ابن عدّو لليهود الذين في يهوذا واورشليم باسم اله اسرائيل عليهم"));
arasuperobject.biblemap.put("b15_5_2", new arasuperobject(15,5,2,"حينئذ قام زربابل بن شألتئيل ويشوع بن يوصاداق وشرعا ببنيان بيت الله الذي في اورشليم ومعهما انبياء الله يساعدونهما"));
arasuperobject.biblemap.put("b15_5_3", new arasuperobject(15,5,3,"في ذلك الزمان جاء اليهم تتناي والي عبر النهر وشتر بوزناي ورفقاؤهما وقالوا لهم هكذا. من أمركم ان تبنوا هذا البيت وتكملوا هذا السور"));
arasuperobject.biblemap.put("b15_5_4", new arasuperobject(15,5,4,"حينئذ اخبرناهم على هذا المنوال ما هي اسماء الرجال الذين يبنون هذا البناء"));
arasuperobject.biblemap.put("b15_5_5", new arasuperobject(15,5,5,"وكانت على شيوخ اليهود عين الههم فلم يوقفوهم حتى وصل الأمر الى داريوس وحينئذ جاوبوا برسالة عن هذا"));
arasuperobject.biblemap.put("b15_5_6", new arasuperobject(15,5,6,"صورة الرسالة التي ارسلها تتناي والي عبر النهر وشتر بوزناي ورفقاؤهما الافرسكيين الذين في عبر النهر الى داريوس الملك"));
arasuperobject.biblemap.put("b15_5_7", new arasuperobject(15,5,7,"ارسلوا اليه رسالة وكان مكتوبا فيها هكذا لداريوس الملك كل سلام"));
arasuperobject.biblemap.put("b15_5_8", new arasuperobject(15,5,8,"ليكن معلوما لدى الملك اننا ذهبنا الى بلاد يهوذا الى بيت الاله العظيم واذا به يبنى بحجارة عظيمة ويوضع خشب في الحيطان وهذا العمل يعمل بسرعة وينجح في ايديهم"));
arasuperobject.biblemap.put("b15_5_9", new arasuperobject(15,5,9,"حينئذ سألنا اولئك الشيوخ وقلنا لهم هكذا. من أمركم ببناء هذا البيت وتكميل هذه الاسوار"));
arasuperobject.biblemap.put("b15_5_10", new arasuperobject(15,5,10,"وسألناهم ايضا عن اسمائهم لنعلمك وكتبنا اسماء الرجال رؤوسهم"));
arasuperobject.biblemap.put("b15_5_11", new arasuperobject(15,5,11,"وبمثل هذا الجواب جاوبوا قائلين نحن عبيد اله السماء والارض ونبني هذا البيت الذي بني قبل هذه السنين الكثيرة وقد بناه ملك عظيم لاسرائيل واكمله"));
arasuperobject.biblemap.put("b15_5_12", new arasuperobject(15,5,12,"ولكن بعد ان اسخط آباؤنا اله السماء دفعهم ليد نبوخذناصّر ملك بابل الكلداني الذي هدم هذا البيت وسبى الشعب الى بابل"));
arasuperobject.biblemap.put("b15_5_13", new arasuperobject(15,5,13,"على انه في السنة الاولى لكورش ملك بابل اصدر كورش الملك أمرا ببناء بيت الله هذا"));
arasuperobject.biblemap.put("b15_5_14", new arasuperobject(15,5,14,"حتى ان آنية بيت الله هذا التي من ذهب وفضة التي اخرجها نبوخذناصّر من الهيكل الذي في اورشليم واتى بها الى الهيكل الذي في بابل اخرجها كورش الملك من الهيكل الذي في بابل وأعطيت لواحد اسمه شيشبصّر الذي جعله واليا"));
arasuperobject.biblemap.put("b15_5_15", new arasuperobject(15,5,15,"وقال له خذ هذه الآنية واذهب واحملها الى الهيكل الذي في اورشليم وليبن بيت الله في مكانه"));
arasuperobject.biblemap.put("b15_5_16", new arasuperobject(15,5,16,"حينئذ جاء شيشبصّر هذا ووضع اساس بيت الله الذي في اورشليم ومن ذلك الوقت الى الآن يبنى ولمّا يكمل"));
arasuperobject.biblemap.put("b15_5_17", new arasuperobject(15,5,17,"والآن اذا حسن عند الملك فليفتش في بيت خزائن الملك الذي هو هناك في بابل هل كان قد صدر أمر من كورش الملك ببناء بيت الله هذا في اورشليم وليرسل الملك الينا مراده في ذلك"));
arasuperobject.biblemap.put("b15_6_1", new arasuperobject(15,6,1,"حينئذ أمر داريوس الملك ففتشوا في بيت الاسفار حيث كانت الخزائن موضوعة في بابل"));
arasuperobject.biblemap.put("b15_6_2", new arasuperobject(15,6,2,"فوجد في احمثا في القصر الذي في بلاد مادي درج مكتوب فيه هكذا. تذكار"));
arasuperobject.biblemap.put("b15_6_3", new arasuperobject(15,6,3,"في السنة الاولى لكورش الملك امر كورش الملك من جهة بيت الله في اورشليم. ليبن البيت المكان الذي يذبحون فيه ذبائح ولتوضع أسسه ارتفاعه ستون ذراعا وعرضه ستون ذراعا"));
arasuperobject.biblemap.put("b15_6_4", new arasuperobject(15,6,4,"بثلاثة صفوف من حجارة عظيمة وصف من خشب جديد. ولتعط النفقة من بيت الملك"));
arasuperobject.biblemap.put("b15_6_5", new arasuperobject(15,6,5,"وايضا آنية بيت الله التي من ذهب وفضة التي اخرجها نبوخذناصّر من الهيكل الذي في اورشليم واتى بها الى بابل فلترد وترجع الى الهيكل الذي في اورشليم الى مكانها وتوضع في بيت الله"));
arasuperobject.biblemap.put("b15_6_6", new arasuperobject(15,6,6,"والآن يا تتناي والي عبر النهر وشتر بوزناي ورفقاءكما الافرسكيين الذين في عبر النهر ابتعدوا من هناك"));
arasuperobject.biblemap.put("b15_6_7", new arasuperobject(15,6,7,"اتركوا عمل بيت الله هذا. اما والي اليهود وشيوخ اليهود فليبنوا بيت الله هذا في مكانه"));
arasuperobject.biblemap.put("b15_6_8", new arasuperobject(15,6,8,"وقد صدر مني أمر بما تعملون مع شيوخ اليهود هؤلاء في بناء بيت الله هذا. فمن مال الملك من جزية عبر النهر تعط النفقة عاجلا لهؤلاء الرجال حتى لا يبطلوا"));
arasuperobject.biblemap.put("b15_6_9", new arasuperobject(15,6,9,"وما يحتاجون اليه من الثيران والكباش والخراف محرقة لاله السماء وحنطة وملح وخمر وزيت حسب قول الكهنة الذين في اورشليم لتعط لهم يوما فيوما حتى لا يهدأوا"));
arasuperobject.biblemap.put("b15_6_10", new arasuperobject(15,6,10,"عن تقريب روائح سرور لاله السماء والصلاة لاجل حياة الملك وبنيه"));
arasuperobject.biblemap.put("b15_6_11", new arasuperobject(15,6,11,"وقد صدر مني أمر ان كل انسان يغير هذا الكلام تسحب خشبة من بيته ويعلق مصلوبا عليها ويجعل بيته مزبلة من اجل هذا"));
arasuperobject.biblemap.put("b15_6_12", new arasuperobject(15,6,12,"والله الذي اسكن اسمه هناك يهلك كل ملك وشعب يمد يده لتغيير او لهدم بيت الله هذا الذي في اورشليم. انا داريوس قد أمرت فليفعل عاجلا"));
arasuperobject.biblemap.put("b15_6_13", new arasuperobject(15,6,13,"حينئذ تتناي والي عبر النهر وشتر بوزناي ورفقاؤهما عملوا عاجلا حسبما ارسل داريوس الملك"));
arasuperobject.biblemap.put("b15_6_14", new arasuperobject(15,6,14,"وكان شيوخ اليهود يبنون وينجحون حسب نبوة حجي النبي وزكريا ابن عدّو. فبنوا واكملوا حسب أمر اله اسرائيل وأمر كورش وداريوس وارتحششتا ملك فارس"));
arasuperobject.biblemap.put("b15_6_15", new arasuperobject(15,6,15,"وكمل هذا البيت في اليوم الثالث من شهر اذار في السنة السادسة من ملك داريوس الملك"));
arasuperobject.biblemap.put("b15_6_16", new arasuperobject(15,6,16,"وبنو اسرائيل الكهنة واللاويون وباقي بني السبي دشنوا بيت الله هذا بفرح"));
arasuperobject.biblemap.put("b15_6_17", new arasuperobject(15,6,17,"وقربوا تدشينا لبيت الله هذا مئة ثور ومئتي كبش واربع مئة خروف واثني عشر تيس معزى ذبيحة خطية عن جميع اسرائيل حسب عدد اسباط اسرائيل"));
arasuperobject.biblemap.put("b15_6_18", new arasuperobject(15,6,18,"واقاموا الكهنة في فرقهم واللاويين في اقسامهم على خدمة الله التي في اورشليم كما هو مكتوب في سفر موسى"));
arasuperobject.biblemap.put("b15_6_19", new arasuperobject(15,6,19,"وعمل بنو السبي الفصح في الرابع عشر من الشهر الاول"));
arasuperobject.biblemap.put("b15_6_20", new arasuperobject(15,6,20,"لان الكهنة واللاويين تطهروا جميعا. كانوا كلهم طاهرين وذبحوا الفصح لجميع بني السبي ولاخوتهم الكهنة ولانفسهم"));
arasuperobject.biblemap.put("b15_6_21", new arasuperobject(15,6,21,"وأكله بنو اسرائيل الراجعون من السبي مع جميع الذين انفصلوا اليهم من رجاسة امم الارض ليطلبوا الرب اله اسرائيل"));
arasuperobject.biblemap.put("b15_6_22", new arasuperobject(15,6,22,"وعملوا عيد الفطير سبعة ايام بفرح لان الرب فرحهم وحول قلب ملك اشور نحوهم لتقوية ايديهم في عمل بيت الله اله اسرائيل"));
arasuperobject.biblemap.put("b15_7_1", new arasuperobject(15,7,1,"وبعد هذه الأمور في ملك ارتحشستا ملك فارس عزرا بن سرايا بن عزريا بن حلقيا"));
arasuperobject.biblemap.put("b15_7_2", new arasuperobject(15,7,2,"بن شلوم بن صادوق بن اخيطوب"));
arasuperobject.biblemap.put("b15_7_3", new arasuperobject(15,7,3,"بن امريا بن عزريا بن مرايوث"));
arasuperobject.biblemap.put("b15_7_4", new arasuperobject(15,7,4,"بن زرحيا بن عزّي بن بقّي"));
arasuperobject.biblemap.put("b15_7_5", new arasuperobject(15,7,5,"بن ابيشوع بن فينحاس بن العازار بن هرون الكاهن الراس"));
arasuperobject.biblemap.put("b15_7_6", new arasuperobject(15,7,6,"عزرا هذا صعد من بابل وهو كاتب ماهر في شريعة موسى التي اعطاها الرب اله اسرائيل. واعطاه الملك حسب يد الرب الهه عليه كل سؤله"));
arasuperobject.biblemap.put("b15_7_7", new arasuperobject(15,7,7,"وصعد معه من بني اسرائيل والكهنة واللاويين والمغنيين والبوابين والنثينيم الى اورشليم في السنة السابعة لارتحشستا الملك"));
arasuperobject.biblemap.put("b15_7_8", new arasuperobject(15,7,8,"وجاء الى اورشليم في الشهر الخامس في السنة السابعة للملك"));
arasuperobject.biblemap.put("b15_7_9", new arasuperobject(15,7,9,"لانه في الشهر الاول ابتدأ يصعد من بابل وفي اول الشهر الخامس جاء الى اورشليم حسب يد الله الصالحة عليه"));
arasuperobject.biblemap.put("b15_7_10", new arasuperobject(15,7,10,"لان عزرا هيّأ قلبه لطلب شريعة الرب والعمل بها وليعلّم اسرائيل فريضة وقضاء"));
arasuperobject.biblemap.put("b15_7_11", new arasuperobject(15,7,11,"وهذه صورة الرسالة التي اعطاها الملك ارتحشستا لعزرا الكاهن الكاتب كاتب كلام وصايا الرب وفرائضه على اسرائيل"));
arasuperobject.biblemap.put("b15_7_12", new arasuperobject(15,7,12,"من ارتحشستا ملك الملوك الى عزرا الكاهن كاتب شريعة اله السماء الكامل الى آخره"));
arasuperobject.biblemap.put("b15_7_13", new arasuperobject(15,7,13,"قد صدر مني أمر ان كل من اراد في ملكي من شعب اسرائيل وكهنته واللاويين ان يرجع الى اورشليم معك فليرجع"));
arasuperobject.biblemap.put("b15_7_14", new arasuperobject(15,7,14,"من اجل انك مرسل من قبل الملك ومشيريه السبعة لاجل السؤال عن يهوذا واورشليم حسب شريعة الهك التي بيدك"));
arasuperobject.biblemap.put("b15_7_15", new arasuperobject(15,7,15,"ولحمل فضة وذهب تبرّع به الملك ومشيروه لاله اسرائيل الذي في اورشليم مسكنه"));
arasuperobject.biblemap.put("b15_7_16", new arasuperobject(15,7,16,"وكل الفضة والذهب التي تجد في كل بلاد بابل مع تبرعات الشعب والكهنة المتبرعين لبيت الههم الذي في اورشليم"));
arasuperobject.biblemap.put("b15_7_17", new arasuperobject(15,7,17,"لكي تشتري عاجلا بهذه الفضة ثيرانا وكباشا وخرافا وتقدماتها وسكائبها وتقرّبها على المذبح الذي في بيت الهكم الذي في اورشليم"));
arasuperobject.biblemap.put("b15_7_18", new arasuperobject(15,7,18,"ومهما حسن عندك وعند اخوتك ان تعملوه بباقي الفضة والذهب فحسب ارادة الهكم تعملونه"));
arasuperobject.biblemap.put("b15_7_19", new arasuperobject(15,7,19,"والآنية التي تعطى لك لاجل خدمة بيت الهك فسلمها امام اله اورشليم"));
arasuperobject.biblemap.put("b15_7_20", new arasuperobject(15,7,20,"وباقي احتياج بيت الهك الذي يتفق لك ان تعطيه فاعطه من بيت خزائن الملك"));
arasuperobject.biblemap.put("b15_7_21", new arasuperobject(15,7,21,"ومني انا ارتحشستا الملك صدر امر الى كل الخزنة الذين في عبر النهر ان كل ما يطلبه منكم عزرا الكاهن كاتب شريعة اله السماء فليعمل بسرعة"));
arasuperobject.biblemap.put("b15_7_22", new arasuperobject(15,7,22,"الى مئة وزنة من الفضة ومئة كرّ من الحنطة ومئة بث من الخمر ومئة بث من الزيت والملح من دون تقييد"));
arasuperobject.biblemap.put("b15_7_23", new arasuperobject(15,7,23,"كل ما أمر به اله السماء فليعمل باجتهاد لبيت اله السماء لانه لماذا يكون غضب على ملك الملك وبنيه"));
arasuperobject.biblemap.put("b15_7_24", new arasuperobject(15,7,24,"ونعلمكم ان جميع الكهنة واللاويين والمغنين والبوابين والنثينيم وخدام بيت الله هذا لا يؤذن ان يلقى عليهم جزية او خراج او خفارة"));
arasuperobject.biblemap.put("b15_7_25", new arasuperobject(15,7,25,"اما انت يا عزرا فحسب حكمة الهك التي بيدك ضع حكاما وقضاة يقضون لجميع الشعب الذي في عبر النهر من جميع من يعرف شرائع الهك والذين لا يعرفون فعلموهم"));
arasuperobject.biblemap.put("b15_7_26", new arasuperobject(15,7,26,"وكل من لا يعمل شريعة الهك وشريعة الملك فليقض عليه عاجلا اما بالموت او بالنفي او بغرامة المال او بالحبس"));
arasuperobject.biblemap.put("b15_7_27", new arasuperobject(15,7,27,"مبارك الرب اله آبائنا الذي جعل مثل هذا في قلب الملك لاجل تزيين بيت الرب الذي في اورشليم"));
arasuperobject.biblemap.put("b15_7_28", new arasuperobject(15,7,28,"وقد بسط عليّ رحمة امام الملك ومشيريه وامام جميع رؤساء الملك المقتدرين. واما انا فقد تشددت حسب يد الرب الهي عليّ وجمعت من اسرائيل رؤساء ليصعدوا معي"));
arasuperobject.biblemap.put("b15_8_1", new arasuperobject(15,8,1,"وهؤلاء هم رؤوس آبائهم ونسبة الذين صعدوا معي في ملك ارتحشستا الملك من بابل"));
arasuperobject.biblemap.put("b15_8_2", new arasuperobject(15,8,2,"من بني فينحاس جرشوم. من بني ايثامار دانيال. من بني داود حطوش"));
arasuperobject.biblemap.put("b15_8_3", new arasuperobject(15,8,3,"من بني شكنيا من بني فرعوش زكريا وانتسب معه من الذكور مئة وخمسون"));
arasuperobject.biblemap.put("b15_8_4", new arasuperobject(15,8,4,"من بني فحث موآب اليهوعيناي بن زرحيا ومعه مئتان من الذكور"));
arasuperobject.biblemap.put("b15_8_5", new arasuperobject(15,8,5,"من بني شكنيا ابن يحزيئيل ومعه ثلاث مئة من الذكور"));
arasuperobject.biblemap.put("b15_8_6", new arasuperobject(15,8,6,"من بني عادين عابد بن يوناثان ومعه خمسون من الذكور"));
arasuperobject.biblemap.put("b15_8_7", new arasuperobject(15,8,7,"من بني عيلام يشعيا بن عثليا ومعه سبعون من الذكور"));
arasuperobject.biblemap.put("b15_8_8", new arasuperobject(15,8,8,"ومن بني شفطيا زبديا بن ميخائيل ومعه ثمانون من الذكور"));
arasuperobject.biblemap.put("b15_8_9", new arasuperobject(15,8,9,"من بني يوآب عوبديا بن يحيئيل ومعه مئتان وثمانية عشر من الذكور"));
arasuperobject.biblemap.put("b15_8_10", new arasuperobject(15,8,10,"ومن بني شلوميث ابن يوشفيا ومعه مئة وستون من الذكور"));
arasuperobject.biblemap.put("b15_8_11", new arasuperobject(15,8,11,"ومن بني باباي زكريا بن باباي ومعه ثمانية وعشرون من الذكور"));
arasuperobject.biblemap.put("b15_8_12", new arasuperobject(15,8,12,"ومن بني عسجد يوحانان بن هقّاطان ومعه مئة وعشرة من الذكور"));
arasuperobject.biblemap.put("b15_8_13", new arasuperobject(15,8,13,"ومن بني ادونيقام الآخرين وهذه اسماؤهم اليفلط ويعيئيل وشمعيا ومعهم ستون من الذكور"));
arasuperobject.biblemap.put("b15_8_14", new arasuperobject(15,8,14,"ومن بني بغواي عوتاي وزبّود ومعهما سبعون من الذكور"));
arasuperobject.biblemap.put("b15_8_15", new arasuperobject(15,8,15,"فجمعتهم الى النهر الجاري الى اهوا ونزلنا هناك ثلاثة ايام. وتأملت الشعب والكهنة ولكنني لم اجد احدا من اللاويين هناك"));
arasuperobject.biblemap.put("b15_8_16", new arasuperobject(15,8,16,"فارسلت الى اليعزر واريئيل وشمعيا والناثان وياريب والناثان وناثان وزكريا ومشلام الرؤوس والى يوياريب والناثان الفهيمين"));
arasuperobject.biblemap.put("b15_8_17", new arasuperobject(15,8,17,"وارسلتهم الى ادّو الراس في المكان المسمى كسفيا وجعلت في افواههم كلاما يكلمون به ادّو واخوته النثينيم في المكان كسفيا ليأتوا الينا بخدام لبيت الهنا"));
arasuperobject.biblemap.put("b15_8_18", new arasuperobject(15,8,18,"فأتوا الينا حسب يد الله الصالحة علينا برجل فطن من بني محلي بن لاوي بن اسرائيل وشربيا وبنيه واخوته ثمانية عشر"));
arasuperobject.biblemap.put("b15_8_19", new arasuperobject(15,8,19,"وحشبيا ومعه يشعيا من بني مراري واخوته وبنوهم عشرون"));
arasuperobject.biblemap.put("b15_8_20", new arasuperobject(15,8,20,"ومن النثينيم الذين جعلهم داود مع الرؤساء لخدمة اللاويين من النثينيم مئتين وعشرين. الجميع تعينوا باسمائهم"));
arasuperobject.biblemap.put("b15_8_21", new arasuperobject(15,8,21,"وناديت هناك بصوم على نهر اهوا لكي نتذلل امام الهنا لنطلب منه طريقا مستقيمة لنا ولاطفالنا ولكل ما لنا"));
arasuperobject.biblemap.put("b15_8_22", new arasuperobject(15,8,22,"لاني خجلت من ان اطلب من الملك جيشا وفرسانا لينجدونا على العدو في الطريق لاننا كلمنا الملك قائلين ان يد الهنا على كل طالبيه للخير. وصولته وغضبه على كل من يتركه"));
arasuperobject.biblemap.put("b15_8_23", new arasuperobject(15,8,23,"فصمنا وطلبنا ذلك من الهنا فاستجاب لنا"));
arasuperobject.biblemap.put("b15_8_24", new arasuperobject(15,8,24,"وافرزت من رؤساء الكهنة اثني عشر شربيا وحشبيا ومعهما من اخوتهما عشرة"));
arasuperobject.biblemap.put("b15_8_25", new arasuperobject(15,8,25,"ووزنت لهم الفضة والذهب والآنية تقدمة بيت الهنا التي قدمها الملك ومشيروه ورؤساؤه وجميع اسرائيل الموجودين"));
arasuperobject.biblemap.put("b15_8_26", new arasuperobject(15,8,26,"وزنت ليدهم ست مئة وخمسين وزنة من الفضة ومئة وزنة من آنية الفضة ومئة وزنة من الذهب"));
arasuperobject.biblemap.put("b15_8_27", new arasuperobject(15,8,27,"وعشرين قدحا من الذهب الف درهم وآنية من نحاس صقيل جيد ثمين كالذهب"));
arasuperobject.biblemap.put("b15_8_28", new arasuperobject(15,8,28,"وقلت لهم انتم مقدسون للرب والآنية مقدسة والفضة والذهب تبرع للرب اله آبائكم"));
arasuperobject.biblemap.put("b15_8_29", new arasuperobject(15,8,29,"فاسهروا واحفظوها حتى تزنوها امام رؤساء الكهنة واللاويين ورؤساء آباء اسرائيل في اورشليم في مخادع بيت الرب"));
arasuperobject.biblemap.put("b15_8_30", new arasuperobject(15,8,30,"فاخذ الكهنة واللاويون وزن الفضة والذهب والآنية ليأتوا بها الى اورشليم الى بيت الهنا"));
arasuperobject.biblemap.put("b15_8_31", new arasuperobject(15,8,31,"ثم رحلنا من نهر اهوا في الثاني عشر من الشهر الاول لنذهب الى اورشليم وكانت يد الهنا علينا فانقذنا من يد العدو والكامن على الطريق"));
arasuperobject.biblemap.put("b15_8_32", new arasuperobject(15,8,32,"فأتينا الى اورشليم واقمنا هناك ثلاثة ايام"));
arasuperobject.biblemap.put("b15_8_33", new arasuperobject(15,8,33,"وفي اليوم الرابع وزنت الفضة والذهب والآنية في بيت الهنا على يد مريموث بن اوريا الكاهن ومعه العازار بن فينحاس ومعهما يوزاباد بن يشوع ونوعديا بن بنّوي اللاويان"));
arasuperobject.biblemap.put("b15_8_34", new arasuperobject(15,8,34,"بالعدد والوزن للكل وكتب كل الوزن في ذلك الوقت"));
arasuperobject.biblemap.put("b15_8_35", new arasuperobject(15,8,35,"وبنو السبي القادمون من السبي قرّبوا محرقات لاله اسرائيل اثني عشر ثورا عن كل اسرائيل وستة وتسعين كبشا وسبعة وسبعين خروفا واثني عشر تيسا ذبيحة خطية. الجميع محرقة للرب"));
arasuperobject.biblemap.put("b15_8_36", new arasuperobject(15,8,36,"واعطوا اوامر الملك لمرازبة الملك وولاة عبر النهر فاعانوا الشعب وبيت الله"));
arasuperobject.biblemap.put("b15_9_1", new arasuperobject(15,9,1,"ولما كملت هذه تقدم اليّ الرؤساء قائلين لم ينفصل شعب اسرائيل والكهنة واللاويون من شعوب الاراضي حسب رجاساتهم من الكنعانيين والحثّيين والفرزّيين واليبوسيين والعمونيين والموآبيين والمصريين والاموريين"));
arasuperobject.biblemap.put("b15_9_2", new arasuperobject(15,9,2,"لانهم اتخذوا من بناتهم لانفسهم ولبنيهم واختلط الزرع المقدس بشعوب الاراضي. وكانت يد الرؤساء والولاة في هذه الخيانة اولا"));
arasuperobject.biblemap.put("b15_9_3", new arasuperobject(15,9,3,"فلما سمعت بهذا الأمر مزقت ثيابي وردائي ونتفت شعر راسي وذقني وجلست متحيّرا"));
arasuperobject.biblemap.put("b15_9_4", new arasuperobject(15,9,4,"فاجتمع اليّ كل من ارتعد من كلام اله اسرائيل من اجل خيانة المسبيين وانا جلست متحيّرا الى تقدمة المساء"));
arasuperobject.biblemap.put("b15_9_5", new arasuperobject(15,9,5,"وعند تقدمة المساء قمت من تذللي وفي ثيابي وردائي الممزقة جثوت على ركبتيّ وبسطت يديّ الى الرب الهي"));
arasuperobject.biblemap.put("b15_9_6", new arasuperobject(15,9,6,"وقلت. اللهم اني اخجل واخزى من ان ارفع يا الهي وجهي نحوك لان ذنوبنا قد كثرت فوق رؤوسنا وآثامنا تعاظمت الى السماء"));
arasuperobject.biblemap.put("b15_9_7", new arasuperobject(15,9,7,"منذ ايام آبائنا نحن في اثم عظيم الى هذا اليوم. ولاجل ذنوبنا قد دفعنا نحن وملوكنا وكهنتنا ليد ملوك الاراضي للسيف والسبي والنهب وخزي الوجوه كهذا اليوم"));
arasuperobject.biblemap.put("b15_9_8", new arasuperobject(15,9,8,"والآن كلحيظة كانت رأفة من لدن الرب الهنا ليبقي لنا نجاة ويعطينا وتدا في مكان قدسه لينير الهنا اعيننا ويعطينا حياة قليلة في عبوديتنا"));
arasuperobject.biblemap.put("b15_9_9", new arasuperobject(15,9,9,"لاننا عبيد نحن وفي عبوديتنا لم يتركنا الهنا بل بسط علينا رحمة امام ملوك فارس ليعطينا حياة لنرفع بيت الهنا ونقيم خرائبه وليعطينا حائطا في يهوذا وفي اورشليم"));
arasuperobject.biblemap.put("b15_9_10", new arasuperobject(15,9,10,"والآن فماذا نقول يا الهنا بعد هذا لاننا قد تركنا وصاياك"));
arasuperobject.biblemap.put("b15_9_11", new arasuperobject(15,9,11,"التي اوصيت بها عن يد عبيدك الانبياء قائلا ان الارض التي تدخلون لتمتلكوها هي ارض متنجسة بنجاسة شعوب الاراضي برجاساتهم التي ملأوها بها من جهة الى جهة بنجاستهم"));
arasuperobject.biblemap.put("b15_9_12", new arasuperobject(15,9,12,"والآن فلا تعطوا بناتكم لبنيهم ولا تأخذوا بناتهم لبنيكم ولا تطلبوا سلامتهم وخيرهم الى الابد لكي تتشددوا وتاكلوا خير الارض وتورثوا بنيكم اياها الى الابد"));
arasuperobject.biblemap.put("b15_9_13", new arasuperobject(15,9,13,"وبعد كل ما جاء علينا لاجل اعمالنا الردية وآثامنا العظيمة. لانك قد جازيتنا يا الهنا اقل من آثامنا واعطيتنا نجاة كهذه"));
arasuperobject.biblemap.put("b15_9_14", new arasuperobject(15,9,14,"افنعود ونتعدّى وصاياك ونصاهر شعوب هذه الرجاسات. اما تسخط علينا حتى تفنينا فلا تكون بقية ولا نجاة"));
arasuperobject.biblemap.put("b15_9_15", new arasuperobject(15,9,15,"ايها الرب اله اسرائيل انت بار لاننا بقينا ناجين كهذا اليوم. ها نحن امامك في آثامنا لانه ليس لنا ان نقف امامك من اجل هذا"));
arasuperobject.biblemap.put("b15_10_1", new arasuperobject(15,10,1,"فلما صلّى عزرا واعترف وهو باك وساقط امام بيت الله اجتمع اليه من اسرائيل جماعة كثيرة جدا من الرجال والنساء والاولاد لان الشعب بكى بكاء عظيما"));
arasuperobject.biblemap.put("b15_10_2", new arasuperobject(15,10,2,"واجاب شكنيا بن يحيئيل من بني عيلام وقال لعزرا اننا قد خنّا الهنا واتخذنا نساء غريبة من شعوب الارض. ولكن الآن يوجد رجاء لاسرائيل في هذا"));
arasuperobject.biblemap.put("b15_10_3", new arasuperobject(15,10,3,"فلنقطع الآن عهدا مع الهنا ان نخرج كل النساء والذين ولدوا منهنّ حسب مشورة سيدي والذين يخشون وصية الهنا وليعمل حسب الشريعة"));
arasuperobject.biblemap.put("b15_10_4", new arasuperobject(15,10,4,"قم فان عليك الأمر ونحن معك. تشجع وافعل"));
arasuperobject.biblemap.put("b15_10_5", new arasuperobject(15,10,5,"فقام عزرا واستحلف رؤساء الكهنة واللاويين وكل اسرائيل ان يعملوا حسب هذا الأمر فحلفوا"));
arasuperobject.biblemap.put("b15_10_6", new arasuperobject(15,10,6,"ثم قام عزرا من امام بيت الله وذهب الى مخدع يهوحانان بن الياشيب. فانطلق الى هناك وهو لم يأكل خبزا ولم يشرب ماء لانه كان ينوح بسبب خيانة اهل السبي"));
arasuperobject.biblemap.put("b15_10_7", new arasuperobject(15,10,7,"واطلقوا نداء في يهوذا واورشليم الى جميع بني السبي لكي يجتمعوا الى اورشليم"));
arasuperobject.biblemap.put("b15_10_8", new arasuperobject(15,10,8,"وكل من لا يأتي في ثلاثة ايام حسب مشورة الرؤساء والشيوخ يحرّم كل ماله وهو يفرز من جماعة اهل السبي"));
arasuperobject.biblemap.put("b15_10_9", new arasuperobject(15,10,9,"فاجتمع كل رجال يهوذا وبنيامين الى اورشليم في الثلاثة الايام اي في الشهر التاسع في العشرين من الشهر وجلس جميع الشعب في ساحة بيت الله مرتعدين من الأمر ومن الامطار"));
arasuperobject.biblemap.put("b15_10_10", new arasuperobject(15,10,10,"فقام عزرا الكاهن وقال لهم. انكم قد خنتم واتخذتم نساء غريبة لتزيدوا على اثم اسرائيل"));
arasuperobject.biblemap.put("b15_10_11", new arasuperobject(15,10,11,"فاعترفوا الآن للرب اله آبائكم واعملوا مرضاته وانفصلوا عن شعوب الارض وعن النساء الغريبة"));
arasuperobject.biblemap.put("b15_10_12", new arasuperobject(15,10,12,"فاجاب كل الجماعة وقالوا بصوت عظيم كما كلمتنا كذلك نعمل"));
arasuperobject.biblemap.put("b15_10_13", new arasuperobject(15,10,13,"الا ان الشعب كثير والوقت وقت امطار. ولا طاقة لنا على الوقوف في الخارج والعمل ليس ليوم واحد او لاثنين لاننا قد اكثرنا الذنب في هذا الأمر"));
arasuperobject.biblemap.put("b15_10_14", new arasuperobject(15,10,14,"فليقف رؤساؤنا لكل الجماعة وكل الذين في مدننا قد اتخذوا نساء غريبة فليأتوا في اوقات معينة ومعهم شيوخ مدينة فمدينة وقضاتها حتى يرتد عنا حمو غضب الهنا من اجل هذا الأمر"));
arasuperobject.biblemap.put("b15_10_15", new arasuperobject(15,10,15,"ويوناثان بن عسائيل ويحزيا بن تقوة فقط قاما على هذا ومشلام وشبتاي اللاوي ساعداهما"));
arasuperobject.biblemap.put("b15_10_16", new arasuperobject(15,10,16,"وفعل هكذا بنو السبي وانفصل عزرا الكاهن ورجال رؤوس آباء حسب بيوت آبائهم وجميعهم باسمائهم وجلسوا في اليوم الاول من الشهر العاشر للفحص عن الأمر"));
arasuperobject.biblemap.put("b15_10_17", new arasuperobject(15,10,17,"وانتهوا من كل الرجال الذين اتخذوا نساء غريبة في اليوم الاول من الشهر الاول"));
arasuperobject.biblemap.put("b15_10_18", new arasuperobject(15,10,18,"فوجد بين بني الكهنة من اتخذ نساء غريبة. فمن بني يشوع بن يوصاداق واخوته معشيا واليعزر وياريب وجدليا"));
arasuperobject.biblemap.put("b15_10_19", new arasuperobject(15,10,19,"واعطوا ايديهم لاخراج نسائهم مقرّبين كبش غنم لاجل اثمهم"));
arasuperobject.biblemap.put("b15_10_20", new arasuperobject(15,10,20,"ومن بني امير حناني وزبديا"));
arasuperobject.biblemap.put("b15_10_21", new arasuperobject(15,10,21,"ومن بني حاريم معسيا وايليا وشمعيا ويحيئيل وعزّيا"));
arasuperobject.biblemap.put("b15_10_22", new arasuperobject(15,10,22,"ومن بني فشحور اليوعيناي ومعسيا واسماعيل ونثنئيل ويوزاباد والعاسة"));
arasuperobject.biblemap.put("b15_10_23", new arasuperobject(15,10,23,"ومن اللاويين يوزاباد وشمعي وقلايا. هو قليطا. وفتحيا ويهوذا واليعزر"));
arasuperobject.biblemap.put("b15_10_24", new arasuperobject(15,10,24,"ومن المغنين الياشيب. ومن البوابين شلوم وطالم واوري"));
arasuperobject.biblemap.put("b15_10_25", new arasuperobject(15,10,25,"ومن اسرائيل من بني فرعوش رميا ويزيا وملكيا وميامين والعازار وملكيا وبنايا"));
arasuperobject.biblemap.put("b15_10_26", new arasuperobject(15,10,26,"ومن بني عيلام متنيا وزكريا ويحيئيل وعبدي ويريموث وايليا"));
arasuperobject.biblemap.put("b15_10_27", new arasuperobject(15,10,27,"ومن بني زتو اليوعيناي والياشيب ومتنيا ويريموث وزاباد وعزيزة"));
arasuperobject.biblemap.put("b15_10_28", new arasuperobject(15,10,28,"ومن بني باباي يهوحانان وحننيا وزباي وعثلاي"));
arasuperobject.biblemap.put("b15_10_29", new arasuperobject(15,10,29,"ومن بني باني مشلام وملّوخ وعدايا وياشوب وشآل وراموث"));
arasuperobject.biblemap.put("b15_10_30", new arasuperobject(15,10,30,"ومن بني فحث موآب عدنا وكلال وبنايا ومعسيا ومتنيا وبصلئيل وبنّوي ومنسّى"));
arasuperobject.biblemap.put("b15_10_31", new arasuperobject(15,10,31,"وبنو حاريم اليعزر ويشيا وملكيا وشمعيا وشمعون"));
arasuperobject.biblemap.put("b15_10_32", new arasuperobject(15,10,32,"وبنيامين وملّوخ وشمريا"));
arasuperobject.biblemap.put("b15_10_33", new arasuperobject(15,10,33,"من بني حشوم متناي ومتّاثا وزاباد واليفلط ويريماي ومنسّى وشمعي"));
arasuperobject.biblemap.put("b15_10_34", new arasuperobject(15,10,34,"من بني باني معداي وعمرام واوئيل"));
arasuperobject.biblemap.put("b15_10_35", new arasuperobject(15,10,35,"وبنايا وبيديا وكلوهي"));
arasuperobject.biblemap.put("b15_10_36", new arasuperobject(15,10,36,"وونيا ومريموث والياشيب"));
arasuperobject.biblemap.put("b15_10_37", new arasuperobject(15,10,37,"ومتنيا ومتناي ويعسو"));
arasuperobject.biblemap.put("b15_10_38", new arasuperobject(15,10,38,"وباني وبنوي وشمعي"));
arasuperobject.biblemap.put("b15_10_39", new arasuperobject(15,10,39,"وشلميا وناثان وعدايا"));
arasuperobject.biblemap.put("b15_10_40", new arasuperobject(15,10,40,"ومكندباي وشاشاي وشاراي"));
arasuperobject.biblemap.put("b15_10_41", new arasuperobject(15,10,41,"وعزرئيل وشلميا وشمريا"));
arasuperobject.biblemap.put("b15_10_42", new arasuperobject(15,10,42,"وشلوم وامريا ويوسف"));
arasuperobject.biblemap.put("b15_10_43", new arasuperobject(15,10,43,"من بني نبو يعيئيل ومتّثيا وزاباد وزبينا ويدو ويوئيل وبنايا"));
arasuperobject.biblemap.put("b15_10_44", new arasuperobject(15,10,44,"كل هؤلاء اتخذوا نساء غريبة ومنهنّ نساء قد وضعن بنين"));

}

}