package biblegenertor;
public class names {
	
	public static String thnames[] = {
		"คัมภีร์ไบเบิล",
		"ทางออก",
		"บท",
		"หนังสือ",
		"พินัยกรรม",
		"ข้อความ",
		"เลือก",
		"พันธสัญญาเดิม",
		"พันธสัญญาใหม่",
		"สดุดี",
		"พระเยซู"
		};	
			
		public static String thbible[] = {
			"ปฐมกาล",
			"อพยพ",
			"เลวีนิติ ",
			"กันดารวิถี",
			"เฉลยธรมบัญญัติ",
			"โยชูวา",
			"ผู้วินิจฉัย ",
			"นางรูธ ",
			"1 ซามูเอล ",
			"2 ซามูเอล ",
			"1 พงศ์กษัตริย์ ",
			"2 พงศ์กษัตริย์ ",
			"1 พงศาวดาร",
			"2 พงศาวดาร ",
			"เอสรา ",
			"เนหะมีย์ ",
			"เอสเธอร์",
			"โยบ",
			"สดุดี ",
			"สุภาษิต ",
			"ปัญญาจารย์ ",
			"เพลงซาโลมอน",
			"อิสยาห์ ",
			"เยเรมีย์",
			"เพลงคร่ำครวญ ",
			"เอเสเคียล",
			"ดาเนียล",
			"โฮเชยา",
			"โยเอล",
			"อาโมส",
			"โอบาดีย์",
			"โยนาห์",
			"มีคาห์",
			"นาฮูม",
			"ฮะบากุก",
			"เศฟันยาห์",
			"ฮักกัย",
			"เศคาริยาห์",
			"มาลาคี",
			"มัทธิว ",
			"มาระโก ",
			"ลูกา ",
			"ยอห์น ",
			"กิจการของอัครทูต",
			"โรม ",
			"1 โครินธ์ ",
			"2 โครินธ์ ",
			"กาลาเทีย ",
			"เอเฟซัส ",
			"ฟิลิปปี ",
			"โคโลสี ",
			"1 เธสะโลนิกา ",
			"2 เธสะโลนิกา ",
			"1 ทิโมธี ",
			"2 ทิโมธี ",
			"ทิตัส ",
			"ฟีเลโมน",
			"ฮีบรู ",
			"ยากอบ ",
			"1 เปโตร ",
			"2 เปโตร ",
			"1 ยอห์น ",
			"2 ยอห์น ",
			"3 ยอห์น ",
			"ยูดา",
			"วิวรณ์"
		};	
	
	public static String hunames[] = {
		"Szent Biblia",
		"kilépés",
		"fejezet",
		"könyv",
		"végrendelet",
		"szöveg",
		"választ",
		"Ószövetség",
		"Újszövetség",
		"zsoltár",
		"evangélium"
		};

		public static String hubible[] = {
		"Mózes első könyve",
		"Mózes második könyve",
		"Mózes harmadik könyve",
		"Mózes negyedik könyve",
		"Mózes ötödik könyve",
		"Józsué - Joshua",
		"A bírák - Judges",
		"Ruth",
		"Sámuel első - 1 Samuel",
		"Sámuel második - 2 Samuel",
		"A királyok első - 1 Kings",
		"A királyok második - 2 Kings",
		"A krónikák első - 1 Chronicles",
		"A krónikák második - 2 Chronicles",
		"Ezsdrás - Ezra",
		"Nehémiás - Nehemiah",
		"Eszter - Esther",
		"Jób - Job",
		"A zsoltárok - Psalms",
		"A példabeszédek - Proverbs",
		"A prédikátor - Ecclesiastes",
		"Énekek - Songs of Solomon",
		"Ézsaiás - Isaiah",
		"Jeremiás - Jeremiah",
		"Jeremiás siralmai - Lamentaions",
		"Ezékiel - Ezekiel",
		"Dániel - Daniel",
		"Hóseás - Hosea",
		"Jóel - Joel",
		"Ámósz - Amos",
		"Abdiás - Obadiah",
		"Jónás - Jonah",
		"Mikeás - Micah",
		"Náhum - Nahum",
		"Habakuk - Habakkuk",
		"Zofóniás - Zephaniah",
		"Haggeus - Haggai",
		"Zakariás - Zechariah",
		"Malakiás - Malachi",
		"Máté - Matthew",
		"Márk - Mark",
		"Lukács - Luke",
		"János - John",
		"Az apostolok cselekedetei - Acts",
		"Rómaiakhoz - Romans",
		"1 korinthusiakhoz - 1 Corinthians",
		"2 korinthusiakhoz - 2 Corinthians",
		"Galatákhoz - Galatians",
		"Efezusiakhoz - Ephesians",
		"Filippiekhez - Philippians",
		"Kolosséiakhoz - Colossians",
		"1 Thesszalonikaiakhoz - 1 Thessalonians",
		"2 Thesszalonikaiakhoz - 2 Thessalonians",
		"1 Timóteushoz - 1 Timothy",
		"2 Timóteushoz - 2 Timothy",
		"Tituszhoz",
		"Filemonhoz - Philemon",
		"Zsidókhoz - Hebrews",
		"Jakab - James",
		"Péter első - 1 Peter",
		"Péter második - 2 Peter",
		"János első - 1 John",
		"János második - 2 John",
		"János harmadik - 3 John",
		"Júdás - Jude",
		"Jelenések könyve - Revelation"
		};

	
	public static String vinames[] = {
		"Kinh Thánh",
		"ra",
		"chương",
		"cuốn sách",
		"di chúc",
		"văn bản",
		"chọn",
		"Cựu Ước",
		"Tân Ước",
		"thánh thi",
		"Tin Mừng"
		};

		public static String vibible[] = {

		"Sáng-thế Ký",
		"Xuất Ê-díp-tô Ký",
		"Lê-vi Ký",
		"Dân-số Ký",
		"Phục-truyền Luật-lệ Ký",
		"Giô-suê",
		"Các Quan Xét",
		"Ru-tơ",
		"1 Sa-mu-ên",
		"2 Sa-mu-ên",
		"1 Các Vua",
		"2 Các Vua",
		"1 Sử-ký",
		"2 Sử-ký",
		"Ê-xơ-ra",
		"Nê-hê-mi",
		"Ê-xơ-tê",
		"Gióp",
		"Thi-thiên",
		"Châm-ngôn",
		"Truyền-đạo",
		"Nhã-ca",
		"Ê-sai",
		"Giê-rê-mi",
		"Ca-thương",
		"Ê-xê-chi-ên",
		"Đa-ni-ên",
		"Ô-sê",
		"Giô-ên",
		"A-mốt",
		"Áp-đia",
		"Giô-na",
		"Mi-chê",
		"Na-hum",
		"Ha-ba-cúc",
		"Sô-phô-ni",
		"A-ghê",
		"Xa-cha-ri",
		"Ma-la-chi",
		"Ma-thi-ơ",
		"Mác",
		"Lu-ca",
		"Giăng",
		"Công-vụ các Sứ-đồ",
		"Rô-ma",
		"1 Cô-rinh-tô",
		"2 Cô-rinh-tô",
		"Ga-la-ti",
		"Ê-phê-sô",
		"Phi-líp",
		"Cô-lô-se",
		"1 Tê-sa-lô-ni-ca",
		"2 Tê-sa-lô-ni-ca",
		"1 Ti-mô-thê",
		"2 Ti-mô-thê",
		"Tít",
		"Phi-lê-môn",
		"Hê-bơ-rơ",
		"Gia-cơ",
		"1 Phi-e-rơ",
		"2 Phi-e-rơ",
		"1 Giăng",
		"2 Giăng",
		"3 Giăng",
		"Giu-đe",
		"Khải-huyền"

		};
	

	public static String dunames[] = {
		"Bijbel",
		"uitgang",
		"hoofdstuk",
		"boek",
		"testament",
		"tekst",
		"kiezen",
		"Oude Testament",
		"Nieuwe Testament",
		"PSALM",
		"Evangelie",
		"vinden"
		};

		public static String dubible[] = {

		"Genesis",
		"Exodus",
		"Leviticus",
		"Numberi",
		"Deuteronomium",
		"Jozua",
		"Richtere",
		"Ruth",
		"1 Samuël",
		"2 Samuël",
		"1 Koningen",
		"2 Koningen",
		"1 Kronieken",
		"2 Kronieken",
		"Ezra",
		"Nehemia",
		"Esther",
		"Job",
		"Psalmen",
		"Spreuken",
		"Prediker",
		"Hooglied",
		"Jesaja",
		"Jeremia",
		"Klaagliederen",
		"Ezechiël",
		"Daniël",
		"Hosea",
		"Joël",
		"Amos",
		"Obadja",
		"Jona",
		"Micha",
		"Nahum",
		"Habakuk",
		"Zefanja",
		"Haggaï",
		"Zacharia",
		"Maleachi",
		"Mattheüs",
		"Markus",
		"Lukas",
		"Johannes",
		"Handelingen",
		"Romeinen",
		"1 Corinthiërs",
		"2 Corinthiër",
		"Galaten",
		"Efeziërs",
		"Filippenzen",
		"Colossenzen",
		"1 Thessalonicenzen",
		"2 Thessalonicenzen",
		"1 Timotheüs",
		"2 Timotheüs",
		"Titus",
		"Filémon",
		"Hebreeën",
		"Jakobus",
		"1 Petrus",
		"2 Petrus",
		"1 Johannes",
		"2 Johannes",
		"3 Johannes",
		"Judas",
		"Openbaring"
		};	
	
	public static String tamnames[] = {
		"பரிசுத்த வேதாகமம்",
		"வெளியேறும்",
		"அத்தியாயம்",
		"புத்தகம்",
		"உயில்",
		"உரை",
		"தேர்வு",
		"பழைய ஏற்பாடு",
		"புதிய ஏற்பாடு",
		"சங்கீதம்",
		"நற்செய்தி",
		"கண்டுபிடித்து"
		};

		public static String tambible[] = {
		"ஆதியாகமம்",
		"யாத்திராகமம்",
		"லேவியராகமம்",
		"எண்ணாகமம்",
		"உபாகமம்",
		"யோசுவா",
		"நியாயாதிபதிகள்",
		"ரூத்",
		"1 சாமுவேல்",
		"2 சாமுவேல்",
		"1 இராஜாக்கள்",
		"2 இராஜாக்கள்",
		"1 நாளாகமம்",
		"2 நாளாகமம்",
		"எஸ்றா",
		"நெகேமியா",
		"எஸ்தர்",
		"யோபு",
		"சங்கீதம்",
		"நீதிமொழிகள்",
		"பிரசங்கி",
		"உன்னதப்பாட்டு",
		"ஏசாயா",
		"எரேமியா",
		"புலம்பல்",
		"எசேக்கியேல்",
		"தானியேல்",
		"ஓசியா",
		"யோவேல்",
		"ஆமோஸ்",
		"ஒபதியா",
		"யோனா",
		"மீகா",
		"நாகூம்",
		"ஆபகூக்",
		"செப்பனியா",
		"ஆகாய்",
		"சகரியா",
		"மல்கியா",
		"மத்தேயு",
		"மாற்கு",
		"லுூக்கா",
		"யோவான்",
		"அப்போஸ்தலருடைய நடபடிகள்",
		"ரோமர்",
		"1 கொரிந்தியர்",
		"2 கொரிந்தியர்",
		"கலாத்தியர்",
		"எபேசியர்",
		"பிலிப்பியர்",
		"கொலோசெயர்",
		"1 தெசலோனிக்கேயர்",
		"2 தெசலோனிக்கேயர்",
		"1 தீமோத்தேயு",
		"2 தீமோத்தேயு",
		"தீத்து",
		"பிலேமோன்",
		"எபிரெயர்",
		"யாக்கோபு",
		"1 பேதுரு",
		"2 பேதுரு",
		"1 யோவான்",
		"2 யோவான்",
		"3 யோவான்",
		"யூதா",
		"வெளிப்படுத்தின விசேஷம்"
		};
	
public static String konames[] = {
"성경",
"아웃",
"머리",
"도서",
"규약",
"텍스트",
"선택",
"구약 성서",
"신약 성경",
"시",
"복음",
"찾기"
};

public static String kobible[] = {
"창세기",
"출애굽기",
"레위기",
"민수기",
"신명기",
"여호수아",
"사사기",
"룻기",
"사무엘상",
"사무엘하",
"열왕기상",
"열왕기하",
"역대상",
"역대하",
"에스라",
"느헤미야",
"에스더",
"욥기",
"시편",
"잠언",
"전도서",
"아가",
"이사야",
"예레미야",
"예레미야 애가",
"에스겔",
"다니엘",
"호세아",
"요엘",
"아모스",
"오바댜",
"요나",
"미가",
"나훔",
"하박국",
"스바냐",
"학개",
"스가랴",
"말라기",
"마태복음",
"마가복음",
"누가복음",
"요한복음",
"사도행전",
"로마서",
"고린도전서",
"고린도후서",
"갈라디아서",
"에베소서",
"빌립보서",
"골로새서",
"데살로니가전서",
"데살로니가후서",
"디모데전서",
"디모데후서",
"디도서",
"빌레몬서",
"히브리서",
"야고보서",
"베드로전서",
"베드로후서",
"요한1서",
"요한2서",
"요한3서",
"유다서",
"요한계시록"
};

	
	public static String japnames[] = {
		"日本聖書",
		"終了する",
		"章",
		"本",
		"聖書",
		"テキスト",
		"選択する",
		"旧約聖書",
		"新約聖書",
		"賛美歌",
		"共観福音書",
		"見つける"
};
	
public static String japbible[] = {
	"創世記",
	"出エジプト記",
	"レビ記",
	"民数記",
	"申命記",
	"ヨシュア記",
	"士師記",
	"ルツ記",
	"サムエル記上",
	"サムエル記下",
	"列王記上",
	"列王記下",
	"代誌上",
	"歴代誌下",
	"エズラ記",
	"ネヘミヤ記",
	"エステル記",
	"ヨブ記",
	"詩編",
	"箴言",
	"コヘレトの言葉",
	"雅歌",
	"イザヤ記",
	"エレミヤ記",
	"哀歌",
	"エゼキエル記",
	"ダニエル記",
	"ホセア記",
	"ヨエル記",
	"アモス記",
	"オバデア記",
	"ヨナ記",
	"ミカ記",
	"ナホム記",
	"ハバクク記",
	"ゼファニヤ記",
	"ハガイ記",
	"ゼカリヤ記",
	"マラキ記",
	"マタイによる福音書",
	"マルコによる福音書",
	"ルカによる福音書",
	"ヨハネによる福音書",
	"使徒言行録",
	"ローマの信徒への手紙",
	"コリントの信徒への手紙一",
	"コリントの信徒への手紙二",
	"ガラテヤの信徒への手紙",
	"エフェソの信徒への手紙",
	"フィリピの信徒への手紙",
	"コロサイの信徒への手紙",
	"テサロニケの信徒への手紙一",
	"テサロニケの信徒への手紙二",
	"テモテへの手紙一",
	"テモテへの手紙二",
	"テトスへの手紙",
	"フィレモンへの手紙",
	"ヘブライ人への手紙",
	"ヤコブの手紙",
	"ペトロの手紙一",
	"ペトロの手紙二",
	"ヨハネの手紙一",
	"ヨハネの手紙二",
	"ヨハネの手紙三",
	"ユダの手紙",
	"ヨハネの黙示録"
};

	
	public static String hinnames[] = {
		"पवित्र बाइबिल",
		"बाहर",
		"अध्याय",
		"किताब",
		"टैस्टमैंट",
		"पाठ",
		"चुनें",
		"ओल्ड टैस्टमैंट",
		"नई टैस्टमैंट",
		"भजन",
		"इंजील",
		"खोज"
		};

	public static String aranames[] = {
		"الكتاب المقدس",
		"نفاد",
		"رئيس",
		"كتاب",
		"العهد",
		"نص",
		"اختر",
		"العهد القديم",
		"العهد الجديد",
		"مزمور",
		"إنجيل",
		"البحث"
		};
	
	public static String hebnames[] = {
		"הקודש במקרא",
		"יציאה",
		"פרק",
		"ספר",
		"צוואה",
		"טקסט",
		"יבחר",
		"תנ'ך",
		"ברית חדשה",
		"תהילים",
		"הבשורות ",
		"למצוא"
		};
	
public static String runames[] = {
"Библия",
"выход",
"глава",
"книга",
"завет",
"текст",
"выбрать",
"Ветхий Завет",
"Новый Завет",
"псалом",
"Евангелие",
"найти"
};

public static String ennames[] = {
"The Bible",
"exit",
"chapter",
"book",
"testament",
"text",
"choose",
"Old Testament",
"New Testament",
"PSALM",
"Gospel",

};

public static String denames[] = {
"Bibel",
"ausgang",
"kapitel",
"buchen",
"testament",
"text",
"wählen",
"Altes Testament",
"Neues Testament",
"Psalmen",
"Evangelium",

};

public static String esnames[] = {
"Biblia",
"de salida",
"capítulo",
"libro",
"testamento",
"texto",
"seleccione",
"Antiguo Testamento",
"Nuevo Testamento",
"SALMO",
"Evangelio",

};

public static String frnames[] = {
"La Bible",
"de sortie",
"chapitre",
"livre",
"testament",
"texte",
"sélectionnez",
"L'Ancien Testament",
"Le Nouveau Testament",
"PSAUME",
"Évangile",

};

public static String itnames[] = {
"Bibbia",
"di uscita",
"capitolo",
"libro",
"testamento",
"testo",
"selezionare",
"Antico Testamento",
"Nuovo Testamento",
"SALMO",
"Vangelo",

};

public static String trnames[] = {
"Kutsal Kitap",
"çıktı",
"bölüm",
"kitap",
"antlaşma",
"metin",
"seçin",
"Eski Antlaşma",
"Yeni Antlaşma",
"MEZMUR",
"İncil",

};

public static String ptnames[] = {
"Bíblia",
"saída",
"capítulo",
"livro",
"testamento",
"texto",
"selecione",
"Velho Testamento",
"Novo Testamento",
"SALMO",
"Evangelho",

};

public static String grnames[] = {
"Αγία Γραφή",
"εξόδου",
"kεφάλαιο",
"bιβλίο",
"Διαθήκη",
"κείμενο",
"επιλέξτε",
"Παλαιά Διαθήκη",
"Καινή Διαθήκη",
"ΨAΛMOΣ",
"Ευαγγέλιο",

};


public static String zhnames[] = {
"简体中文和合本",
"输出",
"章",
"图书",
"约全书",
"文本",
"选择",
"旧约全书",
"新约全书",
"章",
"福音书",

};

String names() {
return "test";
}

}


