package heb.bible;

public class hebbible21 {

public hebbible21() {

putmapbible21();

}

private void putmapbible21() {

hebsuperobject.biblemap.put("b21_1_1", new hebsuperobject(21,1,1,"דברי קהלת בן דוד מלך בירושלם׃"));
hebsuperobject.biblemap.put("b21_1_2", new hebsuperobject(21,1,2,"הבל הבלים אמר קהלת הבל הבלים הכל הבל׃"));
hebsuperobject.biblemap.put("b21_1_3", new hebsuperobject(21,1,3,"מה יתרון לאדם בכל עמלו שיעמל תחת השמש׃"));
hebsuperobject.biblemap.put("b21_1_4", new hebsuperobject(21,1,4,"דור הלך ודור בא והארץ לעולם עמדת׃"));
hebsuperobject.biblemap.put("b21_1_5", new hebsuperobject(21,1,5,"וזרח השמש ובא השמש ואל מקומו שואף זורח הוא שם׃"));
hebsuperobject.biblemap.put("b21_1_6", new hebsuperobject(21,1,6,"הולך אל דרום וסובב אל צפון סובב סבב הולך הרוח ועל סביבתיו שב הרוח׃"));
hebsuperobject.biblemap.put("b21_1_7", new hebsuperobject(21,1,7,"כל הנחלים הלכים אל הים והים איננו מלא אל מקום שהנחלים הלכים שם הם שבים ללכת׃"));
hebsuperobject.biblemap.put("b21_1_8", new hebsuperobject(21,1,8,"כל הדברים יגעים לא יוכל איש לדבר לא תשבע עין לראות ולא תמלא אזן משמע׃"));
hebsuperobject.biblemap.put("b21_1_9", new hebsuperobject(21,1,9,"מה שהיה הוא שיהיה ומה שנעשה הוא שיעשה ואין כל חדש תחת השמש׃"));
hebsuperobject.biblemap.put("b21_1_10", new hebsuperobject(21,1,10,"יש דבר שיאמר ראה זה חדש הוא כבר היה לעלמים אשר היה מלפננו׃"));
hebsuperobject.biblemap.put("b21_1_11", new hebsuperobject(21,1,11,"אין זכרון לראשנים וגם לאחרנים שיהיו לא יהיה להם זכרון עם שיהיו לאחרנה׃"));
hebsuperobject.biblemap.put("b21_1_12", new hebsuperobject(21,1,12,"אני קהלת הייתי מלך על ישראל בירושלם׃"));
hebsuperobject.biblemap.put("b21_1_13", new hebsuperobject(21,1,13,"ונתתי את לבי לדרוש ולתור בחכמה על כל אשר נעשה תחת השמים הוא ענין רע נתן אלהים לבני האדם לענות בו׃"));
hebsuperobject.biblemap.put("b21_1_14", new hebsuperobject(21,1,14,"ראיתי את כל המעשים שנעשו תחת השמש והנה הכל הבל ורעות רוח׃"));
hebsuperobject.biblemap.put("b21_1_15", new hebsuperobject(21,1,15,"מעות לא יוכל לתקן וחסרון לא יוכל להמנות׃"));
hebsuperobject.biblemap.put("b21_1_16", new hebsuperobject(21,1,16,"דברתי אני עם לבי לאמר אני הנה הגדלתי והוספתי חכמה על כל אשר היה לפני על ירושלם ולבי ראה הרבה חכמה ודעת׃"));
hebsuperobject.biblemap.put("b21_1_17", new hebsuperobject(21,1,17,"ואתנה לבי לדעת חכמה ודעת הוללות ושכלות ידעתי שגם זה הוא רעיון רוח׃"));
hebsuperobject.biblemap.put("b21_1_18", new hebsuperobject(21,1,18,"כי ברב חכמה רב כעס ויוסיף דעת יוסיף מכאוב׃"));
hebsuperobject.biblemap.put("b21_2_1", new hebsuperobject(21,2,1,"אמרתי אני בלבי לכה נא אנסכה בשמחה וראה בטוב והנה גם הוא הבל׃"));
hebsuperobject.biblemap.put("b21_2_2", new hebsuperobject(21,2,2,"לשחוק אמרתי מהולל ולשמחה מה זה עשה׃"));
hebsuperobject.biblemap.put("b21_2_3", new hebsuperobject(21,2,3,"תרתי בלבי למשוך ביין את בשרי ולבי נהג בחכמה ולאחז בסכלות עד אשר אראה אי זה טוב לבני האדם אשר יעשו תחת השמים מספר ימי חייהם׃"));
hebsuperobject.biblemap.put("b21_2_4", new hebsuperobject(21,2,4,"הגדלתי מעשי בניתי לי בתים נטעתי לי כרמים׃"));
hebsuperobject.biblemap.put("b21_2_5", new hebsuperobject(21,2,5,"עשיתי לי גנות ופרדסים ונטעתי בהם עץ כל פרי׃"));
hebsuperobject.biblemap.put("b21_2_6", new hebsuperobject(21,2,6,"עשיתי לי ברכות מים להשקות מהם יער צומח עצים׃"));
hebsuperobject.biblemap.put("b21_2_7", new hebsuperobject(21,2,7,"קניתי עבדים ושפחות ובני בית היה לי גם מקנה בקר וצאן הרבה היה לי מכל שהיו לפני בירושלם׃"));
hebsuperobject.biblemap.put("b21_2_8", new hebsuperobject(21,2,8,"כנסתי לי גם כסף וזהב וסגלת מלכים והמדינות עשיתי לי שרים ושרות ותענוגת בני האדם שדה ושדות׃"));
hebsuperobject.biblemap.put("b21_2_9", new hebsuperobject(21,2,9,"וגדלתי והוספתי מכל שהיה לפני בירושלם אף חכמתי עמדה לי׃"));
hebsuperobject.biblemap.put("b21_2_10", new hebsuperobject(21,2,10,"וכל אשר שאלו עיני לא אצלתי מהם לא מנעתי את לבי מכל שמחה כי לבי שמח מכל עמלי וזה היה חלקי מכל עמלי׃"));
hebsuperobject.biblemap.put("b21_2_11", new hebsuperobject(21,2,11,"ופניתי אני בכל מעשי שעשו ידי ובעמל שעמלתי לעשות והנה הכל הבל ורעות רוח ואין יתרון תחת השמש׃"));
hebsuperobject.biblemap.put("b21_2_12", new hebsuperobject(21,2,12,"ופניתי אני לראות חכמה והוללות וסכלות כי מה האדם שיבוא אחרי המלך את אשר כבר עשוהו׃"));
hebsuperobject.biblemap.put("b21_2_13", new hebsuperobject(21,2,13,"וראיתי אני שיש יתרון לחכמה מן הסכלות כיתרון האור מן החשך׃"));
hebsuperobject.biblemap.put("b21_2_14", new hebsuperobject(21,2,14,"החכם עיניו בראשו והכסיל בחשך הולך וידעתי גם אני שמקרה אחד יקרה את כלם׃"));
hebsuperobject.biblemap.put("b21_2_15", new hebsuperobject(21,2,15,"ואמרתי אני בלבי כמקרה הכסיל גם אני יקרני ולמה חכמתי אני אז יותר ודברתי בלבי שגם זה הבל׃"));
hebsuperobject.biblemap.put("b21_2_16", new hebsuperobject(21,2,16,"כי אין זכרון לחכם עם הכסיל לעולם בשכבר הימים הבאים הכל נשכח ואיך ימות החכם עם הכסיל׃"));
hebsuperobject.biblemap.put("b21_2_17", new hebsuperobject(21,2,17,"ושנאתי את החיים כי רע עלי המעשה שנעשה תחת השמש כי הכל הבל ורעות רוח׃"));
hebsuperobject.biblemap.put("b21_2_18", new hebsuperobject(21,2,18,"ושנאתי אני את כל עמלי שאני עמל תחת השמש שאניחנו לאדם שיהיה אחרי׃"));
hebsuperobject.biblemap.put("b21_2_19", new hebsuperobject(21,2,19,"ומי יודע החכם יהיה או סכל וישלט בכל עמלי שעמלתי ושחכמתי תחת השמש גם זה הבל׃"));
hebsuperobject.biblemap.put("b21_2_20", new hebsuperobject(21,2,20,"וסבותי אני ליאש את לבי על כל העמל שעמלתי תחת השמש׃"));
hebsuperobject.biblemap.put("b21_2_21", new hebsuperobject(21,2,21,"כי יש אדם שעמלו בחכמה ובדעת ובכשרון ולאדם שלא עמל בו יתננו חלקו גם זה הבל ורעה רבה׃"));
hebsuperobject.biblemap.put("b21_2_22", new hebsuperobject(21,2,22,"כי מה הוה לאדם בכל עמלו וברעיון לבו שהוא עמל תחת השמש׃"));
hebsuperobject.biblemap.put("b21_2_23", new hebsuperobject(21,2,23,"כי כל ימיו מכאבים וכעס ענינו גם בלילה לא שכב לבו גם זה הבל הוא׃"));
hebsuperobject.biblemap.put("b21_2_24", new hebsuperobject(21,2,24,"אין טוב באדם שיאכל ושתה והראה את נפשו טוב בעמלו גם זה ראיתי אני כי מיד האלהים היא׃"));
hebsuperobject.biblemap.put("b21_2_25", new hebsuperobject(21,2,25,"כי מי יאכל ומי יחוש חוץ ממני׃"));
hebsuperobject.biblemap.put("b21_2_26", new hebsuperobject(21,2,26,"כי לאדם שטוב לפניו נתן חכמה ודעת ושמחה ולחוטא נתן ענין לאסוף ולכנוס לתת לטוב לפני האלהים גם זה הבל ורעות רוח׃"));
hebsuperobject.biblemap.put("b21_3_1", new hebsuperobject(21,3,1,"לכל זמן ועת לכל חפץ תחת השמים׃"));
hebsuperobject.biblemap.put("b21_3_2", new hebsuperobject(21,3,2,"עת ללדת ועת למות עת לטעת ועת לעקור נטוע׃"));
hebsuperobject.biblemap.put("b21_3_3", new hebsuperobject(21,3,3,"עת להרוג ועת לרפוא עת לפרוץ ועת לבנות׃"));
hebsuperobject.biblemap.put("b21_3_4", new hebsuperobject(21,3,4,"עת לבכות ועת לשחוק עת ספוד ועת רקוד׃"));
hebsuperobject.biblemap.put("b21_3_5", new hebsuperobject(21,3,5,"עת להשליך אבנים ועת כנוס אבנים עת לחבוק ועת לרחק מחבק׃"));
hebsuperobject.biblemap.put("b21_3_6", new hebsuperobject(21,3,6,"עת לבקש ועת לאבד עת לשמור ועת להשליך׃"));
hebsuperobject.biblemap.put("b21_3_7", new hebsuperobject(21,3,7,"עת לקרוע ועת לתפור עת לחשות ועת לדבר׃"));
hebsuperobject.biblemap.put("b21_3_8", new hebsuperobject(21,3,8,"עת לאהב ועת לשנא עת מלחמה ועת שלום׃"));
hebsuperobject.biblemap.put("b21_3_9", new hebsuperobject(21,3,9,"מה יתרון העושה באשר הוא עמל׃"));
hebsuperobject.biblemap.put("b21_3_10", new hebsuperobject(21,3,10,"ראיתי את הענין אשר נתן אלהים לבני האדם לענות בו׃"));
hebsuperobject.biblemap.put("b21_3_11", new hebsuperobject(21,3,11,"את הכל עשה יפה בעתו גם את העלם נתן בלבם מבלי אשר לא ימצא האדם את המעשה אשר עשה האלהים מראש ועד סוף׃"));
hebsuperobject.biblemap.put("b21_3_12", new hebsuperobject(21,3,12,"ידעתי כי אין טוב בם כי אם לשמוח ולעשות טוב בחייו׃"));
hebsuperobject.biblemap.put("b21_3_13", new hebsuperobject(21,3,13,"וגם כל האדם שיאכל ושתה וראה טוב בכל עמלו מתת אלהים היא׃"));
hebsuperobject.biblemap.put("b21_3_14", new hebsuperobject(21,3,14,"ידעתי כי כל אשר יעשה האלהים הוא יהיה לעולם עליו אין להוסיף וממנו אין לגרע והאלהים עשה שיראו מלפניו׃"));
hebsuperobject.biblemap.put("b21_3_15", new hebsuperobject(21,3,15,"מה שהיה כבר הוא ואשר להיות כבר היה והאלהים יבקש את נרדף׃"));
hebsuperobject.biblemap.put("b21_3_16", new hebsuperobject(21,3,16,"ועוד ראיתי תחת השמש מקום המשפט שמה הרשע ומקום הצדק שמה הרשע׃"));
hebsuperobject.biblemap.put("b21_3_17", new hebsuperobject(21,3,17,"אמרתי אני בלבי את הצדיק ואת הרשע ישפט האלהים כי עת לכל חפץ ועל כל המעשה שם׃"));
hebsuperobject.biblemap.put("b21_3_18", new hebsuperobject(21,3,18,"אמרתי אני בלבי על דברת בני האדם לברם האלהים ולראות שהם בהמה המה להם׃"));
hebsuperobject.biblemap.put("b21_3_19", new hebsuperobject(21,3,19,"כי מקרה בני האדם ומקרה הבהמה ומקרה אחד להם כמות זה כן מות זה ורוח אחד לכל ומותר האדם מן הבהמה אין כי הכל הבל׃"));
hebsuperobject.biblemap.put("b21_3_20", new hebsuperobject(21,3,20,"הכל הולך אל מקום אחד הכל היה מן העפר והכל שב אל העפר׃"));
hebsuperobject.biblemap.put("b21_3_21", new hebsuperobject(21,3,21,"מי יודע רוח בני האדם העלה היא למעלה ורוח הבהמה הירדת היא למטה לארץ׃"));
hebsuperobject.biblemap.put("b21_3_22", new hebsuperobject(21,3,22,"וראיתי כי אין טוב מאשר ישמח האדם במעשיו כי הוא חלקו כי מי יביאנו לראות במה שיהיה אחריו׃"));
hebsuperobject.biblemap.put("b21_4_1", new hebsuperobject(21,4,1,"ושבתי אני ואראה את כל העשקים אשר נעשים תחת השמש והנה דמעת העשקים ואין להם מנחם ומיד עשקיהם כח ואין להם מנחם׃"));
hebsuperobject.biblemap.put("b21_4_2", new hebsuperobject(21,4,2,"ושבח אני את המתים שכבר מתו מן החיים אשר המה חיים עדנה׃"));
hebsuperobject.biblemap.put("b21_4_3", new hebsuperobject(21,4,3,"וטוב משניהם את אשר עדן לא היה אשר לא ראה את המעשה הרע אשר נעשה תחת השמש׃"));
hebsuperobject.biblemap.put("b21_4_4", new hebsuperobject(21,4,4,"וראיתי אני את כל עמל ואת כל כשרון המעשה כי היא קנאת איש מרעהו גם זה הבל ורעות רוח׃"));
hebsuperobject.biblemap.put("b21_4_5", new hebsuperobject(21,4,5,"הכסיל חבק את ידיו ואכל את בשרו׃"));
hebsuperobject.biblemap.put("b21_4_6", new hebsuperobject(21,4,6,"טוב מלא כף נחת ממלא חפנים עמל ורעות רוח׃"));
hebsuperobject.biblemap.put("b21_4_7", new hebsuperobject(21,4,7,"ושבתי אני ואראה הבל תחת השמש׃"));
hebsuperobject.biblemap.put("b21_4_8", new hebsuperobject(21,4,8,"יש אחד ואין שני גם בן ואח אין לו ואין קץ לכל עמלו גם עיניו לא תשבע עשר ולמי אני עמל ומחסר את נפשי מטובה גם זה הבל וענין רע הוא׃"));
hebsuperobject.biblemap.put("b21_4_9", new hebsuperobject(21,4,9,"טובים השנים מן האחד אשר יש להם שכר טוב בעמלם׃"));
hebsuperobject.biblemap.put("b21_4_10", new hebsuperobject(21,4,10,"כי אם יפלו האחד יקים את חברו ואילו האחד שיפול ואין שני להקימו׃"));
hebsuperobject.biblemap.put("b21_4_11", new hebsuperobject(21,4,11,"גם אם ישכבו שנים וחם להם ולאחד איך יחם׃"));
hebsuperobject.biblemap.put("b21_4_12", new hebsuperobject(21,4,12,"ואם יתקפו האחד השנים יעמדו נגדו והחוט המשלש לא במהרה ינתק׃"));
hebsuperobject.biblemap.put("b21_4_13", new hebsuperobject(21,4,13,"טוב ילד מסכן וחכם ממלך זקן וכסיל אשר לא ידע להזהר עוד׃"));
hebsuperobject.biblemap.put("b21_4_14", new hebsuperobject(21,4,14,"כי מבית הסורים יצא למלך כי גם במלכותו נולד רש׃"));
hebsuperobject.biblemap.put("b21_4_15", new hebsuperobject(21,4,15,"ראיתי את כל החיים המהלכים תחת השמש עם הילד השני אשר יעמד תחתיו׃"));
hebsuperobject.biblemap.put("b21_4_16", new hebsuperobject(21,4,16,"אין קץ לכל העם לכל אשר היה לפניהם גם האחרונים לא ישמחו בו כי גם זה הבל ורעיון רוח׃"));
hebsuperobject.biblemap.put("b21_5_1", new hebsuperobject(21,5,1,"שמר רגליך כאשר תלך אל בית האלהים וקרוב לשמע מתת הכסילים זבח כי אינם יודעים לעשות רע׃"));
hebsuperobject.biblemap.put("b21_5_2", new hebsuperobject(21,5,2,"אל תבהל על פיך ולבך אל ימהר להוציא דבר לפני האלהים כי האלהים בשמים ואתה על הארץ על כן יהיו דבריך מעטים׃"));
hebsuperobject.biblemap.put("b21_5_3", new hebsuperobject(21,5,3,"כי בא החלום ברב ענין וקול כסיל ברב דברים׃"));
hebsuperobject.biblemap.put("b21_5_4", new hebsuperobject(21,5,4,"כאשר תדר נדר לאלהים אל תאחר לשלמו כי אין חפץ בכסילים את אשר תדר שלם׃"));
hebsuperobject.biblemap.put("b21_5_5", new hebsuperobject(21,5,5,"טוב אשר לא תדר משתדור ולא תשלם׃"));
hebsuperobject.biblemap.put("b21_5_6", new hebsuperobject(21,5,6,"אל תתן את פיך לחטיא את בשרך ואל תאמר לפני המלאך כי שגגה היא למה יקצף האלהים על קולך וחבל את מעשה ידיך׃"));
hebsuperobject.biblemap.put("b21_5_7", new hebsuperobject(21,5,7,"כי ברב חלמות והבלים ודברים הרבה כי את האלהים ירא׃"));
hebsuperobject.biblemap.put("b21_5_8", new hebsuperobject(21,5,8,"אם עשק רש וגזל משפט וצדק תראה במדינה אל תתמה על החפץ כי גבה מעל גבה שמר וגבהים עליהם׃"));
hebsuperobject.biblemap.put("b21_5_9", new hebsuperobject(21,5,9,"ויתרון ארץ בכל היא מלך לשדה נעבד׃"));
hebsuperobject.biblemap.put("b21_5_10", new hebsuperobject(21,5,10,"אהב כסף לא ישבע כסף ומי אהב בהמון לא תבואה גם זה הבל׃"));
hebsuperobject.biblemap.put("b21_5_11", new hebsuperobject(21,5,11,"ברבות הטובה רבו אוכליה ומה כשרון לבעליה כי אם ראית עיניו׃"));
hebsuperobject.biblemap.put("b21_5_12", new hebsuperobject(21,5,12,"מתוקה שנת העבד אם מעט ואם הרבה יאכל והשבע לעשיר איננו מניח לו לישון׃"));
hebsuperobject.biblemap.put("b21_5_13", new hebsuperobject(21,5,13,"יש רעה חולה ראיתי תחת השמש עשר שמור לבעליו לרעתו׃"));
hebsuperobject.biblemap.put("b21_5_14", new hebsuperobject(21,5,14,"ואבד העשר ההוא בענין רע והוליד בן ואין בידו מאומה׃"));
hebsuperobject.biblemap.put("b21_5_15", new hebsuperobject(21,5,15,"כאשר יצא מבטן אמו ערום ישוב ללכת כשבא ומאומה לא ישא בעמלו שילך בידו׃"));
hebsuperobject.biblemap.put("b21_5_16", new hebsuperobject(21,5,16,"וגם זה רעה חולה כל עמת שבא כן ילך ומה יתרון לו שיעמל לרוח׃"));
hebsuperobject.biblemap.put("b21_5_17", new hebsuperobject(21,5,17,"גם כל ימיו בחשך יאכל וכעס הרבה וחליו וקצף׃"));
hebsuperobject.biblemap.put("b21_5_18", new hebsuperobject(21,5,18,"הנה אשר ראיתי אני טוב אשר יפה לאכול ולשתות ולראות טובה בכל עמלו שיעמל תחת השמש מספר ימי חיו אשר נתן לו האלהים כי הוא חלקו׃"));
hebsuperobject.biblemap.put("b21_5_19", new hebsuperobject(21,5,19,"גם כל האדם אשר נתן לו האלהים עשר ונכסים והשליטו לאכל ממנו ולשאת את חלקו ולשמח בעמלו זה מתת אלהים היא׃"));
hebsuperobject.biblemap.put("b21_5_20", new hebsuperobject(21,5,20,"כי לא הרבה יזכר את ימי חייו כי האלהים מענה בשמחת לבו׃"));
hebsuperobject.biblemap.put("b21_6_1", new hebsuperobject(21,6,1,"יש רעה אשר ראיתי תחת השמש ורבה היא על האדם׃"));
hebsuperobject.biblemap.put("b21_6_2", new hebsuperobject(21,6,2,"איש אשר יתן לו האלהים עשר ונכסים וכבוד ואיננו חסר לנפשו מכל אשר יתאוה ולא ישליטנו האלהים לאכל ממנו כי איש נכרי יאכלנו זה הבל וחלי רע הוא׃"));
hebsuperobject.biblemap.put("b21_6_3", new hebsuperobject(21,6,3,"אם יוליד איש מאה ושנים רבות יחיה ורב שיהיו ימי שניו ונפשו לא תשבע מן הטובה וגם קבורה לא היתה לו אמרתי טוב ממנו הנפל׃"));
hebsuperobject.biblemap.put("b21_6_4", new hebsuperobject(21,6,4,"כי בהבל בא ובחשך ילך ובחשך שמו יכסה׃"));
hebsuperobject.biblemap.put("b21_6_5", new hebsuperobject(21,6,5,"גם שמש לא ראה ולא ידע נחת לזה מזה׃"));
hebsuperobject.biblemap.put("b21_6_6", new hebsuperobject(21,6,6,"ואלו חיה אלף שנים פעמים וטובה לא ראה הלא אל מקום אחד הכל הולך׃"));
hebsuperobject.biblemap.put("b21_6_7", new hebsuperobject(21,6,7,"כל עמל האדם לפיהו וגם הנפש לא תמלא׃"));
hebsuperobject.biblemap.put("b21_6_8", new hebsuperobject(21,6,8,"כי מה יותר לחכם מן הכסיל מה לעני יודע להלך נגד החיים׃"));
hebsuperobject.biblemap.put("b21_6_9", new hebsuperobject(21,6,9,"טוב מראה עינים מהלך נפש גם זה הבל ורעות רוח׃"));
hebsuperobject.biblemap.put("b21_6_10", new hebsuperobject(21,6,10,"מה שהיה כבר נקרא שמו ונודע אשר הוא אדם ולא יוכל לדין עם שהתקיף ממנו׃"));
hebsuperobject.biblemap.put("b21_6_11", new hebsuperobject(21,6,11,"כי יש דברים הרבה מרבים הבל מה יתר לאדם׃"));
hebsuperobject.biblemap.put("b21_6_12", new hebsuperobject(21,6,12,"כי מי יודע מה טוב לאדם בחיים מספר ימי חיי הבלו ויעשם כצל אשר מי יגיד לאדם מה יהיה אחריו תחת השמש׃"));
hebsuperobject.biblemap.put("b21_7_1", new hebsuperobject(21,7,1,"טוב שם משמן טוב ויום המות מיום הולדו׃"));
hebsuperobject.biblemap.put("b21_7_2", new hebsuperobject(21,7,2,"טוב ללכת אל בית אבל מלכת אל בית משתה באשר הוא סוף כל האדם והחי יתן אל לבו׃"));
hebsuperobject.biblemap.put("b21_7_3", new hebsuperobject(21,7,3,"טוב כעס משחק כי ברע פנים ייטב לב׃"));
hebsuperobject.biblemap.put("b21_7_4", new hebsuperobject(21,7,4,"לב חכמים בבית אבל ולב כסילים בבית שמחה׃"));
hebsuperobject.biblemap.put("b21_7_5", new hebsuperobject(21,7,5,"טוב לשמע גערת חכם מאיש שמע שיר כסילים׃"));
hebsuperobject.biblemap.put("b21_7_6", new hebsuperobject(21,7,6,"כי כקול הסירים תחת הסיר כן שחק הכסיל וגם זה הבל׃"));
hebsuperobject.biblemap.put("b21_7_7", new hebsuperobject(21,7,7,"כי העשק יהולל חכם ויאבד את לב מתנה׃"));
hebsuperobject.biblemap.put("b21_7_8", new hebsuperobject(21,7,8,"טוב אחרית דבר מראשיתו טוב ארך רוח מגבה רוח׃"));
hebsuperobject.biblemap.put("b21_7_9", new hebsuperobject(21,7,9,"אל תבהל ברוחך לכעוס כי כעס בחיק כסילים ינוח׃"));
hebsuperobject.biblemap.put("b21_7_10", new hebsuperobject(21,7,10,"אל תאמר מה היה שהימים הראשנים היו טובים מאלה כי לא מחכמה שאלת על זה׃"));
hebsuperobject.biblemap.put("b21_7_11", new hebsuperobject(21,7,11,"טובה חכמה עם נחלה ויתר לראי השמש׃"));
hebsuperobject.biblemap.put("b21_7_12", new hebsuperobject(21,7,12,"כי בצל החכמה בצל הכסף ויתרון דעת החכמה תחיה בעליה׃"));
hebsuperobject.biblemap.put("b21_7_13", new hebsuperobject(21,7,13,"ראה את מעשה האלהים כי מי יוכל לתקן את אשר עותו׃"));
hebsuperobject.biblemap.put("b21_7_14", new hebsuperobject(21,7,14,"ביום טובה היה בטוב וביום רעה ראה גם את זה לעמת זה עשה האלהים על דברת שלא ימצא האדם אחריו מאומה׃"));
hebsuperobject.biblemap.put("b21_7_15", new hebsuperobject(21,7,15,"את הכל ראיתי בימי הבלי יש צדיק אבד בצדקו ויש רשע מאריך ברעתו׃"));
hebsuperobject.biblemap.put("b21_7_16", new hebsuperobject(21,7,16,"אל תהי צדיק הרבה ואל תתחכם יותר למה תשומם׃"));
hebsuperobject.biblemap.put("b21_7_17", new hebsuperobject(21,7,17,"אל תרשע הרבה ואל תהי סכל למה תמות בלא עתך׃"));
hebsuperobject.biblemap.put("b21_7_18", new hebsuperobject(21,7,18,"טוב אשר תאחז בזה וגם מזה אל תנח את ידך כי ירא אלהים יצא את כלם׃"));
hebsuperobject.biblemap.put("b21_7_19", new hebsuperobject(21,7,19,"החכמה תעז לחכם מעשרה שליטים אשר היו בעיר׃"));
hebsuperobject.biblemap.put("b21_7_20", new hebsuperobject(21,7,20,"כי אדם אין צדיק בארץ אשר יעשה טוב ולא יחטא׃"));
hebsuperobject.biblemap.put("b21_7_21", new hebsuperobject(21,7,21,"גם לכל הדברים אשר ידברו אל תתן לבך אשר לא תשמע את עבדך מקללך׃"));
hebsuperobject.biblemap.put("b21_7_22", new hebsuperobject(21,7,22,"כי גם פעמים רבות ידע לבך אשר גם את קללת אחרים׃"));
hebsuperobject.biblemap.put("b21_7_23", new hebsuperobject(21,7,23,"כל זה נסיתי בחכמה אמרתי אחכמה והיא רחוקה ממני׃"));
hebsuperobject.biblemap.put("b21_7_24", new hebsuperobject(21,7,24,"רחוק מה שהיה ועמק עמק מי ימצאנו׃"));
hebsuperobject.biblemap.put("b21_7_25", new hebsuperobject(21,7,25,"סבותי אני ולבי לדעת ולתור ובקש חכמה וחשבון ולדעת רשע כסל והסכלות הוללות׃"));
hebsuperobject.biblemap.put("b21_7_26", new hebsuperobject(21,7,26,"ומוצא אני מר ממות את האשה אשר היא מצודים וחרמים לבה אסורים ידיה טוב לפני האלהים ימלט ממנה וחוטא ילכד בה׃"));
hebsuperobject.biblemap.put("b21_7_27", new hebsuperobject(21,7,27,"ראה זה מצאתי אמרה קהלת אחת לאחת למצא חשבון׃"));
hebsuperobject.biblemap.put("b21_7_28", new hebsuperobject(21,7,28,"אשר עוד בקשה נפשי ולא מצאתי אדם אחד מאלף מצאתי ואשה בכל אלה לא מצאתי׃"));
hebsuperobject.biblemap.put("b21_7_29", new hebsuperobject(21,7,29,"לבד ראה זה מצאתי אשר עשה האלהים את האדם ישר והמה בקשו חשבנות רבים׃"));
hebsuperobject.biblemap.put("b21_8_1", new hebsuperobject(21,8,1,"מי כהחכם ומי יודע פשר דבר חכמת אדם תאיר פניו ועז פניו ישנא׃"));
hebsuperobject.biblemap.put("b21_8_2", new hebsuperobject(21,8,2,"אני פי מלך שמור ועל דברת שבועת אלהים׃"));
hebsuperobject.biblemap.put("b21_8_3", new hebsuperobject(21,8,3,"אל תבהל מפניו תלך אל תעמד בדבר רע כי כל אשר יחפץ יעשה׃"));
hebsuperobject.biblemap.put("b21_8_4", new hebsuperobject(21,8,4,"באשר דבר מלך שלטון ומי יאמר לו מה תעשה׃"));
hebsuperobject.biblemap.put("b21_8_5", new hebsuperobject(21,8,5,"שומר מצוה לא ידע דבר רע ועת ומשפט ידע לב חכם׃"));
hebsuperobject.biblemap.put("b21_8_6", new hebsuperobject(21,8,6,"כי לכל חפץ יש עת ומשפט כי רעת האדם רבה עליו׃"));
hebsuperobject.biblemap.put("b21_8_7", new hebsuperobject(21,8,7,"כי איננו ידע מה שיהיה כי כאשר יהיה מי יגיד לו׃"));
hebsuperobject.biblemap.put("b21_8_8", new hebsuperobject(21,8,8,"אין אדם שליט ברוח לכלוא את הרוח ואין שלטון ביום המות ואין משלחת במלחמה ולא ימלט רשע את בעליו׃"));
hebsuperobject.biblemap.put("b21_8_9", new hebsuperobject(21,8,9,"את כל זה ראיתי ונתון את לבי לכל מעשה אשר נעשה תחת השמש עת אשר שלט האדם באדם לרע לו׃"));
hebsuperobject.biblemap.put("b21_8_10", new hebsuperobject(21,8,10,"ובכן ראיתי רשעים קברים ובאו וממקום קדוש יהלכו וישתכחו בעיר אשר כן עשו גם זה הבל׃"));
hebsuperobject.biblemap.put("b21_8_11", new hebsuperobject(21,8,11,"אשר אין נעשה פתגם מעשה הרעה מהרה על כן מלא לב בני האדם בהם לעשות רע׃"));
hebsuperobject.biblemap.put("b21_8_12", new hebsuperobject(21,8,12,"אשר חטא עשה רע מאת ומאריך לו כי גם יודע אני אשר יהיה טוב ליראי האלהים אשר ייראו מלפניו׃"));
hebsuperobject.biblemap.put("b21_8_13", new hebsuperobject(21,8,13,"וטוב לא יהיה לרשע ולא יאריך ימים כצל אשר איננו ירא מלפני אלהים׃"));
hebsuperobject.biblemap.put("b21_8_14", new hebsuperobject(21,8,14,"יש הבל אשר נעשה על הארץ אשר יש צדיקים אשר מגיע אלהם כמעשה הרשעים ויש רשעים שמגיע אלהם כמעשה הצדיקים אמרתי שגם זה הבל׃"));
hebsuperobject.biblemap.put("b21_8_15", new hebsuperobject(21,8,15,"ושבחתי אני את השמחה אשר אין טוב לאדם תחת השמש כי אם לאכול ולשתות ולשמוח והוא ילונו בעמלו ימי חייו אשר נתן לו האלהים תחת השמש׃"));
hebsuperobject.biblemap.put("b21_8_16", new hebsuperobject(21,8,16,"כאשר נתתי את לבי לדעת חכמה ולראות את הענין אשר נעשה על הארץ כי גם ביום ובלילה שנה בעיניו איננו ראה׃"));
hebsuperobject.biblemap.put("b21_8_17", new hebsuperobject(21,8,17,"וראיתי את כל מעשה האלהים כי לא יוכל האדם למצוא את המעשה אשר נעשה תחת השמש בשל אשר יעמל האדם לבקש ולא ימצא וגם אם יאמר החכם לדעת לא יוכל למצא׃"));
hebsuperobject.biblemap.put("b21_9_1", new hebsuperobject(21,9,1,"כי את כל זה נתתי אל לבי ולבור את כל זה אשר הצדיקים והחכמים ועבדיהם ביד האלהים גם אהבה גם שנאה אין יודע האדם הכל לפניהם׃"));
hebsuperobject.biblemap.put("b21_9_2", new hebsuperobject(21,9,2,"הכל כאשר לכל מקרה אחד לצדיק ולרשע לטוב ולטהור ולטמא ולזבח ולאשר איננו זבח כטוב כחטא הנשבע כאשר שבועה ירא׃"));
hebsuperobject.biblemap.put("b21_9_3", new hebsuperobject(21,9,3,"זה רע בכל אשר נעשה תחת השמש כי מקרה אחד לכל וגם לב בני האדם מלא רע והוללות בלבבם בחייהם ואחריו אל המתים׃"));
hebsuperobject.biblemap.put("b21_9_4", new hebsuperobject(21,9,4,"כי מי אשר יבחר אל כל החיים יש בטחון כי לכלב חי הוא טוב מן האריה המת׃"));
hebsuperobject.biblemap.put("b21_9_5", new hebsuperobject(21,9,5,"כי החיים יודעים שימתו והמתים אינם יודעים מאומה ואין עוד להם שכר כי נשכח זכרם׃"));
hebsuperobject.biblemap.put("b21_9_6", new hebsuperobject(21,9,6,"גם אהבתם גם שנאתם גם קנאתם כבר אבדה וחלק אין להם עוד לעולם בכל אשר נעשה תחת השמש׃"));
hebsuperobject.biblemap.put("b21_9_7", new hebsuperobject(21,9,7,"לך אכל בשמחה לחמך ושתה בלב טוב יינך כי כבר רצה האלהים את מעשיך׃"));
hebsuperobject.biblemap.put("b21_9_8", new hebsuperobject(21,9,8,"בכל עת יהיו בגדיך לבנים ושמן על ראשך אל יחסר׃"));
hebsuperobject.biblemap.put("b21_9_9", new hebsuperobject(21,9,9,"ראה חיים עם אשה אשר אהבת כל ימי חיי הבלך אשר נתן לך תחת השמש כל ימי הבלך כי הוא חלקך בחיים ובעמלך אשר אתה עמל תחת השמש׃"));
hebsuperobject.biblemap.put("b21_9_10", new hebsuperobject(21,9,10,"כל אשר תמצא ידך לעשות בכחך עשה כי אין מעשה וחשבון ודעת וחכמה בשאול אשר אתה הלך שמה׃"));
hebsuperobject.biblemap.put("b21_9_11", new hebsuperobject(21,9,11,"שבתי וראה תחת השמש כי לא לקלים המרוץ ולא לגבורים המלחמה וגם לא לחכמים לחם וגם לא לנבנים עשר וגם לא לידעים חן כי עת ופגע יקרה את כלם׃"));
hebsuperobject.biblemap.put("b21_9_12", new hebsuperobject(21,9,12,"כי גם לא ידע האדם את עתו כדגים שנאחזים במצודה רעה וכצפרים האחזות בפח כהם יוקשים בני האדם לעת רעה כשתפול עליהם פתאם׃"));
hebsuperobject.biblemap.put("b21_9_13", new hebsuperobject(21,9,13,"גם זה ראיתי חכמה תחת השמש וגדולה היא אלי׃"));
hebsuperobject.biblemap.put("b21_9_14", new hebsuperobject(21,9,14,"עיר קטנה ואנשים בה מעט ובא אליה מלך גדול וסבב אתה ובנה עליה מצודים גדלים׃"));
hebsuperobject.biblemap.put("b21_9_15", new hebsuperobject(21,9,15,"ומצא בה איש מסכן חכם ומלט הוא את העיר בחכמתו ואדם לא זכר את האיש המסכן ההוא׃"));
hebsuperobject.biblemap.put("b21_9_16", new hebsuperobject(21,9,16,"ואמרתי אני טובה חכמה מגבורה וחכמת המסכן בזויה ודבריו אינם נשמעים׃"));
hebsuperobject.biblemap.put("b21_9_17", new hebsuperobject(21,9,17,"דברי חכמים בנחת נשמעים מזעקת מושל בכסילים׃"));
hebsuperobject.biblemap.put("b21_9_18", new hebsuperobject(21,9,18,"טובה חכמה מכלי קרב וחוטא אחד יאבד טובה הרבה׃"));
hebsuperobject.biblemap.put("b21_10_1", new hebsuperobject(21,10,1,"זבובי מות יבאיש יביע שמן רוקח יקר מחכמה מכבוד סכלות מעט׃"));
hebsuperobject.biblemap.put("b21_10_2", new hebsuperobject(21,10,2,"לב חכם לימינו ולב כסיל לשמאלו׃"));
hebsuperobject.biblemap.put("b21_10_3", new hebsuperobject(21,10,3,"וגם בדרך כשהסכל הלך לבו חסר ואמר לכל סכל הוא׃"));
hebsuperobject.biblemap.put("b21_10_4", new hebsuperobject(21,10,4,"אם רוח המושל תעלה עליך מקומך אל תנח כי מרפא יניח חטאים גדולים׃"));
hebsuperobject.biblemap.put("b21_10_5", new hebsuperobject(21,10,5,"יש רעה ראיתי תחת השמש כשגגה שיצא מלפני השליט׃"));
hebsuperobject.biblemap.put("b21_10_6", new hebsuperobject(21,10,6,"נתן הסכל במרומים רבים ועשירים בשפל ישבו׃"));
hebsuperobject.biblemap.put("b21_10_7", new hebsuperobject(21,10,7,"ראיתי עבדים על סוסים ושרים הלכים כעבדים על הארץ׃"));
hebsuperobject.biblemap.put("b21_10_8", new hebsuperobject(21,10,8,"חפר גומץ בו יפול ופרץ גדר ישכנו נחש׃"));
hebsuperobject.biblemap.put("b21_10_9", new hebsuperobject(21,10,9,"מסיע אבנים יעצב בהם בוקע עצים יסכן בם׃"));
hebsuperobject.biblemap.put("b21_10_10", new hebsuperobject(21,10,10,"אם קהה הברזל והוא לא פנים קלקל וחילים יגבר ויתרון הכשיר חכמה׃"));
hebsuperobject.biblemap.put("b21_10_11", new hebsuperobject(21,10,11,"אם ישך הנחש בלוא לחש ואין יתרון לבעל הלשון׃"));
hebsuperobject.biblemap.put("b21_10_12", new hebsuperobject(21,10,12,"דברי פי חכם חן ושפתות כסיל תבלענו׃"));
hebsuperobject.biblemap.put("b21_10_13", new hebsuperobject(21,10,13,"תחלת דברי פיהו סכלות ואחרית פיהו הוללות רעה׃"));
hebsuperobject.biblemap.put("b21_10_14", new hebsuperobject(21,10,14,"והסכל ירבה דברים לא ידע האדם מה שיהיה ואשר יהיה מאחריו מי יגיד לו׃"));
hebsuperobject.biblemap.put("b21_10_15", new hebsuperobject(21,10,15,"עמל הכסילים תיגענו אשר לא ידע ללכת אל עיר׃"));
hebsuperobject.biblemap.put("b21_10_16", new hebsuperobject(21,10,16,"אי לך ארץ שמלכך נער ושריך בבקר יאכלו׃"));
hebsuperobject.biblemap.put("b21_10_17", new hebsuperobject(21,10,17,"אשריך ארץ שמלכך בן חורים ושריך בעת יאכלו בגבורה ולא בשתי׃"));
hebsuperobject.biblemap.put("b21_10_18", new hebsuperobject(21,10,18,"בעצלתים ימך המקרה ובשפלות ידים ידלף הבית׃"));
hebsuperobject.biblemap.put("b21_10_19", new hebsuperobject(21,10,19,"לשחוק עשים לחם ויין ישמח חיים והכסף יענה את הכל׃"));
hebsuperobject.biblemap.put("b21_10_20", new hebsuperobject(21,10,20,"גם במדעך מלך אל תקלל ובחדרי משכבך אל תקלל עשיר כי עוף השמים יוליך את הקול ובעל הכנפים יגיד דבר׃"));
hebsuperobject.biblemap.put("b21_11_1", new hebsuperobject(21,11,1,"שלח לחמך על פני המים כי ברב הימים תמצאנו׃"));
hebsuperobject.biblemap.put("b21_11_2", new hebsuperobject(21,11,2,"תן חלק לשבעה וגם לשמונה כי לא תדע מה יהיה רעה על הארץ׃"));
hebsuperobject.biblemap.put("b21_11_3", new hebsuperobject(21,11,3,"אם ימלאו העבים גשם על הארץ יריקו ואם יפול עץ בדרום ואם בצפון מקום שיפול העץ שם יהוא׃"));
hebsuperobject.biblemap.put("b21_11_4", new hebsuperobject(21,11,4,"שמר רוח לא יזרע וראה בעבים לא יקצור׃"));
hebsuperobject.biblemap.put("b21_11_5", new hebsuperobject(21,11,5,"כאשר אינך יודע מה דרך הרוח כעצמים בבטן המלאה ככה לא תדע את מעשה האלהים אשר יעשה את הכל׃"));
hebsuperobject.biblemap.put("b21_11_6", new hebsuperobject(21,11,6,"בבקר זרע את זרעך ולערב אל תנח ידך כי אינך יודע אי זה יכשר הזה או זה ואם שניהם כאחד טובים׃"));
hebsuperobject.biblemap.put("b21_11_7", new hebsuperobject(21,11,7,"ומתוק האור וטוב לעינים לראות את השמש׃"));
hebsuperobject.biblemap.put("b21_11_8", new hebsuperobject(21,11,8,"כי אם שנים הרבה יחיה האדם בכלם ישמח ויזכר את ימי החשך כי הרבה יהיו כל שבא הבל׃"));
hebsuperobject.biblemap.put("b21_11_9", new hebsuperobject(21,11,9,"שמח בחור בילדותיך ויטיבך לבך בימי בחורותך והלך בדרכי לבך ובמראי עיניך ודע כי על כל אלה יביאך האלהים במשפט׃"));
hebsuperobject.biblemap.put("b21_11_10", new hebsuperobject(21,11,10,"והסר כעס מלבך והעבר רעה מבשרך כי הילדות והשחרות הבל׃"));
hebsuperobject.biblemap.put("b21_12_1", new hebsuperobject(21,12,1,"וזכר את בוראיך בימי בחורתיך עד אשר לא יבאו ימי הרעה והגיעו שנים אשר תאמר אין לי בהם חפץ׃"));
hebsuperobject.biblemap.put("b21_12_2", new hebsuperobject(21,12,2,"עד אשר לא תחשך השמש והאור והירח והכוכבים ושבו העבים אחר הגשם׃"));
hebsuperobject.biblemap.put("b21_12_3", new hebsuperobject(21,12,3,"ביום שיזעו שמרי הבית והתעותו אנשי החיל ובטלו הטחנות כי מעטו וחשכו הראות בארבות׃"));
hebsuperobject.biblemap.put("b21_12_4", new hebsuperobject(21,12,4,"וסגרו דלתים בשוק בשפל קול הטחנה ויקום לקול הצפור וישחו כל בנות השיר׃"));
hebsuperobject.biblemap.put("b21_12_5", new hebsuperobject(21,12,5,"גם מגבה יראו וחתחתים בדרך וינאץ השקד ויסתבל החגב ותפר האביונה כי הלך האדם אל בית עולמו וסבבו בשוק הספדים׃"));
hebsuperobject.biblemap.put("b21_12_6", new hebsuperobject(21,12,6,"עד אשר לא ירחק חבל הכסף ותרץ גלת הזהב ותשבר כד על המבוע ונרץ הגלגל אל הבור׃"));
hebsuperobject.biblemap.put("b21_12_7", new hebsuperobject(21,12,7,"וישב העפר על הארץ כשהיה והרוח תשוב אל האלהים אשר נתנה׃"));
hebsuperobject.biblemap.put("b21_12_8", new hebsuperobject(21,12,8,"הבל הבלים אמר הקוהלת הכל הבל׃"));
hebsuperobject.biblemap.put("b21_12_9", new hebsuperobject(21,12,9,"ויתר שהיה קהלת חכם עוד למד דעת את העם ואזן וחקר תקן משלים הרבה׃"));
hebsuperobject.biblemap.put("b21_12_10", new hebsuperobject(21,12,10,"בקש קהלת למצא דברי חפץ וכתוב ישר דברי אמת׃"));
hebsuperobject.biblemap.put("b21_12_11", new hebsuperobject(21,12,11,"דברי חכמים כדרבנות וכמשמרות נטועים בעלי אספות נתנו מרעה אחד׃"));
hebsuperobject.biblemap.put("b21_12_12", new hebsuperobject(21,12,12,"ויתר מהמה בני הזהר עשות ספרים הרבה אין קץ ולהג הרבה יגעת בשר׃"));
hebsuperobject.biblemap.put("b21_12_13", new hebsuperobject(21,12,13,"סוף דבר הכל נשמע את האלהים ירא ואת מצותיו שמור כי זה כל האדם׃"));
hebsuperobject.biblemap.put("b21_12_14", new hebsuperobject(21,12,14,"כי את כל מעשה האלהים יבא במשפט על כל נעלם אם טוב ואם רע׃"));

}

}