package heb.bible;

public class hebbible28 {

public hebbible28() {

putmapbible28();

}

private void putmapbible28() {

hebsuperobject.biblemap.put("b28_1_1", new hebsuperobject(28,1,1,"דבר יהוה אשר היה אל הושע בן בארי בימי עזיה יותם אחז יחזקיה מלכי יהודה ובימי ירבעם בן יואש מלך ישראל׃"));
hebsuperobject.biblemap.put("b28_1_2", new hebsuperobject(28,1,2,"תחלת דבר יהוה בהושע ויאמר יהוה אל הושע לך קח לך אשת זנונים וילדי זנונים כי זנה תזנה הארץ מאחרי יהוה׃"));
hebsuperobject.biblemap.put("b28_1_3", new hebsuperobject(28,1,3,"וילך ויקח את גמר בת דבלים ותהר ותלד לו בן׃"));
hebsuperobject.biblemap.put("b28_1_4", new hebsuperobject(28,1,4,"ויאמר יהוה אליו קרא שמו יזרעאל כי עוד מעט ופקדתי את דמי יזרעאל על בית יהוא והשבתי ממלכות בית ישראל׃"));
hebsuperobject.biblemap.put("b28_1_5", new hebsuperobject(28,1,5,"והיה ביום ההוא ושברתי את קשת ישראל בעמק יזרעאל׃"));
hebsuperobject.biblemap.put("b28_1_6", new hebsuperobject(28,1,6,"ותהר עוד ותלד בת ויאמר לו קרא שמה לא רחמה כי לא אוסיף עוד ארחם את בית ישראל כי נשא אשא להם׃"));
hebsuperobject.biblemap.put("b28_1_7", new hebsuperobject(28,1,7,"ואת בית יהודה ארחם והושעתים ביהוה אלהיהם ולא אושיעם בקשת ובחרב ובמלחמה בסוסים ובפרשים׃"));
hebsuperobject.biblemap.put("b28_1_8", new hebsuperobject(28,1,8,"ותגמל את לא רחמה ותהר ותלד בן׃"));
hebsuperobject.biblemap.put("b28_1_9", new hebsuperobject(28,1,9,"ויאמר קרא שמו לא עמי כי אתם לא עמי ואנכי לא אהיה לכם׃"));
hebsuperobject.biblemap.put("b28_1_10", new hebsuperobject(28,1,10,"והיה מספר בני ישראל כחול הים אשר לא ימד ולא יספר והיה במקום אשר יאמר להם לא עמי אתם יאמר להם בני אל חי׃"));
hebsuperobject.biblemap.put("b28_1_11", new hebsuperobject(28,1,11,"ונקבצו בני יהודה ובני ישראל יחדו ושמו להם ראש אחד ועלו מן הארץ כי גדול יום יזרעאל׃"));
hebsuperobject.biblemap.put("b28_2_1", new hebsuperobject(28,2,1,"אמרו לאחיכם עמי ולאחותיכם רחמה׃"));
hebsuperobject.biblemap.put("b28_2_2", new hebsuperobject(28,2,2,"ריבו באמכם ריבו כי היא לא אשתי ואנכי לא אישה ותסר זנוניה מפניה ונאפופיה מבין שדיה׃"));
hebsuperobject.biblemap.put("b28_2_3", new hebsuperobject(28,2,3,"פן אפשיטנה ערמה והצגתיה כיום הולדה ושמתיה כמדבר ושתה כארץ ציה והמתיה בצמא׃"));
hebsuperobject.biblemap.put("b28_2_4", new hebsuperobject(28,2,4,"ואת בניה לא ארחם כי בני זנונים המה׃"));
hebsuperobject.biblemap.put("b28_2_5", new hebsuperobject(28,2,5,"כי זנתה אמם הבישה הורתם כי אמרה אלכה אחרי מאהבי נתני לחמי ומימי צמרי ופשתי שמני ושקויי׃"));
hebsuperobject.biblemap.put("b28_2_6", new hebsuperobject(28,2,6,"לכן הנני שך את דרכך בסירים וגדרתי את גדרה ונתיבותיה לא תמצא׃"));
hebsuperobject.biblemap.put("b28_2_7", new hebsuperobject(28,2,7,"ורדפה את מאהביה ולא תשיג אתם ובקשתם ולא תמצא ואמרה אלכה ואשובה אל אישי הראשון כי טוב לי אז מעתה׃"));
hebsuperobject.biblemap.put("b28_2_8", new hebsuperobject(28,2,8,"והיא לא ידעה כי אנכי נתתי לה הדגן והתירוש והיצהר וכסף הרביתי לה וזהב עשו לבעל׃"));
hebsuperobject.biblemap.put("b28_2_9", new hebsuperobject(28,2,9,"לכן אשוב ולקחתי דגני בעתו ותירושי במועדו והצלתי צמרי ופשתי לכסות את ערותה׃"));
hebsuperobject.biblemap.put("b28_2_10", new hebsuperobject(28,2,10,"ועתה אגלה את נבלתה לעיני מאהביה ואיש לא יצילנה מידי׃"));
hebsuperobject.biblemap.put("b28_2_11", new hebsuperobject(28,2,11,"והשבתי כל משושה חגה חדשה ושבתה וכל מועדה׃"));
hebsuperobject.biblemap.put("b28_2_12", new hebsuperobject(28,2,12,"והשמתי גפנה ותאנתה אשר אמרה אתנה המה לי אשר נתנו לי מאהבי ושמתים ליער ואכלתם חית השדה׃"));
hebsuperobject.biblemap.put("b28_2_13", new hebsuperobject(28,2,13,"ופקדתי עליה את ימי הבעלים אשר תקטיר להם ותעד נזמה וחליתה ותלך אחרי מאהביה ואתי שכחה נאם יהוה׃"));
hebsuperobject.biblemap.put("b28_2_14", new hebsuperobject(28,2,14,"לכן הנה אנכי מפתיה והלכתיה המדבר ודברתי על לבה׃"));
hebsuperobject.biblemap.put("b28_2_15", new hebsuperobject(28,2,15,"ונתתי לה את כרמיה משם ואת עמק עכור לפתח תקוה וענתה שמה כימי נעוריה וכיום עלתה מארץ מצרים׃"));
hebsuperobject.biblemap.put("b28_2_16", new hebsuperobject(28,2,16,"והיה ביום ההוא נאם יהוה תקראי אישי ולא תקראי לי עוד בעלי׃"));
hebsuperobject.biblemap.put("b28_2_17", new hebsuperobject(28,2,17,"והסרתי את שמות הבעלים מפיה ולא יזכרו עוד בשמם׃"));
hebsuperobject.biblemap.put("b28_2_18", new hebsuperobject(28,2,18,"וכרתי להם ברית ביום ההוא עם חית השדה ועם עוף השמים ורמש האדמה וקשת וחרב ומלחמה אשבור מן הארץ והשכבתים לבטח׃"));
hebsuperobject.biblemap.put("b28_2_19", new hebsuperobject(28,2,19,"וארשתיך לי לעולם וארשתיך לי בצדק ובמשפט ובחסד וברחמים׃"));
hebsuperobject.biblemap.put("b28_2_20", new hebsuperobject(28,2,20,"וארשתיך לי באמונה וידעת את יהוה׃"));
hebsuperobject.biblemap.put("b28_2_21", new hebsuperobject(28,2,21,"והיה ביום ההוא אענה נאם יהוה אענה את השמים והם יענו את הארץ׃"));
hebsuperobject.biblemap.put("b28_2_22", new hebsuperobject(28,2,22,"והארץ תענה את הדגן ואת התירוש ואת היצהר והם יענו את יזרעאל׃"));
hebsuperobject.biblemap.put("b28_2_23", new hebsuperobject(28,2,23,"וזרעתיה לי בארץ ורחמתי את לא רחמה ואמרתי ללא עמי עמי אתה והוא יאמר אלהי׃"));
hebsuperobject.biblemap.put("b28_3_1", new hebsuperobject(28,3,1,"ויאמר יהוה אלי עוד לך אהב אשה אהבת רע ומנאפת כאהבת יהוה את בני ישראל והם פנים אל אלהים אחרים ואהבי אשישי ענבים׃"));
hebsuperobject.biblemap.put("b28_3_2", new hebsuperobject(28,3,2,"ואכרה לי בחמשה עשר כסף וחמר שערים ולתך שערים׃"));
hebsuperobject.biblemap.put("b28_3_3", new hebsuperobject(28,3,3,"ואמר אליה ימים רבים תשבי לי לא תזני ולא תהיי לאיש וגם אני אליך׃"));
hebsuperobject.biblemap.put("b28_3_4", new hebsuperobject(28,3,4,"כי ימים רבים ישבו בני ישראל אין מלך ואין שר ואין זבח ואין מצבה ואין אפוד ותרפים׃"));
hebsuperobject.biblemap.put("b28_3_5", new hebsuperobject(28,3,5,"אחר ישבו בני ישראל ובקשו את יהוה אלהיהם ואת דויד מלכם ופחדו אל יהוה ואל טובו באחרית הימים׃"));
hebsuperobject.biblemap.put("b28_4_1", new hebsuperobject(28,4,1,"שמעו דבר יהוה בני ישראל כי ריב ליהוה עם יושבי הארץ כי אין אמת ואין חסד ואין דעת אלהים בארץ׃"));
hebsuperobject.biblemap.put("b28_4_2", new hebsuperobject(28,4,2,"אלה וכחש ורצח וגנב ונאף פרצו ודמים בדמים נגעו׃"));
hebsuperobject.biblemap.put("b28_4_3", new hebsuperobject(28,4,3,"על כן תאבל הארץ ואמלל כל יושב בה בחית השדה ובעוף השמים וגם דגי הים יאספו׃"));
hebsuperobject.biblemap.put("b28_4_4", new hebsuperobject(28,4,4,"אך איש אל ירב ואל יוכח איש ועמך כמריבי כהן׃"));
hebsuperobject.biblemap.put("b28_4_5", new hebsuperobject(28,4,5,"וכשלת היום וכשל גם נביא עמך לילה ודמיתי אמך׃"));
hebsuperobject.biblemap.put("b28_4_6", new hebsuperobject(28,4,6,"נדמו עמי מבלי הדעת כי אתה הדעת מאסת ואמאסאך מכהן לי ותשכח תורת אלהיך אשכח בניך גם אני׃"));
hebsuperobject.biblemap.put("b28_4_7", new hebsuperobject(28,4,7,"כרבם כן חטאו לי כבודם בקלון אמיר׃"));
hebsuperobject.biblemap.put("b28_4_8", new hebsuperobject(28,4,8,"חטאת עמי יאכלו ואל עונם ישאו נפשו׃"));
hebsuperobject.biblemap.put("b28_4_9", new hebsuperobject(28,4,9,"והיה כעם ככהן ופקדתי עליו דרכיו ומעלליו אשיב לו׃"));
hebsuperobject.biblemap.put("b28_4_10", new hebsuperobject(28,4,10,"ואכלו ולא ישבעו הזנו ולא יפרצו כי את יהוה עזבו לשמר׃"));
hebsuperobject.biblemap.put("b28_4_11", new hebsuperobject(28,4,11,"זנות ויין ותירוש יקח לב׃"));
hebsuperobject.biblemap.put("b28_4_12", new hebsuperobject(28,4,12,"עמי בעצו ישאל ומקלו יגיד לו כי רוח זנונים התעה ויזנו מתחת אלהיהם׃"));
hebsuperobject.biblemap.put("b28_4_13", new hebsuperobject(28,4,13,"על ראשי ההרים יזבחו ועל הגבעות יקטרו תחת אלון ולבנה ואלה כי טוב צלה על כן תזנינה בנותיכם וכלותיכם תנאפנה׃"));
hebsuperobject.biblemap.put("b28_4_14", new hebsuperobject(28,4,14,"לא אפקוד על בנותיכם כי תזנינה ועל כלותיכם כי תנאפנה כי הם עם הזנות יפרדו ועם הקדשות יזבחו ועם לא יבין ילבט׃"));
hebsuperobject.biblemap.put("b28_4_15", new hebsuperobject(28,4,15,"אם זנה אתה ישראל אל יאשם יהודה ואל תבאו הגלגל ואל תעלו בית און ואל תשבעו חי יהוה׃"));
hebsuperobject.biblemap.put("b28_4_16", new hebsuperobject(28,4,16,"כי כפרה סררה סרר ישראל עתה ירעם יהוה ככבש במרחב׃"));
hebsuperobject.biblemap.put("b28_4_17", new hebsuperobject(28,4,17,"חבור עצבים אפרים הנח לו׃"));
hebsuperobject.biblemap.put("b28_4_18", new hebsuperobject(28,4,18,"סר סבאם הזנה הזנו אהבו הבו קלון מגניה׃"));
hebsuperobject.biblemap.put("b28_4_19", new hebsuperobject(28,4,19,"צרר רוח אותה בכנפיה ויבשו מזבחותם׃"));
hebsuperobject.biblemap.put("b28_5_1", new hebsuperobject(28,5,1,"שמעו זאת הכהנים והקשיבו בית ישראל ובית המלך האזינו כי לכם המשפט כי פח הייתם למצפה ורשת פרושה על תבור׃"));
hebsuperobject.biblemap.put("b28_5_2", new hebsuperobject(28,5,2,"ושחטה שטים העמיקו ואני מוסר לכלם׃"));
hebsuperobject.biblemap.put("b28_5_3", new hebsuperobject(28,5,3,"אני ידעתי אפרים וישראל לא נכחד ממני כי עתה הזנית אפרים נטמא ישראל׃"));
hebsuperobject.biblemap.put("b28_5_4", new hebsuperobject(28,5,4,"לא יתנו מעלליהם לשוב אל אלהיהם כי רוח זנונים בקרבם ואת יהוה לא ידעו׃"));
hebsuperobject.biblemap.put("b28_5_5", new hebsuperobject(28,5,5,"וענה גאון ישראל בפניו וישראל ואפרים יכשלו בעונם כשל גם יהודה עמם׃"));
hebsuperobject.biblemap.put("b28_5_6", new hebsuperobject(28,5,6,"בצאנם ובבקרם ילכו לבקש את יהוה ולא ימצאו חלץ מהם׃"));
hebsuperobject.biblemap.put("b28_5_7", new hebsuperobject(28,5,7,"ביהוה בגדו כי בנים זרים ילדו עתה יאכלם חדש את חלקיהם׃"));
hebsuperobject.biblemap.put("b28_5_8", new hebsuperobject(28,5,8,"תקעו שופר בגבעה חצצרה ברמה הריעו בית און אחריך בנימין׃"));
hebsuperobject.biblemap.put("b28_5_9", new hebsuperobject(28,5,9,"אפרים לשמה תהיה ביום תוכחה בשבטי ישראל הודעתי נאמנה׃"));
hebsuperobject.biblemap.put("b28_5_10", new hebsuperobject(28,5,10,"היו שרי יהודה כמסיגי גבול עליהם אשפוך כמים עברתי׃"));
hebsuperobject.biblemap.put("b28_5_11", new hebsuperobject(28,5,11,"עשוק אפרים רצוץ משפט כי הואיל הלך אחרי צו׃"));
hebsuperobject.biblemap.put("b28_5_12", new hebsuperobject(28,5,12,"ואני כעש לאפרים וכרקב לבית יהודה׃"));
hebsuperobject.biblemap.put("b28_5_13", new hebsuperobject(28,5,13,"וירא אפרים את חליו ויהודה את מזרו וילך אפרים אל אשור וישלח אל מלך ירב והוא לא יוכל לרפא לכם ולא יגהה מכם מזור׃"));
hebsuperobject.biblemap.put("b28_5_14", new hebsuperobject(28,5,14,"כי אנכי כשחל לאפרים וככפיר לבית יהודה אני אני אטרף ואלך אשא ואין מציל׃"));
hebsuperobject.biblemap.put("b28_5_15", new hebsuperobject(28,5,15,"אלך אשובה אל מקומי עד אשר יאשמו ובקשו פני בצר להם ישחרנני׃"));
hebsuperobject.biblemap.put("b28_6_1", new hebsuperobject(28,6,1,"לכו ונשובה אל יהוה כי הוא טרף וירפאנו יך ויחבשנו׃"));
hebsuperobject.biblemap.put("b28_6_2", new hebsuperobject(28,6,2,"יחינו מימים ביום השלישי יקמנו ונחיה לפניו׃"));
hebsuperobject.biblemap.put("b28_6_3", new hebsuperobject(28,6,3,"ונדעה נרדפה לדעת את יהוה כשחר נכון מצאו ויבוא כגשם לנו כמלקוש יורה ארץ׃"));
hebsuperobject.biblemap.put("b28_6_4", new hebsuperobject(28,6,4,"מה אעשה לך אפרים מה אעשה לך יהודה וחסדכם כענן בקר וכטל משכים הלך׃"));
hebsuperobject.biblemap.put("b28_6_5", new hebsuperobject(28,6,5,"על כן חצבתי בנביאים הרגתים באמרי פי ומשפטיך אור יצא׃"));
hebsuperobject.biblemap.put("b28_6_6", new hebsuperobject(28,6,6,"כי חסד חפצתי ולא זבח ודעת אלהים מעלות׃"));
hebsuperobject.biblemap.put("b28_6_7", new hebsuperobject(28,6,7,"והמה כאדם עברו ברית שם בגדו בי׃"));
hebsuperobject.biblemap.put("b28_6_8", new hebsuperobject(28,6,8,"גלעד קרית פעלי און עקבה מדם׃"));
hebsuperobject.biblemap.put("b28_6_9", new hebsuperobject(28,6,9,"וכחכי איש גדודים חבר כהנים דרך ירצחו שכמה כי זמה עשו׃"));
hebsuperobject.biblemap.put("b28_6_10", new hebsuperobject(28,6,10,"בבית ישראל ראיתי שעריריה שם זנות לאפרים נטמא ישראל׃"));
hebsuperobject.biblemap.put("b28_6_11", new hebsuperobject(28,6,11,"גם יהודה שת קציר לך בשובי שבות עמי׃"));
hebsuperobject.biblemap.put("b28_7_1", new hebsuperobject(28,7,1,"כרפאי לישראל ונגלה עון אפרים ורעות שמרון כי פעלו שקר וגנב יבוא פשט גדוד בחוץ׃"));
hebsuperobject.biblemap.put("b28_7_2", new hebsuperobject(28,7,2,"ובל יאמרו ללבבם כל רעתם זכרתי עתה סבבום מעלליהם נגד פני היו׃"));
hebsuperobject.biblemap.put("b28_7_3", new hebsuperobject(28,7,3,"ברעתם ישמחו מלך ובכחשיהם שרים׃"));
hebsuperobject.biblemap.put("b28_7_4", new hebsuperobject(28,7,4,"כלם מנאפים כמו תנור בערה מאפה ישבות מעיר מלוש בצק עד חמצתו׃"));
hebsuperobject.biblemap.put("b28_7_5", new hebsuperobject(28,7,5,"יום מלכנו החלו שרים חמת מיין משך ידו את לצצים׃"));
hebsuperobject.biblemap.put("b28_7_6", new hebsuperobject(28,7,6,"כי קרבו כתנור לבם בארבם כל הלילה ישן אפהם בקר הוא בער כאש להבה׃"));
hebsuperobject.biblemap.put("b28_7_7", new hebsuperobject(28,7,7,"כלם יחמו כתנור ואכלו את שפטיהם כל מלכיהם נפלו אין קרא בהם אלי׃"));
hebsuperobject.biblemap.put("b28_7_8", new hebsuperobject(28,7,8,"אפרים בעמים הוא יתבולל אפרים היה עגה בלי הפוכה׃"));
hebsuperobject.biblemap.put("b28_7_9", new hebsuperobject(28,7,9,"אכלו זרים כחו והוא לא ידע גם שיבה זרקה בו והוא לא ידע׃"));
hebsuperobject.biblemap.put("b28_7_10", new hebsuperobject(28,7,10,"וענה גאון ישראל בפניו ולא שבו אל יהוה אלהיהם ולא בקשהו בכל זאת׃"));
hebsuperobject.biblemap.put("b28_7_11", new hebsuperobject(28,7,11,"ויהי אפרים כיונה פותה אין לב מצרים קראו אשור הלכו׃"));
hebsuperobject.biblemap.put("b28_7_12", new hebsuperobject(28,7,12,"כאשר ילכו אפרוש עליהם רשתי כעוף השמים אורידם איסרם כשמע לעדתם׃"));
hebsuperobject.biblemap.put("b28_7_13", new hebsuperobject(28,7,13,"אוי להם כי נדדו ממני שד להם כי פשעו בי ואנכי אפדם והמה דברו עלי כזבים׃"));
hebsuperobject.biblemap.put("b28_7_14", new hebsuperobject(28,7,14,"ולא זעקו אלי בלבם כי יילילו על משכבותם על דגן ותירוש יתגוררו יסורו בי׃"));
hebsuperobject.biblemap.put("b28_7_15", new hebsuperobject(28,7,15,"ואני יסרתי חזקתי זרועתם ואלי יחשבו רע׃"));
hebsuperobject.biblemap.put("b28_7_16", new hebsuperobject(28,7,16,"ישובו לא על היו כקשת רמיה יפלו בחרב שריהם מזעם לשונם זו לעגם בארץ מצרים׃"));
hebsuperobject.biblemap.put("b28_8_1", new hebsuperobject(28,8,1,"אל חכך שפר כנשר על בית יהוה יען עברו בריתי ועל תורתי פשעו׃"));
hebsuperobject.biblemap.put("b28_8_2", new hebsuperobject(28,8,2,"לי יזעקו אלהי ידענוך ישראל׃"));
hebsuperobject.biblemap.put("b28_8_3", new hebsuperobject(28,8,3,"זנח ישראל טוב אויב ירדפו׃"));
hebsuperobject.biblemap.put("b28_8_4", new hebsuperobject(28,8,4,"הם המליכו ולא ממני השירו ולא ידעתי כספם וזהבם עשו להם עצבים למען יכרת׃"));
hebsuperobject.biblemap.put("b28_8_5", new hebsuperobject(28,8,5,"זנח עגלך שמרון חרה אפי בם עד מתי לא יוכלו נקין׃"));
hebsuperobject.biblemap.put("b28_8_6", new hebsuperobject(28,8,6,"כי מישראל והוא חרש עשהו ולא אלהים הוא כי שבבים יהיה עגל שמרון׃"));
hebsuperobject.biblemap.put("b28_8_7", new hebsuperobject(28,8,7,"כי רוח יזרעו וסופתה יקצרו קמה אין לו צמח בלי יעשה קמח אולי יעשה זרים יבלעהו׃"));
hebsuperobject.biblemap.put("b28_8_8", new hebsuperobject(28,8,8,"נבלע ישראל עתה היו בגוים ככלי אין חפץ בו׃"));
hebsuperobject.biblemap.put("b28_8_9", new hebsuperobject(28,8,9,"כי המה עלו אשור פרא בודד לו אפרים התנו אהבים׃"));
hebsuperobject.biblemap.put("b28_8_10", new hebsuperobject(28,8,10,"גם כי יתנו בגוים עתה אקבצם ויחלו מעט ממשא מלך שרים׃"));
hebsuperobject.biblemap.put("b28_8_11", new hebsuperobject(28,8,11,"כי הרבה אפרים מזבחת לחטא היו לו מזבחות לחטא׃"));
hebsuperobject.biblemap.put("b28_8_12", new hebsuperobject(28,8,12,"אכתוב לו רבו תורתי כמו זר נחשבו׃"));
hebsuperobject.biblemap.put("b28_8_13", new hebsuperobject(28,8,13,"זבחי הבהבי יזבחו בשר ויאכלו יהוה לא רצם עתה יזכר עונם ויפקד חטאותם המה מצרים ישובו׃"));
hebsuperobject.biblemap.put("b28_8_14", new hebsuperobject(28,8,14,"וישכח ישראל את עשהו ויבן היכלות ויהודה הרבה ערים בצרות ושלחתי אש בעריו ואכלה ארמנתיה׃"));
hebsuperobject.biblemap.put("b28_9_1", new hebsuperobject(28,9,1,"אל תשמח ישראל אל גיל כעמים כי זנית מעל אלהיך אהבת אתנן על כל גרנות דגן׃"));
hebsuperobject.biblemap.put("b28_9_2", new hebsuperobject(28,9,2,"גרן ויקב לא ירעם ותירוש יכחש בה׃"));
hebsuperobject.biblemap.put("b28_9_3", new hebsuperobject(28,9,3,"לא ישבו בארץ יהוה ושב אפרים מצרים ובאשור טמא יאכלו׃"));
hebsuperobject.biblemap.put("b28_9_4", new hebsuperobject(28,9,4,"לא יסכו ליהוה יין ולא יערבו לו זבחיהם כלחם אונים להם כל אכליו יטמאו כי לחמם לנפשם לא יבוא בית יהוה׃"));
hebsuperobject.biblemap.put("b28_9_5", new hebsuperobject(28,9,5,"מה תעשו ליום מועד וליום חג יהוה׃"));
hebsuperobject.biblemap.put("b28_9_6", new hebsuperobject(28,9,6,"כי הנה הלכו משד מצרים תקבצם מף תקברם מחמד לכספם קמוש יירשם חוח באהליהם׃"));
hebsuperobject.biblemap.put("b28_9_7", new hebsuperobject(28,9,7,"באו ימי הפקדה באו ימי השלם ידעו ישראל אויל הנביא משגע איש הרוח על רב עונך ורבה משטמה׃"));
hebsuperobject.biblemap.put("b28_9_8", new hebsuperobject(28,9,8,"צפה אפרים עם אלהי נביא פח יקוש על כל דרכיו משטמה בבית אלהיו׃"));
hebsuperobject.biblemap.put("b28_9_9", new hebsuperobject(28,9,9,"העמיקו שחתו כימי הגבעה יזכור עונם יפקוד חטאתם׃"));
hebsuperobject.biblemap.put("b28_9_10", new hebsuperobject(28,9,10,"כענבים במדבר מצאתי ישראל כבכורה בתאנה בראשיתה ראיתי אבותיכם המה באו בעל פעור וינזרו לבשת ויהיו שקוצים כאהבם׃"));
hebsuperobject.biblemap.put("b28_9_11", new hebsuperobject(28,9,11,"אפרים כעוף יתעופף כבודם מלדה ומבטן ומהריון׃"));
hebsuperobject.biblemap.put("b28_9_12", new hebsuperobject(28,9,12,"כי אם יגדלו את בניהם ושכלתים מאדם כי גם אוי להם בשורי מהם׃"));
hebsuperobject.biblemap.put("b28_9_13", new hebsuperobject(28,9,13,"אפרים כאשר ראיתי לצור שתולה בנוה ואפרים להוציא אל הורג בניו׃"));
hebsuperobject.biblemap.put("b28_9_14", new hebsuperobject(28,9,14,"תן להם יהוה מה תתן תן להם רחם משכיל ושדים צמקים׃"));
hebsuperobject.biblemap.put("b28_9_15", new hebsuperobject(28,9,15,"כל רעתם בגלגל כי שם שנאתים על רע מעלליהם מביתי אגרשם לא אוסף אהבתם כל שריהם סררים׃"));
hebsuperobject.biblemap.put("b28_9_16", new hebsuperobject(28,9,16,"הכה אפרים שרשם יבש פרי בלי יעשון גם כי ילדון והמתי מחמדי בטנם׃"));
hebsuperobject.biblemap.put("b28_9_17", new hebsuperobject(28,9,17,"ימאסם אלהי כי לא שמעו לו ויהיו נדדים בגוים׃"));
hebsuperobject.biblemap.put("b28_10_1", new hebsuperobject(28,10,1,"גפן בוקק ישראל פרי ישוה לו כרב לפריו הרבה למזבחות כטוב לארצו היטיבו מצבות׃"));
hebsuperobject.biblemap.put("b28_10_2", new hebsuperobject(28,10,2,"חלק לבם עתה יאשמו הוא יערף מזבחותם ישדד מצבותם׃"));
hebsuperobject.biblemap.put("b28_10_3", new hebsuperobject(28,10,3,"כי עתה יאמרו אין מלך לנו כי לא יראנו את יהוה והמלך מה יעשה לנו׃"));
hebsuperobject.biblemap.put("b28_10_4", new hebsuperobject(28,10,4,"דברו דברים אלות שוא כרת ברית ופרח כראש משפט על תלמי שדי׃"));
hebsuperobject.biblemap.put("b28_10_5", new hebsuperobject(28,10,5,"לעגלות בית און יגורו שכן שמרון כי אבל עליו עמו וכמריו עליו יגילו על כבודו כי גלה ממנו׃"));
hebsuperobject.biblemap.put("b28_10_6", new hebsuperobject(28,10,6,"גם אותו לאשור יובל מנחה למלך ירב בשנה אפרים יקח ויבוש ישראל מעצתו׃"));
hebsuperobject.biblemap.put("b28_10_7", new hebsuperobject(28,10,7,"נדמה שמרון מלכה כקצף על פני מים׃"));
hebsuperobject.biblemap.put("b28_10_8", new hebsuperobject(28,10,8,"ונשמדו במות און חטאת ישראל קוץ ודרדר יעלה על מזבחותם ואמרו להרים כסונו ולגבעות נפלו עלינו׃"));
hebsuperobject.biblemap.put("b28_10_9", new hebsuperobject(28,10,9,"מימי הגבעה חטאת ישראל שם עמדו לא תשיגם בגבעה מלחמה על בני עלוה׃"));
hebsuperobject.biblemap.put("b28_10_10", new hebsuperobject(28,10,10,"באותי ואסרם ואספו עליהם עמים באסרם לשתי עינתם׃"));
hebsuperobject.biblemap.put("b28_10_11", new hebsuperobject(28,10,11,"ואפרים עגלה מלמדה אהבתי לדוש ואני עברתי על טוב צוארה ארכיב אפרים יחרוש יהודה ישדד לו יעקב׃"));
hebsuperobject.biblemap.put("b28_10_12", new hebsuperobject(28,10,12,"זרעו לכם לצדקה קצרו לפי חסד נירו לכם ניר ועת לדרוש את יהוה עד יבוא וירה צדק לכם׃"));
hebsuperobject.biblemap.put("b28_10_13", new hebsuperobject(28,10,13,"חרשתם רשע עולתה קצרתם אכלתם פרי כחש כי בטחת בדרכך ברב גבוריך׃"));
hebsuperobject.biblemap.put("b28_10_14", new hebsuperobject(28,10,14,"וקאם שאון בעמך וכל מבצריך יושד כשד שלמן בית ארבאל ביום מלחמה אם על בנים רטשה׃"));
hebsuperobject.biblemap.put("b28_10_15", new hebsuperobject(28,10,15,"ככה עשה לכם בית אל מפני רעת רעתכם בשחר נדמה נדמה מלך ישראל׃"));
hebsuperobject.biblemap.put("b28_11_1", new hebsuperobject(28,11,1,"כי נער ישראל ואהבהו וממצרים קראתי לבני׃"));
hebsuperobject.biblemap.put("b28_11_2", new hebsuperobject(28,11,2,"קראו להם כן הלכו מפניהם לבעלים יזבחו ולפסלים יקטרון׃"));
hebsuperobject.biblemap.put("b28_11_3", new hebsuperobject(28,11,3,"ואנכי תרגלתי לאפרים קחם על זרועתיו ולא ידעו כי רפאתים׃"));
hebsuperobject.biblemap.put("b28_11_4", new hebsuperobject(28,11,4,"בחבלי אדם אמשכם בעבתות אהבה ואהיה להם כמרימי על על לחיהם ואט אליו אוכיל׃"));
hebsuperobject.biblemap.put("b28_11_5", new hebsuperobject(28,11,5,"לא ישוב אל ארץ מצרים ואשור הוא מלכו כי מאנו לשוב׃"));
hebsuperobject.biblemap.put("b28_11_6", new hebsuperobject(28,11,6,"וחלה חרב בעריו וכלתה בדיו ואכלה ממעצותיהם׃"));
hebsuperobject.biblemap.put("b28_11_7", new hebsuperobject(28,11,7,"ועמי תלואים למשובתי ואל על יקראהו יחד לא ירומם׃"));
hebsuperobject.biblemap.put("b28_11_8", new hebsuperobject(28,11,8,"איך אתנך אפרים אמגנך ישראל איך אתנך כאדמה אשימך כצבאים נהפך עלי לבי יחד נכמרו נחומי׃"));
hebsuperobject.biblemap.put("b28_11_9", new hebsuperobject(28,11,9,"לא אעשה חרון אפי לא אשוב לשחת אפרים כי אל אנכי ולא איש בקרבך קדוש ולא אבוא בעיר׃"));
hebsuperobject.biblemap.put("b28_11_10", new hebsuperobject(28,11,10,"אחרי יהוה ילכו כאריה ישאג כי הוא ישאג ויחרדו בנים מים׃"));
hebsuperobject.biblemap.put("b28_11_11", new hebsuperobject(28,11,11,"יחרדו כצפור ממצרים וכיונה מארץ אשור והושבתים על בתיהם נאם יהוה׃"));
hebsuperobject.biblemap.put("b28_11_12", new hebsuperobject(28,11,12,"סבבני בכחש אפרים ובמרמה בית ישראל ויהודה עד רד עם אל ועם קדושים נאמן׃"));
hebsuperobject.biblemap.put("b28_12_1", new hebsuperobject(28,12,1,"אפרים רעה רוח ורדף קדים כל היום כזב ושד ירבה וברית עם אשור יכרתו ושמן למצרים יובל׃"));
hebsuperobject.biblemap.put("b28_12_2", new hebsuperobject(28,12,2,"וריב ליהוה עם יהודה ולפקד על יעקב כדרכיו כמעלליו ישיב לו׃"));
hebsuperobject.biblemap.put("b28_12_3", new hebsuperobject(28,12,3,"בבטן עקב את אחיו ובאונו שרה את אלהים׃"));
hebsuperobject.biblemap.put("b28_12_4", new hebsuperobject(28,12,4,"וישר אל מלאך ויכל בכה ויתחנן לו בית אל ימצאנו ושם ידבר עמנו׃"));
hebsuperobject.biblemap.put("b28_12_5", new hebsuperobject(28,12,5,"ויהוה אלהי הצבאות יהוה זכרו׃"));
hebsuperobject.biblemap.put("b28_12_6", new hebsuperobject(28,12,6,"ואתה באלהיך תשוב חסד ומשפט שמר וקוה אל אלהיך תמיד׃"));
hebsuperobject.biblemap.put("b28_12_7", new hebsuperobject(28,12,7,"כנען בידו מאזני מרמה לעשק אהב׃"));
hebsuperobject.biblemap.put("b28_12_8", new hebsuperobject(28,12,8,"ויאמר אפרים אך עשרתי מצאתי און לי כל יגיעי לא ימצאו לי עון אשר חטא׃"));
hebsuperobject.biblemap.put("b28_12_9", new hebsuperobject(28,12,9,"ואנכי יהוה אלהיך מארץ מצרים עד אושיבך באהלים כימי מועד׃"));
hebsuperobject.biblemap.put("b28_12_10", new hebsuperobject(28,12,10,"ודברתי על הנביאים ואנכי חזון הרביתי וביד הנביאים אדמה׃"));
hebsuperobject.biblemap.put("b28_12_11", new hebsuperobject(28,12,11,"אם גלעד און אך שוא היו בגלגל שורים זבחו גם מזבחותם כגלים על תלמי שדי׃"));
hebsuperobject.biblemap.put("b28_12_12", new hebsuperobject(28,12,12,"ויברח יעקב שדה ארם ויעבד ישראל באשה ובאשה שמר׃"));
hebsuperobject.biblemap.put("b28_12_13", new hebsuperobject(28,12,13,"ובנביא העלה יהוה את ישראל ממצרים ובנביא נשמר׃"));
hebsuperobject.biblemap.put("b28_12_14", new hebsuperobject(28,12,14,"הכעיס אפרים תמרורים ודמיו עליו יטוש וחרפתו ישיב לו אדניו׃"));
hebsuperobject.biblemap.put("b28_13_1", new hebsuperobject(28,13,1,"כדבר אפרים רתת נשא הוא בישראל ויאשם בבעל וימת׃"));
hebsuperobject.biblemap.put("b28_13_2", new hebsuperobject(28,13,2,"ועתה יוספו לחטא ויעשו להם מסכה מכספם כתבונם עצבים מעשה חרשים כלה להם הם אמרים זבחי אדם עגלים ישקון׃"));
hebsuperobject.biblemap.put("b28_13_3", new hebsuperobject(28,13,3,"לכן יהיו כענן בקר וכטל משכים הלך כמץ יסער מגרן וכעשן מארבה׃"));
hebsuperobject.biblemap.put("b28_13_4", new hebsuperobject(28,13,4,"ואנכי יהוה אלהיך מארץ מצרים ואלהים זולתי לא תדע ומושיע אין בלתי׃"));
hebsuperobject.biblemap.put("b28_13_5", new hebsuperobject(28,13,5,"אני ידעתיך במדבר בארץ תלאבות׃"));
hebsuperobject.biblemap.put("b28_13_6", new hebsuperobject(28,13,6,"כמרעיתם וישבעו שבעו וירם לבם על כן שכחוני׃"));
hebsuperobject.biblemap.put("b28_13_7", new hebsuperobject(28,13,7,"ואהי להם כמו שחל כנמר על דרך אשור׃"));
hebsuperobject.biblemap.put("b28_13_8", new hebsuperobject(28,13,8,"אפגשם כדב שכול ואקרע סגור לבם ואכלם שם כלביא חית השדה תבקעם׃"));
hebsuperobject.biblemap.put("b28_13_9", new hebsuperobject(28,13,9,"שחתך ישראל כי בי בעזרך׃"));
hebsuperobject.biblemap.put("b28_13_10", new hebsuperobject(28,13,10,"אהי מלכך אפוא ויושיעך בכל עריך ושפטיך אשר אמרת תנה לי מלך ושרים׃"));
hebsuperobject.biblemap.put("b28_13_11", new hebsuperobject(28,13,11,"אתן לך מלך באפי ואקח בעברתי׃"));
hebsuperobject.biblemap.put("b28_13_12", new hebsuperobject(28,13,12,"צרור עון אפרים צפונה חטאתו׃"));
hebsuperobject.biblemap.put("b28_13_13", new hebsuperobject(28,13,13,"חבלי יולדה יבאו לו הוא בן לא חכם כי עת לא יעמד במשבר בנים׃"));
hebsuperobject.biblemap.put("b28_13_14", new hebsuperobject(28,13,14,"מיד שאול אפדם ממות אגאלם אהי דבריך מות אהי קטבך שאול נחם יסתר מעיני׃"));
hebsuperobject.biblemap.put("b28_13_15", new hebsuperobject(28,13,15,"כי הוא בין אחים יפריא יבוא קדים רוח יהוה ממדבר עלה ויבוש מקורו ויחרב מעינו הוא ישסה אוצר כל כלי חמדה׃"));
hebsuperobject.biblemap.put("b28_13_16", new hebsuperobject(28,13,16,"תאשם שמרון כי מרתה באלהיה בחרב יפלו עלליהם ירטשו והריותיו יבקעו׃"));
hebsuperobject.biblemap.put("b28_14_1", new hebsuperobject(28,14,1,"שובה ישראל עד יהוה אלהיך כי כשלת בעונך׃"));
hebsuperobject.biblemap.put("b28_14_2", new hebsuperobject(28,14,2,"קחו עמכם דברים ושובו אל יהוה אמרו אליו כל תשא עון וקח טוב ונשלמה פרים שפתינו׃"));
hebsuperobject.biblemap.put("b28_14_3", new hebsuperobject(28,14,3,"אשור לא יושיענו על סוס לא נרכב ולא נאמר עוד אלהינו למעשה ידינו אשר בך ירחם יתום׃"));
hebsuperobject.biblemap.put("b28_14_4", new hebsuperobject(28,14,4,"ארפא משובתם אהבם נדבה כי שב אפי ממנו׃"));
hebsuperobject.biblemap.put("b28_14_5", new hebsuperobject(28,14,5,"אהיה כטל לישראל יפרח כשושנה ויך שרשיו כלבנון׃"));
hebsuperobject.biblemap.put("b28_14_6", new hebsuperobject(28,14,6,"ילכו ינקותיו ויהי כזית הודו וריח לו כלבנון׃"));
hebsuperobject.biblemap.put("b28_14_7", new hebsuperobject(28,14,7,"ישבו ישבי בצלו יחיו דגן ויפרחו כגפן זכרו כיין לבנון׃"));
hebsuperobject.biblemap.put("b28_14_8", new hebsuperobject(28,14,8,"אפרים מה לי עוד לעצבים אני עניתי ואשורנו אני כברוש רענן ממני פריך נמצא׃"));
hebsuperobject.biblemap.put("b28_14_9", new hebsuperobject(28,14,9,"מי חכם ויבן אלה נבון וידעם כי ישרים דרכי יהוה וצדקים ילכו בם ופשעים יכשלו בם׃"));

}

}