package heb.bible;

public class hebbible58 {

public hebbible58() {

putmapbible58();

}

private void putmapbible58() {

hebsuperobject.biblemap.put("b58_1_1", new hebsuperobject(58,1,1,"האלהים אשר דבר מקדם פעמים רבות ובפנים שנים אל אבתינו ביד הנביאים דבר אלינו באחרית הימים האלה ביד בנו׃"));
hebsuperobject.biblemap.put("b58_1_2", new hebsuperobject(58,1,2,"אשר נתנו ליורש כל וגם עשה בידו את העולמות׃"));
hebsuperobject.biblemap.put("b58_1_3", new hebsuperobject(58,1,3,"והוא זהר כבודו וצלם ישותו ונושא כל בדבר גבורתו ואחרי עשתו בנפשו טהרת חטאתינו ישב לימין הגדלה במרומים׃"));
hebsuperobject.biblemap.put("b58_1_4", new hebsuperobject(58,1,4,"ויגדל מאד מן המלאכים כאשר השם אשר נחלו יקר הוא משלהם׃"));
hebsuperobject.biblemap.put("b58_1_5", new hebsuperobject(58,1,5,"כי אל מי מן המלאכים אמר מעולם בני אתה אני היום ילדתיך ועוד אני אהיה לו לאב והוא יהיה לי לבן׃"));
hebsuperobject.biblemap.put("b58_1_6", new hebsuperobject(58,1,6,"ובהביאו את הבכור שנית לעולם אמר והשתחוו לו כל מלאכים אלהים׃"));
hebsuperobject.biblemap.put("b58_1_7", new hebsuperobject(58,1,7,"הן על המלאכים הוא אמר עשה מלאכיו רוחות משרתיו אש להט׃"));
hebsuperobject.biblemap.put("b58_1_8", new hebsuperobject(58,1,8,"אך על הבן אמר כסאך אלהים עולם ועד שבט מישר שבט מלכותך׃"));
hebsuperobject.biblemap.put("b58_1_9", new hebsuperobject(58,1,9,"אהבת צדק ותשנא רשע על כן משחך אלהים אלהיך שמן ששון מחבריך׃"));
hebsuperobject.biblemap.put("b58_1_10", new hebsuperobject(58,1,10,"ועוד אתה אדני לפנים הארץ יסדת ומעשה ידיך שמים׃"));
hebsuperobject.biblemap.put("b58_1_11", new hebsuperobject(58,1,11,"המה יאבדו ואתה תעמד וכלם כבגד יבלו׃"));
hebsuperobject.biblemap.put("b58_1_12", new hebsuperobject(58,1,12,"כלבוש תחליפם ויחלפו ואתה הוא ושנותיך לא יתמו׃"));
hebsuperobject.biblemap.put("b58_1_13", new hebsuperobject(58,1,13,"ואל מי מן המלאכים אמר מעולם שב לימיני עד אשית איביך הדם לרגליך׃"));
hebsuperobject.biblemap.put("b58_1_14", new hebsuperobject(58,1,14,"הלא הם כלם רוחות השרת שלוחים לעזרה בעד העתידים לרשת את הישועה׃"));
hebsuperobject.biblemap.put("b58_2_1", new hebsuperobject(58,2,1,"לכן אנחנו חיבים ביותר להכין לבבנו אל אשר שמענו פן ילוז ויאבד ממנו׃"));
hebsuperobject.biblemap.put("b58_2_2", new hebsuperobject(58,2,2,"כי אם הדבר הנאמר על ידי המלאכים היה קים וכל פשע ומרי נשא את ענשו כמשפט׃"));
hebsuperobject.biblemap.put("b58_2_3", new hebsuperobject(58,2,3,"איך נמלט אנחנו אם לא נשים לב לתשועה גדולה אשר כזאת הנאמרה מתחלה בפי האדון ותקים לנו על ידי שמעיה׃"));
hebsuperobject.biblemap.put("b58_2_4", new hebsuperobject(58,2,4,"וגם אלהים העיד עליה באתות ובמופתים ובגבורות שנות ובהאציל מרוח קדשו כרצונו׃"));
hebsuperobject.biblemap.put("b58_2_5", new hebsuperobject(58,2,5,"כי לא תחת יד המלאכים שת את העולם הבא אשר אנחנו מדברים עליו׃"));
hebsuperobject.biblemap.put("b58_2_6", new hebsuperobject(58,2,6,"כי אם כאשר העיד האמר במקום אחד מה אנוש כי תזכרנו ובן אדם כי תפקדנו׃"));
hebsuperobject.biblemap.put("b58_2_7", new hebsuperobject(58,2,7,"ותחסרהו מעט מאלהים וכבוד והדר תעטרהו ותמשילהו במעשי ידיך׃"));
hebsuperobject.biblemap.put("b58_2_8", new hebsuperobject(58,2,8,"כל שתה תחת רגליו הנה באשר שת כל תחתיו לא השאיר דבר שלא שת תחתיו ועתה זה לא ראינו עדין כי כל הושת תחתיו׃"));
hebsuperobject.biblemap.put("b58_2_9", new hebsuperobject(58,2,9,"אבל ישוע המחסר מעט ממלאכים אותו ראינו מעטר בכבוד והדר מפני ענותו עד מות למען אשר יטעם בחסד אלהים את המות בעד כלם׃"));
hebsuperobject.biblemap.put("b58_2_10", new hebsuperobject(58,2,10,"כי נאה היה לו אשר הכל למענו והכל על ידו בהנחתו בנים רבים לכבוד להשלים בענוים את שר ישועתם׃"));
hebsuperobject.biblemap.put("b58_2_11", new hebsuperobject(58,2,11,"כי גם המקדש גם המקדשים כלם מאחד המה ועל כן לא בוש מקרא להם אחים׃"));
hebsuperobject.biblemap.put("b58_2_12", new hebsuperobject(58,2,12,"באמרו אספרה שמך לאחי בתוך קהל אהללך׃"));
hebsuperobject.biblemap.put("b58_2_13", new hebsuperobject(58,2,13,"ועוד וקויתי לו ועוד הנה אנכי והילדים אשר נתן לי יהוה׃"));
hebsuperobject.biblemap.put("b58_2_14", new hebsuperobject(58,2,14,"ויען כי הילדים כלם יחדו בשר ודם אף הוא לבש בשר ודם כמוהם למען אשר יבטל על ידי המות את אשר לו ממשלת המות הוא השטן׃"));
hebsuperobject.biblemap.put("b58_2_15", new hebsuperobject(58,2,15,"ולהתיר את אלה אשר מאימת המות היו נתנים לעבדות כל ימי חייהם׃"));
hebsuperobject.biblemap.put("b58_2_16", new hebsuperobject(58,2,16,"כי אמנם לא במלאכים החזיק כי אם בזרע אברהם החזיק׃"));
hebsuperobject.biblemap.put("b58_2_17", new hebsuperobject(58,2,17,"על כן היה עליו להדמות לאחיו בכל דבר למען אשר יהיה כהן גדול רחמן ונאמן בעניני אלהים לכפר על חטאת העם׃"));
hebsuperobject.biblemap.put("b58_2_18", new hebsuperobject(58,2,18,"כי באשר הוא בעצמו ענה ונתנסה יכל לעזר את המנסים׃"));
hebsuperobject.biblemap.put("b58_3_1", new hebsuperobject(58,3,1,"לכן אחי הקדושים חברים לקריאה של מעלה הביטו אל השליח וכהן הודיתנו הגדול אל המשיח ישוע׃"));
hebsuperobject.biblemap.put("b58_3_2", new hebsuperobject(58,3,2,"אשר הוא נאמן לעשהו כמו גם משה בכל ביתו׃"));
hebsuperobject.biblemap.put("b58_3_3", new hebsuperobject(58,3,3,"כי כבוד גדול ממשה נחל זה כאשר בנה הבית חשוב יותר מן הבית׃"));
hebsuperobject.biblemap.put("b58_3_4", new hebsuperobject(58,3,4,"כי כל בית יש לו בנה אבל בונה כל הוא האלהים׃"));
hebsuperobject.biblemap.put("b58_3_5", new hebsuperobject(58,3,5,"והן משה נאמן בכל ביתו כעבד לעדות העמדות להאמר׃"));
hebsuperobject.biblemap.put("b58_3_6", new hebsuperobject(58,3,6,"אבל המשיח הוא הבן על ביתו ואנחנו ביתו אם נחזיק בבטחון ובתהלת התקוה ולא נרפנה עד הקץ׃"));
hebsuperobject.biblemap.put("b58_3_7", new hebsuperobject(58,3,7,"לכן כמאמר רוח הקדש היום אם בקלו תשמעו׃"));
hebsuperobject.biblemap.put("b58_3_8", new hebsuperobject(58,3,8,"אל תקשו לבבכם כמריבה כיום מסה במדבר׃"));
hebsuperobject.biblemap.put("b58_3_9", new hebsuperobject(58,3,9,"אשר נסוני אבותיכם בחנוני גם ראו פעלי ארבעים שנה׃"));
hebsuperobject.biblemap.put("b58_3_10", new hebsuperobject(58,3,10,"לכן אקוט בדור ואמר עם תעי לבב הם והם לא ידעו דרכי׃"));
hebsuperobject.biblemap.put("b58_3_11", new hebsuperobject(58,3,11,"אשר נשבעתי באפי אם יבאון אל מנוחתי׃"));
hebsuperobject.biblemap.put("b58_3_12", new hebsuperobject(58,3,12,"ראו עתה אחי פן יש באחד מכם לב רע וחסר אמונה לסור מאלהים חיים׃"));
hebsuperobject.biblemap.put("b58_3_13", new hebsuperobject(58,3,13,"אך הוכח תוכיחו איש את רעהו יום יום עד שיקרא היום למען אשר לא יקשה איש מכם את לבו במדוחי פשע׃"));
hebsuperobject.biblemap.put("b58_3_14", new hebsuperobject(58,3,14,"כי נתחברנו למשיח אם נחזיק בראשית הבטחה ולא נרפנה עד הקץ׃"));
hebsuperobject.biblemap.put("b58_3_15", new hebsuperobject(58,3,15,"כאשר נאמר היום אם בקלו תשמעו אל תקשו לבבכם כמריבה׃"));
hebsuperobject.biblemap.put("b58_3_16", new hebsuperobject(58,3,16,"מי אפוא אלה אשר שמעו ויריבו הלא כל יצאי מצרים ביד משה׃"));
hebsuperobject.biblemap.put("b58_3_17", new hebsuperobject(58,3,17,"ובמי התקוטט ארבעים שנה הלא בחטאים אשר נפלו פגריהם במדבר׃"));
hebsuperobject.biblemap.put("b58_3_18", new hebsuperobject(58,3,18,"ולמי נשבע לבלתי בא אל מנוחתו אם לא לסוררים׃"));
hebsuperobject.biblemap.put("b58_3_19", new hebsuperobject(58,3,19,"ואנחנו ראים כי לא יכלו לבוא על אשר לא האמינו׃"));
hebsuperobject.biblemap.put("b58_4_1", new hebsuperobject(58,4,1,"על כן נירא נא בהמצא עוד ההבטחה לבוא אל מנוחתו פן יראה איש מכם מאחר פעמיו׃"));
hebsuperobject.biblemap.put("b58_4_2", new hebsuperobject(58,4,2,"כי גם אלינו באה הבשורה כמו אליהם אך לא הועיל להם דבר השמועה מפני אשר לא התערב באמונה לשמעים׃"));
hebsuperobject.biblemap.put("b58_4_3", new hebsuperobject(58,4,3,"כי באי המונה אנחנו המאמינים כמו שאמר אשר נשבעתי באפי אם יבאון אל מנוחתי אף כי נגמרו מעשי יהוה מעת הוסד העולם׃"));
hebsuperobject.biblemap.put("b58_4_4", new hebsuperobject(58,4,4,"כי על היום השביעי אמר במקום אחד וישבת ביום השביעי מכל מלאכתו׃"));
hebsuperobject.biblemap.put("b58_4_5", new hebsuperobject(58,4,5,"ובמקום הזה אמר עוד אם יבאון אל מנוחתי׃"));
hebsuperobject.biblemap.put("b58_4_6", new hebsuperobject(58,4,6,"ויען כי יש עוד מקום לבוא אליה ואשר התבשרו בראשונה המה לא באו שם בעבור המרי׃"));
hebsuperobject.biblemap.put("b58_4_7", new hebsuperobject(58,4,7,"לכן הוסיף לקבוע יום באמרו היום על ידי דוד מקץ ימים רבים כמו שנאמר היום אם בקלו תשמעו אל תקשו לבבכם׃"));
hebsuperobject.biblemap.put("b58_4_8", new hebsuperobject(58,4,8,"כי אלו יהושע הניח להם לא היה מדבר אחרי זאת על יום אחר׃"));
hebsuperobject.biblemap.put("b58_4_9", new hebsuperobject(58,4,9,"על כן נשארה עוד מנוחת שבת לעם אלהים׃"));
hebsuperobject.biblemap.put("b58_4_10", new hebsuperobject(58,4,10,"כי הבא אל מנוחתו גם הוא שבת ממלאכתו כמו האלהים משלו׃"));
hebsuperobject.biblemap.put("b58_4_11", new hebsuperobject(58,4,11,"לכן נשקדה נא לבוא אל המנוחה ההיא למען אשר לא יכשל איש והיה ממרה כמוהם׃"));
hebsuperobject.biblemap.put("b58_4_12", new hebsuperobject(58,4,12,"כי דבר האלהים חי הוא ופעל גבורות וחד מחרב פיפיות ונכנס עד להבדיל בין נפש לרוח ובין הדבקים למוח ובחן מחשבות לבב ומזמותיו׃"));
hebsuperobject.biblemap.put("b58_4_13", new hebsuperobject(58,4,13,"ואין כל נברא נסתר מנגדו כי הכל חשוף וגלוי לעיני בעל דברים שלנו׃"));
hebsuperobject.biblemap.put("b58_4_14", new hebsuperobject(58,4,14,"ועתה בהיות לנו כהן ראש גדול אשר עבר בשמים הוא ישוע בן האלהים נחזיקה בהודאתנו׃"));
hebsuperobject.biblemap.put("b58_4_15", new hebsuperobject(58,4,15,"כי אין לנו כהן גדול אשר לא יוכל להצטער על חליינו כי אם המנסה בכל כמונו אך בלי חטא׃"));
hebsuperobject.biblemap.put("b58_4_16", new hebsuperobject(58,4,16,"על כן נקרבה בבטחון אל כסא החסד לשאת רחמים ולמצא חסד לעזרה בעתה׃"));
hebsuperobject.biblemap.put("b58_5_1", new hebsuperobject(58,5,1,"כי כל כהן גדול הלקוח מתוך בני אדם מפקד הוא בעבור בני אדם בעניני אלהים להקריב מנחה וזבח על החטאים׃"));
hebsuperobject.biblemap.put("b58_5_2", new hebsuperobject(58,5,2,"והוא יכול לחמל על השגגים והתעים בהיותו גם הוא ידוע חלי׃"));
hebsuperobject.biblemap.put("b58_5_3", new hebsuperobject(58,5,3,"אשר על כן חיב להקריב על החטאים גם בעד העם גם בעד נפשו׃"));
hebsuperobject.biblemap.put("b58_5_4", new hebsuperobject(58,5,4,"ואת הגדלה הזאת לא יקח איש לעצמו רק הקרוא לה מאת האלהים כמו אהרן׃"));
hebsuperobject.biblemap.put("b58_5_5", new hebsuperobject(58,5,5,"כן גם המשיח לא כבד את עצמו להיות כהן גדול כי אם האמר אליו בני אתה אני היום ילדתיך׃"));
hebsuperobject.biblemap.put("b58_5_6", new hebsuperobject(58,5,6,"כמו שאמר גם במקום אחר אתה כהן לעולם על דברתי מלכי צדק׃"));
hebsuperobject.biblemap.put("b58_5_7", new hebsuperobject(58,5,7,"אשר בימי היותו בבשר הקריב תפלות ותחנונים בצעקה גדולה ובדעות לפני מי שיכול להושיעו ממות ויעתר לו מפני יראתו׃"));
hebsuperobject.biblemap.put("b58_5_8", new hebsuperobject(58,5,8,"ואף כי היה הבן למד מענותו לשמוע׃"));
hebsuperobject.biblemap.put("b58_5_9", new hebsuperobject(58,5,9,"ואחרי אשר השלם היה ממציא תשועת עולמים לכל שמעיו׃"));
hebsuperobject.biblemap.put("b58_5_10", new hebsuperobject(58,5,10,"והאלהים קרא לו כהן גדול על דברתי מלכי צדק׃"));
hebsuperobject.biblemap.put("b58_5_11", new hebsuperobject(58,5,11,"על זאת יש לנו לדבר הרבה וקשות לבאר לכם במלין יען כי כבדו אזניכם׃"));
hebsuperobject.biblemap.put("b58_5_12", new hebsuperobject(58,5,12,"כי תחת אשר היה ראוי לכם לפי ארך הזמן להיות מלמדים עתה מן הצרך לשוב וללמד אתכם עקרי ראשית דברי אלהים ונצרכתם לחלב ולא למאכל בריא׃"));
hebsuperobject.biblemap.put("b58_5_13", new hebsuperobject(58,5,13,"כי כל אשר מאכלו חלב איננו מבין בדבר צדק כי עודנו עולל׃"));
hebsuperobject.biblemap.put("b58_5_14", new hebsuperobject(58,5,14,"אך לשלמים המאכל הבריא אשר על פי ההרגל יש להם חושים מנסים להבדיל בין טוב לרע׃"));
hebsuperobject.biblemap.put("b58_6_1", new hebsuperobject(58,6,1,"על כן בעזב כעת ראשית דבר המשיח נעבר אל השלמות ולא נשוב לשית יסודי התשובה ממעשי מות והאמונה באלהים׃"));
hebsuperobject.biblemap.put("b58_6_2", new hebsuperobject(58,6,2,"ותורת הטבילות וסמיכת ידים ותחית המתים והדין הנצחי׃"));
hebsuperobject.biblemap.put("b58_6_3", new hebsuperobject(58,6,3,"ואת זאת נעשה אם יתן האל׃"));
hebsuperobject.biblemap.put("b58_6_4", new hebsuperobject(58,6,4,"כי אלה אשר נגה עליהם האור וטעמו ממתנת השמים ונתן להם חלקם ברוח הקדש׃"));
hebsuperobject.biblemap.put("b58_6_5", new hebsuperobject(58,6,5,"וטעמו את דבר אלהים הטוב וכחות העולם הבא וימעלו מעל׃"));
hebsuperobject.biblemap.put("b58_6_6", new hebsuperobject(58,6,6,"נמנעו מהתחדש עוד לתשובה כי צלבו להם מחדש את בן האלהים ויתנוהו למשל׃"));
hebsuperobject.biblemap.put("b58_6_7", new hebsuperobject(58,6,7,"כי האדמה השותה את הגשם הירד עליה למכביר ומוציאה עשב טוב לעבדיה תשא ברכה מאת האלהים׃"));
hebsuperobject.biblemap.put("b58_6_8", new hebsuperobject(58,6,8,"ואשר תוציא קוץ ודרדר נמאסה היא וקרובה למארה וסופה להשרף׃"));
hebsuperobject.biblemap.put("b58_6_9", new hebsuperobject(58,6,9,"אמנם ידידי מבטחים אנחנו בכם טבות מאלה וקרבות לישועה אף כי דברנו כזאת׃"));
hebsuperobject.biblemap.put("b58_6_10", new hebsuperobject(58,6,10,"כי האלהים לא יעות צדק לשכח את מעשיכם ואת עמל אהבתכם אשר הראיתם לשמו ששרתם ועודכם משרתים את הקדשים׃"));
hebsuperobject.biblemap.put("b58_6_11", new hebsuperobject(58,6,11,"אבל חפצנו שכל אחד מכם גם ישקד שקוד להחזיק בשלמות התקוה עד הקץ׃"));
hebsuperobject.biblemap.put("b58_6_12", new hebsuperobject(58,6,12,"שלא תעצלו כי אם תלכו בעקבות היורשים באמונה וארך רוח את ההבטחות׃"));
hebsuperobject.biblemap.put("b58_6_13", new hebsuperobject(58,6,13,"כי בהבטיח אלהים את אברהם נשבע בנפשו יען אשר אין גדול ממנו להשבע בו׃"));
hebsuperobject.biblemap.put("b58_6_14", new hebsuperobject(58,6,14,"ויאמר כי ברך אברכך והרבה ארבה אותך׃"));
hebsuperobject.biblemap.put("b58_6_15", new hebsuperobject(58,6,15,"ויהי בהאריך נפשו השיג את ההבטחה׃"));
hebsuperobject.biblemap.put("b58_6_16", new hebsuperobject(58,6,16,"בני האדם ישבעו בגדול מהם והשבועה להם קץ כל ערעור לקיום הדבר׃"));
hebsuperobject.biblemap.put("b58_6_17", new hebsuperobject(58,6,17,"על כן כאשר רצה האלהים להראות ביותר את ירשי ההבטחה כי לא תשתנה עצתו ערב אתה בשבועה׃"));
hebsuperobject.biblemap.put("b58_6_18", new hebsuperobject(58,6,18,"למען על פי שני דברים בלתי משתנים אשר חלילה לאלהים לשקר בם יהיה לנו אשר נסנו עליו זרוז גדול לאחז בתקוה הנתונה לפנינו׃"));
hebsuperobject.biblemap.put("b58_6_19", new hebsuperobject(58,6,19,"אשר היא לנפשנו לעוגין נכון וחזק ומגיע אל מבית לפרכת׃"));
hebsuperobject.biblemap.put("b58_6_20", new hebsuperobject(58,6,20,"אשר בא שמה ישוע העבר לפנינו ויהי כהן גדול לעולם על דברתי מלכי צדק׃"));
hebsuperobject.biblemap.put("b58_7_1", new hebsuperobject(58,7,1,"כי זה מלכי צדק מלך שלם כהן לאל עליון אשר יצא לקראת אברהם בשובו מהכות את המלכים ויברכהו׃"));
hebsuperobject.biblemap.put("b58_7_2", new hebsuperobject(58,7,2,"ואשר חלק לו אברהם מעשר מכל שמו יפרש מלך הצדק ועוד מלך שלם הוא מלך השלום׃"));
hebsuperobject.biblemap.put("b58_7_3", new hebsuperobject(58,7,3,"באין אב באין אם באין יחש ולימיו אין תחלה ולחייו אין סוף כי אם נדמה לבן האלהים הוא עומד בכהנתו לנצח׃"));
hebsuperobject.biblemap.put("b58_7_4", new hebsuperobject(58,7,4,"ראו עתה מה גדול הוא אשר גם אברהם אבינו נתן לו מעשר מראשית השלל׃"));
hebsuperobject.biblemap.put("b58_7_5", new hebsuperobject(58,7,5,"הן אלה מבני לוי אשר נחלי את הכהנה יש להם חק על פי התורה לקחת את המעשרות מן העם מן אחיהם אשר אף הם יצאי ירך אברהם׃"));
hebsuperobject.biblemap.put("b58_7_6", new hebsuperobject(58,7,6,"ואשר איננו מתיחש למשפחתם הוא לקח את המעשר מן אברהם ויברך את אשר היתה לו ההבטחה׃"));
hebsuperobject.biblemap.put("b58_7_7", new hebsuperobject(58,7,7,"והנה נכון הדבר כי הקטן יברך על ידי הגדול ממנו׃"));
hebsuperobject.biblemap.put("b58_7_8", new hebsuperobject(58,7,8,"ופה בני אדם שימותו לקחים את המעשר אבל שם לקחו מי שהועד עליו כי הוא חי׃"));
hebsuperobject.biblemap.put("b58_7_9", new hebsuperobject(58,7,9,"ויתכן לומר כי גם לוי הלקח את המעשרות היה מעשר בעשר אברהם׃"));
hebsuperobject.biblemap.put("b58_7_10", new hebsuperobject(58,7,10,"כי עוד בירך האב היה בצאת מלכי צדק לקראתו׃"));
hebsuperobject.biblemap.put("b58_7_11", new hebsuperobject(58,7,11,"על כן אלו היתה שלמות על ידי כהנת בני לוי אשר בה נתנה התורה לעם למה זה צריך לקום עוד כהן אחר על דברתי מלכי צדק ולא יאמר על דברתי אהרן׃"));
hebsuperobject.biblemap.put("b58_7_12", new hebsuperobject(58,7,12,"כי בהשתנות הכהנה מן הצרך שתשתנה גם התורה׃"));
hebsuperobject.biblemap.put("b58_7_13", new hebsuperobject(58,7,13,"כי אשר מדבר בו כזאת הוא משבט אחר אשר מעולם לא שרת איש ממנו את המזבח׃"));
hebsuperobject.biblemap.put("b58_7_14", new hebsuperobject(58,7,14,"כי גלוי לכל אשר אדנינו זרח מיהודה מן השבט אשר משה לא דבר אליו דבר על הכהנה׃"));
hebsuperobject.biblemap.put("b58_7_15", new hebsuperobject(58,7,15,"ועוד יותר ברור הוא אם יוקם על דמיון מלכי צדק כהן אחר׃"));
hebsuperobject.biblemap.put("b58_7_16", new hebsuperobject(58,7,16,"אשר איננו על פי חקת בשר ודם אלא על פי כח חיים בלתי נפסקים׃"));
hebsuperobject.biblemap.put("b58_7_17", new hebsuperobject(58,7,17,"כי העיד עליו אתה כהן לעולם על דברתי מלכי צדק׃"));
hebsuperobject.biblemap.put("b58_7_18", new hebsuperobject(58,7,18,"בעבור כי המצוה הקדמת הוסרה בהיותה חלושה וקצרת יד מהועיל׃"));
hebsuperobject.biblemap.put("b58_7_19", new hebsuperobject(58,7,19,"כי התורה לא השלימה דבר והנה נכנסה במקומה תקוה טובה ממנה אשר נקרב על ידה לאלהים׃"));
hebsuperobject.biblemap.put("b58_7_20", new hebsuperobject(58,7,20,"וכפי אשר לא היתה זאת בלי שבועה׃"));
hebsuperobject.biblemap.put("b58_7_21", new hebsuperobject(58,7,21,"כי המה נתכהנו בלי שבועה וזה בשבועה על ידי האמר לו נשבע יהוה ולא ינחם אתה כהן לעולם על דברתי מלכי צדק׃"));
hebsuperobject.biblemap.put("b58_7_22", new hebsuperobject(58,7,22,"גם הברית טובה ויתרה היא אשר ישוע ערב אותה׃"));
hebsuperobject.biblemap.put("b58_7_23", new hebsuperobject(58,7,23,"ושם נתכהנו רבים מפני אשר המות לא הניחם להותר בארץ׃"));
hebsuperobject.biblemap.put("b58_7_24", new hebsuperobject(58,7,24,"אבל זה בעמדו לעולם יש לו כהנה אשר לא תעבר ממנו׃"));
hebsuperobject.biblemap.put("b58_7_25", new hebsuperobject(58,7,25,"אשר על כן יוכל גם להושיע בכל וכל את הנגשים על ידו לאלהים כי חי הוא תמיד להפגיע בעדם׃"));
hebsuperobject.biblemap.put("b58_7_26", new hebsuperobject(58,7,26,"כי נאוה לנו כהן כזה שהוא חסיד ותמים וטהור ונבדל מן החטאים ונשא מהשמים׃"));
hebsuperobject.biblemap.put("b58_7_27", new hebsuperobject(58,7,27,"אשר איננו צריך יום יום ככהנים הגדולים ההם להקריב בראשונה על חטאתיו ואחרי כן על חטאת העם כי זאת עשה בפעם אחת בהקריבו את נפשו׃"));
hebsuperobject.biblemap.put("b58_7_28", new hebsuperobject(58,7,28,"כי התורה העמידה לכהנים גדולים בני אדם חלשים אבל דבר השבועה הבאה אחרי התורה העמיד את הבן המשלם לעולם׃"));
hebsuperobject.biblemap.put("b58_8_1", new hebsuperobject(58,8,1,"וזה ראש הנאמרים כי יש לנו כהן גדול היושב לימין כסא הגבורה בשמים׃"));
hebsuperobject.biblemap.put("b58_8_2", new hebsuperobject(58,8,2,"והוא משרת הקדש והמשכן האמתי אשר כוננו אדני ולא אדם׃"));
hebsuperobject.biblemap.put("b58_8_3", new hebsuperobject(58,8,3,"כי כל כהן גדול הוא מפקד להקריב מנחות וזבחים ועל כן צריך שיהיה גם לזה דבר להקריב׃"));
hebsuperobject.biblemap.put("b58_8_4", new hebsuperobject(58,8,4,"והנה אלו היה בארץ לא היה כהן כי יש פה הכהנים המקריבים הקרבנות לפי התורה׃"));
hebsuperobject.biblemap.put("b58_8_5", new hebsuperobject(58,8,5,"ומכהנים לדמות וצל הדברים שבשמים כדבר יהוה אל משה בבאו לכלות את המשכן כי אמר אליו ראה ועשה הכל בתבניתו אשר אתה מראה בהר׃"));
hebsuperobject.biblemap.put("b58_8_6", new hebsuperobject(58,8,6,"ועתה הוא קבל שרות מעלה כפי מעלת הברית הנעשה על ידו אשר הוקמה על הבטחות טבות ויתרות׃"));
hebsuperobject.biblemap.put("b58_8_7", new hebsuperobject(58,8,7,"כי אלו היתה הראשונה ההיא תמימה לא יבקש מקום לשניה׃"));
hebsuperobject.biblemap.put("b58_8_8", new hebsuperobject(58,8,8,"כי כה אמר בהוכיח אתם הנה ימים באים נאם יהוה וכרתי את בית ישראל ואת בית יהודה ברית חדשה׃"));
hebsuperobject.biblemap.put("b58_8_9", new hebsuperobject(58,8,9,"לא כברית אשר כרתי את אבותם ביום החזיקי בידם להוציאם מארץ מצרים אשר המה הפרו את בריתי ואנכי בחלתי בם נאם יהוה׃"));
hebsuperobject.biblemap.put("b58_8_10", new hebsuperobject(58,8,10,"כי זאת הברית אשר אכרת את בית ישראל אחרי הימים ההם נאם יהוה נתתי את תורתי בקרבם ועל לבם אכתבנה והייתי להם לאלהים והמה יהיו לי לעם׃"));
hebsuperobject.biblemap.put("b58_8_11", new hebsuperobject(58,8,11,"ולא ילמדו עוד איש את רעהו ואיש את אחיו לאמר דעו את יהוה כי כולם ידעו אותי למקטנם ועד גדולם׃"));
hebsuperobject.biblemap.put("b58_8_12", new hebsuperobject(58,8,12,"כי אסלח לעונם ולחטאתם ולפשעיהם לא אזכר עוד׃"));
hebsuperobject.biblemap.put("b58_8_13", new hebsuperobject(58,8,13,"הנה באמרו ברית חדשה ישן את הראשונה ומה שהוא נושן ומזקין קרוב הוא אל קצו׃"));
hebsuperobject.biblemap.put("b58_9_1", new hebsuperobject(58,9,1,"הן היה גם לברית הראשונה משפטי העבודה ומקדש ארצי׃"));
hebsuperobject.biblemap.put("b58_9_2", new hebsuperobject(58,9,2,"כי הוקם המשכן החיצון אשר בו המנורה והשלחן ומערכת הלחם והוא נקרא קדש׃"));
hebsuperobject.biblemap.put("b58_9_3", new hebsuperobject(58,9,3,"ומבית לפרכת השנית משכן הנקרא קדש הקדשים׃"));
hebsuperobject.biblemap.put("b58_9_4", new hebsuperobject(58,9,4,"אשר לו מזבח הזהב לקטרת וארון הברית מצפה זהב כלו ובו צנצנת זהב אשר המן בתוכו ומטה אהרן אשר פרח ולוחות הברית׃"));
hebsuperobject.biblemap.put("b58_9_5", new hebsuperobject(58,9,5,"וממעל לו כרובי הכבוד הסככים על הכפרת לא נדבר כעת על כל אחד מהם בפרט׃"));
hebsuperobject.biblemap.put("b58_9_6", new hebsuperobject(58,9,6,"ואחרי שהוכנו אלה ככה באו הכהנים תמיד אל המשכן החיצון לעבד שם את עבודתם׃"));
hebsuperobject.biblemap.put("b58_9_7", new hebsuperobject(58,9,7,"ואל המשכן אשר לפנים ממנו בא שמה הכהן הגדול לבדו פעם אחת בשנה לא בבלי דם אשר יקריב בעד נפשו ובעד שגגות העם׃"));
hebsuperobject.biblemap.put("b58_9_8", new hebsuperobject(58,9,8,"ורוח הקדש מודיע בזאת כי לא נגלה הדרך אל הקדש כל הימים אשר המשכן החיצון יש לו לעמד׃"));
hebsuperobject.biblemap.put("b58_9_9", new hebsuperobject(58,9,9,"והוא משל על העת ההוה אשר בה מקריבים מנחות וזבחים אשר לא יוכלו להשלים את לבב העבד׃"));
hebsuperobject.biblemap.put("b58_9_10", new hebsuperobject(58,9,10,"אך משפטי הגוף המה עם המאכלות והמשקים והטבילות השנות אשר הושמו עד עת התקון׃"));
hebsuperobject.biblemap.put("b58_9_11", new hebsuperobject(58,9,11,"אבל המשיח בבאו להיות כהן גדול לטבות העתידות עבר בתוך המשכן המעלה בגדלה ושלמות אשר לא נעשה בידים כלומר אשר איננו בכלל הבריאה הזאת׃"));
hebsuperobject.biblemap.put("b58_9_12", new hebsuperobject(58,9,12,"גם לא בא בדם שעירים ועגלים אלא בדם נפשו בא בפעם אחת אל הקדש פנימה וימצא גאלת עולם׃"));
hebsuperobject.biblemap.put("b58_9_13", new hebsuperobject(58,9,13,"כי אם דם הפרים והשעירים ואפר הפרה אשר יזה על הטמאים יקדשם לטהרת גופם׃"));
hebsuperobject.biblemap.put("b58_9_14", new hebsuperobject(58,9,14,"אף כי דם המשיח אשר הקריב את עצמו לאלהים ברוח נצחי ובלי מום יטהר לבבכם ממעשי מות לעבד את אלהים חיים׃"));
hebsuperobject.biblemap.put("b58_9_15", new hebsuperobject(58,9,15,"ובעבור זאת הוא גם סרסר לברית חדשה למען אשר יירשו המקראים את הבטחת נחלת עולם אחרי אשר מת לפדות מן הפשעים אשר נעשו תחת הברית הראשונה׃"));
hebsuperobject.biblemap.put("b58_9_16", new hebsuperobject(58,9,16,"כי במקום שיש דיתיקי צריך לדעת מות מקימה׃"));
hebsuperobject.biblemap.put("b58_9_17", new hebsuperobject(58,9,17,"כי רק במות המת תכון דיתיקי ואיננה בתקפה בעוד מקימה בחיים׃"));
hebsuperobject.biblemap.put("b58_9_18", new hebsuperobject(58,9,18,"לכן גם הראשונה לא חנכה בלא דם׃"));
hebsuperobject.biblemap.put("b58_9_19", new hebsuperobject(58,9,19,"כי ככלות משה להגיד לכל העם את כל המצות כתורה לקח דם העגלים והשעירים עם מים ותולעת שני ואזוב ויזרק על הספר ועל כל העם׃"));
hebsuperobject.biblemap.put("b58_9_20", new hebsuperobject(58,9,20,"ויאמר הנה דם הברית אשר צוה אלהים אליכם׃"));
hebsuperobject.biblemap.put("b58_9_21", new hebsuperobject(58,9,21,"וכן הזה מן הדם על המשכן ועל כל כלי השרת׃"));
hebsuperobject.biblemap.put("b58_9_22", new hebsuperobject(58,9,22,"וכמעט הכל יטהר בדם על פי התורה ואין כפרה בלי שפיכת דם׃"));
hebsuperobject.biblemap.put("b58_9_23", new hebsuperobject(58,9,23,"לכן דמיוני הדברים שבשמים צריכים להטהר באלה והדברים שבשמים בעצמם צריכים להטהר בזבחים טובים מאלה׃"));
hebsuperobject.biblemap.put("b58_9_24", new hebsuperobject(58,9,24,"כי המשיח לא בא אל הקדש הנעשה בידים שהוא רק דמות האמתי כי אם בא אל עצם השמים לראות עתה בעדנו את פני האלהים׃"));
hebsuperobject.biblemap.put("b58_9_25", new hebsuperobject(58,9,25,"אף לא להקריב את נפשו פעמים רבות ככהן הגדול אשר בא שנה בשנה אל הקדש בדם אחרים׃"));
hebsuperobject.biblemap.put("b58_9_26", new hebsuperobject(58,9,26,"כי אם כן הוא הלא היה לו לענות פעמים רבות מראשית העולם ועתה בקץ העתים נגלה בפעם אחת כדי לבטל את החטא בזבח נפשו׃"));
hebsuperobject.biblemap.put("b58_9_27", new hebsuperobject(58,9,27,"וכאשר נגזר על בני אדם פעם אחת המות ואחריו הדין׃"));
hebsuperobject.biblemap.put("b58_9_28", new hebsuperobject(58,9,28,"כן הקרב המשיח פעם אחת למען שאת חטאי רבים ופעם שנית יראה בלי חטא לישועה למחכים לו׃"));
hebsuperobject.biblemap.put("b58_10_1", new hebsuperobject(58,10,1,"כי התורה בהיות בה צל הטבות העתידות ולא מראה עצם הדברים אין ביכלתה להשלים את הקרבים בקרבנות ההם אשר יקריבו תמיד מדי שנה בשנה׃"));
hebsuperobject.biblemap.put("b58_10_2", new hebsuperobject(58,10,2,"כי לולא זאת חדלו מהביאם באשר המקריבים בהטהרם פעם אחת לא היתה בהם עוד רגשת חטאים׃"));
hebsuperobject.biblemap.put("b58_10_3", new hebsuperobject(58,10,3,"אבל יש שם הזכרת החטאים שנה בשנה׃"));
hebsuperobject.biblemap.put("b58_10_4", new hebsuperobject(58,10,4,"כי דם הפרים והשעירים לא יוכל להסיר חטאים׃"));
hebsuperobject.biblemap.put("b58_10_5", new hebsuperobject(58,10,5,"ובעבור זאת אמר בבואו לעולם זבח ומנחה לא חפצת גוף כוננת לי׃"));
hebsuperobject.biblemap.put("b58_10_6", new hebsuperobject(58,10,6,"עולה וחטאה לא שאלת׃"));
hebsuperobject.biblemap.put("b58_10_7", new hebsuperobject(58,10,7,"אז אמרתי הנה באתי במגלת ספר כתוב עלי לעשות רצונך אלהי׃"));
hebsuperobject.biblemap.put("b58_10_8", new hebsuperobject(58,10,8,"אחרי אמרו למעלה זבח ומנחה עולה וחטאה לא חפצת ולא שאלת אשר יקריבו אתם על פי התורה׃"));
hebsuperobject.biblemap.put("b58_10_9", new hebsuperobject(58,10,9,"אז אמר הנה באתי לעשות רצונך אלהי מעביר בזה את הראשונה למען הקים את השניה׃"));
hebsuperobject.biblemap.put("b58_10_10", new hebsuperobject(58,10,10,"וברצון הזה מקדשים אנחנו על ידי הקרבת קרבן גוף ישוע המשיח בפעם אחת׃"));
hebsuperobject.biblemap.put("b58_10_11", new hebsuperobject(58,10,11,"וכל כהן עמד יום יום לשרת ומוסיף פעמים רבות להקריב אתן הקרבנות אשר לא יוכלו לעולם להעביר חטאים׃"));
hebsuperobject.biblemap.put("b58_10_12", new hebsuperobject(58,10,12,"אולם זה אחרי הקריבו זבח אחד על החטאים ישב עד עולם לימין האלהים׃"));
hebsuperobject.biblemap.put("b58_10_13", new hebsuperobject(58,10,13,"וחכה יחכה עד כי יושתו איביו הדם לרגליו׃"));
hebsuperobject.biblemap.put("b58_10_14", new hebsuperobject(58,10,14,"כי הוא בקרבן אחת השלים לנצח את המקדשים׃"));
hebsuperobject.biblemap.put("b58_10_15", new hebsuperobject(58,10,15,"ואף רוח הקדש מעיד לנו על זאת כי אחרי אמרו׃"));
hebsuperobject.biblemap.put("b58_10_16", new hebsuperobject(58,10,16,"זאת הברית אשר אכרת אתם אחרי הימים ההם אמר יהוה נתתי את תורתי בקרבם ועל לבם אכתבנה׃"));
hebsuperobject.biblemap.put("b58_10_17", new hebsuperobject(58,10,17,"ולעונם ולחטאתם לא אזכר עוד׃"));
hebsuperobject.biblemap.put("b58_10_18", new hebsuperobject(58,10,18,"והנה באשר נסלחו החטאים אין עוד קרבן עליהם׃"));
hebsuperobject.biblemap.put("b58_10_19", new hebsuperobject(58,10,19,"ועתה אחי בהיות לנו בטחון דרך הקדש בדם ישוע׃"));
hebsuperobject.biblemap.put("b58_10_20", new hebsuperobject(58,10,20,"דרך חדש וחי אשר חדש לנו בפרכת היא בשרו׃"));
hebsuperobject.biblemap.put("b58_10_21", new hebsuperobject(58,10,21,"ובהיות לנו כהן גדול על בית אלהים׃"));
hebsuperobject.biblemap.put("b58_10_22", new hebsuperobject(58,10,22,"נקרבה נא בלבב שלם ובאמונה תמימה מטהרים בהזית לבבנו מרוח רעה ורחוצי בשר במים טהורים׃"));
hebsuperobject.biblemap.put("b58_10_23", new hebsuperobject(58,10,23,"נחזיקה בהודית התקוה בל נמוט כי נאמן המבטיח׃"));
hebsuperobject.biblemap.put("b58_10_24", new hebsuperobject(58,10,24,"ונתבוננה זה על זה לעורר אתנו לאהבה ולמעשים טובים׃"));
hebsuperobject.biblemap.put("b58_10_25", new hebsuperobject(58,10,25,"ואל נעזב את כנאיתנו כמנהג קצת אנשים כי אם נוכיח איש את אחיו וביותר בראתכם כי קרוב היום׃"));
hebsuperobject.biblemap.put("b58_10_26", new hebsuperobject(58,10,26,"כי אם נחטא בזדון אחרי אשר קבלנו דעת האמת לא ישאר עוד זבח קרבן לכפר על החטא׃"));
hebsuperobject.biblemap.put("b58_10_27", new hebsuperobject(58,10,27,"כי אם בעותי הדין העתיד ואש קנאה אשר תאכל את הצררים׃"));
hebsuperobject.biblemap.put("b58_10_28", new hebsuperobject(58,10,28,"הן איש כי יפר תורת משה מות ימות בלי חמלה על פי שנים עדים או שלשה׃"));
hebsuperobject.biblemap.put("b58_10_29", new hebsuperobject(58,10,29,"מה תחשבו כמה יגדל הענש הראוי לרמס ברגלו את בן האלהים וחשב לחל את דם הברית אשר הוא מקדש בו ומחרף את רוח החסד׃"));
hebsuperobject.biblemap.put("b58_10_30", new hebsuperobject(58,10,30,"כי ידענו את האמר לי נקם ושלם ועוד כי ידין יהוה עמו׃"));
hebsuperobject.biblemap.put("b58_10_31", new hebsuperobject(58,10,31,"מה נורא לנפל ביד אלהים חיים׃"));
hebsuperobject.biblemap.put("b58_10_32", new hebsuperobject(58,10,32,"אבל זכרו נא את הימים הראשונים כי אז אחרי ארו עיניכם נשאתם כבד ענוים רבים׃"));
hebsuperobject.biblemap.put("b58_10_33", new hebsuperobject(58,10,33,"פעם בהיותכם לראי בחרפה ותוגה פעם בהשתתף לאשר הגיע אליהם כזאת׃"));
hebsuperobject.biblemap.put("b58_10_34", new hebsuperobject(58,10,34,"כי הצטערתם על מוסרי וגזלת רכושכם סבלתם בשמחה מדעתכם בנפשכם שיש לכם בשמים קנין טוב ממנו וקים לעד׃"));
hebsuperobject.biblemap.put("b58_10_35", new hebsuperobject(58,10,35,"לכן אל תשליכו את בטחונכם כי יש לו שכר רב׃"));
hebsuperobject.biblemap.put("b58_10_36", new hebsuperobject(58,10,36,"כי צריכים אתם לסבלנות למען תעשו רצון אלהים ונשאתם את ההבטחה׃"));
hebsuperobject.biblemap.put("b58_10_37", new hebsuperobject(58,10,37,"כי עוד מעט רגע והבא יבא לא יאחר׃"));
hebsuperobject.biblemap.put("b58_10_38", new hebsuperobject(58,10,38,"הצדיק באמונתו יחיה ואם יסג אחור לא רצתה נפשי בו׃"));
hebsuperobject.biblemap.put("b58_10_39", new hebsuperobject(58,10,39,"אמנם אנחנו איננו מן הנסוגים אחור לאבדם כי אם מן המאמינים להצלת הנפש׃"));
hebsuperobject.biblemap.put("b58_11_1", new hebsuperobject(58,11,1,"כי האמונה היא חסן הבטחון במקוה והוכחת דברים לא נראים׃"));
hebsuperobject.biblemap.put("b58_11_2", new hebsuperobject(58,11,2,"ובה נחלו האבות עדות׃"));
hebsuperobject.biblemap.put("b58_11_3", new hebsuperobject(58,11,3,"באמונה נבין כי העולמות נעשו בדבר האלהים למען אשר יצא הנראה מן הנעלם׃"));
hebsuperobject.biblemap.put("b58_11_4", new hebsuperobject(58,11,4,"באמונה הקריב הבל לאלהים זבח טוב מקין אשר היה לו לעדות כי צדיק הוא בהעיד אלהים על מנחתיו ובה עודנו מדבר אחרי מותו׃"));
hebsuperobject.biblemap.put("b58_11_5", new hebsuperobject(58,11,5,"באמונה לקח חנוך לבלתי ראותו המות ואיננו כי לקח אתו אלהים והועד עליו לפני הלקחו כי את האלהים התהלך׃"));
hebsuperobject.biblemap.put("b58_11_6", new hebsuperobject(58,11,6,"ובלי אמונה לא יוכל איש להיות רצוי אל האלהים כי כל הקרב אליו צריך להאמין כי יש אלהים וגמול הוא משיב לדרשיו׃"));
hebsuperobject.biblemap.put("b58_11_7", new hebsuperobject(58,11,7,"באמונה בנה נח ביראת יהוה את התבה להצלת ביתו אתרי אשר צוה על דברים לא נראים עדין וירשע בה את העולם ויהי לירש הצדקה עקב האמונה׃"));
hebsuperobject.biblemap.put("b58_11_8", new hebsuperobject(58,11,8,"באמונה שמע אברהם כאשר נקרא ללכת אל הארץ אשר יירשנה ויצא ולא ידע אנה יבוא׃"));
hebsuperobject.biblemap.put("b58_11_9", new hebsuperobject(58,11,9,"באמונה היה גר בארץ ההבטחה כמו בנכריה וישב באהלים הוא ויצחק ויעקב אשר ירשו עמו ההבטחה ההיא׃"));
hebsuperobject.biblemap.put("b58_11_10", new hebsuperobject(58,11,10,"כי חכה לעיר אשר יסודתה נאמנה ובונה ומכוננה האלהים׃"));
hebsuperobject.biblemap.put("b58_11_11", new hebsuperobject(58,11,11,"באמונה שרה גם היא קבלה הכח להזריע ותלד אחרי בלתה כי חשבה לנאמן את המבטיח׃"));
hebsuperobject.biblemap.put("b58_11_12", new hebsuperobject(58,11,12,"על כן מאחד אשר כמעט מת גופו יצאו ככוכבי השמים לרב וכחול על שפת הים אשר לא יספר׃"));
hebsuperobject.biblemap.put("b58_11_13", new hebsuperobject(58,11,13,"כפי אמונה מתו כל אלה ולא השיגו את ההבטחות רק מרחוק ראו אותן ויבטחו וישמחו לקראתן ויודו כי גרים הם ותושבים בארץ׃"));
hebsuperobject.biblemap.put("b58_11_14", new hebsuperobject(58,11,14,"הלא המדברים כזאת יודיעו כי הם מבקשי ארץ מושב׃"));
hebsuperobject.biblemap.put("b58_11_15", new hebsuperobject(58,11,15,"ואם היתה דעתם על הארץ ההיא אשר יצאו ממנה הלא היה בידם לשוב אליה׃"));
hebsuperobject.biblemap.put("b58_11_16", new hebsuperobject(58,11,16,"אכן נכספו למושב טוב ממנו והוא בשמים ועל כן לא בוש האלהים להקרא אלהיהם כי הכין להם עיר׃"));
hebsuperobject.biblemap.put("b58_11_17", new hebsuperobject(58,11,17,"באמונה העלה אברהם את יצחק כאשר נסה ואת יחידו הקריב המקבל את ההבטחות׃"));
hebsuperobject.biblemap.put("b58_11_18", new hebsuperobject(58,11,18,"אשר נאמר לו כי ביצחק יקרא לך זרע׃"));
hebsuperobject.biblemap.put("b58_11_19", new hebsuperobject(58,11,19,"ויחשב בלבו כי יכול יוכל אלהים להחיות גם את המתים על כן גם הושב אליו להיות למשל׃"));
hebsuperobject.biblemap.put("b58_11_20", new hebsuperobject(58,11,20,"באמונה ברך יצחק את יעקב ואת עשו וידבר על העתידות׃"));
hebsuperobject.biblemap.put("b58_11_21", new hebsuperobject(58,11,21,"באמונה ברך יעקב את שני בני יוסף לפני מותו וישתחו על ראש המטה׃"));
hebsuperobject.biblemap.put("b58_11_22", new hebsuperobject(58,11,22,"באמונה הזכיר יוסף בקרב קצו את יציאת בני ישראל ויצו על אדות עצמותיו׃"));
hebsuperobject.biblemap.put("b58_11_23", new hebsuperobject(58,11,23,"באמונה הצפינו את משה אבותיו שלשה ירחים אהרי הולדו כראתם את הילד כי טוב הוא ולא יראו את מצות המלך׃"));
hebsuperobject.biblemap.put("b58_11_24", new hebsuperobject(58,11,24,"באמונה מאן משה כאשר גדל להקרא בן לבת פרעה׃"));
hebsuperobject.biblemap.put("b58_11_25", new hebsuperobject(58,11,25,"ויבחר לסבל את עני עם אלהים מלהתענג לשעה בתענוגי החטא׃"));
hebsuperobject.biblemap.put("b58_11_26", new hebsuperobject(58,11,26,"בחשבו את חרפת המשיח לעשר גדול מאצרות מצרים כי הביט אל הגמול׃"));
hebsuperobject.biblemap.put("b58_11_27", new hebsuperobject(58,11,27,"באמונה עזב את ארץ מצרים ולא ירא מחמת המלך כי היה כראה אשר איננו נראה ויתחזק׃"));
hebsuperobject.biblemap.put("b58_11_28", new hebsuperobject(58,11,28,"באמונה עשה את הפסח ונתינת הדם למען אשר לא יגע המשחית בבכוריהם׃"));
hebsuperobject.biblemap.put("b58_11_29", new hebsuperobject(58,11,29,"באמונה עברו את ים סוף ביבשה אשר נסו מצרים גם המה לעבר בו ויטבעו׃"));
hebsuperobject.biblemap.put("b58_11_30", new hebsuperobject(58,11,30,"באמונה נפלו חומות יריחו אחרי הקיפו אותן שבעת ימים׃"));
hebsuperobject.biblemap.put("b58_11_31", new hebsuperobject(58,11,31,"באמונה לא אבדה רחב הזונה עם הסוררים כי אספה את המרגלים אל ביתה בשלום׃"));
hebsuperobject.biblemap.put("b58_11_32", new hebsuperobject(58,11,32,"ומה אמר עוד הן תקצר לי העת אם אספר מעשי גדעון וברק ושמשון ויפתח ודוד ושמואל והנביאים׃"));
hebsuperobject.biblemap.put("b58_11_33", new hebsuperobject(58,11,33,"אשר באמונה כבשו ממלכות ופעלו צדק והשגו הבטחות וסכרו פי אריות׃"));
hebsuperobject.biblemap.put("b58_11_34", new hebsuperobject(58,11,34,"וכבו גבורת האש ונמלטו מפי החרב והתחזקו מחלים ועשו חיל במלחמה והפילו מחנות זרים׃"));
hebsuperobject.biblemap.put("b58_11_35", new hebsuperobject(58,11,35,"נשים לקחו מתחיה את מתיהן ואחרים רטשו בענוים ולא אבו להנצל למען יזכו לתחיה טובה ממנה׃"));
hebsuperobject.biblemap.put("b58_11_36", new hebsuperobject(58,11,36,"מהם נסו בתעלולים ובמכות וגם נמסרו לכבל ומסגר׃"));
hebsuperobject.biblemap.put("b58_11_37", new hebsuperobject(58,11,37,"נסקלו באבנים נסרו במגרה נבחנו ביסורים מתו לפי חרב וינעו עטופי עורת כבשים ועזים בחסר ובעצר רעה ויגון׃"));
hebsuperobject.biblemap.put("b58_11_38", new hebsuperobject(58,11,38,"אשר העולם לא היה כדי להם הם תעו במדבר ובהרים ובמערות ובנקיקי הארץ׃"));
hebsuperobject.biblemap.put("b58_11_39", new hebsuperobject(58,11,39,"וכל אלה אף היתה להם העדות בגלל אמונתם לא קבלו את ההבטחה׃"));
hebsuperobject.biblemap.put("b58_11_40", new hebsuperobject(58,11,40,"למען אשר לא ישלמו בלעדינו כי צפה לנו אלהים מקדם טובה יתרה׃"));
hebsuperobject.biblemap.put("b58_12_1", new hebsuperobject(58,12,1,"לכן גם אנחנו אשר ענן עדים רב כזה סבב אתנו נשליכה ממנו כל טרח והחטא המקיף עלינו ונרוצה בתוחלת את המרוצה הערוכה לפנינו׃"));
hebsuperobject.biblemap.put("b58_12_2", new hebsuperobject(58,12,2,"ונביטה אל ישוע ראש האמונה ומשלימה אשר בעד השמחה השמורה לו סבל את הצלב ויבז החרפה וישב לימין כסא האלהים׃"));
hebsuperobject.biblemap.put("b58_12_3", new hebsuperobject(58,12,3,"התבוננו אליו אשר נשא כלמת חטאים גדולה כזאת למען לא תיעפו ולא תיגעו בנפשותיכם׃"));
hebsuperobject.biblemap.put("b58_12_4", new hebsuperobject(58,12,4,"עדין לא עמדתם עד לדם במלחמתכם עם החטא׃"));
hebsuperobject.biblemap.put("b58_12_5", new hebsuperobject(58,12,5,"ותשכחו דבר הנחומים המדבר אליכם כמו אל בנים לאמר מוסר יהוה בני אל תמאס ואל תקץ בתוכחתו׃"));
hebsuperobject.biblemap.put("b58_12_6", new hebsuperobject(58,12,6,"כי את אשר יאהב יהוה יוכיח יכאב את בן ירצה׃"));
hebsuperobject.biblemap.put("b58_12_7", new hebsuperobject(58,12,7,"אם סבלים אתם מוסר דעו כי כאב עם בניו כן מתנהג אלהים עמכם כי איה הבן אשר אביו לא ייסרנו׃"));
hebsuperobject.biblemap.put("b58_12_8", new hebsuperobject(58,12,8,"אך אם תהיו באין מוסר אשר היה מנת כלם אז ממזרים אתם ולא בנים׃"));
hebsuperobject.biblemap.put("b58_12_9", new hebsuperobject(58,12,9,"ועוד אם אבות בשרנו היו מיסרים אתנו ונירא מהם אף כי נכנע לפני אבי הרוחות ונחיה׃"));
hebsuperobject.biblemap.put("b58_12_10", new hebsuperobject(58,12,10,"כי המה יסרונו כטוב בעיניהם לימים מעטים אבל זה להועיל למען יהיה לנו חלק בקדשתו׃"));
hebsuperobject.biblemap.put("b58_12_11", new hebsuperobject(58,12,11,"וכל מוסר בעת עברו עלינו איננו שמחה בעינינו כי אם יגון אולם באחריתו יתן פרי שלום לצדקה למלמדים בו׃"));
hebsuperobject.biblemap.put("b58_12_12", new hebsuperobject(58,12,12,"על כן חזקו ידים רפות וברכים כשלות׃"));
hebsuperobject.biblemap.put("b58_12_13", new hebsuperobject(58,12,13,"ומעגל רגליכם פלסו למען לא תטה הצלעה מן הדרך כי אם תרפא׃"));
hebsuperobject.biblemap.put("b58_12_14", new hebsuperobject(58,12,14,"רדפו את השלום עם כל אדם ואת הקדשה אשר בלעדיה לא יראה איש את האדון׃"));
hebsuperobject.biblemap.put("b58_12_15", new hebsuperobject(58,12,15,"והזהרו פן יש בכם איש מתאחר מחסד אלהים פן יוגיעכם שרש פרה לענה ויטמאו בו רבים׃"));
hebsuperobject.biblemap.put("b58_12_16", new hebsuperobject(58,12,16,"פן ימצא בכם זנה או חלל כעשו אשר בנזיד אחד מכר את בכורתו׃"));
hebsuperobject.biblemap.put("b58_12_17", new hebsuperobject(58,12,17,"הלא ידעתם כי גם נמאס אחרי כן כאשר רצה לרשת את הברכה כי לא מצא מקום לתשובה אף בקש אותה בדמעות׃"));
hebsuperobject.biblemap.put("b58_12_18", new hebsuperobject(58,12,18,"כי לא באתם אל הר נמשש ובער באש ולא אל ענן וערפל וסערה׃"));
hebsuperobject.biblemap.put("b58_12_19", new hebsuperobject(58,12,19,"ולא לקול שופר ולקול הדברים אשר שמעיו בקשו שלא יוסיף לדבר עמהם עוד׃"));
hebsuperobject.biblemap.put("b58_12_20", new hebsuperobject(58,12,20,"כי לא יכלו לשאת את אשר צוו ואם בהמה תגע בהר סקל תקסל או ירה תירה בחצים׃"));
hebsuperobject.biblemap.put("b58_12_21", new hebsuperobject(58,12,21,"והמראה היה נורא עד מאד ויאמר משה יגרתי וחרדתי׃"));
hebsuperobject.biblemap.put("b58_12_22", new hebsuperobject(58,12,22,"כי אם באתם אל הר ציון ואל עיר אלהים חיים אל ירושלים שבשמים׃"));
hebsuperobject.biblemap.put("b58_12_23", new hebsuperobject(58,12,23,"ואל עצרת רבבות המלאכים ועדת הבכורים הכתובים בשמים ואל אלהים שפט הכל ואל רוחות הצדיקים הנשלמים׃"));
hebsuperobject.biblemap.put("b58_12_24", new hebsuperobject(58,12,24,"ואל ישוע סרסר הברית החדשה ואל דם ההזאה המיטיב דבר מדם הבל׃"));
hebsuperobject.biblemap.put("b58_12_25", new hebsuperobject(58,12,25,"לכן ראו פן תמאנו לשמע אל המדבר כי הן לא נמלטו המאנים לשמע אל המדבר עמהם בארץ אף אנחנו אם נמאן לשמע בקול המדבר מן השמים׃"));
hebsuperobject.biblemap.put("b58_12_26", new hebsuperobject(58,12,26,"אשר קולו הרעיש אז את הארץ ועתה זה הבטיח לאמר עוד אחת ואני מרעיש לא לבד את הארץ כי גם את השמים׃"));
hebsuperobject.biblemap.put("b58_12_27", new hebsuperobject(58,12,27,"וזו עוד אחת שאמר משמיע חליפת הנרעשים אשר הם עשוים למען יעמד אשר איננו נרעש׃"));
hebsuperobject.biblemap.put("b58_12_28", new hebsuperobject(58,12,28,"לכן אנחנו המקבלים מלכות אשר לא תמוט נבאה נא בתודה ונעבד בה את האלהים לרצון לו בצניעות וביראה׃"));
hebsuperobject.biblemap.put("b58_12_29", new hebsuperobject(58,12,29,"כי אלהינו אש אכלה הוא׃"));
hebsuperobject.biblemap.put("b58_13_1", new hebsuperobject(58,13,1,"אהבת האחים תעמד׃"));
hebsuperobject.biblemap.put("b58_13_2", new hebsuperobject(58,13,2,"הכנסת ארחים אל תשכחו כי יש אשר הכניסו בה מלאכים ולא ידעו׃"));
hebsuperobject.biblemap.put("b58_13_3", new hebsuperobject(58,13,3,"זכרו את האסורים כאלו אתם אסורים עמהם ואת הנלחצים באשר גם אתם בבשר׃"));
hebsuperobject.biblemap.put("b58_13_4", new hebsuperobject(58,13,4,"האישות תיקר בכל וערש יצועכם אל יחלל את הזנים ואת המנאפים ידין אלהים׃"));
hebsuperobject.biblemap.put("b58_13_5", new hebsuperobject(58,13,5,"רחקו מאהבת כסף ושמחו בחלקכם כי הוא אמר לא ארפך ולא אעזבך׃"));
hebsuperobject.biblemap.put("b58_13_6", new hebsuperobject(58,13,6,"על כן נבטח ונאמר יהוה לי בעזרי לא אירא מה יעשה לי אדם׃"));
hebsuperobject.biblemap.put("b58_13_7", new hebsuperobject(58,13,7,"זכרו את מנהיגיכם אשר הגידו לכם את דבר האלהים בינו לאחרית דרכם ולכו באמונתם׃"));
hebsuperobject.biblemap.put("b58_13_8", new hebsuperobject(58,13,8,"ישוע המשיח גם תמול גם היום הוא הוא וגם לעולמים׃"));
hebsuperobject.biblemap.put("b58_13_9", new hebsuperobject(58,13,9,"אל תנועו בתורות שנות וזרות כי טוב לכונן לבנו בחסד ולא בעניני מאכל אשר לא הועילו למתהלכים בהם׃"));
hebsuperobject.biblemap.put("b58_13_10", new hebsuperobject(58,13,10,"יש לנו מזבח אשר אינם רשאים לאכל מעליו משרתי המשכן׃"));
hebsuperobject.biblemap.put("b58_13_11", new hebsuperobject(58,13,11,"כי הבהמות אשר הובא דמן בקדש לכפרת החטא על ידי הכהן הגדול גויתיהן נשרפו מחוץ למחנה׃"));
hebsuperobject.biblemap.put("b58_13_12", new hebsuperobject(58,13,12,"בעבור זאת גם ישוע למען קדש בדמו את העם ענה מחוץ לשער׃"));
hebsuperobject.biblemap.put("b58_13_13", new hebsuperobject(58,13,13,"לכן נצאה נא אליו אל מחוץ למחנה ונשא את חרפתו׃"));
hebsuperobject.biblemap.put("b58_13_14", new hebsuperobject(58,13,14,"כי פה אין לנו עיר עמדת כי את העתידה אנחנו מבקשים׃"));
hebsuperobject.biblemap.put("b58_13_15", new hebsuperobject(58,13,15,"לכן נקריב על ידו בכל עת זבח תודה לאלהים היא פרי שפתים המודות לשמו׃"));
hebsuperobject.biblemap.put("b58_13_16", new hebsuperobject(58,13,16,"ואל תשכחו לגמל חסד ולתת לאביונים כי זבחים כאלה יערבו לאלהים׃"));
hebsuperobject.biblemap.put("b58_13_17", new hebsuperobject(58,13,17,"שמעו אל מנהיגיכם והכנעו מפניהם כי שקדים הם על נפשתיכם כעתידים לתת חשבון למען יעשו זאת בשמחה ולא באנחה כי זאת לא להועיל לכם׃"));
hebsuperobject.biblemap.put("b58_13_18", new hebsuperobject(58,13,18,"התפללו בעדנו כי ידענו אשר שלמה מחשבתנו ונחפץ ללכת דרך ישרה בכל׃"));
hebsuperobject.biblemap.put("b58_13_19", new hebsuperobject(58,13,19,"ובחזקה אבקש מכם לעשות זאת למען אושב אליכם במהרה׃"));
hebsuperobject.biblemap.put("b58_13_20", new hebsuperobject(58,13,20,"ואלהי השלום אשר בדם ברית עולם העלה מן המתים את רעה הצאן הגדול את ישוע אדנינו׃"));
hebsuperobject.biblemap.put("b58_13_21", new hebsuperobject(58,13,21,"הוא ישלימכם בכל מעשה טוב לעשות רצונו בפעלו בכם את הרצוי לפניו ביד ישוע המשיח אשר לו הכבוד לעולמי עולמים אמן׃"));
hebsuperobject.biblemap.put("b58_13_22", new hebsuperobject(58,13,22,"ואבקש מכם אחי שאו נא דבר התוכחה כי כתבתי אליכם בקצרה׃"));
hebsuperobject.biblemap.put("b58_13_23", new hebsuperobject(58,13,23,"ודעו כי טימותיוס אחינו יצא מבית האסורים והיה אם יבא במהרה אראה אתו את פניכם׃"));
hebsuperobject.biblemap.put("b58_13_24", new hebsuperobject(58,13,24,"שאלו לשלום כל מנהיגיכם ולשלום כל הקדשים בני ארץ איטליא שאלים לשלומכם׃"));
hebsuperobject.biblemap.put("b58_13_25", new hebsuperobject(58,13,25,"החסד עם כלכם אמן׃"));

}

}