package heb.bible;

public class hebbible45 {

public hebbible45() {

putmapbible45();

}

private void putmapbible45() {

hebsuperobject.biblemap.put("b45_1_1", new hebsuperobject(45,1,1,"פולוס עבד ישוע המשיח מקרא להיות שליח ונבדל לבשורת אלהים׃"));
hebsuperobject.biblemap.put("b45_1_2", new hebsuperobject(45,1,2,"אשר הבטיחה מלפנים ביד נביאיו בכתבי הקדש׃"));
hebsuperobject.biblemap.put("b45_1_3", new hebsuperobject(45,1,3,"על דבר בנו הנולד מזרע דוד לפי הבשר׃"));
hebsuperobject.biblemap.put("b45_1_4", new hebsuperobject(45,1,4,"אשר הוכן לבן האלהים בגבורה לפי רוח הקדשה בתחיתו מבין המתים הוא ישוע המשיח אדנינו׃"));
hebsuperobject.biblemap.put("b45_1_5", new hebsuperobject(45,1,5,"אשר בידו קבלנו חן ושליחות להקים משמעת האמונה בכל הגוים למען שמו׃"));
hebsuperobject.biblemap.put("b45_1_6", new hebsuperobject(45,1,6,"אשר בתוכם הנכם גם אתם קרואי ישוע המשיח׃"));
hebsuperobject.biblemap.put("b45_1_7", new hebsuperobject(45,1,7,"לכל אשר ברומי ידידי אלהים וקרואים להיות קדושים חסד ושלום לכם מאת האלהים אבינו ואדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b45_1_8", new hebsuperobject(45,1,8,"בראשונה אודה לאלהי בישוע המשיח על כלכם אשר ספר אמונתכם בכל העולם׃"));
hebsuperobject.biblemap.put("b45_1_9", new hebsuperobject(45,1,9,"כי האלהים אשר אני עבד אתו ברוחי בבשורת בנו לעד לי כי תמיד אני מזכיר אתכם׃"));
hebsuperobject.biblemap.put("b45_1_10", new hebsuperobject(45,1,10,"בהעתירי בתפלותי בכל עת למען אשר רק הפעם אצליח ברצון אלהים לבוא אליכם׃"));
hebsuperobject.biblemap.put("b45_1_11", new hebsuperobject(45,1,11,"כי נכסף נכספתי לראותכם ולחלק לכם אי זו מתת רוח למען תתחזקי׃"));
hebsuperobject.biblemap.put("b45_1_12", new hebsuperobject(45,1,12,"והוא להתנחם עמכם זה בזה באמונה אשר לכם וגם לי׃"));
hebsuperobject.biblemap.put("b45_1_13", new hebsuperobject(45,1,13,"ולא אכחד מכם אחי כי פעמים רבות שמתי על לבי לבוא אליכם אך נמנע ממני עד הנה למען אמצא פרי גם בכם כמו ביתר הגוים׃"));
hebsuperobject.biblemap.put("b45_1_14", new hebsuperobject(45,1,14,"מחיב אנכי ליונים וגם ללעזים לחכמים וגם לפתאים׃"));
hebsuperobject.biblemap.put("b45_1_15", new hebsuperobject(45,1,15,"לכן נדבני לבי להשמיע את הבשורה גם אתכם אשר ברומי׃"));
hebsuperobject.biblemap.put("b45_1_16", new hebsuperobject(45,1,16,"כי אינני בוש מבשורת המשיח באשר גבורת אלהים היא לתשועת כל המאמין ליהודי בראשונה וכן גם ליוני׃"));
hebsuperobject.biblemap.put("b45_1_17", new hebsuperobject(45,1,17,"כי תגלה בה צדקת אלהים מאמונה אל אמונה ככתוב וצדיק באמונתו יחיה׃"));
hebsuperobject.biblemap.put("b45_1_18", new hebsuperobject(45,1,18,"כי נגלה חרון אלהים מן השמים על כל רשעת בני אדם ועולתם אשר יעצרו את האמת בעולה׃"));
hebsuperobject.biblemap.put("b45_1_19", new hebsuperobject(45,1,19,"יען אשר דעת האלהים גלויה בקרבם כי האלהים הודיעם אותה׃"));
hebsuperobject.biblemap.put("b45_1_20", new hebsuperobject(45,1,20,"כי מהותו הנעלמה היא כחו הנצחי ואלהותו מעת נברא העולם תודע במעשים ותראה לבלתי היות להם להתנצל׃"));
hebsuperobject.biblemap.put("b45_1_21", new hebsuperobject(45,1,21,"יען בדעתם את האלהים לא כבדהו כאלהים וגם לא הודו לו כי אם הלכו אחרי ההבל במועצותיהם ויחשך לבם הנבער׃"));
hebsuperobject.biblemap.put("b45_1_22", new hebsuperobject(45,1,22,"ובאמרם חכמים אנחנו היו לכסילים׃"));
hebsuperobject.biblemap.put("b45_1_23", new hebsuperobject(45,1,23,"וימירו את כבוד האלהים אשר איננו נפסד בדמות צלם אדם הנפסד צלם כל עוף והולך על ארבע ורמש האדמה׃"));
hebsuperobject.biblemap.put("b45_1_24", new hebsuperobject(45,1,24,"על כן גם נתנם האלהים לטמאה בתאות לבם לנבל גויותיהם איש את רעהו׃"));
hebsuperobject.biblemap.put("b45_1_25", new hebsuperobject(45,1,25,"אשר המירו אמת האלהים בכזב ויכבדו ויעבדו את הבריה תחת בראה המברך לעולמים אמן׃"));
hebsuperobject.biblemap.put("b45_1_26", new hebsuperobject(45,1,26,"בעבור זאת נתנם האלהים לתאות בושה כי נשיהם החליפו את התשמיש כדרכן בשלא כדרכן׃"));
hebsuperobject.biblemap.put("b45_1_27", new hebsuperobject(45,1,27,"וכן גם הזכרים עזבו את תשמיש האשה כדרכה ויחמו זה בזה בתשוקתם ויעשו תועבה זכר עם זכר ויקחו שכר משובתם הראוי להם בעצם גופם׃"));
hebsuperobject.biblemap.put("b45_1_28", new hebsuperobject(45,1,28,"וכאשר מאסו להשיג האלהים בדעת נתנם האלהים בידי דעה נמאסה לעשות את אשר לא יתכן׃"));
hebsuperobject.biblemap.put("b45_1_29", new hebsuperobject(45,1,29,"וירב בקרבם כל חמס זנות ורשע בצע ואון וימלאו קנאה ורצח ומריבה ומרמה ותהפכות׃"));
hebsuperobject.biblemap.put("b45_1_30", new hebsuperobject(45,1,30,"הלכי רכיל ומלשינים שנאי אלהים וגאים וזדים והוללים וחשבי און ואינם שמעים בקול אבותם׃"));
hebsuperobject.biblemap.put("b45_1_31", new hebsuperobject(45,1,31,"נבערים מדעת ובגדים אכזרים נטרי שנאה ולא רחמנים׃"));
hebsuperobject.biblemap.put("b45_1_32", new hebsuperobject(45,1,32,"יודעים המה את משפט אלהים כי עשי אלה בני מות הם ולא לבד שיעשו את אלה כי גם רצתה נפשם בעשיהם׃"));
hebsuperobject.biblemap.put("b45_2_1", new hebsuperobject(45,2,1,"לכן אין לך התנצלות אתה בן אדם הדן תהיה מי שתהיה כי במה שתדין את חברך תחיב את נפשך באשר אתה הדן תעשה כמעשהו׃"));
hebsuperobject.biblemap.put("b45_2_2", new hebsuperobject(45,2,2,"וידענו כי משפט אלהים כפי האמת על עשי אלה׃"));
hebsuperobject.biblemap.put("b45_2_3", new hebsuperobject(45,2,3,"ואתה בן אדם הדן את אשר פעלו כאלה ועשית כמעשיהם התחשב להמלט ממשפט האלהים׃"));
hebsuperobject.biblemap.put("b45_2_4", new hebsuperobject(45,2,4,"או התבוז לעתרת טובו ולחמלתו ולארך רוחו ולא תתבונן כי טובת האלהים תדריך אתך לתשובה׃"));
hebsuperobject.biblemap.put("b45_2_5", new hebsuperobject(45,2,5,"ובקשי לבבך הממאן לשוב תצבר לך עברה אל יום עברת האלהים ועת הגלות צדקת משפטו׃"));
hebsuperobject.biblemap.put("b45_2_6", new hebsuperobject(45,2,6,"אשר ישלם לאיש כמעשהו׃"));
hebsuperobject.biblemap.put("b45_2_7", new hebsuperobject(45,2,7,"למתמידים בעשות הטוב ומבקשים את הכבוד וההדר ואת אשר איננו עבד יתן את חיי העולמים׃"));
hebsuperobject.biblemap.put("b45_2_8", new hebsuperobject(45,2,8,"ועל בני המרי ואשר לא ישמעו לאמת כי אם לעולה שמעו חרון אף וחמה׃"));
hebsuperobject.biblemap.put("b45_2_9", new hebsuperobject(45,2,9,"צרה ומצוקה על כל נפש אדם עשה הרע על היהודי בראשונה וכן גם על היוני׃"));
hebsuperobject.biblemap.put("b45_2_10", new hebsuperobject(45,2,10,"וכבוד והדר ושלום לכל עשה הטוב ליהודי בראשונה וכן גם ליוני׃"));
hebsuperobject.biblemap.put("b45_2_11", new hebsuperobject(45,2,11,"כי אין משא פנים עם האלהים׃"));
hebsuperobject.biblemap.put("b45_2_12", new hebsuperobject(45,2,12,"כי כל אלה אשר חטאו בלי תורה גם בבלי תורה יאבדו ואשר חטאו בתורה גם על פי התורה ישפטו׃"));
hebsuperobject.biblemap.put("b45_2_13", new hebsuperobject(45,2,13,"כי לא שמעי התורה צדיקים לפני האלהים כי אם עשי התורה הם יצדקו׃"));
hebsuperobject.biblemap.put("b45_2_14", new hebsuperobject(45,2,14,"כי הגוים אשר אין להם תורה בעשותם כדברי התורה מאליהם גם באין תורה הם תורה לנפשם׃"));
hebsuperobject.biblemap.put("b45_2_15", new hebsuperobject(45,2,15,"בהראותם מעשה התורה כתוב על לבם ודעתם מעידה בהם ומחשבותם בקרבם מחיבות זאת את זאת או גם מזכות׃"));
hebsuperobject.biblemap.put("b45_2_16", new hebsuperobject(45,2,16,"ביום אשר ישפט האלהים את כל תעלמות בני האדם ביד ישוע המשיח כפי בשורתי׃"));
hebsuperobject.biblemap.put("b45_2_17", new hebsuperobject(45,2,17,"הן אתה נקרא בשם יהודי ונשענת על התורה והתהללת באלהים׃"));
hebsuperobject.biblemap.put("b45_2_18", new hebsuperobject(45,2,18,"וידעת הראוי ובהיותך מלמד בתורה תבין בין טוב לרע׃"));
hebsuperobject.biblemap.put("b45_2_19", new hebsuperobject(45,2,19,"ובטחת בנפשך להיות מוליך העורים ואור להלכים בחשך׃"));
hebsuperobject.biblemap.put("b45_2_20", new hebsuperobject(45,2,20,"מיסר לחסרי לב ומורה הפתאים ויש לך צורת המדע והאמת בתורה׃"));
hebsuperobject.biblemap.put("b45_2_21", new hebsuperobject(45,2,21,"ואתה אשר תורה אחרים את נפשך לא תורה אמרת לא תגנב והנך גנב׃"));
hebsuperobject.biblemap.put("b45_2_22", new hebsuperobject(45,2,22,"אמרת לא תנאף ואתה נאף תשקץ את האלילים ואתה גזל את הקדש׃"));
hebsuperobject.biblemap.put("b45_2_23", new hebsuperobject(45,2,23,"תתהלל בתורה ותנבל את האלהים בעברך את התורה׃"));
hebsuperobject.biblemap.put("b45_2_24", new hebsuperobject(45,2,24,"כי שם האלהים בגללכם מחלל בגוים כאשר כתוב׃"));
hebsuperobject.biblemap.put("b45_2_25", new hebsuperobject(45,2,25,"הן המילה מועילה אם תשמר את התורה אבל אם עבר אתה את התורה אז מילתך היתה לך לערלה׃"));
hebsuperobject.biblemap.put("b45_2_26", new hebsuperobject(45,2,26,"לכן אם ישמר הערל את משפטי התורה הלא תחשב לו ערלתו למילה׃"));
hebsuperobject.biblemap.put("b45_2_27", new hebsuperobject(45,2,27,"והערל מלדה המקים את התורה הלא הוא ידין אתך אשר יש לך הכתב והמילה ועברת את התורה׃"));
hebsuperobject.biblemap.put("b45_2_28", new hebsuperobject(45,2,28,"כי לא הנראה מחוץ הוא היהודי ולא הנראה מחוץ בבשר היא המילה׃"));
hebsuperobject.biblemap.put("b45_2_29", new hebsuperobject(45,2,29,"כי אם אשר בפנים הוא יהודי ומילה היא אשר בלב כפי הרוח ולא כפי הכתב אשר לא מבני אדם תהלתו כי אם מאת האלהים׃"));
hebsuperobject.biblemap.put("b45_3_1", new hebsuperobject(45,3,1,"ועתה מה הוא יתרון היהודי ומה היא תועלת המילה׃"));
hebsuperobject.biblemap.put("b45_3_2", new hebsuperobject(45,3,2,"הרבה מכל פנים בראשון כי הפקדו בידם דברי אלהים׃"));
hebsuperobject.biblemap.put("b45_3_3", new hebsuperobject(45,3,3,"כי מה הוא אם מקצתם לא האמינו היבטל חסרון אמונתם את אמונת אלהים׃"));
hebsuperobject.biblemap.put("b45_3_4", new hebsuperobject(45,3,4,"חלילה אבל יהי האל הוא הנאמן וכל האדם כזב ככתוב למען תצדק בדברך תזכה בשפטך׃"));
hebsuperobject.biblemap.put("b45_3_5", new hebsuperobject(45,3,5,"ואם עולתנו תרומם את צדקת האלהים מה נאמר הכי יש עול באלהים המשלח חרון אפו לפי דרך בני אדם אנכי מדבר׃"));
hebsuperobject.biblemap.put("b45_3_6", new hebsuperobject(45,3,6,"חלילה שאם כן איך ישפט האלהים את העולם׃"));
hebsuperobject.biblemap.put("b45_3_7", new hebsuperobject(45,3,7,"כי אם על ידי כזבי תרבה ותפרץ אמת אלהים לתהלתו למה זה אני אשפט עוד כחוטא׃"));
hebsuperobject.biblemap.put("b45_3_8", new hebsuperobject(45,3,8,"ולא נעשה כדבר מחרפינו ומקצת מוציאי דבה עלינו לאמר הנה אמרים נעשה הרע למען יצא הטוב אשר דינם יבא עליהם בצדק׃"));
hebsuperobject.biblemap.put("b45_3_9", new hebsuperobject(45,3,9,"ועתה מה הוא היש לנו מעלה יתרה לא במאומה כבר הוכחנו כי גם היהודים גם היונים כלם הם תחת החטא׃"));
hebsuperobject.biblemap.put("b45_3_10", new hebsuperobject(45,3,10,"ככתוב אין צדיק אין גם אחד׃"));
hebsuperobject.biblemap.put("b45_3_11", new hebsuperobject(45,3,11,"אין משכיל אין דרש את אלהים׃"));
hebsuperobject.biblemap.put("b45_3_12", new hebsuperobject(45,3,12,"הכל סר יחדו נאלחו אין עשה טוב אין גם אחד׃"));
hebsuperobject.biblemap.put("b45_3_13", new hebsuperobject(45,3,13,"קבר פתוח גרונם לשונם יחליקון חמת עכשוב תחת שפתימו׃"));
hebsuperobject.biblemap.put("b45_3_14", new hebsuperobject(45,3,14,"אשר אלה פיהם מלא ומררות׃"));
hebsuperobject.biblemap.put("b45_3_15", new hebsuperobject(45,3,15,"רגליהם ימהרו לשפך דם׃"));
hebsuperobject.biblemap.put("b45_3_16", new hebsuperobject(45,3,16,"שד ושבר במסלותם׃"));
hebsuperobject.biblemap.put("b45_3_17", new hebsuperobject(45,3,17,"ודרך שלום לא ידעו׃"));
hebsuperobject.biblemap.put("b45_3_18", new hebsuperobject(45,3,18,"אין פחד אלהים לנגד עיניהם׃"));
hebsuperobject.biblemap.put("b45_3_19", new hebsuperobject(45,3,19,"ואנחנו ידענו כי כל מה שאמרה התורה מדברת אל אלה אשר תחת התורה למען יסכר כל פה והיה כל העולם מחיב לפני אלהים׃"));
hebsuperobject.biblemap.put("b45_3_20", new hebsuperobject(45,3,20,"יען אשר ממעשי התורה לא יצדק לפניו כל בשר כי על ידי התורה דעת החטא׃"));
hebsuperobject.biblemap.put("b45_3_21", new hebsuperobject(45,3,21,"ועתה בבלי תורה צדקת אלהים לאור יצאה אשר העידו עליה התורה והנביאים׃"));
hebsuperobject.biblemap.put("b45_3_22", new hebsuperobject(45,3,22,"והיא צדקת אלהים באמונת ישוע המשיח אל כל ועל כל אשר האמינו בו כי אין הבדל׃"));
hebsuperobject.biblemap.put("b45_3_23", new hebsuperobject(45,3,23,"כי כלם חטאו וחסרי כבוד אלהים המה׃"));
hebsuperobject.biblemap.put("b45_3_24", new hebsuperobject(45,3,24,"ונצדקו חנם בחסדו על ידי הפדות אשר היתה במשיח ישוע׃"));
hebsuperobject.biblemap.put("b45_3_25", new hebsuperobject(45,3,25,"אשר שמו האלהים לפנינו לכפרת על ידי האמונה בדמו להראות את צדקתו אחרי אשר העביר את החטאים שנעשו לפנים בעת חמלת אלהים׃"));
hebsuperobject.biblemap.put("b45_3_26", new hebsuperobject(45,3,26,"להראות את צדקתו בעת הזאת להיותו צדיק ומצדיק את בן אמונת ישוע׃"));
hebsuperobject.biblemap.put("b45_3_27", new hebsuperobject(45,3,27,"ועתה איה ההתהללות הלא נשבתה ועל ידי תורת מה העל ידי תורת המעשים לא כי על ידי תורת האמונה׃"));
hebsuperobject.biblemap.put("b45_3_28", new hebsuperobject(45,3,28,"לכן נחשב כי באמונה יצדק האדם בבלי מעשי תורה׃"));
hebsuperobject.biblemap.put("b45_3_29", new hebsuperobject(45,3,29,"או האלהים רק אלהי היהודים הלא גם אלהי הגוים אכן גם אלהי הגוים הוא׃"));
hebsuperobject.biblemap.put("b45_3_30", new hebsuperobject(45,3,30,"כי אחד האלהים המצדיק את המולים מתוך האמונה ואת הערלים על ידי האמונה׃"));
hebsuperobject.biblemap.put("b45_3_31", new hebsuperobject(45,3,31,"ועתה המבטלים אנחנו את התורה על ידי האמונה חלילה אך מקימים אנחנו את התורה׃"));
hebsuperobject.biblemap.put("b45_4_1", new hebsuperobject(45,4,1,"ועתה מה נאמר על אברהם אבינו מה זה השיג לפי הבשר׃"));
hebsuperobject.biblemap.put("b45_4_2", new hebsuperobject(45,4,2,"כי אם נצדק אברהם מתוך המעשים לו התהלה אך לא לפני האלהים׃"));
hebsuperobject.biblemap.put("b45_4_3", new hebsuperobject(45,4,3,"כי הכתוב מה הוא אמר והאמן אברהם ביהוה ויחשבה לו צדקה׃"));
hebsuperobject.biblemap.put("b45_4_4", new hebsuperobject(45,4,4,"הנה הפעל לא יחשב לו שכרו על פי החסד כי אם על פי החוב׃"));
hebsuperobject.biblemap.put("b45_4_5", new hebsuperobject(45,4,5,"אבל לאשר איננו פעל כי אם מאמין במצדיק את הרשע אמונתו תחשב לו לצדקה׃"));
hebsuperobject.biblemap.put("b45_4_6", new hebsuperobject(45,4,6,"כאשר גם דוד מאשר את האדם אשר האלהים יחשב לו צדקה בלא מעשים באמרו׃"));
hebsuperobject.biblemap.put("b45_4_7", new hebsuperobject(45,4,7,"אשרי נשוי פשע כסוי חטאה׃"));
hebsuperobject.biblemap.put("b45_4_8", new hebsuperobject(45,4,8,"אשרי אדם לא יחשב יהוה לו עון׃"));
hebsuperobject.biblemap.put("b45_4_9", new hebsuperobject(45,4,9,"ועתה האשור הזה העל המילה הוא אם גם על הערלה הלא אמרנו כי לאברהם נחשבה אמונתו לצדקה׃"));
hebsuperobject.biblemap.put("b45_4_10", new hebsuperobject(45,4,10,"ואין נחשבה לו אם בהיותו מהול או בעודנו ערל הן לא בהיותו מהול כי אם בערלתו׃"));
hebsuperobject.biblemap.put("b45_4_11", new hebsuperobject(45,4,11,"ואות המילה קבל לחותם צדקת האמונה אשר היתה לו בערלתו להיות לאב לכל המאמינים והם ערלים למען אף להם תחשב הצדקה׃"));
hebsuperobject.biblemap.put("b45_4_12", new hebsuperobject(45,4,12,"ולהיות לאב גם למולים אך לא לאשר הם נמולים לבד כי אם גם הלכים בעקבות האמונה שהיתה לו לאברהם בעודנו בערלתו׃"));
hebsuperobject.biblemap.put("b45_4_13", new hebsuperobject(45,4,13,"כי לא על ידי תורה באה ההבטחה לאברהם ולזרעו להיותו ירש העולם כי אם על ידי צדקת האמונה׃"));
hebsuperobject.biblemap.put("b45_4_14", new hebsuperobject(45,4,14,"כי אלו לבני התורה הירשה האמונה לריק תהיה וההבטחה בטלה׃"));
hebsuperobject.biblemap.put("b45_4_15", new hebsuperobject(45,4,15,"כי התורה מביאה קצף כי באשר אין תורה גם אין שם עברה׃"));
hebsuperobject.biblemap.put("b45_4_16", new hebsuperobject(45,4,16,"על כן מתוך אמונה למען לפי חסד למען תחיה ההבטחה קימת לכל זרעו לא לבני התורה לבדם כי גם לבני אמונת אברהם אשר הוא אב לכלנו׃"));
hebsuperobject.biblemap.put("b45_4_17", new hebsuperobject(45,4,17,"ככתוב כי אב המון גוים נתתיך והוא האמין בהביט אל אל המחיה את המתים והקורא את אשר לא היה כמו הוה׃"));
hebsuperobject.biblemap.put("b45_4_18", new hebsuperobject(45,4,18,"באשר אין תקוה קוה ויאמן למען אשר יהיה לאב המון גוים כמו שנאמר כה יהיה זרעך׃"));
hebsuperobject.biblemap.put("b45_4_19", new hebsuperobject(45,4,19,"ולא רפתה אמונתו ולא התבונן אל גופו שכבר נפוג בהיותו כבן מאת שנה ואל בלות רחם שרה׃"));
hebsuperobject.biblemap.put("b45_4_20", new hebsuperobject(45,4,20,"ולא חלק לבו בהבטחת האלהים כחסר האמונה כי אם התחזק באמונתו ויתן כבוד לאלהים׃"));
hebsuperobject.biblemap.put("b45_4_21", new hebsuperobject(45,4,21,"וידע בלבב שלם כי את אשר הבטיח גם יכל לעשותו׃"));
hebsuperobject.biblemap.put("b45_4_22", new hebsuperobject(45,4,22,"על כן גם נחשבה לו לצדקה׃"));
hebsuperobject.biblemap.put("b45_4_23", new hebsuperobject(45,4,23,"ולא לבד למענו כתובה זאת שנחשבה לו׃"));
hebsuperobject.biblemap.put("b45_4_24", new hebsuperobject(45,4,24,"כי אם גם למעננו אשר עתידה להחשב לנו המאמינים במי שהעיר את ישוע אדנינו מן המתים׃"));
hebsuperobject.biblemap.put("b45_4_25", new hebsuperobject(45,4,25,"אשר נמסר בעבור פשעינו ונעור לבעבור צדקנו׃"));
hebsuperobject.biblemap.put("b45_5_1", new hebsuperobject(45,5,1,"לכן אחרי נצדקנו באמונה שלום לנו עם האלהים באדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b45_5_2", new hebsuperobject(45,5,2,"אשר בידו מצאנו באמונה מבוא אל החסד הזה אשר אנחנו עמדים בו ונתהלל בתקות כבוד האלהים׃"));
hebsuperobject.biblemap.put("b45_5_3", new hebsuperobject(45,5,3,"ולא זאת בלבד כי אף נתהלל בצרות יען אשר ידענו כי הצרה מביאה לידי סבלנות׃"));
hebsuperobject.biblemap.put("b45_5_4", new hebsuperobject(45,5,4,"והסבלנות לידי עמידה בנסיון והעמידה בנסיון לידי תקוה׃"));
hebsuperobject.biblemap.put("b45_5_5", new hebsuperobject(45,5,5,"והתקוה היא לא תביש כי הוצק בלבבנו אהבת אל על ידי רוח הקדש הנתן לנו׃"));
hebsuperobject.biblemap.put("b45_5_6", new hebsuperobject(45,5,6,"כי המשיח בעודנו חלשים מת בעתו בעד הרעשים׃"));
hebsuperobject.biblemap.put("b45_5_7", new hebsuperobject(45,5,7,"הן בעד הצדיק יקשה לאיש למות אכן למות בעד הטוב אולי ישאהו לבו׃"));
hebsuperobject.biblemap.put("b45_5_8", new hebsuperobject(45,5,8,"אבל בזאת הודיע האלהים את אהבתו אלינו כי המשיח מת בעדנו בהיותנו עוד חטאים׃"));
hebsuperobject.biblemap.put("b45_5_9", new hebsuperobject(45,5,9,"ועתה אשר נצדקנו בדמו מה מאד נושע בו מן הקצף׃"));
hebsuperobject.biblemap.put("b45_5_10", new hebsuperobject(45,5,10,"כי אם נרצינו לאלהים במות בנו בהיותנו איבים אף כי נושע עתה בחייו אחרי אשר נרצינו׃"));
hebsuperobject.biblemap.put("b45_5_11", new hebsuperobject(45,5,11,"ולא זאת בלבד כי גם מתהללים אנחנו באלהים על יד אדנינו ישוע המשיח אשר בו עתה קבלנו את הרצוי׃"));
hebsuperobject.biblemap.put("b45_5_12", new hebsuperobject(45,5,12,"לכן כאשר על ידי אדם אחד בא החטא לעולם והמות בעקב החטא וכן עבר המות על כל בני אדם מפני אשר כלם חטאו׃"));
hebsuperobject.biblemap.put("b45_5_13", new hebsuperobject(45,5,13,"כי עד זמן התורה היה החטא בעולם אך לא יחשב חטא באין תורה׃"));
hebsuperobject.biblemap.put("b45_5_14", new hebsuperobject(45,5,14,"אולם המות מלך מאדם עד משה גם על אלה אשר לא חטאו בדמיון עברת אדם הראשון אשר הוא דמות העתיד לבוא׃"));
hebsuperobject.biblemap.put("b45_5_15", new hebsuperobject(45,5,15,"אך לא כדבר הפשע דבר המתנה כי אם בפשע האחד מתו הרבים אף כי חסד אלהים ומתנתו עדפו ערוף לרבים בחסד האדם האחד ישוע המשיח׃"));
hebsuperobject.biblemap.put("b45_5_16", new hebsuperobject(45,5,16,"ולא כמו על ידי חטא אחד כן המתנה כי המשפט יצא מאחד לחיב אבל מתנת החסד היא לזכות מפשעים רבים׃"));
hebsuperobject.biblemap.put("b45_5_17", new hebsuperobject(45,5,17,"כי אם בפשע האחד מלך המות על ידי האחד אף כי מקבלי עדף החסד ומתנת הצדקה ימלכו בחיים על ידי האחד ישוע המשיח׃"));
hebsuperobject.biblemap.put("b45_5_18", new hebsuperobject(45,5,18,"לכן כאשר בפשע אחד נאשמו כל בני אדם ככה גם על ידי זכות אחת יזכו כל בני אדם לחיים׃"));
hebsuperobject.biblemap.put("b45_5_19", new hebsuperobject(45,5,19,"כי כאשר במרי האדם האחד היו הרבים לחטאים ככה גם על ידי משמעת האחד יהיו הרבים לצדיקים׃"));
hebsuperobject.biblemap.put("b45_5_20", new hebsuperobject(45,5,20,"אבל התורה נכנסה למען ירבה הפשע ובאשר רבה החטא עדף ממנו החסד׃"));
hebsuperobject.biblemap.put("b45_5_21", new hebsuperobject(45,5,21,"למען כאשר מלך החטא במות ככה ימלך גם החסד על ידי הצדקה לחיי עולם בישוע המשיח אדנינו׃"));
hebsuperobject.biblemap.put("b45_6_1", new hebsuperobject(45,6,1,"אם כן מה נאמר הנעמד בחטא למען ירבה החסד׃"));
hebsuperobject.biblemap.put("b45_6_2", new hebsuperobject(45,6,2,"חלילה לנו כי מתנו לחטא ואיך נוסיף לחיות בו׃"));
hebsuperobject.biblemap.put("b45_6_3", new hebsuperobject(45,6,3,"או האינכם ידעים כי כלנו הנטבלים למשיח ישוע למותו נטבלנו׃"));
hebsuperobject.biblemap.put("b45_6_4", new hebsuperobject(45,6,4,"לכן נקברנו אתו בטבילה למות למען כאשר נעור המשיח מן המתים בכבוד האב כן נתהלך גם אנחנו בחיים מחדשים׃"));
hebsuperobject.biblemap.put("b45_6_5", new hebsuperobject(45,6,5,"כי אם נדבקנו בדמיון מותו אכן גם נהיה דבוקים לתחיתו׃"));
hebsuperobject.biblemap.put("b45_6_6", new hebsuperobject(45,6,6,"באשר ידעים אנחנו כי נצלב אתו האדם הישן אשר בנו למען תבטל גוית החטא לבלתי היותנו עוד עבדים לחטא׃"));
hebsuperobject.biblemap.put("b45_6_7", new hebsuperobject(45,6,7,"כי אשר מת הוא נקה מן החטא׃"));
hebsuperobject.biblemap.put("b45_6_8", new hebsuperobject(45,6,8,"והנה אם מתנו עם המשיח נאמין כי גם נחיה עמו׃"));
hebsuperobject.biblemap.put("b45_6_9", new hebsuperobject(45,6,9,"באשר ידענו כי המשיח אחרי אשר נעור מן המתים לא ימות עוד והמות לא ישלט בו עוד׃"));
hebsuperobject.biblemap.put("b45_6_10", new hebsuperobject(45,6,10,"כי אשר מת מת לחטא פעם אחת ואשר חי חי הוא לאלהים׃"));
hebsuperobject.biblemap.put("b45_6_11", new hebsuperobject(45,6,11,"וכן גם אתם חשבו אתכם מתים לחטא וחיים לאלהים במשיח ישוע אדנינו׃"));
hebsuperobject.biblemap.put("b45_6_12", new hebsuperobject(45,6,12,"אם כן אפוא אל תמלך החטאת בגופכם אשר ימות לנטות אחריה בתאותיו׃"));
hebsuperobject.biblemap.put("b45_6_13", new hebsuperobject(45,6,13,"]31-21[ גם אל תכינו את אבריכם להיות כלי עול לחטא אך תכינו את נפשכם לאלהים כחיים מעם המתים ואבריכם כלי צדקה לאלהים כי החטא לא יוכל למשל עוד בכם יען אינכם תחת יד התורה כי אם תחת יד החסד׃"));
hebsuperobject.biblemap.put("b45_6_14", new hebsuperobject(45,6,14,"]31-21[׃"));
hebsuperobject.biblemap.put("b45_6_15", new hebsuperobject(45,6,15,"ועתה מה הנחטא יען איננו תחת יד התורה כי אם תחת יד החסד חלילה׃"));
hebsuperobject.biblemap.put("b45_6_16", new hebsuperobject(45,6,16,"הלא ידעתם כי לאשר תתנו את נפשכם להיות עבדיו לסור למשמעתו הן עבדים אתם לאשר תשמעו לו אם לחטא אלי מות אם למשמעת אלי צדקה׃"));
hebsuperobject.biblemap.put("b45_6_17", new hebsuperobject(45,6,17,"אבל תודת לאלהים כי הייתם עבדי החטא ואחר שמעתם בכל לבבכם אל תכונת הלקח אשר נמסרתם לו׃"));
hebsuperobject.biblemap.put("b45_6_18", new hebsuperobject(45,6,18,"שחררתם מידי החטא לכן השתעבדתם לצדקה׃"));
hebsuperobject.biblemap.put("b45_6_19", new hebsuperobject(45,6,19,"כדרך בני אדם אני מדבר מפני רפיון בשרכם כי כאשר לפנים הכינותם את אבריכם לעבודת החטאה והרשע להרשיע כן עתה הכינו את אבריכם לעבודת הצדקה להתקדש׃"));
hebsuperobject.biblemap.put("b45_6_20", new hebsuperobject(45,6,20,"כי בעת היותכם עבדי החטא חפשים הייתם מן הצדקה׃"));
hebsuperobject.biblemap.put("b45_6_21", new hebsuperobject(45,6,21,"ומה אפוא הפרי שהיה לכם אז מן המעשים אשר עתה תבשו מהם כי אחריתם המות׃"));
hebsuperobject.biblemap.put("b45_6_22", new hebsuperobject(45,6,22,"אכן עתה בהיותכם משחררים מידי החטא ומשעבדים לאלהים יש לכם פריכם לקדשה ואחריתו חיי עולם׃"));
hebsuperobject.biblemap.put("b45_6_23", new hebsuperobject(45,6,23,"כי שכר החטא הוא המות ומתנת חסד אלהים היא חיי העולם במשיח ישוע אדנינו׃"));
hebsuperobject.biblemap.put("b45_7_1", new hebsuperobject(45,7,1,"או הלא ידעתם אחי ולידעי התורה אנכי מדבר כי התורה תשלט על האדם כל ימי חייו׃"));
hebsuperobject.biblemap.put("b45_7_2", new hebsuperobject(45,7,2,"כי אשה בעלת בעל קשורה היא באישה כפי התורה בחייו ובמות הבעל פטורה היא מתורת בעלה׃"));
hebsuperobject.biblemap.put("b45_7_3", new hebsuperobject(45,7,3,"והנה אם תחיה לאיש אחר בחיי בעלה נאפת יקרא לה אבל אחרי מות בעלה פטורה היא מן התורה ואיננה נאפת בהיותה לאיש אחר׃"));
hebsuperobject.biblemap.put("b45_7_4", new hebsuperobject(45,7,4,"לכן אחי הומתם גם אתם לתורה בגוית המשיח להיותכם לאחר לאשר נעור מן המתים למען נעשה פרי לאלהים׃"));
hebsuperobject.biblemap.put("b45_7_5", new hebsuperobject(45,7,5,"כי בעת היותנו בבשר תשוקות החטא אשר התעוררו על ידי התורה היו פעלות באברינו לעשות פרי למות׃"));
hebsuperobject.biblemap.put("b45_7_6", new hebsuperobject(45,7,6,"אבל עתה נפטרנו מן התורה כי מתנו לאשר היינו אסורים בו למען נעבד מעתה לפי התחדשות הרוח ולא לפי ישן הכתב׃"));
hebsuperobject.biblemap.put("b45_7_7", new hebsuperobject(45,7,7,"אם כן מה נאמר הכי התורה חטא היא חלילה אלא לא ידעתי את החטא בלתי על ידי התורה כי לא הייתי יודע החמוד לולי אמרה התורה לא תחמד׃"));
hebsuperobject.biblemap.put("b45_7_8", new hebsuperobject(45,7,8,"וימצא החטא סבה לו במצוה לעורר בקרבי כל חמוד כי מבלעדי התורה החטא מת הוא׃"));
hebsuperobject.biblemap.put("b45_7_9", new hebsuperobject(45,7,9,"ואני חייתי מלפנים בלא תורה וכאשר באה המצוה ויחי החטא׃"));
hebsuperobject.biblemap.put("b45_7_10", new hebsuperobject(45,7,10,"ואני מתי והמצוה אשר נתנה לחיים היא נמצאה לי למות׃"));
hebsuperobject.biblemap.put("b45_7_11", new hebsuperobject(45,7,11,"כי מצא החטא סבה במצוה להתעות אתי ויהרגני על ידה׃"));
hebsuperobject.biblemap.put("b45_7_12", new hebsuperobject(45,7,12,"ובכן התורה היא קדושה והמצוה קדושה וישרה וטובה׃"));
hebsuperobject.biblemap.put("b45_7_13", new hebsuperobject(45,7,13,"הכי הטובה היתה לי למות חלילה אלא החטא למען יראה כי חטא הוא הביא לי על ידי הטובה את המות למען אשר יהיה החטא לחטאה יתרה על ידי המצוה׃"));
hebsuperobject.biblemap.put("b45_7_14", new hebsuperobject(45,7,14,"כי ידעים אנחנו שהתורה היא רוחנית ואני של בשר ונמכר תחת יד החטא׃"));
hebsuperobject.biblemap.put("b45_7_15", new hebsuperobject(45,7,15,"כי את אשר אני פעל לא ידעתי כי אינני עשה את אשר אני רצה בו כי אם אשר שנאתי אתו אני עשה׃"));
hebsuperobject.biblemap.put("b45_7_16", new hebsuperobject(45,7,16,"ובעשותי את אשר לא רציתי בו הנני מודה בזאת כי התורה טובה היא׃"));
hebsuperobject.biblemap.put("b45_7_17", new hebsuperobject(45,7,17,"ועתה לא אנכי עוד הפעל אתו כי אם החטא הישב בי׃"));
hebsuperobject.biblemap.put("b45_7_18", new hebsuperobject(45,7,18,"כי ידעתי אשר בי בבשרי לא ישב טוב הן הרצון יש עמדי אבל עשות הטוב לא מצאתי׃"));
hebsuperobject.biblemap.put("b45_7_19", new hebsuperobject(45,7,19,"כי אינני עשה הטוב אשר אני רצה בו כי אם הרע אשר אינני רצה בו אותו אני עשה׃"));
hebsuperobject.biblemap.put("b45_7_20", new hebsuperobject(45,7,20,"ואם את אשר לא רציתי בו אני עשה לא עוד אנכי הפעל כי החטא הישב בקרבי׃"));
hebsuperobject.biblemap.put("b45_7_21", new hebsuperobject(45,7,21,"ובכן מצא אני בי זה החק אנכי רצה לעשות הטוב ודבק בי הרע׃"));
hebsuperobject.biblemap.put("b45_7_22", new hebsuperobject(45,7,22,"כי לפי האדם הפנימי חפצתי בתורת אלהים׃"));
hebsuperobject.biblemap.put("b45_7_23", new hebsuperobject(45,7,23,"אך ראה אני באברי חק אחר הלחם לחק שכלי ויוליכני שבי לתורת החטא אשר באברי׃"));
hebsuperobject.biblemap.put("b45_7_24", new hebsuperobject(45,7,24,"אוי לי האדם העני מי יצילני מגוף המות הזה׃"));
hebsuperobject.biblemap.put("b45_7_25", new hebsuperobject(45,7,25,"אודה לאלהים בישוע המשיח אדנינו׃ [ (Romans 7:26) לכן בשכלי הנני עבד לתורת האלהים ובבשרי אני עבד לתורת החטא׃ ]"));
hebsuperobject.biblemap.put("b45_8_1", new hebsuperobject(45,8,1,"על כן אין אשמה באלה אשר הם במשיח ישוע המתהלכים בלא כבשר כי אם לפי הרוח׃"));
hebsuperobject.biblemap.put("b45_8_2", new hebsuperobject(45,8,2,"כי תורת רוח החיים במשיח ישוע שחררה אתי מתורת החטא והמות׃"));
hebsuperobject.biblemap.put("b45_8_3", new hebsuperobject(45,8,3,"כי מה שלא יכלה התורה לעשות הנחלשה על יד הבשר עשה האלהים בשלחו את בנו בתואר בשר החטא ובעד החטא וירשיע את החטא בבשר׃"));
hebsuperobject.biblemap.put("b45_8_4", new hebsuperobject(45,8,4,"למען תמלא חקת התורה בנו המתהלכים בלא כבשר כי אם לפי הרוח׃"));
hebsuperobject.biblemap.put("b45_8_5", new hebsuperobject(45,8,5,"כי אשר המה לבשר בעניני הבשר יחשבו ואשר לרוח בעניני הרוח יחשבו׃"));
hebsuperobject.biblemap.put("b45_8_6", new hebsuperobject(45,8,6,"כי מחשבת הבשר היא המות ומחשבת הרוח היא החיים והשלום׃"));
hebsuperobject.biblemap.put("b45_8_7", new hebsuperobject(45,8,7,"יען מחשבת הבשר רק שנאת אלהים היא באשר לא תשתעבד לתורת האלהים ואף איננה יכולה׃"));
hebsuperobject.biblemap.put("b45_8_8", new hebsuperobject(45,8,8,"ואשר המה בבשר לא יוכלו להיות רצוים לאלהים׃"));
hebsuperobject.biblemap.put("b45_8_9", new hebsuperobject(45,8,9,"ואתם אינכם בבשר כי אם ברוח אם אמנם רוח האלהים שכן בקרבכם כי מי שאין בו רוח המשיח איננו שלו׃"));
hebsuperobject.biblemap.put("b45_8_10", new hebsuperobject(45,8,10,"ואם המשיח בקרבכם אז הגוף מת הוא בדבר החטא והרוח חיים הוא בדבר הצדקה׃"));
hebsuperobject.biblemap.put("b45_8_11", new hebsuperobject(45,8,11,"ואם ישכן בקרבכם רוח המעיר את ישוע מן המתים הוא אשר העיר את המשיח מן המתים גם את גויותיכם המתות יחיה על ידי רוחו השכן בקרבכם׃"));
hebsuperobject.biblemap.put("b45_8_12", new hebsuperobject(45,8,12,"לכן אחי חיבים אנחנו לא לבשר לחיות לפי הבשר׃"));
hebsuperobject.biblemap.put("b45_8_13", new hebsuperobject(45,8,13,"כי אם תחיו לפי הבשר מות תמתון ואם על ידי הרוח תמותתו את מעללי הבשר חיה תחיו׃"));
hebsuperobject.biblemap.put("b45_8_14", new hebsuperobject(45,8,14,"כי כל אשר רוח אלהים ינהגם בני אלהים המה׃"));
hebsuperobject.biblemap.put("b45_8_15", new hebsuperobject(45,8,15,"כי לא קבלתם רוח עבדות לשוב לירא כי אם קבלתם רוח משפט בנים אשר בו קראים אנחנו אבא אבינו׃"));
hebsuperobject.biblemap.put("b45_8_16", new hebsuperobject(45,8,16,"והרוח ההוא מעיד ברוחנו כי בני אלהים אנחנו׃"));
hebsuperobject.biblemap.put("b45_8_17", new hebsuperobject(45,8,17,"ואם בנים אנחנו גם ירשים נהיה ירשי אלהים וחברי המשיח בירשה אם אמנם נתענה אתו למען גם אתו נכבד׃"));
hebsuperobject.biblemap.put("b45_8_18", new hebsuperobject(45,8,18,"כי אחשב אשר ענויי הזמן הזה אינם שקולים כנגד הכבוד העתיד להגלות עלינו׃"));
hebsuperobject.biblemap.put("b45_8_19", new hebsuperobject(45,8,19,"כי הבריאה תערג ועיניה תלויות להתגלות בני אלהים׃"));
hebsuperobject.biblemap.put("b45_8_20", new hebsuperobject(45,8,20,"כי נכבשה הבריאה להבל לא מרצונה כי אם למען הכבש אתה אלי תקוה׃"));
hebsuperobject.biblemap.put("b45_8_21", new hebsuperobject(45,8,21,"אשר הבריאה גם היא תשחרר מעבדות הכליון אל חרות כבוד בני האלהים׃"));
hebsuperobject.biblemap.put("b45_8_22", new hebsuperobject(45,8,22,"כי ידענו אשר הבריאה כלה יחד תאנח ותחיל עד הנה׃"));
hebsuperobject.biblemap.put("b45_8_23", new hebsuperobject(45,8,23,"ולא זאת בלבד כי גם אנחנו אף אם יש לנו בכורי הרוח נאנח בנפשנו ונחכה למשפט הבנים פדות גויתנו׃"));
hebsuperobject.biblemap.put("b45_8_24", new hebsuperobject(45,8,24,"כי נושענו בתקוה אך התקוה הנראה לעינים איננה תקוה כי איך ייחל איש לדבר אשר הוא ראה׃"));
hebsuperobject.biblemap.put("b45_8_25", new hebsuperobject(45,8,25,"אבל אם נקוה לאשר לא ראינהו נחכה לו בסבלנות׃"));
hebsuperobject.biblemap.put("b45_8_26", new hebsuperobject(45,8,26,"וכן גם הרוח תמך אתנו בחלשותינו כי לא ידענו מה להתפלל כראוי אכן הרוח הוא מפגיע בעדנו באנחות עמקות מדבר׃"));
hebsuperobject.biblemap.put("b45_8_27", new hebsuperobject(45,8,27,"והחקר לבבות יודע את אשר יחשב הרוח כי כרצון האלהים יפגיע בעד הקדושים׃"));
hebsuperobject.biblemap.put("b45_8_28", new hebsuperobject(45,8,28,"והנה ידענו כי לאהבי אלהים הקרואים בעצתו הכל יעזר לטוב להם׃"));
hebsuperobject.biblemap.put("b45_8_29", new hebsuperobject(45,8,29,"כי את אשר ידעם מקדם אתם גם יעד מקדם להיות דומים לדמות בנו למען יהיה הבכור בתוך אחים רבים׃"));
hebsuperobject.biblemap.put("b45_8_30", new hebsuperobject(45,8,30,"ואת אשר יעדם מקדם אתם גם קרא ואת אשר קראם אתם גם הצדיק ואת אשר הצדיקם אתם גם פאר׃"));
hebsuperobject.biblemap.put("b45_8_31", new hebsuperobject(45,8,31,"ועתה מה נאמר על זאת אם האלהים לנו מי יריב אתנו׃"));
hebsuperobject.biblemap.put("b45_8_32", new hebsuperobject(45,8,32,"אשר על בנו יחידו לא חס כי אם נתנו בעד כלנו הלא גם יתן לנו עמו את הכל׃"));
hebsuperobject.biblemap.put("b45_8_33", new hebsuperobject(45,8,33,"מי יענה בבחירי אלהים הן אלהים הוא המצדיק׃"));
hebsuperobject.biblemap.put("b45_8_34", new hebsuperobject(45,8,34,"ומי הוא יאשימם הן המשיח אשר מת וביותר אשר נעור מעם המתים הוא לימין האלהים והוא יפגיע בעדנו׃"));
hebsuperobject.biblemap.put("b45_8_35", new hebsuperobject(45,8,35,"מי יפרידנו מאהבת המשיח הצרה או מצוקה או משטמה או רעב אם עריה או סכנה או חרב׃"));
hebsuperobject.biblemap.put("b45_8_36", new hebsuperobject(45,8,36,"ככתוב כי עליך הרגנו כל היום נחשבנו כצאן טבחה׃"));
hebsuperobject.biblemap.put("b45_8_37", new hebsuperobject(45,8,37,"אבל בכל אלה גברנו מאד על ידי האהב אתנו׃"));
hebsuperobject.biblemap.put("b45_8_38", new hebsuperobject(45,8,38,"ובטוח אנכי כי לא המות ולא החיים לא מלאכים ולא שררות ולא גבורות לא ההוה ולא העתיד׃"));
hebsuperobject.biblemap.put("b45_8_39", new hebsuperobject(45,8,39,"לא הרוח ולא העמק ולא כל בריה אחרת יוכלו להפרידנו מאהבת האלהים אשר היא במשיח ישוע אדנינו׃"));
hebsuperobject.biblemap.put("b45_9_1", new hebsuperobject(45,9,1,"אמת אני מדבר במשיח ולא אשקף ודעתי מעידה לי ברוח הקדש׃"));
hebsuperobject.biblemap.put("b45_9_2", new hebsuperobject(45,9,2,"כי גדול עצבוני ואין קץ לדאבון לבי׃"));
hebsuperobject.biblemap.put("b45_9_3", new hebsuperobject(45,9,3,"כי מי יתן היתי אני מחרם מן המשיח בעד אחי שארי ובשרי׃"));
hebsuperobject.biblemap.put("b45_9_4", new hebsuperobject(45,9,4,"אשר הם בני ישראל ויש להם משפט הבנים והכבוד והבריתות ומתן התורה והעבודה וההבטחות׃"));
hebsuperobject.biblemap.put("b45_9_5", new hebsuperobject(45,9,5,"ולהם האבות ואשר מהם יצא המשיח לפי בשרו אשר הוא אל על הכל מברך לעולמים אמן׃"));
hebsuperobject.biblemap.put("b45_9_6", new hebsuperobject(45,9,6,"אבל לא כאלו נפל דבר אלהים ארצה כי לא כל אשר הם מישראל גם ישראל המה׃"));
hebsuperobject.biblemap.put("b45_9_7", new hebsuperobject(45,9,7,"ולא על היותם זרע אברהם כלם בנים הם כי ביצחק יקרא לך זרע׃"));
hebsuperobject.biblemap.put("b45_9_8", new hebsuperobject(45,9,8,"כלומר לא בני הבשר המה בני האלהים כי אם בני ההבטחה הם הנחשבים לזרע׃"));
hebsuperobject.biblemap.put("b45_9_9", new hebsuperobject(45,9,9,"כי דבר הבטחה הוא מה שנאמר למועד אשוב ולשרה בן׃"));
hebsuperobject.biblemap.put("b45_9_10", new hebsuperobject(45,9,10,"ולא זאת בלבד כי כן היה גם ברבקה בהיותה הרה לאחד ליצחק אבינו׃"));
hebsuperobject.biblemap.put("b45_9_11", new hebsuperobject(45,9,11,"כי בטרם ילדו בניה ועוד לא עשו טוב או רע למען תקום עצת האלהים כפי בחירתו לא מתוך מעשים כי אם כרצון הקרא׃"));
hebsuperobject.biblemap.put("b45_9_12", new hebsuperobject(45,9,12,"נאמר לה כי רב יעבד צעיר׃"));
hebsuperobject.biblemap.put("b45_9_13", new hebsuperobject(45,9,13,"ככתוב ואהב את יעקב ואת עשו שנאתי׃"));
hebsuperobject.biblemap.put("b45_9_14", new hebsuperobject(45,9,14,"אם כן מה נאמר הכי יש עול באלהים חלילה׃"));
hebsuperobject.biblemap.put("b45_9_15", new hebsuperobject(45,9,15,"כי למשה אמר וחנתי את אשר אחן ורחמתי את אשר ארחם׃"));
hebsuperobject.biblemap.put("b45_9_16", new hebsuperobject(45,9,16,"ועל כן אין הדבר לא ביד הרצה ולא ביד הרץ כי אם ביד האלהים המרחם׃"));
hebsuperobject.biblemap.put("b45_9_17", new hebsuperobject(45,9,17,"כי כן הכתוב אמר לפרעה בעבור זאת העמדתיך בעבור הראתך את כחי ולמען ספר שמי בכל הארץ׃"));
hebsuperobject.biblemap.put("b45_9_18", new hebsuperobject(45,9,18,"ויוצא מזה כי את אשר יחפץ יחננו ואת אשר יחפץ יקשהו׃"));
hebsuperobject.biblemap.put("b45_9_19", new hebsuperobject(45,9,19,"וכי תאמר אלי מדוע יוכיח עוד נגד רצונו מי יתיצב׃"));
hebsuperobject.biblemap.put("b45_9_20", new hebsuperobject(45,9,20,"אמנם בן אדם מי אתה אשר תריב את האלהים היאמר יצר ליצרו למה ככה עשיתני׃"));
hebsuperobject.biblemap.put("b45_9_21", new hebsuperobject(45,9,21,"אם אין רשות ליצר על החמר לעשות מגלם אחד כלי אחד לכבוד ואחד לקלון׃"));
hebsuperobject.biblemap.put("b45_9_22", new hebsuperobject(45,9,22,"ומה אפוא אם האלהים החפץ להראות זעמו ולהודיע גבורתו נשא בכל ארך רוחו את כלי הזעם הנכונים לאבדון׃"));
hebsuperobject.biblemap.put("b45_9_23", new hebsuperobject(45,9,23,"להודיע גם את עשר כבודו על כלי החנינה אשר יעדם לכבוד׃"));
hebsuperobject.biblemap.put("b45_9_24", new hebsuperobject(45,9,24,"והם אנחנו אשר קראם לא מן היהודים בלבד כי אף מן הגוים׃"));
hebsuperobject.biblemap.put("b45_9_25", new hebsuperobject(45,9,25,"כדברו בהושע אקרא ללא עמי עמי וללא רחמה רחמה׃"));
hebsuperobject.biblemap.put("b45_9_26", new hebsuperobject(45,9,26,"והיה במקום אשר יאמר להם לא עמי אתם יאמר להם בני אל חי׃"));
hebsuperobject.biblemap.put("b45_9_27", new hebsuperobject(45,9,27,"וישעיהו צוח על ישראל כי אם יהיה מספר בני ישראל כחול הים שאר ישוב בו כליון חרוץ שוטף צדקה׃"));
hebsuperobject.biblemap.put("b45_9_28", new hebsuperobject(45,9,28,"כי כלה ונחרצה אדני עשה בקרב הארץ׃"));
hebsuperobject.biblemap.put("b45_9_29", new hebsuperobject(45,9,29,"וכאשר אמר ישעיהו לפנים לולי יהוה צבאות הותיר לנו שריד כמעט כסדם היינו לעמרה דמינו׃"));
hebsuperobject.biblemap.put("b45_9_30", new hebsuperobject(45,9,30,"ועתה מה נאמר הגוים אשר לא רדפו אחרי הצדקה השיגו את הצדקה היא הצדקה אשר מתוך האמונה׃"));
hebsuperobject.biblemap.put("b45_9_31", new hebsuperobject(45,9,31,"וישראל בבקשו אחרי תורת צדקה לתורת הצדקה לא הגיע׃"));
hebsuperobject.biblemap.put("b45_9_32", new hebsuperobject(45,9,32,"ועל מה יען אשר לא מאמונה דרשוה כי אם ממעשים כי התנגפו באבן נגף׃"));
hebsuperobject.biblemap.put("b45_9_33", new hebsuperobject(45,9,33,"ככתוב הנני יסד בציון אבן נגף וצור מכשול וכל המאמין בו לא יבוש׃"));
hebsuperobject.biblemap.put("b45_10_1", new hebsuperobject(45,10,1,"אחי חפץ לבבי ותפלתי לאלהים בעד ישראל אשר יושעו׃"));
hebsuperobject.biblemap.put("b45_10_2", new hebsuperobject(45,10,2,"כי מעיד אני עליהם שיש להם קנאה לאלהים אך לא בדעת׃"));
hebsuperobject.biblemap.put("b45_10_3", new hebsuperobject(45,10,3,"כי את צדקת אלהים לא ידעו ויבקשו להקים את צדקתם ובעבור זאת לצדקת אלהים לא נכנעו׃"));
hebsuperobject.biblemap.put("b45_10_4", new hebsuperobject(45,10,4,"כי המשיח סוף התורה לצדקה לכל המאמין בו׃"));
hebsuperobject.biblemap.put("b45_10_5", new hebsuperobject(45,10,5,"כי משה כתב על דבר הצדקה מתוך התורה אשר יעשה אתם האדם וחי בהם׃"));
hebsuperobject.biblemap.put("b45_10_6", new hebsuperobject(45,10,6,"והצדקה אשר מתוך האמונה כה אמרת אל תאמר בלבבך מי יעלה השמימה הלא זאת היא להוריד את המשיח׃"));
hebsuperobject.biblemap.put("b45_10_7", new hebsuperobject(45,10,7,"או מי ירד לתהום זאת היא להעלות את המשיח מן המתים׃"));
hebsuperobject.biblemap.put("b45_10_8", new hebsuperobject(45,10,8,"אבל מה היא אמרת קרוב אליך הדבר בפיך ובלבבך הוא דבר האמונה אשר אנחנו מבשרים׃"));
hebsuperobject.biblemap.put("b45_10_9", new hebsuperobject(45,10,9,"כי אם תודה בפיך אשר ישוע הוא האדון ותאמין בלבבך אשר האלהים העירו מן המתים אז תושע׃"));
hebsuperobject.biblemap.put("b45_10_10", new hebsuperobject(45,10,10,"כי בלבבו יאמין האדם והיתה לו לצדקה ובפיהו יודה והיתה לו לישועה׃"));
hebsuperobject.biblemap.put("b45_10_11", new hebsuperobject(45,10,11,"כי הכתוב אמר כל המאמין בו לא יבוש׃"));
hebsuperobject.biblemap.put("b45_10_12", new hebsuperobject(45,10,12,"ואין הבדל בזה בין היהודי ליוני כי אדון אחד לכלם והוא עשיר לכל קראיו׃"));
hebsuperobject.biblemap.put("b45_10_13", new hebsuperobject(45,10,13,"כי כל אשר יקרא בשם יהוה ימלט׃"));
hebsuperobject.biblemap.put("b45_10_14", new hebsuperobject(45,10,14,"ועתה איך יקראו אל אשר לא האמינו בו ואיך יאמינו באשר לא שמעו את שמעו ואיך ישמעו באין מגיד׃"));
hebsuperobject.biblemap.put("b45_10_15", new hebsuperobject(45,10,15,"ואיך יגידו אם אינם שלוחים ככתוב מה נאוו רגלי מבשר שלום מבשר טוב׃"));
hebsuperobject.biblemap.put("b45_10_16", new hebsuperobject(45,10,16,"אך לא כלם שמעו לקול הבשורה כי ישעיהו אמר יהוה מי האמין לשמעתנו׃"));
hebsuperobject.biblemap.put("b45_10_17", new hebsuperobject(45,10,17,"לכן האמונה באה מתוך השמועה והשמועה על ידי דבר אלהים׃"));
hebsuperobject.biblemap.put("b45_10_18", new hebsuperobject(45,10,18,"ואמר הכי לא שמעו אמנם בכל הארץ יצא קום ובקצה תבל מליהם׃"));
hebsuperobject.biblemap.put("b45_10_19", new hebsuperobject(45,10,19,"ואמר הכי ישראל לא ידע הנה כבר משה אמר אני אקניאכם בלא עם בגוי נבל אכעיסכם׃"));
hebsuperobject.biblemap.put("b45_10_20", new hebsuperobject(45,10,20,"וישעיהו מלאו לבו לאמר נמצאתי ללא בקשני נדרשתי ללוא שאלו׃"));
hebsuperobject.biblemap.put("b45_10_21", new hebsuperobject(45,10,21,"ועל ישראל הוא אמר פרשתי ידי כל היום אל עם סורר ומרה׃"));
hebsuperobject.biblemap.put("b45_11_1", new hebsuperobject(45,11,1,"ובכן אמר אני הכי זנח האלהים את עמו חלילה כי גם אנכי בן ישראל מזרע אברהם למטה בנימן׃"));
hebsuperobject.biblemap.put("b45_11_2", new hebsuperobject(45,11,2,"לא זנח האלהים את עמו אשר ידעו מקדם או הלא תדעו את אשר הכתוב אמר באליהו כאשר קרא אל האלהים על ישראל לאמר׃"));
hebsuperobject.biblemap.put("b45_11_3", new hebsuperobject(45,11,3,"יהוה את נביאיך הרגו ואת מזבחתיך הרסו ואותר אני לבדי ויבקשו את נפשי׃"));
hebsuperobject.biblemap.put("b45_11_4", new hebsuperobject(45,11,4,"אבל מה ענה אתו מענה אלהים השארתי לי שבעת אלפים איש אשר לא כרעו לבעל׃"));
hebsuperobject.biblemap.put("b45_11_5", new hebsuperobject(45,11,5,"וכן גם בעת הזאת נותרה שארית על פי בחירת החסד׃"));
hebsuperobject.biblemap.put("b45_11_6", new hebsuperobject(45,11,6,"ואם היתה זאת על ידי החסד לא היתה מתוך המעשים כי לולי כן החסד איננו עוד חסד ואם היתה מתוך המעשים איננו עוד חסד כי לולי כן המעשים יחדל להיות מעשה׃"));
hebsuperobject.biblemap.put("b45_11_7", new hebsuperobject(45,11,7,"ועתה מה הוא את אשר בקש ישראל לא השיג רק הנבחרים הם השיגו והנשארים השמינו לבבם׃"));
hebsuperobject.biblemap.put("b45_11_8", new hebsuperobject(45,11,8,"ככתוב נתן להם האלהים רוח תרדמה עינים לא לראות ואזנים לא לשמע עד היום הזה׃"));
hebsuperobject.biblemap.put("b45_11_9", new hebsuperobject(45,11,9,"ודוד הוא אמר יהי שלחנם לפח ולרשת ולמוקש ולשלומים להם׃"));
hebsuperobject.biblemap.put("b45_11_10", new hebsuperobject(45,11,10,"תחשכנה עיניהם מראות ומתניהם תמיד המעד׃"));
hebsuperobject.biblemap.put("b45_11_11", new hebsuperobject(45,11,11,"ובכן אני אמר הנכשלו למען יפלו חלילה אך בפשעם יצאה הישועה לגוים למען הקניאם׃"));
hebsuperobject.biblemap.put("b45_11_12", new hebsuperobject(45,11,12,"ואם פשעם עשר העולם וחסרונם עשר הגוים מלאם על אחת כמה וכמה׃"));
hebsuperobject.biblemap.put("b45_11_13", new hebsuperobject(45,11,13,"כי אליכם הגוים אני מדבר וכפי אשר שליח הגוים אנכי את שרותי אפאר׃"));
hebsuperobject.biblemap.put("b45_11_14", new hebsuperobject(45,11,14,"לו אוכל להקניא את בשרי ולהושיע מקצתם׃"));
hebsuperobject.biblemap.put("b45_11_15", new hebsuperobject(45,11,15,"כי אם געילתם רצוי לעולם מה אפוא תהיה אספתם הלא חיים מן המתים׃"));
hebsuperobject.biblemap.put("b45_11_16", new hebsuperobject(45,11,16,"ואם התרומה קדש כן גם העסה ואם השרש קדש כן גם הענפים׃"));
hebsuperobject.biblemap.put("b45_11_17", new hebsuperobject(45,11,17,"וכי נקפו מקצת הענפים ואתה זית היער הרכבת במקומם ונתחברת לשרש הזית ולדשנו׃"));
hebsuperobject.biblemap.put("b45_11_18", new hebsuperobject(45,11,18,"אל תתפאר על הענפים ואם תתפאר דע שאינך נשא את השרש כי אם השרש הוא נשא אותך׃"));
hebsuperobject.biblemap.put("b45_11_19", new hebsuperobject(45,11,19,"וכי תאמר הלא נקפו הענפים למען ארכב אנכי׃"));
hebsuperobject.biblemap.put("b45_11_20", new hebsuperobject(45,11,20,"כן הוא המה נקפו על אשר לא האמינו ואתה הנך קים על ידי האמונה אל תתגאה כי אם ירא׃"));
hebsuperobject.biblemap.put("b45_11_21", new hebsuperobject(45,11,21,"כי האלהים אם לא חס על הענפים הנולדים מן העץ אולי לא יחוס גם עליך׃"));
hebsuperobject.biblemap.put("b45_11_22", new hebsuperobject(45,11,22,"לכן ראה נא טובת אלהים וזעמו זעמו על הנפלים ועליך טובתו אם תעמד בטובתו ואם אין כי עתה גם אתה תגדע׃"));
hebsuperobject.biblemap.put("b45_11_23", new hebsuperobject(45,11,23,"וגם המה אם לא יעמדו במרים ירכבו כי יכל האלהים לשוב להרכיבם׃"));
hebsuperobject.biblemap.put("b45_11_24", new hebsuperobject(45,11,24,"כי אם אתה נגזרת מעץ אשר הוא בטבעו זית יער והרכבת שלא כטבע בזית טוב אלה היצאים ממנו על אחת כמה וכמה שירכבו בזית שלהם׃"));
hebsuperobject.biblemap.put("b45_11_25", new hebsuperobject(45,11,25,"כי לא אכחד מכם אחי את הסוד הזה פן תהיו חכמים בעיניכם כי טמטום הלב למקצת נהיה לישראל עד כי יכנס מלא הגוים׃"));
hebsuperobject.biblemap.put("b45_11_26", new hebsuperobject(45,11,26,"ובכן כל ישראל יושע ככתוב ובא לציון גואל וישיב פשע מיעקב׃"));
hebsuperobject.biblemap.put("b45_11_27", new hebsuperobject(45,11,27,"ואני זאת בריתי אותם בהסירי חטאתם׃"));
hebsuperobject.biblemap.put("b45_11_28", new hebsuperobject(45,11,28,"הן לפי הבשורה שנואים הם למענכם אך לפי הבחירה חביבים הם למען האבות׃"));
hebsuperobject.biblemap.put("b45_11_29", new hebsuperobject(45,11,29,"כי לא ינחם האלהים על מתנותיו ועל קריאתו׃"));
hebsuperobject.biblemap.put("b45_11_30", new hebsuperobject(45,11,30,"כי כאשר גם אתם מלפנים ממרים הייתם את פי אלהים ועתה הוחנתם במרים של אלה׃"));
hebsuperobject.biblemap.put("b45_11_31", new hebsuperobject(45,11,31,"כן גם אלה עתה ממרים היו למען על ידי חנינתכם גם הם יחנו׃"));
hebsuperobject.biblemap.put("b45_11_32", new hebsuperobject(45,11,32,"כי האלהים הסגיר את כלם ביד המרי למען יחן את כלם׃"));
hebsuperobject.biblemap.put("b45_11_33", new hebsuperobject(45,11,33,"מה עמק עשר חכמת אלהים ועשר דעתו משפטיו מי יחקר ודרכיו מי ימצא׃"));
hebsuperobject.biblemap.put("b45_11_34", new hebsuperobject(45,11,34,"כי מי תכן את רוח יהוה ואיש עצתו יודיענו׃"));
hebsuperobject.biblemap.put("b45_11_35", new hebsuperobject(45,11,35,"או מי הקדימו וישלם לו׃"));
hebsuperobject.biblemap.put("b45_11_36", new hebsuperobject(45,11,36,"הלא הכל ממנו והכל בו והכל אליו אשר לו הכבוד לעולמים אמן׃"));
hebsuperobject.biblemap.put("b45_12_1", new hebsuperobject(45,12,1,"ועתה הנני מזהיר אתכם אחי ברחמי אלהים אשר תשימו את גויותיכם קרבן חי וקדוש ונרצה לאלהים והיתה זאת עבודתכם השכלית׃"));
hebsuperobject.biblemap.put("b45_12_2", new hebsuperobject(45,12,2,"ואל תשתוו לעולם הזה כי אם התחלפו בהתחדש דעתכם למען תבחנו לדעת מה הוא רצון האלהים הטוב והחמד והשלם׃"));
hebsuperobject.biblemap.put("b45_12_3", new hebsuperobject(45,12,3,"כי על פי החסד הנתן לי אמר אני לכל איש ואיש מכם לבלתי רום לבבו למעלה מן הראוי כי אם יהי צנוע במחשבותיו כפי מדת האמונה אשר חלק לו האלהים׃"));
hebsuperobject.biblemap.put("b45_12_4", new hebsuperobject(45,12,4,"כי כאשר בגוף אחד יש לנו אברים הרבה ואין פעלה אחת לכל האברים׃"));
hebsuperobject.biblemap.put("b45_12_5", new hebsuperobject(45,12,5,"כן אנחנו הברים גוף אחד במשיח וכל אחד ואחד ממנו אבר לחברו הוא׃"));
hebsuperobject.biblemap.put("b45_12_6", new hebsuperobject(45,12,6,"ויש לנו מתנות שנות כפי החסד הנתן לנו אם נבואה תהי כפי מדת האמונה׃"));
hebsuperobject.biblemap.put("b45_12_7", new hebsuperobject(45,12,7,"ואם לאיש שמוש יעמל בשמוש ואם מורה בהוראה׃"));
hebsuperobject.biblemap.put("b45_12_8", new hebsuperobject(45,12,8,"ואם מוכיח בתוכחה הנותן יעשה בתם לבב והמנהיג בשקידה והגמל חסד בסבר פנים יפות׃"));
hebsuperobject.biblemap.put("b45_12_9", new hebsuperobject(45,12,9,"האהבה תהיה בלי חנפה שנאו את הרע ודבקו בטוב׃"));
hebsuperobject.biblemap.put("b45_12_10", new hebsuperobject(45,12,10,"באהבת אחים הראו חבה יתרה ובכבוד הקדימו איש את רעהו׃"));
hebsuperobject.biblemap.put("b45_12_11", new hebsuperobject(45,12,11,"שקדו ואל תעצלו התלהבו ברוח עבדו את האדון׃"));
hebsuperobject.biblemap.put("b45_12_12", new hebsuperobject(45,12,12,"שמחו בתוחלת סבלו בצרה שקדו על התפלה׃"));
hebsuperobject.biblemap.put("b45_12_13", new hebsuperobject(45,12,13,"השתתפו בצרכי הקדושים רדפו הכנסת ארחים׃"));
hebsuperobject.biblemap.put("b45_12_14", new hebsuperobject(45,12,14,"ברכו את רדפיכם ברכו ואל תקללו׃"));
hebsuperobject.biblemap.put("b45_12_15", new hebsuperobject(45,12,15,"שמחו עם השמחים ובכו עם הבכים׃"));
hebsuperobject.biblemap.put("b45_12_16", new hebsuperobject(45,12,16,"לב אחד יהי לכלכם אל תהלכו בגדלות כי אם התנהגו עם השפלים אל תהיו חכמים בעיניכם׃"));
hebsuperobject.biblemap.put("b45_12_17", new hebsuperobject(45,12,17,"אל תשלמו לאיש רעה תחת רעה דרשו הטוב בעיני כל אדם׃"));
hebsuperobject.biblemap.put("b45_12_18", new hebsuperobject(45,12,18,"אם תוכלו ככל אשר תמצא ידכם היו בשלום עם כל אדם׃"));
hebsuperobject.biblemap.put("b45_12_19", new hebsuperobject(45,12,19,"אל תנקמו נקם ידידי כי אם תנו מקום לרגז כי כתוב לי נקם ושלם אמר יהוה׃"));
hebsuperobject.biblemap.put("b45_12_20", new hebsuperobject(45,12,20,"לכן אם רעב שנאך האכילהו לחם ואם צמא השקהו מים כי גחלים אתה חתה על ראשו׃"));
hebsuperobject.biblemap.put("b45_12_21", new hebsuperobject(45,12,21,"אל נא יכבשך הרע כבוש אתה את הרע בטוב׃"));
hebsuperobject.biblemap.put("b45_13_1", new hebsuperobject(45,13,1,"כל נפש תכנע לגדלת הרשיות כי אין רשות כי אם מאת האלהים והרשיות הנמצאות על יד אלהים נתמנו׃"));
hebsuperobject.biblemap.put("b45_13_2", new hebsuperobject(45,13,2,"לכן כל המתקומם לרשות מרד הוא בצווי האלהים והמרדים ישאו את דינם׃"));
hebsuperobject.biblemap.put("b45_13_3", new hebsuperobject(45,13,3,"כי השליטים אינם לפחד למעשים הטובים כי אם להרעים ועל כן אם רצונך שלא תירא מן הרשות עשה הטוב והיה לך שבח ממנה׃"));
hebsuperobject.biblemap.put("b45_13_4", new hebsuperobject(45,13,4,"כי משמשת אלהים היא לטוב לך אך אם הרע תעשה ירא כי לא לחנם חגרת חרב היא כי משמשת אלהים היא נקמת בקצף מכל עשה הרע׃"));
hebsuperobject.biblemap.put("b45_13_5", new hebsuperobject(45,13,5,"על כן עלינו להכנע לא לבד בעבור הקצף כי גם בעבור דעת חובתנו׃"));
hebsuperobject.biblemap.put("b45_13_6", new hebsuperobject(45,13,6,"כי לזאת אף משלמים אתם את המס כי משרתי אלהים המה השקדים על זאת׃"));
hebsuperobject.biblemap.put("b45_13_7", new hebsuperobject(45,13,7,"לכן תנו לכל איש כחובתכם המס לאשר לו המס המכס לאשר לו המכס והמורא לאשר לו המורא והכבוד לאשר לו הכבוד׃"));
hebsuperobject.biblemap.put("b45_13_8", new hebsuperobject(45,13,8,"ואל תהיו חיבים לאיש דבר זולתי אהבת איש את רעהו כי האהב את חברו קים את התורה׃"));
hebsuperobject.biblemap.put("b45_13_9", new hebsuperobject(45,13,9,"כי מצות לא תנאף לא תרצח לא תגנב לא תענה עד שקר לא תחמד ועוד כאלה כלולות הנה במאמר הזה ואהבת לרעך כמוך׃"));
hebsuperobject.biblemap.put("b45_13_10", new hebsuperobject(45,13,10,"האהבה לא תרע לרע על כן האהבה קיום התורה כלה׃"));
hebsuperobject.biblemap.put("b45_13_11", new hebsuperobject(45,13,11,"וכזאת עשו מדעתכם את הזמן כי כבר הגיעה השעה להקיץ מן השנה כי ישועתנו קרובה עתה מהיום אשר באנו להאמין׃"));
hebsuperobject.biblemap.put("b45_13_12", new hebsuperobject(45,13,12,"הלילה חלף והיום קרב לכן נסירה נא את מעשי החשך ונלבשה את כלי נשק האור׃"));
hebsuperobject.biblemap.put("b45_13_13", new hebsuperobject(45,13,13,"וכמו ביום נתהלכה בצניעות לא בזוללות ובשכרון ולא בבעילות ועשות זמה ולא במריבה וקנאה׃"));
hebsuperobject.biblemap.put("b45_13_14", new hebsuperobject(45,13,14,"כי אם לבשו את האדון ישוע המשיח ודאגו לבשרכם אך לא להגביר התאות׃"));
hebsuperobject.biblemap.put("b45_14_1", new hebsuperobject(45,14,1,"ואת החלוש באמונה אותו קבלו ולא לדין את המחשבות׃"));
hebsuperobject.biblemap.put("b45_14_2", new hebsuperobject(45,14,2,"יש מאמין כי נכון לאכל כל דבר והחלוש יאכל רק את הירק׃"));
hebsuperobject.biblemap.put("b45_14_3", new hebsuperobject(45,14,3,"האכל אל יבז את אשר לא יאכל ואשר לא יאכל אל ידין את האכל כי קבל אתו האלהים׃"));
hebsuperobject.biblemap.put("b45_14_4", new hebsuperobject(45,14,4,"מי אתה כי תדין את עבד האחר הן לאדניו הוא יקום או יפל אבל יוקם כי יכל האלהים להקימו׃"));
hebsuperobject.biblemap.put("b45_14_5", new hebsuperobject(45,14,5,"יש מבדיל בין יום ליום ויש אשר כל הימים שוים בעיניו ויהי כל איש נכון בדעתו׃"));
hebsuperobject.biblemap.put("b45_14_6", new hebsuperobject(45,14,6,"השמר את היום לאדון שמר אתו ואשר איננו שמר את היום לאדון איננו שמר האכל לאדון הוא אכל כי מודה הוא לאלהים ואשר איננו אכל לאדון איננו אכל ומודה הוא לאלהים׃"));
hebsuperobject.biblemap.put("b45_14_7", new hebsuperobject(45,14,7,"כי אין איש מאתנו אשר יחיה לנפשו ואין איש אשר ימות לנפשו׃"));
hebsuperobject.biblemap.put("b45_14_8", new hebsuperobject(45,14,8,"כי כאשר נחיה נחיה לאדון וכאשר נמות נמות לאדון לכן אם נחיה ואם נמות לאדון הננו׃"));
hebsuperobject.biblemap.put("b45_14_9", new hebsuperobject(45,14,9,"כי לזאת מת המשיח ויקם ויחי למען יהיה אדון גם על המתים גם על החיים׃"));
hebsuperobject.biblemap.put("b45_14_10", new hebsuperobject(45,14,10,"ואתה למה זה תדין את אחיך או אתה למה תבוז לאחיך הלא כלנו עתידים לעמד לפני כסא דין אלהים׃"));
hebsuperobject.biblemap.put("b45_14_11", new hebsuperobject(45,14,11,"כי כתוב חי אני נאם יהוה כי לי תכרע כל ברך וכל לשון תודה לאלהים׃"));
hebsuperobject.biblemap.put("b45_14_12", new hebsuperobject(45,14,12,"הנה נא כל אחד ממנו על נפשו יתן חשבון לאלהים׃"));
hebsuperobject.biblemap.put("b45_14_13", new hebsuperobject(45,14,13,"לכן אל נדין עוד איש את רעהו כי אם זה יהי דינכם שלא יתן איש לפני אחיו מכשול או מוקש׃"));
hebsuperobject.biblemap.put("b45_14_14", new hebsuperobject(45,14,14,"ידעתי ומבטח אני באדון ישוע כי אין דבר טמא בפני עצמו ורק טמא הוא למי שיחשבנו לו לטמא׃"));
hebsuperobject.biblemap.put("b45_14_15", new hebsuperobject(45,14,15,"ואם יעצב אחיך על דבר האכל אינך מתהלך עוד בדרך האהבה אל נא תאבד באכלך את אשר בעדו מת המשיח׃"));
hebsuperobject.biblemap.put("b45_14_16", new hebsuperobject(45,14,16,"לכן הזהרו פן יהיה טובכם לגדופים׃"));
hebsuperobject.biblemap.put("b45_14_17", new hebsuperobject(45,14,17,"כי מלכות האלהים איננה אכילה ושתיה כי צדקה היא ושלום ושמחה ברוח הקדש׃"));
hebsuperobject.biblemap.put("b45_14_18", new hebsuperobject(45,14,18,"והעבד באלה את המשיח רצוי הוא לאלהים ובחון לאנשים׃"));
hebsuperobject.biblemap.put("b45_14_19", new hebsuperobject(45,14,19,"ועתה נרדפה דרך השלום ודרך הבנות יחד איש מרעהו׃"));
hebsuperobject.biblemap.put("b45_14_20", new hebsuperobject(45,14,20,"אל תהרוס את מעשה אלהים על דבר מאכל הן הכל טהור הוא אבל רע לאדם אשר יאכלנו במכשל לבו׃"));
hebsuperobject.biblemap.put("b45_14_21", new hebsuperobject(45,14,21,"טוב שלא תאכל בשר ולא תשתה יין ולא תעשה דבר אשר יתנגף בו אחיך או יכשל או יחלש׃"));
hebsuperobject.biblemap.put("b45_14_22", new hebsuperobject(45,14,22,"יש לך אמונה תהי לך לבדך לפני האלהים אשרי מי שלא ידין את נפשו בדבר אשר כשר בעיניו׃"));
hebsuperobject.biblemap.put("b45_14_23", new hebsuperobject(45,14,23,"ואשר לו ספק באכלו נאשם כי לא עשה מאמונה וכל אשר נעשה מבלי אמונה חטא הוא,׃"));
hebsuperobject.biblemap.put("b45_15_1", new hebsuperobject(45,15,1,"ועלינו החזקים לשאת חלשות הכשלים ואל נבקש הנאת עצמנו׃"));
hebsuperobject.biblemap.put("b45_15_2", new hebsuperobject(45,15,2,"כי כל אחד ממנו יבקש הנאת חברו לטוב לו למען יבנה׃"));
hebsuperobject.biblemap.put("b45_15_3", new hebsuperobject(45,15,3,"כי גם המשיח לא בקש הנאת עצמו אלא ככתוב חרפות חורפיך נפלו עלי׃"));
hebsuperobject.biblemap.put("b45_15_4", new hebsuperobject(45,15,4,"כי כל אשר נכתב מלפנים ללמדנו נכתב למען תהיה לנו תקוה בסבלנות ובתנחומות הכתובים׃"));
hebsuperobject.biblemap.put("b45_15_5", new hebsuperobject(45,15,5,"ואלהי הסבלנות והנחמה הוא יתן לכם להיות כלכם לב אחד על פי המשיח ישוע׃"));
hebsuperobject.biblemap.put("b45_15_6", new hebsuperobject(45,15,6,"אשר תכבדו בנפש אחת ובפה אחד את האלהים אבי אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b45_15_7", new hebsuperobject(45,15,7,"על כן תקבלו איש את אחיו כאשר גם המשיח קבל אתנו לכבוד האלהים׃"));
hebsuperobject.biblemap.put("b45_15_8", new hebsuperobject(45,15,8,"ואני אמר כי ישוע המשיח היה למשרת בני המילה למען אמת האלהים לקים את ההבטחות אשר לאבות׃"));
hebsuperobject.biblemap.put("b45_15_9", new hebsuperobject(45,15,9,"והגוים המה יכבדו את האלהים למען רחמיו ככתוב על כן אודך בגוים ולשמך אזמרה׃"));
hebsuperobject.biblemap.put("b45_15_10", new hebsuperobject(45,15,10,"ואומר הרנינו גוים עמו׃"));
hebsuperobject.biblemap.put("b45_15_11", new hebsuperobject(45,15,11,"ואומר הללו את יהוה כל גוים שבחוהו כל האמים׃"));
hebsuperobject.biblemap.put("b45_15_12", new hebsuperobject(45,15,12,"וישעיהו אמר והיה שרש ישי אשר עמד לנס עמים אליו גוים יקוו׃"));
hebsuperobject.biblemap.put("b45_15_13", new hebsuperobject(45,15,13,"ואלהי התקוה הוא ימלא אתכם כל שמחה ושלום באמונה למען תעדף תקותכם בגבורת רוח הקדש׃"));
hebsuperobject.biblemap.put("b45_15_14", new hebsuperobject(45,15,14,"והנה אחי מבטח אני בכם כי גם אתם בעצמכם מלאי אהבת חסד ממלאים כל דעת ותוכלו להוכיח איש את רעהו׃"));
hebsuperobject.biblemap.put("b45_15_15", new hebsuperobject(45,15,15,"אך העזתי מעט בכתבי אליכם הנה והנה כמזכיר אתכם על פי החסד הנתון לי מאת האלהים׃"));
hebsuperobject.biblemap.put("b45_15_16", new hebsuperobject(45,15,16,"להיותי משרת ישוע המשיח לגוים ולכהן בבשורת האלהים למען יהיה קרבן הגוים רצוי ומקדש ברוח הקדש׃"));
hebsuperobject.biblemap.put("b45_15_17", new hebsuperobject(45,15,17,"על כן יש לי להתהלל במשיח ישוע נגד האלהים׃"));
hebsuperobject.biblemap.put("b45_15_18", new hebsuperobject(45,15,18,"כי לא אעז פני לדבר דבר זולתי אשר עשה המשיח בידי למען הטות באמר ובמעשה את לב הגוים לסור למשמעתו׃"));
hebsuperobject.biblemap.put("b45_15_19", new hebsuperobject(45,15,19,"בגבורת אתות ומופתים ובגבורת רוח אלהים עד כי מלאתי מירושלים וסביבותיה ועד לאלוריקון את בשורת המשיח׃"));
hebsuperobject.biblemap.put("b45_15_20", new hebsuperobject(45,15,20,"בהשתדלי להגיד את הבשורה לא במקמות אשר שם כבר נקרא שם המשיח לבלתי בנות על יסוד אחרים׃"));
hebsuperobject.biblemap.put("b45_15_21", new hebsuperobject(45,15,21,"כי אם ככתוב אשר לא ספר להם ראו ואשר לא שמעו התבוננו׃"));
hebsuperobject.biblemap.put("b45_15_22", new hebsuperobject(45,15,22,"וזה הוא הדבר אשר נעצרתי בגללו פעם ושתים מבוא אליכם׃"));
hebsuperobject.biblemap.put("b45_15_23", new hebsuperobject(45,15,23,"אבל כעת אשר אין עוד מקום לי בגלילות האלה ונכסף נכספתי לבא אליכם זה שנים רבות׃"));
hebsuperobject.biblemap.put("b45_15_24", new hebsuperobject(45,15,24,"אבוא אליכם בלכתי לאספמיא כי מקוה אנכי לראותכם בעברי ואתם תשלחוני שמה ואשבעה מעט מכם בראשונה׃"));
hebsuperobject.biblemap.put("b45_15_25", new hebsuperobject(45,15,25,"אמנם עתה אלכה ירושלימה לעזור את הקדושים׃"));
hebsuperobject.biblemap.put("b45_15_26", new hebsuperobject(45,15,26,"כי מקדוניא ואכיא הואילו לתת משאת נדבה לאביוני הקדושים אשר בירושלים׃"));
hebsuperobject.biblemap.put("b45_15_27", new hebsuperobject(45,15,27,"כי הואילו ואף מחיבים הם להם כי אם היה לגוים חלק בדברי הרוח אשר להם הלא עליהם לעזרם גם בדברי הגוף׃"));
hebsuperobject.biblemap.put("b45_15_28", new hebsuperobject(45,15,28,"לכן כשגמרתי את זאת וחתמתי להם הפרי הזה אז אעברה דרך ארצכם לאספמיא׃"));
hebsuperobject.biblemap.put("b45_15_29", new hebsuperobject(45,15,29,"ויודע אנכי כי בבאי אליכם אבוא במלא ברכת בשורת המשיח׃"));
hebsuperobject.biblemap.put("b45_15_30", new hebsuperobject(45,15,30,"ואני מעורר אתכם אחי באדנינו ישוע המשיח ובאהבת הרוח להתאמץ אתי בהעתיר בעדי אל האלהים׃"));
hebsuperobject.biblemap.put("b45_15_31", new hebsuperobject(45,15,31,"למען אשר אנצל מהסוררים בארץ יהודה ויערב על הקדושים שמושי לשם ירושלים׃"));
hebsuperobject.biblemap.put("b45_15_32", new hebsuperobject(45,15,32,"ואשר אבוא אליכם במשחה ברצון אלהים ואנפש עמכם׃"));
hebsuperobject.biblemap.put("b45_15_33", new hebsuperobject(45,15,33,"ואלהי השלום עם כלכם אמן׃"));
hebsuperobject.biblemap.put("b45_16_1", new hebsuperobject(45,16,1,"והנני מזכיר לכם לטוב את פובי אחותנו שהיא משמשת הקהלה אשר בקנכרי׃"));
hebsuperobject.biblemap.put("b45_16_2", new hebsuperobject(45,16,2,"אשר תקבלוה באדנינו כראוי לקדושים ותעזרו לה בכל אשר תצטרך לכם כי היתה גם היא עזרת לרבים וגם לעצמי׃"));
hebsuperobject.biblemap.put("b45_16_3", new hebsuperobject(45,16,3,"שאלו לשלום פריסקלא ועקילס שהם חברי בעבודת המשיח ישוע׃"));
hebsuperobject.biblemap.put("b45_16_4", new hebsuperobject(45,16,4,"ואשר מסרו את צוארם בעד נפשי ולא אני לבדי אודה להם כי גם כל קהלות הגוים וגם לשלום הקהלה בביתם׃"));
hebsuperobject.biblemap.put("b45_16_5", new hebsuperobject(45,16,5,"שאלו לשלום אפינטוס חביבי שהוא ראשית אכיא למשיח׃"));
hebsuperobject.biblemap.put("b45_16_6", new hebsuperobject(45,16,6,"שאלו לשלום מרים שעמלה עמל רב בעבורנו׃"));
hebsuperobject.biblemap.put("b45_16_7", new hebsuperobject(45,16,7,"שאלו לשלום אנדרוניקוס ויוניס שהם קרובי ואסורים אתי ולהם שם בשליחים ולפני היו במשיח׃"));
hebsuperobject.biblemap.put("b45_16_8", new hebsuperobject(45,16,8,"שאלו לשלום אמפליאס חביבי באדנינו׃"));
hebsuperobject.biblemap.put("b45_16_9", new hebsuperobject(45,16,9,"שאלו לשלום אורבנוס חברנו בעבודת המשיח ולשלום אסטכים חביבי׃"));
hebsuperobject.biblemap.put("b45_16_10", new hebsuperobject(45,16,10,"שאלו לשלום אפליס הבחון במשיח שאלו לשלום בני ביתו של אריסטובלוס׃"));
hebsuperobject.biblemap.put("b45_16_11", new hebsuperobject(45,16,11,"שאלו לשלום הורודיון קרובי שאלו לשלום בני ביתו של נרקיסוס אשר הם באדנינו׃"));
hebsuperobject.biblemap.put("b45_16_12", new hebsuperobject(45,16,12,"שאלו לשלום טרופינה וטרופסה העמלות באדנינו שאלו לשלום פרסיס החביבה שעמלה עמל רב באדנינו׃"));
hebsuperobject.biblemap.put("b45_16_13", new hebsuperobject(45,16,13,"שאלו לשלום רופוס הנבחר באדנינו ולשלום אמו שהיא כאם לי׃"));
hebsuperobject.biblemap.put("b45_16_14", new hebsuperobject(45,16,14,"שאלו לשלום אסונקריטוס ופליגון והרמס ופטרובס יהרמיס והאחים אשר אתם׃"));
hebsuperobject.biblemap.put("b45_16_15", new hebsuperobject(45,16,15,"שאלו לשלום פילולוגוס ויוליא נירוס ואחותו ואולומפס וכל הקדושים אשר אתם׃"));
hebsuperobject.biblemap.put("b45_16_16", new hebsuperobject(45,16,16,"שאלו לשלום איש את רעהו בנשיקה הקדושה קהלות המשיח שאלות לשלומכם׃"));
hebsuperobject.biblemap.put("b45_16_17", new hebsuperobject(45,16,17,"ואני מזהיר אתכם אחי לשום פניכם בעשי מחלקות ומכשולים לנגד הלקח אשר למדתם וסורו מהם׃"));
hebsuperobject.biblemap.put("b45_16_18", new hebsuperobject(45,16,18,"כי אנשים אשר כאלה אינם עבדים את אדנינו ישוע המשיח כי אם את כרשם ובאמרי נעם ושפת חלקות יתעו את לב הפתאים׃"));
hebsuperobject.biblemap.put("b45_16_19", new hebsuperobject(45,16,19,"כי משמעתכם נודעת לכל לכן אני שמח עליכם אך חפצתי היתכם חכמים להטיב ותמימים לבלתי הרע׃"));
hebsuperobject.biblemap.put("b45_16_20", new hebsuperobject(45,16,20,"ואלהי השלום הוא ידכא את השטן במהרה תחת רגליכם חסד אדנינו ישוע המשיח עמכם׃"));
hebsuperobject.biblemap.put("b45_16_21", new hebsuperobject(45,16,21,"טימותיוס חברי ולוקיוס ויסון וסוספטרוס קרובי שאלים לשלומכם׃"));
hebsuperobject.biblemap.put("b45_16_22", new hebsuperobject(45,16,22,"אני טרטיוס כותב האגרת הזאת שאל לשלומכם באדנינו׃"));
hebsuperobject.biblemap.put("b45_16_23", new hebsuperobject(45,16,23,"גיוס המארח אותי ואת כל הקהלה שאל לשלומכם ארסטוס סכן העיר וקורטוס אחינו שאלים לשלומכם׃"));
hebsuperobject.biblemap.put("b45_16_24", new hebsuperobject(45,16,24,"חסד אדנינו ישוע המשיח עם כלכם אמן׃"));
hebsuperobject.biblemap.put("b45_16_25", new hebsuperobject(45,16,25,"ולאשר יכל לחזק אתכם כבשורתי וכקריאת ישוע המשיח כפי גלוי הסוד אשר היה מכסה מימות עולם׃"));
hebsuperobject.biblemap.put("b45_16_26", new hebsuperobject(45,16,26,"ועתה נתפרסם ונודע על ידי כתבי הנביאים כמצות אלהי עולם לכל הגוים להביאם למשמעת האמונה׃"));
hebsuperobject.biblemap.put("b45_16_27", new hebsuperobject(45,16,27,"לאלהים החכם לבדו לו הכבוד בישוע המשיח לעולמים אמן׃"));

}

}