package heb.bible;

public class hebbible15 {

public hebbible15() {

putmapbible15();

}

private void putmapbible15() {

hebsuperobject.biblemap.put("b15_1_1", new hebsuperobject(15,1,1,"ובשנת אחת לכורש מלך פרס לכלות דבר יהוה מפי ירמיה העיר יהוה את רוח כרש מלך פרס ויעבר קול בכל מלכותו וגם במכתב לאמר׃"));
hebsuperobject.biblemap.put("b15_1_2", new hebsuperobject(15,1,2,"כה אמר כרש מלך פרס כל ממלכות הארץ נתן לי יהוה אלהי השמים והוא פקד עלי לבנות לו בית בירושלם אשר ביהודה׃"));
hebsuperobject.biblemap.put("b15_1_3", new hebsuperobject(15,1,3,"מי בכם מכל עמו יהי אלהיו עמו ויעל לירושלם אשר ביהודה ויבן את בית יהוה אלהי ישראל הוא האלהים אשר בירושלם׃"));
hebsuperobject.biblemap.put("b15_1_4", new hebsuperobject(15,1,4,"וכל הנשאר מכל המקמות אשר הוא גר שם ינשאוהו אנשי מקמו בכסף ובזהב וברכוש ובבהמה עם הנדבה לבית האלהים אשר בירושלם׃"));
hebsuperobject.biblemap.put("b15_1_5", new hebsuperobject(15,1,5,"ויקומו ראשי האבות ליהודה ובנימן והכהנים והלוים לכל העיר האלהים את רוחו לעלות לבנות את בית יהוה אשר בירושלם׃"));
hebsuperobject.biblemap.put("b15_1_6", new hebsuperobject(15,1,6,"וכל סביבתיהם חזקו בידיהם בכלי כסף בזהב ברכוש ובבהמה ובמגדנות לבד על כל התנדב׃"));
hebsuperobject.biblemap.put("b15_1_7", new hebsuperobject(15,1,7,"והמלך כורש הוציא את כלי בית יהוה אשר הוציא נבוכדנצר מירושלם ויתנם בבית אלהיו׃"));
hebsuperobject.biblemap.put("b15_1_8", new hebsuperobject(15,1,8,"ויוציאם כורש מלך פרס על יד מתרדת הגזבר ויספרם לששבצר הנשיא ליהודה׃"));
hebsuperobject.biblemap.put("b15_1_9", new hebsuperobject(15,1,9,"ואלה מספרם אגרטלי זהב שלשים אגרטלי כסף אלף מחלפים תשעה ועשרים׃"));
hebsuperobject.biblemap.put("b15_1_10", new hebsuperobject(15,1,10,"כפורי זהב שלשים כפורי כסף משנים ארבע מאות ועשרה כלים אחרים אלף׃"));
hebsuperobject.biblemap.put("b15_1_11", new hebsuperobject(15,1,11,"כל כלים לזהב ולכסף חמשת אלפים וארבע מאות הכל העלה ששבצר עם העלות הגולה מבבל לירושלם׃"));
hebsuperobject.biblemap.put("b15_2_1", new hebsuperobject(15,2,1,"ואלה בני המדינה העלים משבי הגולה אשר הגלה נבוכדנצור מלך בבל לבבל וישובו לירושלם ויהודה איש לעירו׃"));
hebsuperobject.biblemap.put("b15_2_2", new hebsuperobject(15,2,2,"אשר באו עם זרבבל ישוע נחמיה שריה רעליה מרדכי בלשן מספר בגוי רחום בענה מספר אנשי עם ישראל׃"));
hebsuperobject.biblemap.put("b15_2_3", new hebsuperobject(15,2,3,"בני פרעש אלפים מאה שבעים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_4", new hebsuperobject(15,2,4,"בני שפטיה שלש מאות שבעים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_5", new hebsuperobject(15,2,5,"בני ארח שבע מאות חמשה ושבעים׃"));
hebsuperobject.biblemap.put("b15_2_6", new hebsuperobject(15,2,6,"בני פחת מואב לבני ישוע יואב אלפים שמנה מאות ושנים עשר׃"));
hebsuperobject.biblemap.put("b15_2_7", new hebsuperobject(15,2,7,"בני עילם אלף מאתים חמשים וארבעה׃"));
hebsuperobject.biblemap.put("b15_2_8", new hebsuperobject(15,2,8,"בני זתוא תשע מאות וארבעים וחמשה׃"));
hebsuperobject.biblemap.put("b15_2_9", new hebsuperobject(15,2,9,"בני זכי שבע מאות וששים׃"));
hebsuperobject.biblemap.put("b15_2_10", new hebsuperobject(15,2,10,"בני בני שש מאות ארבעים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_11", new hebsuperobject(15,2,11,"בני בבי שש מאות עשרים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_12", new hebsuperobject(15,2,12,"בני עזגד אלף מאתים עשרים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_13", new hebsuperobject(15,2,13,"בני אדניקם שש מאות ששים וששה׃"));
hebsuperobject.biblemap.put("b15_2_14", new hebsuperobject(15,2,14,"בני בגוי אלפים חמשים וששה׃"));
hebsuperobject.biblemap.put("b15_2_15", new hebsuperobject(15,2,15,"בני עדין ארבע מאות חמשים וארבעה׃"));
hebsuperobject.biblemap.put("b15_2_16", new hebsuperobject(15,2,16,"בני אטר ליחזקיה תשעים ושמנה׃"));
hebsuperobject.biblemap.put("b15_2_17", new hebsuperobject(15,2,17,"בני בצי שלש מאות עשרים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_18", new hebsuperobject(15,2,18,"בני יורה מאה ושנים עשר׃"));
hebsuperobject.biblemap.put("b15_2_19", new hebsuperobject(15,2,19,"בני חשם מאתים עשרים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_20", new hebsuperobject(15,2,20,"בני גבר תשעים וחמשה׃"));
hebsuperobject.biblemap.put("b15_2_21", new hebsuperobject(15,2,21,"בני בית לחם מאה עשרים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_22", new hebsuperobject(15,2,22,"אנשי נטפה חמשים וששה׃"));
hebsuperobject.biblemap.put("b15_2_23", new hebsuperobject(15,2,23,"אנשי ענתות מאה עשרים ושמנה׃"));
hebsuperobject.biblemap.put("b15_2_24", new hebsuperobject(15,2,24,"בני עזמות ארבעים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_25", new hebsuperobject(15,2,25,"בני קרית ערים כפירה ובארות שבע מאות וארבעים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_26", new hebsuperobject(15,2,26,"בני הרמה וגבע שש מאות עשרים ואחד׃"));
hebsuperobject.biblemap.put("b15_2_27", new hebsuperobject(15,2,27,"אנשי מכמס מאה עשרים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_28", new hebsuperobject(15,2,28,"אנשי בית אל והעי מאתים עשרים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_29", new hebsuperobject(15,2,29,"בני נבו חמשים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_30", new hebsuperobject(15,2,30,"בני מגביש מאה חמשים וששה׃"));
hebsuperobject.biblemap.put("b15_2_31", new hebsuperobject(15,2,31,"בני עילם אחר אלף מאתים חמשים וארבעה׃"));
hebsuperobject.biblemap.put("b15_2_32", new hebsuperobject(15,2,32,"בני חרם שלש מאות ועשרים׃"));
hebsuperobject.biblemap.put("b15_2_33", new hebsuperobject(15,2,33,"בני לד חדיד ואונו שבע מאות עשרים וחמשה׃"));
hebsuperobject.biblemap.put("b15_2_34", new hebsuperobject(15,2,34,"בני ירחו שלש מאות ארבעים וחמשה׃"));
hebsuperobject.biblemap.put("b15_2_35", new hebsuperobject(15,2,35,"בני סנאה שלשת אלפים ושש מאות ושלשים׃"));
hebsuperobject.biblemap.put("b15_2_36", new hebsuperobject(15,2,36,"הכהנים בני ידעיה לבית ישוע תשע מאות שבעים ושלשה׃"));
hebsuperobject.biblemap.put("b15_2_37", new hebsuperobject(15,2,37,"בני אמר אלף חמשים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_38", new hebsuperobject(15,2,38,"בני פשחור אלף מאתים ארבעים ושבעה׃"));
hebsuperobject.biblemap.put("b15_2_39", new hebsuperobject(15,2,39,"בני חרם אלף ושבעה עשר׃"));
hebsuperobject.biblemap.put("b15_2_40", new hebsuperobject(15,2,40,"הלוים בני ישוע וקדמיאל לבני הודויה שבעים וארבעה׃"));
hebsuperobject.biblemap.put("b15_2_41", new hebsuperobject(15,2,41,"המשררים בני אסף מאה עשרים ושמנה׃"));
hebsuperobject.biblemap.put("b15_2_42", new hebsuperobject(15,2,42,"בני השערים בני שלום בני אטר בני טלמון בני עקוב בני חטיטא בני שבי הכל מאה שלשים ותשעה׃"));
hebsuperobject.biblemap.put("b15_2_43", new hebsuperobject(15,2,43,"הנתינים בני ציחא בני חשופא בני טבעות׃"));
hebsuperobject.biblemap.put("b15_2_44", new hebsuperobject(15,2,44,"בני קרס בני סיעהא בני פדון׃"));
hebsuperobject.biblemap.put("b15_2_45", new hebsuperobject(15,2,45,"בני לבנה בני חגבה בני עקוב׃"));
hebsuperobject.biblemap.put("b15_2_46", new hebsuperobject(15,2,46,"בני חגב בני שמלי בני חנן׃"));
hebsuperobject.biblemap.put("b15_2_47", new hebsuperobject(15,2,47,"בני גדל בני גחר בני ראיה׃"));
hebsuperobject.biblemap.put("b15_2_48", new hebsuperobject(15,2,48,"בני רצין בני נקודא בני גזם׃"));
hebsuperobject.biblemap.put("b15_2_49", new hebsuperobject(15,2,49,"בני עזא בני פסח בני בסי׃"));
hebsuperobject.biblemap.put("b15_2_50", new hebsuperobject(15,2,50,"בני אסנה בני מעונים בני נפיסים׃"));
hebsuperobject.biblemap.put("b15_2_51", new hebsuperobject(15,2,51,"בני בקבוק בני חקופא בני חרחור׃"));
hebsuperobject.biblemap.put("b15_2_52", new hebsuperobject(15,2,52,"בני בצלות בני מחידא בני חרשא׃"));
hebsuperobject.biblemap.put("b15_2_53", new hebsuperobject(15,2,53,"בני ברקוס בני סיסרא בני תמח׃"));
hebsuperobject.biblemap.put("b15_2_54", new hebsuperobject(15,2,54,"בני נציח בני חטיפא׃"));
hebsuperobject.biblemap.put("b15_2_55", new hebsuperobject(15,2,55,"בני עבדי שלמה בני סטי בני הספרת בני פרודא׃"));
hebsuperobject.biblemap.put("b15_2_56", new hebsuperobject(15,2,56,"בני יעלה בני דרקון בני גדל׃"));
hebsuperobject.biblemap.put("b15_2_57", new hebsuperobject(15,2,57,"בני שפטיה בני חטיל בני פכרת הצביים בני אמי׃"));
hebsuperobject.biblemap.put("b15_2_58", new hebsuperobject(15,2,58,"כל הנתינים ובני עבדי שלמה שלש מאות תשעים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_59", new hebsuperobject(15,2,59,"ואלה העלים מתל מלח תל חרשא כרוב אדן אמר ולא יכלו להגיד בית אבותם וזרעם אם מישראל הם׃"));
hebsuperobject.biblemap.put("b15_2_60", new hebsuperobject(15,2,60,"בני דליה בני טוביה בני נקודא שש מאות חמשים ושנים׃"));
hebsuperobject.biblemap.put("b15_2_61", new hebsuperobject(15,2,61,"ומבני הכהנים בני חביה בני הקוץ בני ברזלי אשר לקח מבנות ברזלי הגלעדי אשה ויקרא על שמם׃"));
hebsuperobject.biblemap.put("b15_2_62", new hebsuperobject(15,2,62,"אלה בקשו כתבם המתיחשים ולא נמצאו ויגאלו מן הכהנה׃"));
hebsuperobject.biblemap.put("b15_2_63", new hebsuperobject(15,2,63,"ויאמר התרשתא להם אשר לא יאכלו מקדש הקדשים עד עמד כהן לאורים ולתמים׃"));
hebsuperobject.biblemap.put("b15_2_64", new hebsuperobject(15,2,64,"כל הקהל כאחד ארבע רבוא אלפים שלש מאות ששים׃"));
hebsuperobject.biblemap.put("b15_2_65", new hebsuperobject(15,2,65,"מלבד עבדיהם ואמהתיהם אלה שבעת אלפים שלש מאות שלשים ושבעה ולהם משררים ומשררות מאתים׃"));
hebsuperobject.biblemap.put("b15_2_66", new hebsuperobject(15,2,66,"סוסיהם שבע מאות שלשים וששה פרדיהם מאתים ארבעים וחמשה׃"));
hebsuperobject.biblemap.put("b15_2_67", new hebsuperobject(15,2,67,"גמליהם ארבע מאות שלשים וחמשה חמרים ששת אלפים שבע מאות ועשרים׃"));
hebsuperobject.biblemap.put("b15_2_68", new hebsuperobject(15,2,68,"ומראשי האבות בבואם לבית יהוה אשר בירושלם התנדבו לבית האלהים להעמידו על מכונו׃"));
hebsuperobject.biblemap.put("b15_2_69", new hebsuperobject(15,2,69,"ככחם נתנו לאוצר המלאכה זהב דרכמונים שש רבאות ואלף וכסף מנים חמשת אלפים וכתנת כהנים מאה׃"));
hebsuperobject.biblemap.put("b15_2_70", new hebsuperobject(15,2,70,"וישבו הכהנים והלוים ומן העם והמשררים והשוערים והנתינים בעריהם וכל ישראל בעריהם׃"));
hebsuperobject.biblemap.put("b15_3_1", new hebsuperobject(15,3,1,"ויגע החדש השביעי ובני ישראל בערים ויאספו העם כאיש אחד אל ירושלם׃"));
hebsuperobject.biblemap.put("b15_3_2", new hebsuperobject(15,3,2,"ויקם ישוע בן יוצדק ואחיו הכהנים וזרבבל בן שאלתיאל ואחיו ויבנו את מזבח אלהי ישראל להעלות עליו עלות ככתוב בתורת משה איש האלהים׃"));
hebsuperobject.biblemap.put("b15_3_3", new hebsuperobject(15,3,3,"ויכינו המזבח על מכונתיו כי באימה עליהם מעמי הארצות ויעל עליו עלות ליהוה עלות לבקר ולערב׃"));
hebsuperobject.biblemap.put("b15_3_4", new hebsuperobject(15,3,4,"ויעשו את חג הסכות ככתוב ועלת יום ביום במספר כמשפט דבר יום ביומו׃"));
hebsuperobject.biblemap.put("b15_3_5", new hebsuperobject(15,3,5,"ואחריכן עלת תמיד ולחדשים ולכל מועדי יהוה המקדשים ולכל מתנדב נדבה ליהוה׃"));
hebsuperobject.biblemap.put("b15_3_6", new hebsuperobject(15,3,6,"מיום אחד לחדש השביעי החלו להעלות עלות ליהוה והיכל יהוה לא יסד׃"));
hebsuperobject.biblemap.put("b15_3_7", new hebsuperobject(15,3,7,"ויתנו כסף לחצבים ולחרשים ומאכל ומשתה ושמן לצדנים ולצרים להביא עצי ארזים מן הלבנון אל ים יפוא כרשיון כורש מלך פרס עליהם׃"));
hebsuperobject.biblemap.put("b15_3_8", new hebsuperobject(15,3,8,"ובשנה השנית לבואם אל בית האלהים לירושלם בחדש השני החלו זרבבל בן שאלתיאל וישוע בן יוצדק ושאר אחיהם הכהנים והלוים וכל הבאים מהשבי ירושלם ויעמידו את הלוים מבן עשרים שנה ומעלה לנצח על מלאכת בית יהוה׃"));
hebsuperobject.biblemap.put("b15_3_9", new hebsuperobject(15,3,9,"ויעמד ישוע בניו ואחיו קדמיאל ובניו בני יהודה כאחד לנצח על עשה המלאכה בבית האלהים בני חנדד בניהם ואחיהם הלוים׃"));
hebsuperobject.biblemap.put("b15_3_10", new hebsuperobject(15,3,10,"ויסדו הבנים את היכל יהוה ויעמידו הכהנים מלבשים בחצצרות והלוים בני אסף במצלתים להלל את יהוה על ידי דויד מלך ישראל׃"));
hebsuperobject.biblemap.put("b15_3_11", new hebsuperobject(15,3,11,"ויענו בהלל ובהודת ליהוה כי טוב כי לעולם חסדו על ישראל וכל העם הריעו תרועה גדולה בהלל ליהוה על הוסד בית יהוה׃"));
hebsuperobject.biblemap.put("b15_3_12", new hebsuperobject(15,3,12,"ורבים מהכהנים והלוים וראשי האבות הזקנים אשר ראו את הבית הראשון ביסדו זה הבית בעיניהם בכים בקול גדול ורבים בתרועה בשמחה להרים קול׃"));
hebsuperobject.biblemap.put("b15_3_13", new hebsuperobject(15,3,13,"ואין העם מכירים קול תרועת השמחה לקול בכי העם כי העם מריעים תרועה גדולה והקול נשמע עד למרחוק׃"));
hebsuperobject.biblemap.put("b15_4_1", new hebsuperobject(15,4,1,"וישמעו צרי יהודה ובנימן כי בני הגולה בונים היכל ליהוה אלהי ישראל׃"));
hebsuperobject.biblemap.put("b15_4_2", new hebsuperobject(15,4,2,"ויגשו אל זרבבל ואל ראשי האבות ויאמרו להם נבנה עמכם כי ככם נדרוש לאלהיכם ולא אנחנו זבחים מימי אסר חדן מלך אשור המעלה אתנו פה׃"));
hebsuperobject.biblemap.put("b15_4_3", new hebsuperobject(15,4,3,"ויאמר להם זרבבל וישוע ושאר ראשי האבות לישראל לא לכם ולנו לבנות בית לאלהינו כי אנחנו יחד נבנה ליהוה אלהי ישראל כאשר צונו המלך כורש מלך פרס׃"));
hebsuperobject.biblemap.put("b15_4_4", new hebsuperobject(15,4,4,"ויהי עם הארץ מרפים ידי עם יהודה ומבלהים אותם לבנות׃"));
hebsuperobject.biblemap.put("b15_4_5", new hebsuperobject(15,4,5,"וסכרים עליהם יועצים להפר עצתם כל ימי כורש מלך פרס ועד מלכות דריוש מלך פרס׃"));
hebsuperobject.biblemap.put("b15_4_6", new hebsuperobject(15,4,6,"ובמלכות אחשורוש בתחלת מלכותו כתבו שטנה על ישבי יהודה וירושלם׃"));
hebsuperobject.biblemap.put("b15_4_7", new hebsuperobject(15,4,7,"ובימי ארתחששתא כתב בשלם מתרדת טבאל ושאר כנותו על ארתחששתא מלך פרס וכתב הנשתון כתוב ארמית ומתרגם ארמית׃"));
hebsuperobject.biblemap.put("b15_4_8", new hebsuperobject(15,4,8,"רחום בעל טעם ושמשי ספרא כתבו אגרה חדה על ירושלם לארתחששתא מלכא כנמא׃"));
hebsuperobject.biblemap.put("b15_4_9", new hebsuperobject(15,4,9,"אדין רחום בעל טעם ושמשי ספרא ושאר כנותהון דיניא ואפרסתכיא טרפליא אפרסיא ארכוי בבליא שושנכיא דהוא עלמיא׃"));
hebsuperobject.biblemap.put("b15_4_10", new hebsuperobject(15,4,10,"ושאר אמיא די הגלי אסנפר רבא ויקירא והותב המו בקריה די שמרין ושאר עבר נהרה וכענת׃"));
hebsuperobject.biblemap.put("b15_4_11", new hebsuperobject(15,4,11,"דנה פרשגן אגרתא די שלחו עלוהי על ארתחששתא מלכא עבדיך אנש עבר נהרה וכענת׃"));
hebsuperobject.biblemap.put("b15_4_12", new hebsuperobject(15,4,12,"ידיע להוא למלכא די יהודיא די סלקו מן לותך עלינא אתו לירושלם קריתא מרדתא ובאישתא בנין ושורי אשכללו ואשיא יחיטו׃"));
hebsuperobject.biblemap.put("b15_4_13", new hebsuperobject(15,4,13,"כען ידיע להוא למלכא די הן קריתא דך תתבנא ושוריה ישתכללון מנדה בלו והלך לא ינתנון ואפתם מלכים תהנזק׃"));
hebsuperobject.biblemap.put("b15_4_14", new hebsuperobject(15,4,14,"כען כל קבל די מלח היכלא מלחנא וערות מלכא לא אריך לנא למחזא על דנה שלחנא והודענא למלכא׃"));
hebsuperobject.biblemap.put("b15_4_15", new hebsuperobject(15,4,15,"די יבקר בספר דכרניא די אבהתך ותהשכח בספר דכרניא ותנדע די קריתא דך קריא מרדא ומהנזקת מלכין ומדנן ואשתדור עבדין בגוה מן יומת עלמא על דנה קריתא דך החרבת׃"));
hebsuperobject.biblemap.put("b15_4_16", new hebsuperobject(15,4,16,"מהודעין אנחנה למלכא די הן קריתא דך תתבנא ושוריה ישתכללון לקבל דנה חלק בעבר נהרא לא איתי לך׃"));
hebsuperobject.biblemap.put("b15_4_17", new hebsuperobject(15,4,17,"פתגמא שלח מלכא על רחום בעל טעם ושמשי ספרא ושאר כנותהון די יתבין בשמרין ושאר עבר נהרה שלם וכעת׃"));
hebsuperobject.biblemap.put("b15_4_18", new hebsuperobject(15,4,18,"נשתונא די שלחתון עלינא מפרש קרי קדמי׃"));
hebsuperobject.biblemap.put("b15_4_19", new hebsuperobject(15,4,19,"ומני שים טעם ובקרו והשכחו די קריתא דך מן יומת עלמא על מלכין מתנשאה ומרד ואשתדור מתעבד בה׃"));
hebsuperobject.biblemap.put("b15_4_20", new hebsuperobject(15,4,20,"ומלכין תקיפין הוו על ירושלם ושליטין בכל עבר נהרה ומדה בלו והלך מתיהב להון׃"));
hebsuperobject.biblemap.put("b15_4_21", new hebsuperobject(15,4,21,"כען שימו טעם לבטלא גבריא אלך וקריתא דך לא תתבנא עד מני טעמא יתשם׃"));
hebsuperobject.biblemap.put("b15_4_22", new hebsuperobject(15,4,22,"וזהירין הוו שלו למעבד על דנה למה ישגא חבלא להנזקת מלכין׃"));
hebsuperobject.biblemap.put("b15_4_23", new hebsuperobject(15,4,23,"אדין מן די פרשגן נשתונא די ארתחששתא מלכא קרי קדם רחום ושמשי ספרא וכנותהון אזלו בבהילו לירושלם על יהודיא ובטלו המו באדרע וחיל׃"));
hebsuperobject.biblemap.put("b15_4_24", new hebsuperobject(15,4,24,"באדין בטלת עבידת בית אלהא די בירושלם והות בטלא עד שנת תרתין למלכות דריוש מלך פרס׃"));
hebsuperobject.biblemap.put("b15_5_1", new hebsuperobject(15,5,1,"והתנבי חגי נביאה וזכריה בר עדוא נביאיא על יהודיא די ביהוד ובירושלם בשם אלה ישראל עליהון׃"));
hebsuperobject.biblemap.put("b15_5_2", new hebsuperobject(15,5,2,"באדין קמו זרבבל בר שאלתיאל וישוע בר יוצדק ושריו למבנא בית אלהא די בירושלם ועמהון נביאיא די אלהא מסעדין להון׃"));
hebsuperobject.biblemap.put("b15_5_3", new hebsuperobject(15,5,3,"בה זמנא אתא עליהון תתני פחת עבר נהרה ושתר בוזני וכנותהון וכן אמרין להם מן שם לכם טעם ביתא דנה לבנא ואשרנא דנה לשכללה׃"));
hebsuperobject.biblemap.put("b15_5_4", new hebsuperobject(15,5,4,"אדין כנמא אמרנא להם מן אנון שמהת גבריא די דנה בנינא בנין׃"));
hebsuperobject.biblemap.put("b15_5_5", new hebsuperobject(15,5,5,"ועין אלההם הות על שבי יהודיא ולא בטלו המו עד טעמא לדריוש יהך ואדין יתיבון נשתונא על דנה׃"));
hebsuperobject.biblemap.put("b15_5_6", new hebsuperobject(15,5,6,"פרשגן אגרתא די שלח תתני פחת עבר נהרה ושתר בוזני וכנותה אפרסכיא די בעבר נהרה על דריוש מלכא׃"));
hebsuperobject.biblemap.put("b15_5_7", new hebsuperobject(15,5,7,"פתגמא שלחו עלוהי וכדנה כתיב בגוה לדריוש מלכא שלמא כלא׃"));
hebsuperobject.biblemap.put("b15_5_8", new hebsuperobject(15,5,8,"ידיע להוא למלכא די אזלנא ליהוד מדינתא לבית אלהא רבא והוא מתבנא אבן גלל ואע מתשם בכתליא ועבידתא דך אספרנא מתעבדא ומצלח בידהם׃"));
hebsuperobject.biblemap.put("b15_5_9", new hebsuperobject(15,5,9,"אדין שאלנא לשביא אלך כנמא אמרנא להם מן שם לכם טעם ביתא דנה למבניה ואשרנא דנה לשכללה׃"));
hebsuperobject.biblemap.put("b15_5_10", new hebsuperobject(15,5,10,"ואף שמהתהם שאלנא להם להודעותך די נכתב שם גבריא די בראשיהם׃"));
hebsuperobject.biblemap.put("b15_5_11", new hebsuperobject(15,5,11,"וכנמא פתגמא התיבונא לממר אנחנא המו עבדוהי די אלה שמיא וארעא ובנין ביתא די הוא בנה מקדמת דנה שנין שגיאן ומלך לישראל רב בנהי ושכללה׃"));
hebsuperobject.biblemap.put("b15_5_12", new hebsuperobject(15,5,12,"להן מן די הרגזו אבהתנא לאלה שמיא יהב המו ביד נבוכדנצר מלך בבל כסדיא וביתה דנה סתרה ועמה הגלי לבבל׃"));
hebsuperobject.biblemap.put("b15_5_13", new hebsuperobject(15,5,13,"ברם בשנת חדה לכורש מלכא די בבל כורש מלכא שם טעם בית אלהא דנה לבנא׃"));
hebsuperobject.biblemap.put("b15_5_14", new hebsuperobject(15,5,14,"ואף מאניא די בית אלהא די דהבה וכספא די נבוכדנצר הנפק מן היכלא די בירושלם והיבל המו להיכלא די בבל הנפק המו כורש מלכא מן היכלא די בבל ויהיבו לששבצר שמה די פחה שמה׃"));
hebsuperobject.biblemap.put("b15_5_15", new hebsuperobject(15,5,15,"ואמר לה אלה מאניא שא אזל אחת המו בהיכלא די בירושלם ובית אלהא יתבנא על אתרה׃"));
hebsuperobject.biblemap.put("b15_5_16", new hebsuperobject(15,5,16,"אדין ששבצר דך אתא יהב אשיא די בית אלהא די בירושלם ומן אדין ועד כען מתבנא ולא שלם׃"));
hebsuperobject.biblemap.put("b15_5_17", new hebsuperobject(15,5,17,"וכען הן על מלכא טב יתבקר בבית גנזיא די מלכא תמה די בבבל הן איתי די מן כורש מלכא שים טעם למבנא בית אלהא דך בירושלם ורעות מלכא על דנה ישלח עלינא׃"));
hebsuperobject.biblemap.put("b15_6_1", new hebsuperobject(15,6,1,"באדין דריוש מלכא שם טעם ובקרו בבית ספריא די גנזיא מהחתין תמה בבבל׃"));
hebsuperobject.biblemap.put("b15_6_2", new hebsuperobject(15,6,2,"והשתכח באחמתא בבירתא די במדי מדינתה מגלה חדה וכן כתיב בגוה דכרונה׃"));
hebsuperobject.biblemap.put("b15_6_3", new hebsuperobject(15,6,3,"בשנת חדה לכורש מלכא כורש מלכא שם טעם בית אלהא בירושלם ביתא יתבנא אתר די דבחין דבחין ואשוהי מסובלין רומה אמין שתין פתיה אמין שתין׃"));
hebsuperobject.biblemap.put("b15_6_4", new hebsuperobject(15,6,4,"נדבכין די אבן גלל תלתא ונדבך די אע חדת ונפקתא מן בית מלכא תתיהב׃"));
hebsuperobject.biblemap.put("b15_6_5", new hebsuperobject(15,6,5,"ואף מאני בית אלהא די דהבה וכספא די נבוכדנצר הנפק מן היכלא די בירושלם והיבל לבבל יהתיבון ויהך להיכלא די בירושלם לאתרה ותחת בבית אלהא׃"));
hebsuperobject.biblemap.put("b15_6_6", new hebsuperobject(15,6,6,"כען תתני פחת עבר נהרה שתר בוזני וכנותהון אפרסכיא די בעבר נהרה רחיקין הוו מן תמה׃"));
hebsuperobject.biblemap.put("b15_6_7", new hebsuperobject(15,6,7,"שבקו לעבידת בית אלהא דך פחת יהודיא ולשבי יהודיא בית אלהא דך יבנון על אתרה׃"));
hebsuperobject.biblemap.put("b15_6_8", new hebsuperobject(15,6,8,"ומני שים טעם למא די תעבדון עם שבי יהודיא אלך למבנא בית אלהא דך ומנכסי מלכא די מדת עבר נהרה אספרנא נפקתא תהוא מתיהבא לגבריא אלך די לא לבטלא׃"));
hebsuperobject.biblemap.put("b15_6_9", new hebsuperobject(15,6,9,"ומה חשחן ובני תורין ודכרין ואמרין לעלון לאלה שמיא חנטין מלח חמר ומשח כמאמר כהניא די בירושלם להוא מתיהב להם יום ביום די לא שלו׃"));
hebsuperobject.biblemap.put("b15_6_10", new hebsuperobject(15,6,10,"די להון מהקרבין ניחוחין לאלה שמיא ומצלין לחיי מלכא ובנוהי׃"));
hebsuperobject.biblemap.put("b15_6_11", new hebsuperobject(15,6,11,"ומני שים טעם די כל אנש די יהשנא פתגמא דנה יתנסח אע מן ביתה וזקיף יתמחא עלהי וביתה נולו יתעבד על דנה׃"));
hebsuperobject.biblemap.put("b15_6_12", new hebsuperobject(15,6,12,"ואלהא די שכן שמה תמה ימגר כל מלך ועם די ישלח ידה להשניה לחבלה בית אלהא דך די בירושלם אנה דריוש שמת טעם אספרנא יתעבד׃"));
hebsuperobject.biblemap.put("b15_6_13", new hebsuperobject(15,6,13,"אדין תתני פחת עבר נהרה שתר בוזני וכנותהון לקבל די שלח דריוש מלכא כנמא אספרנא עבדו׃"));
hebsuperobject.biblemap.put("b15_6_14", new hebsuperobject(15,6,14,"ושבי יהודיא בנין ומצלחין בנבואת חגי נביאה וזכריה בר עדוא ובנו ושכללו מן טעם אלה ישראל ומטעם כורש ודריוש וארתחששתא מלך פרס׃"));
hebsuperobject.biblemap.put("b15_6_15", new hebsuperobject(15,6,15,"ושיציא ביתה דנה עד יום תלתה לירח אדר די היא שנת שת למלכות דריוש מלכא׃"));
hebsuperobject.biblemap.put("b15_6_16", new hebsuperobject(15,6,16,"ועבדו בני ישראל כהניא ולויא ושאר בני גלותא חנכת בית אלהא דנה בחדוה׃"));
hebsuperobject.biblemap.put("b15_6_17", new hebsuperobject(15,6,17,"והקרבו לחנכת בית אלהא דנה תורין מאה דכרין מאתין אמרין ארבע מאה וצפירי עזין לחטיא על כל ישראל תרי עשר למנין שבטי ישראל׃"));
hebsuperobject.biblemap.put("b15_6_18", new hebsuperobject(15,6,18,"והקימו כהניא בפלגתהון ולויא במחלקתהון על עבידת אלהא די בירושלם ככתב ספר משה׃"));
hebsuperobject.biblemap.put("b15_6_19", new hebsuperobject(15,6,19,"ויעשו בני הגולה את הפסח בארבעה עשר לחדש הראשון׃"));
hebsuperobject.biblemap.put("b15_6_20", new hebsuperobject(15,6,20,"כי הטהרו הכהנים והלוים כאחד כלם טהורים וישחטו הפסח לכל בני הגולה ולאחיהם הכהנים ולהם׃"));
hebsuperobject.biblemap.put("b15_6_21", new hebsuperobject(15,6,21,"ויאכלו בני ישראל השבים מהגולה וכל הנבדל מטמאת גוי הארץ אלהם לדרש ליהוה אלהי ישראל׃"));
hebsuperobject.biblemap.put("b15_6_22", new hebsuperobject(15,6,22,"ויעשו חג מצות שבעת ימים בשמחה כי שמחם יהוה והסב לב מלך אשור עליהם לחזק ידיהם במלאכת בית האלהים אלהי ישראל׃"));
hebsuperobject.biblemap.put("b15_7_1", new hebsuperobject(15,7,1,"ואחר הדברים האלה במלכות ארתחשסתא מלך פרס עזרא בן שריה בן עזריה בן חלקיה׃"));
hebsuperobject.biblemap.put("b15_7_2", new hebsuperobject(15,7,2,"בן שלום בן צדוק בן אחיטוב׃"));
hebsuperobject.biblemap.put("b15_7_3", new hebsuperobject(15,7,3,"בן אמריה בן עזריה בן מריות׃"));
hebsuperobject.biblemap.put("b15_7_4", new hebsuperobject(15,7,4,"בן זרחיה בן עזי בן בקי׃"));
hebsuperobject.biblemap.put("b15_7_5", new hebsuperobject(15,7,5,"בן אבישוע בן פינחס בן אלעזר בן אהרן הכהן הראש׃"));
hebsuperobject.biblemap.put("b15_7_6", new hebsuperobject(15,7,6,"הוא עזרא עלה מבבל והוא ספר מהיר בתורת משה אשר נתן יהוה אלהי ישראל ויתן לו המלך כיד יהוה אלהיו עליו כל בקשתו׃"));
hebsuperobject.biblemap.put("b15_7_7", new hebsuperobject(15,7,7,"ויעלו מבני ישראל ומן הכהנים והלוים והמשררים והשערים והנתינים אל ירושלם בשנת שבע לארתחשסתא המלך׃"));
hebsuperobject.biblemap.put("b15_7_8", new hebsuperobject(15,7,8,"ויבא ירושלם בחדש החמישי היא שנת השביעית למלך׃"));
hebsuperobject.biblemap.put("b15_7_9", new hebsuperobject(15,7,9,"כי באחד לחדש הראשון הוא יסד המעלה מבבל ובאחד לחדש החמישי בא אל ירושלם כיד אלהיו הטובה עליו׃"));
hebsuperobject.biblemap.put("b15_7_10", new hebsuperobject(15,7,10,"כי עזרא הכין לבבו לדרוש את תורת יהוה ולעשת וללמד בישראל חק ומשפט׃"));
hebsuperobject.biblemap.put("b15_7_11", new hebsuperobject(15,7,11,"וזה פרשגן הנשתון אשר נתן המלך ארתחשסתא לעזרא הכהן הספר ספר דברי מצות יהוה וחקיו על ישראל׃"));
hebsuperobject.biblemap.put("b15_7_12", new hebsuperobject(15,7,12,"ארתחשסתא מלך מלכיא לעזרא כהנא ספר דתא די אלה שמיא גמיר וכענת׃"));
hebsuperobject.biblemap.put("b15_7_13", new hebsuperobject(15,7,13,"מני שים טעם די כל מתנדב במלכותי מן עמה ישראל וכהנוהי ולויא למהך לירושלם עמך יהך׃"));
hebsuperobject.biblemap.put("b15_7_14", new hebsuperobject(15,7,14,"כל קבל די מן קדם מלכא ושבעת יעטהי שליח לבקרא על יהוד ולירושלם בדת אלהך די בידך׃"));
hebsuperobject.biblemap.put("b15_7_15", new hebsuperobject(15,7,15,"ולהיבלה כסף ודהב די מלכא ויעטוהי התנדבו לאלה ישראל די בירושלם משכנה׃"));
hebsuperobject.biblemap.put("b15_7_16", new hebsuperobject(15,7,16,"וכל כסף ודהב די תהשכח בכל מדינת בבל עם התנדבות עמא וכהניא מתנדבין לבית אלההם די בירושלם׃"));
hebsuperobject.biblemap.put("b15_7_17", new hebsuperobject(15,7,17,"כל קבל דנה אספרנא תקנא בכספא דנה תורין דכרין אמרין ומנחתהון ונסכיהון ותקרב המו על מדבחה די בית אלהכם די בירושלם׃"));
hebsuperobject.biblemap.put("b15_7_18", new hebsuperobject(15,7,18,"ומה די עליך ועל אחיך ייטב בשאר כספא ודהבה למעבד כרעות אלהכם תעבדון׃"));
hebsuperobject.biblemap.put("b15_7_19", new hebsuperobject(15,7,19,"ומאניא די מתיהבין לך לפלחן בית אלהך השלם קדם אלה ירושלם׃"));
hebsuperobject.biblemap.put("b15_7_20", new hebsuperobject(15,7,20,"ושאר חשחות בית אלהך די יפל לך למנתן תנתן מן בית גנזי מלכא׃"));
hebsuperobject.biblemap.put("b15_7_21", new hebsuperobject(15,7,21,"ומני אנה ארתחשסתא מלכא שים טעם לכל גזבריא די בעבר נהרה די כל די ישאלנכון עזרא כהנה ספר דתא די אלה שמיא אספרנא יתעבד׃"));
hebsuperobject.biblemap.put("b15_7_22", new hebsuperobject(15,7,22,"עד כסף ככרין מאה ועד חנטין כרין מאה ועד חמר בתין מאה ועד בתין משח מאה ומלח די לא כתב׃"));
hebsuperobject.biblemap.put("b15_7_23", new hebsuperobject(15,7,23,"כל די מן טעם אלה שמיא יתעבד אדרזדא לבית אלה שמיא די למה להוא קצף על מלכות מלכא ובנוהי׃"));
hebsuperobject.biblemap.put("b15_7_24", new hebsuperobject(15,7,24,"ולכם מהודעין די כל כהניא ולויא זמריא תרעיא נתיניא ופלחי בית אלהא דנה מנדה בלו והלך לא שליט למרמא עליהם׃"));
hebsuperobject.biblemap.put("b15_7_25", new hebsuperobject(15,7,25,"ואנת עזרא כחכמת אלהך די בידך מני שפטין ודינין די להון דאנין לכל עמה די בעבר נהרה לכל ידעי דתי אלהך ודי לא ידע תהודעון׃"));
hebsuperobject.biblemap.put("b15_7_26", new hebsuperobject(15,7,26,"וכל די לא להוא עבד דתא די אלהך ודתא די מלכא אספרנא דינה להוא מתעבד מנה הן למות הן לשרשו הן לענש נכסין ולאסורין׃"));
hebsuperobject.biblemap.put("b15_7_27", new hebsuperobject(15,7,27,"ברוך יהוה אלהי אבותינו אשר נתן כזאת בלב המלך לפאר את בית יהוה אשר בירושלם׃"));
hebsuperobject.biblemap.put("b15_7_28", new hebsuperobject(15,7,28,"ועלי הטה חסד לפני המלך ויועציו ולכל שרי המלך הגברים ואני התחזקתי כיד יהוה אלהי עלי ואקבצה מישראל ראשים לעלות עמי׃"));
hebsuperobject.biblemap.put("b15_8_1", new hebsuperobject(15,8,1,"ואלה ראשי אבתיהם והתיחשם העלים עמי במלכות ארתחשסתא המלך מבבל׃"));
hebsuperobject.biblemap.put("b15_8_2", new hebsuperobject(15,8,2,"מבני פינחס גרשם מבני איתמר דניאל מבני דויד חטוש׃"));
hebsuperobject.biblemap.put("b15_8_3", new hebsuperobject(15,8,3,"מבני שכניה מבני פרעש זכריה ועמו התיחש לזכרים מאה וחמשים׃"));
hebsuperobject.biblemap.put("b15_8_4", new hebsuperobject(15,8,4,"מבני פחת מואב אליהועיני בן זרחיה ועמו מאתים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_5", new hebsuperobject(15,8,5,"מבני שכניה בן יחזיאל ועמו שלש מאות הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_6", new hebsuperobject(15,8,6,"ומבני עדין עבד בן יונתן ועמו חמשים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_7", new hebsuperobject(15,8,7,"ומבני עילם ישעיה בן עתליה ועמו שבעים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_8", new hebsuperobject(15,8,8,"ומבני שפטיה זבדיה בן מיכאל ועמו שמנים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_9", new hebsuperobject(15,8,9,"מבני יואב עבדיה בן יחיאל ועמו מאתים ושמנה עשר הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_10", new hebsuperobject(15,8,10,"ומבני שלומית בן יוספיה ועמו מאה וששים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_11", new hebsuperobject(15,8,11,"ומבני בבי זכריה בן בבי ועמו עשרים ושמנה הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_12", new hebsuperobject(15,8,12,"ומבני עזגד יוחנן בן הקטן ועמו מאה ועשרה הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_13", new hebsuperobject(15,8,13,"ומבני אדניקם אחרנים ואלה שמותם אליפלט יעיאל ושמעיה ועמהם ששים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_14", new hebsuperobject(15,8,14,"ומבני בגוי עותי וזבוד ועמו שבעים הזכרים׃"));
hebsuperobject.biblemap.put("b15_8_15", new hebsuperobject(15,8,15,"ואקבצם אל הנהר הבא אל אהוא ונחנה שם ימים שלשה ואבינה בעם ובכהנים ומבני לוי לא מצאתי שם׃"));
hebsuperobject.biblemap.put("b15_8_16", new hebsuperobject(15,8,16,"ואשלחה לאליעזר לאריאל לשמעיה ולאלנתן וליריב ולאלנתן ולנתן ולזכריה ולמשלם ראשים וליויריב ולאלנתן מבינים׃"));
hebsuperobject.biblemap.put("b15_8_17", new hebsuperobject(15,8,17,"ואוצאה אותם על אדו הראש בכספיא המקום ואשימה בפיהם דברים לדבר אל אדו אחיו הנתונים בכספיא המקום להביא לנו משרתים לבית אלהינו׃"));
hebsuperobject.biblemap.put("b15_8_18", new hebsuperobject(15,8,18,"ויביאו לנו כיד אלהינו הטובה עלינו איש שכל מבני מחלי בן לוי בן ישראל ושרביה ובניו ואחיו שמנה עשר׃"));
hebsuperobject.biblemap.put("b15_8_19", new hebsuperobject(15,8,19,"ואת חשביה ואתו ישעיה מבני מררי אחיו ובניהם עשרים׃"));
hebsuperobject.biblemap.put("b15_8_20", new hebsuperobject(15,8,20,"ומן הנתינים שנתן דויד והשרים לעבדת הלוים נתינים מאתים ועשרים כלם נקבו בשמות׃"));
hebsuperobject.biblemap.put("b15_8_21", new hebsuperobject(15,8,21,"ואקרא שם צום על הנהר אהוא להתענות לפני אלהינו לבקש ממנו דרך ישרה לנו ולטפנו ולכל רכושנו׃"));
hebsuperobject.biblemap.put("b15_8_22", new hebsuperobject(15,8,22,"כי בשתי לשאול מן המלך חיל ופרשים לעזרנו מאויב בדרך כי אמרנו למלך לאמר יד אלהינו על כל מבקשיו לטובה ועזו ואפו על כל עזביו׃"));
hebsuperobject.biblemap.put("b15_8_23", new hebsuperobject(15,8,23,"ונצומה ונבקשה מאלהינו על זאת ויעתר לנו׃"));
hebsuperobject.biblemap.put("b15_8_24", new hebsuperobject(15,8,24,"ואבדילה משרי הכהנים שנים עשר לשרביה חשביה ועמהם מאחיהם עשרה׃"));
hebsuperobject.biblemap.put("b15_8_25", new hebsuperobject(15,8,25,"ואשקולה להם את הכסף ואת הזהב ואת הכלים תרומת בית אלהינו ההרימו המלך ויעציו ושריו וכל ישראל הנמצאים׃"));
hebsuperobject.biblemap.put("b15_8_26", new hebsuperobject(15,8,26,"ואשקלה על ידם כסף ככרים שש מאות וחמשים וכלי כסף מאה לככרים זהב מאה ככר׃"));
hebsuperobject.biblemap.put("b15_8_27", new hebsuperobject(15,8,27,"וכפרי זהב עשרים לאדרכנים אלף וכלי נחשת מצהב טובה שנים חמודת כזהב׃"));
hebsuperobject.biblemap.put("b15_8_28", new hebsuperobject(15,8,28,"ואמרה אלהם אתם קדש ליהוה והכלים קדש והכסף והזהב נדבה ליהוה אלהי אבתיכם׃"));
hebsuperobject.biblemap.put("b15_8_29", new hebsuperobject(15,8,29,"שקדו ושמרו עד תשקלו לפני שרי הכהנים והלוים ושרי האבות לישראל בירושלם הלשכות בית יהוה׃"));
hebsuperobject.biblemap.put("b15_8_30", new hebsuperobject(15,8,30,"וקבלו הכהנים והלוים משקל הכסף והזהב והכלים להביא לירושלם לבית אלהינו׃"));
hebsuperobject.biblemap.put("b15_8_31", new hebsuperobject(15,8,31,"ונסעה מנהר אהוא בשנים עשר לחדש הראשון ללכת ירושלם ויד אלהינו היתה עלינו ויצילנו מכף אויב ואורב על הדרך׃"));
hebsuperobject.biblemap.put("b15_8_32", new hebsuperobject(15,8,32,"ונבוא ירושלם ונשב שם ימים שלשה׃"));
hebsuperobject.biblemap.put("b15_8_33", new hebsuperobject(15,8,33,"וביום הרביעי נשקל הכסף והזהב והכלים בבית אלהינו על יד מרמות בן אוריה הכהן ועמו אלעזר בן פינחס ועמהם יוזבד בן ישוע ונועדיה בן בנוי הלוים׃"));
hebsuperobject.biblemap.put("b15_8_34", new hebsuperobject(15,8,34,"במספר במשקל לכל ויכתב כל המשקל בעת ההיא׃"));
hebsuperobject.biblemap.put("b15_8_35", new hebsuperobject(15,8,35,"הבאים מהשבי בני הגולה הקריבו עלות לאלהי ישראל פרים שנים עשר על כל ישראל אילים תשעים וששה כבשים שבעים ושבעה צפירי חטאת שנים עשר הכל עולה ליהוה׃"));
hebsuperobject.biblemap.put("b15_8_36", new hebsuperobject(15,8,36,"ויתנו את דתי המלך לאחשדרפני המלך ופחוות עבר הנהר ונשאו את העם ואת בית האלהים׃"));
hebsuperobject.biblemap.put("b15_9_1", new hebsuperobject(15,9,1,"וככלות אלה נגשו אלי השרים לאמר לא נבדלו העם ישראל והכהנים והלוים מעמי הארצות כתועבתיהם לכנעני החתי הפרזי היבוסי העמני המאבי המצרי והאמרי׃"));
hebsuperobject.biblemap.put("b15_9_2", new hebsuperobject(15,9,2,"כי נשאו מבנתיהם להם ולבניהם והתערבו זרע הקדש בעמי הארצות ויד השרים והסגנים היתה במעל הזה ראשונה׃"));
hebsuperobject.biblemap.put("b15_9_3", new hebsuperobject(15,9,3,"וכשמעי את הדבר הזה קרעתי את בגדי ומעילי ואמרטה משער ראשי וזקני ואשבה משומם׃"));
hebsuperobject.biblemap.put("b15_9_4", new hebsuperobject(15,9,4,"ואלי יאספו כל חרד בדברי אלהי ישראל על מעל הגולה ואני ישב משומם עד למנחת הערב׃"));
hebsuperobject.biblemap.put("b15_9_5", new hebsuperobject(15,9,5,"ובמנחת הערב קמתי מתעניתי ובקרעי בגדי ומעילי ואכרעה על ברכי ואפרשה כפי אל יהוה אלהי׃"));
hebsuperobject.biblemap.put("b15_9_6", new hebsuperobject(15,9,6,"ואמרה אלהי בשתי ונכלמתי להרים אלהי פני אליך כי עונתינו רבו למעלה ראש ואשמתנו גדלה עד לשמים׃"));
hebsuperobject.biblemap.put("b15_9_7", new hebsuperobject(15,9,7,"מימי אבתינו אנחנו באשמה גדלה עד היום הזה ובעונתינו נתנו אנחנו מלכינו כהנינו ביד מלכי הארצות בחרב בשבי ובבזה ובבשת פנים כהיום הזה׃"));
hebsuperobject.biblemap.put("b15_9_8", new hebsuperobject(15,9,8,"ועתה כמעט רגע היתה תחנה מאת יהוה אלהינו להשאיר לנו פליטה ולתת לנו יתד במקום קדשו להאיר עינינו אלהינו ולתתנו מחיה מעט בעבדתנו׃"));
hebsuperobject.biblemap.put("b15_9_9", new hebsuperobject(15,9,9,"כי עבדים אנחנו ובעבדתנו לא עזבנו אלהינו ויט עלינו חסד לפני מלכי פרס לתת לנו מחיה לרומם את בית אלהינו ולהעמיד את חרבתיו ולתת לנו גדר ביהודה ובירושלם׃"));
hebsuperobject.biblemap.put("b15_9_10", new hebsuperobject(15,9,10,"ועתה מה נאמר אלהינו אחרי זאת כי עזבנו מצותיך׃"));
hebsuperobject.biblemap.put("b15_9_11", new hebsuperobject(15,9,11,"אשר צוית ביד עבדיך הנביאים לאמר הארץ אשר אתם באים לרשתה ארץ נדה היא בנדת עמי הארצות בתועבתיהם אשר מלאוה מפה אל פה בטמאתם׃"));
hebsuperobject.biblemap.put("b15_9_12", new hebsuperobject(15,9,12,"ועתה בנותיכם אל תתנו לבניהם ובנתיהם אל תשאו לבניכם ולא תדרשו שלמם וטובתם עד עולם למען תחזקו ואכלתם את טוב הארץ והורשתם לבניכם עד עולם׃"));
hebsuperobject.biblemap.put("b15_9_13", new hebsuperobject(15,9,13,"ואחרי כל הבא עלינו במעשינו הרעים ובאשמתנו הגדלה כי אתה אלהינו חשכת למטה מעוננו ונתתה לנו פליטה כזאת׃"));
hebsuperobject.biblemap.put("b15_9_14", new hebsuperobject(15,9,14,"הנשוב להפר מצותיך ולהתחתן בעמי התעבות האלה הלוא תאנף בנו עד כלה לאין שארית ופליטה׃"));
hebsuperobject.biblemap.put("b15_9_15", new hebsuperobject(15,9,15,"יהוה אלהי ישראל צדיק אתה כי נשארנו פליטה כהיום הזה הננו לפניך באשמתינו כי אין לעמוד לפניך על זאת׃"));
hebsuperobject.biblemap.put("b15_10_1", new hebsuperobject(15,10,1,"וכהתפלל עזרא וכהתודתו בכה ומתנפל לפני בית האלהים נקבצו אליו מישראל קהל רב מאד אנשים ונשים וילדים כי בכו העם הרבה בכה׃"));
hebsuperobject.biblemap.put("b15_10_2", new hebsuperobject(15,10,2,"ויען שכניה בן יחיאל מבני עולם ויאמר לעזרא אנחנו מעלנו באלהינו ונשב נשים נכריות מעמי הארץ ועתה יש מקוה לישראל על זאת׃"));
hebsuperobject.biblemap.put("b15_10_3", new hebsuperobject(15,10,3,"ועתה נכרת ברית לאלהינו להוציא כל נשים והנולד מהם בעצת אדני והחרדים במצות אלהינו וכתורה יעשה׃"));
hebsuperobject.biblemap.put("b15_10_4", new hebsuperobject(15,10,4,"קום כי עליך הדבר ואנחנו עמך חזק ועשה׃"));
hebsuperobject.biblemap.put("b15_10_5", new hebsuperobject(15,10,5,"ויקם עזרא וישבע את שרי הכהנים הלוים וכל ישראל לעשות כדבר הזה וישבעו׃"));
hebsuperobject.biblemap.put("b15_10_6", new hebsuperobject(15,10,6,"ויקם עזרא מלפני בית האלהים וילך אל לשכת יהוחנן בן אלישיב וילך שם לחם לא אכל ומים לא שתה כי מתאבל על מעל הגולה׃"));
hebsuperobject.biblemap.put("b15_10_7", new hebsuperobject(15,10,7,"ויעבירו קול ביהודה וירושלם לכל בני הגולה להקבץ ירושלם׃"));
hebsuperobject.biblemap.put("b15_10_8", new hebsuperobject(15,10,8,"וכל אשר לא יבוא לשלשת הימים כעצת השרים והזקנים יחרם כל רכושו והוא יבדל מקהל הגולה׃"));
hebsuperobject.biblemap.put("b15_10_9", new hebsuperobject(15,10,9,"ויקבצו כל אנשי יהודה ובנימן ירושלם לשלשת הימים הוא חדש התשיעי בעשרים בחדש וישבו כל העם ברחוב בית האלהים מרעידים על הדבר ומהגשמים׃"));
hebsuperobject.biblemap.put("b15_10_10", new hebsuperobject(15,10,10,"ויקם עזרא הכהן ויאמר אלהם אתם מעלתם ותשיבו נשים נכריות להוסיף על אשמת ישראל׃"));
hebsuperobject.biblemap.put("b15_10_11", new hebsuperobject(15,10,11,"ועתה תנו תודה ליהוה אלהי אבתיכם ועשו רצונו והבדלו מעמי הארץ ומן הנשים הנכריות׃"));
hebsuperobject.biblemap.put("b15_10_12", new hebsuperobject(15,10,12,"ויענו כל הקהל ויאמרו קול גדול כן כדבריך עלינו לעשות׃"));
hebsuperobject.biblemap.put("b15_10_13", new hebsuperobject(15,10,13,"אבל העם רב והעת גשמים ואין כח לעמוד בחוץ והמלאכה לא ליום אחד ולא לשנים כי הרבינו לפשע בדבר הזה׃"));
hebsuperobject.biblemap.put("b15_10_14", new hebsuperobject(15,10,14,"יעמדו נא שרינו לכל הקהל וכל אשר בערינו ההשיב נשים נכריות יבא לעתים מזמנים ועמהם זקני עיר ועיר ושפטיה עד להשיב חרון אף אלהינו ממנו עד לדבר הזה׃"));
hebsuperobject.biblemap.put("b15_10_15", new hebsuperobject(15,10,15,"אך יונתן בן עשהאל ויחזיה בן תקוה עמדו על זאת ומשלם ושבתי הלוי עזרם׃"));
hebsuperobject.biblemap.put("b15_10_16", new hebsuperobject(15,10,16,"ויעשו כן בני הגולה ויבדלו עזרא הכהן אנשים ראשי האבות לבית אבתם וכלם בשמות וישבו ביום אחד לחדש העשירי לדריוש הדבר׃"));
hebsuperobject.biblemap.put("b15_10_17", new hebsuperobject(15,10,17,"ויכלו בכל אנשים ההשיבו נשים נכריות עד יום אחד לחדש הראשון׃"));
hebsuperobject.biblemap.put("b15_10_18", new hebsuperobject(15,10,18,"וימצא מבני הכהנים אשר השיבו נשים נכריות מבני ישוע בן יוצדק ואחיו מעשיה ואליעזר ויריב וגדליה׃"));
hebsuperobject.biblemap.put("b15_10_19", new hebsuperobject(15,10,19,"ויתנו ידם להוציא נשיהם ואשמים איל צאן על אשמתם׃"));
hebsuperobject.biblemap.put("b15_10_20", new hebsuperobject(15,10,20,"ומבני אמר חנני וזבדיה׃"));
hebsuperobject.biblemap.put("b15_10_21", new hebsuperobject(15,10,21,"ומבני חרם מעשיה ואליה ושמעיה ויחיאל ועזיה׃"));
hebsuperobject.biblemap.put("b15_10_22", new hebsuperobject(15,10,22,"ומבני פשחור אליועיני מעשיה ישמעאל נתנאל יוזבד ואלעשה׃"));
hebsuperobject.biblemap.put("b15_10_23", new hebsuperobject(15,10,23,"ומן הלוים יוזבד ושמעי וקליה הוא קליטא פתחיה יהודה ואליעזר׃"));
hebsuperobject.biblemap.put("b15_10_24", new hebsuperobject(15,10,24,"ומן המשררים אלישיב ומן השערים שלם וטלם ואורי׃"));
hebsuperobject.biblemap.put("b15_10_25", new hebsuperobject(15,10,25,"ומישראל מבני פרעש רמיה ויזיה ומלכיה ומימן ואלעזר ומלכיה ובניה׃"));
hebsuperobject.biblemap.put("b15_10_26", new hebsuperobject(15,10,26,"ומבני עילם מתניה זכריה ויחיאל ועבדי וירמות ואליה׃"));
hebsuperobject.biblemap.put("b15_10_27", new hebsuperobject(15,10,27,"ומבני זתוא אליועני אלישיב מתניה וירמות וזבד ועזיזא׃"));
hebsuperobject.biblemap.put("b15_10_28", new hebsuperobject(15,10,28,"ומבני בבי יהוחנן חנניה זבי עתלי׃"));
hebsuperobject.biblemap.put("b15_10_29", new hebsuperobject(15,10,29,"ומבני בני משלם מלוך ועדיה ישוב ושאל ירמות׃"));
hebsuperobject.biblemap.put("b15_10_30", new hebsuperobject(15,10,30,"ומבני פחת מואב עדנא וכלל בניה מעשיה מתניה בצלאל ובנוי ומנשה׃"));
hebsuperobject.biblemap.put("b15_10_31", new hebsuperobject(15,10,31,"ובני חרם אליעזר ישיה מלכיה שמעיה שמעון׃"));
hebsuperobject.biblemap.put("b15_10_32", new hebsuperobject(15,10,32,"בנימן מלוך שמריה׃"));
hebsuperobject.biblemap.put("b15_10_33", new hebsuperobject(15,10,33,"מבני חשם מתני מתתה זבד אליפלט ירמי מנשה שמעי׃"));
hebsuperobject.biblemap.put("b15_10_34", new hebsuperobject(15,10,34,"מבני בני מעדי עמרם ואואל׃"));
hebsuperobject.biblemap.put("b15_10_35", new hebsuperobject(15,10,35,"בניה בדיה כלוהי׃"));
hebsuperobject.biblemap.put("b15_10_36", new hebsuperobject(15,10,36,"וניה מרמות אלישיב׃"));
hebsuperobject.biblemap.put("b15_10_37", new hebsuperobject(15,10,37,"מתניה מתני ויעשו׃"));
hebsuperobject.biblemap.put("b15_10_38", new hebsuperobject(15,10,38,"ובני ובנוי שמעי׃"));
hebsuperobject.biblemap.put("b15_10_39", new hebsuperobject(15,10,39,"ושלמיה ונתן ועדיה׃"));
hebsuperobject.biblemap.put("b15_10_40", new hebsuperobject(15,10,40,"מכנדבי ששי שרי׃"));
hebsuperobject.biblemap.put("b15_10_41", new hebsuperobject(15,10,41,"עזראל ושלמיהו שמריה׃"));
hebsuperobject.biblemap.put("b15_10_42", new hebsuperobject(15,10,42,"שלום אמריה יוסף׃"));
hebsuperobject.biblemap.put("b15_10_43", new hebsuperobject(15,10,43,"מבני נבו יעיאל מתתיה זבד זבינא ידו ויואל בניה׃"));
hebsuperobject.biblemap.put("b15_10_44", new hebsuperobject(15,10,44,"כל אלה נשאי נשים נכריות ויש מהם נשים וישימו בנים׃"));

}

}