package heb.bible;

public class hebbible49 {

public hebbible49() {

putmapbible49();

}

private void putmapbible49() {

hebsuperobject.biblemap.put("b49_1_1", new hebsuperobject(49,1,1,"פולוס שליח ישוע המשיח ברצון אלהים אל הקדשים הנמצאים באפסוס ומאמינים במשיח ישוע׃"));
hebsuperobject.biblemap.put("b49_1_2", new hebsuperobject(49,1,2,"חסד לכם ושלום מאת האלהים אבינו ואדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b49_1_3", new hebsuperobject(49,1,3,"ברוך הוא האלהים ואבי אדנינו ישוע המשיח אשר ברכנו בכל ברכת רוח במרומים במשיח׃"));
hebsuperobject.biblemap.put("b49_1_4", new hebsuperobject(49,1,4,"כאשר בחר אתנו בו לפני מוסדות תבל להיות קדשים ותמימים לפניו באהבה׃"));
hebsuperobject.biblemap.put("b49_1_5", new hebsuperobject(49,1,5,"יעדנו לו לבנים על ידי ישוע המשיח כחפץ רצונו׃"));
hebsuperobject.biblemap.put("b49_1_6", new hebsuperobject(49,1,6,"לתהלת כבוד חסדו אשר נתן אתנו בידידו׃"));
hebsuperobject.biblemap.put("b49_1_7", new hebsuperobject(49,1,7,"אשר בו לנו הפדיום בדמו וסליחת הפשעים כרב חסדו׃"));
hebsuperobject.biblemap.put("b49_1_8", new hebsuperobject(49,1,8,"אשר השפיעו עלינו בכל חכמה והשכל׃"));
hebsuperobject.biblemap.put("b49_1_9", new hebsuperobject(49,1,9,"והודיענו את סוד רצונו כעצתו היעוצה בו׃"));
hebsuperobject.biblemap.put("b49_1_10", new hebsuperobject(49,1,10,"על דבר הנהגתו במלאת העתים לקבץ את הכל תחת המשיח הן מה שבשמים הן מה שבארץ׃"));
hebsuperobject.biblemap.put("b49_1_11", new hebsuperobject(49,1,11,"אשר גם לקחנו בו נחלתנו אנחנו המיעדים לה מאז במחשבת פעל הכל כעצת חפצו׃"));
hebsuperobject.biblemap.put("b49_1_12", new hebsuperobject(49,1,12,"להיותנו לתהלת כבודו אנחנו אשר יחלנו אל המשיח מאז׃"));
hebsuperobject.biblemap.put("b49_1_13", new hebsuperobject(49,1,13,"ואשר גם אתם נטועים בו אחרי שמעכם דבר האמת את בשורת ישועתכם ואשר בו כשהאמנתם גם נחתמתם ברוח ההבטחה רוח הקדש׃"));
hebsuperobject.biblemap.put("b49_1_14", new hebsuperobject(49,1,14,"כי זה ערבון ירשתנו לפדות לו עם סגלה לתהלת כבודו׃"));
hebsuperobject.biblemap.put("b49_1_15", new hebsuperobject(49,1,15,"בעבור זאת גם אנכי אחרי שמעי אמונתכם באדנינו ישוע והאהבה אשר אהבתם את כל הקדשים׃"));
hebsuperobject.biblemap.put("b49_1_16", new hebsuperobject(49,1,16,"לא אחדל מהודות בעבורכם בהזכירי אתכם בתפלתי׃"));
hebsuperobject.biblemap.put("b49_1_17", new hebsuperobject(49,1,17,"כי יתן לכם אלהי אדנינו ישוע המשיח אבי הכבוד את רוח החכמה והחזון לדעת אתו׃"));
hebsuperobject.biblemap.put("b49_1_18", new hebsuperobject(49,1,18,"ויאר עיני לבבכם למען תדעו אי זו היא תוחלת קריאתו ואי זה הוא עשר כבוד נחלתו בקדשים׃"));
hebsuperobject.biblemap.put("b49_1_19", new hebsuperobject(49,1,19,"ואי זה הוא יתרון גדלת גבורתו בנו המאמינים כפי פעלת עצת כחו׃"));
hebsuperobject.biblemap.put("b49_1_20", new hebsuperobject(49,1,20,"אשר פעל במשיח בהעיר אתו מן המתים ויושיבנו לימינו במרומים׃"));
hebsuperobject.biblemap.put("b49_1_21", new hebsuperobject(49,1,21,"ממעל לכל שררה ושלטן וגבורה וממשלה וכל הנקרא בשם לא לבד בעולם הזה כי אם גם בעולם הבא׃"));
hebsuperobject.biblemap.put("b49_1_22", new hebsuperobject(49,1,22,"וישת כל תחת רגליו ויתן אתו לראש על הכל אל העדה׃"));
hebsuperobject.biblemap.put("b49_1_23", new hebsuperobject(49,1,23,"אשר היא גופו מלוא הממלא את הכל בכל׃"));
hebsuperobject.biblemap.put("b49_2_1", new hebsuperobject(49,2,1,"גם אתכם המתים לפנים בפשעיכם וחטאתיכם׃"));
hebsuperobject.biblemap.put("b49_2_2", new hebsuperobject(49,2,2,"אשר התהלכתם בהם לפי דור העולם הזה כרצון שר ממשלת האויר והוא הרוח הפעל כעת בבני המרי׃"));
hebsuperobject.biblemap.put("b49_2_3", new hebsuperobject(49,2,3,"וגם אנחנו כלנו בתוכם הלכנו לפנים בתאות הבשר לעשות חפצי בשרנו ומחשבותינו ונהי אך בני רגז בטבענו כאשר בני אדם׃"));
hebsuperobject.biblemap.put("b49_2_4", new hebsuperobject(49,2,4,"אבל האלהים המלא רחמים ברב אהבתו אשר אהב אתנו׃"));
hebsuperobject.biblemap.put("b49_2_5", new hebsuperobject(49,2,5,"אחרי היותנו מתים בפשעים החינו עם המשיח בחסד נושעתם׃"));
hebsuperobject.biblemap.put("b49_2_6", new hebsuperobject(49,2,6,"ויעירנו אתו אף הושיבנו במרומים במשיח ישוע׃"));
hebsuperobject.biblemap.put("b49_2_7", new hebsuperobject(49,2,7,"להראות בדרות הבאים את גדלת עשר חסדו בטובתו עלינו במשיח ישוע׃"));
hebsuperobject.biblemap.put("b49_2_8", new hebsuperobject(49,2,8,"כי בחסד נושעתם על ידי האמונה ולא מידכם היתה זאת כי מתת אלהים היא׃"));
hebsuperobject.biblemap.put("b49_2_9", new hebsuperobject(49,2,9,"לא מתוך המעשים שלא יתהלל איש׃"));
hebsuperobject.biblemap.put("b49_2_10", new hebsuperobject(49,2,10,"כי פעל אלהים אנחנו נבראים במשיח ישוע למעשים טובים אשר הכין האלהים מקדם למען נתהלך בהם׃"));
hebsuperobject.biblemap.put("b49_2_11", new hebsuperobject(49,2,11,"על כן זכרו כי אתם הגוים בבשר הנקראים ערלים בפי הנקראים בני המילה שהיא מעשה ידים בבשר׃"));
hebsuperobject.biblemap.put("b49_2_12", new hebsuperobject(49,2,12,"כי אתם בעת ההיא הייתם בלי משיח מוזרים לעדת ישראל ונכרים לבריתות ההבטחה באין תקוה ובאין לכם אלהים בעולם׃"));
hebsuperobject.biblemap.put("b49_2_13", new hebsuperobject(49,2,13,"ועתה בישוע המשיח אתם הרחוקים מאז הייתם קרובים בדם המשיח׃"));
hebsuperobject.biblemap.put("b49_2_14", new hebsuperobject(49,2,14,"כי הוא שלומנו אשר עשה השנים לאחד והרס מחיצת הגדר׃"));
hebsuperobject.biblemap.put("b49_2_15", new hebsuperobject(49,2,15,"בבטלו האיבה בבשרו את תורת המצות בגזרותיהן לברא בנפשו את השנים לאיש אחד חדש ויעש שלום׃"));
hebsuperobject.biblemap.put("b49_2_16", new hebsuperobject(49,2,16,"וירצה את שניהם בגוף אחד לאלהים על ידי צליבתו בהמיתו בנפשו את האיבה׃"));
hebsuperobject.biblemap.put("b49_2_17", new hebsuperobject(49,2,17,"ויבא ויבשר שלום לכם הרחוקים והקרובים׃"));
hebsuperobject.biblemap.put("b49_2_18", new hebsuperobject(49,2,18,"כי על ידו יש לשנינו מבוא ברוח אחד אל אבינו׃"));
hebsuperobject.biblemap.put("b49_2_19", new hebsuperobject(49,2,19,"לכן אינכם עוד גרים ותושבים כי אתם בני עיר אחת עם הקדשים ובני בית אלהים׃"));
hebsuperobject.biblemap.put("b49_2_20", new hebsuperobject(49,2,20,"בנוים על יסוד השליחים והנביאים וישוע המשיח הוא אבן הפנה׃"));
hebsuperobject.biblemap.put("b49_2_21", new hebsuperobject(49,2,21,"אשר חבר בו יחד הבנין כלו עדי יגבה להיכל קדש ליהוה׃"));
hebsuperobject.biblemap.put("b49_2_22", new hebsuperobject(49,2,22,"ובו נבנים גם אתם להיות משכן אלהים ברוח׃"));
hebsuperobject.biblemap.put("b49_3_1", new hebsuperobject(49,3,1,"בעבור זאת אני פולוס אסיר המשיח למענכם הגוים׃"));
hebsuperobject.biblemap.put("b49_3_2", new hebsuperobject(49,3,2,"כי אמנם שמעתם הנהגת חסד האלהים אשר נתן לי אליכם׃"));
hebsuperobject.biblemap.put("b49_3_3", new hebsuperobject(49,3,3,"כי בחזון גלה לי הסוד אשר למעלה כתבתי לכם במעט׃"));
hebsuperobject.biblemap.put("b49_3_4", new hebsuperobject(49,3,4,"ובקראכם תוכלו להכיר בזאת את בינתי בסוד המשיח׃"));
hebsuperobject.biblemap.put("b49_3_5", new hebsuperobject(49,3,5,"אשר בדורת הראשנים לא נודע לבני אדם כאשר נגלה עתה לשליחיו הקדשים ולנביאיו ברוח׃"));
hebsuperobject.biblemap.put("b49_3_6", new hebsuperobject(49,3,6,"להיות הגוים גם הם בני ירשתו וגוף אחד אתו וחברי הבטחתו במשיח על ידי הבשרה׃"));
hebsuperobject.biblemap.put("b49_3_7", new hebsuperobject(49,3,7,"אשר הייתי לה למשרת במתנת חסד אלהים הנתונה לי כפי פעלת גבורתו׃"));
hebsuperobject.biblemap.put("b49_3_8", new hebsuperobject(49,3,8,"לי צעיר הצעירים שבכל הקדשים נתן החסד הזה לבשר בגוים את עשר המשיח אשר לא יחקר׃"));
hebsuperobject.biblemap.put("b49_3_9", new hebsuperobject(49,3,9,"ולהאיר עיני כל מה היא הנהגת הסוד הנסתר מדרת עולם באלהים יוצר הכל על ידי ישוע המשיח׃"));
hebsuperobject.biblemap.put("b49_3_10", new hebsuperobject(49,3,10,"למען אשר תודע עתה על ידי העדה לשרים לשליטים אשר במרומים חכמת אלהים המפליאה דתכיה׃"));
hebsuperobject.biblemap.put("b49_3_11", new hebsuperobject(49,3,11,"על פי עצת עולמים אשר יעץ במשיח ישוע אדנינו׃"));
hebsuperobject.biblemap.put("b49_3_12", new hebsuperobject(49,3,12,"אשר פתחון פינו ממנו וקרבתנו בבטחה על יד אמונתו׃"));
hebsuperobject.biblemap.put("b49_3_13", new hebsuperobject(49,3,13,"בעבור זאת אבקש שלא תחתו בצרותי למענכם יען כי היא תפארתכם׃"));
hebsuperobject.biblemap.put("b49_3_14", new hebsuperobject(49,3,14,"על כן אכרעה על ברכי לאבי אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b49_3_15", new hebsuperobject(49,3,15,"אשר נקרא על שמו כל בית אבות שבשמים ושבארץ׃"));
hebsuperobject.biblemap.put("b49_3_16", new hebsuperobject(49,3,16,"לתת לכם לפי עשר כבודו להתחזק בגבורה על ידי רוחו לאדם הפנימי׃"));
hebsuperobject.biblemap.put("b49_3_17", new hebsuperobject(49,3,17,"שישכן המשיח בלבבכם באמונה והייתם משרשים ומיסדים באהבה׃"));
hebsuperobject.biblemap.put("b49_3_18", new hebsuperobject(49,3,18,"למען תוכלו להשיג עם כל הקדשים מה הוא הרחב והארך והעמק והגבה׃"));
hebsuperobject.biblemap.put("b49_3_19", new hebsuperobject(49,3,19,"וידעתם את אהבת המשיח הנעלה על כל דעת ונמלאתם את כל מלוא האלהים׃"));
hebsuperobject.biblemap.put("b49_3_20", new hebsuperobject(49,3,20,"ולו אשר יכל להרבות גמוליו עלינו יותר מכל משאלותינו ומחשבותינו לפי הכח הפעל בקרבנו׃"));
hebsuperobject.biblemap.put("b49_3_21", new hebsuperobject(49,3,21,"לו הכבוד בקרב הקהל במשיח ישוע לדר ודר עד עולמי עולמים אמן׃"));
hebsuperobject.biblemap.put("b49_4_1", new hebsuperobject(49,4,1,"לכן אזהירכם אני האסור באדון להתהלך כאשר יאתה למשמרתכם אשר נקראתם לה׃"));
hebsuperobject.biblemap.put("b49_4_2", new hebsuperobject(49,4,2,"בכל נמיכות וענוה ובארך רוח לשאת איש את רעהו באהבה׃"));
hebsuperobject.biblemap.put("b49_4_3", new hebsuperobject(49,4,3,"ושקדו לשמר את אחדות הרוח באגדת השלום׃"));
hebsuperobject.biblemap.put("b49_4_4", new hebsuperobject(49,4,4,"גוף אחד ורוח אחד כאשר גם נקראתם בתקות משמרתכם האחת׃"));
hebsuperobject.biblemap.put("b49_4_5", new hebsuperobject(49,4,5,"אדון אחד אמונה אחת טבילה אחת׃"));
hebsuperobject.biblemap.put("b49_4_6", new hebsuperobject(49,4,6,"אל ואב אחד לכל שהוא על כל ובכל ובתוך כלכם׃"));
hebsuperobject.biblemap.put("b49_4_7", new hebsuperobject(49,4,7,"אבל לכל אחד ואחד ממנו נתן החסד כמדת מתנת המשיח׃"));
hebsuperobject.biblemap.put("b49_4_8", new hebsuperobject(49,4,8,"על כן הוא אומר עלה למרום שבה שבי ויתן מתנות לאדם׃"));
hebsuperobject.biblemap.put("b49_4_9", new hebsuperobject(49,4,9,"ועלה שאמר מה הוא אם לא שירד ירד מקדם לתחתיות ארץ׃"));
hebsuperobject.biblemap.put("b49_4_10", new hebsuperobject(49,4,10,"הירד הוא אשר גם עלה למעלה מכל השמים למען ימלא את הכל׃"));
hebsuperobject.biblemap.put("b49_4_11", new hebsuperobject(49,4,11,"והוא נתן את אלה שליחים ואת אלה נביאים ואת אלה מבשרים ואת אלה רעים ומלמדים׃"));
hebsuperobject.biblemap.put("b49_4_12", new hebsuperobject(49,4,12,"להשלים את הקדשים למעשה העבודה לבנין גוף המשיח׃"));
hebsuperobject.biblemap.put("b49_4_13", new hebsuperobject(49,4,13,"עד כי נגיע כלנו לאחדות האמונה ודעת בן האלהים כאיש אחד שלם לשעור קומת מלוא המשיח׃"));
hebsuperobject.biblemap.put("b49_4_14", new hebsuperobject(49,4,14,"ולא נהיה עוד ילדים נגרשים ונדפים בכל רוח הלמוד בתרמית בני אדם ומקשותם אשר שתו להתעות׃"));
hebsuperobject.biblemap.put("b49_4_15", new hebsuperobject(49,4,15,"כי אם נדבר האמת באהבה ונגדלה בכל דבר לו למשיח שהוא הראש׃"));
hebsuperobject.biblemap.put("b49_4_16", new hebsuperobject(49,4,16,"אשר ממנו כל הגוף בהיותו מרכב ומדבק בכל חבור השמוש כפי מדת הפעלה הנתונה לכל אבר ואבר ירבה ויגדל להשלמת בנינו באהבה׃"));
hebsuperobject.biblemap.put("b49_4_17", new hebsuperobject(49,4,17,"והנה זאת אני אמר ומעיד באדון כי מעתה לא תלכו עוד כיתר הגוים ההלכים בהבלי שכלם׃"));
hebsuperobject.biblemap.put("b49_4_18", new hebsuperobject(49,4,18,"חשכי הדעת ומוזרים לחיי אלהים מפני אולתם אשר בהם כי טח מהשכיל לבבם׃"));
hebsuperobject.biblemap.put("b49_4_19", new hebsuperobject(49,4,19,"אשר השמינו ויתנו את נפשם לזמה לעשות כל תועבה באהבת הבצע׃"));
hebsuperobject.biblemap.put("b49_4_20", new hebsuperobject(49,4,20,"ואתם לא כן למדתם את המשיח׃"));
hebsuperobject.biblemap.put("b49_4_21", new hebsuperobject(49,4,21,"אם אמנם אתו שמעתם ובו למדתם כפי האמת בישוע׃"));
hebsuperobject.biblemap.put("b49_4_22", new hebsuperobject(49,4,22,"אשר תסורו מדרכיכם הראשנים ותפשטו את האדם הישן הנשחת בתאות התרמית׃"));
hebsuperobject.biblemap.put("b49_4_23", new hebsuperobject(49,4,23,"ותתחדשו ברוח שכלכם׃"));
hebsuperobject.biblemap.put("b49_4_24", new hebsuperobject(49,4,24,"ותלבשו את האדם החדש הנברא כדמות אלהים בצדקה וקדשת האמת׃"));
hebsuperobject.biblemap.put("b49_4_25", new hebsuperobject(49,4,25,"על כן הסירו מכם את השקר ודברו אמת איש את רעהו כי אברים כלנו יחד איש לאיש׃"));
hebsuperobject.biblemap.put("b49_4_26", new hebsuperobject(49,4,26,"רגזו ואל תחטאו אל תשקע החמה על רגזכם׃"));
hebsuperobject.biblemap.put("b49_4_27", new hebsuperobject(49,4,27,"גם לא תתנו מקום לשטן׃"));
hebsuperobject.biblemap.put("b49_4_28", new hebsuperobject(49,4,28,"מי שגנב אל יסף לגנב כי אם ייגע ובידיו יעשה את הטוב למען יהיה לו לתת לאיש מחסור׃"));
hebsuperobject.biblemap.put("b49_4_29", new hebsuperobject(49,4,29,"כל דבר נבול לא יצא מפיכם כי אם הטוב והמועיל לבנות לפי הצרך למען יתן חן לשמעיו׃"));
hebsuperobject.biblemap.put("b49_4_30", new hebsuperobject(49,4,30,"ולא תעצבו את רוח הקדש של אלהים אשר נחתמתם בו אל יום הגאלה׃"));
hebsuperobject.biblemap.put("b49_4_31", new hebsuperobject(49,4,31,"כל מרירות וחמה ורגז וצעקה וגדוף תסירו מכם עם כל הרשעה׃"));
hebsuperobject.biblemap.put("b49_4_32", new hebsuperobject(49,4,32,"והיו טובים איש אל רעהו ורחמנים וסלחים איש לאחיו כאשר סלח לכם האלהים במשיח׃"));
hebsuperobject.biblemap.put("b49_5_1", new hebsuperobject(49,5,1,"לכן לכו בדרך האלהים כבנים חביבים׃"));
hebsuperobject.biblemap.put("b49_5_2", new hebsuperobject(49,5,2,"והתהלכו באהבה כאשר גם המשיח אהב אתנו והקריב את נפשו בעדנו לקרבן וזבח לאלהים לריח ניחוח׃"));
hebsuperobject.biblemap.put("b49_5_3", new hebsuperobject(49,5,3,"אבל זנות וכל טמאה ואהבת בצע בל יזכר ביניכם כאשר נאוה לקדשים׃"));
hebsuperobject.biblemap.put("b49_5_4", new hebsuperobject(49,5,4,"גם לא נבול פה ודברי סכלות ולעג אשר לא כהגן כי אם קול תודה׃"));
hebsuperobject.biblemap.put("b49_5_5", new hebsuperobject(49,5,5,"כי זאת ידע תדעו כי כל זנה וטמא ואהב בצע שהוא עבד אלילים אין לו חלק ונחלה במלכות המשיח והאלהים׃"));
hebsuperobject.biblemap.put("b49_5_6", new hebsuperobject(49,5,6,"אל ישיא איש אתכם בדברי ריק כי בגלל אלה חרון אלהים בא על בני המרי׃"));
hebsuperobject.biblemap.put("b49_5_7", new hebsuperobject(49,5,7,"על כן אל יהי חלקכם עמהם׃"));
hebsuperobject.biblemap.put("b49_5_8", new hebsuperobject(49,5,8,"כי מלפנים הייתם חשך ועתה הנכם אור באדנינו התהלכו נא כבני אור׃"));
hebsuperobject.biblemap.put("b49_5_9", new hebsuperobject(49,5,9,"כי פרי הרוח כל מעשי חסד וצדק ואמת׃"));
hebsuperobject.biblemap.put("b49_5_10", new hebsuperobject(49,5,10,"ובחנו מה הוא רצוי בעיני אדנינו׃"));
hebsuperobject.biblemap.put("b49_5_11", new hebsuperobject(49,5,11,"ואל תשתתפו עם מעשי החשך אשר לא יעשו פרי כי אם הוכח תוכיחו אותם׃"));
hebsuperobject.biblemap.put("b49_5_12", new hebsuperobject(49,5,12,"כי מה שהם עשים בסתר חרפה היא אך לספר׃"));
hebsuperobject.biblemap.put("b49_5_13", new hebsuperobject(49,5,13,"אבל כל זאת יגלה כשיוכח על ידי האור כי כל הנגלה אור הוא׃"));
hebsuperobject.biblemap.put("b49_5_14", new hebsuperobject(49,5,14,"על כן הוא אומר עורה הישן וקומה מן המתים ויאר לך המשיח׃"));
hebsuperobject.biblemap.put("b49_5_15", new hebsuperobject(49,5,15,"ועתה ראו והזהרו להתהלך לא ככסילים כי אם כחכמים׃"));
hebsuperobject.biblemap.put("b49_5_16", new hebsuperobject(49,5,16,"מוקירים העת כי הימים רעים המה׃"));
hebsuperobject.biblemap.put("b49_5_17", new hebsuperobject(49,5,17,"על כן אל תהיו חסרי דעת כי אם מבינים לדעת מה הוא רצון אדנינו׃"));
hebsuperobject.biblemap.put("b49_5_18", new hebsuperobject(49,5,18,"ואל תשתכרו מיין המביא לידי פריצות כי אם המלאו ברוח׃"));
hebsuperobject.biblemap.put("b49_5_19", new hebsuperobject(49,5,19,"ושיחו איש לרעהו בתהלות ותשבחות ושירות רוחניות שירו וזמרו לאדני בלבבכם׃"));
hebsuperobject.biblemap.put("b49_5_20", new hebsuperobject(49,5,20,"והודו בכל עת על הכל לאלהים אבינו בשם אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b49_5_21", new hebsuperobject(49,5,21,"הכנעו איש לאחיו ביראת אלהים׃"));
hebsuperobject.biblemap.put("b49_5_22", new hebsuperobject(49,5,22,"הנשים הכנענה לבעליכן כמו לאדנינו׃"));
hebsuperobject.biblemap.put("b49_5_23", new hebsuperobject(49,5,23,"כי האיש הוא ראש האשה כאשר המשיח הוא ראש העדה והוא מושיע של הגוף׃"));
hebsuperobject.biblemap.put("b49_5_24", new hebsuperobject(49,5,24,"אבל כאשר תכנע העדה למשיח ככה גם הנשים לבעליהן בכל דבר׃"));
hebsuperobject.biblemap.put("b49_5_25", new hebsuperobject(49,5,25,"האנשים אהבו את נשיכם כאשר גם המשיח אהב את העדה ויתן את נפשו בעדה׃"));
hebsuperobject.biblemap.put("b49_5_26", new hebsuperobject(49,5,26,"למען קדשה בדברו אחרי אשר טהרה ברחיצת המים׃"));
hebsuperobject.biblemap.put("b49_5_27", new hebsuperobject(49,5,27,"להקימה בכבוד לו לעדה אשר אין בה כתם וקמט וכדומה כי אם למען תהיה קדושה ותמימה׃"));
hebsuperobject.biblemap.put("b49_5_28", new hebsuperobject(49,5,28,"כן האנשים חיבים לאהב את נשיהם כגופם כי האהב את אשתו אהב את עצמו׃"));
hebsuperobject.biblemap.put("b49_5_29", new hebsuperobject(49,5,29,"כי מעולם לא שנא איש את בשרו כי אם זן ומכלכל אתו כאשר גם האדון את עדתו׃"));
hebsuperobject.biblemap.put("b49_5_30", new hebsuperobject(49,5,30,"כי אברי גופו אנחנו משברו ומעצמיו׃"));
hebsuperobject.biblemap.put("b49_5_31", new hebsuperobject(49,5,31,"על כן יעזב איש את אביו ואת אמו ודבק באשתו והיו שניהם לבשר אחד׃"));
hebsuperobject.biblemap.put("b49_5_32", new hebsuperobject(49,5,32,"גדול הסוד הזה ואני מפרש אתו על המשיח ועל עדתו׃"));
hebsuperobject.biblemap.put("b49_5_33", new hebsuperobject(49,5,33,"ואולם גם אתם כל איש מכם יאהב את אשתו כנפשו והאשה היא תזהר ותירא את בעלה׃"));
hebsuperobject.biblemap.put("b49_6_1", new hebsuperobject(49,6,1,"שמעו בנים אל הוריכם באדנינו כי ארח ישר הוא׃"));
hebsuperobject.biblemap.put("b49_6_2", new hebsuperobject(49,6,2,"כבד את אביך ואת אמך זאת היא המצוה הראשונה אשר לה ההבטחה׃"));
hebsuperobject.biblemap.put("b49_6_3", new hebsuperobject(49,6,3,"למען ייטב לך ולמען יאריכן ימיך על האדמה׃"));
hebsuperobject.biblemap.put("b49_6_4", new hebsuperobject(49,6,4,"ואתם האבות אל תכעיסו את בניכם אך גדלום במוסר אדנינו ובתוכחתו׃"));
hebsuperobject.biblemap.put("b49_6_5", new hebsuperobject(49,6,5,"שמעו עבדים אל אדניכם לפי הבשר ביראה ורתת ובתם לבבכם כמו למשיח׃"));
hebsuperobject.biblemap.put("b49_6_6", new hebsuperobject(49,6,6,"לא בעבדת מראה העין כמבקשי חן בני אדם כי אם כעבדי המשיח עשים רצון האלהים בכל נפשם׃"));
hebsuperobject.biblemap.put("b49_6_7", new hebsuperobject(49,6,7,"ועבדים בנפש חפצה את האדון ולא בני אדם׃"));
hebsuperobject.biblemap.put("b49_6_8", new hebsuperobject(49,6,8,"וידעתם כי כל דבר טוב אשר עשה האדם ישלמנו לו אדנינו אם עבד הוא או בן חורין׃"));
hebsuperobject.biblemap.put("b49_6_9", new hebsuperobject(49,6,9,"ואתם האדנים ככה תעשו גם להם חדלו מגער בם וידעתם כי גם עליכם יש אדון בשמים ואין לפניו משא פנים׃"));
hebsuperobject.biblemap.put("b49_6_10", new hebsuperobject(49,6,10,"סוף דבר אחי חזקו באדנינו ובעז גבורתו׃"));
hebsuperobject.biblemap.put("b49_6_11", new hebsuperobject(49,6,11,"לבשו כלי נשק אלהים למען תוכלו עמד נגד נכלי השטן׃"));
hebsuperobject.biblemap.put("b49_6_12", new hebsuperobject(49,6,12,"כי לא עם בשר ודם מלחמתנו כי עם שרים ושליטים עם המשלים בחשכת העולם הזה עם הרוחות הרעות אשר במרומים׃"));
hebsuperobject.biblemap.put("b49_6_13", new hebsuperobject(49,6,13,"על כן אחזו בכלי נשק אלהים למען תוכלו לקום ביום הרע ולמלא צבאכם ולעמוד׃"));
hebsuperobject.biblemap.put("b49_6_14", new hebsuperobject(49,6,14,"עמדו נא חגורי מתנים באמת ומלבשים בשריון הצדק׃"));
hebsuperobject.biblemap.put("b49_6_15", new hebsuperobject(49,6,15,"ורגליכם מנעלות להיותכם מוכנים לבשורת השלום׃"));
hebsuperobject.biblemap.put("b49_6_16", new hebsuperobject(49,6,16,"ועל כל אלה תפשו את מגן האמונה אשר תוכלו לכבות בו את חצי הרשע הבערים׃"));
hebsuperobject.biblemap.put("b49_6_17", new hebsuperobject(49,6,17,"וקחו את כובע הישועה וחרב הרוח שהיא דבר האלהים׃"));
hebsuperobject.biblemap.put("b49_6_18", new hebsuperobject(49,6,18,"והתפללו תמיד בכל עת בתפלה ותחנונים ברוח ושקדו והתאמצו על זאת להעתיר תמיד בעד כל הקדשים׃"));
hebsuperobject.biblemap.put("b49_6_19", new hebsuperobject(49,6,19,"וגם בעדי למען ינתן לי הדבר בפתחי פי להגיד בבטחון את סוד הבשורה אשר אנכי ציר לה במוסרות׃"));
hebsuperobject.biblemap.put("b49_6_20", new hebsuperobject(49,6,20,"למען אדבר בה בבטחה כאשר מטל עלי לדבר׃"));
hebsuperobject.biblemap.put("b49_6_21", new hebsuperobject(49,6,21,"ולמען אשר תדעו גם אתם את קרתי ואת מעשי הנה את הכל יודיע אתכם טוכיקוס האח החביב והמשרת הנאמן באדנינו׃"));
hebsuperobject.biblemap.put("b49_6_22", new hebsuperobject(49,6,22,"אשר לזאת שלחתיהו אליכם למען תדעו את קרתינו ולמען ינחם את לבבכם׃"));
hebsuperobject.biblemap.put("b49_6_23", new hebsuperobject(49,6,23,"השלום לאחים והאהבה עם האמונה מאת האלהים האב ומאת האדון ישוע המשיח׃"));
hebsuperobject.biblemap.put("b49_6_24", new hebsuperobject(49,6,24,"החסד עם כל האהבים את אדנינו ישוע המשיח באהבה אשר לא תכלה אמן׃"));

}

}