package heb.bible;

public class hebbible41 {

public hebbible41() {

putmapbible41();

}

private void putmapbible41() {

hebsuperobject.biblemap.put("b41_1_1", new hebsuperobject(41,1,1,"ראשית בשורת ישוע המשיח בן האלהים׃"));
hebsuperobject.biblemap.put("b41_1_2", new hebsuperobject(41,1,2,"ככתוב בנביאים הנני שלח מלאכי לפניך ופנה דרכך לפניך׃"));
hebsuperobject.biblemap.put("b41_1_3", new hebsuperobject(41,1,3,"קול קורא במדבר פנו דרך יהוה ישרו מסלותיו׃"));
hebsuperobject.biblemap.put("b41_1_4", new hebsuperobject(41,1,4,"ויהי יוחנן טבל במדבר וקורא טבילת התשובה לסליחת החטאים׃"));
hebsuperobject.biblemap.put("b41_1_5", new hebsuperobject(41,1,5,"ותצא אליו כל ארץ יהודה ובני ירושלים ויטבלו כלם על ידו בנהר הירדן מתודים את חטאתם׃"));
hebsuperobject.biblemap.put("b41_1_6", new hebsuperobject(41,1,6,"ויוחנן לבוש שער גמלים ואזור עור במתניו ואכל חגבים ודבש היער׃"));
hebsuperobject.biblemap.put("b41_1_7", new hebsuperobject(41,1,7,"ויקרא לאמר בוא יבא אחרי החזק ממני אשר אינני כדי לכרע ולהתיר את שרוך נעליו׃"));
hebsuperobject.biblemap.put("b41_1_8", new hebsuperobject(41,1,8,"אנכי טבלתי אתכם במים והוא יטבל אתכם ברוח הקדש׃"));
hebsuperobject.biblemap.put("b41_1_9", new hebsuperobject(41,1,9,"ויהי בימים ההם ויבא ישוע מנצרת אשר בגליל ויטבל על ידי יוחנן בירדן׃"));
hebsuperobject.biblemap.put("b41_1_10", new hebsuperobject(41,1,10,"ויהי אך עלה עלה מן המים וירא את השמים נבקעים והרוח כיונה ירדת עליו׃"));
hebsuperobject.biblemap.put("b41_1_11", new hebsuperobject(41,1,11,"ויהי קול מן השמים אתה בני ידידי אשר רצתה נפשי בו׃"));
hebsuperobject.biblemap.put("b41_1_12", new hebsuperobject(41,1,12,"ואחרי כן הוציאו הרוח המדברה׃"));
hebsuperobject.biblemap.put("b41_1_13", new hebsuperobject(41,1,13,"ויהי שם במדבר ארבעים יום והשטן נסהו ויהי עם החיות והמלאכים שרתוהו׃"));
hebsuperobject.biblemap.put("b41_1_14", new hebsuperobject(41,1,14,"ואחרי אשר הסגר יוחנן בא ישוע הגלילה ויקרא את בשורת מלכות האלהים לאמר׃"));
hebsuperobject.biblemap.put("b41_1_15", new hebsuperobject(41,1,15,"מלאה העת והגיעה מלכות האלהים שובו והאמינו בבשורה׃"));
hebsuperobject.biblemap.put("b41_1_16", new hebsuperobject(41,1,16,"ויהי בהתהלכו על יד ים הגליל וירא את שמעון ואת אנדרי אחי שמעון פרשים מצודה בים כי דיגים היו׃"));
hebsuperobject.biblemap.put("b41_1_17", new hebsuperobject(41,1,17,"ויאמר אליהם ישוע לכו אחרי ואשימכם לדיגי אנשים׃"));
hebsuperobject.biblemap.put("b41_1_18", new hebsuperobject(41,1,18,"ויעזבו מהר את מכמרתיהם וילכו אחריו׃"));
hebsuperobject.biblemap.put("b41_1_19", new hebsuperobject(41,1,19,"ויהי כעברו מעט משם וירא את יעקב בן זבדי ואת יוחנן אחיו וגם המה באניה מתקנים את המכמרות׃"));
hebsuperobject.biblemap.put("b41_1_20", new hebsuperobject(41,1,20,"ויקרא מהרה אליהם ויעזבו את זבדי אביהם באניה עם השכירים וילכו אחריו׃"));
hebsuperobject.biblemap.put("b41_1_21", new hebsuperobject(41,1,21,"ויבאו אל כפר נחום וימהר לבוא בשבת לבית הכנסת וילמד׃"));
hebsuperobject.biblemap.put("b41_1_22", new hebsuperobject(41,1,22,"וישתוממו על תורתו כי היה מלמדם כבעל גבורה ולא כספרים׃"));
hebsuperobject.biblemap.put("b41_1_23", new hebsuperobject(41,1,23,"ואיש היה בבית כנסתם אשר רוח טמאה בו ויצעק לאמר׃"));
hebsuperobject.biblemap.put("b41_1_24", new hebsuperobject(41,1,24,"אהה מה לנו ולך ישוע הנצרי באת להאבידנו ידעתי מי אתה קדוש האלהים׃"));
hebsuperobject.biblemap.put("b41_1_25", new hebsuperobject(41,1,25,"ויגער בו ישוע לאמר האלם וצא ממנו׃"));
hebsuperobject.biblemap.put("b41_1_26", new hebsuperobject(41,1,26,"ויסחבהו רוח הטמאה ויצעק בקול גדול ויצא ממנו׃"));
hebsuperobject.biblemap.put("b41_1_27", new hebsuperobject(41,1,27,"ויבהלו כלם וישאלו איש את רעהו לאמר מה זאת מה היא התורה החדשה אשר אף לרוחות הטמאה בגבורה הוא מצוה והנה שמעות לו׃"));
hebsuperobject.biblemap.put("b41_1_28", new hebsuperobject(41,1,28,"ויצא שמעו מהר בכל מקמות ארץ הגליל׃"));
hebsuperobject.biblemap.put("b41_1_29", new hebsuperobject(41,1,29,"ויהי אחרי צאתם מבית הכנסת ויבאו ביתה שמעון ואנדרי המה ויעקב ויוחנן עמם׃"));
hebsuperobject.biblemap.put("b41_1_30", new hebsuperobject(41,1,30,"וחמות שמעון שכבה אחוזת הקדחת וימהרו לדבר אליו עליה׃"));
hebsuperobject.biblemap.put("b41_1_31", new hebsuperobject(41,1,31,"ויגש ויאחז בידה ויקימה ותרף ממנה הקדחת פתאם ותשרת אותם׃"));
hebsuperobject.biblemap.put("b41_1_32", new hebsuperobject(41,1,32,"ויהי בערב כבוא השמש ויביאו אליו את כל החולים ואת אחוזי השדים׃"));
hebsuperobject.biblemap.put("b41_1_33", new hebsuperobject(41,1,33,"וכל העיר נאספו יחדו פתח הבית׃"));
hebsuperobject.biblemap.put("b41_1_34", new hebsuperobject(41,1,34,"וירפא רבים אשר היו חולים חליים שונים ויגרש שדים הרבה ולא נתן את השדים לדבר כי ידעהו׃"));
hebsuperobject.biblemap.put("b41_1_35", new hebsuperobject(41,1,35,"וישכם ממחרת בעוד לילה ויצא וילך אל מקום חרבה ויתפלל שם׃"));
hebsuperobject.biblemap.put("b41_1_36", new hebsuperobject(41,1,36,"וירדפו אחריו שמעון והאנשים אשר אתו׃"));
hebsuperobject.biblemap.put("b41_1_37", new hebsuperobject(41,1,37,"וימצאהו ויאמרו אליו הנה כלם מבקשים אותך׃"));
hebsuperobject.biblemap.put("b41_1_38", new hebsuperobject(41,1,38,"ויאמר אליהם נעברה מזה אל ערי הפרזות הקרבות ואקרא גם שם כי בעבור זאת יצאתי׃"));
hebsuperobject.biblemap.put("b41_1_39", new hebsuperobject(41,1,39,"ויהי קרא בבתי כנסיותיהם בכל הגליל ויגרש את השדים׃"));
hebsuperobject.biblemap.put("b41_1_40", new hebsuperobject(41,1,40,"ויבוא אליו איש מצרע ויתחנן אליו ויכרע על ברכיו ויאמר לו אם תרצה תוכל לטהרני׃"));
hebsuperobject.biblemap.put("b41_1_41", new hebsuperobject(41,1,41,"וירחם עליו וישלח את ידו ויגע בו ויאמר רצה אנכי טהר׃"));
hebsuperobject.biblemap.put("b41_1_42", new hebsuperobject(41,1,42,"עודנו מדבר והצרעת סרה ממנו ויטהר׃"));
hebsuperobject.biblemap.put("b41_1_43", new hebsuperobject(41,1,43,"ויגער בו וימהר להוציאו החוצה׃"));
hebsuperobject.biblemap.put("b41_1_44", new hebsuperobject(41,1,44,"ויאמר אליו ראה אל תספר דבר לאיש כי אם לך הראה אל הכהן והקרב על טהרתך את אשר צוה משה לעדות להם׃"));
hebsuperobject.biblemap.put("b41_1_45", new hebsuperobject(41,1,45,"אך הוא בצאתו החל לקרא הרבה ולהשמיע הדבר עד אשר לא יכל לבוא עוד אל עיר בגלוי כי אם היה ישב מחוץ לעיר במקמות חרבה ויבאו אליו מכל עבריו׃"));
hebsuperobject.biblemap.put("b41_2_1", new hebsuperobject(41,2,1,"ויהי מקץ ימים בשובו אל כפר נחום וישמעו כי הוא בבית׃"));
hebsuperobject.biblemap.put("b41_2_2", new hebsuperobject(41,2,2,"ויאספו רבים מהרה עד אפס מקום לעמד אף מחוץ לפתח וידבר אליהם את הדבר׃"));
hebsuperobject.biblemap.put("b41_2_3", new hebsuperobject(41,2,3,"ויבאו אליו אנשים נשאים איש נכה אברים וישאהו בארבעה׃"));
hebsuperobject.biblemap.put("b41_2_4", new hebsuperobject(41,2,4,"ולא יכלו לגשת אליו מפני העם ויסירו את הגג במקום אשר היה שם ויחתרו חתירה ויורידו את המשכב אשר שכב עליה נכה האברים׃"));
hebsuperobject.biblemap.put("b41_2_5", new hebsuperobject(41,2,5,"ויהי כראות ישוע את אמונתם ויאמר אל נכה האברים בני נסלחו לך חטאתיך׃"));
hebsuperobject.biblemap.put("b41_2_6", new hebsuperobject(41,2,6,"ויהיו מן הסופרים ישבים שם וחשבים בלבם לאמר׃"));
hebsuperobject.biblemap.put("b41_2_7", new hebsuperobject(41,2,7,"מה ידבר זה גדופים כאלה מי יוכל לסלח חטאים בלתי האלהים לבדו׃"));
hebsuperobject.biblemap.put("b41_2_8", new hebsuperobject(41,2,8,"וידע ישוע ברוחו כי ככה חשבו בלבבם ויאמר אליהם מדוע תחשבו כאלה בלבבכם׃"));
hebsuperobject.biblemap.put("b41_2_9", new hebsuperobject(41,2,9,"מה הנקל האמר אל נכה האברים נסלחו לך חטאתיך אם אמור קום שא את משכבך והתהלך׃"));
hebsuperobject.biblemap.put("b41_2_10", new hebsuperobject(41,2,10,"אך למען תדעון כי לבן האדם יש השלטן לסלח חטאים בארץ ויאמר אל נכה האברים׃"));
hebsuperobject.biblemap.put("b41_2_11", new hebsuperobject(41,2,11,"לך אני אמר קום שא את משכבך ולך אל ביתך׃"));
hebsuperobject.biblemap.put("b41_2_12", new hebsuperobject(41,2,12,"ויקם פתאם וישא את משכבו ויצא לעיני כלם עד כי השתממו כלם וישבחו את האלהים לאמר מעולם לא ראינו כזאת׃"));
hebsuperobject.biblemap.put("b41_2_13", new hebsuperobject(41,2,13,"וישב לצאת אל יד הים ויבאו אליו כל העם וילמדם׃"));
hebsuperobject.biblemap.put("b41_2_14", new hebsuperobject(41,2,14,"ויהי בעברו וירא את לוי בן חלפי ישב בבית המכס ויאמר אליו לכה אחרי ויקם וילך אחריו׃"));
hebsuperobject.biblemap.put("b41_2_15", new hebsuperobject(41,2,15,"ויהי כאשר הסב בביתו ויסבו מוכסים וחטאים רבים עם ישוע ועם תלמידיו כי רבים היו ההלכים אחריו׃"));
hebsuperobject.biblemap.put("b41_2_16", new hebsuperobject(41,2,16,"והסופרים והפרושים ראו אתו אכל עם המוכסים והחטאים ויאמרו אל תלמידיו למה זה עם החטאים והמוכסים אכל רבכם׃"));
hebsuperobject.biblemap.put("b41_2_17", new hebsuperobject(41,2,17,"וישמע ישוע ויאמר החזקים אינם צריכים לרפא כי אם החלים לא באתי לקרא הצדיקים כי אם החטאים לתשובה׃"));
hebsuperobject.biblemap.put("b41_2_18", new hebsuperobject(41,2,18,"ותלמידי יוחנן והפרושים היו צמים ויבאו ויאמרו אליו מדוע תלמידי יוחנן ותלמידי הפרושים צמים ותלמידיך אינם צמים׃"));
hebsuperobject.biblemap.put("b41_2_19", new hebsuperobject(41,2,19,"ויאמר אליהם ישוע איך יוכלו בני החפה לצום בעוד החתן עמהם כל ימי היות החתן עמהם לא יוכלו לצום׃"));
hebsuperobject.biblemap.put("b41_2_20", new hebsuperobject(41,2,20,"הנה ימים באים ולקח מאתם החתן ואז יצומו בימים ההם׃"));
hebsuperobject.biblemap.put("b41_2_21", new hebsuperobject(41,2,21,"אין תפר מטלית בגד חדש על שמלה בלה כי אז ינתק מלויו החדש מן הבלה ותרע הקריעה׃"));
hebsuperobject.biblemap.put("b41_2_22", new hebsuperobject(41,2,22,"ואין נתן יין חדש בנאדות בלים כי אז יבקע היין את הנאדות והיין ישפך והנאדות יאבדו אבל בנאדות חדשים ינתן היין החדש׃"));
hebsuperobject.biblemap.put("b41_2_23", new hebsuperobject(41,2,23,"ויהי כעברו בשבת בין הקמה ויחלו תלמידיו לקטף מלילת בלכתם׃"));
hebsuperobject.biblemap.put("b41_2_24", new hebsuperobject(41,2,24,"ויאמרו אליו הפרושים ראה מה המה עשים בשבת דבר אשר לא יעשה׃"));
hebsuperobject.biblemap.put("b41_2_25", new hebsuperobject(41,2,25,"ויאמר אליהם הכי לא קראתם את אשר עשה דוד בהיתו חסר ורעב הוא ואשר היו אתו׃"));
hebsuperobject.biblemap.put("b41_2_26", new hebsuperobject(41,2,26,"כי בא אל בית אלהים בימי אביתר הכהן הגדול ויאכל את לחם הפנים אשר לא נכון לאכלה כי אם לכהנים ויתן גם לאנשים אשר אתו׃"));
hebsuperobject.biblemap.put("b41_2_27", new hebsuperobject(41,2,27,"ויאמר אליהם השבת נעשה בעבור האדם ולא האדם בעבור השבת׃"));
hebsuperobject.biblemap.put("b41_2_28", new hebsuperobject(41,2,28,"לכן בן האדם אדון הוא גם לשבת׃"));
hebsuperobject.biblemap.put("b41_3_1", new hebsuperobject(41,3,1,"וישב ויבאו אל בית הכנסת ושם איש אשר ידו יבשה׃"));
hebsuperobject.biblemap.put("b41_3_2", new hebsuperobject(41,3,2,"ויתבוננו בו אם ירפאהו בשבת למען ימצאו עליו שטנה׃"));
hebsuperobject.biblemap.put("b41_3_3", new hebsuperobject(41,3,3,"ויאמר אל האיש אשר יבשה ידו קום עמד בתוך׃"));
hebsuperobject.biblemap.put("b41_3_4", new hebsuperobject(41,3,4,"ויאמר אליהם הנכון בשבת להיטיב או להרע להציל נפש או לאבדה ויחרישו׃"));
hebsuperobject.biblemap.put("b41_3_5", new hebsuperobject(41,3,5,"ויבט אליהם סביב בחמה ויתעצב על טמטום לבבם ויאמר אל האיש פשט את ידך ויפשט ידו ותרפא ותשב כאחרת׃"));
hebsuperobject.biblemap.put("b41_3_6", new hebsuperobject(41,3,6,"והפרושים יצאו מהרה ויתיעצו עליו עם ההורדוסיים לאבדו׃"));
hebsuperobject.biblemap.put("b41_3_7", new hebsuperobject(41,3,7,"וישוע סר משם עם תלמידיו אל יד הים וילכו אחריו המון עם רב מן הגליל ומיהודה׃"));
hebsuperobject.biblemap.put("b41_3_8", new hebsuperobject(41,3,8,"ומירושלים ומאדום ומעבר הירדן ומסביבות צור וצידון המון רב אשר שמעו את כל אשר עשה ויבאו אליו׃"));
hebsuperobject.biblemap.put("b41_3_9", new hebsuperobject(41,3,9,"ויאמר אל תלמידיו כי יכינו לו אניה קטנה מפני העם למען לא ילחצוהו׃"));
hebsuperobject.biblemap.put("b41_3_10", new hebsuperobject(41,3,10,"כי רפא לרבים עד כי התנפלו עליו כל המנגעים לנגע בו׃"));
hebsuperobject.biblemap.put("b41_3_11", new hebsuperobject(41,3,11,"והרוחות הטמאות כראותן אתו נפלו לפניו ותצעקנה לאמר אתה הוא בן אלהים׃"));
hebsuperobject.biblemap.put("b41_3_12", new hebsuperobject(41,3,12,"ויגער בהן מאד אשר לא תגלינה אותו׃"));
hebsuperobject.biblemap.put("b41_3_13", new hebsuperobject(41,3,13,"ויעל אל ההר ויקרא אל אשר הוא חפץ בם ויבאו אליו׃"));
hebsuperobject.biblemap.put("b41_3_14", new hebsuperobject(41,3,14,"וישם שנים עשר איש למען יהיו אתו ולמען ישלחם לקרא׃"));
hebsuperobject.biblemap.put("b41_3_15", new hebsuperobject(41,3,15,"והיה להם השלטן לרפא את התחלאים ולגרש את השדים׃"));
hebsuperobject.biblemap.put("b41_3_16", new hebsuperobject(41,3,16,"ויכנה את שמעון בשם פטרוס׃"));
hebsuperobject.biblemap.put("b41_3_17", new hebsuperobject(41,3,17,"ואת יעקב בן זבדי ואת יוחנן אחי יעקב ויכנה אתם בשם בני רגוש הוא בני רעם׃"));
hebsuperobject.biblemap.put("b41_3_18", new hebsuperobject(41,3,18,"ואת אנדרי ואת פילפוס ואת בר תלמי ואת מתי ואת תומא ואת יעקב בן חלפי ואת תדי ואת שמעון הקני׃"));
hebsuperobject.biblemap.put("b41_3_19", new hebsuperobject(41,3,19,"ואת יהודה איש קריות אשר גם מסרו׃"));
hebsuperobject.biblemap.put("b41_3_20", new hebsuperobject(41,3,20,"ויבאו הביתה וישב המון העם להתאסף עד כי לא יכלו אף לאכל לחם׃"));
hebsuperobject.biblemap.put("b41_3_21", new hebsuperobject(41,3,21,"וישמעו קרוביו ויצאו להחזיק בו כי אמרו יצא מדעתו׃"));
hebsuperobject.biblemap.put("b41_3_22", new hebsuperobject(41,3,22,"והסופרים אשר ירדו מירושלים אמרו כי בעל זבוב נכנס בו ועל ידי שר השדים הוא מגרש את השדים׃"));
hebsuperobject.biblemap.put("b41_3_23", new hebsuperobject(41,3,23,"ויקרא אותם אליו וידבר להם במשלים לאמר איך יוכל השטן לגרש השטן׃"));
hebsuperobject.biblemap.put("b41_3_24", new hebsuperobject(41,3,24,"ואם נחלקה ממלכה על עצמה לא תוכל לעמד הממלכה ההיא׃"));
hebsuperobject.biblemap.put("b41_3_25", new hebsuperobject(41,3,25,"ובית אם נחלק על עצמו לא יוכל לעמד הבית ההוא׃"));
hebsuperobject.biblemap.put("b41_3_26", new hebsuperobject(41,3,26,"ואם השטן יתקומם אל עצמו ונחלק לא יוכל לעמד כי בא קצו׃"));
hebsuperobject.biblemap.put("b41_3_27", new hebsuperobject(41,3,27,"אין איש אשר יכל לבוא לבית הגבור ולגזל את כליו אם לא יאסר בראשונה את הגבור ואחר ישסה את ביתו׃"));
hebsuperobject.biblemap.put("b41_3_28", new hebsuperobject(41,3,28,"אמן אמר אני לכם כי כל החטאים יסלחו לבני אדם וכל הגדופים אשר יגדפו׃"));
hebsuperobject.biblemap.put("b41_3_29", new hebsuperobject(41,3,29,"אך המגדף את רוח הקדש אין לו סליחה לעולם כי יאשם בעונו לנצח׃"));
hebsuperobject.biblemap.put("b41_3_30", new hebsuperobject(41,3,30,"כי המה אמרו רוח טמאה בו׃"));
hebsuperobject.biblemap.put("b41_3_31", new hebsuperobject(41,3,31,"ויבאו אמו ואחיו ויעמדו מחוץ לבית וישלחו אליו לקרא לו׃"));
hebsuperobject.biblemap.put("b41_3_32", new hebsuperobject(41,3,32,"והמון העם ישבו סביביו ויאמרו אליו הנה אמך ואחיך בחוץ מבקשים אותך׃"));
hebsuperobject.biblemap.put("b41_3_33", new hebsuperobject(41,3,33,"ויען ויאמר אליהם מי הם אמי ואחי׃"));
hebsuperobject.biblemap.put("b41_3_34", new hebsuperobject(41,3,34,"ויבט סביב אל הישבים סביביו ויאמר הנה אמי ואחי׃"));
hebsuperobject.biblemap.put("b41_3_35", new hebsuperobject(41,3,35,"כי כל אשר יעשה רצון האלהים הוא אחי ואחותי ואמי׃"));
hebsuperobject.biblemap.put("b41_4_1", new hebsuperobject(41,4,1,"וישב אל הים ויחל ללמד ויקהלו אליו המון עם רב עד אשר ירד לשבת באניה בים וכל העם עומד על חוף הים ביבשה׃"));
hebsuperobject.biblemap.put("b41_4_2", new hebsuperobject(41,4,2,"וילמדם הרבה במשלים ויאמר אליהם בלמדו אתם׃"));
hebsuperobject.biblemap.put("b41_4_3", new hebsuperobject(41,4,3,"שמעו שמוע הנה הזרע יצא לזרע׃"));
hebsuperobject.biblemap.put("b41_4_4", new hebsuperobject(41,4,4,"ויהי בזרעו ויפל מן הזרע על יד הדרך ויבא עוף השמים ויאכלהו׃"));
hebsuperobject.biblemap.put("b41_4_5", new hebsuperobject(41,4,5,"ויש אשר נפל על מקום הסלע אשר אין לו שם אדמה הרבה וימהר לצמח כי לא היה לו עמק אדמה׃"));
hebsuperobject.biblemap.put("b41_4_6", new hebsuperobject(41,4,6,"ויהי כזרח השמש ויצרב וייבש כי אין לו שרש׃"));
hebsuperobject.biblemap.put("b41_4_7", new hebsuperobject(41,4,7,"ויש אשר נפל בין הקצים ויעלו הקצים וימעכהו ולא נתן פרי׃"));
hebsuperobject.biblemap.put("b41_4_8", new hebsuperobject(41,4,8,"ויש אשר נפל על האדמה הטובה ויתן פרי עלה וגדל ויעש זה שלשים שערים וזה ששים וזה מאה׃"));
hebsuperobject.biblemap.put("b41_4_9", new hebsuperobject(41,4,9,"ויאמר אליהם מי אשר אזנים לו לשמע ישמע׃"));
hebsuperobject.biblemap.put("b41_4_10", new hebsuperobject(41,4,10,"ויהי בהיותו לבדו וישאלוהו האנשים אשר סביביו עם שנים העשר על המשל׃"));
hebsuperobject.biblemap.put("b41_4_11", new hebsuperobject(41,4,11,"ויאמר אליהם לכם נתן לדעת סוד מלכות האלהים ואשר בחוץ להם הכל במשלים׃"));
hebsuperobject.biblemap.put("b41_4_12", new hebsuperobject(41,4,12,"למען יראו ראו ולא ידעו ושמעו שמוע ולא יבינו פן ישובו ונסלח לחטאתם׃"));
hebsuperobject.biblemap.put("b41_4_13", new hebsuperobject(41,4,13,"ויאמר להם הן לא ידעתם את המשל הזה ואיך תבינו את המשלים כלם׃"));
hebsuperobject.biblemap.put("b41_4_14", new hebsuperobject(41,4,14,"הזרע הוא זרע את הדבר׃"));
hebsuperobject.biblemap.put("b41_4_15", new hebsuperobject(41,4,15,"ואלה הם הנזרעים על יד הדרך אשר יזרע בם הדבר וכשמעם אותו מיד בא השטן וישא את הדבר הזרוע בלבבם׃"));
hebsuperobject.biblemap.put("b41_4_16", new hebsuperobject(41,4,16,"וכן הנזרעים על מקמות הסלע הם השמעים את הדבר ומהר בשמחה יקחהו׃"));
hebsuperobject.biblemap.put("b41_4_17", new hebsuperobject(41,4,17,"אך אין להם שרש בקרבם ורק לשעה יעמדו ואחר כן בהיות צרה ורדיפה על אדות הדבר מהרה יכשלו׃"));
hebsuperobject.biblemap.put("b41_4_18", new hebsuperobject(41,4,18,"והאחרים הנזרעים בין הקצים הם השמעים את הדבר׃"));
hebsuperobject.biblemap.put("b41_4_19", new hebsuperobject(41,4,19,"ודאגות העולם הזה ומרמת העשר ותאות שאר הדברים באות וממעכות את הדבר ופרי לא יהיה לו׃"));
hebsuperobject.biblemap.put("b41_4_20", new hebsuperobject(41,4,20,"ואלה המזרעים על האדמה הטובה הם השמעים את הדבר ומקבלים אתו ועשים פרי לשלשים שערים ולששים ולמאה׃"));
hebsuperobject.biblemap.put("b41_4_21", new hebsuperobject(41,4,21,"ויאמר אליהם הכי יביאו הנר למען יושם תחת האיפה ותחת המטה ולא למען יעלהו על המנורה׃"));
hebsuperobject.biblemap.put("b41_4_22", new hebsuperobject(41,4,22,"כי אין דבר סתום אשר לא יגלה ולא נעלם דבר כי אם למען יבא לגלוי׃"));
hebsuperobject.biblemap.put("b41_4_23", new hebsuperobject(41,4,23,"כל אשר אזנים לו לשמע ישמע׃"));
hebsuperobject.biblemap.put("b41_4_24", new hebsuperobject(41,4,24,"ויאמר אליהם ראו מה אתם שמעים במדה אשר אתם מודדים בה ימד לכם ועוד יוסף לכם השמעים׃"));
hebsuperobject.biblemap.put("b41_4_25", new hebsuperobject(41,4,25,"כי מי שיש לו נתון ינתן לו ומי שאין לו גם את אשר יש לו יקח ממנו׃"));
hebsuperobject.biblemap.put("b41_4_26", new hebsuperobject(41,4,26,"ויאמר מלכות האלהים היא כאשר ישליך איש זרע על האדמה׃"));
hebsuperobject.biblemap.put("b41_4_27", new hebsuperobject(41,4,27,"וישן וקם לילה ויום והזרע יצמח וגדל והוא לא ידע׃"));
hebsuperobject.biblemap.put("b41_4_28", new hebsuperobject(41,4,28,"כי הארץ מאליה מוציאה פריה את הדשא ראשונה ואחריו את השבלת ואחרי כן את החטה המלאה בשבלת׃"));
hebsuperobject.biblemap.put("b41_4_29", new hebsuperobject(41,4,29,"וכאשר גמל הפרי ימהר לשלח את המגל כי בשל הקציר׃"));
hebsuperobject.biblemap.put("b41_4_30", new hebsuperobject(41,4,30,"ויאמר אל מה נדמה את מלכות האלהים ובאי זה משל נמשילנה׃"));
hebsuperobject.biblemap.put("b41_4_31", new hebsuperobject(41,4,31,"כגרגר של חרדל אשר יזרע באדמה והוא קטן מכל הזרעים אשר על הארץ׃"));
hebsuperobject.biblemap.put("b41_4_32", new hebsuperobject(41,4,32,"ואחרי הזרעו יעלה ויגדל על כל הירקות ועשה ענפים גדולים עד אשר יוכלו עוף השמים לקנן בצלו׃"));
hebsuperobject.biblemap.put("b41_4_33", new hebsuperobject(41,4,33,"ובמשלים רבים כאלה דבר אליהם את הדבר כפי אשר יכלו לשמע׃"));
hebsuperobject.biblemap.put("b41_4_34", new hebsuperobject(41,4,34,"ובבלי משל לא דבר אליהם והיה בהיותו עם תלמידיו לבדם יבאר להם את הכל׃"));
hebsuperobject.biblemap.put("b41_4_35", new hebsuperobject(41,4,35,"ויאמר אליהם ביום ההוא לפנות ערב נעברה העבר׃"));
hebsuperobject.biblemap.put("b41_4_36", new hebsuperobject(41,4,36,"ויעזבו את המון העם ויקחו אתו כאשר הוא באניה וגם אניות אחרות הלכו עמו׃"));
hebsuperobject.biblemap.put("b41_4_37", new hebsuperobject(41,4,37,"ותקם רוח סערה גדולה וישטפו הגלים אל תוך האניה עד אשר כמעט נמלאה׃"));
hebsuperobject.biblemap.put("b41_4_38", new hebsuperobject(41,4,38,"והוא ישן על הכסת באחרי האניה ויעירו אותו ויאמרו אליו רבי האינך דאג לנו כי נאבד׃"));
hebsuperobject.biblemap.put("b41_4_39", new hebsuperobject(41,4,39,"ויעור ויגער ברוח ויאמר אל הים הס ודם ותשך הרוח ותהי דממה גדולה׃"));
hebsuperobject.biblemap.put("b41_4_40", new hebsuperobject(41,4,40,"ויאמר אליהם למה ככה אתם חרדים איך אין לכם אמונה׃"));
hebsuperobject.biblemap.put("b41_4_41", new hebsuperobject(41,4,41,"וייראו יראה גדולה ויאמרו איש אל רעהו מי אפוא הוא אשר גם הרוח והים שמעים לו׃"));
hebsuperobject.biblemap.put("b41_5_1", new hebsuperobject(41,5,1,"ויבאו אל עבר הים אל ארץ הגדרים׃"));
hebsuperobject.biblemap.put("b41_5_2", new hebsuperobject(41,5,2,"והוא יצא מן האניה והנה איש בא לקראתו מבין הקברים אשר רוח טמאה בו׃"));
hebsuperobject.biblemap.put("b41_5_3", new hebsuperobject(41,5,3,"ומושבו בקברים וגם בעבתים לא יכל איש לאסרו׃"));
hebsuperobject.biblemap.put("b41_5_4", new hebsuperobject(41,5,4,"כי פעמים הרבה אסרוהו בכבלים ובעבתים וינתק את העבתים וישבר את הכבלים ואין איש יכל לכבשו׃"));
hebsuperobject.biblemap.put("b41_5_5", new hebsuperobject(41,5,5,"ותמיד לילה ויומם היה בהרים ובקברים צעק ופצע את עצמו באבנים׃"));
hebsuperobject.biblemap.put("b41_5_6", new hebsuperobject(41,5,6,"ויהי כראותו את ישוע מרחוק וירץ וישתחו לו׃"));
hebsuperobject.biblemap.put("b41_5_7", new hebsuperobject(41,5,7,"ויצעק בקול גדול ויאמר מה לי ולך ישוע בן אל עליון באלהים אני משביעך אשר לא תענני׃"));
hebsuperobject.biblemap.put("b41_5_8", new hebsuperobject(41,5,8,"כי הוא אמר אליו צא רוח טמא מן האדם הזה׃"));
hebsuperobject.biblemap.put("b41_5_9", new hebsuperobject(41,5,9,"וישאל אתו מה שמך ויען ויאמר לגיון שמי כי רבים אנחנו׃"));
hebsuperobject.biblemap.put("b41_5_10", new hebsuperobject(41,5,10,"ויתחנן אליו מאד לבלתי שלחם אל מחוץ לארץ׃"));
hebsuperobject.biblemap.put("b41_5_11", new hebsuperobject(41,5,11,"ועדר חזירים רבים היה שם במרעה ההרים׃"));
hebsuperobject.biblemap.put("b41_5_12", new hebsuperobject(41,5,12,"ויתחננו לו כל השדים לאמר שלחנו אל החזירים ונבאה אל תוכם׃"));
hebsuperobject.biblemap.put("b41_5_13", new hebsuperobject(41,5,13,"וינח להם ויצאו רוחות הטמאה ויבאו בחזירים וישתער העדר מן המורד אל הים כאלפים במספר ויטבעו בים׃"));
hebsuperobject.biblemap.put("b41_5_14", new hebsuperobject(41,5,14,"וינוסו רעי החזירים ויגידו זאת בעיר ובשדות ויצאו לראות מה נהיתה׃"));
hebsuperobject.biblemap.put("b41_5_15", new hebsuperobject(41,5,15,"ויבאו אל ישוע ויראו את אחוז השדים אשר הלגיון בו והוא יושב מלבש וטוב שכל וייראו׃"));
hebsuperobject.biblemap.put("b41_5_16", new hebsuperobject(41,5,16,"ויספרו להם הראים את אשר נעשה לאחוז השדים ואת דבר החזירים׃"));
hebsuperobject.biblemap.put("b41_5_17", new hebsuperobject(41,5,17,"ויחלו להתחנן לו לסור מגבוליהם׃"));
hebsuperobject.biblemap.put("b41_5_18", new hebsuperobject(41,5,18,"ויהי ברדתו אל האניה התחנן אליו האיש אשר היה אחוז שדים לתתו לשבת עמו׃"));
hebsuperobject.biblemap.put("b41_5_19", new hebsuperobject(41,5,19,"ולא הניח לו כי אם אמר אליו שוב לביתך אל בני משפחתך והגד להם את הגדלות אשר עשה לך יהוה ויחנך׃"));
hebsuperobject.biblemap.put("b41_5_20", new hebsuperobject(41,5,20,"וילך לו ויחל לקרא בעשר הערים את הגדלות אשר עשה לו ישוע ויתמהו כלם׃"));
hebsuperobject.biblemap.put("b41_5_21", new hebsuperobject(41,5,21,"וישב ישוע לעבר באניה אל עבר הים ויקהל אליו המון רב והוא על שפת הים׃"));
hebsuperobject.biblemap.put("b41_5_22", new hebsuperobject(41,5,22,"והנה בא אחד מראשי הכנסת ושמו יאיר וירא אתו ויפל לרגליו׃"));
hebsuperobject.biblemap.put("b41_5_23", new hebsuperobject(41,5,23,"ויתחנן אליו מאד לאמר בתי הקטנה חלתה עד למות אנא בוא נא ושים ידיך עליה למען תרפא ותחיה׃"));
hebsuperobject.biblemap.put("b41_5_24", new hebsuperobject(41,5,24,"וילך אתו וילכו אחריו המון רב וידחקהו׃"));
hebsuperobject.biblemap.put("b41_5_25", new hebsuperobject(41,5,25,"ואשה היתה זבת דם שתים עשרה שנה׃"));
hebsuperobject.biblemap.put("b41_5_26", new hebsuperobject(41,5,26,"והיא סבלה הרבה תחת ידי רפאים רבים והוציאה את כל אשר לה ולא להועיל ויהי חליה חזק מאד׃"));
hebsuperobject.biblemap.put("b41_5_27", new hebsuperobject(41,5,27,"ויהי כשמעה את שמע ישוע ותבוא בהמון העם מאחריו ותגע בבגדו׃"));
hebsuperobject.biblemap.put("b41_5_28", new hebsuperobject(41,5,28,"כי אמרה רק אם אגע בבגדיו אושע׃"));
hebsuperobject.biblemap.put("b41_5_29", new hebsuperobject(41,5,29,"וייבש מקור דמיה פתאם ותבן בבשרה כי נרפא נגעה׃"));
hebsuperobject.biblemap.put("b41_5_30", new hebsuperobject(41,5,30,"וברגע ידע ישוע בנפשו כי גבורה יצאה ממנו ויפן בתוך העם ויאמר מי נגע בבגדי׃"));
hebsuperobject.biblemap.put("b41_5_31", new hebsuperobject(41,5,31,"ויאמר אליו תלמידיו אתה ראה את ההמון דוחק אתך ואמרת מי נגע בי׃"));
hebsuperobject.biblemap.put("b41_5_32", new hebsuperobject(41,5,32,"ויבט סביב לראות את אשר עשתה זאת׃"));
hebsuperobject.biblemap.put("b41_5_33", new hebsuperobject(41,5,33,"ותירא האשה ותחרד כי ידעה את אשר נעשה לה ותבא ותפל לפניו ותגד לו את האמת כלה׃"));
hebsuperobject.biblemap.put("b41_5_34", new hebsuperobject(41,5,34,"ויאמר אליה בתי אמונתך הושיעה לך לכי לשלום וחיית מנגעך׃"));
hebsuperobject.biblemap.put("b41_5_35", new hebsuperobject(41,5,35,"עודנו מדבר והנה באים מבית ראש הכנסת לאמר בתך מתה למה תטריח עוד את המורה׃"));
hebsuperobject.biblemap.put("b41_5_36", new hebsuperobject(41,5,36,"וכשמע ישוע את הדבר אשר דברו ויאמר אל ראש הכנסת אל תירא רק האמינה׃"));
hebsuperobject.biblemap.put("b41_5_37", new hebsuperobject(41,5,37,"ולא הניח לאיש ללכת אתו בלתי אם לפטרוס וליעקב וליוחנן אחי יעקב׃"));
hebsuperobject.biblemap.put("b41_5_38", new hebsuperobject(41,5,38,"ויבא בית ראש הכנסת וירא המון הבכים והמיללים הרבה׃"));
hebsuperobject.biblemap.put("b41_5_39", new hebsuperobject(41,5,39,"ובבאו אמר אליהם מה תהמו ותבכו הנערה לא מתה אך ישנה היא׃"));
hebsuperobject.biblemap.put("b41_5_40", new hebsuperobject(41,5,40,"וישחקו לו והוא גרש את כלם ויקח את אבי הנערה ואת אמה ואת אשר אתו ויבא החדרה אשר שם שכבת הנערה׃"));
hebsuperobject.biblemap.put("b41_5_41", new hebsuperobject(41,5,41,"ויאחז ביד הנערה ויאמר אליה טליתא קומי אשר פרושו הילדה אני אמר לך קומי נא׃"));
hebsuperobject.biblemap.put("b41_5_42", new hebsuperobject(41,5,42,"ומיד קמה הילדה ותתהלך והיא בת שתים עשרה שנה וישמו שמה גדולה׃"));
hebsuperobject.biblemap.put("b41_5_43", new hebsuperobject(41,5,43,"ויזהר אותם מאד שלא יודע הדבר לאיש ויאמר לתת לה לאכול׃"));
hebsuperobject.biblemap.put("b41_6_1", new hebsuperobject(41,6,1,"ויצא משם ויבא אל ארצו וילכו אחריו תלמידיו׃"));
hebsuperobject.biblemap.put("b41_6_2", new hebsuperobject(41,6,2,"וביום השבת החל ללמד בבית הכנסת וישמעו רבים וישתוממו לאמר מאין לזה כאלה ומה היא החכמה הנתונה לו עד אשר נעשו גבורות כאלה על ידיו׃"));
hebsuperobject.biblemap.put("b41_6_3", new hebsuperobject(41,6,3,"הלא זה הוא החרש בן מרים ואחי יעקב ויוסי ויהודה ושמעון והלא אחיותיו אתנו פה ויהי להם למכשול׃"));
hebsuperobject.biblemap.put("b41_6_4", new hebsuperobject(41,6,4,"ויאמר אליהם ישוע אין הנביא נקלה כי אם בארצו ובין קרוביו ובביתו׃"));
hebsuperobject.biblemap.put("b41_6_5", new hebsuperobject(41,6,5,"ולא יכל לעשות שם פלא רק על חלשים מעטים שם את ידיו וירפאם׃"));
hebsuperobject.biblemap.put("b41_6_6", new hebsuperobject(41,6,6,"ויתמה על חסרון אמונתם ויסב בכפרים סבוב ולמד׃"));
hebsuperobject.biblemap.put("b41_6_7", new hebsuperobject(41,6,7,"ויקרא אל שנים העשר ויחל לשלח אותם שנים שנים ויתן להם שלטן על רוחות הטמאה׃"));
hebsuperobject.biblemap.put("b41_6_8", new hebsuperobject(41,6,8,"ויצו אותם אשר לא ישאו מאומה לדרך זולתי מקל לבדו לא תרמיל ולא לחם ולא נחשת בחגורה׃"));
hebsuperobject.biblemap.put("b41_6_9", new hebsuperobject(41,6,9,"רק להיות נעולי סנדל ושתי כתנות לא ילבשו׃"));
hebsuperobject.biblemap.put("b41_6_10", new hebsuperobject(41,6,10,"ויאמר אליהם במקום אשר תבאו בית איש שבו בו עד כי תצאו משם׃"));
hebsuperobject.biblemap.put("b41_6_11", new hebsuperobject(41,6,11,"וכל אשר לא יקבלו אתכם ולא ישמעו אליכם צאו משם ונערו את עפר כפות רגליכם לעדות להם אמן אני אמר לכם לסדם ולעמרה יקל ביום הדין מן העיר ההיא׃"));
hebsuperobject.biblemap.put("b41_6_12", new hebsuperobject(41,6,12,"ויצאו ויקראו לשוב בתשובה׃"));
hebsuperobject.biblemap.put("b41_6_13", new hebsuperobject(41,6,13,"ויגרשו שדים רבים ויסוכו בשמן חלשים רבים וירפאום׃"));
hebsuperobject.biblemap.put("b41_6_14", new hebsuperobject(41,6,14,"וישמע עליו המלך הורדוס כי נודע שמו ויאמר יוחנן הטובל קם מן המתים ועל כן פעלות בו הגבורות׃"));
hebsuperobject.biblemap.put("b41_6_15", new hebsuperobject(41,6,15,"ואחרים אמרו כי הוא אליהו ואחרים אמרו כי נביא הוא או כאחד הנביאים׃"));
hebsuperobject.biblemap.put("b41_6_16", new hebsuperobject(41,6,16,"וישמע הורדוס ויאמר יוחנן אשר אנכי נשאתי את ראשו מעליו הוא קם מן המתים׃"));
hebsuperobject.biblemap.put("b41_6_17", new hebsuperobject(41,6,17,"כי הוא הורודס שלח לתפש את יוחנן ויאסרהו בבית הסהר בגלל הורודיה אשת פילפוס אחיו כי אתה לקח לו לאשה׃"));
hebsuperobject.biblemap.put("b41_6_18", new hebsuperobject(41,6,18,"יען אשר אמר יוחנן אל הורדוס אשת אחיך איננה מתרת לך׃"));
hebsuperobject.biblemap.put("b41_6_19", new hebsuperobject(41,6,19,"ותשטם אותו הורודיה ותבקש המיתו ולא יכלה׃"));
hebsuperobject.biblemap.put("b41_6_20", new hebsuperobject(41,6,20,"כי הורדוס ירא את יוחנן בדעתו כי הוא איש צדיק וקדוש ויגן בעדו והרבה עשה בשמעו אליו ויאהב לשמע אתו׃"));
hebsuperobject.biblemap.put("b41_6_21", new hebsuperobject(41,6,21,"ויבא היום המכשר כי הורדוס ביום הלדת אתו עשה משתה לגדוליו ולשרי האלפים ולראשי הגליל׃"));
hebsuperobject.biblemap.put("b41_6_22", new hebsuperobject(41,6,22,"ותבא בת הורודיה ותרקד ותיטב בעיני הורדוס ובעיני המסבים עמו ויאמר המלך אל הנערה שאלי ממני את אשר תחפצי ואתן לך׃"));
hebsuperobject.biblemap.put("b41_6_23", new hebsuperobject(41,6,23,"וישבע לה לאמר כל אשר תשאלי ממני אתן לך עד חצי מלכותי׃"));
hebsuperobject.biblemap.put("b41_6_24", new hebsuperobject(41,6,24,"ותצא ותאמר לאמה מה אשאל ותאמר את ראש יוחנן המטביל׃"));
hebsuperobject.biblemap.put("b41_6_25", new hebsuperobject(41,6,25,"ותמהר מאד לבוא אל המלך ותשאל לאמר רצוני אשר תתן לי עתה בקערה את ראש יוחנן המטביל׃"));
hebsuperobject.biblemap.put("b41_6_26", new hebsuperobject(41,6,26,"ויתעצב המלך מאד אך בעבור השבועה והמסבים עמו לא רצה להשיב פניה׃"));
hebsuperobject.biblemap.put("b41_6_27", new hebsuperobject(41,6,27,"ומיד שלח המלך אחד הטבחים ויצוהו להביא את ראשו׃"));
hebsuperobject.biblemap.put("b41_6_28", new hebsuperobject(41,6,28,"וילך ויכרת את ראשו בבית הסהר ויביאהו בקערה ויתנהו לנערה והנערה נתנה אתו אל אמה׃"));
hebsuperobject.biblemap.put("b41_6_29", new hebsuperobject(41,6,29,"וישמעו תלמידיו ויבאו וישאו את גויתו וישימוה בקבר׃"));
hebsuperobject.biblemap.put("b41_6_30", new hebsuperobject(41,6,30,"ויקהלו השליחים אל ישוע ויגידו לו את כל אשר עשו ואת אשר למדו׃"));
hebsuperobject.biblemap.put("b41_6_31", new hebsuperobject(41,6,31,"ויאמר אליהם באו אתם לבדד אל מקום חרבה ונוחו מעט כי רבים היו הבאים והיצאים עד לאין עת להם לאכול׃"));
hebsuperobject.biblemap.put("b41_6_32", new hebsuperobject(41,6,32,"וילכו משם באניה אל מקום חרבה לבדד׃"));
hebsuperobject.biblemap.put("b41_6_33", new hebsuperobject(41,6,33,"וההמון ראה אותם יצאים ויכירהו רבים וירוצו שמה ברגליהם מכל הערים ויעברו אותם ויאספו אליו׃"));
hebsuperobject.biblemap.put("b41_6_34", new hebsuperobject(41,6,34,"ויצא וירא המון עם רב ויהמו מעיו עליהם כי היו כצאן אשר אין להם רעה ויחל ללמד אותם דברים הרבה׃"));
hebsuperobject.biblemap.put("b41_6_35", new hebsuperobject(41,6,35,"ויהי כאשר רפה היום לערוב ויגשו אליו תלמידיו לאמר הנה המקום חרב והיום רד מאד׃"));
hebsuperobject.biblemap.put("b41_6_36", new hebsuperobject(41,6,36,"שלח אותם וילכו אל החצרים והכפרים מסביב לקנות להם לחם כי אין להם מה לאכל׃"));
hebsuperobject.biblemap.put("b41_6_37", new hebsuperobject(41,6,37,"ויען ויאמר אליהם תנו אתם להם לאכלה ויאמרו אליו הנלך לקנות לחם במאתים דינר ונתן להם לאכלה׃"));
hebsuperobject.biblemap.put("b41_6_38", new hebsuperobject(41,6,38,"ויאמר אליהם כמה ככרות לחם יש לכם לכו וראו וידעו ויאמרו חמש ושני דגים׃"));
hebsuperobject.biblemap.put("b41_6_39", new hebsuperobject(41,6,39,"ויצו אותם לשבת כלם חברה חברה לבדה על ירק הדשא׃"));
hebsuperobject.biblemap.put("b41_6_40", new hebsuperobject(41,6,40,"וישבו להם שורות שורות למאות ולחמשים׃"));
hebsuperobject.biblemap.put("b41_6_41", new hebsuperobject(41,6,41,"ויקח את חמשת ככרות הלחם ואת שני הדגים וישא עיניו השמימה ויברך ויפרס את הלחם ויתן לתלמידיו לשום לפניהם ואת שני הדגים חלק לכלם׃"));
hebsuperobject.biblemap.put("b41_6_42", new hebsuperobject(41,6,42,"ויאכלו כלם וישבעו׃"));
hebsuperobject.biblemap.put("b41_6_43", new hebsuperobject(41,6,43,"וישאו מן הפתותים מלוא סלים שנים עשר וגם מן הדגים׃"));
hebsuperobject.biblemap.put("b41_6_44", new hebsuperobject(41,6,44,"והאכלים מן הלחם היו כחמשת אלפי איש׃"));
hebsuperobject.biblemap.put("b41_6_45", new hebsuperobject(41,6,45,"ואחרי כן האיץ בתלמידיו לרדת באניה ולעבור לפניו אל עבר הים אל בית צידה עד שלחו את העם׃"));
hebsuperobject.biblemap.put("b41_6_46", new hebsuperobject(41,6,46,"ויהי אחר שלחו אתם ויעל ההרה להתפלל׃"));
hebsuperobject.biblemap.put("b41_6_47", new hebsuperobject(41,6,47,"ויהי ערב והאניה באה בתוך הים והוא לבדו ביבשה׃"));
hebsuperobject.biblemap.put("b41_6_48", new hebsuperobject(41,6,48,"וירא אותם מתעמלים בשוטם כי הרוח לנגדם ויהי כעת האשמרת הרביעית ויבא אליהם מתהלך על פני הים ויואל לעבור לפניהם׃"));
hebsuperobject.biblemap.put("b41_6_49", new hebsuperobject(41,6,49,"והם בראתם אתו מתהלך על פני הים חשבו כי מראה רוח הוא ויצעקו׃"));
hebsuperobject.biblemap.put("b41_6_50", new hebsuperobject(41,6,50,"כי כלם ראוהו ויבהלו אז דבר אתם ויאמר אליהם חזקו כי אני הוא אל תיראו׃"));
hebsuperobject.biblemap.put("b41_6_51", new hebsuperobject(41,6,51,"וירד אליהם אל האניה והרוח שככה וישתוממו עוד יותר בלבבם ויתמהו׃"));
hebsuperobject.biblemap.put("b41_6_52", new hebsuperobject(41,6,52,"כי לא השכילו בדבר ככרות הלחם מפני טמטום לבבם׃"));
hebsuperobject.biblemap.put("b41_6_53", new hebsuperobject(41,6,53,"ויעברו את הים ויבאו ארצה גניסר ויקרבו אל היבשה׃"));
hebsuperobject.biblemap.put("b41_6_54", new hebsuperobject(41,6,54,"ויהי כצאתם מן האניה אז הכירהו׃"));
hebsuperobject.biblemap.put("b41_6_55", new hebsuperobject(41,6,55,"וירוצו בכל סביבותיהם ויחלו לשאת את החולים במשכבות אל כל מקום אשר שמעו כי שם הוא׃"));
hebsuperobject.biblemap.put("b41_6_56", new hebsuperobject(41,6,56,"ובכל מקום אשר יבא אל הכפרים או הערים ואל השדות שם שמו את החולים בחוצות ויתחננו לו כי יגעו רק בציצת בגדו והיה כל אשר נגעו ונושעו׃"));
hebsuperobject.biblemap.put("b41_7_1", new hebsuperobject(41,7,1,"ויקהלו אליו הפרושים ומן הסופרים אשר באו מירושלים׃"));
hebsuperobject.biblemap.put("b41_7_2", new hebsuperobject(41,7,2,"ויהי כראותם מתלמידיו אכלים לחם בטמאת ידיהם בלא נטילה ויוכיחו אתם׃"));
hebsuperobject.biblemap.put("b41_7_3", new hebsuperobject(41,7,3,"כי הפרושים וכל היהודים לא יאכלו בלתי את רחצו את ידיהם עד הפרק באחזם בקבלת הזקנים׃"));
hebsuperobject.biblemap.put("b41_7_4", new hebsuperobject(41,7,4,"ואת אשר מן השוק אינם אכלים בלא טבילה ועוד דברים אחרים רבים אשר קבלו לשמר כמו טבילת כסות וכדים ויורות ומטות׃"));
hebsuperobject.biblemap.put("b41_7_5", new hebsuperobject(41,7,5,"וישאלו אותו הפרושים והסופרים מדוע תלמידיך אינם נהגים על פי קבלת הזקנים כי אכלים לחם בלא נטבילת ידים׃"));
hebsuperobject.biblemap.put("b41_7_6", new hebsuperobject(41,7,6,"ויען ויאמר אליהם היטב נבא ישעיהו עליכם החנפים ככתוב העם הזה בשפתיו כבדוני ולבו רחק ממני׃"));
hebsuperobject.biblemap.put("b41_7_7", new hebsuperobject(41,7,7,"ותהו יראתם אתי מצות אנשים מלמדים׃"));
hebsuperobject.biblemap.put("b41_7_8", new hebsuperobject(41,7,8,"כי עזבתם את מצות אלהים לאחז בקבלת בני אדם טבילות כדים וכסות וכאלה רבות אתם עשים׃"));
hebsuperobject.biblemap.put("b41_7_9", new hebsuperobject(41,7,9,"ויאמר אליהם מה יפה עשיתם אשר בטלתם את מצות האלהים כדי שתשמרו את קבלתכם׃"));
hebsuperobject.biblemap.put("b41_7_10", new hebsuperobject(41,7,10,"כי משה אמר כבד את אביך ואת אמך ומקלל אביו ואמו מות יומת׃"));
hebsuperobject.biblemap.put("b41_7_11", new hebsuperobject(41,7,11,"ואתם אמרים איש כי יאמר לאביו ולאמו קרבן פרושו מתנה לאלהים כל מה שאתה נהנה לי׃"));
hebsuperobject.biblemap.put("b41_7_12", new hebsuperobject(41,7,12,"ולא תניחו לו לעשות עוד מאומה לאביו ולאמו׃"));
hebsuperobject.biblemap.put("b41_7_13", new hebsuperobject(41,7,13,"ותפרו את דבר האלהים על ידי קבלתכם אשר קבלתם והרבה כאלה אתם עשים׃"));
hebsuperobject.biblemap.put("b41_7_14", new hebsuperobject(41,7,14,"ויקרא אל כל העם ויאמר אליהם שמעו אלי כלכם והבינו׃"));
hebsuperobject.biblemap.put("b41_7_15", new hebsuperobject(41,7,15,"אין דבר מחוץ לאדם אשר יוכל לטמא אותו בבאו אל קרבו כי אם הדברים היוצאים ממנו המה יטמאו את האדם׃"));
hebsuperobject.biblemap.put("b41_7_16", new hebsuperobject(41,7,16,"כל אשר אזנים לו לשמע ישמע׃"));
hebsuperobject.biblemap.put("b41_7_17", new hebsuperobject(41,7,17,"ויהי כאשר שב הביתה מן ההמון וישאלהו תלמידיו על דבר המשל׃"));
hebsuperobject.biblemap.put("b41_7_18", new hebsuperobject(41,7,18,"ויאמר אליהם האף אתם חסרי בינה הלא תשכילו כי כל הבא את תוך האדם מחוצה לו לא יטמאנו׃"));
hebsuperobject.biblemap.put("b41_7_19", new hebsuperobject(41,7,19,"כי לא יבוא אל לבו כי אם אל כרשו ויצא למוצאות להבר כל אכל׃"));
hebsuperobject.biblemap.put("b41_7_20", new hebsuperobject(41,7,20,"ויאמר היצא מן האדם הוא מטמא את האדם׃"));
hebsuperobject.biblemap.put("b41_7_21", new hebsuperobject(41,7,21,"]22-12[ כי מתוך לב האדם יצאות המחשבות הרעות נאף וזנה ורצוח וגנוב ואהבת בצע ורשעה ורמיה וזוללות וצרות עין וגדוף וזדון וסכלות׃"));
hebsuperobject.biblemap.put("b41_7_22", new hebsuperobject(41,7,22,"]22-12[׃"));
hebsuperobject.biblemap.put("b41_7_23", new hebsuperobject(41,7,23,"כל הרעות האלה מקרב האדם הן יוצאות ומטמאות אתו׃"));
hebsuperobject.biblemap.put("b41_7_24", new hebsuperobject(41,7,24,"ויקם משם וילך לו אל גבולות צור וצידון ובבואו הביתה לא אבה כי יודע לאיש ולא יכל להסתר׃"));
hebsuperobject.biblemap.put("b41_7_25", new hebsuperobject(41,7,25,"כי אשה אשר רוח טמאה נכנסה בבתה הקטנה שמעה את שמעו ותבא ותפל לרגליו׃"));
hebsuperobject.biblemap.put("b41_7_26", new hebsuperobject(41,7,26,"והאשה יונית וארץ מולדתה כנען אשר לסוריא ותבקש ממנו לגרש אר השד מבתה׃"));
hebsuperobject.biblemap.put("b41_7_27", new hebsuperobject(41,7,27,"ויאמר אליה ישוע הניחו לשבע בראשונה הבנים כי לא טוב לקחת לחם הבנים ולהשליכו לצעירי הכלבים׃"));
hebsuperobject.biblemap.put("b41_7_28", new hebsuperobject(41,7,28,"ותען ותאמר אליו כן אדני אבל גם צעירי הכלבים יאכלו תחת השלחן מפרורי לחם הבנים׃"));
hebsuperobject.biblemap.put("b41_7_29", new hebsuperobject(41,7,29,"ויאמר אליה בגלל דברך זה לכי לך יצא השד מבתך׃"));
hebsuperobject.biblemap.put("b41_7_30", new hebsuperobject(41,7,30,"ותבא אל ביתה ותמצא את הילדה משכבת על חמטה והשד יצא ממנה׃"));
hebsuperobject.biblemap.put("b41_7_31", new hebsuperobject(41,7,31,"וישב ויצא מגבול צור וצידון ויבא אל ים הגליל בתוך גבול עשר הערים׃"));
hebsuperobject.biblemap.put("b41_7_32", new hebsuperobject(41,7,32,"ויביאו אליו איש אשר היה חרש ואלם ויתחננו לו לשום עליו את ידו׃"));
hebsuperobject.biblemap.put("b41_7_33", new hebsuperobject(41,7,33,"ויקח אתו לבדו מקרב ההמון וישם את אצבעותיו באזניו וירק ויגע על לשנו׃"));
hebsuperobject.biblemap.put("b41_7_34", new hebsuperobject(41,7,34,"ויבט השמימה ויאנח ויאמר אליו אפתח ופרושו הפתח׃"));
hebsuperobject.biblemap.put("b41_7_35", new hebsuperobject(41,7,35,"וברגע נפתחו אזניו ויתר קשר לשונו וידבר בשפה ברורה׃"));
hebsuperobject.biblemap.put("b41_7_36", new hebsuperobject(41,7,36,"ויזהר אותם כי לא יספרו לאיש וכאשר יזהירם כן ירבו להכריז׃"));
hebsuperobject.biblemap.put("b41_7_37", new hebsuperobject(41,7,37,"וישתוממו עד מאד ויאמרו את הכל עשה יפה גם החרשים הוא עשה לשמעים גם האלמים למדברים׃"));
hebsuperobject.biblemap.put("b41_8_1", new hebsuperobject(41,8,1,"ויהי בימים ההם בהקבץ עם רב ואין להם מה יאכלו ויקרא אל תלמידיו ויאמר אליהם׃"));
hebsuperobject.biblemap.put("b41_8_2", new hebsuperobject(41,8,2,"נכמרו רחמי על העם כי זה שלשת ימים עמדו עמדי ואין להם לחם לאכל׃"));
hebsuperobject.biblemap.put("b41_8_3", new hebsuperobject(41,8,3,"והיה בשלחי אותם רעבים לבתיהם יתעלפו בדרך כי יש מהם אשר באו ממרחק׃"));
hebsuperobject.biblemap.put("b41_8_4", new hebsuperobject(41,8,4,"ויענו אתו תלמידיו מאין יוכל איש להשביע את אלה פה במדבר לחם׃"));
hebsuperobject.biblemap.put("b41_8_5", new hebsuperobject(41,8,5,"וישאל אותם כמה ככרות לחם יש לכם ויאמרו שבע׃"));
hebsuperobject.biblemap.put("b41_8_6", new hebsuperobject(41,8,6,"ויצו את העם לשבת לארץ ויקח את שבע ככרות הלחם ויברך ויפרס ויתן אותם לתלמידיו לשום לפניהם וישימו לפני העם׃"));
hebsuperobject.biblemap.put("b41_8_7", new hebsuperobject(41,8,7,"ויהי להם מעט דגים קטנים ויברך ויאמר לשום לפניהם גם את אלה׃"));
hebsuperobject.biblemap.put("b41_8_8", new hebsuperobject(41,8,8,"ויאכלו וישבעו וישאו מן הפתותים הנותרים שבעת דודים׃"));
hebsuperobject.biblemap.put("b41_8_9", new hebsuperobject(41,8,9,"והאכלים היו כארבעת אלפי איש וישלחם׃"));
hebsuperobject.biblemap.put("b41_8_10", new hebsuperobject(41,8,10,"אז ירד באניה עם תלמידיו ויבא אל גלילות דלמונתא׃"));
hebsuperobject.biblemap.put("b41_8_11", new hebsuperobject(41,8,11,"ויצאו הפרושים ויחלו להתוכח אתו וישאלו מעמו אות מן השמים והם מנסים אתו׃"));
hebsuperobject.biblemap.put("b41_8_12", new hebsuperobject(41,8,12,"ויאנח ברוחו ויאמר מה הדור הזה מבקש לו אות אמן אמר אני לכם אם ינתן אות לדור הזה׃"));
hebsuperobject.biblemap.put("b41_8_13", new hebsuperobject(41,8,13,"ויעזב אותם וירד באניה וישב ויעבר אל עבר הים׃"));
hebsuperobject.biblemap.put("b41_8_14", new hebsuperobject(41,8,14,"וישכחו לקחת אתם לחם ולא היה להם באניה בלתי אם ככר לחם אחת׃"));
hebsuperobject.biblemap.put("b41_8_15", new hebsuperobject(41,8,15,"ויזהר אותם לאמר ראו השמרו לכם משאר הפרושים ומשאר הורדוס׃"));
hebsuperobject.biblemap.put("b41_8_16", new hebsuperobject(41,8,16,"ויחשבו ויאמרו איש אל רעהו על כי לחם אין אתנו׃"));
hebsuperobject.biblemap.put("b41_8_17", new hebsuperobject(41,8,17,"וידע ישוע ויאמר להם מה תחשבו על כי לחם אין לכם העוד לא תשכילו ולא תבינו ולבכם עודנו מטמטם׃"));
hebsuperobject.biblemap.put("b41_8_18", new hebsuperobject(41,8,18,"עינים לכם ולא תראו ואזנים לכם ולא תשמעו ולא תזכרו׃"));
hebsuperobject.biblemap.put("b41_8_19", new hebsuperobject(41,8,19,"כאשר פרסתי את חמשת ככרות הלחם לחמשת אלפי איש כמה סלים מלאי פתותים נשאתם ויאמרו אליו שנים עשר׃"));
hebsuperobject.biblemap.put("b41_8_20", new hebsuperobject(41,8,20,"ובשבע לארבעת אלפי איש כמה דודים מלאי פתותים נשאתם ויאמרו אליו שבעה׃"));
hebsuperobject.biblemap.put("b41_8_21", new hebsuperobject(41,8,21,"ויאמר אליהם איך לא תבינו׃"));
hebsuperobject.biblemap.put("b41_8_22", new hebsuperobject(41,8,22,"ויבא אל בית צידה ויביאו אליו איש עור ויתחננו לו לגעת בו׃"));
hebsuperobject.biblemap.put("b41_8_23", new hebsuperobject(41,8,23,"ויאחז ביד העור ויוליכהו אל מחוץ לכפר וירק בעיניו וישם את ידיו עליו וישאלהו לאמר הראה אתה דבר׃"));
hebsuperobject.biblemap.put("b41_8_24", new hebsuperobject(41,8,24,"ויבט ויאמר אראה את בני האדם כי מתהלכים כאילנות אני ראה׃"));
hebsuperobject.biblemap.put("b41_8_25", new hebsuperobject(41,8,25,"ויוסף לשום את ידיו על עיניו ותפקחנה עיניו וירפא וירא הכל היטב עד למרחוק׃"));
hebsuperobject.biblemap.put("b41_8_26", new hebsuperobject(41,8,26,"וישלחהו אל ביתו לאמר אל תבא בתוך הכפר ואל תדבר לאיש בכפר׃"));
hebsuperobject.biblemap.put("b41_8_27", new hebsuperobject(41,8,27,"ויצא ישוע ותלמידיו ללכת אל כפרי קיסרין של פילפוס ויהי בדרך וישאל את תלמידיו ויאמר אליהם מה אמרים עלי האנשים מי אני׃"));
hebsuperobject.biblemap.put("b41_8_28", new hebsuperobject(41,8,28,"ויענו ויאמרו יוחנן המטביל ויש אמרים אליהו ואחרים אמרים אחד מן הנביאים׃"));
hebsuperobject.biblemap.put("b41_8_29", new hebsuperobject(41,8,29,"וישאל אתם לאמר ואתם מה תאמרו עלי מי אני ויען פטרוס ויאמר אליו אתה הוא המשיח׃"));
hebsuperobject.biblemap.put("b41_8_30", new hebsuperobject(41,8,30,"ויצו אתם בגערה לבלתי דבר עליו לאיש׃"));
hebsuperobject.biblemap.put("b41_8_31", new hebsuperobject(41,8,31,"ויחל ללמדם כי צריך בן האדם לענות הרבה וימאס על ידי הזקנים והכהנים הגדולים והסופרים ויומת ומקצה שלשת ימים קום יקום׃"));
hebsuperobject.biblemap.put("b41_8_32", new hebsuperobject(41,8,32,"והוא בגלוי דבר את הדבר הזה ויקחהו פטרוס ויחל לגער בו׃"));
hebsuperobject.biblemap.put("b41_8_33", new hebsuperobject(41,8,33,"ויפן אחריו ויבט את תלמידיו ויגער בפטרוס לאמר סור מעל פני השטן כי אין לבך לדברי האלהים כי אם לדברי האדם׃"));
hebsuperobject.biblemap.put("b41_8_34", new hebsuperobject(41,8,34,"ויקרא אל העם ואל תלמידיו ויאמר אליהם החפץ ללכת אחרי יכחש בנפשו וישא את צלבו וילך אחרי׃"));
hebsuperobject.biblemap.put("b41_8_35", new hebsuperobject(41,8,35,"כי כל אשר יחפץ להושיע את נפשו תאבד נפשו ממנו וכל אשר תאבד לו נפשו למעני ולמען הבשורה הוא יושיענה׃"));
hebsuperobject.biblemap.put("b41_8_36", new hebsuperobject(41,8,36,"כי מה יסכן לאדם כי יקנה את כל העולם ונשחתה נפשו׃"));
hebsuperobject.biblemap.put("b41_8_37", new hebsuperobject(41,8,37,"או מה יתן איש פדיון נפשו׃"));
hebsuperobject.biblemap.put("b41_8_38", new hebsuperobject(41,8,38,"כי כל איש אשר הייתי אני ודברי לו לחרפה בדור הנאף והחוטא הזה אף הוא יהיה לחרפה לבן האדם בבואו בכבוד אביו עם המלאכים הקדושים׃"));
hebsuperobject.biblemap.put("b41_9_1", new hebsuperobject(41,9,1,"ויאמר אליהם אמן אמר אני לכם כי יש מן העמדים פה אשר לא יטעמו מות עד כי יראו מלכות האלהים באה בגבורה׃"));
hebsuperobject.biblemap.put("b41_9_2", new hebsuperobject(41,9,2,"ואחרי ששת ימים לקח ישוע את פטרוס ואת יעקב ואת יוחנן ויעלם על הר גבה אתו לבדם וישתנה לעיניהם׃"));
hebsuperobject.biblemap.put("b41_9_3", new hebsuperobject(41,9,3,"ובגדיו נהיו מזהירים לבנים מאד כשלג אשר לא יוכל כובס בארץ להלבין כמוהם׃"));
hebsuperobject.biblemap.put("b41_9_4", new hebsuperobject(41,9,4,"וירא אליהם אליהו ומשה מדברים עם ישוע׃"));
hebsuperobject.biblemap.put("b41_9_5", new hebsuperobject(41,9,5,"ויען פטרוס ויאמר אל ישוע רבי טוב היותנו פה נעשה נא שלש סכות לך אחת ולמשה אחת ולאליהו אחת׃"));
hebsuperobject.biblemap.put("b41_9_6", new hebsuperobject(41,9,6,"כי לא ידע מה ידבר כי היו נבהלים׃"));
hebsuperobject.biblemap.put("b41_9_7", new hebsuperobject(41,9,7,"ויהי ענן סוכך עליהם ויצא מן הענן קול אמר זה בני ידידי אליו שמעו׃"));
hebsuperobject.biblemap.put("b41_9_8", new hebsuperobject(41,9,8,"והמה הביטו כה וכה פתאם ולא ראו עוד איש בלתי את ישוע לבדו אתם׃"));
hebsuperobject.biblemap.put("b41_9_9", new hebsuperobject(41,9,9,"וירדו מן ההר ויזהירם לבלתי הגיד לאיש את אשר ראו עד כי יקום בן האדם מן המתים׃"));
hebsuperobject.biblemap.put("b41_9_10", new hebsuperobject(41,9,10,"וישמרו את הדבר בלבבם וידרשו לדעת מה היא התקומה מן המתים׃"));
hebsuperobject.biblemap.put("b41_9_11", new hebsuperobject(41,9,11,"וישאלהו לאמר מה זה אמרים הסופרים כי אליהו בוא יבוא בראשונה׃"));
hebsuperobject.biblemap.put("b41_9_12", new hebsuperobject(41,9,12,"ויען ויאמר להם הנה אליהו בא בראשונה וישיב את הכל ומה כתוב על בן האדם הלא כי יענה הרבה וימאס׃"));
hebsuperobject.biblemap.put("b41_9_13", new hebsuperobject(41,9,13,"אבל אמר אני לכם גם בא אליהו וגם עשו לו כרצונם כאשר כתוב עליו׃"));
hebsuperobject.biblemap.put("b41_9_14", new hebsuperobject(41,9,14,"ויהי כבואו אל התלמידים וירא עם רב סביבותם וסופרים מתוכחים אתם׃"));
hebsuperobject.biblemap.put("b41_9_15", new hebsuperobject(41,9,15,"וכל העם כראותם אתו כן תמהו וירוצי אליו וישאלו לו לשלום׃"));
hebsuperobject.biblemap.put("b41_9_16", new hebsuperobject(41,9,16,"וישאל את הסופרים מה אתם מתוכחים עמהם׃"));
hebsuperobject.biblemap.put("b41_9_17", new hebsuperobject(41,9,17,"ויען אחד מן העם ויאמר רבי הבאתי אליך את בני אשר רוח אלם בקרבו׃"));
hebsuperobject.biblemap.put("b41_9_18", new hebsuperobject(41,9,18,"והיה בכל מקום אשר יאחזהו הוא מרצץ אתו וירד רירו וחרק את שניו ויבש גופו ואמר אל תלמידיך לגרשו ולא יכלו׃"));
hebsuperobject.biblemap.put("b41_9_19", new hebsuperobject(41,9,19,"ויען ויאמר להם הוי דור בלתי מאמין עד מתי אהיה עמכם עד מתי אסבל אתכם הביאו אתו לפני׃"));
hebsuperobject.biblemap.put("b41_9_20", new hebsuperobject(41,9,20,"ויביאהו לפניו ויהי כאשר ראהו הרוח וירוצצנו פתאם ויפל ארצה ויתגולל ויורד רירו׃"));
hebsuperobject.biblemap.put("b41_9_21", new hebsuperobject(41,9,21,"וישאל את אביו כמה ימים היתה לו זאת ויאמר מימי נעוריו׃"));
hebsuperobject.biblemap.put("b41_9_22", new hebsuperobject(41,9,22,"ופעמים רבות הפיל אתו גם באש גם במים להאבידו אך אם יכל תוכל רחם עלינו ועזרנו׃"));
hebsuperobject.biblemap.put("b41_9_23", new hebsuperobject(41,9,23,"ויאמר אליו ישוע לאמר אם תוכל להאמין כל יוכל המאמין׃"));
hebsuperobject.biblemap.put("b41_9_24", new hebsuperobject(41,9,24,"ויתן אבי הילד את קלו בבכי ויאמר אני מאמין עזר נא לחסרון אמונתי׃"));
hebsuperobject.biblemap.put("b41_9_25", new hebsuperobject(41,9,25,"וירא ישוע את העם מתקבץ אליו ויגער ברוח הטמא לאמר רוח אלם וחרש אני מצוך צא ממנו ואל תסף לבוא בו עוד׃"));
hebsuperobject.biblemap.put("b41_9_26", new hebsuperobject(41,9,26,"ויצעק וירצץ אתו מאד ויצא ויהי כמת עד אשר אמרו רבים כי גוע׃"));
hebsuperobject.biblemap.put("b41_9_27", new hebsuperobject(41,9,27,"ויחזק ישוע בידו ויניעהו ויקם׃"));
hebsuperobject.biblemap.put("b41_9_28", new hebsuperobject(41,9,28,"ויהי כאשר בא הביתה וישאלהו תלמידיו בהיותם לבדם אתו מדוע אנחנו לא יכלנו לגרשו׃"));
hebsuperobject.biblemap.put("b41_9_29", new hebsuperobject(41,9,29,"ויאמר אליהם המין הזה יצא לא יצא כי אם בתפלה ובצום׃"));
hebsuperobject.biblemap.put("b41_9_30", new hebsuperobject(41,9,30,"ויצאו משם ויעברו בגליל ולא אבה להודע לאיש׃"));
hebsuperobject.biblemap.put("b41_9_31", new hebsuperobject(41,9,31,"כי היה מלמד את תלמידיו לאמר אליהם כי עתיד בן האדם להמסר בידי בני אדם ויהרגהו ואחרי אשר נהרג יקום ביום השלישי׃"));
hebsuperobject.biblemap.put("b41_9_32", new hebsuperobject(41,9,32,"והם לא הבינו את הדבר וייראו לשאל אותו׃"));
hebsuperobject.biblemap.put("b41_9_33", new hebsuperobject(41,9,33,"ויבא אל כפר נחום ובהיותו בבית וישאל אותם מה התוכחתם איש עם רעהו בדרך׃"));
hebsuperobject.biblemap.put("b41_9_34", new hebsuperobject(41,9,34,"ויחרישו כי התעשקו בדרך מי הוא הגדול בהם׃"));
hebsuperobject.biblemap.put("b41_9_35", new hebsuperobject(41,9,35,"וישב ויקרא אל שנים העשר ויאמר אליהם איש כי יחפץ להיות הראשון הוא יהיה האחרון לכלם ומשרת כלם׃"));
hebsuperobject.biblemap.put("b41_9_36", new hebsuperobject(41,9,36,"ויקח ילד ויעמידהו בתוכם ויחבקהו ויאמר להם׃"));
hebsuperobject.biblemap.put("b41_9_37", new hebsuperobject(41,9,37,"כל אשר יקבל בשמי ילד אחד כזה הוא מקבל אותי וכל אשר אותי יקבל איננו מקבל אותי כי אם את אשר שלחני׃"));
hebsuperobject.biblemap.put("b41_9_38", new hebsuperobject(41,9,38,"ויען יוחנן ויאמר אליו רבי ראינו איש מגרש שדים בשמך ואיננו הולך אחרינו ונכלאנו יען אשר לא הלך אחרינו׃"));
hebsuperobject.biblemap.put("b41_9_39", new hebsuperobject(41,9,39,"ויאמר ישוע אל תכלאהו כי אין איש עשה גבורה בשמי ויוכל במהרה לדבר בי רעה׃"));
hebsuperobject.biblemap.put("b41_9_40", new hebsuperobject(41,9,40,"כי כל אשר איננו נגדנו הוא בעדנו׃"));
hebsuperobject.biblemap.put("b41_9_41", new hebsuperobject(41,9,41,"כי כל המשקה אתכם כוס מים בשמי על אשר אתם למשיח אמן אמר אני לכם כי לא יאבד שכרו׃"));
hebsuperobject.biblemap.put("b41_9_42", new hebsuperobject(41,9,42,"וכל המכשיל אחד הקטנים המאמינים בי טוב לו שיתלה פלח רכב על צוארו והשלך בים׃"));
hebsuperobject.biblemap.put("b41_9_43", new hebsuperobject(41,9,43,"ואם ידך תכשילך קצץ אתה טוב לך לבוא קטע לחיים מהיות לך שתי ידים ותלך אל גיהנם אל האש אשר לא תכבה׃"));
hebsuperobject.biblemap.put("b41_9_44", new hebsuperobject(41,9,44,"אשר שם תולעתם לא תמות ואשם לא תכבה׃"));
hebsuperobject.biblemap.put("b41_9_45", new hebsuperobject(41,9,45,"ואם רגלך תכשילך קצץ אתה טוב לך לבוא פסח לחיים מהיות לך שתי רגלים ותשלך לגיהנם אל האש אשר לא תכבה׃"));
hebsuperobject.biblemap.put("b41_9_46", new hebsuperobject(41,9,46,"אשר שם תולעתם לא תמות ואשם לא תכבה׃"));
hebsuperobject.biblemap.put("b41_9_47", new hebsuperobject(41,9,47,"ואם עינך תכשילך עקר אתה טוב לך לבוא אל מלכות האלהים בעין אחת מהיות לך שתי עינים ותשלך לגיהנם׃"));
hebsuperobject.biblemap.put("b41_9_48", new hebsuperobject(41,9,48,"אשר שם תולעתם לא תמות ואשם לא תכבה׃"));
hebsuperobject.biblemap.put("b41_9_49", new hebsuperobject(41,9,49,"כי כל איש באש ימלח וכל קרבן במלח ימלח׃"));
hebsuperobject.biblemap.put("b41_9_50", new hebsuperobject(41,9,50,"טוב המלח ואם המלח יהיה תפל במה תתקנו אותו יהי לכם מלח בקרבכם ויהי שלום ביניכם׃"));
hebsuperobject.biblemap.put("b41_10_1", new hebsuperobject(41,10,1,"ויקם משם וילך אל גבול יהודה מעבר הירדן ויקהלו עוד אליו המון עם וילמדם כפעם בפעם׃"));
hebsuperobject.biblemap.put("b41_10_2", new hebsuperobject(41,10,2,"ויגשו אליו הפרושים וישאלהו אם יוכל איש לשלח את אשתו והם מנסים אתו׃"));
hebsuperobject.biblemap.put("b41_10_3", new hebsuperobject(41,10,3,"ויען ויאמר אליהם מה צוה אתכם משה׃"));
hebsuperobject.biblemap.put("b41_10_4", new hebsuperobject(41,10,4,"ויאמרו משה התיר לכתב ספר כריתת ולשלח׃"));
hebsuperobject.biblemap.put("b41_10_5", new hebsuperobject(41,10,5,"ויען ישוע ויאמר אליהם בעבור קשי לבבכם כתב לכם את המצוה הזאת׃"));
hebsuperobject.biblemap.put("b41_10_6", new hebsuperobject(41,10,6,"אבל מראשית הבריאה זכר ונקבה עשה אתם אלהים׃"));
hebsuperobject.biblemap.put("b41_10_7", new hebsuperobject(41,10,7,"על כן יעזב איש את אביו ואת אמו ודבק באשתו׃"));
hebsuperobject.biblemap.put("b41_10_8", new hebsuperobject(41,10,8,"והיו שניהם לבשר אחד ואם כן אפוא אינם עוד שנים כי אם בשר אחד׃"));
hebsuperobject.biblemap.put("b41_10_9", new hebsuperobject(41,10,9,"לכן את אשר חבר אלהים לא יפרידנו אדם׃"));
hebsuperobject.biblemap.put("b41_10_10", new hebsuperobject(41,10,10,"ויהי בבית וישובו תלמידיו לשאל אתו על זאת׃"));
hebsuperobject.biblemap.put("b41_10_11", new hebsuperobject(41,10,11,"ויאמר אליהם המשלח את אשתו ולקח אחרת נאף הוא עליה׃"));
hebsuperobject.biblemap.put("b41_10_12", new hebsuperobject(41,10,12,"ואשה כי תעזב אישה ולקחה איש אחר נאפת היא׃"));
hebsuperobject.biblemap.put("b41_10_13", new hebsuperobject(41,10,13,"ויביאו אליו ילדים למען יגע בהם ויגערו התלמידים במביאיהם׃"));
hebsuperobject.biblemap.put("b41_10_14", new hebsuperobject(41,10,14,"וירא ישוע ויכעס ויאמר אליהם הניחו לילדים לבוא אלי ואל תמנעום כי לאלה מלכות האלהים׃"));
hebsuperobject.biblemap.put("b41_10_15", new hebsuperobject(41,10,15,"אמן אמר אני לכם כל אשר לא יקבל את מלכות האלהים כילד הוא לא יבא בה׃"));
hebsuperobject.biblemap.put("b41_10_16", new hebsuperobject(41,10,16,"ויחבקם ויברכם בשומו את ידיו עליהם׃"));
hebsuperobject.biblemap.put("b41_10_17", new hebsuperobject(41,10,17,"ויהי בצאתו לדרך והנה איש רץ אליו ויכרע לפניו וישאל אותו רבי הטוב מה אעשה ואירש חיי עולם׃"));
hebsuperobject.biblemap.put("b41_10_18", new hebsuperobject(41,10,18,"ויאמר לו ישוע מדוע קראת לי טוב אין טוב בלתי אחד האלהים׃"));
hebsuperobject.biblemap.put("b41_10_19", new hebsuperobject(41,10,19,"הן ידעת את המצות לא תנאף לא תרצח לא תגנב לא תענה עד שקר לא תעשק כבד את אביך ואת אמך׃"));
hebsuperobject.biblemap.put("b41_10_20", new hebsuperobject(41,10,20,"ויען ויאמר אליו רבי את כל אלה שמרתי נעורי׃"));
hebsuperobject.biblemap.put("b41_10_21", new hebsuperobject(41,10,21,"ויבט בו ישוע ויאהבהו ויאמר אליו אחת חסרת לך מכר את כל אשר לך ותן לעניים ויהי לך אוצר בשמים ובוא שא את הצלב ולך אחרי׃"));
hebsuperobject.biblemap.put("b41_10_22", new hebsuperobject(41,10,22,"ויצר לו על הדבר הזה ויעצב וילך לו כי הון רב היה לו׃"));
hebsuperobject.biblemap.put("b41_10_23", new hebsuperobject(41,10,23,"ויבט ישוע סביב ויאמר אל תלמידיו כמה יקשה לבעלי נכסים לבוא אל מלכות האלהים׃"));
hebsuperobject.biblemap.put("b41_10_24", new hebsuperobject(41,10,24,"ויבהלו התלמידים על דבריו ויסף ישוע ויען ויאמר להם בני מה קשה לבטחים על חילם לבוא אל מלכות האלהים׃"));
hebsuperobject.biblemap.put("b41_10_25", new hebsuperobject(41,10,25,"נקל לגמל לעבר בתוך נקב המחט מבוא עשיר אל מלכות האלהים׃"));
hebsuperobject.biblemap.put("b41_10_26", new hebsuperobject(41,10,26,"ויוסיפו עוד להשתומם ויאמרו איש אלם אחיו מי אפוא יוכל להושע׃"));
hebsuperobject.biblemap.put("b41_10_27", new hebsuperobject(41,10,27,"ויבט בם ישוע ויאמר מבני אדם תפלא זאת אך לא מאלהים כי מאלהים לא יפלא כל דבר׃"));
hebsuperobject.biblemap.put("b41_10_28", new hebsuperobject(41,10,28,"ויען פטרוס ויאמר אליו הן אנחנו עזבנו את הכל ונלך אחריך׃"));
hebsuperobject.biblemap.put("b41_10_29", new hebsuperobject(41,10,29,"ויאמר ישוע אמן אמר אני לכם כי אין איש אשר עזב את ביתו או את אחיו או את אחיותיו או את אביו או את אמו או את אשתו או את בניו או את שדותיו למעני ולמען הבשורה׃"));
hebsuperobject.biblemap.put("b41_10_30", new hebsuperobject(41,10,30,"אשר לא יקח עתה בזמן הזה בכל הרדיפות מאה פעמים כהמה בתים ואחים ואחיות ואמות ובנים ושדות ובעולם הבא חיי עולמים׃"));
hebsuperobject.biblemap.put("b41_10_31", new hebsuperobject(41,10,31,"ואולם רבים מן הראשונים יהיו אחרונים והאחרונים ראשונים׃"));
hebsuperobject.biblemap.put("b41_10_32", new hebsuperobject(41,10,32,"ויהי בדרך בעלותם ירושלים וישוע הולך לפניהם והמה נבהלים ויראים בלכתם אחריו ויוסף לקחת אליו את שנים העשר ויחל להגיד להם את אשר יקרהו לאמר׃"));
hebsuperobject.biblemap.put("b41_10_33", new hebsuperobject(41,10,33,"הנה אנחנו עלים ירושלימה ובן האדם ימסר לראשי הכהנים ולסופרים וירשיעהו למות וימסרו אתו לגוים׃"));
hebsuperobject.biblemap.put("b41_10_34", new hebsuperobject(41,10,34,"ויהתלו בו ויכהו בשוטים וירקו בפניו וימיתהו וביום השלישי קום יקום׃"));
hebsuperobject.biblemap.put("b41_10_35", new hebsuperobject(41,10,35,"ויקרבו אליו יעקב ויוחנן בני זבדי ויאמרו רבי אותה נפשנו כי תעשה לנו את אשר נשאל ממך׃"));
hebsuperobject.biblemap.put("b41_10_36", new hebsuperobject(41,10,36,"ויאמר אליהם מה אויתם כי אעשה לכם׃"));
hebsuperobject.biblemap.put("b41_10_37", new hebsuperobject(41,10,37,"ויאמרו אליו תנה לנו לשבת אחד לימינך ואחד לשמאלך בכבודך׃"));
hebsuperobject.biblemap.put("b41_10_38", new hebsuperobject(41,10,38,"ויאמר אליהם ישוע לא ידעתם את אשר שאלתם היכל תוכלו לשתות את הכוס אשר אני שתה ולהטבל בטבילה אשר אני נטבל בה׃"));
hebsuperobject.biblemap.put("b41_10_39", new hebsuperobject(41,10,39,"ויאמרו אליו נוכל ויאמר אליהם ישוע את הכוס אשר אני שתה תשתו ובטבילה אשר אני נטבל בה תטבלו׃"));
hebsuperobject.biblemap.put("b41_10_40", new hebsuperobject(41,10,40,"אך שבת לימיני ולשמאלי אין בידי לתתה בלתי לאשר הוכן להם׃"));
hebsuperobject.biblemap.put("b41_10_41", new hebsuperobject(41,10,41,"ויהי כשמע זאת העשרה ויחלו לכעוס על יעקב ויוחנן׃"));
hebsuperobject.biblemap.put("b41_10_42", new hebsuperobject(41,10,42,"ויקרא להם ישוע ויאמר אליהם אתם ידעתם כי הנחשבים לשרי הגוים הם רדים בהם וגדוליהם שולטים עליהם׃"));
hebsuperobject.biblemap.put("b41_10_43", new hebsuperobject(41,10,43,"ואתם לא כן ביניכם כי אם החפץ להיות גדול ביניכם יהיה לכם למשרת׃"));
hebsuperobject.biblemap.put("b41_10_44", new hebsuperobject(41,10,44,"והחפץ להיות בכם ראשון יהיה עבד לכל׃"));
hebsuperobject.biblemap.put("b41_10_45", new hebsuperobject(41,10,45,"כי בן האדם אף הוא לא בא למען ישרתוהו כי אם לשרת ולתת את נפשו כפר תחת רבים׃"));
hebsuperobject.biblemap.put("b41_10_46", new hebsuperobject(41,10,46,"ויבאו יריחו ויהי כצאתו מיריחו הוא ותלמידיו והמון עם רב והנה ברטימי בן טימי איש עור ישב על יד הדרך לשאל נדבות׃"));
hebsuperobject.biblemap.put("b41_10_47", new hebsuperobject(41,10,47,"וישמע כי הוא ישוע הנצרי ויחל לצעק ויאמר אנא בן דוד ישוע חנני׃"));
hebsuperobject.biblemap.put("b41_10_48", new hebsuperobject(41,10,48,"ויגערו בו רבים להשתיקו והוא הרבה לצעק בן דוד חנני׃"));
hebsuperobject.biblemap.put("b41_10_49", new hebsuperobject(41,10,49,"ויעמד ישוע ויאמר קראו לו ויקראו לעור ויאמרו אליו חזק קום קרא לך׃"));
hebsuperobject.biblemap.put("b41_10_50", new hebsuperobject(41,10,50,"וישלך את שמלתו מעליו ויקם ויבא אל ישוע׃"));
hebsuperobject.biblemap.put("b41_10_51", new hebsuperobject(41,10,51,"ויען ישוע ויאמר אליו מה חפצת ואעשה לך ויאמר אליו העור רבוני כי אראה׃"));
hebsuperobject.biblemap.put("b41_10_52", new hebsuperobject(41,10,52,"ויאמר ישוע אליו לך לך אמונתך הושיעה לך ופתאם ראה וילך אחרי ישוע בדרך׃"));
hebsuperobject.biblemap.put("b41_11_1", new hebsuperobject(41,11,1,"ויהי כאשר קרבו לירושלים אל בית פגי ובית היני בהר הזיתים וישלח שנים מתלמידיו׃"));
hebsuperobject.biblemap.put("b41_11_2", new hebsuperobject(41,11,2,"ויאמר אליהם לכו אל הכפר אשר ממולכם והיה כבאכם שמה תמצאו עיר אסור אשר לא ישב עליו אדם אותו התירו והביאו׃"));
hebsuperobject.biblemap.put("b41_11_3", new hebsuperobject(41,11,3,"וכי יאמר אליכם איש למה תעשו זאת ואמרתם האדון צריך לו וברגע ישלחנו הנה׃"));
hebsuperobject.biblemap.put("b41_11_4", new hebsuperobject(41,11,4,"וילכו וימצאו העיר אסור אל השער בחוץ על אם הדרך ויתירוהו׃"));
hebsuperobject.biblemap.put("b41_11_5", new hebsuperobject(41,11,5,"ואנשים מן העמדים שם אמרו אליהם מה זאת תעשו להתיר את העיר׃"));
hebsuperobject.biblemap.put("b41_11_6", new hebsuperobject(41,11,6,"ויאמרו אליהם כאשר צום ישוע ויניחו להם׃"));
hebsuperobject.biblemap.put("b41_11_7", new hebsuperobject(41,11,7,"ויביאו את העיר אל ישוע וישליכו עליו את בגדיהם וישב עליו׃"));
hebsuperobject.biblemap.put("b41_11_8", new hebsuperobject(41,11,8,"ורבים פרשו את בגדיהם על הדרך ואחרים כרתו ענפים מן העצים וישטחו על הדרך׃"));
hebsuperobject.biblemap.put("b41_11_9", new hebsuperobject(41,11,9,"וההלכים לפניו ואחריו צעקים לאמר הושע נא ברוך הבא בשם יהוה׃"));
hebsuperobject.biblemap.put("b41_11_10", new hebsuperobject(41,11,10,"ברוכה מלכות דוד אבינו הבאה בשם יהוה הושע נא במרומים׃"));
hebsuperobject.biblemap.put("b41_11_11", new hebsuperobject(41,11,11,"ויבא ישוע ירושלים ואל בית המקדש וירא ויתבונן על הכל והיום רפה לערוב ויצא אל בית היני עם שנים העשר׃"));
hebsuperobject.biblemap.put("b41_11_12", new hebsuperobject(41,11,12,"ויהי ממחרת בצאתם מבית היני וירעב׃"));
hebsuperobject.biblemap.put("b41_11_13", new hebsuperobject(41,11,13,"וירא תאנה מרחוק ולא עלים ויבא לראות הימצא בה פרי ויקרב אליה ולא מצא בה כי אם עלים לבד כי לא היתה עת תאנים׃"));
hebsuperobject.biblemap.put("b41_11_14", new hebsuperobject(41,11,14,"ויען ויאמר אליה מעתה איש אל יאכל פרי ממך עד עולם וישמעו תלמידיו׃"));
hebsuperobject.biblemap.put("b41_11_15", new hebsuperobject(41,11,15,"ויבאו ירושלים ויבא ישוע אל המקדש ויחל לגרש משם את המוכרים ואת הקונים ויהפך את שלחנות השלחנים ואת מושבות מכרי היונים׃"));
hebsuperobject.biblemap.put("b41_11_16", new hebsuperobject(41,11,16,"ולא הניח לאיש לשאת כלי דרך המקדש׃"));
hebsuperobject.biblemap.put("b41_11_17", new hebsuperobject(41,11,17,"וילמד ויאמר להם הלא כתוב כי ביתי בית תפלה יקרא לכל העמים ואתם עשיתם אתו מערת פריאים׃"));
hebsuperobject.biblemap.put("b41_11_18", new hebsuperobject(41,11,18,"וישמעו הסופרים וראשי הכהנים ויתנכלו אתו להשמידו כי יראו מפניו יען אשר כל העם משתוממים על תורתו׃"));
hebsuperobject.biblemap.put("b41_11_19", new hebsuperobject(41,11,19,"ויהי בערב ויצא אל מחוץ לעיר׃"));
hebsuperobject.biblemap.put("b41_11_20", new hebsuperobject(41,11,20,"ויהי הם עברים בבקר ויראו את התאנה כי יבשה עם שרשיה׃"));
hebsuperobject.biblemap.put("b41_11_21", new hebsuperobject(41,11,21,"ויזכר פטרוס ויאמר אליו רבי הנה התאנה אשר אררתה יבשה׃"));
hebsuperobject.biblemap.put("b41_11_22", new hebsuperobject(41,11,22,"ויען ישוע ויאמר אליהם תהי נא בכם אמונת אלהים׃"));
hebsuperobject.biblemap.put("b41_11_23", new hebsuperobject(41,11,23,"כי אמן אמר אני לכם כל אשר יאמר אל ההר הזה הנשא והעתק אל תוך הים ואין ספק בלבבו כי אם יאמין כי יהיה כאשר אמר כן גם יהיה לו׃"));
hebsuperobject.biblemap.put("b41_11_24", new hebsuperobject(41,11,24,"על כן אני אמר לכם כל אשר תשאלו בהתפללכם האמינו כי תקחו ויהי לכם׃"));
hebsuperobject.biblemap.put("b41_11_25", new hebsuperobject(41,11,25,"וכי תעמדו להתפלל תסלחו לכל איש את אשר בלבבכם עליו למען יסלח לכם אביכם שבשמים אף הוא את פשעיכם׃"));
hebsuperobject.biblemap.put("b41_11_26", new hebsuperobject(41,11,26,"ואתם אם לא תסלחו אף אביכם שבשמים לא יסלח לכם את פשעיכם׃"));
hebsuperobject.biblemap.put("b41_11_27", new hebsuperobject(41,11,27,"וישובו ויבאו ירושלים ויהי הוא מתהלך במקדש ויבאו אליו הכהנים הגדולים והסופרים והזקנים׃"));
hebsuperobject.biblemap.put("b41_11_28", new hebsuperobject(41,11,28,"ויאמרו אליו באי זו רשות אתה עשה אלה ומי נתן לך את הרשות הזאת לעשות את אלה׃"));
hebsuperobject.biblemap.put("b41_11_29", new hebsuperobject(41,11,29,"ויאמר ישוע אליהם גם אני אשאלה אתכם דבר אחד ואתם השיבוני ואמר לכם באי זו רשות אני עשה אלה׃"));
hebsuperobject.biblemap.put("b41_11_30", new hebsuperobject(41,11,30,"טבילת יוחנן המן השמים היתה אם מבני אדם השיבוני׃"));
hebsuperobject.biblemap.put("b41_11_31", new hebsuperobject(41,11,31,"ויחשבו כה וכה בקרבם לאמר אם נאמר מן השמים יאמר מדוע אפוא לא האמנתם לו׃"));
hebsuperobject.biblemap.put("b41_11_32", new hebsuperobject(41,11,32,"או הנאמר מבני אדם וייראו את העם כי כלם חשבו את יוחנן לנביא באמת׃"));
hebsuperobject.biblemap.put("b41_11_33", new hebsuperobject(41,11,33,"ויענו ויאמרו אל ישוע לא ידענו ויען ישוע ויאמר אליהם אם כן גם אני לא אמר לכם באי זו רשות אני עשה אלה׃"));
hebsuperobject.biblemap.put("b41_12_1", new hebsuperobject(41,12,1,"ויחל לדבר אליהם במשלים לאמר איש נטע כרם ויעש גדר סביבותיו ויחצב יקב ויבן מגדל ויתנהו אל כרמים וילך למרחקים׃"));
hebsuperobject.biblemap.put("b41_12_2", new hebsuperobject(41,12,2,"ולמועד שלח אל הכרמים עבד לקחת מאת הכרמים מפרי הכרם׃"));
hebsuperobject.biblemap.put("b41_12_3", new hebsuperobject(41,12,3,"ויחזיקו בו ויכהו וישלחהו ריקם׃"));
hebsuperobject.biblemap.put("b41_12_4", new hebsuperobject(41,12,4,"ויסף לשלח אליהם עבד אחר ואתו סקלו באבנים ומחקו ראשו וישלחהו נכלם׃"));
hebsuperobject.biblemap.put("b41_12_5", new hebsuperobject(41,12,5,"ויסף וישלח אחר וגם אתו הרגו וכן עשו ברבים אחרים מהם הכו ומהם הרגו׃"));
hebsuperobject.biblemap.put("b41_12_6", new hebsuperobject(41,12,6,"ויהי לו עוד בן יחיד אשר אהבו וישלח גם אתו אליהם באחרנה לאמר מפני בני יגורו׃"));
hebsuperobject.biblemap.put("b41_12_7", new hebsuperobject(41,12,7,"והכרמים ההם אמרו איש אל רעהו הנה זה הוא היורש לכו ונהרגהו ולנו תהיה הירשה׃"));
hebsuperobject.biblemap.put("b41_12_8", new hebsuperobject(41,12,8,"ויחזיקו בו ויהרגו אותו וישליכהו אל מחוץ לכרם׃"));
hebsuperobject.biblemap.put("b41_12_9", new hebsuperobject(41,12,9,"ועתה מה יעשה בעל הכרם יבוא ויאבד את הכרמים ההם ויתן את הכרם לאחרים׃"));
hebsuperobject.biblemap.put("b41_12_10", new hebsuperobject(41,12,10,"הלא קראתם את הכתוב הזה אבן מאסו הבונים היתה לראש פנה׃"));
hebsuperobject.biblemap.put("b41_12_11", new hebsuperobject(41,12,11,"מאת יהוה היתה זאת היא נפלאת בעינינו׃"));
hebsuperobject.biblemap.put("b41_12_12", new hebsuperobject(41,12,12,"ויבקשו לתפשו וייראו מפני העם יען אשר הבינו כי עליהם דבר את המשל הזה ויעזבהו וילכו להם׃"));
hebsuperobject.biblemap.put("b41_12_13", new hebsuperobject(41,12,13,"וישלחו אליו אנשים מן הפרושים ומן ההורדוסים ללכד אתו בדברו׃"));
hebsuperobject.biblemap.put("b41_12_14", new hebsuperobject(41,12,14,"ויבאו ויאמרו אליו רבי ידענו כי איש אמת אתה ולא תגור מפני איש כי לא תכיר פנים כי אם באמת מורה אתה את דרך האלהים הנכון לתת מס אל הקיסר אם לא נתן׃"));
hebsuperobject.biblemap.put("b41_12_15", new hebsuperobject(41,12,15,"והוא ידע את חנפתם ויאמר אליהם מה תנסוני הביאו אלי דינר ואראה׃"));
hebsuperobject.biblemap.put("b41_12_16", new hebsuperobject(41,12,16,"ויביאו ויאמר אליהם של מי הצורה הזאת והמכתב אשר עליו ויאמרו אליו של הקיסר׃"));
hebsuperobject.biblemap.put("b41_12_17", new hebsuperobject(41,12,17,"ויאמר ישוע אליהם את אשר לקיסר תנו לקיסר ואת אשר לאלהים תנו לאלהים ויתמהו עליו׃"));
hebsuperobject.biblemap.put("b41_12_18", new hebsuperobject(41,12,18,"ויבאו אליו מן הצדוקים האמרים כי אין תחיה למתים וישאלהו לאמר׃"));
hebsuperobject.biblemap.put("b41_12_19", new hebsuperobject(41,12,19,"רבי כתב לנו משה כי ימות אחי איש ועזב אשה ובנים אין לו ייבם אחיו את אשתו ויקם זרע לאחיו׃"));
hebsuperobject.biblemap.put("b41_12_20", new hebsuperobject(41,12,20,"והנה שבעה אחים והראשון לקח אשה ובמותו לא השאיר אחריו זרע׃"));
hebsuperobject.biblemap.put("b41_12_21", new hebsuperobject(41,12,21,"ויקח אתה השני וימת ולא הניח זרע וכן גם השלישי׃"));
hebsuperobject.biblemap.put("b41_12_22", new hebsuperobject(41,12,22,"ויקחוה כל השבעה ולא השאירו אחריהם זרע ואחרי מות כלם מתה גם האשה׃"));
hebsuperobject.biblemap.put("b41_12_23", new hebsuperobject(41,12,23,"ועתה בתחית המתים כשיקומו למי מהם תהיה לאשה כי לשבעה היתה לאשה׃"));
hebsuperobject.biblemap.put("b41_12_24", new hebsuperobject(41,12,24,"ויאמר ישוע אליהם הלא בזאת אתם תעים באשר אינכם יודעים גם את הכתובים גם את גבורת האלהים׃"));
hebsuperobject.biblemap.put("b41_12_25", new hebsuperobject(41,12,25,"כי בעת קומם מן המתים האנשים לא ישאו נשים ולא תנשאנה אך יהיו כמלאכי השמים׃"));
hebsuperobject.biblemap.put("b41_12_26", new hebsuperobject(41,12,26,"ועל דבר המתים כי קום יקומו הלא קראתם בספר משה בסנה את אשר דבר אליו האלהים לאמר אנכי אלהי אברהם ואלהי יצחק ואלהי יעקב׃"));
hebsuperobject.biblemap.put("b41_12_27", new hebsuperobject(41,12,27,"האלהים איננו אלהי המתים כי אם אלהי החיים לכן הרביתם לתעות׃"));
hebsuperobject.biblemap.put("b41_12_28", new hebsuperobject(41,12,28,"ואחד מן הסופרים שמע אתם מתוכחים ויקרב אליהם וירא כי היטב השיבם וישאלהו מה היא הראשנה לכל המצות׃"));
hebsuperobject.biblemap.put("b41_12_29", new hebsuperobject(41,12,29,"ויען ישוע וידבר אליו הראשנה לכל המצות היא שמע ישראל יהוה אלהינו יהוה אחד׃"));
hebsuperobject.biblemap.put("b41_12_30", new hebsuperobject(41,12,30,"ואהבת את יהוה אלהיך בכל לבבך ובכל נפשך ובכל מדעך ובכל מאדך זאת היא המצוה הראשנה׃"));
hebsuperobject.biblemap.put("b41_12_31", new hebsuperobject(41,12,31,"והשנית הדמה לה היא ואהבת לרעך כמוך ואין מצוה גדולה מאלה׃"));
hebsuperobject.biblemap.put("b41_12_32", new hebsuperobject(41,12,32,"ויאמר אליו הסופר אמנם רבי יפה דברת כי אלהים אחד הוא ואין עוד מלבדו׃"));
hebsuperobject.biblemap.put("b41_12_33", new hebsuperobject(41,12,33,"ולאהבה אתו בכל לבב ובכל מדע ובכל נפש ובכל מאד ולאהבה את הרע כנפשו גדולה היא מכל עלות וזבחים׃"));
hebsuperobject.biblemap.put("b41_12_34", new hebsuperobject(41,12,34,"וירא ישוע כי ענה בדעת ויאמר אליו לא רחוק אתה ממלכות האלהים ואיש לא ערב עוד את לבו לשאל אותו שאלה׃"));
hebsuperobject.biblemap.put("b41_12_35", new hebsuperobject(41,12,35,"ויען ישוע בלמדו במקדש ויאמר איך יאמרו הסופרים כי המשיח הוא בן דוד׃"));
hebsuperobject.biblemap.put("b41_12_36", new hebsuperobject(41,12,36,"והוא דוד אמר ברוח הקדש נאם יהוה לאדני שב לימיני עד אשית איביך הדם לרגליך׃"));
hebsuperobject.biblemap.put("b41_12_37", new hebsuperobject(41,12,37,"הנה דוד בעצמו קרא לו אדון ואיך הוא בנו ויאהב רב העם לשמע אתו׃"));
hebsuperobject.biblemap.put("b41_12_38", new hebsuperobject(41,12,38,"ויאמר אליהם בלמד אתם השמרו מן הסופרים האהבים להתהלך עטופי טלית ואת שאלות שלומם בשוקים׃"));
hebsuperobject.biblemap.put("b41_12_39", new hebsuperobject(41,12,39,"ואת מושבי הראש בבתי כנסיות ואת מסבות הראש בסעודות׃"));
hebsuperobject.biblemap.put("b41_12_40", new hebsuperobject(41,12,40,"הבלעים את בתי האלמנות ומאריכים בתפלה למראה עינים המה משפט על יתר יקחו׃"));
hebsuperobject.biblemap.put("b41_12_41", new hebsuperobject(41,12,41,"וישוע ישב ממול ארון האוצר והוא ראה את העם משליכים מעות לארון האוצר ועשירים רבים נתנו הרבה׃"));
hebsuperobject.biblemap.put("b41_12_42", new hebsuperobject(41,12,42,"ותבא אלמנה עניה ותשלך שתי פרוטות אשר הן רבע אסר׃"));
hebsuperobject.biblemap.put("b41_12_43", new hebsuperobject(41,12,43,"ויקרא אל תלמידיו ויאמר אליהם אמן אמר אני לכם כי האלמנה העניה הזאת נתנה יותר מכל הנתנים אל ארון האוצר׃"));
hebsuperobject.biblemap.put("b41_12_44", new hebsuperobject(41,12,44,"כי כלם נתנו מן העדף שלהם והיא ממחסרה נתנה כל אשר לה את כל רכושה׃"));
hebsuperobject.biblemap.put("b41_13_1", new hebsuperobject(41,13,1,"ויהי בצאתו מן המקדש ויאמר אליו אחד מתלמידיו רבי ראה מה יפו האבנים והבנינים האלה׃"));
hebsuperobject.biblemap.put("b41_13_2", new hebsuperobject(41,13,2,"ויען ישוע אתו ויאמר הראית את כל הבנינים הגדולים האלה לא תשאר אבן על אבן אשר לא תתפרק׃"));
hebsuperobject.biblemap.put("b41_13_3", new hebsuperobject(41,13,3,"וישב על הר הזיתים ממול המקדש וישאלהו פטרוס ויעקב ויוחנן ואנדרי והם אתו לבדם׃"));
hebsuperobject.biblemap.put("b41_13_4", new hebsuperobject(41,13,4,"אמר נא לנו מתי תהיה זאת ומה הוא האות בבא העת אשר תעשה בה כל זאת׃"));
hebsuperobject.biblemap.put("b41_13_5", new hebsuperobject(41,13,5,"ויען אתם ישוע ויחל לדבר ראו פן יתעה אתכם איש׃"));
hebsuperobject.biblemap.put("b41_13_6", new hebsuperobject(41,13,6,"כי רבים יבאו בשמי לאמר אני הוא ויתעו רבים׃"));
hebsuperobject.biblemap.put("b41_13_7", new hebsuperobject(41,13,7,"ובשמעכם מלחמות ושמעות מלחמה אל תבהלו כי היו תהיה זאת אך לא זאת היא הקץ׃"));
hebsuperobject.biblemap.put("b41_13_8", new hebsuperobject(41,13,8,"כי יקום גוי על גוי וממלכה על ממלכה והיה רעש כה וכה והיה רעב ומהומה׃"));
hebsuperobject.biblemap.put("b41_13_9", new hebsuperobject(41,13,9,"אלה ראשית החבלים ואתם השמרו בנפשתיכם כי ימסרו אתכם לסנהדריות והכיתם בבתי כנסיות ולפני משלים ומלכים תובאו למעני לעדות להם׃"));
hebsuperobject.biblemap.put("b41_13_10", new hebsuperobject(41,13,10,"והבשורה צריכה להקרא בראשנה לכל הגוים׃"));
hebsuperobject.biblemap.put("b41_13_11", new hebsuperobject(41,13,11,"וכאשר יוליכו ומסרו אתכם אל תדאגו ואל תחשבו מה תדברו כי הדבר אשר ינתן לכם בשעה ההיא אותו דברו יען לא אתם הם המדברים כי אם רוח הקדש׃"));
hebsuperobject.biblemap.put("b41_13_12", new hebsuperobject(41,13,12,"ואח ימסר את אחיו למות ואב את בנו וקמו בנים באבותם והמיתו אותם׃"));
hebsuperobject.biblemap.put("b41_13_13", new hebsuperobject(41,13,13,"והייתם שנואים לכל אדם למען שמי והמחכה עד עת קץ הוא יושע׃"));
hebsuperobject.biblemap.put("b41_13_14", new hebsuperobject(41,13,14,"וכי תראו את שקוץ משמם הנאמר ביד דניאל הנביא עמד במקום אשר לא לו הקורא יבין אז נוס ינוסו אנשי יהודה אל ההרים׃"));
hebsuperobject.biblemap.put("b41_13_15", new hebsuperobject(41,13,15,"ואשר על הגג אל ירד הביתה ואל יבא פנימה לשאת דבר מביתו׃"));
hebsuperobject.biblemap.put("b41_13_16", new hebsuperobject(41,13,16,"ואשר בשדה אל ישב הביתה לשאת מלבושו׃"));
hebsuperobject.biblemap.put("b41_13_17", new hebsuperobject(41,13,17,"ואוי להרות ולמיניקות בימים ההמה׃"));
hebsuperobject.biblemap.put("b41_13_18", new hebsuperobject(41,13,18,"אך התפללו אשר לא תהיה מנוסתכם בחרף׃"));
hebsuperobject.biblemap.put("b41_13_19", new hebsuperobject(41,13,19,"כי הימים ההם יהיו עת צרה אשר לא נהיתה כמוה מראשית הבריאה אשר ברא אלהים עד עתה וכמוה לא תהיה עוד׃"));
hebsuperobject.biblemap.put("b41_13_20", new hebsuperobject(41,13,20,"ולולי קצר יהוה את הימים ההם לא יושע כל בשר אך למען הבחירים אשר בחר בם קצר את הימים׃"));
hebsuperobject.biblemap.put("b41_13_21", new hebsuperobject(41,13,21,"ואז אם יאמר איש אליכם הנה פה המשיח או הנהו שם אל תאמינו׃"));
hebsuperobject.biblemap.put("b41_13_22", new hebsuperobject(41,13,22,"כי יקומו משיחי שקר ונביאי שקר ונתנו אתות ומופתים להתעות אף את הבחירים אם יוכלו׃"));
hebsuperobject.biblemap.put("b41_13_23", new hebsuperobject(41,13,23,"ואתם ראו הנה מראש הגדתי לכם את כל׃"));
hebsuperobject.biblemap.put("b41_13_24", new hebsuperobject(41,13,24,"והיה בימים ההם אחרי הצרה ההיא תחשך השמש והירח לא יגיה אורו׃"));
hebsuperobject.biblemap.put("b41_13_25", new hebsuperobject(41,13,25,"והכוכבים יפלו מן השמים וכחות השמים יתמוטטו׃"));
hebsuperobject.biblemap.put("b41_13_26", new hebsuperobject(41,13,26,"ואז יראו את בן האדם בא בעננים בגבורה רבה ובכבוד׃"));
hebsuperobject.biblemap.put("b41_13_27", new hebsuperobject(41,13,27,"ואז ישלח את מלאכיו ויקבץ את בחיריו מארבע הרוחות מקצה הארץ עד קצה השמים׃"));
hebsuperobject.biblemap.put("b41_13_28", new hebsuperobject(41,13,28,"למדו נא את משל התאנה כשירטב ענפה ופרח עלה ידעתם כי קרוב הקיץ׃"));
hebsuperobject.biblemap.put("b41_13_29", new hebsuperobject(41,13,29,"כן אף אתם בראתכם כי היו כל אלה דעו כי קרוב הוא לפתח׃"));
hebsuperobject.biblemap.put("b41_13_30", new hebsuperobject(41,13,30,"אמן אמר אני לכם לא יעבר הדור הזה עד אשר יהיו כל אלה׃"));
hebsuperobject.biblemap.put("b41_13_31", new hebsuperobject(41,13,31,"השמים והארץ יעברו ודברי לא יעברון׃"));
hebsuperobject.biblemap.put("b41_13_32", new hebsuperobject(41,13,32,"אך עת בוא היום ההוא והשעה ההיא אין איש יודע אותה גם לא מלאכי השמים גם לא הבן מבלעדי האב׃"));
hebsuperobject.biblemap.put("b41_13_33", new hebsuperobject(41,13,33,"ראו שקדו והתפללו כי לא ידעתם מתי תהיה העת׃"));
hebsuperobject.biblemap.put("b41_13_34", new hebsuperobject(41,13,34,"והיה כאיש הולך למרחק אשר עזב את ביתו ויתן שלטן לעבדיו ולאיש איש את מלאכתו וגם את השוער צוה לשקד׃"));
hebsuperobject.biblemap.put("b41_13_35", new hebsuperobject(41,13,35,"לכן שקדו כי לא ידעתם מתי יבוא בעל הבית אם לעת ערב או בחצות הלילה אם בעת קריאת הגבר או בבקר׃"));
hebsuperobject.biblemap.put("b41_13_36", new hebsuperobject(41,13,36,"פן יבוא פתאם ומצא אתכם ישנים׃"));
hebsuperobject.biblemap.put("b41_13_37", new hebsuperobject(41,13,37,"ואת אשר אמרתי לכם אמר אני לכל שקדו׃"));
hebsuperobject.biblemap.put("b41_14_1", new hebsuperobject(41,14,1,"ויהי יומים לפני חג הפסח והמצות ויבקשו הכהנים הגדולים והסופרים איך יתפשהו בערמה להמיתו׃"));
hebsuperobject.biblemap.put("b41_14_2", new hebsuperobject(41,14,2,"ויאמרו אך לא בחג פן תהיה מהומה בעם׃"));
hebsuperobject.biblemap.put("b41_14_3", new hebsuperobject(41,14,3,"ויהי בהיותו בבית היני בית שמעון המצרע ויסב אל השלחן ותבא אשה ובידה פך שמן נרד זך ויקר מאד ותשבר את הפך ותצק על ראשו׃"));
hebsuperobject.biblemap.put("b41_14_4", new hebsuperobject(41,14,4,"ויש אשר מתרעמים איש אל רעהו לאמר על מה היה אבוד השמן הזה׃"));
hebsuperobject.biblemap.put("b41_14_5", new hebsuperobject(41,14,5,"כי ראוי היה זה להמכר ביותר משלש מאות דינר ולתתו לעניים ויגערו בה׃"));
hebsuperobject.biblemap.put("b41_14_6", new hebsuperobject(41,14,6,"ויאמר ישוע הניחו לה למה תגיון נפשה מעשה טוב עשתה עמדי׃"));
hebsuperobject.biblemap.put("b41_14_7", new hebsuperobject(41,14,7,"כי העניים תמיד עמכם וכשתרצו תוכלו להיטיב להם ואנכי לא אהיה אתכם תמיד׃"));
hebsuperobject.biblemap.put("b41_14_8", new hebsuperobject(41,14,8,"את אשר היה לאל ידה עשתה קדמה למשוח את גופי לחנטו׃"));
hebsuperobject.biblemap.put("b41_14_9", new hebsuperobject(41,14,9,"אמן אמר אני לכם כי באשר תקרא הבשורה הזאת אל כל העולם גם את אשר עשתה היא יספר לזכרון לה׃"));
hebsuperobject.biblemap.put("b41_14_10", new hebsuperobject(41,14,10,"ויהודה איש קריות אחד משנים העשר הלך אל ראשי הכהנים למסר אותו אליהם׃"));
hebsuperobject.biblemap.put("b41_14_11", new hebsuperobject(41,14,11,"והם כשמעם שמחו ויאמרו לתת לו כסף ויבקש תאנה למסרו׃"));
hebsuperobject.biblemap.put("b41_14_12", new hebsuperobject(41,14,12,"ויהי בראשון לחג המצות עת זבח הפסח ויאמרו אליו תלמידיו איפה תחפץ לאכל את הפסח ונלכה ונכין׃"));
hebsuperobject.biblemap.put("b41_14_13", new hebsuperobject(41,14,13,"וישלח שנים מתלמידיו ויאמר אליהם לכו העירה ויפגע אתכם איש נשא צפחת המים לכו אחריו׃"));
hebsuperobject.biblemap.put("b41_14_14", new hebsuperobject(41,14,14,"ובאשר יבוא שמה אמרו לבעל הבית כה אמר הרב איה המלון אשת אכלה שם את הפסח עם תלמידי׃"));
hebsuperobject.biblemap.put("b41_14_15", new hebsuperobject(41,14,15,"והוא יראה אתכם עליה גדולה מצעה ומוכנה ושם הכינו לנו׃"));
hebsuperobject.biblemap.put("b41_14_16", new hebsuperobject(41,14,16,"ויצאו תלמידיו ויבאו העירה וימצאו כאשר דבר להם ויכינו את הפסח׃"));
hebsuperobject.biblemap.put("b41_14_17", new hebsuperobject(41,14,17,"ויהי בערב ויבא עם שנים העשר׃"));
hebsuperobject.biblemap.put("b41_14_18", new hebsuperobject(41,14,18,"ויסבו ויאכלו ויאמר ישוע אמן אמר אני לכם אחד מכם האכל אתי ימסרני׃"));
hebsuperobject.biblemap.put("b41_14_19", new hebsuperobject(41,14,19,"ויחלו להתעצב ויאמרו אליו זה אחר זה הכי אני הוא׃"));
hebsuperobject.biblemap.put("b41_14_20", new hebsuperobject(41,14,20,"ויען ויאמר אליהם אחד משנים העשר הוא הטבל עמי בקערה׃"));
hebsuperobject.biblemap.put("b41_14_21", new hebsuperobject(41,14,21,"הן בן האדם הלך ילך כאשר כתוב עליו אבל אוי לאיש ההוא אשר על ידו ימסר בן האדם טוב לאיש ההוא שלא נולד׃"));
hebsuperobject.biblemap.put("b41_14_22", new hebsuperobject(41,14,22,"ויהי באכלם ויקח ישוע לחם ויברך ויבצע ויתן להם ויאמר קחו אכלו זה הוא גופי׃"));
hebsuperobject.biblemap.put("b41_14_23", new hebsuperobject(41,14,23,"ויקח את הכוס ויברך ויתן להם וישתו ממנה כלם׃"));
hebsuperobject.biblemap.put("b41_14_24", new hebsuperobject(41,14,24,"ויאמר להם זה הוא דמי דם הברית החדשה הנשפך בעד רבים׃"));
hebsuperobject.biblemap.put("b41_14_25", new hebsuperobject(41,14,25,"אמן אמר אני לכם שתה לא אשתה עוד מתנובת הגפן עד היום ההוא אשר אשתה אותה חדשה במלכות האלהים׃"));
hebsuperobject.biblemap.put("b41_14_26", new hebsuperobject(41,14,26,"ואחרי גמרם את ההלל ויצאו אל הר הזיתים׃"));
hebsuperobject.biblemap.put("b41_14_27", new hebsuperobject(41,14,27,"ויאמר אליהם ישוע אתם כלכם תכשלו בי בלילה הזה כי כתוב אכה את הרעה ותפוצין הצאן׃"));
hebsuperobject.biblemap.put("b41_14_28", new hebsuperobject(41,14,28,"ואחרי קומי מן המתים אלך לפניכם הגלילה׃"));
hebsuperobject.biblemap.put("b41_14_29", new hebsuperobject(41,14,29,"ויאמר אליו פטרוס גם אם כלם יכשלו אני לא אכשל׃"));
hebsuperobject.biblemap.put("b41_14_30", new hebsuperobject(41,14,30,"ויאמר אליו ישוע אמן אמר אני לך כי היום בלילה הזה בטרם יקרא התרנגול פעמים אתה תכחש בי שלש פעמים׃"));
hebsuperobject.biblemap.put("b41_14_31", new hebsuperobject(41,14,31,"והוא התחזק ויוסף לדבר ויאמר גם כי יהיה עלי למות אתך כחש לא אכחש בך וכן אמרו גם כלם׃"));
hebsuperobject.biblemap.put("b41_14_32", new hebsuperobject(41,14,32,"ויבאו אל חצר גת שמני שמו ויאמר אל תלמידיו שבו לכם פה עד אשר אתפלל׃"));
hebsuperobject.biblemap.put("b41_14_33", new hebsuperobject(41,14,33,"ויקח אתו את פטרוס ואת יעקב ואת יוחנן ויחל להשמים ולמוג׃"));
hebsuperobject.biblemap.put("b41_14_34", new hebsuperobject(41,14,34,"ויאמר אליהם נפשי מרה לי עד מות עמדו פה ושקדו׃"));
hebsuperobject.biblemap.put("b41_14_35", new hebsuperobject(41,14,35,"ויעבר משם מעט והלאה ויפל ארצה ויתפלל אשר אם יוכל היות תעבר נא מעליו השעה הזאת׃"));
hebsuperobject.biblemap.put("b41_14_36", new hebsuperobject(41,14,36,"ויאמר אבא אבי הכל תוכל העבר נא מעלי את הכוס הזאת אך לא את אשר אני רוצה כי אם את אשר אתה׃"));
hebsuperobject.biblemap.put("b41_14_37", new hebsuperobject(41,14,37,"ויבא וימצאם ישנים ויאמר אל פטרוס שמעון התישן הכי לא יכלת לשקד שעה אחת׃"));
hebsuperobject.biblemap.put("b41_14_38", new hebsuperobject(41,14,38,"שקדו והתפללו פן תבאו לידי נסיון הן הרוח היא חפצה והבשר רפה׃"));
hebsuperobject.biblemap.put("b41_14_39", new hebsuperobject(41,14,39,"ויסף לסור ויתפלל באמרו עוד הפעם כדברים ההמה׃"));
hebsuperobject.biblemap.put("b41_14_40", new hebsuperobject(41,14,40,"וישב וימצאם שנית ישנים כי עיניהם היו כבדות ולא ידעו מה יענהו׃"));
hebsuperobject.biblemap.put("b41_14_41", new hebsuperobject(41,14,41,"ויבא פעם שלישית ויאמר אליהם מעתה נומו ונוחו רב לי כי באה השעה הנה בן האדם נמסר בידי חטאים׃"));
hebsuperobject.biblemap.put("b41_14_42", new hebsuperobject(41,14,42,"קומו ונלכה הנה המוסר אותי קרב׃"));
hebsuperobject.biblemap.put("b41_14_43", new hebsuperobject(41,14,43,"עודנו מדבר ויהודה בא והוא אחד משנים העשר ועמו המון רב בחרבות ובמקלות מאת הכהנים הגדולים והסופרים והזקנים׃"));
hebsuperobject.biblemap.put("b41_14_44", new hebsuperobject(41,14,44,"והמוסר אתו נתן להם אות לאמר האיש אשר אשקהו זה הוא אותו תפשו והוליכהו אל ימלט׃"));
hebsuperobject.biblemap.put("b41_14_45", new hebsuperobject(41,14,45,"הוא בא והוא נגש אליו ויאמר רבי רבי וינשק לו׃"));
hebsuperobject.biblemap.put("b41_14_46", new hebsuperobject(41,14,46,"וישלחו בו את ידיהם ויתפשהו׃"));
hebsuperobject.biblemap.put("b41_14_47", new hebsuperobject(41,14,47,"ואחד מן העמדים אצלו שלף את חרבו ויך את עבד הכהן הגדול ויקצץ את אזנו׃"));
hebsuperobject.biblemap.put("b41_14_48", new hebsuperobject(41,14,48,"ויען ישוע ויאמר אליהם כמו על פריץ יצאתם עלי בחרבות ובמקלות לתפשני׃"));
hebsuperobject.biblemap.put("b41_14_49", new hebsuperobject(41,14,49,"ויום יום הייתי אצלכם מלמד במקדש ולא החזקתם בי אבל למען ימלאו הכתובים׃"));
hebsuperobject.biblemap.put("b41_14_50", new hebsuperobject(41,14,50,"ויעזבו אותו כלם וינוסו׃"));
hebsuperobject.biblemap.put("b41_14_51", new hebsuperobject(41,14,51,"ונער אחד הלך אחריו מעטף בסדין לכסות את ערותו ויאחזהו הנערים׃"));
hebsuperobject.biblemap.put("b41_14_52", new hebsuperobject(41,14,52,"והוא עזב את הסדין בידם וינס ערם מפניהם׃"));
hebsuperobject.biblemap.put("b41_14_53", new hebsuperobject(41,14,53,"ויוליכו את ישוע אל הכהן הגדול ויקהלו אתו כל הכהנים הגדולים והזקנים והסופרים׃"));
hebsuperobject.biblemap.put("b41_14_54", new hebsuperobject(41,14,54,"ופטרוס הלך אחריו מרחוק עד לחצר הכהן הגדול פנימה וישב שם עם המשרתים ויתחמם נגד האור׃"));
hebsuperobject.biblemap.put("b41_14_55", new hebsuperobject(41,14,55,"וראשי הכהנים וכל הסנהדרין בקשו עדות על ישוע להמיתו ולא מצאו׃"));
hebsuperobject.biblemap.put("b41_14_56", new hebsuperobject(41,14,56,"כי רבים ענו בו עדות שקר אך העדיות לא היו שות׃"));
hebsuperobject.biblemap.put("b41_14_57", new hebsuperobject(41,14,57,"ויקומו אנשים ויענו בו עדות שקר לאמר׃"));
hebsuperobject.biblemap.put("b41_14_58", new hebsuperobject(41,14,58,"שמענו אתו אמר אני אהרס את ההיכל הזה מעשה ידי אדם ולשלשת ימים אבנה היכל אחר אשר איננו מעשה ידי אדם׃"));
hebsuperobject.biblemap.put("b41_14_59", new hebsuperobject(41,14,59,"וגם בזאת עדותם לא שותה׃"));
hebsuperobject.biblemap.put("b41_14_60", new hebsuperobject(41,14,60,"ויקם הכהן הגדול ויעמד בתוך וישאל את ישוע לאמר האינך משיב דבר מה זה אלה ענים בך׃"));
hebsuperobject.biblemap.put("b41_14_61", new hebsuperobject(41,14,61,"והוא החריש ולא השיב דבר ויוסף עוד הכהן הגדול לשאל אתו ויאמר אליו האתה הוא המשיח בן המברך׃"));
hebsuperobject.biblemap.put("b41_14_62", new hebsuperobject(41,14,62,"ויאמר ישוע אני הוא ואתם תראו את בן האדם יושב לימין הגבורה ובא עם ענני השמים׃"));
hebsuperobject.biblemap.put("b41_14_63", new hebsuperobject(41,14,63,"ויקרע הכהן הגדול את בגדיו ויאמר מה לנו עוד לבקש עדים׃"));
hebsuperobject.biblemap.put("b41_14_64", new hebsuperobject(41,14,64,"שמעתם את הגדוף מה דעתכם וירשיעהו כלם כי חיב מיתה הוא׃"));
hebsuperobject.biblemap.put("b41_14_65", new hebsuperobject(41,14,65,"ויחלו מהם לרק בו ויחפו את פניו ויכהו באגרף ויאמרו אליו הנבא והמשרתים הכאיבהו בהכותם אותו על הלחי׃"));
hebsuperobject.biblemap.put("b41_14_66", new hebsuperobject(41,14,66,"ויהי בהיות פטרוס בתחתית החצר ותבא אחת משפחות הכהן הגדול׃"));
hebsuperobject.biblemap.put("b41_14_67", new hebsuperobject(41,14,67,"ותרא את פטרוס כי מתחמם הוא ותבט בו ותאמר גם אתה היית עם הנצרי ישוע׃"));
hebsuperobject.biblemap.put("b41_14_68", new hebsuperobject(41,14,68,"ויכחש לאמר לא אדע ולא אבין מה את אמרת ויצא החוצה אל האולם והתרנגל קרא׃"));
hebsuperobject.biblemap.put("b41_14_69", new hebsuperobject(41,14,69,"ותראהו השפחה ותוסף ותאמר אל העמדים שם כי זה הוא אחד מהם ויכחש פעם שנית׃"));
hebsuperobject.biblemap.put("b41_14_70", new hebsuperobject(41,14,70,"וכמעט אחרי כן גם העמדים שם אמרו אל פטרוס אמנם אתה אחד מהם כי אף גלילי אתה ולשונך כלשונם׃"));
hebsuperobject.biblemap.put("b41_14_71", new hebsuperobject(41,14,71,"ויחל להחרים את נפשו ולהשבע לאמר לא יעדתי את האיש הזה אשר אמרתם׃"));
hebsuperobject.biblemap.put("b41_14_72", new hebsuperobject(41,14,72,"והתרנגל קרא פעם שנית ויזכר פטרוס את הדבר אשר אמר לו ישוע בטרם יקרא התרנגל פעמים תכחש בי שלש פעמים וישם אל לבו ויבך׃"));
hebsuperobject.biblemap.put("b41_15_1", new hebsuperobject(41,15,1,"וישכימו ראשי הכהנים עם הזקנים והסופרים וכל הסנהדרין בבקר ויתיעצו ויאסרו את ישוע ויוליכהו משם וימסרהו אל פילטוס׃"));
hebsuperobject.biblemap.put("b41_15_2", new hebsuperobject(41,15,2,"וישאל אותו פילטוס האתה מלך היהודים ויען ויאמר אליו אתה אמרת׃"));
hebsuperobject.biblemap.put("b41_15_3", new hebsuperobject(41,15,3,"וראשי הכהנים הרבו לשטנו׃"));
hebsuperobject.biblemap.put("b41_15_4", new hebsuperobject(41,15,4,"ויוסף פילטוס וישאלהו לאמר האינך משיב דבר ראה כמה הם מעידים בך׃"));
hebsuperobject.biblemap.put("b41_15_5", new hebsuperobject(41,15,5,"וישוע לא השיב עוד אף דבר אחד ויתמה פילטוס׃"));
hebsuperobject.biblemap.put("b41_15_6", new hebsuperobject(41,15,6,"ובכל חג היה דרכו לפטר להם אסיר אחד את אשר יבקשו׃"));
hebsuperobject.biblemap.put("b41_15_7", new hebsuperobject(41,15,7,"ויהי איש הנקרא בשם בר אבא אסור עם המורדים אשר רצחו רצח בעת המרד׃"));
hebsuperobject.biblemap.put("b41_15_8", new hebsuperobject(41,15,8,"וישא ההמון את קולו ויחלו לבקש שיעשה להם כפעם בפעם׃"));
hebsuperobject.biblemap.put("b41_15_9", new hebsuperobject(41,15,9,"ויען אתם פילטוס ויאמר התחפצו כי אפטר לכם את מלך היהודים׃"));
hebsuperobject.biblemap.put("b41_15_10", new hebsuperobject(41,15,10,"כי ידע אשר רק מקנאה מסרוהו ראשי הכהנים׃"));
hebsuperobject.biblemap.put("b41_15_11", new hebsuperobject(41,15,11,"וראשי הכהנים הסיתו את ההמון לבלתי פטר להם כי אם בר אבא׃"));
hebsuperobject.biblemap.put("b41_15_12", new hebsuperobject(41,15,12,"ויסף פילטוס ויען ויאמר להם ומה אפוא חפצתם ואעשה לאשר אתם קראים מלך היהודים׃"));
hebsuperobject.biblemap.put("b41_15_13", new hebsuperobject(41,15,13,"ויוסיפו לצעק הצלב אותו׃"));
hebsuperobject.biblemap.put("b41_15_14", new hebsuperobject(41,15,14,"ויאמר אליהם פילטוס מה אפוא עשה רעה והם הרבו עוד לצעק הצלב אותו׃"));
hebsuperobject.biblemap.put("b41_15_15", new hebsuperobject(41,15,15,"ויואל פילטוס לעשות כרצון העם ויפטר להם את בר אבא ואת ישוע הכה בשוטים וימסר אותו להצלב׃"));
hebsuperobject.biblemap.put("b41_15_16", new hebsuperobject(41,15,16,"ויוליכהו אנשי הצלב אל החצר הפנימית הוא בית המשפט ויזעיקו את כל הגדוד׃"));
hebsuperobject.biblemap.put("b41_15_17", new hebsuperobject(41,15,17,"וילבישהו ארגמן וישרגו עטרת קצים ויעטרהו׃"));
hebsuperobject.biblemap.put("b41_15_18", new hebsuperobject(41,15,18,"ויחלו לברכו לאמר שלום לך מלך היהודים׃"));
hebsuperobject.biblemap.put("b41_15_19", new hebsuperobject(41,15,19,"ויכו על ראשו בקנה וירקו בו ויכרעו על ברכיהם וישתחוו לו׃"));
hebsuperobject.biblemap.put("b41_15_20", new hebsuperobject(41,15,20,"ואחרי התלוצצם בו הפשיטו אותו את הארגמן וילבישהו את בגדיו ויוציאהו לצלב אותו׃"));
hebsuperobject.biblemap.put("b41_15_21", new hebsuperobject(41,15,21,"ויאנסו איש עבר אחד הבא מן השדה ושמו שמעון הקוריני אבי אלכסנדרוס ורופוס לשאת את צלבו׃"));
hebsuperobject.biblemap.put("b41_15_22", new hebsuperobject(41,15,22,"ויביאהו אל מקום גלגלתא הוא מקום הגלגלת׃"));
hebsuperobject.biblemap.put("b41_15_23", new hebsuperobject(41,15,23,"ויתנו לו יין מזוג במר והוא לא קבל׃"));
hebsuperobject.biblemap.put("b41_15_24", new hebsuperobject(41,15,24,"ויהי כאשר צלבו אותו ויחלקו בגדיו להם בהפילם עליהם גורל מה יקח איש איש׃"));
hebsuperobject.biblemap.put("b41_15_25", new hebsuperobject(41,15,25,"ותהי השעה השלישית ויצלבהו׃"));
hebsuperobject.biblemap.put("b41_15_26", new hebsuperobject(41,15,26,"ומכתב דבר אשמתו כתוב למעלה מלך היהודים׃"));
hebsuperobject.biblemap.put("b41_15_27", new hebsuperobject(41,15,27,"ויצלבו אתו שני פריצים אחד לימינו ואחד לשמאלו׃"));
hebsuperobject.biblemap.put("b41_15_28", new hebsuperobject(41,15,28,"וימלא הכתוב האמר ואת פשעים נמנה׃"));
hebsuperobject.biblemap.put("b41_15_29", new hebsuperobject(41,15,29,"והעברים גדפו אותו ויניעו ראשם לאמר האח אתה ההורס את ההיכל ובונה אותו בשלשת ימים׃"));
hebsuperobject.biblemap.put("b41_15_30", new hebsuperobject(41,15,30,"הושע את עצמך ורדה מן הצלב׃"));
hebsuperobject.biblemap.put("b41_15_31", new hebsuperobject(41,15,31,"וכן לעגו לו גם ראשי הכהנים עם הסופרים באמרם איש אל רעהו את אחרים הושיע ואת עצמו לא יוכל להושיע׃"));
hebsuperobject.biblemap.put("b41_15_32", new hebsuperobject(41,15,32,"המשיח מלך ישראל ירד נא מן הצלב למען נראה ונאמין וגם הנצלבים אתו חרפוהו׃"));
hebsuperobject.biblemap.put("b41_15_33", new hebsuperobject(41,15,33,"ובהיות השעה הששית היה חשך על כל הארץ עד השעה התשיעית׃"));
hebsuperobject.biblemap.put("b41_15_34", new hebsuperobject(41,15,34,"ובשעה התשיעית ויצעק ישוע בקול גדול אלהי אלהי למה שבקתני אשר פרושו אלי אלי למה עזבתני׃"));
hebsuperobject.biblemap.put("b41_15_35", new hebsuperobject(41,15,35,"ומקצת העמדים אצלו בשמעם את זאת אמרו הנה אל אליהו הוא קורא׃"));
hebsuperobject.biblemap.put("b41_15_36", new hebsuperobject(41,15,36,"וירץ אחד מהם וימלא ספוג חמץ וישם על קנה וישקהו ויאמר הניחו ונראה אם יבא אליהו להורידו׃"));
hebsuperobject.biblemap.put("b41_15_37", new hebsuperobject(41,15,37,"וישוע נתן קול גדול ויפח את נפשו׃"));
hebsuperobject.biblemap.put("b41_15_38", new hebsuperobject(41,15,38,"ופרכת ההיכל נקרעה לשנים קרעים מלמעלה למטה׃"));
hebsuperobject.biblemap.put("b41_15_39", new hebsuperobject(41,15,39,"וירא שר המאה העמד לנגדו כי בזעקו כן נפח את נפשו ויאמר אכן האיש הזה היה בן האלהים׃"));
hebsuperobject.biblemap.put("b41_15_40", new hebsuperobject(41,15,40,"וגם נשים היו שם ראות מרחוק ובתוכן גם מרים המגדלית ומרים אמו של יעקב הצעיר ושל יוסי ושלמית׃"));
hebsuperobject.biblemap.put("b41_15_41", new hebsuperobject(41,15,41,"אשר גם הלכו אחריו ושרתהו בהיותו בגליל ואחרות רבות אשר עלו אתו ירושלים׃"));
hebsuperobject.biblemap.put("b41_15_42", new hebsuperobject(41,15,42,"ועת הערב הגיע ומפני אשר ערב שבת היה הוא היום שלפני השבת׃"));
hebsuperobject.biblemap.put("b41_15_43", new hebsuperobject(41,15,43,"ויבא יוסף הרמתי יועץ נכבד אשר היה מחכה גם הוא למלכות האלהים ויתחזק ויבא אל פילטוס וישאל את גופת ישוע׃"));
hebsuperobject.biblemap.put("b41_15_44", new hebsuperobject(41,15,44,"ויתמה פילטוס על אשר הוא כבר מת ויקרא אל שר המאה וישאלהו הגוע כבר׃"));
hebsuperobject.biblemap.put("b41_15_45", new hebsuperobject(41,15,45,"וידע מפי שר המאה כי כן ויתן את גופתו מתנה ליוסף׃"));
hebsuperobject.biblemap.put("b41_15_46", new hebsuperobject(41,15,46,"והוא קנה סדין ויורד אתו ויכרכהו בסדין וישימהו בקבר חצוב בסלע ויגל אבן על פתח הקבר׃"));
hebsuperobject.biblemap.put("b41_15_47", new hebsuperobject(41,15,47,"ומרים המגדלית ומרים אם יוסי היו ראות את המקום אשר הושם שמה׃"));
hebsuperobject.biblemap.put("b41_16_1", new hebsuperobject(41,16,1,"ויהי כאשר עבר יום השבת ותקנינה מרים המגגדלית ומרים אם יעקב ושלמית סמים לבוא ולסוך אתו בהם׃"));
hebsuperobject.biblemap.put("b41_16_2", new hebsuperobject(41,16,2,"ובאחד בשבת בבקר השכם באו אל הקבר כזרוח השמש׃"));
hebsuperobject.biblemap.put("b41_16_3", new hebsuperobject(41,16,3,"ותאמרנה אשה אל אחותה מי יגל לנו את האבן מעל פתח הקבר׃"));
hebsuperobject.biblemap.put("b41_16_4", new hebsuperobject(41,16,4,"ובהביטן ראו והנה נגללה האבן כי היתה גדלה מאד׃"));
hebsuperobject.biblemap.put("b41_16_5", new hebsuperobject(41,16,5,"ותבאנה אל תוך הקבר ותראינה בחור אחד ישב מימין והוא עטה שמלה לבנה ותשתוממנה׃"));
hebsuperobject.biblemap.put("b41_16_6", new hebsuperobject(41,16,6,"ויאמר אליהן אל תשתוממנה את ישוע הנצרי אתן מבקשות את הנצלב הוא קם איננו פה הנה זה המקום אשר השכיבהו בו׃"));
hebsuperobject.biblemap.put("b41_16_7", new hebsuperobject(41,16,7,"אך לכנה ואמרתן אל תלמידיו ואל פטרוס כי הולך הוא לפניכם הגלילה ושם תראהו כאשר אמר לכם׃"));
hebsuperobject.biblemap.put("b41_16_8", new hebsuperobject(41,16,8,"ותמהרנה לצאת ותברחנה מן הקבר כי אחזתן רעדה ותמהון ולא הגידו דבר לאיש כי יראו׃"));
hebsuperobject.biblemap.put("b41_16_9", new hebsuperobject(41,16,9,"והוא כאשר קם מן המתים באחד בשבת נראה בראשונה אל מרים המגדלית אשר גרש ממנה שבעה שדים׃"));
hebsuperobject.biblemap.put("b41_16_10", new hebsuperobject(41,16,10,"ותלך ותגד לאנשים אשר היו עמו והם מתאבלים ובכים׃"));
hebsuperobject.biblemap.put("b41_16_11", new hebsuperobject(41,16,11,"וכאשר שמעו כי חי ונראה אליה לא האמינו לה׃"));
hebsuperobject.biblemap.put("b41_16_12", new hebsuperobject(41,16,12,"ואחרי כן נראה בדמות אחרת לשנים מהם בהיתם מתהלכים בצאתם השדה׃"));
hebsuperobject.biblemap.put("b41_16_13", new hebsuperobject(41,16,13,"והם הלכו ויגידו לאחרים וגם להם לא האמינו׃"));
hebsuperobject.biblemap.put("b41_16_14", new hebsuperobject(41,16,14,"ובאחרנה נראה לעשתי העשר בהיותם מסבים ויחרף חסרון אמונתם וקשי לבבם אשר לא האמינו לראים אתו נעור מן המתים׃"));
hebsuperobject.biblemap.put("b41_16_15", new hebsuperobject(41,16,15,"ויאמר אליהם לכו אל כל העולם וקראו את הבשורה לכל הבריאה׃"));
hebsuperobject.biblemap.put("b41_16_16", new hebsuperobject(41,16,16,"המאמין ונטבל הוא יושע ואשר לא יאמין יאשם׃"));
hebsuperobject.biblemap.put("b41_16_17", new hebsuperobject(41,16,17,"ואלה האתות אשר ילוו אל המאמינים יגרשו שדים בשמי ובלשנות חדשות ידברו׃"));
hebsuperobject.biblemap.put("b41_16_18", new hebsuperobject(41,16,18,"נחשים ישאו בידיהם ואם ישתו סם המות לא יזיקם על חולים ישימו את ידיהם וייטב להם׃"));
hebsuperobject.biblemap.put("b41_16_19", new hebsuperobject(41,16,19,"ויהי אחרי אשר דבר אתם האדון וינשא השמימה וישב לימין האלהים׃"));
hebsuperobject.biblemap.put("b41_16_20", new hebsuperobject(41,16,20,"והמה יצאו ויקראו בכל המקמות והאדון עזרם ויחזק את הדבר באתות הבאות אחרי דברם אמן׃"));

}

}