package heb.bible;

public class hebbible17 {

public hebbible17() {

putmapbible17();

}

private void putmapbible17() {

hebsuperobject.biblemap.put("b17_1_1", new hebsuperobject(17,1,1,"ויהי בימי אחשורוש הוא אחשורוש המלך מהדו ועד כוש שבע ועשרים ומאה מדינה׃"));
hebsuperobject.biblemap.put("b17_1_2", new hebsuperobject(17,1,2,"בימים ההם כשבת המלך אחשורוש על כסא מלכותו אשר בשושן הבירה׃"));
hebsuperobject.biblemap.put("b17_1_3", new hebsuperobject(17,1,3,"בשנת שלוש למלכו עשה משתה לכל שריו ועבדיו חיל פרס ומדי הפרתמים ושרי המדינות לפניו׃"));
hebsuperobject.biblemap.put("b17_1_4", new hebsuperobject(17,1,4,"בהראתו את עשר כבוד מלכותו ואת יקר תפארת גדולתו ימים רבים שמונים ומאת יום׃"));
hebsuperobject.biblemap.put("b17_1_5", new hebsuperobject(17,1,5,"ובמלואת הימים האלה עשה המלך לכל העם הנמצאים בשושן הבירה למגדול ועד קטן משתה שבעת ימים בחצר גנת ביתן המלך׃"));
hebsuperobject.biblemap.put("b17_1_6", new hebsuperobject(17,1,6,"חור כרפס ותכלת אחוז בחבלי בוץ וארגמן על גלילי כסף ועמודי שש מטות זהב וכסף על רצפת בהט ושש ודר וסחרת׃"));
hebsuperobject.biblemap.put("b17_1_7", new hebsuperobject(17,1,7,"והשקות בכלי זהב וכלים מכלים שונים ויין מלכות רב כיד המלך׃"));
hebsuperobject.biblemap.put("b17_1_8", new hebsuperobject(17,1,8,"והשתיה כדת אין אנס כי כן יסד המלך על כל רב ביתו לעשות כרצון איש ואיש׃"));
hebsuperobject.biblemap.put("b17_1_9", new hebsuperobject(17,1,9,"גם ושתי המלכה עשתה משתה נשים בית המלכות אשר למלך אחשורוש׃"));
hebsuperobject.biblemap.put("b17_1_10", new hebsuperobject(17,1,10,"ביום השביעי כטוב לב המלך ביין אמר למהומן בזתא חרבונא בגתא ואבגתא זתר וכרכס שבעת הסריסים המשרתים את פני המלך אחשורוש׃"));
hebsuperobject.biblemap.put("b17_1_11", new hebsuperobject(17,1,11,"להביא את ושתי המלכה לפני המלך בכתר מלכות להראות העמים והשרים את יפיה כי טובת מראה היא׃"));
hebsuperobject.biblemap.put("b17_1_12", new hebsuperobject(17,1,12,"ותמאן המלכה ושתי לבוא בדבר המלך אשר ביד הסריסים ויקצף המלך מאד וחמתו בערה בו׃"));
hebsuperobject.biblemap.put("b17_1_13", new hebsuperobject(17,1,13,"ויאמר המלך לחכמים ידעי העתים כי כן דבר המלך לפני כל ידעי דת ודין׃"));
hebsuperobject.biblemap.put("b17_1_14", new hebsuperobject(17,1,14,"והקרב אליו כרשנא שתר אדמתא תרשיש מרס מרסנא ממוכן שבעת שרי פרס ומדי ראי פני המלך הישבים ראשנה במלכות׃"));
hebsuperobject.biblemap.put("b17_1_15", new hebsuperobject(17,1,15,"כדת מה לעשות במלכה ושתי על אשר לא עשתה את מאמר המלך אחשורוש ביד הסריסים׃"));
hebsuperobject.biblemap.put("b17_1_16", new hebsuperobject(17,1,16,"ויאמר מומכן לפני המלך והשרים לא על המלך לבדו עותה ושתי המלכה כי על כל השרים ועל כל העמים אשר בכל מדינות המלך אחשורוש׃"));
hebsuperobject.biblemap.put("b17_1_17", new hebsuperobject(17,1,17,"כי יצא דבר המלכה על כל הנשים להבזות בעליהן בעיניהן באמרם המלך אחשורוש אמר להביא את ושתי המלכה לפניו ולא באה׃"));
hebsuperobject.biblemap.put("b17_1_18", new hebsuperobject(17,1,18,"והיום הזה תאמרנה שרות פרס ומדי אשר שמעו את דבר המלכה לכל שרי המלך וכדי בזיון וקצף׃"));
hebsuperobject.biblemap.put("b17_1_19", new hebsuperobject(17,1,19,"אם על המלך טוב יצא דבר מלכות מלפניו ויכתב בדתי פרס ומדי ולא יעבור אשר לא תבוא ושתי לפני המלך אחשורוש ומלכותה יתן המלך לרעותה הטובה ממנה׃"));
hebsuperobject.biblemap.put("b17_1_20", new hebsuperobject(17,1,20,"ונשמע פתגם המלך אשר יעשה בכל מלכותו כי רבה היא וכל הנשים יתנו יקר לבעליהן למגדול ועד קטן׃"));
hebsuperobject.biblemap.put("b17_1_21", new hebsuperobject(17,1,21,"וייטב הדבר בעיני המלך והשרים ויעש המלך כדבר ממוכן׃"));
hebsuperobject.biblemap.put("b17_1_22", new hebsuperobject(17,1,22,"וישלח ספרים אל כל מדינות המלך אל מדינה ומדינה ככתבה ואל עם ועם כלשונו להיות כל איש שרר בביתו ומדבר כלשון עמו׃"));
hebsuperobject.biblemap.put("b17_2_1", new hebsuperobject(17,2,1,"אחר הדברים האלה כשך חמת המלך אחשורוש זכר את ושתי ואת אשר עשתה ואת אשר נגזר עליה׃"));
hebsuperobject.biblemap.put("b17_2_2", new hebsuperobject(17,2,2,"ויאמרו נערי המלך משרתיו יבקשו למלך נערות בתולות טובות מראה׃"));
hebsuperobject.biblemap.put("b17_2_3", new hebsuperobject(17,2,3,"ויפקד המלך פקידים בכל מדינות מלכותו ויקבצו את כל נערה בתולה טובת מראה אל שושן הבירה אל בית הנשים אל יד הגא סריס המלך שמר הנשים ונתון תמרוקיהן׃"));
hebsuperobject.biblemap.put("b17_2_4", new hebsuperobject(17,2,4,"והנערה אשר תיטב בעיני המלך תמלך תחת ושתי וייטב הדבר בעיני המלך ויעש כן׃"));
hebsuperobject.biblemap.put("b17_2_5", new hebsuperobject(17,2,5,"איש יהודי היה בשושן הבירה ושמו מרדכי בן יאיר בן שמעי בן קיש איש ימיני׃"));
hebsuperobject.biblemap.put("b17_2_6", new hebsuperobject(17,2,6,"אשר הגלה מירושלים עם הגלה אשר הגלתה עם יכניה מלך יהודה אשר הגלה נבוכדנאצר מלך בבל׃"));
hebsuperobject.biblemap.put("b17_2_7", new hebsuperobject(17,2,7,"ויהי אמן את הדסה היא אסתר בת דדו כי אין לה אב ואם והנערה יפת תאר וטובת מראה ובמות אביה ואמה לקחה מרדכי לו לבת׃"));
hebsuperobject.biblemap.put("b17_2_8", new hebsuperobject(17,2,8,"ויהי בהשמע דבר המלך ודתו ובהקבץ נערות רבות אל שושן הבירה אל יד הגי ותלקח אסתר אל בית המלך אל יד הגי שמר הנשים׃"));
hebsuperobject.biblemap.put("b17_2_9", new hebsuperobject(17,2,9,"ותיטב הנערה בעיניו ותשא חסד לפניו ויבהל את תמרוקיה ואת מנותה לתת לה ואת שבע הנערות הראיות לתת לה מבית המלך וישנה ואת נערותיה לטוב בית הנשים׃"));
hebsuperobject.biblemap.put("b17_2_10", new hebsuperobject(17,2,10,"לא הגידה אסתר את עמה ואת מולדתה כי מרדכי צוה עליה אשר לא תגיד׃"));
hebsuperobject.biblemap.put("b17_2_11", new hebsuperobject(17,2,11,"ובכל יום ויום מרדכי מתהלך לפני חצר בית הנשים לדעת את שלום אסתר ומה יעשה בה׃"));
hebsuperobject.biblemap.put("b17_2_12", new hebsuperobject(17,2,12,"ובהגיע תר נערה ונערה לבוא אל המלך אחשורוש מקץ היות לה כדת הנשים שנים עשר חדש כי כן ימלאו ימי מרוקיהן ששה חדשים בשמן המר וששה חדשים בבשמים ובתמרוקי הנשים׃"));
hebsuperobject.biblemap.put("b17_2_13", new hebsuperobject(17,2,13,"ובזה הנערה באה אל המלך את כל אשר תאמר ינתן לה לבוא עמה מבית הנשים עד בית המלך׃"));
hebsuperobject.biblemap.put("b17_2_14", new hebsuperobject(17,2,14,"בערב היא באה ובבקר היא שבה אל בית הנשים שני אל יד שעשגז סריס המלך שמר הפילגשים לא תבוא עוד אל המלך כי אם חפץ בה המלך ונקראה בשם׃"));
hebsuperobject.biblemap.put("b17_2_15", new hebsuperobject(17,2,15,"ובהגיע תר אסתר בת אביחיל דד מרדכי אשר לקח לו לבת לבוא אל המלך לא בקשה דבר כי אם את אשר יאמר הגי סריס המלך שמר הנשים ותהי אסתר נשאת חן בעיני כל ראיה׃"));
hebsuperobject.biblemap.put("b17_2_16", new hebsuperobject(17,2,16,"ותלקח אסתר אל המלך אחשורוש אל בית מלכותו בחדש העשירי הוא חדש טבת בשנת שבע למלכותו׃"));
hebsuperobject.biblemap.put("b17_2_17", new hebsuperobject(17,2,17,"ויאהב המלך את אסתר מכל הנשים ותשא חן וחסד לפניו מכל הבתולת וישם כתר מלכות בראשה וימליכה תחת ושתי׃"));
hebsuperobject.biblemap.put("b17_2_18", new hebsuperobject(17,2,18,"ויעש המלך משתה גדול לכל שריו ועבדיו את משתה אסתר והנחה למדינות עשה ויתן משאת כיד המלך׃"));
hebsuperobject.biblemap.put("b17_2_19", new hebsuperobject(17,2,19,"ובהקבץ בתולות שנית ומרדכי ישב בשער המלך׃"));
hebsuperobject.biblemap.put("b17_2_20", new hebsuperobject(17,2,20,"אין אסתר מגדת מולדתה ואת עמה כאשר צוה עליה מרדכי ואת מאמר מרדכי אסתר עשה כאשר היתה באמנה אתו׃"));
hebsuperobject.biblemap.put("b17_2_21", new hebsuperobject(17,2,21,"בימים ההם ומרדכי ישב בשער המלך קצף בגתן ותרש שני סריסי המלך משמרי הסף ויבקשו לשלח יד במלך אחשורש׃"));
hebsuperobject.biblemap.put("b17_2_22", new hebsuperobject(17,2,22,"ויודע הדבר למרדכי ויגד לאסתר המלכה ותאמר אסתר למלך בשם מרדכי׃"));
hebsuperobject.biblemap.put("b17_2_23", new hebsuperobject(17,2,23,"ויבקש הדבר וימצא ויתלו שניהם על עץ ויכתב בספר דברי הימים לפני המלך׃"));
hebsuperobject.biblemap.put("b17_3_1", new hebsuperobject(17,3,1,"אחר הדברים האלה גדל המלך אחשורוש את המן בן המדתא האגגי וינשאהו וישם את כסאו מעל כל השרים אשר אתו׃"));
hebsuperobject.biblemap.put("b17_3_2", new hebsuperobject(17,3,2,"וכל עבדי המלך אשר בשער המלך כרעים ומשתחוים להמן כי כן צוה לו המלך ומרדכי לא יכרע ולא ישתחוה׃"));
hebsuperobject.biblemap.put("b17_3_3", new hebsuperobject(17,3,3,"ויאמרו עבדי המלך אשר בשער המלך למרדכי מדוע אתה עובר את מצות המלך׃"));
hebsuperobject.biblemap.put("b17_3_4", new hebsuperobject(17,3,4,"ויהי באמרם אליו יום ויום ולא שמע אליהם ויגידו להמן לראות היעמדו דברי מרדכי כי הגיד להם אשר הוא יהודי׃"));
hebsuperobject.biblemap.put("b17_3_5", new hebsuperobject(17,3,5,"וירא המן כי אין מרדכי כרע ומשתחוה לו וימלא המן חמה׃"));
hebsuperobject.biblemap.put("b17_3_6", new hebsuperobject(17,3,6,"ויבז בעיניו לשלח יד במרדכי לבדו כי הגידו לו את עם מרדכי ויבקש המן להשמיד את כל היהודים אשר בכל מלכות אחשורוש עם מרדכי׃"));
hebsuperobject.biblemap.put("b17_3_7", new hebsuperobject(17,3,7,"בחדש הראשון הוא חדש ניסן בשנת שתים עשרה למלך אחשורוש הפיל פור הוא הגורל לפני המן מיום ליום ומחדש לחדש שנים עשר הוא חדש אדר׃"));
hebsuperobject.biblemap.put("b17_3_8", new hebsuperobject(17,3,8,"ויאמר המן למלך אחשורוש ישנו עם אחד מפזר ומפרד בין העמים בכל מדינות מלכותך ודתיהם שנות מכל עם ואת דתי המלך אינם עשים ולמלך אין שוה להניחם׃"));
hebsuperobject.biblemap.put("b17_3_9", new hebsuperobject(17,3,9,"אם על המלך טוב יכתב לאבדם ועשרת אלפים ככר כסף אשקול על ידי עשי המלאכה להביא אל גנזי המלך׃"));
hebsuperobject.biblemap.put("b17_3_10", new hebsuperobject(17,3,10,"ויסר המלך את טבעתו מעל ידו ויתנה להמן בן המדתא האגגי צרר היהודים׃"));
hebsuperobject.biblemap.put("b17_3_11", new hebsuperobject(17,3,11,"ויאמר המלך להמן הכסף נתון לך והעם לעשות בו כטוב בעיניך׃"));
hebsuperobject.biblemap.put("b17_3_12", new hebsuperobject(17,3,12,"ויקראו ספרי המלך בחדש הראשון בשלושה עשר יום בו ויכתב ככל אשר צוה המן אל אחשדרפני המלך ואל הפחות אשר על מדינה ומדינה ואל שרי עם ועם מדינה ומדינה ככתבה ועם ועם כלשונו בשם המלך אחשורש נכתב ונחתם בטבעת המלך׃"));
hebsuperobject.biblemap.put("b17_3_13", new hebsuperobject(17,3,13,"ונשלוח ספרים ביד הרצים אל כל מדינות המלך להשמיד להרג ולאבד את כל היהודים מנער ועד זקן טף ונשים ביום אחד בשלושה עשר לחדש שנים עשר הוא חדש אדר ושללם לבוז׃"));
hebsuperobject.biblemap.put("b17_3_14", new hebsuperobject(17,3,14,"פתשגן הכתב להנתן דת בכל מדינה ומדינה גלוי לכל העמים להיות עתדים ליום הזה׃"));
hebsuperobject.biblemap.put("b17_3_15", new hebsuperobject(17,3,15,"הרצים יצאו דחופים בדבר המלך והדת נתנה בשושן הבירה והמלך והמן ישבו לשתות והעיר שושן נבוכה׃"));
hebsuperobject.biblemap.put("b17_4_1", new hebsuperobject(17,4,1,"ומרדכי ידע את כל אשר נעשה ויקרע מרדכי את בגדיו וילבש שק ואפר ויצא בתוך העיר ויזעק זעקה גדלה ומרה׃"));
hebsuperobject.biblemap.put("b17_4_2", new hebsuperobject(17,4,2,"ויבוא עד לפני שער המלך כי אין לבוא אל שער המלך בלבוש שק׃"));
hebsuperobject.biblemap.put("b17_4_3", new hebsuperobject(17,4,3,"ובכל מדינה ומדינה מקום אשר דבר המלך ודתו מגיע אבל גדול ליהודים וצום ובכי ומספד שק ואפר יצע לרבים׃"));
hebsuperobject.biblemap.put("b17_4_4", new hebsuperobject(17,4,4,"ותבואינה נערות אסתר וסריסיה ויגידו לה ותתחלחל המלכה מאד ותשלח בגדים להלביש את מרדכי ולהסיר שקו מעליו ולא קבל׃"));
hebsuperobject.biblemap.put("b17_4_5", new hebsuperobject(17,4,5,"ותקרא אסתר להתך מסריסי המלך אשר העמיד לפניה ותצוהו על מרדכי לדעת מה זה ועל מה זה׃"));
hebsuperobject.biblemap.put("b17_4_6", new hebsuperobject(17,4,6,"ויצא התך אל מרדכי אל רחוב העיר אשר לפני שער המלך׃"));
hebsuperobject.biblemap.put("b17_4_7", new hebsuperobject(17,4,7,"ויגד לו מרדכי את כל אשר קרהו ואת פרשת הכסף אשר אמר המן לשקול על גנזי המלך ביהודיים לאבדם׃"));
hebsuperobject.biblemap.put("b17_4_8", new hebsuperobject(17,4,8,"ואת פתשגן כתב הדת אשר נתן בשושן להשמידם נתן לו להראות את אסתר ולהגיד לה ולצוות עליה לבוא אל המלך להתחנן לו ולבקש מלפניו על עמה׃"));
hebsuperobject.biblemap.put("b17_4_9", new hebsuperobject(17,4,9,"ויבוא התך ויגד לאסתר את דברי מרדכי׃"));
hebsuperobject.biblemap.put("b17_4_10", new hebsuperobject(17,4,10,"ותאמר אסתר להתך ותצוהו אל מרדכי׃"));
hebsuperobject.biblemap.put("b17_4_11", new hebsuperobject(17,4,11,"כל עבדי המלך ועם מדינות המלך יודעים אשר כל איש ואשה אשר יבוא אל המלך אל החצר הפנימית אשר לא יקרא אחת דתו להמית לבד מאשר יושיט לו המלך את שרביט הזהב וחיה ואני לא נקראתי לבוא אל המלך זה שלושים יום׃"));
hebsuperobject.biblemap.put("b17_4_12", new hebsuperobject(17,4,12,"ויגידו למרדכי את דברי אסתר׃"));
hebsuperobject.biblemap.put("b17_4_13", new hebsuperobject(17,4,13,"ויאמר מרדכי להשיב אל אסתר אל תדמי בנפשך להמלט בית המלך מכל היהודים׃"));
hebsuperobject.biblemap.put("b17_4_14", new hebsuperobject(17,4,14,"כי אם החרש תחרישי בעת הזאת רוח והצלה יעמוד ליהודים ממקום אחר ואת ובית אביך תאבדו ומי יודע אם לעת כזאת הגעת למלכות׃"));
hebsuperobject.biblemap.put("b17_4_15", new hebsuperobject(17,4,15,"ותאמר אסתר להשיב אל מרדכי׃"));
hebsuperobject.biblemap.put("b17_4_16", new hebsuperobject(17,4,16,"לך כנוס את כל היהודים הנמצאים בשושן וצומו עלי ואל תאכלו ואל תשתו שלשת ימים לילה ויום גם אני ונערתי אצום כן ובכן אבוא אל המלך אשר לא כדת וכאשר אבדתי אבדתי׃"));
hebsuperobject.biblemap.put("b17_4_17", new hebsuperobject(17,4,17,"ויעבר מרדכי ויעש ככל אשר צותה עליו אסתר׃"));
hebsuperobject.biblemap.put("b17_5_1", new hebsuperobject(17,5,1,"ויהי ביום השלישי ותלבש אסתר מלכות ותעמד בחצר בית המלך הפנימית נכח בית המלך והמלך יושב על כסא מלכותו בבית המלכות נכח פתח הבית׃"));
hebsuperobject.biblemap.put("b17_5_2", new hebsuperobject(17,5,2,"ויהי כראות המלך את אסתר המלכה עמדת בחצר נשאה חן בעיניו ויושט המלך לאסתר את שרביט הזהב אשר בידו ותקרב אסתר ותגע בראש השרביט׃"));
hebsuperobject.biblemap.put("b17_5_3", new hebsuperobject(17,5,3,"ויאמר לה המלך מה לך אסתר המלכה ומה בקשתך עד חצי המלכות וינתן לך׃"));
hebsuperobject.biblemap.put("b17_5_4", new hebsuperobject(17,5,4,"ותאמר אסתר אם על המלך טוב יבוא המלך והמן היום אל המשתה אשר עשיתי לו׃"));
hebsuperobject.biblemap.put("b17_5_5", new hebsuperobject(17,5,5,"ויאמר המלך מהרו את המן לעשות את דבר אסתר ויבא המלך והמן אל המשתה אשר עשתה אסתר׃"));
hebsuperobject.biblemap.put("b17_5_6", new hebsuperobject(17,5,6,"ויאמר המלך לאסתר במשתה היין מה שאלתך וינתן לך ומה בקשתך עד חצי המלכות ותעש׃"));
hebsuperobject.biblemap.put("b17_5_7", new hebsuperobject(17,5,7,"ותען אסתר ותאמר שאלתי ובקשתי׃"));
hebsuperobject.biblemap.put("b17_5_8", new hebsuperobject(17,5,8,"אם מצאתי חן בעיני המלך ואם על המלך טוב לתת את שאלתי ולעשות את בקשתי יבוא המלך והמן אל המשתה אשר אעשה להם ומחר אעשה כדבר המלך׃"));
hebsuperobject.biblemap.put("b17_5_9", new hebsuperobject(17,5,9,"ויצא המן ביום ההוא שמח וטוב לב וכראות המן את מרדכי בשער המלך ולא קם ולא זע ממנו וימלא המן על מרדכי חמה׃"));
hebsuperobject.biblemap.put("b17_5_10", new hebsuperobject(17,5,10,"ויתאפק המן ויבוא אל ביתו וישלח ויבא את אהביו ואת זרש אשתו׃"));
hebsuperobject.biblemap.put("b17_5_11", new hebsuperobject(17,5,11,"ויספר להם המן את כבוד עשרו ורב בניו ואת כל אשר גדלו המלך ואת אשר נשאו על השרים ועבדי המלך׃"));
hebsuperobject.biblemap.put("b17_5_12", new hebsuperobject(17,5,12,"ויאמר המן אף לא הביאה אסתר המלכה עם המלך אל המשתה אשר עשתה כי אם אותי וגם למחר אני קרוא לה עם המלך׃"));
hebsuperobject.biblemap.put("b17_5_13", new hebsuperobject(17,5,13,"וכל זה איננו שוה לי בכל עת אשר אני ראה את מרדכי היהודי יושב בשער המלך׃"));
hebsuperobject.biblemap.put("b17_5_14", new hebsuperobject(17,5,14,"ותאמר לו זרש אשתו וכל אהביו יעשו עץ גבה חמשים אמה ובבקר אמר למלך ויתלו את מרדכי עליו ובא עם המלך אל המשתה שמח וייטב הדבר לפני המן ויעש העץ׃"));
hebsuperobject.biblemap.put("b17_6_1", new hebsuperobject(17,6,1,"בלילה ההוא נדדה שנת המלך ויאמר להביא את ספר הזכרנות דברי הימים ויהיו נקראים לפני המלך׃"));
hebsuperobject.biblemap.put("b17_6_2", new hebsuperobject(17,6,2,"וימצא כתוב אשר הגיד מרדכי על בגתנא ותרש שני סריסי המלך משמרי הסף אשר בקשו לשלח יד במלך אחשורוש׃"));
hebsuperobject.biblemap.put("b17_6_3", new hebsuperobject(17,6,3,"ויאמר המלך מה נעשה יקר וגדולה למרדכי על זה ויאמרו נערי המלך משרתיו לא נעשה עמו דבר׃"));
hebsuperobject.biblemap.put("b17_6_4", new hebsuperobject(17,6,4,"ויאמר המלך מי בחצר והמן בא לחצר בית המלך החיצונה לאמר למלך לתלות את מרדכי על העץ אשר הכין לו׃"));
hebsuperobject.biblemap.put("b17_6_5", new hebsuperobject(17,6,5,"ויאמרו נערי המלך אליו הנה המן עמד בחצר ויאמר המלך יבוא׃"));
hebsuperobject.biblemap.put("b17_6_6", new hebsuperobject(17,6,6,"ויבוא המן ויאמר לו המלך מה לעשות באיש אשר המלך חפץ ביקרו ויאמר המן בלבו למי יחפץ המלך לעשות יקר יותר ממני׃"));
hebsuperobject.biblemap.put("b17_6_7", new hebsuperobject(17,6,7,"ויאמר המן אל המלך איש אשר המלך חפץ ביקרו׃"));
hebsuperobject.biblemap.put("b17_6_8", new hebsuperobject(17,6,8,"יביאו לבוש מלכות אשר לבש בו המלך וסוס אשר רכב עליו המלך ואשר נתן כתר מלכות בראשו׃"));
hebsuperobject.biblemap.put("b17_6_9", new hebsuperobject(17,6,9,"ונתון הלבוש והסוס על יד איש משרי המלך הפרתמים והלבישו את האיש אשר המלך חפץ ביקרו והרכיבהו על הסוס ברחוב העיר וקראו לפניו ככה יעשה לאיש אשר המלך חפץ ביקרו׃"));
hebsuperobject.biblemap.put("b17_6_10", new hebsuperobject(17,6,10,"ויאמר המלך להמן מהר קח את הלבוש ואת הסוס כאשר דברת ועשה כן למרדכי היהודי היושב בשער המלך אל תפל דבר מכל אשר דברת׃"));
hebsuperobject.biblemap.put("b17_6_11", new hebsuperobject(17,6,11,"ויקח המן את הלבוש ואת הסוס וילבש את מרדכי וירכיבהו ברחוב העיר ויקרא לפניו ככה יעשה לאיש אשר המלך חפץ ביקרו׃"));
hebsuperobject.biblemap.put("b17_6_12", new hebsuperobject(17,6,12,"וישב מרדכי אל שער המלך והמן נדחף אל ביתו אבל וחפוי ראש׃"));
hebsuperobject.biblemap.put("b17_6_13", new hebsuperobject(17,6,13,"ויספר המן לזרש אשתו ולכל אהביו את כל אשר קרהו ויאמרו לו חכמיו וזרש אשתו אם מזרע היהודים מרדכי אשר החלות לנפל לפניו לא תוכל לו כי נפול תפול לפניו׃"));
hebsuperobject.biblemap.put("b17_6_14", new hebsuperobject(17,6,14,"עודם מדברים עמו וסריסי המלך הגיעו ויבהלו להביא את המן אל המשתה אשר עשתה אסתר׃"));
hebsuperobject.biblemap.put("b17_7_1", new hebsuperobject(17,7,1,"ויבא המלך והמן לשתות עם אסתר המלכה׃"));
hebsuperobject.biblemap.put("b17_7_2", new hebsuperobject(17,7,2,"ויאמר המלך לאסתר גם ביום השני במשתה היין מה שאלתך אסתר המלכה ותנתן לך ומה בקשתך עד חצי המלכות ותעש׃"));
hebsuperobject.biblemap.put("b17_7_3", new hebsuperobject(17,7,3,"ותען אסתר המלכה ותאמר אם מצאתי חן בעיניך המלך ואם על המלך טוב תנתן לי נפשי בשאלתי ועמי בבקשתי׃"));
hebsuperobject.biblemap.put("b17_7_4", new hebsuperobject(17,7,4,"כי נמכרנו אני ועמי להשמיד להרוג ולאבד ואלו לעבדים ולשפחות נמכרנו החרשתי כי אין הצר שוה בנזק המלך׃"));
hebsuperobject.biblemap.put("b17_7_5", new hebsuperobject(17,7,5,"ויאמר המלך אחשורוש ויאמר לאסתר המלכה מי הוא זה ואי זה הוא אשר מלאו לבו לעשות כן׃"));
hebsuperobject.biblemap.put("b17_7_6", new hebsuperobject(17,7,6,"ותאמר אסתר איש צר ואויב המן הרע הזה והמן נבעת מלפני המלך והמלכה׃"));
hebsuperobject.biblemap.put("b17_7_7", new hebsuperobject(17,7,7,"והמלך קם בחמתו ממשתה היין אל גנת הביתן והמן עמד לבקש על נפשו מאסתר המלכה כי ראה כי כלתה אליו הרעה מאת המלך׃"));
hebsuperobject.biblemap.put("b17_7_8", new hebsuperobject(17,7,8,"והמלך שב מגנת הביתן אל בית משתה היין והמן נפל על המטה אשר אסתר עליה ויאמר המלך הגם לכבוש את המלכה עמי בבית הדבר יצא מפי המלך ופני המן חפו׃"));
hebsuperobject.biblemap.put("b17_7_9", new hebsuperobject(17,7,9,"ויאמר חרבונה אחד מן הסריסים לפני המלך גם הנה העץ אשר עשה המן למרדכי אשר דבר טוב על המלך עמד בבית המן גבה חמשים אמה ויאמר המלך תלהו עליו׃"));
hebsuperobject.biblemap.put("b17_7_10", new hebsuperobject(17,7,10,"ויתלו את המן על העץ אשר הכין למרדכי וחמת המלך שככה׃"));
hebsuperobject.biblemap.put("b17_8_1", new hebsuperobject(17,8,1,"ביום ההוא נתן המלך אחשורוש לאסתר המלכה את בית המן צרר היהודיים ומרדכי בא לפני המלך כי הגידה אסתר מה הוא לה׃"));
hebsuperobject.biblemap.put("b17_8_2", new hebsuperobject(17,8,2,"ויסר המלך את טבעתו אשר העביר מהמן ויתנה למרדכי ותשם אסתר את מרדכי על בית המן׃"));
hebsuperobject.biblemap.put("b17_8_3", new hebsuperobject(17,8,3,"ותוסף אסתר ותדבר לפני המלך ותפל לפני רגליו ותבך ותתחנן לו להעביר את רעת המן האגגי ואת מחשבתו אשר חשב על היהודים׃"));
hebsuperobject.biblemap.put("b17_8_4", new hebsuperobject(17,8,4,"ויושט המלך לאסתר את שרבט הזהב ותקם אסתר ותעמד לפני המלך׃"));
hebsuperobject.biblemap.put("b17_8_5", new hebsuperobject(17,8,5,"ותאמר אם על המלך טוב ואם מצאתי חן לפניו וכשר הדבר לפני המלך וטובה אני בעיניו יכתב להשיב את הספרים מחשבת המן בן המדתא האגגי אשר כתב לאבד את היהודים אשר בכל מדינות המלך׃"));
hebsuperobject.biblemap.put("b17_8_6", new hebsuperobject(17,8,6,"כי איככה אוכל וראיתי ברעה אשר ימצא את עמי ואיככה אוכל וראיתי באבדן מולדתי׃"));
hebsuperobject.biblemap.put("b17_8_7", new hebsuperobject(17,8,7,"ויאמר המלך אחשורש לאסתר המלכה ולמרדכי היהודי הנה בית המן נתתי לאסתר ואתו תלו על העץ על אשר שלח ידו ביהודיים׃"));
hebsuperobject.biblemap.put("b17_8_8", new hebsuperobject(17,8,8,"ואתם כתבו על היהודים כטוב בעיניכם בשם המלך וחתמו בטבעת המלך כי כתב אשר נכתב בשם המלך ונחתום בטבעת המלך אין להשיב׃"));
hebsuperobject.biblemap.put("b17_8_9", new hebsuperobject(17,8,9,"ויקראו ספרי המלך בעת ההיא בחדש השלישי הוא חדש סיון בשלושה ועשרים בו ויכתב ככל אשר צוה מרדכי אל היהודים ואל האחשדרפנים והפחות ושרי המדינות אשר מהדו ועד כוש שבע ועשרים ומאה מדינה מדינה ומדינה ככתבה ועם ועם כלשנו ואל היהודים ככתבם וכלשונם׃"));
hebsuperobject.biblemap.put("b17_8_10", new hebsuperobject(17,8,10,"ויכתב בשם המלך אחשורש ויחתם בטבעת המלך וישלח ספרים ביד הרצים בסוסים רכבי הרכש האחשתרנים בני הרמכים׃"));
hebsuperobject.biblemap.put("b17_8_11", new hebsuperobject(17,8,11,"אשר נתן המלך ליהודים אשר בכל עיר ועיר להקהל ולעמד על נפשם להשמיד ולהרג ולאבד את כל חיל עם ומדינה הצרים אתם טף ונשים ושללם לבוז׃"));
hebsuperobject.biblemap.put("b17_8_12", new hebsuperobject(17,8,12,"ביום אחד בכל מדינות המלך אחשורוש בשלושה עשר לחדש שנים עשר הוא חדש אדר׃"));
hebsuperobject.biblemap.put("b17_8_13", new hebsuperobject(17,8,13,"פתשגן הכתב להנתן דת בכל מדינה ומדינה גלוי לכל העמים ולהיות היהודיים עתודים ליום הזה להנקם מאיביהם׃"));
hebsuperobject.biblemap.put("b17_8_14", new hebsuperobject(17,8,14,"הרצים רכבי הרכש האחשתרנים יצאו מבהלים ודחופים בדבר המלך והדת נתנה בשושן הבירה׃"));
hebsuperobject.biblemap.put("b17_8_15", new hebsuperobject(17,8,15,"ומרדכי יצא מלפני המלך בלבוש מלכות תכלת וחור ועטרת זהב גדולה ותכריך בוץ וארגמן והעיר שושן צהלה ושמחה׃"));
hebsuperobject.biblemap.put("b17_8_16", new hebsuperobject(17,8,16,"ליהודים היתה אורה ושמחה וששן ויקר׃"));
hebsuperobject.biblemap.put("b17_8_17", new hebsuperobject(17,8,17,"ובכל מדינה ומדינה ובכל עיר ועיר מקום אשר דבר המלך ודתו מגיע שמחה וששון ליהודים משתה ויום טוב ורבים מעמי הארץ מתיהדים כי נפל פחד היהודים עליהם׃"));
hebsuperobject.biblemap.put("b17_9_1", new hebsuperobject(17,9,1,"ובשנים עשר חדש הוא חדש אדר בשלושה עשר יום בו אשר הגיע דבר המלך ודתו להעשות ביום אשר שברו איבי היהודים לשלוט בהם ונהפוך הוא אשר ישלטו היהודים המה בשנאיהם׃"));
hebsuperobject.biblemap.put("b17_9_2", new hebsuperobject(17,9,2,"נקהלו היהודים בעריהם בכל מדינות המלך אחשורוש לשלח יד במבקשי רעתם ואיש לא עמד לפניהם כי נפל פחדם על כל העמים׃"));
hebsuperobject.biblemap.put("b17_9_3", new hebsuperobject(17,9,3,"וכל שרי המדינות והאחשדרפנים והפחות ועשי המלאכה אשר למלך מנשאים את היהודים כי נפל פחד מרדכי עליהם׃"));
hebsuperobject.biblemap.put("b17_9_4", new hebsuperobject(17,9,4,"כי גדול מרדכי בבית המלך ושמעו הולך בכל המדינות כי האיש מרדכי הולך וגדול׃"));
hebsuperobject.biblemap.put("b17_9_5", new hebsuperobject(17,9,5,"ויכו היהודים בכל איביהם מכת חרב והרג ואבדן ויעשו בשנאיהם כרצונם׃"));
hebsuperobject.biblemap.put("b17_9_6", new hebsuperobject(17,9,6,"ובשושן הבירה הרגו היהודים ואבד חמש מאות איש׃"));
hebsuperobject.biblemap.put("b17_9_7", new hebsuperobject(17,9,7,"ואת פרשנדתא ואת דלפון ואת אספתא׃"));
hebsuperobject.biblemap.put("b17_9_8", new hebsuperobject(17,9,8,"ואת פורתא ואת אדליא ואת ארידתא׃"));
hebsuperobject.biblemap.put("b17_9_9", new hebsuperobject(17,9,9,"ואת פרמשתא ואת אריסי ואת ארדי ואת ויזתא׃"));
hebsuperobject.biblemap.put("b17_9_10", new hebsuperobject(17,9,10,"עשרת בני המן בן המדתא צרר היהודים הרגו ובבזה לא שלחו את ידם׃"));
hebsuperobject.biblemap.put("b17_9_11", new hebsuperobject(17,9,11,"ביום ההוא בא מספר ההרוגים בשושן הבירה לפני המלך׃"));
hebsuperobject.biblemap.put("b17_9_12", new hebsuperobject(17,9,12,"ויאמר המלך לאסתר המלכה בשושן הבירה הרגו היהודים ואבד חמש מאות איש ואת עשרת בני המן בשאר מדינות המלך מה עשו ומה שאלתך וינתן לך ומה בקשתך עוד ותעש׃"));
hebsuperobject.biblemap.put("b17_9_13", new hebsuperobject(17,9,13,"ותאמר אסתר אם על המלך טוב ינתן גם מחר ליהודים אשר בשושן לעשות כדת היום ואת עשרת בני המן יתלו על העץ׃"));
hebsuperobject.biblemap.put("b17_9_14", new hebsuperobject(17,9,14,"ויאמר המלך להעשות כן ותנתן דת בשושן ואת עשרת בני המן תלו׃"));
hebsuperobject.biblemap.put("b17_9_15", new hebsuperobject(17,9,15,"ויקהלו היהודיים אשר בשושן גם ביום ארבעה עשר לחדש אדר ויהרגו בשושן שלש מאות איש ובבזה לא שלחו את ידם׃"));
hebsuperobject.biblemap.put("b17_9_16", new hebsuperobject(17,9,16,"ושאר היהודים אשר במדינות המלך נקהלו ועמד על נפשם ונוח מאיביהם והרג בשנאיהם חמשה ושבעים אלף ובבזה לא שלחו את ידם׃"));
hebsuperobject.biblemap.put("b17_9_17", new hebsuperobject(17,9,17,"ביום שלשה עשר לחדש אדר ונוח בארבעה עשר בו ועשה אתו יום משתה ושמחה׃"));
hebsuperobject.biblemap.put("b17_9_18", new hebsuperobject(17,9,18,"והיהודיים אשר בשושן נקהלו בשלשה עשר בו ובארבעה עשר בו ונוח בחמשה עשר בו ועשה אתו יום משתה ושמחה׃"));
hebsuperobject.biblemap.put("b17_9_19", new hebsuperobject(17,9,19,"על כן היהודים הפרוזים הישבים בערי הפרזות עשים את יום ארבעה עשר לחדש אדר שמחה ומשתה ויום טוב ומשלוח מנות איש לרעהו׃"));
hebsuperobject.biblemap.put("b17_9_20", new hebsuperobject(17,9,20,"ויכתב מרדכי את הדברים האלה וישלח ספרים אל כל היהודים אשר בכל מדינות המלך אחשורוש הקרובים והרחוקים׃"));
hebsuperobject.biblemap.put("b17_9_21", new hebsuperobject(17,9,21,"לקים עליהם להיות עשים את יום ארבעה עשר לחדש אדר ואת יום חמשה עשר בו בכל שנה ושנה׃"));
hebsuperobject.biblemap.put("b17_9_22", new hebsuperobject(17,9,22,"כימים אשר נחו בהם היהודים מאויביהם והחדש אשר נהפך להם מיגון לשמחה ומאבל ליום טוב לעשות אותם ימי משתה ושמחה ומשלוח מנות איש לרעהו ומתנות לאביונים׃"));
hebsuperobject.biblemap.put("b17_9_23", new hebsuperobject(17,9,23,"וקבל היהודים את אשר החלו לעשות ואת אשר כתב מרדכי אליהם׃"));
hebsuperobject.biblemap.put("b17_9_24", new hebsuperobject(17,9,24,"כי המן בן המדתא האגגי צרר כל היהודים חשב על היהודים לאבדם והפיל פור הוא הגורל להמם ולאבדם׃"));
hebsuperobject.biblemap.put("b17_9_25", new hebsuperobject(17,9,25,"ובבאה לפני המלך אמר עם הספר ישוב מחשבתו הרעה אשר חשב על היהודים על ראשו ותלו אתו ואת בניו על העץ׃"));
hebsuperobject.biblemap.put("b17_9_26", new hebsuperobject(17,9,26,"על כן קראו לימים האלה פורים על שם הפור על כן על כל דברי האגרת הזאת ומה ראו על ככה ומה הגיע אליהם׃"));
hebsuperobject.biblemap.put("b17_9_27", new hebsuperobject(17,9,27,"קימו וקבל היהודים עליהם ועל זרעם ועל כל הנלוים עליהם ולא יעבור להיות עשים את שני הימים האלה ככתבם וכזמנם בכל שנה ושנה׃"));
hebsuperobject.biblemap.put("b17_9_28", new hebsuperobject(17,9,28,"והימים האלה נזכרים ונעשים בכל דור ודור משפחה ומשפחה מדינה ומדינה ועיר ועיר וימי הפורים האלה לא יעברו מתוך היהודים וזכרם לא יסוף מזרעם׃"));
hebsuperobject.biblemap.put("b17_9_29", new hebsuperobject(17,9,29,"ותכתב אסתר המלכה בת אביחיל ומרדכי היהודי את כל תקף לקים את אגרת הפורים הזאת השנית׃"));
hebsuperobject.biblemap.put("b17_9_30", new hebsuperobject(17,9,30,"וישלח ספרים אל כל היהודים אל שבע ועשרים ומאה מדינה מלכות אחשורוש דברי שלום ואמת׃"));
hebsuperobject.biblemap.put("b17_9_31", new hebsuperobject(17,9,31,"לקים את ימי הפרים האלה בזמניהם כאשר קים עליהם מרדכי היהודי ואסתר המלכה וכאשר קימו על נפשם ועל זרעם דברי הצמות וזעקתם׃"));
hebsuperobject.biblemap.put("b17_9_32", new hebsuperobject(17,9,32,"ומאמר אסתר קים דברי הפרים האלה ונכתב בספר׃"));
hebsuperobject.biblemap.put("b17_10_1", new hebsuperobject(17,10,1,"וישם המלך אחשרש מס על הארץ ואיי הים׃"));
hebsuperobject.biblemap.put("b17_10_2", new hebsuperobject(17,10,2,"וכל מעשה תקפו וגבורתו ופרשת גדלת מרדכי אשר גדלו המלך הלוא הם כתובים על ספר דברי הימים למלכי מדי ופרס׃"));
hebsuperobject.biblemap.put("b17_10_3", new hebsuperobject(17,10,3,"כי מרדכי היהודי משנה למלך אחשורוש וגדול ליהודים ורצוי לרב אחיו דרש טוב לעמו ודבר שלום לכל זרעו׃"));

}

}