package heb.bible;

public class hebbible46 {

public hebbible46() {

putmapbible46();

}

private void putmapbible46() {

hebsuperobject.biblemap.put("b46_1_1", new hebsuperobject(46,1,1,"פולוס המקרא להיות שליח ישוע המשיח ברצון אלהים וסוסתניס אחינו׃"));
hebsuperobject.biblemap.put("b46_1_2", new hebsuperobject(46,1,2,"אל קהלת אלהים אשר בקורנתוס אל המקדשים במשיח ישוע הקרואים להיות קדשים עם כל הקראים בשם אדנינו ישוע המשיח בכל מקום שלהם ושלנו׃"));
hebsuperobject.biblemap.put("b46_1_3", new hebsuperobject(46,1,3,"חסד לכם ושלום מאת האלהים אבינו ואדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b46_1_4", new hebsuperobject(46,1,4,"אודה לאלהי בעבורכם בכל עת על חסד האלהים הנתן לכם במשיח ישוע׃"));
hebsuperobject.biblemap.put("b46_1_5", new hebsuperobject(46,1,5,"אשר עשרתם בו בכל בכל דבור ובכל דעת׃"));
hebsuperobject.biblemap.put("b46_1_6", new hebsuperobject(46,1,6,"באשר עדות המשיח התקימה בכם׃"));
hebsuperobject.biblemap.put("b46_1_7", new hebsuperobject(46,1,7,"עד כי לא חסרתם כל מתן החסד והנכם מחכים להתגלות אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b46_1_8", new hebsuperobject(46,1,8,"אשר גם יקים אתכם ער עת קץ להיות נקיים ביום אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b46_1_9", new hebsuperobject(46,1,9,"נאמן הוא האלהים אשר על פיו נקראתם לחברת בנו ישוע המשיח אדנינו׃"));
hebsuperobject.biblemap.put("b46_1_10", new hebsuperobject(46,1,10,"והנני מזהיר אתכם אחי בשם אדנינו ישוע המשיח להיות כלכם פה אחד ולא תהיין מחלקות בקרבכם כי אם תכוננו יחד בלב אחד ובעצה אחת׃"));
hebsuperobject.biblemap.put("b46_1_11", new hebsuperobject(46,1,11,"כי הגד לי עליכם ביד בני בית כלואה כי יש מריבות ביניכם׃"));
hebsuperobject.biblemap.put("b46_1_12", new hebsuperobject(46,1,12,"וזאת אני אמר כי איש איש מכם זה אמר לפולוס וזה לאפולוס וזה לכיפא וזה למשיח הנני׃"));
hebsuperobject.biblemap.put("b46_1_13", new hebsuperobject(46,1,13,"הכי חלק המשיח הכי פולוס נצלב בעדכם או לשם פולוס נטבלתם׃"));
hebsuperobject.biblemap.put("b46_1_14", new hebsuperobject(46,1,14,"אודה לאלהים שלא טבלתי איש מכם כי אם את קרספוס ואת גיוס׃"));
hebsuperobject.biblemap.put("b46_1_15", new hebsuperobject(46,1,15,"פן יאמרו כי לשמי טבלתי׃"));
hebsuperobject.biblemap.put("b46_1_16", new hebsuperobject(46,1,16,"אך טבלתי גם את בני בית אסטפנוס ומלבד אלה אינני ידע אם טבלתי עוד איש אחר׃"));
hebsuperobject.biblemap.put("b46_1_17", new hebsuperobject(46,1,17,"כי לא שלחני המשיח לטבול כי אם לבשר לא בחכמת דברים למען אשר לא יהיה לריק צלב המשיח׃"));
hebsuperobject.biblemap.put("b46_1_18", new hebsuperobject(46,1,18,"כי דבר הצלב סכלות הוא לאבדים אבל לנו הנושעים גבורת אלהים הוא׃"));
hebsuperobject.biblemap.put("b46_1_19", new hebsuperobject(46,1,19,"כי כן כתוב אאבד חכמת חכמים ובינת נבונים אסתיר׃"));
hebsuperobject.biblemap.put("b46_1_20", new hebsuperobject(46,1,20,"איה חכם איה ספר איה דרש העולם הזה הלא סכל האלהים את חכמת העולם הזה׃"));
hebsuperobject.biblemap.put("b46_1_21", new hebsuperobject(46,1,21,"כי אחרי אשר בחכמת האלהים לא ידע העולם את האלהים בחכמה היה רצון לפניו להושיע בסכלות הקריאה את המאמינים׃"));
hebsuperobject.biblemap.put("b46_1_22", new hebsuperobject(46,1,22,"כי היהודים שאלים להם אות והיונים מבקשים חכמה׃"));
hebsuperobject.biblemap.put("b46_1_23", new hebsuperobject(46,1,23,"ואנחנו משמיעים את המשיח הצלוב מכשול ליהודים וסכלות ליונים׃"));
hebsuperobject.biblemap.put("b46_1_24", new hebsuperobject(46,1,24,"אבל למקראים הן מיהודים הן מיונים את המשיח אשר הוא גבורת אלהים וחכמת אלהים׃"));
hebsuperobject.biblemap.put("b46_1_25", new hebsuperobject(46,1,25,"יען כי סכלות האל חכמה היא מאדם וחלשת האל חזקה היא מאדם׃"));
hebsuperobject.biblemap.put("b46_1_26", new hebsuperobject(46,1,26,"כי ראו נא אחי את קריאתכם שלא רבים המה החכמים לפי הבשר לא רבים השליטים ולא רבים החרים׃"));
hebsuperobject.biblemap.put("b46_1_27", new hebsuperobject(46,1,27,"כי אם בסכל שבעולם בחר האל למען ביש את החכמים ובחלוש שבעולם בחר האל למען ביש את החזק׃"));
hebsuperobject.biblemap.put("b46_1_28", new hebsuperobject(46,1,28,"ובדלת העולם בחר האל ובנמאס ובאשר כאין למען בטל את אשר ישנו׃"));
hebsuperobject.biblemap.put("b46_1_29", new hebsuperobject(46,1,29,"כדי שלא יתהלל לפניו כל בשר׃"));
hebsuperobject.biblemap.put("b46_1_30", new hebsuperobject(46,1,30,"וממנו אתם במשיח ישוע אשר היה לנו לחכמה מאת האלהים ולצדקה ולקדוש ולפדיון׃"));
hebsuperobject.biblemap.put("b46_1_31", new hebsuperobject(46,1,31,"ויהי ככתוב המתהלל יתהלל ביהוה׃"));
hebsuperobject.biblemap.put("b46_2_1", new hebsuperobject(46,2,1,"וגם אנכי בבאי אליכם אחי לא באתי בגאות הדבור והחכמה בהגידי לכם את עדות האלהים׃"));
hebsuperobject.biblemap.put("b46_2_2", new hebsuperobject(46,2,2,"כי לא חשבתי לדעת בתוככם דבר בלתי אם ישוע המשיח והוא הנצלב׃"));
hebsuperobject.biblemap.put("b46_2_3", new hebsuperobject(46,2,3,"ואהי אצלכם בחלשה וביראה ובחלחלה רבה׃"));
hebsuperobject.biblemap.put("b46_2_4", new hebsuperobject(46,2,4,"ודברי וקריאתי לא לפתות באמרי חכמת בני אדם כי אם בתוכחת הרוח והגבורה׃"));
hebsuperobject.biblemap.put("b46_2_5", new hebsuperobject(46,2,5,"למען אשר לא תהיה אמונתכם בחכמת בני אדם כי אם בגבורת אלהים׃"));
hebsuperobject.biblemap.put("b46_2_6", new hebsuperobject(46,2,6,"אכן חכמה נדבר בין השלמים לא חכמת העולם הזה גם לא של שרי העולם הזה אשר יאבדו׃"));
hebsuperobject.biblemap.put("b46_2_7", new hebsuperobject(46,2,7,"כי אם בסוד נדבר חכמת האלהים הנסתרה אשר האלהים יעדה לכבודנו לפני ימי העולם׃"));
hebsuperobject.biblemap.put("b46_2_8", new hebsuperobject(46,2,8,"אשר לא ידעה איש משרי העולם הזה כי לו ידעוה לא צלבו את אדון הכבוד׃"));
hebsuperobject.biblemap.put("b46_2_9", new hebsuperobject(46,2,9,"אלא ככתוב אשר עין לא ראתה ואזן לא שמעה ולא עלה על לב אנוש את אשר הכין האלהים לאהביו׃"));
hebsuperobject.biblemap.put("b46_2_10", new hebsuperobject(46,2,10,"ולנו גלה האלהים ברוחו כי הרוח חוקר את הכל גם את מעמקי האלהים׃"));
hebsuperobject.biblemap.put("b46_2_11", new hebsuperobject(46,2,11,"כי מי הוא בבני אדם הידע את אשר באדם בלתי אם רוח האדם אשר בקרבו כן גם לא ידע איש את אשר באלהים בלתי אם רוח האלהים׃"));
hebsuperobject.biblemap.put("b46_2_12", new hebsuperobject(46,2,12,"ואנחנו לא קבלנו את רוח העולם כי אם הרוח מאת האלהים למען נדע את אשר נתן לנו מאת האלהים בחסדו׃"));
hebsuperobject.biblemap.put("b46_2_13", new hebsuperobject(46,2,13,"ואת זאת נדבר לא בדברים אשר תלמדם חכמת בני אדם כי אם בדברים אשר רוח הקדש תלמדם ונבאר דברים רוחניים על פי הרוח׃"));
hebsuperobject.biblemap.put("b46_2_14", new hebsuperobject(46,2,14,"הן האדם הנפשי איננו מקבל את דברי רוח אלהים כי המה סכלות לו ולא יוכל להבינם באשר המה נדונים בדרך הרוח׃"));
hebsuperobject.biblemap.put("b46_2_15", new hebsuperobject(46,2,15,"אבל האדם הרוחני ידין את הכל ואותו לא ידין איש׃"));
hebsuperobject.biblemap.put("b46_2_16", new hebsuperobject(46,2,16,"כי מי תכן את רוח יהוה ומי יודיענו ואנחנו הנה יש לנו רוח המשיח׃"));
hebsuperobject.biblemap.put("b46_3_1", new hebsuperobject(46,3,1,"ואני לא יכלתי לדבר עמכם אחי כעם רוחניים כי עודכם של הבשר וכמו עוללים במשיח׃"));
hebsuperobject.biblemap.put("b46_3_2", new hebsuperobject(46,3,2,"חלב השקיתי אתכם ולא מאכל כי אז לא יכלתם וגם עתה לא תוכלו יען היתכם עוד של הבשר׃"));
hebsuperobject.biblemap.put("b46_3_3", new hebsuperobject(46,3,3,"כי באשר קנאה ומריבה ומחלקים ביניכם הלא של הבשר אתם ומתהלכים לפי דרך בני אדם׃"));
hebsuperobject.biblemap.put("b46_3_4", new hebsuperobject(46,3,4,"הן באמר האחד אני לפולוס והשני אני לאפולוס הלא של הבשר אתם׃"));
hebsuperobject.biblemap.put("b46_3_5", new hebsuperobject(46,3,5,"מי אפוא פולוס ומי הוא אפולוס אך משרתים הם אשר על ידם באתם להאמין איש איש כמתנת האדון אשר נתן לו׃"));
hebsuperobject.biblemap.put("b46_3_6", new hebsuperobject(46,3,6,"אני נטעתי ואפולוס השקה אבל האלהים הוא הצמיח׃"));
hebsuperobject.biblemap.put("b46_3_7", new hebsuperobject(46,3,7,"על כן הנטע איננו מאומה והמשקה איננו מאומה כי אם האלהים המצמיח׃"));
hebsuperobject.biblemap.put("b46_3_8", new hebsuperobject(46,3,8,"והנטע והמשקה כאחד המה ואיש איש יקבל את שכרו כפי עמלו׃"));
hebsuperobject.biblemap.put("b46_3_9", new hebsuperobject(46,3,9,"כי עזרי אל אנחנו ואתם שדה אלהים ובנין אלהים אתם׃"));
hebsuperobject.biblemap.put("b46_3_10", new hebsuperobject(46,3,10,"]11-01[ ואני כפי חסד אלהים הנתן לי כבני חכם שתי יסוד ואחר בונה עליו אך ירא כל איש לשית יסוד אחר חוץ מן המוסד שהוא ישוע המשיח׃"));
hebsuperobject.biblemap.put("b46_3_11", new hebsuperobject(46,3,11,"]11-01[׃"));
hebsuperobject.biblemap.put("b46_3_12", new hebsuperobject(46,3,12,"ואם יבנה הבונה על היסוד הזה זהב או כסף או אבנים יקרות או עץ או חציר או קש׃"));
hebsuperobject.biblemap.put("b46_3_13", new hebsuperobject(46,3,13,"מעשה כל איש יגלה כי היום הוא יבררהו כי באש יראה ואת מה מעשה כל איש ואיש האש תבחננו׃"));
hebsuperobject.biblemap.put("b46_3_14", new hebsuperobject(46,3,14,"אם יעמד מעשה איש אשר בנה עליו יקבל שכרו׃"));
hebsuperobject.biblemap.put("b46_3_15", new hebsuperobject(46,3,15,"ואם ישרף מעשהו יפסידנו והוא יושע אך כמו מצל מאש׃"));
hebsuperobject.biblemap.put("b46_3_16", new hebsuperobject(46,3,16,"הלא ידעתם כי היכל אלהים אתם ורוח אלהים שכן בקרבכם׃"));
hebsuperobject.biblemap.put("b46_3_17", new hebsuperobject(46,3,17,"ואיש אשר ישחית את היכל אלהים האלהים ישחית אתו כי היכל אלהים קדוש ואתם הנכם קדושים׃"));
hebsuperobject.biblemap.put("b46_3_18", new hebsuperobject(46,3,18,"אל ירמה איש את עצמו והחשב את עצמו חכם בעולם הזה יהי לסכל למען יחכם׃"));
hebsuperobject.biblemap.put("b46_3_19", new hebsuperobject(46,3,19,"כי חכמת העולם הזה סכלות היא לפני האלהים ככתוב לכד חכמים בערמם׃"));
hebsuperobject.biblemap.put("b46_3_20", new hebsuperobject(46,3,20,"ועוד כתוב יהוה ידע מחשבות חכמים כי המה הבל׃"));
hebsuperobject.biblemap.put("b46_3_21", new hebsuperobject(46,3,21,"על כן אל יתהלל איש באדם כי הכל הוא שלכם׃"));
hebsuperobject.biblemap.put("b46_3_22", new hebsuperobject(46,3,22,"אם פולוס אם אפולוס ואם כיפא אם העולם אם החיים ואם המות אם ההוה ואם העתיד הכל הוא שלכם׃"));
hebsuperobject.biblemap.put("b46_3_23", new hebsuperobject(46,3,23,"ואתם הנכם של המשיח והמשיח הוא של אלהים׃"));
hebsuperobject.biblemap.put("b46_4_1", new hebsuperobject(46,4,1,"כן יחשב איש אתנו כמשרתי המשיח וסכני רזי אל׃"));
hebsuperobject.biblemap.put("b46_4_2", new hebsuperobject(46,4,2,"הנה סוף דבר שלא יבקש מן הסכנים כי אם להמצא נאמן׃"));
hebsuperobject.biblemap.put("b46_4_3", new hebsuperobject(46,4,3,"ואני נקלה היא בעיני כי אתם דנים אתי או יום דין של בני אדם גם אני את נפשי לא אדין׃"));
hebsuperobject.biblemap.put("b46_4_4", new hebsuperobject(46,4,4,"כי אינני יודע בנפשי רע ובכל זאת לא אצדק כי הדן אתי הוא יהוה׃"));
hebsuperobject.biblemap.put("b46_4_5", new hebsuperobject(46,4,5,"על כן אל תשפטו שפוט לפני העת עד כי יבוא האדון אשר גם יוציא לאור את תעלמות החשך ויגלה את עצת הלבבות ואז תהיה תהלה לכל איש מאת האלהים׃"));
hebsuperobject.biblemap.put("b46_4_6", new hebsuperobject(46,4,6,"ואת זאת אחי הסבתי על עצמי ועל אפולוס בעבורכם למען תלמדו בנו שלא יתחכם איש יותר ממה שכתוב פן תתגאו איש בשם איש לנגד רעהו׃"));
hebsuperobject.biblemap.put("b46_4_7", new hebsuperobject(46,4,7,"כי מי הפליא אותך ומה בידך אשר לא קבלתו ואם קבלתו למה תתהלל כאיש אשר לא קבל׃"));
hebsuperobject.biblemap.put("b46_4_8", new hebsuperobject(46,4,8,"הן כבר שבעתם כבר עשרתם ובלעדינו מלכתם ולו מלכתם למען נמלך אתכם גם אנחנו׃"));
hebsuperobject.biblemap.put("b46_4_9", new hebsuperobject(46,4,9,"כי אחשב שהאלהים הציג אתנו השליחים שפלי השפלים כבני תמותה כי היינו לראוה לעולם גם למלאכים גם לבני אדם׃"));
hebsuperobject.biblemap.put("b46_4_10", new hebsuperobject(46,4,10,"אנחנו סכלים למען המשיח ואתם חכמים במשיח אנחנו חלשים ואתם גבורים אתם נכבדים ואנחנו נקלים׃"));
hebsuperobject.biblemap.put("b46_4_11", new hebsuperobject(46,4,11,"ועד השעה הזאת הננו רעבים גם צמאים וערמים ומכים באגרף ואין מנוח לנו׃"));
hebsuperobject.biblemap.put("b46_4_12", new hebsuperobject(46,4,12,"ויגעים אנחנו בעמל ידינו קללונו ונברך חרפונו ונסבל׃"));
hebsuperobject.biblemap.put("b46_4_13", new hebsuperobject(46,4,13,"גדפו אתנו ותנחנן ונהי כגללי העולם ולסחי לכלם עד עתה׃"));
hebsuperobject.biblemap.put("b46_4_14", new hebsuperobject(46,4,14,"ולא לביש אתכם אני כתב הדברים האלה כי אם מזהיר אתכם כבני האהובים׃"));
hebsuperobject.biblemap.put("b46_4_15", new hebsuperobject(46,4,15,"כי גם אם היו לכם רבבות אמנים במשיח אין לכם אבות רבים כי אנכי הולדתי אתכם בישוע המשיח על ידי הבשורה׃"));
hebsuperobject.biblemap.put("b46_4_16", new hebsuperobject(46,4,16,"על כן אני מבקש מכם ללכת בעקבותי׃"));
hebsuperobject.biblemap.put("b46_4_17", new hebsuperobject(46,4,17,"ובעבור זאת שלחתי אליכם את טימותיוס בני האהוב והנאמן באדון והוא יזכיר לכם את דרכי במשיח כאשר מלמד אנכי בכל מקום בכל קהלה וקהלה׃"));
hebsuperobject.biblemap.put("b46_4_18", new hebsuperobject(46,4,18,"הן יש מתנשאים כאלו לא אבוא אליכם׃"));
hebsuperobject.biblemap.put("b46_4_19", new hebsuperobject(46,4,19,"אבל בוא אבוא אליכם בזמן קרוב אם ירצה האדון ואדעה לא את דברי המתרוממים כי אם את גבורתם׃"));
hebsuperobject.biblemap.put("b46_4_20", new hebsuperobject(46,4,20,"כי מלכות האלהים איננה בדבר שפתים כי אם בגבורה׃"));
hebsuperobject.biblemap.put("b46_4_21", new hebsuperobject(46,4,21,"ומה תחפצו הבוא אבוא אליכם בשבט או באהבה וברוח ענוה׃"));
hebsuperobject.biblemap.put("b46_5_1", new hebsuperobject(46,5,1,"שמועה נשמעת בארץ כי נמצאה זנות ביניכם ואף זנות אשר בגוים לא ספר כמוה כי יקח איש את אשת אביו׃"));
hebsuperobject.biblemap.put("b46_5_2", new hebsuperobject(46,5,2,"ואתם עוד גבהי רוח תחת אשר היה לכם להתאבל למען יוסר מקרבכם עשה המעשה הזה׃"));
hebsuperobject.biblemap.put("b46_5_3", new hebsuperobject(46,5,3,"הן אנכי הרחוק מכם בגופי וקרוב ברוחי כבר דנתי כאלו הייתי אצלכם על האיש אשר עשה כדבר הזה׃"));
hebsuperobject.biblemap.put("b46_5_4", new hebsuperobject(46,5,4,"בשם אדנינו ישוע המשיח בהקהלתכם יחד ורוחי אתכם עם גבורת אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b46_5_5", new hebsuperobject(46,5,5,"למסר את האיש ההוא לשטן לאבדן הבשר למען יושע הרוח ביום האדון ישוע׃"));
hebsuperobject.biblemap.put("b46_5_6", new hebsuperobject(46,5,6,"לא טוב התהללכם הלא ידעתם כי מעט שאר מחמץ את כל העסה׃"));
hebsuperobject.biblemap.put("b46_5_7", new hebsuperobject(46,5,7,"בערו את השאור הישן למען תהיו עסה חדשה הלא לחם מצות אתם כי גם לנו פסחנו הנזבח בעדנו הוא המשיח׃"));
hebsuperobject.biblemap.put("b46_5_8", new hebsuperobject(46,5,8,"על כן נחגה נא החג לא בשאר ישן ולא בשאר הרע והרשע כי אם במצות הישר והאמת׃"));
hebsuperobject.biblemap.put("b46_5_9", new hebsuperobject(46,5,9,"כתבתי לכם באגרת שלא תתערבו עם הזנים׃"));
hebsuperobject.biblemap.put("b46_5_10", new hebsuperobject(46,5,10,"ואין דעתי בזאת על הזנים שבעולם הזה או על בצעי בצע וגזלנים ועבדי אלילים כי אז יהיה לכם לצאת מן העולם׃"));
hebsuperobject.biblemap.put("b46_5_11", new hebsuperobject(46,5,11,"אך זאת כתבתי לכם לבלתי התערב עם איש אשר אח יקרא והוא זנה או בצע בצע או עבד אלילים או מגדף או סבא או גזלן עם האיש אשר כזה גם לא תאכלו׃"));
hebsuperobject.biblemap.put("b46_5_12", new hebsuperobject(46,5,12,"כי מה לי לשפט את אשר בחוץ הלא תשפטו את אשר בבית׃"));
hebsuperobject.biblemap.put("b46_5_13", new hebsuperobject(46,5,13,"ואשר בחוץ האלהים ישפטם ואתם תבערו את הרע מקרבכם׃"));
hebsuperobject.biblemap.put("b46_6_1", new hebsuperobject(46,6,1,"היש בכם איש אשר בריבו עם רעהו יזיד להביא דבר דינו לפני הרשעים ולא לפני הקדשים׃"));
hebsuperobject.biblemap.put("b46_6_2", new hebsuperobject(46,6,2,"הלא ידעתם כי הקדשים ידינו את העולם ואם העולם ידון על ידכם האינכם ראוים לדין דינים קטנים׃"));
hebsuperobject.biblemap.put("b46_6_3", new hebsuperobject(46,6,3,"הלא ידעתם כי נדין את המלאכים אף כי דברי ממונות׃"));
hebsuperobject.biblemap.put("b46_6_4", new hebsuperobject(46,6,4,"ואתם כאשר יש לכם דיני ממונות מושיבים אתם את הנחשבים לאין בקהל לשפטיכם׃"));
hebsuperobject.biblemap.put("b46_6_5", new hebsuperobject(46,6,5,"לבשתכם אמר אני את זאת הכי אין בכם חכם אחד שיוכל להוכיח בין איש לאחיו׃"));
hebsuperobject.biblemap.put("b46_6_6", new hebsuperobject(46,6,6,"כי אח רב עם אחיו וזאת לפני לא מאמינים׃"));
hebsuperobject.biblemap.put("b46_6_7", new hebsuperobject(46,6,7,"הן בכל ירידה היא לכם שתריבו זה עם זה למה לא תבחרו לסבל הונאה ולמה לא תבחרו להיות עשוקים׃"));
hebsuperobject.biblemap.put("b46_6_8", new hebsuperobject(46,6,8,"אבל מונים אתם ועשקים אף את אחיכם׃"));
hebsuperobject.biblemap.put("b46_6_9", new hebsuperobject(46,6,9,"הלא ידעתם כי הרשעים לא יירשו את מלכות האלהים אל תתעו את נפשותיכם לא הזנים לא עבדי אלילים לא המנאפים ולא הקדשים ולא השכבים את זכר׃"));
hebsuperobject.biblemap.put("b46_6_10", new hebsuperobject(46,6,10,"לא הגנבים ולא בצעי בצע לא הסבאים ולא המגדפים ולא הגזלנים כל אלה לא יירשו את מלכות האלהים׃"));
hebsuperobject.biblemap.put("b46_6_11", new hebsuperobject(46,6,11,"וכאלה לפנים היו מקצתכם אבל רחצתם אבל קדשתם אבל הצדקתם בשם האדון ישוע וברוח אלהינו׃"));
hebsuperobject.biblemap.put("b46_6_12", new hebsuperobject(46,6,12,"הכל הוא ברשותי אך לא כל דבר יועיל הכל הוא ברשותי אך לא ישעבדני דבר׃"));
hebsuperobject.biblemap.put("b46_6_13", new hebsuperobject(46,6,13,"המאכל לכרש והכרש למאכל והאלהים את זה ואת זה ילכה והגוף אל יהי לזנות כי אם לאדון והאדון לגוף׃"));
hebsuperobject.biblemap.put("b46_6_14", new hebsuperobject(46,6,14,"והאלהים העיר גם את אדנינו ויעיר גם אתכם בגבורתו׃"));
hebsuperobject.biblemap.put("b46_6_15", new hebsuperobject(46,6,15,"הלא ידעתם כי גופתיכם אברי המשיח הנה הכי אקח את אברי המשיח ואעשה אתם לאברי זונה חלילה׃"));
hebsuperobject.biblemap.put("b46_6_16", new hebsuperobject(46,6,16,"או הלא ידעתם כי הדבק בזונה גוף אחד הוא עמה כי הכתוב אמר והיו שניהם לבשר אחד׃"));
hebsuperobject.biblemap.put("b46_6_17", new hebsuperobject(46,6,17,"אבל הדבק באדון רוח אחד הוא עמו׃"));
hebsuperobject.biblemap.put("b46_6_18", new hebsuperobject(46,6,18,"נוסו מן הזנות כל חטא אשר יעשה אותו האדם מחוץ לגופו הוא והזונה חטא בעצם גופו׃"));
hebsuperobject.biblemap.put("b46_6_19", new hebsuperobject(46,6,19,"או הלא ידעתם כי גופכם הוא היכל רוח הקדש השכן בקרבכם אשר קבלתם מאת האלהים וכי לא לעצמכם אתם׃"));
hebsuperobject.biblemap.put("b46_6_20", new hebsuperobject(46,6,20,"כי במחיר נקניתם על כן כבדו את האלהים בגופכם וברוחכם אשר לאלהים המה׃"));
hebsuperobject.biblemap.put("b46_7_1", new hebsuperobject(46,7,1,"ולענים מה שכתבתם אלי הנה טוב לאדם שלא יגע באשה׃"));
hebsuperobject.biblemap.put("b46_7_2", new hebsuperobject(46,7,2,"אך מפני הזנות תהי לכל איש אשתו ויהי לכל אשה בעלה׃"));
hebsuperobject.biblemap.put("b46_7_3", new hebsuperobject(46,7,3,"האיש יקים חובת העונה לאשתו וכמו כן האשה לבעלה׃"));
hebsuperobject.biblemap.put("b46_7_4", new hebsuperobject(46,7,4,"האשה איננה שלטת על גופה כי אם בעלה וכמו כן גם האיש איננו שלט על גופו כי אם אשתו׃"));
hebsuperobject.biblemap.put("b46_7_5", new hebsuperobject(46,7,5,"אל תמנעו את עצמכם זה מזה זולתי בהסכמת שניכם על זמן קבוע להיות פנוים לתענית ולתפלה ותשובו ותתאחדו פן ינסה אתכם השטן בעבור פריצות יצרכם׃"));
hebsuperobject.biblemap.put("b46_7_6", new hebsuperobject(46,7,6,"ואני אמר זאת בדרך עצה ולא בדרך מצוה׃"));
hebsuperobject.biblemap.put("b46_7_7", new hebsuperobject(46,7,7,"כי מי יתן והיה כל אדם כמני אך יש לכל איש מתנתו מאת האלהים זה בכה וזה בכה׃"));
hebsuperobject.biblemap.put("b46_7_8", new hebsuperobject(46,7,8,"ואל הפנוים ואל האלמנות אמר אני כי טוב להם אם ישבו ככה כמו גם אני׃"));
hebsuperobject.biblemap.put("b46_7_9", new hebsuperobject(46,7,9,"אך אם לא יוכלו להנזר יתחברו בנשואין כי טוב להתחבר בנשואין מהיות בער בתאוה׃"));
hebsuperobject.biblemap.put("b46_7_10", new hebsuperobject(46,7,10,"והנה את הנשואים אנכי מצוה ולא אנכי כי אם האדון אשר לא תפרש אשה מבעלה׃"));
hebsuperobject.biblemap.put("b46_7_11", new hebsuperobject(46,7,11,"ואם פרש תפרש ממנו תשב בלא איש או תתרצה לבעלה ואיש אל ישלח את אשתו׃"));
hebsuperobject.biblemap.put("b46_7_12", new hebsuperobject(46,7,12,"והנה אל האחרים אמר אנכי ולא האדון כי תהיה לאח אשה אשר איננה מאמנת ורצונה לשבת עמו לא יעזבנה׃"));
hebsuperobject.biblemap.put("b46_7_13", new hebsuperobject(46,7,13,"ואשה כי יהיה לה בעל אשר איננו מאמין ורצונו לשבת עמה לא תעזבנו׃"));
hebsuperobject.biblemap.put("b46_7_14", new hebsuperobject(46,7,14,"כי האיש אשר איננו מאמין מקדש הוא באשה והאשה אשר איננה מאמנת מקדשת היא באיש שאם לא כן יהיו בניכם טמאים אמנם עתה קדושים המה׃"));
hebsuperobject.biblemap.put("b46_7_15", new hebsuperobject(46,7,15,"אבל אם יפרש מי שאיננו מאמין יפרש והאח או האחות אינם משעבדים באלה כי לשלום קראנו האלהים׃"));
hebsuperobject.biblemap.put("b46_7_16", new hebsuperobject(46,7,16,"כי מה תדעי את האשה אם תושיעי את האיש ומה תדע אתה האיש אם תושיע את האשה׃"));
hebsuperobject.biblemap.put("b46_7_17", new hebsuperobject(46,7,17,"רק יתהלך איש איש כפי מה שחלק לו האלהים וכפי מה שקרא אתו האדון וכן מתקן אנכי בכל הקהלות׃"));
hebsuperobject.biblemap.put("b46_7_18", new hebsuperobject(46,7,18,"אם נמול האיש המקרא אל ימשך את ערלתו ואם ערל הוא אל ימול׃"));
hebsuperobject.biblemap.put("b46_7_19", new hebsuperobject(46,7,19,"אין המילה נחשבה ואין הערלה נחשבה כי אם שמירת מצות האלהים׃"));
hebsuperobject.biblemap.put("b46_7_20", new hebsuperobject(46,7,20,"איש איש במשמרתו אשר נקרא בה שם יעמד׃"));
hebsuperobject.biblemap.put("b46_7_21", new hebsuperobject(46,7,21,"אם נקראת בהיותך עבד אל ירע בעיניך אלא אם תשיג ידך לצאת לחפשי בחר בזה׃"));
hebsuperobject.biblemap.put("b46_7_22", new hebsuperobject(46,7,22,"כי הקרוא באדון בהיותו עבד משחרר הוא לאדון וככה גם הקרוא בהיותו חפשי עבד הוא למשיח׃"));
hebsuperobject.biblemap.put("b46_7_23", new hebsuperobject(46,7,23,"במחיר נקניתם אל תהיו עבדי בני אדם׃"));
hebsuperobject.biblemap.put("b46_7_24", new hebsuperobject(46,7,24,"איש איש במשמרת אשר נקרא בה אחי בזאת יעמד לפני האלהים׃"));
hebsuperobject.biblemap.put("b46_7_25", new hebsuperobject(46,7,25,"ועל דבר הבתולות אין לי מצוה מאת האדון רק אודיע את עצתי אחרי אשר חנני האדון להיות נאמן׃"));
hebsuperobject.biblemap.put("b46_7_26", new hebsuperobject(46,7,26,"הנני חשב כי טוב לאדם מפני הצרה הקרובה כי טוב לו להיות כמו שהוא׃"));
hebsuperobject.biblemap.put("b46_7_27", new hebsuperobject(46,7,27,"אם נקשרת באשה אל תבקש להפטר ואם נפטרת אל תבקש אשה׃"));
hebsuperobject.biblemap.put("b46_7_28", new hebsuperobject(46,7,28,"וגם כי תקח אשה אינך חטא והבתולה כי תהיה לאיש איננה חטאת אך יבאום צרות בבשרם והנני חס עליכם׃"));
hebsuperobject.biblemap.put("b46_7_29", new hebsuperobject(46,7,29,"וזאת אני אמר אחי כי השעה דחוקה למען מעתה יהיו הנשואים כאלו אין להם נשים׃"));
hebsuperobject.biblemap.put("b46_7_30", new hebsuperobject(46,7,30,"והבכים כאינם בכים והשמחים כאינם שמחים והקונים כאלו אין קנין בידם׃"));
hebsuperobject.biblemap.put("b46_7_31", new hebsuperobject(46,7,31,"והנהנים מן העולם הזה כאלו אין להם הנאה ממנו כי עבור יעבר תאר העולם הזה׃"));
hebsuperobject.biblemap.put("b46_7_32", new hebsuperobject(46,7,32,"ואני חפצתי שתהיו בלי דאגה מי שאין לו אשה דאג לאשר לאדון איך ייטב בעיני האדון׃"));
hebsuperobject.biblemap.put("b46_7_33", new hebsuperobject(46,7,33,"ומי שיש לו אשה דאג הוא לעניני העולם איך ייטב בעיני האשה׃"));
hebsuperobject.biblemap.put("b46_7_34", new hebsuperobject(46,7,34,"יש הבדל בין אשת איש לבתולה כי האשה אשר לא היתה לאיש דאגת לאשר לאדון ולהיות קדושה גם בגופה גם ברוחה ובעולת בעל דאגת היא לעניני העולם איך תיטב בעיני בעלה׃"));
hebsuperobject.biblemap.put("b46_7_35", new hebsuperobject(46,7,35,"וזאת אני אמר לתועלתכם ולא להשליך עליכם פח כי אם להנהגה טובה ולהיותכם נכונים תמיד לפני האדון באין מנע׃"));
hebsuperobject.biblemap.put("b46_7_36", new hebsuperobject(46,7,36,"וכי יחשב איש למעשה שלא כהגן לבתולתו אם תעבר פרקה ודבר חובה הוא אז יעשה כאשר עם לבבו איננו חוטא ישיאנה׃"));
hebsuperobject.biblemap.put("b46_7_37", new hebsuperobject(46,7,37,"ומי שהוא נכון בלבו ואיננו מכרח ויוכל לעשות כרצונו ויגמר זאת בלבו לשמר את בתולתו טוב עשה׃"));
hebsuperobject.biblemap.put("b46_7_38", new hebsuperobject(46,7,38,"לכן המשיא אתה טוב הוא עשה ואשר איננו משיא עשה טוב ממנו׃"));
hebsuperobject.biblemap.put("b46_7_39", new hebsuperobject(46,7,39,"האשה קשורה לבעלה על פי התורה כל עת שהוא חי וכי מת בעלה אזי מתרת היא להנשא למי שתרצה ובלבד שתהיה באדון׃"));
hebsuperobject.biblemap.put("b46_7_40", new hebsuperobject(46,7,40,"אבל אשריה יותר אם תעמד פנויה זאת דעתי ואחשב גם אני כי רוח אלהים בי׃"));
hebsuperobject.biblemap.put("b46_8_1", new hebsuperobject(46,8,1,"ועל דבר זבחי האלילים ידענו שיש דעה לכלנו הדעת תגביה לב והאהבה היא הבונה׃"));
hebsuperobject.biblemap.put("b46_8_2", new hebsuperobject(46,8,2,"החשב כי הוא ידע דבר מה עוד לא ידע מאומה כאשר עליו לדעת אתו׃"));
hebsuperobject.biblemap.put("b46_8_3", new hebsuperobject(46,8,3,"אבל אם יאהב איש את האלהים האלהים ידעו׃"));
hebsuperobject.biblemap.put("b46_8_4", new hebsuperobject(46,8,4,"ועל דבר אכילת זבחי האלילים הנה ידענו כי האליל אין בעולם ואין אלהים בלתי אחד׃"));
hebsuperobject.biblemap.put("b46_8_5", new hebsuperobject(46,8,5,"ואף כי יש הנקראים אלהים אם בשמים אם בארץ באשר יש אלהים רבים ואדנים רבים׃"));
hebsuperobject.biblemap.put("b46_8_6", new hebsuperobject(46,8,6,"אמנם לנו אך לא אחד האב אשר הכל ממנו ואנחנו אליו ואדון אחד ישוע המשיח אשר הכל על ידו ונחנו על ידו׃"));
hebsuperobject.biblemap.put("b46_8_7", new hebsuperobject(46,8,7,"אך לא בכלם הדעת כי יש אשר בזכרם עוד את האליל אכלים כזבח האליל ובכן לבם החלוש יתגאל׃"));
hebsuperobject.biblemap.put("b46_8_8", new hebsuperobject(46,8,8,"המאכל לא יקרב אתכם לאלהים כי אם נאכל אין לנו יתרון ואם לא נאכל לא נגרע׃"));
hebsuperobject.biblemap.put("b46_8_9", new hebsuperobject(46,8,9,"אבל הזהרו פן יהיה אתו הרשיון שלכם למכשל החלשים׃"));
hebsuperobject.biblemap.put("b46_8_10", new hebsuperobject(46,8,10,"כי האיש הראה אתך אשר לך הדעת מסב בבית אלילים הלא יעז ברוחו החלוש לאכל מזבחי אלילים׃"));
hebsuperobject.biblemap.put("b46_8_11", new hebsuperobject(46,8,11,"ויאבד על ידי דעתך אחיך החלש אשר למענו מת המשיח׃"));
hebsuperobject.biblemap.put("b46_8_12", new hebsuperobject(46,8,12,"ואם ככה תחטאו לאחיכם ותכאיבו את רוחם החלוש למשיח אתם חטאים׃"));
hebsuperobject.biblemap.put("b46_8_13", new hebsuperobject(46,8,13,"על כן אם מאכלי מכשיל את אחי לא אכל בשר לעולם למען לא אכשיל את אחי׃"));
hebsuperobject.biblemap.put("b46_9_1", new hebsuperobject(46,9,1,"הלא שליח אנכי הלא חפשי אנכי הלא ראיתי את ישוע המשיח אדנינו הלא אתם פעלי באדנינו׃"));
hebsuperobject.biblemap.put("b46_9_2", new hebsuperobject(46,9,2,"ואם אינני שליח לאחרים אך לכם הנני שליח כי חותם שליחותי אתם באדנינו׃"));
hebsuperobject.biblemap.put("b46_9_3", new hebsuperobject(46,9,3,"וזאת התנצלותי כנגד הדנים אותי׃"));
hebsuperobject.biblemap.put("b46_9_4", new hebsuperobject(46,9,4,"האין רשות בידנו לאכל ולשתות׃"));
hebsuperobject.biblemap.put("b46_9_5", new hebsuperobject(46,9,5,"האין רשות בידנו להוליך עמנו אחות לאשה כמו גם השליחים האחרים וכמו אחי האדון וכמו כיפא׃"));
hebsuperobject.biblemap.put("b46_9_6", new hebsuperobject(46,9,6,"אם לי לבדי ולבר נבא לא נתנה רשות להבטל ממלאכה׃"));
hebsuperobject.biblemap.put("b46_9_7", new hebsuperobject(46,9,7,"מי הלך לצבא במשכרת של עצמו מי נטע כרם ולא יאכל את פריו מי רעה עדר ומחלב העדר לא יאכל׃"));
hebsuperobject.biblemap.put("b46_9_8", new hebsuperobject(46,9,8,"הכי לפי דרכו של אדם אני מדבר כזאת הלא גם התורה אמרת כן׃"));
hebsuperobject.biblemap.put("b46_9_9", new hebsuperobject(46,9,9,"כי כתוב בתורת משה לא תחסם שור בדישו הלשורים הושש האלהים׃"));
hebsuperobject.biblemap.put("b46_9_10", new hebsuperobject(46,9,10,"או אך למעננו מדבר אכן למעננו נכתב כי החרש יחרש אלי תקוה והדש ידוש אלי תקוה לקחת חלקו בתקוה׃"));
hebsuperobject.biblemap.put("b46_9_11", new hebsuperobject(46,9,11,"אם זרענו בכם עניני הרוח הכי דבר גדול הוא אם נקצר מכם עניני הבשר׃"));
hebsuperobject.biblemap.put("b46_9_12", new hebsuperobject(46,9,12,"ואם לאחרים יש רשות עליכם הלא ביותר לנו אבל לא השתמשנו ברשות הזאת כי אם סבלנו את הכל לבלתי שום מעצור לבשורת המשיח׃"));
hebsuperobject.biblemap.put("b46_9_13", new hebsuperobject(46,9,13,"הלא ידעתם כי עבדי עבדת הקדש אכלים מן הקדשים ומשרתי המזבח לקחים חלקם במזבח׃"));
hebsuperobject.biblemap.put("b46_9_14", new hebsuperobject(46,9,14,"כן תקן אדנינו גם הוא אשר יחיו המבשרים על הבשורה׃"));
hebsuperobject.biblemap.put("b46_9_15", new hebsuperobject(46,9,15,"ואנכי לא השתמשתי באחת מאלה וגם לא כתבתי זאת למען יעשה לי כזאת כי טוב לי המות מאשר ישים איש את תהלתי לריק׃"));
hebsuperobject.biblemap.put("b46_9_16", new hebsuperobject(46,9,16,"אם אבשר את הבשורה אין לי תהלה כי החובה מטלת עלי ואוי לי אם לא אבשר׃"));
hebsuperobject.biblemap.put("b46_9_17", new hebsuperobject(46,9,17,"כי אם ברצוני אעשה כן יהיה לי שכר ואם בעל כרחי פקדת משמרתי היא׃"));
hebsuperobject.biblemap.put("b46_9_18", new hebsuperobject(46,9,18,"ועתה מה הוא שכרי הלא זה שאבשר בשורת המשיח בלא מחיר לבלתי השתמש להנאת עצמי ברשיון הנתן לי בבשורה׃"));
hebsuperobject.biblemap.put("b46_9_19", new hebsuperobject(46,9,19,"כי בהיותי חפשי מכל עשיתי עצמי עבד לכל אדם למען אקנא את הרבים׃"));
hebsuperobject.biblemap.put("b46_9_20", new hebsuperobject(46,9,20,"ואהי ליהודים כיהודי לקנות היהודים ואשר הם תחת התורה הייתי להם כמו תחת התורה למען קנות אותם אשר תחת התורה׃"));
hebsuperobject.biblemap.put("b46_9_21", new hebsuperobject(46,9,21,"לאלה אשר בלי תורה הייתי כבלי תורה אף כי אינני בלי תורת האלהים כי אם תחת תורת המשיח אנכי למען קנות אותם אשר בלי תורה׃"));
hebsuperobject.biblemap.put("b46_9_22", new hebsuperobject(46,9,22,"ולחלשים הייתי כחלש לקנות את החלשים הכל לכלם נהייתי למען בכל דרך אושיע אחדים׃"));
hebsuperobject.biblemap.put("b46_9_23", new hebsuperobject(46,9,23,"ואת זאת אני עשה בעבור הבשורה למען אקח חלקי בה גם אנכי׃"));
hebsuperobject.biblemap.put("b46_9_24", new hebsuperobject(46,9,24,"הלא ידעתם כי רצי המרוצה באסטדין רצים כלם ורק אחד מהם ישיג את שכר הנצוח ככה רוצו למען תשיגהו׃"));
hebsuperobject.biblemap.put("b46_9_25", new hebsuperobject(46,9,25,"וכל העמד להאבק ינזר מכל דבר המה לקחת כתר נפסד ואנחנו לקחת כתר אשר איננו נפסד׃"));
hebsuperobject.biblemap.put("b46_9_26", new hebsuperobject(46,9,26,"לכן הנני רץ לא כמו בחשכה הנני נלחם לא כהולם רוח׃"));
hebsuperobject.biblemap.put("b46_9_27", new hebsuperobject(46,9,27,"כי אם אדכא את גופי ואשעבדנו פן אהיה אני הקורא לאחרים נאלח בעצמי׃"));
hebsuperobject.biblemap.put("b46_10_1", new hebsuperobject(46,10,1,"ולא אכחד מכם אחי אשר אבותינו היו כלם תחת הענן וכלם עברו בתוך הים׃"));
hebsuperobject.biblemap.put("b46_10_2", new hebsuperobject(46,10,2,"וכלם נטבלו למשה בענן ובים׃"));
hebsuperobject.biblemap.put("b46_10_3", new hebsuperobject(46,10,3,"וכלם אכלם מאכל אחד רוחני׃"));
hebsuperobject.biblemap.put("b46_10_4", new hebsuperobject(46,10,4,"וכלם שתו משקה אחד רוחני כי שתו מן הצור הרוחני ההלך עמהם והצור ההוא היה המשיח׃"));
hebsuperobject.biblemap.put("b46_10_5", new hebsuperobject(46,10,5,"אבל ברבם לא רצה האלהים ופגריהם נפלו במדבר׃"));
hebsuperobject.biblemap.put("b46_10_6", new hebsuperobject(46,10,6,"וכל זאת היתה לנו למופת לבלתי התאות לרעה כאשר התאוו גם המה׃"));
hebsuperobject.biblemap.put("b46_10_7", new hebsuperobject(46,10,7,"ולא תהיו עבדי אלילים כאשר היו מקצתם כמו שכתוב וישב העם לאכל ושתו ויקמו לצחק׃"));
hebsuperobject.biblemap.put("b46_10_8", new hebsuperobject(46,10,8,"ולא נהיה זנים כאשר זנו מקצתם ויפלו ביום אחד שלשה ועשרים אלף איש׃"));
hebsuperobject.biblemap.put("b46_10_9", new hebsuperobject(46,10,9,"ולא ננסה את המשיח כאשר נסוהו מקצתם ויאבדום הנחשים׃"));
hebsuperobject.biblemap.put("b46_10_10", new hebsuperobject(46,10,10,"גם לא תלינו כאשר הלינו מקצתם וימותו ביד המשחית׃"));
hebsuperobject.biblemap.put("b46_10_11", new hebsuperobject(46,10,11,"כל זאת מצאתם להיות למופת ותכתב למוסר לנו אשר הגיעו אלינו קצי העולמים׃"));
hebsuperobject.biblemap.put("b46_10_12", new hebsuperobject(46,10,12,"לכן החשב שהוא נצב ירא פן יפול׃"));
hebsuperobject.biblemap.put("b46_10_13", new hebsuperobject(46,10,13,"עדין לא בא עליכם נסיון אחר בלתי אם נסיון בני אדם כי נאמן הוא האלהים אשר לא יניח לנסות אתכם למעלה מיכלתכם כי אם יתן עם הנסיון גם תוצאתיו כדי שתוכלו שאת׃"));
hebsuperobject.biblemap.put("b46_10_14", new hebsuperobject(46,10,14,"על כן חביבי נוסו מעבודת אלילים׃"));
hebsuperobject.biblemap.put("b46_10_15", new hebsuperobject(46,10,15,"כמו אל נבונים מדבר אנכי ושפטו אתם את אשר אמר׃"));
hebsuperobject.biblemap.put("b46_10_16", new hebsuperobject(46,10,16,"כוס הברכה אשר אנחנו מברכים הלא היא התחברות דם המשיח והלחם אשר אנחנו בצעים הלא הוא התחברות גוף המשיח׃"));
hebsuperobject.biblemap.put("b46_10_17", new hebsuperobject(46,10,17,"כי לחם אחד הוא לכן גם נוף אחד אנחנו הרבים באשר לכלנו חלק בלחם האחד׃"));
hebsuperobject.biblemap.put("b46_10_18", new hebsuperobject(46,10,18,"ראו את ישראל לפי הבשר הלא אכלי הזבחים חברי המזבח המה׃"));
hebsuperobject.biblemap.put("b46_10_19", new hebsuperobject(46,10,19,"ועתה מה אמר היש ממש באליל אם יש ממש בזבחי אלילים׃"));
hebsuperobject.biblemap.put("b46_10_20", new hebsuperobject(46,10,20,"אלא את אשר יזבחו הגוים לשדים הם זבחים ולא לאלהים ואני לא אחפץ היתכם חברים לשדים׃"));
hebsuperobject.biblemap.put("b46_10_21", new hebsuperobject(46,10,21,"לא תוכלו לשתות יחד כוס אדנינו וגם כוס השדים ולא תוכלו להתחבר אל שלחן אדנינו וגם אל שלחן השדים׃"));
hebsuperobject.biblemap.put("b46_10_22", new hebsuperobject(46,10,22,"הנעז להקניא את אדנינו הכי חזקים אנחנו ממנו׃"));
hebsuperobject.biblemap.put("b46_10_23", new hebsuperobject(46,10,23,"הכל ברשותי אבל אין הכל מועיל הכל ברשותי אבל אין הכל בנה׃"));
hebsuperobject.biblemap.put("b46_10_24", new hebsuperobject(46,10,24,"איש איש אל יבקש את תועלת עצמו כי אם את תועלת רעהו׃"));
hebsuperobject.biblemap.put("b46_10_25", new hebsuperobject(46,10,25,"כל הנמכר במקולין אתו תאכלו ואל תחקרו מפני מכשל הלב׃"));
hebsuperobject.biblemap.put("b46_10_26", new hebsuperobject(46,10,26,"כי ליהוה הארץ ומלואה׃"));
hebsuperobject.biblemap.put("b46_10_27", new hebsuperobject(46,10,27,"ואם יקרא אתכם איש מאשר אינם מאמינים ותרצו ללכת אליו אכול תאכלו מכל אשר ישימו לפניכם ואל תחקרו מפני מכשול הלב׃"));
hebsuperobject.biblemap.put("b46_10_28", new hebsuperobject(46,10,28,"ואיש כי יאמר אליכם זה הוא זבח אלילים אל תאכלו בעבור המודיע ומפני מכשול הלב כי ליהוה הארץ ולמואה׃"));
hebsuperobject.biblemap.put("b46_10_29", new hebsuperobject(46,10,29,"והלב אשר אני אמר לא לבך כי אם לב רעך כי למה זה תשפט חרותי על ידי לב האחר׃"));
hebsuperobject.biblemap.put("b46_10_30", new hebsuperobject(46,10,30,"ואם אכל אני בתודה למה אהיה מגדף על הדבר אשר אני מודה עליו׃"));
hebsuperobject.biblemap.put("b46_10_31", new hebsuperobject(46,10,31,"לכן אם תאכלו או אם תשתו או כל אשר תעשו את הכל עשו לכבוד אלהים׃"));
hebsuperobject.biblemap.put("b46_10_32", new hebsuperobject(46,10,32,"ואל תתנו מכשול לא ליהודים ולא ליונים ולא לקהלת אלהים׃"));
hebsuperobject.biblemap.put("b46_10_33", new hebsuperobject(46,10,33,"כאשר גם אנכי מבקש להיות רצוי לכל בכל ולא אבקש תועלת עצמי כי אם של הרבים למען יושעו׃"));
hebsuperobject.biblemap.put("b46_11_1", new hebsuperobject(46,11,1,"לכו בעקבותי כאשר גם אני הלך בעקבות המשיח׃"));
hebsuperobject.biblemap.put("b46_11_2", new hebsuperobject(46,11,2,"ועל זאת אני משבח אתכם אחי כי זכרתם אתי בכל לשמר את הקבלות כאשר מסרתי לכם׃"));
hebsuperobject.biblemap.put("b46_11_3", new hebsuperobject(46,11,3,"אך חפץ אנכי שתדעו כי ראש כל איש המשיח וראש האשה האיש וראש המשיח הוא האלהים׃"));
hebsuperobject.biblemap.put("b46_11_4", new hebsuperobject(46,11,4,"כל איש אשר יתפלל או יתנבא וראשו מכסה מבזה הוא את ראשו׃"));
hebsuperobject.biblemap.put("b46_11_5", new hebsuperobject(46,11,5,"וכל אשה אשר תתפלל או תתנבא וראשה פרוע מבזה היא את ראשה יען בזה היא כמו מגלחה׃"));
hebsuperobject.biblemap.put("b46_11_6", new hebsuperobject(46,11,6,"כי האשה אם לא תתכסה גם תתגלח ואם בזיון הוא לאשה להכסם או להתגלח תתכסה׃"));
hebsuperobject.biblemap.put("b46_11_7", new hebsuperobject(46,11,7,"והאיש איננו חיב לכסות את ראשו כי הוא צלם אלהים וכבודו אבל האשה היא כבוד האיש׃"));
hebsuperobject.biblemap.put("b46_11_8", new hebsuperobject(46,11,8,"כי אין האיש מן האשה כי אם האשה מן האיש׃"));
hebsuperobject.biblemap.put("b46_11_9", new hebsuperobject(46,11,9,"גם לא נברא האיש בעבור האשה כי אם האשה בעבור האיש׃"));
hebsuperobject.biblemap.put("b46_11_10", new hebsuperobject(46,11,10,"על כן האשה חיבת להיות לה כפה על ראשה בעבור המלאכים׃"));
hebsuperobject.biblemap.put("b46_11_11", new hebsuperobject(46,11,11,"אבל אין האיש בלא אשה ואין האשה בלא איש באדון׃"));
hebsuperobject.biblemap.put("b46_11_12", new hebsuperobject(46,11,12,"כי כאשר האשה מן האיש כן גם האיש על ידי האשה וכל זאת מאלהים׃"));
hebsuperobject.biblemap.put("b46_11_13", new hebsuperobject(46,11,13,"שפטו נא בנפשכם הנאוה לאשה להתפלל אל האלהים בגלוי ראש׃"));
hebsuperobject.biblemap.put("b46_11_14", new hebsuperobject(46,11,14,"או הלא גם הטבע בעצמו ילמד אתכם כי איש אשר יגדל פרע שער ראשו חרפה היא לו׃"));
hebsuperobject.biblemap.put("b46_11_15", new hebsuperobject(46,11,15,"אבל האשה כי תגדל שערה פאר הוא לה כי נתן לה השער לצניף׃"));
hebsuperobject.biblemap.put("b46_11_16", new hebsuperobject(46,11,16,"ואם יחשב איש לערער עלינו אין לנו מנהג כזה ולא לקהלות האלהים׃"));
hebsuperobject.biblemap.put("b46_11_17", new hebsuperobject(46,11,17,"והנה בצותי את זאת לא אוכל לשבח אתכם על אשר תקהלו יחד לא להועיל כי אם לרעה׃"));
hebsuperobject.biblemap.put("b46_11_18", new hebsuperobject(46,11,18,"כי בראשונה שמעתי שיש מחלקות ביניכם כאשר תועדו בקהל ומקצתו אני מאמין׃"));
hebsuperobject.biblemap.put("b46_11_19", new hebsuperobject(46,11,19,"כי אף צריכות כתות להיות ביניכם למען יודעו הנאמנים בכם׃"));
hebsuperobject.biblemap.put("b46_11_20", new hebsuperobject(46,11,20,"ועתה כאשר תקהלו יחד אין זה לאכל סעודת האדון׃"));
hebsuperobject.biblemap.put("b46_11_21", new hebsuperobject(46,11,21,"כי כל אחד מקדים לקחת סעודתו בעת האכילה וזה ירעב וזה ישתכר׃"));
hebsuperobject.biblemap.put("b46_11_22", new hebsuperobject(46,11,22,"האין לכם בתים לאכל ולשתות בהם או התבוזו את קהל אלהים ותכלימו את אשר אין בידם מאומה מה אמר לכם העל זאת אשבח אתכם אינני משבח׃"));
hebsuperobject.biblemap.put("b46_11_23", new hebsuperobject(46,11,23,"כי כה קבלתי אנכי מן האדון את אשר גם מסרתי לכם כי האדון ישוע בלילה ההוא אשר נמסר בו לקח את הלחם׃"));
hebsuperobject.biblemap.put("b46_11_24", new hebsuperobject(46,11,24,"ויברך ויבצע ויאמר קחו אכלו זה גופי הנבצע בעדכם עשו זאת לזכרוני׃"));
hebsuperobject.biblemap.put("b46_11_25", new hebsuperobject(46,11,25,"וכן גם את הכוס אחר הסעודה ויאמר הכוס הזאת היא הברית החדשה בדמי עשו זאת לזכרוני בכל עת שתשתו׃"));
hebsuperobject.biblemap.put("b46_11_26", new hebsuperobject(46,11,26,"כי בכל עת שתאכלו את הלחם הזה ותשתו את הכוס הזאת הזכר תזכירו את מות אדנינו עד כי יבוא׃"));
hebsuperobject.biblemap.put("b46_11_27", new hebsuperobject(46,11,27,"לכן מי שיאכל מן הלחם הזה או ישתה מכוס האדון שלא כראוי יאשם לגוף אדנינו ולדמו׃"));
hebsuperobject.biblemap.put("b46_11_28", new hebsuperobject(46,11,28,"יבחן האיש את נפשו ואז יאכל מן הלחם וישתה מן הכוס׃"));
hebsuperobject.biblemap.put("b46_11_29", new hebsuperobject(46,11,29,"כי האכל והשתה שלא כראוי אכל ושתה דין לנפשו יען אשר לא הפלה את גוף האדון׃"));
hebsuperobject.biblemap.put("b46_11_30", new hebsuperobject(46,11,30,"בעבור זאת יש בכם חולים וחלשים רבים והרבה ישנו המות׃"));
hebsuperobject.biblemap.put("b46_11_31", new hebsuperobject(46,11,31,"כי אם נבחן את נפשנו לא נהיה נדונים׃"));
hebsuperobject.biblemap.put("b46_11_32", new hebsuperobject(46,11,32,"וכאשר נדון נוסר על יד האדון למען לא נחיב עם העולם׃"));
hebsuperobject.biblemap.put("b46_11_33", new hebsuperobject(46,11,33,"על כן אחי בהקהלכם יחד לאכל תחכו איש אל רעהו׃"));
hebsuperobject.biblemap.put("b46_11_34", new hebsuperobject(46,11,34,"וכי ירעב איש יאכל בביתו פן תקהלו לאשמה ויתר הדברים אתקן בבאי׃"));
hebsuperobject.biblemap.put("b46_12_1", new hebsuperobject(46,12,1,"ובענין הרוחניות אחי לא אכחד מכם דבר׃"));
hebsuperobject.biblemap.put("b46_12_2", new hebsuperobject(46,12,2,"הלא ידעתם כי בהיתכם גוים אחרי אלילים אלמים הובלתם כאשר נמשכתם׃"));
hebsuperobject.biblemap.put("b46_12_3", new hebsuperobject(46,12,3,"לכן אודיע אתכם כי אין איש דבר ברוח אלהים אשר יאמר ישוע חרם הוא ולא יוכל איש לקרא לישוע אדון בלתי אם ברוח הקדש׃"));
hebsuperobject.biblemap.put("b46_12_4", new hebsuperobject(46,12,4,"ושנות הנה המתנות אבל הרוח אחד הוא׃"));
hebsuperobject.biblemap.put("b46_12_5", new hebsuperobject(46,12,5,"ושנים המה השמושים והאדון אחד הוא׃"));
hebsuperobject.biblemap.put("b46_12_6", new hebsuperobject(46,12,6,"ושנות הנה הפעלות והאלהים הוא אחד הפעל את הכל בכל׃"));
hebsuperobject.biblemap.put("b46_12_7", new hebsuperobject(46,12,7,"ולכל איש ואיש נתנה לו התגלות הרוח להועיל׃"));
hebsuperobject.biblemap.put("b46_12_8", new hebsuperobject(46,12,8,"כי האחד נתן לו על ידי הרוח דבור החכמה ולאחד דבור הדעת כפי הרוח ההוא׃"));
hebsuperobject.biblemap.put("b46_12_9", new hebsuperobject(46,12,9,"לאחר האמונה ברוח ההוא ולאחר מתנות הרפאות ברוח ההוא׃"));
hebsuperobject.biblemap.put("b46_12_10", new hebsuperobject(46,12,10,"ולאחר לפעל גבורות ולאחר נבואה ולאחר להבחין בין הרוחות ולאחר מיני לשנות ולאחר באור לשנות׃"));
hebsuperobject.biblemap.put("b46_12_11", new hebsuperobject(46,12,11,"וכל אלה פעל הרוח האחד ההוא המחלק לאיש איש כרצונו׃"));
hebsuperobject.biblemap.put("b46_12_12", new hebsuperobject(46,12,12,"כי כאשר הגוף הוא אחד ויש בו אברים הרבה וכל אברי הגוף ההוא אף כי רבים הם כלם גוף אחד כן גם המשיח׃"));
hebsuperobject.biblemap.put("b46_12_13", new hebsuperobject(46,12,13,"כי ברוח אחד נטבלנו כלנו לגוף אחד אם יהודים אם יונים אם עבדים אם בני חורין וכלנו לרוח אחד השקינו׃"));
hebsuperobject.biblemap.put("b46_12_14", new hebsuperobject(46,12,14,"כי גם הגוף לא אבר אחד הוא כי אם רבים׃"));
hebsuperobject.biblemap.put("b46_12_15", new hebsuperobject(46,12,15,"אם תאמר הרגל אינני יד על כן אינני מן הגוף הבעבור זאת איננה מן הגוף׃"));
hebsuperobject.biblemap.put("b46_12_16", new hebsuperobject(46,12,16,"ואם תאמרו האזן אינני עין על כן אינני מן הגוף הבעבור זאת איננה מן הגוף׃"));
hebsuperobject.biblemap.put("b46_12_17", new hebsuperobject(46,12,17,"אם הגוף כלו יהיה עין איה השמע ואם כלו יהיה שמע איה הריח׃"));
hebsuperobject.biblemap.put("b46_12_18", new hebsuperobject(46,12,18,"ועתה האלהים שת את האברים כל אחד ואחד מהם בגוף כמי רצונו׃"));
hebsuperobject.biblemap.put("b46_12_19", new hebsuperobject(46,12,19,"ואלו היו כלם אבר אחד איה הגוף׃"));
hebsuperobject.biblemap.put("b46_12_20", new hebsuperobject(46,12,20,"הנה רבים הם האברים והגוף אחד׃"));
hebsuperobject.biblemap.put("b46_12_21", new hebsuperobject(46,12,21,"העין לא תוכל דבר אל היד לאמר לא אצטרך לך וגם הראש לא יוכל דבר אל הרגלים לאמר לא אצטרך לכן׃"));
hebsuperobject.biblemap.put("b46_12_22", new hebsuperobject(46,12,22,"כי להפך אברי הגוף הנראים רפים הם לנו לצרך ביותר׃"));
hebsuperobject.biblemap.put("b46_12_23", new hebsuperobject(46,12,23,"והנראים לנו נקלים בגוף אתם נלביש ביתר כבוד ואשר לבשת לנו המה כאלו ההגונים מכלם׃"));
hebsuperobject.biblemap.put("b46_12_24", new hebsuperobject(46,12,24,"כי ההגונים לנו אינם צריכים לזאת אבל האלהים מזג ככה את הגוף שנתן כבוד יותר לגרוע׃"));
hebsuperobject.biblemap.put("b46_12_25", new hebsuperobject(46,12,25,"למען לא תהיה מחלקת בגוף כי אם ידאגו כל האברים יחד זה לזה׃"));
hebsuperobject.biblemap.put("b46_12_26", new hebsuperobject(46,12,26,"ואם יכאב אבר אחד יכאבו אתו כל האברים ואם יכבד אבד אחד ישמחו אתו כל האברים׃"));
hebsuperobject.biblemap.put("b46_12_27", new hebsuperobject(46,12,27,"אכן גוף המשיח אתם ואבריו כל אחד לפי חלקו׃"));
hebsuperobject.biblemap.put("b46_12_28", new hebsuperobject(46,12,28,"ומהם שם האלהים בקהל ראשונה לשליחים ושנית לנביאים ושלישית למלמדים ויתן גבורות אף מתנות הרפאות ועזרים ומנהיגים ומיני לשנות׃"));
hebsuperobject.biblemap.put("b46_12_29", new hebsuperobject(46,12,29,"הכלם שליחים אם כלם נביאים או כלם מלמדים הכלם עשי גבורות׃"));
hebsuperobject.biblemap.put("b46_12_30", new hebsuperobject(46,12,30,"הלכלם מתנות רפאות הכלם מדברים בלשנות הכלם מפרשי לשנות׃"));
hebsuperobject.biblemap.put("b46_12_31", new hebsuperobject(46,12,31,"ואתם התאוו המתנות המועילות ביותר ובכל זאת אראה אתכם דרך נעלה על כלנה׃"));
hebsuperobject.biblemap.put("b46_13_1", new hebsuperobject(46,13,1,"אם בלשנות אנשים ומלאכים אדבר ואין בי האהבה הייתי כנחשת המה או כצלצל תרועה׃"));
hebsuperobject.biblemap.put("b46_13_2", new hebsuperobject(46,13,2,"וכי תהיה לי נבואה ואדע כל הסודות וכל הדעת וכי תהיה לי כל האמונה עד כי אעתיק הרים ואין בי האהבה הייתי כאין׃"));
hebsuperobject.biblemap.put("b46_13_3", new hebsuperobject(46,13,3,"ואם אחלק את כל הוני ואם אתן את גופי לשרפה ואין בי האהבה כל זאת לא תועילני׃"));
hebsuperobject.biblemap.put("b46_13_4", new hebsuperobject(46,13,4,"האהבה מארכת אף ועשה חסד האהבה לא תקנא האהבה לא תתפאר ולא תתרומם׃"));
hebsuperobject.biblemap.put("b46_13_5", new hebsuperobject(46,13,5,"לא תעשה דבר תפלה ולא תבקש את אשר לה ולא תתמרמר ולא תחשב הרעה׃"));
hebsuperobject.biblemap.put("b46_13_6", new hebsuperobject(46,13,6,"לא תשמח בעולה כי שמחתה עם האמת׃"));
hebsuperobject.biblemap.put("b46_13_7", new hebsuperobject(46,13,7,"את כל תשא את כל תאמין את כל תקוה ואת כל תסבל׃"));
hebsuperobject.biblemap.put("b46_13_8", new hebsuperobject(46,13,8,"האהבה לא תבל לעולם אך הנבואות הנה תבטלנה והלשנות תכלינה והדעת תבטל׃"));
hebsuperobject.biblemap.put("b46_13_9", new hebsuperobject(46,13,9,"כי קצת הוא שידענו וקצת הוא שנבאנו׃"));
hebsuperobject.biblemap.put("b46_13_10", new hebsuperobject(46,13,10,"וכבוא התמים אז עבור תעבר הקצת׃"));
hebsuperobject.biblemap.put("b46_13_11", new hebsuperobject(46,13,11,"כאשר הייתי עולל כעולל דברתי כעולל הגיתי כעולל חשבתי וכאשר הייתי לאיש הסירתי דברי העולל׃"));
hebsuperobject.biblemap.put("b46_13_12", new hebsuperobject(46,13,12,"כי כעת מביטים אנחנו במראה ובחידות ואז פנים אל פנים כעת יודע אני קצתו ואז כאשר נודעתי אדע אף אני׃"));
hebsuperobject.biblemap.put("b46_13_13", new hebsuperobject(46,13,13,"ועתה שלש אלה תעמדנה האמונה והתקוה והאהבה והגדולה בהן היא האהבה׃"));
hebsuperobject.biblemap.put("b46_14_1", new hebsuperobject(46,14,1,"רדפו אחרי האהבה והתאוו מתנות הרוח וביותר אשר תתנבאו׃"));
hebsuperobject.biblemap.put("b46_14_2", new hebsuperobject(46,14,2,"כי המדבר בלשון איננו מדבר לאדם כי אם לאלהים כי אין איש אשר ישמעהו רק ברוח הוא מדבר סודות׃"));
hebsuperobject.biblemap.put("b46_14_3", new hebsuperobject(46,14,3,"והמתנבא הוא מדבר לבני אדם לבנותם וליסרם ולנחמם׃"));
hebsuperobject.biblemap.put("b46_14_4", new hebsuperobject(46,14,4,"המדבר בלשון בונה את נפשו והמתנבא בונה את העדה׃"));
hebsuperobject.biblemap.put("b46_14_5", new hebsuperobject(46,14,5,"וחפצתי כי תדברו כלכם בלשנות וביותר כי תתנבאו כי גדול המתנבא מן המדבר בלשנות בלתי אם יפרש למען תבנה העדה׃"));
hebsuperobject.biblemap.put("b46_14_6", new hebsuperobject(46,14,6,"ועתה אחי כי אבוא אליכם ואדבר בלשנות מה אועיל לכם אם לא אדבר אליכם בחזון או בדעת או בנבואה או בהוראה׃"));
hebsuperobject.biblemap.put("b46_14_7", new hebsuperobject(46,14,7,"הלא גם הכלים הדוממים הנתנים קול הן חליל הן כנור אם לא ישמיעו קלות אשר תוכל האזן להבחין איכה יודע מה יזמר ומה ינגן׃"));
hebsuperobject.biblemap.put("b46_14_8", new hebsuperobject(46,14,8,"גם השופר אם יתן את קולו בלתי ברור מי יחלץ למלחמה׃"));
hebsuperobject.biblemap.put("b46_14_9", new hebsuperobject(46,14,9,"כן גם אתם אם לא תוציאו בלשונכם דבור מפרש איכה יודע האמור הלא תהיו כמדברים לרוח׃"));
hebsuperobject.biblemap.put("b46_14_10", new hebsuperobject(46,14,10,"הן כמה מיני לשנות יש בעולם ואין אחת מהן בלי קול׃"));
hebsuperobject.biblemap.put("b46_14_11", new hebsuperobject(46,14,11,"לכן אם אינני ידע פשר הקול אהיה נכרי בעיני המדבר והמדבר יהיה נכרי בעיני׃"));
hebsuperobject.biblemap.put("b46_14_12", new hebsuperobject(46,14,12,"כן גם אתם בהיותכם מתאוים לכחות רוחניות בקשו להעדיף במה שיבנה את העדה׃"));
hebsuperobject.biblemap.put("b46_14_13", new hebsuperobject(46,14,13,"על כן יתפלל המדבר בלשון וגם יפרשנה׃"));
hebsuperobject.biblemap.put("b46_14_14", new hebsuperobject(46,14,14,"כי אם אתפלל בלשון רוחי מתפלל ושכלי איננו עשה פרי׃"));
hebsuperobject.biblemap.put("b46_14_15", new hebsuperobject(46,14,15,"ועתה מה לעשות אתפללה ברוחי ואתפללה גם בשכלי אזמרה ברוחי ואזמרה גם בשכלי׃"));
hebsuperobject.biblemap.put("b46_14_16", new hebsuperobject(46,14,16,"כי אם תברך ברוח איך יענה העמד נמצב ההדיוט אמן על הודיתך באשר לא ידע מה אתה אמר׃"));
hebsuperobject.biblemap.put("b46_14_17", new hebsuperobject(46,14,17,"הן אתה תיטיב להודות אבל רעך לא יבנה׃"));
hebsuperobject.biblemap.put("b46_14_18", new hebsuperobject(46,14,18,"אודה לאלהי כי יותר מכלכם אני מדבר בלשנות׃"));
hebsuperobject.biblemap.put("b46_14_19", new hebsuperobject(46,14,19,"אכן בקהל אבחר לדבר חמש מלין בשכלי למען הורת גם את האחרים מלדבר רבבות מלין בלשון׃"));
hebsuperobject.biblemap.put("b46_14_20", new hebsuperobject(46,14,20,"אחי אל תהיו ילדים בבינה רק לרע היו עללים ובבינה היו שלמים׃"));
hebsuperobject.biblemap.put("b46_14_21", new hebsuperobject(46,14,21,"הן כתוב בתורה כי בלעגי שפה ובלשון אחרת אדבר אל העם הזה וגם בזאת לא אבו שמע לי אמר יהוה׃"));
hebsuperobject.biblemap.put("b46_14_22", new hebsuperobject(46,14,22,"לכן הלשנות לא למאמינים הנה לאות כי אם לאשר אינם מאמינים אבל הנבואה איננה לאשר אינם מאמינים כי אם למאמינים׃"));
hebsuperobject.biblemap.put("b46_14_23", new hebsuperobject(46,14,23,"והנה אם תקהל כל העדה יחד וכלם ידברו בלשנות ויבואו הדיוטים או אשר אינם מאמינים הלא יאמרו כי משגעים אתם׃"));
hebsuperobject.biblemap.put("b46_14_24", new hebsuperobject(46,14,24,"אבל אם יתנבאו כלם ובא איש לא מאמין או הדיוט אז יוכח על ידי כלם וידון על ידי כלם׃"));
hebsuperobject.biblemap.put("b46_14_25", new hebsuperobject(46,14,25,"ובכן יגלו תעלמות לבבו ויפל על פניו וישתחוה לאלהים ויודה בקול כי באמת האלהים בקרבכם׃"));
hebsuperobject.biblemap.put("b46_14_26", new hebsuperobject(46,14,26,"ועתה מה לעשות אחי בהקהלכם יחד כל אחד ואחד מכם יש לו מזמור יש לו הוראה יש לו לשון יש לו חזון יש לו באור אך יעשה הכל להבנות׃"));
hebsuperobject.biblemap.put("b46_14_27", new hebsuperobject(46,14,27,"כי ידבר איש בלשון ידברו נא שנים שנים או על היותר שלשה וזה אחר זה ואחד יפרש׃"));
hebsuperobject.biblemap.put("b46_14_28", new hebsuperobject(46,14,28,"ואם אין מפרש אז ידם בקהל וידבר לנפשו ולאלהים׃"));
hebsuperobject.biblemap.put("b46_14_29", new hebsuperobject(46,14,29,"והנביאים הם ידברו שנים או שלשה והאחרים יבחנו׃"));
hebsuperobject.biblemap.put("b46_14_30", new hebsuperobject(46,14,30,"וכי נגלה חזון לאחר הישב שם אז ידם הראשון׃"));
hebsuperobject.biblemap.put("b46_14_31", new hebsuperobject(46,14,31,"כי תוכלו להתנבא כלכם זה אחר זה למען ילמדו כלם וכלם יזהרו׃"));
hebsuperobject.biblemap.put("b46_14_32", new hebsuperobject(46,14,32,"ורוחות הנביאים תחת ידי הנביאים המה׃"));
hebsuperobject.biblemap.put("b46_14_33", new hebsuperobject(46,14,33,"כי לא אלהי מבוכה האלהים כי אם אלהי השלום כאשר בכל קהלות הקדשים׃"));
hebsuperobject.biblemap.put("b46_14_34", new hebsuperobject(46,14,34,"נשיכם בכנסיות תשתקנה כי לא נתנה להן רשות לדבר כי אם להכנע כאשר גם אמרה התורה׃"));
hebsuperobject.biblemap.put("b46_14_35", new hebsuperobject(46,14,35,"ואם חפצן ללמד דבר תשאלנה את בעליהן בבית כי חרפה היא לנשים לדבר בקהל׃"));
hebsuperobject.biblemap.put("b46_14_36", new hebsuperobject(46,14,36,"או המכם יצא דבר אלהים אם אליכם לבדכם הגיע׃"));
hebsuperobject.biblemap.put("b46_14_37", new hebsuperobject(46,14,37,"כי יתברך איש בלבבו להיות נביא או איש הרוח בין יבין את אשר אני כתב לכם כי מצות האדון הנה׃"));
hebsuperobject.biblemap.put("b46_14_38", new hebsuperobject(46,14,38,"ומי אשר לא ידע אל ידע׃"));
hebsuperobject.biblemap.put("b46_14_39", new hebsuperobject(46,14,39,"לכן אחי השתדלו להתנבא ואל תכלאו מלדבר בלשנות׃"));
hebsuperobject.biblemap.put("b46_14_40", new hebsuperobject(46,14,40,"הכל יעשה כהגן וכשורה׃"));
hebsuperobject.biblemap.put("b46_15_1", new hebsuperobject(46,15,1,"ואני אחי אודיעכם את הבשורה אשר בשרתי אתכם אשר גם קבלתם אתה וגם עמדתם בה׃"));
hebsuperobject.biblemap.put("b46_15_2", new hebsuperobject(46,15,2,"אשר גם תושעו בה אם תחזיקו בדבר אשר בשרתי אתכם אך אם לא לשוא האמנתם׃"));
hebsuperobject.biblemap.put("b46_15_3", new hebsuperobject(46,15,3,"כי מסרתי לכם בראשונה את אשר גם קבלתי כי המשיח מת בעד חטאתינו כפי הכתובים׃"));
hebsuperobject.biblemap.put("b46_15_4", new hebsuperobject(46,15,4,"וכי נקבר וכי הוקם ביום השלישי כפי הכתובים׃"));
hebsuperobject.biblemap.put("b46_15_5", new hebsuperobject(46,15,5,"וכי נראה אל כיפא ואחריו אל שנים העשר׃"));
hebsuperobject.biblemap.put("b46_15_6", new hebsuperobject(46,15,6,"ואחרי כן נראה ליותר מחמש מאות אחים כאחד אשר רבם עודם בחיים ומקצתם ישנו׃"));
hebsuperobject.biblemap.put("b46_15_7", new hebsuperobject(46,15,7,"ואחרי כן נראה אל יעקב ואחריו אל כל השליחים׃"));
hebsuperobject.biblemap.put("b46_15_8", new hebsuperobject(46,15,8,"ואחרי כלם נראה גם אלי כמו אל הנפל׃"));
hebsuperobject.biblemap.put("b46_15_9", new hebsuperobject(46,15,9,"כי אני הצעיר בשליחים ואינני כדי להקרא שליח באשר רדפתי את קהל האלהים׃"));
hebsuperobject.biblemap.put("b46_15_10", new hebsuperobject(46,15,10,"אבל בחסד אלהים הייתי מה שהייתי וחסדו עלי לא היה לריק כי יותר מכלם עבדתי ולא אני כי אם חסד אלהים אשר עמדי׃"));
hebsuperobject.biblemap.put("b46_15_11", new hebsuperobject(46,15,11,"והנה גם אני גם המה ככה משמיעים וככה האמנתם׃"));
hebsuperobject.biblemap.put("b46_15_12", new hebsuperobject(46,15,12,"ואם הגד הגד כי הוקם המשיח מן המתים איך יאמרו אנשים מכם כי אין תחיה למתים׃"));
hebsuperobject.biblemap.put("b46_15_13", new hebsuperobject(46,15,13,"אם אין תחיה למתים גם המשיח לא הוקם׃"));
hebsuperobject.biblemap.put("b46_15_14", new hebsuperobject(46,15,14,"ואם המשיח לא הוקם כי עתה ריק שמועתנו וגם ריק אמונתכם׃"));
hebsuperobject.biblemap.put("b46_15_15", new hebsuperobject(46,15,15,"וגם נמצא עדי שקר לאלהים יען אשר העידנו את האלהים כי הקים את המשיח אשר לא הקימו אם אמת הוא שהמתים לא יקומו׃"));
hebsuperobject.biblemap.put("b46_15_16", new hebsuperobject(46,15,16,"כי אם המתים לא יקומו גם המשיח לא קם׃"));
hebsuperobject.biblemap.put("b46_15_17", new hebsuperobject(46,15,17,"ואם המשיח לא קם הבל אמונתכם ועודכם בחטאתיכם׃"));
hebsuperobject.biblemap.put("b46_15_18", new hebsuperobject(46,15,18,"אזי גם אשר ישנו במשיח אבד אבדו׃"));
hebsuperobject.biblemap.put("b46_15_19", new hebsuperobject(46,15,19,"ואם בחיים האלה לבד בטחים אנחנו במשיח אמללים אנחנו מכל אדם׃"));
hebsuperobject.biblemap.put("b46_15_20", new hebsuperobject(46,15,20,"ועתה המשיח הוקם מן המתים ויהי לראשית הישנים׃"));
hebsuperobject.biblemap.put("b46_15_21", new hebsuperobject(46,15,21,"כי אחרי אשר בא המות על ידי אדם אחד גם תחית המתים באה על ידי אדם אחד׃"));
hebsuperobject.biblemap.put("b46_15_22", new hebsuperobject(46,15,22,"כי כאשר באדם מתים כלם כן גם יחיו כלם במשיח׃"));
hebsuperobject.biblemap.put("b46_15_23", new hebsuperobject(46,15,23,"וכל אחד ואחד בסדרו ראשית כלם המשיח ואחרי כן אשר הם למשיח בבואו׃"));
hebsuperobject.biblemap.put("b46_15_24", new hebsuperobject(46,15,24,"ואחרי כן הקץ כשימסר את המלכות אל האלהים האב אחרי בטלו כל משרה וכל שלטן וגבורה׃"));
hebsuperobject.biblemap.put("b46_15_25", new hebsuperobject(46,15,25,"כי הוא מלך ימלך עד כי ישית את כל איביו תחת רגליו׃"));
hebsuperobject.biblemap.put("b46_15_26", new hebsuperobject(46,15,26,"ואחרון האיבים אשר יבטל הוא המות׃"));
hebsuperobject.biblemap.put("b46_15_27", new hebsuperobject(46,15,27,"כי כל שת תחת רגליו ובאמרו כל הושת תחתיו ברור הוא שהשת כל תחתיו איננו בכלל׃"));
hebsuperobject.biblemap.put("b46_15_28", new hebsuperobject(46,15,28,"וכאשר יושת הכל תחתיו אז הבן גם הוא יושת תחת השת כל תחתיו למען יהיה האלהים הכל בכל׃"));
hebsuperobject.biblemap.put("b46_15_29", new hebsuperobject(46,15,29,"כי מה יעשו הנטבלים בעד המתים אם אמת הוא שהמתים קום לא יקומו למה זה יטבלו בעד המתים׃"));
hebsuperobject.biblemap.put("b46_15_30", new hebsuperobject(46,15,30,"ולמה זה אנחנו בסכנה בכל שעה׃"));
hebsuperobject.biblemap.put("b46_15_31", new hebsuperobject(46,15,31,"בתהלתנו אשר יש לי במשיח ישוע אדנינו מעיד אני עלי כי מת אנכי בכל יום ויום׃"));
hebsuperobject.biblemap.put("b46_15_32", new hebsuperobject(46,15,32,"אם לפי ררכו של אדם נלחמתי עם החיות הרעות באפסוס מה תועלת יש לי אם המתים לא יקומו נאכלה ונשתה כי מחר נמות׃"));
hebsuperobject.biblemap.put("b46_15_33", new hebsuperobject(46,15,33,"אל נא תתעו חברת אנשים רעים משחתת מדות טבות׃"));
hebsuperobject.biblemap.put("b46_15_34", new hebsuperobject(46,15,34,"הקיצו במישרים משכרון ואל תחטאו כי יש אנשים אשר אין בהם דעת אלהים לבשתכם אני אמר זאת׃"));
hebsuperobject.biblemap.put("b46_15_35", new hebsuperobject(46,15,35,"ואם יאמר איש איך יקומו המתים ובאי זה גוף יבואו׃"));
hebsuperobject.biblemap.put("b46_15_36", new hebsuperobject(46,15,36,"אתה הסכל הן מה שתזרע לא יחיה בלתי אם ימות׃"));
hebsuperobject.biblemap.put("b46_15_37", new hebsuperobject(46,15,37,"ומה שתזרע אינך זרע את הגוף אשר יהיה כי אם כגרגר ערם של חטה או של אחד הזרעים׃"));
hebsuperobject.biblemap.put("b46_15_38", new hebsuperobject(46,15,38,"והאלהים יתן לו גוף כפי רצונו ולכל זרע וזרע את גופו למינהו׃"));
hebsuperobject.biblemap.put("b46_15_39", new hebsuperobject(46,15,39,"לא כל הבשר באשר אחד הוא כי מין אחר הוא בשר האדם ומין אחר בשר הבהמה ומין אחר בשר הדגה ומין אחר בשר העוף׃"));
hebsuperobject.biblemap.put("b46_15_40", new hebsuperobject(46,15,40,"ויש גופות שבשמים וגופות שבארץ אבל אחר הוא כבוד הגופות שבשמים וגופות שבארץ אבל אחר הוא כבוד הגופות שבשמים ואחר הוא כבוד הגופות שבארץ׃"));
hebsuperobject.biblemap.put("b46_15_41", new hebsuperobject(46,15,41,"אחר הוא כבוד השמש ואחר הוא כבוד הירח ואחר הוא כבוד הכוכבים כי כוכב מכוכב נבדל בכבודו׃"));
hebsuperobject.biblemap.put("b46_15_42", new hebsuperobject(46,15,42,"וכן גם בתחיה המתים הן יזרע בכליון ויקום בלא כליון׃"));
hebsuperobject.biblemap.put("b46_15_43", new hebsuperobject(46,15,43,"יזרע בבזיון ויקום בכבוד יזרע בחלשה ויקום בגבורה׃"));
hebsuperobject.biblemap.put("b46_15_44", new hebsuperobject(46,15,44,"יזרע גוף נפשי ויקום גוף רוחני יש גוף נפשי ויש גוף רוחני׃"));
hebsuperobject.biblemap.put("b46_15_45", new hebsuperobject(46,15,45,"כן גם כתוב ויהי האדם הוא אדם הראשון לנפש חיה אדם האחרון לרוח מחיה׃"));
hebsuperobject.biblemap.put("b46_15_46", new hebsuperobject(46,15,46,"אבל לא של הרוח היא הראשונה אלא של הנפש ואחרי כן של הרוח׃"));
hebsuperobject.biblemap.put("b46_15_47", new hebsuperobject(46,15,47,"האדם הראשון מן האדמה הוא של עפר והאדם השני הוא האדון מן השמים׃"));
hebsuperobject.biblemap.put("b46_15_48", new hebsuperobject(46,15,48,"וכמו אשר הוא מעפר ככה גם אשר הם מעפר וכמו אשר הוא מן השמים ככה גם אשר הם מן השמים׃"));
hebsuperobject.biblemap.put("b46_15_49", new hebsuperobject(46,15,49,"וכאשר לבשנו דמות האדם אשר מעפר כן נלבש גם דמות האדם אשר מן השמים׃"));
hebsuperobject.biblemap.put("b46_15_50", new hebsuperobject(46,15,50,"וזאת אני אמר אחי כי בשר ודם לא יוכל לרשת את מלכות האלהים ואשר יכלה לא יירש את אשר לא יכלה׃"));
hebsuperobject.biblemap.put("b46_15_51", new hebsuperobject(46,15,51,"הנה סוד אגידה לכם הן לא כלנו נישן המות אבל כלנו נתחלף׃"));
hebsuperobject.biblemap.put("b46_15_52", new hebsuperobject(46,15,52,"ברגע אחד כהרף עין כתקע השופר האחרון כי יתקע בשופר והמתים יחיו בלי כליון ואנחנו נתחלף׃"));
hebsuperobject.biblemap.put("b46_15_53", new hebsuperobject(46,15,53,"כי מה שעתה לכליון לבוש ילבש אל כליון ואמר ימות יבוש ילבש אל מות׃"));
hebsuperobject.biblemap.put("b46_15_54", new hebsuperobject(46,15,54,"וכשילבש מה שעתה לכליון אל כליון ומה שעתה למות ילבש אל מות אז יהיה דבר הכתוב בלע המות לנצח׃"));
hebsuperobject.biblemap.put("b46_15_55", new hebsuperobject(46,15,55,"איה עקצף המות איה שאול בצחונך׃"));
hebsuperobject.biblemap.put("b46_15_56", new hebsuperobject(46,15,56,"עקץ המות הוא החטא וכח החטא היא התורה׃"));
hebsuperobject.biblemap.put("b46_15_57", new hebsuperobject(46,15,57,"אבל תודות לאלהים אשר נתן לנו הנצחון על ידי אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b46_15_58", new hebsuperobject(46,15,58,"על כן אחי חביבי התכוננו בל תמוטו והעדיפו בכל עת במעשה אדנינו מדעתכם כי לא לריק עמלכם באדנינו׃"));
hebsuperobject.biblemap.put("b46_16_1", new hebsuperobject(46,16,1,"ועל דבר קבוץ התרומות לעזרת הקדושים כאשר תקנתי לקהלות אשר בגלטיא כן תעשו גם אתם׃"));
hebsuperobject.biblemap.put("b46_16_2", new hebsuperobject(46,16,2,"בכל אחד בשבת יניח אצלו איש איש מכם ויאצר את אשר עלה בידו למען אשר בבאי לא יקבץ עוד׃"));
hebsuperobject.biblemap.put("b46_16_3", new hebsuperobject(46,16,3,"ואני בבאי את אשר תמצאו נאמנים עם אגרות אשלח אתם להביא את נדבתכם לירושלים׃"));
hebsuperobject.biblemap.put("b46_16_4", new hebsuperobject(46,16,4,"ואם שוה הטרח שגם אנכי אלך שמה אתי ילכו׃"));
hebsuperobject.biblemap.put("b46_16_5", new hebsuperobject(46,16,5,"ואני אבא אליכם אחרי עברי את מקדוניא כי את מקדוניא אעברה׃"));
hebsuperobject.biblemap.put("b46_16_6", new hebsuperobject(46,16,6,"ואולי אשב עמכם ימים אחדים או כל ימי הסתו למען תלוני אל אשר אלך שמה׃"));
hebsuperobject.biblemap.put("b46_16_7", new hebsuperobject(46,16,7,"כי כעת אין רצוני לראתכם אך בעברי כי אקוה לשבת אצלכם זמן מה אם ירצה יהוה׃"));
hebsuperobject.biblemap.put("b46_16_8", new hebsuperobject(46,16,8,"אבל אשב באפסוס עד חג השבועות׃"));
hebsuperobject.biblemap.put("b46_16_9", new hebsuperobject(46,16,9,"כי נפתח לי פתח גדול ורב פעלים ורבים המתקוממים׃"));
hebsuperobject.biblemap.put("b46_16_10", new hebsuperobject(46,16,10,"וכי יבוא אליכם טימותיוס ראו נא שיהיה עמכם בלי פחד כי מלאכת יהוה הוא עשה כמו גם אני׃"));
hebsuperobject.biblemap.put("b46_16_11", new hebsuperobject(46,16,11,"על כן איש אל יבז אתו אך שלחהו בשלום למען יבא אלי כי אחכה לו עם האחים׃"));
hebsuperobject.biblemap.put("b46_16_12", new hebsuperobject(46,16,12,"ואפולוס האח הנה פצרתי בו לבוא אליכם עם האחים אך לא היה ברצונו לבוא עתה אמנם בוא יבוא במצאו עת נכונה׃"));
hebsuperobject.biblemap.put("b46_16_13", new hebsuperobject(46,16,13,"שקדו ועמדו באמונה התאששו והתחזקו׃"));
hebsuperobject.biblemap.put("b46_16_14", new hebsuperobject(46,16,14,"וכל דבריכם יעשו באהבה׃"));
hebsuperobject.biblemap.put("b46_16_15", new hebsuperobject(46,16,15,"ואבקשה מכם אחי הלא ידעתם את בית אסטפנוס שהוא ראשית אכיא ויתנו את נפשם לשרות הקדשים׃"));
hebsuperobject.biblemap.put("b46_16_16", new hebsuperobject(46,16,16,"לכן הכנעו גם אתם מפני אנשים כאלה ומפני כל אשר יעבד עמהם ויעמלו׃"));
hebsuperobject.biblemap.put("b46_16_17", new hebsuperobject(46,16,17,"והנני שמח בביאת אסטפנוס ופרטונטוס ואכיקוס כי המה מלאו את אשר חסרתי אתכם׃"));
hebsuperobject.biblemap.put("b46_16_18", new hebsuperobject(46,16,18,"ויניחו את רוחי ואת רוחכם על כן הכירו אנשים כאלה׃"));
hebsuperobject.biblemap.put("b46_16_19", new hebsuperobject(46,16,19,"הקהלות אשר באסיא שאלות לשלומכם עקילס ופריסקלא וגם הקהלה אשר בביתם מרבים לשאל לשלומכם באדנינו׃"));
hebsuperobject.biblemap.put("b46_16_20", new hebsuperobject(46,16,20,"האחים כלם שאלים לשלומכם שאלו לשלום איש את רעהו בנשקה הקדושה׃"));
hebsuperobject.biblemap.put("b46_16_21", new hebsuperobject(46,16,21,"שאלת שלומכם בידי אני פולוס׃"));
hebsuperobject.biblemap.put("b46_16_22", new hebsuperobject(46,16,22,"מי שלא יאהב את האדון ישוע המשיח יחרם מרן אתא׃"));
hebsuperobject.biblemap.put("b46_16_23", new hebsuperobject(46,16,23,"חסד ישוע המשיח אדנינו יהי עמכם׃"));
hebsuperobject.biblemap.put("b46_16_24", new hebsuperobject(46,16,24,"ואהבתי את כלכם במשיח ישוע אמן׃"));

}

}