package heb.bible;

public class hebbible30 {

public hebbible30() {

putmapbible30();

}

private void putmapbible30() {

hebsuperobject.biblemap.put("b30_1_1", new hebsuperobject(30,1,1,"דברי עמוס אשר היה בנקדים מתקוע אשר חזה על ישראל בימי עזיה מלך יהודה ובימי ירבעם בן יואש מלך ישראל שנתים לפני הרעש׃"));
hebsuperobject.biblemap.put("b30_1_2", new hebsuperobject(30,1,2,"ויאמר יהוה מציון ישאג ומירושלם יתן קולו ואבלו נאות הרעים ויבש ראש הכרמל׃"));
hebsuperobject.biblemap.put("b30_1_3", new hebsuperobject(30,1,3,"כה אמר יהוה על שלשה פשעי דמשק ועל ארבעה לא אשיבנו על דושם בחרצות הברזל את הגלעד׃"));
hebsuperobject.biblemap.put("b30_1_4", new hebsuperobject(30,1,4,"ושלחתי אש בבית חזאל ואכלה ארמנות בן הדד׃"));
hebsuperobject.biblemap.put("b30_1_5", new hebsuperobject(30,1,5,"ושברתי בריח דמשק והכרתי יושב מבקעת און ותומך שבט מבית עדן וגלו עם ארם קירה אמר יהוה׃"));
hebsuperobject.biblemap.put("b30_1_6", new hebsuperobject(30,1,6,"כה אמר יהוה על שלשה פשעי עזה ועל ארבעה לא אשיבנו על הגלותם גלות שלמה להסגיר לאדום׃"));
hebsuperobject.biblemap.put("b30_1_7", new hebsuperobject(30,1,7,"ושלחתי אש בחומת עזה ואכלה ארמנתיה׃"));
hebsuperobject.biblemap.put("b30_1_8", new hebsuperobject(30,1,8,"והכרתי יושב מאשדוד ותומך שבט מאשקלון והשיבותי ידי על עקרון ואבדו שארית פלשתים אמר אדני יהוה׃"));
hebsuperobject.biblemap.put("b30_1_9", new hebsuperobject(30,1,9,"כה אמר יהוה על שלשה פשעי צר ועל ארבעה לא אשיבנו על הסגירם גלות שלמה לאדום ולא זכרו ברית אחים׃"));
hebsuperobject.biblemap.put("b30_1_10", new hebsuperobject(30,1,10,"ושלחתי אש בחומת צר ואכלה ארמנותיה׃"));
hebsuperobject.biblemap.put("b30_1_11", new hebsuperobject(30,1,11,"כה אמר יהוה על שלשה פשעי אדום ועל ארבעה לא אשיבנו על רדפו בחרב אחיו ושחת רחמיו ויטרף לעד אפו ועברתו שמרה נצח׃"));
hebsuperobject.biblemap.put("b30_1_12", new hebsuperobject(30,1,12,"ושלחתי אש בתימן ואכלה ארמנות בצרה׃"));
hebsuperobject.biblemap.put("b30_1_13", new hebsuperobject(30,1,13,"כה אמר יהוה על שלשה פשעי בני עמון ועל ארבעה לא אשיבנו על בקעם הרות הגלעד למען הרחיב את גבולם׃"));
hebsuperobject.biblemap.put("b30_1_14", new hebsuperobject(30,1,14,"והצתי אש בחומת רבה ואכלה ארמנותיה בתרועה ביום מלחמה בסער ביום סופה׃"));
hebsuperobject.biblemap.put("b30_1_15", new hebsuperobject(30,1,15,"והלך מלכם בגולה הוא ושריו יחדו אמר יהוה׃"));
hebsuperobject.biblemap.put("b30_2_1", new hebsuperobject(30,2,1,"כה אמר יהוה על שלשה פשעי מואב ועל ארבעה לא אשיבנו על שרפו עצמות מלך אדום לשיד׃"));
hebsuperobject.biblemap.put("b30_2_2", new hebsuperobject(30,2,2,"ושלחתי אש במואב ואכלה ארמנות הקריות ומת בשאון מואב בתרועה בקול שופר׃"));
hebsuperobject.biblemap.put("b30_2_3", new hebsuperobject(30,2,3,"והכרתי שופט מקרבה וכל שריה אהרוג עמו אמר יהוה׃"));
hebsuperobject.biblemap.put("b30_2_4", new hebsuperobject(30,2,4,"כה אמר יהוה על שלשה פשעי יהודה ועל ארבעה לא אשיבנו על מאסם את תורת יהוה וחקיו לא שמרו ויתעום כזביהם אשר הלכו אבותם אחריהם׃"));
hebsuperobject.biblemap.put("b30_2_5", new hebsuperobject(30,2,5,"ושלחתי אש ביהודה ואכלה ארמנות ירושלם׃"));
hebsuperobject.biblemap.put("b30_2_6", new hebsuperobject(30,2,6,"כה אמר יהוה על שלשה פשעי ישראל ועל ארבעה לא אשיבנו על מכרם בכסף צדיק ואביון בעבור נעלים׃"));
hebsuperobject.biblemap.put("b30_2_7", new hebsuperobject(30,2,7,"השאפים על עפר ארץ בראש דלים ודרך ענוים יטו ואיש ואביו ילכו אל הנערה למען חלל את שם קדשי׃"));
hebsuperobject.biblemap.put("b30_2_8", new hebsuperobject(30,2,8,"ועל בגדים חבלים יטו אצל כל מזבח ויין ענושים ישתו בית אלהיהם׃"));
hebsuperobject.biblemap.put("b30_2_9", new hebsuperobject(30,2,9,"ואנכי השמדתי את האמרי מפניהם אשר כגבה ארזים גבהו וחסן הוא כאלונים ואשמיד פריו ממעל ושרשיו מתחת׃"));
hebsuperobject.biblemap.put("b30_2_10", new hebsuperobject(30,2,10,"ואנכי העליתי אתכם מארץ מצרים ואולך אתכם במדבר ארבעים שנה לרשת את ארץ האמרי׃"));
hebsuperobject.biblemap.put("b30_2_11", new hebsuperobject(30,2,11,"ואקים מבניכם לנביאים ומבחוריכם לנזרים האף אין זאת בני ישראל נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_2_12", new hebsuperobject(30,2,12,"ותשקו את הנזרים יין ועל הנביאים צויתם לאמר לא תנבאו׃"));
hebsuperobject.biblemap.put("b30_2_13", new hebsuperobject(30,2,13,"הנה אנכי מעיק תחתיכם כאשר תעיק העגלה המלאה לה עמיר׃"));
hebsuperobject.biblemap.put("b30_2_14", new hebsuperobject(30,2,14,"ואבד מנוס מקל וחזק לא יאמץ כחו וגבור לא ימלט נפשו׃"));
hebsuperobject.biblemap.put("b30_2_15", new hebsuperobject(30,2,15,"ותפש הקשת לא יעמד וקל ברגליו לא ימלט ורכב הסוס לא ימלט נפשו׃"));
hebsuperobject.biblemap.put("b30_2_16", new hebsuperobject(30,2,16,"ואמיץ לבו בגבורים ערום ינוס ביום ההוא נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_3_1", new hebsuperobject(30,3,1,"שמעו את הדבר הזה אשר דבר יהוה עליכם בני ישראל על כל המשפחה אשר העליתי מארץ מצרים לאמר׃"));
hebsuperobject.biblemap.put("b30_3_2", new hebsuperobject(30,3,2,"רק אתכם ידעתי מכל משפחות האדמה על כן אפקד עליכם את כל עונתיכם׃"));
hebsuperobject.biblemap.put("b30_3_3", new hebsuperobject(30,3,3,"הילכו שנים יחדו בלתי אם נועדו׃"));
hebsuperobject.biblemap.put("b30_3_4", new hebsuperobject(30,3,4,"הישאג אריה ביער וטרף אין לו היתן כפיר קולו ממענתו בלתי אם לכד׃"));
hebsuperobject.biblemap.put("b30_3_5", new hebsuperobject(30,3,5,"התפל צפור על פח הארץ ומוקש אין לה היעלה פח מן האדמה ולכוד לא ילכוד׃"));
hebsuperobject.biblemap.put("b30_3_6", new hebsuperobject(30,3,6,"אם יתקע שופר בעיר ועם לא יחרדו אם תהיה רעה בעיר ויהוה לא עשה׃"));
hebsuperobject.biblemap.put("b30_3_7", new hebsuperobject(30,3,7,"כי לא יעשה אדני יהוה דבר כי אם גלה סודו אל עבדיו הנביאים׃"));
hebsuperobject.biblemap.put("b30_3_8", new hebsuperobject(30,3,8,"אריה שאג מי לא יירא אדני יהוה דבר מי לא ינבא׃"));
hebsuperobject.biblemap.put("b30_3_9", new hebsuperobject(30,3,9,"השמיעו על ארמנות באשדוד ועל ארמנות בארץ מצרים ואמרו האספו על הרי שמרון וראו מהומת רבות בתוכה ועשוקים בקרבה׃"));
hebsuperobject.biblemap.put("b30_3_10", new hebsuperobject(30,3,10,"ולא ידעו עשות נכחה נאם יהוה האוצרים חמס ושד בארמנותיהם׃"));
hebsuperobject.biblemap.put("b30_3_11", new hebsuperobject(30,3,11,"לכן כה אמר אדני יהוה צר וסביב הארץ והורד ממך עזך ונבזו ארמנותיך׃"));
hebsuperobject.biblemap.put("b30_3_12", new hebsuperobject(30,3,12,"כה אמר יהוה כאשר יציל הרעה מפי הארי שתי כרעים או בדל אזן כן ינצלו בני ישראל הישבים בשמרון בפאת מטה ובדמשק ערש׃"));
hebsuperobject.biblemap.put("b30_3_13", new hebsuperobject(30,3,13,"שמעו והעידו בבית יעקב נאם אדני יהוה אלהי הצבאות׃"));
hebsuperobject.biblemap.put("b30_3_14", new hebsuperobject(30,3,14,"כי ביום פקדי פשעי ישראל עליו ופקדתי על מזבחות בית אל ונגדעו קרנות המזבח ונפלו לארץ׃"));
hebsuperobject.biblemap.put("b30_3_15", new hebsuperobject(30,3,15,"והכיתי בית החרף על בית הקיץ ואבדו בתי השן וספו בתים רבים נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_1", new hebsuperobject(30,4,1,"שמעו הדבר הזה פרות הבשן אשר בהר שמרון העשקות דלים הרצצות אביונים האמרת לאדניהם הביאה ונשתה׃"));
hebsuperobject.biblemap.put("b30_4_2", new hebsuperobject(30,4,2,"נשבע אדני יהוה בקדשו כי הנה ימים באים עליכם ונשא אתכם בצנות ואחריתכן בסירות דוגה׃"));
hebsuperobject.biblemap.put("b30_4_3", new hebsuperobject(30,4,3,"ופרצים תצאנה אשה נגדה והשלכתנה ההרמונה נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_4", new hebsuperobject(30,4,4,"באו בית אל ופשעו הגלגל הרבו לפשע והביאו לבקר זבחיכם לשלשת ימים מעשרתיכם׃"));
hebsuperobject.biblemap.put("b30_4_5", new hebsuperobject(30,4,5,"וקטר מחמץ תודה וקראו נדבות השמיעו כי כן אהבתם בני ישראל נאם אדני יהוה׃"));
hebsuperobject.biblemap.put("b30_4_6", new hebsuperobject(30,4,6,"וגם אני נתתי לכם נקיון שנים בכל עריכם וחסר לחם בכל מקומתיכם ולא שבתם עדי נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_7", new hebsuperobject(30,4,7,"וגם אנכי מנעתי מכם את הגשם בעוד שלשה חדשים לקציר והמטרתי על עיר אחת ועל עיר אחת לא אמטיר חלקה אחת תמטר וחלקה אשר לא תמטיר עליה תיבש׃"));
hebsuperobject.biblemap.put("b30_4_8", new hebsuperobject(30,4,8,"ונעו שתים שלש ערים אל עיר אחת לשתות מים ולא ישבעו ולא שבתם עדי נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_9", new hebsuperobject(30,4,9,"הכיתי אתכם בשדפון ובירקון הרבות גנותיכם וכרמיכם ותאניכם וזיתיכם יאכל הגזם ולא שבתם עדי נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_10", new hebsuperobject(30,4,10,"שלחתי בכם דבר בדרך מצרים הרגתי בחרב בחוריכם עם שבי סוסיכם ואעלה באש מחניכם ובאפכם ולא שבתם עדי נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_11", new hebsuperobject(30,4,11,"הפכתי בכם כמהפכת אלהים את סדם ואת עמרה ותהיו כאוד מצל משרפה ולא שבתם עדי נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_4_12", new hebsuperobject(30,4,12,"לכן כה אעשה לך ישראל עקב כי זאת אעשה לך הכון לקראת אלהיך ישראל׃"));
hebsuperobject.biblemap.put("b30_4_13", new hebsuperobject(30,4,13,"כי הנה יוצר הרים וברא רוח ומגיד לאדם מה שחו עשה שחר עיפה ודרך על במתי ארץ יהוה אלהי צבאות שמו׃"));
hebsuperobject.biblemap.put("b30_5_1", new hebsuperobject(30,5,1,"שמעו את הדבר הזה אשר אנכי נשא עליכם קינה בית ישראל׃"));
hebsuperobject.biblemap.put("b30_5_2", new hebsuperobject(30,5,2,"נפלה לא תוסיף קום בתולת ישראל נטשה על אדמתה אין מקימה׃"));
hebsuperobject.biblemap.put("b30_5_3", new hebsuperobject(30,5,3,"כי כה אמר אדני יהוה העיר היצאת אלף תשאיר מאה והיוצאת מאה תשאיר עשרה לבית ישראל׃"));
hebsuperobject.biblemap.put("b30_5_4", new hebsuperobject(30,5,4,"כי כה אמר יהוה לבית ישראל דרשוני וחיו׃"));
hebsuperobject.biblemap.put("b30_5_5", new hebsuperobject(30,5,5,"ואל תדרשו בית אל והגלגל לא תבאו ובאר שבע לא תעברו כי הגלגל גלה יגלה ובית אל יהיה לאון׃"));
hebsuperobject.biblemap.put("b30_5_6", new hebsuperobject(30,5,6,"דרשו את יהוה וחיו פן יצלח כאש בית יוסף ואכלה ואין מכבה לבית אל׃"));
hebsuperobject.biblemap.put("b30_5_7", new hebsuperobject(30,5,7,"ההפכים ללענה משפט וצדקה לארץ הניחו׃"));
hebsuperobject.biblemap.put("b30_5_8", new hebsuperobject(30,5,8,"עשה כימה וכסיל והפך לבקר צלמות ויום לילה החשיך הקורא למי הים וישפכם על פני הארץ יהוה שמו׃"));
hebsuperobject.biblemap.put("b30_5_9", new hebsuperobject(30,5,9,"המבליג שד על עז ושד על מבצר יבוא׃"));
hebsuperobject.biblemap.put("b30_5_10", new hebsuperobject(30,5,10,"שנאו בשער מוכיח ודבר תמים יתעבו׃"));
hebsuperobject.biblemap.put("b30_5_11", new hebsuperobject(30,5,11,"לכן יען בושסכם על דל ומשאת בר תקחו ממנו בתי גזית בניתם ולא תשבו בם כרמי חמד נטעתם ולא תשתו את יינם׃"));
hebsuperobject.biblemap.put("b30_5_12", new hebsuperobject(30,5,12,"כי ידעתי רבים פשעיכם ועצמים חטאתיכם צררי צדיק לקחי כפר ואביונים בשער הטו׃"));
hebsuperobject.biblemap.put("b30_5_13", new hebsuperobject(30,5,13,"לכן המשכיל בעת ההיא ידם כי עת רעה היא׃"));
hebsuperobject.biblemap.put("b30_5_14", new hebsuperobject(30,5,14,"דרשו טוב ואל רע למען תחיו ויהי כן יהוה אלהי צבאות אתכם כאשר אמרתם׃"));
hebsuperobject.biblemap.put("b30_5_15", new hebsuperobject(30,5,15,"שנאו רע ואהבו טוב והציגו בשער משפט אולי יחנן יהוה אלהי צבאות שארית יוסף׃"));
hebsuperobject.biblemap.put("b30_5_16", new hebsuperobject(30,5,16,"לכן כה אמר יהוה אלהי צבאות אדני בכל רחבות מספד ובכל חוצות יאמרו הו הו וקראו אכר אל אבל ומספד אל יודעי נהי׃"));
hebsuperobject.biblemap.put("b30_5_17", new hebsuperobject(30,5,17,"ובכל כרמים מספד כי אעבר בקרבך אמר יהוה׃"));
hebsuperobject.biblemap.put("b30_5_18", new hebsuperobject(30,5,18,"הוי המתאוים את יום יהוה למה זה לכם יום יהוה הוא חשך ולא אור׃"));
hebsuperobject.biblemap.put("b30_5_19", new hebsuperobject(30,5,19,"כאשר ינוס איש מפני הארי ופגעו הדב ובא הבית וסמך ידו על הקיר ונשכו הנחש׃"));
hebsuperobject.biblemap.put("b30_5_20", new hebsuperobject(30,5,20,"הלא חשך יום יהוה ולא אור ואפל ולא נגה לו׃"));
hebsuperobject.biblemap.put("b30_5_21", new hebsuperobject(30,5,21,"שנאתי מאסתי חגיכם ולא אריח בעצרתיכם׃"));
hebsuperobject.biblemap.put("b30_5_22", new hebsuperobject(30,5,22,"כי אם תעלו לי עלות ומנחתיכם לא ארצה ושלם מריאיכם לא אביט׃"));
hebsuperobject.biblemap.put("b30_5_23", new hebsuperobject(30,5,23,"הסר מעלי המון שריך וזמרת נבליך לא אשמע׃"));
hebsuperobject.biblemap.put("b30_5_24", new hebsuperobject(30,5,24,"ויגל כמים משפט וצדקה כנחל איתן׃"));
hebsuperobject.biblemap.put("b30_5_25", new hebsuperobject(30,5,25,"הזבחים ומנחה הגשתם לי במדבר ארבעים שנה בית ישראל׃"));
hebsuperobject.biblemap.put("b30_5_26", new hebsuperobject(30,5,26,"ונשאתם את סכות מלככם ואת כיון צלמיכם כוכב אלהיכם אשר עשיתם לכם׃"));
hebsuperobject.biblemap.put("b30_5_27", new hebsuperobject(30,5,27,"והגליתי אתכם מהלאה לדמשק אמר יהוה אלהי צבאות שמו׃"));
hebsuperobject.biblemap.put("b30_6_1", new hebsuperobject(30,6,1,"הוי השאננים בציון והבטחים בהר שמרון נקבי ראשית הגוים ובאו להם בית ישראל׃"));
hebsuperobject.biblemap.put("b30_6_2", new hebsuperobject(30,6,2,"עברו כלנה וראו ולכו משם חמת רבה ורדו גת פלשתים הטובים מן הממלכות האלה אם רב גבולם מגבלכם׃"));
hebsuperobject.biblemap.put("b30_6_3", new hebsuperobject(30,6,3,"המנדים ליום רע ותגישון שבת חמס׃"));
hebsuperobject.biblemap.put("b30_6_4", new hebsuperobject(30,6,4,"השכבים על מטות שן וסרחים על ערשותם ואכלים כרים מצאן ועגלים מתוך מרבק׃"));
hebsuperobject.biblemap.put("b30_6_5", new hebsuperobject(30,6,5,"הפרטים על פי הנבל כדויד חשבו להם כלי שיר׃"));
hebsuperobject.biblemap.put("b30_6_6", new hebsuperobject(30,6,6,"השתים במזרקי יין וראשית שמנים ימשחו ולא נחלו על שבר יוסף׃"));
hebsuperobject.biblemap.put("b30_6_7", new hebsuperobject(30,6,7,"לכן עתה יגלו בראש גלים וסר מרזח סרוחים׃"));
hebsuperobject.biblemap.put("b30_6_8", new hebsuperobject(30,6,8,"נשבע אדני יהוה בנפשו נאם יהוה אלהי צבאות מתאב אנכי את גאון יעקב וארמנתיו שנאתי והסגרתי עיר ומלאה׃"));
hebsuperobject.biblemap.put("b30_6_9", new hebsuperobject(30,6,9,"והיה אם יותרו עשרה אנשים בבית אחד ומתו׃"));
hebsuperobject.biblemap.put("b30_6_10", new hebsuperobject(30,6,10,"ונשאו דודו ומסרפו להוציא עצמים מן הבית ואמר לאשר בירכתי הבית העוד עמך ואמר אפס ואמר הס כי לא להזכיר בשם יהוה׃"));
hebsuperobject.biblemap.put("b30_6_11", new hebsuperobject(30,6,11,"כי הנה יהוה מצוה והכה הבית הגדול רסיסים והבית הקטן בקעים׃"));
hebsuperobject.biblemap.put("b30_6_12", new hebsuperobject(30,6,12,"הירצון בסלע סוסים אם יחרוש בבקרים כי הפכתם לראש משפט ופרי צדקה ללענה׃"));
hebsuperobject.biblemap.put("b30_6_13", new hebsuperobject(30,6,13,"השמחים ללא דבר האמרים הלוא בחזקנו לקחנו לנו קרנים׃"));
hebsuperobject.biblemap.put("b30_6_14", new hebsuperobject(30,6,14,"כי הנני מקים עליכם בית ישראל נאם יהוה אלהי הצבאות גוי ולחצו אתכם מלבוא חמת עד נחל הערבה׃"));
hebsuperobject.biblemap.put("b30_7_1", new hebsuperobject(30,7,1,"כה הראני אדני יהוה והנה יוצר גבי בתחלת עלות הלקש והנה לקש אחר גזי המלך׃"));
hebsuperobject.biblemap.put("b30_7_2", new hebsuperobject(30,7,2,"והיה אם כלה לאכול את עשב הארץ ואמר אדני יהוה סלח נא מי יקום יעקב כי קטן הוא׃"));
hebsuperobject.biblemap.put("b30_7_3", new hebsuperobject(30,7,3,"נחם יהוה על זאת לא תהיה אמר יהוה׃"));
hebsuperobject.biblemap.put("b30_7_4", new hebsuperobject(30,7,4,"כה הראני אדני יהוה והנה קרא לרב באש אדני יהוה ותאכל את תהום רבה ואכלה את החלק׃"));
hebsuperobject.biblemap.put("b30_7_5", new hebsuperobject(30,7,5,"ואמר אדני יהוה חדל נא מי יקום יעקב כי קטן הוא׃"));
hebsuperobject.biblemap.put("b30_7_6", new hebsuperobject(30,7,6,"נחם יהוה על זאת גם היא לא תהיה אמר אדני יהוה׃"));
hebsuperobject.biblemap.put("b30_7_7", new hebsuperobject(30,7,7,"כה הראני והנה אדני נצב על חומת אנך ובידו אנך׃"));
hebsuperobject.biblemap.put("b30_7_8", new hebsuperobject(30,7,8,"ויאמר יהוה אלי מה אתה ראה עמוס ואמר אנך ויאמר אדני הנני שם אנך בקרב עמי ישראל לא אוסיף עוד עבור לו׃"));
hebsuperobject.biblemap.put("b30_7_9", new hebsuperobject(30,7,9,"ונשמו במות ישחק ומקדשי ישראל יחרבו וקמתי על בית ירבעם בחרב׃"));
hebsuperobject.biblemap.put("b30_7_10", new hebsuperobject(30,7,10,"וישלח אמציה כהן בית אל אל ירבעם מלך ישראל לאמר קשר עליך עמוס בקרב בית ישראל לא תוכל הארץ להכיל את כל דבריו׃"));
hebsuperobject.biblemap.put("b30_7_11", new hebsuperobject(30,7,11,"כי כה אמר עמוס בחרב ימות ירבעם וישראל גלה יגלה מעל אדמתו׃"));
hebsuperobject.biblemap.put("b30_7_12", new hebsuperobject(30,7,12,"ויאמר אמציה אל עמוס חזה לך ברח לך אל ארץ יהודה ואכל שם לחם ושם תנבא׃"));
hebsuperobject.biblemap.put("b30_7_13", new hebsuperobject(30,7,13,"ובית אל לא תוסיף עוד להנבא כי מקדש מלך הוא ובית ממלכה הוא׃"));
hebsuperobject.biblemap.put("b30_7_14", new hebsuperobject(30,7,14,"ויען עמוס ויאמר אל אמציה לא נביא אנכי ולא בן נביא אנכי כי בוקר אנכי ובולס שקמים׃"));
hebsuperobject.biblemap.put("b30_7_15", new hebsuperobject(30,7,15,"ויקחני יהוה מאחרי הצאן ויאמר אלי יהוה לך הנבא אל עמי ישראל׃"));
hebsuperobject.biblemap.put("b30_7_16", new hebsuperobject(30,7,16,"ועתה שמע דבר יהוה אתה אמר לא תנבא על ישראל ולא תטיף על בית ישחק׃"));
hebsuperobject.biblemap.put("b30_7_17", new hebsuperobject(30,7,17,"לכן כה אמר יהוה אשתך בעיר תזנה ובניך ובנתיך בחרב יפלו ואדמתך בחבל תחלק ואתה על אדמה טמאה תמות וישראל גלה יגלה מעל אדמתו׃"));
hebsuperobject.biblemap.put("b30_8_1", new hebsuperobject(30,8,1,"כה הראני אדני יהוה והנה כלוב קיץ׃"));
hebsuperobject.biblemap.put("b30_8_2", new hebsuperobject(30,8,2,"ויאמר מה אתה ראה עמוס ואמר כלוב קיץ ויאמר יהוה אלי בא הקץ אל עמי ישראל לא אוסיף עוד עבור לו׃"));
hebsuperobject.biblemap.put("b30_8_3", new hebsuperobject(30,8,3,"והילילו שירות היכל ביום ההוא נאם אדני יהוה רב הפגר בכל מקום השליך הס׃"));
hebsuperobject.biblemap.put("b30_8_4", new hebsuperobject(30,8,4,"שמעו זאת השאפים אביון ולשבית ענוי ארץ׃"));
hebsuperobject.biblemap.put("b30_8_5", new hebsuperobject(30,8,5,"לאמר מתי יעבר החדש ונשבירה שבר והשבת ונפתחה בר להקטין איפה ולהגדיל שקל ולעות מאזני מרמה׃"));
hebsuperobject.biblemap.put("b30_8_6", new hebsuperobject(30,8,6,"לקנות בכסף דלים ואביון בעבור נעלים ומפל בר נשביר׃"));
hebsuperobject.biblemap.put("b30_8_7", new hebsuperobject(30,8,7,"נשבע יהוה בגאון יעקב אם אשכח לנצח כל מעשיהם׃"));
hebsuperobject.biblemap.put("b30_8_8", new hebsuperobject(30,8,8,"העל זאת לא תרגז הארץ ואבל כל יושב בה ועלתה כאר כלה ונגרשה ונשקה כיאור מצרים׃"));
hebsuperobject.biblemap.put("b30_8_9", new hebsuperobject(30,8,9,"והיה ביום ההוא נאם אדני יהוה והבאתי השמש בצהרים והחשכתי לארץ ביום אור׃"));
hebsuperobject.biblemap.put("b30_8_10", new hebsuperobject(30,8,10,"והפכתי חגיכם לאבל וכל שיריכם לקינה והעליתי על כל מתנים שק ועל כל ראש קרחה ושמתיה כאבל יחיד ואחריתה כיום מר׃"));
hebsuperobject.biblemap.put("b30_8_11", new hebsuperobject(30,8,11,"הנה ימים באים נאם אדני יהוה והשלחתי רעב בארץ לא רעב ללחם ולא צמא למים כי אם לשמע את דברי יהוה׃"));
hebsuperobject.biblemap.put("b30_8_12", new hebsuperobject(30,8,12,"ונעו מים עד ים ומצפון ועד מזרח ישוטטו לבקש את דבר יהוה ולא ימצאו׃"));
hebsuperobject.biblemap.put("b30_8_13", new hebsuperobject(30,8,13,"ביום ההוא תתעלפנה הבתולת היפות והבחורים בצמא׃"));
hebsuperobject.biblemap.put("b30_8_14", new hebsuperobject(30,8,14,"הנשבעים באשמת שמרון ואמרו חי אלהיך דן וחי דרך באר שבע ונפלו ולא יקומו עוד׃"));
hebsuperobject.biblemap.put("b30_9_1", new hebsuperobject(30,9,1,"ראיתי את אדני נצב על המזבח ויאמר הך הכפתור וירעשו הספים ובצעם בראש כלם ואחריתם בחרב אהרג לא ינוס להם נס ולא ימלט להם פליט׃"));
hebsuperobject.biblemap.put("b30_9_2", new hebsuperobject(30,9,2,"אם יחתרו בשאול משם ידי תקחם ואם יעלו השמים משם אורידם׃"));
hebsuperobject.biblemap.put("b30_9_3", new hebsuperobject(30,9,3,"ואם יחבאו בראש הכרמל משם אחפש ולקחתים ואם יסתרו מנגד עיני בקרקע הים משם אצוה את הנחש ונשכם׃"));
hebsuperobject.biblemap.put("b30_9_4", new hebsuperobject(30,9,4,"ואם ילכו בשבי לפני איביהם משם אצוה את החרב והרגתם ושמתי עיני עליהם לרעה ולא לטובה׃"));
hebsuperobject.biblemap.put("b30_9_5", new hebsuperobject(30,9,5,"ואדני יהוה הצבאות הנוגע בארץ ותמוג ואבלו כל יושבי בה ועלתה כיאר כלה ושקעה כיאר מצרים׃"));
hebsuperobject.biblemap.put("b30_9_6", new hebsuperobject(30,9,6,"הבונה בשמים מעלותו ואגדתו על ארץ יסדה הקרא למי הים וישפכם על פני הארץ יהוה שמו׃"));
hebsuperobject.biblemap.put("b30_9_7", new hebsuperobject(30,9,7,"הלוא כבני כשיים אתם לי בני ישראל נאם יהוה הלוא את ישראל העליתי מארץ מצרים ופלשתיים מכפתור וארם מקיר׃"));
hebsuperobject.biblemap.put("b30_9_8", new hebsuperobject(30,9,8,"הנה עיני אדני יהוה בממלכה החטאה והשמדתי אתה מעל פני האדמה אפס כי לא השמיד אשמיד את בית יעקב נאם יהוה׃"));
hebsuperobject.biblemap.put("b30_9_9", new hebsuperobject(30,9,9,"כי הנה אנכי מצוה והנעותי בכל הגוים את בית ישראל כאשר ינוע בכברה ולא יפול צרור ארץ׃"));
hebsuperobject.biblemap.put("b30_9_10", new hebsuperobject(30,9,10,"בחרב ימותו כל חטאי עמי האמרים לא תגיש ותקדים בעדינו הרעה׃"));
hebsuperobject.biblemap.put("b30_9_11", new hebsuperobject(30,9,11,"ביום ההוא אקים את סכת דויד הנפלת וגדרתי את פרציהן והרסתיו אקים ובניתיה כימי עולם׃"));
hebsuperobject.biblemap.put("b30_9_12", new hebsuperobject(30,9,12,"למען יירשו את שארית אדום וכל הגוים אשר נקרא שמי עליהם נאם יהוה עשה זאת׃"));
hebsuperobject.biblemap.put("b30_9_13", new hebsuperobject(30,9,13,"הנה ימים באים נאם יהוה ונגש חורש בקצר ודרך ענבים במשך הזרע והטיפו ההרים עסיס וכל הגבעות תתמוגגנה׃"));
hebsuperobject.biblemap.put("b30_9_14", new hebsuperobject(30,9,14,"ושבתי את שבות עמי ישראל ובנו ערים נשמות וישבו ונטעו כרמים ושתו את יינם ועשו גנות ואכלו את פריהם׃"));
hebsuperobject.biblemap.put("b30_9_15", new hebsuperobject(30,9,15,"ונטעתים על אדמתם ולא ינתשו עוד מעל אדמתם אשר נתתי להם אמר יהוה אלהיך׃"));

}

}