package heb.bible;

public class hebbible48 {

public hebbible48() {

putmapbible48();

}

private void putmapbible48() {

hebsuperobject.biblemap.put("b48_1_1", new hebsuperobject(48,1,1,"פולוס השליח לא מבני אדם ולא על ידי בן אדם כי אם על ידי ישוע המשיח ואלהים האב אשר העירו מן המתים׃"));
hebsuperobject.biblemap.put("b48_1_2", new hebsuperobject(48,1,2,"וכל האחים אשר עמדי אל הקהלות אשר בגלטיא׃"));
hebsuperobject.biblemap.put("b48_1_3", new hebsuperobject(48,1,3,"חסד לכם ושלום מאת האלהים אבינו ומאת אדנינו ישוע המשיח׃"));
hebsuperobject.biblemap.put("b48_1_4", new hebsuperobject(48,1,4,"אשר נתן את נפשו בעד חטאתינו לחלצנו מן העולם הרע הזה כרצון אלהינו אבינו׃"));
hebsuperobject.biblemap.put("b48_1_5", new hebsuperobject(48,1,5,"אשר לו הכבוד לעולמי עולמים אמן׃"));
hebsuperobject.biblemap.put("b48_1_6", new hebsuperobject(48,1,6,"תמה אני כי סרתם מהר מאחרי הקרא אתכם בחסד המשיח אל בשורה זרה׃"));
hebsuperobject.biblemap.put("b48_1_7", new hebsuperobject(48,1,7,"והיא איננה אחרת רק שיש אנשים העכרים אתכם וחפצים להפך את בשורת המשיח׃"));
hebsuperobject.biblemap.put("b48_1_8", new hebsuperobject(48,1,8,"אבל גם אנחנו או מלאך מן השמים אם יבוא לבשר אתכם בשורה מבלעדי זאת אשר בשרנו אתכם חרם יהיה׃"));
hebsuperobject.biblemap.put("b48_1_9", new hebsuperobject(48,1,9,"כמו שאמרנו כבר כן אמר עתה עוד הפעם איש כי יבשר אתכם בשורה מבלעדי אשר קבלתם חרם יהיה׃"));
hebsuperobject.biblemap.put("b48_1_10", new hebsuperobject(48,1,10,"ועתה המתרצה אנכי אל בני אדם אם אל האלהים או המבקש אנכי למצא חן בעיני בני אדם כי במצאי חן בעיני בני אדם לא אהיה עוד עבד המשיח׃"));
hebsuperobject.biblemap.put("b48_1_11", new hebsuperobject(48,1,11,"אבל מודיע אני אתכם אחי כי הבשורה אשר בשרתי לא לפי דרך אדם היא׃"));
hebsuperobject.biblemap.put("b48_1_12", new hebsuperobject(48,1,12,"כי גם אנכי לא קבלתיה מאדם ולא למדוני אתה כי אם בחזיון ישוע המשיח׃"));
hebsuperobject.biblemap.put("b48_1_13", new hebsuperobject(48,1,13,"כי הלא שמעתם את דרכי אשר התהלכתי מלפנים בין היהודים ואת אשר רדפתי על יתר את עדת אלהים ואבדתיה׃"));
hebsuperobject.biblemap.put("b48_1_14", new hebsuperobject(48,1,14,"ואהי הולך וחזק בדת היהודית על רבים מבני גילי בעמי בקנאתי הגדולה לקבלות אבותי׃"));
hebsuperobject.biblemap.put("b48_1_15", new hebsuperobject(48,1,15,"אך כאשר היה רצון האלהים אשר הבדיל אתי מרחם אמי ויקראני בחסדו׃"));
hebsuperobject.biblemap.put("b48_1_16", new hebsuperobject(48,1,16,"לגלות בי את בנו שאבשרנו בגוים מיד לא נועצתי עם בשר ודם׃"));
hebsuperobject.biblemap.put("b48_1_17", new hebsuperobject(48,1,17,"גם לא עליתי ירושלים אל אשר היו שליחים לפני כי אם הלכתי לערב ומשם שבתי אל דמשק׃"));
hebsuperobject.biblemap.put("b48_1_18", new hebsuperobject(48,1,18,"אחרי כן מקץ שלש שנים עליתי ירושלים לראות את כיפא ואשב עמו חמשה עשר יום׃"));
hebsuperobject.biblemap.put("b48_1_19", new hebsuperobject(48,1,19,"ואחר מן השליחים לא ראיתי זולתי את יעקב אחי אדנינו׃"));
hebsuperobject.biblemap.put("b48_1_20", new hebsuperobject(48,1,20,"ואשר אני כתב אליכם הנה נגד האלהים כי לא אכזב׃"));
hebsuperobject.biblemap.put("b48_1_21", new hebsuperobject(48,1,21,"אחרי כן באתי אל גלילות סוריא וקיליקיא׃"));
hebsuperobject.biblemap.put("b48_1_22", new hebsuperobject(48,1,22,"אבל קהלות יהודה אשר במשיח הנה לא ידעו את פני׃"));
hebsuperobject.biblemap.put("b48_1_23", new hebsuperobject(48,1,23,"רק זאת בלבד שמעו כי האיש ההוא אשר היה רדף אתנו מאז עתה הוא מבשר את האמונה אשר האבידה מלפנים׃"));
hebsuperobject.biblemap.put("b48_1_24", new hebsuperobject(48,1,24,"ויהללו בי את האלהים׃"));
hebsuperobject.biblemap.put("b48_2_1", new hebsuperobject(48,2,1,"אחרי כן מקץ ארבע עשרה שנה שבתי ועליתי לירושלים עם בר נבא ואקח אתי גם את טיטוס׃"));
hebsuperobject.biblemap.put("b48_2_2", new hebsuperobject(48,2,2,"ואעל שמה על פי מחזה ואשים לפניהם את הבשורה אשר קראתי בגוים וביחוד שמתיה לפני החשובים שבהם פן תהיה לריק מרוצתי אשר ארוץ או רצתי׃"));
hebsuperobject.biblemap.put("b48_2_3", new hebsuperobject(48,2,3,"אבל גם טיטוס אשר אתי אף כי יוני הוא לא הכרח להמול׃"));
hebsuperobject.biblemap.put("b48_2_4", new hebsuperobject(48,2,4,"מפני אחי השקר הנכנסים בסתר בתוכנו אשר באו לרגל את חרותנו אשר לנו בישוע המשיח למען העבידנו׃"));
hebsuperobject.biblemap.put("b48_2_5", new hebsuperobject(48,2,5,"אשר לא סרנו למשמעתם אף לא שעה אחת למען אשר תעמד בקרבכם אמתה של הבשורה׃"));
hebsuperobject.biblemap.put("b48_2_6", new hebsuperobject(48,2,6,"ומאת הנחשבים להיות מה יהיו מי שיהיו אינני חושש לזה כי האלהים לא ישא פני איש לי לא הוסיפו החשובים מאומה׃"));
hebsuperobject.biblemap.put("b48_2_7", new hebsuperobject(48,2,7,"ותהי להפך בראותם כי הפקדה לי הבשורה אל הערלים כמו שהפקד כיפא אל המולים׃"));
hebsuperobject.biblemap.put("b48_2_8", new hebsuperobject(48,2,8,"כי הפעל בכיפא לשלחו אל המולים הוא פעל גם בי לשלחני אל הגוים׃"));
hebsuperobject.biblemap.put("b48_2_9", new hebsuperobject(48,2,9,"וכאשר ידעו יעקב וכיפא ויוחנן הנחשבים לעמודים את החסד הנתן לי נתנו לי ולבר נבא את יד ימינם ונאות כי נלך אנחנו לגוים והמה למולים׃"));
hebsuperobject.biblemap.put("b48_2_10", new hebsuperobject(48,2,10,"רק שנזכר את האביונים אשר גם שקדתי לעשותה׃"));
hebsuperobject.biblemap.put("b48_2_11", new hebsuperobject(48,2,11,"וכאשר בא כיפא לאנטיוכיא הוכחתי אל פניו דרכו מפני שהיה בו אשם׃"));
hebsuperobject.biblemap.put("b48_2_12", new hebsuperobject(48,2,12,"כי לפני בא אנשים מאת יעקב היה אכל עם הגוים יחדו וכבאם היה מתרחק ופורש מהם מיראתו את בני המילה׃"));
hebsuperobject.biblemap.put("b48_2_13", new hebsuperobject(48,2,13,"ויכחשו עמו גם שאר היהודים עד כי בר נבא גם הוא נדח אחרי כחשם׃"));
hebsuperobject.biblemap.put("b48_2_14", new hebsuperobject(48,2,14,"אכן בראותו את אשר לא ישרו לכת כאמתה של הבשורה אמרתי אל כיפא בפני כל אם אתה היהודי תתנהג כנכרי ולא כיהודי למה תכריח את הגוים להתנהג כיהודים׃"));
hebsuperobject.biblemap.put("b48_2_15", new hebsuperobject(48,2,15,"הן מזרע היהודים אנחנו ולא חטאים מן הגוים׃"));
hebsuperobject.biblemap.put("b48_2_16", new hebsuperobject(48,2,16,"ומדעתנו כי לא יצדק אדם מתוך מעשי התורה כי אם באמונת ישוע המשיח גם אנחנו האמנו במשיח ישוע למען נצדק מאמונת המשיח ולא ממעשי התורה כי ממעשי התורה לא יצדק כל בשר׃"));
hebsuperobject.biblemap.put("b48_2_17", new hebsuperobject(48,2,17,"ואם בבקשנו להצדק במשיח נמצא גם אנחנו חטאים הנה המשיח משרת החטא חלילה׃"));
hebsuperobject.biblemap.put("b48_2_18", new hebsuperobject(48,2,18,"כי אם אשוב ואבנה את מה שסתרתי אני עשה את עצמי פשע׃"));
hebsuperobject.biblemap.put("b48_2_19", new hebsuperobject(48,2,19,"כי מתי אני לתורה על ידי התורה למען אחיה לאלהים׃"));
hebsuperobject.biblemap.put("b48_2_20", new hebsuperobject(48,2,20,"עם המשיח נצלבתי ואין עוד אנכי החי כי אם המשיח הוא חי בקרבי ואשר אני חי עתה בבשר אחיה באמונת בן אלהים אשר אהבני ויתן את נפשו בעדי׃"));
hebsuperobject.biblemap.put("b48_2_21", new hebsuperobject(48,2,21,"לא אמאס את חסד האלהים כי אלו תהיה על ידי התורה צדקה הנה חנם מת המשיח׃"));
hebsuperobject.biblemap.put("b48_3_1", new hebsuperobject(48,3,1,"אהה גלטים חסרי דעת מי התעה אתכם בכשפיו משמע את האמת אחרי אשר ציר בתוככם ישוע המשיח הצלוב לנגד עיניכם׃"));
hebsuperobject.biblemap.put("b48_3_2", new hebsuperobject(48,3,2,"זאת לבד חפצתי ללמד מכם האם ממעשי התורה קבלתם את הרוח או משמועת האמונה׃"));
hebsuperobject.biblemap.put("b48_3_3", new hebsuperobject(48,3,3,"האתם סכלים כל כך אשר החלותם ברוח ועתה תכלו בבשר׃"));
hebsuperobject.biblemap.put("b48_3_4", new hebsuperobject(48,3,4,"הכזאת סבלתם לריק אם אמנם אך לריק׃"));
hebsuperobject.biblemap.put("b48_3_5", new hebsuperobject(48,3,5,"הנה המפיק לכם את הרוח ופעל בכם גבורות הכי ממעשי התורה הוא עשה אלה או משמועת האמונה׃"));
hebsuperobject.biblemap.put("b48_3_6", new hebsuperobject(48,3,6,"כאשר האמין אברהם באלהים ותחשב לו לצדקה׃"));
hebsuperobject.biblemap.put("b48_3_7", new hebsuperobject(48,3,7,"דעו אפוא כי בני האמונה בני אברהם המה׃"));
hebsuperobject.biblemap.put("b48_3_8", new hebsuperobject(48,3,8,"והמקרא בראתו מראש כי האלהים יצדיק את הגוים מתוך האמונה קדם לבשר את אברהם לאמר ונברכו בך כל הגוים׃"));
hebsuperobject.biblemap.put("b48_3_9", new hebsuperobject(48,3,9,"על כן בני האמונה יתברכו עם אברהם המאמין׃"));
hebsuperobject.biblemap.put("b48_3_10", new hebsuperobject(48,3,10,"כי בני מעשי התורה תחת הקללה המה שנאמר ארור אשר לא יקים את כל הדברים הכתובים בספר התורה לעשות אותם׃"));
hebsuperobject.biblemap.put("b48_3_11", new hebsuperobject(48,3,11,"וגלוי הוא כי על ידי התורה לא יצדק האדם לפני האלהים כי צדיק באמונתו יחיה׃"));
hebsuperobject.biblemap.put("b48_3_12", new hebsuperobject(48,3,12,"והתורה איננה מן האמונה כי אם אשר יעשה אתם האדם וחי בהם׃"));
hebsuperobject.biblemap.put("b48_3_13", new hebsuperobject(48,3,13,"המשיח פדנו מקללת התורה בהיותו לקללה בעדנו שנאמר קללת אלהים תלוי׃"));
hebsuperobject.biblemap.put("b48_3_14", new hebsuperobject(48,3,14,"למען אשר תבא ברכת אברהם במשיח ישוע על הגוים למען אשר נשא את הבטחת הרוח על ידי האמונה׃"));
hebsuperobject.biblemap.put("b48_3_15", new hebsuperobject(48,3,15,"אחי לפי דרך אדם אדבר אפלו דיתיקי של בן אדם אם מקימת היא לא יפרנה איש גם לא יוסיף עליה דבר׃"));
hebsuperobject.biblemap.put("b48_3_16", new hebsuperobject(48,3,16,"והנה לאברהם נאמרו ההבטחות ולזרעו ולא אמר ולזרעיך כאלו לרבים אלא כאלו ליחיד ולזרעך והוא המשיח׃"));
hebsuperobject.biblemap.put("b48_3_17", new hebsuperobject(48,3,17,"וזאת אני אמר כי דיתיקי אשר קימה האלהים מאז לימות המשיח לא תוכל התורה אשר באה אחרי ארבע מאות ושלשים שנה להפר אותה ולבטל את ההבטחה׃"));
hebsuperobject.biblemap.put("b48_3_18", new hebsuperobject(48,3,18,"כי אם תבוא הנחלה מתוך התורה לא תבוא עוד מתוך ההבטחה אבל את אברהם חנן האלהים על ידי הבטחה׃"));
hebsuperobject.biblemap.put("b48_3_19", new hebsuperobject(48,3,19,"אם כן התורה מה היא מפני הפשעים נוספה עד כי יבוא הזרע אשר לו ההבטחה ותושם התורה על ידי המלאכים וביד סרסר׃"));
hebsuperobject.biblemap.put("b48_3_20", new hebsuperobject(48,3,20,"והסרסר לא של אחד הוא אך האלהים הוא אחד׃"));
hebsuperobject.biblemap.put("b48_3_21", new hebsuperobject(48,3,21,"ועתה הכי התורה סתרת את הבטחות האלהים חלילה כי אלו נתנה תורה אשר בכחה להחיות אז באמת היתה הצדקה על ידי התורה׃"));
hebsuperobject.biblemap.put("b48_3_22", new hebsuperobject(48,3,22,"אבל הכתוב סגר את הכל ביד החטא למען תנתן ההבטחה אל המאמינים באמונת ישוע המשיח׃"));
hebsuperobject.biblemap.put("b48_3_23", new hebsuperobject(48,3,23,"לפני בוא האמונה היינו סגורים ונשמרים תחת התורה אלי האמונה העתידה להגלות׃"));
hebsuperobject.biblemap.put("b48_3_24", new hebsuperobject(48,3,24,"ובכן התורה היתה אמנת אותנו אל המשיח למען נצדק על ידי האמונה׃"));
hebsuperobject.biblemap.put("b48_3_25", new hebsuperobject(48,3,25,"אבל עתה אחרי אשר באה האמונה אין אנחנו עוד תחת יד האמן׃"));
hebsuperobject.biblemap.put("b48_3_26", new hebsuperobject(48,3,26,"כי כלכם בני אלהים אתם על ידי האמונה במשיח ישוע׃"));
hebsuperobject.biblemap.put("b48_3_27", new hebsuperobject(48,3,27,"כי כלכם אשר נטבלתם למשיח לבשתם את המשיח׃"));
hebsuperobject.biblemap.put("b48_3_28", new hebsuperobject(48,3,28,"ואין עוד לא יהודי ולא יוני לא עבד ולא בן חורין לא זכר ולא נקבה כי אתם כלכם אחד במשיח ישוע׃"));
hebsuperobject.biblemap.put("b48_3_29", new hebsuperobject(48,3,29,"ואם אתם למשיח הנכם זרע אברהם ונחלים כפי ההבטחה׃"));
hebsuperobject.biblemap.put("b48_4_1", new hebsuperobject(48,4,1,"ואני אמר היורש כל עת היותו קטן אין הבדל בינו ובין העבד אף אם הוא אדון הכל׃"));
hebsuperobject.biblemap.put("b48_4_2", new hebsuperobject(48,4,2,"אלא הוא תחת יד אמנים ופקידי הבית עד לזמן המיעד לו מאת אביו׃"));
hebsuperobject.biblemap.put("b48_4_3", new hebsuperobject(48,4,3,"ככה גם אנחנו בעוד היותנו קטנים היינו משעבדים ליסדות העולם׃"));
hebsuperobject.biblemap.put("b48_4_4", new hebsuperobject(48,4,4,"ובמלאת העת שלח האלהים את בנו אשר נולד מאשה ונתן תחת יד התורה׃"));
hebsuperobject.biblemap.put("b48_4_5", new hebsuperobject(48,4,5,"לפדות את אשר היו תחת יד התורה למען נקבל את משפט הבנים׃"));
hebsuperobject.biblemap.put("b48_4_6", new hebsuperobject(48,4,6,"ויען כי בנים אתם שלח האלהים בלבבכם את רוח בנו הקורא אבא אבינו׃"));
hebsuperobject.biblemap.put("b48_4_7", new hebsuperobject(48,4,7,"לכן אינך עוד עבד כי אם בן ואם בן אתה הנך גם יורש האלהים על ידי המשיח׃"));
hebsuperobject.biblemap.put("b48_4_8", new hebsuperobject(48,4,8,"הן לפנים באין דעת אלהים הייתם עבדים את אשר בעצמותם אינם אלהים׃"));
hebsuperobject.biblemap.put("b48_4_9", new hebsuperobject(48,4,9,"ועתה אחרי ידעתם את האלהים ויותר אחרי שנודעתם לאלהים איך תשובו אל היסדות הרפים והדלים ההם אשר תרצו להכנע להם מחדש׃"));
hebsuperobject.biblemap.put("b48_4_10", new hebsuperobject(48,4,10,"ימים אתם שמרים וחדשים ומועדים ושנים׃"));
hebsuperobject.biblemap.put("b48_4_11", new hebsuperobject(48,4,11,"מתירא אני פן לריק עמלתי בכם׃"));
hebsuperobject.biblemap.put("b48_4_12", new hebsuperobject(48,4,12,"היו נא כמוני כי גם אני כמוכם מתחנן אני לכם אחי לא הרעתם לי מאומה׃"));
hebsuperobject.biblemap.put("b48_4_13", new hebsuperobject(48,4,13,"אתם ידעתם אשר בחלשת בשרי בשרתי לכם את הבשורה לראשונה׃"));
hebsuperobject.biblemap.put("b48_4_14", new hebsuperobject(48,4,14,"ואתם לא בזיתם את נסיוני אשר נסיתי בבשרי ולא געלתם אתו כי אם קבלתם אתי כמלאך אלהים כמשיח ישוע׃"));
hebsuperobject.biblemap.put("b48_4_15", new hebsuperobject(48,4,15,"ועתה איה אשרכם כי מעיד אני עליכם אשר אם יכלתם הייתם עקרים את עיניכם לתתן לי׃"));
hebsuperobject.biblemap.put("b48_4_16", new hebsuperobject(48,4,16,"ועתה הנהייתי לכם לאיב בדברי אמת אליכם׃"));
hebsuperobject.biblemap.put("b48_4_17", new hebsuperobject(48,4,17,"אינם מקנאים לכם לטובה כי חפצם להפריד אתכם מעלינו למען תהיו מקנאים להם׃"));
hebsuperobject.biblemap.put("b48_4_18", new hebsuperobject(48,4,18,"אבל טוב לקנא תמיד לטובה ולא לבד בהיותו אצלכם׃"));
hebsuperobject.biblemap.put("b48_4_19", new hebsuperobject(48,4,19,"בני אשר אני מחולל שנית עד כי יוצר בכם המשיח׃"));
hebsuperobject.biblemap.put("b48_4_20", new hebsuperobject(48,4,20,"אמנה חפצתי להיות עתה אצלכם לשנות את קול דברי כי נבוך אני בכם׃"));
hebsuperobject.biblemap.put("b48_4_21", new hebsuperobject(48,4,21,"אמרו לי אתם החפצים להיות משעבדים לתורה הלא שמעתם את התורה׃"));
hebsuperobject.biblemap.put("b48_4_22", new hebsuperobject(48,4,22,"כי כתוב שהיו לאברהם שני בנים האחד מן האמה והשני מן החפשיה׃"));
hebsuperobject.biblemap.put("b48_4_23", new hebsuperobject(48,4,23,"ואשר לאמה הוא נולד לפי הבשר ואשר לחפשיה על פי ההבטחה׃"));
hebsuperobject.biblemap.put("b48_4_24", new hebsuperobject(48,4,24,"והדברים הם לרמז כי שתי הבריתות הנה האחת מן הר סיני היולדת לעבדות והיא הגר׃"));
hebsuperobject.biblemap.put("b48_4_25", new hebsuperobject(48,4,25,"כי הגר סיני הר בערב הוא והוא כנגד ירושלים של עתה כי היא בעבדות עם בניה׃"));
hebsuperobject.biblemap.put("b48_4_26", new hebsuperobject(48,4,26,"אבל ירושלים של מעלה היא חפשיה והיא אם כלנו׃"));
hebsuperobject.biblemap.put("b48_4_27", new hebsuperobject(48,4,27,"כי כתוב רני עקרה לא ילדה פצחי רנה וצהלי לא חלה כי רבים בני שוממה מבני בעולה׃"));
hebsuperobject.biblemap.put("b48_4_28", new hebsuperobject(48,4,28,"ואנחנו אחי הננו כיצחק בני ההבטחה׃"));
hebsuperobject.biblemap.put("b48_4_29", new hebsuperobject(48,4,29,"וכאשר הנולד לפי הבשר אז היה רדף את הנולד לפי הרוח כן הוא גם עתה׃"));
hebsuperobject.biblemap.put("b48_4_30", new hebsuperobject(48,4,30,"אבל הכתוב מה הוא אמר גרש האמה ואת בנה כי לא יירש בן האמה עם בן החפשיה׃"));
hebsuperobject.biblemap.put("b48_4_31", new hebsuperobject(48,4,31,"על כן אחי לא בני האמה אנחנו כי אם בני החפשיה׃"));
hebsuperobject.biblemap.put("b48_5_1", new hebsuperobject(48,5,1,"ועתה עמדו נא בחרות אשר שחרר אתנו המשיח ואל תשובו להלכד בעל העבדות׃"));
hebsuperobject.biblemap.put("b48_5_2", new hebsuperobject(48,5,2,"הנה אני פולוס אמר לכם כי אם תמולו לא יועיל לכם המשיח׃"));
hebsuperobject.biblemap.put("b48_5_3", new hebsuperobject(48,5,3,"ומעיד אני עוד הפעם בכל איש אשר ימול כי מחיב הוא לשמר את כל התורה׃"));
hebsuperobject.biblemap.put("b48_5_4", new hebsuperobject(48,5,4,"נגזרתם מן המשיח אתם המצטדקים בתורה נפלתם מן החסד׃"));
hebsuperobject.biblemap.put("b48_5_5", new hebsuperobject(48,5,5,"כי אנחנו ברוח ניחל מתוך האמונה לתקות הצדקה׃"));
hebsuperobject.biblemap.put("b48_5_6", new hebsuperobject(48,5,6,"כי במשיח איננה נחשבת לא המילה ולא הערלה כי אם האמונה הפעלת באהבה׃"));
hebsuperobject.biblemap.put("b48_5_7", new hebsuperobject(48,5,7,"היטבתם לרוץ מי חשך אתכם משמע אל האמת׃"));
hebsuperobject.biblemap.put("b48_5_8", new hebsuperobject(48,5,8,"הפתוי הזה איננו מאת הקרא אתכם׃"));
hebsuperobject.biblemap.put("b48_5_9", new hebsuperobject(48,5,9,"מעט שאר מחמץ הוא את כל העסה׃"));
hebsuperobject.biblemap.put("b48_5_10", new hebsuperobject(48,5,10,"מבטח אני בכם באדון שלא תהיה רוח אחרת עמכם והעכר אתכם ישא את עונו יהיה מי שיהיה׃"));
hebsuperobject.biblemap.put("b48_5_11", new hebsuperobject(48,5,11,"ואני אחי אם אכריז עוד המילה על מה אהיה נרדף הלא אז מבטל מכשול הצלב׃"));
hebsuperobject.biblemap.put("b48_5_12", new hebsuperobject(48,5,12,"מי יתן ויכרתו המדיחים אתכם׃"));
hebsuperobject.biblemap.put("b48_5_13", new hebsuperobject(48,5,13,"כי אתם אחי לחרות נקראתם ובלבד שלא תהיה החרות תאנה לבשר אלא שתעבדו איש את רעהו באהבה׃"));
hebsuperobject.biblemap.put("b48_5_14", new hebsuperobject(48,5,14,"כי כל התורה כלולה במצוה אחת והיא ואהבת לרעך כמוך׃"));
hebsuperobject.biblemap.put("b48_5_15", new hebsuperobject(48,5,15,"אבל אם תנשכו ותאכלו איש את אחיו ראו פן תכלו איש על ידי רעהו׃"));
hebsuperobject.biblemap.put("b48_5_16", new hebsuperobject(48,5,16,"והנני אמר התהלכו ברוח ולא תמלאו את תאות הבשר׃"));
hebsuperobject.biblemap.put("b48_5_17", new hebsuperobject(48,5,17,"כי הבשר מתאוה הפך מן הרוח והרוח הפך מן הבשר ושניהם מתקוממים זה לזה עד שלא תוכלו לעשות את אשר תחפצו׃"));
hebsuperobject.biblemap.put("b48_5_18", new hebsuperobject(48,5,18,"ואם תנהגו על ידי הרוח אז אינכם תחת התורה׃"));
hebsuperobject.biblemap.put("b48_5_19", new hebsuperobject(48,5,19,"וגלוים הם פעלי הבשר אשר הם נאוף זנות טמאה וזמה׃"));
hebsuperobject.biblemap.put("b48_5_20", new hebsuperobject(48,5,20,"עבודת אלילים וכשוף איבות ומצות וקנאה ורגז מריבות מחלקות וכתות׃"));
hebsuperobject.biblemap.put("b48_5_21", new hebsuperobject(48,5,21,"צרות עין ושפיכות דמים ושרון וזוללות ודומיהן אשר אמר עליהן כמו שאמרתי כבר כי עשי אלה לא ינחלו מלכות האלהים׃"));
hebsuperobject.biblemap.put("b48_5_22", new hebsuperobject(48,5,22,"ופרי הרוח אהבה שמחה ושלום ארך רוח ונדיבות וחסד ואמונה׃"));
hebsuperobject.biblemap.put("b48_5_23", new hebsuperobject(48,5,23,"וענוה ופרישות אין תורה לנגד עשי אלה׃"));
hebsuperobject.biblemap.put("b48_5_24", new hebsuperobject(48,5,24,"ואשר הם למשיח צלבו את בשרם עם כל תשוקתיו ותאותיו׃"));
hebsuperobject.biblemap.put("b48_5_25", new hebsuperobject(48,5,25,"אם נחיה ברוח נתהלכה גם ברוח׃"));
hebsuperobject.biblemap.put("b48_5_26", new hebsuperobject(48,5,26,"ולא נרדף אחרי כבוד שוא להכעיס איש את רעהו ולקנא איש את רעהו׃"));
hebsuperobject.biblemap.put("b48_6_1", new hebsuperobject(48,6,1,"אחי גם כי יתפש איש מכם בעברה אתם אנשי הרוח תקימהו ברוח ענוה והשמר לנפשך פן תבא לידי נסיון גם אתה׃"));
hebsuperobject.biblemap.put("b48_6_2", new hebsuperobject(48,6,2,"שאו איש את משא רעהו בזאת תמלאו את תורת המשיח׃"));
hebsuperobject.biblemap.put("b48_6_3", new hebsuperobject(48,6,3,"כי החשב את עצמו להיות מה ואיננו מאומה את נפשו הוא מרמה׃"));
hebsuperobject.biblemap.put("b48_6_4", new hebsuperobject(48,6,4,"אבל יבחן כל איש את מעשהו ואז לו לבדו תהיה תהלתו ולא לנגד אחר׃"));
hebsuperobject.biblemap.put("b48_6_5", new hebsuperobject(48,6,5,"כי כל איש את משאו ישא׃"));
hebsuperobject.biblemap.put("b48_6_6", new hebsuperobject(48,6,6,"המלמד בדבר יחלק מכל טובו למלמדהו׃"));
hebsuperobject.biblemap.put("b48_6_7", new hebsuperobject(48,6,7,"אל תתעו לא יתן אלהים להתל בו כי מה שזרע האדם אתו יקצר׃"));
hebsuperobject.biblemap.put("b48_6_8", new hebsuperobject(48,6,8,"הזרע בבשרו יקצר כליון משברו והזרע ברוח יקצר מן הרוח חיי עולם׃"));
hebsuperobject.biblemap.put("b48_6_9", new hebsuperobject(48,6,9,"ואנחנו בעשות הטוב אל נחת כי נקצר בעתו אם לא נרפה׃"));
hebsuperobject.biblemap.put("b48_6_10", new hebsuperobject(48,6,10,"לכן כאשר העת בידנו נעשה נא את הטוב עם כל אדם וביותר עם בני אמונתנו׃"));
hebsuperobject.biblemap.put("b48_6_11", new hebsuperobject(48,6,11,"ראו נא מה גדול המכתב אשר כתבתי אליכם בידי׃"));
hebsuperobject.biblemap.put("b48_6_12", new hebsuperobject(48,6,12,"החפצים להתהדר בבשר מכריחים אתכם להמול רק למען לא ירדפו על צלב המשיח׃"));
hebsuperobject.biblemap.put("b48_6_13", new hebsuperobject(48,6,13,"כי גם הם הנמולים אינם שמרים את התורה אלא רצונם שתמולו למען יתהללו בבשרכם׃"));
hebsuperobject.biblemap.put("b48_6_14", new hebsuperobject(48,6,14,"ואנכי חלילה מהתהלל זולתי בצלב אדנינו ישוע המשיח אשר בו העולם נצלב לי ואני נצלב לעולם׃"));
hebsuperobject.biblemap.put("b48_6_15", new hebsuperobject(48,6,15,"כי במשיח ישוע גם המילה גם הערלה אינן נחשבות כי אם בריאה חדשה׃"));
hebsuperobject.biblemap.put("b48_6_16", new hebsuperobject(48,6,16,"וכל המהלכים כפי השורה הזאת שלום ורחמים עליהם ועל ישראל אשר לאלהים׃"));
hebsuperobject.biblemap.put("b48_6_17", new hebsuperobject(48,6,17,"מעתה איש אל ילאני עוד כי את חבורות האדון ישוע אני נשא בגויתי׃"));
hebsuperobject.biblemap.put("b48_6_18", new hebsuperobject(48,6,18,"חסד ישוע המשיח אדנינו יהי עם רוחכם אחי אמן׃"));

}

}