package heb.bible;

public class hebbible6 {

public hebbible6() {

putmapbible6();

}

private void putmapbible6() {

hebsuperobject.biblemap.put("b6_1_1", new hebsuperobject(6,1,1,"ויהי אחרי מות משה עבד יהוה ויאמר יהוה אל יהושע בן נון משרת משה לאמר׃"));
hebsuperobject.biblemap.put("b6_1_2", new hebsuperobject(6,1,2,"משה עבדי מת ועתה קום עבר את הירדן הזה אתה וכל העם הזה אל הארץ אשר אנכי נתן להם לבני ישראל׃"));
hebsuperobject.biblemap.put("b6_1_3", new hebsuperobject(6,1,3,"כל מקום אשר תדרך כף רגלכם בו לכם נתתיו כאשר דברתי אל משה׃"));
hebsuperobject.biblemap.put("b6_1_4", new hebsuperobject(6,1,4,"מהמדבר והלבנון הזה ועד הנהר הגדול נהר פרת כל ארץ החתים ועד הים הגדול מבוא השמש יהיה גבולכם׃"));
hebsuperobject.biblemap.put("b6_1_5", new hebsuperobject(6,1,5,"לא יתיצב איש לפניך כל ימי חייך כאשר הייתי עם משה אהיה עמך לא ארפך ולא אעזבך׃"));
hebsuperobject.biblemap.put("b6_1_6", new hebsuperobject(6,1,6,"חזק ואמץ כי אתה תנחיל את העם הזה את הארץ אשר נשבעתי לאבותם לתת להם׃"));
hebsuperobject.biblemap.put("b6_1_7", new hebsuperobject(6,1,7,"רק חזק ואמץ מאד לשמר לעשות ככל התורה אשר צוך משה עבדי אל תסור ממנו ימין ושמאול למען תשכיל בכל אשר תלך׃"));
hebsuperobject.biblemap.put("b6_1_8", new hebsuperobject(6,1,8,"לא ימוש ספר התורה הזה מפיך והגית בו יומם ולילה למען תשמר לעשות ככל הכתוב בו כי אז תצליח את דרכך ואז תשכיל׃"));
hebsuperobject.biblemap.put("b6_1_9", new hebsuperobject(6,1,9,"הלוא צויתיך חזק ואמץ אל תערץ ואל תחת כי עמך יהוה אלהיך בכל אשר תלך׃"));
hebsuperobject.biblemap.put("b6_1_10", new hebsuperobject(6,1,10,"ויצו יהושע את שטרי העם לאמר׃"));
hebsuperobject.biblemap.put("b6_1_11", new hebsuperobject(6,1,11,"עברו בקרב המחנה וצוו את העם לאמר הכינו לכם צידה כי בעוד שלשת ימים אתם עברים את הירדן הזה לבוא לרשת את הארץ אשר יהוה אלהיכם נתן לכם לרשתה׃"));
hebsuperobject.biblemap.put("b6_1_12", new hebsuperobject(6,1,12,"ולראובני ולגדי ולחצי שבט המנשה אמר יהושע לאמר׃"));
hebsuperobject.biblemap.put("b6_1_13", new hebsuperobject(6,1,13,"זכור את הדבר אשר צוה אתכם משה עבד יהוה לאמר יהוה אלהיכם מניח לכם ונתן לכם את הארץ הזאת׃"));
hebsuperobject.biblemap.put("b6_1_14", new hebsuperobject(6,1,14,"נשיכם טפכם ומקניכם ישבו בארץ אשר נתן לכם משה בעבר הירדן ואתם תעברו חמשים לפני אחיכם כל גבורי החיל ועזרתם אותם׃"));
hebsuperobject.biblemap.put("b6_1_15", new hebsuperobject(6,1,15,"עד אשר יניח יהוה לאחיכם ככם וירשו גם המה את הארץ אשר יהוה אלהיכם נתן להם ושבתם לארץ ירשתכם וירשתם אותה אשר נתן לכם משה עבד יהוה בעבר הירדן מזרח השמש׃"));
hebsuperobject.biblemap.put("b6_1_16", new hebsuperobject(6,1,16,"ויענו את יהושע לאמר כל אשר צויתנו נעשה ואל כל אשר תשלחנו נלך׃"));
hebsuperobject.biblemap.put("b6_1_17", new hebsuperobject(6,1,17,"ככל אשר שמענו אל משה כן נשמע אליך רק יהיה יהוה אלהיך עמך כאשר היה עם משה׃"));
hebsuperobject.biblemap.put("b6_1_18", new hebsuperobject(6,1,18,"כל איש אשר ימרה את פיך ולא ישמע את דבריך לכל אשר תצונו יומת רק חזק ואמץ׃"));
hebsuperobject.biblemap.put("b6_2_1", new hebsuperobject(6,2,1,"וישלח יהושע בן נון מן השטים שנים אנשים מרגלים חרש לאמר לכו ראו את הארץ ואת יריחו וילכו ויבאו בית אשה זונה ושמה רחב וישכבו שמה׃"));
hebsuperobject.biblemap.put("b6_2_2", new hebsuperobject(6,2,2,"ויאמר למלך יריחו לאמר הנה אנשים באו הנה הלילה מבני ישראל לחפר את הארץ׃"));
hebsuperobject.biblemap.put("b6_2_3", new hebsuperobject(6,2,3,"וישלח מלך יריחו אל רחב לאמר הוציאי האנשים הבאים אליך אשר באו לביתך כי לחפר את כל הארץ באו׃"));
hebsuperobject.biblemap.put("b6_2_4", new hebsuperobject(6,2,4,"ותקח האשה את שני האנשים ותצפנו ותאמר כן באו אלי האנשים ולא ידעתי מאין המה׃"));
hebsuperobject.biblemap.put("b6_2_5", new hebsuperobject(6,2,5,"ויהי השער לסגור בחשך והאנשים יצאו לא ידעתי אנה הלכו האנשים רדפו מהר אחריהם כי תשיגום׃"));
hebsuperobject.biblemap.put("b6_2_6", new hebsuperobject(6,2,6,"והיא העלתם הגגה ותטמנם בפשתי העץ הערכות לה על הגג׃"));
hebsuperobject.biblemap.put("b6_2_7", new hebsuperobject(6,2,7,"והאנשים רדפו אחריהם דרך הירדן על המעברות והשער סגרו אחרי כאשר יצאו הרדפים אחריהם׃"));
hebsuperobject.biblemap.put("b6_2_8", new hebsuperobject(6,2,8,"והמה טרם ישכבון והיא עלתה עליהם על הגג׃"));
hebsuperobject.biblemap.put("b6_2_9", new hebsuperobject(6,2,9,"ותאמר אל האנשים ידעתי כי נתן יהוה לכם את הארץ וכי נפלה אימתכם עלינו וכי נמגו כל ישבי הארץ מפניכם׃"));
hebsuperobject.biblemap.put("b6_2_10", new hebsuperobject(6,2,10,"כי שמענו את אשר הוביש יהוה את מי ים סוף מפניכם בצאתכם ממצרים ואשר עשיתם לשני מלכי האמרי אשר בעבר הירדן לסיחן ולעוג אשר החרמתם אותם׃"));
hebsuperobject.biblemap.put("b6_2_11", new hebsuperobject(6,2,11,"ונשמע וימס לבבנו ולא קמה עוד רוח באיש מפניכם כי יהוה אלהיכם הוא אלהים בשמים ממעל ועל הארץ מתחת׃"));
hebsuperobject.biblemap.put("b6_2_12", new hebsuperobject(6,2,12,"ועתה השבעו נא לי ביהוה כי עשיתי עמכם חסד ועשיתם גם אתם עם בית אבי חסד ונתתם לי אות אמת׃"));
hebsuperobject.biblemap.put("b6_2_13", new hebsuperobject(6,2,13,"והחיתם את אבי ואת אמי ואת אחי ואת אחותי ואת כל אשר להם והצלתם את נפשתינו ממות׃"));
hebsuperobject.biblemap.put("b6_2_14", new hebsuperobject(6,2,14,"ויאמרו לה האנשים נפשנו תחתיכם למות אם לא תגידו את דברנו זה והיה בתת יהוה לנו את הארץ ועשינו עמך חסד ואמת׃"));
hebsuperobject.biblemap.put("b6_2_15", new hebsuperobject(6,2,15,"ותורדם בחבל בעד החלון כי ביתה בקיר החומה ובחומה היא יושבת׃"));
hebsuperobject.biblemap.put("b6_2_16", new hebsuperobject(6,2,16,"ותאמר להם ההרה לכו פן יפגעו בכם הרדפים ונחבתם שמה שלשת ימים עד שוב הרדפים ואחר תלכו לדרככם׃"));
hebsuperobject.biblemap.put("b6_2_17", new hebsuperobject(6,2,17,"ויאמרו אליה האנשים נקים אנחנו משבעתך הזה אשר השבעתנו׃"));
hebsuperobject.biblemap.put("b6_2_18", new hebsuperobject(6,2,18,"הנה אנחנו באים בארץ את תקות חוט השני הזה תקשרי בחלון אשר הורדתנו בו ואת אביך ואת אמך ואת אחיך ואת כל בית אביך תאספי אליך הביתה׃"));
hebsuperobject.biblemap.put("b6_2_19", new hebsuperobject(6,2,19,"והיה כל אשר יצא מדלתי ביתך החוצה דמו בראשו ואנחנו נקים וכל אשר יהיה אתך בבית דמו בראשנו אם יד תהיה בו׃"));
hebsuperobject.biblemap.put("b6_2_20", new hebsuperobject(6,2,20,"ואם תגידי את דברנו זה והיינו נקים משבעתך אשר השבעתנו׃"));
hebsuperobject.biblemap.put("b6_2_21", new hebsuperobject(6,2,21,"ותאמר כדבריכם כן הוא ותשלחם וילכו ותקשר את תקות השני בחלון׃"));
hebsuperobject.biblemap.put("b6_2_22", new hebsuperobject(6,2,22,"וילכו ויבאו ההרה וישבו שם שלשת ימים עד שבו הרדפים ויבקשו הרדפים בכל הדרך ולא מצאו׃"));
hebsuperobject.biblemap.put("b6_2_23", new hebsuperobject(6,2,23,"וישבו שני האנשים וירדו מההר ויעברו ויבאו אל יהושע בן נון ויספרו לו את כל המצאות אותם׃"));
hebsuperobject.biblemap.put("b6_2_24", new hebsuperobject(6,2,24,"ויאמרו אל יהושע כי נתן יהוה בידנו את כל הארץ וגם נמגו כל ישבי הארץ מפנינו׃"));
hebsuperobject.biblemap.put("b6_3_1", new hebsuperobject(6,3,1,"וישכם יהושע בבקר ויסעו מהשטים ויבאו עד הירדן הוא וכל בני ישראל וילנו שם טרם יעברו׃"));
hebsuperobject.biblemap.put("b6_3_2", new hebsuperobject(6,3,2,"ויהי מקצה שלשת ימים ויעברו השטרים בקרב המחנה׃"));
hebsuperobject.biblemap.put("b6_3_3", new hebsuperobject(6,3,3,"ויצוו את העם לאמר כראותכם את ארון ברית יהוה אלהיכם והכהנים הלוים נשאים אתו ואתם תסעו ממקומכם והלכתם אחריו׃"));
hebsuperobject.biblemap.put("b6_3_4", new hebsuperobject(6,3,4,"אך רחוק יהיה ביניכם ובינו כאלפים אמה במדה אל תקרבו אליו למען אשר תדעו את הדרך אשר תלכו בה כי לא עברתם בדרך מתמול שלשום׃"));
hebsuperobject.biblemap.put("b6_3_5", new hebsuperobject(6,3,5,"ויאמר יהושע אל העם התקדשו כי מחר יעשה יהוה בקרבכם נפלאות׃"));
hebsuperobject.biblemap.put("b6_3_6", new hebsuperobject(6,3,6,"ויאמר יהושע אל הכהנים לאמר שאו את ארון הברית ועברו לפני העם וישאו את ארון הברית וילכו לפני העם׃"));
hebsuperobject.biblemap.put("b6_3_7", new hebsuperobject(6,3,7,"ויאמר יהוה אל יהושע היום הזה אחל גדלך בעיני כל ישראל אשר ידעון כי כאשר הייתי עם משה אהיה עמך׃"));
hebsuperobject.biblemap.put("b6_3_8", new hebsuperobject(6,3,8,"ואתה תצוה את הכהנים נשאי ארון הברית לאמר כבאכם עד קצה מי הירדן בירדן תעמדו׃"));
hebsuperobject.biblemap.put("b6_3_9", new hebsuperobject(6,3,9,"ויאמר יהושע אל בני ישראל גשו הנה ושמעו את דברי יהוה אלהיכם׃"));
hebsuperobject.biblemap.put("b6_3_10", new hebsuperobject(6,3,10,"ויאמר יהושע בזאת תדעון כי אל חי בקרבכם והורש יוריש מפניכם את הכנעני ואת החתי ואת החוי ואת הפרזי ואת הגרגשי והאמרי והיבוסי׃"));
hebsuperobject.biblemap.put("b6_3_11", new hebsuperobject(6,3,11,"הנה ארון הברית אדון כל הארץ עבר לפניכם בירדן׃"));
hebsuperobject.biblemap.put("b6_3_12", new hebsuperobject(6,3,12,"ועתה קחו לכם שני עשר איש משבטי ישראל איש אחד איש אחד לשבט׃"));
hebsuperobject.biblemap.put("b6_3_13", new hebsuperobject(6,3,13,"והיה כנוח כפות רגלי הכהנים נשאי ארון יהוה אדון כל הארץ במי הירדן מי הירדן יכרתון המים הירדים מלמעלה ויעמדו נד אחד׃"));
hebsuperobject.biblemap.put("b6_3_14", new hebsuperobject(6,3,14,"ויהי בנסע העם מאהליהם לעבר את הירדן והכהנים נשאי הארון הברית לפני העם׃"));
hebsuperobject.biblemap.put("b6_3_15", new hebsuperobject(6,3,15,"וכבוא נשאי הארון עד הירדן ורגלי הכהנים נשאי הארון נטבלו בקצה המים והירדן מלא על כל גדותיו כל ימי קציר׃"));
hebsuperobject.biblemap.put("b6_3_16", new hebsuperobject(6,3,16,"ויעמדו המים הירדים מלמעלה קמו נד אחד הרחק מאד באדם העיר אשר מצד צרתן והירדים על ים הערבה ים המלח תמו נכרתו והעם עברו נגד יריחו׃"));
hebsuperobject.biblemap.put("b6_3_17", new hebsuperobject(6,3,17,"ויעמדו הכהנים נשאי הארון ברית יהוה בחרבה בתוך הירדן הכן וכל ישראל עברים בחרבה עד אשר תמו כל הגוי לעבר את הירדן׃"));
hebsuperobject.biblemap.put("b6_4_1", new hebsuperobject(6,4,1,"ויהי כאשר תמו כל הגוי לעבור את הירדן ויאמר יהוה אל יהושע לאמר׃"));
hebsuperobject.biblemap.put("b6_4_2", new hebsuperobject(6,4,2,"קחו לכם מן העם שנים עשר אנשים איש אחד איש אחד משבט׃"));
hebsuperobject.biblemap.put("b6_4_3", new hebsuperobject(6,4,3,"וצוו אותם לאמר שאו לכם מזה מתוך הירדן ממצב רגלי הכהנים הכין שתים עשרה אבנים והעברתם אותם עמכם והנחתם אותם במלון אשר תלינו בו הלילה׃"));
hebsuperobject.biblemap.put("b6_4_4", new hebsuperobject(6,4,4,"ויקרא יהושע אל שנים העשר איש אשר הכין מבני ישראל איש אחד איש אחד משבט׃"));
hebsuperobject.biblemap.put("b6_4_5", new hebsuperobject(6,4,5,"ויאמר להם יהושע עברו לפני ארון יהוה אלהיכם אל תוך הירדן והרימו לכם איש אבן אחת על שכמו למספר שבטי בני ישראל׃"));
hebsuperobject.biblemap.put("b6_4_6", new hebsuperobject(6,4,6,"למען תהיה זאת אות בקרבכם כי ישאלון בניכם מחר לאמר מה האבנים האלה לכם׃"));
hebsuperobject.biblemap.put("b6_4_7", new hebsuperobject(6,4,7,"ואמרתם להם אשר נכרתו מימי הירדן מפני ארון ברית יהוה בעברו בירדן נכרתו מי הירדן והיו האבנים האלה לזכרון לבני ישראל עד עולם׃"));
hebsuperobject.biblemap.put("b6_4_8", new hebsuperobject(6,4,8,"ויעשו כן בני ישראל כאשר צוה יהושע וישאו שתי עשרה אבנים מתוך הירדן כאשר דבר יהוה אל יהושע למספר שבטי בני ישראל ויעברום עמם אל המלון וינחום שם׃"));
hebsuperobject.biblemap.put("b6_4_9", new hebsuperobject(6,4,9,"ושתים עשרה אבנים הקים יהושע בתוך הירדן תחת מצב רגלי הכהנים נשאי ארון הברית ויהיו שם עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_4_10", new hebsuperobject(6,4,10,"והכהנים נשאי הארון עמדים בתוך הירדן עד תם כל הדבר אשר צוה יהוה את יהושע לדבר אל העם ככל אשר צוה משה את יהושע וימהרו העם ויעברו׃"));
hebsuperobject.biblemap.put("b6_4_11", new hebsuperobject(6,4,11,"ויהי כאשר תם כל העם לעבור ויעבר ארון יהוה והכהנים לפני העם׃"));
hebsuperobject.biblemap.put("b6_4_12", new hebsuperobject(6,4,12,"ויעברו בני ראובן ובני גד וחצי שבט המנשה חמשים לפני בני ישראל כאשר דבר אליהם משה׃"));
hebsuperobject.biblemap.put("b6_4_13", new hebsuperobject(6,4,13,"כארבעים אלף חלוצי הצבא עברו לפני יהוה למלחמה אל ערבות יריחו׃"));
hebsuperobject.biblemap.put("b6_4_14", new hebsuperobject(6,4,14,"ביום ההוא גדל יהוה את יהושע בעיני כל ישראל ויראו אתו כאשר יראו את משה כל ימי חייו׃"));
hebsuperobject.biblemap.put("b6_4_15", new hebsuperobject(6,4,15,"ויאמר יהוה אל יהושע לאמר׃"));
hebsuperobject.biblemap.put("b6_4_16", new hebsuperobject(6,4,16,"צוה את הכהנים נשאי ארון העדות ויעלו מן הירדן׃"));
hebsuperobject.biblemap.put("b6_4_17", new hebsuperobject(6,4,17,"ויצו יהושע את הכהנים לאמר עלו מן הירדן׃"));
hebsuperobject.biblemap.put("b6_4_18", new hebsuperobject(6,4,18,"ויהי בעלות הכהנים נשאי ארון ברית יהוה מתוך הירדן נתקו כפות רגלי הכהנים אל החרבה וישבו מי הירדן למקומם וילכו כתמול שלשום על כל גדותיו׃"));
hebsuperobject.biblemap.put("b6_4_19", new hebsuperobject(6,4,19,"והעם עלו מן הירדן בעשור לחדש הראשון ויחנו בגלגל בקצה מזרח יריחו׃"));
hebsuperobject.biblemap.put("b6_4_20", new hebsuperobject(6,4,20,"ואת שתים עשרה האבנים האלה אשר לקחו מן הירדן הקים יהושע בגלגל׃"));
hebsuperobject.biblemap.put("b6_4_21", new hebsuperobject(6,4,21,"ויאמר אל בני ישראל לאמר אשר ישאלון בניכם מחר את אבותם לאמר מה האבנים האלה׃"));
hebsuperobject.biblemap.put("b6_4_22", new hebsuperobject(6,4,22,"והודעתם את בניכם לאמר ביבשה עבר ישראל את הירדן הזה׃"));
hebsuperobject.biblemap.put("b6_4_23", new hebsuperobject(6,4,23,"אשר הוביש יהוה אלהיכם את מי הירדן מפניכם עד עברכם כאשר עשה יהוה אלהיכם לים סוף אשר הוביש מפנינו עד עברנו׃"));
hebsuperobject.biblemap.put("b6_4_24", new hebsuperobject(6,4,24,"למען דעת כל עמי הארץ את יד יהוה כי חזקה היא למען יראתם את יהוה אלהיכם כל הימים׃"));
hebsuperobject.biblemap.put("b6_5_1", new hebsuperobject(6,5,1,"ויהי כשמע כל מלכי האמרי אשר בעבר הירדן ימה וכל מלכי הכנעני אשר על הים את אשר הוביש יהוה את מי הירדן מפני בני ישראל עד עברנו וימס לבבם ולא היה בם עוד רוח מפני בני ישראל׃"));
hebsuperobject.biblemap.put("b6_5_2", new hebsuperobject(6,5,2,"בעת ההיא אמר יהוה אל יהושע עשה לך חרבות צרים ושוב מל את בני ישראל שנית׃"));
hebsuperobject.biblemap.put("b6_5_3", new hebsuperobject(6,5,3,"ויעש לו יהושע חרבות צרים וימל את בני ישראל אל גבעת הערלות׃"));
hebsuperobject.biblemap.put("b6_5_4", new hebsuperobject(6,5,4,"וזה הדבר אשר מל יהושע כל העם היצא ממצרים הזכרים כל אנשי המלחמה מתו במדבר בדרך בצאתם ממצרים׃"));
hebsuperobject.biblemap.put("b6_5_5", new hebsuperobject(6,5,5,"כי מלים היו כל העם היצאים וכל העם הילדים במדבר בדרך בצאתם ממצרים לא מלו׃"));
hebsuperobject.biblemap.put("b6_5_6", new hebsuperobject(6,5,6,"כי ארבעים שנה הלכו בני ישראל במדבר עד תם כל הגוי אנשי המלחמה היצאים ממצרים אשר לא שמעו בקול יהוה אשר נשבע יהוה להם לבלתי הראותם את הארץ אשר נשבע יהוה לאבותם לתת לנו ארץ זבת חלב ודבש׃"));
hebsuperobject.biblemap.put("b6_5_7", new hebsuperobject(6,5,7,"ואת בניהם הקים תחתם אתם מל יהושע כי ערלים היו כי לא מלו אותם בדרך׃"));
hebsuperobject.biblemap.put("b6_5_8", new hebsuperobject(6,5,8,"ויהי כאשר תמו כל הגוי להמול וישבו תחתם במחנה עד חיותם׃"));
hebsuperobject.biblemap.put("b6_5_9", new hebsuperobject(6,5,9,"ויאמר יהוה אל יהושע היום גלותי את חרפת מצרים מעליכם ויקרא שם המקום ההוא גלגל עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_5_10", new hebsuperobject(6,5,10,"ויחנו בני ישראל בגלגל ויעשו את הפסח בארבעה עשר יום לחדש בערב בערבות יריחו׃"));
hebsuperobject.biblemap.put("b6_5_11", new hebsuperobject(6,5,11,"ויאכלו מעבור הארץ ממחרת הפסח מצות וקלוי בעצם היום הזה׃"));
hebsuperobject.biblemap.put("b6_5_12", new hebsuperobject(6,5,12,"וישבת המן ממחרת באכלם מעבור הארץ ולא היה עוד לבני ישראל מן ויאכלו מתבואת ארץ כנען בשנה ההיא׃"));
hebsuperobject.biblemap.put("b6_5_13", new hebsuperobject(6,5,13,"ויהי בהיות יהושע ביריחו וישא עיניו וירא והנה איש עמד לנגדו וחרבו שלופה בידו וילך יהושע אליו ויאמר לו הלנו אתה אם לצרינו׃"));
hebsuperobject.biblemap.put("b6_5_14", new hebsuperobject(6,5,14,"ויאמר לא כי אני שר צבא יהוה עתה באתי ויפל יהושע אל פניו ארצה וישתחו ויאמר לו מה אדני מדבר אל עבדו׃"));
hebsuperobject.biblemap.put("b6_5_15", new hebsuperobject(6,5,15,"ויאמר שר צבא יהוה אל יהושע של נעלך מעל רגלך כי המקום אשר אתה עמד עליו קדש הוא ויעש יהושע כן׃"));
hebsuperobject.biblemap.put("b6_6_1", new hebsuperobject(6,6,1,"ויריחו סגרת ומסגרת מפני בני ישראל אין יוצא ואין בא׃"));
hebsuperobject.biblemap.put("b6_6_2", new hebsuperobject(6,6,2,"ויאמר יהוה אל יהושע ראה נתתי בידך את יריחו ואת מלכה גבורי החיל׃"));
hebsuperobject.biblemap.put("b6_6_3", new hebsuperobject(6,6,3,"וסבתם את העיר כל אנשי המלחמה הקיף את העיר פעם אחת כה תעשה ששת ימים׃"));
hebsuperobject.biblemap.put("b6_6_4", new hebsuperobject(6,6,4,"ושבעה כהנים ישאו שבעה שופרות היובלים לפני הארון וביום השביעי תסבו את העיר שבע פעמים והכהנים יתקעו בשופרות׃"));
hebsuperobject.biblemap.put("b6_6_5", new hebsuperobject(6,6,5,"והיה במשך בקרן היובל בשמעכם את קול השופר יריעו כל העם תרועה גדולה ונפלה חומת העיר תחתיה ועלו העם איש נגדו׃"));
hebsuperobject.biblemap.put("b6_6_6", new hebsuperobject(6,6,6,"ויקרא יהושע בן נון אל הכהנים ויאמר אלהם שאו את ארון הברית ושבעה כהנים ישאו שבעה שופרות יובלים לפני ארון יהוה׃"));
hebsuperobject.biblemap.put("b6_6_7", new hebsuperobject(6,6,7,"ויאמרו אל העם עברו וסבו את העיר והחלוץ יעבר לפני ארון יהוה׃"));
hebsuperobject.biblemap.put("b6_6_8", new hebsuperobject(6,6,8,"ויהי כאמר יהושע אל העם ושבעה הכהנים נשאים שבעה שופרות היובלים לפני יהוה עברו ותקעו בשופרות וארון ברית יהוה הלך אחריהם׃"));
hebsuperobject.biblemap.put("b6_6_9", new hebsuperobject(6,6,9,"והחלוץ הלך לפני הכהנים תקעו השופרות והמאסף הלך אחרי הארון הלוך ותקוע בשופרות׃"));
hebsuperobject.biblemap.put("b6_6_10", new hebsuperobject(6,6,10,"ואת העם צוה יהושע לאמר לא תריעו ולא תשמיעו את קולכם ולא יצא מפיכם דבר עד יום אמרי אליכם הריעו והריעתם׃"));
hebsuperobject.biblemap.put("b6_6_11", new hebsuperobject(6,6,11,"ויסב ארון יהוה את העיר הקף פעם אחת ויבאו המחנה וילינו במחנה׃"));
hebsuperobject.biblemap.put("b6_6_12", new hebsuperobject(6,6,12,"וישכם יהושע בבקר וישאו הכהנים את ארון יהוה׃"));
hebsuperobject.biblemap.put("b6_6_13", new hebsuperobject(6,6,13,"ושבעה הכהנים נשאים שבעה שופרות היבלים לפני ארון יהוה הלכים הלוך ותקעו בשופרות והחלוץ הלך לפניהם והמאסף הלך אחרי ארון יהוה הולך ותקוע בשופרות׃"));
hebsuperobject.biblemap.put("b6_6_14", new hebsuperobject(6,6,14,"ויסבו את העיר ביום השני פעם אחת וישבו המחנה כה עשו ששת ימים׃"));
hebsuperobject.biblemap.put("b6_6_15", new hebsuperobject(6,6,15,"ויהי ביום השביעי וישכמו כעלות השחר ויסבו את העיר כמשפט הזה שבע פעמים רק ביום ההוא סבבו את העיר שבע פעמים׃"));
hebsuperobject.biblemap.put("b6_6_16", new hebsuperobject(6,6,16,"ויהי בפעם השביעית תקעו הכהנים בשופרות ויאמר יהושע אל העם הריעו כי נתן יהוה לכם את העיר׃"));
hebsuperobject.biblemap.put("b6_6_17", new hebsuperobject(6,6,17,"והיתה העיר חרם היא וכל אשר בה ליהוה רק רחב הזונה תחיה היא וכל אשר אתה בבית כי החבאתה את המלאכים אשר שלחנו׃"));
hebsuperobject.biblemap.put("b6_6_18", new hebsuperobject(6,6,18,"ורק אתם שמרו מן החרם פן תחרימו ולקחתם מן החרם ושמתם את מחנה ישראל לחרם ועכרתם אותו׃"));
hebsuperobject.biblemap.put("b6_6_19", new hebsuperobject(6,6,19,"וכל כסף וזהב וכלי נחשת וברזל קדש הוא ליהוה אוצר יהוה יבוא׃"));
hebsuperobject.biblemap.put("b6_6_20", new hebsuperobject(6,6,20,"וירע העם ויתקעו בשפרות ויהי כשמע העם את קול השופר ויריעו העם תרועה גדולה ותפל החומה תחתיה ויעל העם העירה איש נגדו וילכדו את העיר׃"));
hebsuperobject.biblemap.put("b6_6_21", new hebsuperobject(6,6,21,"ויחרימו את כל אשר בעיר מאיש ועד אשה מנער ועד זקן ועד שור ושה וחמור לפי חרב׃"));
hebsuperobject.biblemap.put("b6_6_22", new hebsuperobject(6,6,22,"ולשנים האנשים המרגלים את הארץ אמר יהושע באו בית האשה הזונה והוציאו משם את האשה ואת כל אשר לה כאשר נשבעתם לה׃"));
hebsuperobject.biblemap.put("b6_6_23", new hebsuperobject(6,6,23,"ויבאו הנערים המרגלים ויציאו את רחב ואת אביה ואת אמה ואת אחיה ואת כל אשר לה ואת כל משפחותיה הוציאו ויניחום מחוץ למחנה ישראל׃"));
hebsuperobject.biblemap.put("b6_6_24", new hebsuperobject(6,6,24,"והעיר שרפו באש וכל אשר בה רק הכסף והזהב וכלי הנחשת והברזל נתנו אוצר בית יהוה׃"));
hebsuperobject.biblemap.put("b6_6_25", new hebsuperobject(6,6,25,"ואת רחב הזונה ואת בית אביה ואת כל אשר לה החיה יהושע ותשב בקרב ישראל עד היום הזה כי החביאה את המלאכים אשר שלח יהושע לרגל את יריחו׃"));
hebsuperobject.biblemap.put("b6_6_26", new hebsuperobject(6,6,26,"וישבע יהושע בעת ההיא לאמר ארור האיש לפני יהוה אשר יקום ובנה את העיר הזאת את יריחו בבכרו ייסדנה ובצעירו יציב דלתיה׃"));
hebsuperobject.biblemap.put("b6_6_27", new hebsuperobject(6,6,27,"ויהי יהוה את יהושע ויהי שמעו בכל הארץ׃"));
hebsuperobject.biblemap.put("b6_7_1", new hebsuperobject(6,7,1,"וימעלו בני ישראל מעל בחרם ויקח עכן בן כרמי בן זבדי בן זרח למטה יהודה מן החרם ויחר אף יהוה בבני ישראל׃"));
hebsuperobject.biblemap.put("b6_7_2", new hebsuperobject(6,7,2,"וישלח יהושע אנשים מיריחו העי אשר עם בית און מקדם לבית אל ויאמר אליהם לאמר עלו ורגלו את הארץ ויעלו האנשים וירגלו את העי׃"));
hebsuperobject.biblemap.put("b6_7_3", new hebsuperobject(6,7,3,"וישבו אל יהושע ויאמרו אליו אל יעל כל העם כאלפים איש או כשלשת אלפים איש יעלו ויכו את העי אל תיגע שמה את כל העם כי מעט המה׃"));
hebsuperobject.biblemap.put("b6_7_4", new hebsuperobject(6,7,4,"ויעלו מן העם שמה כשלשת אלפים איש וינסו לפני אנשי העי׃"));
hebsuperobject.biblemap.put("b6_7_5", new hebsuperobject(6,7,5,"ויכו מהם אנשי העי כשלשים וששה איש וירדפום לפני השער עד השברים ויכום במורד וימס לבב העם ויהי למים׃"));
hebsuperobject.biblemap.put("b6_7_6", new hebsuperobject(6,7,6,"ויקרע יהושע שמלתיו ויפל על פניו ארצה לפני ארון יהוה עד הערב הוא וזקני ישראל ויעלו עפר על ראשם׃"));
hebsuperobject.biblemap.put("b6_7_7", new hebsuperobject(6,7,7,"ויאמר יהושע אהה אדני יהוה למה העברת העביר את העם הזה את הירדן לתת אתנו ביד האמרי להאבידנו ולו הואלנו ונשב בעבר הירדן׃"));
hebsuperobject.biblemap.put("b6_7_8", new hebsuperobject(6,7,8,"בי אדני מה אמר אחרי אשר הפך ישראל ערף לפני איביו׃"));
hebsuperobject.biblemap.put("b6_7_9", new hebsuperobject(6,7,9,"וישמעו הכנעני וכל ישבי הארץ ונסבו עלינו והכריתו את שמנו מן הארץ ומה תעשה לשמך הגדול׃"));
hebsuperobject.biblemap.put("b6_7_10", new hebsuperobject(6,7,10,"ויאמר יהוה אל יהושע קם לך למה זה אתה נפל על פניך׃"));
hebsuperobject.biblemap.put("b6_7_11", new hebsuperobject(6,7,11,"חטא ישראל וגם עברו את בריתי אשר צויתי אותם וגם לקחו מן החרם וגם גנבו וגם כחשו וגם שמו בכליהם׃"));
hebsuperobject.biblemap.put("b6_7_12", new hebsuperobject(6,7,12,"ולא יכלו בני ישראל לקום לפני איביהם ערף יפנו לפני איביהם כי היו לחרם לא אוסיף להיות עמכם אם לא תשמידו החרם מקרבכם׃"));
hebsuperobject.biblemap.put("b6_7_13", new hebsuperobject(6,7,13,"קם קדש את העם ואמרת התקדשו למחר כי כה אמר יהוה אלהי ישראל חרם בקרבך ישראל לא תוכל לקום לפני איביך עד הסירכם החרם מקרבכם׃"));
hebsuperobject.biblemap.put("b6_7_14", new hebsuperobject(6,7,14,"ונקרבתם בבקר לשבטיכם והיה השבט אשר ילכדנו יהוה יקרב למשפחות והמשפחה אשר ילכדנה יהוה תקרב לבתים והבית אשר ילכדנו יהוה יקרב לגברים׃"));
hebsuperobject.biblemap.put("b6_7_15", new hebsuperobject(6,7,15,"והיה הנלכד בחרם ישרף באש אתו ואת כל אשר לו כי עבר את ברית יהוה וכי עשה נבלה בישראל׃"));
hebsuperobject.biblemap.put("b6_7_16", new hebsuperobject(6,7,16,"וישכם יהושע בבקר ויקרב את ישראל לשבטיו וילכד שבט יהודה׃"));
hebsuperobject.biblemap.put("b6_7_17", new hebsuperobject(6,7,17,"ויקרב את משפחת יהודה וילכד את משפחת הזרחי ויקרב את משפחת הזרחי לגברים וילכד זבדי׃"));
hebsuperobject.biblemap.put("b6_7_18", new hebsuperobject(6,7,18,"ויקרב את ביתו לגברים וילכד עכן בן כרמי בן זבדי בן זרח למטה יהודה׃"));
hebsuperobject.biblemap.put("b6_7_19", new hebsuperobject(6,7,19,"ויאמר יהושע אל עכן בני שים נא כבוד ליהוה אלהי ישראל ותן לו תודה והגד נא לי מה עשית אל תכחד ממני׃"));
hebsuperobject.biblemap.put("b6_7_20", new hebsuperobject(6,7,20,"ויען עכן את יהושע ויאמר אמנה אנכי חטאתי ליהוה אלהי ישראל וכזאת וכזאת עשיתי׃"));
hebsuperobject.biblemap.put("b6_7_21", new hebsuperobject(6,7,21,"ואראה בשלל אדרת שנער אחת טובה ומאתים שקלים כסף ולשון זהב אחד חמשים שקלים משקלו ואחמדם ואקחם והנם טמונים בארץ בתוך האהלי והכסף תחתיה׃"));
hebsuperobject.biblemap.put("b6_7_22", new hebsuperobject(6,7,22,"וישלח יהושע מלאכים וירצו האהלה והנה טמונה באהלו והכסף תחתיה׃"));
hebsuperobject.biblemap.put("b6_7_23", new hebsuperobject(6,7,23,"ויקחום מתוך האהל ויבאום אל יהושע ואל כל בני ישראל ויצקם לפני יהוה׃"));
hebsuperobject.biblemap.put("b6_7_24", new hebsuperobject(6,7,24,"ויקח יהושע את עכן בן זרח ואת הכסף ואת האדרת ואת לשון הזהב ואת בניו ואת בנתיו ואת שורו ואת חמרו ואת צאנו ואת אהלו ואת כל אשר לו וכל ישראל עמו ויעלו אתם עמק עכור׃"));
hebsuperobject.biblemap.put("b6_7_25", new hebsuperobject(6,7,25,"ויאמר יהושע מה עכרתנו יעכרך יהוה ביום הזה וירגמו אתו כל ישראל אבן וישרפו אתם באש ויסקלו אתם באבנים׃"));
hebsuperobject.biblemap.put("b6_7_26", new hebsuperobject(6,7,26,"ויקימו עליו גל אבנים גדול עד היום הזה וישב יהוה מחרון אפו על כן קרא שם המקום ההוא עמק עכור עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_8_1", new hebsuperobject(6,8,1,"ויאמר יהוה אל יהושע אל תירא ואל תחת קח עמך את כל עם המלחמה וקום עלה העי ראה נתתי בידך את מלך העי ואת עמו ואת עירו ואת ארצו׃"));
hebsuperobject.biblemap.put("b6_8_2", new hebsuperobject(6,8,2,"ועשית לעי ולמלכה כאשר עשית ליריחו ולמלכה רק שללה ובהמתה תבזו לכם שים לך ארב לעיר מאחריה׃"));
hebsuperobject.biblemap.put("b6_8_3", new hebsuperobject(6,8,3,"ויקם יהושע וכל עם המלחמה לעלות העי ויבחר יהושע שלשים אלף איש גבורי החיל וישלחם לילה׃"));
hebsuperobject.biblemap.put("b6_8_4", new hebsuperobject(6,8,4,"ויצו אתם לאמר ראו אתם ארבים לעיר מאחרי העיר אל תרחיקו מן העיר מאד והייתם כלכם נכנים׃"));
hebsuperobject.biblemap.put("b6_8_5", new hebsuperobject(6,8,5,"ואני וכל העם אשר אתי נקרב אל העיר והיה כי יצאו לקראתנו כאשר בראשנה ונסנו לפניהם׃"));
hebsuperobject.biblemap.put("b6_8_6", new hebsuperobject(6,8,6,"ויצאו אחרינו עד התיקנו אותם מן העיר כי יאמרו נסים לפנינו כאשר בראשנה ונסנו לפניהם׃"));
hebsuperobject.biblemap.put("b6_8_7", new hebsuperobject(6,8,7,"ואתם תקמו מהאורב והורשתם את העיר ונתנה יהוה אלהיכם בידכם׃"));
hebsuperobject.biblemap.put("b6_8_8", new hebsuperobject(6,8,8,"והיה כתפשכם את העיר תציתו את העיר באש כדבר יהוה תעשו ראו צויתי אתכם׃"));
hebsuperobject.biblemap.put("b6_8_9", new hebsuperobject(6,8,9,"וישלחם יהושע וילכו אל המארב וישבו בין בית אל ובין העי מים לעי וילן יהושע בלילה ההוא בתוך העם׃"));
hebsuperobject.biblemap.put("b6_8_10", new hebsuperobject(6,8,10,"וישכם יהושע בבקר ויפקד את העם ויעל הוא וזקני ישראל לפני העם העי׃"));
hebsuperobject.biblemap.put("b6_8_11", new hebsuperobject(6,8,11,"וכל העם המלחמה אשר אתו עלו ויגשו ויבאו נגד העיר ויחנו מצפון לעי והגי בינו ובין העי׃"));
hebsuperobject.biblemap.put("b6_8_12", new hebsuperobject(6,8,12,"ויקח כחמשת אלפים איש וישם אותם ארב בין בית אל ובין העי מים לעיר׃"));
hebsuperobject.biblemap.put("b6_8_13", new hebsuperobject(6,8,13,"וישימו העם את כל המחנה אשר מצפון לעיר ואת עקבו מים לעיר וילך יהושע בלילה ההוא בתוך העמק׃"));
hebsuperobject.biblemap.put("b6_8_14", new hebsuperobject(6,8,14,"ויהי כראות מלך העי וימהרו וישכימו ויצאו אנשי העיר לקראת ישראל למלחמה הוא וכל עמו למועד לפני הערבה והוא לא ידע כי ארב לו מאחרי העיר׃"));
hebsuperobject.biblemap.put("b6_8_15", new hebsuperobject(6,8,15,"וינגעו יהושע וכל ישראל לפניהם וינסו דרך המדבר׃"));
hebsuperobject.biblemap.put("b6_8_16", new hebsuperobject(6,8,16,"ויזעקו כל העם אשר בעיר לרדף אחריהם וירדפו אחרי יהושע וינתקו מן העיר׃"));
hebsuperobject.biblemap.put("b6_8_17", new hebsuperobject(6,8,17,"ולא נשאר איש בעי ובית אל אשר לא יצאו אחרי ישראל ויעזבו את העיר פתוחה וירדפו אחרי ישראל׃"));
hebsuperobject.biblemap.put("b6_8_18", new hebsuperobject(6,8,18,"ויאמר יהוה אל יהושע נטה בכידון אשר בידך אל העי כי בידך אתננה ויט יהושע בכידון אשר בידו אל העיר׃"));
hebsuperobject.biblemap.put("b6_8_19", new hebsuperobject(6,8,19,"והאורב קם מהרה ממקומו וירוצו כנטות ידו ויבאו העיר וילכדוה וימהרו ויציתו את העיר באש׃"));
hebsuperobject.biblemap.put("b6_8_20", new hebsuperobject(6,8,20,"ויפנו אנשי העי אחריהם ויראו והנה עלה עשן העיר השמימה ולא היה בהם ידים לנוס הנה והנה והעם הנס המדבר נהפך אל הרודף׃"));
hebsuperobject.biblemap.put("b6_8_21", new hebsuperobject(6,8,21,"ויהושע וכל ישראל ראו כי לכד הארב את העיר וכי עלה עשן העיר וישבו ויכו את אנשי העי׃"));
hebsuperobject.biblemap.put("b6_8_22", new hebsuperobject(6,8,22,"ואלה יצאו מן העיר לקראתם ויהיו לישראל בתוך אלה מזה ואלה מזה ויכו אותם עד בלתי השאיר לו שריד ופליט׃"));
hebsuperobject.biblemap.put("b6_8_23", new hebsuperobject(6,8,23,"ואת מלך העי תפשו חי ויקרבו אתו אל יהושע׃"));
hebsuperobject.biblemap.put("b6_8_24", new hebsuperobject(6,8,24,"ויהי ככלות ישראל להרג את כל ישבי העי בשדה במדבר אשר רדפום בו ויפלו כלם לפי חרב עד תמם וישבו כל ישראל העי ויכו אתה לפי חרב׃"));
hebsuperobject.biblemap.put("b6_8_25", new hebsuperobject(6,8,25,"ויהי כל הנפלים ביום ההוא מאיש ועד אשה שנים עשר אלף כל אנשי העי׃"));
hebsuperobject.biblemap.put("b6_8_26", new hebsuperobject(6,8,26,"ויהושע לא השיב ידו אשר נטה בכידון עד אשר החרים את כל ישבי העי׃"));
hebsuperobject.biblemap.put("b6_8_27", new hebsuperobject(6,8,27,"רק הבהמה ושלל העיר ההיא בזזו להם ישראל כדבר יהוה אשר צוה את יהושע׃"));
hebsuperobject.biblemap.put("b6_8_28", new hebsuperobject(6,8,28,"וישרף יהושע את העי וישימה תל עולם שממה עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_8_29", new hebsuperobject(6,8,29,"ואת מלך העי תלה על העץ עד עת הערב וכבוא השמש צוה יהושע וירידו את נבלתו מן העץ וישליכו אותה אל פתח שער העיר ויקימו עליו גל אבנים גדול עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_8_30", new hebsuperobject(6,8,30,"אז יבנה יהושע מזבח ליהוה אלהי ישראל בהר עיבל׃"));
hebsuperobject.biblemap.put("b6_8_31", new hebsuperobject(6,8,31,"כאשר צוה משה עבד יהוה את בני ישראל ככתוב בספר תורת משה מזבח אבנים שלמות אשר לא הניף עליהן ברזל ויעלו עליו עלות ליהוה ויזבחו שלמים׃"));
hebsuperobject.biblemap.put("b6_8_32", new hebsuperobject(6,8,32,"ויכתב שם על האבנים את משנה תורת משה אשר כתב לפני בני ישראל׃"));
hebsuperobject.biblemap.put("b6_8_33", new hebsuperobject(6,8,33,"וכל ישראל וזקניו ושטרים ושפטיו עמדים מזה ומזה לארון נגד הכהנים הלוים נשאי ארון ברית יהוה כגר כאזרח חציו אל מול הר גרזים והחציו אל מול הר עיבל כאשר צוה משה עבד יהוה לברך את העם ישראל בראשנה׃"));
hebsuperobject.biblemap.put("b6_8_34", new hebsuperobject(6,8,34,"ואחרי כן קרא את כל דברי התורה הברכה והקללה ככל הכתוב בספר התורה׃"));
hebsuperobject.biblemap.put("b6_8_35", new hebsuperobject(6,8,35,"לא היה דבר מכל אשר צוה משה אשר לא קרא יהושע נגד כל קהל ישראל והנשים והטף והגר ההלך בקרבם׃"));
hebsuperobject.biblemap.put("b6_9_1", new hebsuperobject(6,9,1,"ויהי כשמע כל המלכים אשר בעבר הירדן בהר ובשפלה ובכל חוף הים הגדול אל מול הלבנון החתי והאמרי הכנעני הפרזי החוי והיבוסי׃"));
hebsuperobject.biblemap.put("b6_9_2", new hebsuperobject(6,9,2,"ויתקבצו יחדו להלחם עם יהושע ועם ישראל פה אחד׃"));
hebsuperobject.biblemap.put("b6_9_3", new hebsuperobject(6,9,3,"וישבי גבעון שמעו את אשר עשה יהושע ליריחו ולעי׃"));
hebsuperobject.biblemap.put("b6_9_4", new hebsuperobject(6,9,4,"ויעשו גם המה בערמה וילכו ויצטירו ויקחו שקים בלים לחמוריהם ונאדות יין בלים ומבקעים ומצררים׃"));
hebsuperobject.biblemap.put("b6_9_5", new hebsuperobject(6,9,5,"ונעלות בלות ומטלאות ברגליהם ושלמות בלות עליהם וכל לחם צידם יבש היה נקדים׃"));
hebsuperobject.biblemap.put("b6_9_6", new hebsuperobject(6,9,6,"וילכו אל יהושע אל המחנה הגלגל ויאמרו אליו ואל איש ישראל מארץ רחוקה באנו ועתה כרתו לנו ברית׃"));
hebsuperobject.biblemap.put("b6_9_7", new hebsuperobject(6,9,7,"ויאמרו איש ישראל אל החוי אולי בקרבי אתה יושב ואיך אכרות לך ברית׃"));
hebsuperobject.biblemap.put("b6_9_8", new hebsuperobject(6,9,8,"ויאמרו אל יהושע עבדיך אנחנו ויאמר אלהם יהושע מי אתם ומאין תבאו׃"));
hebsuperobject.biblemap.put("b6_9_9", new hebsuperobject(6,9,9,"ויאמרו אליו מארץ רחוקה מאד באו עבדיך לשם יהוה אלהיך כי שמענו שמעו ואת כל אשר עשה במצרים׃"));
hebsuperobject.biblemap.put("b6_9_10", new hebsuperobject(6,9,10,"ואת כל אשר עשה לשני מלכי האמרי אשר בעבר הירדן לסיחון מלך חשבון ולעוג מלך הבשן אשר בעשתרות׃"));
hebsuperobject.biblemap.put("b6_9_11", new hebsuperobject(6,9,11,"ויאמרו אלינו זקינינו וכל ישבי ארצנו לאמר קחו בידכם צידה לדרך ולכו לקראתם ואמרתם אליהם עבדיכם אנחנו ועתה כרתו לנו ברית׃"));
hebsuperobject.biblemap.put("b6_9_12", new hebsuperobject(6,9,12,"זה לחמנו חם הצטידנו אתו מבתינו ביום צאתנו ללכת אליכם ועתה הנה יבש והיה נקדים׃"));
hebsuperobject.biblemap.put("b6_9_13", new hebsuperobject(6,9,13,"ואלה נאדות היין אשר מלאנו חדשים והנה התבקעו ואלה שלמותינו ונעלינו בלו מרב הדרך מאד׃"));
hebsuperobject.biblemap.put("b6_9_14", new hebsuperobject(6,9,14,"ויקחו האנשים מצידם ואת פי יהוה לא שאלו׃"));
hebsuperobject.biblemap.put("b6_9_15", new hebsuperobject(6,9,15,"ויעש להם יהושע שלום ויכרת להם ברית לחיותם וישבעו להם נשיאי העדה׃"));
hebsuperobject.biblemap.put("b6_9_16", new hebsuperobject(6,9,16,"ויהי מקצה שלשת ימים אחרי אשר כרתו להם ברית וישמעו כי קרבים הם אליו ובקרבו הם ישבים׃"));
hebsuperobject.biblemap.put("b6_9_17", new hebsuperobject(6,9,17,"ויסעו בני ישראל ויבאו אל עריהם ביום השלישי ועריהם גבעון והכפירה ובארות וקרית יערים׃"));
hebsuperobject.biblemap.put("b6_9_18", new hebsuperobject(6,9,18,"ולא הכום בני ישראל כי נשבעו להם נשיאי העדה ביהוה אלהי ישראל וילנו כל העדה על הנשיאים׃"));
hebsuperobject.biblemap.put("b6_9_19", new hebsuperobject(6,9,19,"ויאמרו כל הנשיאים אל כל העדה אנחנו נשבענו להם ביהוה אלהי ישראל ועתה לא נוכל לנגע בהם׃"));
hebsuperobject.biblemap.put("b6_9_20", new hebsuperobject(6,9,20,"זאת נעשה להם והחיה אותם ולא יהיה עלינו קצף על השבועה אשר נשבענו להם׃"));
hebsuperobject.biblemap.put("b6_9_21", new hebsuperobject(6,9,21,"ויאמרו אליהם הנשיאים יחיו ויהיו חטבי עצים ושאבי מים לכל העדה כאשר דברו להם הנשיאים׃"));
hebsuperobject.biblemap.put("b6_9_22", new hebsuperobject(6,9,22,"ויקרא להם יהושע וידבר אליהם לאמר למה רמיתם אתנו לאמר רחוקים אנחנו מכם מאד ואתם בקרבנו ישבים׃"));
hebsuperobject.biblemap.put("b6_9_23", new hebsuperobject(6,9,23,"ועתה ארורים אתם ולא יכרת מכם עבד וחטבי עצים ושאבי מים לבית אלהי׃"));
hebsuperobject.biblemap.put("b6_9_24", new hebsuperobject(6,9,24,"ויענו את יהושע ויאמרו כי הגד הגד לעבדיך את אשר צוה יהוה אלהיך את משה עבדו לתת לכם את כל הארץ ולהשמיד את כל ישבי הארץ מפניכם ונירא מאד לנפשתינו מפניכם ונעשה את הדבר הזה׃"));
hebsuperobject.biblemap.put("b6_9_25", new hebsuperobject(6,9,25,"ועתה הננו בידך כטוב וכישר בעיניך לעשות לנו עשה׃"));
hebsuperobject.biblemap.put("b6_9_26", new hebsuperobject(6,9,26,"ויעש להם כן ויצל אותם מיד בני ישראל ולא הרגום׃"));
hebsuperobject.biblemap.put("b6_9_27", new hebsuperobject(6,9,27,"ויתנם יהושע ביום ההוא חטבי עצים ושאבי מים לעדה ולמזבח יהוה עד היום הזה אל המקום אשר יבחר׃"));
hebsuperobject.biblemap.put("b6_10_1", new hebsuperobject(6,10,1,"ויהי כשמע אדני צדק מלך ירושלם כי לכד יהושע את העי ויחרימה כאשר עשה ליריחו ולמלכה כן עשה לעי ולמלכה וכי השלימו ישבי גבעון את ישראל ויהיו בקרבם׃"));
hebsuperobject.biblemap.put("b6_10_2", new hebsuperobject(6,10,2,"וייראו מאד כי עיר גדולה גבעון כאחת ערי הממלכה וכי היא גדולה מן העי וכל אנשיה גברים׃"));
hebsuperobject.biblemap.put("b6_10_3", new hebsuperobject(6,10,3,"וישלח אדני צדק מלך ירושלם אל הוהם מלך חברון ואל פראם מלך ירמות ואל יפיע מלך לכיש ואל דביר מלך עגלון לאמר׃"));
hebsuperobject.biblemap.put("b6_10_4", new hebsuperobject(6,10,4,"עלו אלי ועזרני ונכה את גבעון כי השלימה את יהושע ואת בני ישראל׃"));
hebsuperobject.biblemap.put("b6_10_5", new hebsuperobject(6,10,5,"ויאספו ויעלו חמשת מלכי האמרי מלך ירושלם מלך חברון מלך ירמות מלך לכיש מלך עגלון הם וכל מחניהם ויחנו על גבעון וילחמו עליה׃"));
hebsuperobject.biblemap.put("b6_10_6", new hebsuperobject(6,10,6,"וישלחו אנשי גבעון אל יהושע אל המחנה הגלגלה לאמר אל תרף ידיך מעבדיך עלה אלינו מהרה והושיעה לנו ועזרנו כי נקבצו אלינו כל מלכי האמרי ישבי ההר׃"));
hebsuperobject.biblemap.put("b6_10_7", new hebsuperobject(6,10,7,"ויעל יהושע מן הגלגל הוא וכל עם המלחמה עמו וכל גבורי החיל׃"));
hebsuperobject.biblemap.put("b6_10_8", new hebsuperobject(6,10,8,"ויאמר יהוה אל יהושע אל תירא מהם כי בידך נתתים לא יעמד איש מהם בפניך׃"));
hebsuperobject.biblemap.put("b6_10_9", new hebsuperobject(6,10,9,"ויבא אליהם יהושע פתאם כל הלילה עלה מן הגלגל׃"));
hebsuperobject.biblemap.put("b6_10_10", new hebsuperobject(6,10,10,"ויהמם יהוה לפני ישראל ויכם מכה גדולה בגבעון וירדפם דרך מעלה בית חורן ויכם עד עזקה ועד מקדה׃"));
hebsuperobject.biblemap.put("b6_10_11", new hebsuperobject(6,10,11,"ויהי בנסם מפני ישראל הם במורד בית חורן ויהוה השליך עליהם אבנים גדלות מן השמים עד עזקה וימתו רבים אשר מתו באבני הברד מאשר הרגו בני ישראל בחרב׃"));
hebsuperobject.biblemap.put("b6_10_12", new hebsuperobject(6,10,12,"אז ידבר יהושע ליהוה ביום תת יהוה את האמרי לפני בני ישראל ויאמר לעיני ישראל שמש בגבעון דום וירח בעמק אילון׃"));
hebsuperobject.biblemap.put("b6_10_13", new hebsuperobject(6,10,13,"וידם השמש וירח עמד עד יקם גוי איביו הלא היא כתובה על ספר הישר ויעמד השמש בחצי השמים ולא אץ לבוא כיום תמים׃"));
hebsuperobject.biblemap.put("b6_10_14", new hebsuperobject(6,10,14,"ולא היה כיום ההוא לפניו ואחריו לשמע יהוה בקול איש כי יהוה נלחם לישראל׃"));
hebsuperobject.biblemap.put("b6_10_15", new hebsuperobject(6,10,15,"וישב יהושע וכל ישראל עמו אל המחנה הגלגלה׃"));
hebsuperobject.biblemap.put("b6_10_16", new hebsuperobject(6,10,16,"וינסו חמשת המלכים האלה ויחבאו במערה במקדה׃"));
hebsuperobject.biblemap.put("b6_10_17", new hebsuperobject(6,10,17,"ויגד ליהושע לאמר נמצאו חמשת המלכים נחבאים במערה במקדה׃"));
hebsuperobject.biblemap.put("b6_10_18", new hebsuperobject(6,10,18,"ויאמר יהושע גלו אבנים גדלות אל פי המערה והפקידו עליה אנשים לשמרם׃"));
hebsuperobject.biblemap.put("b6_10_19", new hebsuperobject(6,10,19,"ואתם אל תעמדו רדפו אחרי איביכם וזנבתם אותם אל תתנום לבוא אל עריהם כי נתנם יהוה אלהיכם בידכם׃"));
hebsuperobject.biblemap.put("b6_10_20", new hebsuperobject(6,10,20,"ויהי ככלות יהושע ובני ישראל להכותם מכה גדולה מאד עד תמם והשרידים שרדו מהם ויבאו אל ערי המבצר׃"));
hebsuperobject.biblemap.put("b6_10_21", new hebsuperobject(6,10,21,"וישבו כל העם אל המחנה אל יהושע מקדה בשלום לא חרץ לבני ישראל לאיש את לשנו׃"));
hebsuperobject.biblemap.put("b6_10_22", new hebsuperobject(6,10,22,"ויאמר יהושע פתחו את פי המערה והוציאו אלי את חמשת המלכים האלה מן המערה׃"));
hebsuperobject.biblemap.put("b6_10_23", new hebsuperobject(6,10,23,"ויעשו כן ויציאו אליו את חמשת המלכים האלה מן המערה את מלך ירושלם את מלך חברון את מלך ירמות את מלך לכיש את מלך עגלון׃"));
hebsuperobject.biblemap.put("b6_10_24", new hebsuperobject(6,10,24,"ויהי כהוציאם את המלכים האלה אל יהושע ויקרא יהושע אל כל איש ישראל ויאמר אל קציני אנשי המלחמה ההלכוא אתו קרבו שימו את רגליכם על צוארי המלכים האלה ויקרבו וישימו את רגליהם על צואריהם׃"));
hebsuperobject.biblemap.put("b6_10_25", new hebsuperobject(6,10,25,"ויאמר אליהם יהושע אל תיראו ואל תחתו חזקו ואמצו כי ככה יעשה יהוה לכל איביכם אשר אתם נלחמים אותם׃"));
hebsuperobject.biblemap.put("b6_10_26", new hebsuperobject(6,10,26,"ויכם יהושע אחרי כן וימיתם ויתלם על חמשה עצים ויהיו תלוים על העצים עד הערב׃"));
hebsuperobject.biblemap.put("b6_10_27", new hebsuperobject(6,10,27,"ויהי לעת בוא השמש צוה יהושע וירידום מעל העצים וישלכם אל המערה אשר נחבאו שם וישמו אבנים גדלות על פי המערה עד עצם היום הזה׃"));
hebsuperobject.biblemap.put("b6_10_28", new hebsuperobject(6,10,28,"ואת מקדה לכד יהושע ביום ההוא ויכה לפי חרב ואת מלכה החרם אותם ואת כל הנפש אשר בה לא השאיר שריד ויעש למלך מקדה כאשר עשה למלך יריחו׃"));
hebsuperobject.biblemap.put("b6_10_29", new hebsuperobject(6,10,29,"ויעבר יהושע וכל ישראל עמו ממקדה לבנה וילחם עם לבנה׃"));
hebsuperobject.biblemap.put("b6_10_30", new hebsuperobject(6,10,30,"ויתן יהוה גם אותה ביד ישראל ואת מלכה ויכה לפי חרב ואת כל הנפש אשר בה לא השאיר בה שריד ויעש למלכה כאשר עשה למלך יריחו׃"));
hebsuperobject.biblemap.put("b6_10_31", new hebsuperobject(6,10,31,"ויעבר יהושע וכל ישראל עמו מלבנה לכישה ויחן עליה וילחם בה׃"));
hebsuperobject.biblemap.put("b6_10_32", new hebsuperobject(6,10,32,"ויתן יהוה את לכיש ביד ישראל וילכדה ביום השני ויכה לפי חרב ואת כל הנפש אשר בה ככל אשר עשה ללבנה׃"));
hebsuperobject.biblemap.put("b6_10_33", new hebsuperobject(6,10,33,"אז עלה הרם מלך גזר לעזר את לכיש ויכהו יהושע ואת עמו עד בלתי השאיר לו שריד׃"));
hebsuperobject.biblemap.put("b6_10_34", new hebsuperobject(6,10,34,"ויעבר יהושע וכל ישראל עמו מלכיש עגלנה ויחנו עליה וילחמו עליה׃"));
hebsuperobject.biblemap.put("b6_10_35", new hebsuperobject(6,10,35,"וילכדוה ביום ההוא ויכוה לפי חרב ואת כל הנפש אשר בה ביום ההוא החרים ככל אשר עשה ללכיש׃"));
hebsuperobject.biblemap.put("b6_10_36", new hebsuperobject(6,10,36,"ויעל יהושע וכל ישראל עמו מעגלונה חברונה וילחמו עליה׃"));
hebsuperobject.biblemap.put("b6_10_37", new hebsuperobject(6,10,37,"וילכדוה ויכוה לפי חרב ואת מלכה ואת כל עריה ואת כל הנפש אשר בה לא השאיר שריד ככל אשר עשה לעגלון ויחרם אותה ואת כל הנפש אשר בה׃"));
hebsuperobject.biblemap.put("b6_10_38", new hebsuperobject(6,10,38,"וישב יהושע וכל ישראל עמו דברה וילחם עליה׃"));
hebsuperobject.biblemap.put("b6_10_39", new hebsuperobject(6,10,39,"וילכדה ואת מלכה ואת כל עריה ויכום לפי חרב ויחרימו את כל נפש אשר בה לא השאיר שריד כאשר עשה לחברון כן עשה לדברה ולמלכה וכאשר עשה ללבנה ולמלכה׃"));
hebsuperobject.biblemap.put("b6_10_40", new hebsuperobject(6,10,40,"ויכה יהושע את כל הארץ ההר והנגב והשפלה והאשדות ואת כל מלכיהם לא השאיר שריד ואת כל הנשמה החרים כאשר צוה יהוה אלהי ישראל׃"));
hebsuperobject.biblemap.put("b6_10_41", new hebsuperobject(6,10,41,"ויכם יהושע מקדש ברנע ועד עזה ואת כל ארץ גשן ועד גבעון׃"));
hebsuperobject.biblemap.put("b6_10_42", new hebsuperobject(6,10,42,"ואת כל המלכים האלה ואת ארצם לכד יהושע פעם אחת כי יהוה אלהי ישראל נלחם לישראל׃"));
hebsuperobject.biblemap.put("b6_10_43", new hebsuperobject(6,10,43,"וישב יהושע וכל ישראל עמו אל המחנה הגלגלה׃"));
hebsuperobject.biblemap.put("b6_11_1", new hebsuperobject(6,11,1,"ויהי כשמע יבין מלך חצור וישלח אל יובב מלך מדון ואל מלך שמרון ואל מלך אכשף׃"));
hebsuperobject.biblemap.put("b6_11_2", new hebsuperobject(6,11,2,"ואל המלכים אשר מצפון בהר ובערבה נגב כנרות ובשפלה ובנפות דור מים׃"));
hebsuperobject.biblemap.put("b6_11_3", new hebsuperobject(6,11,3,"הכנעני ממזרח ומים והאמרי והחתי והפרזי והיבוסי בהר והחוי תחת חרמון בארץ המצפה׃"));
hebsuperobject.biblemap.put("b6_11_4", new hebsuperobject(6,11,4,"ויצאו הם וכל מחניהם עמם עם רב כחול אשר על שפת הים לרב וסוס ורכב רב מאד׃"));
hebsuperobject.biblemap.put("b6_11_5", new hebsuperobject(6,11,5,"ויועדו כל המלכים האלה ויבאו ויחנו יחדו אל מי מרום להלחם עם ישראל׃"));
hebsuperobject.biblemap.put("b6_11_6", new hebsuperobject(6,11,6,"ויאמר יהוה אל יהושע אל תירא מפניהם כי מחר כעת הזאת אנכי נתן את כלם חללים לפני ישראל את סוסיהם תעקר ואת מרכבתיהם תשרף באש׃"));
hebsuperobject.biblemap.put("b6_11_7", new hebsuperobject(6,11,7,"ויבא יהושע וכל עם המלחמה עמו עליהם על מי מרום פתאם ויפלו בהם׃"));
hebsuperobject.biblemap.put("b6_11_8", new hebsuperobject(6,11,8,"ויתנם יהוה ביד ישראל ויכום וירדפום עד צידון רבה ועד משרפות מים ועד בקעת מצפה מזרחה ויכם עד בלתי השאיר להם שריד׃"));
hebsuperobject.biblemap.put("b6_11_9", new hebsuperobject(6,11,9,"ויעש להם יהושע כאשר אמר לו יהוה את סוסיהם עקר ואת מרכבתיהם שרף באש׃"));
hebsuperobject.biblemap.put("b6_11_10", new hebsuperobject(6,11,10,"וישב יהושע בעת ההיא וילכד את חצור ואת מלכה הכה בחרב כי חצור לפנים היא ראש כל הממלכות האלה׃"));
hebsuperobject.biblemap.put("b6_11_11", new hebsuperobject(6,11,11,"ויכו את כל הנפש אשר בה לפי חרב החרם לא נותר כל נשמה ואת חצור שרף באש׃"));
hebsuperobject.biblemap.put("b6_11_12", new hebsuperobject(6,11,12,"ואת כל ערי המלכים האלה ואת כל מלכיהם לכד יהושע ויכם לפי חרב החרים אותם כאשר צוה משה עבד יהוה׃"));
hebsuperobject.biblemap.put("b6_11_13", new hebsuperobject(6,11,13,"רק כל הערים העמדות על תלם לא שרפם ישראל זולתי את חצור לבדה שרף יהושע׃"));
hebsuperobject.biblemap.put("b6_11_14", new hebsuperobject(6,11,14,"וכל שלל הערים האלה והבהמה בזזו להם בני ישראל רק את כל האדם הכו לפי חרב עד השמדם אותם לא השאירו כל נשמה׃"));
hebsuperobject.biblemap.put("b6_11_15", new hebsuperobject(6,11,15,"כאשר צוה יהוה את משה עבדו כן צוה משה את יהושע וכן עשה יהושע לא הסיר דבר מכל אשר צוה יהוה את משה׃"));
hebsuperobject.biblemap.put("b6_11_16", new hebsuperobject(6,11,16,"ויקח יהושע את כל הארץ הזאת ההר ואת כל הנגב ואת כל ארץ הגשן ואת השפלה ואת הערבה ואת הר ישראל ושפלתה׃"));
hebsuperobject.biblemap.put("b6_11_17", new hebsuperobject(6,11,17,"מן ההר החלק העולה שעיר ועד בעל גד בבקעת הלבנון תחת הר חרמון ואת כל מלכיהם לכד ויכם וימיתם׃"));
hebsuperobject.biblemap.put("b6_11_18", new hebsuperobject(6,11,18,"ימים רבים עשה יהושע את כל המלכים האלה מלחמה׃"));
hebsuperobject.biblemap.put("b6_11_19", new hebsuperobject(6,11,19,"לא היתה עיר אשר השלימה אל בני ישראל בלתי החוי ישבי גבעון את הכל לקחו במלחמה׃"));
hebsuperobject.biblemap.put("b6_11_20", new hebsuperobject(6,11,20,"כי מאת יהוה היתה לחזק את לבם לקראת המלחמה את ישראל למען החרימם לבלתי היות להם תחנה כי למען השמידם כאשר צוה יהוה את משה׃"));
hebsuperobject.biblemap.put("b6_11_21", new hebsuperobject(6,11,21,"ויבא יהושע בעת ההיא ויכרת את הענקים מן ההר מן חברון מן דבר מן ענב ומכל הר יהודה ומכל הר ישראל עם עריהם החרימם יהושע׃"));
hebsuperobject.biblemap.put("b6_11_22", new hebsuperobject(6,11,22,"לא נותר ענקים בארץ בני ישראל רק בעזה בגת ובאשדוד נשארו׃"));
hebsuperobject.biblemap.put("b6_11_23", new hebsuperobject(6,11,23,"ויקח יהושע את כל הארץ ככל אשר דבר יהוה אל משה ויתנה יהושע לנחלה לישראל כמחלקתם לשבטיהם והארץ שקטה ממלחמה׃"));
hebsuperobject.biblemap.put("b6_12_1", new hebsuperobject(6,12,1,"ואלה מלכי הארץ אשר הכו בני ישראל וירשו את ארצם בעבר הירדן מזרחה השמש מנחל ארנון עד הר חרמון וכל הערבה מזרחה׃"));
hebsuperobject.biblemap.put("b6_12_2", new hebsuperobject(6,12,2,"סיחון מלך האמרי היושב בחשבון משל מערוער אשר על שפת נחל ארנון ותוך הנחל וחצי הגלעד ועד יבק הנחל גבול בני עמון׃"));
hebsuperobject.biblemap.put("b6_12_3", new hebsuperobject(6,12,3,"והערבה עד ים כנרות מזרחה ועד ים הערבה ים המלח מזרחה דרך בית הישמות ומתימן תחת אשדות הפסגה׃"));
hebsuperobject.biblemap.put("b6_12_4", new hebsuperobject(6,12,4,"וגבול עוג מלך הבשן מיתר הרפאים היושב בעשתרות ובאדרעי׃"));
hebsuperobject.biblemap.put("b6_12_5", new hebsuperobject(6,12,5,"ומשל בהר חרמון ובסלכה ובכל הבשן עד גבול הגשורי והמעכתי וחצי הגלעד גבול סיחון מלך חשבון׃"));
hebsuperobject.biblemap.put("b6_12_6", new hebsuperobject(6,12,6,"משה עבד יהוה ובני ישראל הכום ויתנה משה עבד יהוה ירשה לראובני ולגדי ולחצי שבט המנשה׃"));
hebsuperobject.biblemap.put("b6_12_7", new hebsuperobject(6,12,7,"ואלה מלכי הארץ אשר הכה יהושע ובני ישראל בעבר הירדן ימה מבעל גד בבקעת הלבנון ועד ההר החלק העלה שעירה ויתנה יהושע לשבטי ישראל ירשה כמחלקתם׃"));
hebsuperobject.biblemap.put("b6_12_8", new hebsuperobject(6,12,8,"בהר ובשפלה ובערבה ובאשדות ובמדבר ובנגב החתי האמרי והכנעני הפרזי החוי והיבוסי׃"));
hebsuperobject.biblemap.put("b6_12_9", new hebsuperobject(6,12,9,"מלך יריחו אחד מלך העי אשר מצד בית אל אחד׃"));
hebsuperobject.biblemap.put("b6_12_10", new hebsuperobject(6,12,10,"מלך ירושלם אחד מלך חברון אחד׃"));
hebsuperobject.biblemap.put("b6_12_11", new hebsuperobject(6,12,11,"מלך ירמות אחד מלך לכיש אחד׃"));
hebsuperobject.biblemap.put("b6_12_12", new hebsuperobject(6,12,12,"מלך עגלון אחד מלך גזר אחד׃"));
hebsuperobject.biblemap.put("b6_12_13", new hebsuperobject(6,12,13,"מלך דבר אחד מלך גדר אחד׃"));
hebsuperobject.biblemap.put("b6_12_14", new hebsuperobject(6,12,14,"מלך חרמה אחד מלך ערד אחד׃"));
hebsuperobject.biblemap.put("b6_12_15", new hebsuperobject(6,12,15,"מלך לבנה אחד מלך עדלם אחד׃"));
hebsuperobject.biblemap.put("b6_12_16", new hebsuperobject(6,12,16,"מלך מקדה אחד מלך בית אל אחד׃"));
hebsuperobject.biblemap.put("b6_12_17", new hebsuperobject(6,12,17,"מלך תפוח אחד מלך חפר אחד׃"));
hebsuperobject.biblemap.put("b6_12_18", new hebsuperobject(6,12,18,"מלך אפק אחד מלך לשרון אחד׃"));
hebsuperobject.biblemap.put("b6_12_19", new hebsuperobject(6,12,19,"מלך מדון אחד מלך חצור אחד׃"));
hebsuperobject.biblemap.put("b6_12_20", new hebsuperobject(6,12,20,"מלך שמרון מראון אחד מלך אכשף אחד׃"));
hebsuperobject.biblemap.put("b6_12_21", new hebsuperobject(6,12,21,"מלך תענך אחד מלך מגדו אחד׃"));
hebsuperobject.biblemap.put("b6_12_22", new hebsuperobject(6,12,22,"מלך קדש אחד מלך יקנעם לכרמל אחד׃"));
hebsuperobject.biblemap.put("b6_12_23", new hebsuperobject(6,12,23,"מלך דור לנפת דור אחד מלך גוים לגלגל אחד׃"));
hebsuperobject.biblemap.put("b6_12_24", new hebsuperobject(6,12,24,"מלך תרצה אחד כל מלכים שלשים ואחד׃"));
hebsuperobject.biblemap.put("b6_13_1", new hebsuperobject(6,13,1,"ויהושע זקן בא בימים ויאמר יהוה אליו אתה זקנתה באת בימים והארץ נשארה הרבה מאד לרשתה׃"));
hebsuperobject.biblemap.put("b6_13_2", new hebsuperobject(6,13,2,"זאת הארץ הנשארת כל גלילות הפלשתים וכל הגשורי׃"));
hebsuperobject.biblemap.put("b6_13_3", new hebsuperobject(6,13,3,"מן השיחור אשר על פני מצרים ועד גבול עקרון צפונה לכנעני תחשב חמשת סרני פלשתים העזתי והאשדודי האשקלוני הגתי והעקרוני והעוים׃"));
hebsuperobject.biblemap.put("b6_13_4", new hebsuperobject(6,13,4,"מתימן כל ארץ הכנעני ומערה אשר לצידנים עד אפקה עד גבול האמרי׃"));
hebsuperobject.biblemap.put("b6_13_5", new hebsuperobject(6,13,5,"והארץ הגבלי וכל הלבנון מזרח השמש מבעל גד תחת הר חרמון עד לבוא חמת׃"));
hebsuperobject.biblemap.put("b6_13_6", new hebsuperobject(6,13,6,"כל ישבי ההר מן הלבנון עד משרפת מים כל צידנים אנכי אורישם מפני בני ישראל רק הפלה לישראל בנחלה כאשר צויתיך׃"));
hebsuperobject.biblemap.put("b6_13_7", new hebsuperobject(6,13,7,"ועתה חלק את הארץ הזאת בנחלה לתשעת השבטים וחצי השבט המנשה׃"));
hebsuperobject.biblemap.put("b6_13_8", new hebsuperobject(6,13,8,"עמו הראובני והגדי לקחו נחלתם אשר נתן להם משה בעבר הירדן מזרחה כאשר נתן להם משה עבד יהוה׃"));
hebsuperobject.biblemap.put("b6_13_9", new hebsuperobject(6,13,9,"מערוער אשר על שפת נחל ארנון והעיר אשר בתוך הנחל וכל המישר מידבא עד דיבון׃"));
hebsuperobject.biblemap.put("b6_13_10", new hebsuperobject(6,13,10,"וכל ערי סיחון מלך האמרי אשר מלך בחשבון עד גבול בני עמון׃"));
hebsuperobject.biblemap.put("b6_13_11", new hebsuperobject(6,13,11,"והגלעד וגבול הגשורי והמעכתי וכל הר חרמון וכל הבשן עד סלכה׃"));
hebsuperobject.biblemap.put("b6_13_12", new hebsuperobject(6,13,12,"כל ממלכות עוג בבשן אשר מלך בעשתרות ובאדרעי הוא נשאר מיתר הרפאים ויכם משה וירשם׃"));
hebsuperobject.biblemap.put("b6_13_13", new hebsuperobject(6,13,13,"ולא הורישו בני ישראל את הגשורי ואת המעכתי וישב גשור ומעכת בקרב ישראל עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_13_14", new hebsuperobject(6,13,14,"רק לשבט הלוי לא נתן נחלה אשי יהוה אלהי ישראל הוא נחלתו כאשר דבר לו׃"));
hebsuperobject.biblemap.put("b6_13_15", new hebsuperobject(6,13,15,"ויתן משה למטה בני ראובן למשפחתם׃"));
hebsuperobject.biblemap.put("b6_13_16", new hebsuperobject(6,13,16,"ויהי להם הגבול מערוער אשר על שפת נחל ארנון והעיר אשר בתוך הנחל וכל המישר על מידבא׃"));
hebsuperobject.biblemap.put("b6_13_17", new hebsuperobject(6,13,17,"חשבון וכל עריה אשר במישר דיבון ובמות בעל ובית בעל מעון׃"));
hebsuperobject.biblemap.put("b6_13_18", new hebsuperobject(6,13,18,"ויהצה וקדמת ומפעת׃"));
hebsuperobject.biblemap.put("b6_13_19", new hebsuperobject(6,13,19,"וקריתים ושבמה וצרת השחר בהר העמק׃"));
hebsuperobject.biblemap.put("b6_13_20", new hebsuperobject(6,13,20,"ובית פעור ואשדות הפסגה ובית הישמות׃"));
hebsuperobject.biblemap.put("b6_13_21", new hebsuperobject(6,13,21,"וכל ערי המישר וכל ממלכות סיחון מלך האמרי אשר מלך בחשבון אשר הכה משה אתו ואת נשיאי מדין את אוי ואת רקם ואת צור ואת חור ואת רבע נסיכי סיחון ישבי הארץ׃"));
hebsuperobject.biblemap.put("b6_13_22", new hebsuperobject(6,13,22,"ואת בלעם בן בעור הקוסם הרגו בני ישראל בחרב אל חלליהם׃"));
hebsuperobject.biblemap.put("b6_13_23", new hebsuperobject(6,13,23,"ויהי גבול בני ראובן הירדן וגבול זאת נחלת בני ראובן למשפחתם הערים וחצריהן׃"));
hebsuperobject.biblemap.put("b6_13_24", new hebsuperobject(6,13,24,"ויתן משה למטה גד לבני גד למשפחתם׃"));
hebsuperobject.biblemap.put("b6_13_25", new hebsuperobject(6,13,25,"ויהי להם הגבול יעזר וכל ערי הגלעד וחצי ארץ בני עמון עד ערוער אשר על פני רבה׃"));
hebsuperobject.biblemap.put("b6_13_26", new hebsuperobject(6,13,26,"ומחשבון עד רמת המצפה ובטנים וממחנים עד גבול לדבר׃"));
hebsuperobject.biblemap.put("b6_13_27", new hebsuperobject(6,13,27,"ובעמק בית הרם ובית נמרה וסכות וצפון יתר ממלכות סיחון מלך חשבון הירדן וגבל עד קצה ים כנרת עבר הירדן מזרחה׃"));
hebsuperobject.biblemap.put("b6_13_28", new hebsuperobject(6,13,28,"זאת נחלת בני גד למשפחתם הערים וחצריהם׃"));
hebsuperobject.biblemap.put("b6_13_29", new hebsuperobject(6,13,29,"ויתן משה לחצי שבט מנשה ויהי לחצי מטה בני מנשה למשפחותם׃"));
hebsuperobject.biblemap.put("b6_13_30", new hebsuperobject(6,13,30,"ויהי גבולם ממחנים כל הבשן כל ממלכות עוג מלך הבשן וכל חות יאיר אשר בבשן ששים עיר׃"));
hebsuperobject.biblemap.put("b6_13_31", new hebsuperobject(6,13,31,"וחצי הגלעד ועשתרות ואדרעי ערי ממלכות עוג בבשן לבני מכיר בן מנשה לחצי בני מכיר למשפחותם׃"));
hebsuperobject.biblemap.put("b6_13_32", new hebsuperobject(6,13,32,"אלה אשר נחל משה בערבות מואב מעבר לירדן יריחו מזרחה׃"));
hebsuperobject.biblemap.put("b6_13_33", new hebsuperobject(6,13,33,"ולשבט הלוי לא נתן משה נחלה יהוה אלהי ישראל הוא נחלתם כאשר דבר להם׃"));
hebsuperobject.biblemap.put("b6_14_1", new hebsuperobject(6,14,1,"ואלה אשר נחלו בני ישראל בארץ כנען אשר נחלו אותם אלעזר הכהן ויהושע בן נון וראשי אבות המטות לבני ישראל׃"));
hebsuperobject.biblemap.put("b6_14_2", new hebsuperobject(6,14,2,"בגורל נחלתם כאשר צוה יהוה ביד משה לתשעת המטות וחצי המטה׃"));
hebsuperobject.biblemap.put("b6_14_3", new hebsuperobject(6,14,3,"כי נתן משה נחלת שני המטות וחצי המטה מעבר לירדן וללוים לא נתן נחלה בתוכם׃"));
hebsuperobject.biblemap.put("b6_14_4", new hebsuperobject(6,14,4,"כי היו בני יוסף שני מטות מנשה ואפרים ולא נתנו חלק ללוים בארץ כי אם ערים לשבת ומגרשיהם למקניהם ולקנינם׃"));
hebsuperobject.biblemap.put("b6_14_5", new hebsuperobject(6,14,5,"כאשר צוה יהוה את משה כן עשו בני ישראל ויחלקו את הארץ׃"));
hebsuperobject.biblemap.put("b6_14_6", new hebsuperobject(6,14,6,"ויגשו בני יהודה אל יהושע בגלגל ויאמר אליו כלב בן יפנה הקנזי אתה ידעת את הדבר אשר דבר יהוה אל משה איש האלהים על אדותי ועל אדותיך בקדש ברנע׃"));
hebsuperobject.biblemap.put("b6_14_7", new hebsuperobject(6,14,7,"בן ארבעים שנה אנכי בשלח משה עבד יהוה אתי מקדש ברנע לרגל את הארץ ואשב אתו דבר כאשר עם לבבי׃"));
hebsuperobject.biblemap.put("b6_14_8", new hebsuperobject(6,14,8,"ואחי אשר עלו עמי המסיו את לב העם ואנכי מלאתי אחרי יהוה אלהי׃"));
hebsuperobject.biblemap.put("b6_14_9", new hebsuperobject(6,14,9,"וישבע משה ביום ההוא לאמר אם לא הארץ אשר דרכה רגלך בה לך תהיה לנחלה ולבניך עד עולם כי מלאת אחרי יהוה אלהי׃"));
hebsuperobject.biblemap.put("b6_14_10", new hebsuperobject(6,14,10,"ועתה הנה החיה יהוה אותי כאשר דבר זה ארבעים וחמש שנה מאז דבר יהוה את הדבר הזה אל משה אשר הלך ישראל במדבר ועתה הנה אנכי היום בן חמש ושמונים שנה׃"));
hebsuperobject.biblemap.put("b6_14_11", new hebsuperobject(6,14,11,"עודני היום חזק כאשר ביום שלח אותי משה ככחי אז וככחי עתה למלחמה ולצאת ולבוא׃"));
hebsuperobject.biblemap.put("b6_14_12", new hebsuperobject(6,14,12,"ועתה תנה לי את ההר הזה אשר דבר יהוה ביום ההוא כי אתה שמעת ביום ההוא כי ענקים שם וערים גדלות בצרות אולי יהוה אותי והורשתים כאשר דבר יהוה׃"));
hebsuperobject.biblemap.put("b6_14_13", new hebsuperobject(6,14,13,"ויברכהו יהושע ויתן את חברון לכלב בן יפנה לנחלה׃"));
hebsuperobject.biblemap.put("b6_14_14", new hebsuperobject(6,14,14,"על כן היתה חברון לכלב בן יפנה הקנזי לנחלה עד היום הזה יען אשר מלא אחרי יהוה אלהי ישראל׃"));
hebsuperobject.biblemap.put("b6_14_15", new hebsuperobject(6,14,15,"ושם חברון לפנים קרית ארבע האדם הגדול בענקים הוא והארץ שקטה ממלחמה׃"));
hebsuperobject.biblemap.put("b6_15_1", new hebsuperobject(6,15,1,"ויהי הגורל למטה בני יהודה למשפחתם אל גבול אדום מדבר צן נגבה מקצה תימן׃"));
hebsuperobject.biblemap.put("b6_15_2", new hebsuperobject(6,15,2,"ויהי להם גבול נגב מקצה ים המלח מן הלשן הפנה נגבה׃"));
hebsuperobject.biblemap.put("b6_15_3", new hebsuperobject(6,15,3,"ויצא אל מנגב למעלה עקרבים ועבר צנה ועלה מנגב לקדש ברנע ועבר חצרון ועלה אדרה ונסב הקרקעה׃"));
hebsuperobject.biblemap.put("b6_15_4", new hebsuperobject(6,15,4,"ועבר עצמונה ויצא נחל מצרים והיה תצאות הגבול ימה זה יהיה לכם גבול נגב׃"));
hebsuperobject.biblemap.put("b6_15_5", new hebsuperobject(6,15,5,"וגבול קדמה ים המלח עד קצה הירדן וגבול לפאת צפונה מלשון הים מקצה הירדן׃"));
hebsuperobject.biblemap.put("b6_15_6", new hebsuperobject(6,15,6,"ועלה הגבול בית חגלה ועבר מצפון לבית הערבה ועלה הגבול אבן בהן בן ראובן׃"));
hebsuperobject.biblemap.put("b6_15_7", new hebsuperobject(6,15,7,"ועלה הגבול דברה מעמק עכור וצפונה פנה אל הגלגל אשר נכח למעלה אדמים אשר מנגב לנחל ועבר הגבול אל מי עין שמש והיו תצאתיו אל עין רגל׃"));
hebsuperobject.biblemap.put("b6_15_8", new hebsuperobject(6,15,8,"ועלה הגבול גי בן הנם אל כתף היבוסי מנגב היא ירושלם ועלה הגבול אל ראש ההר אשר על פני גי הנם ימה אשר בקצה עמק רפאים צפנה׃"));
hebsuperobject.biblemap.put("b6_15_9", new hebsuperobject(6,15,9,"ותאר הגבול מראש ההר אל מעין מי נפתוח ויצא אל ערי הר עפרון ותאר הגבול בעלה היא קרית יערים׃"));
hebsuperobject.biblemap.put("b6_15_10", new hebsuperobject(6,15,10,"ונסב הגבול מבעלה ימה אל הר שעיר ועבר אל כתף הר יערים מצפונה היא כסלון וירד בית שמש ועבר תמנה׃"));
hebsuperobject.biblemap.put("b6_15_11", new hebsuperobject(6,15,11,"ויצא הגבול אל כתף עקרון צפונה ותאר הגבול שכרונה ועבר הר הבעלה ויצא יבנאל והיו תצאות הגבול ימה׃"));
hebsuperobject.biblemap.put("b6_15_12", new hebsuperobject(6,15,12,"וגבול ים הימה הגדול וגבול זה גבול בני יהודה סביב למשפחתם׃"));
hebsuperobject.biblemap.put("b6_15_13", new hebsuperobject(6,15,13,"ולכלב בן יפנה נתן חלק בתוך בני יהודה אל פי יהוה ליהושע את קרית ארבע אבי הענק היא חברון׃"));
hebsuperobject.biblemap.put("b6_15_14", new hebsuperobject(6,15,14,"וירש משם כלב את שלושה בני הענק את ששי ואת אחימן ואת תלמי ילידי הענק׃"));
hebsuperobject.biblemap.put("b6_15_15", new hebsuperobject(6,15,15,"ויעל משם אל ישבי דבר ושם דבר לפנים קרית ספר׃"));
hebsuperobject.biblemap.put("b6_15_16", new hebsuperobject(6,15,16,"ויאמר כלב אשר יכה את קרית ספר ולכדה ונתתי לו את עכסה בתי לאשה׃"));
hebsuperobject.biblemap.put("b6_15_17", new hebsuperobject(6,15,17,"וילכדה עתניאל בן קנז אחי כלב ויתן לו את עכסה בתו לאשה׃"));
hebsuperobject.biblemap.put("b6_15_18", new hebsuperobject(6,15,18,"ויהי בבואה ותסיתהו לשאול מאת אביה שדה ותצנח מעל החמור ויאמר לה כלב מה לך׃"));
hebsuperobject.biblemap.put("b6_15_19", new hebsuperobject(6,15,19,"ותאמר תנה לי ברכה כי ארץ הנגב נתתני ונתתה לי גלת מים ויתן לה את גלת עליות ואת גלת תחתיות׃"));
hebsuperobject.biblemap.put("b6_15_20", new hebsuperobject(6,15,20,"זאת נחלת מטה בני יהודה למשפחתם׃"));
hebsuperobject.biblemap.put("b6_15_21", new hebsuperobject(6,15,21,"ויהיו הערים מקצה למטה בני יהודה אל גבול אדום בנגבה קבצאל ועדר ויגור׃"));
hebsuperobject.biblemap.put("b6_15_22", new hebsuperobject(6,15,22,"וקינה ודימונה ועדעדה׃"));
hebsuperobject.biblemap.put("b6_15_23", new hebsuperobject(6,15,23,"וקדש וחצור ויתנן׃"));
hebsuperobject.biblemap.put("b6_15_24", new hebsuperobject(6,15,24,"זיף וטלם ובעלות׃"));
hebsuperobject.biblemap.put("b6_15_25", new hebsuperobject(6,15,25,"וחצור חדתה וקריות חצרון היא חצור׃"));
hebsuperobject.biblemap.put("b6_15_26", new hebsuperobject(6,15,26,"אמם ושמע ומולדה׃"));
hebsuperobject.biblemap.put("b6_15_27", new hebsuperobject(6,15,27,"וחצר גדה וחשמון ובית פלט׃"));
hebsuperobject.biblemap.put("b6_15_28", new hebsuperobject(6,15,28,"וחצר שועל ובאר שבע ובזיותיה׃"));
hebsuperobject.biblemap.put("b6_15_29", new hebsuperobject(6,15,29,"בעלה ועיים ועצם׃"));
hebsuperobject.biblemap.put("b6_15_30", new hebsuperobject(6,15,30,"ואלתולד וכסיל וחרמה׃"));
hebsuperobject.biblemap.put("b6_15_31", new hebsuperobject(6,15,31,"וצקלג ומדמנה וסנסנה׃"));
hebsuperobject.biblemap.put("b6_15_32", new hebsuperobject(6,15,32,"ולבאות ושלחים ועין ורמון כל ערים עשרים ותשע וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_33", new hebsuperobject(6,15,33,"בשפלה אשתאול וצרעה ואשנה׃"));
hebsuperobject.biblemap.put("b6_15_34", new hebsuperobject(6,15,34,"וזנוח ועין גנים תפוח והעינם׃"));
hebsuperobject.biblemap.put("b6_15_35", new hebsuperobject(6,15,35,"ירמות ועדלם שוכה ועזקה׃"));
hebsuperobject.biblemap.put("b6_15_36", new hebsuperobject(6,15,36,"ושערים ועדיתים והגדרה וגדרתים ערים ארבע עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_37", new hebsuperobject(6,15,37,"צנן וחדשה ומגדל גד׃"));
hebsuperobject.biblemap.put("b6_15_38", new hebsuperobject(6,15,38,"ודלען והמצפה ויקתאל׃"));
hebsuperobject.biblemap.put("b6_15_39", new hebsuperobject(6,15,39,"לכיש ובצקת ועגלון׃"));
hebsuperobject.biblemap.put("b6_15_40", new hebsuperobject(6,15,40,"וכבון ולחמס וכתליש׃"));
hebsuperobject.biblemap.put("b6_15_41", new hebsuperobject(6,15,41,"וגדרות בית דגון ונעמה ומקדה ערים שש עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_42", new hebsuperobject(6,15,42,"לבנה ועתר ועשן׃"));
hebsuperobject.biblemap.put("b6_15_43", new hebsuperobject(6,15,43,"ויפתח ואשנה ונציב׃"));
hebsuperobject.biblemap.put("b6_15_44", new hebsuperobject(6,15,44,"וקעילה ואכזיב ומראשה ערים תשע וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_45", new hebsuperobject(6,15,45,"עקרון ובנתיה וחצריה׃"));
hebsuperobject.biblemap.put("b6_15_46", new hebsuperobject(6,15,46,"מעקרון וימה כל אשר על יד אשדוד וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_47", new hebsuperobject(6,15,47,"אשדוד בנותיה וחצריה עזה בנותיה וחצריה עד נחל מצרים והים הגבול וגבול׃"));
hebsuperobject.biblemap.put("b6_15_48", new hebsuperobject(6,15,48,"ובהר שמיר ויתיר ושוכה׃"));
hebsuperobject.biblemap.put("b6_15_49", new hebsuperobject(6,15,49,"ודנה וקרית סנה היא דבר׃"));
hebsuperobject.biblemap.put("b6_15_50", new hebsuperobject(6,15,50,"וענב ואשתמה וענים׃"));
hebsuperobject.biblemap.put("b6_15_51", new hebsuperobject(6,15,51,"וגשן וחלן וגלה ערים אחת עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_52", new hebsuperobject(6,15,52,"ארב ורומה ואשען׃"));
hebsuperobject.biblemap.put("b6_15_53", new hebsuperobject(6,15,53,"וינים ובית תפוח ואפקה׃"));
hebsuperobject.biblemap.put("b6_15_54", new hebsuperobject(6,15,54,"וחמטה וקרית ארבע היא חברון וציער ערים תשע וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_55", new hebsuperobject(6,15,55,"מעון כרמל וזיף ויוטה׃"));
hebsuperobject.biblemap.put("b6_15_56", new hebsuperobject(6,15,56,"ויזרעאל ויקדעם וזנוח׃"));
hebsuperobject.biblemap.put("b6_15_57", new hebsuperobject(6,15,57,"הקין גבעה ותמנה ערים עשר וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_58", new hebsuperobject(6,15,58,"חלחול בית צור וגדור׃"));
hebsuperobject.biblemap.put("b6_15_59", new hebsuperobject(6,15,59,"ומערת ובית ענות ואלתקן ערים שש וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_60", new hebsuperobject(6,15,60,"קרית בעל היא קרית יערים והרבה ערים שתים וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_61", new hebsuperobject(6,15,61,"במדבר בית הערבה מדין וסככה׃"));
hebsuperobject.biblemap.put("b6_15_62", new hebsuperobject(6,15,62,"והנבשן ועיר המלח ועין גדי ערים שש וחצריהן׃"));
hebsuperobject.biblemap.put("b6_15_63", new hebsuperobject(6,15,63,"ואת היבוסי יושבי ירושלם לא יוכלו בני יהודה להורישם וישב היבוסי את בני יהודה בירושלם עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_16_1", new hebsuperobject(6,16,1,"ויצא הגורל לבני יוסף מירדן יריחו למי יריחו מזרחה המדבר עלה מיריחו בהר בית אל׃"));
hebsuperobject.biblemap.put("b6_16_2", new hebsuperobject(6,16,2,"ויצא מבית אל לוזה ועבר אל גבול הארכי עטרות׃"));
hebsuperobject.biblemap.put("b6_16_3", new hebsuperobject(6,16,3,"וירד ימה אל גבול היפלטי עד גבול בית חורן תחתון ועד גזר והיו תצאתו ימה׃"));
hebsuperobject.biblemap.put("b6_16_4", new hebsuperobject(6,16,4,"וינחלו בני יוסף מנשה ואפרים׃"));
hebsuperobject.biblemap.put("b6_16_5", new hebsuperobject(6,16,5,"ויהי גבול בני אפרים למשפחתם ויהי גבול נחלתם מזרחה עטרות אדר עד בית חורן עליון׃"));
hebsuperobject.biblemap.put("b6_16_6", new hebsuperobject(6,16,6,"ויצא הגבול הימה המכמתת מצפון ונסב הגבול מזרחה תאנת שלה ועבר אותו ממזרח ינוחה׃"));
hebsuperobject.biblemap.put("b6_16_7", new hebsuperobject(6,16,7,"וירד מינוחה עטרות ונערתה ופגע ביריחו ויצא הירדן׃"));
hebsuperobject.biblemap.put("b6_16_8", new hebsuperobject(6,16,8,"מתפוח ילך הגבול ימה נחל קנה והיו תצאתיו הימה זאת נחלת מטה בני אפרים למשפחתם׃"));
hebsuperobject.biblemap.put("b6_16_9", new hebsuperobject(6,16,9,"והערים המבדלות לבני אפרים בתוך נחלת בני מנשה כל הערים וחצריהן׃"));
hebsuperobject.biblemap.put("b6_16_10", new hebsuperobject(6,16,10,"ולא הורישו את הכנעני היושב בגזר וישב הכנעני בקרב אפרים עד היום הזה ויהי למס עבד׃"));
hebsuperobject.biblemap.put("b6_17_1", new hebsuperobject(6,17,1,"ויהי הגורל למטה מנשה כי הוא בכור יוסף למכיר בכור מנשה אבי הגלעד כי הוא היה איש מלחמה ויהי לו הגלעד והבשן׃"));
hebsuperobject.biblemap.put("b6_17_2", new hebsuperobject(6,17,2,"ויהי לבני מנשה הנותרים למשפחתם לבני אביעזר ולבני חלק ולבני אשריאל ולבני שכם ולבני חפר ולבני שמידע אלה בני מנשה בן יוסף הזכרים למשפחתם׃"));
hebsuperobject.biblemap.put("b6_17_3", new hebsuperobject(6,17,3,"ולצלפחד בן חפר בן גלעד בן מכיר בן מנשה לא היו לו בנים כי אם בנות ואלה שמות בנתיו מחלה ונעה חגלה מלכה ותרצה׃"));
hebsuperobject.biblemap.put("b6_17_4", new hebsuperobject(6,17,4,"ותקרבנה לפני אלעזר הכהן ולפני יהושע בן נון ולפני הנשיאים לאמר יהוה צוה את משה לתת לנו נחלה בתוך אחינו ויתן להם אל פי יהוה נחלה בתוך אחי אביהן׃"));
hebsuperobject.biblemap.put("b6_17_5", new hebsuperobject(6,17,5,"ויפלו חבלי מנשה עשרה לבד מארץ הגלעד והבשן אשר מעבר לירדן׃"));
hebsuperobject.biblemap.put("b6_17_6", new hebsuperobject(6,17,6,"כי בנות מנשה נחלו נחלה בתוך בניו וארץ הגלעד היתה לבני מנשה הנותרים׃"));
hebsuperobject.biblemap.put("b6_17_7", new hebsuperobject(6,17,7,"ויהי גבול מנשה מאשר המכמתת אשר על פני שכם והלך הגבול אל הימין אל ישבי עין תפוח׃"));
hebsuperobject.biblemap.put("b6_17_8", new hebsuperobject(6,17,8,"למנשה היתה ארץ תפוח ותפוח אל גבול מנשה לבני אפרים׃"));
hebsuperobject.biblemap.put("b6_17_9", new hebsuperobject(6,17,9,"וירד הגבול נחל קנה נגבה לנחל ערים האלה לאפרים בתוך ערי מנשה וגבול מנשה מצפון לנחל ויהי תצאתיו הימה׃"));
hebsuperobject.biblemap.put("b6_17_10", new hebsuperobject(6,17,10,"נגבה לאפרים וצפונה למנשה ויהי הים גבולו ובאשר יפגעון מצפון וביששכר ממזרח׃"));
hebsuperobject.biblemap.put("b6_17_11", new hebsuperobject(6,17,11,"ויהי למנשה ביששכר ובאשר בית שאן ובנותיה ויבלעם ובנותיה ואת ישבי דאר ובנותיה וישבי עין דר ובנתיה וישבי תענך ובנתיה וישבי מגדו ובנותיה שלשת הנפת׃"));
hebsuperobject.biblemap.put("b6_17_12", new hebsuperobject(6,17,12,"ולא יכלו בני מנשה להוריש את הערים האלה ויואל הכנעני לשבת בארץ הזאת׃"));
hebsuperobject.biblemap.put("b6_17_13", new hebsuperobject(6,17,13,"ויהי כי חזקו בני ישראל ויתנו את הכנעני למס והורש לא הורישו׃"));
hebsuperobject.biblemap.put("b6_17_14", new hebsuperobject(6,17,14,"וידברו בני יוסף את יהושע לאמר מדוע נתתה לי נחלה גורל אחד וחבל אחד ואני עם רב עד אשר עד כה ברכני יהוה׃"));
hebsuperobject.biblemap.put("b6_17_15", new hebsuperobject(6,17,15,"ויאמר אליהם יהושע אם עם רב אתה עלה לך היערה ובראת לך שם בארץ הפרזי והרפאים כי אץ לך הר אפרים׃"));
hebsuperobject.biblemap.put("b6_17_16", new hebsuperobject(6,17,16,"ויאמרו בני יוסף לא ימצא לנו ההר ורכב ברזל בכל הכנעני הישב בארץ העמק לאשר בבית שאן ובנותיה ולאשר בעמק יזרעאל׃"));
hebsuperobject.biblemap.put("b6_17_17", new hebsuperobject(6,17,17,"ויאמר יהושע אל בית יוסף לאפרים ולמנשה לאמר עם רב אתה וכח גדול לך לא יהיה לך גורל אחד׃"));
hebsuperobject.biblemap.put("b6_17_18", new hebsuperobject(6,17,18,"כי הר יהיה לך כי יער הוא ובראתו והיה לך תצאתיו כי תוריש את הכנעני כי רכב ברזל לו כי חזק הוא׃"));
hebsuperobject.biblemap.put("b6_18_1", new hebsuperobject(6,18,1,"ויקהלו כל עדת בני ישראל שלה וישכינו שם את אהל מועד והארץ נכבשה לפניהם׃"));
hebsuperobject.biblemap.put("b6_18_2", new hebsuperobject(6,18,2,"ויותרו בבני ישראל אשר לא חלקו את נחלתם שבעה שבטים׃"));
hebsuperobject.biblemap.put("b6_18_3", new hebsuperobject(6,18,3,"ויאמר יהושע אל בני ישראל עד אנה אתם מתרפים לבוא לרשת את הארץ אשר נתן לכם יהוה אלהי אבותיכם׃"));
hebsuperobject.biblemap.put("b6_18_4", new hebsuperobject(6,18,4,"הבו לכם שלשה אנשים לשבט ואשלחם ויקמו ויתהלכו בארץ ויכתבו אותה לפי נחלתם ויבאו אלי׃"));
hebsuperobject.biblemap.put("b6_18_5", new hebsuperobject(6,18,5,"והתחלקו אתה לשבעה חלקים יהודה יעמד על גבולו מנגב ובית יוסף יעמדו על גבולם מצפון׃"));
hebsuperobject.biblemap.put("b6_18_6", new hebsuperobject(6,18,6,"ואתם תכתבו את הארץ שבעה חלקים והבאתם אלי הנה ויריתי לכם גורל פה לפני יהוה אלהינו׃"));
hebsuperobject.biblemap.put("b6_18_7", new hebsuperobject(6,18,7,"כי אין חלק ללוים בקרבכם כי כהנת יהוה נחלתו וגד וראובן וחצי שבט המנשה לקחו נחלתם מעבר לירדן מזרחה אשר נתן להם משה עבד יהוה׃"));
hebsuperobject.biblemap.put("b6_18_8", new hebsuperobject(6,18,8,"ויקמו האנשים וילכו ויצו יהושע את ההלכים לכתב את הארץ לאמר לכו והתהלכו בארץ וכתבו אותה ושובו אלי ופה אשליך לכם גורל לפני יהוה בשלה׃"));
hebsuperobject.biblemap.put("b6_18_9", new hebsuperobject(6,18,9,"וילכו האנשים ויעברו בארץ ויכתבוה לערים לשבעה חלקים על ספר ויבאו אל יהושע אל המחנה שלה׃"));
hebsuperobject.biblemap.put("b6_18_10", new hebsuperobject(6,18,10,"וישלך להם יהושע גורל בשלה לפני יהוה ויחלק שם יהושע את הארץ לבני ישראל כמחלקתם׃"));
hebsuperobject.biblemap.put("b6_18_11", new hebsuperobject(6,18,11,"ויעל גורל מטה בני בנימן למשפחתם ויצא גבול גורלם בין בני יהודה ובין בני יוסף׃"));
hebsuperobject.biblemap.put("b6_18_12", new hebsuperobject(6,18,12,"ויהי להם הגבול לפאת צפונה מן הירדן ועלה הגבול אל כתף יריחו מצפון ועלה בהר ימה והיה תצאתיו מדברה בית און׃"));
hebsuperobject.biblemap.put("b6_18_13", new hebsuperobject(6,18,13,"ועבר משם הגבול לוזה אל כתף לוזה נגבה היא בית אל וירד הגבול עטרות אדר על ההר אשר מנגב לבית חרון תחתון׃"));
hebsuperobject.biblemap.put("b6_18_14", new hebsuperobject(6,18,14,"ותאר הגבול ונסב לפאת ים נגבה מן ההר אשר על פני בית חרון נגבה והיה תצאתיו אל קרית בעל היא קרית יערים עיר בני יהודה זאת פאת ים׃"));
hebsuperobject.biblemap.put("b6_18_15", new hebsuperobject(6,18,15,"ופאת נגבה מקצה קרית יערים ויצא הגבול ימה ויצא אל מעין מי נפתוח׃"));
hebsuperobject.biblemap.put("b6_18_16", new hebsuperobject(6,18,16,"וירד הגבול אל קצה ההר אשר על פני גי בן הנם אשר בעמק רפאים צפונה וירד גי הנם אל כתף היבוסי נגבה וירד עין רגל׃"));
hebsuperobject.biblemap.put("b6_18_17", new hebsuperobject(6,18,17,"ותאר מצפון ויצא עין שמש ויצא אל גלילות אשר נכח מעלה אדמים וירד אבן בהן בן ראובן׃"));
hebsuperobject.biblemap.put("b6_18_18", new hebsuperobject(6,18,18,"ועבר אל כתף מול הערבה צפונה וירד הערבתה׃"));
hebsuperobject.biblemap.put("b6_18_19", new hebsuperobject(6,18,19,"ועבר הגבול אל כתף בית חגלה צפונה והיה תצאותיו הגבול אל לשון ים המלח צפונה אל קצה הירדן נגבה זה גבול נגב׃"));
hebsuperobject.biblemap.put("b6_18_20", new hebsuperobject(6,18,20,"והירדן יגבל אתו לפאת קדמה זאת נחלת בני בנימן לגבולתיה סביב למשפחתם׃"));
hebsuperobject.biblemap.put("b6_18_21", new hebsuperobject(6,18,21,"והיו הערים למטה בני בנימן למשפחותיהם יריחו ובית חגלה ועמק קציץ׃"));
hebsuperobject.biblemap.put("b6_18_22", new hebsuperobject(6,18,22,"ובית הערבה וצמרים ובית אל׃"));
hebsuperobject.biblemap.put("b6_18_23", new hebsuperobject(6,18,23,"והעוים והפרה ועפרה׃"));
hebsuperobject.biblemap.put("b6_18_24", new hebsuperobject(6,18,24,"וכפר העמני והעפני וגבע ערים שתים עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_18_25", new hebsuperobject(6,18,25,"גבעון והרמה ובארות׃"));
hebsuperobject.biblemap.put("b6_18_26", new hebsuperobject(6,18,26,"והמצפה והכפירה והמצה׃"));
hebsuperobject.biblemap.put("b6_18_27", new hebsuperobject(6,18,27,"ורקם וירפאל ותראלה׃"));
hebsuperobject.biblemap.put("b6_18_28", new hebsuperobject(6,18,28,"וצלע האלף והיבוסי היא ירושלם גבעת קרית ערים ארבע עשרה וחצריהן זאת נחלת בני בנימן למשפחתם׃"));
hebsuperobject.biblemap.put("b6_19_1", new hebsuperobject(6,19,1,"ויצא הגורל השני לשמעון למטה בני שמעון למשפחותם ויהי נחלתם בתוך נחלת בני יהודה׃"));
hebsuperobject.biblemap.put("b6_19_2", new hebsuperobject(6,19,2,"ויהי להם בנחלתם באר שבע ושבע ומולדה׃"));
hebsuperobject.biblemap.put("b6_19_3", new hebsuperobject(6,19,3,"וחצר שועל ובלה ועצם׃"));
hebsuperobject.biblemap.put("b6_19_4", new hebsuperobject(6,19,4,"ואלתולד ובתול וחרמה׃"));
hebsuperobject.biblemap.put("b6_19_5", new hebsuperobject(6,19,5,"וצקלג ובית המרכבות וחצר סוסה׃"));
hebsuperobject.biblemap.put("b6_19_6", new hebsuperobject(6,19,6,"ובית לבאות ושרוחן ערים שלש עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_7", new hebsuperobject(6,19,7,"עין רמון ועתר ועשן ערים ארבע וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_8", new hebsuperobject(6,19,8,"וכל החצרים אשר סביבות הערים האלה עד בעלת באר ראמת נגב זאת נחלת מטה בני שמעון למשפחתם׃"));
hebsuperobject.biblemap.put("b6_19_9", new hebsuperobject(6,19,9,"מחבל בני יהודה נחלת בני שמעון כי היה חלק בני יהודה רב מהם וינחלו בני שמעון בתוך נחלתם׃"));
hebsuperobject.biblemap.put("b6_19_10", new hebsuperobject(6,19,10,"ויעל הגורל השלישי לבני זבולן למשפחתם ויהי גבול נחלתם עד שריד׃"));
hebsuperobject.biblemap.put("b6_19_11", new hebsuperobject(6,19,11,"ועלה גבולם לימה ומרעלה ופגע בדבשת ופגע אל הנחל אשר על פני יקנעם׃"));
hebsuperobject.biblemap.put("b6_19_12", new hebsuperobject(6,19,12,"ושב משריד קדמה מזרח השמש על גבול כסלת תבר ויצא אל הדברת ועלה יפיע׃"));
hebsuperobject.biblemap.put("b6_19_13", new hebsuperobject(6,19,13,"ומשם עבר קדמה מזרחה גתה חפר עתה קצין ויצא רמון המתאר הנעה׃"));
hebsuperobject.biblemap.put("b6_19_14", new hebsuperobject(6,19,14,"ונסב אתו הגבול מצפון חנתן והיו תצאתיו גי יפתח אל׃"));
hebsuperobject.biblemap.put("b6_19_15", new hebsuperobject(6,19,15,"וקטת ונהלל ושמרון וידאלה ובית לחם ערים שתים עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_16", new hebsuperobject(6,19,16,"זאת נחלת בני זבולן למשפחותם הערים האלה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_17", new hebsuperobject(6,19,17,"ליששכר יצא הגורל הרביעי לבני יששכר למשפחותם׃"));
hebsuperobject.biblemap.put("b6_19_18", new hebsuperobject(6,19,18,"ויהי גבולם יזרעאלה והכסולת ושונם׃"));
hebsuperobject.biblemap.put("b6_19_19", new hebsuperobject(6,19,19,"וחפרים ושיאן ואנחרת׃"));
hebsuperobject.biblemap.put("b6_19_20", new hebsuperobject(6,19,20,"והרבית וקשיון ואבץ׃"));
hebsuperobject.biblemap.put("b6_19_21", new hebsuperobject(6,19,21,"ורמת ועין גנים ועין חדה ובית פצץ׃"));
hebsuperobject.biblemap.put("b6_19_22", new hebsuperobject(6,19,22,"ופגע הגבול בתבור ושחצומה ובית שמש והיו תצאות גבולם הירדן ערים שש עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_23", new hebsuperobject(6,19,23,"זאת נחלת מטה בני יששכר למשפחתם הערים וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_24", new hebsuperobject(6,19,24,"ויצא הגורל החמישי למטה בני אשר למשפחותם׃"));
hebsuperobject.biblemap.put("b6_19_25", new hebsuperobject(6,19,25,"ויהי גבולם חלקת וחלי ובטן ואכשף׃"));
hebsuperobject.biblemap.put("b6_19_26", new hebsuperobject(6,19,26,"ואלמלך ועמעד ומשאל ופגע בכרמל הימה ובשיחור לבנת׃"));
hebsuperobject.biblemap.put("b6_19_27", new hebsuperobject(6,19,27,"ושב מזרח השמש בית דגן ופגע בזבלון ובגי יפתח אל צפונה בית העמק ונעיאל ויצא אל כבול משמאל׃"));
hebsuperobject.biblemap.put("b6_19_28", new hebsuperobject(6,19,28,"ועברן ורחב וחמון וקנה עד צידון רבה׃"));
hebsuperobject.biblemap.put("b6_19_29", new hebsuperobject(6,19,29,"ושב הגבול הרמה ועד עיר מבצר צר ושב הגבול חסה ויהיו תצאתיו הימה מחבל אכזיבה׃"));
hebsuperobject.biblemap.put("b6_19_30", new hebsuperobject(6,19,30,"ועמה ואפק ורחב ערים עשרים ושתים וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_31", new hebsuperobject(6,19,31,"זאת נחלת מטה בני אשר למשפחתם הערים האלה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_32", new hebsuperobject(6,19,32,"לבני נפתלי יצא הגורל הששי לבני נפתלי למשפחתם׃"));
hebsuperobject.biblemap.put("b6_19_33", new hebsuperobject(6,19,33,"ויהי גבולם מחלף מאלון בצעננים ואדמי הנקב ויבנאל עד לקום ויהי תצאתיו הירדן׃"));
hebsuperobject.biblemap.put("b6_19_34", new hebsuperobject(6,19,34,"ושב הגבול ימה אזנות תבור ויצא משם חוקקה ופגע בזבלון מנגב ובאשר פגע מים וביהודה הירדן מזרח השמש׃"));
hebsuperobject.biblemap.put("b6_19_35", new hebsuperobject(6,19,35,"וערי מבצר הצדים צר וחמת רקת וכנרת׃"));
hebsuperobject.biblemap.put("b6_19_36", new hebsuperobject(6,19,36,"ואדמה והרמה וחצור׃"));
hebsuperobject.biblemap.put("b6_19_37", new hebsuperobject(6,19,37,"וקדש ואדרעי ועין חצור׃"));
hebsuperobject.biblemap.put("b6_19_38", new hebsuperobject(6,19,38,"ויראון ומגדל אל חרם ובית ענת ובית שמש ערים תשע עשרה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_39", new hebsuperobject(6,19,39,"זאת נחלת מטה בני נפתלי למשפחתם הערים וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_40", new hebsuperobject(6,19,40,"למטה בני דן למשפחתם יצא הגורל השביעי׃"));
hebsuperobject.biblemap.put("b6_19_41", new hebsuperobject(6,19,41,"ויהי גבול נחלתם צרעה ואשתאול ועיר שמש׃"));
hebsuperobject.biblemap.put("b6_19_42", new hebsuperobject(6,19,42,"ושעלבין ואילון ויתלה׃"));
hebsuperobject.biblemap.put("b6_19_43", new hebsuperobject(6,19,43,"ואילון ותמנתה ועקרון׃"));
hebsuperobject.biblemap.put("b6_19_44", new hebsuperobject(6,19,44,"ואלתקה וגבתון ובעלת׃"));
hebsuperobject.biblemap.put("b6_19_45", new hebsuperobject(6,19,45,"ויהד ובני ברק וגת רמון׃"));
hebsuperobject.biblemap.put("b6_19_46", new hebsuperobject(6,19,46,"ומי הירקון והרקון עם הגבול מול יפו׃"));
hebsuperobject.biblemap.put("b6_19_47", new hebsuperobject(6,19,47,"ויצא גבול בני דן מהם ויעלו בני דן וילחמו עם לשם וילכדו אותה ויכו אותה לפי חרב וירשו אותה וישבו בה ויקראו ללשם דן כשם דן אביהם׃"));
hebsuperobject.biblemap.put("b6_19_48", new hebsuperobject(6,19,48,"זאת נחלת מטה בני דן למשפחתם הערים האלה וחצריהן׃"));
hebsuperobject.biblemap.put("b6_19_49", new hebsuperobject(6,19,49,"ויכלו לנחל את הארץ לגבולתיה ויתנו בני ישראל נחלה ליהושע בן נון בתוכם׃"));
hebsuperobject.biblemap.put("b6_19_50", new hebsuperobject(6,19,50,"על פי יהוה נתנו לו את העיר אשר שאל את תמנת סרח בהר אפרים ויבנה את העיר וישב בה׃"));
hebsuperobject.biblemap.put("b6_19_51", new hebsuperobject(6,19,51,"אלה הנחלת אשר נחלו אלעזר הכהן ויהושע בן נון וראשי האבות למטות בני ישראל בגורל בשלה לפני יהוה פתח אהל מועד ויכלו מחלק את הארץ׃"));
hebsuperobject.biblemap.put("b6_20_1", new hebsuperobject(6,20,1,"וידבר יהוה אל יהושע לאמר׃"));
hebsuperobject.biblemap.put("b6_20_2", new hebsuperobject(6,20,2,"דבר אל בני ישראל לאמר תנו לכם את ערי המקלט אשר דברתי אליכם ביד משה׃"));
hebsuperobject.biblemap.put("b6_20_3", new hebsuperobject(6,20,3,"לנוס שמה רוצח מכה נפש בשגגה בבלי דעת והיו לכם למקלט מגאל הדם׃"));
hebsuperobject.biblemap.put("b6_20_4", new hebsuperobject(6,20,4,"ונס אל אחת מהערים האלה ועמד פתח שער העיר ודבר באזני זקני העיר ההיא את דבריו ואספו אתו העירה אליהם ונתנו לו מקום וישב עמם׃"));
hebsuperobject.biblemap.put("b6_20_5", new hebsuperobject(6,20,5,"וכי ירדף גאל הדם אחריו ולא יסגרו את הרצח בידו כי בבלי דעת הכה את רעהו ולא שנא הוא לו מתמול שלשום׃"));
hebsuperobject.biblemap.put("b6_20_6", new hebsuperobject(6,20,6,"וישב בעיר ההיא עד עמדו לפני העדה למשפט עד מות הכהן הגדול אשר יהיה בימים ההם אז ישוב הרוצח ובא אל עירו ואל ביתו אל העיר אשר נס משם׃"));
hebsuperobject.biblemap.put("b6_20_7", new hebsuperobject(6,20,7,"ויקדשו את קדש בגליל בהר נפתלי ואת שכם בהר אפרים ואת קרית ארבע היא חברון בהר יהודה׃"));
hebsuperobject.biblemap.put("b6_20_8", new hebsuperobject(6,20,8,"ומעבר לירדן יריחו מזרחה נתנו את בצר במדבר במישר ממטה ראובן ואת ראמת בגלעד ממטה גד ואת גלון בבשן ממטה מנשה׃"));
hebsuperobject.biblemap.put("b6_20_9", new hebsuperobject(6,20,9,"אלה היו ערי המועדה לכל בני ישראל ולגר הגר בתוכם לנוס שמה כל מכה נפש בשגגה ולא ימות ביד גאל הדם עד עמדו לפני העדה׃"));
hebsuperobject.biblemap.put("b6_21_1", new hebsuperobject(6,21,1,"ויגשו ראשי אבות הלוים אל אלעזר הכהן ואל יהושע בן נון ואל ראשי אבות המטות לבני ישראל׃"));
hebsuperobject.biblemap.put("b6_21_2", new hebsuperobject(6,21,2,"וידברו אליהם בשלה בארץ כנען לאמר יהוה צוה ביד משה לתת לנו ערים לשבת ומגרשיהן לבהמתנו׃"));
hebsuperobject.biblemap.put("b6_21_3", new hebsuperobject(6,21,3,"ויתנו בני ישראל ללוים מנחלתם אל פי יהוה את הערים האלה ואת מגרשיהן׃"));
hebsuperobject.biblemap.put("b6_21_4", new hebsuperobject(6,21,4,"ויצא הגורל למשפחת הקהתי ויהי לבני אהרן הכהן מן הלוים ממטה יהודה וממטה השמעני וממטה בנימן בגורל ערים שלש עשרה׃"));
hebsuperobject.biblemap.put("b6_21_5", new hebsuperobject(6,21,5,"ולבני קהת הנותרים ממשפחת מטה אפרים וממטה דן ומחצי מטה מנשה בגורל ערים עשר׃"));
hebsuperobject.biblemap.put("b6_21_6", new hebsuperobject(6,21,6,"ולבני גרשון ממשפחות מטה יששכר וממטה אשר וממטה נפתלי ומחצי מטה מנשה בבשן בגורל ערים שלש עשרה׃"));
hebsuperobject.biblemap.put("b6_21_7", new hebsuperobject(6,21,7,"לבני מררי למשפחתם ממטה ראובן וממטה גד וממטה זבולן ערים שתים עשרה׃"));
hebsuperobject.biblemap.put("b6_21_8", new hebsuperobject(6,21,8,"ויתנו בני ישראל ללוים את הערים האלה ואת מגרשיהן כאשר צוה יהוה ביד משה בגורל׃"));
hebsuperobject.biblemap.put("b6_21_9", new hebsuperobject(6,21,9,"ויתנו ממטה בני יהודה וממטה בני שמעון את הערים האלה אשר יקרא אתהן בשם׃"));
hebsuperobject.biblemap.put("b6_21_10", new hebsuperobject(6,21,10,"ויהי לבני אהרן ממשפחות הקהתי מבני לוי כי להם היה הגורל ראישנה׃"));
hebsuperobject.biblemap.put("b6_21_11", new hebsuperobject(6,21,11,"ויתנו להם את קרית ארבע אבי הענוק היא חברון בהר יהודה ואת מגרשה סביבתיה׃"));
hebsuperobject.biblemap.put("b6_21_12", new hebsuperobject(6,21,12,"ואת שדה העיר ואת חצריה נתנו לכלב בן יפנה באחזתו׃"));
hebsuperobject.biblemap.put("b6_21_13", new hebsuperobject(6,21,13,"ולבני אהרן הכהן נתנו את עיר מקלט הרצח את חברון ואת מגרשה ואת לבנה ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_14", new hebsuperobject(6,21,14,"ואת יתר ואת מגרשה ואת אשתמע ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_15", new hebsuperobject(6,21,15,"ואת חלן ואת מגרשה ואת דבר ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_16", new hebsuperobject(6,21,16,"ואת עין ואת מגרשה ואת יטה ואת מגרשה את בית שמש ואת מגרשה ערים תשע מאת שני השבטים האלה׃"));
hebsuperobject.biblemap.put("b6_21_17", new hebsuperobject(6,21,17,"וממטה בנימן את גבעון ואת מגרשה את גבע ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_18", new hebsuperobject(6,21,18,"את ענתות ואת מגרשה ואת עלמון ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_19", new hebsuperobject(6,21,19,"כל ערי בני אהרן הכהנים שלש עשרה ערים ומגרשיהן׃"));
hebsuperobject.biblemap.put("b6_21_20", new hebsuperobject(6,21,20,"ולמשפחות בני קהת הלוים הנותרים מבני קהת ויהי ערי גורלם ממטה אפרים׃"));
hebsuperobject.biblemap.put("b6_21_21", new hebsuperobject(6,21,21,"ויתנו להם את עיר מקלט הרצח את שכם ואת מגרשה בהר אפרים ואת גזר ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_22", new hebsuperobject(6,21,22,"ואת קבצים ואת מגרשה ואת בית חורן ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_23", new hebsuperobject(6,21,23,"וממטה דן את אלתקא ואת מגרשה את גבתון ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_24", new hebsuperobject(6,21,24,"את אילון ואת מגרשה את גת רמון ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_25", new hebsuperobject(6,21,25,"וממחצית מטה מנשה את תענך ואת מגרשה ואת גת רמון ואת מגרשה ערים שתים׃"));
hebsuperobject.biblemap.put("b6_21_26", new hebsuperobject(6,21,26,"כל ערים עשר ומגרשיהן למשפחות בני קהת הנותרים׃"));
hebsuperobject.biblemap.put("b6_21_27", new hebsuperobject(6,21,27,"ולבני גרשון ממשפחת הלוים מחצי מטה מנשה את עיר מקלט הרצח את גלון בבשן ואת מגרשה ואת בעשתרה ואת מגרשה ערים שתים׃"));
hebsuperobject.biblemap.put("b6_21_28", new hebsuperobject(6,21,28,"וממטה יששכר את קשיון ואת מגרשה את דברת ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_29", new hebsuperobject(6,21,29,"את ירמות ואת מגרשה את עין גנים ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_30", new hebsuperobject(6,21,30,"וממטה אשר את משאל ואת מגרשה את עבדון ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_31", new hebsuperobject(6,21,31,"את חלקת ואת מגרשה ואת רחב ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_32", new hebsuperobject(6,21,32,"וממטה נפתלי את עיר מקלט הרצח את קדש בגליל ואת מגרשה ואת חמת דאר ואת מגרשה ואת קרתן ואת מגרשה ערים שלש׃"));
hebsuperobject.biblemap.put("b6_21_33", new hebsuperobject(6,21,33,"כל ערי הגרשני למשפחתם שלש עשרה עיר ומגרשיהן׃"));
hebsuperobject.biblemap.put("b6_21_34", new hebsuperobject(6,21,34,"ולמשפחות בני מררי הלוים הנותרים מאת מטה זבולן את יקנעם ואת מגרשה את קרתה ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_35", new hebsuperobject(6,21,35,"את דמנה ואת מגרשה את נהלל ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_36", new hebsuperobject(6,21,36,"וממטה ראובן את בצר ואת מגרשה ואת יהצה ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_37", new hebsuperobject(6,21,37,"את קדמות ואת מגרשה ואת מיפעת ואת מגרשה ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_38", new hebsuperobject(6,21,38,"וממטה גד את עיר מקלט הרצח את רמת בגלעד ואת מגרשה ואת מחנים ואת מגרשה׃"));
hebsuperobject.biblemap.put("b6_21_39", new hebsuperobject(6,21,39,"את חשבון ואת מגרשה את יעזר ואת מגרשה כל ערים ארבע׃"));
hebsuperobject.biblemap.put("b6_21_40", new hebsuperobject(6,21,40,"כל הערים לבני מררי למשפחתם הנותרים ממשפחות הלוים ויהי גורלם ערים שתים עשרה׃"));
hebsuperobject.biblemap.put("b6_21_41", new hebsuperobject(6,21,41,"כל ערי הלוים בתוך אחזת בני ישראל ערים ארבעים ושמנה ומגרשיהן׃"));
hebsuperobject.biblemap.put("b6_21_42", new hebsuperobject(6,21,42,"תהיינה הערים האלה עיר עיר ומגרשיה סביבתיה כן לכל הערים האלה׃"));
hebsuperobject.biblemap.put("b6_21_43", new hebsuperobject(6,21,43,"ויתן יהוה לישראל את כל הארץ אשר נשבע לתת לאבותם וירשוה וישבו בה׃"));
hebsuperobject.biblemap.put("b6_21_44", new hebsuperobject(6,21,44,"וינח יהוה להם מסביב ככל אשר נשבע לאבותם ולא עמד איש בפניהם מכל איביהם את כל איביהם נתן יהוה בידם׃"));
hebsuperobject.biblemap.put("b6_21_45", new hebsuperobject(6,21,45,"לא נפל דבר מכל הדבר הטוב אשר דבר יהוה אל בית ישראל הכל בא׃"));
hebsuperobject.biblemap.put("b6_22_1", new hebsuperobject(6,22,1,"אז יקרא יהושע לראובני ולגדי ולחצי מטה מנשה׃"));
hebsuperobject.biblemap.put("b6_22_2", new hebsuperobject(6,22,2,"ויאמר אליהם אתם שמרתם את כל אשר צוה אתכם משה עבד יהוה ותשמעו בקולי לכל אשר צויתי אתכם׃"));
hebsuperobject.biblemap.put("b6_22_3", new hebsuperobject(6,22,3,"לא עזבתם את אחיכם זה ימים רבים עד היום הזה ושמרתם את משמרת מצות יהוה אלהיכם׃"));
hebsuperobject.biblemap.put("b6_22_4", new hebsuperobject(6,22,4,"ועתה הניח יהוה אלהיכם לאחיכם כאשר דבר להם ועתה פנו ולכו לכם לאהליכם אל ארץ אחזתכם אשר נתן לכם משה עבד יהוה בעבר הירדן׃"));
hebsuperobject.biblemap.put("b6_22_5", new hebsuperobject(6,22,5,"רק שמרו מאד לעשות את המצוה ואת התורה אשר צוה אתכם משה עבד יהוה לאהבה את יהוה אלהיכם וללכת בכל דרכיו ולשמר מצותיו ולדבקה בו ולעבדו בכל לבבכם ובכל נפשכם׃"));
hebsuperobject.biblemap.put("b6_22_6", new hebsuperobject(6,22,6,"ויברכם יהושע וישלחם וילכו אל אהליהם׃"));
hebsuperobject.biblemap.put("b6_22_7", new hebsuperobject(6,22,7,"ולחצי שבט המנשה נתן משה בבשן ולחציו נתן יהושע עם אחיהם מעבר הירדן ימה וגם כי שלחם יהושע אל אהליהם ויברכם׃"));
hebsuperobject.biblemap.put("b6_22_8", new hebsuperobject(6,22,8,"ויאמר אליהם לאמר בנכסים רבים שובו אל אהליכם ובמקנה רב מאד בכסף ובזהב ובנחשת ובברזל ובשלמות הרבה מאד חלקו שלל איביכם עם אחיכם׃"));
hebsuperobject.biblemap.put("b6_22_9", new hebsuperobject(6,22,9,"וישבו וילכו בני ראובן ובני גד וחצי שבט המנשה מאת בני ישראל משלה אשר בארץ כנען ללכת אל ארץ הגלעד אל ארץ אחזתם אשר נאחזו בה על פי יהוה ביד משה׃"));
hebsuperobject.biblemap.put("b6_22_10", new hebsuperobject(6,22,10,"ויבאו אל גלילות הירדן אשר בארץ כנען ויבנו בני ראובן ובני גד וחצי שבט המנשה שם מזבח על הירדן מזבח גדול למראה׃"));
hebsuperobject.biblemap.put("b6_22_11", new hebsuperobject(6,22,11,"וישמעו בני ישראל לאמר הנה בנו בני ראובן ובני גד וחצי שבט המנשה את המזבח אל מול ארץ כנען אל גלילות הירדן אל עבר בני ישראל׃"));
hebsuperobject.biblemap.put("b6_22_12", new hebsuperobject(6,22,12,"וישמעו בני ישראל ויקהלו כל עדת בני ישראל שלה לעלות עליהם לצבא׃"));
hebsuperobject.biblemap.put("b6_22_13", new hebsuperobject(6,22,13,"וישלחו בני ישראל אל בני ראובן ואל בני גד ואל חצי שבט מנשה אל ארץ הגלעד את פינחס בן אלעזר הכהן׃"));
hebsuperobject.biblemap.put("b6_22_14", new hebsuperobject(6,22,14,"ועשרה נשאים עמו נשיא אחד נשיא אחד לבית אב לכל מטות ישראל ואיש ראש בית אבותם המה לאלפי ישראל׃"));
hebsuperobject.biblemap.put("b6_22_15", new hebsuperobject(6,22,15,"ויבאו אל בני ראובן ואל בני גד ואל חצי שבט מנשה אל ארץ הגלעד וידברו אתם לאמר׃"));
hebsuperobject.biblemap.put("b6_22_16", new hebsuperobject(6,22,16,"כה אמרו כל עדת יהוה מה המעל הזה אשר מעלתם באלהי ישראל לשוב היום מאחרי יהוה בבנותכם לכם מזבח למרדכם היום ביהוה׃"));
hebsuperobject.biblemap.put("b6_22_17", new hebsuperobject(6,22,17,"המעט לנו את עון פעור אשר לא הטהרנו ממנו עד היום הזה ויהי הנגף בעדת יהוה׃"));
hebsuperobject.biblemap.put("b6_22_18", new hebsuperobject(6,22,18,"ואתם תשבו היום מאחרי יהוה והיה אתם תמרדו היום ביהוה ומחר אל כל עדת ישראל יקצף׃"));
hebsuperobject.biblemap.put("b6_22_19", new hebsuperobject(6,22,19,"ואך אם טמאה ארץ אחזתכם עברו לכם אל ארץ אחזת יהוה אשר שכן שם משכן יהוה והאחזו בתוכנו וביהוה אל תמרדו ואתנו אל תמרדו בבנתכם לכם מזבח מבלעדי מזבח יהוה אלהינו׃"));
hebsuperobject.biblemap.put("b6_22_20", new hebsuperobject(6,22,20,"הלוא עכן בן זרח מעל מעל בחרם ועל כל עדת ישראל היה קצף והוא איש אחד לא גוע בעונו׃"));
hebsuperobject.biblemap.put("b6_22_21", new hebsuperobject(6,22,21,"ויענו בני ראובן ובני גד וחצי שבט המנשה וידברו את ראשי אלפי ישראל׃"));
hebsuperobject.biblemap.put("b6_22_22", new hebsuperobject(6,22,22,"אל אלהים יהוה אל אלהים יהוה הוא ידע וישראל הוא ידע אם במרד ואם במעל ביהוה אל תושיענו היום הזה׃"));
hebsuperobject.biblemap.put("b6_22_23", new hebsuperobject(6,22,23,"לבנות לנו מזבח לשוב מאחרי יהוה ואם להעלות עליו עולה ומנחה ואם לעשות עליו זבחי שלמים יהוה הוא יבקש׃"));
hebsuperobject.biblemap.put("b6_22_24", new hebsuperobject(6,22,24,"ואם לא מדאגה מדבר עשינו את זאת לאמר מחר יאמרו בניכם לבנינו לאמר מה לכם וליהוה אלהי ישראל׃"));
hebsuperobject.biblemap.put("b6_22_25", new hebsuperobject(6,22,25,"וגבול נתן יהוה ביננו וביניכם בני ראובן ובני גד את הירדן אין לכם חלק ביהוה והשביתו בניכם את בנינו לבלתי ירא את יהוה׃"));
hebsuperobject.biblemap.put("b6_22_26", new hebsuperobject(6,22,26,"ונאמר נעשה נא לנו לבנות את המזבח לא לעולה ולא לזבח׃"));
hebsuperobject.biblemap.put("b6_22_27", new hebsuperobject(6,22,27,"כי עד הוא בינינו וביניכם ובין דרותינו אחרינו לעבד את עבדת יהוה לפניו בעלותינו ובזבחינו ובשלמינו ולא יאמרו בניכם מחר לבנינו אין לכם חלק ביהוה׃"));
hebsuperobject.biblemap.put("b6_22_28", new hebsuperobject(6,22,28,"ונאמר והיה כי יאמרו אלינו ואל דרתינו מחר ואמרנו ראו את תבנית מזבח יהוה אשר עשו אבותינו לא לעולה ולא לזבח כי עד הוא בינינו וביניכם׃"));
hebsuperobject.biblemap.put("b6_22_29", new hebsuperobject(6,22,29,"חלילה לנו ממנו למרד ביהוה ולשוב היום מאחרי יהוה לבנות מזבח לעלה למנחה ולזבח מלבד מזבח יהוה אלהינו אשר לפני משכנו׃"));
hebsuperobject.biblemap.put("b6_22_30", new hebsuperobject(6,22,30,"וישמע פינחס הכהן ונשיאי העדה וראשי אלפי ישראל אשר אתו את הדברים אשר דברו בני ראובן ובני גד ובני מנשה וייטב בעיניהם׃"));
hebsuperobject.biblemap.put("b6_22_31", new hebsuperobject(6,22,31,"ויאמר פינחס בן אלעזר הכהן אל בני ראובן ואל בני גד ואל בני מנשה היום ידענו כי בתוכנו יהוה אשר לא מעלתם ביהוה המעל הזה אז הצלתם את בני ישראל מיד יהוה׃"));
hebsuperobject.biblemap.put("b6_22_32", new hebsuperobject(6,22,32,"וישב פינחס בן אלעזר הכהן והנשיאים מאת בני ראובן ומאת בני גד מארץ הגלעד אל ארץ כנען אל בני ישראל וישבו אותם דבר׃"));
hebsuperobject.biblemap.put("b6_22_33", new hebsuperobject(6,22,33,"וייטב הדבר בעיני בני ישראל ויברכו אלהים בני ישראל ולא אמרו לעלות עליהם לצבא לשחת את הארץ אשר בני ראובן ובני גד ישבים בה׃"));
hebsuperobject.biblemap.put("b6_22_34", new hebsuperobject(6,22,34,"ויקראו בני ראובן ובני גד למזבח כי עד הוא בינתינו כי יהוה האלהים׃"));
hebsuperobject.biblemap.put("b6_23_1", new hebsuperobject(6,23,1,"ויהי מימים רבים אחרי אשר הניח יהוה לישראל מכל איביהם מסביב ויהושע זקן בא בימים׃"));
hebsuperobject.biblemap.put("b6_23_2", new hebsuperobject(6,23,2,"ויקרא יהושע לכל ישראל לזקניו ולראשיו ולשפטיו ולשטריו ויאמר אלהם אני זקנתי באתי בימים׃"));
hebsuperobject.biblemap.put("b6_23_3", new hebsuperobject(6,23,3,"ואתם ראיתם את כל אשר עשה יהוה אלהיכם לכל הגוים האלה מפניכם כי יהוה אלהיכם הוא הנלחם לכם׃"));
hebsuperobject.biblemap.put("b6_23_4", new hebsuperobject(6,23,4,"ראו הפלתי לכם את הגוים הנשארים האלה בנחלה לשבטיכם מן הירדן וכל הגוים אשר הכרתי והים הגדול מבוא השמש׃"));
hebsuperobject.biblemap.put("b6_23_5", new hebsuperobject(6,23,5,"ויהוה אלהיכם הוא יהדפם מפניכם והוריש אתם מלפניכם וירשתם את ארצם כאשר דבר יהוה אלהיכם לכם׃"));
hebsuperobject.biblemap.put("b6_23_6", new hebsuperobject(6,23,6,"וחזקתם מאד לשמר ולעשות את כל הכתוב בספר תורת משה לבלתי סור ממנו ימין ושמאול׃"));
hebsuperobject.biblemap.put("b6_23_7", new hebsuperobject(6,23,7,"לבלתי בוא בגוים האלה הנשארים האלה אתכם ובשם אלהיהם לא תזכירו ולא תשביעו ולא תעבדום ולא תשתחוו להם׃"));
hebsuperobject.biblemap.put("b6_23_8", new hebsuperobject(6,23,8,"כי אם ביהוה אלהיכם תדבקו כאשר עשיתם עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_23_9", new hebsuperobject(6,23,9,"ויורש יהוה מפניכם גוים גדלים ועצומים ואתם לא עמד איש בפניכם עד היום הזה׃"));
hebsuperobject.biblemap.put("b6_23_10", new hebsuperobject(6,23,10,"איש אחד מכם ירדף אלף כי יהוה אלהיכם הוא הנלחם לכם כאשר דבר לכם׃"));
hebsuperobject.biblemap.put("b6_23_11", new hebsuperobject(6,23,11,"ונשמרתם מאד לנפשתיכם לאהבה את יהוה אלהיכם׃"));
hebsuperobject.biblemap.put("b6_23_12", new hebsuperobject(6,23,12,"כי אם שוב תשובו ודבקתם ביתר הגוים האלה הנשארים האלה אתכם והתחתנתם בהם ובאתם בהם והם בכם׃"));
hebsuperobject.biblemap.put("b6_23_13", new hebsuperobject(6,23,13,"ידוע תדעו כי לא יוסיף יהוה אלהיכם להוריש את הגוים האלה מלפניכם והיו לכם לפח ולמוקש ולשטט בצדיכם ולצננים בעיניכם עד אבדכם מעל האדמה הטובה הזאת אשר נתן לכם יהוה אלהיכם׃"));
hebsuperobject.biblemap.put("b6_23_14", new hebsuperobject(6,23,14,"והנה אנכי הולך היום בדרך כל הארץ וידעתם בכל לבבכם ובכל נפשכם כי לא נפל דבר אחד מכל הדברים הטובים אשר דבר יהוה אלהיכם עליכם הכל באו לכם לא נפל ממנו דבר אחד׃"));
hebsuperobject.biblemap.put("b6_23_15", new hebsuperobject(6,23,15,"והיה כאשר בא עליכם כל הדבר הטוב אשר דבר יהוה אלהיכם אליכם כן יביא יהוה עליכם את כל הדבר הרע עד השמידו אותכם מעל האדמה הטובה הזאת אשר נתן לכם יהוה אלהיכם׃"));
hebsuperobject.biblemap.put("b6_23_16", new hebsuperobject(6,23,16,"בעברכם את ברית יהוה אלהיכם אשר צוה אתכם והלכתם ועבדתם אלהים אחרים והשתחויתם להם וחרה אף יהוה בכם ואבדתם מהרה מעל הארץ הטובה אשר נתן לכם׃"));
hebsuperobject.biblemap.put("b6_24_1", new hebsuperobject(6,24,1,"ויאסף יהושע את כל שבטי ישראל שכמה ויקרא לזקני ישראל ולראשיו ולשפטיו ולשטריו ויתיצבו לפני האלהים׃"));
hebsuperobject.biblemap.put("b6_24_2", new hebsuperobject(6,24,2,"ויאמר יהושע אל כל העם כה אמר יהוה אלהי ישראל בעבר הנהר ישבו אבותיכם מעולם תרח אבי אברהם ואבי נחור ויעבדו אלהים אחרים׃"));
hebsuperobject.biblemap.put("b6_24_3", new hebsuperobject(6,24,3,"ואקח את אביכם את אברהם מעבר הנהר ואולך אותו בכל ארץ כנען וארב את זרעו ואתן לו את יצחק׃"));
hebsuperobject.biblemap.put("b6_24_4", new hebsuperobject(6,24,4,"ואתן ליצחק את יעקב ואת עשו ואתן לעשו את הר שעיר לרשת אותו ויעקב ובניו ירדו מצרים׃"));
hebsuperobject.biblemap.put("b6_24_5", new hebsuperobject(6,24,5,"ואשלח את משה ואת אהרן ואגף את מצרים כאשר עשיתי בקרבו ואחר הוצאתי אתכם׃"));
hebsuperobject.biblemap.put("b6_24_6", new hebsuperobject(6,24,6,"ואוציא את אבותיכם ממצרים ותבאו הימה וירדפו מצרים אחרי אבותיכם ברכב ובפרשים ים סוף׃"));
hebsuperobject.biblemap.put("b6_24_7", new hebsuperobject(6,24,7,"ויצעקו אל יהוה וישם מאפל ביניכם ובין המצרים ויבא עליו את הים ויכסהו ותראינה עיניכם את אשר עשיתי במצרים ותשבו במדבר ימים רבים׃"));
hebsuperobject.biblemap.put("b6_24_8", new hebsuperobject(6,24,8,"ואביאה אתכם אל ארץ האמרי היושב בעבר הירדן וילחמו אתכם ואתן אותם בידכם ותירשו את ארצם ואשמידם מפניכם׃"));
hebsuperobject.biblemap.put("b6_24_9", new hebsuperobject(6,24,9,"ויקם בלק בן צפור מלך מואב וילחם בישראל וישלח ויקרא לבלעם בן בעור לקלל אתכם׃"));
hebsuperobject.biblemap.put("b6_24_10", new hebsuperobject(6,24,10,"ולא אביתי לשמע לבלעם ויברך ברוך אתכם ואצל אתכם מידו׃"));
hebsuperobject.biblemap.put("b6_24_11", new hebsuperobject(6,24,11,"ותעברו את הירדן ותבאו אל יריחו וילחמו בכם בעלי יריחו האמרי והפרזי והכנעני והחתי והגרגשי החוי והיבוסי ואתן אותם בידכם׃"));
hebsuperobject.biblemap.put("b6_24_12", new hebsuperobject(6,24,12,"ואשלח לפניכם את הצרעה ותגרש אותם מפניכם שני מלכי האמרי לא בחרבך ולא בקשתך׃"));
hebsuperobject.biblemap.put("b6_24_13", new hebsuperobject(6,24,13,"ואתן לכם ארץ אשר לא יגעת בה וערים אשר לא בניתם ותשבו בהם כרמים וזיתים אשר לא נטעתם אתם אכלים׃"));
hebsuperobject.biblemap.put("b6_24_14", new hebsuperobject(6,24,14,"ועתה יראו את יהוה ועבדו אתו בתמים ובאמת והסירו את אלהים אשר עבדו אבותיכם בעבר הנהר ובמצרים ועבדו את יהוה׃"));
hebsuperobject.biblemap.put("b6_24_15", new hebsuperobject(6,24,15,"ואם רע בעיניכם לעבד את יהוה בחרו לכם היום את מי תעבדון אם את אלהים אשר עבדו אבותיכם אשר בעבר הנהר ואם את אלהי האמרי אשר אתם ישבים בארצם ואנכי וביתי נעבד את יהוה׃"));
hebsuperobject.biblemap.put("b6_24_16", new hebsuperobject(6,24,16,"ויען העם ויאמר חלילה לנו מעזב את יהוה לעבד אלהים אחרים׃"));
hebsuperobject.biblemap.put("b6_24_17", new hebsuperobject(6,24,17,"כי יהוה אלהינו הוא המעלה אתנו ואת אבותינו מארץ מצרים מבית עבדים ואשר עשה לעינינו את האתות הגדלות האלה וישמרנו בכל הדרך אשר הלכנו בה ובכל העמים אשר עברנו בקרבם׃"));
hebsuperobject.biblemap.put("b6_24_18", new hebsuperobject(6,24,18,"ויגרש יהוה את כל העמים ואת האמרי ישב הארץ מפנינו גם אנחנו נעבד את יהוה כי הוא אלהינו׃"));
hebsuperobject.biblemap.put("b6_24_19", new hebsuperobject(6,24,19,"ויאמר יהושע אל העם לא תוכלו לעבד את יהוה כי אלהים קדשים הוא אל קנוא הוא לא ישא לפשעכם ולחטאותיכם׃"));
hebsuperobject.biblemap.put("b6_24_20", new hebsuperobject(6,24,20,"כי תעזבו את יהוה ועבדתם אלהי נכר ושב והרע לכם וכלה אתכם אחרי אשר היטיב לכם׃"));
hebsuperobject.biblemap.put("b6_24_21", new hebsuperobject(6,24,21,"ויאמר העם אל יהושע לא כי את יהוה נעבד׃"));
hebsuperobject.biblemap.put("b6_24_22", new hebsuperobject(6,24,22,"ויאמר יהושע אל העם עדים אתם בכם כי אתם בחרתם לכם את יהוה לעבד אותו ויאמרו עדים׃"));
hebsuperobject.biblemap.put("b6_24_23", new hebsuperobject(6,24,23,"ועתה הסירו את אלהי הנכר אשר בקרבכם והטו את לבבכם אל יהוה אלהי ישראל׃"));
hebsuperobject.biblemap.put("b6_24_24", new hebsuperobject(6,24,24,"ויאמרו העם אל יהושע את יהוה אלהינו נעבד ובקולו נשמע׃"));
hebsuperobject.biblemap.put("b6_24_25", new hebsuperobject(6,24,25,"ויכרת יהושע ברית לעם ביום ההוא וישם לו חק ומשפט בשכם׃"));
hebsuperobject.biblemap.put("b6_24_26", new hebsuperobject(6,24,26,"ויכתב יהושע את הדברים האלה בספר תורת אלהים ויקח אבן גדולה ויקימה שם תחת האלה אשר במקדש יהוה׃"));
hebsuperobject.biblemap.put("b6_24_27", new hebsuperobject(6,24,27,"ויאמר יהושע אל כל העם הנה האבן הזאת תהיה בנו לעדה כי היא שמעה את כל אמרי יהוה אשר דבר עמנו והיתה בכם לעדה פן תכחשון באלהיכם׃"));
hebsuperobject.biblemap.put("b6_24_28", new hebsuperobject(6,24,28,"וישלח יהושע את העם איש לנחלתו׃"));
hebsuperobject.biblemap.put("b6_24_29", new hebsuperobject(6,24,29,"ויהי אחרי הדברים האלה וימת יהושע בן נון עבד יהוה בן מאה ועשר שנים׃"));
hebsuperobject.biblemap.put("b6_24_30", new hebsuperobject(6,24,30,"ויקברו אתו בגבול נחלתו בתמנת סרח אשר בהר אפרים מצפון להר געש׃"));
hebsuperobject.biblemap.put("b6_24_31", new hebsuperobject(6,24,31,"ויעבד ישראל את יהוה כל ימי יהושע וכל ימי הזקנים אשר האריכו ימים אחרי יהושע ואשר ידעו את כל מעשה יהוה אשר עשה לישראל׃"));
hebsuperobject.biblemap.put("b6_24_32", new hebsuperobject(6,24,32,"ואת עצמות יוסף אשר העלו בני ישראל ממצרים קברו בשכם בחלקת השדה אשר קנה יעקב מאת בני חמור אבי שכם במאה קשיטה ויהיו לבני יוסף לנחלה׃"));
hebsuperobject.biblemap.put("b6_24_33", new hebsuperobject(6,24,33,"ואלעזר בן אהרן מת ויקברו אתו בגבעת פינחס בנו אשר נתן לו בהר אפרים׃"));

}

}