package heb.bible;

public class hebbible27 {

public hebbible27() {

putmapbible27();

}

private void putmapbible27() {

hebsuperobject.biblemap.put("b27_1_1", new hebsuperobject(27,1,1,"בשנת שלוש למלכות יהויקים מלך יהודה בא נבוכדנאצר מלך בבל ירושלם ויצר עליה׃"));
hebsuperobject.biblemap.put("b27_1_2", new hebsuperobject(27,1,2,"ויתן אדני בידו את יהויקים מלך יהודה ומקצת כלי בית האלהים ויביאם ארץ שנער בית אלהיו ואת הכלים הביא בית אוצר אלהיו׃"));
hebsuperobject.biblemap.put("b27_1_3", new hebsuperobject(27,1,3,"ויאמר המלך לאשפנז רב סריסיו להביא מבני ישראל ומזרע המלוכה ומן הפרתמים׃"));
hebsuperobject.biblemap.put("b27_1_4", new hebsuperobject(27,1,4,"ילדים אשר אין בהם כל מאום וטובי מראה ומשכילים בכל חכמה וידעי דעת ומביני מדע ואשר כח בהם לעמד בהיכל המלך וללמדם ספר ולשון כשדים׃"));
hebsuperobject.biblemap.put("b27_1_5", new hebsuperobject(27,1,5,"וימן להם המלך דבר יום ביומו מפת בג המלך ומיין משתיו ולגדלם שנים שלוש ומקצתם יעמדו לפני המלך׃"));
hebsuperobject.biblemap.put("b27_1_6", new hebsuperobject(27,1,6,"ויהי בהם מבני יהודה דניאל חנניה מישאל ועזריה׃"));
hebsuperobject.biblemap.put("b27_1_7", new hebsuperobject(27,1,7,"וישם להם שר הסריסים שמות וישם לדניאל בלטשאצר ולחנניה שדרך ולמישאל מישך ולעזריה עבד נגו׃"));
hebsuperobject.biblemap.put("b27_1_8", new hebsuperobject(27,1,8,"וישם דניאל על לבו אשר לא יתגאל בפתבג המלך וביין משתיו ויבקש משר הסריסים אשר לא יתגאל׃"));
hebsuperobject.biblemap.put("b27_1_9", new hebsuperobject(27,1,9,"ויתן האלהים את דניאל לחסד ולרחמים לפני שר הסריסים׃"));
hebsuperobject.biblemap.put("b27_1_10", new hebsuperobject(27,1,10,"ויאמר שר הסריסים לדניאל ירא אני את אדני המלך אשר מנה את מאכלכם ואת משתיכם אשר למה יראה את פניכם זעפים מן הילדים אשר כגילכם וחיבתם את ראשי למלך׃"));
hebsuperobject.biblemap.put("b27_1_11", new hebsuperobject(27,1,11,"ויאמר דניאל אל המלצר אשר מנה שר הסריסים על דניאל חנניה מישאל ועזריה׃"));
hebsuperobject.biblemap.put("b27_1_12", new hebsuperobject(27,1,12,"נס נא את עבדיך ימים עשרה ויתנו לנו מן הזרעים ונאכלה ומים ונשתה׃"));
hebsuperobject.biblemap.put("b27_1_13", new hebsuperobject(27,1,13,"ויראו לפניך מראינו ומראה הילדים האכלים את פתבג המלך וכאשר תראה עשה עם עבדיך׃"));
hebsuperobject.biblemap.put("b27_1_14", new hebsuperobject(27,1,14,"וישמע להם לדבר הזה וינסם ימים עשרה׃"));
hebsuperobject.biblemap.put("b27_1_15", new hebsuperobject(27,1,15,"ומקצת ימים עשרה נראה מראיהם טוב ובריאי בשר מן כל הילדים האכלים את פתבג המלך׃"));
hebsuperobject.biblemap.put("b27_1_16", new hebsuperobject(27,1,16,"ויהי המלצר נשא את פתבגם ויין משתיהם ונתן להם זרענים׃"));
hebsuperobject.biblemap.put("b27_1_17", new hebsuperobject(27,1,17,"והילדים האלה ארבעתם נתן להם האלהים מדע והשכל בכל ספר וחכמה ודניאל הבין בכל חזון וחלמות׃"));
hebsuperobject.biblemap.put("b27_1_18", new hebsuperobject(27,1,18,"ולמקצת הימים אשר אמר המלך להביאם ויביאם שר הסריסים לפני נבכדנצר׃"));
hebsuperobject.biblemap.put("b27_1_19", new hebsuperobject(27,1,19,"וידבר אתם המלך ולא נמצא מכלם כדניאל חנניה מישאל ועזריה ויעמדו לפני המלך׃"));
hebsuperobject.biblemap.put("b27_1_20", new hebsuperobject(27,1,20,"וכל דבר חכמת בינה אשר בקש מהם המלך וימצאם עשר ידות על כל החרטמים האשפים אשר בכל מלכותו׃"));
hebsuperobject.biblemap.put("b27_1_21", new hebsuperobject(27,1,21,"ויהי דניאל עד שנת אחת לכורש המלך׃"));
hebsuperobject.biblemap.put("b27_2_1", new hebsuperobject(27,2,1,"ובשנת שתים למלכות נבכדנצר חלם נבכדנצר חלמות ותתפעם רוחו ושנתו נהיתה עליו׃"));
hebsuperobject.biblemap.put("b27_2_2", new hebsuperobject(27,2,2,"ויאמר המלך לקרא לחרטמים ולאשפים ולמכשפים ולכשדים להגיד למלך חלמתיו ויבאו ויעמדו לפני המלך׃"));
hebsuperobject.biblemap.put("b27_2_3", new hebsuperobject(27,2,3,"ויאמר להם המלך חלום חלמתי ותפעם רוחי לדעת את החלום׃"));
hebsuperobject.biblemap.put("b27_2_4", new hebsuperobject(27,2,4,"וידברו הכשדים למלך ארמית מלכא לעלמין חיי אמר חלמא לעבדיך ופשרא נחוא׃"));
hebsuperobject.biblemap.put("b27_2_5", new hebsuperobject(27,2,5,"ענה מלכא ואמר לכשדיא מלתא מני אזדא הן לא תהודעונני חלמא ופשרה הדמין תתעבדון ובתיכון נולי יתשמון׃"));
hebsuperobject.biblemap.put("b27_2_6", new hebsuperobject(27,2,6,"והן חלמא ופשרה תהחון מתנן ונבזבה ויקר שגיא תקבלון מן קדמי להן חלמא ופשרה החוני׃"));
hebsuperobject.biblemap.put("b27_2_7", new hebsuperobject(27,2,7,"ענו תנינות ואמרין מלכא חלמא יאמר לעבדוהי ופשרה נהחוה׃"));
hebsuperobject.biblemap.put("b27_2_8", new hebsuperobject(27,2,8,"ענה מלכא ואמר מן יציב ידע אנה די עדנא אנתון זבנין כל קבל די חזיתון די אזדא מני מלתא׃"));
hebsuperobject.biblemap.put("b27_2_9", new hebsuperobject(27,2,9,"די הן חלמא לא תהודענני חדה היא דתכון ומלה כדבה ושחיתה הזמנתון למאמר קדמי עד די עדנא ישתנא להן חלמא אמרו לי ואנדע די פשרה תהחונני׃"));
hebsuperobject.biblemap.put("b27_2_10", new hebsuperobject(27,2,10,"ענו כשדיא קדם מלכא ואמרין לא איתי אנש על יבשתא די מלת מלכא יוכל להחויה כל קבל די כל מלך רב ושליט מלה כדנה לא שאל לכל חרטם ואשף וכשדי׃"));
hebsuperobject.biblemap.put("b27_2_11", new hebsuperobject(27,2,11,"ומלתא די מלכה שאל יקירה ואחרן לא איתי די יחונה קדם מלכא להן אלהין די מדרהון עם בשרא לא איתוהי׃"));
hebsuperobject.biblemap.put("b27_2_12", new hebsuperobject(27,2,12,"כל קבל דנה מלכא בנס וקצף שגיא ואמר להובדה לכל חכימי בבל׃"));
hebsuperobject.biblemap.put("b27_2_13", new hebsuperobject(27,2,13,"ודתא נפקת וחכימיא מתקטלין ובעו דניאל וחברוהי להתקטלה׃"));
hebsuperobject.biblemap.put("b27_2_14", new hebsuperobject(27,2,14,"באדין דניאל התיב עטא וטעם לאריוך רב טבחיא די מלכא די נפק לקטלה לחכימי בבל׃"));
hebsuperobject.biblemap.put("b27_2_15", new hebsuperobject(27,2,15,"ענה ואמר לאריוך שליטא די מלכא על מה דתא מהחצפה מן קדם מלכא אדין מלתא הודע אריוך לדניאל׃"));
hebsuperobject.biblemap.put("b27_2_16", new hebsuperobject(27,2,16,"ודניאל על ובעה מן מלכא די זמן ינתן לה ופשרא להחויה למלכא׃"));
hebsuperobject.biblemap.put("b27_2_17", new hebsuperobject(27,2,17,"אדין דניאל לביתה אזל ולחנניה מישאל ועזריה חברוהי מלתא הודע׃"));
hebsuperobject.biblemap.put("b27_2_18", new hebsuperobject(27,2,18,"ורחמין למבעא מן קדם אלה שמיא על רזה דנה די לא יהבדון דניאל וחברוהי עם שאר חכימי בבל׃"));
hebsuperobject.biblemap.put("b27_2_19", new hebsuperobject(27,2,19,"אדין לדניאל בחזוא די ליליא רזה גלי אדין דניאל ברך לאלה שמיא׃"));
hebsuperobject.biblemap.put("b27_2_20", new hebsuperobject(27,2,20,"ענה דניאל ואמר להוא שמה די אלהא מברך מן עלמא ועד עלמא די חכמתא וגבורתא די לה היא׃"));
hebsuperobject.biblemap.put("b27_2_21", new hebsuperobject(27,2,21,"והוא מהשנא עדניא וזמניא מהעדה מלכין ומהקים מלכין יהב חכמתא לחכימין ומנדעא לידעי בינה׃"));
hebsuperobject.biblemap.put("b27_2_22", new hebsuperobject(27,2,22,"הוא גלא עמיקתא ומסתרתא ידע מה בחשוכא ונהירא עמה שרא׃"));
hebsuperobject.biblemap.put("b27_2_23", new hebsuperobject(27,2,23,"לך אלה אבהתי מהודא ומשבח אנה די חכמתא וגבורתא יהבת לי וכען הודעתני די בעינא מנך די מלת מלכא הודעתנא׃"));
hebsuperobject.biblemap.put("b27_2_24", new hebsuperobject(27,2,24,"כל קבל דנה דניאל על על אריוך די מני מלכא להובדה לחכימי בבל אזל וכן אמר לה לחכימי בבל אל תהובד העלני קדם מלכא ופשרא למלכא אחוא׃"));
hebsuperobject.biblemap.put("b27_2_25", new hebsuperobject(27,2,25,"אדין אריוך בהתבהלה הנעל לדניאל קדם מלכא וכן אמר לה די השכחת גבר מן בני גלותא די יהוד די פשרא למלכא יהודע׃"));
hebsuperobject.biblemap.put("b27_2_26", new hebsuperobject(27,2,26,"ענה מלכא ואמר לדניאל די שמה בלטשאצר האיתיך כהל להודעתני חלמא די חזית ופשרה׃"));
hebsuperobject.biblemap.put("b27_2_27", new hebsuperobject(27,2,27,"ענה דניאל קדם מלכא ואמר רזה די מלכא שאל לא חכימין אשפין חרטמין גזרין יכלין להחויה למלכא׃"));
hebsuperobject.biblemap.put("b27_2_28", new hebsuperobject(27,2,28,"ברם איתי אלה בשמיא גלא רזין והודע למלכא נבוכדנצר מה די להוא באחרית יומיא חלמך וחזוי ראשך על משכבך דנה הוא׃"));
hebsuperobject.biblemap.put("b27_2_29", new hebsuperobject(27,2,29,"אנתה מלכא רעיונך על משכבך סלקו מה די להוא אחרי דנה וגלא רזיא הודעך מה די להוא׃"));
hebsuperobject.biblemap.put("b27_2_30", new hebsuperobject(27,2,30,"ואנה לא בחכמה די איתי בי מן כל חייא רזא דנה גלי לי להן על דברת די פשרא למלכא יהודעון ורעיוני לבבך תנדע׃"));
hebsuperobject.biblemap.put("b27_2_31", new hebsuperobject(27,2,31,"אנתה מלכא חזה הוית ואלו צלם חד שגיא צלמא דכן רב וזיוה יתיר קאם לקבלך ורוה דחיל׃"));
hebsuperobject.biblemap.put("b27_2_32", new hebsuperobject(27,2,32,"הוא צלמא ראשה די דהב טב חדוהי ודרעוהי די כסף מעוהי וירכתה די נחש׃"));
hebsuperobject.biblemap.put("b27_2_33", new hebsuperobject(27,2,33,"שקוהי די פרזל רגלוהי מנהון די פרזל ומנהון די חסף׃"));
hebsuperobject.biblemap.put("b27_2_34", new hebsuperobject(27,2,34,"חזה הוית עד די התגזרת אבן די לא בידין ומחת לצלמא על רגלוהי די פרזלא וחספא והדקת המון׃"));
hebsuperobject.biblemap.put("b27_2_35", new hebsuperobject(27,2,35,"באדין דקו כחדה פרזלא חספא נחשא כספא ודהבא והוו כעור מן אדרי קיט ונשא המון רוחא וכל אתר לא השתכח להון ואבנא די מחת לצלמא הות לטור רב ומלת כל ארעא׃"));
hebsuperobject.biblemap.put("b27_2_36", new hebsuperobject(27,2,36,"דנה חלמא ופשרה נאמר קדם מלכא׃"));
hebsuperobject.biblemap.put("b27_2_37", new hebsuperobject(27,2,37,"אנתה מלכא מלך מלכיא די אלה שמיא מלכותא חסנא ותקפא ויקרא יהב לך׃"));
hebsuperobject.biblemap.put("b27_2_38", new hebsuperobject(27,2,38,"ובכל די דארין בני אנשא חיות ברא ועוף שמיא יהב בידך והשלטך בכלהון אנתה הוא ראשה די דהבא׃"));
hebsuperobject.biblemap.put("b27_2_39", new hebsuperobject(27,2,39,"ובתרך תקום מלכו אחרי ארעא מנך ומלכו תליתיא אחרי די נחשא די תשלט בכל ארעא׃"));
hebsuperobject.biblemap.put("b27_2_40", new hebsuperobject(27,2,40,"ומלכו רביעיה תהוא תקיפה כפרזלא כל קבל די פרזלא מהדק וחשל כלא וכפרזלא די מרעע כל אלין תדק ותרע׃"));
hebsuperobject.biblemap.put("b27_2_41", new hebsuperobject(27,2,41,"ודי חזיתה רגליא ואצבעתא מנהון חסף די פחר ומנהון פרזל מלכו פליגה תהוה ומן נצבתא די פרזלא להוא בה כל קבל די חזיתה פרזלא מערב בחסף טינא׃"));
hebsuperobject.biblemap.put("b27_2_42", new hebsuperobject(27,2,42,"ואצבעת רגליא מנהון פרזל ומנהון חסף מן קצת מלכותא תהוה תקיפה ומנה תהוה תבירה׃"));
hebsuperobject.biblemap.put("b27_2_43", new hebsuperobject(27,2,43,"די חזית פרזלא מערב בחסף טינא מתערבין להון בזרע אנשא ולא להון דבקין דנה עם דנה הא כדי פרזלא לא מתערב עם חספא׃"));
hebsuperobject.biblemap.put("b27_2_44", new hebsuperobject(27,2,44,"וביומיהון די מלכיא אנון יקים אלה שמיא מלכו די לעלמין לא תתחבל ומלכותה לעם אחרן לא תשתבק תדק ותסיף כל אלין מלכותא והיא תקום לעלמיא׃"));
hebsuperobject.biblemap.put("b27_2_45", new hebsuperobject(27,2,45,"כל קבל די חזית די מטורא אתגזרת אבן די לא בידין והדקת פרזלא נחשא חספא כספא ודהבא אלה רב הודע למלכא מה די להוא אחרי דנה ויציב חלמא ומהימן פשרה׃"));
hebsuperobject.biblemap.put("b27_2_46", new hebsuperobject(27,2,46,"באדין מלכא נבוכדנצר נפל על אנפוהי ולדניאל סגד ומנחה וניחחין אמר לנסכה לה׃"));
hebsuperobject.biblemap.put("b27_2_47", new hebsuperobject(27,2,47,"ענה מלכא לדניאל ואמר מן קשט די אלהכון הוא אלה אלהין ומרא מלכין וגלה רזין די יכלת למגלא רזה דנה׃"));
hebsuperobject.biblemap.put("b27_2_48", new hebsuperobject(27,2,48,"אדין מלכא לדניאל רבי ומתנן רברבן שגיאן יהב לה והשלטה על כל מדינת בבל ורב סגנין על כל חכימי בבל׃"));
hebsuperobject.biblemap.put("b27_2_49", new hebsuperobject(27,2,49,"ודניאל בעא מן מלכא ומני על עבידתא די מדינת בבל לשדרך מישך ועבד נגו ודניאל בתרע מלכא׃"));
hebsuperobject.biblemap.put("b27_3_1", new hebsuperobject(27,3,1,"נבוכדנצר מלכא עבד צלם די דהב רומה אמין שתין פתיה אמין שת אקימה בבקעת דורא במדינת בבל׃"));
hebsuperobject.biblemap.put("b27_3_2", new hebsuperobject(27,3,2,"ונבוכדנצר מלכא שלח למכנש לאחשדרפניא סגניא ופחותא אדרגזריא גדבריא דתבריא תפתיא וכל שלטני מדינתא למתא לחנכת צלמא די הקים נבוכדנצר מלכא׃"));
hebsuperobject.biblemap.put("b27_3_3", new hebsuperobject(27,3,3,"באדין מתכנשין אחשדרפניא סגניא ופחותא אדרגזריא גדבריא דתבריא תפתיא וכל שלטני מדינתא לחנכת צלמא די הקים נבוכדנצר מלכא וקאמין לקבל צלמא די הקים נבוכדנצר׃"));
hebsuperobject.biblemap.put("b27_3_4", new hebsuperobject(27,3,4,"וכרוזא קרא בחיל לכון אמרין עממיא אמיא ולשניא׃"));
hebsuperobject.biblemap.put("b27_3_5", new hebsuperobject(27,3,5,"בעדנא די תשמעון קל קרנא משרוקיתא קיתרס סבכא פסנתרין סומפניה וכל זני זמרא תפלון ותסגדון לצלם דהבא די הקים נבוכדנצר מלכא׃"));
hebsuperobject.biblemap.put("b27_3_6", new hebsuperobject(27,3,6,"ומן די לא יפל ויסגד בה שעתא יתרמא לגוא אתון נורא יקדתא׃"));
hebsuperobject.biblemap.put("b27_3_7", new hebsuperobject(27,3,7,"כל קבל דנה בה זמנא כדי שמעין כל עממיא קל קרנא משרוקיתא קיתרס שבכא פסנטרין וכל זני זמרא נפלין כל עממיא אמיא ולשניא סגדין לצלם דהבא די הקים נבוכדנצר מלכא׃"));
hebsuperobject.biblemap.put("b27_3_8", new hebsuperobject(27,3,8,"כל קבל דנה בה זמנא קרבו גברין כשדאין ואכלו קרציהון די יהודיא׃"));
hebsuperobject.biblemap.put("b27_3_9", new hebsuperobject(27,3,9,"ענו ואמרין לנבוכדנצר מלכא מלכא לעלמין חיי׃"));
hebsuperobject.biblemap.put("b27_3_10", new hebsuperobject(27,3,10,"אנתה מלכא שמת טעם די כל אנש די ישמע קל קרנא משרקיתא קיתרס שבכא פסנתרין וסיפניה וכל זני זמרא יפל ויסגד לצלם דהבא׃"));
hebsuperobject.biblemap.put("b27_3_11", new hebsuperobject(27,3,11,"ומן די לא יפל ויסגד יתרמא לגוא אתון נורא יקדתא׃"));
hebsuperobject.biblemap.put("b27_3_12", new hebsuperobject(27,3,12,"איתי גברין יהודאין די מנית יתהון על עבידת מדינת בבל שדרך מישך ועבד נגו גבריא אלך לא שמו עליך מלכא טעם לאלהיך לא פלחין ולצלם דהבא די הקימת לא סגדין׃"));
hebsuperobject.biblemap.put("b27_3_13", new hebsuperobject(27,3,13,"באדין נבוכדנצר ברגז וחמה אמר להיתיה לשדרך מישך ועבד נגו באדין גבריא אלך היתיו קדם מלכא׃"));
hebsuperobject.biblemap.put("b27_3_14", new hebsuperobject(27,3,14,"ענה נבכדנצר ואמר להון הצדא שדרך מישך ועבד נגו לאלהי לא איתיכון פלחין ולצלם דהבא די הקימת לא סגדין׃"));
hebsuperobject.biblemap.put("b27_3_15", new hebsuperobject(27,3,15,"כען הן איתיכון עתידין די בעדנא די תשמעון קל קרנא משרוקיתא קיתרס שבכא פסנתרין וסומפניה וכל זני זמרא תפלון ותסגדון לצלמא די עבדת והן לא תסגדון בה שעתה תתרמון לגוא אתון נורא יקדתא ומן הוא אלה די ישיזבנכון מן ידי׃"));
hebsuperobject.biblemap.put("b27_3_16", new hebsuperobject(27,3,16,"ענו שדרך מישך ועבד נגו ואמרין למלכא נבוכדנצר לא חשחין אנחנה על דנה פתגם להתבותך׃"));
hebsuperobject.biblemap.put("b27_3_17", new hebsuperobject(27,3,17,"הן איתי אלהנא די אנחנא פלחין יכל לשיזבותנא מן אתון נורא יקדתא ומן ידך מלכא ישיזב׃"));
hebsuperobject.biblemap.put("b27_3_18", new hebsuperobject(27,3,18,"והן לא ידיע להוא לך מלכא די לאלהיך לא איתנא פלחין ולצלם דהבא די הקימת לא נסגד׃"));
hebsuperobject.biblemap.put("b27_3_19", new hebsuperobject(27,3,19,"באדין נבוכדנצר התמלי חמא וצלם אנפוהי אשתנו על שדרך מישך ועבד נגו ענה ואמר למזא לאתונא חד שבעה על די חזה למזיה׃"));
hebsuperobject.biblemap.put("b27_3_20", new hebsuperobject(27,3,20,"ולגברין גברי חיל די בחילה אמר לכפתה לשדרך מישך ועבד נגו למרמא לאתון נורא יקדתא׃"));
hebsuperobject.biblemap.put("b27_3_21", new hebsuperobject(27,3,21,"באדין גבריא אלך כפתו בסרבליהון פטישיהון וכרבלתהון ולבשיהון ורמיו לגוא אתון נורא יקדתא׃"));
hebsuperobject.biblemap.put("b27_3_22", new hebsuperobject(27,3,22,"כל קבל דנה מן די מלת מלכא מחצפה ואתונא אזה יתירא גבריא אלך די הסקו לשדרך מישך ועבד נגו קטל המון שביבא די נורא׃"));
hebsuperobject.biblemap.put("b27_3_23", new hebsuperobject(27,3,23,"וגבריא אלך תלתהון שדרך מישך ועבד נגו נפלו לגוא אתון נורא יקדתא מכפתין׃"));
hebsuperobject.biblemap.put("b27_3_24", new hebsuperobject(27,3,24,"אדין נבוכדנצר מלכא תוה וקם בהתבהלה ענה ואמר להדברוהי הלא גברין תלתא רמינא לגוא נורא מכפתין ענין ואמרין למלכא יציבא מלכא׃"));
hebsuperobject.biblemap.put("b27_3_25", new hebsuperobject(27,3,25,"ענה ואמר הא אנה חזה גברין ארבעה שרין מהלכין בגוא נורא וחבל לא איתי בהון ורוה די רביעיא דמה לבר אלהין׃"));
hebsuperobject.biblemap.put("b27_3_26", new hebsuperobject(27,3,26,"באדין קרב נבוכדנצר לתרע אתון נורא יקדתא ענה ואמר שדרך מישך ועבד נגו עבדוהי די אלהא עליא פקו ואתו באדין נפקין שדרך מישך ועבד נגו מן גוא נורא׃"));
hebsuperobject.biblemap.put("b27_3_27", new hebsuperobject(27,3,27,"ומתכנשין אחשדרפניא סגניא ופחותא והדברי מלכא חזין לגבריא אלך די לא שלט נורא בגשמהון ושער ראשהון לא התחרך וסרבליהון לא שנו וריח נור לא עדת בהון׃"));
hebsuperobject.biblemap.put("b27_3_28", new hebsuperobject(27,3,28,"ענה נבוכדנצר ואמר בריך אלההון די שדרך מישך ועבד נגו די שלח מלאכה ושיזב לעבדוהי די התרחצו עלוהי ומלת מלכא שניו ויהבו גשמיהון די לא יפלחון ולא יסגדון לכל אלה להן לאלההון׃"));
hebsuperobject.biblemap.put("b27_3_29", new hebsuperobject(27,3,29,"ומני שים טעם די כל עם אמה ולשן די יאמר שלה על אלההון די שדרך מישך ועבד נגוא הדמין יתעבד וביתה נולי ישתוה כל קבל די לא איתי אלה אחרן די יכל להצלה כדנה׃"));
hebsuperobject.biblemap.put("b27_3_30", new hebsuperobject(27,3,30,"באדין מלכא הצלח לשדרך מישך ועבד נגו במדינת בבל׃"));
hebsuperobject.biblemap.put("b27_4_1", new hebsuperobject(27,4,1,"נבוכדנצר מלכא לכל עממיא אמיא ולשניא די דארין בכל ארעא שלמכון ישגא׃"));
hebsuperobject.biblemap.put("b27_4_2", new hebsuperobject(27,4,2,"אתיא ותמהיא די עבד עמי אלהא עליא שפר קדמי להחויה׃"));
hebsuperobject.biblemap.put("b27_4_3", new hebsuperobject(27,4,3,"אתוהי כמה רברבין ותמהוהי כמה תקיפין מלכותה מלכות עלם ושלטנה עם דר ודר׃"));
hebsuperobject.biblemap.put("b27_4_4", new hebsuperobject(27,4,4,"אנה נבוכדנצר שלה הוית בביתי ורענן בהיכלי׃"));
hebsuperobject.biblemap.put("b27_4_5", new hebsuperobject(27,4,5,"חלם חזית וידחלנני והרהרין על משכבי וחזוי ראשי יבהלנני׃"));
hebsuperobject.biblemap.put("b27_4_6", new hebsuperobject(27,4,6,"ומני שים טעם להנעלה קדמי לכל חכימי בבל די פשר חלמא יהודענני׃"));
hebsuperobject.biblemap.put("b27_4_7", new hebsuperobject(27,4,7,"באדין עללין חרטמיא אשפיא כשדיא וגזריא וחלמא אמר אנה קדמיהון ופשרה לא מהודעין לי׃"));
hebsuperobject.biblemap.put("b27_4_8", new hebsuperobject(27,4,8,"ועד אחרין על קדמי דניאל די שמה בלטשאצר כשם אלהי ודי רוח אלהין קדישין בה וחלמא קדמוהי אמרת׃"));
hebsuperobject.biblemap.put("b27_4_9", new hebsuperobject(27,4,9,"בלטשאצר רב חרטמיא די אנה ידעת די רוח אלהין קדישין בך וכל רז לא אנס לך חזוי חלמי די חזית ופשרה אמר׃"));
hebsuperobject.biblemap.put("b27_4_10", new hebsuperobject(27,4,10,"וחזוי ראשי על משכבי חזה הוית ואלו אילן בגוא ארעא ורומה שגיא׃"));
hebsuperobject.biblemap.put("b27_4_11", new hebsuperobject(27,4,11,"רבה אילנא ותקף ורומה ימטא לשמיא וחזותה לסוף כל ארעא׃"));
hebsuperobject.biblemap.put("b27_4_12", new hebsuperobject(27,4,12,"עפיה שפיר ואנבה שגיא ומזון לכלא בה תחתוהי תטלל חיות ברא ובענפוהי ידרון צפרי שמיא ומנה יתזין כל בשרא׃"));
hebsuperobject.biblemap.put("b27_4_13", new hebsuperobject(27,4,13,"חזה הוית בחזוי ראשי על משכבי ואלו עיר וקדיש מן שמיא נחת׃"));
hebsuperobject.biblemap.put("b27_4_14", new hebsuperobject(27,4,14,"קרא בחיל וכן אמר גדו אילנא וקצצו ענפוהי אתרו עפיה ובדרו אנבה תנד חיותא מן תחתוהי וצפריא מן ענפוהי׃"));
hebsuperobject.biblemap.put("b27_4_15", new hebsuperobject(27,4,15,"ברם עקר שרשוהי בארעא שבקו ובאסור די פרזל ונחש בדתאא די ברא ובטל שמיא יצטבע ועם חיותא חלקה בעשב ארעא׃"));
hebsuperobject.biblemap.put("b27_4_16", new hebsuperobject(27,4,16,"לבבה מן אנושא ישנון ולבב חיוה יתיהב לה ושבעה עדנין יחלפון עלוהי׃"));
hebsuperobject.biblemap.put("b27_4_17", new hebsuperobject(27,4,17,"בגזרת עירין פתגמא ומאמר קדישין שאלתא עד דברת די ינדעון חייא די שליט עליא במלכות אנושא ולמן די יצבא יתננה ושפל אנשים יקים עליה׃"));
hebsuperobject.biblemap.put("b27_4_18", new hebsuperobject(27,4,18,"דנה חלמא חזית אנה מלכא נבוכדנצר ואנתה בלטשאצר פשרא אמר כל קבל די כל חכימי מלכותי לא יכלין פשרא להודעתני ואנתה כהל די רוח אלהין קדישין בך׃"));
hebsuperobject.biblemap.put("b27_4_19", new hebsuperobject(27,4,19,"אדין דניאל די שמה בלטשאצר אשתומם כשעה חדה ורעינהי יבהלנה ענה מלכא ואמר בלטשאצר חלמא ופשרא אל יבהלך ענה בלטשאצר ואמר מראי חלמא לשנאיך ופשרה לעריך׃"));
hebsuperobject.biblemap.put("b27_4_20", new hebsuperobject(27,4,20,"אילנא די חזית די רבה ותקף ורומה ימטא לשמיא וחזותה לכל ארעא׃"));
hebsuperobject.biblemap.put("b27_4_21", new hebsuperobject(27,4,21,"ועפיה שפיר ואנבה שגיא ומזון לכלא בה תחתוהי תדור חיות ברא ובענפוהי ישכנן צפרי שמיא׃"));
hebsuperobject.biblemap.put("b27_4_22", new hebsuperobject(27,4,22,"אנתה הוא מלכא די רבית ותקפת ורבותך רבת ומטת לשמיא ושלטנך לסוף ארעא׃"));
hebsuperobject.biblemap.put("b27_4_23", new hebsuperobject(27,4,23,"ודי חזה מלכא עיר וקדיש נחת מן שמיא ואמר גדו אילנא וחבלוהי ברם עקר שרשוהי בארעא שבקו ובאסור די פרזל ונחש בדתאא די ברא ובטל שמיא יצטבע ועם חיות ברא חלקה עד די שבעה עדנין יחלפון עלוהי׃"));
hebsuperobject.biblemap.put("b27_4_24", new hebsuperobject(27,4,24,"דנה פשרא מלכא וגזרת עליא היא די מטת על מראי מלכא׃"));
hebsuperobject.biblemap.put("b27_4_25", new hebsuperobject(27,4,25,"ולך טרדין מן אנשא ועם חיות ברא להוה מדרך ועשבא כתורין לך יטעמון ומטל שמיא לך מצבעין ושבעה עדנין יחלפון עליך עד די תנדע די שליט עליא במלכות אנשא ולמן די יצבא יתננה׃"));
hebsuperobject.biblemap.put("b27_4_26", new hebsuperobject(27,4,26,"ודי אמרו למשבק עקר שרשוהי די אילנא מלכותך לך קימה מן די תנדע די שלטן שמיא׃"));
hebsuperobject.biblemap.put("b27_4_27", new hebsuperobject(27,4,27,"להן מלכא מלכי ישפר עליך וחטיך בצדקה פרק ועויתך במחן ענין הן תהוא ארכה לשלותך׃"));
hebsuperobject.biblemap.put("b27_4_28", new hebsuperobject(27,4,28,"כלא מטא על נבוכדנצר מלכא׃"));
hebsuperobject.biblemap.put("b27_4_29", new hebsuperobject(27,4,29,"לקצת ירחין תרי עשר על היכל מלכותא די בבל מהלך הוה׃"));
hebsuperobject.biblemap.put("b27_4_30", new hebsuperobject(27,4,30,"ענה מלכא ואמר הלא דא היא בבל רבתא די אנה בניתה לבית מלכו בתקף חסני וליקר הדרי׃"));
hebsuperobject.biblemap.put("b27_4_31", new hebsuperobject(27,4,31,"עוד מלתא בפם מלכא קל מן שמיא נפל לך אמרין נבוכדנצר מלכא מלכותה עדת מנך׃"));
hebsuperobject.biblemap.put("b27_4_32", new hebsuperobject(27,4,32,"ומן אנשא לך טרדין ועם חיות ברא מדרך עשבא כתורין לך יטעמון ושבעה עדנין יחלפון עליך עד די תנדע די שליט עליא במלכות אנשא ולמן די יצבא יתננה׃"));
hebsuperobject.biblemap.put("b27_4_33", new hebsuperobject(27,4,33,"בה שעתא מלתא ספת על נבוכדנצר ומן אנשא טריד ועשבא כתורין יאכל ומטל שמיא גשמה יצטבע עד די שערה כנשרין רבה וטפרוהי כצפרין׃"));
hebsuperobject.biblemap.put("b27_4_34", new hebsuperobject(27,4,34,"ולקצת יומיה אנה נבוכדנצר עיני לשמיא נטלת ומנדעי עלי יתוב ולעליא ברכת ולחי עלמא שבחת והדרת די שלטנה שלטן עלם ומלכותה עם דר ודר׃"));
hebsuperobject.biblemap.put("b27_4_35", new hebsuperobject(27,4,35,"וכל דארי ארעא כלה חשיבין וכמצביה עבד בחיל שמיא ודארי ארעא ולא איתי די ימחא בידה ויאמר לה מה עבדת׃"));
hebsuperobject.biblemap.put("b27_4_36", new hebsuperobject(27,4,36,"בה זמנא מנדעי יתוב עלי וליקר מלכותי הדרי וזוי יתוב עלי ולי הדברי ורברבני יבעון ועל מלכותי התקנת ורבו יתירה הוספת לי׃"));
hebsuperobject.biblemap.put("b27_4_37", new hebsuperobject(27,4,37,"כען אנה נבוכדנצר משבח ומרומם ומהדר למלך שמיא די כל מעבדוהי קשט וארחתה דין ודי מהלכין בגוה יכל להשפלה׃"));
hebsuperobject.biblemap.put("b27_5_1", new hebsuperobject(27,5,1,"בלשאצר מלכא עבד לחם רב לרברבנוהי אלף ולקבל אלפא חמרא שתה׃"));
hebsuperobject.biblemap.put("b27_5_2", new hebsuperobject(27,5,2,"בלשאצר אמר בטעם חמרא להיתיה למאני דהבא וכספא די הנפק נבוכדנצר אבוהי מן היכלא די בירושלם וישתון בהון מלכא ורברבנוהי שגלתה ולחנתה׃"));
hebsuperobject.biblemap.put("b27_5_3", new hebsuperobject(27,5,3,"באדין היתיו מאני דהבא די הנפקו מן היכלא די בית אלהא די בירושלם ואשתיו בהון מלכא ורברבנוהי שגלתה ולחנתה׃"));
hebsuperobject.biblemap.put("b27_5_4", new hebsuperobject(27,5,4,"אשתיו חמרא ושבחו לאלהי דהבא וכספא נחשא פרזלא אעא ואבנא׃"));
hebsuperobject.biblemap.put("b27_5_5", new hebsuperobject(27,5,5,"בה שעתה נפקו אצבען די יד אנש וכתבן לקבל נברשתא על גירא די כתל היכלא די מלכא ומלכא חזה פס ידה די כתבה׃"));
hebsuperobject.biblemap.put("b27_5_6", new hebsuperobject(27,5,6,"אדין מלכא זיוהי שנוהי ורעינהי יבהלונה וקטרי חרצה משתרין וארכבתה דא לדא נקשן׃"));
hebsuperobject.biblemap.put("b27_5_7", new hebsuperobject(27,5,7,"קרא מלכא בחיל להעלה לאשפיא כשדיא וגזריא ענה מלכא ואמר לחכימי בבל די כל אנש די יקרה כתבה דנה ופשרה יחונני ארגונא ילבש והמונכא די דהבא על צוארה ותלתי במלכותא ישלט׃"));
hebsuperobject.biblemap.put("b27_5_8", new hebsuperobject(27,5,8,"אדין עללין כל חכימי מלכא ולא כהלין כתבא למקרא ופשרא להודעה למלכא׃"));
hebsuperobject.biblemap.put("b27_5_9", new hebsuperobject(27,5,9,"אדין מלכא בלשאצר שגיא מתבהל וזיוהי שנין עלוהי ורברבנוהי משתבשין׃"));
hebsuperobject.biblemap.put("b27_5_10", new hebsuperobject(27,5,10,"מלכתא לקבל מלי מלכא ורברבנוהי לבית משתיא עללת ענת מלכתא ואמרת מלכא לעלמין חיי אל יבהלוך רעיונך וזיויך אל ישתנו׃"));
hebsuperobject.biblemap.put("b27_5_11", new hebsuperobject(27,5,11,"איתי גבר במלכותך די רוח אלהין קדישין בה וביומי אבוך נהירו ושכלתנו וחכמה כחכמת אלהין השתכחת בה ומלכא נבכדנצר אבוך רב חרטמין אשפין כשדאין גזרין הקימה אבוך מלכא׃"));
hebsuperobject.biblemap.put("b27_5_12", new hebsuperobject(27,5,12,"כל קבל די רוח יתירה ומנדע ושכלתנו מפשר חלמין ואחוית אחידן ומשרא קטרין השתכחת בה בדניאל די מלכא שם שמה בלטשאצר כען דניאל יתקרי ופשרה יהחוה׃"));
hebsuperobject.biblemap.put("b27_5_13", new hebsuperobject(27,5,13,"באדין דניאל העל קדם מלכא ענה מלכא ואמר לדניאל אנתה הוא דניאל די מן בני גלותא די יהוד די היתי מלכא אבי מן יהוד׃"));
hebsuperobject.biblemap.put("b27_5_14", new hebsuperobject(27,5,14,"ושמעת עליך די רוח אלהין בך ונהירו ושכלתנו וחכמה יתירה השתכחת בך׃"));
hebsuperobject.biblemap.put("b27_5_15", new hebsuperobject(27,5,15,"וכען העלו קדמי חכימיא אשפיא די כתבה דנה יקרון ופשרה להודעתני ולא כהלין פשר מלתא להחויה׃"));
hebsuperobject.biblemap.put("b27_5_16", new hebsuperobject(27,5,16,"ואנה שמעת עליך די תוכל פשרין למפשר וקטרין למשרא כען הן תוכל כתבא למקרא ופשרה להודעתני ארגונא תלבש והמונכא די דהבא על צוארך ותלתא במלכותא תשלט׃"));
hebsuperobject.biblemap.put("b27_5_17", new hebsuperobject(27,5,17,"באדין ענה דניאל ואמר קדם מלכא מתנתך לך להוין ונבזביתך לאחרן הב ברם כתבא אקרא למלכא ופשרא אהודענה׃"));
hebsuperobject.biblemap.put("b27_5_18", new hebsuperobject(27,5,18,"אנתה מלכא אלהא עליא מלכותא ורבותא ויקרא והדרה יהב לנבכדנצר אבוך׃"));
hebsuperobject.biblemap.put("b27_5_19", new hebsuperobject(27,5,19,"ומן רבותא די יהב לה כל עממיא אמיא ולשניא הוו זאעין ודחלין מן קדמוהי די הוה צבא הוא קטל ודי הוה צבא הוה מחא ודי הוה צבא הוה מרים ודי הוה צבא הוה משפיל׃"));
hebsuperobject.biblemap.put("b27_5_20", new hebsuperobject(27,5,20,"וכדי רם לבבה ורוחה תקפת להזדה הנחת מן כרסא מלכותה ויקרה העדיו מנה׃"));
hebsuperobject.biblemap.put("b27_5_21", new hebsuperobject(27,5,21,"ומן בני אנשא טריד ולבבה עם חיותא שוי ועם ערדיא מדורה עשבא כתורין יטעמונה ומטל שמיא גשמה יצטבע עד די ידע די שליט אלהא עליא במלכות אנשא ולמן די יצבה יהקים עליה׃"));
hebsuperobject.biblemap.put("b27_5_22", new hebsuperobject(27,5,22,"ואנתה ברה בלשאצר לא השפלת לבבך כל קבל די כל דנה ידעת׃"));
hebsuperobject.biblemap.put("b27_5_23", new hebsuperobject(27,5,23,"ועל מרא שמיא התרוממת ולמאניא די ביתה היתיו קדמיך ואנתה ורברבניך שגלתך ולחנתך חמרא שתין בהון ולאלהי כספא ודהבא נחשא פרזלא אעא ואבנא די לא חזין ולא שמעין ולא ידעין שבחת ולאלהא די נשמתך בידה וכל ארחתך לה לא הדרת׃"));
hebsuperobject.biblemap.put("b27_5_24", new hebsuperobject(27,5,24,"באדין מן קדמוהי שליח פסא די ידא וכתבא דנה רשים׃"));
hebsuperobject.biblemap.put("b27_5_25", new hebsuperobject(27,5,25,"ודנה כתבא די רשים מנא מנא תקל ופרסין׃"));
hebsuperobject.biblemap.put("b27_5_26", new hebsuperobject(27,5,26,"דנה פשר מלתא מנא מנה אלהא מלכותך והשלמה׃"));
hebsuperobject.biblemap.put("b27_5_27", new hebsuperobject(27,5,27,"תקל תקילתה במאזניא והשתכחת חסיר׃"));
hebsuperobject.biblemap.put("b27_5_28", new hebsuperobject(27,5,28,"פרס פריסת מלכותך ויהיבת למדי ופרס׃"));
hebsuperobject.biblemap.put("b27_5_29", new hebsuperobject(27,5,29,"באדין אמר בלשאצר והלבישו לדניאל ארגונא והמונכא די דהבא על צוארה והכרזו עלוהי די להוא שליט תלתא במלכותא׃"));
hebsuperobject.biblemap.put("b27_5_30", new hebsuperobject(27,5,30,"בה בליליא קטיל בלאשצר מלכא כשדיא׃"));
hebsuperobject.biblemap.put("b27_5_31", new hebsuperobject(27,5,31,"ודריוש מדיא קבל מלכותא כבר שנין שתין ותרתין׃"));
hebsuperobject.biblemap.put("b27_6_1", new hebsuperobject(27,6,1,"שפר קדם דריוש והקים על מלכותא לאחשדרפניא מאה ועשרין די להון בכל מלכותא׃"));
hebsuperobject.biblemap.put("b27_6_2", new hebsuperobject(27,6,2,"ועלא מנהון סרכין תלתא די דניאל חד מנהון די להון אחשדרפניא אלין יהבין להון טעמא ומלכא לא להוא נזק׃"));
hebsuperobject.biblemap.put("b27_6_3", new hebsuperobject(27,6,3,"אדין דניאל דנה הוא מתנצח על סרכיא ואחשדרפניא כל קבל די רוח יתירא בה ומלכא עשית להקמותה על כל מלכותא׃"));
hebsuperobject.biblemap.put("b27_6_4", new hebsuperobject(27,6,4,"אדין סרכיא ואחשדרפניא הוו בעין עלה להשכחה לדניאל מצד מלכותא וכל עלה ושחיתה לא יכלין להשכחה כל קבל די מהימן הוא וכל שלו ושחיתה לא השתכחת עלוהי׃"));
hebsuperobject.biblemap.put("b27_6_5", new hebsuperobject(27,6,5,"אדין גבריא אלך אמרין די לא נהשכח לדניאל דנה כל עלא להן השכחנה עלוהי בדת אלהה׃"));
hebsuperobject.biblemap.put("b27_6_6", new hebsuperobject(27,6,6,"אדין סרכיא ואחשדרפניא אלן הרגשו על מלכא וכן אמרין לה דריוש מלכא לעלמין חיי׃"));
hebsuperobject.biblemap.put("b27_6_7", new hebsuperobject(27,6,7,"אתיעטו כל סרכי מלכותא סגניא ואחשדרפניא הדבריא ופחותא לקימה קים מלכא ולתקפה אסר די כל די יבעה בעו מן כל אלה ואנש עד יומין תלתין להן מנך מלכא יתרמא לגב אריותא׃"));
hebsuperobject.biblemap.put("b27_6_8", new hebsuperobject(27,6,8,"כען מלכא תקים אסרא ותרשם כתבא די לא להשניה כדת מדי ופרס די לא תעדא׃"));
hebsuperobject.biblemap.put("b27_6_9", new hebsuperobject(27,6,9,"כל קבל דנה מלכא דריוש רשם כתבא ואסרא׃"));
hebsuperobject.biblemap.put("b27_6_10", new hebsuperobject(27,6,10,"ודניאל כדי ידע די רשים כתבא על לביתה וכוין פתיחן לה בעליתה נגד ירושלם וזמנין תלתה ביומא הוא ברך על ברכוהי ומצלא ומודא קדם אלהה כל קבל די הוא עבד מן קדמת דנה׃"));
hebsuperobject.biblemap.put("b27_6_11", new hebsuperobject(27,6,11,"אדין גבריא אלך הרגשו והשכחו לדניאל בעא ומתחנן קדם אלהה׃"));
hebsuperobject.biblemap.put("b27_6_12", new hebsuperobject(27,6,12,"באדין קריבו ואמרין קדם מלכא על אסר מלכא הלא אסר רשמת די כל אנש די יבעה מן כל אלה ואנש עד יומין תלתין להן מנך מלכא יתרמא לגוב אריותא ענה מלכא ואמר יציבא מלתא כדת מדי ופרס די לא תעדא׃"));
hebsuperobject.biblemap.put("b27_6_13", new hebsuperobject(27,6,13,"באדין ענו ואמרין קדם מלכא די דניאל די מן בני גלותא די יהוד לא שם עליך מלכא טעם ועל אסרא די רשמת וזמנין תלתה ביומא בעא בעותה׃"));
hebsuperobject.biblemap.put("b27_6_14", new hebsuperobject(27,6,14,"אדין מלכא כדי מלתא שמע שגיא באש עלוהי ועל דניאל שם בל לשיזבותה ועד מעלי שמשא הוא משתדר להצלותה׃"));
hebsuperobject.biblemap.put("b27_6_15", new hebsuperobject(27,6,15,"באדין גבריא אלך הרגשו על מלכא ואמרין למלכא דע מלכא די דת למדי ופרס די כל אסר וקים די מלכא יהקים לא להשניה׃"));
hebsuperobject.biblemap.put("b27_6_16", new hebsuperobject(27,6,16,"באדין מלכא אמר והיתיו לדניאל ורמו לגבא די אריותא ענה מלכא ואמר לדניאל אלהך די אנתה פלח לה בתדירא הוא ישיזבנך׃"));
hebsuperobject.biblemap.put("b27_6_17", new hebsuperobject(27,6,17,"והיתית אבן חדה ושמת על פם גבא וחתמה מלכא בעזקתה ובעזקת רברבנוהי די לא תשנא צבו בדניאל׃"));
hebsuperobject.biblemap.put("b27_6_18", new hebsuperobject(27,6,18,"אדין אזל מלכא להיכלה ובת טות ודחון לא הנעל קדמוהי ושנתה נדת עלוהי׃"));
hebsuperobject.biblemap.put("b27_6_19", new hebsuperobject(27,6,19,"באדין מלכא בשפרפרא יקום בנגהא ובהתבהלה לגבא די אריותא אזל׃"));
hebsuperobject.biblemap.put("b27_6_20", new hebsuperobject(27,6,20,"וכמקרבה לגבא לדניאל בקל עציב זעק ענה מלכא ואמר לדניאל דניאל עבד אלהא חיא אלהך די אנתה פלח לה בתדירא היכל לשיזבותך מן אריותא׃"));
hebsuperobject.biblemap.put("b27_6_21", new hebsuperobject(27,6,21,"אדין דניאל עם מלכא מלל מלכא לעלמין חיי׃"));
hebsuperobject.biblemap.put("b27_6_22", new hebsuperobject(27,6,22,"אלהי שלח מלאכה וסגר פם אריותא ולא חבלוני כל קבל די קדמוהי זכו השתכחת לי ואף קדמיך מלכא חבולה לא עבדת׃"));
hebsuperobject.biblemap.put("b27_6_23", new hebsuperobject(27,6,23,"באדין מלכא שגיא טאב עלוהי ולדניאל אמר להנסקה מן גבא והסק דניאל מן גבא וכל חבל לא השתכח בה די הימן באלהה׃"));
hebsuperobject.biblemap.put("b27_6_24", new hebsuperobject(27,6,24,"ואמר מלכא והיתיו גבריא אלך די אכלו קרצוהי די דניאל ולגב אריותא רמו אנון בניהון ונשיהון ולא מטו לארעית גבא עד די שלטו בהון אריותא וכל גרמיהון הדקו׃"));
hebsuperobject.biblemap.put("b27_6_25", new hebsuperobject(27,6,25,"באדין דריוש מלכא כתב לכל עממיא אמיא ולשניא די דארין בכל ארעא שלמכון ישגא׃"));
hebsuperobject.biblemap.put("b27_6_26", new hebsuperobject(27,6,26,"מן קדמי שים טעם די בכל שלטן מלכותי להון זאעין ודחלין מן קדם אלהה די דניאל די הוא אלהא חיא וקים לעלמין ומלכותה די לא תתחבל ושלטנה עד סופא׃"));
hebsuperobject.biblemap.put("b27_6_27", new hebsuperobject(27,6,27,"משיזב ומצל ועבד אתין ותמהין בשמיא ובארעא די שיזיב לדניאל מן יד אריותא׃"));
hebsuperobject.biblemap.put("b27_6_28", new hebsuperobject(27,6,28,"ודניאל דנה הצלח במלכות דריוש ובמלכות כורש פרסיא׃"));
hebsuperobject.biblemap.put("b27_7_1", new hebsuperobject(27,7,1,"בשנת חדה לבלאשצר מלך בבל דניאל חלם חזה וחזוי ראשה על משכבה באדין חלמא כתב ראש מלין אמר׃"));
hebsuperobject.biblemap.put("b27_7_2", new hebsuperobject(27,7,2,"ענה דניאל ואמר חזה הוית בחזוי עם ליליא וארו ארבע רוחי שמיא מגיחן לימא רבא׃"));
hebsuperobject.biblemap.put("b27_7_3", new hebsuperobject(27,7,3,"וארבע חיון רברבן סלקן מן ימא שנין דא מן דא׃"));
hebsuperobject.biblemap.put("b27_7_4", new hebsuperobject(27,7,4,"קדמיתא כאריה וגפין די נשר לה חזה הוית עד די מריטו גפיה ונטילת מן ארעא ועל רגלין כאנש הקימת ולבב אנש יהיב לה׃"));
hebsuperobject.biblemap.put("b27_7_5", new hebsuperobject(27,7,5,"וארו חיוה אחרי תנינה דמיה לדב ולשטר חד הקמת ותלת עלעין בפמה בין שניה וכן אמרין לה קומי אכלי בשר שגיא׃"));
hebsuperobject.biblemap.put("b27_7_6", new hebsuperobject(27,7,6,"באתר דנה חזה הוית וארו אחרי כנמר ולה גפין ארבע די עוף על גביה וארבעה ראשין לחיותא ושלטן יהיב לה׃"));
hebsuperobject.biblemap.put("b27_7_7", new hebsuperobject(27,7,7,"באתר דנה חזה הוית בחזוי ליליא וארו חיוה רביעיה דחילה ואימתני ותקיפא יתירא ושנין די פרזל לה רברבן אכלה ומדקה ושארא ברגליה רפסה והיא משניה מן כל חיותא די קדמיה וקרנין עשר לה׃"));
hebsuperobject.biblemap.put("b27_7_8", new hebsuperobject(27,7,8,"משתכל הוית בקרניא ואלו קרן אחרי זעירה סלקת ביניהון ותלת מן קרניא קדמיתא אתעקרו מן קדמיה ואלו עינין כעיני אנשא בקרנא דא ופם ממלל רברבן׃"));
hebsuperobject.biblemap.put("b27_7_9", new hebsuperobject(27,7,9,"חזה הוית עד די כרסון רמיו ועתיק יומין יתב לבושה כתלג חור ושער ראשה כעמר נקא כרסיה שביבין די נור גלגלוהי נור דלק׃"));
hebsuperobject.biblemap.put("b27_7_10", new hebsuperobject(27,7,10,"נהר די נור נגד ונפק מן קדמוהי אלף אלפים ישמשונה ורבו רבון קדמוהי יקומון דינא יתב וספרין פתיחו׃"));
hebsuperobject.biblemap.put("b27_7_11", new hebsuperobject(27,7,11,"חזה הוית באדין מן קל מליא רברבתא די קרנא ממללה חזה הוית עד די קטילת חיותא והובד גשמה ויהיבת ליקדת אשא׃"));
hebsuperobject.biblemap.put("b27_7_12", new hebsuperobject(27,7,12,"ושאר חיותא העדיו שלטנהון וארכה בחיין יהיבת להון עד זמן ועדן׃"));
hebsuperobject.biblemap.put("b27_7_13", new hebsuperobject(27,7,13,"חזה הוית בחזוי ליליא וארו עם ענני שמיא כבר אנש אתה הוה ועד עתיק יומיא מטה וקדמוהי הקרבוהי׃"));
hebsuperobject.biblemap.put("b27_7_14", new hebsuperobject(27,7,14,"ולה יהיב שלטן ויקר ומלכו וכל עממיא אמיא ולשניא לה יפלחון שלטנה שלטן עלם די לא יעדה ומלכותה די לא תתחבל׃"));
hebsuperobject.biblemap.put("b27_7_15", new hebsuperobject(27,7,15,"אתכרית רוחי אנה דניאל בגוא נדנה וחזוי ראשי יבהלנני׃"));
hebsuperobject.biblemap.put("b27_7_16", new hebsuperobject(27,7,16,"קרבת על חד מן קאמיא ויציבא אבעא מנה על כל דנה ואמר לי ופשר מליא יהודענני׃"));
hebsuperobject.biblemap.put("b27_7_17", new hebsuperobject(27,7,17,"אלין חיותא רברבתא די אנין ארבע ארבעה מלכין יקומון מן ארעא׃"));
hebsuperobject.biblemap.put("b27_7_18", new hebsuperobject(27,7,18,"ויקבלון מלכותא קדישי עליונין ויחסנון מלכותא עד עלמא ועד עלם עלמיא׃"));
hebsuperobject.biblemap.put("b27_7_19", new hebsuperobject(27,7,19,"אדין צבית ליצבא על חיותא רביעיתא די הות שניה מן כלהון דחילה יתירה שניה די פרזל וטפריה די נחש אכלה מדקה ושארא ברגליה רפסה׃"));
hebsuperobject.biblemap.put("b27_7_20", new hebsuperobject(27,7,20,"ועל קרניא עשר די בראשה ואחרי די סלקת ונפלו מן קדמיה תלת וקרנא דכן ועינין לה ופם ממלל רברבן וחזוה רב מן חברתה׃"));
hebsuperobject.biblemap.put("b27_7_21", new hebsuperobject(27,7,21,"חזה הוית וקרנא דכן עבדה קרב עם קדישין ויכלה להון׃"));
hebsuperobject.biblemap.put("b27_7_22", new hebsuperobject(27,7,22,"עד די אתה עתיק יומיא ודינא יהב לקדישי עליונין וזמנא מטה ומלכותא החסנו קדישין׃"));
hebsuperobject.biblemap.put("b27_7_23", new hebsuperobject(27,7,23,"כן אמר חיותא רביעיתא מלכו רביעיא תהוא בארעא די תשנא מן כל מלכותא ותאכל כל ארעא ותדושנה ותדקנה׃"));
hebsuperobject.biblemap.put("b27_7_24", new hebsuperobject(27,7,24,"וקרניא עשר מנה מלכותה עשרה מלכין יקמון ואחרן יקום אחריהון והוא ישנא מן קדמיא ותלתה מלכין יהשפל׃"));
hebsuperobject.biblemap.put("b27_7_25", new hebsuperobject(27,7,25,"ומלין לצד עליא ימלל ולקדישי עליונין יבלא ויסבר להשניה זמנין ודת ויתיהבון בידה עד עדן ועדנין ופלג עדן׃"));
hebsuperobject.biblemap.put("b27_7_26", new hebsuperobject(27,7,26,"ודינא יתב ושלטנה יהעדון להשמדה ולהובדה עד סופא׃"));
hebsuperobject.biblemap.put("b27_7_27", new hebsuperobject(27,7,27,"ומלכותה ושלטנא ורבותא די מלכות תחות כל שמיא יהיבת לעם קדישי עליונין מלכותה מלכות עלם וכל שלטניא לה יפלחון וישתמעון׃"));
hebsuperobject.biblemap.put("b27_7_28", new hebsuperobject(27,7,28,"עד כה סופא די מלתא אנה דניאל שגיא רעיוני יבהלנני וזיוי ישתנון עלי ומלתא בלבי נטרת׃"));
hebsuperobject.biblemap.put("b27_8_1", new hebsuperobject(27,8,1,"בשנת שלוש למלכות בלאשצר המלך חזון נראה אלי אני דניאל אחרי הנראה אלי בתחלה׃"));
hebsuperobject.biblemap.put("b27_8_2", new hebsuperobject(27,8,2,"ואראה בחזון ויהי בראתי ואני בשושן הבירה אשר בעילם המדינה ואראה בחזון ואני הייתי על אובל אולי׃"));
hebsuperobject.biblemap.put("b27_8_3", new hebsuperobject(27,8,3,"ואשא עיני ואראה והנה איל אחד עמד לפני האבל ולו קרנים והקרנים גבהות והאחת גבהה מן השנית והגבהה עלה באחרנה׃"));
hebsuperobject.biblemap.put("b27_8_4", new hebsuperobject(27,8,4,"ראיתי את האיל מנגח ימה וצפונה ונגבה וכל חיות לא יעמדו לפניו ואין מציל מידו ועשה כרצנו והגדיל׃"));
hebsuperobject.biblemap.put("b27_8_5", new hebsuperobject(27,8,5,"ואני הייתי מבין והנה צפיר העזים בא מן המערב על פני כל הארץ ואין נוגע בארץ והצפיר קרן חזות בין עיניו׃"));
hebsuperobject.biblemap.put("b27_8_6", new hebsuperobject(27,8,6,"ויבא עד האיל בעל הקרנים אשר ראיתי עמד לפני האבל וירץ אליו בחמת כחו׃"));
hebsuperobject.biblemap.put("b27_8_7", new hebsuperobject(27,8,7,"וראיתיו מגיע אצל האיל ויתמרמר אליו ויך את האיל וישבר את שתי קרניו ולא היה כח באיל לעמד לפניו וישליכהו ארצה וירמסהו ולא היה מציל לאיל מידו׃"));
hebsuperobject.biblemap.put("b27_8_8", new hebsuperobject(27,8,8,"וצפיר העזים הגדיל עד מאד וכעצמו נשברה הקרן הגדולה ותעלנה חזות ארבע תחתיה לארבע רוחות השמים׃"));
hebsuperobject.biblemap.put("b27_8_9", new hebsuperobject(27,8,9,"ומן האחת מהם יצא קרן אחת מצעירה ותגדל יתר אל הנגב ואל המזרח ואל הצבי׃"));
hebsuperobject.biblemap.put("b27_8_10", new hebsuperobject(27,8,10,"ותגדל עד צבא השמים ותפל ארצה מן הצבא ומן הכוכבים ותרמסם׃"));
hebsuperobject.biblemap.put("b27_8_11", new hebsuperobject(27,8,11,"ועד שר הצבא הגדיל וממנו הרים התמיד והשלך מכון מקדשו׃"));
hebsuperobject.biblemap.put("b27_8_12", new hebsuperobject(27,8,12,"וצבא תנתן על התמיד בפשע ותשלך אמת ארצה ועשתה והצליחה׃"));
hebsuperobject.biblemap.put("b27_8_13", new hebsuperobject(27,8,13,"ואשמעה אחד קדוש מדבר ויאמר אחד קדוש לפלמוני המדבר עד מתי החזון התמיד והפשע שמם תת וקדש וצבא מרמס׃"));
hebsuperobject.biblemap.put("b27_8_14", new hebsuperobject(27,8,14,"ויאמר אלי עד ערב בקר אלפים ושלש מאות ונצדק קדש׃"));
hebsuperobject.biblemap.put("b27_8_15", new hebsuperobject(27,8,15,"ויהי בראתי אני דניאל את החזון ואבקשה בינה והנה עמד לנגדי כמראה גבר׃"));
hebsuperobject.biblemap.put("b27_8_16", new hebsuperobject(27,8,16,"ואשמע קול אדם בין אולי ויקרא ויאמר גבריאל הבן להלז את המראה׃"));
hebsuperobject.biblemap.put("b27_8_17", new hebsuperobject(27,8,17,"ויבא אצל עמדי ובבאו נבעתי ואפלה על פני ויאמר אלי הבן בן אדם כי לעת קץ החזון׃"));
hebsuperobject.biblemap.put("b27_8_18", new hebsuperobject(27,8,18,"ובדברו עמי נרדמתי על פני ארצה ויגע בי ויעמידני על עמדי׃"));
hebsuperobject.biblemap.put("b27_8_19", new hebsuperobject(27,8,19,"ויאמר הנני מודיעך את אשר יהיה באחרית הזעם כי למועד קץ׃"));
hebsuperobject.biblemap.put("b27_8_20", new hebsuperobject(27,8,20,"האיל אשר ראית בעל הקרנים מלכי מדי ופרס׃"));
hebsuperobject.biblemap.put("b27_8_21", new hebsuperobject(27,8,21,"והצפיר השעיר מלך יון והקרן הגדולה אשר בין עיניו הוא המלך הראשון׃"));
hebsuperobject.biblemap.put("b27_8_22", new hebsuperobject(27,8,22,"והנשברת ותעמדנה ארבע תחתיה ארבע מלכיות מגוי יעמדנה ולא בכחו׃"));
hebsuperobject.biblemap.put("b27_8_23", new hebsuperobject(27,8,23,"ובאחרית מלכותם כהתם הפשעים יעמד מלך עז פנים ומבין חידות׃"));
hebsuperobject.biblemap.put("b27_8_24", new hebsuperobject(27,8,24,"ועצם כחו ולא בכחו ונפלאות ישחית והצליח ועשה והשחית עצומים ועם קדשים׃"));
hebsuperobject.biblemap.put("b27_8_25", new hebsuperobject(27,8,25,"ועל שכלו והצליח מרמה בידו ובלבבו יגדיל ובשלוה ישחית רבים ועל שר שרים יעמד ובאפס יד ישבר׃"));
hebsuperobject.biblemap.put("b27_8_26", new hebsuperobject(27,8,26,"ומראה הערב והבקר אשר נאמר אמת הוא ואתה סתם החזון כי לימים רבים׃"));
hebsuperobject.biblemap.put("b27_8_27", new hebsuperobject(27,8,27,"ואני דניאל נהייתי ונחליתי ימים ואקום ואעשה את מלאכת המלך ואשתומם על המראה ואין מבין׃"));
hebsuperobject.biblemap.put("b27_9_1", new hebsuperobject(27,9,1,"בשנת אחת לדריוש בן אחשורוש מזרע מדי אשר המלך על מלכות כשדים׃"));
hebsuperobject.biblemap.put("b27_9_2", new hebsuperobject(27,9,2,"בשנת אחת למלכו אני דניאל בינתי בספרים מספר השנים אשר היה דבר יהוה אל ירמיה הנביא למלאות לחרבות ירושלם שבעים שנה׃"));
hebsuperobject.biblemap.put("b27_9_3", new hebsuperobject(27,9,3,"ואתנה את פני אל אדני האלהים לבקש תפלה ותחנונים בצום ושק ואפר׃"));
hebsuperobject.biblemap.put("b27_9_4", new hebsuperobject(27,9,4,"ואתפללה ליהוה אלהי ואתודה ואמרה אנא אדני האל הגדול והנורא שמר הברית והחסד לאהביו ולשמרי מצותיו׃"));
hebsuperobject.biblemap.put("b27_9_5", new hebsuperobject(27,9,5,"חטאנו ועוינו והרשענו ומרדנו וסור ממצותך וממשפטיך׃"));
hebsuperobject.biblemap.put("b27_9_6", new hebsuperobject(27,9,6,"ולא שמענו אל עבדיך הנביאים אשר דברו בשמך אל מלכינו שרינו ואבתינו ואל כל עם הארץ׃"));
hebsuperobject.biblemap.put("b27_9_7", new hebsuperobject(27,9,7,"לך אדני הצדקה ולנו בשת הפנים כיום הזה לאיש יהודה וליושבי ירושלם ולכל ישראל הקרבים והרחקים בכל הארצות אשר הדחתם שם במעלם אשר מעלו בך׃"));
hebsuperobject.biblemap.put("b27_9_8", new hebsuperobject(27,9,8,"יהוה לנו בשת הפנים למלכינו לשרינו ולאבתינו אשר חטאנו לך׃"));
hebsuperobject.biblemap.put("b27_9_9", new hebsuperobject(27,9,9,"לאדני אלהינו הרחמים והסלחות כי מרדנו בו׃"));
hebsuperobject.biblemap.put("b27_9_10", new hebsuperobject(27,9,10,"ולא שמענו בקול יהוה אלהינו ללכת בתורתיו אשר נתן לפנינו ביד עבדיו הנביאים׃"));
hebsuperobject.biblemap.put("b27_9_11", new hebsuperobject(27,9,11,"וכל ישראל עברו את תורתך וסור לבלתי שמוע בקלך ותתך עלינו האלה והשבעה אשר כתובה בתורת משה עבד האלהים כי חטאנו לו׃"));
hebsuperobject.biblemap.put("b27_9_12", new hebsuperobject(27,9,12,"ויקם את דבריו אשר דבר עלינו ועל שפטינו אשר שפטונו להביא עלינו רעה גדלה אשר לא נעשתה תחת כל השמים כאשר נעשתה בירושלם׃"));
hebsuperobject.biblemap.put("b27_9_13", new hebsuperobject(27,9,13,"כאשר כתוב בתורת משה את כל הרעה הזאת באה עלינו ולא חלינו את פני יהוה אלהינו לשוב מעוננו ולהשכיל באמתך׃"));
hebsuperobject.biblemap.put("b27_9_14", new hebsuperobject(27,9,14,"וישקד יהוה על הרעה ויביאה עלינו כי צדיק יהוה אלהינו על כל מעשיו אשר עשה ולא שמענו בקלו׃"));
hebsuperobject.biblemap.put("b27_9_15", new hebsuperobject(27,9,15,"ועתה אדני אלהינו אשר הוצאת את עמך מארץ מצרים ביד חזקה ותעש לך שם כיום הזה חטאנו רשענו׃"));
hebsuperobject.biblemap.put("b27_9_16", new hebsuperobject(27,9,16,"אדני ככל צדקתך ישב נא אפך וחמתך מעירך ירושלם הר קדשך כי בחטאינו ובעונות אבתינו ירושלם ועמך לחרפה לכל סביבתינו׃"));
hebsuperobject.biblemap.put("b27_9_17", new hebsuperobject(27,9,17,"ועתה שמע אלהינו אל תפלת עבדך ואל תחנוניו והאר פניך על מקדשך השמם למען אדני׃"));
hebsuperobject.biblemap.put("b27_9_18", new hebsuperobject(27,9,18,"הטה אלהי אזנך ושמע פקחה עיניך וראה שממתינו והעיר אשר נקרא שמך עליה כי לא על צדקתינו אנחנו מפילים תחנונינו לפניך כי על רחמיך הרבים׃"));
hebsuperobject.biblemap.put("b27_9_19", new hebsuperobject(27,9,19,"אדני שמעה אדני סלחה אדני הקשיבה ועשה אל תאחר למענך אלהי כי שמך נקרא על עירך ועל עמך׃"));
hebsuperobject.biblemap.put("b27_9_20", new hebsuperobject(27,9,20,"ועוד אני מדבר ומתפלל ומתודה חטאתי וחטאת עמי ישראל ומפיל תחנתי לפני יהוה אלהי על הר קדש אלהי׃"));
hebsuperobject.biblemap.put("b27_9_21", new hebsuperobject(27,9,21,"ועוד אני מדבר בתפלה והאיש גבריאל אשר ראיתי בחזון בתחלה מעף ביעף נגע אלי כעת מנחת ערב׃"));
hebsuperobject.biblemap.put("b27_9_22", new hebsuperobject(27,9,22,"ויבן וידבר עמי ויאמר דניאל עתה יצאתי להשכילך בינה׃"));
hebsuperobject.biblemap.put("b27_9_23", new hebsuperobject(27,9,23,"בתחלת תחנוניך יצא דבר ואני באתי להגיד כי חמודות אתה ובין בדבר והבן במראה׃"));
hebsuperobject.biblemap.put("b27_9_24", new hebsuperobject(27,9,24,"שבעים שבעים נחתך על עמך ועל עיר קדשך לכלא הפשע ולחתם חטאות ולכפר עון ולהביא צדק עלמים ולחתם חזון ונביא ולמשח קדש קדשים׃"));
hebsuperobject.biblemap.put("b27_9_25", new hebsuperobject(27,9,25,"ותדע ותשכל מן מצא דבר להשיב ולבנות ירושלם עד משיח נגיד שבעים שבעה ושבעים ששים ושנים תשוב ונבנתה רחוב וחרוץ ובצוק העתים׃"));
hebsuperobject.biblemap.put("b27_9_26", new hebsuperobject(27,9,26,"ואחרי השבעים ששים ושנים יכרת משיח ואין לו והעיר והקדש ישחית עם נגיד הבא וקצו בשטף ועד קץ מלחמה נחרצת שממות׃"));
hebsuperobject.biblemap.put("b27_9_27", new hebsuperobject(27,9,27,"והגביר ברית לרבים שבוע אחד וחצי השבוע ישבית זבח ומנחה ועל כנף שקוצים משמם ועד כלה ונחרצה תתך על שמם׃"));
hebsuperobject.biblemap.put("b27_10_1", new hebsuperobject(27,10,1,"בשנת שלוש לכורש מלך פרס דבר נגלה לדניאל אשר נקרא שמו בלטשאצר ואמת הדבר וצבא גדול ובין את הדבר ובינה לו במראה׃"));
hebsuperobject.biblemap.put("b27_10_2", new hebsuperobject(27,10,2,"בימים ההם אני דניאל הייתי מתאבל שלשה שבעים ימים׃"));
hebsuperobject.biblemap.put("b27_10_3", new hebsuperobject(27,10,3,"לחם חמדות לא אכלתי ובשר ויין לא בא אל פי וסוך לא סכתי עד מלאת שלשת שבעים ימים׃"));
hebsuperobject.biblemap.put("b27_10_4", new hebsuperobject(27,10,4,"וביום עשרים וארבעה לחדש הראשון ואני הייתי על יד הנהר הגדול הוא חדקל׃"));
hebsuperobject.biblemap.put("b27_10_5", new hebsuperobject(27,10,5,"ואשא את עיני וארא והנה איש אחד לבוש בדים ומתניו חגרים בכתם אופז׃"));
hebsuperobject.biblemap.put("b27_10_6", new hebsuperobject(27,10,6,"וגויתו כתרשיש ופניו כמראה ברק ועיניו כלפידי אש וזרעתיו ומרגלתיו כעין נחשת קלל וקול דבריו כקול המון׃"));
hebsuperobject.biblemap.put("b27_10_7", new hebsuperobject(27,10,7,"וראיתי אני דניאל לבדי את המראה והאנשים אשר היו עמי לא ראו את המראה אבל חרדה גדלה נפלה עליהם ויברחו בהחבא׃"));
hebsuperobject.biblemap.put("b27_10_8", new hebsuperobject(27,10,8,"ואני נשארתי לבדי ואראה את המראה הגדלה הזאת ולא נשאר בי כח והודי נהפך עלי למשחית ולא עצרתי כח׃"));
hebsuperobject.biblemap.put("b27_10_9", new hebsuperobject(27,10,9,"ואשמע את קול דבריו וכשמעי את קול דבריו ואני הייתי נרדם על פני ופני ארצה׃"));
hebsuperobject.biblemap.put("b27_10_10", new hebsuperobject(27,10,10,"והנה יד נגעה בי ותניעני על ברכי וכפות ידי׃"));
hebsuperobject.biblemap.put("b27_10_11", new hebsuperobject(27,10,11,"ויאמר אלי דניאל איש חמדות הבן בדברים אשר אנכי דבר אליך ועמד על עמדך כי עתה שלחתי אליך ובדברו עמי את הדבר הזה עמדתי מרעיד׃"));
hebsuperobject.biblemap.put("b27_10_12", new hebsuperobject(27,10,12,"ויאמר אלי אל תירא דניאל כי מן היום הראשון אשר נתת את לבך להבין ולהתענות לפני אלהיך נשמעו דבריך ואני באתי בדבריך׃"));
hebsuperobject.biblemap.put("b27_10_13", new hebsuperobject(27,10,13,"ושר מלכות פרס עמד לנגדי עשרים ואחד יום והנה מיכאל אחד השרים הראשנים בא לעזרני ואני נותרתי שם אצל מלכי פרס׃"));
hebsuperobject.biblemap.put("b27_10_14", new hebsuperobject(27,10,14,"ובאתי להבינך את אשר יקרה לעמך באחרית הימים כי עוד חזון לימים׃"));
hebsuperobject.biblemap.put("b27_10_15", new hebsuperobject(27,10,15,"ובדברו עמי כדברים האלה נתתי פני ארצה ונאלמתי׃"));
hebsuperobject.biblemap.put("b27_10_16", new hebsuperobject(27,10,16,"והנה כדמות בני אדם נגע על שפתי ואפתח פי ואדברה ואמרה אל העמד לנגדי אדני במראה נהפכו צירי עלי ולא עצרתי כח׃"));
hebsuperobject.biblemap.put("b27_10_17", new hebsuperobject(27,10,17,"והיך יוכל עבד אדני זה לדבר עם אדני זה ואני מעתה לא יעמד בי כח ונשמה לא נשארה בי׃"));
hebsuperobject.biblemap.put("b27_10_18", new hebsuperobject(27,10,18,"ויסף ויגע בי כמראה אדם ויחזקני׃"));
hebsuperobject.biblemap.put("b27_10_19", new hebsuperobject(27,10,19,"ויאמר אל תירא איש חמדות שלום לך חזק וחזק וכדברו עמי התחזקתי ואמרה ידבר אדני כי חזקתני׃"));
hebsuperobject.biblemap.put("b27_10_20", new hebsuperobject(27,10,20,"ויאמר הידעת למה באתי אליך ועתה אשוב להלחם עם שר פרס ואני יוצא והנה שר יון בא׃"));
hebsuperobject.biblemap.put("b27_10_21", new hebsuperobject(27,10,21,"אבל אגיד לך את הרשום בכתב אמת ואין אחד מתחזק עמי על אלה כי אם מיכאל שרכם׃"));
hebsuperobject.biblemap.put("b27_11_1", new hebsuperobject(27,11,1,"ואני בשנת אחת לדריוש המדי עמדי למחזיק ולמעוז לו׃"));
hebsuperobject.biblemap.put("b27_11_2", new hebsuperobject(27,11,2,"ועתה אמת אגיד לך הנה עוד שלשה מלכים עמדים לפרס והרביעי יעשיר עשר גדול מכל וכחזקתו בעשרו יעיר הכל את מלכות יון׃"));
hebsuperobject.biblemap.put("b27_11_3", new hebsuperobject(27,11,3,"ועמד מלך גבור ומשל ממשל רב ועשה כרצונו׃"));
hebsuperobject.biblemap.put("b27_11_4", new hebsuperobject(27,11,4,"וכעמדו תשבר מלכותו ותחץ לארבע רוחות השמים ולא לאחריתו ולא כמשלו אשר משל כי תנתש מלכותו ולאחרים מלבד אלה׃"));
hebsuperobject.biblemap.put("b27_11_5", new hebsuperobject(27,11,5,"ויחזק מלך הנגב ומן שריו ויחזק עליו ומשל ממשל רב ממשלתו׃"));
hebsuperobject.biblemap.put("b27_11_6", new hebsuperobject(27,11,6,"ולקץ שנים יתחברו ובת מלך הנגב תבוא אל מלך הצפון לעשות מישרים ולא תעצר כוח הזרוע ולא יעמד וזרעו ותנתן היא ומביאיה והילדה ומחזקה בעתים׃"));
hebsuperobject.biblemap.put("b27_11_7", new hebsuperobject(27,11,7,"ועמד מנצר שרשיה כנו ויבא אל החיל ויבא במעוז מלך הצפון ועשה בהם והחזיק׃"));
hebsuperobject.biblemap.put("b27_11_8", new hebsuperobject(27,11,8,"וגם אלהיהם עם נסכיהם עם כלי חמדתם כסף וזהב בשבי יבא מצרים והוא שנים יעמד ממלך הצפון׃"));
hebsuperobject.biblemap.put("b27_11_9", new hebsuperobject(27,11,9,"ובא במלכות מלך הנגב ושב אל אדמתו׃"));
hebsuperobject.biblemap.put("b27_11_10", new hebsuperobject(27,11,10,"ובנו יתגרו ואספו המון חילים רבים ובא בוא ושטף ועבר וישב ויתגרו עד מעזה׃"));
hebsuperobject.biblemap.put("b27_11_11", new hebsuperobject(27,11,11,"ויתמרמר מלך הנגב ויצא ונלחם עמו עם מלך הצפון והעמיד המון רב ונתן ההמון בידו׃"));
hebsuperobject.biblemap.put("b27_11_12", new hebsuperobject(27,11,12,"ונשא ההמון ירום לבבו והפיל רבאות ולא יעוז׃"));
hebsuperobject.biblemap.put("b27_11_13", new hebsuperobject(27,11,13,"ושב מלך הצפון והעמיד המון רב מן הראשון ולקץ העתים שנים יבוא בוא בחיל גדול וברכוש רב׃"));
hebsuperobject.biblemap.put("b27_11_14", new hebsuperobject(27,11,14,"ובעתים ההם רבים יעמדו על מלך הנגב ובני פריצי עמך ינשאו להעמיד חזון ונכשלו׃"));
hebsuperobject.biblemap.put("b27_11_15", new hebsuperobject(27,11,15,"ויבא מלך הצפון וישפך סוללה ולכד עיר מבצרות וזרעות הנגב לא יעמדו ועם מבחריו ואין כח לעמד׃"));
hebsuperobject.biblemap.put("b27_11_16", new hebsuperobject(27,11,16,"ויעש הבא אליו כרצונו ואין עומד לפניו ויעמד בארץ הצבי וכלה בידו׃"));
hebsuperobject.biblemap.put("b27_11_17", new hebsuperobject(27,11,17,"וישם פניו לבוא בתקף כל מלכותו וישרים עמו ועשה ובת הנשים יתן לו להשחיתה ולא תעמד ולא לו תהיה׃"));
hebsuperobject.biblemap.put("b27_11_18", new hebsuperobject(27,11,18,"וישב פניו לאיים ולכד רבים והשבית קצין חרפתו לו בלתי חרפתו ישיב לו׃"));
hebsuperobject.biblemap.put("b27_11_19", new hebsuperobject(27,11,19,"וישב פניו למעוזי ארצו ונכשל ונפל ולא ימצא׃"));
hebsuperobject.biblemap.put("b27_11_20", new hebsuperobject(27,11,20,"ועמד על כנו מעביר נוגש הדר מלכות ובימים אחדים ישבר ולא באפים ולא במלחמה׃"));
hebsuperobject.biblemap.put("b27_11_21", new hebsuperobject(27,11,21,"ועמד על כנו נבזה ולא נתנו עליו הוד מלכות ובא בשלוה והחזיק מלכות בחלקלקות׃"));
hebsuperobject.biblemap.put("b27_11_22", new hebsuperobject(27,11,22,"וזרעות השטף ישטפו מלפניו וישברו וגם נגיד ברית׃"));
hebsuperobject.biblemap.put("b27_11_23", new hebsuperobject(27,11,23,"ומן התחברות אליו יעשה מרמה ועלה ועצם במעט גוי׃"));
hebsuperobject.biblemap.put("b27_11_24", new hebsuperobject(27,11,24,"בשלוה ובמשמני מדינה יבוא ועשה אשר לא עשו אבתיו ואבות אבתיו בזה ושלל ורכוש להם יבזור ועל מבצרים יחשב מחשבתיו ועד עת׃"));
hebsuperobject.biblemap.put("b27_11_25", new hebsuperobject(27,11,25,"ויער כחו ולבבו על מלך הנגב בחיל גדול ומלך הנגב יתגרה למלחמה בחיל גדול ועצום עד מאד ולא יעמד כי יחשבו עליו מחשבות׃"));
hebsuperobject.biblemap.put("b27_11_26", new hebsuperobject(27,11,26,"ואכלי פת בגו ישברוהו וחילו ישטוף ונפלו חללים רבים׃"));
hebsuperobject.biblemap.put("b27_11_27", new hebsuperobject(27,11,27,"ושניהם המלכים לבבם למרע ועל שלחן אחד כזב ידברו ולא תצלח כי עוד קץ למועד׃"));
hebsuperobject.biblemap.put("b27_11_28", new hebsuperobject(27,11,28,"וישב ארצו ברכוש גדול ולבבו על ברית קדש ועשה ושב לארצו׃"));
hebsuperobject.biblemap.put("b27_11_29", new hebsuperobject(27,11,29,"למועד ישוב ובא בנגב ולא תהיה כראשנה וכאחרנה׃"));
hebsuperobject.biblemap.put("b27_11_30", new hebsuperobject(27,11,30,"ובאו בו ציים כתים ונכאה ושב וזעם על ברית קודש ועשה ושב ויבן על עזבי ברית קדש׃"));
hebsuperobject.biblemap.put("b27_11_31", new hebsuperobject(27,11,31,"וזרעים ממנו יעמדו וחללו המקדש המעוז והסירו התמיד ונתנו השקוץ משומם׃"));
hebsuperobject.biblemap.put("b27_11_32", new hebsuperobject(27,11,32,"ומרשיעי ברית יחניף בחלקות ועם ידעי אלהיו יחזקו ועשו׃"));
hebsuperobject.biblemap.put("b27_11_33", new hebsuperobject(27,11,33,"ומשכילי עם יבינו לרבים ונכשלו בחרב ובלהבה בשבי ובבזה ימים׃"));
hebsuperobject.biblemap.put("b27_11_34", new hebsuperobject(27,11,34,"ובהכשלם יעזרו עזר מעט ונלוו עליהם רבים בחלקלקות׃"));
hebsuperobject.biblemap.put("b27_11_35", new hebsuperobject(27,11,35,"ומן המשכילים יכשלו לצרוף בהם ולברר וללבן עד עת קץ כי עוד למועד׃"));
hebsuperobject.biblemap.put("b27_11_36", new hebsuperobject(27,11,36,"ועשה כרצונו המלך ויתרומם ויתגדל על כל אל ועל אל אלים ידבר נפלאות והצליח עד כלה זעם כי נחרצה נעשתה׃"));
hebsuperobject.biblemap.put("b27_11_37", new hebsuperobject(27,11,37,"ועל אלהי אבתיו לא יבין ועל חמדת נשים ועל כל אלוה לא יבין כי על כל יתגדל׃"));
hebsuperobject.biblemap.put("b27_11_38", new hebsuperobject(27,11,38,"ולאלה מעזים על כנו יכבד ולאלוה אשר לא ידעהו אבתיו יכבד בזהב ובכסף ובאבן יקרה ובחמדות׃"));
hebsuperobject.biblemap.put("b27_11_39", new hebsuperobject(27,11,39,"ועשה למבצרי מעזים עם אלוה נכר אשר הכיר ירבה כבוד והמשילם ברבים ואדמה יחלק במחיר׃"));
hebsuperobject.biblemap.put("b27_11_40", new hebsuperobject(27,11,40,"ובעת קץ יתנגח עמו מלך הנגב וישתער עליו מלך הצפון ברכב ובפרשים ובאניות רבות ובא בארצות ושטף ועבר׃"));
hebsuperobject.biblemap.put("b27_11_41", new hebsuperobject(27,11,41,"ובא בארץ הצבי ורבות יכשלו ואלה ימלטו מידו אדום ומואב וראשית בני עמון׃"));
hebsuperobject.biblemap.put("b27_11_42", new hebsuperobject(27,11,42,"וישלח ידו בארצות וארץ מצרים לא תהיה לפליטה׃"));
hebsuperobject.biblemap.put("b27_11_43", new hebsuperobject(27,11,43,"ומשל במכמני הזהב והכסף ובכל חמדות מצרים ולבים וכשים במצעדיו׃"));
hebsuperobject.biblemap.put("b27_11_44", new hebsuperobject(27,11,44,"ושמעות יבהלהו ממזרח ומצפון ויצא בחמא גדלה להשמיד ולהחרים רבים׃"));
hebsuperobject.biblemap.put("b27_11_45", new hebsuperobject(27,11,45,"ויטע אהלי אפדנו בין ימים להר צבי קדש ובא עד קצו ואין עוזר לו׃"));
hebsuperobject.biblemap.put("b27_12_1", new hebsuperobject(27,12,1,"ובעת ההיא יעמד מיכאל השר הגדול העמד על בני עמך והיתה עת צרה אשר לא נהיתה מהיות גוי עד העת ההיא ובעת ההיא ימלט עמך כל הנמצא כתוב בספר׃"));
hebsuperobject.biblemap.put("b27_12_2", new hebsuperobject(27,12,2,"ורבים מישני אדמת עפר יקיצו אלה לחיי עולם ואלה לחרפות לדראון עולם׃"));
hebsuperobject.biblemap.put("b27_12_3", new hebsuperobject(27,12,3,"והמשכלים יזהרו כזהר הרקיע ומצדיקי הרבים ככוכבים לעולם ועד׃"));
hebsuperobject.biblemap.put("b27_12_4", new hebsuperobject(27,12,4,"ואתה דניאל סתם הדברים וחתם הספר עד עת קץ ישטטו רבים ותרבה הדעת׃"));
hebsuperobject.biblemap.put("b27_12_5", new hebsuperobject(27,12,5,"וראיתי אני דניאל והנה שנים אחרים עמדים אחד הנה לשפת היאר ואחד הנה לשפת היאר׃"));
hebsuperobject.biblemap.put("b27_12_6", new hebsuperobject(27,12,6,"ויאמר לאיש לבוש הבדים אשר ממעל למימי היאר עד מתי קץ הפלאות׃"));
hebsuperobject.biblemap.put("b27_12_7", new hebsuperobject(27,12,7,"ואשמע את האיש לבוש הבדים אשר ממעל למימי היאר וירם ימינו ושמאלו אל השמים וישבע בחי העולם כי למועד מועדים וחצי וככלות נפץ יד עם קדש תכלינה כל אלה׃"));
hebsuperobject.biblemap.put("b27_12_8", new hebsuperobject(27,12,8,"ואני שמעתי ולא אבין ואמרה אדני מה אחרית אלה׃"));
hebsuperobject.biblemap.put("b27_12_9", new hebsuperobject(27,12,9,"ויאמר לך דניאל כי סתמים וחתמים הדברים עד עת קץ׃"));
hebsuperobject.biblemap.put("b27_12_10", new hebsuperobject(27,12,10,"יתבררו ויתלבנו ויצרפו רבים והרשיעו רשעים ולא יבינו כל רשעים והמשכלים יבינו׃"));
hebsuperobject.biblemap.put("b27_12_11", new hebsuperobject(27,12,11,"ומעת הוסר התמיד ולתת שקוץ שמם ימים אלף מאתים ותשעים׃"));
hebsuperobject.biblemap.put("b27_12_12", new hebsuperobject(27,12,12,"אשרי המחכה ויגיע לימים אלף שלש מאות שלשים וחמשה׃"));
hebsuperobject.biblemap.put("b27_12_13", new hebsuperobject(27,12,13,"ואתה לך לקץ ותנוח ותעמד לגרלך לקץ הימין׃"));

}

}