package heb.bible;

public class hebbible66 {

public hebbible66() {

putmapbible66();

}

private void putmapbible66() {

hebsuperobject.biblemap.put("b66_1_1", new hebsuperobject(66,1,1,"חזון ישוע המשיח אשר נתן לו האלהים להראות את עבדיו את אשר היה יהיה במהרה והוא הודיע בשלחו ביד מלאכו לעבדו יוחנן׃"));
hebsuperobject.biblemap.put("b66_1_2", new hebsuperobject(66,1,2,"אשר העיד דבר האלהים ועדות ישוע המשיח ואת כל אשר ראה׃"));
hebsuperobject.biblemap.put("b66_1_3", new hebsuperobject(66,1,3,"אשרי הקורא ואשרי השמעים את דברי הנבואה ושמרים את אשר כתוב בה כי קרובה העת׃"));
hebsuperobject.biblemap.put("b66_1_4", new hebsuperobject(66,1,4,"יוחנן אל שבע הקהלות אשר באסיא חסד לכם ושלום מאת ההוה והיה ויבוא ומן שבעת הרוחות אשר לפני כסאו׃"));
hebsuperobject.biblemap.put("b66_1_5", new hebsuperobject(66,1,5,"ומאת ישוע המשיח העד הנאמן ובכור מן המתים ועליון למלכי ארץ לו אשר אהב אתנו ובדמו גאלנו מחטאתינו׃"));
hebsuperobject.biblemap.put("b66_1_6", new hebsuperobject(66,1,6,"ויעש אתנו למלכים וכהנים לאלהים אביו הכבוד והעז לעולמי עולמים אמן׃"));
hebsuperobject.biblemap.put("b66_1_7", new hebsuperobject(66,1,7,"הנה הוא בא עם העננים וראתה אתו כל עין גם אלה אשר דקרהו וספדו עליו כל משפחות הארץ כן יהיה אמן׃"));
hebsuperobject.biblemap.put("b66_1_8", new hebsuperobject(66,1,8,"אני האלף ואני התו ראש וסוף נאם יהוה אלהים ההוה והיה ויבוא אלהי צבאות׃"));
hebsuperobject.biblemap.put("b66_1_9", new hebsuperobject(66,1,9,"אני יוחנן אחיכם וגם חבר לכם בלחץ ובמלכות ובסבלנות למען ישוע המשיח הייתי באי אשר שמו פטמוס בעבור דבר האלהים ובעבור עדות ישוע המשיח׃"));
hebsuperobject.biblemap.put("b66_1_10", new hebsuperobject(66,1,10,"ואהי ברוח ביום האדון ואשמע אחרי קול גדול כקול שופר׃"));
hebsuperobject.biblemap.put("b66_1_11", new hebsuperobject(66,1,11,"ויאמר אני האלף ואני התו הראשון והאחרון ואת אשר אתה ראה כתב אל ספר ושלחהו אל הקהלות אשר באסיא לאפסוס ולזמירנא ולפרגמוס ולתיאטירא ולסרדיס ולפילדפיא וללודקיא׃"));
hebsuperobject.biblemap.put("b66_1_12", new hebsuperobject(66,1,12,"ואפן לראות את הקול המדבר אלי ויהי בפנותי וארא שבע מנרות זהב׃"));
hebsuperobject.biblemap.put("b66_1_13", new hebsuperobject(66,1,13,"ובתוך שבע המנרות דמות בן אדם לבוש מעיל וחגור אזור זהב על לבו׃"));
hebsuperobject.biblemap.put("b66_1_14", new hebsuperobject(66,1,14,"וראשו ושערו לבנים כצמר צחר כשלג ועיניו כלבת אש׃"));
hebsuperobject.biblemap.put("b66_1_15", new hebsuperobject(66,1,15,"ומרגלתיו כעין נחשת קלל כצרופות בכור וקולו כקול מים רבים׃"));
hebsuperobject.biblemap.put("b66_1_16", new hebsuperobject(66,1,16,"ויהי לו ביד ימינו שבעה כוכבים ומפיו יוצאת חרב פיפיות חדה ופניו כשמש המאיר בגבורתו׃"));
hebsuperobject.biblemap.put("b66_1_17", new hebsuperobject(66,1,17,"וכראתי אותו ואפל לרגליו כמת וישת עלי יד ימינו ויאמר אל תירא אני הראשון והאחרון והחי׃"));
hebsuperobject.biblemap.put("b66_1_18", new hebsuperobject(66,1,18,"ואהי מת והנני חי לעולמי עולמים אמן ובידי מפתחות שאול ומות׃"));
hebsuperobject.biblemap.put("b66_1_19", new hebsuperobject(66,1,19,"ועתה כתב את אשר ראית ואשר נעשה עתה ואשר עתיד להיות אחרי כן׃"));
hebsuperobject.biblemap.put("b66_1_20", new hebsuperobject(66,1,20,"את סוד שבעת הכוכבים אשר ראית בימיני ואת שבע מנרות הזהב שבעת הכוכבים הם מלאכי שבע הקהלות ושבע המנרות אשר ראית שבע קהלות הנה׃"));
hebsuperobject.biblemap.put("b66_2_1", new hebsuperobject(66,2,1,"אל מלאך קהל אפסוס כתב כה אמר האחז בימינו שבעת הכוכבים המתהלך בתוך שבע מנרות הזהב׃"));
hebsuperobject.biblemap.put("b66_2_2", new hebsuperobject(66,2,2,"ידעתי את מעשיך ואת עמלך ואת סבלך וכי לא תוכל שאת את הרשעים ותנסה את האמרים שליחים אנחנו ואינם ותמצאם כזבים׃"));
hebsuperobject.biblemap.put("b66_2_3", new hebsuperobject(66,2,3,"ואתה נשאת הרבה ויש לך סבלנות ולמען שמי לא יעפת׃"));
hebsuperobject.biblemap.put("b66_2_4", new hebsuperobject(66,2,4,"אך יש לי עליך כי עזבת את אהבתך הראשונה׃"));
hebsuperobject.biblemap.put("b66_2_5", new hebsuperobject(66,2,5,"זכר אפוא אי מזה נפלת ושובה ועשה מעשיך הראשנים ואם לא הנני בא עליך מהר ונסחתי מנורתך ממקומה אם לא תשוב׃"));
hebsuperobject.biblemap.put("b66_2_6", new hebsuperobject(66,2,6,"אבל זאת היא לך כי תשנא את מעשי הניקלסיים אשר שנאתים גם אני׃"));
hebsuperobject.biblemap.put("b66_2_7", new hebsuperobject(66,2,7,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות המנצח אתן לו לאכל מעץ החיים אשר בתוך גן עדן לאלהים׃"));
hebsuperobject.biblemap.put("b66_2_8", new hebsuperobject(66,2,8,"ואל מלאך קהל זמירנא כתב כה אמר הראשון והאחרון אשר מת ויחי׃"));
hebsuperobject.biblemap.put("b66_2_9", new hebsuperobject(66,2,9,"ידעתי את מעשיך ואת צרתך ואת רישך ואולם עשיר אתה ואת גדוף האמרים יהודים אנחנו ואינם כי אם כנסית השטן׃"));
hebsuperobject.biblemap.put("b66_2_10", new hebsuperobject(66,2,10,"אל תירא את אשר עליך לסבל הנה עתיד המלשין להשליך מכם לבית המשמר למען תנסו והייתם בצרה עשרת ימים היה נאמן עד מות ואתנה לך עטרת החיים׃"));
hebsuperobject.biblemap.put("b66_2_11", new hebsuperobject(66,2,11,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות המנצח לא ינזק במות השני׃"));
hebsuperobject.biblemap.put("b66_2_12", new hebsuperobject(66,2,12,"ואל מלאך קהל פרגמוס כתב כה אמר אשר לו חרב פיפיות החדה׃"));
hebsuperobject.biblemap.put("b66_2_13", new hebsuperobject(66,2,13,"ידעתי את מעשיך ואת מקום שבתך אשר שם כסא השטן ותדבק בשמי ולא שקרת באמונתי גם בימי אנטיפס עדי הנאמן אשר נהרג אצלכם מקום מושב השטן׃"));
hebsuperobject.biblemap.put("b66_2_14", new hebsuperobject(66,2,14,"אך מעט יש לי עליך כי שם עמך אנשים דבקים בתורת בלעם אשר הורה את בלק לתת מכשול לפני בני ישראל לאכל מזבחי אלילים ולזנות׃"));
hebsuperobject.biblemap.put("b66_2_15", new hebsuperobject(66,2,15,"כן נמצאו גם בך אנשים דבקים בתורת הניקלסיים אשר שנאתי׃"));
hebsuperobject.biblemap.put("b66_2_16", new hebsuperobject(66,2,16,"שובה ואם לא כי עתה אבוא עליך מהרה ונלחמתי בם בחרב פי׃"));
hebsuperobject.biblemap.put("b66_2_17", new hebsuperobject(66,2,17,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות המנצח אאכילנו מן המן הגנוז ונתתי לו אבן לבנה ועל האבן מפתח שם חדש אשר לא ידענו איש זולתי המקבל׃"));
hebsuperobject.biblemap.put("b66_2_18", new hebsuperobject(66,2,18,"ואל מלאך קהל תיאטירא כתב כה אמר בן האלהים אשר עיניו כלבת אש ומרגלתיו כעין נחשת קלל׃"));
hebsuperobject.biblemap.put("b66_2_19", new hebsuperobject(66,2,19,"ידעתי את מעשיך ואהבתך ואמונתך ועבורתך וסבלך וכי מעשיך האחרונים רבים הם מן הראשנים׃"));
hebsuperobject.biblemap.put("b66_2_20", new hebsuperobject(66,2,20,"אך מעט יש לי עליך כי תניח את האשה איזבל האמרת כי היא נביאה ללמד ולהתעות את עבדי לזנות ולאכל זבחי אלילים׃"));
hebsuperobject.biblemap.put("b66_2_21", new hebsuperobject(66,2,21,"ואתן לה זמן לשוב והיא מאנה לשוב מתזנותיה׃"));
hebsuperobject.biblemap.put("b66_2_22", new hebsuperobject(66,2,22,"הנני מפיל אתה על מטה ואת המנאפים אתה בצרה גדולה אם לא ישובו ממעשיהם׃"));
hebsuperobject.biblemap.put("b66_2_23", new hebsuperobject(66,2,23,"והרגתי במות את בניה וידעו כל הקהלות כי אני חקר כליות ולב ונתתי לכם לכל איש כפרי מעלליו׃"));
hebsuperobject.biblemap.put("b66_2_24", new hebsuperobject(66,2,24,"אבל אמר אני לכם ולשאר הנמצאים בתיאטירא כל אשר אין להם הלקח ההוא ולא ידעו את עמקות השטן כאשר הם מתהללים לא אשים עליכם משא אחר׃"));
hebsuperobject.biblemap.put("b66_2_25", new hebsuperobject(66,2,25,"אפס מה שיש לכם החזיקו בו עד כי אבוא׃"));
hebsuperobject.biblemap.put("b66_2_26", new hebsuperobject(66,2,26,"והמנצח ושמר את מעשי עד עת קץ אתן לו שלטן על הגוים׃"));
hebsuperobject.biblemap.put("b66_2_27", new hebsuperobject(66,2,27,"ורעם בשבט ברזל ככלי יוצר ינפצו כאשר קבלתי גם אנכי מאת אבי׃"));
hebsuperobject.biblemap.put("b66_2_28", new hebsuperobject(66,2,28,"ונתתי לו כוכב השחר׃"));
hebsuperobject.biblemap.put("b66_2_29", new hebsuperobject(66,2,29,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות׃"));
hebsuperobject.biblemap.put("b66_3_1", new hebsuperobject(66,3,1,"ואל מלאך קהל סרדיס כתב כה אמר אשר לו שבע רוחות האלהים ושבעת הכוכבים ידעתי את מעשיך כי לך שם כאלו אתה חי והנך מת׃"));
hebsuperobject.biblemap.put("b66_3_2", new hebsuperobject(66,3,2,"שקד וחזק את השארית הקרובה למות כי לא מצאתי מעשיך שלמים לפני האלהים׃"));
hebsuperobject.biblemap.put("b66_3_3", new hebsuperobject(66,3,3,"זכור את אשר קבלת ושמעת ושמרה זאת ושובה ואם לא תשקד הנני בא עליך כגנב ולא תדע באי זו שעה אבא עליך׃"));
hebsuperobject.biblemap.put("b66_3_4", new hebsuperobject(66,3,4,"יש לך גם בסרדיס שמות מעטים אשר לא גאלו את מלבושיהם ויתהלכו אתי לבשי לבנים כי ראוים הם לזאת׃"));
hebsuperobject.biblemap.put("b66_3_5", new hebsuperobject(66,3,5,"המנצח ילבש בגדים לבנים ולא אמחה את שמו מספר החיים ואודה שמו לפני אבי ולפני מלאכיו׃"));
hebsuperobject.biblemap.put("b66_3_6", new hebsuperobject(66,3,6,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות׃"));
hebsuperobject.biblemap.put("b66_3_7", new hebsuperobject(66,3,7,"ואל מלאך קהל פילדלפיא כתב כה אמר הקדוש האמתי אשר בידו מפתח דוד הפתח ואין סגר והסגר ואין פתח׃"));
hebsuperobject.biblemap.put("b66_3_8", new hebsuperobject(66,3,8,"ידעתי את מעשיך הנה נתתי לפניך פתח נפתח אשר לא יוכל איש לסגרו כי גבורת מעט לך ותשמר את דברי ולא כחשת בשמי׃"));
hebsuperobject.biblemap.put("b66_3_9", new hebsuperobject(66,3,9,"הנני נתן אנשים מכנסית השטן האמרים יהודים אנחנו ואינם כי כזבים המה הנני עשה אשר יבאו להשתחות לפני רגליך וידעו כי אני אהבתיך׃"));
hebsuperobject.biblemap.put("b66_3_10", new hebsuperobject(66,3,10,"יען שמרת דבר סבלנותי אשמרך גם אנכי משעת הנסיון העתידה לבוא על תבל כלה לנסות את ישבי הארץ׃"));
hebsuperobject.biblemap.put("b66_3_11", new hebsuperobject(66,3,11,"הנני בא מהרה החזק באשר לך למען לא יקח איש את נזרך׃"));
hebsuperobject.biblemap.put("b66_3_12", new hebsuperobject(66,3,12,"המנצח אתננו לעמוד בהיכל אלהי ולא יצא עוד החוצה וכתבתי עליו את שם אלהי ואת שם עיר אלהי ירושלים החדשה הירדת משמים מעם אלהי ואת שמי החדש׃"));
hebsuperobject.biblemap.put("b66_3_13", new hebsuperobject(66,3,13,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות׃"));
hebsuperobject.biblemap.put("b66_3_14", new hebsuperobject(66,3,14,"ואל מלאך קהל לודקיא כתב כה אמר האמן העד הנאמן והאמתי ראשית בריאת האלהים׃"));
hebsuperobject.biblemap.put("b66_3_15", new hebsuperobject(66,3,15,"ידעתי את מעשיך כי לא קר ולא חם אתה מי יתן והיית קר או חם׃"));
hebsuperobject.biblemap.put("b66_3_16", new hebsuperobject(66,3,16,"כי עתה פושר אתה ולא קר ולא חם על כן אקיאך מפי׃"));
hebsuperobject.biblemap.put("b66_3_17", new hebsuperobject(66,3,17,"כי אמרת אך עשרתי מצאתי און לי ולא חסרתי כל ולא ידעת כי אמלל אתה ודוי ועני ועור וערם׃"));
hebsuperobject.biblemap.put("b66_3_18", new hebsuperobject(66,3,18,"אני איעצך לפנות מאתי זהב צרוף באש למען תעשיר ובגדים לבנים למען תתכסה בהם ולא תראה בשת ערותות ולמשח עיניך קלורית למען תראה׃"));
hebsuperobject.biblemap.put("b66_3_19", new hebsuperobject(66,3,19,"]12-02[ אני את כל אשר אהב אוכיחם ואיסרם לכן תשקד ותשוב, הנני עמד לפתח ודפק והיה כי ישמע איש לקולי ופתח הפתח אבוא אליו לסעוד עמו והוא עמדי׃"));
hebsuperobject.biblemap.put("b66_3_20", new hebsuperobject(66,3,20,"]12-02[׃"));
hebsuperobject.biblemap.put("b66_3_21", new hebsuperobject(66,3,21,"המנצח אתננו לשבת אתי על כסאי כאשר נצחתי גם אנכי ואשב את אבי על כסאו׃"));
hebsuperobject.biblemap.put("b66_3_22", new hebsuperobject(66,3,22,"מי אשר אזן לו ישמע את אשר הרוח אמר לקהלות׃"));
hebsuperobject.biblemap.put("b66_4_1", new hebsuperobject(66,4,1,"ויהי אחר הדברים האלה וארא והנה פתח נפתח בשמים והקול הראשון אשר שמעתיו כקול שופר מדבר אלי אמר עלה הנה ואראך את אשר היה יהיה אחרי כן׃"));
hebsuperobject.biblemap.put("b66_4_2", new hebsuperobject(66,4,2,"וכרגע הייתי ברוח והנה כסא נראה בשמים ואחד ישב על הכסא׃"));
hebsuperobject.biblemap.put("b66_4_3", new hebsuperobject(66,4,3,"והישב מראהו כמראה אבן ישפה ואדם וקשת סביב לכסא ומראיה כעין ברקת׃"));
hebsuperobject.biblemap.put("b66_4_4", new hebsuperobject(66,4,4,"וסביב לכסא ארבעה ועשרים כסאות ועל הכסאות ראיתי את ארבעה ועשרים הזקנים ישבים והם לבשי בגדים לבנים ועטרות זהב בראשיהם׃"));
hebsuperobject.biblemap.put("b66_4_5", new hebsuperobject(66,4,5,"ומן הכסא יוצאים ברקים ורעמים וקולות ושבעה לפידי אש בערים לפני הכסא אשר הם שבעה רוחות האלהים׃"));
hebsuperobject.biblemap.put("b66_4_6", new hebsuperobject(66,4,6,"ולפני הכסא ים זכוכית כעין הקרח ובין הכסא וסביב לכסא ארבע חיות מלאות עינים מלפניהם ומאחריהם׃"));
hebsuperobject.biblemap.put("b66_4_7", new hebsuperobject(66,4,7,"ודמות החיה הראשונה כאריה והחיה השנית כשור ופני החיה השלישית כפני אדם ודמות החיה הרביעית כנשר מעופף׃"));
hebsuperobject.biblemap.put("b66_4_8", new hebsuperobject(66,4,8,"ולכל אחת מארבע החיות שש כנפים מסביב ולפנימה הנה מלאות עינים ואין דמי להן יומם ולילה ואמרות קדוש קדוש קדוש יהוה אלהים צבאות היה והוה ויבוא׃"));
hebsuperobject.biblemap.put("b66_4_9", new hebsuperobject(66,4,9,"ומדי תת החיות כבוד והדר ותודה לישב על הכסא אשר הוא חי לעולמי עולמים׃"));
hebsuperobject.biblemap.put("b66_4_10", new hebsuperobject(66,4,10,"אז יפלו עשרים וארבעה הזקנים על פניהם לפני הישב על הכסא והשתחוו לחי עולמי העולמים ושמו את עטרותיהם לפני הכסא לאמר׃"));
hebsuperobject.biblemap.put("b66_4_11", new hebsuperobject(66,4,11,"לך נאה אדנינו לקחת כבוד והדר ועז כי אתה בראת הכל והכל ברצונך היו ונבראו׃"));
hebsuperobject.biblemap.put("b66_5_1", new hebsuperobject(66,5,1,"וארא בימין הישב על הכסא ספר כתוב פנים ואחור וחתום בשבעה חתמות׃"));
hebsuperobject.biblemap.put("b66_5_2", new hebsuperobject(66,5,2,"וארא מלאך אביר קורא בקול גדול מי הוא הזכה לפתח הספר ולהתיר את חותמיו׃"));
hebsuperobject.biblemap.put("b66_5_3", new hebsuperobject(66,5,3,"ולא יכל איש גם בשמים גם בארץ גם מתחת לארץ לפתח את הספר או להביט אליו׃"));
hebsuperobject.biblemap.put("b66_5_4", new hebsuperobject(66,5,4,"ואבך בכי גדול על אשר לא נמצא איש זכה לפתח את הספר ולקרא בו או להביט אליו׃"));
hebsuperobject.biblemap.put("b66_5_5", new hebsuperobject(66,5,5,"ויאמר אלי אחד מן הזקנים אל תבכה הנה נצח האריה אשר הוא משבט יהודה שרש דוד לפתח את הספר ולהתיר שבעת חותמיו׃"));
hebsuperobject.biblemap.put("b66_5_6", new hebsuperobject(66,5,6,"וארא והנה בין הכסא וארבע החיות ובין הזקנים שה עמד כמו טבוח ולו שבע קרנים ושבעה עינים אשר הם שבעה רוחות האלהים השלוחים אל כל הארץ׃"));
hebsuperobject.biblemap.put("b66_5_7", new hebsuperobject(66,5,7,"ויבא ויקח את הספר מימין הישב על הכסא׃"));
hebsuperobject.biblemap.put("b66_5_8", new hebsuperobject(66,5,8,"ויהי בקחתו את הספר ויפלו לפני השה ארבע החיות ועשרים וארבעה הזקנים ואיש איש כנור בידו וקערות זהב מלאת קטרת אשר הנה תפלות הקדושים׃"));
hebsuperobject.biblemap.put("b66_5_9", new hebsuperobject(66,5,9,"וישירו שיר חדש לאמר לך נאה לקחת את הספר ולפתח את חותמיו כי אתה נשחטת ובדמך קניתנו לאלהים מכל משפחה ולשון וכל עם וגוי׃"));
hebsuperobject.biblemap.put("b66_5_10", new hebsuperobject(66,5,10,"ותעש אתם מלכים וכהנים לאלהינו וימלכו על הארץ׃"));
hebsuperobject.biblemap.put("b66_5_11", new hebsuperobject(66,5,11,"וארא ואשמע קול מלאכים רבים סביב לכסא ולחיות ולזקנים מספרם רבו רבבות ואלפי אלפים׃"));
hebsuperobject.biblemap.put("b66_5_12", new hebsuperobject(66,5,12,"קראים בקול גדול נאה לשה הטבוח לקחת עז ועשר וחכמה וגבורה והדר וכבוד וברכה׃"));
hebsuperobject.biblemap.put("b66_5_13", new hebsuperobject(66,5,13,"וכל בריה אשר בשמים ובארץ ומתחת לארץ ואשר על הים וכל אשר בהם את כלם שמעתי אמרים לאמר לישב על הכסא ולשה הברכה וההדר והכבוד והעז לעולמי עולמים׃"));
hebsuperobject.biblemap.put("b66_5_14", new hebsuperobject(66,5,14,"ותאמרנה ארבע החיות אמן ועשרים וארבעה הזקנים נפלו על פניהם וישתחוו לחי עולמי העולמים׃"));
hebsuperobject.biblemap.put("b66_6_1", new hebsuperobject(66,6,1,"וארא כאשר פתח השה אחד מן שבעה החתמות ואשמע אחת מארבע החיות מדברת כקול רעם לאמר בא וראה׃"));
hebsuperobject.biblemap.put("b66_6_2", new hebsuperobject(66,6,2,"ואביט והנה סוס לבן והרכב עליו קשת בידו ותנתן לו עטרה ויצא מנצח ולמען ינצח׃"));
hebsuperobject.biblemap.put("b66_6_3", new hebsuperobject(66,6,3,"וכפתחו את החותם השני ואשמע את החיה השנית אמרת בא וראה׃"));
hebsuperobject.biblemap.put("b66_6_4", new hebsuperobject(66,6,4,"ויצא סוס שני והוא אדם ולרכב עליו נתן לשאת את השלום מן הארץ למען יהרגו איש את אחיו ותנתן לו חרב גדולה׃"));
hebsuperobject.biblemap.put("b66_6_5", new hebsuperobject(66,6,5,"וכפתחו את החותם השלישי ואשמע את החיה השלישית אמרת בא וראה ואביט והנה סוס שחר והרכב עליו מאזנים בידו׃"));
hebsuperobject.biblemap.put("b66_6_6", new hebsuperobject(66,6,6,"ואשמע קול מתוך ארבע החיות לאמר קב חטים בדינר ושלשה קבים שערים בדינר ואת השמן והיין אל תשחת׃"));
hebsuperobject.biblemap.put("b66_6_7", new hebsuperobject(66,6,7,"וכפתחו את החותם הרביעי ואשמע את החיה הרביעית אמרת בא וראה׃"));
hebsuperobject.biblemap.put("b66_6_8", new hebsuperobject(66,6,8,"וארא והנה סוס ירקרק והרכב עליו שמו המות ושאול יוצאת לרגליו וינתן להם שלטן על רביעית הארץ להמית בחרב וברעב ובדבר ובחית הארץ׃"));
hebsuperobject.biblemap.put("b66_6_9", new hebsuperobject(66,6,9,"וכפתחו החותם החמישי וארא מתחת למזבח את נפשות הטבוחים על דבר האלהים ועל העדות אשר היתה להם׃"));
hebsuperobject.biblemap.put("b66_6_10", new hebsuperobject(66,6,10,"ויזעקו בקול גדול ויאמרו עד מתי אדני הקדוש והאמתי לא תשפט ולא תקום את דמינו מישבי הארץ׃"));
hebsuperobject.biblemap.put("b66_6_11", new hebsuperobject(66,6,11,"ויתן לאיש איש מהם שמלות לבנות ויאמר אליהם לנוח עוד זמן מעט עד מלאת מספר העבדים חברים ואחיהם העתידים להרג כמוהם׃"));
hebsuperobject.biblemap.put("b66_6_12", new hebsuperobject(66,6,12,"וארא בפתחו את החותם הששי והנה רעש גדול היה ויקדר השמש כשק שער והירח נהפך לדם׃"));
hebsuperobject.biblemap.put("b66_6_13", new hebsuperobject(66,6,13,"וכוכבי השמים נפלו ארצה כאשר תנוע תאנה ברוח חזקה והשליכה פגיה׃"));
hebsuperobject.biblemap.put("b66_6_14", new hebsuperobject(66,6,14,"והשמים משו כספר נגלל וכל הר ואי הנתקו ממקומם׃"));
hebsuperobject.biblemap.put("b66_6_15", new hebsuperobject(66,6,15,"ומלכי הארץ והרזנים ושרי האלפים והעשירים והתקיפים וכל עבד וכל בן חרים התחבאו במערות ובסלעי ההרים׃"));
hebsuperobject.biblemap.put("b66_6_16", new hebsuperobject(66,6,16,"ויאמרו אל ההרים ואל הסלעים נפלו עלינו וכסונו מפני הישב על הכסא ומפני חמת השה׃"));
hebsuperobject.biblemap.put("b66_6_17", new hebsuperobject(66,6,17,"כי בא יום עברתו הגדול ומי יוכל להתיצב׃"));
hebsuperobject.biblemap.put("b66_7_1", new hebsuperobject(66,7,1,"ואחרי כן ראיתי ארבעה מלאכים עמדים בארבע כנפות הארץ ויעצרו את ארבע רוחות הארץ למען לא תשב רוח לא בארץ ולא בים ולא בכל עץ׃"));
hebsuperobject.biblemap.put("b66_7_2", new hebsuperobject(66,7,2,"וארא מלאך אחר עלה ממרח שמש ובידו חתמת אלהים חיים ויקרא בקול גדול אל ארבעה המלאכים אשר נתן להם לחבל הארץ והים לאמר׃"));
hebsuperobject.biblemap.put("b66_7_3", new hebsuperobject(66,7,3,"אל תחבלו את הארץ ואת הים ואת העץ עד אם חתמנו את עבדי אלהינו על מצחותם׃"));
hebsuperobject.biblemap.put("b66_7_4", new hebsuperobject(66,7,4,"ואשמע מספר החתומים מאה אלף וארבעים וארבעה אלף והם חתומים מכל שבטי בני ישראל׃"));
hebsuperobject.biblemap.put("b66_7_5", new hebsuperobject(66,7,5,"לשבט יהודה חתומים שנים עשר אלף לשבט ראובן חתומים שנים עשר אלף לשבט גד חתומים שנים עשר אלף׃"));
hebsuperobject.biblemap.put("b66_7_6", new hebsuperobject(66,7,6,"לשבט אשר חתומים שנים עשר אלף לשבט נפתלי חתומים שנים עשר אלף לשבט מנשה חתומים שנים עשר אלף׃"));
hebsuperobject.biblemap.put("b66_7_7", new hebsuperobject(66,7,7,"לשבט שמעון חתומים שנים עשר אלף לשבט לוי חתומים שנים עשר אלף לשבט יששכר חתומים שנים עשר אלף׃"));
hebsuperobject.biblemap.put("b66_7_8", new hebsuperobject(66,7,8,"לשבט זבלון חתומים שנים עשר אלף לשבט יוסף חתומים שנים עשר אלף לשבט בנימן חתומים שנים עשר אלף׃"));
hebsuperobject.biblemap.put("b66_7_9", new hebsuperobject(66,7,9,"אחרי כן ראיתי והנה המון רב אשר לא יכל איש למנותו מכל הגוים והמשפחות והעמים והלשנות ויעמדו לפני הכסא ולפני השה מלבשים שמלות לבנות וכפות תמרים בידיהם׃"));
hebsuperobject.biblemap.put("b66_7_10", new hebsuperobject(66,7,10,"ויקראו בקול גדול לאמר הישועה לאלהינו הישב על הכסא ולשה׃"));
hebsuperobject.biblemap.put("b66_7_11", new hebsuperobject(66,7,11,"וכל המלאכים עמדו סביב לכסא וסביב לזקנים ולארבע החיות ויפלו על פניהם לפני הכסא וישתחוו לאלהים׃"));
hebsuperobject.biblemap.put("b66_7_12", new hebsuperobject(66,7,12,"ויאמרו אמן הברכה והכבוד והחכמה והתודה וההדר והכח והעז לאלהינו לעולמי עולמים אמן׃"));
hebsuperobject.biblemap.put("b66_7_13", new hebsuperobject(66,7,13,"ויען אחד מן הזקנים ויאמר אלי אלה המלבשים בגדי לבן מי המה ומאין באו׃"));
hebsuperobject.biblemap.put("b66_7_14", new hebsuperobject(66,7,14,"ואמר אליו אדני אתה ידעת ויאמר אלי אלה הם הבאים מן הצרה הגדולה ויכבסו את שמלתם וילבינום בדם השה׃"));
hebsuperobject.biblemap.put("b66_7_15", new hebsuperobject(66,7,15,"לכן הנם לפני כסא האלהים ומשרתים אותו בהיכלו יומם ולילה והישב על הכסא יתן משכנו עליהם׃"));
hebsuperobject.biblemap.put("b66_7_16", new hebsuperobject(66,7,16,"לא ירעבו עוד ולא יצמאו ולא יכם שמש ושרב׃"));
hebsuperobject.biblemap.put("b66_7_17", new hebsuperobject(66,7,17,"כי השה אשר בתוך הכסא הוא ירעם ועל מבועי מים חיים ינהלם ומחה אליהם כל דמעה מעיניהם׃"));
hebsuperobject.biblemap.put("b66_8_1", new hebsuperobject(66,8,1,"וכפתחו החותם השביעי ותהי דממה בשמים כחצי שעה׃"));
hebsuperobject.biblemap.put("b66_8_2", new hebsuperobject(66,8,2,"וארא את שבעת המלאכים אשר עמדו לפני האלהים וינתנו להם שבעה שופרות׃"));
hebsuperobject.biblemap.put("b66_8_3", new hebsuperobject(66,8,3,"ויבא מלאך אחר ויגש אל המזבח ומחתת זהב בידו ותנתן לו קטרת הרבה לתתה עם תפלות כל הקדשים על מזבח הזהב אשר לפני הכסא׃"));
hebsuperobject.biblemap.put("b66_8_4", new hebsuperobject(66,8,4,"ויעל עשן הקטרת עם תפלות הקדשים מיד המלאך לפני אלהים׃"));
hebsuperobject.biblemap.put("b66_8_5", new hebsuperobject(66,8,5,"ויקח המלאך את המחתה וימלאה אש מעל המזבח וישלך על הארץ ויהי קולות ורעמים וברקים ורעש׃"));
hebsuperobject.biblemap.put("b66_8_6", new hebsuperobject(66,8,6,"ושבעה המלאכים ההם אשר בידם שבעת השופרות התעתדו לתקע׃"));
hebsuperobject.biblemap.put("b66_8_7", new hebsuperobject(66,8,7,"והמלאך הראשון תקע בשופר ויהי ברד ואש בלולים בדם ותשלך ארצה ותשרף שלישית העץ וכל ירק עשב נשרף׃"));
hebsuperobject.biblemap.put("b66_8_8", new hebsuperobject(66,8,8,"והמלאך השני תקע בשופר והנה כדמות הר גדול בער באש השלך אל תוך הים ותהי שלישית הים לדם׃"));
hebsuperobject.biblemap.put("b66_8_9", new hebsuperobject(66,8,9,"ותמת שלישית כל נפש חיה אשר בים ושלישית האניות נשחתה׃"));
hebsuperobject.biblemap.put("b66_8_10", new hebsuperobject(66,8,10,"והמלאך השלישי תקע בשופר ויפל מן השמים כוכב גדול בער כלפיד ויפל על שלישית הנהרות ועל מעינות המים׃"));
hebsuperobject.biblemap.put("b66_8_11", new hebsuperobject(66,8,11,"ושם הכוכב נקרא לענה ותהי שלישית המים ללענה ורבים מבני אדם מתו מן המים כי מרים היו׃"));
hebsuperobject.biblemap.put("b66_8_12", new hebsuperobject(66,8,12,"והמלאך הרביעי תקע בשופר ותכה שלישית השמש ושלישית הירח ושלישית הכוכבים למען תחשך שלישיתם והיום לא יאיר שלישיתו וכן גם הלילה׃"));
hebsuperobject.biblemap.put("b66_8_13", new hebsuperobject(66,8,13,"וארא ואשמע מלאך אחד מעופף במרום הרקיע הקורא בקול גדול אוי אוי אוי לישבי הארץ משאר קלות שופר שלשת המלאכים העתידים לתקע׃"));
hebsuperobject.biblemap.put("b66_9_1", new hebsuperobject(66,9,1,"והמלאך החמישי תקע בשופר וארא כוכב נפל מן השמים לארץ וינתן לו מפתח באר התהום׃"));
hebsuperobject.biblemap.put("b66_9_2", new hebsuperobject(66,9,2,"ויפתח את באר התהום ויעל עשן מן הבאר כעשן כבשן גדול ויחשך השמש והרקיע מקיטר הבאר׃"));
hebsuperobject.biblemap.put("b66_9_3", new hebsuperobject(66,9,3,"ומן הקיטר יצא ארבה על הארץ וינתן להם שלטן כשלטן עקרבי הארץ׃"));
hebsuperobject.biblemap.put("b66_9_4", new hebsuperobject(66,9,4,"ויאמר אליהם אשר לא ישחיתו את עשב הארץ ולא כל ירק ולא כל עץ כי אם את בני האדם אשר אין להם חותם אלהים במצחותם׃"));
hebsuperobject.biblemap.put("b66_9_5", new hebsuperobject(66,9,5,"ולא נתן להם להמיתם רק להכאיבם חמשה חדשים וכאבם ככאב איש אשר יכהו העקרב׃"));
hebsuperobject.biblemap.put("b66_9_6", new hebsuperobject(66,9,6,"ובימים ההם יבקשו בני אדם את המות ולא ימצאהו וישאלו את נפשם למות והמות יברח מהם׃"));
hebsuperobject.biblemap.put("b66_9_7", new hebsuperobject(66,9,7,"ויהי מראה הארבה כדמות סוסים ערוכי מלחמה ועל ראשיהם כעטרות כעין זהב ופניהם כפני אדם׃"));
hebsuperobject.biblemap.put("b66_9_8", new hebsuperobject(66,9,8,"ושער להם כשער נשים ושניהם שני אריה׃"));
hebsuperobject.biblemap.put("b66_9_9", new hebsuperobject(66,9,9,"ושרינים להם כשריני ברזל וקול כנפיהם כקול מרכבות סוסים רבים הרצים למלחמה׃"));
hebsuperobject.biblemap.put("b66_9_10", new hebsuperobject(66,9,10,"וזנבות להם כזנבות עקרבים ועקצים בזנבותם והשלטו לענות את בני האדם חמשה חדשים׃"));
hebsuperobject.biblemap.put("b66_9_11", new hebsuperobject(66,9,11,"ומלאך התהום הוא מלך עליהם ושמו אבדון בעברית והוא אפוליון בלשון יון׃"));
hebsuperobject.biblemap.put("b66_9_12", new hebsuperobject(66,9,12,"הצרה האחת חלפה הלכה לה והנה באות אחריה עוד צרות שתים׃"));
hebsuperobject.biblemap.put("b66_9_13", new hebsuperobject(66,9,13,"והמלאך הששי תקע בשופר ואשמע קול אחד מארבע קרנות מזבח הזהב אשר לפני אלהים׃"));
hebsuperobject.biblemap.put("b66_9_14", new hebsuperobject(66,9,14,"ויאמר למלאך הששי אשר השופר בידו התר את ארבעה המלאכים ההם האסורים על הנהר הגדול נהר פרת׃"));
hebsuperobject.biblemap.put("b66_9_15", new hebsuperobject(66,9,15,"ויתרו ארבעה המלאכים אשר היו נכונים לשעה וליום ולחדש ולשנה להמית שלישית בני האדם׃"));
hebsuperobject.biblemap.put("b66_9_16", new hebsuperobject(66,9,16,"ויהי מספר צבאות הפרשים שתי רבוא רבבות ואני שמעתי מספרם׃"));
hebsuperobject.biblemap.put("b66_9_17", new hebsuperobject(66,9,17,"וכן ראיתי במראה את הסוסים ורכביהם אשר שרינותיהם כעין אש ותכלת וגפרית וראשי הסוסים כראשי אריות ותצא מפיהם אש וקיטור וגפרית׃"));
hebsuperobject.biblemap.put("b66_9_18", new hebsuperobject(66,9,18,"ותומת שלישית בני אדם בשלש האלה באש ובקיטור ובגפרית היצאות מפיהם׃"));
hebsuperobject.biblemap.put("b66_9_19", new hebsuperobject(66,9,19,"כי כח הסוסים בפיהם כי זנבותם דומים לנחשים ויש להם ראשים ובהם ישחיתו׃"));
hebsuperobject.biblemap.put("b66_9_20", new hebsuperobject(66,9,20,"ושאר בני אדם אשר לא נהרגו במגפות האלה בכל זאת לא שבו ממעשי ידיהם מהשתחות עוד לשדים ולעצבי זהב וכסף ונחשת ואבן ועץ אשר לא יראו ולא ישמעו ולא יהלכו׃"));
hebsuperobject.biblemap.put("b66_9_21", new hebsuperobject(66,9,21,"ולא שבו מדרכם לרצח ולכשף ולזנות ולגנב׃"));
hebsuperobject.biblemap.put("b66_10_1", new hebsuperobject(66,10,1,"וארא מלאך אחר אביר יורד מן השמים והוא עטה ענן ועל ראשו כמראה קשת הענן ופניו כשמש ורגליו כעמודי אש׃"));
hebsuperobject.biblemap.put("b66_10_2", new hebsuperobject(66,10,2,"ובידו ספר קטן פתוח וישם את רגל ימינו על הים ואת שמאלו על הארץ׃"));
hebsuperobject.biblemap.put("b66_10_3", new hebsuperobject(66,10,3,"ויקרא בקול גדול כאשר ישאג האריה ובקראו דברו שבעת הרעמים בקולתיהם׃"));
hebsuperobject.biblemap.put("b66_10_4", new hebsuperobject(66,10,4,"וכדבר שבעת הרעמים בקולתיהם חפצתי לכתב ואשמע קול מן השמים לאמר חתום את אשר דברו שבעת הרעמים ואל תכתב זאת׃"));
hebsuperobject.biblemap.put("b66_10_5", new hebsuperobject(66,10,5,"והמלאך אשר ראיתיו עמד על הים ועל הארץ הרים ידו אל השמים׃"));
hebsuperobject.biblemap.put("b66_10_6", new hebsuperobject(66,10,6,"וישבע בחי עולמי העולמים אשר ברא את השמים וכל אשר בהם והארץ וכל אשר בה והים וכל אשר בו כי לא יהיה עוד זמן׃"));
hebsuperobject.biblemap.put("b66_10_7", new hebsuperobject(66,10,7,"אך בימי קול המלאך השביעי בעת עמדו לתקוע ונשלם סוד האלהים כאשר בשר את עבדיו הנביאים׃"));
hebsuperobject.biblemap.put("b66_10_8", new hebsuperobject(66,10,8,"והקול אשר שמעתי מן השמים שב לדבר אלי לאמר לך וקח את הספר הקטן הפתוח אשר ביד המלאך העמד על הים ועל הארץ׃"));
hebsuperobject.biblemap.put("b66_10_9", new hebsuperobject(66,10,9,"ואבא אל המלאך ואמר לו תנה לי את הספר ויאמר אלי קח ואכל אתו וימר לבטנך אבל בפיך יהיה מתוק כדבש׃"));
hebsuperobject.biblemap.put("b66_10_10", new hebsuperobject(66,10,10,"ואקח את הספר מיד המלאך ואכלהו ויהי בפי כדבש למתוק ואחרי אכלי אתו וימלא בטני מרורים׃"));
hebsuperobject.biblemap.put("b66_10_11", new hebsuperobject(66,10,11,"ויאמר אלי עליך לשוב להנבא עוד על עמים וגוים ולשנות ומלכים רבים׃"));
hebsuperobject.biblemap.put("b66_11_1", new hebsuperobject(66,11,1,"וינתן לי קנה דומה למטה ויעמד המלאך ויאמר קום ומד את היכל יהוה ואת המזבח ואת המשתחוים בו׃"));
hebsuperobject.biblemap.put("b66_11_2", new hebsuperobject(66,11,2,"ואת החצר אשר לפנימה להיכל השלך חוצה ואל תמדנה כי נתנה לגוים ורמסו את העיר הקדשה ארבעים ושנים חדשים׃"));
hebsuperobject.biblemap.put("b66_11_3", new hebsuperobject(66,11,3,"ואתן לשני עדי ונבאו ימים אלף ומאתים וששים מתכסים בשקים׃"));
hebsuperobject.biblemap.put("b66_11_4", new hebsuperobject(66,11,4,"אלה הם שני הזיתים ושתי המנרות העמדים לפני אלהי הארץ׃"));
hebsuperobject.biblemap.put("b66_11_5", new hebsuperobject(66,11,5,"וכי יבקש איש להרע להם תצא אש מפיהם ואכלה את איביהם וכן כל המבקש להרע להם מות יומת׃"));
hebsuperobject.biblemap.put("b66_11_6", new hebsuperobject(66,11,6,"ולהם השלטן לעצר את השמים ולא יהיה מטר בימי נבואתם וישלטו על המים להפכם לדם ועל הארץ להכתה בכל נגע מדי יחפצו׃"));
hebsuperobject.biblemap.put("b66_11_7", new hebsuperobject(66,11,7,"ואחרי השלימם עדותם החיה העלה מן התהום תעשה עמהם מלחמה ותוכל להם והרגתם׃"));
hebsuperobject.biblemap.put("b66_11_8", new hebsuperobject(66,11,8,"והיתה נבלתם ברהוב העיר הגדולה הנקראת כפי הרוח בשם סדום ומצרים אשר שם נצלב גם אדנינו׃"));
hebsuperobject.biblemap.put("b66_11_9", new hebsuperobject(66,11,9,"ורבים מן העמים והמשפחות והלשנות והגוים יראו את נבלתם ימים שלשה וחצי ולא יתנו את גויתם לשום בקברים׃"));
hebsuperobject.biblemap.put("b66_11_10", new hebsuperobject(66,11,10,"וישבי הארץ ישמחו עליהם ויעלזו וישלחו מנות זה לזה כי שני הנביאים האלה הכאיבו את ישבי הארץ׃"));
hebsuperobject.biblemap.put("b66_11_11", new hebsuperobject(66,11,11,"ויהי אחרי ימים שלשה וחצי ותבא בהם רוח חיים מאת האלהים ויעמדו על רגליהם ואימה גדולה נפלה על כל ראיהם׃"));
hebsuperobject.biblemap.put("b66_11_12", new hebsuperobject(66,11,12,"וישמעו קול גדול מן השמים מדבר אליהם לאמר עלו הנה ויעלו בענן השמימה ושנאיהם ראים אתם׃"));
hebsuperobject.biblemap.put("b66_11_13", new hebsuperobject(66,11,13,"ובשעה ההיא היה רעש גדול ותפל עשירית העיר ושבעת אלפים שמות בני אדם נהרגו ברעש והנשארים רעדה אחזתם ויתנו כבוד לאלהי השמים׃"));
hebsuperobject.biblemap.put("b66_11_14", new hebsuperobject(66,11,14,"הצרה השנית חלפה הלכה לה והנה הצרה השלישית מהרה תבוא׃"));
hebsuperobject.biblemap.put("b66_11_15", new hebsuperobject(66,11,15,"והמלאך השביעי תקע בשופר ויהי קלות גדולים בשמים ויאמרו הנה ממלכת העולם היתה לאדיניו ולמשיחו והוא ימלך לעולמי עולמים׃"));
hebsuperobject.biblemap.put("b66_11_16", new hebsuperobject(66,11,16,"ועשרים וארבעה הזקנים הישבים לפני האלהים על כסאותם נפלו על פניהם וישתחוו לאלהים׃"));
hebsuperobject.biblemap.put("b66_11_17", new hebsuperobject(66,11,17,"ויאמרו מודים אנחנו לך יהוה אלהים צבאות ההוה והיה ויבוא כי לבשת עזך הגדול ותמלך׃"));
hebsuperobject.biblemap.put("b66_11_18", new hebsuperobject(66,11,18,"והגוים קצפו ויבא קצפך ועת המתים להשפט ולתת שכר לעבדיך הנביאים ולקדשים וליראי שמך למקטנם ועד גדולם ולהשחית את משחיתי הארץ׃"));
hebsuperobject.biblemap.put("b66_11_19", new hebsuperobject(66,11,19,"ויפתח היכל יהוה בשמים וירא ארון בריתו בהיכל ויהי ברקים וקלות ורעמים ורעש וברד כבד׃"));
hebsuperobject.biblemap.put("b66_12_1", new hebsuperobject(66,12,1,"ואות גדולה נראתה בשמים אשה אשר השמש לבושה והירח תחת רגליה ועל ראשה עטרת שנים עשר כוכבים׃"));
hebsuperobject.biblemap.put("b66_12_2", new hebsuperobject(66,12,2,"והיא הרה ותזעק בחבליה ותקש בלדתה׃"));
hebsuperobject.biblemap.put("b66_12_3", new hebsuperobject(66,12,3,"ותרא אות אחרת בשמים והנה תנין גדול אדם כאש ולו שבעה ראשים ועשר קרנים ועל ראשיו שבעה כתרים׃"));
hebsuperobject.biblemap.put("b66_12_4", new hebsuperobject(66,12,4,"וזנבו סחב מן השמים שלישית הכוכבים וישליכם ארצה ויתיצב התנין לפני האשה החלה ללדת למען בלע את בנה בלדתה׃"));
hebsuperobject.biblemap.put("b66_12_5", new hebsuperobject(66,12,5,"ותלד בן זכר העתיד לרעות כל הגוים בשבט ברזל וילקח בנה אל האלהים ואל כסאו׃"));
hebsuperobject.biblemap.put("b66_12_6", new hebsuperobject(66,12,6,"והאשה ברחה המדברה אשר שם הוכן לה מקום מאת אלהים למען יכלכלוה שם ימים אלף ומאתים וששים׃"));
hebsuperobject.biblemap.put("b66_12_7", new hebsuperobject(66,12,7,"ותהי מלחמה בשמים מיכאל ומלאכיו נלחמים בתנין והתנין נלחם ומלאכיו׃"));
hebsuperobject.biblemap.put("b66_12_8", new hebsuperobject(66,12,8,"ולא התחזקו וגם מקומם לא נמצא עוד בשמים׃"));
hebsuperobject.biblemap.put("b66_12_9", new hebsuperobject(66,12,9,"ויוטל התנין הגדול הנחש הקדמוני אשר נקרא שמו מלשין ושטן המדיח תבל כלה הוא הוטל ארצה ומלאכיו עמו הוטלו׃"));
hebsuperobject.biblemap.put("b66_12_10", new hebsuperobject(66,12,10,"ואשמע קול גדול בשמים ויאמר עתה באה ישועת אלהינו ועזו ומלכותו וממשלת משיחו כי הורד שוטן אחינו העמד לשטנם לפני אלהינו יומם ולילה׃"));
hebsuperobject.biblemap.put("b66_12_11", new hebsuperobject(66,12,11,"והם נצחהו למען דם השה ולמען דבר עדותם ולא אהבו את נפשם עד למות׃"));
hebsuperobject.biblemap.put("b66_12_12", new hebsuperobject(66,12,12,"רנו על זאת שמים ושכניהם אוי לישבי ארץ וים כי ירד אליכם המלשין בחמה גדולה מדעתו כי קצרה עתו׃"));
hebsuperobject.biblemap.put("b66_12_13", new hebsuperobject(66,12,13,"ויהי כאשר ראה התנין כי הוטל ארצה וירדף את האשה אשר ילדה את הזכר׃"));
hebsuperobject.biblemap.put("b66_12_14", new hebsuperobject(66,12,14,"ויתנו לאשה שתי כנפי הנשר הגדול לעוף המדברה אל מקומה אשר תכלכל שם מועד מועדים וחצי מפני הנחש׃"));
hebsuperobject.biblemap.put("b66_12_15", new hebsuperobject(66,12,15,"וישלח הנחש נהר מים מפיו אחרי האשה לשטפה בנהר׃"));
hebsuperobject.biblemap.put("b66_12_16", new hebsuperobject(66,12,16,"ותעזר הארץ את האשה ותפתח הארץ את פיה ותבלע את הנהר אשר שלח התנין מפיהו׃"));
hebsuperobject.biblemap.put("b66_12_17", new hebsuperobject(66,12,17,"ויקצף התנין על האשה וילך לעשות מלחמה עם יתר זרעה השמרים פקודי אלהים ואשר להם עדות ישוע׃"));
hebsuperobject.biblemap.put("b66_13_1", new hebsuperobject(66,13,1,"ואהי עמד על חול הים וארא חיה עלה מן הים ולה שבעה ראשים ועשר קרנים ועל קרניה עשרה כתרים ועל ראשיה שם גדופים׃"));
hebsuperobject.biblemap.put("b66_13_2", new hebsuperobject(66,13,2,"והחיה אשר ראיתי מראה כנמר ורגליה כרגלי דב ופיה כפי אריה ויתן לה התנין את כחו ואת כסאו וממשל רב׃"));
hebsuperobject.biblemap.put("b66_13_3", new hebsuperobject(66,13,3,"וארא והנה אחד מראשיה כפצוע עד מות ומכת מות אשר לו נרפאה ותשתומם כל הארץ אחרי החיה׃"));
hebsuperobject.biblemap.put("b66_13_4", new hebsuperobject(66,13,4,"וישתחוו לתנין אשר נתן ממשלה לחיה וישתחוו לחיה ויאמרו מי ידמה לחיה ומי יוכל להלחם אתה׃"));
hebsuperobject.biblemap.put("b66_13_5", new hebsuperobject(66,13,5,"וינתן לה פה ממלל גדלות ונאצות ושלטן נתן לה להלחם ארבעים ושנים חדשים׃"));
hebsuperobject.biblemap.put("b66_13_6", new hebsuperobject(66,13,6,"ותפתח את פיה לנאצה אל האלהים ותנאץ את שמו ואת משכנו ואת החנים בשמים׃"));
hebsuperobject.biblemap.put("b66_13_7", new hebsuperobject(66,13,7,"וינתן לה לעשות מלחמה עם הקדשים ולנצחם ותנתן לה ממשלה על כל משפחה ועם ולשון וגוי׃"));
hebsuperobject.biblemap.put("b66_13_8", new hebsuperobject(66,13,8,"וישתחוו לה כל ישבי הארץ אשר לא נכתבו שמותם בספר החיים אשר לשה הטבוח מיום הוסד תבל׃"));
hebsuperobject.biblemap.put("b66_13_9", new hebsuperobject(66,13,9,"כל אשר אזן לו ישמע׃"));
hebsuperobject.biblemap.put("b66_13_10", new hebsuperobject(66,13,10,"כל המוליך לשבי ילך בשבי וכל ההרג בחרב הרג יהרג בחרב בזה סבלנות ואמונת הקדשים׃"));
hebsuperobject.biblemap.put("b66_13_11", new hebsuperobject(66,13,11,"וארא חיה אחרת עלה מן האדמה ולה קרנים כקרני שה ומדברת כתנין׃"));
hebsuperobject.biblemap.put("b66_13_12", new hebsuperobject(66,13,12,"והיא עשה כל פקודי החיה הראשונה בפניה ומביאה את הארץ וישביה להשתחות לחיה הראשונה אשר נרפאה מכת מות אשר לה׃"));
hebsuperobject.biblemap.put("b66_13_13", new hebsuperobject(66,13,13,"ונתנת אותות גדלות וגם אש מן השמים תוריד ארצה לעיני בני אדם׃"));
hebsuperobject.biblemap.put("b66_13_14", new hebsuperobject(66,13,14,"ותתעה את ישבי הארץ על ידי האותות אשר נתן לה לעשות בפני החיה באמרה אל ישבי הארץ לעשות צלם לחיה אשר הכתה מכת חרב ותחי׃"));
hebsuperobject.biblemap.put("b66_13_15", new hebsuperobject(66,13,15,"וינתן לה לתת רוח בצלם החיה למען דבר ידבר צלם החיה ועשתה כי כל אשר אימן משתחוים לצלם החיה מות יומתו׃"));
hebsuperobject.biblemap.put("b66_13_16", new hebsuperobject(66,13,16,"ותעש כי כלם למקטן ועד גדול אם אביון ואם עשיר גם בני החרים גם העבדים יתוו תו על די ימינם או על מצחתם׃"));
hebsuperobject.biblemap.put("b66_13_17", new hebsuperobject(66,13,17,"וכי לא יוכל איש לקנות או למכר כי אם בהיות עליו תו החיה או שמה או מספר שמה׃"));
hebsuperobject.biblemap.put("b66_13_18", new hebsuperobject(66,13,18,"בזה החכמה מי אשר לו תבונה יחשב מספר החיה כי מספר בן אדם הוא ומספרו שש מאות וששים ושש׃"));
hebsuperobject.biblemap.put("b66_14_1", new hebsuperobject(66,14,1,"וארא והנה שה עמד על הר ציון ועמו מאת אלף וארבעים וארבעה אלפים הנשאים שם אביו כתוב על מצחותם׃"));
hebsuperobject.biblemap.put("b66_14_2", new hebsuperobject(66,14,2,"ואשמע קול מן השמים כקול מים רבים וכקול רעם גדול ואשמע קול תפשי כנור המנגנים בכנורותיהם׃"));
hebsuperobject.biblemap.put("b66_14_3", new hebsuperobject(66,14,3,"וישירו כשיר חדש לפני הכסא ולפני ארבע החיות ולפני הזקנים ואין איש אשר יכל ללמד את השיר זולתי מאת האלף וארבעים וארבעת האלפים ההם אשר נקנו מן הארץ׃"));
hebsuperobject.biblemap.put("b66_14_4", new hebsuperobject(66,14,4,"אלה הם אשר לא נגאלו בנשים כי בתולות המה אלה הם ההלכים אחרי השה אל כל אשר ילך אלה נקנו מתוך בני האדם לראשית בכורים לאלהים ולשה׃"));
hebsuperobject.biblemap.put("b66_14_5", new hebsuperobject(66,14,5,"ותרמית לא נמצאה בפיהם כי תמימים המה לפני כסא האלהים׃"));
hebsuperobject.biblemap.put("b66_14_6", new hebsuperobject(66,14,6,"וארא מלאך אחר מעופף במרום הרקיע אשר היה לו בשורת עולם לבשר את ישבי הארץ ואת כל גוי ונשפחה ולשון ועם׃"));
hebsuperobject.biblemap.put("b66_14_7", new hebsuperobject(66,14,7,"ויאמר בקול גדול יראו את האלהים והבו לו כבוד כי באה עת משפטו והשתחוו לעשה שמים וארץ את הים ומעינות המים׃"));
hebsuperobject.biblemap.put("b66_14_8", new hebsuperobject(66,14,8,"ומלאך אחר בא אחריו ויאמר נפלה נפלה בבל העיר הגדולה כי השקתה כל הגוים מיין חמת תזנתה׃"));
hebsuperobject.biblemap.put("b66_14_9", new hebsuperobject(66,14,9,"ומלאך שלישי בא אחריהם ויאמר בקול גדול כל אשר ישתחוה לפני החיה ולפני צלמה ונשא את תוה על מצחו או על ידו׃"));
hebsuperobject.biblemap.put("b66_14_10", new hebsuperobject(66,14,10,"גם הוא שתה ישתה מיין חמת אלהים יין בלתי מהול הנמסך בכוס זעמו ויענה באש וגפרית לפני המלאכים הקדשים ולפני השה׃"));
hebsuperobject.biblemap.put("b66_14_11", new hebsuperobject(66,14,11,"ועשן ענוים יעלה לעולמי עד ולא ימצאו מנוחה יומם ולילה המשתחוים לחיה ולצלמה ואשר ישא את תו שמה׃"));
hebsuperobject.biblemap.put("b66_14_12", new hebsuperobject(66,14,12,"בזה סבלנות הקדשים בזה השמרים את מצות האלהים ואת אמונת ישוע׃"));
hebsuperobject.biblemap.put("b66_14_13", new hebsuperobject(66,14,13,"ואשמע קול מן השמים מדבר אלי כתב אשרי המתים אשר ימותו באדון מעתה אמנם כן אמר הרוח למען ינוחו מעמלם ומעשיהם הלך ילכו אחריהם׃"));
hebsuperobject.biblemap.put("b66_14_14", new hebsuperobject(66,14,14,"וארא והנה ענן בהיר ועל הענן ישב כדמות בן אדם ועל ראשו עטרת זהב ובידו מגל מלטש׃"));
hebsuperobject.biblemap.put("b66_14_15", new hebsuperobject(66,14,15,"ומלאך אחר יצא מן ההיכל ויזעק בקול גדול אל הישב על הענן לאמר שלח מגלך וקצר כי באה העת לקצר כי יבש קציר הארץ׃"));
hebsuperobject.biblemap.put("b66_14_16", new hebsuperobject(66,14,16,"וישלח הישב בענן את מגלו בארץ והארץ נקצרה׃"));
hebsuperobject.biblemap.put("b66_14_17", new hebsuperobject(66,14,17,"ומלאך אחר יצא מן ההיכל אשר בשמים וגם לו מגל מלטש בידו׃"));
hebsuperobject.biblemap.put("b66_14_18", new hebsuperobject(66,14,18,"ויצא מלאך אחר מן המזבח וממשלתו על האש ויקרא קול גדול אל אשר בידו המגל המלטש לאמר שלח מגלך המלטש ובצר את גפן הארץ כי בשלו ענביהם׃"));
hebsuperobject.biblemap.put("b66_14_19", new hebsuperobject(66,14,19,"וינף המלאך את מגלו על הארץ ויבצר את אשכלת גפן הארץ וישליכם בגת חמת אלהים הגדולה׃"));
hebsuperobject.biblemap.put("b66_14_20", new hebsuperobject(66,14,20,"ותדרך הגת מחוץ לעיר ויצא דם מן הגת עד רסני הסוסים דרך אלף ושש מאות ריס׃"));
hebsuperobject.biblemap.put("b66_15_1", new hebsuperobject(66,15,1,"וארא אות אחרת בשמים גדולה ונפלאה שבעה מלאכים הנשאים את שבע המכות האחרנות כי בהן כלה זעם אלהים׃"));
hebsuperobject.biblemap.put("b66_15_2", new hebsuperobject(66,15,2,"וארא כים זכוכית בלול באש ואת המתגברים על החיה ועל צלמה ועל תוה ועל מספר שמה עמדים על ים הזכוכית וכנרות אלהים בידיהם׃"));
hebsuperobject.biblemap.put("b66_15_3", new hebsuperobject(66,15,3,"וישירו את שירת משה עבד אלהים ושירת השה לאמר גדולים מעשיך ונפלאים יהוה אלהים צבאות צדק ואמת דרכיך מלך הגוים׃"));
hebsuperobject.biblemap.put("b66_15_4", new hebsuperobject(66,15,4,"מי לא ייראך יהוה ולא יכבד את שמך כי קדוש אתה לבדך כי כל הגוים יבאו וישתחוו לפניך כי נגלו משפטי צדקך׃"));
hebsuperobject.biblemap.put("b66_15_5", new hebsuperobject(66,15,5,"ואחרי כן ראיתי והנה נפתח היכל משכן העדות בשמים׃"));
hebsuperobject.biblemap.put("b66_15_6", new hebsuperobject(66,15,6,"ויצאו מן ההיכל שבעה המלאכים הנשאים את שבע המכות מלבשים בד טהור וצח וחגורים אזורי זהב על לבביהם׃"));
hebsuperobject.biblemap.put("b66_15_7", new hebsuperobject(66,15,7,"ואחת מארבע החיות נתנה אל שבעת המלאכים שבע קערת זהב מלאות חמת האלהים החי לעולמי העולמים׃"));
hebsuperobject.biblemap.put("b66_15_8", new hebsuperobject(66,15,8,"וימלא ההיכל עשן מכבוד אלהים ועזו ולא יכל איש לבוא אל ההיכל עד אשר כלו שבע המכות אשר בידי שבעה המלאכים׃"));
hebsuperobject.biblemap.put("b66_16_1", new hebsuperobject(66,16,1,"ואשמע קול גדול מן ההיכל האמר אל שבעת המלאכים לכו ושפכו את קערת חמת האלהים ארצה׃"));
hebsuperobject.biblemap.put("b66_16_2", new hebsuperobject(66,16,2,"וילך הראשון וישפך את קערתו על הארץ ויהי שהין רע ומכאיב באנשים אשר עליהם תו החיה ובמשתחוים לצלמה׃"));
hebsuperobject.biblemap.put("b66_16_3", new hebsuperobject(66,16,3,"וישפך השני את קערתו על הים ויהי לדם כדם חלל ותמת כל נפש חיה אשר בים׃"));
hebsuperobject.biblemap.put("b66_16_4", new hebsuperobject(66,16,4,"וישפך השלישי את קערתו בנהרות ובמעינות המים ויהיו לדם׃"));
hebsuperobject.biblemap.put("b66_16_5", new hebsuperobject(66,16,5,"ואשמע את מלאך המים אמר צדיק אתה ההוה והיה והקדוש כי כן שפטת׃"));
hebsuperobject.biblemap.put("b66_16_6", new hebsuperobject(66,16,6,"כי דם קדשים ונביאים שפכו ודם השקיתם כי גמול ידם הוא׃"));
hebsuperobject.biblemap.put("b66_16_7", new hebsuperobject(66,16,7,"ואשמע את המזבח אמר אמנם כן יהוה אלהים צבאות אמת וצדק משפטיך׃"));
hebsuperobject.biblemap.put("b66_16_8", new hebsuperobject(66,16,8,"וישפך המלאך הרביעי את קערתו על השמש וינתן לו לצרב את בני אדם באש׃"));
hebsuperobject.biblemap.put("b66_16_9", new hebsuperobject(66,16,9,"ויצרבו בני אדם בחם גדול ויגדפו את שם אלהים אשר לו הממשלה על המכות האלה ולא שבו לתת לו הכבוד׃"));
hebsuperobject.biblemap.put("b66_16_10", new hebsuperobject(66,16,10,"וישפך החמישי את קערתו על כסא החיה ותחשך מלכותה וינשכו מכאב לב את לשונם׃"));
hebsuperobject.biblemap.put("b66_16_11", new hebsuperobject(66,16,11,"ויגדפו את אלהי השמים ממכאבם ושחינם ולא שבו ממעשיהם׃"));
hebsuperobject.biblemap.put("b66_16_12", new hebsuperobject(66,16,12,"וישפך הששי את קערתו על הנהר הגדול נהר פרת ויחרבו מימיו למען תישר מסלה למלכים אשר ממזרח שמש׃"));
hebsuperobject.biblemap.put("b66_16_13", new hebsuperobject(66,16,13,"וארא והנה מפי התנין ומפי החיה ומפי נביא השקר יצאות שלש רוחות טמאות דומת לצפרדעים׃"));
hebsuperobject.biblemap.put("b66_16_14", new hebsuperobject(66,16,14,"כי רוחות השדים הנה עשות אותות ויצאות אל מלכי ארץ ותבל כלה לאספם למלחמה היום ההוא הגדול יום אלהי הצבאות׃"));
hebsuperobject.biblemap.put("b66_16_15", new hebsuperobject(66,16,15,"הנני בא כגנב אשרי השקד ושמר את בגדיו למען לא ילך ערם וראו את ערותו׃"));
hebsuperobject.biblemap.put("b66_16_16", new hebsuperobject(66,16,16,"ויאסף אתם אל המקום הנקרא בעברית הר מגדון׃"));
hebsuperobject.biblemap.put("b66_16_17", new hebsuperobject(66,16,17,"וישפך המלאך השביעי את קערתו על האור ויצא קול גדול מהיכל השמים מן הכסא ויאמר היה נהיתה׃"));
hebsuperobject.biblemap.put("b66_16_18", new hebsuperobject(66,16,18,"ויהיו קלות ורעמים וברקים ויהי רעש גדול אשר לא היה כמהו למן היות אדם על הארץ רעש כזה גדול עד מאד׃"));
hebsuperobject.biblemap.put("b66_16_19", new hebsuperobject(66,16,19,"והעיר הגדולה נחלקה לשלשה חלקים ותפלנה ערי הגוים ותזכר בבל הגדולה לפני אלהים לתת לה כוס יין חמת אפו׃"));
hebsuperobject.biblemap.put("b66_16_20", new hebsuperobject(66,16,20,"וינס כל אי וההרים לא נמצאו׃"));
hebsuperobject.biblemap.put("b66_16_21", new hebsuperobject(66,16,21,"וברד כבד כככר ירד מן השמים על בני האדם ויגדפו בני האדם את האלהים על אדות מכת הברד כי כבדה מכתו מאד׃"));
hebsuperobject.biblemap.put("b66_17_1", new hebsuperobject(66,17,1,"ויבא אחד מן שבעה המלאכים הנשאים שבע הקערות וידבר אלי לאמר בא ואראך את משפט הזונה הגדולה הישבת על מים רבים׃"));
hebsuperobject.biblemap.put("b66_17_2", new hebsuperobject(66,17,2,"אשר זנו אתה מלכי האדמה וישכרו שכני תבל מיין תזנותה׃"));
hebsuperobject.biblemap.put("b66_17_3", new hebsuperobject(66,17,3,"ויוליכני ברוח המדברה וארא והנה אשה ישבת על חיה אדמה כתולע מלאת שמות גדופים ולה שבעה ראשים ועשר קרנים׃"));
hebsuperobject.biblemap.put("b66_17_4", new hebsuperobject(66,17,4,"והאשה לבושה ארגמן ושני והיא מכללה בזהב ואבן יקרה ופנינים ובידה כוס זהב מלאה תועבות וטמאת תזנותה׃"));
hebsuperobject.biblemap.put("b66_17_5", new hebsuperobject(66,17,5,"ועל מצחה כתוב שם סוד בבל הגדולה אם הזנות ותועבות האדמה׃"));
hebsuperobject.biblemap.put("b66_17_6", new hebsuperobject(66,17,6,"וארא את האשה שכורה מדם הקדשים ומדם עדי ישוע ואשתומם על המראה שמה גדולה׃"));
hebsuperobject.biblemap.put("b66_17_7", new hebsuperobject(66,17,7,"ויאמר אלי המלאך למה זה השתוממת אני אמר לך את סוד האשה והחיה הנשאת אתה בעלת שבעת הראשים ועשרת הקרנים׃"));
hebsuperobject.biblemap.put("b66_17_8", new hebsuperobject(66,17,8,"החיה אשר ראיתה היתה ואיננה ועתידה לעלות מן התהום וללכת לאבדון וישבי הארץ אשר שמם איננו נכתב בספר החיים מיום הוסד תבל ישתוממו בראתם את החיה אשר היתה ואיננה ותבוא׃"));
hebsuperobject.biblemap.put("b66_17_9", new hebsuperobject(66,17,9,"בזה להבין לאשר לו חכמה שבעת הראשים שבעת הרים המה אשר האשה ישבת עליהם׃"));
hebsuperobject.biblemap.put("b66_17_10", new hebsuperobject(66,17,10,"ושבעה מלכים המה חמשה מהם נפלו והאחד ישנו והאחר עוד לא בא והיה כי יבוא עמד יעמד לעת מעט׃"));
hebsuperobject.biblemap.put("b66_17_11", new hebsuperobject(66,17,11,"והחיה אשר היתה ואיננה הוא השמיני והוא מן השבעה וילך לאבדון׃"));
hebsuperobject.biblemap.put("b66_17_12", new hebsuperobject(66,17,12,"ועשר הקרנים אשר ראית עשרה מלכים הם אשר לא קבלו מלכות עד הנה רק לשעה אחת ממשלה כמלכים יקבלו עם החיה׃"));
hebsuperobject.biblemap.put("b66_17_13", new hebsuperobject(66,17,13,"ולאלה עצה אחת ואת כחם ואת ממשלתם יתנו לחיה׃"));
hebsuperobject.biblemap.put("b66_17_14", new hebsuperobject(66,17,14,"המה ילחמו בשה והשה יכול יוכל להם כי הוא אדני האדנים ומלך המלכים ועמו הקרואים והבחירים והנאמנים׃"));
hebsuperobject.biblemap.put("b66_17_15", new hebsuperobject(66,17,15,"ויאמר אלי המים ההם אשר ראית אשר הזונה ישבת עליהם עמים והמנים המה וגוים ולשנות׃"));
hebsuperobject.biblemap.put("b66_17_16", new hebsuperobject(66,17,16,"ועשר הקרנים אשר ראית והחיה המה ישנאו את הזונה ועשוה גלמודה וערמה ואכלו את בשרה ואתה ישרפו באש׃"));
hebsuperobject.biblemap.put("b66_17_17", new hebsuperobject(66,17,17,"כי האלהים נתן בלבם לעשות את עצתו ולעשות עצה אחת ולתת את ממשלתם לחיה עד כי ישלמו דברי האלהים׃"));
hebsuperobject.biblemap.put("b66_17_18", new hebsuperobject(66,17,18,"והאשה אשר ראית היא העיר הגדולה אשר היא נברת ממלכות הארץ׃"));
hebsuperobject.biblemap.put("b66_18_1", new hebsuperobject(66,18,1,"אחרי כן ראיתי מלאך אחר יורד מן השמים אשר לו שלטן גדול והארץ האירה מכבדו׃"));
hebsuperobject.biblemap.put("b66_18_2", new hebsuperobject(66,18,2,"ויקרא בקול עז לאמר נפלה נפלה בבל הגדולה ותהי נוה שערים ומשמר לכל רוח טמא ומשמר לכל עוף טמא ונמאס׃"));
hebsuperobject.biblemap.put("b66_18_3", new hebsuperobject(66,18,3,"כי מיין חמת זנותה שתו כל הגוים ומלכי ארץ זנו עמה וסחרי ארץ משפעת תענגיה העשירו׃"));
hebsuperobject.biblemap.put("b66_18_4", new hebsuperobject(66,18,4,"ואשמע קול אחר מן השמים האמר צאו ממנה עמי פן תתחברו אל חטאתיה ופן תקחו ממכותיה׃"));
hebsuperobject.biblemap.put("b66_18_5", new hebsuperobject(66,18,5,"כי חטאתיה הגיעו עד לשמים ויזכר אלהים את עונותיה׃"));
hebsuperobject.biblemap.put("b66_18_6", new hebsuperobject(66,18,6,"שלמו לה גמולה שגמלה לכם ועשו לה כפלים כפעלה בכוס אשר מסכה מסכו לה כפלים׃"));
hebsuperobject.biblemap.put("b66_18_7", new hebsuperobject(66,18,7,"כאשר התרוממה והתענגה כן תנו לה חבל ואבל כי אמרה התרוממה והתענגה כן תנו לה חבל ואבל כי אמרה בלבבה אני ישבתי מלכה ולא אהיה אלמנה ואבל לא אראה׃"));
hebsuperobject.biblemap.put("b66_18_8", new hebsuperobject(66,18,8,"על כן רגע ביום אחד תבאנה מכותיה מות ואבל ורעב ותשרף במו אש כי חזק יהוה אלהים השפט אתה׃"));
hebsuperobject.biblemap.put("b66_18_9", new hebsuperobject(66,18,9,"ויבכו ויספדו עליה מלכי ארץ אשר זנו והתענגו עמה בראתם את עשן שרפתה׃"));
hebsuperobject.biblemap.put("b66_18_10", new hebsuperobject(66,18,10,"ומרחוק יעמדו מפני אימת ענויה ואמרו אוי אוי לך בבל העיר הגדולה העיר החזקה כי בשעה אחת בא משפטך׃"));
hebsuperobject.biblemap.put("b66_18_11", new hebsuperobject(66,18,11,"וסחרי הארץ בכים ומתאבלים עליה כי עתה לא יקנה עוד איש את משא אניותם׃"));
hebsuperobject.biblemap.put("b66_18_12", new hebsuperobject(66,18,12,"את משא זהב וכסף ואבן יקרה ופנינים ובוץ וארגמן ומשי ושני וכל עצי בשם וכל כלי שנהבים וכל כלי עץ יקר וכלי נחשת וברזל ושיש׃"));
hebsuperobject.biblemap.put("b66_18_13", new hebsuperobject(66,18,13,"וקנמון וקטרת סמים ומר ולבונה ויין ושמן וסלת וחטים ומקנה וצאן וסוסים ומרכבות וגויות ונפש אדם׃"));
hebsuperobject.biblemap.put("b66_18_14", new hebsuperobject(66,18,14,"והמגדים מחמד נפשך אזלו ממך וכל שמן ומצהיר אבד ממך ולא תמצאם עוד׃"));
hebsuperobject.biblemap.put("b66_18_15", new hebsuperobject(66,18,15,"ורכליהם אשר העשירו ממנה יעמדו מרחוק מפני אימת ענויה ובכו והתאבלו׃"));
hebsuperobject.biblemap.put("b66_18_16", new hebsuperobject(66,18,16,"ואמרו אוי אוי העיר הגדולה המכסה בשש וארגמן ושני ומכללה בזהב ואבן יקרה ופנינים כי בשעה אחת החרב עשר גדול כזה׃"));
hebsuperobject.biblemap.put("b66_18_17", new hebsuperobject(66,18,17,"וכל חבל וכל בעל מעברת והמלחים וכל עשי מלאכה בים עמדו מרחוק׃"));
hebsuperobject.biblemap.put("b66_18_18", new hebsuperobject(66,18,18,"ויצעקו בראתם עשן שרפתה לאמר מי בערים כעיר הגדולה׃"));
hebsuperobject.biblemap.put("b66_18_19", new hebsuperobject(66,18,19,"ויזרקו עפר על ראשיהם ויצעקו בכה וספוד לאמר אוי אוי העיר הגדולה אשר בה העשירו מהונה כל אשר להם אניות בים כי בשעה אחת החרבה׃"));
hebsuperobject.biblemap.put("b66_18_20", new hebsuperobject(66,18,20,"רנו עליה השמים והשליחים הקדשים והנביאים כי שפט אלהים את משפטכם ממנה׃"));
hebsuperobject.biblemap.put("b66_18_21", new hebsuperobject(66,18,21,"וישא מלאך נורא אבן גדולה כפלח רכב וישליכה אל תוך הים לאמר ככה תשלך במערצה בבל העיר הגדולה ולא תמצא עוד׃"));
hebsuperobject.biblemap.put("b66_18_22", new hebsuperobject(66,18,22,"וקול המנגנים בכנור והמזמרים ומחללים בחלילים ומחצרים בחצצרות בל ישמע עוד בתוכך וכל חרש וחשב בל ימצא בך עוד וקול רחים בל ישמע עוד בקרבך׃"));
hebsuperobject.biblemap.put("b66_18_23", new hebsuperobject(66,18,23,"ואור נר לא יאיר לך עוד וקול חתן וקול כלה לא ישמע בך עוד כי כנעניך היו נכבדי ארץ ובכשפיך תעו כל הגוים׃"));
hebsuperobject.biblemap.put("b66_18_24", new hebsuperobject(66,18,24,"ובה נמצא דם הנביאים והקדשים וכל הרוגי ארץ׃"));
hebsuperobject.biblemap.put("b66_19_1", new hebsuperobject(66,19,1,"אחרי כן שמעתי קול גדול כקול המון רב בשמים האמרים הללויה הישועה והכבוד והעז ליהוה אלהינו׃"));
hebsuperobject.biblemap.put("b66_19_2", new hebsuperobject(66,19,2,"כי אמת וישר משפטיו כי שפט את הזונה הגדולה אשר השחיתה את הארץ בתזנתה וידרש מידה טאת דם עבדיו׃"));
hebsuperobject.biblemap.put("b66_19_3", new hebsuperobject(66,19,3,"וישנו ויאמרו הללויה ועשנה יעלה לעולמי עולמים׃"));
hebsuperobject.biblemap.put("b66_19_4", new hebsuperobject(66,19,4,"ועשרים וארבעה הזקנים וארבע החיות נפלו על פניהם וישתחוו לאלהים הישב על הכסא ויאמרו אמן הללויה׃"));
hebsuperobject.biblemap.put("b66_19_5", new hebsuperobject(66,19,5,"וקול יוצא מן הכסא ויאמר הללו את אלהינו כל עבדיו ויראיו הקטנים עם הגדולים׃"));
hebsuperobject.biblemap.put("b66_19_6", new hebsuperobject(66,19,6,"ואשמע כקול המון רב וכקול מים רבים וכקול רעמים חזקים ויאמרו הללויה כי מלך אלהינו יהוה צבאות׃"));
hebsuperobject.biblemap.put("b66_19_7", new hebsuperobject(66,19,7,"נשמחה ונגילה ונתנה לו הכבוד כי באה חתנת השה ואשתו התקדשה׃"));
hebsuperobject.biblemap.put("b66_19_8", new hebsuperobject(66,19,8,"וינתן לה ללבש בוץ טהור וצח כי הבוץ הוא צדקות הקדשים׃"));
hebsuperobject.biblemap.put("b66_19_9", new hebsuperobject(66,19,9,"ויאמר אלי כתב אשרי הקרואים אל משתה חתנת השה ויאמר אלי אלה הדברים אמת הם דברי אלהים׃"));
hebsuperobject.biblemap.put("b66_19_10", new hebsuperobject(66,19,10,"ואפל לפני רגליו להשתחות לו ויאמר אלי ראה אל תעשה זאת עבד כמוך אנכי וחבר לך ולאחיך אשר להם עדות ישוע השתחוה לאלהים כי עדות ישוע היא רוח הנבואה׃"));
hebsuperobject.biblemap.put("b66_19_11", new hebsuperobject(66,19,11,"וארא את השמים נפתחים והנה סוס לבן והרכב עליו נקרא נאמן ואמתי ובצדק הוא שפט ולחם׃"));
hebsuperobject.biblemap.put("b66_19_12", new hebsuperobject(66,19,12,"ועיניו כלבת אש ועטרות הרבה על ראשו ויש לו שם כתוב אשר לא ידע איש כי אם הוא לבדו׃"));
hebsuperobject.biblemap.put("b66_19_13", new hebsuperobject(66,19,13,"והוא לבוש בלבוש מאדם בדם ושמו נקרא דבר האלהים׃"));
hebsuperobject.biblemap.put("b66_19_14", new hebsuperobject(66,19,14,"וצבאות השמים יצאים אחריו על סוסים לבנים מלבשים בגדי בוץ לבן וטהור׃"));
hebsuperobject.biblemap.put("b66_19_15", new hebsuperobject(66,19,15,"ומפיו יצאת חרב חדה להכות בה את הגוים והוא ירעם בשבט ברזל והוא דרך פורת יין חמת אף אלהי הצבאות׃"));
hebsuperobject.biblemap.put("b66_19_16", new hebsuperobject(66,19,16,"ועל בגדו ועל ירכו כתוב שם מלך המלכים ואדני האדנים׃"));
hebsuperobject.biblemap.put("b66_19_17", new hebsuperobject(66,19,17,"וארא מלאך אחד עמד בשמש ויצעק בקול גדול ויאמר אל צפור כל כנף אשר תעוף במרום הרקיע באו והאספו על זבח האלהים הגדול׃"));
hebsuperobject.biblemap.put("b66_19_18", new hebsuperobject(66,19,18,"ואכלתם בשר מלכים ובשר שרי אלפים ובשר גבורים ובשר סוסים ורכביהם ובשר כל בני חורים ועבדים הקטנים עם הגדולים׃"));
hebsuperobject.biblemap.put("b66_19_19", new hebsuperobject(66,19,19,"וארא את החיה ומלכי הארץ ואגפיהם נקהלים לעשות מלחמה עם הרכב על הסוס ובצבאו׃"));
hebsuperobject.biblemap.put("b66_19_20", new hebsuperobject(66,19,20,"ותתפש החיה ונביא השקר אתה אשר עשה האותות לפניה אשר הדיח בהן את נשאי תו החיה והמשתחוים לצלמה וחיים השלכו שניהם באגם האש הבער בגפרית׃"));
hebsuperobject.biblemap.put("b66_19_21", new hebsuperobject(66,19,21,"והנשארית נהרגו בחרב היוצאת מפי הרכב על הסוס וכל העוף שבעו מבשרם׃"));
hebsuperobject.biblemap.put("b66_20_1", new hebsuperobject(66,20,1,"וארא מלאך יורד מן השמים ובידו מפתח התהום וכבל גדול׃"));
hebsuperobject.biblemap.put("b66_20_2", new hebsuperobject(66,20,2,"ויתפש את התנין את הנחש הקדמוני הוא המלשין והוא השטן ויאסרהו לאלף שנים׃"));
hebsuperobject.biblemap.put("b66_20_3", new hebsuperobject(66,20,3,"וישליכהו בתהום ויסגר בעדו ויחתם עליו למען לא ידיח עוד את הגוים עד כלות אלף השנים ואחרי כן יתר לזמן מצער׃"));
hebsuperobject.biblemap.put("b66_20_4", new hebsuperobject(66,20,4,"וארא כסאות וישבו עליהם והמשפט נתן בידם ונפשות ההרוגים על עדות ישוע ועל דבר האלהים ואשר לא השתחוו לחיה ולצלמה ולא קבלו את תוה על מצחותם ועל ידם ויקומו ויחיו וימלכו עם המשיח אלף שנים׃"));
hebsuperobject.biblemap.put("b66_20_5", new hebsuperobject(66,20,5,"ושאר המתים לא קמו לחיים עד כלות אלף השנים זאת היא התחיה הראשונה׃"));
hebsuperobject.biblemap.put("b66_20_6", new hebsuperobject(66,20,6,"אשרי האיש וקדוש הוא אשר חלקו לקום בתחיה הראשונה באלה לא ישלט המות השני כי אם יהיו כהנים לאלהים ולמשיחו וימלכו אתו אלף שנים׃"));
hebsuperobject.biblemap.put("b66_20_7", new hebsuperobject(66,20,7,"ואחרי כלות אלף השנים יתר השטן מבית משמרו׃"));
hebsuperobject.biblemap.put("b66_20_8", new hebsuperobject(66,20,8,"ויצא להדיח את הגוים בארבע כנפות הארץ את גוג ומגוג ולקבצם למלחמה אשר מספרם כחול הים׃"));
hebsuperobject.biblemap.put("b66_20_9", new hebsuperobject(66,20,9,"ויעלו על מרחבי ארץ ויסבו את מחנה הקדשים ואת העיר החביבה ותרד אש מאת האלהים מן השמים ותאכל אתם׃"));
hebsuperobject.biblemap.put("b66_20_10", new hebsuperobject(66,20,10,"והשטן אשר הדיחם השלך באגם אש וגפרית אשר שם גם החיה ונביא השקר ויסרו יומם ולילה לעולמי עולמים׃"));
hebsuperobject.biblemap.put("b66_20_11", new hebsuperobject(66,20,11,"וארא כסא לבן וגדול ואת הישב עליו אשר מפניו נסו ארץ ושמים ולא נמצא להם מקום׃"));
hebsuperobject.biblemap.put("b66_20_12", new hebsuperobject(66,20,12,"וארא את המתים הקטנים עם הגדלים עמדים לפני הכסא וספרים נפתחים ויפתח ספר אחר אשר הוא ספר החיים וישפטו המתים על פי הכתוב בספרים כמעשיהם׃"));
hebsuperobject.biblemap.put("b66_20_13", new hebsuperobject(66,20,13,"ויתן הים את מתיו והמות והשאול נתנו את מתיהם וישפטו איש איש כמעשיהם׃"));
hebsuperobject.biblemap.put("b66_20_14", new hebsuperobject(66,20,14,"והמות והשאול השלכו באגם האש והוא המות השני׃"));
hebsuperobject.biblemap.put("b66_20_15", new hebsuperobject(66,20,15,"וכל איש אשר לא נמצא כתוב בספר החיים השלך באגם האש׃"));
hebsuperobject.biblemap.put("b66_21_1", new hebsuperobject(66,21,1,"וארא שמים חדשים וארץ חדשה כי השמים הראשנים והארץ הראשונה עברו והים איננו עוד׃"));
hebsuperobject.biblemap.put("b66_21_2", new hebsuperobject(66,21,2,"וארא את העיר הקדושה ירושלים החדשה ירדת מאת האלהים מן השמים נכונה ככלה המקשטת לבעלה׃"));
hebsuperobject.biblemap.put("b66_21_3", new hebsuperobject(66,21,3,"ואשמע קול גדול מן השמים לאמר הנה משכן אלהים עם בני האדם ושכן בתוכם והמה יהיו לו לעם והוא האלהים יהיה אתם אלהיהם׃"));
hebsuperobject.biblemap.put("b66_21_4", new hebsuperobject(66,21,4,"ומחה אלהים כל דמעה מעיניהם והמות לא יהיה עוד וגם אבל וזעקה וכאב לא יהיה עוד כי הראשנות עברו׃"));
hebsuperobject.biblemap.put("b66_21_5", new hebsuperobject(66,21,5,"ויאמר הישב על הכסא הנני עשה הכל חדש ויאמר אלי כתב כי הדברים האלה אמתים ונאמנים הם׃"));
hebsuperobject.biblemap.put("b66_21_6", new hebsuperobject(66,21,6,"ויאמר אלי היה נהיתה אני האלף והתו הראש והסוף אני אתן לצמא ממעין מים חיים חנם׃"));
hebsuperobject.biblemap.put("b66_21_7", new hebsuperobject(66,21,7,"המנצח יירש הכל ואני אהיה לו לאלהים והוא יהיה לי לבן׃"));
hebsuperobject.biblemap.put("b66_21_8", new hebsuperobject(66,21,8,"אבל רכי הלב ואשר אינם מאמינים והמגאלים והמרצחים והזנים והמכשפים ועבדי האלילים וכל המכזבים חלקם יהיה באגם הבער באש וגפרית אשר הוא המות השני׃"));
hebsuperobject.biblemap.put("b66_21_9", new hebsuperobject(66,21,9,"ויבא אלי אחד משבעת המלאכים הנשאים שבע הקערות המלאות שבע המכות האחרנות וידבר אלי לאמר בא ואראך את הכלה אשת השה׃"));
hebsuperobject.biblemap.put("b66_21_10", new hebsuperobject(66,21,10,"ויוליכני ברוח על הר גדול וגבה ויראני העיר הגדולה ירושלים הקדושה ירדת מן השמים מאת האלהים׃"));
hebsuperobject.biblemap.put("b66_21_11", new hebsuperobject(66,21,11,"ויש לה כבוד אלהים ואור נגהה כאבן יקרה מאד כאבן ישפה המבהקת כעין הקרח׃"));
hebsuperobject.biblemap.put("b66_21_12", new hebsuperobject(66,21,12,"ויש לה חומה גדולה וגבהה ושנים עשר שערים לה ועל השערים שנים עשר מלאכים ושמות כתובים עליהם אשר הם שמות שנים עשר שבטי בני ישראל׃"));
hebsuperobject.biblemap.put("b66_21_13", new hebsuperobject(66,21,13,"שערים שלשה ממזרח שערים שלשה מצפון שערים שלשה מנגב ושערים שלשה ממערב׃"));
hebsuperobject.biblemap.put("b66_21_14", new hebsuperobject(66,21,14,"ולחומת העיר שנים עשר מוסדות ועליהם שנים עשר שמות לשנים עשר שליחי השה׃"));
hebsuperobject.biblemap.put("b66_21_15", new hebsuperobject(66,21,15,"וביד המדבר אלי היה קנה זהב למד בו את העיר ואת שעריה ואת חומתה׃"));
hebsuperobject.biblemap.put("b66_21_16", new hebsuperobject(66,21,16,"ומושב העיר מרבע וארכה כרחבה וימד את העיר בקנה המדה שנים עשר אלף ריס ארכה ורחבה וקומתה שוים המה׃"));
hebsuperobject.biblemap.put("b66_21_17", new hebsuperobject(66,21,17,"וימד את חומתה על מאה וארבעים וארבע אמות במדת איש אשר היא מדת המלאך׃"));
hebsuperobject.biblemap.put("b66_21_18", new hebsuperobject(66,21,18,"ובנין חומתה אבן ישפה והעיר זהב מופז דומה לזכוכית זכה׃"));
hebsuperobject.biblemap.put("b66_21_19", new hebsuperobject(66,21,19,"ומוסדות חומת העיר מרבצות בכל אבני חפץ המוסד הראשון ישפה השני ספיר השלישי שבו הרביעי ברקת׃"));
hebsuperobject.biblemap.put("b66_21_20", new hebsuperobject(66,21,20,"החמישי יהלם הששי אדם השביעי תרשיש השמיני שהם התשיעי פטדה העשירי נפך אחד העשר לשם שנים העשר אחלמה׃"));
hebsuperobject.biblemap.put("b66_21_21", new hebsuperobject(66,21,21,"ושנים עשר השערים הם שתים עשרה מרגליות כל שער ושער מרגלית אחת ורחוב העיר זהב מופז כזכוכית בהירה׃"));
hebsuperobject.biblemap.put("b66_21_22", new hebsuperobject(66,21,22,"והיכל לא ראיתי בה כי יהוה אלהים צבאות היכלה הוא והשה׃"));
hebsuperobject.biblemap.put("b66_21_23", new hebsuperobject(66,21,23,"והעיר איננה צריכה לאור השמש ולנגה הירח כי כבוד אלהים האיר לה ונרה הוא השה׃"));
hebsuperobject.biblemap.put("b66_21_24", new hebsuperobject(66,21,24,"והגוים ילכו לאורה ומלכי ארץ מביאים כבודם ותפארתם אליה׃"));
hebsuperobject.biblemap.put("b66_21_25", new hebsuperobject(66,21,25,"ושעריה יומם לא יסגרו כי לילה לא יהיה שם׃"));
hebsuperobject.biblemap.put("b66_21_26", new hebsuperobject(66,21,26,"והביאו בה כבוד הגוים ותפארתם׃"));
hebsuperobject.biblemap.put("b66_21_27", new hebsuperobject(66,21,27,"ולא יבוא בה כל טמא ועשה תועבה ושקר כי אם הכתובים בספר החיים של השה׃"));
hebsuperobject.biblemap.put("b66_22_1", new hebsuperobject(66,22,1,"ויראני נחל של מים חיים זך מבהיק כעין הקרח יצא מכסא האלהים והשה׃"));
hebsuperobject.biblemap.put("b66_22_2", new hebsuperobject(66,22,2,"ובתוך רחוב העיר ואל שפת הנחל מזה ומזה עץ חיים עשה פרי שנים עשר כי מדי חדש בחדשו יתן את פריו ועלה העץ לתרופת הגוים׃"));
hebsuperobject.biblemap.put("b66_22_3", new hebsuperobject(66,22,3,"וכל חרם לא יהיה עוד וכסא האלהים והשה יהיה בה ועבדיו ישרתהו׃"));
hebsuperobject.biblemap.put("b66_22_4", new hebsuperobject(66,22,4,"והמה יראו את פניו ושמו על מצחותם׃"));
hebsuperobject.biblemap.put("b66_22_5", new hebsuperobject(66,22,5,"ולילה לא יהיה עוד ולא יצטרכו עוד לאור נר ולאור שמש כי יהוה אלהים הוא יאיר להם וימלכו עד עולמי עולמים׃"));
hebsuperobject.biblemap.put("b66_22_6", new hebsuperobject(66,22,6,"ויאמר אלי הדברים האלה אמתים ונאמנים הם ויהוה אלהי הנביאים הקדשים שלח את מלאכו להראות את עבדיו את אשר היה יהיה במהרה׃"));
hebsuperobject.biblemap.put("b66_22_7", new hebsuperobject(66,22,7,"הנני בא מהר אשרי השמר את דברי נבואת הספר הזה׃"));
hebsuperobject.biblemap.put("b66_22_8", new hebsuperobject(66,22,8,"ואני יוחנן הוא הראה אלה ושמעם ויהי כשמעי וכראותי ואפל לפני רגלי המלאך אשר הראני את אלה להשתחות לו׃"));
hebsuperobject.biblemap.put("b66_22_9", new hebsuperobject(66,22,9,"ויאמר אלי ראה אל תעשה זאת כי עבד כמוך אנכי וחבר לך ולאחיך הנביאים ולשמרים את דברי הספר הזה לאלהים השתחוה׃"));
hebsuperobject.biblemap.put("b66_22_10", new hebsuperobject(66,22,10,"ויאמר אלי אל תחתם את דברי נבואת הספר הזה כי קרוב המועד׃"));
hebsuperobject.biblemap.put("b66_22_11", new hebsuperobject(66,22,11,"החומס יוסיף לחמס והטמא יוסיף להטמא והצדיק יוסיף להצדק והקדוש יוסיף להתקדש׃"));
hebsuperobject.biblemap.put("b66_22_12", new hebsuperobject(66,22,12,"והנני בא מהר ושכרי אתי לשלם לכל איש כמעשהו׃"));
hebsuperobject.biblemap.put("b66_22_13", new hebsuperobject(66,22,13,"אני האלף והתו הראש והסוף הראשון והאחרון׃"));
hebsuperobject.biblemap.put("b66_22_14", new hebsuperobject(66,22,14,"אשרי העשים את מצותיו למען תהיה ממשלתם בעץ החיים ובאו העירה דרך השערים׃"));
hebsuperobject.biblemap.put("b66_22_15", new hebsuperobject(66,22,15,"ומחוץ לה הכלבים והמכשפים והזנים והמרצחים ועבדי האלילים וכל אהב שקר ועשהו׃"));
hebsuperobject.biblemap.put("b66_22_16", new hebsuperobject(66,22,16,"אני ישוע שלחתי את מלאכי להעיד לכם את אלה בפני הקהלות אנכי שרש דוד ותולדתו כוכב נגה השחר׃"));
hebsuperobject.biblemap.put("b66_22_17", new hebsuperobject(66,22,17,"והרוח והכלה אמרים בא והשמע יאמר בא והצמא יבוא והחפץ יקח מים חיים חנם׃"));
hebsuperobject.biblemap.put("b66_22_18", new hebsuperobject(66,22,18,"מעיד אני בכל השמע דברי נבואת הספר הזה אם יוסיף איש עליהם יוסיף עליו האלהים את המכות הכתובות בספר הזה׃"));
hebsuperobject.biblemap.put("b66_22_19", new hebsuperobject(66,22,19,"ואם יגרע איש מדברי ספר הנבואה הזאת יגרע האלהים את לחקו מעץ החיים ומעיר הקדש הכתובים בספר הזה׃"));
hebsuperobject.biblemap.put("b66_22_20", new hebsuperobject(66,22,20,"המעיד את אלה אמר אמנם כן אני בא מהר אמן באה נא האדון ישוע׃"));
hebsuperobject.biblemap.put("b66_22_21", new hebsuperobject(66,22,21,"חסד אדנינו ישוע המשיח עם כלכם כל הקדושים אמן׃"));

}

}